### ISSUE TITLE
How to prevent full page scroll when using anchor links

### ISSUE THREAD

**Issue by Dejan90** [alvarotrigo/fullPage.js#1000]
Hej,

On the website I'm using anchor points for sections and on some of the section I got some link to the subpages. So when you want to go back I added a link to get back to the anchor point like for example index.html/#thirdSection but the problem is, when you load the page, it scrolls through section1, section2.

Is there a way to go around this, because if there are multiple links to subpages then overtime you come back the whole page would scroll down to the section where you left. I should jump right there.

**Comment by alvarotrigo** [comment]
Use the plugin option `animateAnchor: false`. Although it will still scrolling to the horizontal slide, but it will go directly to the section.

**Comment by Dejan90** [comment]
I only have vertical slide so no horizontal. But thanks for the quick feedback it helped!
