### ISSUE TITLE
Disable scrollOverflow on Mobile Devices only

### ISSUE THREAD

**Issue by Stefanowitsch84** [alvarotrigo/fullPage.js#1001]
Is there a way to disable the scrollOverflow behaviour for mobile devices only? 

I want to use this feature on the desktop version but by default I've got scrolling issues on mobile devices (you get "trapped" inside the single sections when trying to scroll down).

**Comment by alvarotrigo** [comment]
Nop. [There's a bug](https://github.com/alvarotrigo/fullPage.js/issues/553) with it originated in the vendor plugin slimScroll.

**Comment by alvarotrigo** [comment]
In any case, if you want it only for mobile phones, try using:
```csss
.fp-section,
.fp-slide,
.fp-tableCell{
    height: auto !important;
}
```

**Comment by Stefanowitsch84** [comment]
Thanks for the answer but this does not help for I am still seeing the scrollbars in the mobile view.

**Comment by alvarotrigo** [comment]
You would need to use another initialization for mobile phones (or whatever you consider a "mobile phone") using `scrollOverflow:false`.
