### ISSUE TITLE
Rebuild on input focus (mobile)

### ISSUE THREAD

**Issue by rzamoramty** [alvarotrigo/fullPage.js#1002]
I have an issue on mobile devices. I have a form on this page -> http://www.bpublic.mx/#a9

On mobile devices, whenever I try to input the phone (telefono) or email, the page rebuids itself like when one resize the window. This doesn't happen on the other inputs.

I tried different things to no avail, ¿could you suggest me what could be the problem and/or how to solve it?

Thanks in advance.

**Comment by Rantahu** [comment]
I guess you have to use text type for now.

**Comment by alvarotrigo** [comment]
Yep, as @Rantahu says, right now fullpage.js only accepts ´type="text"´, but I'll keep it in mind for the next version!
Thanks for reporting it.

**Comment by rzamoramty** [comment]
Thank you!

I'll try to use the workarounds that you sugested. I hope this issue is resolved soon, because we use this field types not only for the convenience of a diferent keyboard on mobile phones but also for quick js validation.

Best regards!

**Comment by rorodezign** [comment]
Hi @rzamoramty , I've tested your form on mobile and it works pretty well now ... may you tell me how you figured it out ? Or maybe @alvarotrigo you can do something for me ?
I've been trying to find a solution but couldn't find it...

Here's my website www.premium-conciergerie.com/pro (check the "Contact" section on mobile)

Thank you in advance
Rom

**Comment by alvarotrigo** [comment]
@rzamoramty it should be fixed now. At least partially. Download the latest release 2.5.7 and let me know if its better.

**Comment by alvarotrigo** [comment]
I will close this issue and [keep the related one](https://github.com/alvarotrigo/fullPage.js/issues/145) open. As the problem with the `tel` type of input has already been solved.

**Comment by rorodezign** [comment]
It's workin well now, thank you, you did a great job.

Romain

2015-02-17 17:28 GMT+01:00 Álvaro <notifications@github.com>:

> I will close this issue and keep the related one
> <https://github.com/alvarotrigo/fullPage.js/issues/145> open. As the
> problem with the tel type of input has already been solved.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1002#issuecomment-74697518>
> .
>



-- 

*RORO *♦ *FISH HIGH*

Web Designer | Infographiste | Créatif


Tél : 06.10.32.05.63

Mail : roro[at]fishhigh[dot]com


www.fishhigh.com
