### ISSUE TITLE
Gradient Ease color change only working for first three slides 

### ISSUE THREAD

**Issue by ianpetraca** [alvarotrigo/fullPage.js#1003]
Hi,

New to this so don't eat me alive :). Really loving fullPage.js for a project I'm working on now but I'm encountering a bug with the ease affect on the gradient example. The background fades very nicely for the first three sections but after I add anymore it stops easing and displays the change as a single non-easing line. 

For example if my first three sections are 0,1,2 and I add a section 3 <div> the background will be the correctly assigned color, but the change is instant and no longer eases. Any thoughts on this?

**Comment by alvarotrigo** [comment]
Problem with your own CSS, nothing to do with fullPage.js. You'd better ask in other place such as stackoverflow.com
