### ISSUE TITLE
fullPage with Final Tiles Gallery

### ISSUE THREAD

**Issue by errazib** [alvarotrigo/fullPage.js#1004]
Trying to use Final Tiles Gallery (http://final-tiles-gallery.com/index.php) plugin with fullPage. The grid executes correctly, and modifies the layout as needed, however I'm unable to get the "scrollOverflow: true" to work. This is shown here: http://loiseau-noir.com/seb/gallery.html There should be many more images visible. Is this an issue of using afterRender?

       afterRender: function(){
       $('#gallery').finalTilesGallery({
              minTileWidth: 100,
              margin: 5,
              gridCellSize: 50, 
              imageSizeFactor: 1, 
              enableTwitter: false,   
              enableFacebook: false,   
              enableGplus: false,   
              enablePinterest: false,  
              hoverEffect: 'fade',   
              hoverEasing: 'swing',   
              hoverEffectDuration: 250,
              allowEnlargement: true,
            })
      }

**Comment by alvarotrigo** [comment]
If `finalTilesGallery` has any callback after it renders, you should be calling `$fn.fullpage.reBuild` in it.

**Comment by errazib** [comment]
Alright, I called the rebuild function within the finalTilesGallery plugin, and it still gets clipped off. Now the gallery sits in the first section, when it should be in the second section. It also does not make use of the scrollOverflow.

      $('#gallery').finalTilesGallery({
        gridCellSize: 5,
        minTileWidth: 100,
        enableTwitter: false,
        enableFacebook: false,
        enableGplus: false,
        enablePinterest: false,
        onComplete: function () { $.fn.fullpage.reBuild(); }
      })

 I've uploaded another page with less plugins so it may be clearer. http://loiseau-noir.com/seb/test.html

**Comment by alvarotrigo** [comment]
Its a matter of CSS. Use:

```css
.fp-section, .fp-slide{
    position:relative;
}
```

**Comment by alvarotrigo** [comment]
And keep initializating the gallery inside the `afterRender`...

**Comment by errazib** [comment]
I put the gallery initialization back into the afterRender, however it still is not showing the overflow. Am I missing something?

The CSS did at least fix the initial page (http://loiseau-noir.com/seb/test.html) so cheers for that.

**Comment by alvarotrigo** [comment]
It is very possible that the cause of it is that those images are using an absolute position.
