### ISSUE TITLE
normalScrollElements not working it seems

### ISSUE THREAD

**Issue by roiabrazaldo** [alvarotrigo/fullPage.js#1006]
This is my structure of my section

            <div id="general-search" class="section">
                <div class="container">
                    <div class="row">
                        Search Result
                    </div> 
                </div> 
            </div> 

this one particularly tends to get a height more than the full window so I wanted it to be on normalScroll, but when I applied it, mouse scroll isn't working in entire site. I use bootstrap too I may add.

**Comment by alvarotrigo** [comment]
You should be applying `scrollOverflow`, not `normalScrollElements`.

> **scrollOverflow:** (default false) defines whether or not to create a scroll for the section in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor plugin jquery.slimscroll.min and it should be loaded before the fullPage.js plugin.

**Comment by roiabrazaldo** [comment]
Worked great! thanks man for this amazing plugin
