### ISSUE TITLE
Class "active" get switched off and on if scrollBar: true

### ISSUE THREAD

**Issue by rzwei-web** [alvarotrigo/fullPage.js#1007]
If I use anchors with the menu option and scrollBar is set to true the class "active" is switched off and on and off again if I click on an other link in my menu.
If ScrollBar is set to false the class is just switched off.

**Comment by alvarotrigo** [comment]
Which class are you talking about? In which element?

**Comment by rzwei-web** [comment]
I am talking about the class "active" in the li-tag of the menu. This class is automatically set when the section corresponding to the menu item is in view.

**Comment by alvarotrigo** [comment]
Already reported [here](https://github.com/alvarotrigo/fullPage.js/issues/974).

**Comment by rzwei-web** [comment]
"The issue takes place only when using scrollBar:true without providing the anchors option."
But here if use the anchors option. Is it the same anyway?

**Comment by alvarotrigo** [comment]
I think so. I'll work on it for the next release.
