### ISSUE TITLE
Scrollbar true: can not slide down and up on mobile

### ISSUE THREAD

**Issue by GeorgeTodea** [alvarotrigo/fullPage.js#1008]
Hello, I have not seen any bug like this after I did several searches in the topics. I am using Android.

If you enable the scrollBar: true and then try on mobile (native browser) to scroll down, it works for the first time but then you are "stucked" on the 2nd slide. Can not move up or down anymore. 

Same happens on your demo: http://alvarotrigo.com/fullPage/examples/scrollBar.html#secondPage - mobile only. 

Weird is that on mobile Chrome, both my website and yours, works ok.

Do you have any idea how to solve this? I wish there was a method for enabling/disabling the scrollBar, like setAutoScrolling and others. In that way I would play with conditions for mobile only.
Thank you !

LE: Same for mobile Firefox. Seems that only the Chrome does his job good.

**Comment by alvarotrigo** [comment]
Solved in 2.6.0.
Let me know if it works well for you now.
