### ISSUE TITLE
Remove fullPage styling when responsive is 600

### ISSUE THREAD

**Issue by peterph-am** [alvarotrigo/fullPage.js#1009]
Hi,

Is it possible to remove all inline styling that fullPage adds to the slides, when the viewport width is within the range of the responsive setting (in my case 600px or smaller)?

And also refire fullpage when your above that responsive threshold?

My Settings:
````
navigation: false,
navigationPosition: 'left',
slidesNavigation: true,
autoScrolling: true,
continuousVertical: false,
css3: true,
easing: 'easeOutQuart',
easingcss3: 'ease',
loopBottom: false,
loopHorizontal: true,
loopTop: false,
normalScrollElementTouchThreshold: 5,
resize: false,
scrollBar: true,
scrollingSpeed: 1000,
scrollOverflow: false,
sectionSelector: _el.slides,
touchSensitivity: 15,
responsive: 600,
````

**Comment by alvarotrigo** [comment]
You could use the `destroy('all')` function by your own, checking with jQuery the width of the device. And then initialising it again when its bigger.

The function with the `all` parameter will destroy everything fullPage.js has done in your site.
