### ISSUE TITLE
Destroy all doesn't work on window resize

### ISSUE THREAD

**Issue by peterph-am** [alvarotrigo/fullPage.js#1010]
I'm trying to destroy the fullpage plugin when viewport width is smaller that 600px,

first of all i get a js error:

**Uncaught TypeError: Cannot read property 'top' of undefined**
line 121: $('html, body').scrollTop(element.position().top);

I tried commenting it out and that stopped the error.

However when I resize the browser under 600px, the destroy function seems to fire then undo, so the slide heights get removed then added again:

````
var _slider = function() {
    if (VPW > 600 && $('#main').hasClass('js_homepage')) {
        $(document).scrollTop(0);
        _el.container.fullpage({
            //Options
            navigation: false,
            navigationPosition: 'left',
            slidesNavigation: true,
            autoScrolling: true,
            continuousVertical: false,
            css3: true,
            easing: 'easeOutQuart',
            easingcss3: 'ease',
            loopBottom: false,
            loopHorizontal: true,
            loopTop: false,
            normalScrollElementTouchThreshold: 5,
            resize: false,
            scrollBar: true,
            scrollingSpeed: 1000,
            scrollOverflow: false,
            sectionSelector: _el.slides,
            touchSensitivity: 15,
            responsive: 600,
            //events
            onLeave: function(index, nextIndex, direction) {
                if (index === 1 && nextIndex === 2) {
                    _el.header.removeClass('is_alt');
                } else if (index === 2 && nextIndex === 1) {
                    _el.header.addClass('is_alt');
                }
            },
            afterLoad: function(anchorLink, index) {
                if (index !== 1) {
                    _el.header.removeClass('is_alt');
                }
                $(this).addClass('js_animate');
            },
            afterRender: function() {
                // console.log('afterRender');
                $(this).addClass('js_animate');
            }
        });
    }
};

var _resize = function() {
    if (VPW < 600 && $('#main').hasClass('js_homepage')) {
        _el.container.fullpage.destroy('all');
    }
};
````

**Comment by alvarotrigo** [comment]
`destroy('all')` works correctly as you can see in the [example page](http://alvarotrigo.com/fullPage/examples/methods.html).

Make sure you only call the function once, it seems you will call it tends of times while the viewport is resizing and fullPage.js doesn't exist anymore...

You can get the exact same error by clicking on the `destroy('all')` button twice on the example page.

**Comment by peterph-am** [comment]
The destroy function doesn't seem to work when applied to a resize event, it works when attached to a click event though.

**Comment by alvarotrigo** [comment]
Can you provide a reproduction of the error? If it works, it does in all cases. You might be attaching the resize even incorrectly.

**Comment by peterph-am** [comment]
I've sent you an email with a link to an example, thanks.

**Comment by alvarotrigo** [comment]
Thanks for them. I confirm its a bug. I'll detected the problem and I'll solve it for the next version.

**Comment by peterph-am** [comment]
Thanks Álvaro, when will the next version be released?

**Comment by alvarotrigo** [comment]
Hopefully next week.

**Comment by alvarotrigo** [comment]
@peterph-am let me know if it works well for you now. Version 2.5.7.

**Comment by peterph-am** [comment]
Thanks Alvaro, works great now!

**Comment by richgcook** [comment]
@peterph-am Did you ever solve this 'Uncaught TypeError: Cannot read property 'top' of undefined' error? How did you keep it only firing once? And can you scroll on resize? I can't.

**Comment by alvarotrigo** [comment]
@richgcook read his latest reply and you'll find your answer...

**Comment by richgcook** [comment]
@alvarotrigo Not that helpful, I want to know how he solved the 'mousewheel' being disabled on resize. And what he did to solve the 'Uncaught TypeError: Cannot read property 'top' of undefined'  error.

**Comment by alvarotrigo** [comment]
@richgcook if you read the topic of the issue you'll see it was related with bug with the `destroy` functionally which I solved in the last version of fullPage.js.
That's how he solved it. Using the latest version.

**Comment by alvarotrigo** [comment]
If you still having problems is probably because your issue is not related at all with his issue. And very probably because you are doing something wrong.

**Comment by richgcook** [comment]
@alvarotrigo This wasn't necessarily about your answer or plugin, I was asking him directly how he solved this specific part.

**Comment by alvarotrigo** [comment]
@richgcook well, I'm telling you. This "specific part" is related with the plugin itself...

**Comment by richgcook** [comment]
@alvarotrigo And I was asking him directly if he solved it? Can't you let me be?

**Comment by peterph-am** [comment]
@richgcook the issue was my js was firing destroy too much, which resulted in the 'Uncaught TypeError'. I resolved it by setting a conditional to check if waypoints had been initialized before firing the destroy function.

As @alvarotrigo said the destroy on resize was resolved in the latest version update.

**Comment by adrianlacheta** [comment]
Hi, I have the same Problem. The destroy function doesn't seem to work when applied to a resize event, it works when attached to a click event though. At least ist doesn't remove html styles when applied to a resize event.

**Comment by adrianlacheta** [comment]
This does not remove HTML-Styles:
`if($(window).width() < 768) {
      $.fn.fullpage.destroy('all');
}`

This also doesn't remove HTML-Styles:
`$( window ).resize(function() {		
      if ($(window).width() > 767) {
            createFullpage();
      } else {
            if(fullPageCreated == true) {
                  fullPageCreated = false;
                  $('#fullpage').fullpage.destroy('all');
            }
      }
});`

This removes HTML-Styles:
`$('body').on('click',function(){
      $.fn.fullpage.destroy('all');
      fullPageCreated = false;
});`

**Comment by alvarotrigo** [comment]
@adrianlacheta please open a new issue with an isolated reproduction of it in jsfiddle or codepen if you are having this issue with the latest fullpage.js version 3.0.4.

Otherwise, I do not provide support for older versions so there's nothing I can do there.
