### ISSUE TITLE
Is it possible to disable the use of the scrollbar all-together?

### ISSUE THREAD

**Issue by samholmes** [alvarotrigo/fullPage.js#1011]
I'm using the `scrollOverflow` setting to allow for scrollbars within slides, but it can become annoying to have a transition to the next slide once you reach the very bottom of the scroll within a slide. 

So, one idea to solve this problem for me would be to disable the use of the scrollbar to transitioning between slides, and instead use only a set of navigation links to get to each slide.

Thoughts?

**Comment by alvarotrigo** [comment]
You can use [`setAlllowScrolling(false)`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) for it and `setKeyboardScrolling`.
