### ISSUE TITLE
afterrender competes with afterlod

### ISSUE THREAD

**Issue by Mommoth** [alvarotrigo/fullPage.js#1012]
Hi,

I have an animation on my Nav that is fired when the page loads on the home (afterrender). I have another animation on the Nav that is fired when you change to other sections. The problem is that when you load the website on another section than the Nav, the "afterload" animation is fired and then the "afterrender" animation is fired.

**Comment by alvarotrigo** [comment]
You shouldn't be using `afterRender` presupposing that the user will always load the 1st section.
That's not its purpose.

You should keep using `afterLoad` to fire your animation on the home page. Just use the `anchorLink` or the `index` parameters to filter your actions, or even the section object itself (`$(this)`).
