### ISSUE TITLE
Disabling fullPage on certain page?

### ISSUE THREAD

**Issue by roiabrazaldo** [alvarotrigo/fullPage.js#1013]
Heres the scenario,

I wanted fullPage to work on home page but not on certain page who had a overflowscroll because on mousescroll users accidentally just scroll up to footer when they meet the bottom of the div with overflowscroll. But disabling fullPage would disabled everything on it.

I got this javascript

```javascript
jQuery(document).ready(function() {
var ishome;
    if (window.location.origin.indexOf('192.168') > -1) {
        ishome = (((window.location.origin + '/public/sample') === window.location.href) ? true : false );
    }else {
        ishome = ((window.location.origin === window.location.href) ? true : false );
    }
    
    jQuery('#fullpage').fullpage({
        scrollOverflow: !ishome,
        autoScrolling: ishome,
        verticalCentered: false
    });
});
```

This would enable me to get normal scroll but also scrollOverflow which has its own scrollbar..
disabling scrollOverflow would not show the rest of the search result..

I hope you guys get what I mean..

**Comment by roiabrazaldo** [comment]
The only problem is how can I prevent the user from accidentally over scrolling to footer when they reach the bottom of the div with overflowscroll?

**Comment by alvarotrigo** [comment]
There's an [open issue](https://github.com/alvarotrigo/fullPage.js/issues/941) treating the accidental scroll problem.

**Comment by roiabrazaldo** [comment]
Ok I got what I wanted..

On pages with many overflowscroll affected div which in my case everything except home..
I just added this after my code above..

    if (ishome === false ){
        jQuery('#fullpage .section').css({
            'height':'auto'
        });
    }
