### ISSUE TITLE
Scrolling in textbox causes slide to jump

### ISSUE THREAD

**Issue by isaachinman** [alvarotrigo/fullPage.js#1015]
I've got a textbox on one of my slides, with a fixed height and overflow: auto, so that it will scroll independently. When I mouse inside the box and scroll, it forces the slide to jump. Any fixes?

**Comment by alvarotrigo** [comment]
Already [reported](https://github.com/alvarotrigo/fullPage.js/issues/1002).

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements` for it.
