### ISSUE TITLE
Centering images

### ISSUE THREAD

**Issue by Lazyfattree** [alvarotrigo/fullPage.js#1017]
How do you center your images like on this page:
http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage

I didn't find it in the sources.

**Comment by alvarotrigo** [comment]
You can take a look at the source code and figure it out by yourself. [The page sourcode](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrolling.html) is available in the [examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) of the downloaded files.

It is all about CSS. Nothing to do with fullPage.js
