### ISSUE TITLE
Navigating slides

### ISSUE THREAD

**Issue by jnettik** [alvarotrigo/fullPage.js#1018]
I've been playing with this now for a few hours and I can't tell if I need to build this on or if I just don't have things set up correctly. I have a parent > child menu of all sections > slides.

```html
<nav id="primary-nav">
<ul class="primary-nav">
  <li class="primary-nav--item primary-nav--item__children" data-menuanchor="board">
    <a href="#board">Boards and Advisors</a>

    <ul class="primary-nav--children">
      <li data-menuanchor="board-2014"><a href="#board/board-2014">Board of Directors 2014 - 2015</a></li>
      <li data-menuanchor="international-boards"><a href="#board/international-boards">International Boards</a></li>
      <li data-menuanchor="global-advisory-council"><a href="#board/global-advisory-council">Global Advisory Council</a></li>        
      <li data-menuanchor="new-innovators-council"><a href="#board/new-innovators-council">New Innovators Council</a></li>
    </ul>
  </li>
</ul>
</nav>
```

I would like to have slide menu items marked as active as well as the section their in. My current config is:

```javascript
$('#fullpage').fullpage({
          fixedElements: '#primary-nav',
          normalScrollElements: '#primary-nav',
          loopHorizontal: false,
          verticalCentered: false,
          scrollOverflow: true,
          menu: '#primary-nav > ul',
          anchors: [parent links]
        });
```

Is this possible out of the box or do I need to add that functionality myself?

**Comment by alvarotrigo** [comment]
The plugin only provides a way to activate sections in a menu, not slides, as it is detailed in the docs.

To activate slides in your menu you would need to work with the callbacks provided by the plugin such as `afterSlideLoad` or use the added class in the body element to work with CSS instead.

**Comment by jnettik** [comment]
Thank you for the quick reply and for the plugin. It saved me a ton of time.

**Comment by alvarotrigo** [comment]
No problem! Glad to know it!
