### ISSUE TITLE
Strange behavior when hiding the vertical dotted navigation from a specific section

### ISSUE THREAD

**Issue by kokoda** [alvarotrigo/fullPage.js#1020]
Dear all, 

 I am trying to hide the dotted vertical navigation bar from the first section only. Through the support on this forum, I have got a solution by implementing the following code on the site I am working on:

<pre>
afterLoad: function(anchorLink, index) { // you need to add the parameters
    navColor();
    addClassNav();
    // $('#fp-nav').fadeIn(); 
    section.not('.active').find('.section-content').mCustomScrollbar('scrollTo', 'top');
    videoBg();
    setTimeout(function() {
        sandwichAnimation();
    }, 0);
    // simply ask fullpage for section index:
    if (index === 1) {
         $('#fp-nav').hide(); // or toggle by class
     }
     else {
         $('#fp-nav').show(); // or toggle by class
     }
} //,
</pre>

  The issue is very strange. The vertical navigation bar sometimes appears and sometimes disappears (where I want it to be always hidden on the first section only). It appears when you load the page, but once you scroll down then up it disappears. And even sometimes it disappears when you load the page. I have spent lots of time before I post trying to fixed the issue but I couldn't. I would greatly appreciate if any one can lead me to a solution to the strange issue.

Kind regards,
Kokoda

**Comment by tripletto** [comment]
Hi Kokoda,
when u say, the navi appears when u load the page, then it seems to me, that you maybe forgot to add display: none to #fp-nav in your css for initial #fp-nav invisibility directly after the page rendered. I think afterLoad gets the first time called when u switch sections. When u want something done, directly when the page comes up you would need afterRender.

Best regards
tripletto

**Comment by alvarotrigo** [comment]
It sounds like a problem with your script, not with fullPage.js.

As @tripletto says, you are probably forgetting to hide it at first.
See [this example](http://jsfiddle.net/97tbk/474/).

Using:
```css
#fp-nav{
    display: none;
}
```
