### ISSUE TITLE
Block slides to scroll down possibilities ?

### ISSUE THREAD

**Issue by useram00** [alvarotrigo/fullPage.js#1023]
Here is what I would like to do :

section
↓
slide → slide → slide → slide → slide
↓---------↓---------↓---------↓---------↓
x---------x---------x--------section section                                       
------------------------------ ↓---------↓
------------------------------section section

block the 3 first over 5 slibe to be able to scroll down... Is it possible ?

Thanks...

**Comment by alvarotrigo** [comment]
You can emulate that by using the provided function `setAllowScrolling` and allowing only to scroll down on the last 2 slides.
