### ISSUE TITLE
scrollBar: true causing mobile to scroll

### ISSUE THREAD

**Issue by kvieira90** [alvarotrigo/fullPage.js#1026]
Seeing minor issue when I set scrollBar: true where mobile safari (iOS6) allows the user to free scroll after the first slide. Also, all the slides following the first have their height incorrectly calculated. Digging into this further but figured I'd make you aware.

**Comment by alvarotrigo** [comment]
Already reported: https://github.com/alvarotrigo/fullPage.js/issues/1008
