### ISSUE TITLE
First anchor is not set to class "active" if navigating from another url.

### ISSUE THREAD

**Issue by rzwei-web** [alvarotrigo/fullPage.js#1027]
I use anchors for my sections and all works well but when I navigate from another url to the first anchor of my full page the anchor is not set to class "active" as in your example.
If I navigate from within the full page the anchor highlighting works.
If i set animateAnchor to false the active class is set correctly but then  the wrong section is scrolled in.
Here is my site: www.airgonautics.de

**Comment by rzwei-web** [comment]
I have to correct me. With animateAnchors set to false everything works. There was obviously a error in my code.
But the problem with the first anchor still is there with animateAnchors true.

**Comment by alvarotrigo** [comment]
It can not be reproduced in the demo page: 
http://alvarotrigo.com/fullPage/#firstPage

Provide a reproduce it.

**Comment by rzwei-web** [comment]
So please have a look at my site, there you can see it:
http://www.airgonautics.de/architektur-marketing-dokumentation/#industrie-_und_architekturdokumentation

**Comment by alvarotrigo** [comment]
Right. Thanks for it. As you said, it occurs when using `animateAnchor: true` AND when you load the 1st section of your site. 

It will get solved for the next release.

**Comment by alvarotrigo** [comment]
Should be solved now in 2.5.8.

**Comment by rzwei-web** [comment]
Solved and working!
Thank you.
