### ISSUE TITLE
automatically add slim scroll 

### ISSUE THREAD

**Issue by chamara-fg** [alvarotrigo/fullPage.js#1028]
How to activate Slimscroll when dynamic height

**Comment by alvarotrigo** [comment]
Using [`reBuild`](https://github.com/alvarotrigo/fullPage.js#rebuild) 

> **reBuild()**
Updates the DOM structure to fit the new window size or its contents. Ideal to use in combination with AJAX calls or external changes in the DOM structure of the site.
$.fn.fullpage.reBuild();

**Comment by chamara-fg** [comment]
Thank you for the fast response ...i add it but
