### ISSUE TITLE
Padding-top not working well with slide sections

### ISSUE THREAD

**Issue by josiahwiebe** [alvarotrigo/fullPage.js#1031]
I'm implementing Fullpage.js with a fixed header, so I've set `paddingTop: '90px',` to account for that header. That works well, until I come to a `.section` that has slides. 

With those sections, there's a 90px white blank area above the slide section. This behaviour only happens on the slides, which seems odd, but I could be making an error that I'm unaware of. Could you  be of any assistance?

You can see a demo [here](http://tripleerv.github.io/fifty/).

N.B. I cannot use the plugin's `fixedElements` function, as it breaks the functionality of the menu.

**Comment by alvarotrigo** [comment]
Which browser are you using? I can't see anything weird from Chrome.

**Comment by josiahwiebe** [comment]
Chrome v. 40. 

The issue is noticeable when scrolling (you can see the white section scroll past). Also, try making your browser about 500px wide, it's noticeable then.

**Comment by alvarotrigo** [comment]
I can only see none of the sections fill the whole viewport when using `autoScrolling:false`, after you use the responsive option.

**Comment by josiahwiebe** [comment]
Nope. See this screenshot. The "Nineteen Seventy Two" section contains slides. 
![screen shot 2015-02-18 at 16 07 36](https://cloud.githubusercontent.com/assets/265638/6257728/543128c2-b788-11e4-836c-0935b9cea980.png)

For comparison, this "Nineteen Sixty Nine" section contains no slides. There is no white gap between sections.
![screen shot 2015-02-18 at 16 08 28](https://cloud.githubusercontent.com/assets/265638/6257781/aa9cffd8-b788-11e4-9760-afd51c06d20a.png)

**Comment by alvarotrigo** [comment]
Oh, right, I see what you mean.
Not sure if that's a bug or if that was done on purpose to deal with overflowScroll:true...  I'll check it soon.

**Comment by alvarotrigo** [comment]
I would recommend you to solve it by using the CSS property `background-position` and adding a negative value equals to the `paddingTop` value for the Y axys.

**Comment by bbmatt** [comment]
Had the same issue, background-position doesn't solve it, *however*, applying a margin top to the body the same height as the header works great. 

html.fp-enabled body {
  margin-top: 119px;
}

**Comment by mihai10stoica** [comment]
Also facing this issue. Since I set different background images on each .slide (not on the .section), the paddingTop area of the .section appears blank. Solution would be to move the paddingTop to the slides when slides are used, rather than the section. I tried doing this in the afterRender event handler, but I'm not getting any results.

**Comment by alvarotrigo** [comment]
@mihai10stoica you might want to see this pull request https://github.com/alvarotrigo/fullPage.js/pull/2420

**Comment by BenFictional** [comment]
I encountered this problem too when using unique background images for each slide, and the `afterRender` solution from @mihai10stoica worked like a charm.
