### ISSUE TITLE
slimScroll doesn't work with scrollBar: true in Firefox

### ISSUE THREAD

**Issue by jnettik** [alvarotrigo/fullPage.js#1032]
Sections set up with slimScroll don't scroll in Firefox when scrollBar is set to true. This seems to work fine in Chrome, and as soon as I disable the scrollBar setting, Firefox works fine. My settings are:

```javascript
var options = {
          anchors: [],
          fixedElements: '#primary-nav',
          normalScrollElements: '#primary-nav',
          loopHorizontal: false,
          verticalCentered: false,
          scrollOverflow: true,
          scrollBar: true,
          resize: true,
          menu: '#primary-nav > ul'
}
```

I'm also having some trouble debugging the slimScroll library since the only one I can see in the repo is the minified version, and the version from the slimScroll repo doesn't work with fullPage.js.

**Comment by alvarotrigo** [comment]
`scrollOverflow:true` was never tested with `scrollOverflow:true` as it doesn't make much sense to have two scroll bars.

Moreover slimScroll will probably be removed from fullPage.js in change of probably iScroll.js which seem to be a much better library. 

Therefore I don't think this problem will get solved. 

If you want to take a look at the slimScroll library customized for fullPage.js, just do the change I mentioned [in this topic](https://github.com/rochal/jQuery-slimScroll/issues/133) of their issues forum.

**Comment by jnettik** [comment]
The use case for me was I needed `scrollOverflow` for the content of some slides, but also needed to be able to track `scrollTop` for another plugin I am using. I've since figured out a way around that.

**Comment by qdladoooo** [comment]
wow.js needs "scrollBar:true" option; A very high section needs "scrollOverflow: true" option. So I guess there is no way to use wow.js and fullpage.js at the same time. :(

**Comment by alvarotrigo** [comment]
@qdladoooo just do not use scrollOverflow: true. it doesn't make sense from the user experience point of view to have two scroll bars. Force the section to be auto height by using `fp-auto-height` on the big section.
