### ISSUE TITLE
Resize Site on first Load

### ISSUE THREAD

**Issue by physikinstrumente** [alvarotrigo/fullPage.js#1033]
Hello,

I have the Problem that the website is resizing only when I change the browser window. But not on first load of the site. So If I open the site on a small screen the site is not resizing. I have to make the browser window small and after this fullsize again for resize. Is there an option to check and resize on the first load and not only after changing the browser window size?
Sorry for my bad english ;)
Best regards
Robert

**Comment by alvarotrigo** [comment]
You can search for related topics using the search. It has been treated multiple times.

In any case, the resize functionality might get removed from fullPage.js.

You'd better look at other better alternatives such as https://github.com/simplefocus/FlowType.JS
