### ISSUE TITLE
reInit fullpage.js

### ISSUE THREAD

**Issue by danilvalov** [alvarotrigo/fullPage.js#1034]
After fullpage.js destroy ($.fn.fullpage.destroy('all')), i can't run it again.
Problem with class 'fp-destroyed' (i have to remove it yourself).

Fix it please in next version.

**Comment by alvarotrigo** [comment]
Right. Thanks for reporting it.
It will get solve soon!

**Comment by alvarotrigo** [comment]
Should be solved now in v 2.5.8.
