### ISSUE TITLE
Fullscreen mode causes a glitches

### ISSUE THREAD

**Issue by vkrol** [alvarotrigo/fullPage.js#1036]
Hi. I find the bug. 
Steps:
1. Try to open http://jsbin.com/baqonuteju/1;
2. Go to the second slide;
3. Click on play button;
4. Go to the full screen mode;
5. Try to exit full screen.
You will see a very frustrating glitch.

Thanks!

**Comment by alvarotrigo** [comment]
Yep, related with [this issue](https://github.com/alvarotrigo/fullPage.js/issues/64). 
I should give it a though maybe for the next version.

**Comment by VKrol** [comment]
Thank you for the clarification!

**Comment by alvarotrigo** [comment]
I believe this has been solved. 
Correct me if I'm wrong.
