### ISSUE TITLE
Static header per section

### ISSUE THREAD

**Issue by dajuric** [alvarotrigo/fullPage.js#1039]
Is there a way to have fixed header and footer per each section ?
Header and footer should be unique per section, but should not change if a slide is changed inside a section.

I think this question is more appropriate for this Q&A (Issues) than for the Stackoverflow forum.

P.S.
Thank you for the previous answer.

**Comment by alvarotrigo** [comment]
Yeah, but that has nothing to do with fullPage.js. It is all about css.
Use absoluted positions for those elements and use a relative one for the sections / slides.
