### ISSUE TITLE
verticalCenter has sometimes problems with slimscroll library.

### ISSUE THREAD

**Issue by ludwiczakpawel** [alvarotrigo/fullPage.js#104]
I've noticed that verticalCenter option SOMETIMES (not always) just doesn't work for first slide when I have slimscroll library attached. So I try to refresh page few times and see what happens... And it seems like time to time it doesn't center vertically my content in first slide.. I've noticed this on latest version of Chrome, both: Mac OS X & Windows

**Comment by rohan-krishna** [comment]
I'm using this plugin with 4 sections.When I used verticalCentered : true , I can't seem to scroll to other sections.Only the first two works. The navigation seems to update but the sections are not scrolling.
```
//Full Page
	$('#fullPage').fullpage({
		navigation : 'true',
		anchors : ['firstPage','secondPage','thirdPage','fourthPage'],
		paddingBottom : '1.52em',
	});
```
