### ISSUE TITLE
Add touch Callback

### ISSUE THREAD

**Issue by Zarinia** [alvarotrigo/fullPage.js#1042]
Hi,
I want run script on touch device
i want function callback if my script run in touch device or desktop
thanks alvaro for nice script

**Comment by alvarotrigo** [comment]
You can achieve that with pure javascript:
```javascript
var isTouch = (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0) || (navigator.maxTouchPoints));
```

**Comment by Zarinia** [comment]
thanks alot my dear friend.
