### ISSUE TITLE
Scrollbar thumb not showing up in sections

### ISSUE THREAD

**Issue by mihai101** [alvarotrigo/fullPage.js#1043]
Hi.

The scrollbar thumb doesn't show up in the sections of the slider (namely .fp-scrollable). It's just the thumb, the rest of the scrollbar appreas. The thumb only shows up when I resize the window of the browser, after I refresh, it's gone again. any idea on how to fix this? Thanks

Here are my settings:
	$('#fullpage').fullpage({
		scrollOverflow: true,
		verticalCentered: false,
		resize: false,
		autoScrolling: false
	});

[scrollbar](https://cloud.githubusercontent.com/assets/6075329/6345175/560e433c-bc0b-11e4-9e16-f391c67b97b3.png)

**Comment by alvarotrigo** [comment]
Not quite sure what you mean with *thumb*.
In any case, try to reproduce the problem [here](http://jsfiddle.net/97tbk/418/) or somewhere else. 

[In the example page](http://alvarotrigo.com/fullPage/examples/scrolling.html) included in the plugin it works as expected.
