### ISSUE TITLE
Disable height when responsive is on 

### ISSUE THREAD

**Issue by borko-petkov** [alvarotrigo/fullPage.js#1044]
Hi,
First i wan to say a big thanks for this wonderful plugin.
My problem is when responsive width is 1024 and when when the screen size is 1023 it turns page on normal scroll which is fine but its make every page 1023 height and i want to disable this. I want to make every section without defined height.
Is it possible?

**Comment by alvarotrigo** [comment]
>  I want to make every section without defined height.

What do you mean with that.

**Comment by borko-petkov** [comment]
When  screen size is 1023px i still have this extra style on each section style="height: 602px; background-color: rgb(240, 242, 244);". I want to remove this extra height when screen size is smaller than 1024.

**Comment by alvarotrigo** [comment]
You can overwrite it.

```css
.fp-section,
.fp-slide,
.fp-tableCell{
    height: auto !important;
}
```

**Comment by mezanddav** [comment]
I am sorry but this feature just doesn't make sense. The height: initial CSS is applied on the HTML and the body but the section keeps the height? In fact, it should be min-height...
I am having trouble going around this senseless feature.

**Comment by alvarotrigo** [comment]
@mezanddav can you please elaborate your view on it?
There's a reason why sections keep the heigh value, in part, to be able to deal with `verticalCentered:true` and `scrollOverflow:true` options.

This feature was released way before the time flexbox was usable in most browsers, so perhaps we could review the implementation. 
But please, use constructive comments providing alternatives and solutions. Destructive comments won't help anyone. 

It would be nice if you could detail:

- What your issue is.
- Why you think the solution doesn't make sense.
- Provide alternative solutions.

**Comment by Sorumeiji** [comment]
Hello @alvarotrigo,

I do have a issue with inline height being added when verticalCentered = { false }. Although it removes the fp-table classes. I still get added inline fixed heights to the sections. I don't think I can override this with !important,  Fixed heights cause things to overflow and break the responsive nature of the web. 

Using a min-height of 100%  for each section will ensure that each page is the full height, and it allows the browser to grow dynamically when content is added. I do understand there is the overflow and responsive height options, but it doesn't keep the same height always at 100% if you have different sizes of content on each page. 

I really love this plugin and it is saving by butt for a project, but I was wondering is there already an option to remove the fixed heights that are injected into the sections?

**Comment by alvarotrigo** [comment]
> I really love this plugin and it is saving by butt for a project, but I was wondering is there already an option to remove the fixed heights that are injected into the sections?

fullPage.js 4 will be released very soon (this week?). And it won't be using fixed heights for most cases ;)
