### ISSUE TITLE
Update Scrollbar when autoscrolling: true

### ISSUE THREAD

**Issue by Stefanowitsch84** [alvarotrigo/fullPage.js#1045]
Hey,

I'm using autoscrolling: true -  except there's lot's of content in a slide. Therefore I do also use the scrolloverflow function.

Now I have an anchorlink in a section that jumps to the bottom. It works but the Slimscrollbar at the right does stay in place. Then, when pulling the mousweel to scroll down, I jump back to the top of the page before scrolling down. 

Is there a way to kind of update the slimscroller position when using anchor links within a slide?

**Comment by alvarotrigo** [comment]
That's a question for [slimScroll.js plugin](https://github.com/rochal/jQuery-slimScroll), not for fullpage.js.
