### ISSUE TITLE
Possible Readme.md bug

### ISSUE THREAD

**Issue by dajuric** [alvarotrigo/fullPage.js#1046]
The description "setFitToSection(boolean)" does not match the shown sample.

**Comment by alvarotrigo** [comment]
I don't know where do you see the error. 
False and True are booleans :)

**Comment by willfong** [comment]
The example of "setFitToSection" says "setAutoScrolling" instead of "setFitToSection". :)

**Comment by alvarotrigo** [comment]
Haha, right right :) Thanks for pointing it out @willfong !
