### ISSUE TITLE
Autoscroll off for first section

### ISSUE THREAD

**Issue by yanodnoralov** [alvarotrigo/fullPage.js#1047]
I have 3 sections. The first section needs to be larger in height than the viewport so the user should be able to scroll through it. The rest of the section I'd like to function normally with fullpage (auto scroll and all). I try "normalScrollElements" with no luck.

Is there a way I can exclude the first section from autoscroll and let it have it's normal scroll until the user reaches the second section? I'd still like to have the first section part of the vertical navigation.

I've set up a fiddle with what I'm trying to do: http://jsfiddle.net/4yqd8rs9/5/

Thanks!
Yan

**Comment by alvarotrigo** [comment]
Use `scrollOverflow` as [in this example.](http://alvarotrigo.com/fullPage/examples/scrolling.html)

> **scrollOverflow:** (default false) defines whether or not to create a scroll for the section in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor plugin jquery.slimscroll.min and it should be loaded before the fullPage.js plugin. For example:

**Comment by alvarotrigo** [comment]
Demo online for your example:
http://jsfiddle.net/4yqd8rs9/11/

**Comment by yanodnoralov** [comment]
Duh! I didn't realize that scrollOverflow would fix my issue. Thanks! 

Is it possible to make the scrolling through this div more smooth? I'm using a mac and when you use the track pad to scroll through this div, it doesn't ease as all other pages in your browser. Any ideas?

Thanks!
Yan

**Comment by alvarotrigo** [comment]
Nop, not at the moment. 
Probably I'll change the used vendor plugin that fullPage.js is using at the moment (slimScroll.js) for a better one (iScroll.js), but that's a change for the future. 

If you really need it for now, [contact me. ](http://alvarotrigo.com/#contact-page)
