### ISSUE TITLE
One Single Section auto scrolling back up

### ISSUE THREAD

**Issue by bethblinebury** [alvarotrigo/fullPage.js#1049]
Hi there, 

First of all - GREAT plugin! 

I am working with two sections and then content below the slider. I referenced your One Single Section sample but noticed a glitch - once you scroll past the last section into the single section <wrap> content, the page is automatically scrolled back up. It's happening in your sample and how I'm trying to use it: http://alvarotrigo.com/fullPage/examples/oneSection.html

Any ideas? 

Thanks in advanced!

**Comment by alvarotrigo** [comment]
You can solve it by using the option `fitToSection:false` if you are using the latest version of fullPage.js. I'll check that for a future and set the option to false when using autoScrolling:false.

**Comment by bethblinebury** [comment]
Thanks for the quick response! I take it there's no combo solution here right? I'd love to be able to use autoScrolling for the first two sections if possible. Thanks again for the quick reply and the really beautiful plugin.

**Comment by alvarotrigo** [comment]
No combo.

**Comment by bethblinebury** [comment]
Ohh, okay great. That might work! Thanks for the help and I'll be sure to donate later today.
