### ISSUE TITLE
fullpage.js makes button almost unresponsive

### ISSUE THREAD

**Issue by AlmondFace** [alvarotrigo/fullPage.js#1051]
Hi there,

amazing work with the plugin. I have this working with bootstrap 3 for iOS devices. I have a crossfader element where i have a '+' button at the bottom right of the page. Since i have implemented fullpage.js, this button has become almost unresponsive since adding fullpage.js so that i have to press the screen extremely hard for it to register my touch.

Any ideas how i can restore the responsiveness of this button to my touch again?

Alex

**Comment by alvarotrigo** [comment]
Show us how are you adding the event over that button. You probably need to use `touchstart` and not only `click`.

**Comment by AlmondFace** [comment]
Here is a live link to my code, im running it in safari wthin an UIWebView, as part of an iOS app, but im getting the same problem viewing this on safari browser on iphone 5s, 6, and iPad Air.

http://dev3.comma-design.eu/

Plus white flickering on my backgroud images :(

**Comment by alvarotrigo** [comment]
Which is the button you are talking about, and the action assigned to it?

**Comment by AlmondFace** [comment]
check out the 2,4,6 slides. The design is set up for mobile devices, so alternative images for iPhone 4, 5-6+, and iPad. 2,4,6 have full screen images,so you can see the button on the bottom right. The issue im referring to is occurring with each of the buttons. np re:chrome, this is Safari specific.

**Comment by alvarotrigo** [comment]
Please add here the event / code that you are associating to those buttons actions.

**Comment by AlmondFace** [comment]
(function( $ ){

  $.fn.CrossFade = function(options, callback){

		var self = this;
		
		var params = $.extend(
				{	
					item_class : false,
					but_holder_class : '.but-holder',
					but_show_class : '.on',
					but_hide_class : '.off',
					content_class : '.content-holder',
					but_position: 'RightBottom', 
					window_position: 'Middle', 
					window_type: 'absolute',
					window_size_w: '50%', 
					window_size_h: '50%', 
					window_opacity: 0.9, 
					transition_time: 0.3
				},
				options
			);
		
		var method = {
			init: function(){

				this.prepare._init();
				this.observer._init();
				
			},
			observer: {
				_init: function(){
					this._show();
					this._hide();
					this._resize();
				},
				_show: function(){
					self.find(params.but_show_class).on('click', function(){
						method.animate._show();
					})
				},
				_hide: function(){
					self.find(params.but_hide_class).on('click', function(){
						method.animate._hide();
					})
				},
				_resize: function(){
					$(window).on('resize', function(){
						method.prepare._init();
					});
				}
			},
			prepare: {
				_init: function(){

					this._set_position(params.but_holder_class, params.but_position);
					this._set_window_size();
					this._set_window_type();
					this._set_position(params.content_class, params.window_position);
					
				},
				_set_position: function(item_class, pos){
					
					var item = self.find(item_class);
					
					if(pos == 'Middle'){
						
						item.addClass(pos);
						
						item.css({
							'margin-top'  : -item.height() / 2,
							'margin-left' : -item.width() / 2
						});
						
					} else if(pos != 'none'){
						item.addClass(pos);
					} 
				},
				_set_window_size: function(){
					
					var item = self.find(params.content_class),
						w_w = $(window).width(),
						w_h = $(window).height();
				
					if(params.window_size_w == 'auto'){
						
						item.width(w_w);
						
					} else if(params.window_size_w.indexOf('%') > 0){
						
						item.width(w_w / 100 * parseInt(params.window_size_w));
						
					} else {
						item.width(params.window_size_w);
					}
					
					if(params.window_size_h == 'auto'){
						
						item.height(w_h);
						
					} else if(params.window_size_h.indexOf('%') > 0){
						
						item.height(w_h / 100 * parseInt(params.window_size_h));
						
					} else {
						item.height(params.window_size_h);
					}
				},
				_set_window_type: function(){
					
					var item = self.find(params.content_class);
					
					switch(params.window_type){
						case 'absolute' : item.addClass('Abs'); break;
						case 'fixed' : item.addClass('Fix'); break;
					}
				}
			},
			animate: {
				_show: function(){
					var item = self.find(params.content_class);
					
					self.find(params.but_show_class).fadeOut(params.transition_time * 1000);
					self.find(params.but_hide_class).fadeIn(params.transition_time * 1000);
					
					item.fadeTo(params.transition_time * 1000, params.window_opacity, function(){
						//self.addClass('active');
					});
				},
				_hide: function(){
					var item = self.find(params.content_class);
					
					self.find(params.but_show_class).fadeIn(params.transition_time * 1000);
					self.find(params.but_hide_class).fadeOut(params.transition_time * 1000);
					
					item.fadeOut(params.transition_time * 1000, function(){
						//self.removeClass('active');
					});
				}
			}
		}

		method.init();
	
		if (callback && typeof(callback) === "function") { 
			callback(); 
		}  
	}
	
})( jQuery );

**Comment by alvarotrigo** [comment]
I need the specific code for the buttons. Can't waste time trying to understand all your code.

**Comment by alvarotrigo** [comment]
If you are using any kind of plugin, just initialize it in the afterRender callback.

**Comment by alvarotrigo** [comment]
I'll close this issue until some specific problem is reported.
