### ISSUE TITLE
Horizontal slides cannot scroll on mobile

### ISSUE THREAD

**Issue by lickcreative** [alvarotrigo/fullPage.js#1052]
I am using the responsive function to disable autoscrolling on mobile, which allows my longer sections to fit on a phone screen. My problem is that the horizontal slides are not affected by this setting, so I can only fit one screen height of content in each slide.

Is there any way to disable the slide layout for smaller screen sizes, and just stack the slides below the sections vertically?

**Comment by alvarotrigo** [comment]
You should be overriding the slides styles if you want slides bigger than the viewport height.  As you do with your sections.

**Comment by strigga** [comment]
so i can only override it with a fixed height?
and is it possible to set only 1 section with verticalCentered: false ?

**Comment by alvarotrigo** [comment]
Many things are possible with the right knowledge. 
It just happens that this forum is to treat fullpage.js issues and questions and not CSS ones.

**Comment by strigga** [comment]
yes, it was just a question if there is a JS event for setting a section to verticalCentered:false

**Comment by alvarotrigo** [comment]
> and is it possible to set only 1 section with verticalCentered: false ?

No, but again, you can override this with CSS.

**Comment by strigga** [comment]
okay, thank you.
