### ISSUE TITLE
Is it possible to clean url when I reload the page ?

### ISSUE THREAD

**Issue by davidprati** [alvarotrigo/fullPage.js#1053]
Hi,

First, thanks for your awesome script !
Second, sorry for my english :(

I use it, with anchors. The url changes when I scroll through the section, but when I reload the page, because of hash, the website is automatically scrolled at the previous section.

Is it a way to fix it ?

Thanks !

**Comment by alvarotrigo** [comment]
> when I reload the page, because of hash, the website is automatically scrolled at the previous section.

It is scrolled to the section with the anchor given in the URL.
That's the default behaviour of anchors for any site and part of the purpose of using anchors.

Nop, there's no way to avoid that. Just don't use anchors then.

**Comment by davidprati** [comment]
Hem yes sure, is it a js way to "clean" the url when the website load ?
Maybe split the url to delete the "#section" ?
website.com/#section1

Anyway, I just want to put a button to go to the last section, not necessarily an entire menu… Is it an other solution than anchors ? (windows.scrollTop ?)

**Comment by alvarotrigo** [comment]
If you want to do that you would have to do it yourself in the afterRender callback. The plugin doesn't provide that functionality. 

And if you don't know how to do it with javascript, then ask in stackoverflow.com 



> Anyway, I just want to put a button to go to the last section, not necessarily an entire menu… Is it an other solution than anchors ? (windows.scrollTop ?)

Use the methods the plugin provide. Such as `moveTo`.
