### ISSUE TITLE
afterRender not triggering on mobile devices

### ISSUE THREAD

**Issue by shocknawe** [alvarotrigo/fullPage.js#1056]
afterRender not triggering on mobile devices

**Comment by alvarotrigo** [comment]
That sounds weird. 
Which phone and browser are you using.

**Comment by alvarotrigo** [comment]
I'll close it meanwhile. 

You can test it using this [demo page](http://alvarotrigo.com/fullPage/examples/callbacks.html).
Which works for me all the devices I tried (iOS, Windows Phone, Android...)
