### ISSUE TITLE
sectionSelector only under specific parent... not all instances on page

### ISSUE THREAD

**Issue by richgcook** [alvarotrigo/fullPage.js#1058]
Is there the option to specific the sectionSelector to `$(this)` only. I have another element on the page with the same class but it is outside the `.fullpage` container but still getting included.

I thought the below would've work...

```
$('.home-section-container.desktop').fullpage({
    sectionSelector: '> .each-section',
````

Any thoughts?

**Comment by alvarotrigo** [comment]
Nop.
Use a different class for your fullPage.js sections then. A different one to any used outside its wrapper.
