### ISSUE TITLE
AutoScrolling

### ISSUE THREAD

**Issue by dchollo82** [alvarotrigo/fullPage.js#106]
Hi there,

I'm looking to use your carousel for a showcase I'm currently working on. It's going to be a demonstration thats on show for customers, and needs to automatically scroll vertically between pages without being invoked by mouse or swipe. I saw your section for setting autoScrolling, but can't seem to get it to work. Can you explain what I might be doing wrong please? 

Many thanks,

David

**Comment by strimdaddy** [comment]
Hi @alvarotrigo ,  when I turn autoscrolling to false the page keeps jumping back to the bottom anchor when i get to the top.  Anyway to turn off autoscrolling without this issue?
