### ISSUE TITLE
Slow on mobile

### ISSUE THREAD

**Issue by byzance** [alvarotrigo/fullPage.js#1061]
Hi, thanks for this amazing plugin! quick question here: my site is extremely slow when scrolling on mobile. I just tested the demo site, and it's fast, so there's no "delay" problem. I tested my site on Chrome for iPhone and it's a bit faster. 

Each of my sections has several slides which can flip using CSS3 transform animations. I wonder if my content is too heavy for the sections to load quickly and I wonder if anything can be done to improve performance. 

Thanks a million !

**Comment by alvarotrigo** [comment]
Make sure you use the latest version.  (2.5.9)
That you are using the option `css3:true`.
And that your images aren't huge. (in KB and in size) (use media queries, compressed images...)

This last point has nothing to do with fullPage.js, so I'd recommend you to ask in other places about it.
