### ISSUE TITLE
Separating user scrolling animation from anchor scrolling animation

### ISSUE THREAD

**Issue by aireater** [alvarotrigo/fullPage.js#1062]
Hi, 

Is it possible to enable scrolling animation for user driven events like prev and next buttons while disabling scrolling animation for anchor links?

I tried adding the following setting:

```javascript
animateAnchor: false,
```

But I had the scrolling speed set:
```javascript
scrollingSpeed: 600, 
```

And that wasn't working for me. 

When I set the scrolling speed to 0 the anchor animation was disabled.

It is possible to have both? 

Thanks.

**Comment by alvarotrigo** [comment]
Use the method `setAllowScrolling` on the `afterRender` callback for it:

Take a look at this:
http://jsfiddle.net/97tbk/493/

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    afterRender: function () {
        $.fn.fullpage.setAllowScrolling(false);
    }
});

$('button').click(function(){
    $.fn.fullpage.moveSectionDown();
});
```
