### ISSUE TITLE
Layout Extra Height with adding Section Number 5

### ISSUE THREAD

**Issue by soulmotion** [alvarotrigo/fullPage.js#1064]
The scroll works well till i added section 5 and more.
The section gives extra height and my pictures and elements that should be in the middle which was hidden or cover half to the bottom.
I have to resize the broswer window to fix this problem. After i resize it the whole layout goes well.
But if i am not resize it manually it gone wrong randomly sometimes layout is good sometimes extra height for the section gained.

here is my link
www.lejournaldejyeong.com

![capture](https://cloud.githubusercontent.com/assets/11367339/6542663/6bbf6980-c53a-11e4-8fd9-03ca62028e37.JPG)

**Comment by alvarotrigo** [comment]
You are missing the compulsore DOCTYPE declaration. 
It is not in the correct place. 

Put this at the very start of your document:

```html
<!doctype html>
```

And delete it from the position you have it now.

**Comment by soulmotion** [comment]
Thanks a lot~ Quick and Easy
