### ISSUE TITLE
Chrome ruins fonts after section preparing

### ISSUE THREAD

**Issue by BaldCatDev** [alvarotrigo/fullPage.js#1067]
Hi,
Found some weird issue. When in Chrome text becomes blurry after section preparing. All entire text within sections. 
Here is the example:
![image](https://cloud.githubusercontent.com/assets/10120407/6575275/15ef5436-c736-11e4-81fa-3977ce1f336c.png)

I've tried different settings with no luck. While Moz and Opera work great on it.
Any suggestions, please?

Anyway, appreciates come to alvarotigo for a great work.

**Comment by alvarotrigo** [comment]
Probably related with the css3 property `translate3d` and the way the browser deal with the fonts.
Not a problem of fullPage.js but of the brower.

http://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d

**Comment by BaldCatDev** [comment]
Thanks, it worked.
