### ISSUE TITLE
Horizontal scrolling speed separate from vertical speed

### ISSUE THREAD

**Issue by Zanfe** [alvarotrigo/fullPage.js#1068]
Hi,
it it possible to develop the "horizontal scrolling speed" option and the "auto horizontal scrolling" option for the sections?

Thanks
Bye
Andrea

**Comment by alvarotrigo** [comment]
The auto horizontal scrolling won't be added. Just use callbacks for it. Check [this answer](https://github.com/alvarotrigo/fullPage.js/issues/532).

**Comment by alvarotrigo** [comment]
Related with this topic https://github.com/alvarotrigo/fullPage.js/issues/4536

This is possible since version 4 that provides a `beforeLeave` callback.
