### ISSUE TITLE
Background image to cover each section.

### ISSUE THREAD

**Issue by visiblefrank** [alvarotrigo/fullPage.js#1069]
Hi, is it possible to have each section have an image background as so

background: url('img/rocks.jpg') no-repeat center center fixed;
	-webkit-background-size: cover;
	-moz-background-size: cover;
	-o-background-size: cover;
	background-size: cover;

when i use this the first section is the only one that displays the image. others loose all background settings. Possibly that i am using slides in the second section?

Many thanks and thanks for the plugin!

**Comment by alvarotrigo** [comment]
You might have problems using fixed positioned backgrounds when using `css3:true`.
That depends on the browser. It is a bug in Chrome.

http://codepen.io/herzflimmern/blog/chrome-bug-with-fixed-background-and-translate3d

**Comment by visiblefrank** [comment]
Thank you I'll have a look. Yes was using chrome.

**Comment by J3QQ4** [comment]
Turns out you just need to disable 'fixed', but keep 'center' and 'cover'.
