### ISSUE TITLE
2 sections, the last with a vertical scrollbar

### ISSUE THREAD

**Issue by jbclot** [alvarotrigo/fullPage.js#1071]
Hello,

I'm trying to build a Phonegap project with fullpage.js, but I have some difficulties with scrollable sections.

This is what I need :
A first section with an horizontal slider, which contains a background picture and a title.
A second (and last) section with another slider, with the content, height will vary, so the slide must be scrollable.
Between the scenes : swipe up/down and swipe left/right.

My problem is on the second section : I don't want to use the slimScroll plugin, because the scrolling experience is bad on a mobile ( slow, and no momentum)
I tried the fix with afterSlideLoad found on this page http://stackoverflow.com/questions/21817799/scrollbar-on-active-slide-for-overflowing-content-with-fullpage-js but with no result...

Do you know how can I make the last section scrollable,  or how can I use another plugin (like iScroll.js for example) with Fullpage.js ?

Thanks !

**Comment by alvarotrigo** [comment]
Not implemented yet in fullPage.js.

Related with https://github.com/alvarotrigo/fullPage.js/issues/623
