### ISSUE TITLE
How do you initialize fullpage when the page is partially loaded with pjax?

### ISSUE THREAD

**Issue by trichask** [alvarotrigo/fullPage.js#1073]
When the page is partially loaded with ajax, event handlers are attached multiple times.
There is a workaround to this by invoking jquery e.stopImmediatePropagation()
However this onlys work to keydownHandler and not scrollHandler.

**Comment by alvarotrigo** [comment]
You initialize it once. and Every time you render new content into the site, you destroy it with `$.fn.fullpage.destroy('all')` and you initialize it again.

Although my personal advice is DO NOT USE AJAX when using fullPage.js. It makes no sense.
Just create normal links.

**Comment by trichask** [comment]
This worked for me. Thank you.
