### ISSUE TITLE
Fullpage.js active statement on more than 3 navs.

### ISSUE THREAD

**Issue by cmehmet** [alvarotrigo/fullPage.js#1074]
Hi , I'm new on this website sector so i was wondering if you can help me on this . 

I'm using your awesome plugin to create a website for my gym. But having problem on making navigation items active . My website consists of 3 navigation menus . Main Menu , Services Menu and Contact Menu . And all of active statements for different navigation bars are working correctly. 

But ,there is a problem on a Page Slide Section which consists of two slides . One is for Location and when clicked to the arrow in the right it appears a Contact Slide Part . 
This section has it's uniqe navigation , consisting of two navbar items , Location and Contact . 

When i move to the first slide it's correctly showing me the active state of navbar item , which in this case it's Location . Then i slide to the right part , in the Contact section , it removes the li's first-child active state and ataches to this Navbar item . 

The problem is that , when i go  back to left slide , it doesn't remove the active statement from that slide and neither makes the Location slide navbar item active . 

Here's my code . 

afterLoad: function(anchorLink, index){
                var loadedSection = $(this);

                if(index == 8){
                    $( "#contactMenu ul li").removeClass("active");
                    $( "#contactMenu ul li:nth-child(1)").addClass("active");
                    

                }
}//end after load

afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
				var loadedSlide = $(this);

					if(slideAnchor == 'contact'){
						$( "#contactMenu ul li").removeClass("active");
						$( "#contactMenu ul li:nth-child(2)").addClass("active");
					}
			},
 
Can you please help on this , thanks again ...

**Comment by alvarotrigo** [comment]
You should be using the callbacks provided by the plugin to deal with your own menu, or if you prefer, yo can make use of the class added to the body as detailed in [this tutorial](https://www.youtube.com/watch?v=qiCVPpI9l3M).
