### ISSUE TITLE
linking to first slide

### ISSUE THREAD

**Issue by dynamic75** [alvarotrigo/fullPage.js#1075]
Hi Alvaro. I read some of the other threads but I still get get my page to scroll back to the first section after I have clicked another section. The site is: http://dynamic75.com/  I saw one of your other post suggested: adding an afterLoad handler, but that doesn't do anything. What am I missing? 

```javascript
 afterLoad: function(anchor, index){
	if(index == 1){
        	$.fn.fullpage.moveTo(1,0);
	}
}
```

**Comment by alvarotrigo** [comment]
I don't know what are you asking for. Not clear.
Please explain it better.
