### ISSUE TITLE
setAllowScrolling false not working in iOS

### ISSUE THREAD

**Issue by olavocarvlho** [alvarotrigo/fullPage.js#1076]
Hello, i was set setAllowScrolling to false and its all appear ok bur when i tested in iOS this option is not working, it´s something about new version of iOS??

**Comment by alvarotrigo** [comment]
It is working as far as I know. You can test it in [this demo page](http://alvarotrigo.com/fullPage/examples/methods.html) by clicking in the button "setAllowScrolling(false)".

If you think there's a bug with some other config, please provide a way to reproduce it. Your URL, a fiddle...

**Comment by olavocarvlho** [comment]
@alvarotrigo im´m testing on this page www.boostyourknowledge.com.br/mnb2015 and you can see the script at  www.boostyourknowledge.com.br/mnb2015/js/custom.js

**Comment by alvarotrigo** [comment]
Unable to reproduce it with your settings in this [demo I created](http://alvarotrigo.com/fullPage/prueba/examples/testAuto.html). 

In any case, add the function `setAutoScrolling` inside the `afterRender`.

And try to isolate the problem. Remove any other plugin or javascript that could be interfering with fullPage.js. 
Meanwhile, I'll close the topic until a clean reproduction is provided.

**Comment by olavocarvlho** [comment]
i uploaded a version with only fullPaje.js and i dont discover why this function dont working for me. I tried on the demo and worked fine. Can you help me?

http://boostyourknowledge.com.br/mnb2015e

**Comment by alvarotrigo** [comment]
Please, add the credits in the fullPage.js file as per:

> (The MIT License)
>
> Copyright (c) 2013 Alvaro Trigo <alvaro@alvarotrigo.com>
>
>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
>
>The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

And for me to know which version are you using.

**Comment by alvarotrigo** [comment]
I tried your last link. It works well on iPhone 5. The site doesn't scroll as expected.

**Comment by olavocarvlho** [comment]
Sorry about the credits but the minified file from the zip dont have this header before the code, check this by yourself. 

And about the scroll on Iphone 4S and 5 the site doesn´t scroll but on 5s and 6 it´s scroll..

**Comment by alvarotrigo** [comment]
Did you change the file again? It was not scrolling before and it is doing it now.

In any case, as I told you, **you should isolate the problem**. This is. I don't want to see **any other** javascript code in your custom.js besides the fullPage.js initialization (not even the callbacks code is needed to reproduce your problem)

**Comment by olavocarvlho** [comment]
Really sorry Alvaro, i changed the file for a new test but now i really isolate the problem! Is the same url.

**Comment by alvarotrigo** [comment]
@olavocarvlho now it seems to be working as expected. Tested in my iPhone 5 and http://www.browserstack.com/

**Comment by olavocarvlho** [comment]
Please, test in iPhone 5s or 6.. In the iPhone 5 is working as expected..

Em sex, 13 de mar de 2015 13:48, Álvaro <notifications@github.com> escreveu:

**Comment by alvarotrigo** [comment]
As I said, i tested it in browserstack using iPhone 6. It seems to work... 
The only thing I can think of is that its a matter of the last OS...

**Comment by olavocarvlho** [comment]
Thanks for attention Alvaro, now is working and i dont know why.. i´ll put the right credits on.. pls check the minified version cause thats dont have this header..

**Comment by alvarotrigo** [comment]
The latest one has them:
https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.min.js

**Comment by olavocarvlho** [comment]
I will put this version :)

Em dom, 15 de mar de 2015 09:12, Álvaro <notifications@github.com> escreveu:
