### ISSUE TITLE
Menu anchors don't always trigger a click

### ISSUE THREAD

**Issue by dennismonsewicz** [alvarotrigo/fullPage.js#1079]
For some reason clicking on a nav item doesn't always register that a click occurred and won't take you to that section. No errors occur just won't work

**Comment by alvarotrigo** [comment]
Nav or menu elements? You are talking about both but they are not the same...
If you are talking about menu elements, then YOU have to make sure they act in the correct way by adding the touchstart action over them or using some other technique to prevent the double click. 

Read this:
http://stackoverflow.com/questions/3038898/ipad-iphone-hover-problem-causes-the-user-to-double-click-a-link

**Comment by dennismonsewicz** [comment]
Thanks for getting back with me! What's happening is if I click an item in my menu to jump to that section, it sometimes doesn't jump or ease to that section.

**Comment by dennismonsewicz** [comment]
Here's the site for reference: http://staging-marketing360.herokuapp.com/

**Comment by alvarotrigo** [comment]
First of all, you are ilegally using fullPage.js as you are violating its license because you are not keeping the Copyright credits of the javascript file.


> (The MIT License)
>
> Copyright (c) 2013 Alvaro Trigo <alvaro@alvarotrigo.com>
>
>Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
>
>**The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.**

Keep them at the start:

> /**
 * fullPage 2.6.0
 * https://github.com/alvarotrigo/fullPage.js
 * MIT licensed
 *
 * Copyright (C) 2015 alvarotrigo.com - A project by Alvaro Trigo

 >*/

And secondly, you would have isolate the problem and recreate it somewhere without any external javacript. 
As you can see, the menu works properly on the [demo site](http://alvarotrigo.com/fullPage/examples/normalScroll.html). 

I would recommend in any case you to try using `fitToSection:false`.

**Comment by dennismonsewicz** [comment]
I'm so sorry the copyright credits were stripped out. Not sure how that
happened. Thanks for your help! Love the plugin

On Friday, March 13, 2015, Álvaro <notifications@github.com> wrote:

> First of all, you are ilegally using fullPage.js as you are violating its
> license because you are not keeping the Copyright credits of the javascript
> file.
>
> (The MIT License)
>
> Copyright (c) 2013 Alvaro Trigo alvaro@alvarotrigo.com
> <javascript:_e(%7B%7D,'cvml','alvaro@alvarotrigo.com');>
>
> Permission is hereby granted, free of charge, to any person obtaining a
> copy of this software and associated documentation files (the 'Software'),
> to deal in the Software without restriction, including without limitation
> the rights to use, copy, modify, merge, publish, distribute, sublicense,
> and/or sell copies of the Software, and to permit persons to whom the
> Software is furnished to do so, subject to the following conditions:
>
> *The above copyright notice and this permission notice shall be included
> in all copies or substantial portions of the Software.*
>
> Keep them at the start:
>
> /**
>
>    - fullPage 2.6.0
>    - https://github.com/alvarotrigo/fullPage.js
>    - MIT licensed *
>    - Copyright (C) 2015 alvarotrigo.com - A project by Alvaro Trigo
>
> */
>
> And secondly, you would have isolate the problem and recreate it somewhere
> without any external javacript.
> As you can see, the menu works properly on the demo site
> <http://alvarotrigo.com/fullPage/examples/normalScroll.html>.
>
> I would recommend in any case you to try using fitToSection:false.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1079#issuecomment-79030048>
> .
>


-- 

Dennis Monsewicz Jr.C: (256) 339-8716dennismonsewicz.com

**Comment by dennismonsewicz** [comment]
I looked into the issue with the copyright not being included. Rails wasn't configured properly when minifying assets and is stripping out any and all comments from asset files. This is being adjusted (in prod and staging) and a new build will go out shortly.

**Comment by alvarotrigo** [comment]
Did you solve your problem then? Did you tried using `fitToSection:false`?

**Comment by dennismonsewicz** [comment]
Yep! My markup wasn't correct and that setting worked great!

On Friday, March 13, 2015, Álvaro <notifications@github.com> wrote:

> Did you solve your problem then? Did you tried using fitToSection:false?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1079#issuecomment-79466958>
> .
>


-- 

Dennis Monsewicz Jr.C: (256) 339-8716dennismonsewicz.com

**Comment by alvarotrigo** [comment]
No problem!
