### ISSUE TITLE
scollOverflow not reinitializing after resize.

### ISSUE THREAD

**Issue by BeauKelsey** [alvarotrigo/fullPage.js#1080]
I have a .section that has a child div (".scrollable") that has nested content that scrolls. ".scrollable" has a relative position. Basically scrollOverflow works as it should upon load. If I resize the window and make it bigger the content shrinks and there is no need for the scroll bar so it disappears as it should. The problem is... If I shrink the window again... slimScroll does not re-appear as it should. What could be happening?

```
<div class="section">
     <div class="scrollable">
     </div>
</div
```

**Comment by BeauKelsey** [comment]
This only happens in Chrome.

**Comment by alvarotrigo** [comment]
Can you provide a link to reproduce the issue? 
It can be related with absolute positioned elements.

**Comment by BeauKelsey** [comment]
I tried to reproduce but couldn't. I can send you my project if you want. Might be easier. I am not using absolutes and sometimes the scrollbar decides to show up.

**Comment by alvarotrigo** [comment]
A clean reproduction isolating the problem is preferable.  Otherwise, a link to your site.

**Comment by BeauKelsey** [comment]
Okay check this out. So much better just to upload my project instead of using a fiddle. shrink your window and scroll down to the second to last section. Then resize to full screen... and shrink again. Use Chrome.

 http://wonderpin.co/test/

**Comment by alvarotrigo** [comment]
I don't see any problem. If you are taking about the section just after the video (the 6th), I see it well.

**Comment by BeauKelsey** [comment]
See the screenshot. No scroll bar... 

![screen shot 2015-03-15 at 7 04 54 pm](https://cloud.githubusercontent.com/assets/10481312/6659586/408ee904-cb46-11e4-9a31-937a6ae8b69b.png)

**Comment by alvarotrigo** [comment]
I'm sorry, I'm not able to reproduce the error. I get the scroll bar.

**Comment by alvarotrigo** [comment]
Right, I was able to reproduce the problem but it is not something that takes place all times. Just randomly.

Try removing the :before and :after classes from your sections.

**Comment by BeauKelsey** [comment]
I removed the :before and :after. No change. I made this section in to a slide and added a couple slides to it. The problem fixed itself with this structure change.
