### ISSUE TITLE
Mixed behaviour in demo page Scrolling inside sections

### ISSUE THREAD

**Issue by HA-KR** [alvarotrigo/fullPage.js#1082]
On this demo page [Scrolling inside sections](http://alvarotrigo.com/fullPage/examples/scrolling.html), observed a mixed behaviour

1. `Click-hold-drag` of scrollbar just shows me contents of firstPage
2. `PageUp`/ `PageDown` - goes to next page without showing the full contents of firstPage
3. `scroll` using mouse seems to work fine

**Comment by alvarotrigo** [comment]
1- Its suppose to be like that. 
2- That's something to think about.

**Comment by alvarotrigo** [comment]
Won't be solved as slimScroll.js doesn't provide a way to deal with it and probably fullpage.js will turn to iScroll.js.
