### ISSUE TITLE
Pure javascript version produce error on IE11

### ISSUE THREAD

**Issue by Alston-Tang** [alvarotrigo/fullPage.js#1084]
There is something wrong with pure javascript version on IE, Windows8.1 on my computer.
The position of error is
at addTouchHandler (http://localhost:9000/shared/vendor/fullpage.js:1768:9)

        document.removeEventListener('touchstart ' + MSPointer.down);
        document.removeEventListener('touchmove ' + MSPointer.move);

        document.addEventListener('touchstart ' + MSPointer.down, touchStartHandler);
        document.addEventListener('touchmove ' + MSPointer.move, touchMoveHandler);
It seems that removeEventListener requires two parameters while here only provide one.
Also I don't quit understand why concatenate MS event name with touchstart here.

**Comment by alvarotrigo** [comment]
It doesn't produce any error to me testing it with browserstack.com.
In any case, as detailed in the docs:

> This is in Alpha version and support for it won't be provided yet.
