### ISSUE TITLE
undefined problem

### ISSUE THREAD

**Issue by ambicoder** [alvarotrigo/fullPage.js#1085]
The console displays "undefined is not a function" a problem.I followed the rules about the placement of the required files...nonetheless they do not work. I have a fear that there might an interference with other plugins I am using(fullcalendar,backbone...etc).Anyway...here is the jsfiddle http://jsbin.com/silajo/77/

**Comment by alvarotrigo** [comment]
And... where is fullPage.js in your jsbin?

**Comment by ambicoder** [comment]
http://jsbin.com/silajo/78/

**Comment by alvarotrigo** [comment]
Documentation says:

> jQuery library. (1.6.0 minimum)

**Comment by ambicoder** [comment]
give me 2 minutes

**Comment by ambicoder** [comment]
nonetheless there is still an issue,,,even if the scrolling works....take a look at this fiddle http://jsbin.com/silajo/76/ without fullpage included...a calendar is displayed.....by a plugin(FullCalendar)....with fullpage included the calendar is "lost" http://jsbin.com/silajo/79/

**Comment by alvarotrigo** [comment]
Make sure you initializae it on the afterRender callback. Check the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

**Comment by ambicoder** [comment]
is this what you mean http://jsbin.com/qinulu/3/ ? go at line 46...I still do not get what I want.

**Comment by alvarotrigo** [comment]
No, initialize all your external plugins inside the `afterRender` callback.

**Comment by ambicoder** [comment]
well...my problem is I am using backbone...and I am not quite sure how to do it(meaning in the context of backbone).Do you know anything from backbone...or else I will address my issue to backbone support...I am  just asking....since this is not here a backbone support forum you are not obliged to answer anyway.

**Comment by alvarotrigo** [comment]
As far as I know, backbone is similar to Angular. When dealing with this frameworks you have to be careful of how many times you initialize a plugin, as this is one of the common problems people have initializing per content loaded (per link users click).

You should be playing with the function `$.fn.fullpage.destroy('all')` and the initialization. So whenever you load a new fullpage.js page (if that's the case), you should destroy fullpage.js (if it was initialized before) and then initialize it again.
If you load a new content which doesn't require fullpage.js, then you just need to destroy fullpage.js to liberate the events used by it (mousewheel, scroll, touch...).

**Comment by ambicoder** [comment]
well I managed to solve the problem(mostly)...without resorting to what you refer to http://jsbin.com/silajo/99/   the only problem now is with HTML...despite I have enclosed an input element is a separate section...look at the jsbin to see what happens. They kind of overlap...just scroll to see the input element at the bottom.maybe this problem is not related to fullpage

**Comment by alvarotrigo** [comment]
I don't  know what are you talking about. I don't see anything weird with the input element.

**Comment by ambicoder** [comment]
look at this image..it is a snapshot from jsbin http://1drv.ms/1ASr8zW can you see the overlap...after you scroll into the section that holds the input element

**Comment by alvarotrigo** [comment]
I'm not having that problem in Chrome. Which browser are you using?

**Comment by ambicoder** [comment]
I am using chrome too...I do not what to say...I see clearly the problem in jsbin,here is the link again just to be sure  http://jsbin.com/silajo/100/

**Comment by ambicoder** [comment]
the problem seems to be css related
