### ISSUE TITLE
conflict with jquery.event.move?

### ISSUE THREAD

**Issue by jackyon** [alvarotrigo/fullPage.js#1088]
Hi, 

thanks for the great plugin! I have one issue:
is it possible enable horizontal drag with fullpage.js?

the drag event works perfect without fullpage.js, but not with fullpage.js, how can I integrate with fullpage.js? 

two demo link:
works without fullpage.js: http://www.cstory.cn/before-after/before-after.html
not working with fullpage.js: http://www.cstory.cn/before-after-1/before-after.html (chrome device model)

plz advise!

thx!

**Comment by alvarotrigo** [comment]
Please read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

Initialize external plugins in the `afterRender` plugin.

**Comment by jackyon** [comment]
Hi alvarotrigo,

I haved read the doc & faq, and also tried both afterRender and onLeave method. but all failed, I think this  issue is not the rendering issue, the code still can run but just the horizontal drag method is disable by the fullpage.js.

here is the issue link:
http://www.cstory.cn/before-after-1/before-after.html (chrome device model, the drag function only works in desktop model)

plz advise.

thx!

**Comment by alvarotrigo** [comment]
Oh right.. you are talking about mobile devices...
That's gonna be more difficult to solve. It seems both plugins are adding the touch events to the document. 
And, in any case, unless you  make an straight line in the X axys, fullPage.js would scroll vertically with your swipe...

**Comment by jackyon** [comment]
Hi alvarotrigo,

so do you mean there is no way to disable the touch events temporary from the fullpage.js?

btw, I have tried to drag straight line in the X axys, but the drag events seems still block by fullpage.js. It only works in desktop version.

thx.

**Comment by alvarotrigo** [comment]
You can do that, but it doesn't seem to be working. Not sure the reason. 
Even if you remove the touch and move events of fullPage.js, it doesn't work.

**Comment by alvarotrigo** [comment]
Try using the latest version 2.6.3.
I believe it has been solved.

**Comment by jackyon** [comment]
wow, this works! thx! alvarotrigo.

**Comment by jackyon** [comment]
Hi alvarotrigo,

hm... after I updated to the 2.6.3 version, everything is okay, except the overlay elements not working any more..

i.e
My html structure:
```
<div class="fixed-overlay" style="position:fixed;bottom:0;z-index:99999;height:80%;width:100%;">
        fixed overlay elements here
    </div>
  	<div id="fullpage">
	    <div class="section">Some section</div>
	    <div class="section">Some section</div>
	    <div class="section">Some section</div>
	    <div class="section">Some section</div>
	</div>
```

when I scroll on the overlay elements, the section didn't jump to the next section/prev section.

Here is the issue demo link:
http://cstory.cn/fullpage-test/

plz advise! thx!

**Comment by alvarotrigo** [comment]
I'm afraid that solving one issue will make the other appear. 

The only solution to this would be to add your fixed element inside the fullPage.js wrapper, but that might carry some problems when using css3:true in some browsers (or at least, it did in the past) and it doesn't sound like the proper solution to it....

I might have to go back to the previous version as

**Comment by alvarotrigo** [comment]
I see the problem.
When I updated fullPage.js I tried to improve also the mouse scrolling behavior, but I guess I will  have to revert it and leave only the touch improvement.

**Comment by alvarotrigo** [comment]
I'll close the issue as the problem with the touch events was solved.
