### ISSUE TITLE
top section problem

### ISSUE THREAD

**Issue by ambicoder** [alvarotrigo/fullPage.js#1089]
I have a top section in my website which I wanted to be in place when fullpage is used to alter pages/views...as such I have not enclosed it in section div...there are two problems though.

When I scroll to alter page/view the page goes above this top section.

Second...after scrolling has taken place,in the top.some area from the bottom of the first section/page appear to overlap the top section....see for yourself these two issues: 
http://jsbin.com/silajo/107/

**Comment by alvarotrigo** [comment]
You should check the [fixed headers example](http://alvarotrigo.com/fullPage/examples/fixedHeaders.html) also available in the examples folder.

You should be using a fixed header, and playing with the `paddingTop` property.

> When I scroll to alter page/view the page goes above this top section.

Problem of CSS knowledge. `z-index` property. It doesn't belong to this forum.

**Comment by ambicoder** [comment]
thanks again
