### ISSUE TITLE
Funky Resizing 

### ISSUE THREAD

**Issue by BeauKelsey** [alvarotrigo/fullPage.js#1090]
Any idea why I am getting this weird resize delay on section 6?

http://wonderpin.co/test/#college-essays/Does-College-pay

**Comment by alvarotrigo** [comment]
Please explain yourself.

**Comment by BeauKelsey** [comment]
Please have a look at section 6. When you resize the window the other slides become visible. Any idea why? That shouldn't happen.

**Comment by alvarotrigo** [comment]
Searh through the forum. That has been answered before.
