### ISSUE TITLE
Anchor Problem

### ISSUE THREAD

**Issue by elizabeth268** [alvarotrigo/fullPage.js#1091]
Hi Alvaro,

When working on my project and trying to declare anchors .... I keep on having this problem where when anchors are declared they end up screwing up my page and skipping the second section during scrolling. Therefore I did some tests on previous projects of my and they cause the same problems too. 
For example: I have 5 sections ... each with a unique id .... they will than be grabbed and declared as anchors .... Eg. anchors [ 'home', 'about', 'history', 'gallery', 'contact us' ] ..... once this is done, the webpage would skip section 2 when scrolling ... anyhow, after taking the anchor initialization out ... the problem is gone. 

What might be the cause of this issue and how may I fix it asap?

Thanks.

**Comment by alvarotrigo** [comment]
If you check your javascript consosole you will find this error:

> data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).

And in the docs:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by elizabeth268** [comment]
Yes, I read through all your docs already and have noticed this warning. But I didn't think it applied to this situation ... since I thought that in order for the anchors to know which section is which they had to be declared. Guess I was wrong. Thinking about it again the anchors are an array so they would be declared in sequence anyways. 
I'm just learning everyday. Thanks.
