### ISSUE TITLE
fade instead of easing 

### ISSUE THREAD

**Issue by redreeva** [alvarotrigo/fullPage.js#1093]
Hi! Is it possible to add fade effect on slide changing? Thanks.

**Comment by alvarotrigo** [comment]
Nop, this is an scrolling plugin I'm afraid.

**Comment by redreeva** [comment]
Ok. Thank you for answer.

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
