### ISSUE TITLE
minified css please?

### ISSUE THREAD

**Issue by tomByrer** [alvarotrigo/fullPage.js#1096]
I was going to automate uploading of your lib to (jsDelivr CDN](http://www.jsdelivr.com/#!jquery.fullpage), but noted you only minify the JS.  Could you also minify the CSS so I can program the bot to auto-update?

**Comment by alvarotrigo** [comment]
I usually try to keep it as simple as possible for newbies and adding more files can make it a bit more confusing for this group.
I don't consider a minification of the existent CSS file will provide much benefits, so I'm not quite sure about this idea.
Also, other CDNs such as cdnjs.com get all files and compress them when needed:
https://cdnjs.com/libraries/fullpage.js, which sounds like a good alternative solution to me.

**Comment by tomByrer** [comment]
Many (majority?) of Github repos use a `/dist` folder or the like for the minified files.
Minifying your CSS will save 2.5k, adds up.
I thought about programming the bot to minify CSS, but I'm apprehensive about breaking the CSS; I'd hope the dev would test minified files before publishing.

[jquery.reveal](http://www.jsdelivr.com/#!jquery.reveal) or [reveal.js](http://www.jsdelivr.com/#!reveal.js)?  impress is there also.  Humm... 2/3 of those are providing non-minified files, but I think they were uploaded before minification enforcement.

BTW, I prefer minified files include a comment-header like you do for your `.min.js`, since we can [concoct files](http://cdn.jsdelivr.net/g/jquery@1.11,jquery.ui@1.9.2%28jquery.ui.effect.min.js%29,slimscroll@1.3,jquery.fullpage@2.4), saving several HTTP requests & a bit smaller compression.

**Comment by alvarotrigo** [comment]
> jquery.reveal or reveal.js? impress is there also.

Nop, I'm talking about [reveal.js](https://github.com/hakimel/reveal.js) or [impress.js](https://github.com/bartaz/impress.js/), which are different from the files you can find in jsdelivr.


> I thought about programming the bot to minify CSS, but I'm apprehensive about breaking the CSS

How would you break it? Not quite sure to understand it. A proper compression should provide the exact same results as the non minified version. In the case of using CSS, by just removing whitespaces, indentation and line jumps.

**Comment by tomByrer** [comment]
> I'm talking about reveal.js ... , which are different from the files you can find in jsdelivr.

Uploaded by a human being who compressed said files on their own, which I don't want to do any more, esp for someone like you who publishes new versions almost weekly (which is a good thing).
https://github.com/jsdelivr/jsdelivr/pull/3156
I'm not expecting you to compress by hand either; do you use a build tool?

> just removing whitespaces, indentation and line jumps

This would be the safest compression; perhaps the bot should do that?
I'm used to using [more aggressive CSS compressors](http://goalsmashers.github.io/css-minification-benchmark/).

**Comment by alvarotrigo** [comment]
It is provided now in the `dist` folder. Created using the `gulp` script as detailed in the docs.

**Comment by alvarotrigo** [comment]
@tomByrer  jsdeliver still sin version 2.5.9 when the current one is 2.8.6.
No idea why this is happening. I am already providing the `dist` folder with the minified CSS file.

**Comment by tomByrer** [comment]
Hmmm, not sure how to make the [`update.json`](https://github.com/jsdelivr/libgrabber#add-updatejson-schema) to automate the uploading process since you have a vendor sub-folder.  We don't have any mapping of folder like that sorry.... & the main dev is reprogramming jsDelivr I think to mirror npm I believe.

So unfortunately for the short-term, [manual uploads](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md#advanced---manual) are needed; just mirror the last version's files to prevent the bot's complaints.
