### ISSUE TITLE
IE9 section height with paddingTop settings

### ISSUE THREAD

**Issue by Stefanowitsch84** [alvarotrigo/fullPage.js#1097]
I want my sections to have a top padding of 40px (set as a parameter when initialising the plugin). 
I have a fixed header and the scrollbars should start below the header (scrollOverflow: true).

It works on every browser, except the IE9. Here the section height goes beyond the browser viewport when I set a value for padding top. So the footer (which sits at bottom: 0) is cut off at the bottom.

**Comment by alvarotrigo** [comment]
Can you provide a way to reproduce it?

**Comment by Stefanowitsch84** [comment]
Please have a look here:

http://beta.beachmotels.de/motel/bulliparkplaetze

Scrollbars go beyond the viewport.

**Comment by alvarotrigo** [comment]
You have some unusual stuff going on, such as the `backgroundimgs` element which has position fixed. Try removing it and also removing the `:before` and `:after` styles you have in some of those divs. They are applying `content: " ";  display: table;` and that might be causing problems to calculate the height of the content.
