### ISSUE TITLE
Disable scroll

### ISSUE THREAD

**Issue by lizzy-creative-covered** [alvarotrigo/fullPage.js#1098]
Hi, Is there a way to disable 'upwards' scrolling? so the user can only scroll down, or click on a 'back to top' arrow to get to the start of the sections and start scrolling down again.

Thanks

**Comment by alvarotrigo** [comment]
Check the [setAllowScrolling](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) function.

**Comment by lizzy-creative-covered** [comment]
Thanks, I have added this in, but my 'scrollup' button doesn't seem to work?

Here's the fiddle: http://jsfiddle.net/804mnwbz/1/

(I'm also using the cool multiscroll plugin)

Any ideas?

**Comment by alvarotrigo** [comment]
Just keep using the plugin functions `$.fn.fullpage.moveSectionUp();`  
http://jsfiddle.net/804mnwbz/3/
