### ISSUE TITLE
Scroll second div on the page

### ISSUE THREAD

**Issue by dingo-d** [alvarotrigo/fullPage.js#1099]
Hi!

Love the plugin, I just have one question. I have a site, where my main sections are fullwidth, and when I click on one of them, a second section opens up to the right. The main one where the fullPage scroll is, shrinks to 60% of the page, and the right one is 40%. 

Now, several things are worrying me. First, even if the right div is visible, when I scroll down, my left section scrolls. That's probably because you binded some kind of mouse scroll event to it? I am wondering is it possible to limit that scroll only when the slide is on full width (I am controlling that via css and by adding the class on it on click)?

Also When I 'open' the right div, even tho it's height is greater then the window height, I cannot scroll it. I tried with `overflow-y:scroll` but nothing happened, It just scrolls the left div (the one with fullPage working on it). Is there some workaround? 

Thanks :)

**Comment by alvarotrigo** [comment]
> Now, several things are worrying me. First, even if the right div is visible, when I scroll down, my left section scrolls. That's probably because you binded some kind of mouse scroll event to it? I am wondering is it possible to limit that scroll only when the slide is on full width (I am controlling that via css and by adding the class on it on click)?

You can use the option `normalScrollElements` or rather use the function `setAllowScrolling('false')`.



> Also When I 'open' the right div, even tho it's height is greater then the window height, I cannot scroll it. I tried with overflow-y:scroll but nothing happened, It just scrolls the left div (the one with fullPage working on it). Is there some workaround?

Se its height to 100%, then use `overflow-y:scroll` and use the option `normalScrollElements` for it.

**Comment by dingo-d** [comment]
Thank you very much! :)
