### ISSUE TITLE
Just a lil' question on the slide classes

### ISSUE THREAD

**Issue by ceocookie** [alvarotrigo/fullPage.js#1100]
Hey there!

Not sure if it's okay to ask here, but could your kindly clarify if
using fixed headers will affect the height of the slide divs(`<div class="slide">`)?
I am trying to get the slide div to occupy the remaining space up to
the fixed header but it would seem that the div can't be moved(the blue border).

Thanks!
![screenshot 2015-03-23 12 27 17](https://cloud.githubusercontent.com/assets/6264679/6774208/1d571e4e-d158-11e4-856d-b92f33973033.png)

**Comment by alvarotrigo** [comment]
You might have that problem because you are using `paddingTop`, not because of using fixed elements. 

In that case I would recommend you to solve it by using the CSS property `background-position` and adding a negative value equals to the paddingTop value for the Y axys.

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/1031
