### ISSUE TITLE
Need to load dynamic data in the section when that section is active

### ISSUE THREAD

**Issue by aswinkumar** [alvarotrigo/fullPage.js#1102]
Hi
 I have requirement that I need to load the data into a section whenever that section is loading or whenever that particular anchor index is clicked. 

<div id="fullpage">
<div class="section">Some text or image loaded already</div>
<div class="section">Some text loaded already</div>
<div class="section">Some graphical content to be loaded dynamically when this section is showing in the browser</div>
<div class="section">Some text loaded already</div>

Please help me

**Comment by alvarotrigo** [comment]
That has nothing to do with fullPage.js.
You will need to use javascript and the ajax technique to do it.

The only thing you might need to know that can be related with fullpage.js is that if you want to use `scrollOverflow`, then you would need to call the `reBuild` function after you load the content into the section, so fullPage.js can calculate the size to the new content and determine whether to use an scroll bar or not, and which size should it have.
