### ISSUE TITLE
Section 1 to section 3 step by step?

### ISSUE THREAD

**Issue by valimvf** [alvarotrigo/fullPage.js#1103]
Is there any way to scroll from section 1 to section 3 step by step? So the scroll from 1 to 3 will not last 700ms as it is default, but 1400, and if easings are used see them applied at each step, not just once? Here is an example. http://chooseyouretec.com/en-us/

The only possible way that I see right now is to rewrite the actions from the navigation. I just wanna make sure this isn't already done yet.

**Comment by alvarotrigo** [comment]
I'm not sure to understand what are you talking about.
I don't see any difference in the link you provide besides the animations of the engine.

**Comment by valimvf** [comment]
Ignore the animation. Look at the backgrounds. If you go to the second screen it takes 1 second (let's say), and if you go from first slide to the 4th slide using the navigation from the right side of the screen it doesn't take 1 second, but 4.

**Comment by alvarotrigo** [comment]
Ok, I see what you mean.

Nop, the plugin doesn't provide any option for it. I'll think about it.

**Comment by valimvf** [comment]
Ok, thanks a lot.

**Comment by alvarotrigo** [comment]
So, [contact me](http://alvarotrigo.com/#contact-page) in case you really need it.
