### ISSUE TITLE
Scroll from Section 1 to Section 3 without showing Section 2?

### ISSUE THREAD

**Issue by magentapose** [alvarotrigo/fullPage.js#1104]
Hi!

Thanks for the great code.

I'm wondering if there is a way to scroll between sections whilst missing out the sections in-between?

E.g.... is there a method that will allow me to scroll from section 1 to section 3 without displaying section 2 in between? I need to create a link to section 3 from section 1, but I don't want the user to see section 2 as they scroll from section 1 to 3.

Thanks in advance for your time

**Comment by alvarotrigo** [comment]
You can use the plugin function `moveTo` and before calling it set the scrolling speed to 0 by using the function `setScrollingSpeed`.

Something like:

```javascript
$('#link').click(function () {
    $.fn.fullpage.setScrollilngSpeed(0);
    $.fn.fullpage.moveTo(3);
    $.fn.fullpage.setScrollilngSpeed(700);
});
```

**Comment by magentapose** [comment]
@alvarotrigo Thanks a lot - but what will that last setScrollilngSpeed do? I understand the first one, but why the second one?

**Comment by alvarotrigo** [comment]
The default one:
> scrollingSpeed: (default 700) Speed in milliseconds for the scrolling transitions.
