### ISSUE TITLE
Disable scrolling between sections on desktop and mobile?

### ISSUE THREAD

**Issue by magentapose** [alvarotrigo/fullPage.js#1105]
Is it currently possible to disable scrolling between sections on desktop and mobile (e.g. using the mousescroll or touch)?

I want the user to switch sections by pressing a button rather than scrolling or swiping down the page for example. However, I still want the user to be able to swipe to the left/right to scroll through slides.

Thank you

**Comment by alvarotrigo** [comment]
Yeah, it is.
Just use the function `setAllowScrollilng` and use for your buttons normal links if you are using anchors, or the function `moveTo`.

**Comment by magentapose** [comment]
thanks!
