### ISSUE TITLE
Can I use $.fn.fullpage.setScrollOverflow(false); ?

### ISSUE THREAD

**Issue by magentapose** [alvarotrigo/fullPage.js#1107]
Hi, 

Can I use $.fn.fullpage.setScrollOverflow(false); in a function, when the default scrollOverflow is true?

**Comment by alvarotrigo** [comment]
There's no such function. So nop.

**Comment by magentapose** [comment]
@alvarotrigo Is there some alternative that I can do? Can you do me a custom job?

**Comment by alvarotrigo** [comment]
For what exactly do you need it for. `scrollOverflow` doesn't act if there's no need to create the scroll bar.
