### ISSUE TITLE
Stop the slider on mouse hover

### ISSUE THREAD

**Issue by foxpcteam** [alvarotrigo/fullPage.js#1108]
How can we stop the slider on mouse hover?

Thanks

**Comment by alvarotrigo** [comment]
I don't understand what are you asking for. Please elaborate it.

**Comment by foxpcteam** [comment]
Hi sorry that i did not explain.

i am using slider with auto slide function:

	        afterLoad: function( anchorLink, index){
            var loadedSlide = $(this);
            if(index == 4){
                slideTimeout = setInterval(function () {
                $.fn.fullpage.moveSlideRight();
             }, 8000);	
            }
        },

the question is if there is any way to pause the slider when the user hover with mouse on the slider?

**Comment by alvarotrigo** [comment]
I guess you mean, "mean the user MOVES his mouse".

And yeah, of course, just clear the interval with clearInterval(slideTimeout); whenever you want. 

That's a matter of javascript, not related with fullPage.js.

**Comment by marcstampfli** [comment]
I did the following..
`var interval = 7000;`

`afterRender: function(){
					slideTimeout = setInterval(function(){
						$.fn.fullpage.moveSlideRight();
					}, interval);
				},`

`$('.slide-item img').hover(function() {
				clearInterval(slideTimeout)
			}, function() {
				slideTimeout = setInterval(function(){
					$.fn.fullpage.moveSlideRight();
				}, interval);
			});`

Seems to be working to pause and resume interval on hover.
