### ISSUE TITLE
Change sectionsColor to sectionsBG

### ISSUE THREAD

**Issue by marcusparsons** [alvarotrigo/fullPage.js#1109]
Hello,

I am using this option in my own copy of fullPage.js, but I think that the sectionsColor option should be sectionsBG (or another similar option title) and use the "background" property instead of "background-color" that way that any valid background that can be applied via CSS can be used instead of just colors.

**Comment by alvarotrigo** [comment]
Thanks, but the option `sectionsColor` is only there to make it easier for people with few CSS knowledge to be able to create a fast fullPage.js website.
I believe any matter of design should be done by CSS preferable. 

I'm not planning to include any option regarding backgrounds, as [they are more](http://www.w3schools.com/css/css_background.asp) than just adding a link to an image. 
Also, fullPage.js would applying them with an inline style which is not desirable.

**Comment by marcusparsons** [comment]
What are you talking about? How do you get that they would be applied via an inline style? All I had to do was change the jQuery call from "background-color" to "background" lmao.  I don't even know where you got "adding a link to an image" from...lol.

**Comment by marcusparsons** [comment]
It is literally the same code except for you are using the CSS background property instead of the CSS background-color property.  

if (typeof options.sectionsBG[index] !==  'undefined') {
    $(this).css('background', options.sectionsBG[index]);
}

**Comment by alvarotrigo** [comment]
> $(this).css('background', options.sectionsBG[index]);

That applies and inline style I'm afraid. 

In any case, as I said, I'm afraid I'm not planning to add the feature.

**Comment by marcusparsons** [comment]
That is literally the code you use in your fullPage.js with a different property.  Do you have any idea what's going on in your own project? lol

**Comment by marcusparsons** [comment]
You're an idiot.

**Comment by alvarotrigo** [comment]
@marcobuettner using `background` to apply an inline color will cause troubles when trying to use any other background property by using CSS.

Feel free to keep using your modification if you prefer it that way.

**Comment by marcusparsons** [comment]
You are correct.  Can you please delete this issue? Thanks.

**Comment by alvarotrigo** [comment]
I'm sorry, [issues can not be deleted at github](http://stackoverflow.com/questions/3081521/removing-github-issues).
