### ISSUE TITLE
Hide Dots Menu on first Page

### ISSUE THREAD

**Issue by N0WayH0me** [alvarotrigo/fullPage.js#1110]
Hi.

I want to use navigationV with a little mod.
I will have 1 fixed menu on top of first page and then the dots menu during navigation.

So on first page ( in fact, first anchor ) only, i want to hide the dots menu.

How to do such things ?

Thanks.

**Comment by alvarotrigo** [comment]
Just use CSS to hide them by using the class adde to the body element, for example:

```css
body.fp-viewing-0 #fp-nav{
    display:none;
}
```

Or jquery with some callback if you prefer.

**Comment by N0WayH0me** [comment]
Thanks a lot.
Works fine.
