### ISSUE TITLE
Videos not clipping until after load.

### ISSUE THREAD

**Issue by akrigline** [alvarotrigo/fullPage.js#1111]
This is an odd thing:

http://codepen.io/akrigline/pen/WbPVMR

Videos aren't accepting overflow:hidden until the slide they're in is done scrolling (which incidentally is also when the video starts playing).

I made a pen without fullpage, and the videos have no problem accepting the overflow.
http://codepen.io/akrigline/pen/vEbojB

Any chance you know of a way to fix this?

**Comment by alvarotrigo** [comment]
What do you mean with:

> Videos aren't accepting overflow:hidden

**Comment by akrigline** [comment]
I've been trying to get my video elements clipped into a circle by putting them into a div with a border radius of 50% and overflow: hidden.

The first slide's video of each section was accepting this without problem and was being clipped into a circle without issue. But each slide's video after that one was having problems.

Demo of problem outside codepen here:
http://experiments.akrigline.com/seniorshow/
Note that this only happens in Safari and Chrome.

In Chrome, the video flashes as a square briefly before clipping into a circle, in safari it simple refuses to clip.

I tried to isolate the problem with a codepen but it seems to have not transferred. Interesting.

**Comment by alvarotrigo** [comment]
It is probably related with the use of `translate3d` and videos. They are not very good friends.
You probably can solve that by using the plugin option `css3:false`. Let me know if that's the case.
