### ISSUE TITLE
Small inconsistency between Sass and CSS: slide nav dots are missing margin

### ISSUE THREAD

**Issue by dylanfisher** [alvarotrigo/fullPage.js#1113]
Looks like there's an inconsistency in the Sass and CSS files, which prevents the slide dots from displaying correctly when using the Sass stylesheet.

`.fp-slidesNav ul li` in the CSS file has `margin: 7px;` set in it. This is missing in the Sass file, which makes it look like the slide dots are piled on top of each other. 

https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.css#L129

**Comment by alvarotrigo** [comment]
Thanks, looking at it!

**Comment by alvarotrigo** [comment]
@dylanfisher try again. I've updated the file.
