### ISSUE TITLE
SetAllowScrolling with more than 2 parameters

### ISSUE THREAD

**Issue by terrymacdonald** [alvarotrigo/fullPage.js#1114]
When trying to restrict movement left and right for the slides in the top section of a multi-section page, I found some bugs in your very awesome plugin. I've tried to document my fixes in the hope it will help you fix them. 

1. setAllowScrolling didn't use the first supplied direction

I found that when supplying two directions to SetAllowScrolling only the second one was being applied. So I replaced the code with the following:

        FP.setAllowScrolling = function (value, directions){
            if(typeof directions != 'undefined'){
                // CHANGED THIS SECTION 
                if (directions.indexOf("up")>=0) setIsScrollable(value, "up");
                if (directions.indexOf("down")>=0) setIsScrollable(value, "down");
                if (directions.indexOf("left")>=0) setIsScrollable(value, "left");
                if (directions.indexOf("right")>=0) setIsScrollable(value, "right");
            }
            else if(value){
                FP.setMouseWheelScrolling(true);
                addTouchHandler();
            }else{
                FP.setMouseWheelScrolling(false);
                removeTouchHandler();
            }
        };

This worked with touch events but still didn't stop the page from scrolling using mouse or keyboard, so I did this:

2. modify function MouseWheelHandler

                    //to avoid double swipes...
                    if(isAccelerating){
                        //scrolling down?
                        if (delta < 0) {
                            if(isScrollAllowed.down){
                                scrolling('down', scrollable);
                            }
                        //scrolling up?
                        }else {
                            if(isScrollAllowed.up){
                                scrolling('up', scrollable);
                            }
                        }
                    }

This still didn't stop the page from scrolling using mouse or keyboard, so I did this:

3. Modify scrollPage:
		
Adding the following into function scrollPage blocks the movement as it is supposed to do:

            if(!v.isMovementUp && !isScrollAllowed.down){
                return;
            } else if(v.isMovementUp && !isScrollAllowed.up){
                return;
            }
			
This works fine and now my client is a happy person!

Cheers
Terry MacDonald

**Comment by alvarotrigo** [comment]
That's not a bug. 

> **setAllowScrolling(boolean, [directions])**
> Adds or remove the possibility of scrolling through sections by using the mouse wheel/trackpad or touch gestures (which is active by default).

Note the text:
>  by using the mouse wheel/trackpad or touch gestures

If you want to disable the arrow navigation, you should be using the function `setKeyboardScrolling()`.
Although this will disable it in general.

**Comment by alvarotrigo** [comment]
> I found that when supplying two directions to SetAllowScrolling only the second one was being applied. So I replaced the code with the following:

That's right. There's a bug there. The replace function is not working as I expected. 
Thanks for reporting it! 
Although this won't solve the keyboard navigation. Which as I said, its not a bug, but a matter of design.

**Comment by alvarotrigo** [comment]
> I found that when supplying two directions to SetAllowScrolling only the second one was being applied. So I replaced the code with the following:

That's right. There's a bug there. The replace function is not working as I expected. 
Thanks for reporting it! 
Although this won't solve the keyboard navigation. Which as I said, its not a bug, but a matter of design.

**Comment by terrymacdonald** [comment]
Yep, but this was broken for mouse and touch as well as keyboard.... I thought SetAllowScrolling stopped mouse and touch scrolling in the direction you wanted. Thats what it does for me now anyways. Works beautifully

Also, modifying scrollpage stopped scrolling at all in content with overflow-y turned on. So I removed that code and put it in mouseMoveHandler instead:

        function mouseMoveHandler(e){
            // moving up
            if(canScroll){
                if (e.pageY < oldPageY){
                    if (!isScrollAllowed.up){
                        return;
                    }
                    FP.moveSectionUp();

                // moving downw
                }else if(e.pageY > oldPageY){
                    if (!isScrollAllowed.down){
                        return;
                    }
                    FP.moveSectionDown();
                }
            }
            oldPageY = e.pageY;
        }

**Comment by alvarotrigo** [comment]
Solved in the latest version 2.6.3.
