### ISSUE TITLE
Custom hashes(SEO)

### ISSUE THREAD

**Issue by david43** [alvarotrigo/fullPage.js#1115]
Hi,
Can i change the hash to /#!/xxxxx
for example:
http://alvarotrigo.com/fullPage/examples/navigationV.html#secondPage
http://alvarotrigo.com/fullPage/examples/navigationV.html/#!/secondPage
Thanks you

**Comment by alvarotrigo** [comment]
No. Why would you do that?
fullPage.js uses `/` as a separator between sections (vertical) and slides (horizontal).

**Comment by david43** [comment]
It for google analytics and google search
Example site 
https://developers.google.com/webmasters/ajax-crawling/docs/getting-started
http://grooveshark.com/#!/genre/Electronic/156

**Comment by alvarotrigo** [comment]
@david43 there's a difference. 
fullPage.js isn't using AJAX, just anchors in the URL.

Google details that:

> This document outlines the steps that are necessary in order to make **your AJAX application crawlable.**
