### ISSUE TITLE
Change anchor URL for slides from /#firstSlide/anchor to /#anchor

### ISSUE THREAD

**Issue by magentapose** [alvarotrigo/fullPage.js#1116]
My fullPage instance consists only of slides, I don't have multiple sections.

For this reason, I want to change the anchor URLs from /#firstSlide/anchor to just /#anchor. The #anchor would be the anchor of the slide.

Is this currently possible, any modifications I can make to accomplish it?

Thanks

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide a way to do it. 
But, of course you can always modify the plugin to achieve it :)

If you need a customization, [contact me](http://alvarotrigo.com/#contact-page) and we can talk about it.
