### ISSUE TITLE
Table scroll issue in touch devices

### ISSUE THREAD

**Issue by dipalshah87** [alvarotrigo/fullPage.js#1117]
Hi,

I have used this plugin in my website along with bootstrap css & js. I am using responsive table in my page. When I try to scroll page on hover of table, page doesn't scroll. Also table is not horizontally scrolling in touch based devices.

**Comment by alvarotrigo** [comment]
Impossible to guess what's going on if you dont provide more data, a way to reproduce your problem or a link to your site.
