### ISSUE TITLE
responsive Table on touch dont scroll inside fullpage section

### ISSUE THREAD

**Issue by raghu556** [alvarotrigo/fullPage.js#1118]
Hi,

I am using fullpage.js and bootstrap in my site. In section, i am using table having container class as table-responsive. If table is longer in width, horizontal scroll appears which is proper. 
When i view the page in touch phones especially ipads and iphones. Horizontal scroll of table doesn't work. 
I tried modifying the options of fullpage.js as below:
normalScrollElements: '.table-responsive',
scrollOverflow: false,
touchSensitivity: 5,
normalScrollElementTouchThreshold: 7,

Please let me know how can we resolve this issue.

For reference:
```javascript
$('#fullpage').fullpage({
    navigation: true,
    navigationPosition: 'left',
    navigationTooltips: [],
    scrollOverflow: true,
    responsive: 0,
    easingcss3: '',
    afterRender: function () {
        var textAnchorsList = $("#fp-nav ul li a"),
            anchorTexts = ["Leveraging the Legacy", "Stakeholder Collaboration", "On Demand Data & Services", "Digital Enterprise Security", "Testing Services", "Digital Analytics", "Cloud Enablement"];
        for (var i = 0; i < textAnchorsList.length; i++) {
            $(textAnchorsList[i]).append("<div class='left-nav-text'>" + anchorTexts[i] + "</div>");
        }
        var serviceParamValue = getParameterByName('serviceParamValue');
        $("#fp-nav").addClass("scroll-section1");
        $("#fp-nav li").eq(serviceParamValue).find('a').trigger('click');
    },
    onLeave: function (index, nextIndex, direction) {
        $("#fp-nav").removeAttr('class');
        $("#fp-nav").addClass("left scroll-section" + nextIndex);
        var fpSectioncount = $("#fullpage .fp-section").size();
        if (fpSectioncount == nextIndex) {
            $("#footer").addClass('fixed-footer');
        } else {
            $("#footer").removeClass('fixed-footer');
        }
    }
});
```

**Comment by alvarotrigo** [comment]
Please provide a reproduction of your problem.

**Comment by raghu556** [comment]
Hey thanks for replying, can you please share you email id, i can share the zip with you.

**Comment by alvarotrigo** [comment]
Sorry, I don't accept zips. Just a link to the reproduction. You can do it in a website, or rather isolate the problem and do it in jsfiddle or codepen.

**Comment by raghu556** [comment]
Hi,

Please find the files here : https://github.com/raghu556/fullpage-issue

Regards,
Raghavendra

On Tue, Mar 31, 2015 at 5:22 PM, Álvaro <notifications@github.com> wrote:

> Please provide a reproduction of your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1118#issuecomment-88057326>
> .
>



-- 
Regards,
*Raghavendra N. Nayak*
"If you judge people, you have no time to love them."
 -- *Mother Teresa*

**Comment by raghu556** [comment]
Ok no issues, you can find the files here: https://github.com/raghu556/fullpage-issue

**Comment by raghu556** [comment]
Hi alvarotrigo ,

Any update on this issue. We have made the site Live. You can reproduce the issue.
https://etouch.net/services/index.html
Keep mover over on table and try to scroll. It doesn't scroll.

**Comment by alvarotrigo** [comment]
Because in [your own modification of fullPage.js](https://etouch.net/js/jquery.fullPage.js) you are using `normalScrollElements: '.table-responsive',` in the plugin options.

Remove it and everything will be ok.
