### ISSUE TITLE
Jquery mobile Slider

### ISSUE THREAD

**Issue by marshall200** [alvarotrigo/fullPage.js#1119]
Hello thank you for your plugin, Im testing it but the jquery mobile slider doesnt work, could you please tell where do i have to move in order to work

https://demos.jquerymobile.com/1.4.5/slider/

Whe i try to slide the elment it scroll the slide to left

**Comment by alvarotrigo** [comment]
Might be related with this other topic: https://github.com/alvarotrigo/fullPage.js/issues/1088

Have you tried using `normalScrollElements` for that slider element? `normalScrollElements: '.ui-slider'` ??

**Comment by alvarotrigo** [comment]
I believe it has been solved in the latest version 2.6.3.
Let me know if it works well for you now.
