### ISSUE TITLE
Single/One Slide not supported

### ISSUE THREAD

**Issue by edwinlimlx** [alvarotrigo/fullPage.js#1120]
Hi, 
As my slides content are CMS drvien, there will be scenario of multiple slides and single slides when page is loaded. However I encounter problem when there's only one slide present. 

Is there a way I can disable initializing the slides if there's only 1 slide?

![image](https://cloud.githubusercontent.com/assets/514865/6956685/bac5cd50-d924-11e4-8c03-78878d662a52.png)

![image](https://cloud.githubusercontent.com/assets/514865/6956674/8ee5037c-d924-11e4-8a83-21f1d27f3a7c.png)

Thanks, 
Edwin

**Comment by alvarotrigo** [comment]
Yep, fullPage.js was not suppose to allow that structure with only one single slide.
Nevertheless, I'll solve it for the next release as it is not the first time I'm faced with the same question. 

I'll release it today.

**Comment by alvarotrigo** [comment]
Solved in the latest version 2.6.3.

**Comment by edwinlimlx** [comment]
Thanks! Dude!

**Comment by drawcard** [comment]
Awesome stuff, this solved a similar issue I was having with a CMS setup where there may only be 1 slide at a given time.
