### ISSUE TITLE
Slide Anchor

### ISSUE THREAD

**Issue by goldspy98** [alvarotrigo/fullPage.js#1121]
Hi, I am not sure if this is a bug, in a scenario with 2 sections, 2 slides in the first section and 3 slides in the second section, using anchors, we could navigate to second section, second slide using as url ".../index.html#second/1", after the slide load the url will change to ".../index.html#second/3" since the first section has 2 slides, now if the user bookmark the page it will save ".../index.html#second/3" and if the user try to open it the page will show the first slide of the second section. It's possible to notice in the methods.html example file. Not sure if it's important but I am using Google Chrome as browser.

**Comment by alvarotrigo** [comment]
That's indeed a bug. A recently added one. Thanks for reporting it! I'll solve it for today!

**Comment by alvarotrigo** [comment]
Solved in the latest version 2.6.3.
