### ISSUE TITLE
normalScrollElements: how to set up ?

### ISSUE THREAD

**Issue by karlienfabre** [alvarotrigo/fullPage.js#1122]
Hi! 

First of all, nice plugin. 

I'm setting up a website with it, but I'm struggling with the option 'normalScrollElements' .
I've setup the option, but instead of scrolling the content inside the div nothing is happening when I scroll. 
So, I'm doing it wrong but I can't find the issue. 

It would be nice if you can take a small look at it. I've put it online on a staging url: http://swiped.be/staging/#page-blog/9

Thanks in advance!

Kr, 
Karlien

**Comment by alvarotrigo** [comment]
> normalScrollElements: (default null) If you want to avoid the auto scroll when scrolling over some elements, this is the option you need to use. (useful for maps, scrolling divs etc.) It requires a string with the jQuery selectors for those elements. (For example: normalScrollElements: '#element1, .element2')

The aim of using it is to prevent the plugin to scroll up or down when scrolling over the element to which the option is applied. 
Usually used to deal with elements with scroll bar, google maps and so on.

**Comment by karlienfabre** [comment]
OK. Pretty stupid question. Fixed it now by using the normalScrollElements and put css to that div 'overflow: auto' and some fixed height. 

Sorry for wasting your time
