### ISSUE TITLE
afterSlideLoad Event Called on Sections Change

### ISSUE THREAD

**Issue by goldspy98** [alvarotrigo/fullPage.js#1124]
Hi, I am experiencing a problem with afterSlideLoad event, I am not sure if it's a bug or if it's meant to be like that, anyway, the question is when we move to a new section ,the event afterSlideLoad will be called even though the slide of section did not change, although it take a while before the event be called.

There is also another issue, using Methods to navigate into the sections and slides, in my case I am making a custom menu using Methods, the user may press like one button and quickly press another, this will call the methods and move to the right slide however, if the user press the other button before the new latest slide has loaded the page goes to the new selection, which right, the problem is that the afterSlideLoad event will be called for the page which was not even loaded since the user quickly changed it.

I may ask a question too, is there a way to change paddingTop from section 1 to section 2?

**Comment by alvarotrigo** [comment]
> when we move to a new section ,the event afterSlideLoad will be called even though the slide of section did not change

I can not reproduce it [here](http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage).
If you can, then you should provide a way to reproduce it or the necessary initialization or markup for it.

> There is also another issue, using Methods to navigate into the sections and slides, in my case I am making a custom menu using Methods, the user may press like one button and quickly press another, this will call the methods and move to the right slide however, if the user press the other button before the new latest slide has loaded the page goes to the new selection, which right, the problem is that the afterSlideLoad event will be called for the page which was not even loaded since the user quickly changed it.

Provide a way to reproduce it please.

> I may ask a question too, is there a way to change paddingTop from section 1 to section 2?

Overriding the value by using CSS and `!important`.

**Comment by goldspy98** [comment]
I tried to reproduce the issue in the example you provided (http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage) and I noticed the problem is about the navigation menu, if use the mouse wheel to scroll you will get onLeave and afterLoad events called however if you use the navigation menu (press Second Slide since the other don't have slides) you will get onLeave, afterLoad and afterSlideLoad events called, let me know if you understood what I mean, I may provide an image if you need.

**Comment by alvarotrigo** [comment]
> I noticed the problem is about the navigation menu, if use the mouse wheel to scroll you will get onLeave and afterLoad events called however if you use the navigation menu (press Second Slide since the other don't have slides) you will get onLeave, afterLoad and afterSlideLoad events called,

It doesn't happen anymore. You can check it again in [the callbacks demo page](http://alvarotrigo.com/fullPage/examples/callbacks.html). 

I'll close the issue.
