### ISSUE TITLE
Problem on Click in dots navigation Menu

### ISSUE THREAD

**Issue by N0WayH0me** [alvarotrigo/fullPage.js#1126]
Hi.

I made some minor change in the dots navigation menu.
I remove 
    opacity: 0;
    width: 0;
from #fp-nav ul li .fp-tooltip in css to have text allways display.

I add a link on this text.

But when i click those link ( simple anchor ) it allways goes to section 2 .. 

i dont know why .
A mistake on my mod ?
A thing in your script that overide those link ?

Here the page

http://jsfiddle.net/N0WayH0me/tk202yup/

Could you help me ?

Thanks a lot

**Comment by N0WayH0me** [comment]
Oh damned i just notice another problem.

Anchor dont work with 
$(window).load(function(){
used to hide menu in first page

and hide menu dont work with
$(document).ready(function() {
used with anchor .. :(

**Comment by alvarotrigo** [comment]
Sorry but the plugin doesn't provide such an option.
The option navigationTooltips only admits plane text and it is not ready to work with HTML links.

If you really need it, [let me know](http://alvarotrigo.com/#contact-page) and I can customise the plugin for you.
