### ISSUE TITLE
Fulpage.js on WordPress

### ISSUE THREAD

**Issue by Tharaka-karunarathne** [alvarotrigo/fullPage.js#1127]
Hi, I'am using fullpage.js pluging and I have integrated it's javascript version to my WordPress site. it was working well with desktop screens but not in mobiles. touch is not working and also links doesn't direct. So i tried to get jQuery version but i'am stuck as WordPress cannot read "$" sign. reference. (http://www.ericmmartin.com/5-tips-for-using-jquery-with-wordpress/) please read 5th tip. I'am sure you know the issue better.
can you please give me quick solution? I need to deliver my project within 2 days.

**Comment by alvarotrigo** [comment]
That's a problem for wordpress, not for fullPage.js.
