### ISSUE TITLE
Question : how to achieve scrolling inside div

### ISSUE THREAD

**Issue by MihaiCraciun** [alvarotrigo/fullPage.js#1129]
Hello Alvaro,

First off, kudos for the plugin! It's awesome !
How would you suggest achieving scrolling on a div that is inside a slide ?

I have a layout that is split in two halfs : one has an image and another has text.
![image](https://cloud.githubusercontent.com/assets/7666090/7023935/e9e7e642-dd41-11e4-879b-b088adf61e62.png)
The text can vary in length but the image should always be visible fully. 

What i've done so far but it's buggy : i've set a special class for the divs that have text, added that class to normalScrollElements option and i've applied the slimscroll plugin to that class. 
Also i've added custom js, which listens to the slimscroll event to detect when the scroll bar has reached top or bottom, and if the user is still scrolling, fire the coresponding $.fn.fullpage.moveSectionUp or Down.

The issue is that because I have multiple slides being generated and some content areas are shorter than the height set for the scrolling to appear, when i mouse over the content area and try to scroll, nothing happens. The expected behaviour would be to advance to the next / previous slide, depending on scroll direction.

Any suggestions ?

**Comment by MihaiCraciun** [comment]
also, even with the "hack" that i did to trigger next/prev slide, it's still buggy - continuing to scroll has no effect when landing on the next slide. It only regains functionality if i move the mouse slightly.

You can check all of the above here http://www.modernwings.com/swan-aeroplane/

**Comment by alvarotrigo** [comment]
> What i've done so far but it's buggy : i've set a special class for the divs that have text, added that class to normalScrollElements option and i've applied the slimscroll plugin to that class. 
Also i've added custom js, which listens to the slimscroll event to detect when the scroll bar has reached top or bottom, and if the user is still scrolling, fire the coresponding $.fn.fullpage.moveSectionUp or Down.

That's the way to do it. 
Now I guess you have to detect if there's a scroll bar or not, and if not, scroll up or down a section.

**Comment by MihaiCraciun** [comment]
Looking through the code of slimscroll i noticed that there are some prevent defaults on the mouse over event. That coupled with fullpagejs and custom code will be a nightmare to figure out.
Also as i mentioned in the second comment, when scrolling is triggered by movesectionup i noticed that if i don't move the mouse, nothing happens.
So I guess what I need to detect is not so easy as checking for the scrollbar (which by the way is always present in the DOM but is not shown if it's height is equal to the text containing div's height)

**Comment by alvarotrigo** [comment]
> i noticed that if i don't move the mouse, nothing happens.

Use the slimScroll version included in fullPage.js.

In any case, this question doesn't regard any issue with fullPage.js but a specific problem of your own. I would recommend you to ask in other place. 

Fullpage.js provides a way to create a scrolling bar in any slide or section by using the option `scrollOverflow:true` as you can see [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by Pavel-Kazakov** [comment]
Your example doesn't work 

> see in this example.

**Comment by alvarotrigo** [comment]
@Pavel-Kazakov that has been solved in the dev branch as stated here https://github.com/alvarotrigo/fullPage.js/issues/2353. 
It is only the 1st section which doesn't scroll at the moment, use the keyboard to scroll to the next and be able to see it working.
