### ISSUE TITLE
Issue with scrollOverflow and firefox/chrome

### ISSUE THREAD

**Issue by MagicMicky** [alvarotrigo/fullPage.js#1130]
I'm having an issue with fullpage.js when using the scrollOverflow feature.
On some browsers, when I scroll from a section to another, and don't move the mouse, it doesn't want to scroll anymore. I have to first move the mouse and then scroll again. That can get really anoying for our users !
You can see the error here : [http://etud.insa-toulouse.fr/~goubin/DaVinciRoad/](http://etud.insa-toulouse.fr/~goubin/DaVinciRoad/#day-1) between day 1 and 2
It has been tested on firefox (Windows/Ubuntu/Mac OS) and chrome (Mac OS but it works on Ubuntu).

**Comment by alvarotrigo** [comment]
Make sure you are using the version of slimScroll library provided by fullPage.js and not the official one.

**Comment by MagicMicky** [comment]
Fixed ! Thanks a lot !
