### ISSUE TITLE
$.fn.fullpage.setScrollingSpeed(700) throw a error in console

### ISSUE THREAD

**Issue by SunLn** [alvarotrigo/fullPage.js#1131]
My fullpage plugin is v.2.6.3 . My code  is 

```
$(function(){
     $.fn.fullpage.setScrollingSpeed(700)
     $('#element').fullpage({
        // init code here
     })
})
```
or 

```
$.fn.fullpage.setScrollingSpeed(700)
$(function(){
     $('#element').fullpage({
        // init code here
     })
})
```

Both not worked well ,throwed a error in console, said ' Uncaught TypeError: undefined is not a function'.
But removed this line '$.fn.fullpage.setScrollingSpeed(700)' , it worked normally.

typeof  $.fn.fullpage is 'function'
typeof  $.fn.fullpage.setScrollingSpeed is undefined 

How to make this work , I want to slow the speed when scrolling . 

Thanks very much .

**Comment by alvarotrigo** [comment]
You can not call a function of a plugin that hasn't been initialized yet.
So you would need to place the call to the function after the initialization:

```javascript

$(function(){
     $('#element').fullpage({
        // init code here
     });

     $.fn.fullpage.setScrollingSpeed(700)
})
```

In any case, you can set the scrolling speed by using the option `scrollingSpeed` rather than using a function for it.

     $('#element').fullpage({
        scrollingSpeed: 1500
     });

**Comment by SunLn** [comment]
Thanks a lot . I get it.
