### ISSUE TITLE
Scrolling up and down, but change mousewheel direction inside slide to left and right

### ISSUE THREAD

**Issue by mibisc** [alvarotrigo/fullPage.js#1134]
Hello, I'm using your plugin and I have a question about it. Is there a possibility to change the direction of scrolling in one special slide. So if I'm scrolling down on this special slide, it should scroll inside!! the slide to the right, and if I'm scrolling up, it should scroll inside the slide to the left. 

Thanks a lot for your help.

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide such an option at the moment. 
If you really need it, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by intech** [comment]
Very important!

**Comment by locksoft** [comment]
Thanks for your answer, Alvaro (and sorry for duplicate issue).

**Comment by locksoft** [comment]
I think I've came to a partial solution. it's not great code as I'm not a programmer and it requires a bit of personalization but it works.

you can see a demo here: http://lemonskin.net/fullPage_horizontal/apps/test.html

You need to declare some variables inside your javascript section:

```
var P2_max = 4;	// number of slides in page 2
var P3_max = 6;	// number of slides in page 2
var P2_index = 0;  var P3_index = 0;	// needed for remember last position
```

Paste this code inside the call function:

```
onLeave: function (anchorLink, index, slideIndex, direction) {
//console.log('page: index='+index+' slideIndex='+slideIndex+' S2_index='+S2_index+' S3_index='+S3_index+' last_S='+last_S);

        if (slideIndex == 'down') {
        	
        	// 2nd page
        	if (index == 3) {
        		if (P2_index < (P2_max - 1)) {
        			$.fn.fullpage.moveSlideRight();
        			return false;
        		}
        	}

        	// 3nd page
        	if (index == 4) {
        		if (P3_index < (P3_max - 1)) {
        			$.fn.fullpage.moveSlideRight();
        			return false;
        		}
        	}

        } else { // up
        	
        	// 2nd page
        	if ((index == 1) && (slideIndex == 'up')) {
        		if (P2_index > 0) {
        			$.fn.fullpage.moveSlideLeft();
        			return false;
        		}

        	}

        	// 3nd page
        	if ((index == 2) && (slideIndex == 'up')) {
        		if (P3_index > 0) {
        			$.fn.fullpage.moveSlideLeft();
        			return false;
        		}

        	}
        }
    },
    afterSlideLoad: function  (anchorLink, index, slideAnchor, slideIndex) {
    	//console.log('slide: index='+index+' slideIndex='+slideIndex);
        if (index == 2) { P2_index = slideIndex; }
        if (index == 3) { P3_index = slideIndex; }
    }
```

The only problem with this solution is that sidedots navigation doesn't work, as I can't find a way to distinguish the change of page between arrows/mousewheel and clicks. My function can only calcolate previous and next page/slide. It can't make jumps.

Maybe Alvaro could have an idea about it.

**Comment by alvarotrigo** [comment]
This is now possible thanks to the fullpage.js extension [Scroll Horizontally](http://alvarotrigo.com/fullPage/extensions/scrollHorizontally.html).
