### ISSUE TITLE
normalScroll not working for Chrome, slow on Firefox, good on Safari

### ISSUE THREAD

**Issue by lentilz** [alvarotrigo/fullPage.js#1135]
Hi,
I have read through some of the scrollOverflow/normalScroll related issues, and dont think Ive come across this case. Within each fullpage section i have an overlay section set to 100% of the section. The normal scrolling is set for the overlay div and works fine on safari, slows sluggishly on firefox, and doesnt scroll at all on Chrome. The scroll bars dont show up either.

Here are my settings:
        anchors: panels,
        fixedElements: '#fixed-nav-bar',
        paddingTop: '60px',
        responsive: 1030,
        scrollOverflow: true,
        normalScrollElements: '.overlay-panel',
        scrollbar: true,
        verticalCentered: false,
        navigation: true,

**Comment by alvarotrigo** [comment]
If you want to create the scroll bar, then you should use `scrollOverflow:true` and nothing else. 
`normalScrollElements` has nothing to do here. That's for another purpose.

**Comment by lentilz** [comment]
Thanks. In my case the reason it wasnt working as intended was because I needed scrollOVerflow off and kept normalscroll and scrollbars.
