### ISSUE TITLE
on resize error

### ISSUE THREAD

**Issue by waterschaats** [alvarotrigo/fullPage.js#1136]
On risize I get the following error: Uncaught TypeError: Cannot read property 'left' of undefined
Anybody an idea?

**Comment by alvarotrigo** [comment]
Add a link to reproduce your issue and make sure you use the latest version.
Until a way to reproduce it is provided, I'll close the issue.

**Comment by waterschaats** [comment]
I was a version behind, sorry, that solved it! Great plugin!
