### ISSUE TITLE
onSlideLeave not working

### ISSUE THREAD

**Issue by ecurtis** [alvarotrigo/fullPage.js#1137]
I noticed when trying to implement an action on leaving a slide that your onSlideLeave function was not working. I stripped everything else out of the project and only tried logging out the slideIndex with no luck.

For an example it appears your recent demo displays the same behavior:
http://alvarotrigo.com/fullPage/examples/callbacks.html

One odd thing I noticed in your example is that it will occasionally work on the first slide change after load.

PS. Thank you for the library, it is very impressive.

**Comment by alvarotrigo** [comment]
Its working for me. You can also see the printed information in the javascript console.
![onleave](https://cloud.githubusercontent.com/assets/1706326/7069821/e0a300ac-ded2-11e4-878f-abb1cbdd7131.PNG)

Which browser are you using?

**Comment by ecurtis** [comment]
Strange it is not working here. Using Chrome 41
![image](https://cloud.githubusercontent.com/assets/494286/7069866/131c44e6-de90-11e4-97fe-89df9c19f0a2.png)

**Comment by alvarotrigo** [comment]
It only fires when going from one slide to another. Remember that slides are the horizontal ones, the other ones are refereed as "sections" by fullPage.js as detailed in the docs.

**Comment by ecurtis** [comment]
Ah, I was confusing sections and slides - apologies and thank you for the clarification.

**Comment by cupcakedream** [comment]
I'm not able to get the "onLeave" event to fire when scrolling through sections - am I missing something?

**Comment by alvarotrigo** [comment]
@cupcakedream definitely you are. It works as expected as you can see in the [demo online](http://alvarotrigo.com/fullPage/examples/callbacks.html) and in the callbacks.html file included with the plugin examples.

**Comment by cupcakedream** [comment]
Yeah I do see it's working there.. Is there anything configuration-wise
that would interfere with that callback?

**Comment by alvarotrigo** [comment]
I don't know, but its not a problem with the plugin. Seems to be a problem with your own code.
