### ISSUE TITLE
A problem occurs in my site when a keyboard pops up on mobile.

### ISSUE THREAD

**Issue by taeguk** [alvarotrigo/fullPage.js#1138]
A problem occurs in my homepage when keyboard pops up on mobile.

![image](https://cloud.githubusercontent.com/assets/9107889/7083524/eda27244-df9d-11e4-849d-5bab679d5952.png)
This is my homepage.

![image](https://cloud.githubusercontent.com/assets/9107889/7083528/fdcbcc56-df9d-11e4-9deb-0f46741164ce.png)
when i touch input tag, keyboard pops up.

![image](https://cloud.githubusercontent.com/assets/9107889/7083529/0abbcf38-df9e-11e4-9f92-0d2758efa1eb.png)
And after when i type something, browser focibly scroll my page.

![image](https://cloud.githubusercontent.com/assets/9107889/7083532/13cfc340-df9e-11e4-889e-6254ad0f2c7b.png)
And after a keyboard close, the homepage don't go back to original.

![image](https://cloud.githubusercontent.com/assets/9107889/7083782/cead9abe-dfa0-11e4-92ae-42adaeae29f7.png)
This is partitial source.

I want to know the problem and solution.

p.s. sorry to my foolish english skill.

**Comment by alvarotrigo** [comment]
It seems that you are talking about [this same issue](https://github.com/alvarotrigo/fullPage.js/issues/145).

Please, continue the discussion there. I'll close this one to prevent duplicates.

Just to let you know, no solution to it has yet been found.
