### ISSUE TITLE
Navigation not working when first slide is located outside of fixed width container.

### ISSUE THREAD

**Issue by kccarter1** [alvarotrigo/fullPage.js#1139]
My page is constructed like so:
* Main Container `<div id="fullpage">`
     * Section 1 (full width of screen)
        - Fixed Width Container
            - Section 2
            - Section 3
            - etc....

In this scenario, my navigation does work except for section 1. I cannot navigate back to section 1 from other sections.

When I construct the page like this, the navigation works perfectly:
* Main Container `<div id="fullpage">`
  * Fixed Width Container
         - Section 1
         - Section 2
         - Section 3
         - etc....

Is there a way to get the first scenario to work, with section 1 outside of the fixed width container? I need my first section to be full-width. Thank you so much for you help!

**Comment by alvarotrigo** [comment]
That's mainly because you are not following the required structure which have to look like this:

```html
<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">
          <div class="slide"> Slide 1 </div>
          <div class="slide"> Slide 2 </div>
          <div class="slide"> Slide 3 </div>
          <div class="slide"> Slide 4 </div>
    </div>
    <div class="section">Some section</div>
</div>
````

Your *fixed width container* shouldn't be there.
