### ISSUE TITLE
responsive option causes horizontal scrolling

### ISSUE THREAD

**Issue by leavingpictures** [alvarotrigo/fullPage.js#1140]
Hey first of all really great script. I have an issue with the responsive option. Since I want to get a normal kind of scrolling at 780px or less i used that. But if I'm using firefox on mobile or even if I go to 780px width in the firefox desktop it starts scrolling horizontal. Because of that problem I think the horizontal swipe isn't working there also. There is a small gap on the right side I don't know where it comes from. I tried everything an I'm hoping it's not a simple css kind of thing I just didn't get so far. Do you have any idea where this comes from? I'm kind of desperate right know.

Link: nemuscycles.de/website

Thanks for your help!!

**Comment by alvarotrigo** [comment]
Probably a CSS problem. Not related with fullPage.js at all.
As you can see, it the [demo page](http://alvarotrigo.com/fullPage/examples/responsive.html) works as expected.
