### ISSUE TITLE
Disable scrolling when Bootstrap modal opened

### ISSUE THREAD

**Issue by rubaff** [alvarotrigo/fullPage.js#1142]
Is it possible to disable scrolling of sections when a Bootstrap modal is opened? Bootstrap will add the class .modal-open to the body. Maybe we can work with that?

Thanks, r!

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements` for it.

**Comment by rubaff** [comment]
normalScrollElements: '.modal'

...did the job! Thanks for the quick replay!

**Comment by areddyprasad** [comment]
Excellent **@alvarotrigo** ... It works like a charm...

**Comment by Giegling** [comment]
It works like a charm when scrolling, but when modal is open and I can still scroll with arrow down and up buttons.

**Comment by raphaelrpais** [comment]
For the record, works fine with MDL's dialog also.

**Comment by Giovancruz** [comment]
Maybe this will solve:
`$('.modal').on('show.bs.modal', function () {
	$("body").css('overflow', 'hidden');
	$('.modal .modal-body').css('overflow-y', 'auto');
	$('.modal .modal-body').css('max-height', $(window).height() * 0.7);
}).on("hidden", function () {
		$("body").css('overflow', 'auto');
});`

**Comment by pascarel** [comment]
it's not working on mobile devices, please can you help me !!!

**Comment by NimbusSoftware** [comment]
That worked for me

**Comment by imbalar** [comment]
> Maybe this will solve:
> 
> ```js
> $('.modal').on('show.bs.modal', function () {
> 	$("body").css('overflow', 'hidden');
> }).on("hidden", function () {
>         $("body").css('overflow', 'auto');
> });
> ```

but all content jump when open model.
