### ISSUE TITLE
Slimscroll jump issue with Ajax call

### ISSUE THREAD

**Issue by sharpe89** [alvarotrigo/fullPage.js#1143]
Hi there

Absolutely love your plugin but i seem to have an issue with how slimscroll.js fetches the original scroll point when an ajax call has been triggered. 

Link: http://nfp.sharpeart.com/#how-we-think/blog

You'll see that when you scroll down, slimscroll is working flawlessly, however when I click the load more button, the content loads but when i start scrolling, the page jumps to some point further down and the original position of the user is lost (if you get what i mean).

I tried reinitializing slimscroll.js but that didn't give me any luck.

Any help would be much appreciated. :+1: 

Thanks!
Stephen

**Comment by alvarotrigo** [comment]
Use the `reBuild` method provided by fullPage.js.

**Comment by sharpe89** [comment]
Thanks for the quick reply. :)

Apologies, forgot to mention I've used rebuild - $.fn.fullpage.reBuild(); before and nothing has changed. :( Its currently being used with my ajaxComplete function and no change as of yet. 

Thanks!
Stephen

**Comment by alvarotrigo** [comment]
I dont know where your "load more" button is so I can not test it. But it should work as expected.

**Comment by sharpe89** [comment]
Hi alvarotrigo

Just solved it there - slimscroll.js had its 'start: bottom' as default, so when user clicks load more ajax call, it dragged the user down to the bottom of the content newly loaded content.

So i just rebuilt with ajaxComplete and used:

<code>$(".fp-scrollable").slimScroll({start: 'top'})</code>

no need for fullPage.js rebuild function. :)
