### ISSUE TITLE
animonscroll.js not working in slide whith scrolling

### ISSUE THREAD

**Issue by pabloni** [alvarotrigo/fullPage.js#1145]
Hi, 
I'm trying to implement a plugin to animate a grid of items that appear as you scroll down (opacity change 0 to 1). Try to initialize the function within afterRender: and applying normalScrollElements: in this section but not working.
Any ideas?
Thank you in advance!

P.S: the link to plugin is 
https://github.com/codrops/GridLoadingEffects

**Comment by alvarotrigo** [comment]
Read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

> **Short answer:** use the scrollBar:true option for fullPage.js or autoScrolling:false if you don't want to use the auto-scrolling feature.

> **Explanation:** Parallax, **as well as many other plugins which depends on the scrolling of the site**, listens the scrollTop property of javascript. fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.
