### ISSUE TITLE
Remove SlimScroll for mobile only

### ISSUE THREAD

**Issue by lentilz** [alvarotrigo/fullPage.js#1146]
I am using slimscroll for tablet and up for overflow content and have the plugin responsive option set to 640. All is working beautifully except on mobile, the slimscroll is still effective on overflow sections rather than being normal scroll causing weird/unnecessary scrolling. Is there a way to turn off slimscroll at the given breakpoint when the site scrolls like a normal page?

Thanks

**Comment by alvarotrigo** [comment]
Nop. Related with [this issue](https://github.com/alvarotrigo/fullPage.js/issues/553).

I would encourage you to override the section height like suggested in [this post](https://github.com/alvarotrigo/fullPage.js/issues/1044).
