### ISSUE TITLE
afterload on first section

### ISSUE THREAD

**Issue by ivanturtu** [alvarotrigo/fullPage.js#1147]
is there a way to fire afterLoad() on loading of the first section? it seams to work only if index = 2 or higher...

**Comment by alvarotrigo** [comment]
You should be using `afterRender`. But I'll take a look in the next weeks.

**Comment by ivanturtu** [comment]
Hi Alvaro, thanks for quick response... I'm working on a project were I want to do some animation with velocity.js only on fisrtload of the site www.domain.com and only if i'm on first section... I have been plaing with afterRender and AfterLoad but no way... :-( do you have sugestions???

**Comment by alvarotrigo** [comment]
It should work in you place it in the `afterRender` and the 1st section is the visible one on page load.

Make sure you are using velocity correctly.

**Comment by ivanturtu** [comment]
If I use <code>afterRender</code> the animation is fired also if i'm on section 2 or other but maybe I'm doing sometingh wrong... anyway I did a workaround using the hash and it seams to do what i want... i'll check to see if you find something next week

**Comment by markidm** [comment]
Hi, I want to detect which section is active when the page loads (in case of using a hash to go directly to a certain section), but `afterRender` does not have `index` as an available parameter. Is there any solution, or shall I wait until you've implemented `afterLoad` on page load?

**Comment by alvarotrigo** [comment]
> I want to detect which section is active when the page loads (in case of using a hash to go directly to a certain section)

You don't need to. fullPage.js does it automatically when using anchors as you can see on the [demo page](http://alvarotrigo.com/fullPage/).
If you dont want the scrolling animation, then use the option `animateAnchor:false` (which works for the vertical animation).

Keep in mind as well that the active section or slide will have the class `active`. You can also check the class `fp-viewing-x-x` added to the body of the page.

**Comment by markidm** [comment]
Thanks Alvaro, 

 

I’ve got the data-menuanchor attributes in place now, but they don’t seem to work. You can see my example here: http://idmdevsites.co.uk/idg-mobile-digest/responsivepdf/the-growing-importance-of-wifi-in-hotels/#page6

 

What am I doing wrong?

 

Cheers

 

Mark

**Comment by alvarotrigo** [comment]
@markidm not a matter of fullPage.js. Your javascript console is full of errors.

**Comment by markidm** [comment]
Hi Alvaro, 

 

Sorry, there were a couple of errors due to debugging quickly after I sent the last note, I never expected such a quick reply! Kudos. I’ve cleaned them up now. The menu works, but the ‘active’ class is not applied to the menu elements… what am I doing wrong now?!

 

Cheers

 

Mark

**Comment by markidm** [comment]
Ah, you have to specify the selector. My bad. Sorry to waste your time, keep up the good work!

 

Cheers

 

Mark

**Comment by alvarotrigo** [comment]
The `afterLoad` callback will now be fired on page render in the latest release 2.6.5.

**Comment by ascottmccauley** [comment]
Awesome work. Love the enhancements. 

Similarly, I think it would also be smart to have the `afterSlideLoad` callback fire on all first slides as well.

**Comment by alvarotrigo** [comment]
Please create another issue for it.
