### ISSUE TITLE
Does not play nicely with Turbolinks

### ISSUE THREAD

**Issue by dja** [alvarotrigo/fullPage.js#115]
I have fullPage.js implemented on my homepage, but when a user navigates to a different page via link on the page, they cannot scroll on that new page unless the page is refreshed/reloaded.

I think it's a matter of Turbolinks being enabled on Rails 4. I want Turbolinks throughout the rest of the app, just not to coincide with fullPage.js.

Do you have anything you can change to optimize this? Or do you have a suggestion?

**Comment by yuriytickets** [comment]
This is the way I did turbolinks, fullpage and scrolloverflow works as expected with Rails4 / Turbolinks5
$(document).on('turbolinks:load', function(){
    if (typeof $.fn.fullpage.destroy == 'function') { 
        $.fn.fullpage.destroy('all');
    }
    $('#fullpage').fullpage({
        //your options
    });
    $.fn.fullpage.reBuild();
}
