### ISSUE TITLE
Achieve the sony asia website effect

### ISSUE THREAD

**Issue by landed1** [alvarotrigo/fullPage.js#1150]
If you check the sony asia site in the demos section there are backgrounds that seem masked and other items maybe that are using the value of the scroll. But I would be unsure where to start looking to emulate these great effects. So for example as a section is scrolled up a page behind is revealed.

**Comment by alvarotrigo** [comment]
That's not an issue for fullPage.js or this forum, but a matter of design and the designer skills.
I would recommend you to ask in other place such as http://stackoverflow.com/.

Also, use Chrome inspector and you will easily see how things are done.

**Comment by landed1** [comment]
Oh dear - sorry for breaking your strict rules. Was merely trying to get some help on the concept. I will just move along quietly.

**Comment by alvarotrigo** [comment]
@landed1 do not take it personally. I try to keep the forum as clear as possible for its purpose and lead other possible question to better places in which you will get more attention and more professional answers.

**Comment by landed1** [comment]
in fact due to some anomaly I cannot post to stack, am building reputation steadily but cannot post. I'm sorry that github didn't give you a forum labeled correctly (where I could post a question that others might also like to comment on) and that you need to put things in boxes. Go ahead and clean my dirty comments and questions away. Your avatar is a good fit for you.

**Comment by alvarotrigo** [comment]
Some people need learn how to to appreciate the free work of others... 
It's amazing...

**Comment by landed1** [comment]
but you in fact don't - more untruths and rhetoric.. I was sure you would bite yur avatar speaks more than the bible
ten cuidado
