### ISSUE TITLE
Why don't work scroll? If remove any tags or styles - worked.

### ISSUE THREAD

**Issue by npofopr** [alvarotrigo/fullPage.js#1151]
Why don't work scroll? And what could be the solution?
Example: http://shadow.perm.ru/test/obl/index.html

If I'm remove any tags or styles or commented 'scrollOverflow' it worked.
Chrome 42.0.2311.82 beta-m (64-bit)

**Comment by alvarotrigo** [comment]
Everything is working but, you are just using `autoScrolling: false,` if you want autoscrolling just turn it to true.

**Comment by npofopr** [comment]
Don't work scroll then height < 500px

**Comment by alvarotrigo** [comment]
Related with [this bug](https://github.com/alvarotrigo/fullPage.js/issues/553).
There's no solution for it.
