### ISSUE TITLE
Hide anchor links for slides only

### ISSUE THREAD

**Issue by MISTERGITADMIN** [alvarotrigo/fullPage.js#1152]
Hi, I would like to know if it is possible to keep the anchor for the sections, but hide the /1 /2 /3 etc. anchors for the slides?

Thank you in advance!

**Comment by alvarotrigo** [comment]
Nop.

**Comment by MISTERGITADMIN** [comment]
Could it be done through a customization or its completely not possible?

**Comment by alvarotrigo** [comment]
@MISTERGITADMIN yeah, it may. But then you probably won't be able to scroll back to the slide by providing the URL to somebody or by reloading the site. 
If you are interested just [contact me](http://alvarotrigo.com/#contact-page).
