### ISSUE TITLE
ScrollTo Possibility for anchor tags within Slide?

### ISSUE THREAD

**Issue by sharpe89** [alvarotrigo/fullPage.js#1153]
Hi Alvarotrigo

Still in development with a website and have a request. Looking to know is it possible to create an anchor tag within a scrolling slide and allow a user to be brought to that from a direct link through fullPage, for example:

I want the user to click 'Read Steven's Story' which has the following link:
http://nfp.sharpeart.com/#what-we-do/client-reviews/#steven

The link successfully brings me to the slide I want but doesn't scroll down to the desired part of the page. Is this a limitation with SlimScroll or would I need to add something more through jQuery?

Your help is always much appreciated!

Thanks!
Stephen

**Comment by alvarotrigo** [comment]
fullPage.js definitely doesn't provide a way to make use of the common anchors in the URL to scroll to any part of the site.

I'm not sure [if slimScroll provides anyway to access to a certain part of the scrollable area](https://github.com/rochal/jQuery-slimScroll/issues/98), but even in case it does, you would need to modify the plugin the parse the anchor string (#what-we-do/client-reviews/#steven) and get only the last bit (#steven).
And then very probably you'll have to calculate the position of the element containing that anchor inside the scrollable element to pass it to slimScroll.

You probably can do all of this by just forcing the scroll of the scrollable element and then manually moving its scrollbar to the right position.

**Comment by sharpe89** [comment]
Sounds like more effort than its worth if I'm honest. Will stick to content open up in a fixed div. Thanks for the help Alvarotigo. :+1:

**Comment by Forethinker** [comment]
I want this feature, but since slimScroll does not provide any access to its internal and the iScrollInstances is empty after the scroll has been enabled, I don't know if this is possible at all. The scrollBar does not add any HTML to work with. @alvarotrigo do you happen to how to manually move the scrollbar to the right position?

**Comment by alvarotrigo** [comment]
@sharpe89 interesting to see a reply more than a year after the question :D

**Comment by raza2022** [comment]
@sharpe89 i want to see how you achieve it. can you please
