### ISSUE TITLE
Prevent slides from scrolling when changing orientation on mobile

### ISSUE THREAD

**Issue by Stefanowitsch84** [alvarotrigo/fullPage.js#1154]
It seems to be a normal behaviour that the slides scroll up/down a little bit when you are viewing a page on a mobile device and change the orientation (due to resizing of section height I think). 

Is there a way to prevent the plugin from doing that?

The problem is: when you open a lightview image on the page an then change the orientation,  the page is scrolling up and the image is disappearing.

Edit: This is a workaround

I changed the code at Line 1244 into:

if (!isTouchDevice) {
	$(window).resize(resizeHandler);
}

**Comment by alvarotrigo** [comment]
Related with [this issue](https://github.com/alvarotrigo/fullPage.js/issues/64).
The plugin doesn't provide any solution for it yet.
