### ISSUE TITLE
onSlideLeave: show which arrow key has been pressed

### ISSUE THREAD

**Issue by sepastian** [alvarotrigo/fullPage.js#1155]
In `onSlideLeave(anchorLink, index, slideIndex, direction)`, the value of `direction` is the scrolling direction, not the key pressed by the user.

When on the first (left-most) slide and pressing 'left', the scrolling direction becomes 'right'; when on the first slide and pressing 'right', the scrolling direction becomes 'right'. Similarly, when on the last (right-most) slide and pressing 'right', the scrolling direction becomes 'left'; when on the last slide and pressing 'left', the scrolling direction becomes 'left'.

Thus, with the information currently provided in `onSlideLeave`, there is no way of telling which key the user has pressed. The `direction` can come about because the user pressed that key or because slides are "spooling back".

I am trying to update the content displayed in a navigation bar, based on slide transitions. With the information in `onSlideLeave`, this is not possible, because it is unknown whether the user really pressed 'right'; or the user actually pressed 'left' on the first slide and, because of that, slides are spooling back to the right.

The function signature should be changed to

`onSlideLeave(anchorLink, index, slideIndex, scrollingDirection, key)`

where `scrollingDirection` is the value of the current `direction` and `key` is either `'left'` or `'right'`, depending on which key the user pressed.

What do you think? Anyone else who would need that?

**Comment by alvarotrigo** [comment]
Why do you need to know if the user clicked on the right or in the left arrow? Could you elaborate it?
And, why don't you use instead the `afterSlideLoad` event to determine in which section your users are?

An easy way to solve your problem is just using the `slideIndex` to determine it. Just check if its 0 or if its the same as the number of slides in that section.

**Comment by alvarotrigo** [comment]
Closed until an answer/explanation is provided.

**Comment by sepastian** [comment]
Sorry for the wait. I have solved the problem using several slick sliders instead of a combination of slick and fullPage.

For an explanation of the problem, see my original posting. When using fullPage only, it is not necessary to know which key has been pressed, because fullPage will take care of showing the right slide. However, when fullPage needs to be combined with other controls, such as a slick slider, then it is necessary to know into which direction the user intends to move, i.e. which key has been pressed. FullPage does not provide that information because it will move into a single direction, independently of whether it is moving to the next slide or looping after reaching an edge.

Providing the intended direction of movement in fullPage does make sense in my opinion. Especially, when fullPage should be combined with other controls that need to change based on the direction of movement.

Still, I have found a better way of solving this, fullPage has not been the ideal candidate for what I am trying to do - I am fine with closing this issue.

Thanks!

**Comment by alvarotrigo** [comment]
In your case you wouldn't even have to deal with fullPage.js callbacks. You could have used a normal event linked to each arrow:

```javascript
        $('.fp-section').on('click touchstart', '.fp-controlArrow', function() {
            if ($(this).hasClass('.fp-prev')) {
                //left arrow clicked
            } else {
                //right arrow clicked
            }
        });
```
