### ISSUE TITLE
Problem with slides transition

### ISSUE THREAD

**Issue by fonfon6666** [alvarotrigo/fullPage.js#1156]
Hello,

Can you find my error ?

This is the link on my test website: http://www.g-incub.ch/test

The slides transition not work...

Thanks for your help

Nico

**Comment by alvarotrigo** [comment]
I'm afraid I can not provide you any support as you remove the credits of the plugin and I don't even know which version it is.

Remember the credits are not optional. You should add them or otherwise you are breaking the MIT license of the plugin.

**Comment by fonfon6666** [comment]
I am realy sorry.
I begin in coding and I am not still familiar these processes, I reinserted the license !
Really really sorry !!

**Comment by alvarotrigo** [comment]
You are not using the anchors at all and therefore you shouldn't be using anchors in your URL (#).

If you want to make use of them you have to use the option` anchors` and specify them in there. Then, your url would look like '#sectionAnchor/#slideAnchor`

You can see how fullPage.js is working as expected if you use the keyboard arrows to scroll horizontally.
