### ISSUE TITLE
jquery dependencies

### ISSUE THREAD

**Issue by BARTlab** [alvarotrigo/fullPage.js#1157]
Hi

fullpage.js version: 2.5.1 - have in dependencies "jquery": "latest"
But 2.5.2 and later have "jquery": "1.x" .... Why? This conflict with other bower package, who depend jquery 2.x

**Comment by alvarotrigo** [comment]
I guess the best option would be to use `>=1.6.0`.

I don't want to specify 2.x as some people might want compatibility with old browsers only supported by 1.X.

**Comment by BARTlab** [comment]
ok, fix bower.json :)

**Comment by alvarotrigo** [comment]
Let me know if it works well for you now.

**Comment by alvarotrigo** [comment]
Any comments?

**Comment by BARTlab** [comment]
Thank you, the problem is solved

**Comment by alvarotrigo** [comment]
Great.
