### ISSUE TITLE
Vertical Slides

### ISSUE THREAD

**Issue by caesai** [alvarotrigo/fullPage.js#1158]
So, please, tell me, how to make vertical scroll in slider? I mean something like this http://nicolas-bussiere.fr/ Sections scroll vertically, but when you go to the next slide, section scrolls horizontally, and while you on this slide you can scroll vertically and so on. I've read much your answers, i've done #200 and it works fine, but i don't understant what next.

**Comment by caesai** [comment]
I mean, i need a sections within slides.

**Comment by alvarotrigo** [comment]
The plugin doesn't provide the functionality I'm afraid.
It is not an easy task.

If you really need it, [contact me](http://alvarotrigo.com/#contact-page) for a customization.
