### ISSUE TITLE
hasClass active

### ISSUE THREAD

**Issue by Ourelius** [alvarotrigo/fullPage.js#1159]
Hello,

I need to request, which section in currently active.

if( $( '.anySection' ).hasClass( 'active' ) ){
do...
}

Thanks.

**Comment by Ourelius** [comment]
'onLeave': function(index, nextIndex, direction){
            if (index == 1 && direction == 'down'){
              $('.headlines').delay(5000).slideDown(4000);
            }
          }

works for me!

**Comment by alvarotrigo** [comment]
No idea what are you asking for.
