### ISSUE TITLE
Weird refresh to top on Chrome on form validation (gravity forms)

### ISSUE THREAD

**Issue by rzamoramty** [alvarotrigo/fullPage.js#1160]
Hello, I'm having this issue that I suspect has to do with a recent Chrome actualization, because when I installed the plugin on the site, this issue was non-existent.

This is the site -> http://www.bpublic.mx/

When you try to submit the form with invalid values and the form validation kicks in, the page does this weird refresh to top. This is only happening in Chrome resently as testing on Firefox could not replicate the issue.

The website is on Wordpress using the gravity forms plugin. I didn't have this issue on February, so I suspect is a bug caused by some interactión with a recent Chrome actualization.

If you need any more info regarding this issue, ¡please ask!

I'm searching desesperately for a solution.

¡Thanks in advance!

**Comment by alvarotrigo** [comment]
Your form action is going to the top `action="/#gf_1"` that's why.

**Comment by alvarotrigo** [comment]
It doesn't seem to be related with fullPage.js but with you own script on the ajax call. 
Unless you public it, we can not tell you what it is.

**Comment by alvarotrigo** [comment]
Closed until any code is provided.

**Comment by rzamoramty** [comment]
I'm very sorry It seemed to be that it was a problem with the gravity forms plugin in wordpress.

For anyone experiencing this issue, it can be solved adding ->
add_filter("gform_confirmation_anchor", create_function("","return false;"));

To the functions.php.

Thanks for checking this isssue!
