### ISSUE TITLE
Horizontal scroll w/ tall content, cant use touchpad/keyboard to scroll up/down

### ISSUE THREAD

**Issue by hornetnz** [alvarotrigo/fullPage.js#1162]
Working on a microsite and using fullpage for a horizontal scrolling site. However many of the slides have enough content to require scrolling down. We found that we're unable to scroll vertically unless using the mousewheel. Keyboard arrows/page down, touchpad and mobile wont scroll vertically. I'm unable to tell if this is expected behaviour or not by looking at your demos.
http://bit.ly/1bfH9e6

Below are the options set...
options = $.extend({
			//navigation
			'menu': false,
			'anchors':[],
			'navigation': false,
			'navigationPosition': 'right',
			'navigationTooltips': [],
			'slidesNavigation': false,
			'slidesNavPosition': 'bottom',
			'scrollBar': false,

			//scrolling
			'css3': true,
			'scrollingSpeed': 700,
			'autoScrolling': true,
			'fitToSection': true,
			'easing': 'easeInOutCubic',
			'easingcss3': 'ease',
			'loopBottom': false,
			'loopTop': false,
			'loopHorizontal': true,
			'continuousVertical': false,
			'normalScrollElements': null,
			'scrollOverflow': false,
			'touchSensitivity': 5,
			'normalScrollElementTouchThreshold': 5,

			//Accessibility
			'keyboardScrolling': true,
			'animateAnchor': true,
			'recordHistory': true,

			//design
			'controlArrows': true,
			//'controlArrowColor': '#fff',
			'verticalCentered': true,
			'resize': false,
			'sectionsColor' : [],
			'paddingTop': 0,
			'paddingBottom': 0,
			'fixedElements': null,
			'responsive': 0,

			//Custom selectors
			'sectionSelector': '.section',
			'slideSelector': '.slide',

			//events
			'afterLoad': null,
			'onLeave': null,
			'afterRender': null,
			'afterResize': null,
			'afterReBuild': null,
			'afterSlideLoad': null,
			'onSlideLeave': null
		}, options);

**Comment by alvarotrigo** [comment]
> Keyboard arrows/page down, touchpad and mobile wont scroll vertically.

That's because you are not making use of the option `scrollOverflow:true` that deals automatically with that problem as you can see [in this demo](http://alvarotrigo.com/fullPage/examples/scrolling.html).

Therefore, you should be using the option `normalScrollElements` and apply it to your scrollable content. 
Read more about it in the docs.

Check as well `normalScrollElementTouchThreshold` just in case you need to change it.

**Comment by hornetnz** [comment]
Thanks for the reply.
I set scrolloverflow and added #slide3 to normalscrollelements, but the behaviour hasn't changed.

**Comment by alvarotrigo** [comment]
No.
You have to use one or the other. Not both. 
Just use `normalScrollElements` if you only have horizontal slides in your site.
