### ISSUE TITLE
Scrolling inside section issues

### ISSUE THREAD

**Issue by B-iggy** [alvarotrigo/fullPage.js#1163]
Hi,

I'm using your script with joy but at the moment it runs into troubles.

http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage
First: the feature to scroll inside a section doesn't work in Chrome42+ for me anymore. Can you confirm?
In IE11+ and FF37+ it is working. (in older Chrome versions it's working too).

http://www.ignaz-biegler.de/#home
Second: in my own project and in all browsers (besides Chrome42+...) this feature is only working with the setting scrollBar: false. I already placed the slimscroll script before fullpage. Any idea?

Thanks in advance!

**Comment by alvarotrigo** [comment]
> the feature to scroll inside a section doesn't work in Chrome42+ for me anymore. Can you confirm?

It works for me. Make sure the site finished loading.

> this feature is only working with the setting scrollBar: false.

It is not designed to work with `scrollBar:true`. Two scroll bars make no sense.

**Comment by B-iggy** [comment]
After installing a fresh version of Chrome I figured it out and just sharing the information.
The chrome extension for smooth scrolling which I'm using likely (https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb?hl=en) disallowed the scroll inside behavor. Don't want to dig to deep in it but I guess it's a normal script vs script conflict. Well, no big deal at the end. Thanks though.

The second scroll bar was for UX reasons. I guess I need micro actions instead.
