### ISSUE TITLE
Is it possible to have a full site background?

### ISSUE THREAD

**Issue by corysimmons** [alvarotrigo/fullPage.js#1164]
Not a single page background, but a single background image that spans across all your sections/slides?

**Comment by alvarotrigo** [comment]
Many things are possible with the right knowledge.
Your question is a matter of CSS and I'm afraid this is not the best place to ask.

Try asking in http://stackoverflow.com/

**Comment by corysimmons** [comment]
Just to clarify, it *is* possible I just don't know how?

**Comment by Pakuku** [comment]
It's very possible but different screen heights make it more challenging to use an image that attempts to tell a story over X pages.  You would need to deliver a different version of the background image based on screen height... all of which has nothing to do with fullPage.  This works for me and is a starting point:

<div id="app">
  <div id="fullpage" style="background: url('wallpaper.png'">
    <div id="section0" data-anchor="slide0"></div>
    <div id="section1" data-anchor="slide1"></div>    
    <div id="section2" data-anchor="slide2"></div>
  </div>
</div>
