### ISSUE TITLE
Vertical Slides

### ISSUE THREAD

**Issue by itsjms** [alvarotrigo/fullPage.js#1167]
I am trying to make a section that has multiple slides in it, however, I would like them to scroll vertically instead of horizontally. Is this possible/already built in? (essentially I am looking to have sections in sections so that it does not make the web page extra long)

**Comment by alvarotrigo** [comment]
Not possible. 
You can ask for a customisation if you want.

**Comment by itsjms** [comment]
Uhg. I might just have to add in the functionality myself then. It's like the last thing this plugin needs to be perfect.

**Comment by alvarotrigo** [comment]
@itsjms if you are talking about something like what was discussed [on this topic](https://github.com/alvarotrigo/fullPage.js/issues/200) it is not a trivial change at all.
