### ISSUE TITLE
Possible bug in $.fn.fullpage.setAllowScrolling.

### ISSUE THREAD

**Issue by bardiharborow** [alvarotrigo/fullPage.js#1169]
The following jsfiddle does not work as it is supposed to, at least on Chrome 42 (latest stable).

http://jsfiddle.net/97tbk/554/

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    afterLoad: function(anchorLink, index){
        //on load section 2...
        if(index == 2){
            $.fn.fullpage.setAllowScrolling(false, 'up');
        }else{
            $.fn.fullpage.setAllowScrolling(true, 'up');
        }
    }
});
```

**Comment by alvarotrigo** [comment]
Can you explain why not?
It is disabling the scrolling up when reaching the 2nd vertical section.

**Comment by alvarotrigo** [comment]
Closed until new evidence / explanation is provided.

**Comment by bardiharborow** [comment]
Supposedly it works on Chrome 42 Mac, but it's not disabling scrolling up on Chrome 42 Windows.

**Comment by alvarotrigo** [comment]
> Supposedly it works on Chrome 42 Mac, but it's not disabling scrolling up on Chrome 42 Windows.

Sorry I'm not able to reproduce it. Its working as expected on Chrome 42 Windows for me.
