### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by theofidry** [alvarotrigo/fullPage.js#1170]
Could it be possible to publish a npm pacakge too? In some cases we can't afford to use Bower :(

**Comment by alvarotrigo** [comment]
Yeah, I hope to do it soon.
Waiting for a response [in this topic](https://github.com/alvarotrigo/fullPage.js/pull/1168) about it.

**Comment by theofidry** [comment]
Ok great :)

**Comment by alvarotrigo** [comment]
Added to npm: https://www.npmjs.com/package/fullpage.js

**Comment by theofidry** [comment]
Thanks!
