### ISSUE TITLE
slides keyboard usage

### ISSUE THREAD

**Issue by procmail** [alvarotrigo/fullPage.js#1171]
Hi,

Sorry if I missed it in the documentation, but I'm looking for a way to enable keyboard usage (perhaps left/right arrow keys) to navigate between horizontal slides.

Currently it seems pressing the up, down, left and right arrow keys just move between sections.

**Comment by alvarotrigo** [comment]
The keyboard arrows work for horizontal slides as well, you can try it [in the demo page](http://alvarotrigo.com/fullPage/).
