### ISSUE TITLE
Autoplay problem on Android

### ISSUE THREAD

**Issue by erknrio** [alvarotrigo/fullPage.js#1172]
Hello Álvaro,

When I searched for this issue, I saw a lot of issues about autoplay option but I didn't see anything about this exactly problem. 

I try to combine the background video and onesection examples. This works great on desktop but the autoplay option doesn't work on android  :S. Same problem for your background video example.
#### HTML:
```
<div id="fullpage">
	<div class="section " id="section0">
		<video autoplay loop muted id="myVideo">
			<source src="resources/flowers.mp4" type="video/mp4">
			<source src="resources/flowers.webm" type="video/webm">
		</video>
		<div class="layer">
			<h1>MY WEBSITE</h1>
		</div>
	</div>
</div>
```

#### JS:
````
$(document).ready(function() {
	$('#fullpage').fullpage({
		autoScrolling: false,
		css3: true,
		afterRender: function() {
			//playing the video
			$('video').get(0).play();
			//document.getElementById("myVideo").play();
		}
	});
});
```
Tested on this web: http://adriangarrido.com.es/test/apps/fullpage/oneSectionVideo.html

Thank you very much for your reply.

**Comment by alvarotrigo** [comment]
Not related with fullPage.js.
As far as I know [you can not autoplay videos on mobile browsers](http://stackoverflow.com/questions/12496144/can-you-autoplay-html5-videos-on-the-ipad). 

[Android either](http://stackoverflow.com/questions/9075520/how-to-autoplay-html5-mp4-video-on-android).

**Comment by erknrio** [comment]
I don't know that. Thank you very much and sorry :S.
