### ISSUE TITLE
auto navigate to top of page

### ISSUE THREAD

**Issue by rjcrystal** [alvarotrigo/fullPage.js#1173]
i cant disable navigate to top when using onepage example 
when i put navigate: false it stops scrolling to top but then sliders are also removed

**Comment by alvarotrigo** [comment]
I have no clue what `navigate:false` is. If you find it in the docs please let me know :)

**Comment by rjcrystal** [comment]
sorry i meant navigation:false and why does the page autonavigates to top when i scroll down thats the problem

**Comment by alvarotrigo** [comment]
I'm sorry, you would have to reproduce your problem [here](http://jsfiddle.net/97tbk/418/) because I can not understand what your problem is.

**Comment by rjcrystal** [comment]
if you could please visit this link http://scaps.me/fullpage/examples/oneSection.html i have replicated the problem there

**Comment by alvarotrigo** [comment]
Use `fitToSection:false`.

**Comment by rjcrystal** [comment]
:+1:  what was the problem ? what does fittoSection do ?

**Comment by alvarotrigo** [comment]
> what was the problem ? what does fittoSection do ?

Read the documentation.
