### ISSUE TITLE
How to make sections for a slide?

### ISSUE THREAD

**Issue by Ultear** [alvarotrigo/fullPage.js#1177]
Hello,

I have a question i want to make a website in a such format:

Page Page Page Page Page
||||||||||||||||||||Page
||||||||||||||||||||Page
||||||||||||||||||||Page

So how to manage to make a landscape website with a sections just under one slide, since ive tried to run event on down arrow press and check wheather the slide where it was clicked was i third slde if not return false, but it returned me always all indexes of all slides.

**Comment by alvarotrigo** [comment]
You can emulate that by using `setAllowScrolling`. You can set it to false in the `down` direction for all the slides except for the 1st one by using a callback such as `afterSlideLoad`.

**Comment by Ultear** [comment]
Wont setAllowScrolling work only for mouse scroll and not for arrows?

**Comment by alvarotrigo** [comment]
Exactly. You would need to disable the arrows navigation and very probably use something like this: http://stackoverflow.com/a/29822757/1081396

**Comment by Ultear** [comment]
Ok, ty for helping ^^
