### ISSUE TITLE
Section re-adjusts after scrolling

### ISSUE THREAD

**Issue by acandael** [alvarotrigo/fullPage.js#1178]
Hi,

I'm using the fullPage.js library for my new webproject:

http://superintendant-rabbit-82576.bitballoon.com/

Because the website also needs to render on mobile devices, I turned off autoscrolling.

However, when I scroll the section on my iPhone 4S, the section re-adjust automatically after a couple of seconds.

Is there a way to turn the re-adjusting behaviour off, so when scrolling the section stays at the position the user scrolled at?

Thanks for your help,

Anthony

**Comment by alvarotrigo** [comment]
Use `fitToSection:false`:

> **fitToSection:** (default true). Determines whether or not to fit sections to the viewport or not. When set to true the currente active section will always fill the whole viewport. Otherwise the user will be free to stop in the middle of a section (when )

**Comment by acandael** [comment]
Thanks alvarotrigo, that fixed it.
