### ISSUE TITLE
Repetitive use of the MoveTo

### ISSUE THREAD

**Issue by theofidry** [alvarotrigo/fullPage.js#1180]
If I make a simple menu like so:

```html
<li><a href="#s1" onclick="$.fn.fullpage.moveTo('s1-section')">S1</a></li>
<li><a href="#s2" onclick="$.fn.fullpage.moveTo('s2-section')">S2</a></li>
<li><a href="#s3" onclick="$.fn.fullpage.moveTo('s3-section')">S3</a></li>
<li><a href="#s4" onclick="$.fn.fullpage.moveTo('s4-section')">S4</a></li>
```

Then if I clic two times on S1 and then on S2, I'll be redirected to S3...

for each section I added the `data-anchor="sX-section"`.

Also, I don't know if it's related, but if I load my page at `/#s3`, the two first sections won't appear, the page is loaded as if the third section is the first!

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it [here](http://jsfiddle.net/97tbk/567/).
Please provide a reproduction of the error.

**Comment by theofidry** [comment]
Thanks for the fiddle, I was using the ID of the section for my links instead of the data-anchor -_-
