### ISSUE TITLE
Sign ! in the url

### ISSUE THREAD

**Issue by pceuropa** [alvarotrigo/fullPage.js#1181]
I would like to present regulations on this page https://developers.google.com/webmasters/ajax-crawling/
add character ! before # the url (ex. example.com\!#section0)
 How to do it?

**Comment by alvarotrigo** [comment]
The title says:

> Making AJAX Applications Crawlable

Fullpage.js doesn't use ajax. So nothing in there is applicable to it...

**Comment by pceuropa** [comment]
Anyway, is there any way to get it to add character! to address?

**Comment by alvarotrigo** [comment]
No, the plugin doesn't provide it.

**Comment by pceuropa** [comment]
ok, tnx
