### ISSUE TITLE
Avtice class afect the text inside a div when the parent is position relative.

### ISSUE THREAD

**Issue by PabloArty** [alvarotrigo/fullPage.js#1183]
Simploe this is my div's css:

.active{
	text-decoration: underline;
}
.txt-slide-one{
	font-family: 'Source Sans Pro', sans-serif;
	text-decoration: none !important;
	position: absolute;
	z-index: 3;
	width: 20%;
	max-width: 450px;
	min-width: 370px;
	text-align: justify;
	right: 6%;
  	top: 205px;
  	color: #165F30;
}

then:

@media (max-width: 1000px){
	.txt-slide-one{
		position: relative;
		text-decoration: none !important;
		margin: 0 auto;
		top:0px;
		right: 0px;
	}
}

when the responsive query actives my .txt-slide-one text get the underline style too. and nothing can remove it (!important and that stuff). The text is just content of a slide, it's an anchor or anything like that.

**Comment by alvarotrigo** [comment]
Well, that's because you are using : 
```css
.active{
text-decoration: underline;
}
```

In any case, this is not a question for this forum as its a matter of CSS rather than about fullPage.js itself. 
Check other places such as http://stackoverflow.com/
