### ISSUE TITLE
All slides inherits first slide background + elements inside slide doesn't display bg

### ISSUE THREAD

**Issue by Ultear** [alvarotrigo/fullPage.js#1184]
Hello, im trying to make an element with fixed bg attachment inside a slide:

div[data-anchor='news']{
	div.cover-photo{
		//background:rgba(0,0,0,0.7) url('../images/bg.jpg'); // Will display blank page with first slide bg
                //background:rgba(0,0,0,0.7); // Will display transparent black color of 95% height
		background:{
			attachment: fixed;
		}
		width:100%;
		height:95%;
	}
	
}

and html here:

div id="fullpage">
    	div class="section" data-anchor="page">
    		div class="slide home" data-anchor="home" data-scheme="light">
                    slide1
    	        /div>
    		div class="slide news" data-anchor="news" data-scheme="dark">
                    div class="cover-photo">slide2</div>
            /div>
/div>
/div> -->

deleted first < since dont know how to attach code
![zrzut ekranu 2015-04-27 o 20 09 24](https://cloud.githubusercontent.com/assets/11744682/7354168/887b61d0-ed19-11e4-8f8e-658c9a0423f5.png)
![zrzut ekranu 2015-04-27 o 20 10 11](https://cloud.githubusercontent.com/assets/11744682/7354167/8875c022-ed19-11e4-9add-e124f1e38797.png)

After checking if cover-photo is affected with css, yeah it is, but wont display background-image at all ;s

**Comment by alvarotrigo** [comment]
Sounds like a CSS problem, not a fullPage.js one.
