### ISSUE TITLE
Plugin skips one section in firefox

### ISSUE THREAD

**Issue by sky82510** [alvarotrigo/fullPage.js#1186]
Hi! 

I'm using Fullpage.js, and I'm overall very happy with it! 

I however discovered that the plugin will skip one section when scrolling AND using nav menu when using Firefox. 
It'll skip #secondpage.

Did anyone have the same problem ? 
What should I do ?

Here's the website:

www.graphink.be

Thanks a million, guys !

**Comment by alvarotrigo** [comment]
Check the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions), Do not use IDs as anchors.

As you can see, it works perfectly [on the demo site](http://alvarotrigo.com/fullPage/).
