### ISSUE TITLE
Page content overflow - Gallery with MediaBoxes

### ISSUE THREAD

**Issue by dukeyduke** [alvarotrigo/fullPage.js#1187]
Hi,

Great plugin. However I am having issues getting another plugin Media Boxes to work well with full page.js. It would be great if there could be a full page tiled gallery like in the example (http://grandduchy.co.uk/test/mbfullpage/) that worked well responsively. Is this a possibility, am I missing an easy solution even if it was just to crop any of the content that flows over onto the next page?

**Comment by alvarotrigo** [comment]
Check the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) you might find your answer regarding the use of other plugins in there.
