### ISSUE TITLE
fullPage.js with smoothState.js?

### ISSUE THREAD

**Issue by omgummy** [alvarotrigo/fullPage.js#1188]
Hello everyone,

I'm still pretty new at implementing js in webpages, and I'm trying to figure out how I can implement <a href="http://miguel-perez.github.io/smoothState.js/index.html">smoothState.js</a> without breaking the code? I'm sure it's a simple solution to applying js, but any help is appreciated, thank you!

- Omgummy

**Comment by alvarotrigo** [comment]
That's not a question regarding fullPage.js usage. You'd better ask in other place such as http://stackoverflow.com/

I have no clue about smoothState.
