### ISSUE TITLE
Zoom on the page

### ISSUE THREAD

**Issue by prusieck** [alvarotrigo/fullPage.js#1189]
Hi,

before I go on - great job. I absolutely love the framework and I just rebuild our company's webpage with it: www.aquilamtech.co.uk

It's working pretty well but I've noticed that ctrl + mouse scroll works only on the top page. I'll look through the code and my page and try to fix it, but I thought it's worthwhile to let you know. I got the feedback from one of the testers that check the support for accessibility functions.

Regards,
Piotr

**Comment by alvarotrigo** [comment]
Related with [this open issue](https://github.com/alvarotrigo/fullPage.js/issues/55). 
Not solution was found yet.
