### ISSUE TITLE
Looping horizontal slideshow ?

### ISSUE THREAD

**Issue by shivanraptor** [alvarotrigo/fullPage.js#1190]
Once reached the last slide of horizontal slideshow, can the slideshow continues to show the 1st slide, but don't have the animation of left-scrolling all way back to slide 1 ?

**Comment by alvarotrigo** [comment]
Already treated [here](https://github.com/alvarotrigo/fullPage.js/issues/124).

Short answer: no, if you want it, I can customize the plugin for you.

**Comment by hostedvideorn** [comment]
Can you please customize the plugin to me as well? I need this functionality. Thanks

**Comment by alvarotrigo** [comment]
@hostedvideorn [contact me](http://alvarotrigo.com/#contact-page) for more details.

**Comment by hostedvideorn** [comment]
Done. Thanks!

**Comment by alvarotrigo** [comment]
This is now possible by using the [Continuous Horizontal extension](https://alvarotrigo.com/fullPage/extensions/continuous-horizontal.html).
