### ISSUE TITLE
problem with fp-view-class

### ISSUE THREAD

**Issue by BeBo007** [alvarotrigo/fullPage.js#1191]
i'm trying to work with css-transitions as you show in your tutorial-video. my problem is, that the "fp-view"-class is not changing at the end of a section. instead it's changing somerwhere in the middle. 
Do you have a clue why this could happen? Or do you have a solution?

i post post the options i set below...

thx a lot!

		$(document).ready(function() {
			$('#fullpage').fullpage({ 
				    sectionsColor: ['transparent', '#fff', '#fff', '#fff', '#fff'],
					paddingTop: '0px',
					
					 //Navigation
					navigation: false,
					
					//Scrolling
					css3: true,
					scrollingSpeed: 1500,
					autoScrolling: false,
					fitToSection: false,
					scrollBar: true,
					easing: 'easeInOutExpo',
					easingcss3: 'ease',
					loopBottom: false,
					loopTop: false,
					continuousVertical: false,
					scrollOverflow: false,
					touchSensitivity: 15,
					normalScrollElementTouchThreshold: 5,
					recordHistory: true,
					resize: true,
					
					//menue
					fixedElements: '#header',
					anchors: ['start', 'Kapitel1', 'Kapitel2', 'Kapitel3', 'ende'],
					menu:'.menue',

**Comment by alvarotrigo** [comment]
Related with this [open issue](https://github.com/alvarotrigo/fullPage.js/issues/919).
The plugin is only ready to work with full screen sections I'm afraid. 

I might take a look at it in a future, but it's not a high priority issue.

**Comment by BeBo007** [comment]
good to know. thank you for your quick reply and your support!
