### ISSUE TITLE
Rewind horizontal loop

### ISSUE THREAD

**Issue by packytagliaferro** [alvarotrigo/fullPage.js#1192]
Is there a way to make the plugin not rewind back to the first slide when it reaches the end, but rather just show the first slide like all the others? In other words instead of rewinding back to the beginning it slides the first slide in from the right like its a continuous loop

**Comment by alvarotrigo** [comment]
Related with [this open issue](https://github.com/alvarotrigo/fullPage.js/issues/124). 

Short answer: no, if you want it, I can customize the plugin for you.

**Comment by kaochihhui** [comment]
Please add in this feature. It's really useful for others, like me. Thanks :)

**Comment by holyzfy** [comment]
It works for me.

```css
.no_transition {
    transition: none !important;
}
```

```js
onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex) {
    var isFirst = direction === 'right' && nextSlideIndex > slideIndex + 1;
    var isLast = direction === 'left' && slideIndex > nextSlideIndex + 1;
    $(this).parent().toggleClass('no_transition', isFirst || isLast);
}
```

**Comment by nim-f** [comment]
Hi, could you customize it for me too?

**Comment by alvarotrigo** [comment]
@nim-f [write me a mail](http://alvarotrigo.com/#contact-page) and we can talk about it.

**Comment by faliqaiman** [comment]
hi @holyzfy can you share in fiddle? thanks

**Comment by alvarotrigo** [comment]
Available now through [the fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/).
