### ISSUE TITLE
Slide directly in specific slide like in pagePiling.js

### ISSUE THREAD

**Issue by geraldnako** [alvarotrigo/fullPage.js#1195]
Hey Alvaro thanks for this awesome plugin.

I have one question.

I am using the slider of fullpage.To navigating the sliders I have created a menu with the links that data-ancores create. 

Is there any option to slide directly in one slide without passing in the other slides like in the pagePiling.js plugin. 

Thanks

**Comment by alvarotrigo** [comment]
You can use the new method  [`silentMoveTo`](https://github.com/alvarotrigo/fullPage.js#silentmovetosection-slide).
