### ISSUE TITLE
if i add a <object> tag the scroll crashed

### ISSUE THREAD

**Issue by Tibicenas** [alvarotrigo/fullPage.js#1196]
I want to add a svg to my webpage using object tag
<object type="image/svg+xml" data="img/mysvg.svg" class="mysvg">

Image that i have 4 sections. If i add the <object> in the section 2, then i cannot keep navigating in the next sections.

**Comment by alvarotrigo** [comment]
Please provide a way to reproduce the issue.

**Comment by Tibicenas** [comment]
<!DOCTYPE html>
<html lang="en-EN">
  <head>
    <meta charset="utf-8">
    <title>Testing FullPage</title>
    <link href="jquery.fullPage.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script type="text/javascript" src="jquery.fullPage.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      $('#fullpage').fullpage({
      });
    });

  </script>
  </head>

  <body>
    <div id="fullpage">
    

      <section class="section sobran"><h1>Testing fullPage.js  SECTION 1</h1></section>


      <section class="section"><h1>SECTION 2</h1></section>
      <section class="section">
         <div class="btn__group">
                <h1>SECTION 3</h1>
            
            <button class="btn btn--info">Information</button>
            <button class="btn btn--success">Information</button>
            <button class="btn btn--warning">Information</button>
          </div>

      </section>



      <section class="section boom">
        <article class="slide">
          <h1>SECTION 4 SLIDES</h1>
          <h2>SLIDE 1</h2>
        </article>
        <article class="slide"><h2>SLIDE 2</h2></article>
        <article class="slide"><h2>SLIDE 3</h2></article>
        <article class="slide"><h2>SLIDE 4</h2></article>
      </section>

      <section class="section"><h1>SECTION 5</h1></section>





    </div>  
  </body>
</html>

Si descomentas el svg, la navegación dejará de ir.

**Comment by alvarotrigo** [comment]
I mean, an online way to reproduce it if possible. Create a jsfiddle from here: http://jsfiddle.net/97tbk/418/  or provide a link to your site.

**Comment by Tibicenas** [comment]
Checking in the jsfiddle (html more clean) i found the problem, obviously my fault, a tag without closing.
Sorry for the inconvenience.
