### ISSUE TITLE
Multiple moveSlideDown only works once

### ISSUE THREAD

**Issue by mikezclements** [alvarotrigo/fullPage.js#1197]
I have five section and only three of them have a button to move the section down using moveSlideDown. The first buton works fine while the second and third dont move the section on click. Can you please help me how get those button work? Thank you.

**Comment by alvarotrigo** [comment]
No way to solve your issue unless you provide a way to reproduce the error.
As you can see in [this demo page](http://alvarotrigo.com/fullPage/examples/methods.html) the method moveSectionDown works as expected no matter how many times you fire it.

**Comment by mikezclements** [comment]
The button in the demo page has a fixed position while mine is not.

**Comment by alvarotrigo** [comment]
Unless you reproduce your issue somewhere, I won't be able to help you. 
You probably are having some jQuery / javascript issue rather than a problem with fullPage.js.
