### ISSUE TITLE
locking hashchange event

### ISSUE THREAD

**Issue by wojtekw92** [alvarotrigo/fullPage.js#1198]
Can you add posibility to lock internal routing, for people who want use external routing library?

**Comment by alvarotrigo** [comment]
Could you explain it better? Not sure to understand what are you asking for.

**Comment by wojtekw92** [comment]
yeah. What I am trying to say is to add some flag in initial config which will lock everything conected with hash starting from event listener for example
 ```
 $window.on('hashchange', hashChangeHandler);
```
to
```
if(hashEnable) {
    $window.on('hashchange', hashChangeHandler);
}
```
for me the biggest problem is, that function ```setState``` overwrite the hash ```setUrlHash(sectionHash + '/' + slideAnchor);```. I am using more complex library in my my project, and now both are trying to make changes in url.

**Comment by alvarotrigo** [comment]
@weiliank why don't you just use fullPage.js without anchors?

**Comment by wojtekw92** [comment]
Yes I can ust  fullpage without anchors but using it with data-anchor and moveTo(anchor) is much more comofortable  event if you using external lib for routing :)  I Just wont  lock hash change without removeing any functionaltity :)

**Comment by alvarotrigo** [comment]
You can still using `moveTo` using indexes instead.

**Comment by wojtekw92** [comment]
Yeah I can but when i'm using nice links for example  ```#! /projects/34/about``` i get projects from the first part i prefer to use moveTo('projects ')  intel of makeing map of section indexes and names

**Comment by alvarotrigo** [comment]
The option `lockAnchors` has been introduced in fullPage.js 2.6.6.

Also a function `setLockAnchors(boolean)`. More at the docs: https://github.com/alvarotrigo/fullPage.js#setlockanchorsboolean
