### ISSUE TITLE
Strange behavior when toggling setAutoScrolling(false/true). Jumps to first section.

### ISSUE THREAD

**Issue by adaptifyDesigns** [alvarotrigo/fullPage.js#120]
I am using a plugin called Magnific Popup - http://dimsemenov.com/plugins/magnific-popup/documentation.html in conjunction with your plugin.

You can see my project here: http://www.safetec.net/know-your-chemicals/

The problem is that when I activate a popup window any scrolling or swiping causes the sections behind the popup (the fullpage slides) to autoscroll like normal.

So my first attempt to solve this was to trigger setAutoScrolling(false) when the popup window opens, and then setAutoScrolling(true) when the popup window is closed. But with this configuration when I activate the popup (which is a transparent overlay) the website jumps immediately to the top section. And then when I close the popup, the site jumps immediately back to the section it was in.

BUT, to make it even weirder, if, while the popup is open, I scroll or swipe even a little, then when I close the popup, the site remains in the top most section. Meaning it does not jump back to the section I was when opening the popup.

This is very difficult to explain. So please check it out here: http://www.safetec.net/know-your-chemicals

I want the user to only be able to scroll within the popup content while the popup is open, without the website scrolling at all. And when the popup is closed, I need the user to remain on the section on which they opened the popup from. Does that make sense?

I can only allow public access for a limited time. So check it out as soon as you can. 

Thanks so much in advance for any help with this!
- Colin

**Comment by muyaszed** [comment]
Hi is this fix still applicable? I cannot find the code mention in this issue, I am having the same problem, the scroll bar and scrolling function disappeared after closing the popup.
