### ISSUE TITLE
Next Section Button (Not hard coded, dynamic next) 

### ISSUE THREAD

**Issue by thekennysong** [alvarotrigo/fullPage.js#1200]
Was wondering if there is an example of a next icon that would scroll to the next section. For example, with one page scroll, there is this example http://codepen.io/soren-tree/pen/jwEvk, where the button just goes to the next section. Something like:

			$('.arrow').click(function(){
				$("#fullpage").moveDown();
			})

Thanks!

**Comment by alvarotrigo** [comment]
I guess you answered yourself?

yeah, you can use [`$.fn.fullpage.moveSectionDow();`](https://github.com/alvarotrigo/fullPage.js#movesectiondown)

**Comment by thekennysong** [comment]
Yeah, I was confused though because I did $.fn.fullpage.moveSectionDown(); for a on click function but it didn't work. But now I got it to work! 

Thanks! Your plugin is a lot better than onepage scroll! :)
