### ISSUE TITLE
Slides issue

### ISSUE THREAD

**Issue by pol971** [alvarotrigo/fullPage.js#1202]
Hi man, 
when i try to add slides to my website i have a trouble: the slide isn't correctly scaled and it leaves a space blank, but when i scroll down to a section without slides everything returns ok...
What can I do?
PS. I added a Header using the same code you used in your example
![screenshot 4](https://cloud.githubusercontent.com/assets/12299626/7520126/c7d3b422-f4e4-11e4-978e-78d8c73b46cc.png)
![screenshot 5](https://cloud.githubusercontent.com/assets/12299626/7520221/6fd6d000-f4e5-11e4-93ee-41c31a4c9a8b.png)
Thanks in advance,
-Pol

**Comment by alvarotrigo** [comment]
Reproduce your problem somewhere to get help.
As you can see, your problem doesn't take place in [the demo page](http://alvarotrigo.com/fullPage/).

**Comment by pol971** [comment]
Hi, i uploaded the html with his resources online 
http://tuttoflash.altervista.org/Site/Problems.html#secondPage
If you can take a look when you have time you'll do me a great favour

**Comment by alvarotrigo** [comment]
You are using the initialization I provided **as an example** in the documentation... And it is using `paddingTop: '3em'`, so the result is totally expected.

Create your own initialisation with only the options you need.

**Comment by pol971** [comment]
Thank you for your help, now it works as smooth as silk and sorry if I bothered you only for a distraction/noobness problem of mine
