### ISSUE TITLE
site breaks on firefox when resize window.

### ISSUE THREAD

**Issue by gerleone73** [alvarotrigo/fullPage.js#1204]
I am near completion of my portfolio website. I had been testing it on chrome and on safari where all seems well.

However i have recently discovered to my horror that the site breaks completely when resize window on Firefox.

gerleone.com

**Comment by alvarotrigo** [comment]
I can not reproduce your problem. Your site scrolls normally when resizing it down.
I don't know what you are doing because you have 2 scroll bars, but the plugin seems to work as expected and turn to `autoScrolling:false` under 1000 px.

**Comment by alvarotrigo** [comment]
I would suggest you to try to reproduce your problem in [this jsfiddle](http://jsfiddle.net/97tbk/418/).

**Comment by gerleone73** [comment]
I have been asking people to check the site on firefox and they are all experiencing problems.. the content sometimes vanishes, they can't scroll until they resize again etc...   also some people have complained that even when they click on normal scroll button it still stops scrolling at sections occasionally (on all browsers)

**Comment by gerleone73** [comment]
sorry i can't reproduce problem on jsfiddle.... as i don't know how/why these problems are happening..

**Comment by gerleone73** [comment]
also i am not seeing the "two scrollbars" you mentioned , just one when resize down

**Comment by alvarotrigo** [comment]
@gerleone73 as you can see, the plugin woks as expected on [the demo page](http://alvarotrigo.com/fullPage/). 

Unless you can reproduce the problem and isolate it as much as possible to verify it is produced by fullPage.js and not by your own CSS/JS I'm afraid I can not help you with it.

I would suggest you to solve the problem you have with 2 scroll bars. As that's not how fullpage.js works and it seems a problem generated from your part. 

![twoscrollbars](https://cloud.githubusercontent.com/assets/1706326/7534637/5065d876-f574-11e4-8e91-f9f709abc924.PNG)

If you are not able to solve it, I would recommend you to start from one of the examples provided in fullpage.js and check from time to time if you are having that problem or not until you identify the cause of it.

**Comment by gerleone73** [comment]
![screen shot 2015-05-08 at 11 20 13](https://cloud.githubusercontent.com/assets/4580059/7534630/3b667e4e-f574-11e4-86ca-15516c154e20.jpg)
![screen shot 2015-05-08 at 11 20 46](https://cloud.githubusercontent.com/assets/4580059/7534636/4fcb1318-f574-11e4-9938-6951e7cd3f08.jpg)

same page content vanishes then reappears when resize window on firefox

**Comment by alvarotrigo** [comment]
@gerleone73 see my previous answer.

**Comment by gerleone73** [comment]
ok i have looked at forums and through documentation ... i appreciate its difficult of you to pinpoint what could be causing these issues but if you have any ideas what I might have done to cause these problems  I would greatly appreciate your help....
