### ISSUE TITLE
Reference slide above/below the active one

### ISSUE THREAD

**Issue by lluuccaass** [alvarotrigo/fullPage.js#1205]
Hi,

i want to target the slide which is directly over/below the active one to load the containing image dynamically.
but i am not able to find a solution to reference these slides especially if they have different indexes.

I really appreciate your help, thanks a lot !

```javascript
onLeave: function() {
   if (direction == "up") {
      // go to section 3 / slide 4
   }
});
```

![bildschirmfoto 2015-05-08 um 15 39 10](https://cloud.githubusercontent.com/assets/6495226/7537365/93d613d6-f598-11e4-9e83-eb68d81d8726.png)

**Comment by alvarotrigo** [comment]
Explain what you are trying to do, because I have no idea what is the `onLeave` event doing there... and what you mean by "reference slide above".

**Comment by lluuccaass** [comment]
every slide contains an image without a src attribute. 
on leaving the active slide the image in the next/prev slide loads by getting a src attribute (lazy load like). i also want this for these slide to the top respectively bottom.

for example: this snippet i am using for the slide right to the active one  

```javascript
onSlideLeave: function() {
       	if (direction == "right") {
       		if( $('.slide').hasClass('active') ) {
			var findNextImg = $(this).next().find('img'),
       		 	nextImgUrl 	= findNextImg.attr('data-url');
	  			  
	  			  findNextImg
	  			  	.attr('src', nextImgUrl)
	  			  		.removeAttr('data-url');
	   		}
	   	}
}
```

**Comment by alvarotrigo** [comment]
Now you changed to `onSlideLeave`. No idea why.

You just need to get the active slide in the previous or next section:

```javascript
onLeave: function(index, nextIndex, direction){
    var destination = $('.section').eq(nextIndex - 1).find('.slide.active');    

    //if there are no slides...
    if(typeof destionation === 'undefined'){
        destination = $('.section').eq(nextIndex - 1);
    }
});
```

That will return you the destination slide or section.
