### ISSUE TITLE
Way to use scrollOverflow for one section only?

### ISSUE THREAD

**Issue by lunarose23** [alvarotrigo/fullPage.js#1206]
I have some sections that run close to the bottom and they move as well. I would like to turn this on for one section only, Not all.

**Comment by alvarotrigo** [comment]
The scroll bar will only appear in the sections which needs scroll bar, so you don't have to worry about it.

**Comment by lunarose23** [comment]
Please check out this video I recorded as I am not live yet - the first section which should NOT scroll is scrolling. I would like to turn it off for certain sections. http://youtu.be/dYodcZAnlLw

**Comment by alvarotrigo** [comment]
If it is scrolling its because its content is bigger than the height of the viewport.
The video is private, I can't see it.

**Comment by lunarose23** [comment]
It's still publishing give it a second.
In order, for me to place a special feature I had to have it larger than
the viewport on desktop. And overflow is hidden on the first section.

Laura Leigh Barry
857-919-6991
lunarose23@gmail.com

**Comment by lunarose23** [comment]
its loaded now

**Comment by alvarotrigo** [comment]
I'm afraid the plugin doesn't provide a way to do that. 
The scroll bar will be applied whenever the content of the section is bigger than the one of the viewport, which seems to be your case.
