### ISSUE TITLE
Fullpage + Scroll Magic

### ISSUE THREAD

**Issue by thekennysong** [alvarotrigo/fullPage.js#1207]
Hello, 

I am wondering how you would go about using Scroll Magic with Fullpage.js so we can make the sections stack on each other versus just scrolling down? 

Thanks!

Kenny

**Comment by alvarotrigo** [comment]
Please read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

You probably have to use `scrollBar:true`.
