### ISSUE TITLE
$.fn.fullpage.destroy() undefined is not a function

### ISSUE THREAD

**Issue by pratiklodha95** [alvarotrigo/fullPage.js#1208]
I tried a lot of solution but none worked,
when in the console of the page in developer mode $.fn.fullpage.destroy() works fine , 
but in my home.js , it doesn't works

**Comment by alvarotrigo** [comment]
Reproduce the problem somewhere. As you can see, it is working as expected on this [demo page](http://alvarotrigo.com/fullPage/examples/methods.html).

**Comment by pratiklodha95** [comment]
This is my Html
<div ui-view class='about'>
<div class='about_wrapper' id='aboutus' ng-init='slides()'>
	
	<div class='section div1'>

i initialize using ng-init
 
$scope.slides=function()
    {
        $('#aboutus').fullpage({
        onLeave: function(index, nextIndex, direction){
            animate(index,direction);
        }
        });    
    };

works fine , but after revisiting after changing to a new view , the slides start skipping ,
I tried 
$.fn.fullpage.destroy() inside the controller but i get a error in console that undefined is not a function

**Comment by alvarotrigo** [comment]
@pratiklodha95 you might want to ask about those things in some angular forum. Not related with fullPage.js at all.
