### ISSUE TITLE
Background repeat right side on slides

### ISSUE THREAD

**Issue by mitcheal** [alvarotrigo/fullPage.js#1209]
I noticed in your examples on in my tests on background images for slides that there is about 118 or so pixels that repeat the background image,  this is happening on Chrome, IE, Firefox etc.  In there a reason for this and how to I get a slide background image to go full width?   Section images work great, just slides.

**Comment by alvarotrigo** [comment]
Exactly, its a matter of CSS, not of fullpage.js.
Thanks for letting me know anyway, I'll correct the example file.
