### ISSUE TITLE
Slide and section fade

### ISSUE THREAD

**Issue by Zarinia** [alvarotrigo/fullPage.js#121]
Hi,
please go to this url:
http://www.apple.com/iphone-5s/
when slide from 1 to 3 for example or slide from section " Home " to section " IOS 7 " this slide with fade effect instead of slide down
and when slide from slide " Home " to next section like " Design " this slide down effect
can you put this effect !?
thanks alot ...

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
