### ISSUE TITLE
2nd page doesn't load anything.

### ISSUE THREAD

**Issue by razieltov** [alvarotrigo/fullPage.js#1210]
Hi,

I'm trying to use this plugin but when i scroll to the next part of my site nothing loads.  It is suppose to have these elements

http://epidemicz.altervista.org/home2.html

This next link shows how it works with this plugin. What can I do to fix it?

http://epidemicz.altervista.org/home.html

**Comment by alvarotrigo** [comment]
A matter of CSS. Not related with fullPage.js.
