### ISSUE TITLE
Active navigation not changing on click

### ISSUE THREAD

**Issue by mitcheal** [alvarotrigo/fullPage.js#1211]
I'm pretty sure this is a bootstrap conflict with listing styles and class conflicts, but when I click the buttons to navigate in this case a slider the button style doesn't change,  is there a way to get the current state of a button/link/li to change style when on a different slide,  also for it to auto select the first slide button when the page loads?

**Comment by mitcheal** [comment]
Another way of asking this is, is it possible to do something like a data-menuanchor for slides?
I wanting three big buttons that you click on to scroll through each slide.

**Comment by alvarotrigo** [comment]
> Another way of asking this is, is it possible to do something like a data-menuanchor for slides instead of sections?
> I wanting three big buttons that you click on to scroll through each slide.

Just use the method available in the plugin such as `moveTo` in combination with the callback `afterSlideLoad` or even with the CSS class added to the body.

**Comment by alvarotrigo** [comment]
> I'm pretty sure this is a bootstrap conflict with listing styles and class conflicts

I don't think it is related with that at all. Fullpage.js prefixed as its classes with `fp-` to prevent those kind of conflicts.

**Comment by mitcheal** [comment]
I see,  I was refering the the menu system you had in your examples,   #menu  plus listing elements that are used which can cause issues in bootstrap.

**Comment by alvarotrigo** [comment]
@mitcheal the examples are just examples. You would have to deal with the conflicts by your own.
