### ISSUE TITLE
Navigate through sliders with arrow keys if autoScrolling is false

### ISSUE THREAD

**Issue by aronsommer** [alvarotrigo/fullPage.js#1212]
When autoScrolling is false I can not navigate with the arrow keys through horizontal sliders.

Is there a workaround for this problem?

**Comment by alvarotrigo** [comment]
Yeah, just create your own keydown events and assign to them the `moveSlideRight` or `moveSlideLeft` feature.

They were disabled as `autoScrolling:false` turns the page to a normal page, in which the keyboard act as in any other page and gets totally free from fullpage.js. It's a matter of design.

**Comment by aronsommer** [comment]
Thank you!

```javascript
$("body").keydown(function(e) {
  if(e.keyCode == 37) { // left
    $.fn.fullpage.moveSlideLeft();
  }
  else if(e.keyCode == 39) { // right
    $.fn.fullpage.moveSlideRight();
  }
});
```
