### ISSUE TITLE
Double scrolling on mac using chrome and safari

### ISSUE THREAD

**Issue by istvanskeri** [alvarotrigo/fullPage.js#1214]
Try to scroll down the page one by one, you'll notice that some pages scroll 2 times. I'm using apple magic mouse 

http://harmoniafilms.com/istvan/

**Comment by alvarotrigo** [comment]
You are using fullpage.js `2.5.2` and the current version is `2.6.5`, which means you are 13 versions old. 

Just update it...

**Comment by istvanskeri** [comment]
i just upgraded and its still happening

**Comment by istvanskeri** [comment]
When i changed the scrollspeed from 500 to 800 i see better performance but i would like the speed to be 500

**Comment by alvarotrigo** [comment]
Only works properly if you keep the default scrolling speed. (700)

I might solve it in a future, but the solution may not be what you expect. The only way I see to solve it is by forcing 700 milliseconds delay between you arrive to one section/slide until you can do any other action.
This is how this plugin worked in a past and [I got many complains about that behavior](https://github.com/alvarotrigo/fullPage.js/issues/333). 

My recommendation is, keep the default scrolling speed. I don't think there's any proper solution for it I'm afraid.

**Comment by yetone** [comment]
[![LGTM](http://lgtm.in/p/U4awZiSnq)](http://lgtm.in/i/U4awZiSnq)

[:+1:](http://lgtm.in/u/U4awZiSnq) [:-1:](http://lgtm.in/r/U4awZiSnq)

**Comment by yetone** [comment]
LGTM!
[![LGTM](http://lgtm.in/p/MuvLf8kPs)](http://lgtm.in/i/MuvLf8kPs)

[:+1:](http://lgtm.in/u/MuvLf8kPs) [:-1:](http://lgtm.in/r/MuvLf8kPs)

**Comment by Zaithe** [comment]
changing the scrolling speed does nothing for me. I changed it to 4000 and still the same. Think perhaps your looking in the wrong direction.

**Comment by alvarotrigo** [comment]
> changing the scrolling speed does nothing for me. I changed it to 4000 and still the same.

You are then doing something definitely wrong :)

**Comment by Zaithe** [comment]
Here are my initialization settings. Using latest version. Not initializing more than once or anything. ![fullpage](https://cloud.githubusercontent.com/assets/2839791/26010964/e9de5262-3703-11e7-80b9-9f9b72017a26.png)

**Comment by Zaithe** [comment]
Seems like this issue originated from the single call of $(window).trigger('resize'); which was used to fix a weird bug with a social feed. For some reason it made the browser double scroll over pages only on trackpads.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen.
