### ISSUE TITLE
toFitSection doesn't work until resize browser windows. 

### ISSUE THREAD

**Issue by xiaochi1214** [alvarotrigo/fullPage.js#1215]
Hi guys, 

I am working on my personal website: www.creativezhang.com/Version2
Everything works fine untill resize browser windows. The images doesn't fit full browser window when first load the page. I am new to web so I need help on that. Thanks!

Joey Z

**Comment by alvarotrigo** [comment]
Check the example that comes with the plugin `backgrounds.html`. 

I'll close the issue as it is a CSS issue and not a fullPage.js one. You should be asking in other places such as http://stackoverflow.com/
