### ISSUE TITLE
How To move to new div not in the sections 

### ISSUE THREAD

**Issue by meroomaher** [alvarotrigo/fullPage.js#1216]
Thank you so much for that great plugins ,, however i have an issue 
now I need to scroll down for div out of the fullpage div  to get the other site content 

I have 3 section 
Section 1
Section 2 
Section 3 

then i need in the last section ( section 3 ) if i make scroll down the fullpage will be scrolled to get the normal scroll 

and also i cannot use it with Owl.Carsual 

thank you

**Comment by alvarotrigo** [comment]
Use a 4th section and the option `scrollOverflow:true`.

**Comment by meroomaher** [comment]
I make the code like that is it ryt ???? 
$(document).ready(function()
{
   $('#fullpage').fullpage(
   {
      anchors : ['firstPage', 'secondPage', 'thirdPage',  'lastPage'],
      menu : '#myMenu',

      // Scrolling
      css3 : true,
      scrollingSpeed : 700,
      autoScrolling : true,

      scrollBar : false,
      easing : 'easeInOutCubic',
      easingcss3 : 'ease',
      loopBottom : false,
      loopTop : false,
      loopHorizontal : true,
      continuousVertical : false,
      normalScrollElements : '#element1, .element2',
      scrollOverflow : true,
      touchSensitivity : 15,
      normalScrollElementTouchThreshold : 5,

      // Accessibility
      keyboardScrolling : true,
      animateAnchor : true,
      recordHistory : true,



      // Custom selectors
      sectionSelector : '.pageslide',
      slideSelector : '.slide',
      afterRender : function()
      {

         // Preloader
         $(window).load(function()
         {
            $('.preloader').fadeOut();
         }
         );
         // Intro Slider
         $('.intro-slider').owlCarousel(
         {
            singleItem : true,
            pagination : false,
            autoHeight : false,
            itemsDesktop : [1000, 4], // 5 items between 1000px and 901px
            itemsDesktopSmall : [900, 2], // betweem 900px and 601px
            itemsTablet : [600, 1], // 2 items between 600 and 0
            itemsMobile : false // itemsMobile disabled - inherit from itemsTablet option
         }
         );
         // Initiat WOW.js
         var wow = new WOW(
         {
            mobile : false
         }
         );
         wow.init();

         // .intro - section reduce opacity when scrolling down
         $(window).scroll(function()
         {
            if($(window).width() > 1260)
            {
               windowScroll = $(window).scrollTop();
               contentOpacity = 1 - (windowScroll / ($('#intro').offset().top + $('#intro').height()));
               $('.intro-section').css('transform', 'translateY(' + Math.floor(windowScroll * 0.16) + 'px)');
               $('.intro-section').css('-webkit-transform', 'translateY(' + Math.floor(windowScroll * 0.16) + 'px)');
               $('.intro-section').css('opacity', contentOpacity.toFixed(2));
            }
         }
         );

         // Fixed navigation
         $(window).scroll(function()
         {
            if ($(window).scrollTop() > 500)
            {
               $('.navbar').addClass('fixednav');
            }
            else
            {
               $('.navbar').removeClass('fixednav');
            }
         }
         );

         // Initiat onepageNav.js
         $('.nav').onePageNav(
         {
            currentClass : 'current',
            'scrollOffset' : 500
         }
         );

         // Hide Mobile Nav when clicking item
         $(".nav a, .navbar-header a").click(function(event)
         {
            $(".navbar-collapse").removeClass("in").addClass("collapse");
         }
         );

         /* Buttons Scroll to Div */
         $('.navbar-brand').click(function ()
         {
            $.scrollTo('.intro', 1000);
            return false;
         }
         );

         $('.btn-custom').click(function ()
         {
            $.scrollTo('.download', 1000);
            return false;
         }
         );

         $('.btn-custom-border, a.mouse').click(function ()
         {
            $.scrollTo('.features', 1000);
            return false;
         }
         );

         // Screenshot carousel
         $(".screens").owlCarousel(
         {
            items : 4,
            navigation : true,
            navigationText : [
            "<i class='fa fa-angle-left btn-slide'></i>",
            "<i class='fa fa-angle-right btn-slide'></i>"
            ],
            pagination : false,
            itemsDesktop : [1000, 4],
            itemsDesktopSmall : [990, 3],
            itemsTablet : [600, 1],
            itemsMobile : false
         }
         );

         // Screenshot lightbox
         $('.screens a').nivoLightbox(
         {
            effect : 'fadeScale'
         }
         );

         // Brief carousel
         $(".small-slider").owlCarousel(
         {
            items : 1,
            navigation : true,
            navigationText : [
            "<i class='fa fa-angle-left btn-slide'></i>",
            "<i class='fa fa-angle-right btn-slide'></i>"
            ],
            pagination : false,
            itemsDesktop : [1000, 1],
            itemsDesktopSmall : [900, 1],
            itemsTablet : [600, 1],
            itemsMobile : false
         }
         )

         // Testemonial carousel
         $(".testemonials").owlCarousel(
         {
            autoPlay : 5000,
            autoHeight : false,
            singleItem : true,
            pagination : false,
            transitionStyle : "fadeUp",
            itemsDesktop : [1000, 1],
            itemsDesktopSmall : [900, 1],
            itemsTablet : [600, 1],
            itemsMobile : false
         }
         );

        
     
         // Testemonial carousel
         $(".customer-slider").owlCarousel(
         {
            autoPlay : 4000,
            items : 4,
            pagination : false,

            itemsDesktop : [1000, 1],
            itemsDesktopSmall : [900, 1],
            itemsTablet : [600, 1],
            itemsMobile : false
         }
         );
         // EmpArea
         $(".Emps-slider").owlCarousel(
         {
            autoPlay : 3000,
            items : 3,
            pagination : false,
            transitionStyle : "fadeUp",
            itemsDesktop : [1000, 1],
            itemsDesktopSmall : [900, 1],
            itemsTablet : [600, 1],
            itemsMobile : false,
            stopOnHover : true
         }
         );


      }
      )
   }
   );

**Comment by alvarotrigo** [comment]
If you have any specific question just ask. Do not add big portions of code.

**Comment by meroomaher** [comment]
ahh ok I am sorry ....
