### ISSUE TITLE
On resize console error

### ISSUE THREAD

**Issue by adelivuk** [alvarotrigo/fullPage.js#1218]
I've implemented fullpage.js with wordpress and it works fine, but when I resize my browser window I keep getting -  `Uncaught TypeError: Cannot read property 'left' of undefined`.

![pic](https://cloud.githubusercontent.com/assets/6178877/7628905/8a06300e-fa28-11e4-8d7b-06dfeeb8f393.png)

As for my JS script, I only use `jQuery('#fullpage').fullpage();`.

How to remove this error?

**Comment by alvarotrigo** [comment]
Provide a link to reproduce it.

**Comment by adelivuk** [comment]
I've updated fullpage.js from `2.6.1` to `2.6.5.` and the console error is gone.

Thanks
