### ISSUE TITLE
Hide navigation of slider on first slide

### ISSUE THREAD

**Issue by anoukkolkman** [alvarotrigo/fullPage.js#1219]
Hi,

I'm trying to hide the .fp-prev when the first slide has the class active, but I can't seem to figure it out.. 
Could you help with a solution how to do it? 

I've tried :not(first-child) ~ .fp-prev and some other things, but it just doesn't work. 

Thanks in advance!

**Comment by alvarotrigo** [comment]
Why don't you just use `loopHorizontal: false,`.
