### ISSUE TITLE
Autoscroll skipping second slide.

### ISSUE THREAD

**Issue by sloyer** [alvarotrigo/fullPage.js#122]
Hello, 

I am having an issue with the autoscroll functionality. 

When scrolling down when on the first slide, the autoscroll will skip the second slide.
When scroll up from the first slide the auto scroll will once again skip the second slide.

It does not matter how many slide are in-between the first and last, it will scroll to the first or last no matter what.

Also is there a way to hide scroll bars with the scrolloverflow active? when I change the .scrollable class to hide them, I lose the functionality to scroll in the slide.

**Comment by boutzamat** [comment]
@alvarotrigo nice, it works. thank you
