### ISSUE TITLE
Lazy load for images and backgrounds 

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#1220]
As lazy load plugins don't usually work with fullPage.js due to the fact that fullPage.js doesn't use scrollbar unless the option `scrollBar` is set to `true`, a lazy load feature will be implemented in future versions of fullPage.js to make things even easier yet.

**Comment by alvarotrigo** [comment]
The new functionality has been added in fullPage.js 2.6.6
More about it [here](https://github.com/alvarotrigo/fullPage.js#lazy-loading).

**Comment by drawcard** [comment]
Hi, could I please get some advice on how to implement this for background images, ie images that are loaded into a DIV using something like "background-image:url('image.jpg');" ?

**Comment by alvarotrigo** [comment]
@drawcard  see [this answer](https://github.com/alvarotrigo/fullPage.js/issues/46#issuecomment-26509996).

**Comment by drawcard** [comment]
Thanks Alvaro for the quick response. Your example would work fine for predefined background images written in a CSS stylesheet but I'll have to figure out a way of making this work with "background-image" references in inline HTML, as my background images are being inserted via shortcodes in Wordpress and that requires use of inline declarations. Unless I'm missing something in your example :)

Failing that I might rewrite my shortcode plugin to have <img> elements placed absolutely on the page, and have the page content sit on top of it, to simulate a background image setup, while getting the benefit of the data-src attribute.

**Comment by alvarotrigo** [comment]
@drawcard then your question doesn't fit very well in this forum. You'd better ask in other place such as stackoverflow.com. Your's is a generic question that has very few to do with fullPage.js.

**Comment by drawcard** [comment]
Thanks Alvaro. Can you tell me which library you're using for the lazy load function, or if it's something custom written yourself, as that will give me a starting point to ask in those forums?

**Comment by alvarotrigo** [comment]
@drawcard none. In any case, as I said, your problem has nothing to do with fullPage.js. No matter how fullPage.js lazy load images, your problem is about lazy loading inline background images.

**Comment by drawcard** [comment]
Ok. Thanks for clarifying.

**Comment by drawcard** [comment]
Just for the benefit of anyone wanting a solution, I have made something here that takes `data-src` attributes and assigns them to the background-image property of a section DIV. It uses CSS3 transitions to fade in each section panel upon completion of the image load. It 'sort of' works for slides (I can't get the first slide to fade in, because I don't think there isn't a callback for that event, eg onSlideLoad). But this works fine otherwise.

http://codepen.io/anon/pen/jPKEvZ
