### ISSUE TITLE
Height is not changed when resizing in mobile

### ISSUE THREAD

**Issue by DominikVogt** [alvarotrigo/fullPage.js#1222]
Hello there,
i just wanted to let you know that the height is not changing when resizing the window in mobile view. It seems to work when rotating though.

Let me know if this is intended or there is a fix to that.

**Comment by alvarotrigo** [comment]
In a mobile phone you can not resize the window. I'm not sure to understand your issue...

**Comment by alvarotrigo** [comment]
Closed until provided an explanation.
