### ISSUE TITLE
need help for transition slide 

### ISSUE THREAD

**Issue by laliev** [alvarotrigo/fullPage.js#1223]
hi!) how can I make that transition from the slide and the section was like a plug pagepiling.js

**Comment by alvarotrigo** [comment]
You can't.
This is a scrolling plugin.

**Comment by laliev** [comment]
Is it possible to make the plugin pazhepiling and vertical and horizontal scrolling?

**Comment by alvarotrigo** [comment]
Nop. Just one of them.

**Comment by laliev** [comment]
may have the hacks? I really need!!!

**Comment by laliev** [comment]
the first question I asked is not correct. Could it be scrolling between slides in fullpage the same as in pagepiling?
Thank you!

**Comment by alvarotrigo** [comment]
The answer is no.

**Comment by alvarotrigo** [comment]
If you really need it, [contact me](http://alvarotrigo.com/#contact-page) for a customization of the plugin.
