### ISSUE TITLE
One Single Section `fitToSection`.

### ISSUE THREAD

**Issue by itsjms** [alvarotrigo/fullPage.js#1224]
The documentation for the one single section example states you need to only provide fullpage.js with the autoScrolling: false option. I think you should also note in the documentation to keep the page from scrolling back up to the top automatically you will need to also include the fitToSection: false option. It would be nice to be able to just use the autoScrolling: false and still allow it to fitToSection but this does not seem to work currently.

**Comment by alvarotrigo** [comment]
Yeah right. It was added after the example was created.
Thanks for mentioning it, I'll solve it.

**Comment by alvarotrigo** [comment]
The example was updated.
