### ISSUE TITLE
Problem scrolling with fix header and footer

### ISSUE THREAD

**Issue by jdelafuente** [alvarotrigo/fullPage.js#1225]
Hi Alvaro,
I have problems with the scrolling area using fixed header and footer.
The header and the footer are perfect. Well positioned... but the content area uses more space than it should and goes above footer.
The scroll of the content area / section get to the bottom of the page, overlapping the footer.
Can you help me please? May be I have to use some special css ...
Thanks in advance

**Comment by alvarotrigo** [comment]
Use the options `paddingTop` and `paddingBottom`.
