### ISSUE TITLE
Using slimscroll not for a whole section but for divs within a section

### ISSUE THREAD

**Issue by aunruh** [alvarotrigo/fullPage.js#1226]
Hey, just wanted to share how to do this. 

I'm working on a site where every section has two child-divs `.half`. In my case the child divs have 50% width, 100% height of the section. And they have content with different heights. So I need to be able to scroll inside those divs and when I reached the bottom of either divs, fullpage-js needs to go to the next section.

The problem: 
When you activate slimscroll with fullpage.js, then it will scroll both divs instead of just one.

The solution:
Don't use slimscroll with fullpage.js, but initialize it yourself. In each `.half` you will need an inner div that contains your content `.fp-scrollable`. Initialize slimscroll by yourself like this:

```javascript
jQuery('.fp-scrollable').slimScroll({
    height: window.innerHeight+'px',
    alwaysVisible: true,
    color: '#fff',
    size: '10px',
    allowPageScroll: true,
});
```

We need the class `fp-scrollable`, this way your slimscroll containers will be compatible with fullpage.js.
You may need to resize the slimscroll containers on window resize.

**Comment by alvarotrigo** [comment]
Thanks for sharing it, but this forum is dedicated to fullPage.js issues, bugs or enhancements and therefore I should close this "issue" as there's nothing in the plugin that can be done to deal with such specific case.

Anyway, this issue might be reached by Google for other people with the same problem and your solution can be very useful for them.

**Comment by chandrakailash1993** [comment]
@aunruh thanks :) this worked like a charm... wasted lot of time on this issue... cheers :)
