### ISSUE TITLE
Single slide - slidesNavigation dot is showing

### ISSUE THREAD

**Issue by drawcard** [alvarotrigo/fullPage.js#1227]
Hi,

With slidesNavigation set to true, single slides are displaying a small circle indicating the slide position. Can this be hidden in cases where there's only one slide available? This might also be the case for single sections + vertical navigation too, haven't tested yet.

**Comment by alvarotrigo** [comment]
You are not suppose to create a single slide in a section anyways. That'd be the proper way of doing it. 

But I guess I can take a look at it, as many people who seem to be using CMSs or some server side language to create the markup seem to be asking for sections with a single section.

**Comment by drawcard** [comment]
> You are not suppose to create a single slide in a section anyways. That'd be the proper way of doing it.

I know, but as you've pointed out I am building a portfolio website using Wordpress and I've been using fullpage.js for the layout :)

Thanks for looking into it.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 2.6.6.
