### ISSUE TITLE
Putting a Div on top of fullPage with overflow:scroll

### ISSUE THREAD

**Issue by gambolputty** [alvarotrigo/fullPage.js#1229]
Hello,

I searched the GitHub issues but couldn't come up with a proper solution by myself.

I am trying to put a full page Div above the fullPage site that has to be scrollable. It is `positon:fixed` so that it can bee seen from any fullPage section the user is calling it. 

It displays a collection of image thumbnails – clicking on a thumbnail navigates the user to the matching fullPage section (scenario: Gallery & Gallery overview).

What I did so far to achieve this:
1. I gave the div a css `positon:fixed` and `overflow:scroll` value
2. I put the div ID into the fullPage `fixedElements` value
3. When the Div is shown, the fullPage scrolling in the background is disabled via `$.fn.fullpage.setAllowScrolling(false, 'up, down, left, right');`

The Div is being display on top of fullPage now – but not scrollable. So:

4. additionally I put the Div ID into the fullPage `normalScrollElements` value. The Div becomes scrollable now, but so does the fullPage wrapper in the background again.

What am I doing wrong? How can I handle the fullPage site and the Div (Gallery-Thumbnail-view) separately, so that fullPage is temporarily disabled while the Div in the foreground is visible?

Best,
Gregor

**Comment by gambolputty** [comment]
Another solution that came to my mind: I could destroy and initialize fullPage again every time the Div is shown/faded out from the browser view. But that's not a good scenario on mobile browsers (performance related), isn't it?

**Comment by alvarotrigo** [comment]
Just use `normalScrollElements` and use `$.fn.fullpage.setAllowScrolling(false);`.
That should work.

If not, please provide a [jsfiddle](http://jsfiddle.net/97tbk/418/) with a reproduction of your problem.

**Comment by gambolputty** [comment]
Thank you for the quick response! :)

I did it as you wrote, but both 1. the fixed Div and 2. fullPage were still scrollable at the same time. I initialized fullPage with the option `scrollBar: true`. I removed it – it worked! :)

With `scrollBar: false` the body element stayed `overflow:visible`. Removing the option `scrollBar: true` made it `overflow:hidden` again.
