### ISSUE TITLE
normalScrollElements not working on touch device. Swipe up/down moves slides behind.

### ISSUE THREAD

**Issue by adaptifyDesigns** [alvarotrigo/fullPage.js#123]
Hi again alvarotrigo, 
while testing on mobile I discovered that swiping up/down still autoscrolls the slides even when the popup is enabled and the popup element is included in the normalScrollElements option.

I've included this as a separate issue because it is mobile specific, but it is also related to my previous thread:
https://github.com/alvarotrigo/fullPage.js/issues/120
I assume it has something to do with the touch event vs the mouse scrolling events.

Any ideas how to prevent the swipe up/down actions while the popup is open?

Thanks!

**Comment by denidip** [comment]
Hi alvarotrigo, found a similar problem in versions 2.8.8 and 2.8.9dev. The fixed element is outside wrapper, but to scroll on touch devices is not working. Tried normalScrollElements and normalScrollElementTouchThreshold, does not work ... https://goo.gl/SY4tmF

**Comment by alvarotrigo** [comment]
@denidip if you believe its a bug provide an isolated reproduction (not the link you posted, as it contains external CSS and JS and it is all minified) ideally in jsfiddle or codpen and then proceed to create a new issue.
