### ISSUE TITLE
Is possible hide slide after scrolled them?

### ISSUE THREAD

**Issue by Alexand3r3** [alvarotrigo/fullPage.js#1231]
Hi everyone!!

I'm trying to hide previous slide after I've scrolled them.

For example I have 4 slide, the last has scrollOverflow: true, option. When I reach the fourth and last slide I want hide three previous slide. How I can do it?It's possible?

I've tried with this option: 
```javascript
if(index == 3 && direction =='down'){
	$('.section0').hide();
}
```

but this doesn't work fine.

**Comment by alvarotrigo** [comment]
Why don't you just use `setAllowScrolling(false, 'up')`

**Comment by Alexand3r3** [comment]
thanks you so very much. I feel stupid for don't have seen before this option!! :D
