### ISSUE TITLE
Touch capabilities scroll

### ISSUE THREAD

**Issue by Alexand3r3** [alvarotrigo/fullPage.js#1232]
I have a section with "scrollOverflow: true" option enabled but this section has a bad and slow scroll. Is possible enable normal touch scroll for this section for a better User Experience?

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/506

You can, if you use `normalScrollElements` and whenever YOU detect they reach the top or the button, then YOU call the methods `moveSectionUp` or `moveSectionDown`.

**Comment by Alexand3r3** [comment]
Sorry but I don't understand that are you saying... :S

**Comment by alvarotrigo** [comment]
If you don't, then the answer is no.

**Comment by Alexand3r3** [comment]
I don't understand where I set the normalScrollElements option. I have this:

$(document).ready(function() {
			$('.fullpage').fullpage({
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage'],
				css3: true,
				scrollOverflow: true,
			    	scrollingSpeed: 700,


				afterLoad: function (anchorLink, index) {
				    var loadedSection = $(this);

				    //using index for animate menu comparison
				    if (index == 4) {
				        $('.main-nav').delay(100).animate({
				            top: '0%'
				        }, 1500, 'easeOutExpo', function () {
				            $('.main-nav').fadeIn(700, function () {
				            });
				        });
				        $('.arrow').hide();
				    }
				},
			    onLeave: function(index, nextIndex, direction){
			        var leavingSection = $(this);

			        //after leaving section 3
			        if(index == 4 && direction =='up'){
			            setAllowScrolling(false, 'up')
			        }
			    },
			});
		});

I have noticed that if I set option 
scrollOverflow: false,
responsive: 1024,

the scroll touch works perfectly.

You can see it on my test page on touch devices: http://demo.creazionesito.biz/index_touch.aspx

Possible is slimscroll js plugin that do create this issue?

**Comment by alvarotrigo** [comment]
> Possible is slimscroll js plugin that do create this issue?

Yeah, as I said before:

> Related with #506
