### ISSUE TITLE
The slide class from bootstrap carousel is in conflict with fullPage.js

### ISSUE THREAD

**Issue by ZetCoby** [alvarotrigo/fullPage.js#1233]
in bootstrat the carousel component has a class called slide, `<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">` because of this class on resize fullpage wraps it in divs with class `fp-slides`

**Comment by alvarotrigo** [comment]
Use the option `slideSelector`

**Comment by sameeravithanage** [comment]
where can i find the other selector options?

**Comment by S-Rahemi** [comment]
excellent

**Comment by S-Rahemi** [comment]
Also you can set display to grid system to fixed from top carousel

.fullpage .fp-section.fp-table,
.fullpage .fp-slide.fp-table {
    display: grid;
    table-layout: fixed;
    width: 100%;
    vertical-align:bottom;
}
