### ISSUE TITLE
Ability to set start slide for section 

### ISSUE THREAD

**Issue by lanzs** [alvarotrigo/fullPage.js#1234]
Couldn't found it in faq/options, do you plan to make special option for this?
I tried to make it with $.fn.fullpage.moveTo('sectionName', slideNumber); but it slides you to 'sectionName' and I want just to set initial start slide for section.

**Comment by alvarotrigo** [comment]
It's detailed in the docs.
Use the `active` class for the slide and for the section containing that slide.
