### ISSUE TITLE
Method `onSlideLeave` should give `nextSlideIndex` like `nextIndex` in `onLeave`

### ISSUE THREAD

**Issue by eugene-lazarev** [alvarotrigo/fullPage.js#1235]
Now, `onSlideLeave` method give us 4 arguments:  `anchorLink`, `index`, `slideIndex`, `direction`.
On the other hand, `onLeave` method give us 3 arguments: `index`, `nextIndex`, `direction`.

So, it would be awesome if `onSlideLeave` give something like `nextSlideIndex` (same as `nextIndex` in `onLeave`).

Thanks.

**Comment by alvarotrigo** [comment]
Right.
I take note of it. Thanks for sharing it.

**Comment by alvarotrigo** [comment]
The new parameter `nextSlideIndex ` has been introduced in fullPage.js 2.6.6.
You can see it now [in the docs](https://github.com/alvarotrigo/fullPage.js#onslideleave-anchorlink-index-slideindex-direction-nextslideindex).
