### ISSUE TITLE
`keyboardScrolling` option should be separated for horizontal and vertical one

### ISSUE THREAD

**Issue by eugene-lazarev** [alvarotrigo/fullPage.js#1236]
In my project, I would like to switch off horizontal scrolling by keyboard arrows but keep the vertical one switched-on.

**Comment by alvarotrigo** [comment]
Yeah. Not possible at the moment. 
You can always do something similar to what I suggested [here](http://stackoverflow.com/a/29822757/1081396) and disable the keyboard with `setKeyboardScrolling(false)` but then assign the fullpage functions `moveSlideRight` and `moveSlideLeft` to your own keydown events:
```javascript
$(document).keydown(function (e) {
    var shiftPressed = e.shiftKey;

    switch (e.which) {
        //up
        case 38:
        case 33:
            $.fn.fullpage.moveSlideLeft();
            break;

        //down
        case 40:
        case 34:
            $.fn.fullpage.moveSlideRight();
            break;

    }
});
```

**Comment by alvarotrigo** [comment]
A new functionality for the function `setKeyboardScrolling` has been introduced in fullPage.js 2.6.6.
Now, the function admits a `directions` parameter:

More in the docs: 
https://github.com/alvarotrigo/fullPage.js#setkeyboardscrollingboolean-directions
