### ISSUE TITLE
Feature request: cancel scrolling if `onLeave` returns false

### ISSUE THREAD

**Issue by eugene-lazarev** [alvarotrigo/fullPage.js#1239]
...or something like this.

I have the case when I should cancel movement after event happened (scroll or touch event or whatever that triggered `moveTo`). Try to explain step-by-step:

1. I scrolled via mouse
2. Section should move now
3. But at first method `onLeave` executing
4. I'm calculating something here
5. If my rule here solves that movement should be cancelled, I want to give fullPage know that it should abort its plan about movement

So, I see the best way to do it: return false in `onLeave` method. Is my logic correct?

**Comment by alvarotrigo** [comment]
Already proposed [here](https://github.com/alvarotrigo/fullPage.js/pull/1194)
