### ISSUE TITLE
Continuous horizontal slider

### ISSUE THREAD

**Issue by fmendoza** [alvarotrigo/fullPage.js#124]
Buenas

Any ideas in how to get a circular slider?

**Comment by NathanJudson** [comment]
Anyone managed to achieve this modification?

**Comment by cwolfie** [comment]
Heya all,

Anyone got Circular Looping with Slides working?

Thanks

**Comment by alvarotrigo** [comment]
@NathanJudson @cwolfie I customized the plugin to someone requesting a customization like a year ago. [Feel free](http://alvarotrigo.com/#contact-page) to do the same.

**Comment by horans** [comment]
my "workaround":
1. when scroll to the last slide, start a `setTimeout()` for the display time, then "fade out" all slides. 
2. when scroll to the first slide, start a `setTimeout()` for the "pull back" action, then "fade in" all slides.

js:

    onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){
        var sect = $('.full-page .section:eq(' + (index - 1) + ')');
        var slid = sect.find('.slide');
        var leng = slid.length;
        if(nextSlideIndex === (leng - 1)){
            setTimeout(function(){
                slid.addClass('transparent');
            }, 4100);
        }
        if(nextSlideIndex === 0){
            setTimeout(function(){
                slid.removeClass('transparent');
            }, 600);
        }
    }

css:

    .full-page .section {
        transition:all 0.5s ease-in-out;
    }
    .transparent {
        opacity:0;
    }

**Comment by CreativeWolf** [comment]
@horans Thank you for sharing. Although, it didn't work for me.

**Comment by horans** [comment]
i was using ".full-page" rather than default "#fullpage" in the code. (comment updated.)

**Comment by omarel1** [comment]
Thanks Alvaro, I just send you a private message regarding a workaround.

It would be really great for the workaround if instead of simply preventing the user from moving on at the last photo, it continued to the right and started at the first photo again.

The way superslide js does it.
http://archive.nicinabox.com/superslides/#1

**Comment by holyzfy** [comment]
There is a solution #1192

**Comment by gy134340** [comment]
thanks a lot

**Comment by alvarotrigo** [comment]
Available now through the [fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/)

**Comment by Splintex** [comment]
`continuousHorizontal: true` doesn't work correct with extension ContinuousHorizontal. I was trying on [demo page](http://alvarotrigo.com/fullPage/extensions/continuousHorizontal.html#firstPage).
Slider jumps to the first slide after reached last slide. @alvarotrigo could you check, please?

**Comment by alvarotrigo** [comment]
@Splintex steps to reproduce it? OS and device?
It seems to work completely fine for me on the link you gave.

**Comment by Splintex** [comment]
macOS 10.12.1 (16B2555) Chrome Version 54.0.2840.98 (64-bit)

**Comment by alvarotrigo** [comment]
@Splintex  steps to reproduce it?

**Comment by Splintex** [comment]
just open link and  change slides http://alvarotrigo.com/fullPage/extensions/continuousHorizontal.html#3rdPage
