### ISSUE TITLE
How to stop scroll when select is open?

### ISSUE THREAD

**Issue by ian90911** [alvarotrigo/fullPage.js#1240]
Here is a section that have select element,
when I click select element and scroll  down the list,
page scroll will be fired.
How to stop scroll when select is open?

my fullpage setting:
```javascript
$(document).ready(function () {
$('#divFullpage').fullpage({
            navigation: true,
            navigationPosition: 'right',
            verticalCentered: false,
            scrollOverflow: true,
            paddingTop: '40px',
            paddingBottom: '40px',
            normalScrollElements: '#divFirst,#ddlHeaderTime_Hour, #divSecond, #divThird, #divFourth',
});
$.fn.fullpage.setAllowScrolling(false);
```

**Comment by alvarotrigo** [comment]
Check out [this question](http://stackoverflow.com/questions/30185586/fullpage-js-scrolling-on-top-of-select-element-in-ie-and-firefox/30188977#30188977) and [the answer I provided](http://stackoverflow.com/a/30188977/1081396).

**Comment by ian90911** [comment]
I use IE10.
My page use button to control section page next or back,
and I set AllowScrolling to false at ```$(document).ready()``` first,
not only when at click select element.
so the page should only scroll by button,
but it scroll when I scroll select list.

**Comment by alvarotrigo** [comment]
Provide a reproduction of your issue. It shouldn't be scrolling at all if you use `autoScrolling:false.`
