### ISSUE TITLE
Stop page scrolling on Page Refresh

### ISSUE THREAD

**Issue by oneal387** [alvarotrigo/fullPage.js#1241]
This is not an issue more of just a question.

Is there away when you refresh the page or slide in the browser to have the page or slide just refresh and stay on its link and not have the whole script refresh and then scroll and/or slide to that page link?

**Comment by alvarotrigo** [comment]
It sounds like you want to use AJAX for it. 
Probably on the `onLeave` or on the `afterLoad` callback.

If you don't know how to use ajax I would encourage you to ask in http://stackoverflow.com/
