### ISSUE TITLE
Menu item active for multiple sections

### ISSUE THREAD

**Issue by anoukkolkman** [alvarotrigo/fullPage.js#1242]
I can't seem to find it anywhere, but is it possible to let a menu item have the class active for multiple sections?

Like
 ```
<li data-menuanchor="cases" class="active"> <a href="#cases">Our work</a> </li>
```
must have the class active for section "cases" and for section "customers". 

It's working for only the section "cases" but I don't know how to add a second section.

**Comment by alvarotrigo** [comment]
Yeah. Just add the active class by using the callbacks the plugin provides, such as `afterLoad` or `onLeave`.

Or use the class added to the body to do so:

```css
.fp-viewing-secondPage-0 #myMenu #section2{
   background: red;
}
```

**Comment by AliHussain85** [comment]
How do I suppose to use callbacks?
