### ISSUE TITLE
Mousewheel fix for older versions of Firefox

### ISSUE THREAD

**Issue by gyopiazza** [alvarotrigo/fullPage.js#1244]
Hello! While using this plugin in a project I found out that the mousewheel is not working for some versions of Firefox (particularly v16).

The fix is quite simple, just add the `DOMMouseScroll` event handler to the others.

**Inside the function removeMouseWheelHandler()**
```
document.removeEventListener('DOMMouseScroll', MouseWheelHandler, false); //Old Firefox
```

**Inside the function addMouseWheelHandler()**
```
document.addEventListener('DOMMouseScroll', MouseWheelHandler, false); //Old Firefox
```

Hope it helps, thanks for this piece of cake! :)

**Comment by alvarotrigo** [comment]
Firefox is in version 40 right now...

**Comment by gyopiazza** [comment]
I know... but Firefox 16 was released less than 3 years ago. I've been reported people being stuck with older versions of FF because they can't update (due to their old OSX).

It's just a small fix I thought to share, since fullPage even supports IE8.

**Comment by alvarotrigo** [comment]
@gyopiazza feel free to add a pull request if you want.

**Comment by alvarotrigo** [comment]
Otherwise let me know and I'll make the changes.

**Comment by gyopiazza** [comment]
Sure, there you go:
https://github.com/alvarotrigo/fullPage.js/pull/1246

I actually didn't do it before for the shame. ;)

**Comment by alvarotrigo** [comment]
I was not able to merge your PR, but I've solved in the fullPage.js 2.6.6.
Thanks for it!

**Comment by gyopiazza** [comment]
Thank you!

**Comment by alvarotrigo** [comment]
It seems [this is causing problems for some users](http://stackoverflow.com/questions/32550549/fullpage-js-onleave-firing-twice-when-return-false-in-all-browsers-but-chrome/32568174?noredirect=1#comment52999086_32568174) as Firefox listen to both events.

**Comment by alvarotrigo** [comment]
I might go for a way of detectin which handler to use as described [here](https://developer.mozilla.org/en-US/docs/Web/Events/wheel).

```javascript
    // detect event model
    if ( window.addEventListener ) {
        _addEventListener = "addEventListener";
    } else {
        _addEventListener = "attachEvent";
        prefix = "on";
    }

    // detect available wheel event
    support = "onwheel" in document.createElement("div") ? "wheel" : // Modern browsers support "wheel"
              document.onmousewheel !== undefined ? "mousewheel" : // Webkit and IE support at least "mousewheel"
              "DOMMouseScroll"; // let's assume that remaining browsers are older Firefox

    window.addWheelListener = function( elem, callback, useCapture ) {
        _addWheelListener( elem, support, callback, useCapture );

        // handle MozMousePixelScroll in older Firefox
        if( support == "DOMMouseScroll" ) {
            _addWheelListener( elem, "MozMousePixelScroll", callback, useCapture );
        }
    };
```
