### ISSUE TITLE
Height more 100%

### ISSUE THREAD

**Issue by evgenyshev** [alvarotrigo/fullPage.js#1247]
I apologize for my clumsy English. I understand that a plugin called "FullPage", but maybe you could tell how to make a height of more than 100%, if the content does not fit? "scrollOverflow" — not for me.

**Comment by alvarotrigo** [comment]
`scrollOverflow` is what you want.

**Comment by evgenyshev** [comment]
No. It simply adds a scroll. And I say to increase the height of the block, that is, that he went beyond the visible part of the window.

**Comment by evgenyshev** [comment]
in other words, something like: height: auto; min-height: 100%. Possible?

**Comment by alvarotrigo** [comment]
It only make sense if you are going to use `autoScrolling:false`.

Check [this topic](https://github.com/alvarotrigo/fullPage.js/issues/1044)

**Comment by evgenyshev** [comment]
No. min-height: 100% not working

**Comment by alvarotrigo** [comment]
This is not an issue of fullPage.js but of CSS. 
You should ask in other place such as http://stackoverflow.com/ where they will provide you with better answers.
