### ISSUE TITLE
mobile device : not correctly resized after orientation changed

### ISSUE THREAD

**Issue by AlonsoZeng** [alvarotrigo/fullPage.js#1248]
I am developing mobile app with fullpage.js, which was fine at first. But then I found that after devices' orientation changed from landscape to portrait, the resizing would be a little bit shorter than the window's height, about 2 or 3 pixels. Then I wrote a few line of code to fix it . Not a big deal ,but i think no harm to tell you . Hope it's not my problem.
ps: test enviroment is safari in iphone5

**Comment by alvarotrigo** [comment]
I've tested the [demo page](http://alvarotrigo.com/fullPage/) in my iPhone 5, in Safari. Everything seems to work ok.
When turning it to landscape mode, the top and bottom bars will hide part of the site, but that issue doesn't have a solution unless you avoid using anchors. 

If are more specific with your problem (or provide some pictures of it) I might open the topic again.

**Comment by AlonsoZeng** [comment]
seemed to be jquery mobile's problem. after unlinking with jquery mobile, the problem solved
