### ISSUE TITLE
button links not working in IE

### ISSUE THREAD

**Issue by acandael** [alvarotrigo/fullPage.js#1249]
Hi,

I noticed that links to fullPage.js sections don't scroll to the designated sections 'activities' and 'team' when clicked in IE.

the website is online at:

http://superintendant-rabbit-82576.bitballoon.com/

Try to push the buttons 'Onze Activiteiten' and 'Ons Team' in IE, and you'll notice the page doesn't scroll to the designated sections.

This works in Chrome and Firefox, but not in any version of IE. 

the markup for my buttons looks like this:

    <div class="cta">
      <form action="#activities" method="get">
        <button class="activiteiten">Onze Activiteiten</button>
      </form>
      <form action="#team" method="get">
        <button class="team">Ons Team</button>
      </form>
    </div>

The Javascript on the page looks like this:

    <script type="text/javascript">
     $(document).ready(function() {
       $('#fullpage').fullpage(
         {
         anchors: ['hero', 'activities', 'about', 'team', 'referrals'],
         autoScrolling: false,
         fitToSection: false
         }
       );
       $('.bxslider').bxSlider({
          adaptiveHeight: true
       });
    }); 
    </script>

my source repository can be viewed at:

https://github.com/acandael/actionmaker/tree/master/source

Does anyone know why the links don't work in IE?

Thanks for your help,

**Comment by alvarotrigo** [comment]
You are not using normal links with anchors. You are adding a new URL with parameters in it: `?form-name=form+2`.

It seems IE is deleting the anchors in the URL when submitting the form. 
That has nothing to do with fullPage.js.

YOu can check other people having similar problems:
http://stackoverflow.com/questions/693545/is-it-possible-to-add-an-anchor-to-a-form-post-get
http://community.sitepoint.com/t/go-to-anchor-after-form-submit-not-working-ie/53951
https://www.google.co.uk/search?q=anchor+action+form+IE&oq=anchor+action+form+IE+&aqs=chrome..69i57.4303j0j4&sourceid=chrome&es_sm=0&ie=UTF-8

**Comment by acandael** [comment]
Hi Alvaro,

yeah, adding an anchor in front of the button element - partially - fixed the issue.

        <div class="cta">
      <a name="#activities"></a>
      <form action="index.html#activities" method="get">
        <button class="activiteiten">Onze Activiteiten</button>
      </form>
      <a name="#team"></a>
      <form action="index.html#team" method="get">
        <button class="team">Ons Team</button>
      </form>
    </div>

greetings,

Anthony
