### ISSUE TITLE
Jump to 1st slide after N slide

### ISSUE THREAD

**Issue by posthack** [alvarotrigo/fullPage.js#1250]
Here's my page: http://imatte.ru/work/term

After scroll from 8 slide to 9 slide slider jumps to 1st slide, and just after that to 9 slide.

Can't understand what is wrong. Help, please.

**Comment by alvarotrigo** [comment]
Reproduce your problem in [a fiddle](http://jsfiddle.net/97tbk/418/) to isolate it form any other external code.
