### ISSUE TITLE
Dynamic anchors?

### ISSUE THREAD

**Issue by nightcoregirl** [alvarotrigo/fullPage.js#1252]
I am trying to put the anchors in dynamically using a variable. 

In console I keep getting the error,
Syntax error, unrecognized expression: #

When I remove the hash like this var stringCut = classes.match(/#\S+/g); the plugin works but every section has a URL like this, 

http://mysite.com/blogs#undefined

Each section is #undefined but the plugin doesn't break. 

How can I successfully use a variable to create anchors and maintain the anchor titles?

**Comment by alvarotrigo** [comment]
You have to provide the anchors as an array in the `anchors` option of the plugin as specified in the docs:
```javascript
 $('#fullpage').fullpage({
        anchors:['firstPage', 'secondPage', 'thirdPage']
});
```

So you can do something like:
```javascript
var myAnchors = ['firstPage', 'secondPage', 'thirdPage'];
 $('#fullpage').fullpage({
        anchors: myAnchors
});
```

Or even:

```javascript
var myAnchors = [];

for(var i = 1; i<4; i++){
    myAnchors.push('page' + i);
}

 $('#fullpage').fullpage({
        anchors: myAnchors
});
```

**Comment by nightcoregirl** [comment]
I will try the third method. Your second method is pretty much what we have done except that we are getting the string for "var myAnchors" from the class names of a list of divs.

**Comment by alvarotrigo** [comment]
This is not a fullPage.js related issue in any case.
This is an issue of passing variables between the serverside and the client side. You'll find much more info in other places about this.

**Comment by alvarotrigo** [comment]
Since fullpage.js 2.6.8 it is possible to define anchors using the `data-anchor` tag:

[Documentation details: ](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides).

> Note that section anchors can also be defined in the same way, by using the data-anchor attribute, if no anchors array is provided.
