### ISSUE TITLE
slidesNavigation: false not working

### ISSUE THREAD

**Issue by notflip** [alvarotrigo/fullPage.js#1253]
Hi,

Great plugin for starters! I'm setting slidesNavigation to false but it's still showing the 2 white triangles left and right.

    $('#page').fullpage({
        slidesNavigation: false
    });

**Comment by alvarotrigo** [comment]
From the docs:

> **slidesNavigation:** (default false) If set to true it will show a navigation bar **made up of small circles** for each landscape slider on the site.

That's not the option you want...
Just use css to hide the arrows.

**Comment by notflip** [comment]
Hi,

Found the solution, I can hide them with

    controlArrows: false

**Comment by alvarotrigo** [comment]
Or just use the option `controlArrows`:

> controlArrows: (default true) Determines whether to use control arrows for the slides to move right or left.
