### ISSUE TITLE
Responsive javascript

### ISSUE THREAD

**Issue by svdg** [alvarotrigo/fullPage.js#1254]
How to make the padding for top and bottom responsive for different sizes?

<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		paddingTop: '100px',
		paddingBottom: '200px',
        fixedElements: '#header',
		anchors:['home', 'voordelen', 'zoeken'],
    });
});
</script>

**Comment by alvarotrigo** [comment]
Use your own padding in CSS and use media queries.

**Comment by svdg** [comment]
Ah, OK. Thanks!
