### ISSUE TITLE
Which slide the section is after it loads

### ISSUE THREAD

**Issue by inigocanedo** [alvarotrigo/fullPage.js#1255]
Hi,
Is there a way to know which slide the section is after it loads ?

I have a fixed element (the logo) that should only be visible in the first slide.
But since fullPage.js remembers the last slide the user were in each section, I'm having trouble making that fixed element disappear when going from a (let's say) Section 2/Slide 1 to Section 3/Slide 2
My idea is to check which slide the section is after it loads, and, if is not the first slide, my fixed element should go away.

You can see it working here:
http://avec.mx/clientes/brodeer/
(Right now you may navigate using the arrow keys)

Any help would be appreciated.
Thanks

**Comment by alvarotrigo** [comment]
Use the callback `afterSlideLoad` or even `onLeave` with the `nextIndex` parameter.

**Comment by inigocanedo** [comment]
I already did that and couldn't make it work. Apparently afterSlideLoads only works after manually changing the slide, not after changing section:

        //Cambio de Slide
        onSlideLeave: function( anchorLink, index, slideIndex, direction){
            var leavingSlide = $(this);

            //De la primer Slide a la derehca
            if(slideIndex == 0 && direction == 'right'){
                $('#logo').addClass('movido');
            }

            //De la primer Slide a la derehca
            else if(slideIndex == 1 && direction == 'left'){
                $('#logo').removeClass('movido');
            }
        },
        //Termina Cambio de Slide
        
        //Quita el Class al logo cada que cambia de sección
        onLeave: function(index, nextIndex, direction){
            var leavingSection = $(this);
            
            $('#logo').removeClass('movido');
            
        },
        
        //Checa que slide es y en base a eso agrega o quita la class
        afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
            var loadedSlide = $(this);

             //Si el Slide Sí es el Primero
            if(slideIndex == 0){
                $('#logo').removeClass('movido');
            }

            //Si el Slide NO es el Primero
            else {
                $('#logo').addClass('movido');
            }
        },
        //Termina Cambio de Sección

Thanks

**Comment by alvarotrigo** [comment]
> Apparently afterSlideLoads only works after manually changing the slide, not after changing section:

Doesn't look like so:
http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage/1

**Comment by inigocanedo** [comment]
It triggers afterSlideLoad when I click the link, but in normal navigation through the page it wont call it again after changing section.

Changing section only triggers aferLoad, but no afterSlideLoad. I also check it on your example :-(

Any ideas?
Thank you for your help

LDI Iñigo Cañedo

**Comment by alvarotrigo** [comment]
> Any ideas?

I gave you a couple in my previous post. Just read it carefully.

**Comment by inigocanedo** [comment]
Sorry, I has all this time following this conversation through my e-mail (and it was not showing the full answers you wrote).

I looked for a '0' in the class added to the body and it's now working as I wanted to.

Thank you very much!
