### ISSUE TITLE
Responsive height

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#1256]
Disabling `autoScrolling` when the viewport `height` is less than a value is something I find quite useful when dealing with small screens such as the ones of some tablets, which `width` can be quite big when turning the device into landscape position but their `height` is quite small. 

Something like the current `responsive` option working for the `width` could be done with the `height` as well.

**Comment by salmanpatnee** [comment]
Could you please provide a sample code snippet it will be helpful.

**Comment by alvarotrigo** [comment]
An option `responsiveHeight` has been introduced in fullPage.js 2.6.6.
