### ISSUE TITLE
Detect the end of sections / scroll down/up

### ISSUE THREAD

**Issue by omaribarra** [alvarotrigo/fullPage.js#1259]
Is there any way to detect if the user scrolls down but there aren any sections?

Example
Detect that the user goes to the end of slides and when he want to navigate down an alert shows "this is the end of the page "

thanks in advance

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any option for it. 
I'll consider it for a future.

**Comment by omaribarra** [comment]
Thanks a lot, for now i had modified the core, this is for a custom footer functionality, when he scroll down the footer shows up.

**Comment by alvarotrigo** [comment]
I believe it doesn't make much sense to create another callback when you can use the existent ones `afterLoad` or `onLeave` to detect the last or 1st section.

By just using its index you can accomplish it:
```javascript
afterLoad: function(anchorLink, index){
     //if last section
     if(index == $('.section').length){
     }
}
```

You can use `onLeave` for the same exact purpose.
