### ISSUE TITLE
Change orientation

### ISSUE THREAD

**Issue by svdg** [alvarotrigo/fullPage.js#1260]
Is there a way to detect orientation on mobile devices? My sections does not fit when in landscape mode, but are ment for portrait mode. So a nice solution would be when turned 90 degrees: (message) please turn your device to portrait mode.

**Comment by alvarotrigo** [comment]
That has nothing to do with fullPage.js. 
You can do that with javascript. I'd recommend you to ask in other places such as http://stackoverflow.com/
