### ISSUE TITLE
Responsive is not working

### ISSUE THREAD

**Issue by omaribarra** [alvarotrigo/fullPage.js#1261]
Sorry, with the update of fullpage.js the responsive function stop working even on the demo, i have tested it on a cellphone with 600px width.

I have also place a console.log in the responsive function but it doesnt show up

**Comment by alvarotrigo** [comment]
The [responsive example](http://alvarotrigo.com/fullPage/examples/responsive.html) is working as expected.



> I have also place a console.log in the responsive function but it doesnt show up

You can not place anything in there... just a value (600, 900...).

From the docs:

> **responsive:** (default 0) A normal scroll (autoScrolling:false) will be used under the defined width in pixels. A class fp-responsive is added to the plugin's container in case the user wants to use it for his own responsive CSS. For example, if set to 900, whenever the browser's width is less than 900 the plugin will scroll like a normal site.

**Comment by omaribarra** [comment]
It is not working on mobile devices but now i figured out why, in your demo  http://alvarotrigo.com/fullPage/examples/responsive.html you have the  fullPage 2.6.0 CSS an this css have: 
html, body {
     margin: 0; 
     padding: 0; 
     overflow:hidden; 

    /*Avoid flicker on slides transitions for mobile phones #336 */
     -webkit-tap-highlight-color: rgba(0,0,0,0); 
}

this prevent the scroll on mobile devices 

I only have updated this fullPage 2.6.0 to the last one  fullPage 2.6.4


cheers!

**Comment by alvarotrigo** [comment]
> It is not working on mobile devices but now i figured out why, in your demo

If your phone has more than 900px width, don't expect to do anything different.

**Comment by omaribarra** [comment]
I only have updated this fullPage.css 2.6.0 to the last one fullPage.css 2.6.4

this is the solution to scroll into the devices 

at least this fixed my problem

**Comment by THER10N** [comment]
i've done some update, but the problem still exists !
[this page](http://lvrbkv.ru)

**Comment by alvarotrigo** [comment]
@THER10N check it again, because neither your CSS or your JS file are the latest 2.7.5.
