### ISSUE TITLE
Feature request: beforeLeave() and cancelMove()

### ISSUE THREAD

**Issue by russellbrown** [alvarotrigo/fullPage.js#1262]
It would be really great if there was a way to hook into a `beforeLeave(index, nextIndex, direction)` callback and halt the normal movement between sections with a `cancelMove()` method.

This is because in some cases I don't want the next scroll/swipe to move to the next section but to trigger something else within the current section instead, like an animation or something.  For example:

```html
...
<section>
  <p>This paragraph appears from the start</p>
  <p class="hidden">This one fades in with the next swipe</p>
</section>
...
```

```javascript
$('#fullpage').fullpage({
  beforeLeave: function(index, nextIndex, direction){
    var leavingSection = $('#fullpage section').eq(index-1);
    if (leavingSection.find("p.hidden").length > 0) {
      $.fn.fullpage.cancelMove();
      leavingSection.find("p.hidden").removeClass("hidden");
    }
  }
});
```

**Comment by alvarotrigo** [comment]
Related with [this pull request]https://github.com/alvarotrigo/fullPage.js/pull/1194).

It will be added in the next release.

**Comment by russellbrown** [comment]
Awesome thanks, I'll keep my eyes open for that.  Really great plugin by the way, thank you.
