### ISSUE TITLE
Re: Issue #136

### ISSUE THREAD

**Issue by Im4boardn** [alvarotrigo/fullPage.js#1264]
Thanks for a great plug-in! I've gotten really far, but my client is asking for the same functionality as issue #136. I want to prevent scrolling on the secondary slides (the second and third horizontal, but not the first). I wish I understood your instructions in the opened and closed issue #136, but I don't. Can you please simplify the steps for me? I tried with the normalScrollElements, but it's disabling the scrolling on the whole section and I only want it on the second and third slides of that section. 

Please help! Thanks!

**Comment by Im4boardn** [comment]
I kept trying, using a wrapper that I had within each slide I didn't want to be able to scroll vertically as the normalScrollElements, but I'm still able to scroll up from them, just not down. Is there a way to fix this so I can't scroll up either?

**Comment by alvarotrigo** [comment]
> I want to prevent scrolling on the secondary slides (the second and third horizontal, but not the first). I wish I understood your instructions in the opened and closed issue #136, but I don't.

Just use the callbacks `afterSlideLoad` or `onSlideLeave` to call the function `$.fn.fullpage.setAllowScrolling(false, 'top bottom');`

**Comment by Im4boardn** [comment]
Can you please simplify further? What I'm doing isn't working...

afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
	var loadedSlide = $(this);

            //second slide of the second section (supposing #secondSlide is the
            //anchor for the second slide		
            if(index == 2 && slideIndex == 'secondSlide'){
                        $.fn.fullpage.setAllowScrolling(false, 'up, down');
	}
}

Also, by "anchor" for the slide you mean "data-anchor" correct?

**Comment by alvarotrigo** [comment]
The `slideIndex` is an index, not an anchor.
Check that.

`slideIndex == 'secondSlide'`

**Comment by Im4boardn** [comment]
Thank you! You rock!

**Comment by Im4boardn** [comment]
What if I want to be able to scroll down, but not up? I tried:

					if(index == # && slideAnchor == 'slideAnchor'){
						$.fn.fullpage.setAllowScrolling(false, 'up');
					}
					if(index == # && slideAnchor == 'slideAnchor'){
						$.fn.fullpage.setAllowScrolling(true, 'down');
					}

**Comment by Im4boardn** [comment]
This is all breaking if you click randomly for some reason... Is that a bug?

**Comment by Im4boardn** [comment]
This functionality is breaking when I click on one of the links to an anchor link. Is that a bug?

**Comment by alvarotrigo** [comment]
I'm not sure to understand what you mean. Can you explain it again or create a jsfiddle reproducing the issue?

And yeah, the down exist, check [the docs](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions).
