### ISSUE TITLE
Jumpy on mousewheel

### ISSUE THREAD

**Issue by Im4boardn** [alvarotrigo/fullPage.js#1265]
Is it possible to use https://github.com/fatlinesofcode/jquery.smoothwheel or https://github.com/simov/simplr-smoothscroll to smooth out the jumpiness of scrolling with a mousewheel?

**Comment by alvarotrigo** [comment]
Nop.

**Comment by Im4boardn** [comment]
So you have no suggestions other than not to have any overflow?

**Comment by alvarotrigo** [comment]
I don't know what does the `overflow` has to do here.
I'm talking about `autoScrolling`.

**Comment by Im4boardn** [comment]
Will I still be able to turn off vertical scrolling on second and third horizontal slides and have no auto scrolling? I have overflow that scrolls up over the cover images on all slides, like a parallax cheat. It currently scrolls up super choppy. The client wants to be able to scroll a div over each cover background image manually. Thanks for your help!
