### ISSUE TITLE
PreLoader?

### ISSUE THREAD

**Issue by jacobkossman** [alvarotrigo/fullPage.js#1266]
Is it possible to make this work with a preloader? I'm getting feedback from users with slower internet saying that the sections are showing up all jumbled together and i'd love for a simple loading effect until it's all ready? Is something like this possible?

**Comment by alvarotrigo** [comment]
I don't see why not. But that's not a fullPage.js issue. 
Just add a loader as you would do in any other site. 

[Lazy loading of images and backgrounds will soon be implemented in fullPage.js](https://github.com/alvarotrigo/fullPage.js/issues/1220), but meanwhile, you can use for the backgrounds the technique I recommended [in this topic](https://github.com/alvarotrigo/fullPage.js/issues/46#issuecomment-26509996).
