### ISSUE TITLE
How to slideshow autoplay?

### ISSUE THREAD

**Issue by salmanpatnee** [alvarotrigo/fullPage.js#1269]
Hey, nice plugin
 I'm using fullpage.js in my second project. i want to know that how i can auto play slideshow i'm using this example http://alvarotrigo.com/fullPage/examples/navigationV.html#secondPage/1 could you please tell me? it;s really urgent looking forward to you

**Comment by alvarotrigo** [comment]
Use the search in this forum, you'll find it.

**Comment by salmanpatnee** [comment]
Could you please give me the link?

**Comment by alvarotrigo** [comment]
I believe my search skills are the same as yours :)
Give it a try.

**Comment by salmanpatnee** [comment]
Thank you.
