### ISSUE TITLE
On Normal scroll ) How to change scroll amount, to move to next section ? 

### ISSUE THREAD

**Issue by junghoon-lee** [alvarotrigo/fullPage.js#1270]
Hi thank you for the great script.

I found when using normal scroll feature, mobile devices' touch functions are working so well, 

so I want to use the normal scroll, and I setup the 'clearTimeout(scrollId2)' 1000 to 100.
 now when I wheel-scroll over than half, after 0.1 sec, next section automatically fits to the screen. 
but less than half scrolled, the current section fits to the screen.

What I wanna do is, even if I wheel scroll less than half (like only once or twice of wheel scrolled), next section fits to the screen. 

How can I setup the scroll amount to do that? 

and if I could, I want one more,to make it work that way better. 
[][] when touch zoom has activated more than original zoom amount, the fitting function doesn't work. [][]
so that works for people to look into it easily with pinch zooming.

**Comment by alvarotrigo** [comment]
You can not change the `fitToSection` behavior. The plugin doesn't provide such option.

> and if I could, I want one more,to make it work that way better. 
> [][] when touch zoom has activated more than original zoom amount, the fitting function doesn't work. [][]
> so that works for people to look into it easily with pinch zooming.

You can turn off or on the fitting feature by using the provided function [`$.fn.fullpage.setFitToSection`](https://github.com/alvarotrigo/fullPage.js#setfittosectionboolean).
