### ISSUE TITLE
How to set scrollOverflow false on some section?

### ISSUE THREAD

**Issue by salmanpatnee** [alvarotrigo/fullPage.js#1271]
Hy, this is a Great plugin.
i want to know how i can set scrolloverflow false on a specific section for example i want to just disable only on a one section and enable on all other 3 or 4 section. help please

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such an option.
`scrollOverflow` will detect whether or not your section content is bigger than the viewport and in that case it will create the scroll bar.
Otherwise, the scollbar won't be created.

**Comment by salmanpatnee** [comment]
Look at here i'm using revolution slider and that what i'm getting http://mim.raw.agency/
slides coming beneath each other

**Comment by alvarotrigo** [comment]
Sounds a like a very specific problem you have with your own code inside the slider.
As I said, fullpage.js doesn't provide a way to disable scrollOverflow only in some sections.

**Comment by salmanpatnee** [comment]
Brother, if i disable scrollOverflow the slider works fine but i lost the scroll functionality that i want on some sections :-(

**Comment by salmanpatnee** [comment]
any otherway ?

**Comment by alvarotrigo** [comment]
Yeah, you probably can disable it manually by changing the necessary CSS.

If you don't know how to do it, [contact me](http://alvarotrigo.com/#contact-page).

**Comment by salmanpatnee** [comment]
Thank you. I did it.

**Comment by tayyabroy786** [comment]
How?

**Comment by alvarotrigo** [comment]
This is possible since quite a few time ago. As detailed in the docs:

> In order to prevent fullpage.js from creating the scrollbar in certain sections or slides use the class `fp-noscroll`. For example: `<div class="section fp-noscroll">`

**Comment by raphaelrpais** [comment]
Is it "formally" possible to set scrollOverflow to `false`, get the same `fp-noscroll` effect, just when the user click on certain element?

**Comment by alvarotrigo** [comment]
> Is it "formally" possible to set scrollOverflow to false

You mean dynamically? Yes, when using the `responsiveWidth` or `responsiveHeight` options it gets disabled after reaching the defined size.

**Comment by raphaelrpais** [comment]
Almost... I want to, somehow, "toggle" the scrollOverflow option when the user clicks on a button.

**Comment by eliooses** [comment]
> This is possible since quite a few time ago. As detailed in the docs:
> 
> > In order to prevent fullpage.js from creating the scrollbar in certain sections or slides use the class `fp-noscroll`. For example: `<div class="section fp-noscroll">`

This save my life. Ok ok... the night.

Thanks a lot @alvarotrigo
