### ISSUE TITLE
smooth inner scroll for the "Scrolling inside sections and slides" demo

### ISSUE THREAD

**Issue by shanDB** [alvarotrigo/fullPage.js#1272]
I was wondering if there was a way to achieve a smooth  inner scroll for the "Scrolling inside sections and slides" demo. At the moment the inner scroll is just a little bit jerky when using the mouse wheel compared to the section scroll.

**Comment by alvarotrigo** [comment]
The scrollOverflow feature was done using slimScroll. It is not something belonging to fullPage.js.

It is not perfect, you can try to use iScroll.js if you prefer, but it hasn't been adopted by fullPage.js yet because it doesn't provide support to old versions of IE.

**Comment by andremacola** [comment]
You could use https://github.com/4alexandr/iscroll5-ie8

slimScroll is terrible in touch devices, even in desktop browsers. In nowadays mobile and tablets are more important than the IE8

**Comment by alvarotrigo** [comment]
> In nowadays mobile and tablets are more important than the IE8

That's a good point. 
Ideally we could use iScroll.js and have slimScroll as a fallback.

If you provide a pull request for it that'd be awesome. Not having much time lately...
