### ISSUE TITLE
scrolling stops external links from loading on Chrome

### ISSUE THREAD

**Issue by MC-Escherichia** [alvarotrigo/fullPage.js#1275]
If a user clicks an external link on our fullPage site, and then scrolls to the next section, Chrome will stop loading the external link and replace the address bar with site.com/#section2. This behavior is not evident in firefox. 

Our fullPage setup is as follows 
```javascript
$(document).ready(function() {
        $('#fullpage').fullpage({
            anchors: ['welcome', 'discover', 'collect','engage','join','benefit','bottom'],
            navigation: true,
            navigationPosition: 'right',
            navigationTooltips: ['Welcome', 'Discover', 'Collect','Engage','Join','Benefit','Bottom']
        });
    });
```

Any ideas?

**Comment by alvarotrigo** [comment]
I guess that only happens if you scroll just after clicking on the external link, just before the new URL starts loading, right?

**Comment by MC-Escherichia** [comment]
I don't know how to be sure the new URL is loading, but the loading spiral on the chrome tab will start to run, and scrolling will stop it.  In firefox, the page will scroll down and still continue to the external link.

**Comment by alvarotrigo** [comment]
I believe that depends on the browser and that there's no much fullPage.js can do about it.

**Comment by MC-Escherichia** [comment]
Ok thanks anway.
