### ISSUE TITLE
auto advance issue

### ISSUE THREAD

**Issue by maggiecreatives** [alvarotrigo/fullPage.js#1278]
Hi,
great slider. 
I checked out video on how to auto advance - implemented it...
but still there is an issue for when I click a menu item near the time the slide autoadvances -- seems to break the slider ....how to fix?
Thanks!

<script type="text/javascript">
	(function($) {

		$(document).ready( function() {
		var slideTimeout;
		var idInterval;

			$('#cover-slider').fullpage({
				anchors: <?php echo json_encode($anchor); ?>,
				navigation: true,
				continuousVertical: true,
				navigationPosition: 'right',
				animateAnchor: false,
				scrollingSpeed: 900,
				
				afterRender: function() {

				setInterval(function(){
						
						
                  			  $.fn.fullpage.moveSectionDown();
              			}, 7500);

				
				

  				}//after render

			}); //coverslider

		}); //doc ready
	})(jQuery); 
</script>

**Comment by alvarotrigo** [comment]
> seems to break the slider

What do you mean by that?

It seems to me this is an issue of javascript knowledge rather than a bug or an issue of fullPage.js.
I'll close the topic until proved the opposite. (ideally with a jsfiddle)
