### ISSUE TITLE
Dealing with modals

### ISSUE THREAD

**Issue by mitcheal** [alvarotrigo/fullPage.js#1279]
I'm trying to find a good full screen modal to house a full screen video embed.   I'm trying to link a button in the middle of a slide that triggers the modals.    It seems most of the modals i've tried popup for a split second and disappear.     

Do you have suggestions for using modals triggered within slides?

**Comment by alvarotrigo** [comment]
There shouldn't be any problem. 
Just make sure you disable the scrolling when opening the popup.

Use something like `$.fn.fullpage.setAllowScrolling(false)` when clicking on the button to open the popup, and then revert it with the `true` value.
