### ISSUE TITLE
fullPage.js and owl-carousel

### ISSUE THREAD

**Issue by kongolml** [alvarotrigo/fullPage.js#1280]
Hi! When useing safari (at least on mac), owl-carousel doesn't work with fullPage.js - it doesn't add   transform: translate3d() property to ".owl-stage" and for now i can't figure out why. Do you have any ideas? Thanks!

**Comment by alvarotrigo** [comment]
Read [the FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

If you still having troubles. Reproduce the problem in a jsfiddle.

**Comment by alvarotrigo** [comment]
Also read [this topic](https://github.com/alvarotrigo/fullPage.js/issues/895).

**Comment by kongolml** [comment]
So for those who will experience the same problem - "scrollBar:true" will solve your problem.

**Comment by xXJD** [comment]
Where do I put the code scrollBar:true

**Comment by xXJD** [comment]
I had the same problem my Owl carousel not working on fullpage.js

**Comment by kongolml** [comment]
$(document).ready(function() {
    $(/*selector*/).fullpage({scrollBar:true});
});

**Comment by xXJD** [comment]
I already put that code on it and my owl carousel is not works. But my Owl carousel is working when it is on outside of fullpage

**Comment by xXJD** [comment]
![capture](https://cloud.githubusercontent.com/assets/7666439/11087367/c7dfd998-8894-11e5-80f7-fbf8ac7d6ea8.PNG)
