### ISSUE TITLE
The browser's back button will not work in one case

### ISSUE THREAD

**Issue by JBarna** [alvarotrigo/fullPage.js#1282]
Preface: All sections DO have anchor tags in this case. 

If you navigate to the index of a fullpage.js webpage without using an anchor link , you automatically go to the first section.
If you then scroll to the section below (or slide left/right), you will not be able to press the Browser's back button to go to the first section/page. 

Example: Go to http://alvarotrigo.com/fullPage/
Scroll down one section, then press the browser's back button. (I'm using Chrome). 
Your browser has not registered the first page and you either skip to the page previous or it does nothing at all.

Best,
Joel

**Comment by alvarotrigo** [comment]
Already [reported time ago](https://github.com/alvarotrigo/fullPage.js/issues/950).
I'll close this issue as the other stills open.
