### ISSUE TITLE
Is there a way to disable scrolling and hide dots in mobile?

### ISSUE THREAD

**Issue by jitendravyas** [alvarotrigo/fullPage.js#1285]

**Comment by alvarotrigo** [comment]
What about using the `responsive` option?

**Comment by jitendravyas** [comment]
I tried responsive option in my mobile. scroll is not normal

**Comment by alvarotrigo** [comment]
Maybe you didn't set the correct value for it.
The [demo page](http://alvarotrigo.com/fullPage/examples/responsive.html) works as expected.

**Comment by jitendravyas** [comment]
I tested the demo page only. I will send you recorded video.

**Comment by alvarotrigo** [comment]
If your phone has more than 900 pixels width, the plugin won't change. 
As I said, you probably are using the wrong value for the `responsive` option.

**Comment by jitendravyas** [comment]
I'm testing in this phone http://www.gsmarena.com/oneplus_one-6327.php


Jitendra Vyas
Twitter <http://twitter.com/jitendravyas> | Linkedin
<http://www.linkedin.com/in/jitendravyas>

**Comment by alvarotrigo** [comment]
I don't know about that phone, you will have to figure out what's its resolution.

**Comment by jitendravyas** [comment]
It's 1080 x 1920 pixels (~401 ppi pixel density)

**Comment by jitendravyas** [comment]
Here is the video recorded on device in Chrome browser

https://www.dropbox.com/s/ov5wduv6dfvz5av/2015-06-05-19-34-12_screenRecording.mp4?dl=0

**Comment by alvarotrigo** [comment]
> It's 1080 x 1920 pixels (~401 ppi pixel density)

Then, do not use 900 as a value for `responsive`... I told you already:

> If your phone has more than 900 pixels width, the plugin won't change.
