### ISSUE TITLE
Resize Window on Horizontal Slideshow

### ISSUE THREAD

**Issue by elitzer2** [alvarotrigo/fullPage.js#1286]
When resizing the browser window when in a horizontal slideshow (on every slide except the first/default), the content moves over first (leaving part of the current slide and part of the next) and then adjusts. Is there a better way to handle this behavior and not have it get all funky? This happens when resizing in both the vertical and horizontal direction.

![screen shot 2015-06-05 at 2 42 24 pm](https://cloud.githubusercontent.com/assets/5624305/8013765/1f28772c-0b91-11e5-9889-faa1dddeceb7.png)

**Comment by alvarotrigo** [comment]
There's an open issue about it [here](https://github.com/alvarotrigo/fullPage.js/issues/64).
There's a way, but it will perform so many operations per millisecond it can potentially make the site laggy.
