### ISSUE TITLE
Is it able to set custom section height? 

### ISSUE THREAD

**Issue by linchen1987** [alvarotrigo/fullPage.js#1287]
like[http://www.smartisan.com/en/#/design](http://www.smartisan.com/en/#/design). 

when i first do the 'scroll down' action, u can see, the first scrolling section is not 100% height.

**Comment by alvarotrigo** [comment]
Same issue as [this open one](https://github.com/alvarotrigo/fullPage.js/issues/781).
I'll close it to avoid duplicates.

**Comment by linchen1987** [comment]
got it, thanks
