### ISSUE TITLE
Custom offset to add to scroll amount between elements

### ISSUE THREAD

**Issue by evonsdesigns** [alvarotrigo/fullPage.js#1288]
I have a fixed header on the top of my viewport that is obstructing the view of the top of each section that I scroll to. I looked through the various settings but I could not find an offset ability for the scrolling height (to offset the height of the header). The **paddingTop** field provided some assistance but was giving me odd looking/uneven section headers. 

What I ended up doing was manually adding the pixel amount inside the function getScrollSettings. It would be great (and not too hard, from the looks of it) if there was a setting in the startup that allows this custom offset. Great plugin btw!

I can't mark the label here but it should be 'enhancement'.

**Comment by alvarotrigo** [comment]
> The paddingTop field provided some assistance but was giving me odd looking/uneven section headers.

The `paddingTop` option is the answer to your problem.

Your solution might carry problems when using the option `overflowScroll` or even `verticalCentered`.
