### ISSUE TITLE
Small touchscreens scrolls very slow on scrollOverflow

### ISSUE THREAD

**Issue by jscontrust** [alvarotrigo/fullPage.js#1291]
When scrollOverflow is activated, the page scrolls very slow, especially on iOs devices in safari (the scroll on the page itself, not the scroll to the next section). On Android with Opera mini it was a bit better.

Is there the possibility to configurate the slim scroll plugin? What could be a fix/workaround?

**Comment by alvarotrigo** [comment]
Already treated [here](https://github.com/alvarotrigo/fullPage.js/issues/506).
