### ISSUE TITLE
fullPage.js scrolling slides to different direction

### ISSUE THREAD

**Issue by s3kawka** [alvarotrigo/fullPage.js#1293]
Im using fullPage.js to my website and i want to create scrolling in different direction I mean, if i have ex.4 section and every section have slides in it i want to first section have arrows to left and scrolling this slide to left and second section have only arrow to riht and scrolling thi slides to right, and so on, 3th to left and forth to right. is it possible?

**Comment by alvarotrigo** [comment]
Just add the `active` class to the section you want to be active by default. Then use `loopHorizontal:false`.

**Comment by s3kawka** [comment]
ok it disable loop but it doesnt shows how to change direction, in default every slide goes to right, but how change it to left

**Comment by alvarotrigo** [comment]
From the docs:

> If you want to define a different starting point rather than the first section or the first slide of a section, just add the class active to the section and slide you want to load first.

 ```
<div class="section active">Some section</div>
```

**Comment by alvarotrigo** [comment]
So set the 1st one as active if you want the arrow in the right.
Or the last one as active if you want the arrow in the left.

**Comment by alvarotrigo** [comment]
Here a [demo online](http://jsfiddle.net/97tbk/640/).

HTML:

```html
<div id="fullpage">
    <div class="section">
        <div class="slide active">Two 1</div>
        <div class="slide">Two 2</div>
        <div class="slide">Three 3</div>
    </div>
    <div class="section">
        <div class="slide">Two 1</div>
        <div class="slide">Two 2</div>
        <div class="slide active">Three 3</div>
    </div>
    <div class="section">Three</div>
</div>
```

Javascript
```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    loopHorizontal: false
});
`

**Comment by s3kawka** [comment]
Thank you veru much :)
