### ISSUE TITLE
Add Section at Mobile Breakpoint and don't show in navigation above breakpoint

### ISSUE THREAD

**Issue by buniden** [alvarotrigo/fullPage.js#1294]
I'm trying to add a breakpoint below 600px.  Using a media query i'm able to hide the section correctly above 600px but there is an extra section in the navigation dots and it also scrolls to the section that is not existent.  I've read trough all the other issues asking similar questions but am not able to see a solution for this.  Is there a way to do this?

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any way to do what you want. I'm afraid you should figure it out yourself or ask in another place such as http://stackoverflow.com/
