### ISSUE TITLE
Disable fullscreen fit (height) mode on mobile

### ISSUE THREAD

**Issue by lclhst** [alvarotrigo/fullPage.js#1295]
Welcome. 
Is it possible to disable fullscreen height fit for each section? If I set autoScrolling to false, content is cut at the end of screen- scrollOverflow doesn't work properly on mobile. I'd like to stay with working slides and href changing, so destroy() method is not solution. 
Thanks for replies!

**Comment by alvarotrigo** [comment]
Read this topic: https://github.com/alvarotrigo/fullPage.js/issues/1044
