### ISSUE TITLE
Horizontal scrolling trough sliders

### ISSUE THREAD

**Issue by DLudo** [alvarotrigo/fullPage.js#1297]
Hi, first i want to thank you for this killer plugin!

I actually want to have horizontal scrollable sections with the same behavior as for the vertical ones (when the content is larger). I've seen that fullPage is using slimscroll, but this one cannot do what i need.
What would be the best solution?

Best regards.

**Comment by alvarotrigo** [comment]
> I actually want to have horizontal scrollable sections with the same behavior as for the vertical ones

why can't you use scrollOverflow:true as [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html)?

**Comment by DLudo** [comment]
This kind of thing inside a single section -> http://www.pixxelfactory.net/jInvertScroll/

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such option. 
If you really need it, I could help you to achieve it. Just [contact me](http://alvarotrigo.com/#contact-page).
