### ISSUE TITLE
is it possible to watch which section or slide are actually active?

### ISSUE THREAD

**Issue by s3kawka** [alvarotrigo/fullPage.js#1299]
i want to write a function which will be working all the time after page full load, which will be changing color of arrows  on every section and slide, i mean i am using background images and not for every backgroun black arrow is visible so i must change it colors to white for some slides and section, is it possible? if so, how to do this?

**Comment by alvarotrigo** [comment]
You can just look for the `active` class in the sections or slides.
You can also check the `fp-viewing-xxx`  class added to the body.

**Comment by s3kawka** [comment]
ok, thanks but im a begginer and i know how to do this once when page is loaded but i dont know how to write it for every change of slide, can you please help me? i mean i need to change colors to different for every page, so how to do a loop or something which will be working all time and checkin which one is active?

**Comment by alvarotrigo** [comment]
If you don't know enough about javascript, better ask those question in http://stackoverflow.com/.
This forum is to treat fullPage.js specific problems.
