### ISSUE TITLE
Init plugins afterRender()

### ISSUE THREAD

**Issue by FKSI** [alvarotrigo/fullPage.js#1301]
Hi,

Can anyone put an example for "initiliazing plugins" in afterRender() method? Thanks a lot.

**Comment by alvarotrigo** [comment]
You'd better ask those kind of questions in other place such as http://stackoverflow.com/.
This is not fullPage.js specific. It is general knowledge about javascript.

In any case, here you have:

```javascript
$('#fullpage').fullpage({
    afterRender: function(){
        $('#whatever').whatever();
    }
});
´´´
