### ISSUE TITLE
Normal scrollable content after the last slide

### ISSUE THREAD

**Issue by nerdwithme** [alvarotrigo/fullPage.js#1302]
This feature may exist but i'm having a hard time finding it.  When the user gets to the last slide i'd like to be able to show normal non plugin content below it.  Is there a way to enable this with the current iteration of this plugin?

**Comment by alvarotrigo** [comment]
Nop. It doesn't exist such an option.

You can use `scrollOverflow` in the last section if you prefer, like [in this demo](http://alvarotrigo.com/fullPage/examples/scrolling.html).
