### ISSUE TITLE
fullpage and slimscroll on android browser

### ISSUE THREAD

**Issue by labbyjoel** [alvarotrigo/fullPage.js#1303]
Hello! 

I'm just developping my first website with your fullpage tool. 

http://www.labsinfo.be/NWAVE

It works like a charm on almost any desktop webbrowser unless android browser (aosp)  on tablet ( tested on galaxy tab 2 and 3, acer ). On those tablets, if I use chrome or firefox, no problem.  On samsung android phone and ipad, that works too.

I've got a section with an overflow ( library ). But on tablet, I'm unable to scroll inside the section or even clic on pictures.

Any idea ?? 

Thanks

joel

**Comment by alvarotrigo** [comment]
You might have problems on those devices to play videos with this:

```$('#reelVideo').get(0).play();```

So it might break other scripts.

**Comment by labbyjoel** [comment]
The video plays well on all devices... I don't really understand your answer... sorry...

**Comment by alvarotrigo** [comment]
Videos can't autoplay in some devices such iPhones or iPads.

**Comment by alvarotrigo** [comment]
If that's not the issue. Then I would encourage you to try slimScroll.js by its own in the device you are having problems to see if the problem in in slimScroll.js plugin or not.

**Comment by labbyjoel** [comment]
OK I will remove the video for the test and keep you updated about the 
result !


Le 15/06/2015 13:51, Álvaro a écrit :
>
> If that's not the issue. Then I would encourage you to try 
> slimScroll.js by its own in the device you are having problems to see 
> if the problem in in slimScroll.js plugin or not.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alvarotrigo/fullPage.js/issues/1303#issuecomment-112031670>.
>

-- 

Rue de la Sablonniere, 35
7390 Wasmuel
Tel: 0476/62.49.82

**Comment by alvarotrigo** [comment]
> OK I will remove the video for the test and keep you updated about the
> result !

No. I didn't mean just that.
What I'm suggesting is you to create an empty page and create some example of use of the library slimScroll.js 

http://rocha.la/jQuery-slimScroll
https://github.com/rochal/jQuery-slimScroll

I'm suggesting to try slimScroll.js. Not to use fullPage.js at all.

**Comment by labbyjoel** [comment]
OK ! sorry :-)

I will try that !


Le 15/06/2015 14:02, Álvaro a écrit :
>
>     OK I will remove the video for the test and keep you updated about the
>     result !
>
> No. I didn't mean just that.
> What I'm suggesting is you to create an empty page and create some 
> example of use of the library slimScroll.js
>
> http://rocha.la/jQuery-slimScroll
> https://github.com/rochal/jQuery-slimScroll
>
> I'm suggesting to try slimScroll.js. Not to use fullPage.js at all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alvarotrigo/fullPage.js/issues/1303#issuecomment-112037101>.
>

-- 

Rue de la Sablonniere, 35
7390 Wasmuel
Tel: 0476/62.49.82

**Comment by labbyjoel** [comment]
you're welcome ;-)



Le 15/06/2015 14:02, Álvaro a écrit :
>
>     OK I will remove the video for the test and keep you updated about the
>     result !
>
> No. I didn't mean just that.
> What I'm suggesting is you to create an empty page and create some 
> example of use of the library slimScroll.js
>
> http://rocha.la/jQuery-slimScroll
> https://github.com/rochal/jQuery-slimScroll
>
> I'm suggesting to try slimScroll.js. Not to use fullPage.js at all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alvarotrigo/fullPage.js/issues/1303#issuecomment-112037101>.
>

-- 

Rue de la Sablonniere, 35
7390 Wasmuel
Tel: 0476/62.49.82

**Comment by labbyjoel** [comment]
sorry not for you :-)


Le 15/06/2015 14:02, Álvaro a écrit :
>
>     OK I will remove the video for the test and keep you updated about the
>     result !
>
> No. I didn't mean just that.
> What I'm suggesting is you to create an empty page and create some 
> example of use of the library slimScroll.js
>
> http://rocha.la/jQuery-slimScroll
> https://github.com/rochal/jQuery-slimScroll
>
> I'm suggesting to try slimScroll.js. Not to use fullPage.js at all.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alvarotrigo/fullPage.js/issues/1303#issuecomment-112037101>.
>

-- 

Rue de la Sablonniere, 35
7390 Wasmuel
Tel: 0476/62.49.82

**Comment by labbyjoel** [comment]
I've tested the slimscroll example on those tablets
http://www.labsinfo.be/NWAVE/jQuery-slimScroll-1.3.0/examples/
the scrolling zones works well, but the hyperlinks on the left side are disabled.
So the problem comes from slimScroll... Don't seems to be referenced by anybody else... Strange...

**Comment by alvarotrigo** [comment]
Then you'd better open an issue in their project:
https://github.com/rochal/jQuery-slimScroll

Although I believe the project is not being very actively maintained anymore.

**Comment by labbyjoel** [comment]
That's what I did but effectively I'm affraid having to wait too long 
time...

Nobody reports this problem before ?

is it difficult in your script to switch to another tool like 
mCustomScrollbar for example. ?



Le 16/06/2015 12:26, Álvaro a écrit :
>
> Then you'd better open an issue in their project:
> https://github.com/rochal/jQuery-slimScroll
>
> Although I believe the project is not being very actively maintained 
> anymore.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/alvarotrigo/fullPage.js/issues/1303#issuecomment-112377374>.
>

-- 

Rue de la Sablonniere, 35
7390 Wasmuel
Tel: 0476/62.49.82
