### ISSUE TITLE
Slides: fade instead of horizontal scroll

### ISSUE THREAD

**Issue by nhylated** [alvarotrigo/fullPage.js#1304]
This is more of a how-to rather than an issue. There have been several requests for this (#517, #1093, #783). 

This can be implemented using the plugin's settings to add callbacks on slide transitions. Check this gist for an example: https://gist.github.com/nhylated/6a1a360a0ad321546abc

This gives a pretty decent effect even though it isn't a true cross-fade.

Hope this helps others!

Demo: https://jsfiddle.net/0hLzxrea/2/

Edit: updated the code to reset the scrollingSpeed after the slide fade-in is over.

**Comment by alvarotrigo** [comment]
Thanks for it, but I'll close it as it is not an issue or neither a question. 
It will still be accessible from Google searches, so hopefully it will help somebody.

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
