### ISSUE TITLE
Keeps scrolling to anchor!

### ISSUE THREAD

**Issue by infinitodk** [alvarotrigo/fullPage.js#1305]
Hey!

Thanks for a great plugin. I might need some customization, but I can write the details and get a quote from you!

Right now I have one issue. I have the following settings:

..
menu: '#menu',
css3: true,
autoScrolling: false,
scrollBar:true,
scrollingSpeed: 900,
..

If i scroll to a section longer than the current viewport and start scrolling into it, after a second or so, it will scroll up to the beginning, making it impossible to read the content. How can I avoid this?

The slimscroll plugin is very sluggerish on tablets and does not seem like a good fit for this projekt (It's the United Nations Annual Digital report, so it needs to be perfect)

Any ideas? Maybe a paid work-around?

**Comment by alvarotrigo** [comment]
If you use ´autoScrolling:false´ it makes no sense to use `scrollBar:true`. So turn `scrollBar` to false.

> If i scroll to a section longer than the current viewport and start scrolling into it, after a second or so, it will scroll up to the beginning, making it impossible to read the content. How can I avoid this?

Use `fitToSection:false`.


> Any ideas? Maybe a paid work-around?

Maybe using other plugins such as iScroll.js. Although you will lose compatibility with IE 9.
