### ISSUE TITLE
set body as fullpage wrapper error

### ISSUE THREAD

**Issue by linchen1987** [alvarotrigo/fullPage.js#1306]
i find that <body> element can't be used as fullpage wrapper (like "#fullpage"), or it will be confusion (which had bother me a lot),   i think this tip may be added to README.md to let other knows.

**Comment by alvarotrigo** [comment]
I don't know what are you talking about. Can you explain it in another way?

There's no problem using `#fullpage` as the wrapper. In fact, all the examples in the website work that way.

**Comment by linchen1987** [comment]
sorry, i lose the word "body".  the `<body>` element can't be fullpage wrapper.  for example.

```
<body id="fullpage">
</body>
```

you can use any other element except `<body>` . for example: 

```
<body>
  <div id="fullpage">
  </div>
</body>
```

i think this tip may be added to README.md to let other knows because it bothers me a lot : (

**Comment by alvarotrigo** [comment]
I see what you  mean now. 
I'll update the docs.

**Comment by alvarotrigo** [comment]
Documentation updated.
