### ISSUE TITLE
slide animation fade-in/out, slide up/down

### ISSUE THREAD

**Issue by salmanpatnee** [alvarotrigo/fullPage.js#1307]
Hy, this is a nice plugin so far and have used in many sites. now i'm struggling from a problem upon request of my client how can i slide in different way like slide fadein or out like bespoke-fx https://github.com/ebow/bespoke-fx i've tried bespoke-fx but the nav-pager not working. please solve this issue with only using good old fullpage.js or any other way. its really urgent

**Comment by alvarotrigo** [comment]
I'm afraid the plugin doesn't provide any option for it. 
This is an scrolling plugin.

**Comment by salmanpatnee** [comment]
Yeah, but fullpage.js has a slider so with  that in my mind i asked..
