### ISSUE TITLE
console.log("wee"); in npm install

### ISSUE THREAD

**Issue by camswords** [alvarotrigo/fullPage.js#1308]
Hi,

I just installed your library using npm install. I'm using version 2.6.6.

I noticed that the console prints "play" a few times. In your source in my node_modules/fullpage.js/jquery.fullPage.js it has three strange console.logs:

line 1327: console.log("wee");
line 1330: console.log("wee");
line 1334: console.log("play");

lol! I notice in your github code that you haven't got the same console.logs. Is it possible that you have released a different version to the NPM repo than what you checked in?

Cheers
Cam

**Comment by alvarotrigo** [comment]
That's weird. It might be possible. 
I'll check it on Monday.

**Comment by alvarotrigo** [comment]
Thanks for reporting it. Solved.

**Comment by camswords** [comment]
Thank you for fixing it :-)
