### ISSUE TITLE
Scroll problem after click back button

### ISSUE THREAD

**Issue by likedo** [alvarotrigo/fullPage.js#1312]
Hi , I'm sorry for my English .
I'll explain my problem . Div with the id fullpage , is only present in the home ,
and it works perfectly . When going in a section , for example , profile / luna ,
the content is loaded via Ajax , without fullpage . When I click the back
browser , the content of the home page is loaded via Ajax and instantiated
the fullpage . But when I try to scroll the page , scrolling is very sensitive
and are not positioned well the various sections .

Can you help me?

thanks a lot

**Comment by alvarotrigo** [comment]
You are probably initializating fullPage.js multiple times.

**Comment by likedo** [comment]
thanks for the reply!
