### ISSUE TITLE
Move to first slide anchor, does not work on the second time

### ISSUE THREAD

**Issue by svenAku** [alvarotrigo/fullPage.js#1313]
Hi

I have an issue, where I have an anchor that scrolls to the first slide. It is fixed element in the header. It works on the first click. The #home is appended to the URL. And after that when I scroll down, and click on it again. It wont work

It acts like that with all the anchors.

Is there any solution for this?

**Comment by alvarotrigo** [comment]
Provide a reproduction of the issue. You are probably doing something wrong.

**Comment by svenAku** [comment]
sorry, my bad.

I did not add the anchors properly in my JS file. (anchors worked tho)
