### ISSUE TITLE
moveSectionUp button should disappear

### ISSUE THREAD

**Issue by plexity** [alvarotrigo/fullPage.js#1314]
I'm trying to make the moveSectionUp button disappear when at the top of the page when I have loops set to false, same with the movesectionbottom button when at the bottom of the page.

Anyone have any ideas?

https://jsfiddle.net/doLcnjss/

**Comment by alvarotrigo** [comment]
Not a question for this forum. Please ask javascript questions in http://stackoverflow.com/
