### ISSUE TITLE
How to add a standard function scroll without changing its visibility?

### ISSUE THREAD

**Issue by Diargon345** [alvarotrigo/fullPage.js#1317]
Together with fullpage.js I use the plugin Scrollr. For it to work properly should be standard scroll function. If you set the value of the scrollbar: false (default), the plugin does not work properly. If you set the value of the scrollbar: true, all works correctly. But I don't know how to make scrolling invisible. How can I do it? What I mean is shown in the examples below:
Scroll bar: true - http://aleshkalavrushka.tk/test%20copy%201.html
Scroll bar: false - http://aleshkalavrushka.tk/test.html

**Comment by alvarotrigo** [comment]
I know what you mean, and the use of scrollBar: true for those cases it's explained in the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

There's no other way to make it work. 
But it is nice to point out that you don't need it at all as you can use the fullPage.js callbacks to fire the effects you want.

**Comment by Diargon345** [comment]
Thanks =)
