### ISSUE TITLE
How to scroll after animation ended?

### ISSUE THREAD

**Issue by Diargon345** [alvarotrigo/fullPage.js#1318]
I tried that once, but then the page stopped scrolling:
```
onLeave (index, nextIndex, direction){
 var $info_panel = $('.info_panel');
	var $el2 = $('.el2');
            if(index == 1){ 
return false;
			$info_panel.removeClass('slide_panel');
            $el2.removeClass('slide_content');
            $.fn.fullpage.moveSectionDown();
            }
    }
```
Why? How to implement this? Because fullpage does not have a callback before.

**Comment by alvarotrigo** [comment]
As I said in you [previous answer](https://github.com/alvarotrigo/fullPage.js/issues/340#issuecomment-113292936).

> To disable it, you return false. Otherwise it will scroll normally. 
You might want to use javascript callbacks to return true if you make some action, your code doesn´t make sense with two returns.

You'd better ask for javascript question in other place such as stackoverflow.com
