### ISSUE TITLE
Ability to change paddingTop after resize 

### ISSUE THREAD

**Issue by jonasva** [alvarotrigo/fullPage.js#1319]
Is it possible to change the paddingTop after a window resize? I'm asking as responsive websites often reduce the height of a fixed header on mobile.

**Comment by alvarotrigo** [comment]
I would recommend to do it manually rather than using the `paddingTop` option. 
That's only for people who don't know CSS or are dealing with `scrollOverflow:true`.

**Comment by alvarotrigo** [comment]
```html
<div class="section">
    <div class="container></div>
</div>
```

```css
    .container{
        padding-top: 60px;
    }
```

**Comment by jonasva** [comment]
Thx for the advice @alvarotrigo, but the page I'm building actually requires `verticalCentered` to be set on true, as I want my content to be in the middle of the page. The `paddingTop` option seems to have the vertically centred div compensate for the offset, while with just using a CSS class it doesn't compensate.

I ended up using a padding-top on the body (to solve another issue specific to my layout as well). You can see it here: http://maximum.com/offices/shanghai/virtual-tour

**Comment by alvarotrigo** [comment]
Use the padding in your section content wrapper then.

Something like:

```html
<div class="section">
     <div class="content"></div>
</div>
```

```css
.section.content{
    text-align:center;
    padding-top: 60px;
}
```
