### ISSUE TITLE
bottom part of the normalScrollElement is hidden

### ISSUE THREAD

**Issue by edgarchandev** [alvarotrigo/fullPage.js#1322]
This is my site: http://danceinhk.orgfree.com/bcdc
( I set that fullpage would be initialize only if user use non-mobile device and window.width>1200)

There is a html time table inside a "section". If the screen height is not enough for showing the entire time table, eg. 1250 x 633 px (Im currently using Chrome for testing), some part of the normalScrollElement is hidden at the bottom which cause scrolling will trigger showing the next section content instead of the remaining last row of the time table.
i found similar situation on other pages i created.

I'm sorry for my English. >< Many Thank!

**Comment by alvarotrigo** [comment]
You are using `padding-top: 50px !important;` 
This is a full page plugin and it doesn't know you are using a padding top in the body. You are not suppose to use it.

**Comment by edgarchandev** [comment]
oops,
but without setting padding-top, how can I keep fullpage's content show below my navbar?
Thanks!!

**Comment by edgarchandev** [comment]
sorry, I found it.
adding "fixed" class to my navbar solve it. Thanks!!
