### ISSUE TITLE
Go to straight to section anchor from other page, but without the animation?

### ISSUE THREAD

**Issue by ReGGaeBOSS** [alvarotrigo/fullPage.js#1323]
Hi,

Is it possible to link to a section without the whole "scrolldown down to correct section" -animation when using anchors?

**Comment by alvarotrigo** [comment]
Not sure what are you asking for, but here two answers:

- Use the fullpage.js function [silentMoveTo](https://github.com/alvarotrigo/fullPage.js#silentmovetosection-slide)

Or, if you are talking about accessing to a URL with anchors:
- Use the option `animateAnchor:false`.
