### ISSUE TITLE
Desktop Scroll Sensitivity

### ISSUE THREAD

**Issue by gregk8288** [alvarotrigo/fullPage.js#1324]
Hi there,

Great plug-in, well done!

Is there a way to change the scroll sensitivity on desktop like you're able to for mobile devices using touch scroll sensitivity?

**Comment by alvarotrigo** [comment]
Nop.
Why? Because mouse scroll sensitivity is not the same in all computers. 

Kinetic scrolling like the one in Apple laptops or some trackpads is very different from a mouse wheel.

**Comment by gregk8288** [comment]
OK Thanks. Yip, on my magic mouse it seems very sensitive, the slightest touch seems to activate the scroll. The percentage height / width movement seems like a clever solution for touch and wouldn't be a bad inclusion if it could be made to work with trackpads / mouse wheels.

**Comment by alvarotrigo** [comment]
> The percentage height / width movement seems like a clever solution for touch and wouldn't be a bad inclusion if it could be made to work with trackpads / mouse wheels.

Well, if you find a way to implement it I would be more than welcome to add it.

**Comment by gregk8288** [comment]
Sounds good!

**Comment by IrynaArnautova** [comment]
> Sounds good!

Hi, have you solution with mac mouse wheels?

**Comment by alvarotrigo** [comment]
@IrynaArnautova there's no such improvement. You won't find an easy solution as kinetic scrolling is not easy to deal with.
