### ISSUE TITLE
sectionSlideUp() not working

### ISSUE THREAD

**Issue by lolafrerot** [alvarotrigo/fullPage.js#1326]
Hello there, 

I'm working on a project that needs a slide only 1 time, like if the index page was cut in two part. The moveSectionDown function is working very well, including touching and violent scrolling -> nice job!  and allow me to go to the second section correctly. 

The thing is, the moveSectionUp function is not working for me when the setAutoScrolling is false! I'm pretty sure i did it wrong, but I can't figure why.. Can i have more explanation about this 2 function? Is there some conditions for them to work?

Sorry for my poor english, I'm just a french front-end developper who slept too many time in english class! My bad..

**Comment by alvarotrigo** [comment]
I'm confused. In the title of the issue you use `sectionSlideUp` and in the body `moveSectionUp `.
Which one are you actually using? Because the first one doesn't exist.

Also, it works as expected as you can see [in the methods example page](http://alvarotrigo.com/fullPage/examples/methods.html). So you are probably doing something wrong. 
Check your JavaScript console. 

If you still believing its a bug, reproduce the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) to isolate it from any external code.

**Comment by lolafrerot** [comment]
Yes, moveSectionUp, sorry! Nothing in the console, i'm doing this actually:

$('#fullpage').fullpage({
        fitToSection: false,
         anchors:['conteneur', 'conteneur-principal'],
           afterLoad: function(anchorLink, index){
            var loadedSection = $(this);

            //using index
            if(index == 2){
               // alert("Section 2 ended loading");
                $.fn.fullpage.setAutoScrolling(false);
                 menuBig();
                  $(".encore").fadeOut();
              //  $.fn.fullpage.fitToSection(false);
            }

        },
         onLeave: function(index, nextIndex, direction){
            var leavingSection = $("#conteneur-principal");

            //after leaving section 2
            if(index == 2 && direction =='down'){
               // alert("Going to section 3!");
            }

            else if(index == 2 && direction == 'up'){
                  alert("Going to section 1!");
                 // $.fn.fullpage.setAutoScrolling(true);
                   $.fn.fullpage.moveSectionUp();
                  // $.fn.fullpage.setAutoScrolling(true);
             
           }
            
        }

I get the alert but not the animation.

**Comment by alvarotrigo** [comment]
Sorry, you will have to recreate your problem in jsfiddle.

**Comment by rahul78275** [comment]
The same issue i too facing.

**Comment by alvarotrigo** [comment]
@rahul78275 it works on the demo provided on the docs. You'll have to provide an isolated reproduction to prove it.
