### ISSUE TITLE
How to remove the effect of the fullpage.js to a page like (single blog page), I am using a Wordpress.

### ISSUE THREAD

**Issue by ayeibithao** [alvarotrigo/fullPage.js#1327]
My home page is perfectly working with fullpage.js but my only problem is when I click the blog post that leads me to the single post (where I don't need the fullpage.js script in it) and I noticed that I cannot scroll down properly and I even tried to use autoscrolling:false but it affects my home page, did someone encounter the same problem? hope someone can help me :(

**Comment by alvarotrigo** [comment]
Destroy it with [`detroy('all')`](https://github.com/alvarotrigo/fullPage.js#destroytype) or easier yet, do not initialise it if its not necessary...
