### ISSUE TITLE
Fire scroll event after a certain scroll offset or scrolling time

### ISSUE THREAD

**Issue by GreenNoise** [alvarotrigo/fullPage.js#1328]
I was searching for a solution on this issue, saw many threads about it but no real solution... The only post i see is what i want to achieve is this one you answered:
http://stackoverflow.com/questions/19513065/fire-scroll-event-after-a-certain-scroll-offset-or-scrolling-time

But its from the 1.0 version of fullpage, when i try that code it doesnt work...

Could you advice me on applying this same solution with MouseWheelHandler() but for the latest fullpage version?

Thanks a lot

**Comment by alvarotrigo** [comment]
Hi @GreenNoise, as you can see from my answer in stackoverflow, that method only works for conventional mouse wheels and not for laptops or mouses with kinetic scrolling.
It is not an ideal solution.

You can try to apply it to the new code in fullPage.js by following the instructions I detailed in stackoverflow.

If you do not manage to do so and you really need it, [contact me](http://alvarotrigo.com/#contact-page) for a customisation of fullpage.js.
