### ISSUE TITLE
Stop between two section while navigating

### ISSUE THREAD

**Issue by salmanpatnee** [alvarotrigo/fullPage.js#1331]
I'm having an issue with fullpage.js. when i'm navigate from one section to another using navigation it stops between two sections. it works fine on mouse scroll whell up and down. I set the option fitToSection:true but no success  what is the reason looking forward to you. its urgent here

here mi fullpage initilization

```javascript
$('#fullpage').fullpage({
        //Navigation

        anchors: ['home', 'about-us', 'services', 'clients', 'work', 'blog'],

        fitToSection: true,
        navigation: true,

        //Scrolling
        autoScrolling: true,
        scrollOverflow: true,

        //Accessibility
        keyboardScrolling: true,

        //Design
        resize : true,
        responsive: 1,

      
   
    });  //FULL PAGE SCRIPT END
```
and here is the site link: http://mim.raw.agency/

**Comment by alvarotrigo** [comment]
Probably due to your fancy menu. fullPage.js has nothing to do with it. 

You might probably want to do something different to solve it. Your menu should be closed once the plugin starts to scroll.

I'd recommend you to make use of the function `$.fn.fullpage.moveTo` inside a timeout. So you can have enought time to close the menu before forcing fullpage.js to scroll.

Something like:
```javascript
$('.menu').find('li').click(function(){
    var elementIndex = $(this).index() + 1;
    //close menu
    closeMenu();

    //delay added until menu is closed
    setTimeout(function(){
         $.fn.moveTo(elementIndex);
    }, 1000);
});
```

Ideally if your menu plugin provides a callback when its closed you could use it instead of the timeout solution.

**Comment by salmanpatnee** [comment]
Brother i'm not an expert programmer i don't know how to slove that problem. i'm using this menu https://github.com/hakimel/Meny and yes this is provide some API and methods 4. API & Events

A few handy methods API methods are included, you call these on the instance returned by Meny.create (see above).

meny.configure({ mouse: false }); // change settings after initialization

meny.open();

meny.close();

meny.isOpen(); // true/false

meny.destroy(); // revert original DOM state, unbind events

please tell me what i do?

**Comment by alvarotrigo** [comment]
> Brother i'm not an expert programmer i don't know how to slove that problem.

I'm afraid I do not provide free support for external problems. If you need my help [contact me](http://alvarotrigo.com/#contact-page).

**Comment by salmanpatnee** [comment]
Hey Alvaro thanks for above code it works like a charm! but for correction you wrote this  $.fn.moveTo(elementIndex); but its actually $.fn.fullpage.moveTo(elementIndex); Thanks again

**Comment by alvarotrigo** [comment]
@salmanpatnee right. Corrected.

**Comment by salmanpatnee** [comment]
One thing that impressed me that how you diagnose the problem ? what tools do you use?

**Comment by alvarotrigo** [comment]
@salmanpatnee Chrome inspector.
But in this case it my eyes and the way the plugin works helped me to understand what was the bug. 

The plugin looks for the position of the next or previous section to scroll. It position in the Y axys its determined by its top. When you open your menu the position in the screen of the sections changes and `position()` will provide a wrong value.

**Comment by salmanpatnee** [comment]
Thanks Alvaro you are awesome!
