### ISSUE TITLE
Clicking Embedded Google Street View messes up sections

### ISSUE THREAD

**Issue by mb303** [alvarotrigo/fullPage.js#1332]
Please see https://jsfiddle.net/5q6t5zrn/9/

In the second section I have an iframe with a google street view embedded - clicking on this results in the first section being overwritten with the contents of the second and all the subsequent sections being moved up one.

Any ideas how to prevent this behaviour? I tried adding normalScrollElements: '.tour' but this had no effect.

**Comment by alvarotrigo** [comment]
That's a bug of Google maps when dealing with the css property `translate3d`.
[Here a reproduction of the error without using fullPage.js](http://jsfiddle.net/q9g4v85o/)

You'd better report it to Google Maps.

**Comment by alvarotrigo** [comment]
A solution for it? Use `scrollBar:true` or `css3:false`.
[Demo with scrollBar](https://jsfiddle.net/5q6t5zrn/12/)
[Demo with css3:false](https://jsfiddle.net/5q6t5zrn/13/)

**Comment by mb303** [comment]
Thanks for the workaround - using scrollBar: true
Martin
