### ISSUE TITLE
scrollOverview disables verticalCentered

### ISSUE THREAD

**Issue by MrMacStripe** [alvarotrigo/fullPage.js#1335]
Hi,

I need to enable scroll Overview for the responsive part of my newest project. If I do so, the verticalCentered option loses it´s functionality even on the big displays with more space than needed. Is there a way to stop this and only activate slimscroll if needed?

**Comment by alvarotrigo** [comment]
I don't understand your problem.
Could you recreate it in [a fiddle](http://jsfiddle.net/97tbk/418/)?

**Comment by MrMacStripe** [comment]
I can´t recreate it anymore for some reasons. Maybe I had a typo somewhere, nevermind. Sorry for that ;)
