### ISSUE TITLE
Do not display warning if an ID is set for a data-anchor item

### ISSUE THREAD

**Issue by blueyed** [alvarotrigo/fullPage.js#1336]
The warning "data-anchor tags can not have the same value as any `id` element" should not get displayed in case it's set for the same element that fullPage.js would attach it to.

The code in question is:

            //anchors can not have the same value as any element ID or NAME
            $.each(options.anchors, function(index, name){
                if($('#' + name).length || $('[name="'+name+'"]').length ){
                    showError('error', 'data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).');
                }
            });

This should probably check if the element with the ID is the one that would get the ID - therefore the checking for the warning might get moved to the handler that attaches/adds the IDs.

It makes sense to provide the IDs for clients without JavaScript.

**Comment by alvarotrigo** [comment]
Nop. "data-anchor tags can not have the same value as any id element". 
Otherwise the site won't scroll properly when using a URL with an anchor link. You can check it by yourself.
