### ISSUE TITLE
Hiding Arrows

### ISSUE THREAD

**Issue by pacificfrost** [alvarotrigo/fullPage.js#1339]
I have been trying to figure this out for some time now, but is there a way to hide/deactivate the arrows when you get to the last section/slide in the page.
So far, the best I can get to hiding the arrows is by colouring them the same, but I intend to make each section/slide similar to the bottom slide. And also if the slides didn't "repeat"/roll-over.

```javascript
function hideArrowUp() {
            if(index == 1){
                $('.arrowUp').style.opacity = "0";
            }
            else {
                $('.arrowUp').style.opacity = "1";
            }
        }
        
        function hideArrowDown(anchorlink) {
            if(index == 3){
                $('.arrowDown').style.opacity = "0";
            }
            else {
                $('.arrowDown').style.opacity = "1";
            }
        }
```

I'm probably way off with this. But this is what i'm hoping to achieve.

![help](https://cloud.githubusercontent.com/assets/13089172/8398004/1faaf1c0-1d9d-11e5-8bf4-3850d19430f0.jpg)

**Comment by alvarotrigo** [comment]
which arrows are you talking about?
The arrows only appear if the section has any slides. If there's no slides no arrows will be shown.

**Comment by pacificfrost** [comment]
Sorry, what I was meaning is: If you take the bottom section for instance, I was hoping I could hide that green arrow at the bottom when on that section, as that arrow is inactive/it doesn't take you anywhere? 
But also if there was a way to stop the roll-over on the slides. ie. (if on blue, hitting left shouldn't take you to the red slide - not sure if that's a simple fix)

Thanks for getting back so quick!

**Comment by alvarotrigo** [comment]
Just use the plugin callbacks such as `afterLoad` or `onLeave` to remove the arrow by using javascript or by adding a class.

You can also use the class of type `fp-viewing-xxxx` added to your `body` element to apply one or another style.
