### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by khudia** [alvarotrigo/fullPage.js#1341]
How to make a delay before slides (difrent delay on diffrent slides). I need to perform some actions before change slide. Such as fadeOut text for example. Thanks

**Comment by alvarotrigo** [comment]
There's no easy way to do that at the moment.

**Comment by alvarotrigo** [comment]
If you really need it as soon as possible [contact me](http://alvarotrigo.com/#contact-page).

**Comment by khudia** [comment]
Wrote email to you. Thanks.

**Comment by khudia** [comment]
I've done it mysell. thanks for answear again.
