### ISSUE TITLE
Bootstrap "de-activating" the plugin

### ISSUE THREAD

**Issue by ds1239** [alvarotrigo/fullPage.js#1342]
Hello. I am trying to use fullPage.js with Bootstrap, but as soon as I include the bootstrap files, it just "forgets" about fullScreen.js. here is my code:

https://drive.google.com/a/akiva.org/file/d/0B899j5opxMkhS21XNHF0MDlIUmM/view

Please help! Thanks

**Comment by alvarotrigo** [comment]
You would have to reproduce the problem [this jsfiddle](http://jsfiddle.net/97tbk/696/).
As you can see, I'm importing the Bootstrap CSS and JS in the external resources and it still working as expected.
