### ISSUE TITLE
Why is &nbsp being added to to the top of the body?

### ISSUE THREAD

**Issue by jarvisjohnson** [alvarotrigo/fullPage.js#1344]
Hi Alvaro - this is such a cool project!
Can you please help me out? When the page renders it renders 3 nbsp's at the top of body, shifting all the sections down.  
![image](https://cloud.githubusercontent.com/assets/12746936/8432902/2d9f6960-1f86-11e5-82da-5b45dd6056dd.png)
Do you know how to get rid of this?
Thanks

**Comment by alvarotrigo** [comment]
Nothing to do with fullPage.js.
As you can see it doesn't happen in [any of the demo pages](http://alvarotrigo.com/fullPage/).

**Comment by jarvisjohnson** [comment]
Everything was actually just copied from your demoPage.html you provided in the download...

So there is nothing *but* fullPage.js...

**Surely** others would have had this issue? Seeing as you are the author, I thought you might have some ideas on that?

**Comment by alvarotrigo** [comment]
> Everything was actually just copied from your demoPage.html you provided in the download...

If you can not reproduce it in the original example `demoPage.html`, then it looks like you introduced the problem with some of your changes. 

If you think its an issue (which I don't), reproduce the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) for further examination.

**Comment by jarvisjohnson** [comment]
That's fair enough mate; I'll go back and see where I've gone wrong because it definitely works in your demoPage.html.

To clarify, I don't think it's an issue with fullPage.js, I was just looking to get advice.  In future is it better to send a pm with a question like that rather than opening an issue?

thanks

**Comment by alvarotrigo** [comment]
> In future is it better to send a pm with a question like that rather than opening an issue?

Better to open an issue. In case it is, it will get recorded and marked to be fixed.
