### ISSUE TITLE
Would like to actually skip sections, or have "transitional" sections between anchors

### ISSUE THREAD

**Issue by mmarcell** [alvarotrigo/fullPage.js#1345]
I was curious if there were an option or a good way to include sections that just appear between transitions. I currently have it set up on my local system and it seems to stop or loop to the top when I use the mouse to scroll to the next anchor with the "non-anchored" section in between. Is there any way to fix this?

**Comment by alvarotrigo** [comment]
> sections that just appear between transitions

I guess that you mean. Sections that are skipped when moving up or down. Just being visible while the movement takes place.

The plugin doesn't provide a way to deal with it. You would have to do it by yourself.

**Comment by mmarcell** [comment]
Yeah, exactly. Ok, I will see if I can figure that out. Thanks.
