### ISSUE TITLE
Back and forth on Ajax pages gives Uncaught TypeError

### ISSUE THREAD

**Issue by GeckoIt** [alvarotrigo/fullPage.js#1346]
On my home page I have implemented an Ajax plugin and Fullpage.js with autoScrolling on false which works great on the first page. From here you can click to other pages which haven't loaded that plugin. Back to the home page gives the following error:

`Uncaught TypeError: Cannot read property 'offsetTop' of undefined`

I applied a check for pages where Fullpage.js doens't have to work:

```javascript
if ($('div#fullpage').length) {
    $('#fullpage').fullpage({autoScrolling: true, loopBottom: true});
    $("div.index div.btn-nav").click(function(e){
        e.preventDefault();
        $.fn.fullpage.moveSectionDown();
    });
}
```

but I think it won't listen any time I want cause of the ajax implemention.

When I enable autoScrolling the above error doesn't appear.
Working with methods like destroy and reBuild didn't help me on this case.

Any thoughts on solving this issue?

**Comment by alvarotrigo** [comment]
You have to destroy it when loading new ajax content if you are not planning to use fullPage.js on the new loaded page.

**Comment by GeckoIt** [comment]
Your answer was clear enough to solve my issue within an hour, thanks!
