### ISSUE TITLE
My sites, sometimes load video bg and sometimes not

### ISSUE THREAD

**Issue by DavidCstllns** [alvarotrigo/fullPage.js#1347]
hi alvaro i have a big problem, since a long time i am trying to put a video background single page, but, not work ...sometimes load and other times no, it is very confused.
If i put a image, the Fullpage work it, but it is a video, does it sometimes

![nocarga](https://cloud.githubusercontent.com/assets/13154390/8483137/3c7d1bba-20b4-11e5-8403-40a337e99f73.png)
![carga](https://cloud.githubusercontent.com/assets/13154390/8483138/3c7e8d2e-20b4-11e5-86fa-44a07fccf230.png)

**Comment by alvarotrigo** [comment]
Add a link to your site or reproduce your problem in [jsfifdle](http://jsfiddle.net/97tbk/418/). 

Also, specify what you mean by "sometimes load".
Do you see it but it doesn't load? You see it but it doesn't play? It doesn't even appear?
