### ISSUE TITLE
can not find sections under different tags

### ISSUE THREAD

**Issue by Avemaar** [alvarotrigo/fullPage.js#1348]
First of all i am sorry if this question is already answered.But i haven't found it.
I create the site in pingendo and below the section tag there are other tags:

http://jsfiddle.net/27ywnftm/

```html
<div id="fullpage">	
<div class="container">
                   <div class="section">
            
                <div class="row">
                    <div class="col-md-12">
                        <div class="ccimg"></div>
                    </div>
                </div>
             </div>
</div>
.
.
<div class="container">
                   <div class="section">
.
.
```
I found that in this case the fullpage.js does not find the section tags.
Do you have any suggestion?

**Comment by alvarotrigo** [comment]
That is simply because you are not following the [required HTML structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure). 
```html
<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>
```

**Comment by Avemaar** [comment]
thank you i already know that.But pingendo will not works with the suggested structure

**Comment by alvarotrigo** [comment]
Then use the `.container` as the wrapper for fullpage.js.
```javascript
$('.container').fullPage();
```

**Comment by Avemaar** [comment]
Excusme i have to use the 
sectionSelector: '.container',
option
