### ISSUE TITLE
how to allow only scrollbar-y?

### ISSUE THREAD

**Issue by Avemaar** [alvarotrigo/fullPage.js#1350]
i have an unwanted scrollbar-x appeared in my body tag due the fullpage.js plugin.
I know i can tilt in css by:
overflow-x: hidden
but hier does not work.I use scrollBar: true which add the scrollbars to the site.
How can i only allow the scrollbar-y?

**Comment by alvarotrigo** [comment]
Reproduce and isolate the problem in [jsfiddle](http://jsfiddle.net/97tbk/418/) if you believe its a bug.

None of the example pages has any scroll bar in the X axys, it seems to me that its a matter of CSS and other elements of your site such as Images.

**Comment by Avemaar** [comment]
thank xou for your answer,well i believe its not a bug in the plugin.
Its just comes because my design:
http://jsfiddle.net/gxkLkmrL/
So i have to show the image like this way,i hide the scroll-x while i need the scroll-y

When scrollBar: true than both scrolls are emabled

**Comment by alvarotrigo** [comment]
> Its just comes because my design:

You'd better ask in other place then.
