### ISSUE TITLE
Scrolling inside section issue on firefox (scrollOverflow: true, scrollBar: true)

### ISSUE THREAD

**Issue by DLudo** [alvarotrigo/fullPage.js#1352]
scrollOverflow: true,
scrollBar: true,

These two lines seems to create conflict. In firefox, it's impossible to scroll to the next section, the only way to solve it is to set the scrollBar as false (It cancel the window scroll functions unfortunately.)
Chrome is fine with it.

Best regards & ty for all.

**Comment by alvarotrigo** [comment]
> scrollOverflow: true,
> scrollBar: true,

Those options are not compatible with each other.

I guess I'll have to show a warning message or disable one when enabling the other as other people reported the same problem. (which is not a bug, but a design decision)

**Comment by alvarotrigo** [comment]
Solved in 2.6.7 with a warning message.
