### ISSUE TITLE
div ID

### ISSUE THREAD

**Issue by ds1239** [alvarotrigo/fullPage.js#1353]
Hello,
I would like to add ids to the divs so I could use a bootstrap navbar, but when I try, It removes the scrolling animation when switching pages. Can someone please help?

**Comment by alvarotrigo** [comment]
It is not possible. Browsers don't allow to overide the default behaviour of a URL with an ID value for an anchor link.

As said in the docs:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by ds1239** [comment]
How could I use the native bootstrap navbar then?

**Comment by alvarotrigo** [comment]
You don't need IDs to use it...

**Comment by ds1239** [comment]
When I click on a navbar link, the item's class isn't set to "active", and there is no indication on the navbar showing which page the user is on.

**Comment by alvarotrigo** [comment]
See [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) sourcecode and read the docs regarding the `menu` option.

**Comment by ds1239** [comment]
Got it thanks.
