### ISSUE TITLE
Multiple pages for a single menu element

### ISSUE THREAD

**Issue by kelf47** [alvarotrigo/fullPage.js#1354]
Hello! I'm trying to add multiple pages for each menu element, for example the user can scroll down three pages and the top menu is fixed in the same elem.
I repeat the elems in the anchors and the scroll goes well, but not the links.
anchors: ['first', 'first', 'first', 'second', 'second', 'third']
In the example above just the last link is working, the others are raising this error: 
```
Uncaught TypeError: Cannot read property 'replace' of undefined
```
There is a properly way to do this? 
Thanks a lot.

**Comment by alvarotrigo** [comment]
Anchors can not be duplicated.

**Comment by alvarotrigo** [comment]
I guess I'll have to add in the documentation, but it should be quite obvious... you can not bookmark two URLs which are the same, and it wouldn't make any sense when coming from a direct link.

**Comment by kelf47** [comment]
Ok, at the end I've add a trick to underline the Menu with the other pages. Anyway I think would be good to allow users to have more than one page for the same menu item. A section could be 3 or 4 pages scrolling down, and the link just scroll to the first one.
Amazing peace of code anyway :) thanks

**Comment by alvarotrigo** [comment]
> Anyway I think would be good to allow users to have more than one page for the same menu item.

That is already possible. You just have to play with the plugin callbacks or with the class added to the body (`fp-viewing-xxx`)

**Comment by kelf47** [comment]
Ok, I didn't found it in any demo or docs, maybe I missed it.
Thanks for the info.

**Comment by alvarotrigo** [comment]
> Ok, I didn't find it in any demo or docs, maybe I missed.

Because there arent about it. 
It is a specific issue as many others.

Knocking about how callbacks works or the basics of CSS many things, including your specific case, are easy to solve.

**Comment by alvarotrigo** [comment]
Documentation updated.
