### ISSUE TITLE
"vertical-align: top" not working

### ISSUE THREAD

**Issue by ds1239** [alvarotrigo/fullPage.js#1355]
Hello. Sorry for asking so many questions. I like the default "vertical-align: center", but I want a few elements to be set to "vertical-align: top" (images), however it doesn't seem to have any effect on the elements. Thanks in advance

**Comment by alvarotrigo** [comment]
You should overide the value by using `!important`.

**Comment by ds1239** [comment]
That didn't work

**Comment by alvarotrigo** [comment]
You'd better ask in another place such as stackoverflow or look for the answer in the forum, that's about CSS, not about fullpage.js.
