### ISSUE TITLE
With a fixed header and a normal footer, how to?

### ISSUE THREAD

**Issue by purezhi** [alvarotrigo/fullPage.js#1356]
I want to create a page like: [http://www.smartisan.com/en/#/overview](http://www.smartisan.com/en/#/overview).
The page has a fixed header, and after serveral full page there is a normal scroll footer.
How to do this with fullPage.js? Any tips? 
Thanks.

**Comment by alvarotrigo** [comment]
> The page has a fixed header, and after serveral full page there is a normal scroll footer.

It is not normal. But in any case, fullPage.js doesn't provide a way to do it.
