### ISSUE TITLE
Popin with dropdown list outside fullpage  - Disable mousewheel / trackpad

### ISSUE THREAD

**Issue by ELacasia** [alvarotrigo/fullPage.js#1358]
Hello,
In my project, a popin is present outside the fullpage element (before body end, position fixed, ...).
When the popin is open, you can choose a country in a dropdown list but when you use the mousewheel or a trackpad, you switch in another section, but I want to disable this when the focus is in this select box.
"normalScrollElements" for parents elements works with chrome, not firefox..
How can I do that?
Thanks for your answers.

**Comment by alvarotrigo** [comment]
Reproduce your issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) for further examination. 
Closed until then.

**Comment by ELacasia** [comment]
Thanks, I've Updated the jsfiddle <http://jsfiddle.net/97tbk/704/>.

  <http://www.onibi.fr>
 Eric Lacasia
eric.lacasia@onibi.fr
T : +33 (0)970 44 66 57
www.onibi.fr

2015-07-09 13:08 GMT+02:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
Sorry I can not reproduce your issue. 
[Here's the fiddle](http://jsfiddle.net/imac/97tbk/705/) working properly on the latest version of Firefox  after using `normalScrollElements`

**Comment by ELacasia** [comment]
I have a Macbook Air :
- if the cursor is hover in .geopopin, the use of Mousewheel or Trackpad does
not trigger the section switch and it is good,
- if the focus is in the dropdown list and I use the Mousewheel or the
Trackpad to list all countries (up and down), I switch to another section

Could you please try again ?
Sorry for my english sometimes...

  <http://www.onibi.fr>
 Eric Lacasia
eric.lacasia@onibi.fr
T : +33 (0)970 44 66 57
www.onibi.fr

2015-07-09 14:00 GMT+02:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
Are you able to reproduce the problem it [in the jsfiddle I provided](http://jsfiddle.net/imac/97tbk/705/)?

**Comment by alvarotrigo** [comment]
I would recommend you to follow [this suggestion](http://stackoverflow.com/questions/30185586/fullpage-js-scrolling-on-top-of-select-element-in-ie-and-firefox/30188977#30188977).

Which is, disabling the autoscroll whenever you open the fixed element. 

```javascript
//enabling
$.fn.fullpage.setAllowScrolling(true);

//disabling
$.fn.fullpage.setAllowScrolling(false);
```

**Comment by ELacasia** [comment]
Ok, Thank you so much for your  time, your quick answer and your
suggestion, it solves my problem :)
Best Regards !

  <http://www.onibi.fr>
 Eric Lacasia
eric.lacasia@onibi.fr
T : +33 (0)970 44 66 57
www.onibi.fr

2015-07-09 15:56 GMT+02:00 Álvaro <notifications@github.com>:
