### ISSUE TITLE
Still problems on WP 8.1

### ISSUE THREAD

**Issue by JanaKemmer** [alvarotrigo/fullPage.js#1359]
I just read the old issue regarding the WP8.1 bug and it still is present on my device. 
The site scrolls after clicking any of the navigation-elements, but it can't scroll in any way else. 

The problem appears on my site aswell as your demo-page.

**Comment by alvarotrigo** [comment]
I am waiting for an answer of @kamilgrymuza  in [this other topic](https://github.com/alvarotrigo/fullPage.js/issues/160).

If you can provide me with the feedback that'd be awesome.

I'll close the topic as it is being discussed in the previous link.
