### ISSUE TITLE
Scroll behaviour improvement for scrollOverflow=True

### ISSUE THREAD

**Issue by jscontrust** [alvarotrigo/fullPage.js#1360]
When scrollOverflow is activated, the inner scroll of the section is not always at bottom, when scrolling to the section above, or it is not at top, when scrolling to the section below. This creates ugly effects while scrolling through the sections.

I added the following function to avoid this:

    setSectionScroll: function (current_anchor) {
      // Correct scroll value of section above and below
      var $cur_section = $(".section[data-anchor='" + current_anchor + "']");

      $cur_section.prev().each(function () {
        $(this).find(".fp-scrollable").slimScroll({ scrollTo: '10000px' }); 
      });

      $cur_section.next().each(function () {
        $(this).find(".fp-scrollable").slimScroll({ scrollTo: '0px' }); 
      });
    },

Maybe something like this is useful for the fullpage.js core code.

**Comment by alvarotrigo** [comment]
If you reproduce the issue you are talking about in [jsfiddle](http://jsfiddle.net/97tbk/418/) I'll be able to examine it.

**Comment by jscontrust** [comment]
I will try to find some time to demonstrate this in jsfiddle...

**Comment by alvarotrigo** [comment]
It seems you are talking about [this same issue](https://github.com/alvarotrigo/fullPage.js/issues/1361)?

Using magic mouse? (kinetic scrolling)

**Comment by tulsadome** [comment]
I added this code to fix this for me.

'''onLeave: function() {
        setTimeout(function() {
          $('.fp-scrollable').slimScroll({ scrollTo : '0px' });
        }, 1000);'''

**Comment by alvarotrigo** [comment]
Closed until provided a reproduction of the issue.
