### ISSUE TITLE
Apple Magic mouse scroll improvement

### ISSUE THREAD

**Issue by jscontrust** [alvarotrigo/fullPage.js#1361]
It is hard to navigate on a fullpage.js page with scrollOverscroll=True with the apple magic mouse, because even if you scroll gentle, you always land on the next section if you want to scroll inside a section.
So I changed a part of the MouseWheelHandler Function to

    //haven't they scrolled in a while?
    //(enough to be consider a different scrolling action to scroll another section)
    if(timeDiff > 500){
        //emptying the array, we dont care about old scrollings for our averages
        scrollings = [];
    }

    if(canScroll){
        var averageEnd = getAverage(scrollings, 10);
        var averageMiddle = getAverage(scrollings, 70);
        var isAccelerating = averageEnd >= averageMiddle;

        var isVerySlow = false;
        if (scrollings.length>10 && scrollable) {
            isVerySlow = getAverage(scrollings, 10) < 50;    
        }  

This works much better, because it kind stops when you scroll gentle and continues to next slide if you continue scrolling.

By the way: Thank you for this great plugin :)

**Comment by alvarotrigo** [comment]
It seems you need to add more of your code, you don't show what you do with the variable `isVerySlow` in your portion of code.

In any case, make sure you test it with normal mouses too!

**Comment by alvarotrigo** [comment]
Closed until provided more info.

**Comment by Schwankenson** [comment]
Oh, I`m sorry, I forgot to copy the line:

                //haven't they scrolled in a while?
                //(enough to be consider a different scrolling action to scroll another section)
                if(timeDiff > 500){
                    //emptying the array, we dont care about old scrollings for our averages
                    scrollings = [];
                }

                if(canScroll){
                    var averageEnd = getAverage(scrollings, 10);
                    var averageMiddle = getAverage(scrollings, 70);
                    var isAccelerating = averageEnd >= averageMiddle;

                    var isVerySlow = false;
                    if (scrollings.length>10 && scrollable) {
                        isVerySlow = getAverage(scrollings, 10) < 50;    
                    }                    

                    //to avoid double swipes...
                    if(isAccelerating && !isVerySlow){

**Comment by jscontrust** [comment]
Oh, I`m sorry, I forgot to copy the last needed line. I corrected it in the entry above

    //to avoid double swipes...
    if(isAccelerating && !isVerySlow){

**Comment by alvarotrigo** [comment]
As I said:

> In any case, make sure you test it with normal mouses too!

**Comment by Schwankenson** [comment]
I did, and it worked with the mouses I tested...

**Comment by jscontrust** [comment]
I did, and it worked with the mouses I tested...

**Comment by kilianso** [comment]
Can you provide a demo? Because i have exactly the same problem and the approaches here with setTimeout aren't really fixing the problem. I have a fullpage slider with five slides and the last one is higher than the viewport so scrollOverflow is true. But with the magic mouse, the fp-scrollable site already scrolls down if i enter that slide. I need to block this.
