### ISSUE TITLE
Return false on click won't work

### ISSUE THREAD

**Issue by Vanss472** [alvarotrigo/fullPage.js#1363]
Hi, I'm using return false on my index 5 to lock the scroll down and then creating an on click event to reveal my index 6. It is working fine except when I'm on the index 5. I'm not scrolling, I'm just clicking index 6 link. Why would it fire on the rest and not on the 5?

 Here a jsfiddle example:  https://jsfiddle.net/Vanss472/eLxxj357/

V

**Comment by alvarotrigo** [comment]
Just read your own comment:

>  //it won't scroll if the destination is the 6th section

Your destination still being the 6th section, so it wont scroll.

If you only want to disable the mouse wheel scroll use the function [`setAllowScrolling`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions)

**Comment by Vanss472** [comment]
Rad, all good now. Thanks!

https://jsfiddle.net/Vanss472/eLxxj357/2/
