### ISSUE TITLE
Update options

### ISSUE THREAD

**Issue by JoshuaNovak919** [alvarotrigo/fullPage.js#1366]
Anyone know of a way to update options after the plugin has been called? Basically because of resizing issues etc I need to change `fixedElements` when the window is resized to a certain size.

**Comment by alvarotrigo** [comment]
You really wouldn't need to use `fixedElements` option anymore. 
Why don't you just place those elements outside the plugin wrapper ?

**Comment by JoshuaNovak919** [comment]
I ended up destroying the plugin, hiding the elements, adding them to `fixedElements` which basically moves them outside of the wrapper anyway, and then build again. Then when the size gets bigger I destroy the plugin again, move the element back, and build the plugin.

**Comment by alvarotrigo** [comment]
Ok, I'll close the issue then.
