### ISSUE TITLE
Rebuilding Fullpage.js to detect dynamically added slide class

### ISSUE THREAD

**Issue by spandadk** [alvarotrigo/fullPage.js#1368]
Im trying to rebuild fullpage so it detects slides that i've dynamically added when having re-sized the browser to a specific breakpoint.

I have an initial structure without any slide class that looks as so:
```
<div class="section">
<div class="block">Content block that will turn into a slide at some point...</div>
<div class="block">Content block that will turn into a slide at some point...</div>
</div>
```

However when hitting some mobile specific breakpoint, then i'd like to rebuild the content block, to behave as a slide.

Simplified what im doing is, to check for the breakpoint and when hitting it then I change all my class="block" to class="slide" and then use the Fullpage rebuild function.
```
if (!mobile && $(window).width() > 320 && $(window).width() < 400) {
	var total = $('.section').length;

	$('.section').each(function(index){
	    $('.section').find(".block").removeClass( "block" ).addClass( "slide" );

	    if (index === total - 1) {
	        // the last index - were ready to rebuild

	        $.fn.fullpage.reBuild(); //rebuild to detect the slide class
	    }
	})
}
```

The class="slide" gets added/changed fine however im not seeing an results when rebuilding. What im trying to do, is that possible to achieve with Fullpage?

**Comment by alvarotrigo** [comment]
The reBuild function does not what you expect:

> **reBuild()**
Updates the DOM structure to fit the new window size or its contents. Ideal to use in combination with AJAX calls or external changes in the DOM structure of the site.

It only adapts the plugin to the new window dimensions. Something necessary when using `scrollOverflow:true`.

In your case you would have to use `destroy('all)` to destroy the plugin and then initialize it again.
