### ISSUE TITLE
Fullpage.js keeps throwing this error on certain pages

### ISSUE THREAD

**Issue by umarfarooq360** [alvarotrigo/fullPage.js#1371]
Uncaught TypeError: Cannot read property 'offsetTop' of undefined
scrollHandler @ jquery.fullPage.js:774
m.event.dispatch @ jquery.js:3
m.event.add.r.handle @ jquery.js:3

**Comment by alvarotrigo** [comment]
Closed until provided a reproduction of the problem or a way to reproduce it.
