### ISSUE TITLE
How to disable plugin when content is longer and doesn't fit screen?

### ISSUE THREAD

**Issue by testerr123** [alvarotrigo/fullPage.js#1372]
Hey guys, I have a problem with different resolutions of screen. Sometimes content doesn't fit and I can't see it

I guess I should disable fullPage.js on ceratin resolutions but I don't know when. Could you check my demo and suggest something?

Here is a demo: http://codepen.io/anon/pen/aOjKYo

**Comment by alvarotrigo** [comment]
Here you [have a demo](http://alvarotrigo.com/fullPage/examples/responsive.html).

Use the `responsiveWidth` or `responsiveHeight` options available now. Check the docs for more info.

**Comment by alvarotrigo** [comment]
If besides that, you want to make the sectionsn bigger than the viewport height, follow [this instructions](https://github.com/alvarotrigo/fullPage.js/issues/1044#issuecomment-75812112).

If you still want to destroy it all, use the `destroy` function.

**Comment by testerr123** [comment]
I will check this out, however it is more complicated than I thought.
