### ISSUE TITLE
Video and Lazy Load

### ISSUE THREAD

**Issue by br0k3n** [alvarotrigo/fullPage.js#1374]
I'm using your fullpage.js jquery plugin, it\'s great!
I've only an issue that I can't explain, in particular the lazy load doesn't seems to work.
Take a look to this link: http://goo.gl/CF0URS
The second slide (test001) is a video with the data-src tag, but it doesn't work :(

Please, could you help me?

Thanks so much

Nicola

**Comment by iarcas** [comment]
same problem!

**Comment by alvarotrigo** [comment]
Will be solved for the next release.

**Comment by iarcas** [comment]
Cool! Do you know when will the next release be? (more or less)

**Comment by alvarotrigo** [comment]
@iarcas as I'll be on holidays for two weeks, I guess at least 3 weeks. There are some other issues I want to solve for the next release.

If you need it earlier feel free to ask for [an urgent request](http://alvarotrigo.com/#contact-page) and I'll provide with a quote.

**Comment by alvarotrigo** [comment]
Solved in 2.6.8.
