### ISSUE TITLE
Page not scrolling on load

### ISSUE THREAD

**Issue by robhadfield** [alvarotrigo/fullPage.js#1375]
Hi all

I'm sure this is a really daft issue but I can't seem to get my site to scroll to the correct section on page load. My init is very simple and I don't see any differences from the live demo but it just won't scroll to the hashed section on page load eg: domain.com#about (which is the second section) it still loads the first section.

        $('#siteWrap').fullpage({
          anchors: ['home', 'about', 'gallery', 'prices', 'contact', 'info'],
          navigation: true,
          navigationPosition: 'right',
          scrollingSpeed: 1000,
          css3: true
        });

Everything else works fine with no errors - menu, navigation, back button. It's just that initial load.

Dev site link : http://bit.ly/1Lk8kEj

Any ideas?

**Comment by alvarotrigo** [comment]
Sorry I can't provide support because you have removed the compulsory credits of the plugin and I can not even know which version you are using. 

The MIT license states:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by robhadfield** [comment]
Sorry @alvarotrigo , I think that's my minification settings ripping all comments out - certainly not deliberate.

Anyway, it appears that it was a conflict from another plugin causing it (jquery lightbox). I've corrected the code and also reinstated the licencing :+1:
