### ISSUE TITLE
[suggestion] Use transform instead of margin ?

### ISSUE THREAD

**Issue by darkyen** [alvarotrigo/fullPage.js#1376]
While using fp-nav you seem to be using -ve margin for centering, it is though very possible to simply use transform instead by transform[Dir]: -50%; and it will center the nav.

**Comment by alvarotrigo** [comment]
Anything against the way its done now? 
Any advantages with your suggestion?

**Comment by alvarotrigo** [comment]
If you think it is possible to do it maintaining compatibility with IE 8, then feel free to open a pull request.

**Comment by darkyen** [comment]
IE 8 might not be possible, but transforms are much better for animating in general.

**Comment by darkyen** [comment]
Also please check out css snap point spec, its getting nice traction and allows to have butter smooth scroll experience even on really starting range phone (tested on a lumia 520) maybe create a polyfill for snap points as core for this lib ?

**Comment by alvarotrigo** [comment]
> IE 8 might not be possible

Then it won't be added yet. Plus the advantages seems not to be clear. I'll close the topic for now.

> Also please check out css snap point spec

I would recommend you to create another issue for it for further discussion.
