### ISSUE TITLE
Disable One page scroll for single section

### ISSUE THREAD

**Issue by paramsinghvc** [alvarotrigo/fullPage.js#1379]
Is it possible to disable full page scroll for a single section that has larger height. I have to compromise with the content otherwise. Is there a way? I want the user to scroll in between these two section
![screen shot 2015-07-20 at 1 12 30 pm](https://cloud.githubusercontent.com/assets/4329912/8771613/61d0aab8-2ee1-11e5-89b1-29ccfcbb0e3a.png)
![screen shot 2015-07-20 at 1 12 42 pm](https://cloud.githubusercontent.com/assets/4329912/8771614/61d25c6e-2ee1-11e5-9367-5082fbc20bdb.png)

**Comment by paramsinghvc** [comment]
Solved It

**Comment by alvarotrigo** [comment]
I guess you ended up using the option `scrollOverflow:true`.

**Comment by fabriziofeitosa** [comment]
Sorry to relive the post, but what was the solution?
