### ISSUE TITLE
[Error?] Auto scrolling to beginning of the section

### ISSUE THREAD

**Issue by ljubic** [alvarotrigo/fullPage.js#1381]
Please take a look at the website I created for my friend:
http://www.szv-bau.at

There is a problem when it's displayed on mobile:
* Scroll to the very bottom of the page (of the contact section)
* After you release your finger, the it will be auto scrolled to the beginning of contact section

How can I disable this?

**Comment by alvarotrigo** [comment]
Use `fitToSection:false`.
