### ISSUE TITLE
Custom slide arrows?

### ISSUE THREAD

**Issue by asplogin** [alvarotrigo/fullPage.js#1382]
Hey

I have 2 sections with slides. First section has 2 slides on white background. The second section has also 2 slides but on blue background. How to make those arrows different? green on white and white on blue?

Thanks!

**Comment by alvarotrigo** [comment]
CSS is your answer. Look in the forum, it has been treated before.

**Comment by asplogin** [comment]
Can't find a solution. I can change the arrows by css but it changes both of them. I don't know how to separate them between the sections.....

**Comment by alvarotrigo** [comment]
That's not a question for this forum I'm afraid. It is about CSS and not about fullpage.js.
