### ISSUE TITLE
fullpage.js related - regarding scrolling

### ISSUE THREAD

**Issue by grchap1** [alvarotrigo/fullPage.js#1384]
Hey, 
My usecase is there are 3 sections in the page. First section is a intro text to the page, the 2nd section is a html form - long section in the page. Here, when the user is scrolling,  if there a way to stop in the middle of a section with a mouse click so user could enter the form fields and proceed?  Currently it scrolls all the way to next section. Even a mouseclick does not stop the scrolling

**Comment by alvarotrigo** [comment]
Use `scrollOverflow:true` as [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html). 
It is available in the examples folder as well.

**Comment by grchap1** [comment]
U D man !!! Thanks
