### ISSUE TITLE
Is it possible to have swipable cards ?

### ISSUE THREAD

**Issue by darkyen** [alvarotrigo/fullPage.js#1385]
Like the material design card stack for horizontal swipe ?

**Comment by alvarotrigo** [comment]
Nothing to do with fullPage.js I'm afraid.

**Comment by darkyen** [comment]
I am afraid it does, what I was asking is instead of pure linear slide moves is it possible to make custom transitions ?

**Comment by alvarotrigo** [comment]
Nop, this is a scrolling plugin. If you want to do so, you'd better use another external slider inside a section, although you might have problems on mobile.

**Comment by darkyen** [comment]
@alvarotrigo ended up creating my own :-) its a css snap point polyfill (internal)
