### ISSUE TITLE
trouble getting height for non-full page scroller

### ISSUE THREAD

**Issue by djowett** [alvarotrigo/fullPage.js#1386]
I'm working on [this](http://borgbakery.jowettenterprises.com/), which is working pretty well, but note that there is a header that is not meant to scroll.  It does stay fixed, but it seems that the height of my section is being calculated to be the height of the whole page.

That doesn't matter in the most part, but it IS meaning I'm not seeing 150-160 pixels of the bottom of my background image. (See the our-products section).

Do you have any advice on how to solve that?  I've thought of subtracting the height of specified elements (in my case #header & friends) from the windowsHeight variable, but I'm not sure whether that's the best approach.

I am working on a solution, which I can present as a Pull Request in due course, but I'm not sure if you will agree with the approach...

**Comment by alvarotrigo** [comment]
Your `header` doesn't have position `fixed`.

**Comment by djowett** [comment]
Thanks Alvaro.   spot on!  That (and the package in general) is worth a large coffee I reckon :-)
