### ISSUE TITLE
Can't scroll other pages while using fullPage.js

### ISSUE THREAD

**Issue by rohan-krishna** [alvarotrigo/fullPage.js#1387]
I'm using this in wordpress and I have other pages in my wordpress which aren't using the flow. It seems that I can't scroll in all of my other pages since the plugin is adding 
```
overflow : hidden;
height: 100%;

```
in the body tag and html tag which prevents the other normal pages from scrolling.Any fixes for this?
I even tried 
```
scrollBar : true

```
I could see the scrollBar bu seems like I can't scroll using mouse wheel ... I have to drag the bar to scroll.

**Comment by alvarotrigo** [comment]
Yeah. Just don't initialise it.
