### ISSUE TITLE
Remove a slide afte render

### ISSUE THREAD

**Issue by aireater** [alvarotrigo/fullPage.js#1390]
Is it possible to remove a slide after render? 

For example, there are slides 1-15. In certain cases (after an async ajax call) it would need to remove slide 7 and move from 6 directly to 8. 

Great plugin btw and thanks in advance.

**Comment by alvarotrigo** [comment]
I dont see why not. Just use jQuery or javascript for it.

**Comment by aireater** [comment]
That was simple enough. Leaving the solution here if isn't obvious for someone else. You have to remove the element, just hiding it breaks scrolling.
