### ISSUE TITLE
Scrolling only using keyboard arrows

### ISSUE THREAD

**Issue by iarcas** [alvarotrigo/fullPage.js#1392]
Hi!
First of all, congrats for this great library!

I was wondering if there is any way to allow scrolling only using the keyboard arrows so no mouse scrolling allowed.

Thanks in advance!
I.

**Comment by llahnoraa** [comment]
Yes, you can. With up/down arrow. Did you not read the instruction? ;)

**Comment by iarcas** [comment]
Lol, I knew that. What I mean is how to disable mouse scrolling. There is a keyboardScrolling: true, and I was wondering if there is any way to set "mouseScrolling: false" so even if user tries to scroll with mouse it won't do anything.

Thanks!

**Comment by llahnoraa** [comment]
Ah, makes sense. That's a good suggestion. We'll see what this guy has to say.

**Comment by alvarotrigo** [comment]
You can easily use `setAllowScrolling` inside the `afterRender` element to disable the mouse/touch scrolling. 

I guess using only arrows won't make much sense in touch devices, but in any case, a new option to disable it by default might be a nice idea.

I'll mark it as an enhancement.

**Comment by iarcas** [comment]
That's exactly what I was looking for! Thanks a lot :)
