### ISSUE TITLE
slimscroll scrolling changes active section too easily

### ISSUE THREAD

**Issue by tulsadome** [alvarotrigo/fullPage.js#1394]
When scrolling in a section with slimscroll, near the bottom of the section it is too easy to scroll to the next section accidentally. This makes the site appear buggy as you then have to scroll back up to the section you just accidentally exited. It would make more sense if when you scroll to the bottom of a slimscroll element it would bottom out and you would have to scroll once again to change sections.

**Comment by iMoses** [comment]
+1
I just started working on a landing page with some scrollable sections and I came across this issue.
I'll pick at the source code tomorrow to see if I can create a quick fix.

**Comment by alvarotrigo** [comment]
Already being treated in this open issue:
https://github.com/alvarotrigo/fullPage.js/issues/941

I'll close this one as it is duplicated.

**Comment by iMoses** [comment]
I couldn't figure from the original issue if it has been solved or simply closed. If anyone needs a solution please contact me, I've create a really simple solution locally and I'm willing to share :)

**Comment by alvarotrigo** [comment]
@iMoses it hasn't been solved. That's why the issue still open. If you have any suggestion, add a pull request or comment it in the original issue.

**Comment by tulsadome** [comment]
@iMoses I'd love to have a look at your simple fix if it's possible

**Comment by heron88** [comment]
@iMoses also interested in your solution.

**Comment by alvarotrigo** [comment]
@tulsadome @heron88 which "simple fix" are you talking about? I haven't provided any solution for it at the moment.

**Comment by tulsadome** [comment]
@alvarotrigo we're referring to @imoses offering to share his simple fix for this problem if anyone was interested

"I couldn't figure from the original issue if it has been solved or simply closed. If anyone needs a solution please contact me, I've create a really simple solution locally and I'm willing to share :)"

**Comment by iMoses** [comment]
The code is currently located at my office pc, so I'll update you at the beginning of next week.
