### ISSUE TITLE
normalScrollElements on chrome

### ISSUE THREAD

**Issue by khoatranthanh** [alvarotrigo/fullPage.js#1395]
normalScrollElements not run in Chrome newest. Please help me!
I add class into it and nothing happend. Firefox ok but chrome error

**Comment by alvarotrigo** [comment]
It is working for me on the [demo page](http://alvarotrigo.com/fullPage/examples/scrolling.html).

You don't have to add any class at all. Read the documentation and take a look at the examples provided in the plugin.
