### ISSUE TITLE
My menu doesn't overlap...and looks awful! && Why does slider scrolling fail?

### ISSUE THREAD

**Issue by haydgately** [alvarotrigo/fullPage.js#1397]
Any ideas as to why my menu would do this on http://www.technicode-solutions.com/ ? It doesn't scroll down to other pages! Also, is it meant to link to the fullPage.css and look like the demo page menu?

Also, any ideas why scrolling with the mouse works downwards but not horizontally on slide 4? Only the buttons work! 

Thanks.

**Comment by alvarotrigo** [comment]
You are not even initialising fullpage.js.
