### ISSUE TITLE
One single selection using left,right arrowkeys

### ISSUE THREAD

**Issue by Avemaar** [alvarotrigo/fullPage.js#1398]
First of all let me appologise if i haven't read the documentation
properly.I have i page like in the demo one single selection with a slider.
However keyboardScrolling: true, i can not use left and right keys.
What should i do?

**Comment by alvarotrigo** [comment]
You can use them in the slides as you can see in [the demo page](http://alvarotrigo.com/fullPage/#secondPage)

**Comment by Avemaar** [comment]
excusme but as i described it i want to adjust the plugin only in one page(selection) as a slider.
On the rest of the pages i don't want to apply i want those pages as normal website pages

**Comment by alvarotrigo** [comment]
I guess you are talking about [this example](http://alvarotrigo.com/fullPage/examples/oneSection.html).

In that case the plugin doesn't provide keyboard navigation. This is a design decision and it won't change. 

You can always attach the events to the keyboard by yourself by using javascript/jQuery and the method $.fn.fullpage.moveSlideRight()  or $.fn.fullpage.moveSlideLeft().

Take a look at [this answer](http://stackoverflow.com/a/29822757/1081396).
