### ISSUE TITLE
Text abruptly hides then shows if overlaying on video

### ISSUE THREAD

**Issue by jephjohnson** [alvarotrigo/fullPage.js#1401]
Not sure if this has been reported yet or if anyone can let me know the fix. In the example below, if I am in the last section then scroll backup to the top (first section) where my video is playing, my text will hide abruptly then reappear. I tried forcing styles on the selector to keep it visible, etc.. but nothing seems to work. This bug is happening on all modern browsers and only when using video.

You can view the bug here:
http://alvarotrigo.com/fullPage/examples/videoBackground.html

**Comment by alvarotrigo** [comment]
Try using `-webkit-transform: translate3d(0,0,0);` for the text.

It is a bug with the browsers rather than with fullpage.js. 
http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d

**Comment by jephjohnson** [comment]
@alvarotrigo - Thank you!!
