### ISSUE TITLE
Wrapping slides into more divs while in .section

### ISSUE THREAD

**Issue by jelenajjo** [alvarotrigo/fullPage.js#1402]
Maybe this isn't even possible but it would be cool if it is. So, here is the simple example of what I need: 
```
<div id="fullpage">
<div class="section" id="section1">
    <div class="sliding">
            <div class="slide">
                SLIDE 1
            </div>
            <div class="slide">
                SLIDE 2
            </div>
            <div class="slide">
                SLIDE 3
            </div>
            <div class="slide">
                SLIDE 4
            </div>
	</div>
	<div class="sliding2">
            <div class="slide">
                SLIDE 1
            </div>
            <div class="slide">
                SLIDE 2
            </div>
            <div class="slide">
                SLIDE 3
            </div>
            <div class="slide">
                SLIDE 4
            </div>
	</div>
</div>
</div>
```

The idea is to `display:none;` the `.sliding2` div on desktop and to display only on smaller resolutions, because of different content inside slides. Basically, to work with those two divs through CSS media queries. But the weird thing happens. 

![](http://content.screencast.com/users/plavo0kac/folders/Jing/media/31e891db-96ac-485b-b955-66eb16c79ce5/2015-07-28_0019.png)

As you can see, all slides are inside `.sliding` div and the `.sliding2` is empty. Any ideas how to make this work?

Thanks! :)

**Comment by alvarotrigo** [comment]
I'm afraid the plugin doesn't provide such an option.
You would have to do it by yourself.
