### ISSUE TITLE
Destroy() doesn't clear html/body classes and inline styles

### ISSUE THREAD

**Issue by SergeRNR** [alvarotrigo/fullPage.js#1403]
After destroy() method call helper classes and inline styles are not cleared:
html : class= fp-enabled, style=overflow: visible; height: initial;
body: class= fp-viewing-0, style=overflow: visible; height: initial;

Demo from DOCs, please inspect iFrame:
http://codepen.io/alvarotrigo/pen/bdxBzv

**Comment by alvarotrigo** [comment]
Thanks for reporting it.
I'll take a look at it for the next release.

**Comment by ziggythehamster** [comment]
#1414 fixes the style, #1418 fixes the classes

**Comment by alvarotrigo** [comment]
Solved.
