### ISSUE TITLE
fullPage Javascript not workin on iOS?

### ISSUE THREAD

**Issue by lichtensteinberlin** [alvarotrigo/fullPage.js#1404]
hi,

just tested the demo of the pure js fullpage script and was wondering if it is working on iphone/ipad as well?

thanks.

sascha

**Comment by alvarotrigo** [comment]
It does

**Comment by lichtensteinberlin** [comment]
fullpage pure javascript (alpha).
mh, it only shows the first (green) section on ios 8.4 safari
i tested on both devices (ipad and iphone). even not with chrome developer tools (mobile view). but thanks anyway.
