### ISSUE TITLE
ui-tabs and fullpage.js issue

### ISSUE THREAD

**Issue by grchap1** [alvarotrigo/fullPage.js#1406]
This usecase is as below - 
I have horizontal tabs on top (that uses jquery-ui  - ui-tabs)
<div id="tabs1">
  <ul>
    <li><a id="t1" href="#">First</a></li>
    <li><a id="t2" href="#">Second</a></li>
    <li><a id="t3" href="#">Third</a></li>
 </ul> </div>
Each tab is a hyperlink.
When "second" Tab is clicked it pulls up a page where I use the fullpage.js
That page has 3 sections. The first section pulls up with the 3 tabs on the top.

When user is scrolling the second section shows up with part of first section on top(that height kind of matches the tab height in first section)

I do have scrollOverflow:true.

How do I fix that please.

**Comment by grchap1** [comment]
![image](https://cloud.githubusercontent.com/assets/8300562/8942997/6ba7b7e6-3546-11e5-9a4a-088417a4a774.png)
![image](https://cloud.githubusercontent.com/assets/8300562/8943059/b5a79726-3546-11e5-818e-8a74d5c4aa8c.png)

**Comment by grchap1** [comment]
Hey alvarotrigo,
Could you please have a look at this?

**Comment by alvarotrigo** [comment]
Please provide a reproduction of the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) for further investigation.

Closed until then.

**Comment by grchap1** [comment]
Thanks for your response.
Here is the jsfiddle link,
http://jsfiddle.net/97tbk/736/

**Comment by alvarotrigo** [comment]
I'm afraid that's not a fullpage.js issue but an issue with external code / CSS.

You'd better ask those questions in other place such as stackoverflow.com

Take into account that fullpage.js is a FULL PAGE plugin and it is suppose to work as so. It is not suppose to be inside any other element.

**Comment by grchap1** [comment]
I agree it is a for FULLPAGE. I, along with others really appreciate your work. This particular usecase is very common need. Your  fullpage.js  will become more prevalant and more famous if this is addressed. I tried playing with z-index - still fullpage.js simply stays on the top of the tab always. Any help welcome.
I will post in stackoverflow.com also.

**Comment by alvarotrigo** [comment]
Your problem is not in fullpage.js but in the way you are using it. Not a topic which belongs to this forum.
