### ISSUE TITLE
Disable vertical scroll for few scrolls, and attach it to individual elements

### ISSUE THREAD

**Issue by talk2mitjain** [alvarotrigo/fullPage.js#1410]
Hi, Wonderful plugin. Need help with below situation-

1) My second section, has a animation, where the elements of the section animate with scroll (say 3-4 scrolls), and the section itself does not scroll up.
2) Hence I need to customise fullpage.js such that, the scroll is disabled for that section, so that it does not scroll for a specific scroll duration. And get it back.
3) Animate the individual elements with the scroll. (Position:fixed, with a plugin like scrolltie?)

I understand I can use normalScrollElements, to disable scroll on an element, but I just want to disable it for few scrolls, while I perform a in-section scroll based animation.

Thanks a lot!

**Comment by alvarotrigo** [comment]
Just use the method [`setAllowScrolling`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) to disable or enable it whenever you need.

The logic underneath to activate it or not depends on you as well as the animation of your elements on scroll.
That's not directly related with fullpage.js features.
