### ISSUE TITLE
Swipe left issue on mobile devices

### ISSUE THREAD

**Issue by manjunathkundar** [alvarotrigo/fullPage.js#1411]
Site is scrolling to previous section on swipe left on mobile devices. How can I disable this?

**Comment by alvarotrigo** [comment]
Provide a reproduction of the problem.

It doesn't happen [in the demo page](http://alvarotrigo.com/fullPage/). 
Take into account that if your swipe in diagonal and the Y movement is bigger than the one int he X axis, the it will scroll vertically.

You can adjust the sensitivity with the `touchSensitivity` option.

**Comment by manjunathkundar** [comment]
Thanks Alvarotrigo.. Its working fine now.
