### ISSUE TITLE
Scrolling up or down - transitions won't animate sometimes

### ISSUE THREAD

**Issue by drawcard** [alvarotrigo/fullPage.js#1412]
I've noticed a bug in Chrome for Mac, where the up/down transitions used to animate the scrolling don't fire sometimes, and the page abruptly moves up or down rather than being a fluid scroll. Also if you scroll quicker than ~1 frame per second, the layout gets confused and randomly skips around the entire slide deck. It's happening on the Fullpage.js site itself as well as my own layouts as seen in my screen recording: 

http://gfycat.com/UntimelyAnxiousLcont

It might be related to #1389 but I'm not certain. The problem doesn't occur in Firefox or Safari.

Chrome v. Version 44.0.2403.125 (64-bit), OSX 10.10.3

Edit: Problem is also occuring on PC too (just tested in a VM). Microsoft Edge is working OK.

**Comment by alvarotrigo** [comment]
Seems to be related with #1389. 
I'll close this issue.
