### ISSUE TITLE
autoScrolling: false is busted

### ISSUE THREAD

**Issue by kylerbeetun** [alvarotrigo/fullPage.js#1413]
This was working fine in earlier versions. Now when you try to scroll down in a long section, it will just scrolls up or down to next section after about a second.

This issue can be seen in the demo too. http://alvarotrigo.com/fullPage/examples/normalScroll.html#3rdPage

**Comment by alvarotrigo** [comment]
The option `fitToSection` was introduce time ago.
Read the docs for more info about its configuration.

**Comment by kylerbeetun** [comment]
thanks @alvarotrigo , that works.
