### ISSUE TITLE
Want to resize the height

### ISSUE THREAD

**Issue by usman87** [alvarotrigo/fullPage.js#1415]
Hi,

I am working on a questionaire and I like typeform questionnaire style. I want to set a custom height for each slide. How can I do it, I want to keep the sections for focus like in typeform but want the sections to be closer. I tried and tried but cant do it.

Regards

**Comment by alvarotrigo** [comment]
Not sure what you mean, but this is a full page plugin at the moment and it is suppose to work with full width and height and therefore the plugin doesn't provide any option to do anything different.

**Comment by usman87** [comment]
How can I change the full height for this plugin. I want to use the full width but I need the height to be auto regarding the content height.

**Comment by alvarotrigo** [comment]
Check out this: https://github.com/alvarotrigo/fullPage.js/issues/1044

**Comment by usman87** [comment]
Thanks. That did the trick for me :)
