### ISSUE TITLE
Slide URL still visible after redirect

### ISSUE THREAD

**Issue by joeynimu** [alvarotrigo/fullPage.js#1417]
Hi guys,

I have this website i have made fullpage.js and in one of my slides, i have a form which on submit the details are saved in a database and the user is redirected to another website. But after redirect, the last URL is added onto the redirect url.

For example if the hash url where the form sits is 
www.mydomain.com/#shesworthit/1
and the redirect url is
http://google.com
after the redirect the url becomes 
http://google.com#shesworthit/1

I am doing the redirect using php's header 
```php
 header('Location: http://www.myurlhere.com');
```

What could be the issue? many thanks for this amazing plugin.

**Comment by alvarotrigo** [comment]
Doesn't seem to be a fullpage.js related problem. 
I would suggest you to ask in other place such as stackoverflow.com
