### ISSUE TITLE
Scrolling "too fast" makes transitions seem chopped

### ISSUE THREAD

**Issue by dsagastume** [alvarotrigo/fullPage.js#1419]
I made a basic implementation, whenever I keep scrolling before a transition completely ends the problem appears:

![example](https://cloud.githubusercontent.com/assets/4360846/9072033/f341e81a-3ab5-11e5-8224-4defa8d53bff.gif)

What could be happening?

**Comment by alvarotrigo** [comment]
Duplicated of: https://github.com/alvarotrigo/fullPage.js/issues/1389
