### ISSUE TITLE
Scroll Inside Sections Threshold at the end of the section

### ISSUE THREAD

**Issue by lilyliao** [alvarotrigo/fullPage.js#1420]
So it works great with full-page sections. But if there's a section that allows free-scrolling(with slimscroll plugin), when it reaches the end of the section, it doesn't stop to go to the next section, making it look very jumpy. The demo acts like this (https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrolling.html)
How to add a threshold at the end of the free-scrolling section?

**Comment by alvarotrigo** [comment]
Duplicated of: https://github.com/alvarotrigo/fullPage.js/issues/941

No solution was found yet I'm afraid.
