### ISSUE TITLE
My video background doesn't play first

### ISSUE THREAD

**Issue by Delemo** [alvarotrigo/fullPage.js#1421]
Hello,

I'm working on a fullpagejs project composed of 3 sections.
I've activated the navigation by vertical dotnav, with tooltips and link names.
In my first section there is a video background.

All is working like a charm except for one thing:
The video of the first section doesn't play at first time (immediatly after the first load of the fullpagejs page).
When navigating to the following section and the back to the first section the video starts to play.
When I'm removing the initialization code that enabling the vertical navigation (leaving only the afterRender function), the video is playing as excepcted after the first load of my page.

It seems that my initialization code is not good.
Here is my code:
```javascript
$(document).ready(function() {
		$('#fullpage').fullpage({
	        anchors:['intro', 'sectors', 'savoirFaire'],
	        navigation: true,
	        navigationPosition: 'right',
	        navigationTooltips: ['intro', 'expertises', 'savoir-faire'],
	        showActiveTooltip: false,
			afterRender: function(){
				//playing the video
				$('video').get(0).play();
			}
		});
	});
```

**Comment by alvarotrigo** [comment]
Are you using the latest version of fullpage.js ? `2.6.7.1` ?

**Comment by Delemo** [comment]
Hi alvarotrigo,

Thank you for your reply.

In the header of my jquery.fullPage.min.js file, it is said:
/*!
 * fullPage 2.6.7
 * https://github.com/alvarotrigo/fullPage.js
 * @license MIT licensed
 *
 * Copyright (C) 2015 alvarotrigo.com - A project by Alvaro Trigo
 */

Does it means I need to update?
Is there a 'good way to' update fullPage.js?

Thanks

**Comment by alvarotrigo** [comment]
There's no much difference between the previous version and the current one, do not worry.
Just make sure you have the `autoplay`tag in your video:

```html
<video autoplay>
	<source src="imgs/flowers.mp4" type="video/mp4">
	<source src="imgs/flowers.webm" type="video/webm">
</video>
```

**Comment by alvarotrigo** [comment]
You don't even need the ` $('video').get(0).play();` anymore. Videos are played automatically once the section becomes visible if they have the `autoplay` tag.

**Comment by Delemo** [comment]
Alvarotrigo,

Hum, it still not working as you describe.
If you are ok I will publish my project and provide you a url.
Best regards

**Comment by alvarotrigo** [comment]
I can not reproduce it [here](http://jsfiddle.net/97tbk/745/).
You are probably doing something wrong.

If you believe there's a bug, please reproduce the issue in the same jsfiddle.

**Comment by Delemo** [comment]
Hi Alvarotrigo,

My test site is visibile here: http://www.staminic.com/joomla

Best regards
Simon

**Comment by alvarotrigo** [comment]
As I said:

> If you believe there's a bug, please reproduce the issue in the same jsfiddle.

That's the way to isolate the problem from your external scripts. Use jsfiddle.
