### ISSUE TITLE
Inertia (momentum) scrolling not working within .fp-scrollable

### ISSUE THREAD

**Issue by eystein** [alvarotrigo/fullPage.js#1422]
Hi,

I'm wondering why I can't get inertia scrolling working (on iPhone) when using `-webkit-overflow-scrolling: touch;` on the elements that are longer than the viewport. Is there something in the plugin stopping it?

I've got a demo here: https://dl.dropboxusercontent.com/u/384667/eltek/index.html#who/are-our-people

The direct link to the uncompiled js is https://dl.dropboxusercontent.com/u/384667/eltek/assets/js/main.js (please excuse the commented out code - I've been testing things)

Thanks!

**Comment by alvarotrigo** [comment]
The plugin fullpage.js uses for the scrollable element (slimScroll) doesn't provide inertia.

**Comment by alvarotrigo** [comment]
Related with: https://github.com/alvarotrigo/fullPage.js/issues/506

**Comment by eystein** [comment]
@alvarotrigo Thank you for the reply, and for maintaining this project. I'll try digging into slimScroll.

**Comment by alvarotrigo** [comment]
@eystein Ideally fullpage.js will change to [iScroll.js](http://cubiq.org/iscroll-5) in a future, which provides a much better functionality.
