### ISSUE TITLE
Problem with normalScrollElements

### ISSUE THREAD

**Issue by nTuply** [alvarotrigo/fullPage.js#1423]
Hi,

I am using fullPage in a website and I need to have a section with normal scrolling. From the documentation, normalScrollElements should do the job(which it does) but the problem is that after using it on a section element, I cannot scroll further down to the other sections which do not use normalScrollElements.

Here's a link to my site:
http://sabirmb.com/Parallax

You will see when you scroll, from Home, Collections to Showroom, it works fine. Showroom uses the normalScrollElements. Then when I try scrolling to Contact and About it just doesn't work. 

I would really appreciate some help regarding this.

Thanks :)

**Comment by alvarotrigo** [comment]
You shouldn't be using `normalScrollElements` for a whole section. That's not the purpose of it.

If you want normal scroll for it you should be using `scrollOverflow:true` as [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html) available in the download.

**Comment by nTuply** [comment]
Thanks. I didn't think about that. :)
