### ISSUE TITLE
Change Section / Pages orientation?

### ISSUE THREAD

**Issue by kleffmann** [alvarotrigo/fullPage.js#1424]
Is it possible to change the logic so that the pages which are actually displayed in horizontal direction to be displayed underneath/vertical? and the sections horizontal? 

If not, how can i disable the auto-scrolling for the vertical swipes/sections?

Thank you very much for your support!!

**Comment by alvarotrigo** [comment]
> Is it possible to change the logic so that the pages which are actually displayed in horizontal direction to be displayed underneath/vertical? and the sections horizontal?

No

> If not, how can i disable the auto-scrolling for the vertical swipes/sections?

http://alvarotrigo.com/fullPage/examples/normalScroll.html
