### ISSUE TITLE
Window Height and Window Width

### ISSUE THREAD

**Issue by MuTLY** [alvarotrigo/fullPage.js#1425]
Hi Alvaro,

Please consider to use `$(window)[0].innerHeight` and `$(window)[0].innerWidth` instead of jQuery's .height() and .width() methods to get the screen dimensions.

I have a case where Android Chrome is returning 640px as the window height, but it is actually 511px.

    $(window)[0].innerHeight
    511

    $(window).innerHeight()
    640

**Comment by alvarotrigo** [comment]
> I have a case where Android Chrome is returning 640px as the window height, but it is actually 511px.

Make sure you are using the the compulsory DOCTYPE declaration.

No one else has complain about Android browsers returning incorrect heights. 

Is the [demo page](http://alvarotrigo.com/fullPage/) working as expected for your?

**Comment by MuTLY** [comment]
Yeah I guess Android Chrome is being a troll... I indeed had the <!DOCTYPE html> declaration, only it was typed just like that, lowercase 'html'. When I changed it to HTML (all uppercase) it started working.

Thanks for your time!
