### ISSUE TITLE
Scroll to top of scrollable section when user enters

### ISSUE THREAD

**Issue by redonditodericota** [alvarotrigo/fullPage.js#1430]
Hello, I have found something that is a bit disturbing while using this plugin.

First of all I want to thank you for the plugin, it is really easy and usefull.

The problem is with the scrollable sections. When user leaves a scrollable section, and then goes back to it again(for example, clicking on the anchor that goes to it) the section remains scrolled as the user has left it before.
I would like the section to be full scrolled top when the user goes to it thru an anchor link. Is this possible any way?
Thank you very much, and again, congratulations for this incredible plugin.

**Comment by alvarotrigo** [comment]
You'll have to do it by yourself, the plugin doesn't provide any option for it. 

The scrollable section works as any other iframe or scrollable div in any website. It will retain its position once you leave it.

**Comment by redonditodericota** [comment]
Thank you very much for your fast answer.
I figured out how to do this, I post it here in case anyone may find it usefull, or in case you would want to somehow add it to the readme.

On the hashchange event, I retrieve the data-anchor value with location.hash.slice(1)(or location.hash.slice(1,-2) if there are slides); and then I run this line: $('div[data-anchor="'+dataAnchor+'"] .fp-scrollable').scrollTop(0);
