### ISSUE TITLE
Updating anchors array dynamically (via CMS)

### ISSUE THREAD

**Issue by richgcook** [alvarotrigo/fullPage.js#1431]
Hi folks,

I am using the anchors setup, which is nice, but I want the anchor array to be dynamic via the CMS (as new 'sections' will be added over time etc.) and thought this would work:

```
anchors: function() {
    var projects = $('.projects-list').html();
    return $.parseJSON(projects);
},
```

And I have this at the bottom of my site;

```
<script class="projects-list">
    ['southern-soul-festival','vinyl-me-please']
</script>
```

Any reason why this wouldn't work? And has anyone had any success in updating their anchor array dynamically?

Thanks very much,
R

**Comment by richgcook** [comment]
I also thought this might've been better:

````
var myAnchors = function() {
    var projects = $('.projects-list').html();
    return $.parseJSON(projects);
};
```
```
anchors: myAnchors,
```
As referenced here: https://github.com/alvarotrigo/fullPage.js/issues/1252, but still no success.

**Comment by alvarotrigo** [comment]
Since today, in version 2.6.8 you will be able to use the tag `data-anchor` in each section to define the anchors.

[Documentation was updated few hours ago](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides).

> Note that section anchors can also be defined in the same way, by using the data-anchor attribute, if no anchors array is provided.

**Comment by richgcook** [comment]
Thanks @alvarotrigo so I don't include anchor: at all now?

**Comment by alvarotrigo** [comment]
Exactly.

**Comment by richgcook** [comment]
Ah, I have to add the data-anchor in manually now, I get it. Thanks!

**Comment by alvarotrigo** [comment]
Yep.
