### ISSUE TITLE
How to make the buttons to show up vertically

### ISSUE THREAD

**Issue by grchap1** [alvarotrigo/fullPage.js#1432]
Great plugin. Please refer to your page
http://alvarotrigo.com/fullPage/#4thpage

How to show the "First  Section" "First  Section"  "Second  Section"  "Third  Section" .. buttons in the left hand side of the page vertically like
"First  Section"   
 "Second  Section"
 "Third  Section"

**Comment by alvarotrigo** [comment]
Not related with fullpage.js at all.
That's just the design used in the example. You can create whatever menu you want with CSS and HTML.
