### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by pawlikdoc** [alvarotrigo/fullPage.js#1434]
Last time i used 2.6.4 version of fullPage.js and everything was ok.

Now i see something wrong on demo page from the beginning. 
When scroll the mouse wheel fast and repeatedly in different directions, slides can move momentarily without animation sometimes.

I can take video of this...? This is obvious issue. 

Please, check this... I will use 2.6.4 instead for now.

**Comment by alvarotrigo** [comment]
You are probably talking about a [Chrome bug reported here](https://github.com/alvarotrigo/fullPage.js/issues/1389).

**Comment by pawlikdoc** [comment]
Oh, clear.
But still, why does it work quite well on this website?
http://medoff.ua/en/

**Comment by alvarotrigo** [comment]
I have no clue to be honest. It is interesting... but it is not related with the fullpage.js version.

**Comment by alvarotrigo** [comment]
Just checked it again, it still taking place in that site at some moments. 
Scrolling down and up multiple times for some period of times ends up showing the problem.
