### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by lironrichkid** [alvarotrigo/fullPage.js#1436]
Hi , first of all this is an amazing plugin so thanks. 
How do you do the amazing effect of scrolling like power point presentation?

This is the website I am using your plugin:
http://www.eurocom.richkid.co.il/en/home/a/main

I have two main questions:
1. Responsiveheight and width. I am using it but i noticed that if you change the screen back to big screen the normal scroll is still there instead of fullpage scroll. How can i fix it on resize?
2. I am using fixed header. And therefore padding top in each section. It is absolutly fine with fullpage but whenever responsive height is working on normalscroll it looks bad (for example in mobile and small screen). It looks like a huge space between pages.
There is a way instead of padsing to tell the fullpage to margin itself not the beginning of div but minus the fixed header size?

Thanks a lot,Liron

**Comment by lironrichkid** [comment]
P.s the url is without wwe

**Comment by alvarotrigo** [comment]
You need to provide isolated reproductions of your problems.

> 1. Responsiveheight and width. I am using it but i noticed that if you change the screen back to big screen the normal scroll is still there instead of fullpage scroll. How can i fix it on resize?

I can not reproduce your problem [on the demo page](http://alvarotrigo.com/fullPage/examples/responsive.html). Therefore, unless you provide a reproduction of it in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen, there's nothing else I can do for you there. 

> 2. I am using fixed header. And therefore padding top in each section. It is absolutly fine with fullpage but whenever responsive height is working on normalscroll it looks bad (for example in mobile and small screen). It looks like a huge space between pages.

Provide a reproduction in jsfiddle or codepen. No sure what's your problem.

Closed until a reproduction is provided.

**Comment by alvarotrigo** [comment]
> I am using fixed header. And therefore padding top in each section. It is absolutly fine with fullpage but whenever responsive height is working on normalscroll it looks bad (for example in mobile and small screen). It looks like a huge space between pages.

Regarding this point. You are not using the option `paddingTop`, so that's not a fullpage.js problem it seems, but rather a responsive problem of yours.
Try to deal with CSS3 media queries for it. Not something to treat in this forum anyway.

**Comment by lironrichkid** [comment]
It doesnt matter it is the same if i am using it in the fullpage function. I want the fullpage not padding top but margin minus to see the fixed header. Do you understand?? What about second problem. Btw it makes safari die

**Comment by alvarotrigo** [comment]
> Provide a reproduction in jsfiddle or codepen.
