### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by lironrichkid** [alvarotrigo/fullPage.js#1437]
Hi i do not need code pen because I wrote you the site url. Try now it is without www , first of all this is an amazing plugin so thanks.
How do you do the amazing effect of scrolling like power point presentation?

This is the website I am using your plugin:
http://eurocom.richkid.co.il/en/home/a/main

I have two main questions:
1. Responsiveheight and width. I am using it but i noticed that if you change the screen back to big screen the normal scroll is still there instead of fullpage scroll. How can i fix it on resize?
2. I am using fixed header. And therefore padding top in each section. It is absolutly fine with fullpage but whenever responsive height is working on normalscroll it looks bad (for example in mobile and small screen). It looks like a huge space between pages.
There is a way instead of padsing to tell the fullpage to margin itself not the beginning of div but minus the fixed header size?

Thanks a lot,Liron

**Comment by alvarotrigo** [comment]
When I ask for codepen or jsfiddle is because I want you to isolate the problem from your own code / scripts and CSS.
