### ISSUE TITLE
normalScrollElements not work on chrome and safari

### ISSUE THREAD

**Issue by south-pacific** [alvarotrigo/fullPage.js#1438]
there is a div with scroll in the section, and i have use normalScrollElements, but the div can not scroll when i hover, the entire page does not have any reaction

**Comment by alvarotrigo** [comment]
Reproduce the problem in jsfiddle or codepen, it is working as expected [in this demo](http://jsfiddle.net/97tbk/786/).
Closed until then.

**Comment by south-pacific** [comment]
it is a bug of chromium. 
https://code.google.com/p/chromium/issues/detail?id=417345
sorry to bother you

**Comment by alvarotrigo** [comment]
I'm afraid I can not help you unless you reproduce it in jsfiddle or codepen. 
I was not able to.
