### ISSUE TITLE
SlimScroll doesn't work on mousewheel and touch

### ISSUE THREAD

**Issue by ReFury** [alvarotrigo/fullPage.js#1440]
Hi,

I'm creating website with fullPage.js. Site is avaible here: www.jacoby.pl/mit . I have issue with SlimScroll. I don't know why, but this add-on stop working. I can't scroll pages with mousewheel or touch on Android (on BB10 everything is fine). I can scroll only with mouseclick holding scrollbar.  Can u help me to repair that issue? 

Regards,
Jacoby.

**Comment by alvarotrigo** [comment]
You are loading slimScroll after fullpage.js and not before...

```html
       <script src="js/jquery.fullPage.js"></script> <!-- Minify this in production process -->
        <script src="js/jquery.slimscroll.min.js"></script>
```

**Comment by ReFury** [comment]
Thanks for an answer but your advice doesn't work. I tried it before. :/

**Comment by alvarotrigo** [comment]
Then you would have to reproduce the issue in jsfiddle or codepen, as [the available example is working as expected](http://alvarotrigo.com/fullPage/examples/scrolling.html) and it is looking more like an error in your side than in fullpage.js.

**Comment by alvarotrigo** [comment]
In any case, you still have to make the change I told you, and you didn't in the link you provided.

**Comment by ReFury** [comment]
I changed it and now I'm still looking solution.

**Comment by alvarotrigo** [comment]
I'm afraid you didn't change it yet. I still seeing it exactly as it was....

**Comment by ReFury** [comment]
I changed in my PC. I found solution, problem is in other wheel events. I can't use it on other elements because there is 'collision' with slimscroll.
