### ISSUE TITLE
Want to move to section 1 from section 4 using onLeave call back

### ISSUE THREAD

**Issue by pradipc-cuelogic** [alvarotrigo/fullPage.js#1441]
Hello Alvaro,

Need your help, on my project I have a requirement, I want to go section 1 from section 4 using an onLeave function. is it possible? I have tried but getting recursion errors.
I am using below function-
```javascript
onLeave: function(index, nextIndex, direction){
		            if(index ==  3 && direction == 'up'){
		            	$.fn.fullpage.moveTo(1);
		            }
}
```
Please let me know, am I doing right or not.

**Comment by alvarotrigo** [comment]
Nop.

**Comment by alvarotrigo** [comment]
You are doing it right. You can check it [on this jsfiddle](http://jsfiddle.net/97tbk/789/).

**Comment by pradipc-cuelogic** [comment]
Thanks Man. 
Actually I was wrong. I was using old version of fullpage.js 2.6.7. Now its working fine using 2.6.9.

Thanks.
