### ISSUE TITLE
Bug Chrome iOS Mobile

### ISSUE THREAD

**Issue by pabloworks** [alvarotrigo/fullPage.js#1443]
weird bug in chrome mobile iOS
browser adding extra padding, in others browsers mobile like safari not happen

**Comment by pabloworks** [comment]
also slow :/
(Only chrome mobile iOS)

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it in [the demo page](http://alvarotrigo.com/fullPage/) in Chrome using iOS 5.
Please provide a reproduction of the issue.

**Comment by pabloworks** [comment]
Here weeo.com.br/demo/

**Comment by alvarotrigo** [comment]
Fullpage.js is  a full page plugin. You are not suppose to use any other element in the body unless it is fixed, and you are not doing so. Your header is not fixed.

**Comment by pabloworks** [comment]
Ok thanks

**Comment by alvarotrigo** [comment]
If you believe it is something else, please provide a clean reproduction of the problem. Basically, using [one of the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) as a base for your reproduction and without any external javascript code or CSS.

**Comment by pabloworks** [comment]
I will try to fix it, if I can I share here

**Comment by pabloworks** [comment]
my solution in css

.fp-table,
	.fp-tableCell{
		position:relative !important;
		float:left !important;
		display:block !important;
		height:auto !important;
	}
