### ISSUE TITLE
Multiple horizontal sliders/navigation in one window/section

### ISSUE THREAD

**Issue by Valentine-Mick** [alvarotrigo/fullPage.js#1444]
Hi there,
Love your work! 

I'm putting together a microsite using your plugin & wish to create 2 horizontal navigations in one section/window.

Example of what I mean:
https://jsfiddle.net/ValentineMick/a60bnfjj/

I want to use this for mobile size screens.
Are you able to provide a snippet to achieve this?

Thanks plenty,

**Comment by alvarotrigo** [comment]
Nop.

**Comment by Valentine-Mick** [comment]
Thanks for the direction @alvarotrigo

**Comment by alvarotrigo** [comment]
:) This forum is to treat fullpage.js bugs, issues or implementations of it. 
You are asking for a customization and not for a simple one. I do not have time to help everyone who comes with a different need. 

Fullpage.js doesn't provide a way to deal with your problem and it is not easy to do it.

**Comment by Valentine-Mick** [comment]
Understood & appreciated. But if it were possible to do, and I didn't ask, then I'd be foolish. 
Your plugins are great anyway - awesome stuff. 
I'll use slick or flickity for the section.

Thanks
