### ISSUE TITLE
Problem scrolling inside sections on mobile

### ISSUE THREAD

**Issue by redonditodericota** [alvarotrigo/fullPage.js#1445]
Hello.
I have some sections which are a bit large so i have set scrollOverflow: true, 
The issue is that on mobile devices when scrolling inside the section it does not have the inertia feeling, it is very slow and uncomfortable for the user to scroll inside the section. Also, when entering the scrollable section at the first touch-scroll inside it, it unwantedly scrolls a lot, and after that happens, the touchscrolling becomes slow and inertia-less.
I searched the issues hoping someone else have asked this before but I did not find. Please forgive me if this is a duplicate.
Is there any known way to solve this out?
Thank you very much for your assistance.

**Comment by alvarotrigo** [comment]
> The issue is that on mobile devices when scrolling inside the section it does not have the inertia feeling, it is very slow and uncomfortable for the user to scroll inside the section

There's an [open topic for that problem](https://github.com/alvarotrigo/fullPage.js/issues/506).

No solution for it yet. I would recommend you to really adapt your site to your device by removing content or directly by destroying fullpage.js or [overriding the size of the sections](https://github.com/alvarotrigo/fullPage.js/issues/1044#issuecomment-75812112).
