### ISSUE TITLE
After last section jumps to before last section

### ISSUE THREAD

**Issue by redonditodericota** [alvarotrigo/fullPage.js#1446]
Hello again.
First of all I want to apologyze for so many issues and tell you I am really grateful for your always fast assistance. (is there any way I can upvote your plugin or something, in return for all the work and time you are saving me?)

The thing now is, on mobile, when I am at the last section if I keep scrolling down it jumps to the previous section (the one before the last). On desktop this does not happen, the web does not have continuous vertical scrolling.

Again, thank you very very much.

**Comment by alvarotrigo** [comment]
> is there any way I can upvote your plugin or something, in return for all the work and time you are saving me?

- You can *star* the project on github. 
- You can retweet it in [the homepage](http://alvarotrigo.com/fullPage/) 
- And [you can donate](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=BEK5JQCQMED4J&lc=GB&item_name=fullPage%2ejs&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted). 


> On desktop this does not happen, the web does not have continuous vertical scrolling.

It works on mobiles as well, you just have to enter in [the available demo](http://alvarotrigo.com/fullPage/examples/continuous.html) from your phone to check it.

**Comment by redonditodericota** [comment]
No, I do not want the continuous scroll. The issue is that when I am at the last section(on mobile), if I keep scrolling down nothing should happen, instead it scrolls back to the 1-before-last section.

**Comment by alvarotrigo** [comment]
I'm afraid I can not reproduce it in any of the fullpage.js demos.

**Comment by redonditodericota** [comment]
I opened a question in stackoverflow, if you want to you can check it, it is a bit more complete than this issue. 
 http://stackoverflow.com/questions/32017240/google-maps-in-fullpage-plugin-bug

Best wishes!

**Comment by redonditodericota** [comment]
There is a clear issue with your plugin when using google maps on any section of it, on mobile devices when the user touches the map it scrolls back to the previous section which is really annoying.

I found a work around by adding a transparent div overlay over the map only on mobile device, this fixes the section jumping problem but makes the map unusable, what is not the idea of adding a map to the website.

It would be really nice if you can provide a better workaround for this.

Except for this, your plugin is great

Cheers

**Comment by alvarotrigo** [comment]
> There is a clear issue with your plugin when using google maps on any section of it, on mobile devices when the user touches the map it scrolls back to the previous section which is really annoying.

It is just the way it is. You won't be able to use maps unless you use `normalScrollElements` for it. But then, you won't be able to scroll to any other section if you are using it in fullscreen and using `autoScroll:true`. 

If you are in fact using `normalScrollElements` [there's another bug regarding it which is has been opened for a while](https://github.com/alvarotrigo/fullPage.js/issues/1281).

No solution was found I'm afraid.

**Comment by redonditodericota** [comment]
I can't figure out why adding `normalScrollElements` to the map container does not make any difference at all.
The map is not full height, so that the user may still be able to scroll the page when standing on the map containing section.

Is there any way to disable the plugin scolling when touching on the map? If I did not missunderstood, `normalScrollElements` should do this, but it does not. It is worth to say in desktop browsers when the mouse is over the map, the plugin scrolling does get disabled, but in mobile it does not.

Again, thank you very much for your help. When I get my payment I promise I will make a little donation to encourage your work and dedication, which I admire.

Regards

**Comment by alvarotrigo** [comment]
It might be related with the bug I mentioned. 
Try using `normalScrollElementTouchThreshold`. Otherwise, probably you are experience the same bug as the one specified in the previous link.

**Comment by redonditodericota** [comment]
Also, I did not understand what `normalScrollElementTouchThreshold` option do. Mind explaining a little bit what does it do, and when and how it should be used? Maybe this option could help with my issue.
Again, thank you very much.

**Comment by kgrube1** [comment]
Not a fix, but if you don't need to interact with it you can add a div over top of it with a transparent background.This seems to work fine.  Really wish there was a solution for this though.

**Comment by slavajacobson** [comment]
Hey, any luck?
