### ISSUE TITLE
Video Background problem

### ISSUE THREAD

**Issue by MannayDesign** [alvarotrigo/fullPage.js#1447]
Hi,
I have trouble using the video part. I am currently developping a website with fullpage 1.5.3.

You can see the problem on http://brakamusic.com/
The video won't start on the first section until you go down, then go up again. If anyone could help me, that would be wonderful.

Here's the html section : 

<div class="section active" id="section0">

        <video autoplay loop muted id="myVideo">
            <source src="img/movideo.mp4" type="video/mp4">
        </video>

        <div class="layertop">
            (..........)
        </div></div>

And here is my main.js : 

        $(window).load(function() {
	$('#loader').css( 'opacity', '0' );
	$('#loader').delay(1000).queue(function() {
			$('#loader').addClass('hidden');
			$(this).dequeue();
		});
		
	$('img.vector').each(function(){
			var $img = jQuery(this);
			var imgID = $img.attr('id');
			var imgClass = $img.attr('class');
			var imgURL = $img.attr('src');
			
			jQuery.get(imgURL, function(data) {
				// Get the SVG tag, ignore the rest
				var $svg = jQuery(data).find('svg');
			
				// Add replaced image's ID to the new SVG
				if(typeof imgID !== 'undefined') {
					$svg = $svg.attr('id', imgID);
				}
				// Add replaced image's classes to the new SVG
				if(typeof imgClass !== 'undefined') {
					$svg = $svg.attr('class', imgClass+' replaced-svg');
				}
			
				// Remove any invalid XML tags as per http://validator.w3.org
				$svg = $svg.removeAttr('xmlns:a');
			
				// Replace image with new SVG
				$img.replaceWith($svg);
			
			}, 'xml');
		
		});
     });

       $(document).ready(function() {
	var menu = $('.menu-inner');
	var trigger = $('.menu-trigger a');
	var container = $('.menu-wrapper');
	var styles = {
		opacity : "1",
		marginTop: "-30px"
	};
		
	$('#fullpage').fullpage({
		
		anchors: ['accueil', 'caveprod', 'brakaradio', 'brakavideo', 'brakashop', 'brakafrika'],

		afterLoad: function(anchorLink, index){

		if(anchorLink == 'accueil'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
		}
		if(anchorLink == 'caveprod'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
		}
		if(anchorLink == 'brakaradio'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
		}
		if(anchorLink == 'brakavideo'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
			$('.section-content').css( styles );
		}
		if(anchorLink == 'brakashop'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
			$('.section-content4').css( styles );
		}
		if(anchorLink == 'brakafrika'){
			menu.css( 'background-color', '#dbd1a1' );
			$('.vector path').css( 'fill', '#fff' );
			$('.menu li a').css( 'color', '#fff' );
			$('.menu-dark li a').css( 'color', '#fff' );
			$('.menu').css( 'border-top-color', '#fff' );
			$('.section-content4').css( styles );
		}

		//playing the video
			$('video').get(0).play();

		}
	});
	
	menu.css('left', -menu.outerWidth());
	
	trigger.click(function(e) {
		e.preventDefault();
    	e.stopPropagation();
		$('.menu-wrapper').toggleClass('on-top');
		trigger.removeAttr('href');
		menu.animate({
		  left: parseInt(menu.css('left'),10) == 0 ?
			-menu.outerWidth() :
			0
		}
		);
	});
	
	// Hide navigation and remove z-index so that arrows become visible
	$(document).mouseup(function (e) {
			if (!container.is(e.target)
				&& container.has(e.target).length === 0) 
			{
				container.removeClass('on-top');
				menu.css('left', -menu.outerWidth());
			}
		});
	
         });

**Comment by alvarotrigo** [comment]
>  I am currently developping a website with fullpage 1.5.3.

I'm afraid I only provide support for the latest version of fullpage.js (2.6.9 at the moment)
