### ISSUE TITLE
scrollOverflow won't work

### ISSUE THREAD

**Issue by sabirMB** [alvarotrigo/fullPage.js#1448]
Hi,

I asked a question before and I was told to use scrollOverflow and it doesn't work. I'm trying to have a scrollable section of content on my site but it's just being skipped, that is on scrolling it simply scrolls to the next section even though I'm having more content on that section. I have scrollOverflow: true, but the problem still persists. 

Any idea on this?

**Comment by sabirMB** [comment]
Problem fixed.

**Comment by luchorengo** [comment]
Would you please let me know the fix for this issue? I'm trying to do the same but the section is being skiped despite long height content.
