### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by Jerryskate** [alvarotrigo/fullPage.js#1449]
Hi Alvaro! 

I wonder if its possible to have Horizontal scroll? You scroll down like regular, but it moves to the side? I started off with the jQuery one page plugin that could do this- but it didnt work with anchors. I tried yours, and it warks way better! Easy to setup too. 

The only thing Im missing is the horizontal mode - I know some would consider it bad practise, but I need it for the site Im working on regardless. 

Again, great plugin. 

Regards,
Jerry

**Comment by alvarotrigo** [comment]
Duplicate question of: https://github.com/alvarotrigo/fullPage.js/issues/1134
