### ISSUE TITLE
Modal killing wheel scrolling under responsive value

### ISSUE THREAD

**Issue by olimax** [alvarotrigo/fullPage.js#1452]
If the window width is less than the responsiveWidth value and a modal window is opened, when closed the wheel scrolling is dead
The keyboard arrow scrolling still works
I have tried calling $.fn.fullpage.reBuild(); from the onClose callback of the modal but that made no difference
However if the browser is resized beyond the responsiveWidth value then made smaller again the scrolling works
It does not seem to be browser specific
Is this a bug?

**Comment by alvarotrigo** [comment]
> Is this a bug?

Probably your mistake until proven the opposite. 

Reproduce your error in jsfiddle or codepen to isolate it and proceed to further investigation.
The topic will be closed until then.
