### ISSUE TITLE
Horizontal section scroll

### ISSUE THREAD

**Issue by cinghaman** [alvarotrigo/fullPage.js#1453]
Hi I read all other posts and everyone is making a very complex function, i just need a simple way to have sections scroll left to right instead of top to bottom, most of the function/methods being explained r too overwheliming, is there i a simple way to achieve it. 
I just have 
<div class="section" data-anchor="#">content</div> 
<div class="section" data-anchor="#">content</div> 
With slideNavigation

**Comment by alvarotrigo** [comment]
If you mean scroll with the mouse wheel, the plugin doesn't provide any way for it. 
There's [an open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/316).

If you really need it, [contact me](http://alvarotrigo.com/#contact-page) for a customization and I'll provide you with a quote.

**Comment by cinghaman** [comment]
no its not mouse scroll, just simple scroll, by clicking navigation dots 
just instead of sections going down/up thy need to go left / right

**Comment by alvarotrigo** [comment]
The plugin provides horizontal navigations dots for it as you can see [in this example](http://alvarotrigo.com/fullPage/examples/navigationH.html) in the 2nd section.

Just create a single section with multiple horizontal slides.

**Comment by cinghaman** [comment]
i have a header menu (navigation -as its not a slide but a full website) (which get active class as the section moves to next section) 
if i convert this into slides and 1 section the menu doesnt work as now the slide will have url as #sectionurl#slidenumber

**Comment by alvarotrigo** [comment]
You'll have to deal with the callback `afterSlideLoad` for that or even just with CSS with the class added to the `body`in the form of `fp-viewing-SECTION-SLIDE`

**Comment by cinghaman** [comment]
just checked ur pagepilling, and its example in horizontal scroll is what i wanted, with sections scrolling horizontally, and working with the top menu..
I think u should add this feature to fullpage.js too :)

**Comment by alvarotrigo** [comment]
> I think u should add this feature to fullpage.js too :)

I'm afraid It won't be done in a short term.

**Comment by alvarotrigo** [comment]
This is now possible using the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).

**Comment by jeroentiem** [comment]
Hi, how to use the "Scroll Horizontally extension" in Wordpress with Elementor?

**Comment by alvarotrigo** [comment]
@jeroentiem first you have to purchase both [the plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html) (or the bundle with all of them)
Then follow the [instructions in the Elementor docs](https://www.meceware.com/docs/fullpage-for-elementor/#extensions)
