### ISSUE TITLE
Scroll not work in Firefox and IE when mouse over SVG <object>

### ISSUE THREAD

**Issue by imaximym** [alvarotrigo/fullPage.js#1455]
To reproduce issue - open Firefox (up to last version) or IE (up to Edge) and go to link
https://jsfiddle.net/imaximym/suaguLzp/7/
Mouse over svg image (<object>) and try to scroll.

**Comment by alvarotrigo** [comment]
I don't know if you've noticed it, but the SVG doesn't get displayed in Chrome at all.

**Comment by molchansky** [comment]
Не знаю, какой добрый человек добавил мой адрес в рассылку, но отпишите
меня пожалуйста!

_________________________
Best regards, Anna Timoshenko
LiveTex | PR manager
Тел. +7(812) 449-49-20, доб. 751
Моб.+7(921) 945-46-17
E-mail: anna.t@livetex.ru
livetex.ru
*LinkedIn <https://www.linkedin.com/in/annatimoshenko>*

2015-08-20 18:32 GMT+03:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
From [this answer](http://stackoverflow.com/a/32123678/1081396) at stackoverflow:

> You need to make the SVG content pointer-events: none i.e.
```css
#svg_object {

    background:yellow;
    pointer-events: none;
}
```
> otherwise the SVG document gets all the pointer events rather than the html container.
