### ISSUE TITLE
normalScrollElements mobile touch

### ISSUE THREAD

**Issue by matthiaskp** [alvarotrigo/fullPage.js#1456]
Hey

First of all: thanks for the amazing plugin - we've used it on many projects and it works great. 

There is one issue about the normalScrollElements. On: http://www.matthiaskappeler.ch the about container is overlaying the fullpage containers. If I scroll with the mouse wheel it works fine but as soon as I try to scroll on a mobile device the fullpage scrolls in the background. It can also be tested on "mobile mode" of chrome developer tools - same issue there... 

Is there a possibility to temporarily disable the scroll events?

Thanks in advance!

**Comment by alvarotrigo** [comment]
You will have to be more specific about the steps to reproduce it. I didn't get it.

**Comment by alvarotrigo** [comment]
> Is there a possibility to temporarily disable the scroll events?

Of course. Just use `setAllowScrolling` as detailed in the docs.
