### ISSUE TITLE
Also scroll down on Slides inside Sections

### ISSUE THREAD

**Issue by joDelicious** [alvarotrigo/fullPage.js#1457]
Hello dear, 

Thanx for your work.
I have looked, and haven't found an answer yet ...

Simple question : 
Say I have this structure :

```html
<div class="section" id="section1"></div>`
<div class="section" id="section2">
     <div class="slide"><div>
     <div class="slide"><div>
     <div class="slide"><div>
</div>
<div class="section" id="section3"></div>
```

I would like this to happen :
From Section1, when i scroll down, go to Section2
From Section2/Slide1, when i scroll down, go to Section2/Slide2
From Section2/Slide2, when i scroll down, go to Section2/Slide3
From Section2/Slide3, when i scroll down, go to Section3

Any tip :) ?

Thank you !

Best regards from Belgium, 
Johan

**Comment by alvarotrigo** [comment]
> Any tip :) ?

The plugin doesn't provide any way to do it. You'll have to do it yourself.
You would have to attach and event to the mouse wheel scrolling when you reach a section with slides.
Then you would have to disable the plugin scrolling with `setAllowScrolling` and then you'll have to call `moveSlideRight`or `moveSlideLeft` depending on the direction of the scrolling.

**Comment by alvarotrigo** [comment]
If you really  need it and don't manage to make it work, [contact me](http://alvarotrigo.com/#contact-page) and I'll provide you with a quote.

**Comment by alvarotrigo** [comment]
Related with [this open topic](https://github.com/alvarotrigo/fullPage.js/issues/316)

**Comment by joDelicious** [comment]
Ok thank you, I'll get back to you if needed.
