### ISSUE TITLE
Background images get larger the more slides I add to the slider with horizontal nagination 

### ISSUE THREAD

**Issue by goeagile** [alvarotrigo/fullPage.js#1458]
I have a strange behavior going on. I'm using the newest version of fullPage.js (ie. 2.6.9)
I have 4 sections defined. When the 3nd section has only two slides with images as background it works fine, meaning the images extend to the max visible resolution of the browser. However the more slides I add to the 3nd section the more all the background slides seem to grow beyond the max resolution of the browser. It got to a point where if I add 9 slides all 9 background images are twice the original size of the browser window. This happens both in Chrome and Firefox.

I didn't modify any of the js or css styles except what comes in the backgrounds.html example.
Here's my code:

CSS:
	/* Style for our header texts
	* --------------------------------------- */
	h1{
		font-size: 5em;
		font-family: arial,helvetica;
		color: #fff;
		margin:0;
		padding:0;
	}

	/* Centered texts in each section
	* --------------------------------------- */
	.section{
		text-align:center;
	}

	/* Backgrounds will cover all the section
	* --------------------------------------- */
	.section{
		background-size: cover;
	}
	.slide{
		background-size: cover;
	}

	/* Defining each section background and styles
	* --------------------------------------- */
	#section0{
		background-image: url(images/home.jpg);
		padding: 30% 0 0 0;
	}
	#section1{
		background-image: url(images/about.jpg);
		padding: 6% 0 0 0;
	}
	#section3{
		background-image: url(images/shop.jpg);
		padding: 6% 0 0 0;
	}

 	/*Adding background for the slides
	* --------------------------------------- */
	#slide1{
		background-image: url(images/prod_1.jpg);
		padding: 6% 0 0 0;
	}
	#slide2{
		background-image: url(images/prod_2.jpg);
		padding: 6% 0 0 0;
	}		
	#slide3{
		background-image: url(images/prod_3.jpg);
		padding: 6% 0 0 0;
	}	
	#slide4{
		background-image: url(images/prod_4.jpg);
		padding: 6% 0 0 0;
	}	
	#slide5{
		background-image: url(images/prod_5.jpg);
		padding: 6% 0 0 0;
	}			
	#slide6{
		background-image: url(images/prod_6.jpg);
		padding: 6% 0 0 0;
	}	
	#slide7{
		background-image: url(images/prod_7.jpg);
		padding: 6% 0 0 0;
	}	
	#slide8{
		background-image: url(images/prod_8.jpg);
		padding: 6% 0 0 0;
	}	
	#slide9{
		background-image: url(images/prod_9.jpg);
		padding: 6% 0 0 0;
	}	

	/* Bottom menu
	* --------------------------------------- */
	#infoMenu li a {
		color: #fff;
	}

JavaScript:
	<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage({
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage'],
				menu: '#menu',
				verticalCentered: false,
				slidesNavigation: true
			});
		});
	</script>

HTML:
<ul id="menu">
	<li data-menuanchor="firstPage"><a href="#firstPage">Home</a></li>
	<li data-menuanchor="secondPage"><a href="#secondPage">About</a></li>
	<li data-menuanchor="3rdPage"><a href="#3rdPage">Portfolio</a></li>
	<li data-menuanchor="4thpage"><a href="#4thpage">Shop</a></li>
</ul>

<div id="fullpage">
	<div class="section" id="section0"><h1></h1></div>
	<div class="section" id="section1"></div>
	<div class="section" id="section2">
	        <div class="slide" id="slide1"><h1></h1></div>
		<div class="slide" id="slide2"><h1></h1></div>
		<div class="slide" id="slide3"><h1></h1></div>
		<div class="slide" id="slide4"><h1></h1></div>
		<div class="slide" id="slide5"><h1></h1></div>
		<div class="slide" id="slide6"><h1></h1></div>
		<div class="slide" id="slide7"><h1></h1></div>
		<div class="slide" id="slide8"><h1></h1></div>
		<div class="slide" id="slide9"><h1></h1></div>
	</div>
	<div class="section" id="section3"></div>	
</div>

**Comment by alvarotrigo** [comment]
Not a fullpage.js problem but a CSS one. 
Not for this forum I'm afraid.

**Comment by claudiasilva** [comment]
Hi, I have the same problem and i didn't change nothing of your css or js.I just add one more slide to your example.
