### ISSUE TITLE
Anchor links not working in IE

### ISSUE THREAD

**Issue by nithishj** [alvarotrigo/fullPage.js#1459]
Hi there,
    The plugin works normal on chrome,safari,firefox but not working properly on IE
on IE 8 - on anchor click or on scroll, skips a section.
on IE 11 - along with 'skip a section' issue stated above, getting a blank section at the end.

our website is http://flyinstyle.co/

Dont know if the issue is with plugin or my code.

**Comment by alvarotrigo** [comment]
From the docs:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

It seems IE is case insensitive.
