### ISSUE TITLE
Slimscroll css settings

### ISSUE THREAD

**Issue by Strutsagget** [alvarotrigo/fullPage.js#1461]
Hi how do i add slimscroll default design settings? Like left side and not right and wish and height and so on :)

$(selector).slimScroll({
    width: '300px',
    height: '500px',
    size: '10px',
    position: 'left',
    color: '#ffcc00',
    alwaysVisible: true,
    distance: '20px',
    start: $('#child_image_element'),
    railVisible: true,
    railColor: '#222',
    railOpacity: 0.3,
    wheelStep: 10,
    allowPageScroll: false,
    disableFadeOut: false
});

**Comment by alvarotrigo** [comment]
You can't.

**Comment by Strutsagget** [comment]
ok thx for info. Feature Request! :) 
Btw fullPage.js looks awesome. Great Work!
