### ISSUE TITLE
normal scroll not working

### ISSUE THREAD

**Issue by lironrichkid** [alvarotrigo/fullPage.js#1462]
Hi,
I have the holdings section in my website:
http://eurocom.richkid.co.il/en/home/a/main/#holdingsPage
 and when click on part of the map a lightbox is opened and i dont want to enable scroll in that phase.
so i put         
normalScrollElements:'#myModal',(light box id)
normalScrollElementTouchThreshold:0,
i have some questions:
1. when try to open the lightbox(by clicking on some map area) and then fast scroll to next section after you clicked (especially in longer then screen lightboxes) , you can scroll, while when clicking on some map area and waiting a second after the lightbox is shown you cant scroll as I wish.
2. what is normalScrollElementTouchThreshold?

how to solve it?
thanks.

**Comment by alvarotrigo** [comment]
> 1. when try to open the lightbox(by clicking on some map area) and then fast scroll to next section after you clicked (especially in longer then screen lightboxes) , you can scroll, while when clicking on some map area and waiting a second after the lightbox is shown you cant scroll as I wish.

Totally normal. Make use of the function `setAllowScrolling(false)` for those cases in which you don't want to wait for the element to appear to prevent the scroll.

> 2. what is normalScrollElementTouchThreshold?

You can see it in the docs: 5
