### ISSUE TITLE
Add config support for slimScroll

### ISSUE THREAD

**Issue by s-pmpodolski** [alvarotrigo/fullPage.js#1463]
Hello, your plugin is pretty awesome! But it would be even more awesome if there would be an option for setting up slimScroll, especially allowing to hide slimScroll scrollbar (alwaysVisible: false)

Thank you anyway for a great piece of code!

**Comment by alvarotrigo** [comment]
Actually I'm more include for the idea of removing slimScroll and opting in a near future for something like iScroll.js, which was not yet adopted as it drops compatibility for IE < 10

**Comment by alvarotrigo** [comment]
In any case, you can take a look at this [pull request](https://github.com/alvarotrigo/fullPage.js/pull/612) regarding your issue.
