### ISSUE TITLE
fp-auto-height ignored when first section

### ISSUE THREAD

**Issue by mladenjanjetovic** [alvarotrigo/fullPage.js#1464]
Hi,
Great lib!

I have four full screen galleries preceding by a single placeholder for a header. That placeholder has class .fp-auto-height and one DIV with height set to 200px. What I need is that on the first mouse scroll, I get the first gallery (second section) fill the screen. And it works great when scroll direction is down. But when scroll direction is up, I get stuck with second section even if I get alert that section 2 is leaving and the next index is 1. The first section is not showing on the screen

```
	$('#fullpage').fullpage({
        onLeave: function(index, nextIndex, direction){
            if(index == 2 && direction =='up'){
                alert(nextIndex);
            }
        }
    });
```

Thanks

**Comment by alvarotrigo** [comment]
> fp-auto-height ignored when first section

From the docs: 

> If there is more than one section in the initial load of the site, the plugin won't scroll at all to see the next one as it will be already in the viewport.

**Comment by alvarotrigo** [comment]
This means at least the first section of your site will have to be FULL PAGE.

**Comment by mladenjanjetovic** [comment]
Ok, thanks.

In case someone needs it, I wrote some workaround that did the trick for me:

```	$('#fullpage').fullpage({
        onLeave: function(index, nextIndex, direction){
            if(index == 2 && direction =='up'){
                $('.fullpage-wrapper').css('transform', 'translate3d(0px, 0px, 0px)');
            }
        }
    });
```

**Comment by wcalebgray** [comment]
If you need to have a menu (like the demo page has to switch between pages) with this situation, this modification of the above workaround works for me

```
onLeave: function(index, nextIndex, direction){
      if(index !== 1 && nextIndex == 1 && direction =='up'){
        $('.fullpage-wrapper').css('transform', 'translate3d(0px, 0px, 0px)');
      }
    },
```

**Comment by AlexGach** [comment]
Thanks! really useful workaround :)

**Comment by MladenJanjetovic** [comment]
It will be useful to implement something similar as a feature, to support menu and/or cover photo

**Comment by AlexGach** [comment]
Take a look to this:
https://github.com/alvarotrigo/fullPage.js/issues/1688

**Comment by brianecook** [comment]
@alvarotrigo This can now be implemented with the Offset Sections extension right?

**Comment by alvarotrigo** [comment]
@brianecook you don't need that.  Now  you can use `fp-auto-height` for that as seen in this example:
http://jsfiddle.net/97tbk/1733/

The Offset Sections extension is ideal to deal with viewport percentages as well as to use sections vertically centered in the viewport.

**Comment by brianecook88** [comment]
Thanks for savin me $28 @alvarotrigo!!!
