### ISSUE TITLE
Question: Is there a way to hide non-active slides or slide divs?

### ISSUE THREAD

**Issue by Jimmy-Codes** [alvarotrigo/fullPage.js#1466]
Hi there,

I placed a few absolutely positioned elements in different sections on my page which, when viewing the website at a "normal" height, work well and display correctly. The intent is to maintain their position on the page no matter the viewport height, but only to display when a particular slide is showing. However, when I shrink the height of the viewport to <~600px, the absolutely positioned elements begin to show on the page and overlap with each other.

I am using Bootstrap 3 and am positioning elements with the following:

````   
.screen-match {color:#ffffff;position: absolute;bottom:20px;right:20px;}
````
Is there some way to hide other slides and elements inside of fullpage.js while one is showing? Can you suggest another method for spacing them out?

Any help or insight is greatly appreciated.

**Comment by alvarotrigo** [comment]
This is not a fullPage.js problem. It seems like a problem with your design and your CSS.

Try using `overflow:hidden;` for the sections. 
If that doesn't solve your problem I would recommend you to ask in other place such as stackoverflow.com

**Comment by Jimmy-Codes** [comment]
Thank you!
