### ISSUE TITLE
BootStrap 3 ScrollSpy and Anchors/Data-Anchors

### ISSUE THREAD

**Issue by Jimmy-Codes** [alvarotrigo/fullPage.js#1468]
Hi there,

I am attempting combine a Bootstrap Navbar, with ScrollSpy enabled, with FullPage.js to navigate through anchored slides in a page. But I think that because of a previously discussed and document limitation/issue with naming the section IDs the same as the data-anchors, I am getting both scrollspy issues and issues with the last section of the page. Specifically, scroll spy is not working and the last section causes "errors" and navigates/animated incorrectly (shakes sporadically), and the slide after the first is skipped.

Is there an example available that integrates a Bootstrap Navbar that updates the "active" highlight with scrollspy working with FullPage.js? Specifically, one where the actively highlighted section in the Bootstrap Navbar updates as the user scrolls the page and the links in the navbar are able to link to slides in the page?

If not, might you have any insight onto getting these functions to play nice with one another?

Thank you!

**Comment by alvarotrigo** [comment]
> Is there an example available that integrates a Bootstrap Navbar that updates the "active" highlight with scrollspy working with FullPage.js?

Nop. 

> Specifically, one where the actively highlighted section in the Bootstrap Navbar updates as the user scrolls the page and the links in the navbar are able to link to slides in the page?

The previous question was already very a specific one. The answer here will be "no" again. 

> If not, might you have any insight onto getting these functions to play nice with one another?

Nop. But you wouldn't need to use scrollspy.... [fullpage.js already does it for you](http://alvarotrigo.com/fullPage/examples/normalScroll.html)... 
Do not try to solve a problem you have in your markup, such as using the same value for anchor links and id elements, by using other plugins. 
Fullpage.js won't work.

**Comment by Jimmy-Codes** [comment]
That's very clear, thank you!

Am I relegated to the navbar style provided by fullpage.js or may I use the navbar from Bootstrap and then use fullpage.js's functionality? I'd love to continue using my current bootstrap styles and have them follow the rules of fullpage.js?

**Comment by alvarotrigo** [comment]
> I'd love to continue using my current bootstrap styles and have them follow the rules of fullpage.js?

You can code your own events on them to go to one or another slide. Check at how fullpage.js does it internally:
https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1629

**Comment by Jimmy-Codes** [comment]
I was able to achieve the desired results by making my <ul> for bootstrap follow your very detailed rules on the main documentation. 

To supplement the code, I currently have the following JS to activate the "active" class on the <li> that someone clicks on:

````   $(".nav a").on("click", function(){
        $(".nav").find(".active").removeClass("active");
        $(this).parent().addClass("active");
        $('.active').closest('li.dropdown').addClass('active');
     });

````

**Comment by Jimmy-Codes** [comment]
Is there a way for your code to provide menu dropdowns? (Nested menu items) in your navbar?

Akin to:

```html

<ul id="myMenu">
    <li data-menuanchor="firstPage" class="active"><a href="#firstPage">First section</a></li>
    <li data-menuanchor="secondPage"><a href="#secondPage">Second section</a></li>
    <li data-menuanchor="thirdPage"><a href="#thirdPage">Third section</a></li>
     <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li data-menuanchor="fourthPage"><a href="#fourthPage">Action</a></li>
            <li data-menuanchor="fifthPage><a href="#fifthPage">Another action</a></li>
       </ul>
</ul> 
```

Or even:

``` html

<ul id="myMenu">
    <li data-menuanchor="firstPage" class="active"><a href="#firstPage">First section</a></li>
    <li data-menuanchor="secondPage"><a href="#secondPage">Second section</a></li>
    <li data-menuanchor="thirdPage"><a href="#thirdPage">Third section</a></li>
     <li data-menuanchor="fourthPage, fifthPage" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#fourthPage">Action</a></li>
            <li><a href="#fifthPage">Another action</a></li>
       </ul>
</ul>

```
Where `<li class="dropdown">` always retains `class="active"` while one its `<li>` children is the current active slide? 
 
I guess the more general question is: Can a single `<li>` tag be selected and active for multiple dropdown-toggles?

**Comment by 24Degrees** [comment]
@Jimmy-Codes: hi, did you tried this for Bootstrap 4 Alpha 6 already? Somehow, my navbar stopped indicating the active class and when clicked, it jumps to the page without the scroll effect.

I already tried to implement your JS code (replacing nav with navbar) but to no avail :-(

Thanks.

**Comment by MissPicky** [comment]
Hi alvarotrigo, could you please explain a bit more in detail how to use the scrollspy function that is already integrated in fullPage js? I tried to follow all the instructions and googled like crazy, but I can't figure out why it is not working on my site.

**Comment by alvarotrigo** [comment]
> could you please explain a bit more in detail how to use the scrollspy function that is already integrated in fullPage js?

That's using the `menu` option. Check the docs for more information about it. 
Examples available in the examples folder.

If there's anything that's not clear to you let me know.

**Comment by MissPicky** [comment]
Thank you :) That was the piece, I was missing.
