### ISSUE TITLE
fewer SectionsColor than sections

### ISSUE THREAD

**Issue by dwblmo** [alvarotrigo/fullPage.js#1470]
Is it possible to define fewer colors in sectionsColor[] and being at index+1 having the first color again?

I'd like to have something like 5 sections, but with the following definition of fullpage.js

`$('#fullpage').fullpage({
	sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE']
});`

I'd like to have the color 1bbc9b again on the fourth section.

**Comment by alvarotrigo** [comment]
> Is it possible to define fewer colors in sectionsColor[] and being at index+1 having the first color again?

Nop. The plugin doesn't provide a way to do it. 

I would recommend you to use CSS classes for it in any case.
