### ISSUE TITLE
Hover effects on Chrome - Chome bug affecting fullpage.js

### ISSUE THREAD

**Issue by juandanceswild** [alvarotrigo/fullPage.js#1471]
Hi, thanks for this awesome plugin. 

I'm building a site with fullpage and there seems to be a bug in Chrome. When I change sections, the hover events on the active sections don't start firing up until I click on the window of the active section.

This problem is not happening in Firefox nor Safari. 

Is this something that has been reported before?

**Comment by alvarotrigo** [comment]
I would need you to reproduce the issue in [this jsfiddle](http://jsfiddle.net/97tbk/418/) for further examination and to make sure is not something else what's causing it.

**Comment by juandanceswild** [comment]
Sure thing. 

Here you go. 

https://jsfiddle.net/kcocn3sm/

Thank you!

**Comment by alvarotrigo** [comment]
I believe [this is a much better reproduction of it](http://jsfiddle.net/97tbk/804/).
Seems like a Chrome bug rather than a fullPage.js. 
You can reproduce it without fullpage.js as you can see [here](http://jsfiddle.net/f5pfoo83/7/).

I'll report it to Chrome, although I believe it is related with [this other problem](https://code.google.com/p/chromium/issues/detail?id=513206) which was also reported by me.

**Comment by alvarotrigo** [comment]
I've just [opened a ticked at Chrome issues](https://code.google.com/p/chromium/issues/detail?id=525213&thanks=525213&ts=1440623441)

**Comment by paulrevival** [comment]
This is my answer to Google's ticket posted by **alvarotrigo**.

I have the same problem with full-screen sliding blocks. After slide (transform) I can't hover anything until I click anywhere. But when I'm trying to hover smth, it looks like visible objects (all things that you see on display) are in their places correctly, but clickable and hoverable objects are not on their places.
Example: I have some text in some div. After sliding (transform) and while trying to hover this text the text-edit cursor appears near the text I'm trying to hover.

_**My temporary solution is some little action with browser or DOM: append some element to body on sliding ends or trigger some event like $('body').trigger('resize').**_

In this plugin i'm triggering `resize` event on `body` in `afterLoad` callback.

Here's some video https://drive.google.com/file/d/0B-Etwkh-k8aSVDE3VTM0a1c2ek0/view?usp=sharing

**Comment by alvarotrigo** [comment]
This isssue was solved in Chrome [time ago](https://code.google.com/p/chromium/issues/detail?id=525213&can=1&q=hover%20fullpage&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by mhoffmann98** [comment]
@alvarotrigo I still seem to have the issue described above. As soon as I scroll, either by clicking an anchor link or by using the scroll wheel, the anchor links become unclick-able until I reload the page.

**Comment by alvarotrigo** [comment]
That's not exactly the same problem.
If you believe its a problem reproduce it in jsfiddle or codepen for further investigation.

**Comment by mhoffmann98** [comment]
Thank you. 
Here is a fiddle: https://jsfiddle.net/byqcLhf2/2/

I'm still trying to figure out how to use jsfiddle, but maybe you can already see what is wrong with my code. The links also become clickable when you scroll all the way back to the top.
