### ISSUE TITLE
disable scrollbehaviour when in dropdown list

### ISSUE THREAD

**Issue by JanaKemmer** [alvarotrigo/fullPage.js#1473]
Hey everyone, 
an a site where I have used fullPage.js I added a select box with multiple options. Now when I try to select something and scroll out of habbit it naturally scrolls the whole site, and not my list of options. 

I tried multiple things so far, including this as the most promising approach, but it also didnt work as I wanted it to:

if ((fullpage) && ($("#p_store_id").focus(function(){
        isFocused = true;
        $.fn.fullpage.setAllowScrolling(false);
    }).blur(function(){
        isFocused = false;
        $.fn.fullpage.setAllowScrolling(true);
    })));

Is it even possible with this script?
Thank you in advance :)

**Comment by CricriSDN** [comment]
Hello,
Have you try to add your *#p_store_id* to the *normalScrollElements* Fullpage param ?

**Comment by alvarotrigo** [comment]
Check [this answer](http://stackoverflow.com/questions/30185586/fullpage-js-scrolling-on-top-of-select-element-in-ie-and-firefox)

**Comment by JanaKemmer** [comment]
Hey, your answer kinda worked. At least I now know where the real problem lies. 
                    $.fn.fullpage.setAllowScrolling(false);
does work as expected and my check to see if the drop-down list is selected also works
The thing that keeps it from working is that our site uses 
                    ScrollOverflow: true
and I can't seem to overwrite it, that when the drop-down is selected scrollOverflow gets changed to false. I tried changing it to false in my if-clause but nothing seems to happen. If you want I can provide code etc. It would be really great if we would be able to fix that. And maybe it helps out other people in the future.

**Comment by alvarotrigo** [comment]
> The thing that keeps it from working is that our site uses 
> ScrollOverflow: true
> and I can't seem to overwrite it, that when the drop-down is selected scrollOverflow gets changed to false. I tried changing it to false in my if-clause but nothing seems to happen. If you want I can provide code etc. It would be really great if we would be able to fix that. And maybe it helps out other people in the future.

Fullpage.js doesn't provide a way to turn off or on scrollOverflow I'm afraid.

**Comment by JanaKemmer** [comment]
Thank you for your answer anyway! At least I can now tell the graphic designer that it just isn't possible. Thank you!

**Comment by timgaines** [comment]
Hi, I am loving fullpage.js!

So I am experiencing the same issue on IE 11 where scrolling a select box's options scrolls the page. Is this something you are looking to fix/handle within fullpage.js?

You can see it in action here: http://codepen.io/timdoes/full/GqZXRB/

Thanks!

**Comment by alvarotrigo** [comment]
@timgaines not planning to add the solution in fullpage.js.
You can solve it by yourself as suggested [in this answer](http://stackoverflow.com/a/30188977/1081396).

**Comment by timgaines** [comment]
@alvarotrigo Thanks for the response.
