### ISSUE TITLE
Advance Options, How to add a new page?

### ISSUE THREAD

**Issue by misterzik** [alvarotrigo/fullPage.js#1474]
Hello,

I am using Advanced settings for my .js, I cannot get to work the extra section i added (thirdPage), what am i missing?

     $('#fullpage').fullpage({
        //Navigation
        menu: false,
        lockAnchors: false,
        anchors:['firstPage', 'secondPage', 'thirdPage'],
        navigation: false,
        navigationPosition: 'right',
        navigationTooltips: ['firstSlide', 'secondSlide', 'thirdSlide'],
        showActiveTooltip: true,
        slidesNavigation: true,
        slidesNavPosition: 'bottom',

        //Scrolling
        css3: true,
        scrollingSpeed: 700,
        autoScrolling: true,
        fitToSection: true,
        fitToSectionDelay: 1000,
        scrollBar: false,
        easing: 'easeInOutCubic',
        easingcss3: 'ease',
        loopBottom: false,
        loopTop: false,
        loopHorizontal: true,
        continuousVertical: false,
        normalScrollElements: '#element1, .element2',
        scrollOverflow: false,
        touchSensitivity: 15,
        normalScrollElementTouchThreshold: 5,

        //Accessibility
        keyboardScrolling: true,
        animateAnchor: true,
        recordHistory: true,

        //Design
        controlArrows: true,
        verticalCentered: true,
        resize : false,
        sectionsColor : ['rgb(58, 179, 225)', 'rgb(58, 179, 225)', '#000000'],
        paddingTop: '3em',
        paddingBottom: '10px',
        fixedElements: '#header, .footer',
        responsiveWidth: 0,
        responsiveHeight: 0,

        //Custom selectors
        sectionSelector: '.section',
        slideSelector: '.slide',

        //events
        onLeave: function(index, nextIndex, direction){},
        afterLoad: function(anchorLink, index){},
        afterRender: function(){},
        afterResize: function(){},
        afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
        onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){}
    });

		});

**Comment by alvarotrigo** [comment]
You don't need to use the whole example provided in the docs... you are using things such as `normaScrollElements` when you shouldn't... 

The problem is no there, probably in you markup, just see the examples provided in fullpage.js

**Comment by misterzik** [comment]
<div id="fullpage">
    <div class="section" id="section0">
    1
    </div>
    <div class="section" id="section1">
    2
    </div>
    <div class="section" id="section2">
    3
    </div>
    </div>

@alvarotrigo

**Comment by alvarotrigo** [comment]
I recommend you to see [the examples available](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) and start working with one of them for your base file. 

That way you will avoid problems. You are doing something wrong. Check the javascript console as well.
