### ISSUE TITLE
If css3:true and screen < 768px ... i can't scroll up

### ISSUE THREAD

**Issue by grapparubinsky** [alvarotrigo/fullPage.js#1475]
Hi,
thanks for your plugin!

I have a running website where I have this problem:
http://bit.ly/1F2Ue2Z

When css3:true option is enabled and resolution is under 768px I can't scroll up or anything.
As you can see in my source code I have only bootstrap framework (that I imagine that there are no incompatibilities).

Can you help me?
(I tried to change css3 setting in "false", everything works fine..but animations become very slow on mobile devices)

Thanks
R.

**Comment by alvarotrigo** [comment]
Please reproduce the problemin [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen to isolate the problem.

Closed until then.
