### ISSUE TITLE
silentMoveTo sets the original scrollingSpeed before performMovement is called, so it's not a silentMove

### ISSUE THREAD

**Issue by rameau1982** [alvarotrigo/fullPage.js#1476]
The function seilentMoveTo is defined like this:

FP.silentMoveTo = function(sectionAnchor, slideAnchor){
            FP.setScrollingSpeed (0, 'internal');
            FP.moveTo(sectionAnchor, slideAnchor)
            FP.setScrollingSpeed (originals.scrollingSpeed, 'internal');
        };

But as FP.moveTo calls to scrollPage which has a call to requestAnimFrame and it is asynchronous, the scrollingSpeed is reseted to its original value (700) and the movement is done WITH animation.

The solution would be to define the function moveTo with a third argument: callback and pass this callback to the function scrollPage, which accepts a callback as the second argument of the function.
Inside the callback would be the call to FP.setScrollingSpeed (originals.scrollingSpeed, 'internal');

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/1465 and https://github.com/alvarotrigo/fullPage.js/issues/1442

Waiting for [Chrome to fix their bug](https://github.com/alvarotrigo/fullPage.js/issues/1389) before spending time on this problem.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.7.0
