### ISSUE TITLE
After adding onLeave callback scrolling effect is reset

### ISSUE THREAD

**Issue by jacobdo** [alvarotrigo/fullPage.js#1477]
Hi, 

I am trying to use afterLoad and onLeave callbacks. afterLoad seems to work fine, but when I add onLeave, the nice scrolling effect (i.e. scrolling only to the next section no matter how far I turn the mousewheel per event) is reset and if I, say, turn the mousewheel by four steps it will jump from first to last and in order to achieve the previous effect, I have to scroll very slowly.

I have just used the default code snippets and added colours to the sections.

**Comment by voxes** [comment]
what are you running in the `onLeave` callback?

**Comment by jacobdo** [comment]
Just the default onLeave code from the example.

**Comment by alvarotrigo** [comment]
Make sure you use the latest version of fullpage.js. 2.6.9 
You are basically describing [the solved bug](https://github.com/alvarotrigo/fullPage.js/issues/1389) caused by a Chrome bug.
