### ISSUE TITLE
Sections with overflow-x

### ISSUE THREAD

**Issue by juandanceswild** [alvarotrigo/fullPage.js#1478]
Is there a way to allow overflow-x scrolling on sections when the content is wider than the viewport?

Currently trying to scroll the slide results in a change of section. I would like to scroll horizontally only - vertical scroll should still switch sections. 

Is this possible?

JSFiddle :
https://jsfiddle.net/juandanceswild/jatwuwn3/

**Comment by alvarotrigo** [comment]
Nop. And it won't be done.
