### ISSUE TITLE
Android orientation change on mobile shows a desktop version 

### ISSUE THREAD

**Issue by mrtom100** [alvarotrigo/fullPage.js#1480]
I have been using your script which has worked flawless, i found a little bug that seems to affect Android chrome browsers. When you have it in portrait site looks fine then change to landscape it reverts to the desktop version. If i refresh while in landscape it looks great again. If i change it then to portrait its the same issue. It seems like the change in orientation is confusing the css. This only happens on pages using the fullpage.js script so i know the css is fine. Any help and ideas would be great...

**Comment by alvarotrigo** [comment]
Nothing to do with fullpage.js. 
It is a matter on how you determine when to load one or another view.
