### ISSUE TITLE
Keep url segments before hastags 

### ISSUE THREAD

**Issue by tamben** [alvarotrigo/fullPage.js#1482]
Is it possible to keep original url segments before the anchor hastag while scrolling? 

Or how can I prevent switching from "myurl.com/services#hastag-1" to "myurl.com/#hastag-2" after section change?

**Comment by alvarotrigo** [comment]
> Or how can I prevent switching from "myurl.com/services#hastag-1" to "myurl.com/#hastag-2" after section change?

Just do not use the `anchor` option or any `data-anchor` attribute in your sections.
You have [an example available](http://alvarotrigo.com/fullPage/examples/noAnchor.html) in the plugin files to download.
