### ISSUE TITLE
Site is not mobile responsive

### ISSUE THREAD

**Issue by koolkav1** [alvarotrigo/fullPage.js#1483]
I am trying to use full page js but in my mobile the screen does not resize even though on my browser it does. Any help would be highly appreciated. www.dev-william-russell.com

**Comment by jamez14** [comment]
This question might be better suited for Stackoverflow (because it doesn't directly relate to the plugin itself). Regardless, I believe if you place this in the `<head>

**Comment by alvarotrigo** [comment]
@jamez14 is right. 
If you belive its a fullpage.js issue then you would have to replicate it in jsfiddle or codepen to isolate the problem.
