### ISSUE TITLE
direction is not defined

### ISSUE THREAD

**Issue by pogocki** [alvarotrigo/fullPage.js#1485]
There is a bug in  FP.moveSectionDown.
When I declare onBeforeMoveSection callback, there is an error when script tries to call it.

if(options.onBeforeMoveSection.call(this, **direction**, currentSlide, destiny, slides, activeSection) === false){}

And why onBeforeMoveSection in not used in moveSectionUp? I think it should..

**Comment by alvarotrigo** [comment]
> When I declare onBeforeMoveSection callback

There's no callback with that name...

**Comment by pogocki** [comment]
https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L327

**Comment by alvarotrigo** [comment]
Nice to know... I'll have to remove it again. 
It seems I added it by mistake after [having removed it](https://github.com/alvarotrigo/fullPage.js/pull/1251). 

Just use `onLeave`. It works the same way.

**Comment by pogocki** [comment]
Thanks.
BTW.. fullPage is great!

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.7.0
