### ISSUE TITLE
how to disable/hide a section?

### ISSUE THREAD

**Issue by pogocki** [alvarotrigo/fullPage.js#1487]
Is there a way to disable (or hide) a section in order do skip it while scrolling?
I need to disable/hide sections #optionB1 and #optionB2, and show #optionA1 and #optionA2 when a user choose "option A" on the first section, and also disable/hide sections #optionA1 and #optionA2, and show #optionB1 and #optionB2, when a user choose "option B".

**Comment by alvarotrigo** [comment]
Nop. You can not hide them.

**Comment by alvarotrigo** [comment]
You could somehow simulate that by using callbacks together with the CSS style `display:none` for the section you want to hide.
But you would have to do the logic for each special case.

[Reproduction online](http://jsfiddle.net/97tbk/813/)

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    onLeave: function(index, nextIndex, direction){
        if(nextIndex == 2){
            if(direction == "down"){
            	$.fn.fullpage.moveTo(3);
            }else if(direction == "up"){
                $.fn.fullpage.moveTo(1);
            }
        }
    }
});
```

**Comment by pogocki** [comment]
It works! Thanx.
I tried this before, but indexing sections like 1,2,3... worked wrong with $('.section:eq(' + nextIndex + ')').hide(). 
Now with $('.section:eq(' + (nextIndex-1) + ')').hide() it works great.
