### ISSUE TITLE
Lazy loading background images

### ISSUE THREAD

**Issue by dademaru** [alvarotrigo/fullPage.js#1488]
Hi Álvaro,
As always thanks for your great plugin, I hope to complete the project where I used it soon to show you ;-)
I'm using only background images, 9 slides per section, some pages have 7-8 sections.
What about lazy loading background images?
Is it already supported by fullPage or should I add other lazy loading plugin such as
http://dinbror.dk/blog/blazy/#Background ?
Thanks.
Davide

**Comment by alvarotrigo** [comment]
Check [this answer](https://github.com/alvarotrigo/fullPage.js/issues/46#issuecomment-26509996).

**Comment by dademaru** [comment]
Hi Álvaro,
thanks, I missed that answer while looking for this issue/feature.
