### ISSUE TITLE
Content moves vertically

### ISSUE THREAD

**Issue by Chrisande** [alvarotrigo/fullPage.js#1490]
Hey and thank you so much for the plug in, I love it. 

However, there is a problem that I never seem to solve, perhaps it's something with my CSS, but I don't know for sure. When I first load the page, the content on all the slides moves down a bit, until I resize the window back again (default -> fullscreen -> default) and then everything seems to be normal. You can even see that the slide arrows have moved up after I resized the windows. 

This is how two of the sections look before I resized the window:

![screen shot 2015-09-08 at 13 50 37](https://cloud.githubusercontent.com/assets/13556844/9726056/d6ea85b4-5630-11e5-92dc-045ada0a7b90.png)
![screen shot 2015-09-08 at 13 50 58](https://cloud.githubusercontent.com/assets/13556844/9726059/d6f0ecf6-5630-11e5-8074-44f3021f305a.png)

And this is how it looks after I resized it...

![screen shot 2015-09-08 at 13 51 25](https://cloud.githubusercontent.com/assets/13556844/9726057/d6eb1470-5630-11e5-8f68-a4588ebb7413.png)
![screen shot 2015-09-08 at 13 51 35](https://cloud.githubusercontent.com/assets/13556844/9726058/d6f05444-5630-11e5-9f18-728e7d12f0a1.png)

Would appreciate a lot for help!

Thanks

**Comment by alvarotrigo** [comment]
Sorry I would need a clean reproduction of the problem for further investigation.
Please reproduce your issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen. I'll close the issue until then.

Your problem as you can see doesn't take place in any of the [demo pages](http://alvarotrigo.com/fullPage/).

**Comment by Chrisande** [comment]
Hahah that exclamation mark solved everything, thanks!!!!!!!!!!

**Comment by alvarotrigo** [comment]
> Hahah that exclamation mark solved everything, thanks!!!!!!!!!!

Just out of curiosity. Why did you forget the exclamation? Did you copy it from somewhere else?

**Comment by Chrisande** [comment]
https://www.youtube.com/watch?v=F6602KMtq1Y

I just followed you (even though you made remarks on it), so it's my fault...

**Comment by alvarotrigo** [comment]
Right ok.
