### ISSUE TITLE
Fullpagejs & Webflow Conflict

### ISSUE THREAD

**Issue by slimbl2** [alvarotrigo/fullPage.js#1492]
Hello, 
I'm using webflow and i'm happy about using it.
I'm using Fullpage plugin and i'm more than happy about using it too.

It works well, except one thing, it stops the native animations "onscroll" from working.
Basely, I have a menu created by Webflow and i set an effect to make the text change color when the section is on the screen.. but from the moment i added fullpage, it does not change anymore.
Last point to notice, is the effect works only at the right moment i re-size the navigator window.

I'm not sure that i'm expressing my self very well, but it will be really great of you if you could help me.

Thank you very much for taking my request on consideration.

**Comment by alvarotrigo** [comment]
Read the [FAQ Frequently Answered Questions](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

Use `scrollBar:true` or `autoScroll:false`.

**Comment by slimbl2** [comment]
THank you very much... It was so nice of you

**Comment by slimbl2** [comment]
Sorry to comeback, but there is no way to do it without having the scroll bars?

**Comment by slimbl2** [comment]
Sorry to insist, but there is no third possibility? I mean with keeping both plugins work together (Im not a web designer, so coding is quite difficult for me).
Thank you again

**Comment by alvarotrigo** [comment]
I already answered you:

> Use scrollBar:true or autoScrolling:false.

**Comment by slimbl2** [comment]
But without showing the scrollbar and keeping both plugins.. No?

**Comment by alvarotrigo** [comment]
> But without showing the scrollbar and keeping both plugins.. No?

I already explained it. 

> use the callbacks or the CSS class added to the body. 

Check the video tutorial I posted or learn how to use the callbacks.

**Comment by slimbl2** [comment]
Callback don't work anymore when used with webflow.. Or i didn't succeed to
make it work.. That's my problem.. If any access to my work could help you?
You are already freely kind but if u could help me rt will be really great

**Comment by alvarotrigo** [comment]
> If any access to my work could help you?

The only thing I need is a reproduction of your problem in jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
> Callback don't work anymore when used with webflow

Try the latest fullpage.js 2.7.1. I've just fixed a bug which took place on orientation change or resize regarding the callbacks.
