### ISSUE TITLE
windows.scroll does not work

### ISSUE THREAD

**Issue by aliogul** [alvarotrigo/fullPage.js#1493]
hello,

this example works on an empty file but does not work when vendors/jquery.slimscroll.min.js is included.

```javascript
$(window).scroll(function(){
		alert("aa");
});
```

any idea on how to fix this issue? 

thank you.

**Comment by alvarotrigo** [comment]
Nothing to do with fullpage.js. 
Slimscroll does not really scroll the element anyways.

**Comment by aliogul** [comment]
thank you using fullpage does not mean that we shouldn't use any other javascript codes.
slimscroll simply interrupts this code. 

I need to use this to fade out an element as the user scrolls

thank you.

**Comment by alvarotrigo** [comment]
> this example works on an empty file but does not work when vendors/jquery.slimscroll.min.js is included.

You have said it doesn't work when including slimScroll. 

If its not about slimScroll, then read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions), you'll find your answer there. 

`scrollBar:true` or `autoScrolling:false`.
