### ISSUE TITLE
Weird issue when resizing window

### ISSUE THREAD

**Issue by reddo** [alvarotrigo/fullPage.js#1495]
I have a setup like this: http://jsfiddle.net/reddo/8aj1fo6u/
Disregard the right half, some animation will happen there.

When the active section is not the first one and I resize the window, the left side, the one on which the fullPage.js is running, doesn't resize correctly and the section scrolls out of screen by a little.

Any ideas as to what is causing this and maybe a solution?

**Comment by reddo** [comment]
Nevermind, updating to 2.7.1 fixed it. Thanks for the great plugin!

**Comment by reddo** [comment]
I'm really sorry to bother you again, but it seems the problem still persists. Check out this setup: http://jsfiddle.net/reddo/8aj1fo6u/3/

**Comment by alvarotrigo** [comment]
I'm afraid fullpage.js is mean to work in full width. 
Unless you can reproduce the same issue in a full width page I have nothing to say about it.

I was not able to reproduce it with your same initialization [in this example](http://jsfiddle.net/97tbk/819/).

Also, you are not suppose to place the fullpage.js container inside any other one.

**Comment by reddo** [comment]
I'm sorry to have bothered you. I just founf your multiscroll plugin which is exactly what I need. Great work with both of them

**Comment by alvarotrigo** [comment]
@reddo no problem!
