### ISSUE TITLE
Scroll issue with Google Maps

### ISSUE THREAD

**Issue by dademaru** [alvarotrigo/fullPage.js#1497]
Hi Alvàro,

I have different Google Maps in different sections.
The maps should remain draggable and while dragging the fullpage scroll should be blocked.
On desktop, with trackpad, adding the option `normalScrollElements: '.map',` it works (after dragging a map, the section scroll is disabled – I've added an overlay div above the map to see if moving trackpad on it the section keeps moving).
But normalScrollElements doesn't seem to affect touch devices.
What's worst is that on tablet fullPage scroll seems to get crazy, since it often scrolls in the opposite direction to your swipe. I can't understand why it behaves so.
 
I've tried to reproduce the issue here: http://codepen.io/dademaru/pen/pjJXpd
(the first section is an empty section only to try the scroll on sections without maps).
Maybe you already have a fix.
Thanks

Davide

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1281

**Comment by alvarotrigo** [comment]
One thing is for sure: you can not have a whole section with a draggable map. Or you won't be able to scroll up or down your site. 

What I would recommend is disabling the scroll in all directions with `setAllowScrolling` once your reach the map section ( by using a callback such as `afterLoad`).

Then, in order to move up or down I would add two arrows (or whatever you prefer) to which you can bind the `moveSectionDown` or `moveSectionUp` functions.

**Comment by dademaru** [comment]
Hi Alvàro,
thanks for the answer, I missed the duplicated ticket.
I have the map on a layer and the overlay with text (as reproduced in 2nd section) above it, so the whole section should be swipeable, right?
Thanks

**Comment by alvarotrigo** [comment]
I don't know why you have the overlay over the section or why you have two maps in two different sections.

As I said, you can not have a map taking the whole section unless you do something such as what I suggested above.

**Comment by dademaru** [comment]
;-)
I have other pages with full background slides inside sections (with a text overlay always above them, fixed with `position: absolute`), so I thought it was possible to have a similar layout for maps, with text overlay that can be activated / deactivated as needed (to see background images or full screen maps).

I need different maps like this website: http://energycoalition.org/energy-architects-in-action/
one for each section, with marker links in the overlay.

I'm going to try what you suggested, by disabling the scroll with `afterLoad` when section has a map.
I already have custom buttons with keyboard support to let you move between sections even when scroll is disabled: my concern was with touch swipe with Google Maps.

I let you know, meanwhile thanks for your support.

**Comment by vectorman1** [comment]
Hi,

dug up this issue, hope not too annoying to bring it back up, it's been only a month and a half right?

Anyways, I have a map covering the whole section and I've put an arrow to go to the next one, how can I make it so the map is actually usable in mobile?

`normalScrollElements: '#map'` doesn't do the trick and I've been trying to do it, not figuring a solution for quite some time now. 

I wasn't able to find anything regarding my issue and I'm quite novice.

**Comment by alvarotrigo** [comment]
> how can I make it so the map is actually usable in mobile?

Cover it with with fullscreen layer.

**Comment by vectorman1** [comment]
I am not sure what you meant, I did this ->
`<div id="map"></div>`
`<div class="map-cover"></div>`

and the CSS for map-cover being `.map-cover {
	width:100%;
	height:100%;
	position: absolute;
	top:0;
}` and the map is totally unfunctional, I can see why, perhaps I didn't understand specifically?

**Comment by alvarotrigo** [comment]
Haha! :D Sorry my fault. I understood **unuseful** instead of **useful**.

I suggest you to turn scrolling of by using `$.fn.fullpage.setAllowScrolling(false)` once you load the section with the map (using the `afterLoad` callback).

Then turn it on again `onLeave`.

**Comment by vectorman1** [comment]
So I did that, I had an assumption for something as that but wasn't sure. Not sure what's going wrong though - https://github.com/vectorman1/Thinqi/blob/gh-pages/scripts/scripts.js#L9-L21

It doesn't change anything - you can see for yourself at http://vectorman1.github.io/Thinqi/

**Comment by alvarotrigo** [comment]
@vectorman1 please reproduce it on jsfiddle or codepen to isolate the problem.

**Comment by vectorman1** [comment]
@alvarotrigo the project is a bit too big for me to do that, also - lazy. What I did was remove the map and it doesn't scroll to the next segment, although if you scroll on the map then it scrolls.

**Comment by vectorman1** [comment]
Also - found something strange - it scrolls only if you scroll downwards ( top -> bottom ) and not upwards left or right. Any ideas ?
