### ISSUE TITLE
Parallax background

### ISSUE THREAD

**Issue by darksist** [alvarotrigo/fullPage.js#150]
Hi, i want a make parallax background effect with stellar.js. How can i integrate with fullpage.js?

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!

**Comment by Charlie91** [comment]
Does parallax extension work with pureJS version of Fullscale.js?

**Comment by alvarotrigo** [comment]
> Does parallax extension work with pureJS version of Fullpage.js?

Nop. None of the extensions. The pure JS version hasn't got a good update since 2015.

**Comment by duongtrunga** [comment]
i really read document parallax extension then do like that. but it not work, i dont know how to do this. Can u build a template by css html and js for demo?

**Comment by alvarotrigo** [comment]
@duongtrunga please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase.
