### ISSUE TITLE
Does autoHeight also work with larger sections?

### ISSUE THREAD

**Issue by visualcookie** [alvarotrigo/fullPage.js#1501]
Hi,

I got a tiny "problem" and need a possible solution to this. I have one section, thats higher than the others on mobile - there are three tiles in it - is this possible? If so, do I have to change something?

**Comment by alvarotrigo** [comment]
> there are three tiles in it - is this possible?

Have you tried it? Just give it a go.

**Comment by visualcookie** [comment]
It's not working like expected. I can scroll through the page now but the section that's larger and has the class ```fp-auto-height``` will be completely ignored. It stops in the middle of this section and after two seconds it goes to the next section instead of letting me scroll and read myself through this section first.

The tiles, I've spoken of, are below each other on mobile.

**Comment by alvarotrigo** [comment]
Well, of course you would have to use the `responsive` option to turn out `autoScrolling`. 
[Working demo](http://jsfiddle.net/97tbk/822/)

You can not have both things at the same time:

- autoScrolling:true
- Sections bigger than the viewport.

If you want that, the only solution is to to use `scrollOverflow:true` as [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by alvarotrigo** [comment]
[Here's an example of a site doing exactly what you want. ](http://www.boxreload.com/)

**Comment by visualcookie** [comment]
Thanks. :+1:
