### ISSUE TITLE
`resize: true` should be processed also at `init()`

### ISSUE THREAD

**Issue by helloheesu** [alvarotrigo/fullPage.js#1504]
Resizing process (`resizeMe()`) should be done also at `init()`.
As it is not, with `resize: true`, initial screen is not resized through that process, and resizing window a little makes a big difference.

**Comment by alvarotrigo** [comment]
There's no way for the plugin to know how you want to display your text.

Read [this answer](https://github.com/alvarotrigo/fullPage.js/issues/492#issuecomment-45110427).

I would encourage you to use other plugin for that such as [Flowtype](http://simplefocus.com/flowtype/)
