### ISSUE TITLE
$.fn.fullpage.setAllowScrolling(true) doesn't work

### ISSUE THREAD

**Issue by aliogul** [alvarotrigo/fullPage.js#1505]
$.fn.fullpage.setAllowScrolling(false); works fine and disables mouse scrolling, but $.fn.fullpage.setAllowScrolling(true); does not work.

is this not the correct way to enable it again?

FYI : I open a popup (full screen div) and disable scrolling temporarily, and when popup is closed I need to enable again.  I do these in 2 simple javascript functions.

thank you for your support.

**Comment by alvarotrigo** [comment]
It is working as expected on [this page](http://alvarotrigo.com/fullPage/examples/methods.html).

I'll close the issue until you can provide an isolated reproduction of the problem in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.
