### ISSUE TITLE
Error: Syntax error, unrecognized expression: .fp-section[data-anchor="""]

### ISSUE THREAD

**Issue by q2amarket** [alvarotrigo/fullPage.js#1506]
I have not idea, since I haven't setup any navigation and still giving error for `data-anchor`. Can you please help to fix it?

In console log I am getting below message
````text
Error: Syntax error, unrecognized expression: .fp-section[data-anchor="""]
....value:null},gb.error=function(a){throw new Error("Syntax error, unrecognized ex...
````

**Comment by alvarotrigo** [comment]
You would have to provide an isolated reproduction of the problem in jsfiddle or codepen for further investigation. I'll close the topic until then.

I was not able to reproduce the issue in any of the [demo pages](http://alvarotrigo.com/fullPage/).
