### ISSUE TITLE
Jumpy horizontal scroll on rapid right/left clicking

### ISSUE THREAD

**Issue by asalisbury** [alvarotrigo/fullPage.js#1507]
Rapidly clicking on the right / left arrows causes the slide to animate from the beginning slide each time, resulting in a strange jumping or skipping motion. 

Happens in Chrome version 45.0.2454.85 (64-bit) on OS X 10.10.5, but unable to reproduce in Firefox or Safari.

For example, see: http://alvarotrigo.com/fullPage/#secondPage. When clicking rightwards, the "1" icon is visible until the very end since it animates from the initial slide for every rightwards move.

Implement a debouncer?

**Comment by alvarotrigo** [comment]
Yep, I'm aware of it, thanks for reporting it anyway!
It's related with [this topic regarding](https://github.com/alvarotrigo/fullPage.js/issues/1389) a [bug in Chrome > 44](https://code.google.com/p/chromium/issues/detail?id=513206).

**Comment by asalisbury** [comment]
Thanks Alvaro. That's really too bad they haven't fixed this bug still. Any idea on when your next release may be?

**Comment by alvarotrigo** [comment]
> Any idea on when your next release may be?

Not quite sure. Maybe a week?

**Comment by alvarotrigo** [comment]
Chrome solved the issue.
