### ISSUE TITLE
Navigation Anchor Links stop working after some clicks 

### ISSUE THREAD

**Issue by andreassp** [alvarotrigo/fullPage.js#1509]
Hi
I implemented fullpage.js for a project and found the following behaviour:

After clicking some sections and scrolling through the page, some anchor-links stop working.
The are formatted correctly but do not jump to the section.

The strange thing is, that this only "sometimes" happens which makes it very hard to track...

For example:
http://46.101.149.29/home-en/
Start clicking different sections/anchor-links and then return to "01 About -> Introduction" (or any other link, mostly the ones at the top of the list) - it gets stuck.
Why is this?

I tried to exclude any other js file or put the whole navigation in one big list, but didnt find anything.

I am using basic bootstrap (with bootstrap.js) for the menu-dropdowns - the fullpage.js setup looks like this

``` javascript
    $('#fullpage').fullpage({
        anchors: getAnchors(),
        menu: '.scrollnav',
        scrollingSpeed: 1000,
        scrollBar: true,
        paddingTop: '150px',
        responsiveWidth: 900,
    });
```

(getAnchors collects all the anchors).

Thanks for your help and the great script!

**Comment by alvarotrigo** [comment]
I'm afraid I would need you to reproduce the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen to isolate fullpage.js from any external CSS or JS you are using.

I'll close the issue until then.

**Comment by andreassp** [comment]
Hello
I isolated my case here:
https://jsfiddle.net/97tbk/860/

If you click through the (second-level) links up and down and then try to go back to "Einleitung" it (sometimes) doesnt work...

**Comment by alvarotrigo** [comment]
Right, I see, it seems to happen only when clicking the menu very fast, right ?

**Comment by andreassp** [comment]
i think its not about the speed... i even get the error, when navigating "normally".
Mostly on the very first nav-item, but sometimes also on other links.

**Comment by alvarotrigo** [comment]
Have you tried it with `fitToSection:false`?

**Comment by andreassp** [comment]
I just tried in JSFiddle, same effect.. did it work out for you?

**Comment by andreassp** [comment]
btw - i am testing on Safari/OSX, but expierenced the same on chrome and firefox

**Comment by andreassp** [comment]
Hello Alvaro

I guess, i found something here:

If the section div´s look like this

```
 <div class="section">....</div>
 <div class="section">....</div>
 <div class="section">....</div>
 <div class="section">....</div>

```

it seems to work.

But if there are container-divs around that, like

```
<div class="area-1">
    <div class="section">....</div>
    <div class="section">....</div>
</div>
<div class="area-2">
    <div class="section">....</div>
    <div class="section">....</div>
</div>
```

it happens, that some links do not work occasionally..

What do you think?

Best regards
Andreas

**Comment by alvarotrigo** [comment]
> If the section div´s look like this it seems to work.

I thought the same the first time, but I believe I was able to reproduce it with a normal structure as well when clicking fast multiple times over multiple links.

About the structure, you should be following the [required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure). I won't deal with any problems you can have regarding your custom structure.

**Comment by andreassp** [comment]
I also tried it on JSfiddle - i guess it really doesnt work, when there are <div>s around or in between the section-divs...
I think, i have to rework the code structure of the site for now.
Anyhow - Thanks a lot!

**Comment by alvarotrigo** [comment]
This should be fixed in v4 now!! 👍
