### ISSUE TITLE
alarotrigo's attitude is shit

### ISSUE THREAD

**Issue by Corbyj1** [alvarotrigo/fullPage.js#1511]
Hi, 

I have multiple issues with this plugin, however useful it is. I tried to look up these issues against previous github questions that actually described them pretty well. 

Unfortunately they've all been closed because you have the attitude and patience of a five-year old. It'd be lovely if you actually even tried to support your users.

Is their any fix for your douchey attitude? Probably not though. 

Thanks,

**Comment by alvarotrigo** [comment]
I'm sorry you didn't find your answer. I'll keep trying my best.
