### ISSUE TITLE
Issue when reloading the page with hash

### ISSUE THREAD

**Issue by karugianni** [alvarotrigo/fullPage.js#1512]
Hello all, thank you for the great plugin. However, there is an issue in this website:

http://petsiavas.businesswebsites.gr/staging/

Everything breaks when the page has a hash. 

Any ideas?

**Comment by alvarotrigo** [comment]
> when the page has a hash.

Can you be more specific and provide an example? 
I'm not quite sure what are you talking about. 

Also, I would recommend you to use the latest version 2.7.1 instead.

**Comment by karugianni** [comment]
Hello again, yes. Navigating in inner pages, but when I go from the inner pages of the website in the homepage with a hash, the fullpage breaks.

**Comment by alvarotrigo** [comment]
Can you provide me the direct URL or section from which I can fire the hash in the url?

**Comment by karugianni** [comment]
http://petsiavas.businesswebsites.gr/staging/#company-section Check here

**Comment by alvarotrigo** [comment]
Use the option `lockAnchors:true` and let me know if that fixs it for you

**Comment by alvarotrigo** [comment]
Also, remember:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by karugianni** [comment]
Yes, actually I do, but I need this element, and no, the  lockAnchors:true not working.

**Comment by alvarotrigo** [comment]
Sorry I misunderstood your problem.
It seems you are trying to scroll within a section to a certain internal anchor by its `id`.

I would say you can not use internal anchors to scroll to anywhere in your site, as this is a full page plugin and therefore the browser scrolling to the `id` element will move all the sections in the wrong position. 

You can only fix it if you decide to use fullpage.js with the option `scrollBar:true` or `autoScrolling:false`.

**Comment by karugianni** [comment]
Thank you  for this great info. That did it. Thank you again.
