### ISSUE TITLE
Scroll doesn't work on mobile device (with an overlay)

### ISSUE THREAD

**Issue by br0k3n** [alvarotrigo/fullPage.js#1513]
Hi,

great plugin, I've an issue with the latest version.
I'm developing a website with your plugin, but I am committed in a little issue.
Every vertical section has a div overlay that fully covers the sectionSelector area, all works good on every desktop / laptop, but on mobile device (so with a touch screen) the sections don't scroll. In my opinion it is related with the position of the overlay div.
All works correctly with the previous version but this the last one the scroll has been block on mobile.

Any suggestion?

Thanks

**Comment by alvarotrigo** [comment]
Can you provide a reproduction of the issue?

**Comment by br0k3n** [comment]
Sure, here's the url:

http://goo.gl/jUKkWX

Thanks :)

**Comment by alvarotrigo** [comment]
What are the steps I should do to reproduce the problem?

**Comment by br0k3n** [comment]
Hi,

please check the site on desktop (ex. with Google Chrome) anche scroll down; all works correctly.
Now check the site on a touch device, here you can't scroll down because the sectionSelector area is under the caption one.

Thanks

**Comment by alvarotrigo** [comment]
I believe you are talking about your `thmlvCaptionWrapper` element.
I would be surprised if this worked with older versions of fullpage.js.

You should place it within the section, not outside the fullpage.js wrapper.

**Comment by br0k3n** [comment]
Hi, thanks, however if you try with 2.5.6 all works correctly

Regards

**Comment by alvarotrigo** [comment]
The plugin evolved :)

**Comment by alvarotrigo** [comment]
I believe [here's](https://github.com/alvarotrigo/fullPage.js/issues/1088) the origin of the change.

**Comment by br0k3n** [comment]
Hi,

thanks so much.

There's a way to revert it?

Thanks again

2015-09-16 17:02 GMT+02:00 Álvaro <notifications@github.com>:

> I believe here's <https://github.com/alvarotrigo/fullPage.js/issues/1088>
> the origin of the change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1513#issuecomment-140768257>
> .
>



-- 
-----------------

Questo messaggio può contenere informazioni confidenziali o strettamente
riservate ed è indirizzato unicamente ai destinatari previsti dal mittente.
Qualora non facciate parte di costoro, siete pregati di non usare,
sfruttare, diffondere o riprodurre il contenuto di questo messaggio. Se si
tratta di un errore, vogliate avvertire il mittente con cortese
sollecitudine. Qualunque uso illecito sarà soggetto ad adeguati
provvedimenti.

-----------------

**Comment by alvarotrigo** [comment]
I would recommend you to set your overlay to `position: fixed` and set it inside the plugin's wrapper.


> There's a way to revert it?

Indeed you can, but think that any other updates of fullpage.js won't have that reverted change and you won't be able to use newer version of fullpage.js without reverting the change by yourself.

See the changes [here.](https://github.com/alvarotrigo/fullPage.js/commit/8561fd59ff4cbe2149b239a1ae32f719e7aebf6a)

Revert the ones for `addTouchHandler` and `removeTouchHandler`.:

Instead of `$(WRAPPER_SEL).off` use `$document.off` for those two functions.

**Comment by br0k3n** [comment]
Thanks :)

2015-09-16 17:20 GMT+02:00 Álvaro <notifications@github.com>:

> I would recommend you to set your overlay to position: fixed and set it
> inside the plugin's wrapper.
>
> There's a way to revert it?
>
> Indeed you can, but think that any other updates of fullpage.js won't have
> that reverted change and you won't be able to use newer version of
> fullpage.js without reverting the change by yourself.
>
> See the changes here.
> <https://github.com/alvarotrigo/fullPage.js/commit/8561fd59ff4cbe2149b239a1ae32f719e7aebf6a>
>
> Revert the ones for addTouchHandler and removeTouchHandler.:
>
> Instead of $(WRAPPER_SEL).off use $document.off for those two functions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1513#issuecomment-140774592>
> .
>



-- 
-----------------

Questo messaggio può contenere informazioni confidenziali o strettamente
riservate ed è indirizzato unicamente ai destinatari previsti dal mittente.
Qualora non facciate parte di costoro, siete pregati di non usare,
sfruttare, diffondere o riprodurre il contenuto di questo messaggio. Se si
tratta di un errore, vogliate avvertire il mittente con cortese
sollecitudine. Qualunque uso illecito sarà soggetto ad adeguati
provvedimenti.

-----------------
