### ISSUE TITLE
Is it possible to click elements inside a slide?

### ISSUE THREAD

**Issue by Sl0b** [alvarotrigo/fullPage.js#1516]
I can't click button or link inside a slide, outside, in section for example, no problem but as soon as i put it in a slide...
I tried different things but nothing worked. Is it normal behavior did I miss something?

**Comment by alvarotrigo** [comment]
Can you please provide a reproduction of your problem? Ideally in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.

**Comment by Sl0b** [comment]
I'm sorry, finally found a colleague of mine put a negative z-index on .fp-slides... Everything is back to normal.
