### ISSUE TITLE
fp-table not added to the first section

### ISSUE THREAD

**Issue by hijklmno** [alvarotrigo/fullPage.js#1518]
Hi guys, awesome plugin! 

This is my first issue I've ever filed, so bare with me if I am missing any critical information. I am using jquery.fullPage.min.js, version 2.7.1. 

Not sure if this is a design decision, but the class `fp-table` is not injected onto the first section. This causes the second section in my page to disappear (everything within the div with class container - bootstrap one) only during the transition from the first section to the second section. 

This issue is apparent in Chrome 44 and Safari 8.

Adding the class `fp-table` to the first section fixes this issue in Chrome.

Thanks for your help!

EDIT: I would like to add that my first section contains slides, whereas the second section (and so forth) do not. 
EDIT2: markdown.

**Comment by alvarotrigo** [comment]
Are you trying to add the class `fp-table` by yourself?
Or you are just saying fullpage.js doesn't add it when using `verticalCentred:true`?

Can you provide an isolated reproduction of the problem in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen?

**Comment by hijklmno** [comment]
Hi, thanks for your help.

I am not trying to add the class `fp-table` by myself. I noticed that the fullpage.js is adding `fp-table` and `fp-section` to each `<section>` element, except the first section. Only after adding this class back into the first section manually, does the weird transition thing not happen anymore. 

I will try to isolate in the jsfiddle you provided.

**Comment by hijklmno** [comment]
Hi alvaro,

I have resolved this issue by changing the sections color via javascript (eg. `sectionsColor`), instead of previously using css to change each section via `background-color`.

Thank you for your time. I will close this issue. Keep up the good work! (:
