### ISSUE TITLE
How to make data-menu-anchors transparent ? 

### ISSUE THREAD

**Issue by credo92** [alvarotrigo/fullPage.js#1521]
How to make data-menu-anchors transparent ? Can we animate it ? or apply some button transitions to it .. trying  but not able to do so.

Please reply@the earliest .

Vipul 
New Delhi, IN

**Comment by alvarotrigo** [comment]
Transparent data-anchors? I have no idea what are you trying to say with that. 
Can you elaborate it?

> Can we animate it ? 

Animate what?

**Comment by alvarotrigo** [comment]
Closed until a better explanation is provided.
