### ISSUE TITLE
Fullpane - Full Section Scrolling Not Working on Mobile

### ISSUE THREAD

**Issue by crivgil** [alvarotrigo/fullPage.js#1523]
I love this theme but the full section scrolling isn't working on mobile devices any idea how to fix it?

https://themify.me/demo/themes/fullpane/

**Comment by alvarotrigo** [comment]
I'm afraid this forum only treats fullpage.js problems and it has nothing to do with the theme you ask for.
You'd better ask the creators of the theme. 

Fullpage.js works as expected on mobile phones as you can see [in the demo page](http://alvarotrigo.com/fullPage/).
