### ISSUE TITLE
Transition CSS3 freeze in google Chrome  Windows

### ISSUE THREAD

**Issue by EvanDorlot** [alvarotrigo/fullPage.js#1524]
Hi there, 

First of all : a Huge thanks to this awesome plug-in ! I'm using it very often and never experienced any bug until the website I'm doing right now :)

I'm not 100% sure it's due to fullPage.js. I'm experiencing a very weird chrome (45 and 46 windows only) behaviour when I switch from the first to the second slide of my website. : The transitions "freeze" 80% of the time. When "CSS3" is "true" it goes instantly from the first to the second slide, but when "CSS3" is "false" the transition between the first and the second slide is playing but each other CSS3 transition in the page are instantly on their final stage. They are not playing.

You can take a look by yourself if you are on windows :

1. first you will need to login as the website is still under construction.  www.evandorlot.com/wp-login
Login : Guest - Pass: Luckyone

then, come back to the home page www.evandorlot.com

2. Sroll down, here's the bug. From the first to the second slide of the website, the transitions "freeze" they pop instantly to their final stage.

3. After pressing ctrl+f5 and trying again, sometime it work, sometime no... 

I'm working on this bug for more than a week now and don't find any solutions: 
I tried to disable all the TweenMax animations, then all the css3 animations that are not vital. I also disabled all my custom javascript except fullpage.js function without any configuration, I tried removing the image from the second slide, deleting the second slide, swapping the second slide with another, replacing the image, the text, deleting the diamond icon, deleting the menu on the bottom right corner, activating GPU acceleration by adding CSS3 "translateZ" to each elements that is animated on the first and second slide... Nothing fixed the bug.

The only way to make it working properly is to empty ALL the content from the second slide and leave the entire section empty. So I guess something cause the issue, but I really don't know what.

I know it's a long shot but if anyone has already experienced similar bug or has a suggestion to fix it. It will be very useful as I'm totally desperate :)

PS: I'm using the last version of Fullpage.js

**Comment by alvarotrigo** [comment]
Are you able to reproduce the issue in the [demo page](http://alvarotrigo.com/fullPage/) or any of the available examples?
Are you able to reproduce it in an isolated reproduction in jsfiddle or codepen with the same plugin initialisation?

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided. 
As per the comment [in stackoverflow](http://stackoverflow.com/questions/32673931/transition-css3-freeze-in-google-chrome-windows) it seems the issue is not with fullpage.js but with the frames your site renders per second.

> I just have checked the painting frames of your website site first to second slide it's hits huge. It's logging more than 60fps. Hopes that makes us to feel the animation is not happening.

**Comment by EvanDorlot** [comment]
Hi,
Yes, that's interesting, I'm going to investigate in this way. 
I'm also trying to reproduce the bug in stackoverflow if somehow the bug is not due to a FPS drop.
I'll keep this topic updated.
Thanks !
