### ISSUE TITLE
Initial height gap on small browser window

### ISSUE THREAD

**Issue by albhardy** [alvarotrigo/fullPage.js#1527]
Hi Alvaro,
Awesome plugin! I just noticed there is small gap when I first load the page on small browser window, (but will disappear once the the window is resized) on following examples:
- http://alvarotrigo.com/fullPage/examples/backgrounds.html
- http://alvarotrigo.com/fullPage/examples/autoHeight.html
- http://alvarotrigo.com/fullPage/examples/scrolling.html

![image](https://cloud.githubusercontent.com/assets/1732018/9988572/4681fa76-6084-11e5-873c-094df095d809.png)

To solve this, I temporarily use this approach:
```
afterRender: function() {
                $(window).trigger('resize');
            }
```
Perhaps there's a better way?

**Comment by alvarotrigo** [comment]
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1502
