### ISSUE TITLE
How to turn off centering position

### ISSUE THREAD

**Issue by archasek** [alvarotrigo/fullPage.js#1528]
Hi.

I use fullPage.js only for vertical dotted menu. I would like to turn centering off, when user scroll is between sections. How can I do it?

This is my actual code:

```

        jQuery('.container:first').fullpage({
            anchors: ['home-section', 'project-section'],
            navigation: true,
            navigationPosition: 'right',
            autoScrolling: false,
            controlArrows: false,
            verticalCentered: false,
            fitToSection: false,
            responsiveWidth: 801
        });
```

**Comment by alvarotrigo** [comment]
You would need to use CSS for it. 
Please ask in other place such as http://stackoverflow.com/

Fullpage.js doesn't provide a way to do it.

**Comment by archasek** [comment]
So Fullpage.js will ALWAYS try to scroll to one section it when I'm between sections?

**Comment by alvarotrigo** [comment]
I though you were speaking about the centering of the dotted menu.

If you are speaking about the fitting to the section, [you already created another topic for it.](https://github.com/alvarotrigo/fullPage.js/issues/1530)
