### ISSUE TITLE
Disable fullPage below specified resolution / window width OR a page

### ISSUE THREAD

**Issue by archasek** [alvarotrigo/fullPage.js#1529]
Hi.

I configured fullPage with `responsiveWidth` set to `801`. Unfortunately, below 801px in width, the plugin works normally, as above 801px. How can I turn it off then?

I would also disable the plugin from firing on all pages but homepage. How to do it?

This is my actual code:

```
        jQuery('.container:first').fullpage({
            anchors: ['home-section', 'project-section'],
            navigation: true,
            navigationPosition: 'right',
            autoScrolling: false,
            controlArrows: false,
            verticalCentered: false,
            fitToSection: false,
            responsiveWidth: 801
        });
```

**Comment by alvarotrigo** [comment]
The responsive option is not to turn it off.
Please read the documentation regarding the responsive options:

> **responsiveWidth:** (default 0) A normal scroll (autoScrolling:false) will be used under the defined width in pixels. A class fp-responsive is added to the plugin's container in case the user wants to use it for his own responsive CSS. For example, if set to 900, whenever the browser's width is less than 900 the plugin will scroll like a normal site.

> **responsiveHeight:** (default 0) A normal scroll (autoScrolling:false) will be used under the defined height in pixels. A class fp-responsive is added to the plugin's container in case the user wants to use it for his own responsive CSS. For example, if set to 900, whenever the browser's height is less than 900 the plugin will scroll like a normal site.
