### ISSUE TITLE
load image after show

### ISSUE THREAD

**Issue by Zarinia** [alvarotrigo/fullPage.js#153]
Hi,
How can i use load image like lazy load after image show
i used lazy load but not work correctly
please give me suggestion.
thanks

**Comment by alvarotrigo** [comment]
Lazy loading has been implemented in fullPage.js 2.6.6.
You can read more about it [here](https://github.com/alvarotrigo/fullPage.js#lazy-loading).

**Comment by thiru26** [comment]
i used full page js in my website. if i reloading my website it seems like this (https://abc.html/#sectionfour) .I want https://abc.html like this only after reloading is there any way to overcome this..
thanks,
thiru

**Comment by thisisfed** [comment]
@thiru26 

$("#fullpage").fullpage({
      lockAnchors: true
});

**Comment by thiru26** [comment]
its not working......
