### ISSUE TITLE
Postback problem for buttons within a fixed element

### ISSUE THREAD

**Issue by cziox** [alvarotrigo/fullPage.js#1531]
Hi,

I use the following Script:

    <script>
        $(document).ready(function () {
                    $('#fullpage').fullpage({
                        fixedElements: '#divFixedTopContent',
                        normalScrollElements: '#pnlMaster',
                        scrollOverflow: 'false',
                    });           
        });
    </script>

For the following HTML Code:

```html
<div class="fullpage-wrapper" style="height: 100%; position: relative; transform: translate3d(0px, 0px, 0px);" id="fullpage">
    <div id="divFixedTopContent" class="StartPage">
            <input name="HeaderPane1$ctl03$btnOpenLogin$btnOpenLogin_moImgBtn" id="HeaderPane1_ctl03_btnOpenLogin_btnOpenLogin_moImgBtn" class="hoverLoginButtonNotLogedIn oxButton_Image oxWebControlWrap" src="/oxEShop-Stutzer/includes/Layout/default/images/TransparentBG25x25.png" alt="Anmelden" type="image">
    </div>
</div>
```

If I use the script as discribed above, the btnOpenLogin.click event (code behind) doesn't work anymore. If I remove "fixedElements: '#divFixedTopContent'" the btnOpenLogin.click event works again.

P.S.: Thx for this cool plugin! Tried a few and this one is really awesome!

**Comment by alvarotrigo** [comment]
Can you please provide a reproduction in [jsiffle](http://jsfiddle.net/97tbk/418/) or codepen?

**Comment by cziox** [comment]
Actually its not possible to reproduce this problem in jsfiddle. Because it is a complete shop page (.net) with a lot of generated content and server side code as well.

I tried to create an example by shrinking the genereted html code down to the relevant stuff, to get you an idea about the structure:

https://jsfiddle.net/5k7s9yo7/4/

As you can see there is the button "HeaderPane1_ctl03_btnOpenLogin_btnOpenLogin_moImgBtn". As soon as I add the "fixedElements" parameter, the button doesn't work anymore. It should execute a code behind functions. I have the same effect for all buttons in the fixed div.

I don't know if this will help you?

**Comment by alvarotrigo** [comment]
Sorry I can not help you without an isolation of the problem and a reproduction of it I'm afraid.
I'll close the issue until a reproduction is provided.

**Comment by cziox** [comment]
Would it help you if I provice you the Link to the website where the problem occurs?

**Comment by alvarotrigo** [comment]
Nop. I need an isolated reproduction. That's why I ask for jsfiddle or codepen. 
That's the place where you can isolate the problem and prove its in fullpage.js and not in any external script.

**Comment by alvarotrigo** [comment]
No matter what technology you are using. You should always be able to reproduce a front end problem in jsfiddle or codepen.
It is HTML + JS + CSS. No more.

**Comment by cziox** [comment]
Finally I found the problem. The code line "$(options.fixedElements).appendTo($body);" moved my fixed header out of the form tag. Because of this the the buttons didn't work anymore...

Thx for your support...
