### ISSUE TITLE
How to disable "fitToSection" for all sections?

### ISSUE THREAD

**Issue by wingDeveloper** [alvarotrigo/fullPage.js#1535]
How to disable "fitToSection" for all sections?
---
fitToSection: false,
autoScrolling: false,
Still not disabled

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/1499

I'll solve it for the next release. 
Meanwhile you can easily solve it by just removing the line 863 from your fullpage.js script.

**Comment by wingDeveloper** [comment]
Thank you so much!!!
