### ISSUE TITLE
Question: 2 sections in one main section

### ISSUE THREAD

**Issue by DanDvoracek** [alvarotrigo/fullPage.js#1537]
Hi --

As I wrote in the title, I am looking for a way to have two scrollable sections inside one section.
Is there a way to achieve this?

I need the main section-scroll to snap like on this example:
http://alvarotrigo.com/fullPage/#3rdPage

However I would like the exact same behaviour inside one of the section. Is there any existing setting for that? I saw that I can enable the scroll inside the section but it is slightly different in my case.. I would like this scroll to snap to the bottom and then run a callback function.

Any tips/ideas?

Many thanks,

**Comment by alvarotrigo** [comment]
Not quite sure what you are asking for, but probably not :)

Sections are vertical.
Slides are horizontal.

You can not have two vertical sections inside a single section. It just doesn't make sense.

**Comment by DanDvoracek** [comment]
Well I tried to be explicit but it's maybe not enough. 

Basically the idea would be to have a fullpage element inside a section that is part of another fullpage element.. Does that make sense?

Thanks,
Dan

**Comment by alvarotrigo** [comment]
I'm not quite sure if you are just talking about slides instead. Because having a section within a section doesn't make any sense to me.

Maybe if you explain why you want to do that I will be able to understand your point of view and suggest an alternative.

**Comment by DanDvoracek** [comment]
I'm definitely not speaking about slides. I have understood what that is. I simply don't need to use slide in my case as everything has to happen vertically.

So here is another attempt to make it more clear. 
See this demo as a starting point: http://alvarotrigo.com/fullPage/

Basically I would need to detect the scroll INSIDE a section in order to set a callback and process some animations in this exact same section. 
The aim being that I would like to switch/extend the content of the section once the user scroll inside it.

However, if I do so in the same way as the demo, the browser would scroll to the next section instead of triggering my callback function. Does that make sense?

I really need the scroll behaviour like in the demo, but inside a section itself. Does that make sense? I'm not sure I can make it any clearer..

**Comment by alvarotrigo** [comment]
You can get the scrolling event and the direction of it by using the `onLeave` callback.

Then, [you can cancel the scroll before it takes place](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place) and do whatever you want instead. 

But of course, the animation you want to do, or whatever you have in mind, would have to be done by yourself.

**Comment by DanDvoracek** [comment]
Interesting. I will do some tests and see if it works for me. However, I am afraid that it will then completely disable the scroll for that section. But I may find a way to put it back.

Thanks for your guidance !

**Comment by alvarotrigo** [comment]
> However, I am afraid that it will then completely disable the scroll for that section. But I may find a way to put it back.

It will only disable it depending on the condition you use to `return false`.

**Comment by DanDvoracek** [comment]
Hi there!

So I'm coming back with my little problem.

I tried your suggestion of returning false on the onLeave callback.. However this stops the scroll in a way that (I think, maybe I missed something) it is impossible to enable it again (?).

I actually found another way of telling you what my problem is about.
This example is pretty much what I do: http://alvarotrigo.com/fullPage/#3rdPage

BUT I need to find a way to keep the same background for two sections. Does that make sense? 

Regarding your example, it would mean that once you get to the "Easy to use plugin" section (for example), the background color (the div) will remain fixed and the next section will slide on overlay and snap like it does for all the sections ... Is that clear? I can quickly make a drawing if you prefer..

Most importantly, is there a way to achieve this with you plugin / a workaround for this?

Many thanks,

Dan

**Comment by alvarotrigo** [comment]
> However this stops the scroll in a way that (I think, maybe I missed something) it is impossible to enable it again (?).

You can enable it again returning true whenever you you want as I said, for example:

```javascript
   $('#fullpage').fullpage({
        onLeave: function(index, nextIndex, direction){
            return $('#demo').hasClass('active');
        }
    });
```

> Most importantly, is there a way to achieve this with you plugin / a workaround for this?

There's probably a way, just make use of the callbacks and options the plugin provides.
You might also want to look into CSS in order to fix a background, although there might be some troubles with `css3:true` for that.

I would encourage you to ask in other place such as http://stackoverflow.com/ in which they might help you in this regard.

This forum in basically to treat fullpage.js issues, bugs or recommendations, but yours is a personal question regarding a personal problem.

**Comment by alvarotrigo** [comment]
Oh, and check the [backgroundsFixed.html example I provide with the plugin](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

If you still need help, [contact me](http://alvarotrigo.com/#contact-page) and I'll provide you with a quote.

**Comment by DanDvoracek** [comment]
I see. Interesting approach. I think I may be able to work something out by "syncing" the fixed background of a section with a changing body background at the right time, and play with the "hide-change-show" recipe ;)

Thanks for your help! It is greatly appreciated. As for my question here, I thought it could help someone else facing the same problematic, that's why I posted it here. Anyway, many thanks!

**Comment by alaalqadi** [comment]
Hello there guys, i wanted to know if there's a way to do scroll animation inside the sections ...
for example: on the 1st scroll background appears, on the 2nd scroll a paragraph appears and so on ...
is there a way to accomplish this with Fullpage.js ???
if yes please tell me how ... thanks in advance

**Comment by alvarotrigo** [comment]
@alaalqadi see [the callbacks2.html example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/callbacks2.html).
 
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
