### ISSUE TITLE
Background image not scaling properly on iOS

### ISSUE THREAD

**Issue by alucidwake** [alvarotrigo/fullPage.js#1538]
Hello,

Apparently this is a well known bug, but backgrounds on iOS scale to the body div and not screen size with size:cover. What effectively happens is the image gets rendered at full-scale, thus only showing the top-left corner of it, zoomed in (depending on size of image)

The solution that is often given (https://css-tricks.com/forums/topic/full-page-backgrounds-on-ios-background-size-cover/page/3/) is to make div fixed and size: 100% 100%, but with fullpage.js, if I want my second slide down to have a background image, that solution won't work.

I searched the web and this forum to see if anyone else had come across this problem, and I was surprised to not find anything.

Has anyone come across this problem before and may know of a solution?

The website I'm working on, for reference, is: http://nickaxel.com/foam/index_test.html

Thank you.

**Comment by alvarotrigo** [comment]
It doesn't seem to be a fullpage.js related problem.
Also, the topic is from 2012 and probably the bug doesn't exist in modern phones or iOS anymore. 

I can see [the background demo](http://alvarotrigo.com/fullPage/examples/backgrounds.html) as expected on my iPhone 5 with the latest iOS.

**Comment by alucidwake** [comment]
Hi Alvaro,

Sorry but I think this is a fullpage related issue. You're right, the background demo works, but the backgroundsFixed.html page you have in your examples folder (not hosted online) produces the problem I describe. The problem seems to be the relation between fullpage and the background-attachment: fixed; property?

**Comment by RobR8** [comment]
I have successfully used `background-attachment: local;` and it seems to work just as well, even though it is not technically what I want based on W3C's description.

I don't know if that fixes the issue with iOS, but it did fix my issue on Windows 7 Chrome/Firefox/IE 11

**Comment by alvarotrigo** [comment]
> The problem seems to be the relation between fullpage and the background-attachment: fixed; property?

Have you tried using `css3:false`? 
Let me know if it works for you.

**Comment by alucidwake** [comment]
css3:false doesn't fix the issue :/
