### ISSUE TITLE
Disable/Re-Enable scroll functionality?

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#154]
Quite self-explanatory. It would be nice to have a feature in which you can make a simple call to disable/enable the ability to scroll. I /might/ have found a workaround that works for me but the support for it would be nice nonetheless.

Thanks.

**Comment by zshahab91** [comment]
@alvarotrigo
Hi 
How to disable fullpage to another page?
I used ngx-fullpage of angular for home page but I do'nt want fullpage to another page

**Comment by alvarotrigo** [comment]
@zshahab91 I'm not familiar with ngx-fullpage.js.
I can only suggest you to:

- Not initialise fullPage.js in that new page
- Or if you can't do that, just destroy it using `$.fn.fullpage.destroy('all')`

**Comment by zshahab91** [comment]
when use destroy when reload page

ERROR TypeError: $.fn.fullpage.destroy is not a function
how to fix it?

**Comment by alvarotrigo** [comment]
Destroy works in the ngx website: http://meiblorn.github.io/ngx-fullpage/
Try running it on the console and you'll see you don't get the error. 
Probably the error is on your side, it seems it is not even detecting fullPage.js as if it was not being initialised.

**Comment by zshahab91** [comment]
​in my new page has not fullpage
how to check if have or not?
​

**Comment by alvarotrigo** [comment]
> how to check if have or not?

Executing `$.fn.fullpage` in the js console.

**Comment by zshahab91** [comment]
$ not work in angular 5

**Comment by alvarotrigo** [comment]
$ is just jQuery, a library you can include anywhere?
You'd better ask in some angular forum or in stackoverflow.com

**Comment by zshahab91** [comment]
import { Component, OnInit, OnDestroy } from '@angular/core';

export class HomeComponent implements OnInit {


  constructor(private fullpageService: MnFullpageService) {

  }

  ngOnInit() {}
  ngOnDestroy() {
    this.fullpageService.destroy('all');
  }

}

this solution work

**Comment by Nehul50** [comment]
full page js in mobile view navigation bar not click. if i remove  responsiveWidth: 1199 than work perfect what is solution in my code please tell me suggestion soon as possible.
<script type="text/javascript">
		var myFullpage = new fullpage('#fullpage', {
        anchors: ['Home', 'About', 'Skills', 'Services', 'Reviews', 'Team1, 'Contact'],
        menu: '#menu',
	navigation: true,
        slidesNavigation: true,
        lazyLoad: true,
        credits: {enabled: false},
        responsiveWidth: 1199,// this remove than work menu
        afterResponsive: function(isResponsive)	
        },
    });
	</script>

**Comment by alvarotrigo** [comment]
> full page js in mobile view navigation bar not click. if i remove responsiveWidth: 1199 than work perfect what is solution in my code please tell me suggestion soon as possible.

Update to the latest version 4.0.10
