### ISSUE TITLE
Issue on horizontal scrolling speed

### ISSUE THREAD

**Issue by br0k3n** [alvarotrigo/fullPage.js#1540]
Hi,

thanks for your plugin :)
I'm using your plugin to built a Wordpress theme, all works fine, but the auto scroll on horizontal slides change the timeout without any reason after some time on the page.

I add these lines:

```
afterLoad: function(anchorLink, index){
  setInterval(function () {
     $.fn.fullpage.moveSlideRight();
  }, 3000);
}
```

If you browse the page scrolling up and down some times you can see the horizontal scrolling spped (the timeout) changing.

Here's the link: http://goo.gl/uz4UIC

Thanks so much :)

**Comment by alvarotrigo** [comment]
Well, you are creating an interval every time a section loads, so you can end up having multiple intervals steeping each other.

This is a javascript question and it doesn't belong to this forum.
I'll close the issue.
