### ISSUE TITLE
Bug with anchors

### ISSUE THREAD

**Issue by redonditodericota** [alvarotrigo/fullPage.js#1541]
Hello. I have a website made with fullPage plugin and I found it has a little bug. This is what happens:

When somebody is navigating in the website and copies the URL ( Which may be looking something like http://www.myweb.com/#section_name ) and sends it to any other person, when the other person clicks on that URL and enters the website, it fails, the website does not display neither in the first section nor the hashed section. Is there any workaround for this? Some way to force the browser to wait until everything is loaded up before scrolling(via plugin) to the hashed section?

FYI: I saw other issue with a similar problem, he had the same id in sections than the hash. It is not my case, the url is myweb.com/#section_name and the html element id is `section_name-id`

Thank you very much Alvaro
Regards

**Comment by alvarotrigo** [comment]
> FYI: I saw other issue with a similar problem, he had the same id in sections than the hash. It is not my case, the url is myweb.com/#section_name and the html element id is section_name-id

You just answered yourself.
[The documentation says](https://github.com/alvarotrigo/fullPage.js):

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by redonditodericota** [comment]
I know that, I have read the whole documentation before asking this, but the anchors do not have the same value. The anchor href value is `section_name` and the ID element is `section_name-id`. (Per example, I have `<a href="#portfolio">` and the section is `<div class="section" id="portfolio-id">`) Is this wrong somehow? I have defined the `anchors` option in the initialization with the anchor values.

**Comment by alvarotrigo** [comment]
Sorry I missunderstood you then.
In any case, you would need to reproduct the problem and isolate it from any external CSS or Javascript file.

As you can see, the problem doesn't take place in [the demo pages](Added fp-auto-height for SCSS users #1496).
