### ISSUE TITLE
$.fn.fullpage.destroy('all') broken in 2.7.2 minified

### ISSUE THREAD

**Issue by aaroncolon** [alvarotrigo/fullPage.js#1546]
Hi Alvaro,

It seems the destroy('all') method is broken in the fullpage.js 2.7.2 minified version found here: #1545 

I am getting the following error in Chrome when attempting to invoke it:

```
jquery.fullPage.min.js:40 Uncaught ReferenceError: removeSlimScroll is not defined
```
with the following section of code identified in the console as causing the issue:

```
d(".fp-section, .fp-slide").each(function(){removeSlimScroll(d(this));d(this).removeClass("fp-table active")});h.addClass("fp-notransition");h.find(".fp-tableCell, .fp-slidesContainer, .fp-slides").each(function(){d(this).replaceWith(this.childNodes)});
```

**Comment by alvarotrigo** [comment]
Solved in the latest version 2.7.2.
