### ISSUE TITLE
fullPage 2.7.2 scrolling broken in IE 11 / Windows 8, IE 9 / Windows 7

### ISSUE THREAD

**Issue by aaroncolon** [alvarotrigo/fullPage.js#1547]
Scrolling does not advance to next / prev section / slide.

See demo here: http://codepen.io/alvarotrigo/pen/XbPNQv

Only tested running virtual machines via Virtual Box on OS X 10.10.5

**Comment by alvarotrigo** [comment]
Thanks for reporting it, that was a big bug I introduced yesterday. 
There's no horizontal detection for IE as far as I know. So scrolling horizontally with a trackpad in IE will scroll vertically I'm afraid.

I made a hot fix in the same version 2.7.2 to avoid problems with NPM. Please get the latest version under the same version number.
