### ISSUE TITLE
[critical] Second seciton is being always passed by while scrolling with anchors option enabled

### ISSUE THREAD

**Issue by Hast** [alvarotrigo/fullPage.js#1548]
When I scroll down from the first section, the script just passes by the second one. Whereas browser's address bar shows me the anchor which is applied to the second section. When I reach the end and start scrolling up, it starts to work.

It works from the beginning only if I remove "anchors" options from the plugin initialization.
Live example of the issue is here: http://test.magaz4.ru/betonova/test.html
Screencast: https://www.youtube.com/watch?v=c3iCgh7a5j4

```html
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <div id="fullpage">
        <div class="section" id="test1">
            test 1
        </div>
        <div class="section" id="test2">
            test 2
        </div>
        <div class="section" id="test3">
            test 3
        </div>
        <div class="section" id="test4">
            test 4
        </div>
    </div>
</body>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>

    <script type="text/javascript" src="js/jquery.fullPage.js"></script>

    <script type="text/javascript">
        $(document).ready(function() {
            var $fp = $('#fullpage');

            $fp.fullpage({
                anchors: [
                    'test1', 'test2', 'test3', 'test4'
                ]
            });
        });
    </script>
</html>
```

**Comment by alvarotrigo** [comment]
Read your Javascript console errors:

> fullPage: data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).

**Comment by Hast** [comment]
@alvarotrigo is such behavior documented anywhere?

**Comment by alvarotrigo** [comment]
It's in the documentation multiple times.
