### ISSUE TITLE
normalScrollElements seems to be selecting overzealously

### ISSUE THREAD

**Issue by milesgrover** [alvarotrigo/fullPage.js#1549]
I'm not sure if this is a bug or just an issue that could be fixed with documentation.

I am using both scrollOverflow: true and normalScrollElements so that certain slides with a lot of content will scroll through the content but not to other slides/sections (I have other navigation elements for getting to other slides). 

When I upgraded from 2.6.0 to 2.7.2, this functionality changed in a way I didn't expect. My site had been structured like this:

    <div id="fullpage">
        <div class="section">...</div>
        <div class="section">
            <div class="slide">...</div>
            <div class="slide slide-content">
                long scrolling content here
            </div>
        </div>
    </div>

I had `normalScrollElements` set to `.slide-content`.

In 2.7.2, that structure produced behavior where I could scroll from the first section to the second, but once I got to the second, scrolling stopped. When I went to the second slide in the second section (.slide-content), I still got the expected behavior (content scrolling, but locked so as not to scroll to other sections).

The way that I worked around the issue was to change the structure to this:

    <div id="fullpage">
        <div class="section">...</div>
        <div class="section">
            <div class="slide">...</div>
            <div class="slide">
                <div class="slide-content">
                    long scrolling content here
                </div>
            </div>
        </div>
    </div>

Once I did that, I could scroll between sections as desired, as well as having the `.slide-content` slides scroll through their content but not to other slides (as desired).

That leads me to think that setting `normalScrollElements` to `.slide-content` and having `.slide-content` on the same div as `.slide` caused the `normalScrollElements` functionality to apply to all the `.slide` divs. It didn't apply to the first section because the first section had no slides.

Again, this behavior was not happening when I was on 2.6.0.

**Comment by alvarotrigo** [comment]
You are not suppose to use `normalScrollElements` in any section or slide element. 

Check the change log in any case if you want to find out why. You might find the answer there:
https://github.com/alvarotrigo/fullPage.js/releases
