### ISSUE TITLE
Can't implement: Uncaught TypeError: $(...).fullpage is not a function

### ISSUE THREAD

**Issue by finchyz** [alvarotrigo/fullPage.js#1550]
Hello,
Sorry to be a bother  but I am trying to implement this onto my site http://www.zactech.co.uk/ but can't work out what I have done wrong (yes I know it will be staring me in the face). The inspector in chrome comes up with: Uncaught TypeError: $(...).fullpage is not a function 
Hope you can help.
Thanks,
Zac

**Comment by alvarotrigo** [comment]
Start with one of [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) as a base for your site.

This forum is to treat fullpage.js issues and not specific issues for each website trying to implement it.

**Comment by finchyz** [comment]
Sorry. Thank you for your help
