### ISSUE TITLE
scrollOverflow breaks verticalCentered

### ISSUE THREAD

**Issue by studio174** [alvarotrigo/fullPage.js#1551]
It seems when I set scrollOverflow to true vertical centering breaks unless I resize the browser or window.  I know this issue was reported and apparently fixed before, but that doesn't seem to be the case with me.

http://gfx.websiteprogress.ca/

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the problem. Ideally in jsfiddle or codepen.

[I was not able to reproduce it](http://jsfiddle.net/97tbk/868/)

**Comment by studio174** [comment]
I was able to resolve the matter, it turned out to be an issue with the framework I was using.  Thanks for your help!

Cheers!
