### ISSUE TITLE
Scrolling not working on Android 5 and iOS 8 and 9.

### ISSUE THREAD

**Issue by jeffisowens** [alvarotrigo/fullPage.js#1553]
This includes http://alvarotrigo.com/fullPage/ - I can't get this to scroll on multiple iOS or Android devices. Using the menu works, but touch scrolling does not.

**Comment by alvarotrigo** [comment]
That's a big bug... I'll check it now.

**Comment by alvarotrigo** [comment]
Solved in 2.7.3.
Thanks again for reporting it!

**Comment by CoryWA** [comment]
Thank you so much! That was quick.  I subbed it when you marked it.  25 mins not bad.

**Comment by jeffisowens** [comment]
Awesome. Great response time. I'll test again in my morning.
