### ISSUE TITLE
how to prevent continuous scrolling during one touch?

### ISSUE THREAD

**Issue by caohongtao** [alvarotrigo/fullPage.js#1554]
When I slide on screen with my finger, current section scroll normally.
But if I continue pressing the screen and not to lift, more sections will continue scrolling.

I want an effect that only one section scrolled during one touch .
In other words，I want to capture the touchend event but not the touchmove event.

How can I implement in an easy way?
I come up with an idea that stop touch event detecting in the callback onLeave(), but I don't know how to implement it.

**Comment by alvarotrigo** [comment]
I don't understand your problem.
Can you please tell us which initialisation are you using for fullpage.js?

The [demo page](http://alvarotrigo.com/fullPage/) scroll on swipe one by one as it is suppose to do.

**Comment by caohongtao** [comment]
Thank you for your patience.
This is my initialisation：

```javascript
$('#fullpage').fullpage({
            anchors:['intro', 'ppt', 'milestones', 'members'],
            scrollOverflow: true,
            navigation: true,
            continuousVertical: true,
            loopHorizontal: false,
            scrollingSpeed: 1000,
 });
```

**Comment by alvarotrigo** [comment]
So, you are using `autoScrolling:true` as that's the default value.
No scrollbar `scrollBar:false`.

It should be working as expected.
Which browser are you using and which Phone and OS ?

**Comment by caohongtao** [comment]
Yes, I'm using `autoScrolling:true` and  `scrollBar:false`.
And this issue is not  about scrollOverflow. It's about scroll over different sections.

I do swiping on a mobile. If I swipe down and my finger not to leave the screen. More than one section will auto scroll up. But I want only the next section scrolled, then  stop scrolling until I put up my finger and swap the screen again.

**Comment by alvarotrigo** [comment]
I see what you mean. And nop, the plugin doesn't provide a way to deal with it I'm afraid. 
I'll consider it for a future. 

If you really need it, [contact me](http://alvarotrigo.com/#contact-page) for a customization.

**Comment by yingyuk** [comment]
same issues

**Comment by alvarotrigo** [comment]
@yingyuk try the [Drag And Move extension instead](http://alvarotrigo.com/fullPage/extensions/drag-and-move.html). It is a much precise touch feature.

**Comment by abdulaziz65** [comment]
@caohongtao  just slow down the scrolling speed with
scrollingSpeed: 1000, or 2000  in initialization.
it will also solve this issue

**Comment by abdulaziz65** [comment]
slowing down the speed of scrolling with scrollingSpeed: 1000, or 2000 in initialization is also a solution that can be used here. It will fix the issue hopefully. 
Worked for me:)
