### ISSUE TITLE
fullPage does not work on mobile

### ISSUE THREAD

**Issue by leongg** [alvarotrigo/fullPage.js#1557]
Hi I updated the js from Version: 2.6.7.1  to 2.7.2 because the transition between each #section was not that smooth on chrome.

Now the problem that I have is that in smart phones is not working the scroll between each section.

The structure is like this:
 
#fullpage
     #section0
     #section1
     #section2

And the js:

$(document).ready(function() {
         $('#fullpage').fullpage({
            scrollOverflow: true,
         });
});

You can see it in http://polisofia.com/ 

Right now, I'm trying to do this on the js but still not working (on my local environment):

$(document).ready(function() {
        if(screen.width < 480) { 
          $('#fullpage').fullpage({
            scrollOverflow: true,
            allowPageScroll: true,            
            scrollBar:false,
            touchSensitivity: 6,            
            autoScrolling:false,
           });
          return;
          } else {
          $('#fullpage').fullpage({
            scrollOverflow: true,
            allowPageScroll: true,
           });
          }
         
      });

Thanks if someone can point me what I'm doing wrong or how to fix it.. I know I can disable on mobile but is not what I want. 

Thanks again

**Comment by alvarotrigo** [comment]
Get 2.7.3

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/1553

**Comment by leongg** [comment]
Thanks!! I didn't check for the update because yesterday I did it. 

Great work!
