### ISSUE TITLE
Build script for compilation and compressing of SCSS, CSS and JS files

### ISSUE THREAD

**Issue by d13** [alvarotrigo/fullPage.js#1558]
Providing a build process will ensure parity in the compilation and compressing of files.

I have a working version of this on my fork: https://github.com/d13/fullPage.js

This also addresses #1096

Thanks and keep up the great work!

**Comment by alvarotrigo** [comment]
Sounds good to me!
I'm not familiarized with gulp, but feel free to commit the pull request.

**Comment by alvarotrigo** [comment]
Merged here: https://github.com/alvarotrigo/fullPage.js/pull/1570
