### ISSUE TITLE
fittosection gets activated after using menu / navs

### ISSUE THREAD

**Issue by hyperglow** [alvarotrigo/fullPage.js#1561]
Hey there,

I am not able to deactivate fittosection functionality. The page always scrolls to the anchor automatically. Any ideas?
I am using fullPage 2.6.6.

here is my code:

$('#fullpage').fullpage({
fitToSection:false,
autoScrolling:false,
anchors: ['site1','site2','site1'],				
menu: '#menu',
controlArrows: false,
slidesNavigation: true,
slidesNavPosition: 'bottom',
afterRender: function () {
            setInterval(function () {
                $.fn.fullpage.moveSlideRight();
            }, 5000);
        },
scrollBar: true,
lockAnchors: false
});

**Comment by hyperglow** [comment]
Ok, i see.
It only works in 2.7.2. Solved it by upgrading! Thanks for the grat script!

**Comment by alvarotrigo** [comment]
Working in 2.7.3
http://jsfiddle.net/97tbk/870/

**Comment by hyperglow** [comment]
Thanks for your answer.
I see, but it gets reactivated when using the menue. Any ideas on this?

**Comment by alvarotrigo** [comment]
Right, that's a bug, I'll reopen the issue and change its title.

**Comment by alvarotrigo** [comment]
Fixed in 2.7.4.
