### ISSUE TITLE
Adding class to body when responsiveHeight is triggered

### ISSUE THREAD

**Issue by netm** [alvarotrigo/fullPage.js#1562]
I freakin love fullpage.

Does anybody know an easy way to add a class to to the body tag when responsiveHeight is triggered? My goal is to have a responsive class in body indicating if fullpage is operating or not. At the moment I have the 'fp-viewing class' in body but it stays there on window resize to less than what responsiveHeight is set to.

Many thanks :-)

**Comment by alvarotrigo** [comment]
The class `fp-responsive` is added to the fullpage.js wrapper used to initialize fullpage.js

**Comment by netm** [comment]
Thank you! Should it also remove on changing height of viewport automatically? If I drag my window small fp-responsive appears but when making it larger again it stays.

**Comment by alvarotrigo** [comment]
I'm afraid I can not reproduce it in [the example page](http://alvarotrigo.com/fullPage/examples/responsive.html).
It will always get removed when turning responsive off as you can check [in the code](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L454).

**Comment by netm** [comment]
Hiya,

I think there may be a bug with responsiveHeight. If I take the [example page](http://alvarotrigo.com/fullPage/examples/responsive.html#firstPage) and change 

    //responsiveWidth: 900
    responsiveHeight: 700

Then make the window smaller in height than 700 the responsiveness works but when I drag it taller than 700 it doesn't bring back the menu etc as it does with responsiveWidth.

:-)

**Comment by alvarotrigo** [comment]
Right, seems like a bug yep. Can you please open a new issue for it?
