### ISSUE TITLE
animateAnchor implementation

### ISSUE THREAD

**Issue by GoncaloJsf** [alvarotrigo/fullPage.js#1563]
First of all my sincere compliments to you for putting together this fantastic plugin!

I am having problems in using the option animateAnchor. If I make use of animateAnchor:false I get stuck on the main page (1st section) and cannot scroll down. What can I do to overcome this?

Can you refer to an implementation in which this option (animateAnchor) is working such that I can see the final result.

Thank you @alvarotrigo

**Comment by alvarotrigo** [comment]
I can not reproduce your issue.
Could you please provide your fullpage.js initialization so I can try to reproduce it?

Are you using the latest fullpage.js verison 2.7.3?

**Comment by GoncaloJsf** [comment]
Alvaro, thank you for your help! We think we have solved the problem. When trying to set up the implementation in order to reproduce the exact problem, we detected an error with another plugin that was affecting the page behaviour. It seems that for the moment everything is working with fullPage.
Keep up the great work!
