### ISSUE TITLE
onSlideLeave with scrollBar visible breaks

### ISSUE THREAD

**Issue by paul-blundell** [alvarotrigo/fullPage.js#1565]
Please see this: http://codepen.io/anon/pen/EVZMvB

When `scrollBar` is set to true the function `onSlideLeave` is called the first time but then after you scroll a bit and go back it is never called again.

Any ideas why that might be? I need to run a function every time the slide changes.

**Comment by alvarotrigo** [comment]
Duplicated of: https://github.com/alvarotrigo/fullPage.js/issues/1556
