### ISSUE TITLE
responsiveWidth not working on iPhone

### ISSUE THREAD

**Issue by kimber-no-ly** [alvarotrigo/fullPage.js#1566]
hello,

i'm trying to use the responsiveWidth option to resume normal scrolling when viewing my site on a mobile device. i've been referencing the responsive width demo you've included. i've found that it works as it should when the normal browser size is less than the value inputted, however when i view it on an iphone or developer tools device preview it returns to the auto scrolling. when i apply those options to my own site i get the same result.

is there something i'm missing?
thanks,
kimber

**Comment by alvarotrigo** [comment]
It all depends on the resolution you are talking about. 
The Chrome mobile developer tools have also different resolutions. Take a look at them.

**Comment by alvarotrigo** [comment]
My mistake. There's something wrong. You are right.

**Comment by alvarotrigo** [comment]
Ok I've checked it again and it is working properly on the phones. 
Phones (any iPhone even iPhone 3, have 980pixels width, and the demo breaks at 900).

Regarding the problem with the developer tools, no matter how much you expand or contract the window size in Chrome mobile simulator, it is always reporting 980 pixels width.

**Comment by alvarotrigo** [comment]
You can check it in this other demo:
http://alvarotrigo.com/fullPage/ie/examples/responsiveWidth.html#firstPage

**Comment by alvarotrigo** [comment]
I've updated the example so it turns to normal scrolling at 1100px instead of 900:
http://alvarotrigo.com/fullPage/examples/responsive.html
