### ISSUE TITLE
Bug with responsiveHeight

### ISSUE THREAD

**Issue by netm** [alvarotrigo/fullPage.js#1567]
I think there may be a bug with responsiveHeight:

    responsiveHeight: 700

Then make the window smaller in height than 700 the responsiveness works but when I drag it taller than 700 it doesn't reinstate the menu etc as it does with responsiveWidth.

:-)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by alvarotrigo** [comment]
Fixed in 2.7.4.
