### ISSUE TITLE
Bug: #fullpage container do not translate on Safari 9.0 beetween page 0 & 1

### ISSUE THREAD

**Issue by matissev** [alvarotrigo/fullPage.js#1568]
Hello,
I think there is a strange thing going on between pages 0 and 1 on the new safari 9.0 : The #fullpage container is sometimes not translated. I tested it in Firefox 40.0.3, Safari 8.0.8, Chrome 45.0 and Opera 32.0 and did not notice the bug.

Here is my fullpage config : 
```javascript
verticalCentered: false,
loopTop: false,
loopBottom: false,
scrollBar: false,
fitToSection: false,
css3: true,
recordHistory: false,
autoScrolling: true,
fixedElements: nav,
```

By the way, thank's for your plugin, it's really great!

**Comment by alvarotrigo** [comment]
I'm not able to reproduce your issue on the [demo page](http://alvarotrigo.com/fullPage/) under the same environment. 

Do you see the bug in the demo page?

**Comment by alvarotrigo** [comment]
Neither was I able to reproduce it in [this fiddle](http://jsfiddle.net/97tbk/874/) with your same initialization.

**Comment by matissev** [comment]
You are right, it works for me too. I must have some code blocking the update. Sorry about that, my bad...
