### ISSUE TITLE
Mobile Browser Header AutoHide Not Working 

### ISSUE THREAD

**Issue by arj-196** [alvarotrigo/fullPage.js#1569]
On mobile browsers when you scroll down the header auto hides itself to give more space to view the content. But with fullpage.js it is not working. Could it be because the scrolling is "artificially" done?

![screenshot_2015-10-02-21-51-03](https://cloud.githubusercontent.com/assets/10669206/10256539/3abc4210-6952-11e5-9080-e0009ca7058d.png)

As in the picture above you can see, scrolling does not autohide the header. This is important for me because my fullpage implementation is a "gallery" where each page is an image. So it is important that the header is hidden to have a fullscreen effect. 

How could i make this work?

**Comment by alvarotrigo** [comment]
> On mobile browsers when you scroll down the header auto hides itself to give more space to view the content.

On some.

> Could it be because the scrolling is "artificially" done?

Try not using anchor or using `recordHistory:false`.

In any case, there's nothing we can do to deal with that. That depends on each browser and we have no access to the address bar controls.

**Comment by alvarotrigo** [comment]
> As in the picture above you can see, scrolling does not autohide the header. This is important for me because my fullpage implementation is a "gallery" where each page is an image. So it is important that the header is hidden to have a fullscreen effect.

I'm afraid you won't have your ideal effect in many other browsers, or Operative Systems.

**Comment by arj-196** [comment]
@alvarotrigo ok thank you, i will try the options you suggested.
