### ISSUE TITLE
not working proper animation  in scrolling slider

### ISSUE THREAD

**Issue by rahi4u** [alvarotrigo/fullPage.js#1572]
plz my animation not work it properly plz checked it
![sorcecode](https://cloud.githubusercontent.com/assets/14973444/10278398/a7ca2c62-6b7a-11e5-8e33-57addab00d8a.gif)

**Comment by alvarotrigo** [comment]
Again, you'll have to be more specific with your issue. I have no time to read your whole code.

**Comment by rahi4u** [comment]
if you not understand my problem than i send u link

**Comment by rahi4u** [comment]
my an

**Comment by alvarotrigo** [comment]
You just have to explain it with your own words.
