### ISSUE TITLE
not working proper animation on click and scroll

### ISSUE THREAD

**Issue by rahi4u** [alvarotrigo/fullPage.js#1573]
my problem is animation not proper work on click and scroll because FP.setScrollingSpeed

**Comment by alvarotrigo** [comment]
Sorry I can't help you because I can not understand your problem. 
Please stop opening new issues and just respond to the ones you created. 

**Otherwise I will ban you from the forum.**

**Comment by rahi4u** [comment]
ok sorry i what i do plz help me dear sir

**Comment by alvarotrigo** [comment]
As i said.
Please explain with your own words your problem. Starting with the scenario you are working on, what you want to achieve, what initialization you are using, what libraries are you using, what animations you are talking about... and ideally, you should reproduce your issue in jsfiddle or codepen. 

This should be at least more than 2 lines of your own words...

**Comment by rahi4u** [comment]
OK sir thanks to help me
On 5 Oct 2015 17:02, "Álvaro" <notifications@github.com> wrote:
>
> As i said.
> Please explain with your own words your problem. Starting with the
scenario you are working on, what you want to achieve, what initialization
you are using, what libraries are you using, what animations you are
talking about... and ideally, you should reproduce your issue in jsfiddle
or codepen.
