### ISSUE TITLE
Touch devices not swiping 

### ISSUE THREAD

**Issue by peterhintondesign** [alvarotrigo/fullPage.js#1574]
Firstly, thanks for a great plugin! It works perfectly for my project with just one issue; the swipe/scroll isn't working on touch devices.

- Link: http://www.peterhintondesign.co.uk/work/v9a/about.html
- With the responsiveWidth setting this is only an issue on iPad currently. However when I removed the responsiveWidth setting to test touchswipe on iPhone it didn't work on the iPhone either.

	$('#sections-plugin-container').fullpage({
		navigation: true,
		navigationPosition: 'right',
		responsiveWidth: 900,
		scrollingSpeed: 750,
		touchSensitivity: 5,
		onLeave: function(index, nextIndex, direction){
			$('.seperator').removeClass('anim-seperator');
			setTimeout(function(){
				$('.seperator').addClass('anim-seperator');
			}, 150);			
		}					
	});

As far as I can see I'm not missing anything. Any thoughts?

**Comment by alvarotrigo** [comment]
Use the latest version 2.7.4

**Comment by peterhintondesign** [comment]
Been working on this for a few weeks and didn't realise you'd updated the JS yesterday.

Huge thanks, keep up the good work :).
