### ISSUE TITLE
Header and footer issues

### ISSUE THREAD

**Issue by lecollective** [alvarotrigo/fullPage.js#1576]
I'm unsure if i'm completely missing something here as I can see from the documentation you added paddingTop a while back to solve this issue.

But it's not working for me. I'm assuming this is due to my position absolute divs?

Do you have a work around?

Loving this JS by the way!

http://jsfiddle.net/lecollective/o4xhgepw/2/

**Comment by alvarotrigo** [comment]
Add this style:

```css
.fp-tableCell{
    position:relative;
}
```

**Comment by lecollective** [comment]
That's great! Thank you!
