### ISSUE TITLE
fitToSection 2.7.4

### ISSUE THREAD

**Issue by sanserve91** [alvarotrigo/fullPage.js#1577]
Hi,
I've been using the last release and I found that even if I don't initialize fullpage in my main.js, the fitToSection is still running, in mobile version I don't want to use fullpage, and also I don't want the fitToSection feature to be executed. Thanks, the rest seems to work well.

**Comment by alvarotrigo** [comment]
> even if I don't initialize fullpage in my main.js, the fitToSection is still running

I'm afraid that's not possible. fitToSection can not exist if the plugin is not initialised. 

You would have to provide more details of your issue such as your current initialisation and ideally a reproduction in [this jsfiddle](http://jsfiddle.net/97tbk/418/)

**Comment by sanserve91** [comment]
Yes that is true, it was a browser-sync plugin issue, thank you. It is working all fine, I will keep testing.
