### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by strigga** [alvarotrigo/fullPage.js#1579]
I have a problem with the responsive option.
in the view below responsiveWidth, the sections are correct (bigger than window height), but if i scroll down, it scrolls automatically to the beginning of this section.
How to disable that?

**Comment by alvarotrigo** [comment]
Make sure you use the latest version 2.7.4.
i was not able to reproduce your issue here: http://jsfiddle.net/97tbk/883/

I'll close the issue until a reproduction is provided.
