### ISSUE TITLE
Video on slide.... why this happens?

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/fullPage.js#1580]
Hey Alvaro! How's going? hope ok

Look, I was trying to make the video runs as background (as your example) but in the first slide. But, I don't know how neither why, the video is zoomed and it is running in all slides, even if the video code is set only for the 1st slide.... mind to take a look on it?

Here is a codepen to check it out - http://codepen.io/tofanelli/pen/jbwEJJ

Cheers =)

**Comment by alvarotrigo** [comment]
Its a CSS issue, not a fullpage.js one:
Use:
```
.slide{
  position:relative;
}
```

**Comment by tofanelli** [comment]
Awesome!! 

Thanks very much! =)

PS: this might be included by default to avoid silly questions like this in a new version if you pleased to =)


Cheers =D

**Comment by alvarotrigo** [comment]
> PS: this might be included by default to avoid silly questions like this in a new version if you pleased to =)

Some people might not be interested in having the relative position in the slide. 
That's a matter of design.

**Comment by tofanelli** [comment]
swell then....

thanks very much anyway for so fast reply and help =D
