### ISSUE TITLE
slimScroll doesn't get destroyed on destroy();

### ISSUE THREAD

**Issue by oliverfarrell** [alvarotrigo/fullPage.js#1582]
I'm using the script to add a slider to the top of a page. I'm using the `scrollOverflow` method to ensure the content in the last slide is entirely scrollable as this will be the main website content. Think of the slider as being an intro to the website that when finished scrolls to the main website that can then we navigated as normal.

I'm using the `destroy` method to remove the slider when on the last slide with the intention of the natural browser scrolling to be reinstated – the scrolling that is applied by the script to slides doesn't quite match the natural scrolling of the browser (seems a bit too quick in comparison to a normal page).

In doing this however, the scrolling is disabled completely when destroying the slider. I've knocked up a quick example that hopefully shows what I'm trying to do better than I can explain it: https://jsfiddle.net/yhn9x16v/

I've tested this is Latest Chrome, Firefox and Safari – all results are the same.

You'll notice I'm also using the `onLeave` callback rather than `afterSlideLoad` which I assume would negate the need for the `setTimeout` however I can't seem to get that to work. It looks like that particular callback isn't working? It's quite possible that I'm doing something wrong.

Awesome plugin by the way!

Thanks!

**Comment by alvarotrigo** [comment]
Yep, looks like slimScroll doesn't get destroyed. 

In your case you have it easy, just remove `scrollOverflow:true`. It makes no sense if you are planning to destroy the plugin.

I'll mark it as a bug in any case.

**Comment by oliverfarrell** [comment]
Ah! Great – that's sorted it. Thanks for that :+1:

**Comment by alvarotrigo** [comment]
This has been fixed on the `dev` branch in [this commit ](https://github.com/alvarotrigo/fullPage.js/commit/fdae83074d321c47cb79784d11052890b6a54413). It will be added in the next release.

**Comment by sean-stanley** [comment]
Progress on this being merged to next release?

**Comment by alvarotrigo** [comment]
It was already merged in 2.7.6.
Next release (2.8.0) will get rid of slimScroll in favor of iScroll.js

**Comment by sean-stanley** [comment]
Thanks! Good to know. Awesome package btw. I thought I had this issue but then I found the destroy('all') method in the readme and was all good just using that.

**Comment by alvarotrigo** [comment]
Fixed in 2.8.0.
