### ISSUE TITLE
Chain moving slide after moving section on scroll

### ISSUE THREAD

**Issue by lambdaka** [alvarotrigo/fullPage.js#1586]
Hi, 
thanks for this great plugin !
I'm using it everytrime I can !

I would like to move a slide by scrolling after moving a section.

I got a slider in my third section and I would like to be able to move to the second slide by using my mouse wheel. And after the second (and last slide) the mouse whell will make move to the next section.
I only achieve to move slide by clicking on the arrow or I achieve to automaticly move slides on afterload.

Do you have a clue..?
Found some infos on a forum but no luck   :

$('#fullpage').on('mousewheel', function(event) {
       if (event.deltaY > 0){$.fn.fullpage.moveSlideRight();}
       else{$.fn.fullpage.moveSlideLeft();}
});
https://github.com/jquery/jquery-mousewheel

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/316

Short answer: fullpage.js doesn't provide it. You'll have to do it yourself or contact me [for a customisation](http://alvarotrigo.com/#contact-page).

**Comment by lambdaka** [comment]
‎I just send you an email through your link for customisation.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        De: ÁlvaroEnvoyé: vendredi 9 octobre 2015 22:55À: alvarotrigo/fullPage.jsRépondre à: alvarotrigo/fullPage.jsCc: lambdakaObjet: Re: [fullPage.js] Chain moving slide after moving section on scroll (#1586)Duplicated of #316

Short answer: fullpage.js doesn't provide it. You'll have to do it yourself or contact me for a customisation. 

—Reply to this email directly or view it on GitHub.
