### ISSUE TITLE
whatever I write inside "onleave" and "after load" dont work

### ISSUE THREAD

**Issue by shabinmp** [alvarotrigo/fullPage.js#1590]
Hello alvaro,

I'm using your script on a project I'm working on. IT works fine here
http://flamboyamedia.com/demo/pnkids/site/
Then I converted that to wordpress. 
http://flamboyamedia.com/demo/pnkids/wp

There the full page works, but, whatever I write inside "onleave" and "after load" dont work. "afterload" actually works once and then it doesnt. Can you have a look?

To test I'm only using the following lines in the events section 

        //events
        onLeave: function(index, nextIndex, direction){
			alert("left" + index);
		 },
        afterLoad: function(anchorLink, index){
			alert("loaded" + index);
		 },
        afterRender: function(){},
        afterResize: function(){}

**Comment by alvarotrigo** [comment]
It seems a problem in your side and not in fullpage.js. 
I can not help you with it as your problem is in the implementation in wordpress. You'd probably want to ask in some wordpress forum.

**Comment by alvarotrigo** [comment]
Also, I am getting the alerts in Chrome in your lat link.

**Comment by shabinmp** [comment]
Hey, I just made scrollBar: false and it works perfect. Any idea?

**Comment by alvarotrigo** [comment]
Download the latest version 2.7.4.
