### ISSUE TITLE
Fullpage.js : Ipad|Android tablets portrait mode when address bar to hide.  how to fit height in full page window height.

### ISSUE THREAD

**Issue by prakashsam** [alvarotrigo/fullPage.js#1591]
Fullpage.js : when a user scrolls down the pages in ipad|Android tablets portrait mode and causes the address bar to hide. that time 1st full page appear but 2nd page some 200 px also appear. how to fit height in full page.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/896
