### ISSUE TITLE
Menu Links not scrolling to specific page section

### ISSUE THREAD

**Issue by ajmaurya99** [alvarotrigo/fullPage.js#1592]
This is my Navigation Structure - https://jsfiddle.net/ajmaurya/psdcbbo4/1/ 
So when i am on the Discover page -  and then when i click to buyers guide sub menu, my page does not scroll to that section it just loads the page. 
I want this type of effects.  http://alvarotrigo.com/fullPage/#secondPage/2 

i am not able to figure out, what i did wrong?

**Comment by alvarotrigo** [comment]
You are not even using fullpage.js in the jsfiddle you provided.

**Comment by alvarotrigo** [comment]
You can find tens of examples within the plugin files: 
https://github.com/alvarotrigo/fullPage.js/tree/master/examples

**Comment by ajmaurya99** [comment]
Issue resolved.  Sorry My bad,  i was using the older version of Full Page Js.
This helped me.

https://github.com/alvarotrigo/fullPage.js/issues/555
