### ISSUE TITLE
Slides nav to align left 

### ISSUE THREAD

**Issue by dsiglin** [alvarotrigo/fullPage.js#1593]
Hi, currently it appears slidesNav (horizontal dots) is hard coded to center itself off the middle dot. When I added "left: 21px;" to ".fp-slidesNav.bottom" the dots moved left but it was the center of the nav dots that was 21px from the window edge and so half of the dots were lost off the left edge of the screen. Is it possible to have the nav dots align left? Or is that not possible currently? I hope this made sense as to what I'm asking, thanks!

**Comment by alvarotrigo** [comment]
It's not possible. You'll have to do it with your own CSS by overriding the styles applied to `.fp-slidesNav` and its childs.

**Comment by dsiglin** [comment]
I tried with CSS by changing ".fp-slidesNav.bottom" to include "left: 21px;" but that runs into the problem of the center of the slidesNav being moved to 21px from left. Is there something going on with the javascript that forces the SlidesNav to be centered off the middle dot/area? I can't seem to find anything CSS related which forces this to do what I want. Thanks for your help.

**Comment by alvarotrigo** [comment]
I'm afraid this is not the best place to ask for CSS question. Try in other place such as stackoverflow.com.

**Comment by dsiglin** [comment]
Yes sorry, I'm not asking about general CSS questions. I know this is a place just for discussing fullpage.js, what I was asking is have you, in the javascript, made the dots of slidesNav to be centered around eachother? If yes then I at least know there's nothing I can do. If not then I know I can change it with CSS so they extend to the right of the first nav dot.

**Comment by alvarotrigo** [comment]
> If yes then I at least know there's nothing I can do. If not then I know I can change it with CSS so they extend to the right of the first nav dot.

Everything can be changed with CSS. Inline styles can be replaced by using `!important`. So you don't need to know anything else that what you can examine in your site by using any DOM inspector.

**Comment by dsiglin** [comment]
Ok, thanks, just wanted to know if my attempts were going to be in vain. If I get it figured out I'll post the changes here in case anyone else wants to have the dots align left.

**Comment by dsiglin** [comment]
Figured it out. However, something is dynamically creating a negative margin-left. The margin-left of .fp-slidesNav changed based on how many nav dots there are.

So, if anyone reading this wants nav dots that align left you should do the following:
.fp-slidesNav{
    position: absolute;
    z-index: 4;
    left: 50%;
    opacity: 1;
    margin-left: 0px !important;
}

**Comment by alvarotrigo** [comment]
Won't be implemented. 
Dealing with CSS is the way to go for it.
