### ISSUE TITLE
Slides not working when using `fp-auto-height` and `responsiveWidth` together. 

### ISSUE THREAD

**Issue by strigga** [alvarotrigo/fullPage.js#1594]
I have set responsiveWidth so it scrolls normal on mobile devices. But the horizontal slider does not work.

Maybe the problem is:
i have set it do fp-auto-height

Does it not work then?

**Comment by alvarotrigo** [comment]
> Maybe the problem is:
> i have set it do fp-auto-height

That's why. 

[Reproduction online](http://jsfiddle.net/imac/97tbk/890/)

**Comment by alvarotrigo** [comment]
It has been solved in the `dev` branch: https://github.com/alvarotrigo/fullPage.js/tree/dev

**Comment by alvarotrigo** [comment]
Solved in 2.7.5.
