### ISSUE TITLE
Not able to scroll to auto height section at bottom

### ISSUE THREAD

**Issue by MariusRumpf** [alvarotrigo/fullPage.js#1595]
When putting a auto-height section at the bottom of all sections the container can be scrolled to but will be scrolled up to section before again.

Tested with version 2.7.4.
https://jsfiddle.net/f4m48vbu/1/

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/1489

Short answer: don't use `scrollBa:true`. Othewise you'll have to wait for a future release that solves the problem or [ask for an urgent request](http://alvarotrigo.com/#contact-page).

**Comment by MariusRumpf** [comment]
Thanks a lot, need `scrollBar: true` for parallax effects, but will see what I can do about it.
