### ISSUE TITLE
Fire top onLeave direction event for the first section 

### ISSUE THREAD

**Issue by julianfox** [alvarotrigo/fullPage.js#1597]
Hello,
I need to fire an animation before to leave the first section, i already managed it with the onLeave callback but i would like to launch again this animation when the user scroll top in the first section.

There is a way to fire the onLeave callback for the top direction on the first section ? or just detect the direction ?

For example this website use the same can of animation in the first section: http://www.newjumoconcept.com/en

Thanks in advance ! And yes awesome plugin !

**Comment by alvarotrigo** [comment]
The callback `onLeave` provides you with the direction.
I don't know what's your issue.

**Comment by alvarotrigo** [comment]
fullpage.js doesn't provide any way of mouse wheel detection. But you can always listen the event by yourself by using jQuery.

**Comment by julianfox** [comment]
Ok perfect, thanks for your response :-)
