### ISSUE TITLE
Naming slides?

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/fullPage.js#1598]
Hey Alvaro!

How's going? Hope ok...

This is not an issue.... is just a question.... 

Look... i was wondering.... as I can name my anchors to shown on URL.... can I name slides as well?

When i go to the second slide, the url changes to "slides/2"". can I change this "number" to a name i want as the anchors?

cheers =D

**Comment by alvarotrigo** [comment]
As detailed [in the documentation](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides):

> We could have used a custom anchor for the slide instead of its index if we would have used the attribute data-anchor on the HTML markup like so:

```html
<div class="section">
    <div class="slide" data-anchor="slide1"> Slide 1 </div>
    <div class="slide" data-anchor="slide2"> Slide 2 </div>
    <div class="slide" data-anchor="slide3"> Slide 3 </div>
    <div class="slide" data-anchor="slide4"> Slide 4 </div>
</div>
```
