### ISSUE TITLE
Is there a way we can have some static content and slider in the same page?

### ISSUE THREAD

**Issue by mitul45** [alvarotrigo/fullPage.js#1599]
I want to have some constant content and 3 slides (horizontal scroll) in single page. 

I can make it work with slider which covers the whole page, but is there a way we can specify some part of page to be static (same for all three slides)?

**Comment by alvarotrigo** [comment]
Of course, but that has nothing to do with fullpage.js. 

Just use some fixed or absoluted positioned element in relation to the section.
Use `position:realtive` for the `section` of you want them to be relative to it. 

I would recommend you to ask in other placer where they'll help you better such as stackoverflow.com with the `css` tag.
