### ISSUE TITLE
touch scroll on Windows 8 tablet 

### ISSUE THREAD

**Issue by Ouadie** [alvarotrigo/fullPage.js#160]
Your demo http://alvarotrigo.com/fullPage/ do not work on a windows 8 simulator, we can't navigate.

**Comment by llbarre** [comment]
Hello -- 
It still doesn't work on IE11 using a Surface Pro 3. Has there been any new development re: this?

**Comment by alvarotrigo** [comment]
@llbarre It is working properly on Lumia. 
Can you let me know if this returns `true` for your tablet?

```javascript
var isTouch = (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0) || (navigator.maxTouchPoints));
```

**Comment by llbarre** [comment]
Yes, it returns true. I use slimscroll. Here's my initialization:

$(document).ready(function() {
		$('#fullpage').fullpage({
		anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
		verticalCentered: false,
		scrollOverflow: true,
		navigation: true,
		autoScrolling: true,
		navigationPosition: 'right'
		});
	});

**Comment by alvarotrigo** [comment]
> My user agent: Mozilla/5.0

? You said you were using IE11.

**Comment by alvarotrigo** [comment]
@llbarre can you confirm it works in [the demo site](http://alvarotrigo.com/fullPage/)?

**Comment by llbarre** [comment]
The user agent was provide by https://www.whatismybrowser.com/. Here's the browser output:
Your web browser is:
Internet Explorer 11 on Windows 8.1

**Comment by llbarre** [comment]
No, the demo site doesn't work either.

**Comment by kamilgrymuza** [comment]
I can confirm - the demo page doesn't work on either Lumia 520 or Toshiba Encore tablet (former runs Win 8, latter Win 8.1). I'd be happy to help with the debugging.

**Comment by alvarotrigo** [comment]
@kamilgrymuza that'd be great.

Can you tell us which value this variables get in your device?

```javascript
var isTouchDevice = navigator.userAgent.match(/(iPhone|iPod|iPad|Android|playbook|silk|BlackBerry|BB10|Windows Phone|Tizen|Bada|webOS|IEMobile|Opera Mini)/);

var isTouch = (('ontouchstart' in window) || (navigator.msMaxTouchPoints > 0) || (navigator.maxTouchPoints));

var pointer = getMSPointer();

 function getMSPointer(){
            var pointer;

            //IE >= 11 & rest of browsers
            if(window.PointerEvent){
                pointer = { down: 'pointerdown', move: 'pointermove'};
            }

            //IE < 11
            else{
                pointer = { down: 'MSPointerDown', move: 'MSPointerMove'};
            }

            return pointer;
        }
```

**Comment by Peckoman** [comment]
Take a look at your method "getEventsPage". I figured out that the MS Surface Pointer Events don't have any "touches" Array. So I've changed the conditions to check for the "touches" Array:

        /**
        * Gets the pageX and pageY properties depending on the browser.
        * https://github.com/alvarotrigo/fullPage.js/issues/194#issuecomment-34069854
        */
        function getEventsPage(e){
            var events = [];

            events.y = (typeof e.pageY !== 'undefined' && (e.pageY || e.pageX) ? e.pageY : e.touches[0].pageY);
            events.x = (typeof e.pageX !== 'undefined' && (e.pageY || e.pageX) ? e.pageX : e.touches[0].pageX);

            //in touch devices with scrollBar:true, e.pageY is detected, but we have to deal with touch events. #1008
            if(isTouch && isReallyTouch(e) && e.touches != undefined){
                events.y = e.touches[0].pageY;
                events.x = e.touches[0].pageX;
            }

            return events;
        } 


It works in my case. Maybe there's an alternative Object in the MS Pointer Event to the "touches" Array. Couldn't figure it out yet.

**Comment by alvarotrigo** [comment]
@Peckoman  thanks for the feedback. Could you specify a bit more under which conditions are you testing it? 

- Device
- fullPage.js initialization (scrollbar, autoScrolling ) 
- OS

**Comment by Peckoman** [comment]
I've tested on IE11, Windows 8.1 Pro, MS Surface Tablet. 
The fullpage.js Init: 

...
resize: false,
verticalCentered: false,
navigation: true,
navigationPosition: 'right',
slidesNavigation: true,
slidesNavPosition: 'bottom',
scrollOverflow: true,
css3: true,
responsive: 1024
...

This Surface tablet is known to handle up to 10 Touchpoints.
Maybe i'm able to find out about these touches in the next days.

BTW: Your current demo is working on Chrome (43.0.2357.130 m), not working on FireFox.

**Comment by alvarotrigo** [comment]
> Your current demo is working on Chrome (43.0.2357.130 m), not working on FireFox.

There's an open issue for it [here](https://github.com/alvarotrigo/fullPage.js/issues/1016).

Regarding the issue of the topic, have you tried changing the condition for:

```javascript
if(isTouch && isReallyTouch(e) && options.scrollBar){
```

Try it and let me know if it works as expected.

**Comment by kamilgrymuza** [comment]
@alvarotrigo sorry that I haven't done it earlier, but the output you asked for is as follows:

```
# Lumia 520
isTouchDevice: 'Windows Phone,Windows Phone'
isTouch: true
pointer: Object with keys 'down' and 'move'
navigator.userAgent: "Mozilla/5.0 (compatible; MSIE 10.0;Windows Phone 8.0;Trident/6.0;IEMobile/10.0;ARM;Touch;NOKIA;Lumia 520"

# Toshiba Encore
isTouchDevice: null
isTouch: true
pointer: Object with keys 'down' and 'move'
navigator.userAgent: "Mozilla/5.0 (Windows NT 6.3;Trident/7.0;Touch;.NET4.0E;.NET4.0C;Tablet PC 2.0; McAffee;rv:11.0) like Gecko"
```

I had no easy way to copy the output, so I retyped user agents. Might be a missing space somewhere, but other than that they should be precise.

**Comment by alvarotrigo** [comment]
@kamilgrymuza thanks for it. Could you specify the values of the `pointer` array? They depend on `window. PointerEvent ` value as you can see [in the previous comment](https://github.com/alvarotrigo/fullPage.js/issues/160#issuecomment-109479893).

**Comment by kamilgrymuza** [comment]
Sure... on Lumia it is:
```
{
  down: MSPointerDown,
  move: MSPointerMove
}
```

and on the tablet it is:
```
{
  down: pointerdown,
  move: pointermove
}
```

**Comment by Peckoman** [comment]
@alvarotrigo 
i've changed the condition like you mentioned above – it works on IE11.

**Comment by alvarotrigo** [comment]
@Peckoman thanks for the feeback!

@kamilgrymuza could you also confirm making the following changes solves it for both of your devices as well?


[Line 2255 of the latest fullPage.js version](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L2255)
```javascript
if(isTouch && isReallyTouch(e)){
```
Change it for this this one:
```javascript
if(isTouch && isReallyTouch(e) && options.scrollBar){
```

Let me know if it fixes the issue.

**Comment by alvarotrigo** [comment]
@kamilgrymuza  Can you confirm if the error persists in the latest version of fullPage.js? 2.6.7 ?

**Comment by kamilgrymuza** [comment]
Hey @alvarotrigo - the problem is gone, the scrolling works well now (just tested on both devices)! Thanks for fixing it (and sorry for slow response times) :+1:

**Comment by renestalder** [comment]
Just want to point out: The scrolling of sections whose content is scrollable via `scrollOverflow`option, can't be scrolled by touch. In those section I have to use the scroll bar to scroll to the end of the section, then I'm able to swipe to the next section. It's possible that it's a problem of slimscroll.

I've tested it on a Microsoft Surface 3 with Microsoft Edge and Internet Explorer 11 with the "Scrolling inside sections" demo of fullpage.js
