### ISSUE TITLE
Chrome slides up on last section if user scrolls down

### ISSUE THREAD

**Issue by matthewhirsch** [alvarotrigo/fullPage.js#1600]
On a site I'm working on when a user scrolls down on the last section in Chrome they are moved up one slide, then scrolling down works as it should but once they hit the bottom  again and scroll down they're moved up one slide. Only seems to be a chrome issue and it's only an issue on half of the machines I've tested.

Paramaters: 
      keyboardScrolling: true,
      recordHistory: false,
      controlArrows: true,
      loopTop: false,
      loopBottom: false,

**Comment by alvarotrigo** [comment]
I'm afraid I can not provide you any help unless you reproduce the issue in [jsffidle](http://jsfiddle.net/97tbk/418/) or codepen.
I am not able to reproduce your issue in any of the [demo pages](http://alvarotrigo.com/fullPage/).

**Comment by matthewhirsch** [comment]
Just noticed a 2.7.4 was released. That solved the issue. Sorry for the issue
