### ISSUE TITLE
Navigate ith Arrows up and down

### ISSUE THREAD

**Issue by ernex24** [alvarotrigo/fullPage.js#1601]
Hello i have an issue i just want to put vertical arrows with the horizontal arrows and move arround clicking  4 arrows in the screen, i can do that? and how i can do it?

**Comment by alvarotrigo** [comment]
> i can do that? 

You can

> and how i can do it?

The plugin doesn't provide a way to do it, so you'll have to do it by yourself. 
Just create the arrows using CSS and assign them the methods `$.fn.fullpage.moveSectionUp()` and `$.fn.fullpage.moveSectionDown()`

**Comment by ernex24** [comment]
Hello Alvaro thank you for your answer, i did  it ! i have another question, i can lock the vertical movements in the slides section ?(But obviusly not in the main slide) im using fullpage.js in a mobile version of a web, i need people can't go up or down when they are in a slide, because they can lost in content.

**Comment by alvarotrigo** [comment]
Use the function `setAllowScrolling`

**Comment by ernex24** [comment]
Hello alvaro im doing the mobile version of a site with fullpage.js this is the adress
http://www.lime-xl.com/execo/execo2/execomovil/index.html
I use the function setAllowScrolling but is not working and i use the function normalScrollElements: "#slide1", to set a normal scroll in that slide, and is ok but other slides begin to fail when i do that i can use gestures only the arrows and i need use both. 

How i can solve that? Maybe im not using the functions very well.

**Comment by alvarotrigo** [comment]
> Maybe im not using the functions very well.

Read [the documentation](https://github.com/alvarotrigo/fullPage.js) and see [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) provided on it.

They are working as expected as you can check [on this example page](http://alvarotrigo.com/fullPage/examples/methods.html) and in the codepen links available in the docs.

**Comment by ernex24** [comment]
Hello Alvaro! im using fullpage js for a mobile web and im using the 4 directions to move around the web with fingers gestures, but i need the section 2 slide 0 have a scroll, and i made it! but i cant go back to home with finger gestures only pressing the arrow. i need to goback with gestures too i dont konow what i need to add to the code. 

normalScrollElements: '#slide1',

afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
          	if(index == 2 && slideIndex == 0 ){
         $.fn.fullpage.setAllowScrolling(false);
          }else {
            $.fn.fullpage.setAllowScrolling(true );



And i have aother issue im using anchors, but i cant make external links to a section i dont no why is not working, im using this code

anchors: ['firstPage', 'secondPage', 'thirdPage', 'lastPage'],

And when i try to go to the third section, send me to the active section #secondPage/1. 

This is the external link:
http://ernestomanuel.com/execomovil/#thirdPage

Thank you alvaro!

**Comment by alvarotrigo** [comment]
You should be using the option `scrollOverflow:true` for it, as in [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).
