### ISSUE TITLE
Multiple Horizontal Navigation

### ISSUE THREAD

**Issue by hendhyhutomo** [alvarotrigo/fullPage.js#1602]
Hi!

I am creating an app which pops a div with fullpage,js as its sub page. It works like a charm on its first sub page open but on the second page, my vertical navigation has double content. I realized what was going on when i look through the code apparently it creates extra li on the navigation div. thus one solution i came up is to delete the previous div first before adding the new one.

Something like this.

if($("#" + SECTION_NAV).length != 0) {
	$('#'+ SECTION_NAV).remove();
}

I want to post this as contribution but i am new to github. So you may take this suggestion or not but its up to you. Anyway keep up the good work man!

**Comment by alvarotrigo** [comment]
You are probably initializing fullpage.js multiple times. Check it out.

**Comment by hendhyhutomo** [comment]
Yea i gotta have to, i am using it with angular js as well. So i am initialling fullpage js everytime i reload the new page. but somehow it keeps adding incorrect number of navigation.

**Comment by alvarotrigo** [comment]
> Yea i gotta have to

No, you don't have to. And if you are doing it, that's wrong.

**Comment by hellsan631** [comment]
The navigation problem occurs when you initialize the page, change views, but don't  correctly call the destroy method when your switching views.

I created an [angular directive](https://github.com/hellsan631/angular-fullpage.js) and that was one of the problems that I solved. When ever your view changes it will correctly destroy the old html (navigation) and re-initialize it again when ever the directive appears again.

**Comment by lisathetangerine** [comment]
Hello guys! 

I'm a beginner coder. I'm getting this message "Fullpage.js can only be initialized once and you are doing it multiple times!", what does it mean? What shoud I do to fix it?

**Comment by alvarotrigo** [comment]
@lisathetangerine in means that you are initializing the plugin multiple times. Not sure how can I express it otherwise. You care calling `$('#fullpage').fullpage();` in multiple locations or multiple times in the same location.

Look for help in other place such as stackoverflow.com for general knowledge questions.

**Comment by Timeless1009** [comment]
@lisathetangerine I also met this bug, " fullPage: Fullpage.js can only be initialized once and you are doing it multiple times! ". I am trying to load the page that using fullpage.js in the AJAX, and comes with this bug , How do you solve this problem?

**Comment by Timeless1009** [comment]
@lisathetangerine Oh, I get it, the first page has mentioned this in the case of AJAX. 
in the source file _jquery.fullPage.js_  update the following code :
`if($('html').hasClass(ENABLED)){
        	displayWarnings();
        	return
        };`

to 
`if($('html').hasClass(ENABLED)){
        	//displayWarnings();
        	//return
        	FP.destroy('all');
        };`

this will work fine !

**Comment by alvarotrigo** [comment]
Note there are multiple angular resources for fullpage.js:

- https://github.com/meiblorn/ng2-fullpage
- https://github.com/hellsan631/angular-fullpage.js
- https://github.com/mmautomatizacion/angular-fullpage.js
