### ISSUE TITLE
Custom navigation

### ISSUE THREAD

**Issue by donAtortugo** [alvarotrigo/fullPage.js#1604]
Hi!
I want to build my own custon navigation with no anchorlinks in the URL (lockAnchors: true)
I don't mean modifying the default circles navigation bar. I mean an all new navbar.

I've managed to do it in two ways:
1) Change my custom navigation id to "#fp-nav".
The problem is that adds all css from fullPage.css, forces me to use that id, and doesn't work for slides inside a section.

2) Modifying jquery.fullPage.js line 1637 to 1631
  
  > //Scrolls to the section when clicking the navigation bullet        
     $document.on('click touchstart',**'.my-nav-links'**, function(e){
            e.preventDefault();
            var index = $(this).parent().index();			
            scrollPage($(SECTION_SEL).eq(index));			
        });
Still, that doesn't work for slides inside sections. And only works if the links are in the same order as the sections.

So... is there any easier way to accomplish this? Any way to call a section by its anchorname or index outside the jquery.fullPage.js file ?
I've tryied using **scrollPage** and **moveTo** in my custom .js file, after initialization and inside callbacks... with no success.

Thanks in advance!

**Comment by alvarotrigo** [comment]
> So... is there any easier way to accomplish this?

Yeah. Use the `menu` option. 
You can create any kind of menu / nav with it and it will add the active class where it should. 

From [the documentation](https://github.com/alvarotrigo/fullPage.js):

> **menu:** (default false) A selector can be used to specify the menu to link with the sections. This way the scrolling of the sections will activate the corresponding element in the menu using the class active. **This won't generate a menu but will just add the active class to the element in the given menu with the corresponding anchor links**. In order to link the elements of the menu with the sections, an HTML 5 data-tag (data-menuanchor) will be needed to use with the same anchor links as used within the sections. Example:

> I've tryied using scrollPage and moveTo in my custom .js file, after initialization and inside callbacks... with no success.

It seems you are doing something wrong or you broke the plugin with your modification.
It is working as expected as you can check it [here](http://alvarotrigo.com/fullPage/examples/methods.html).

**Comment by donAtortugo** [comment]
Thanks you very much! Really helped me!
Somehow i missed that part of the documentation.... and about the moveTo function... i just had to  add **$.fn.**fullpage.moveTo(x,y) (im kinda new to jQ :3)
