### ISSUE TITLE
jQuery issue

### ISSUE THREAD

**Issue by alxkski** [alvarotrigo/fullPage.js#1607]
Hi, thanks for creating this plugin it's exactly what I was looking for!
I'm having an issue with some drop down menus on my WordPress theme not working when on a page with the plugin:

http://haines.co.uk.gridhosted.co.uk/testimonials/

I've narrowed down the issue to me inserting the jquery.js code into the page:
```<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>```
if I remove that, the issue doesn't occur but the plugin also doesn't work.
I find this strange as my WordPress site already includes jquery in the header of every page throughout the site yet I have to reference it again for some reason, when I do the dropdowns no longer work.

If anyone could help me fix this issue I'd be really grateful.

Thanks,

Alex

**Comment by alvarotrigo** [comment]
Sounds like you are doing something wrong. But probably not a problem of fullpage.js. 
Read the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) in case you might find one of those situations.

**Comment by alvarotrigo** [comment]
Oh, and check the [wordpress theme which uses fullpage.js](https://goo.gl/HuFudq). You might find it useful.
