### ISSUE TITLE
Center content bigger than viewport

### ISSUE THREAD

**Issue by EvilDonkeyLondon** [alvarotrigo/fullPage.js#1608]
Hi Alvaro,

Is it possible to center some content bigger than the viewport?

For example, from this link http://jsfiddle.net/97tbk/894/, 

after clicking on click here,
if you go from the side navigation to Floor Plans
 and then click for example on number 13 or 14,

the content obviously doesn't center properly as it is bigger than the viewport. Ideally I would need to have the content push outside of it's container, having a top negative position.

Does it make sense and would that possible with your plugin?

Thank you for your amazing plugin!

**Comment by alvarotrigo** [comment]
> Does it make sense and would that possible with your plugin?

No it doesn't really. Vertically to what? Your section is not even using `scrollOverflow` and therefore will only have the viewport height.

You would have to use a scrollbar or use `scrollOverflow:true` and then `reBuild` once you open your row. But that wouldn't center it vertically. It would just allow you to scroll to the content.

**Comment by EvilDonkeyLondon** [comment]
Ok thank you for your help. I will use scrollOverflow:true and then center vertically it to the viewport with javascript. Thank you again.
