### ISSUE TITLE
Why is horizontal swipe not working with overflow-y?

### ISSUE THREAD

**Issue by eystein** [alvarotrigo/fullPage.js#1609]
Hi,

I can swipe left from the homepage, to bring up a new panel. The new panel allows vertical scrolling. But swiping back to the home panel only works when touching the blue bar on the left, but not swiping on white area.

I figured disabling `overflow-y: auto;` helps, but the panel needs scrolling. My example is here: http://eltek-staging.eystein.no/

I can't figure out why that is. Any idea on how to fix that?

Regards,
Eystein

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it on the [demo page](http://alvarotrigo.com/fullPage/examples/scrolling.html). 

Please create a jsfiddle or codepen to isolate the problem.

**Comment by alvarotrigo** [comment]
Also, add the credits for the plugin: http://eltek-staging.eystein.no/assets/js/jquery.fullPage.min.js

It is compulsory with the MIT licence. Plus it helps me to provide you support...

**Comment by eystein** [comment]
Thanks for the quick reply, I didn't expect that late on a Friday! 

I'll have to create a codepen later, as it's pretty late here already. 
Regarding the credits, they've been stripped out by a gulp uglify task, I'll have to rewrite that later too.

**Comment by alvarotrigo** [comment]
> I didn't expect that late on a Friday!

Time is relative. I'm in the UK, so its not actually late :)

Anyway, it looks like you are not using `scrollOverflow`. So you might be doing something in your side to prevent the scrolling down or up once you reach the slide.
The problem might be there in your side.

**Comment by eystein** [comment]
:)

Oh yeah, I've disabled scrolling down and up from the "sub-slides". But not left and right. 
And it works when touching and swiping on/from the blue bar. But not within the white area. 
The white area has `overflow-y: auto; -webkit-overflow-scrolling: touch;`. The swiping works when I disable those.

**Comment by alvarotrigo** [comment]
A clean reproduction would be easier to debug.

**Comment by eystein** [comment]
I discovered my horisontal swipe doesn't work because I had `normalScrollElements: '.page__content'`. 

Removing that enables the horisontal swipes again. But that offcourse cuts off the content within `.page__content`.

I tried using `setAllowScrolling` instead
```
afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
  if(slideIndex == 1){
    $.fn.fullpage.setAllowScrolling(false);
  }
}
```
but that also disables horisontal swipes. And for some reason setting the `direction` parameters won't work either. Maybe I'm not grasping how it's ment to work, but shouldn't the following work?
```
$.fn.fullpage.setAllowScrolling(false, 'down, up');
```

(BTW I figured out how to make gulp uglify keep the license in the minified file)

**Comment by eystein** [comment]
Closed? The issue still remains, though the title doesn't reflect the exact cause of the it anymore.

Now it's more to do with 
```
$.fn.fullpage.setAllowScrolling(false, 'down, up');
```
Or at least I assume so.

**Comment by alvarotrigo** [comment]
Please open a new issue for it and try to provide a reproduction in jsfiddle or codepen.

**Comment by abhishek-ashmar** [comment]
the correct answer is just paste "touch-action: pan-y !important" in your class with the overflow property
