### ISSUE TITLE
Mobile swipe not working

### ISSUE THREAD

**Issue by michaels750** [alvarotrigo/fullPage.js#1614]
Hi, I cannot seem to get the mobile scrolling to work locally on my server. Even online I do not seem to be able to get the mobile scroll to work.

I see your web demo work but even coping them and changing the links to local copies it just breaks. I know I'm missing something I just can't seem to spot it.

I have a copy here that just won't work. Could anyone see what I've missed?

**Comment by alvarotrigo** [comment]
Reproduce your issue in jsfiddle or codepen to isolate the problem.

I recommend you to start with one of the examples I provide and then add your own stuff bit by bit until you detect the problem.
