### ISSUE TITLE
Callback  afterLoad: function(index) not working

### ISSUE THREAD

**Issue by wanbinkimoon** [alvarotrigo/fullPage.js#1615]
Hello, <br>
I'm trying to trigger some events onLeave and afterLoad using the index positioning but it wont work, there is any code I have to refer in order to activate this function?

At the moment my code look like this
```$(document).ready(function() {
  $('#fullpage').fullpage({

    //Navigation
    menu: true,
    lockAnchors: false,
    navigation: true,
    navigationPosition: 'left',

    //Scrolling
    css3: true,
    scrollingSpeed: 700,
    autoScrolling: true,
    fitToSection: true,
    fitToSectionDelay: 1000,
    scrollBar: false,
    easing: 'easeInOutCubic',
    easingcss3: 'cubic-bezier(0.490, 0.635, 0.485, 1.125)',
    loopBottom: true,
    loopTop: true,
    continuousVertical: false,
    scrollOverflow: false,
    touchSensitivity: 15,
    normalScrollElementTouchThreshold: 5,

    afterLoad: function(index) {
            var loadedSection = $(this);
      if(index == 1){
          alert("Section 1 ended loading");
           }
         }
       });
    });

and the html is really simple 
```
 <div id="fullpage">
        <div id="section-wrap"> 
          <div id="section1" class="section">
            <section>
              <div class="bg-wrap"><img src="assets/img/bg.svg" class="bg-section odd"></div>
              <div class="section-content">
                <div class="big-logo-campitura">
                  <h1>campitura</h1>
                </div>
              </div>
            </section>
          </div>
          <div id="section2" class="section">
            <section>
              <div class="logo-campitura">
                <h1>campitura</h1>
              </div>
              <div class="bg-wrap"><img src="assets/img/bg.svg" class="bg-section"></div>
              <div class="section-content section2">
                <div class="text-wrap">
                  <p class="lead-section2">some text.</p>
                  <p class="mailus-section2">some other text.</p>
                </div>
                <div class="container-wrap-section2"><img src="assets/img/container2.svg" class="container-svg-section2"></div>
              </div>
            </section>
          </div>
```

**Comment by alvarotrigo** [comment]
Not able to reproduce it in [the demo page](http://alvarotrigo.com/fullPage/examples/callbacks.html).

Please provide a jsfiddle or codepen that reproduces your issue.

**Comment by alvarotrigo** [comment]
Also, afterLoad has two params, take a look at the docs:

```afterLoad: function(anchorLink, index){```

The index is the 2nd one.

**Comment by wanbinkimoon** [comment]
I will provide a jsfiddle, but i would like to avoid the anchorLink

**Comment by alvarotrigo** [comment]
Just ignore the param if you dont have anchor. You can not just avoid the parameter... that's not how javascript works.

**Comment by wanbinkimoon** [comment]
ok, now works fine. Sorry to bother, i didn't knew that :disappointed:
