### ISSUE TITLE
Gap appearing after section on DOM load

### ISSUE THREAD

**Issue by DanDvoracek** [alvarotrigo/fullPage.js#1619]
As written in the title, I have a gap appearing after the section element.

It seems that it happens when I first load the page. A horizontal scrollbar appears for a fraction of second and then disappears, leaving a gap behind.

However, if I resize the window, everything gets back to normal and the gap disappears..

Any idea what's causing this issue? I am pretty sure that I have no elements pushing for a horizontal scroll by the way..

Any ideas? 

Thanks

**Comment by alvarotrigo** [comment]
You would have to provide an isolated reproduction of the issue in jsfiddle or codepen as the problem doesn't occur in any of the [demo pages](http://alvarotrigo.com/fullPage/). 

I'll close the issue until then.

**Comment by DanDvoracek** [comment]
Well, I have a complete wordpress installation and I can't just share the url here... Can I send you the link maybe? Cheers.

**Comment by alvarotrigo** [comment]
If you think its a bug of the plugin you should be able to reproduce it in jsfiddle or codepen.
This way you will be isolating the problem from any external script or CSS.

I do not provide free support for web specific issues I'm afraid.

**Comment by DanDvoracek** [comment]
Ok never mind. I may have found what the issue was and it wasn't related to your plugin. Which is great btw.

Thanks
