### ISSUE TITLE
I want button class that will scroll to next section.

### ISSUE THREAD

**Issue by Ansif** [alvarotrigo/fullPage.js#1620]
Hi,

I want one class, that have function of scroll to next section!

I know it's possible but i saw in documentation it's only have slide to horizontally left and right function. Anyone please let me know about this function!

Thanks! :)

**Comment by alvarotrigo** [comment]
There's no such thing in the plugin, you would have to do it yourself by assigning the `moveSectionDown` function to any element in your site.
