### ISSUE TITLE
Touch autoscrolling broken over iframe/video

### ISSUE THREAD

**Issue by quantumgraphics** [alvarotrigo/fullPage.js#1621]
autoscrolling on touch devices (and firefox) seems to break over an iframe youtube video embed... Example http://en.qgdev.co.uk/#video 

If you click the cover div away to reveal the iframe it turns into normal scrolling and then breaks the snapping on the previous and next slides.

Am I missing a setting or something??

Thanks!

**Comment by alvarotrigo** [comment]
Please read https://github.com/alvarotrigo/fullPage.js/issues/803
