### ISSUE TITLE
scrollOverflow: true and swipe on mobile devices

### ISSUE THREAD

**Issue by Blackbam** [alvarotrigo/fullPage.js#1623]
Hello how can i configure the Plugin in order to make it both possible? Swipe to the next area if bottom is reached. Swipe to the previous area if on top. Swipe to right slide / left slide normally.

http://stackoverflow.com/questions/33288286/fullpage-js-and-mobile-devices-how-to-enable-section-slide-switch-if-content

**Comment by alvarotrigo** [comment]
It works as expected in iOS Tested in an iPhone 5.
Which device are you using?

**Comment by Blackbam1337** [comment]
I tried with the mobile device emulator on Google Chrome it does not work on any of the devices with touch swipe.

Furthermore I tried with Google Chrome on Android 4.2 also no reaction. The slides themselfes are working but you can not do any swipe to switch between any slides :-(

**Comment by alvarotrigo** [comment]
@Blackbam I've tested it in Browserstack using Android 4.2 and Nexus 4 and it works as expected. 

Can you provide a video with your real device?

**Comment by Blackbam1337** [comment]
Hi thanks for the quick response. I do not think this is a device dependent problem. The problem is that you can not switch between slides with moving your fingers up and down or left and right, but only when clicking a certain anchor link. Correct me if I am wrong.

If the problem is still unclear I can provide a video as soon as possible.

**Comment by alvarotrigo** [comment]
As I said:

> I've tested it in Browserstack using Android 4.2 and Nexus 4 and it works as expected.

Which means I can not reproduce your problem in a device using your same OS. Although I wasn't able to use Chrome for that case, I tried it in BrowserStack using a Samsung S5 with Android 4.4 and Chrome and it works as expected. You can slide vertically and horizontally. 

Of course, I'm talking about the [demo page](http://alvarotrigo.com/fullPage/examples/scrolling.html) which is by now the only isolated environment for the reproduction unless some other is provided.

**Comment by Blackbam** [comment]
Ok wow sorry the demo page is working in both, chrome and mobile devices.

It is therefore not a real bug. So I guess common problems for slides not to work are additional JavaScript, CSS and HTML contents.

**Comment by alvarotrigo** [comment]
@Blackbam the only way to check it is by creating an isolated reproduction of the problem. 
Same plugin initialisation and no extra css or js which might be interfering with it. Then, add those extra bits slowly until you find the problem.
