### ISSUE TITLE
Full page js scrolling not smooth.

### ISSUE THREAD

**Issue by ajmaurya99** [alvarotrigo/fullPage.js#1624]
When i scroll my website, i can feel that the section is vibrating,bouncing of the screen when i scroll from one section to another. The scrolling effect is  not that smooth.
as when you reach to this section who can feel that disturbance in the scrolling.
http://mahindramojo.com/buyers-guide.php#getQuote

also on home page,.
http://mahindramojo.com/index.php

The Third Section on both the page vibrates.
http://mahindramojo.com/index.php#features
http://mahindramojo.com/buyers-guide.php#getQuote

**Comment by alvarotrigo** [comment]
It works totally ok for me.
