### ISSUE TITLE
height 100% and variable width - section offset

### ISSUE THREAD

**Issue by dudusan** [alvarotrigo/fullPage.js#1627]
Is there a way to have this behavior with fullPage.js, centered slides with variable width and height 100%, always showing a part of next and prev slides.

Follows the layout scheme. 

![rain_v04_a](https://cloud.githubusercontent.com/assets/15528121/10867211/37704384-803d-11e5-815c-f32730528b6a.png)

Thanks!

**Comment by alvarotrigo** [comment]
Nop.

**Comment by dudusan** [comment]
Alvaro,

This will be a good improvement for fullPage.js.
Do you know or recommend any plugin that works like this?

Thanks again! :D

**Comment by alvarotrigo** [comment]
> This will be a good improvement for fullPage.js.

I'll consider it at some point.

> Do you know or recommend any plugin that works like this?

Nop.
If you really need it contact me [for a customisation](http://alvarotrigo.com/#contact-page)

**Comment by alvarotrigo** [comment]
This is possible now with the [Offset Sections extension](http://alvarotrigo.com/fullPage/extensions/offsetSections.html).

**Comment by alvarotrigo** [comment]
Variable width for slides not yet possible.

**Comment by elalemanyo** [comment]
@dudusan: Do you achieve at the end what you wanted? I am working on a project and I wanted something similar: offset not just for sections also for slides.

Thanks for any information you can give me.

**Comment by dudusan** [comment]
I simply gave up this plugin and lost the project and the client. I worked
like a dog trying to make it work and not received even a penny.
The plugin's author suggested that I pay him to do this customization.
Amazing, no?


2017-01-17 7:26 GMT-03:00 El Alemaño <notifications@github.com>:

**Comment by alvarotrigo** [comment]
> The plugin's author suggested that I pay him to do this customization.
> Amazing, no?

You expect everyone in life to work for you by free? Nice philosophy uh? 
Do you treat the same way the work of others in real life? 
I'm giving away for free the whole library in which I've spent hundreds of hours during more than 3 years. But I guess that doesn't count for you? 
It won't stop to amaze me how little some people value free things in life. 

One thing is for sure. If everybody were like you, there will be no free libraries at all.
