### ISSUE TITLE
Change slide the mouse wheel event?

### ISSUE THREAD

**Issue by WebBizMedia** [alvarotrigo/fullPage.js#1629]
Hi, may make a change of slide by scrolling the mouse wheel event?
So it works, but bad. Scroll to only one slide forward.

```javascript
var scrollPages = true;
$('#home').mousewheel(function(event) {
		if(event.deltaY < 0){
			if(scrollPages){
				$.fn.fullpage.moveSlideRight();
				console.log('up');
				scrollPages = false;
				setTimeout(function(){scrollPages = true}, 300);
			}
		}else{
			if(scrollPages){	
				$.fn.fullpage.moveSlideLeft();
				console.log('down');
				scrollPages = false;
				setTimeout(function(){scrollPages = true}, 300);
			}
		}
    	
	});
```

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such functionality I'm afraid. 
There's an open issue about it: https://github.com/alvarotrigo/fullPage.js/issues/316

I'll close this one.

**Comment by alvarotrigo** [comment]
Possible now through [the fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/).
