### ISSUE TITLE
Lightweight option

### ISSUE THREAD

**Issue by bitcity** [alvarotrigo/fullPage.js#1631]
I just want full page scrolls without any other bells & whistles. Is there an easy way to strip down the library and just retain the core plugin (kind of like many JS/CSS frameworks let you customize the build) ? 

i.e. just this vanilla example & nothing else : http://alvarotrigo.com/fullPage/examples/noAnchor.html

**Comment by alvarotrigo** [comment]
The question is. Why do you care that much?
The library its just 7Kb gzipped and 25Kb uncopmressed and ungzipped.

If you do not want to use jQuery, then you can always use [the pure Javascript version](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)), which will save you the loading of the jQuery library.

**Comment by bitcity** [comment]
> Why do you care that much ? The library its just 7Kb gzipped and 25Kb uncompressed and ungzipped.

I understand that fullpage.js doesn't have any options to cut down functionalities. However, just to answer the above question: 

There are still a large chunk of internet users who live on a very slow connection. Depending on what's your target market / demographics, 10kB could mean a lot, esp. on mobile. As a side note, see why Facbeook is experimenting with [2G tuesdays](http://www.theverge.com/2015/10/28/9625062/facebook-2g-tuesdays-slow-internet-developing-world)
