### ISSUE TITLE
URL not changing when autoheight is used with autoScrolling

### ISSUE THREAD

**Issue by etiko** [alvarotrigo/fullPage.js#1632]
Hello. First of all this is an amazing plugin.

I have a couple of auto height sections defined using this class fp-auto-height. In my JS, i have autoScrolling: false, fitToSection:false.  On any section where fp-auto-height is defined, the URL doesn't change on scroll to that section. I have tried increasing the padding  top and bottom by 300px with no luck.

Any help would be much appreciated.

**Comment by alvarotrigo** [comment]
Please provide a reproduction of your problem in [jsffidle](http://jsfiddle.net/97tbk/418/) or codepen.

**Comment by etiko** [comment]
Please see below

http://jsfiddle.net/kdy56gjm/

**Comment by alvarotrigo** [comment]
Right. When using `autoScrolling:false` fullpage.js will consider you are in the section with more content visible within the viewport.

**Comment by etiko** [comment]
Is there anything that can be done to prevent this?

I tried huge top and bottom padding and a lot of latin text but that did not help.

**Comment by alvarotrigo** [comment]
> Is there anything that can be done to prevent this?

Nop, the plugin doesn't provide any way to deal with it. 
The most you can do it [request a customization](http://alvarotrigo.com/#contact-page).

**Comment by alvarotrigo** [comment]
Related issue: https://github.com/alvarotrigo/fullPage.js/issues/919
Pull request solving the issue: https://github.com/alvarotrigo/fullPage.js/pull/1752

The PR was merged and will be released on fullpage.js 2.7.7

I'll close the issue to keep only one of them open. 
Discussion here: https://github.com/alvarotrigo/fullPage.js/issues/919
