### ISSUE TITLE
Add different menu anchors to same element

### ISSUE THREAD

**Issue by Enri1991** [alvarotrigo/fullPage.js#1634]
Hello. Let's say i have 3 section called #works1, #works2, #works3.

in my menu:
```
li data-menuanchor="home">Home
li data-menuanchor="works1">Works
li data-menuanchor="contact">Contact
```

I'd like the li element to be highlighted with the active class even when i'm on section works2, works3 etc
I tried with the afterLoad, onLeave with no success.
Thanks

**Comment by alvarotrigo** [comment]
> I'd like the li element to be highlighted with the active class even when i'm on section works2, works3

Which element areyou talking about? 
There are 3 LI elements there...

**Comment by Enri1991** [comment]
Hello.
Ok, it was late in the night and i didn't made myself clear enough. Sorry.

**sections:**
<pre>
div id="fullpage">
    div class="section-1">Home
    div class="section-2"> About
    div class="section-3"> Work1
    div class="section-4"> Work2
    div class="section-5"> Contact
/div>
</pre>

**Menu:**
<pre>
div class="menu">
    li data-menuanchor="home">Home
    li data-menuanchor="home">About
    li data-menuanchor="work1">Work
    li data-menuanchor="contact">Contact
/div>
</pre>

When i'm on section **about** the about menu anchor is highlighted.
When i'm on section **work1** the work menu anchor is highlighted.
When i'm on section **work2** the work menu anchor is NOT highlighted.

I would like the menu anchor work to be highlighted when i'm on section **work1** and on section **work2**

I already tried doing it with jquery inside the fullpage functions (on leave, after load) but it does not work quite well as the menu anchor do.

**Comment by alvarotrigo** [comment]
That's not the way the menu option works.

in your case I would be making use of callbacks such as `onLeave` or `afterLoad`, or if you prefer to go for the CSS only way, just use the CSS class added to the body and do it by yourself.

For example:

```
.fp-viewing-secondPage .work1{
    background:yellow;
}
.fp-viewing-3rdPage .work1{
    background:yellow;
}
```

**Comment by Enri1991** [comment]
Wow. The simple solution is always the better. Thank you.
