### ISSUE TITLE
slide inside slide.... is it even possible?

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/fullPage.js#1635]
Hi Alvaro! How are you... hope good!

I just stumbled in this website - http://www.designdisruptors.com/ - and saw something that looks similar to FullPage, but it has a slide inside a slide..... check it out.....

is it even possible?? I like that and thought many ideias to it =D

Cheers =D

**Comment by alvarotrigo** [comment]
> is it even possible??

Many things are possible with the right knowledge. 
Fullpage.js doens't provide a direct way of doing that, but you could if you make use of some external plugin to create those animations inside the slide and make use of some fullpage.js callbacks such as `onLeave` to cancel the movement when scrolling up or down and to fire the external plugin actions.
