### ISSUE TITLE
Displaying more than one slide

### ISSUE THREAD

**Issue by patrickcameron** [alvarotrigo/fullPage.js#1636]
Is it possible to set slide width to less than 100%? I'd like to have one slide centred, and then the previous and next slides partially displayed at either side of the page.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/1627

**Comment by verybigelephants** [comment]
+1
fp-auto-width would be so very cool on the "slides", the only little thing that the slides are missing :(
