### ISSUE TITLE
FullPage + jQuery.steps

### ISSUE THREAD

**Issue by sintro** [alvarotrigo/fullPage.js#1638]
Found bug with this two plugins on Safari. When initializing fullpage before query.steps on some element inside fullpage`s sections, everything is breaking up. There is no such problem on Chrome and Firefox, and it took some time for me to figure out what cause broken layout. So, if anyone use this two plugins, be sure you first initialize $(...).steps, and then $().fullpage

**Comment by alvarotrigo** [comment]
You usually want to initialise all the plugin in the `afterRender` callback of fullpage.js. 
That's the equivalent to document ready of jQuery.

**Comment by sintro** [comment]
Actually, both initializer was exactly inside $(document).ready. Still the order is matters

**Comment by alvarotrigo** [comment]
As I said:

> You usually want to initialize all the plugin in the afterRender callback of fullpage.js.
