### ISSUE TITLE
Is the pause between screen when scrolling configurable ?

### ISSUE THREAD

**Issue by benjR** [alvarotrigo/fullPage.js#164]
Hi!
When scrolling down with mouse wheel there is a little pause time between each "page" or "screen", is it possible to configure it to: 
1- make it longer
2- or not have this pause delay at all to have smooth scrolling ?

Thanks!

**Comment by alissonsilv** [comment]
how we can stop the slider when mouse hover slider, something like that:

$(document).ready(function () {
    $('#fullpage').fullpage({
        sectionsColor: ['#1bbc9b', '#4BBFC3'],
        loopBottom: true,
      **  pauseOnHover: true,**
        afterRender: function () {
            setInterval(function () {
                $.fn.fullpage.moveSlideRight();
            }, 1000);
        }
    });
});

It is possible ? look bold text
