### ISSUE TITLE
Fullpage adaptive height footer not active

### ISSUE THREAD

**Issue by HiOliver** [alvarotrigo/fullPage.js#1641]
Hi, 

I'm using the adaptive height class 'fp-auto-height'. Issue is when scrolling to the last section or clicking on the navigation dot the section does not stay active but makes the previous section active instead. 

View issue here: http://tinyurl.com/qxfcke2

What might be causing this?

**Comment by alvarotrigo** [comment]
Related with this other open topic: https://github.com/alvarotrigo/fullPage.js/issues/1632

**Comment by cygery** [comment]
I tried to implement a fix here: https://github.com/cygery/fullPage.js/commit/8db320daf3fb16bd0448d6f0f5e80008778fce80. The general idea is to check if we scrolled to the bottom (or at most 1px from it) and then always select the last section as the active one. Needs an additional check when using the scroll bar (see commit).
I did some tests and can't find any issues with that approach so far. However, I don't know what issues it might cause in other configurations although I can't think of any.
Also, a similar approach could be used for an auto height top section.
What do you think about it? Please also tell me if it needs anything else to be ready for a PR.

**Comment by alvarotrigo** [comment]
Solved as per https://github.com/alvarotrigo/fullPage.js/issues/1632

**Comment by alvarotrigo** [comment]
Regarding the `fitToSection` feature, this issue still open: 
https://github.com/alvarotrigo/fullPage.js/issues/1724
