### ISSUE TITLE
Link to anchor within a scrolling slide

### ISSUE THREAD

**Issue by mac2net** [alvarotrigo/fullPage.js#1645]
I added the following on the TOC slide in order to link to an ID in the middle of another slide.
The link works but when clicking on it it resets the URL logic. The destination slide becomes an extension of the original page and the other slides then match different (wrong) links.
Note: I am only using one section.
Any ideas how to overcome this?

Cheers Mike

```javascript
<script type='text/javascript'>function jumpto(anchor){
    window.location.href = "#"+anchor;
}</script>
```
```html
<a href="#" onclick="jumpto('XY1.ZZZ2');">
```

**Comment by alvarotrigo** [comment]
Use the fullpage function [`moveTo`](https://github.com/alvarotrigo/fullPage.js#movetosection-slide) instead of creating your own hacky function.

**Comment by mac2net** [comment]
I want to link from a TOC in section 1 slide 1 to a subsection in (for example) section 1 slide 4 which is located on a scrolled page below the viewport. moveto does not do this.
While the javascript above works it wipes out the fullpage context. The destination link effectively becomes part of the TOC page and everything shifts from that context.

**Comment by alvarotrigo** [comment]
You can not link to internal anchors when using fullpage.js.
