### ISSUE TITLE
Destroy all doesn't remove section and slide selectors 

### ISSUE THREAD

**Issue by trsh** [alvarotrigo/fullPage.js#1647]
1) Class .fp-section is never been remove on destroy('all'). So it doesn't go fully back to initial DOM as stated.

2) When any other element in page has the class 'section', FP get's crazy (for ex. to much navigation links). Should be really abstracted like this $(SOME_SELECTOR, this). It's a must be when doing most of the stuff with Javascript, without fully reloading from one FullPage to another (like in FB React).

Abstract JS sample:

$('#one_fp').show().fullpage({...});
$.fn.fullpage.destroy('all');
$('#one_fp').hide();
$('#second_fp').show().fullpage({...}); // generates to much navigations, taking also from #one_fp .section

**Comment by alvarotrigo** [comment]
> 1) Class .fp-section is never been remove on destroy('all'). So it doesn't go fully back to initial DOM as stated.

Right. Thanks for reporting it!



> 2) When any other element in page has the class 'section', FP get's crazy (for ex. to much navigation links). Should be really abstracted like this $(SOME_SELECTOR, this). It's a must be when doing most of the stuff with Javascript, without fully reloading from one FullPage to another (like in FB React).

Just use the option `sectionSelector` and use another one for fullpage.js. 
Not quite sure to understand what you mean when you talk about React. This has nothing to do with it. 

Your abstract example doesn't make much sense to me. Hiding something is far from ideal. You usually want to use ajax to create or remove new content and then just destroy and initialize fullpage.js.

**Comment by trsh** [comment]
OK. Sorry I overlooked sectionSelector.

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.6.
