### ISSUE TITLE
setAllowScrolling and -webkit-overflow-scrolling: touch;

### ISSUE THREAD

**Issue by rbnschlz** [alvarotrigo/fullPage.js#1648]
Hey,
currently working on a website with two sections. The upper section is made up from around 100 thumbnails and therefore overflows the container. The lower section is three slideshows which are responsive and next to each other.

Fullpage is setup like:

```$('document').ready(function(){
	$('#fullpage').fullpage({
		loopBottom: true,
        verticalCentered: false,
        keyboardScrolling: false,
        scrollingSpeed: 700
    });
	$.fn.fullpage.setAllowScrolling(false, 'down');
});
```

`$.fn.fullpage.setAllowScrolling(false);` only overrides the transitioning from slide to slide. 
(Wanted behaviour)
`$.fn.fullpage.setAllowScrolling(false, 'down');` overrides the touch scrolling on an iPad. 
(Unwanted behaviour)

Scrolling to section two is triggered by the spacebar or a button. However, the user should be able to simple scroll/swipe up again from section two to section one. Therefore it would be great if I could simply deactivate down scrolling, but keep `-webkit-overflow-scrolling: touch;` behaviour.

Thanks!

**Comment by alvarotrigo** [comment]
> The upper section is made up from around 100 thumbnails and therefore overflows the container.

How are you doing it? It doesn't seem you are using `scrollOverlow:true`.

It seems you found a bug but not with your desired results.
`$.fn.fullpage.setAllowScrolling(false, 'down');` should disable the touch functionality when you swipe down as well. 

I'm not quite sure to understand what you mean by:

> $.fn.fullpage.setAllowScrolling(false); **only overrides the transitioning from slide to slide.**
(Wanted behaviour)

And:

>  overrides the touch scrolling on an iPad

Can you explain it better?

**Comment by rbnschlz** [comment]
The content of section 1 needs to be scrollable. I never want to transition to section 2 by scrolling!
But: If I am in section 2 I wanna be able to scroll up to section 1 again!

Therefore I would like to disable only the scroll down transition (never need it).
But if I write `$.fn.fullpage.setAllowScrolling(false, 'down');` I can’t scroll inside section 1 on an iPad.

**Comment by rbnschlz** [comment]
With `$.fn.fullpage.setAllowScrolling(false, 'down');`I can still scroll inside section 1! This is how it should be, however this also prevents me from scrolling up in section 2.

**Comment by rbnschlz** [comment]
http://robinscholz.de/marco7
Here is the current state. (Select three images and press Spacebar the button underneath the images to scroll down)

**Comment by alvarotrigo** [comment]
You should be using `scrollOverflow:true`. That would make it easier for you.

**Comment by alvarotrigo** [comment]
> It seems you found a bug but not with your desired results.

I was not right. There's no bug there.
