### ISSUE TITLE
fullPage.js 

### ISSUE THREAD

**Issue by parsimania** [alvarotrigo/fullPage.js#1649]
Downloaded this a week ago, and am getting on great.
As I use animations on most sections, and would like to add more, I need to stop then running onLeave.
Is there a simple routine to do this? There seem to be many out there, but I haven't been able to get any of them to work0

**Comment by alvarotrigo** [comment]
Check the callbacks example that comes with the plugin in the examples folder.

**Comment by alvarotrigo** [comment]
Or the one online: http://alvarotrigo.com/fullPage/examples/callbacks.html

**Comment by parsimania** [comment]
I shall do that very thing! 
Just love this Jquery.
Many thanks.
Stephen Howey.
