### ISSUE TITLE
Fluent scrolling for bigger content than height of the viewport

### ISSUE THREAD

**Issue by zraly** [alvarotrigo/fullPage.js#165]
If section contains bigger (higher) content than actual height of the section (viewport), it would be nice to scroll it in common way up to the end of the section. Then, screen would roll to another one.

In other words, section's height could have eqal or bigger height (depending on the content), then height of the viewport. Not always the same (viewport) height, as it is now.

(`scrollOverflow` doesn't seem to be working perfectly (especially on phones))

**Comment by bhavan21** [comment]
c
