### ISSUE TITLE
URL Fragments issue in Safari, # fragments not being preserved across page change

### ISSUE THREAD

**Issue by mylespalmer** [alvarotrigo/fullPage.js#1657]
Hi,

I'm currently using fullPage.js and have found it great, apart from I have come across one issue.
I currently have an 'index' (index.html) page which has a list of URLs in a container, all of which then have a relative fullPage.js section on another URL. For example:

```html
<div>
  <li>
    <a href="/projects#FULLPAGE">
      nameofproject
    </a>
  </li>
</div>
```

The #FULLPAGE is where I place the name of the relative anchor in fullPage.js, and when clicking on the index project link it should redirect to that specific 'section' on another page (i.e projects.html), but it goes to the first. This is a safari specific issue and I believe it's to do with Safari not processing hash fragments, whereas Chrome and Firefox preserve them. 

If there's any information that you could provide as I'm sure that there have been others trying to do a similar thing with fullPage.js that would be great. Let me know if any more information is needed, thanks.

**Comment by alvarotrigo** [comment]
Can you provide a reproduction of the issue somewhere? 
Which version of Safari are you talking to? (the latest 9 for Mac Os X ? )

**Comment by alvarotrigo** [comment]
Accessing a section or slide on page load works correctly on Safari 9. Tested in the [demo page](http://alvarotrigo.com/fullPage/#secondPage).

**Comment by alvarotrigo** [comment]
Working correctly on Safari 5.1 for Windows. Tested on the [demo page](http://alvarotrigo.com/fullPage/#secondPage).

**Comment by mylespalmer** [comment]
Here's a link to the test site, it's private for a client, so I'll remove it after you've seen. http://ben.mylespalmer.co.uk

It's when going from the index, click any link that isn't the first in any Safari browser (including iOS), and it will go the first and just /projects/ not /projects/#SECTIONNAME. If you test it in Chrome / FF, it behaves as normal.

It works if you go directly to http://ben.mylespalmer.co.uk/projects/#LV for example though, but not if you go via the index.

**Comment by alvarotrigo** [comment]
You have errors in your javascript code that might be causing the issue. 
Solve them first.
![errors](https://cloud.githubusercontent.com/assets/1706326/11238261/465be3ce-8ddc-11e5-9607-59c4c266eb35.PNG)

**Comment by mylespalmer** [comment]
Sorry, I should turn those logs off. They are unrelated, the redirects were my trying to fix the issue using Javascript. The handlebars won't be effecting it as far as I'm aware as that's just the templating, from my understanding it's to do with Safari not processing the hash as part of the URL, you can see that when it goes to the page it doesn't actually append the #SECTIONNAME anchor. 

Have come across a similar use case before of a page linking to an anchor on another page that's part of Fullpage?

**Comment by alvarotrigo** [comment]
I tried it again and it was not able to reproduce it in Safari 9.
It seems it is not something that happens all the time. I would suggest you to create an isolated reproduction of the issue or test it by using [the one I created](http://alvarotrigo.com/fullPage/demoPage4.html) with `animateAnchor:false` as you have.

**Comment by mylespalmer** [comment]
That one works though because it's not coming from another page, the fullpage is contained within the one page that you're straight into.

If however you had an external page that had those four anchor links, which linked to the respective anchors which were on another page, I believe this is when the issue occurs. Please bare with me whilst I attempt to create a simplified version.

**Comment by alvarotrigo** [comment]
Not quite sure if this can be related, but just in case, check [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/1396) and add those changes to check if it works for you that way.

**Comment by alvarotrigo** [comment]
> That one works though because it's not coming from another page, the fullpage is contained within the one page that you're straight into.

[Here you have a link from other page](http://alvarotrigo.com/fullPage/demoPage4.html#secondPage) :D

**Comment by mylespalmer** [comment]
That you're right, d'oh!

OK, I've isolated what I believe to be the issue then. As I was stripping the .html from the URL in .htaccess (just to make it look prettier!) this was causing the problem as there was a ModRewrite, so I think this might be it:

```html 
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^/]+)/$ $1.php
RewriteRule ^([^/]+)/([^/]+)/$ /$1/$2.php
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !(\.[a-zA-Z0-9]{1,5}|/)$
RewriteRule (.*)$ /$1/ [R=301,L]
```

**Comment by alvarotrigo** [comment]
If you are sure that's the issue then I'll close the topic.

**Comment by mylespalmer** [comment]
Yep, I believe that is the case. I'll look into it further and open it up if needs be. Thank you for the swift response :)
