### ISSUE TITLE
Scroll To issue

### ISSUE THREAD

**Issue by kiltna** [alvarotrigo/fullPage.js#1658]
Hi, i have a problem.
I used two section with fp-auto-height class. Everything is all right, but when i scroll down, this sections appear at the bottom of view.
This screen show my problem :)
http://images76.fotosik.pl/85/ac18ed2c610f6826.jpg

Sections must started always on top, can i do this?

**Comment by alvarotrigo** [comment]
That's not the way the auto height sections work. They are mainly designed to deal with footers.
