### ISSUE TITLE
window.height() mis-reporting on iPhone 4

### ISSUE THREAD

**Issue by mellinger** [alvarotrigo/fullPage.js#1659]
Something I noticed:

1) On an iPhone 6, $(window).height() returns 559 which reflects the actual viewport (minus the Safari header and footer elements). This works great.
2) On an iPhone 4, $(window).height() returns 480, which reflects the full canvas (with the header and footer elements included). This causes extra room on the top and the bottom which messes with vertical alignment and can potentially allow the user to wiggle the page. 

I think window.innerHeight is a better solution. It returns 372 on the iPhone 4 which is the correct value. 

-Max

**Comment by alvarotrigo** [comment]
> This causes extra room on the top and the bottom which messes with vertical alignment and can potentially allow the user to wiggle the page.

I can't see any room in the iphone4.

iPhone4
![iphone4](https://cloud.githubusercontent.com/assets/1706326/11268356/494d0834-8ea8-11e5-83af-ce3b5d43b180.PNG)

iPhone6
![iphone6](https://cloud.githubusercontent.com/assets/1706326/11268357/496ced3e-8ea8-11e5-97ab-1b8accc2c4cf.PNG)

**Comment by mellinger** [comment]
Yes, we are. This is with iOS 9, specifically — but I think the difference exists from iOS 7 forward (when they started using the semi-transparent overlay style for the Safari menus). You could actually scroll the page only if you included an element that wasn't capturing the touch events.

**Comment by alvarotrigo** [comment]
> EDIT – Nevermind, you know what it was? I had a viewport meta tag that set a height of 480. Height() was picking up on that.

Closing the issue.
