### ISSUE TITLE
moveSectionDown() moves from first slide to last slide

### ISSUE THREAD

**Issue by ronnyandre** [alvarotrigo/fullPage.js#166]
I have a button laying over the slides, which the user can click. That invokes the `moveSectionDown()` method, but what it does the first time, is to move to the last slide, and skip all the slides in between.

When clicking several times, it acts normally. So this bug is only there when using the first time after page load.

Firefox 25 + 26 on Mac OS X 10.9 
and
Internet Explorer 9 on Windows 7.

**Comment by vagu71** [comment]
Alvaro, replacing the files did not solve the issue on firefox. Help solicited....

**Comment by vagu71** [comment]
This is the code I'm using: 

 $('.arrow-down.down').on('click', function() {
alert("move to the next section");
$.fn.fullpage.moveSectionDown();
});
$('.arrow-down.up').on('click', function() {
$.fn.fullpage.moveSectionUp();
});
$('.logo-small').on('click', function() {
$.fn.fullpage.moveTo(1);
});

**Comment by nikssardana** [comment]
I faced a similar issue. It works well on my screen, but on another screen with a marginally smaller resolution it goes to the last slide of the website. Any ideas how to fix it?
I'm using chromium on ubuntu right now.
