### ISSUE TITLE
slide animation onSlideLeave

### ISSUE THREAD

**Issue by bluufoox** [alvarotrigo/fullPage.js#1664]
Hi Alvaro.

First, thanks for your great plugin. This is the first time I use it in a future stable site. I'm a beginner with JavaScript.

I'm using some lines of code I found on <a href="http://stackoverflow.com/questions/24793062/multiple-instances-of-fullpage-js#new-answer">stackoverflow</a> + <a href="http://julian.com/research/velocity/">velocity.js</a> to add animate transitions between sections:
```javascript
onLeave: function(index, newIndex, direction) {
  if (direction == 'down') {
    $('.fp-section:nth-child(' + newIndex + ')').velocity('transition.slideUpBigIn');
  }
  if (direction == 'up') {
    $('.fp-section:nth-child(' + newIndex + ')').velocity('transition.slideDownBigIn');
  }
},
```
This code works fine for vertical scroll transitions between sections, but I try to use it with slides <code>onSlide Leave</code> to animate some content inside slides:
```javascript
onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex) {
  if (direction == 'right') {
    $('.fp-slide:nth-child(' + nextSlideIndex + ')').velocity('transition.expandIn');
  }
}
```
but the code apply the transition to the current slide (or the slide is passing) not to the next slide (or the slide is coming) like I expect. I tray with <code> slideIndex </code> but this just do nothing.

Other way I can use:
```javascript
if (index == 2 && slideIndex == 0 && direction == 'right') {
  $('#id-slide-1').velocity('transition.expandIn');
}
if (index == 2 && slideIndex == 1 && direction == 'right') {
  $('#id-slide-2').velocity('transition.expandIn');
}
...
```
But result complex because I have many sliders and I want to find a different way that apply a transition to each slide separately (better all at once).

Do you have any clue, link to tutorial or idea to add some transition between slides or fix this code?

**Comment by alvarotrigo** [comment]
The `onSlideLeave` callback is returning the correct values as you can check on the [example page](http://alvarotrigo.com/fullPage/examples/callbacks.html).

I wouldn't use `nth-child` anyway, I would go for `eqt`. And you should specify the active section if you have multiple section with slides.

```javascript
$('.fp-section.active').find('.fp-slide').eq(nextSlideIndex);
```

**Comment by bluufoox** [comment]
Hi Alvaro,

Thanks for your answer. I forgot to say there is no problems with the callback for me, It works correctly. Is just I'm learning JavaScript and want to do something custom and your help is very important to this. Many thanks.

I define the `var` that you mention (code that I like much than `:nth-child`) and I use it like in the example:
````javascript
 onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex, nextSlide) {
   var nextSlide = $('.fp-section.active').find('.fp-slide').eq(nextSlideIndex);

   if (direction == 'right') {
     nextSlide.velocity('transition.expandIn');
   }
 }
````
and the code animates the nextSlide correctly. Now I'm looking for a way to animate some specific content (with some specific class or id ) inside the slide.


Like you, I think that use `:nth-child()` is not the best practice, but if I define a var like 

````javascript
onLeave: function(index, newIndex, direction, nextSection) {
  var nextSection = $('#fullpage').find('.fp-section').eq(index);
  if (direction == 'down') {
    nextSection.velocity('transition.slideUpBigIn');
  }
},
`````
The down "coming" section it's correctly animated, but if I define `(direction == 'up')`doesn't work for me by now, so I continue using `nth-child()` on direction up and working on find a `eq()` solution.

Any idea is welcome :)

Thanks a lot again for your help Alvaro.

**Comment by alvarotrigo** [comment]
```javascript
  if (direction == 'up') {
    $('.fp-section').eq(newIndex ).velocity('transition.slideDownBigIn');
  }
```

**Comment by bluufoox** [comment]
Animates the current or "passing" section not the "coming" or next section...

**Comment by bluufoox** [comment]
Maybe this lines are helpful for someone that want animate repeated content inside slides using the `var` proposed on this topic 

````javascript
 onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex, nextSlideInside) {
   var nextSlideInside = $('.fp-section.active').find('.fp-slide').eq(nextSlideIndex).find('.repeated-content-class-or-id');

   if (direction == 'right') {
     nextSlideInside.velocity('transition.expandIn');
   }
 }
````

**Comment by nyljn** [comment]
Hi Alvaro,

First of all, thank you for the nice plugin!

Since my question is related to ghost question, let me ask you here instead of making new issue. My problem is that I have 2 slider section, how can I target the first slide section on onLeaveSlide?

        `onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex) {
	    	var nextSlide = $('.fp-section.active').find('.fp-slide').eq(nextSlideIndex);

	    	if ( nextSlide && nextSlideIndex == 1 ) {
	    		reasonSliderLeft.eq(1).addClass('animated fadeInLeftBig');
	        	reasonSliderRight.eq(1).addClass('animated fadeInRightBig');
	    	} else if ( ( nextSlide ) && nextSlideIndex == 2 ) {
	    		reasonSliderLeft.eq(2).addClass('animated fadeInUpBig');
	        	reasonSliderRight.eq(2).addClass('animated fadeInDownBig');
	    	} else if ( ( nextSlide ) && nextSlideIndex == 3 ) {
	    		reasonSliderLeft.eq(3).addClass('animated fadeInLeftBig');
	        	reasonSliderRight.eq(3).addClass('animated fadeInRightBig');
	    	} else if ( ( nextSlide ) && nextSlideIndex == 4 ) {
	    		reasonSliderLeft.eq(4).addClass('animated fadeInUpBig');
	        	reasonSliderRight.eq(4).addClass('animated fadeInDownBig');
	    	} else if ( ( nextSlide ) && nextSlideIndex == 5 ) {
	    		reasonSliderLeft.eq(5).addClass('animated fadeInLeftBig');
	        	reasonSliderRight.eq(5).addClass('animated fadeInRightBig');
	    	}
	    },`

**Comment by nyljn** [comment]
I've figured it out by adding the index == 5

    if ( index == 5 && nextSlide && nextSlideIndex == 1 ) {
        // add animate
    }
