### ISSUE TITLE
Scrolloverflow problem

### ISSUE THREAD

**Issue by Eldar88** [alvarotrigo/fullPage.js#1666]
Hi! I need to set the scrollOverflow true cause I have a content longer than the section, but i have some conflicts with the responsive option when i switch to the mobile. It's like I have two scrolling bar, one for the global page (given by the responsive option) and one for the sections I have (given by the scrolloverflow option). How to fix this?
Thanks in advance

**Comment by alvarotrigo** [comment]
> How to fix this?

I would encourage you not to use `scrollOverflow` and use a real responsive design :) 

The problem you found is being treated in [this other topic](https://github.com/alvarotrigo/fullPage.js/issues/958) and there's no solution for the moment. 

If you really need it now, feel free to [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by Yana1** [comment]
Hi, do anyone have solution for this issue ? Can you please provide a solution here?
