### ISSUE TITLE
Add property for pointing to left/right slide switch buttons

### ISSUE THREAD

**Issue by sv3k** [alvarotrigo/fullPage.js#1668]
Currently if I want to have custom buttons for switching between slides, I need to override `.fp-prev` and `.fp-next` contents via JS in `afterRender` callback.
It would be more convenient to have two additional properties like `prevSlideButton` and `nextSlideButton` to set appropriate jQuery selectors for custom previous/next buttons.

**Comment by alvarotrigo** [comment]
> , I need to override .fp-prev and .fp-next contents via JS in afterRender callback.

If you just want to change the CSS styles, I would say, do it with CSS. Why go for the JS option?

**Comment by sv3k** [comment]
Say I want to add some text and <svg> inside the button (not as background-image, to be able to customize fill color of SVG). It's pretty tricky to do using only CSS.

**Comment by alvarotrigo** [comment]
And why do you need to change the classes? Can't you use the default ones?

**Comment by sv3k** [comment]
I need to have complex layout for slide arrows for design/functionality purposes. Like the name of the next slide as the part of the «next slide» button.

Anyway, I found a good solution: just disable default slide arrows using `controlArrows: false` and use `moveSlideLeft()`/`moveSlideRight()` methods on the custom buttons. Hope it will help somebody.

Sorry for bothering you!
