### ISSUE TITLE
destroy('all') removes background-color but not background-image

### ISSUE THREAD

**Issue by xavianaxw** [alvarotrigo/fullPage.js#1669]
First up, thank you for the plugin and all the work you put into it!

Secondly, the issue I'm facing.

In short, I'm trying to destroy the fullpage plugin when it goes to mobile which I am able to do but there's a slight catch. In each of my sections, there is an option to put in a background color/image. So when I am triggering the function like so

```
$.fn.fullpage.destroy('all');
```

everything gets removed without a hitch. However I notice that background-image and background-position are not being removed but only background-color which I'm not complaining but is there a way to make background-color stay when the fullpage initialization is destroyed?

I've also replicated this scenario in fiddlejs
https://jsfiddle.net/xavianaxw/mhrkLgsn/

**Comment by xavianaxw** [comment]
So I just did some digging and I actually found a solution to this problem so I'll be closing this.

For those curious about how. Just look in jquery.fullpage.js file and look for line 2422 and uncomment it. It should look something like this.

[highlighted section](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L2413-L2427)

```
function destroyStructure(){
    //reseting the `top` or `translate` properties to 0
    silentScroll(0);

    $(SECTION_NAV_SEL + ', ' + SLIDES_NAV_SEL +  ', ' + SLIDES_ARROW_SEL).remove();

    //removing inline styles
    $(SECTION_SEL).css( {
        'height': '',
        //'background-color' : '', <-- uncomment this line
        'padding': ''
    });

   .
   .
   .
```

Cheers

**Comment by alvarotrigo** [comment]
fullPage.js will only remove the styles it added or any inline style that fullpage.js might add.
