### ISSUE TITLE
Stop Video on leave slides

### ISSUE THREAD

**Issue by peerfischer** [alvarotrigo/fullPage.js#1671]
Hello,

we're trying to pause/play a video in the current slide or section.
Any hint how to achieve this? We've tried for days now....the "afterLoad"  and "afterSlideLoad" Events are firing several times when a page is deeplinked :( we#ve also added the "footer"-hack which causes the slideIndex to mess up? Isn't there an easy way to start a video in the current slide or section and to pause all others?  Thanks a lot!

**Comment by alvarotrigo** [comment]
> the "afterLoad" and "afterSlideLoad" Events are firing several times when a page is deeplinked

What do you mean by *deeplinked* ?

**Comment by alvarotrigo** [comment]
> we#ve also added the "footer"-hack which 

What is the footer hack?

**Comment by alvarotrigo** [comment]
> Isn't there an easy way to start a video in the current slide or section and to pause all others?

fullPage.js automatically plays HTML 5 videos when you enter in the section / slide with them if they have the `autoplay` property.

For example:

```html
<video autoplay loop muted controls="false" id="myVideo">
    <source src="http://www.w3schools.com/html/mov_bbb.mp4" type="video/mp4">
        <source src="http://www.w3schools.com/html/mov_bbb.ogg" type="video/ogg">
</video>
```

Regarding the pause, it seems you've discovered a bug. They should be paused automatically when you leave the section / slide.

**Comment by peerfischer** [comment]
Thanks a lot. Is there perhaps a quick fix / workarround for this?

Best 
P.

**Comment by alvarotrigo** [comment]
Fixed in the [`dev` branch](https://github.com/alvarotrigo/fullPage.js/tree/dev). 
Will be merged in a near future.

**Comment by peerfischer** [comment]
Thanks a lot, but there seems to be a little glitch, When a video is embeded for example i  the second slide , the sound already plays when entering the section an viewing the first slide....
How could I solve this?

**Comment by alvarotrigo** [comment]
Right I see. I'll take a look at it in the next few days.

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.6.

**Comment by noerw** [comment]
Is it possible to toggle this behaviour in the configuration?
I have some audio element on a slide, which i want to keep playing on the whole site.

**Comment by alvarotrigo** [comment]
If you want to play in on page load, then just use the standard `autoplay`.

Then i fyou want to keep it playing even after section/slide leave, use `data-keeplaying`. As detailed in [the docs](https://github.com/alvarotrigo/fullPage.js#pause-on-leave).

**Comment by noerw** [comment]
oh thank you, must have overlooked that.

however, that does not work. maybe because i'm not using the audio-tag directly but via [audio.js](https://github.com/kolber/audiojs). i'll see
