### ISSUE TITLE
Content is blank when "autoScrolling: true"

### ISSUE THREAD

**Issue by devindavid** [alvarotrigo/fullPage.js#1672]
I'm pretty sure I have everything set up properly, but the auto scrolling isn't working and none of the content is visible when autoScrolling is not set or set to true. If I set it to false, the content comes back, and it snaps back to the sections, but the auto scrolling is the whole reason I'm using this. The plugin does resize the hight of the sections regardless, even if the content isn't visible. There doesn't seem to be any errors, what am I missing?

**Comment by alvarotrigo** [comment]
An example of autoScrolling:true can be found [here](http://alvarotrigo.com/fullPage/) working as expected.

Please reproduce your issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen if you think its a bug with fullpage.js.

**Comment by devindavid** [comment]
I'm not sure if I could reproduce it in jsfiddle or codepen since it's whole WordPress site, and I currently have it on a local server. If it's any indication of what's wrong, I also tried using PagePiling, which seemed to work only with the navigation bubbles, but not by scrolling (mouse wheel or wacom tablet) or arrow keys. Also, the navigation was set to true as the default, despite the documentation saying it should be false.

I don't know if it's a bug with the plugin necessarily, or some issue with the way i'm deploying it in the wordpress environment. Do you know of any conflicts I might be overlooking?

**Comment by alvarotrigo** [comment]
Sorry but I can not identify the problem without an isolated reproduction of the issue. If you are not able to recreate the problem without wordpress, then probably your problem is with wordpress or any other component outside fullpage.js.

I'll close the issue until an isolated reproduction is provided.
