### ISSUE TITLE
FitToSection on mobile not working

### ISSUE THREAD

**Issue by Eldar88** [alvarotrigo/fullPage.js#1673]
Hi, I can't figure out how my FitToSection doesn't work on mobile. I have responsive option enabled too. This is my code:

```
 $('#fullpage').fullpage({
        sectionsColor: ['#6b907f', '#6b907f', '#6b907f', '#6b907f','#6b907f', '#6b907f','#6b907f', '#6b907f','#6b907f', '#6b907f', '#6b907f'],
	anchors:['TOP', '50-46', '45-41', '40-36', '35-31', '30-26', '25-21', '20-16', '15-11', '10-1', 'Playlist'],
	navigation: true,
	navigationPosition: 'bottom',
	navigationTooltips: ['TOP', '50/46', '45/41', '40/36', '35/31', '30/26', '25/21', '20/16', '15/11', '10/1', 'Playlist'], 
	loopHorizontal: false,
	responsive: 650,
	scrollOverflow: false,
	fitToSection:false,
  	fitToSectionDelay: 3200,
});
```
I've set a delay for trying to solve this problem.
Any idea how to remove the fit in the mobile?

**Comment by alvarotrigo** [comment]
`fitToSection` is turned off when using the responsive mode comes in as you can see [in the code](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L449).

Make sure you use the latest fullPage.js version 2.7.5.

**Comment by Eldar88** [comment]
Thanks for the quickly reply. I was running the 2.7.1. My bad!
