### ISSUE TITLE
IEMobile anchors and responsive width

### ISSUE THREAD

**Issue by PogoniiA** [alvarotrigo/fullPage.js#1674]
Hi, sorry, i'm trying to find a solution of my problem for 2 day now. 
The problem is when method responsive is set the link anchor is not working on IEMobile.

PS problem is not in matching data or ID or sacesensivity

**Comment by alvarotrigo** [comment]
> anchor is not working on IEMobile.

What do you mean by that. Can you be more specific? What isn't it working? The change of the URL? The menu with anchor links?

**Comment by PogoniiA** [comment]
the menu with anchor links. well, that's the problem. it shows data, index but it seems like not responding to action when all data is gathered

**Comment by alvarotrigo** [comment]
> like not responding to action when all data is gathered

What do you mean by that? Which action? Which data are we talking about?

**Comment by PogoniiA** [comment]
nvm, by bad. Reviewed my code, it was my mistake
