### ISSUE TITLE
Add section into anchors after successful ajax

### ISSUE THREAD

**Issue by mahi786** [alvarotrigo/fullPage.js#1675]
```javascript
$(document).ready(function() {
            $('#fullpage').fullpage({
                    sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE'],
                    anchors: ['videos', 'sign_up'],
                    loopTop: true,
                    loopBottom: true,
                    afterRender: function(){
                            //playing the video
                            $('video').get(0).play();
                    }
            });
    });
```

i want to modify anchors anchors: ['videos', 'sign_up'] to anchors: ['videos', 'sign_up',terms and conditions], like this

```javascript
$.ajax({
           type:'Post',
           url:'ajax/terms_conditions.php',
           success:function(data){
               $('#fullpage').fullpage({
                    sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE'],
                    anchors: ['videos', 'sign_up','term_condition'],
                    loopTop: true,
                    loopBottom: true,
                    afterRender: function(){
                            //playing the video
                            $('video').get(0).play();
                    }
            });
            $('#fullpage').append(data);
           }
       });
```

unfortunately this is not working for me....please help me

**Comment by alvarotrigo** [comment]
You are probably using another element in your page with the same `id` or `name` value and that's what's cause you trouble.

As documentations says:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by mahi786** [comment]
NO,I want add new elemnet into existence elemnt of anchors that is not  have same id or name

**Comment by mahi786** [comment]
can i add some element dynamically into anchors?????

**Comment by alvarotrigo** [comment]
> I want add new elemnet into existence elemnt of anchors that is not have same id or name

Your code doesn't look like that. 

In any case, you can not add anchors dynamically. You would have to destroy and initialize fullpage.js again.
