### ISSUE TITLE
Upgrading from version 2.2.1 to 2.7.5?

### ISSUE THREAD

**Issue by edgarklepek42** [alvarotrigo/fullPage.js#1676]
Hi,

right now I am working on a website which uses the version 2.2.1 of fullpage.js. It should run on all major browser and mobile devices. Is it worth to upgrade from to 2.2.1 to 2.7.5 and are there any problems or things to consider when upgrading such an old version from fullpage.js?

Thank you very much for such an awesome plugin :+1:

**Comment by alvarotrigo** [comment]
Check the [release notes](https://github.com/alvarotrigo/fullPage.js/releases)

**Comment by alvarotrigo** [comment]
I would say: yeah, you should definitely update. There has been 54 versions since then...
