### ISSUE TITLE
Delay after scroll

### ISSUE THREAD

**Issue by IvanMayorov** [alvarotrigo/fullPage.js#1684]
Hello, can i set custom delay after scroll? I want to stop animation after it's begin http://quick.as/gl74h95bd. Like on this site http://www.kennedyandoswald.com/#!/premiere-screen

**Comment by alvarotrigo** [comment]
You will have to be more specific. I don't know what you are asking for.

**Comment by IvanMayorov** [comment]
I would like to increase the speed of the slide, without changing the animation speed. The behavior should be like jumping from the first slide on the fourth http://quick.as/7o7nsg9wx I apologize for the incomprehensible explanation.

**Comment by alvarotrigo** [comment]
Sorry that's not possible.
