### ISSUE TITLE
Is it possible to set same anchor on more than one section?

### ISSUE THREAD

**Issue by roving-php** [alvarotrigo/fullPage.js#1685]
navigation like this:
```
<ul>
    <li data-menuanchor="intro"><a href="#intro">Intro</a></li>
    <li data-menuanchor="design"><a href="#design">Design</a></li>
</ul>
```
and fullpage config like this:
`anchors: ['intro','intro','design','design']`

I want the first navigation item keeps active when both section1 and section2 visited.

**Comment by alvarotrigo** [comment]
Documentation says:

> **anchors:** (default []) Defines the anchor links (#example) to be shown on the URL for each section. **Anchors value should be unique. **

**Comment by roving-php** [comment]
Many thanks for your reply.
