### ISSUE TITLE
Script doesn't work in Firefox 42 + Windows 10 - touch device (tablet mode)

### ISSUE THREAD

**Issue by tomasito478** [alvarotrigo/fullPage.js#1687]
Laptop Lenovo ThinkPad 2 in 1.
It works fine in Chrome, Edge, but in Firefox (tested in ver. 42) doesn't work at all.
On touch and swipe it selects all elements placed on slide instead of changing slide.
It works fine when using mouse though.

**Comment by alvarotrigo** [comment]
There's [an open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/1016) already.

Unfortunately no solution was found.

**Comment by tomasito478** [comment]
Thanks a lot, I haven't noticed that
