### ISSUE TITLE
fp-auto-height not scrolling on firstPage

### ISSUE THREAD

**Issue by genemnagle** [alvarotrigo/fullPage.js#1688]
On version 2.7.5, I had an issue of not being able to scroll all the way back to the top when using `fp-auto-height` the first page (i.e. the very top section), which was set to less than the window height. It was set to 90vh.

The issue seems to be on ln 1181 of jquery.fullPage.js:

```
var dtop = element.hasClass(AUTO_HEIGHT) ? (dest.top - windowsHeight + element.height()) : dest.top;
```

In my case, since `windowsHeight` is greater than `element.height()`, dtop became negative, preventing the scroll. I corrected my problem by adding a new line below:

```
if (dtop < 0) dtop = 0;
```

This fixes my issue and doesn't seem to have any side effects.

**Comment by alvarotrigo** [comment]
It has been solved today in the `dev` branch as you can see in [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/1683).

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.6.
