### ISSUE TITLE
Wrap section inside div

### ISSUE THREAD

**Issue by dacastro4** [alvarotrigo/fullPage.js#1691]
I need to wrap multiples section inside one div because I need that all that sections have the same background! I created a codepen to show the issue.

http://codepen.io/dacastro4/pen/EPYgYp

Thanks in advance.

**Comment by alvarotrigo** [comment]
So why don't you use the fullpage.js wrapper for it?

**Comment by dacastro4** [comment]
Can you explain me? fullpage.js wrapper?

**Comment by alvarotrigo** [comment]
From the docs:

> Sections should be placed inside a wrapper (`<div id="fullpage">` in this case). The wrapper can not be the body element.
```html
<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>
```
