### ISSUE TITLE
When destroying an instance of fullPage – removeSlimScroll is not defined

### ISSUE THREAD

**Issue by oliverfarrell** [alvarotrigo/fullPage.js#1692]
When using `$.fn.fullpage.destroy('all');` to destroy a slider I'm getting a `Uncaught ReferenceError: removeSlimScroll is not defined` console error.

I've knocked up a demo here: https://jsfiddle.net/b0tm95mg/

**Comment by alvarotrigo** [comment]
Duplicated https://github.com/alvarotrigo/fullPage.js/issues/1582

**Comment by oliverfarrell** [comment]
Duplicating my own question. That's embarrassing.
