### ISSUE TITLE
When scrolling up from the second to last slide the slider is destroyed

### ISSUE THREAD

**Issue by oliverfarrell** [alvarotrigo/fullPage.js#1693]
I've got a scenario that requires the slider to be destroyed when the user hits the last slide so the rest of the site acts like a normal scrollable site (think of the slider as an intro). So, when the user hits the last slide (which is effectively the rest of the website rapped in a `<div class="section">`) I then destroy it immediately to resume normal functionality.

However, when I hit the second to last slide, then scroll to the previous slide the slider is destroyed.

I've knocked up a demo here: https://jsfiddle.net/b0tm95mg/

Scroll to slide 6 (the purple slide) then scroll back up. The slider will be destroyed prematurely. It should only be destroyed when you hit the slide with all the text (the last slide).

**Comment by alvarotrigo** [comment]
You telling fullpage.js to destroy it when it leaves section 6.(up or down), so its normal...

Just use `afterLoad` or use `onLeave` but use a condition to filter the `direction`.

**Comment by oliverfarrell** [comment]
Aha! Thanks!
