### ISSUE TITLE
fullpage and multiscroll anchor links

### ISSUE THREAD

**Issue by flamner** [alvarotrigo/fullPage.js#1694]
I have little problem with anhor links on site which use both plugins:

-fullpage set data-anchors for sections e.g #section
-multiscroll set data-anchors for sliders e.g #section/slide in this sections, I had to do this that way, becouse I need a links to single slides to control multiscroll navigation

when I scroll to the secion it has double anchor name: mysitename.com/#section/section/slide Is any chance to fix double "section"?

**Comment by alvarotrigo** [comment]
They are not suppose to be used together.
