### ISSUE TITLE
How do i visit all the pages scrolldown? (slider included)

### ISSUE THREAD

**Issue by tugbae** [alvarotrigo/fullPage.js#1698]

**Comment by tugbae** [comment]
Like this "https://ihatetomatoes.net/demos/full-screen-layout-with-skrollr/" horizontal and vertical scroll sametime.

**Comment by alvarotrigo** [comment]
This plugin is not for that.

**Comment by tugbae** [comment]
I guess, I did. As this way ;

var slideIndex  = 1,
					sliding     = false;
			$(document).ready(function() {

				$('#fullpage').fullpage({
					sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
					anchors: ['firstPage', 'secondPage', '3rdPage', '4rdPage', '5rdPage'],
					navigation: true,
					navigationPosition: 'right',
					navigationTooltips: ['First page', 'Second page', 'Third and last page', 'Second page'],
					scrollingSpeed:1000,
					css3: true,

					onLeave: function(index, nextIndex, direction) {

						if(index == 2 && !sliding) {

							if(direction == 'down' && slideIndex < 5) {

								sliding = true;
								$.fn.fullpage.moveSlideRight();
								slideIndex++;
								return false;

							} else if(direction == 'up' && slideIndex > 1) {

								sliding = true;
								$.fn.fullpage.moveSlideLeft();
								slideIndex--;
								return false;

							}

						} else if(sliding) {

							return false;

						}

					},

					afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex) {

						sliding = false;

					}

				});
			});
