### ISSUE TITLE
Filter Slides

### ISSUE THREAD

**Issue by greyeyes** [alvarotrigo/fullPage.js#1699]
Hi,

is there a way to "filter" / "skip" the slides?

For example I got 10 slides (1-10) and I only want to display 3-8.
What I have to do after I opened the slide?

```
$.fn.fullpage.moveTo(0, 3);
```

Maybe you could help.

Thanks

**Comment by alvarotrigo** [comment]
The plugin doesn't provide a way to do it.

**Comment by warapitiya** [comment]
@greyeyes this is a good question. Hiding sections & slides will be really helpful
