### ISSUE TITLE
special characters problem

### ISSUE THREAD

**Issue by pedluis** [alvarotrigo/fullPage.js#1700]
Hi, I'm having some problems with apostrophe and special characters. I have some sections names like " cura dell'ambiente ", that apostrophe make crash the plugin, i also try to use the escape "cura dell\' ambiente" but i still have problems.

    //Fullpage
    function fullpage(scrollbar, autoscrolling) {
                $('#fullpage').fullpage({
            'css3': true,
            'navigation': true,
            'scrollBar': scrollbar,
            'slideFlagFooter': true,
            'slideFooter': "section_footer",
            'slideFooterHeight': '100',
            'slideFooterArrow': true,
            'anchors': ['Azienda','Ieri, oggi e domani','Immagine sfondo e Zoom testo','cura dell'ambiente','scatto 2', 'Footer'],
            'slidesNavigation': false,
            'navigationTooltips': ['Azienda','Ieri, oggi e domani','Immagine sfondo e Zoom testo','cura dell'ambiente','scatto 2'],
            'autoScrolling': autoscrolling,
            'afterLoad': function (anchorLink, index) {
            }
        })
    }

**Comment by alvarotrigo** [comment]
Do not use those characters then. This is just for the URL. An those characters are not allowed.

**Comment by alvarotrigo** [comment]
For the navigation tool-tips just escape the character: `'cura dell\'ambiente'`
