### ISSUE TITLE
fullpage.js conflict in detection of scroll direction

### ISSUE THREAD

**Issue by Matso89** [alvarotrigo/fullPage.js#1701]
Hi alvarotrigo, Thanks for your nice plugin.

I have used the plugin in one of my projects:
http://we.pe/ebv

The problem is some times when scrolling between sections, it shows some conflict. for example, when I am scrolling to bottom it has to go to next section but it goes to previous one and vise versa.

**Comment by alvarotrigo** [comment]
Make sure you use the latest version 2.7.5.
I can not reproduce it in the [demo page](http://alvarotrigo.com/fullPage/).

**Comment by Matso89** [comment]
I didn't get that.
Can you explain a bit more that how can I solve this problem.

it works perfect with keyboard up and down keys. but when it comes to scrolling with mouse wheel it shows the problem I mentioned.

When the interval of between two scroll is too short the problem happens.

**Comment by alvarotrigo** [comment]
Download again the plugin to get its latest version

**Comment by Matso89** [comment]
Now I am using the latest version, but the problem persists.

**Comment by alvarotrigo** [comment]
As I said, I can not reproduce it in the demo page. Unless you can reproduce it in an isolated environment (jsfiddle or codepen) I can not help you with it.
