### ISSUE TITLE
ie and microsoft edge bug

### ISSUE THREAD

**Issue by sonqor** [alvarotrigo/fullPage.js#1702]
Hi;
I have a problem with fullpage.js
I have added it in my webpage and works good on all browsers except ie and microsoft edge.'
here is my page
http://www.warcraft-fans.ir/k/
please say me why?

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/) is working on IE and Edge,so you will have to provide an isolated reproduction of it  (no external CSS or JS) for further investigation.

Meanwhile I'll close the issue.

**Comment by sonqor** [comment]
Bad support. pff :|
