### ISSUE TITLE
Using jQuery ajax to load new slides?

### ISSUE THREAD

**Issue by scharpentier0** [alvarotrigo/fullPage.js#1703]
I am using Ajax to load new slides and my problem is that the divs created by fullpage stack within each other when I $.fn.fullpage.destroy(); $('#fullpage').fullpage(); . I'm talking about the .fp-tableCell divs. destroy('all') wont let me start the fullpage again somehow.

Thank you for the great work!

**Comment by alvarotrigo** [comment]
Please reproduce your issue in jsfiddle or codepen for further investigation.

**Comment by scharpentier0** [comment]
http://jsfiddle.net/6vb40gc4/
See how the <a> get wrapped by 2 <div class=".fp-tableCell"> with inspect element (I use Chrome) and make it hug the left side.

**Comment by alvarotrigo** [comment]
You have to use `$.fn.fullpage.destroy('all')` not `$.fn.fullpage.destroy();.
More [in the docs](https://github.com/alvarotrigo/fullPage.js#destroytype).

**Comment by scharpentier0** [comment]
http://jsfiddle.net/6vb40gc4/2/
just found out `$('.fp-tableCell').contents().unwrap();` works fine but I wondered if there is a way to not have to add that line with fullpage.js

**Comment by scharpentier0** [comment]
http://jsfiddle.net/6vb40gc4/3/
Not shure to understand what `$.fn.fullpage.destroy('all')` does for me. The jsfiddle don't work with that eighter

**Comment by alvarotrigo** [comment]
As I said, you need to use the development version of fullpage.js (2.7.6) and not 2.7.5

**Comment by alvarotrigo** [comment]
Because of this bug: https://github.com/alvarotrigo/fullPage.js/issues/1582
