### ISSUE TITLE
Scroll only first section to a second one that is normal site

### ISSUE THREAD

**Issue by dangelion** [alvarotrigo/fullPage.js#1706]
I have a first section (fullscreen hero), scrolling it has to scroll to a second section that however is not a fullscreen section (like the first one) but it's the normal site with content. How can do it?

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/614

The most you can do now is using `scrollOverflow:true` to end up with something like [this](http://alvarotrigo.com/fullPage/examples/scrolling.html) on the 2nd section.
