### ISSUE TITLE
Show timer progress rotating through pages

### ISSUE THREAD

**Issue by waveminded** [alvarotrigo/fullPage.js#1707]
Really liking FullPage.js ... I'm using this to auto rotate the sections

```
afterRender: function(){
    setInterval(function(){
        $.fn.fullpage.moveSectionDown();
    }, 10000);
}
```

Trying to setup a progress bar that is fixed to the top (like the navigation / menu) to show the timer progress... Having trouble figuring out where to place the wrapping DIV so it doesn't break the FullPage functionality.  Right now I have it outside the `<div id="#fullpage">`

**Comment by alvarotrigo** [comment]
> Right now I have it outside the <div id="#fullpage">

I don't see any problem with that.
