### ISSUE TITLE
Skipping Sections

### ISSUE THREAD

**Issue by waveminded** [alvarotrigo/fullPage.js#1708]
My scroll is skipping every other section (hopping over 2nd and 4th second).  Tried adjusting CSS3 - true / false ... scrollOverflow: true actually prevents it, but I don't have slimscroll,js installed (causes JS error).  When I add slimscroll.js and set scrollOverflow:true it goes back to skipping sections.  Here is my configuration.

````
$('#fullpage').fullpage({
                //Navigation
                navigation: true,
                navigationPosition: 'right',
                showActiveTooltip: false,
                css3: true,
                scrollOverflow: false,

                //Scrolling
                continuousVertical: true,
                autoScrolling:true,
                scrollingSpeed: 1000,
                keyboardScrolling: true,

                //Design
                controlArrows: true,
                verticalCentered: true,

                //events
                afterRender: function(){
                    setInterval(function(){
                        $.fn.fullpage.moveSectionDown();
                    }, 6000);
                }
            });
````

**Comment by alvarotrigo** [comment]
You probably are missing this from the docs:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).
