### ISSUE TITLE
Horizontal slide - jumps to first slide instead of last slide

### ISSUE THREAD

**Issue by ragcsalo** [alvarotrigo/fullPage.js#1710]
I have 1 section with 12 slides. I've set loopHorizontal: false.
I can scroll to every slide, except the last one... from the 11th slide I'd expect to scroll to the 12th (last) slide, but it scrolls back to the first slide (even though loopHorizontal is set to false). So I can never reach the last slide.... When I use the navigation bullets, the last bullet is selected but content of the 1st slide is displayed...
Is it a bug?

**Comment by alvarotrigo** [comment]
You are probably doing something wrong.
Please provide an isolated reproduction of the issue in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided.

**Comment by thibalte** [comment]
If this can help, I had the exact same situation and issue. I found out that I added some `padding` in some slides, without adding `box-sizing: border-box`, adding this property to each slides with `padding` fixed everything.
