### ISSUE TITLE
How to stop fullpage from scrolling up or down on mobile?

### ISSUE THREAD

**Issue by studio174** [alvarotrigo/fullPage.js#1711]
How do I prevent fullpage from scrolling up (or down) when I have scrolled halfway through a section?

**Comment by alvarotrigo** [comment]
> when I have scrolled halfway through a section?

While you are scrolling a section? Not possible. Only after you stop.

**Comment by studio174** [comment]
Thanks for the quick response. I think you may have misunderstand my question though. I should have said:

When viewing the website on a mobile device and STOPPING half-way through a section. The page will either scroll up or down to fit the section on the screen.  How can I prevent this?

In any case I have a solution which is to set the fit to screen delay to 99999999. 

Thanks again

**Comment by alvarotrigo** [comment]
Check the option fitToSection.
