### ISSUE TITLE
responsiveWidth, whitespace on right side.

### ISSUE THREAD

**Issue by holabadola** [alvarotrigo/fullPage.js#1713]
I'm trying to use the responsiveWidth funktion to get normal scrolling on smaller devices. the problem is that I get this white space to the right of the page, the sections is not filling out the full browser width.

My scripts looks like this, what have i done wrong? 
<img width="563" alt="skarmavbild 2015-12-10 kl 22 19 22" src="https://cloud.githubusercontent.com/assets/16246607/11728789/2105586e-9f8c-11e5-93dd-41a0c810f349.png">

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the issue in jsfiddle or codepen.

**Comment by holabadola** [comment]
I'm a beginner at coding, do you mean that you need to see my complete code? is it enough if send u the link? I don't know what jsfiddle or codepen is.

**Comment by alvarotrigo** [comment]
Reproduce it here and save the changes. 
Do not add any external CSS or JS. http://jsfiddle.net/97tbk/418/

**Comment by holabadola** [comment]
Ok i've placed my html there and my css. I've placed your "jquery.fullPage.js" in javascript is that enough or should i be able to se my complete website in there :o

**Comment by alvarotrigo** [comment]
Just do whatever you have to do to reproduce your issue there. If you don't see the problem there, that's not useful.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided.
