### ISSUE TITLE
normal scroll , fitToSection 

### ISSUE THREAD

**Issue by zhongyz** [alvarotrigo/fullPage.js#1714]
I am writing html by use fullpage , my html and js code like this:
![qq 20151211105022](https://cloud.githubusercontent.com/assets/11351844/11734740/f916033a-9ff4-11e5-9216-139517b1d1b0.png)

In my js code ,I set the autoScrolling paramater to false . I hope only from the section4 to section5 or from section5 to section4 ,the page can fitToSection , otherwise not  .  how can I do ?

**Comment by zhongyz** [comment]
I mean ,others is normal scrolling ,do not fit to section

**Comment by alvarotrigo** [comment]
Use the method [setFitToSection](https://github.com/alvarotrigo/fullPage.js#setfittosectionboolean) inside some callback such as [afterLoad](https://github.com/alvarotrigo/fullPage.js#afterload-anchorlink-index).

**Comment by zhongyz** [comment]
I haved try and get no answer . Can you post an example ?

**Comment by alvarotrigo** [comment]
Post your code and provide a jsfiddle with it and I'll take a look at it.

**Comment by zhongyz** [comment]
this is my code on jsfiddle ：
https://jsfiddle.net/ptwk3dsp/4/embedded/result/

I hope only from the section4 to section5 or from section5 to section4 ,the page can fitToSection ,
others normal scroll ,do not fit to section !

**Comment by alvarotrigo** [comment]
Same problem as this issue: https://github.com/alvarotrigo/fullPage.js/issues/1489
I'll consider it a duplicate.
