### ISSUE TITLE
Set the maximum number of slides

### ISSUE THREAD

**Issue by webgeckos** [alvarotrigo/fullPage.js#1715]
Hi there, 

Am I wrong or is the maximum number of slides limited to 5? Is there an option to change that? I am using the slides in a WordPress Loop and it would be great to give the users of my theme the opportunity to add as many slides as they want.

Thank you.

**Comment by alvarotrigo** [comment]
> Am I wrong or is the maximum number of slides limited to 5?

You are wrong :)
