### ISSUE TITLE
continuousHorizontal?

### ISSUE THREAD

**Issue by jamescabrera** [alvarotrigo/fullPage.js#1717]
Is there an easy way to get continuous horizontal, so that when you get to the last slide you can continue in the same direction to the first slide instead of getting a super fast reverse animation to the first slide? Maybe this has been addressed already but thanks for any help.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/124

**Comment by alvarotrigo** [comment]
Available now through [the fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/).
