### ISSUE TITLE
How to change Scrolling speed ??? 

### ISSUE THREAD

**Issue by TamaraBlanc** [alvarotrigo/fullPage.js#1719]
Hey ! 
I'm coding a one-page website for a school project. To do so, I use the fullpage.js thing. I want to make a stop motion: each section contains a still and the whole thing gets animating by scrolling. I want my sequence of stills smooth ( like a stop motion so) but I ve small knowledges in code. I know that I have to directly add lines of code in the file but i don't know how I can change scrolling speed ... Can you help me please ??

**Comment by ZsharE** [comment]
You need to use slimScroll for that and to set the scroll speed using wheelStep option.
Documentation page: http://rocha.la/jQuery-slimScroll

**Comment by alvarotrigo** [comment]
Use the option scrollingSpeed as detailed in the docs.
