### ISSUE TITLE
fullpage.js safari and ie problem video background

### ISSUE THREAD

**Issue by gellina** [alvarotrigo/fullPage.js#1720]
hi,
I have implement bootstrap with fullpage.js.
my site is this like:
many pages in witch is loaded a video in background.
on each video there is a div with some text. the pages scroll vertically with an anchor with the click of the mouse and also the arrow on the keyboard.

with chrome and firefox on pc no problem.
with internet explorer and safari a lot.

with safari: 
if i use the click on the mouse on the arrow on the first page, it look fine in the other.
otherwise, if i use the keyboard to scroll, in the next pages, the video overlap the div with the content.
( the z-index are correct)

with ie (and also mobile) the pages are not resize well and i don't see al the content.
the scroll il fine but the page is cut and i don't see the arrow to scroll.

also the video, even if is very small, is not loaded well. it seems like it's like 20gb of weight.
big. too big. and it's not.

is there maybe an hack for those browsers that i have to put?
maybe for the positioning obsolute or the z-index?

i don't know what to do exactly cos i don't know javascript well.
[github.zip](https://github.com/alvarotrigo/fullPage.js/files/62545/github.zip)

**Comment by alvarotrigo** [comment]
It doesn't have anything to do with fullpage.js but with CSS only very probably.

**Comment by gellina** [comment]
i think that the problem of "slow" loadind on internet explore is due to the fact that he load all the video i have in all the pages in the same time.
so it tries to load 11 videos in the beginning.
i have to change the call of javascript so to load a video per time.

don't know how, but that's it ^^
