### ISSUE TITLE
animation.css and fullPage.js

### ISSUE THREAD

**Issue by EuRusik** [alvarotrigo/fullPage.js#1721]
Hey guys. how to do that?
I have this code for animation.css:

```javascript
//code start
$(document).ready(function(){
	var divAn =	$('#an-container #forAnimation');
	$(window).scroll(function() {
		divAn.each(function(){
		var imagePos = $(this).offset().top;
		var topOfWindow = $(window).scrollTop();
			if (imagePos < topOfWindow+300) {
				var animation = $(this).attr('animate');
				if ( $(this).attr('animate') == null) animation = 'slideUp'; 
				$(this).addClass(animation);
			}
		});	
	});
});
//code end
```
How to write correctly it using afterLoad: function (anchor Link, index) {....

**Comment by alvarotrigo** [comment]
Read [the fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) regarding the use of the `scroll` event.

**Comment by EuRusik** [comment]
Yes, I read this faq, but I do not know much to js/jq and I can not write the code correctly, help

**Comment by alvarotrigo** [comment]
Then you should better ask for help in other places such as stackoverflow in which they will help you much better.

**Comment by alvarotrigo** [comment]
The easy way is by using `scrollBar:true` in your fullpage.js options:

```javascript
$('#fullpage').fullpage({
    scrollBar:true
});
```

**Comment by EuRusik** [comment]
Yes, I tried it, it does not work; (
