### ISSUE TITLE
Thanks Alvaro

### ISSUE THREAD

**Issue by neil-s** [alvarotrigo/fullPage.js#1723]
This is not an issue, I just wanted to say thanks @alvarotrigo . I tried implementing the full-page sections functionality myself, and it was horrible. I then tried fullPage.js, and it was a breeze. The library works well (so far, at least) with Foundation, is documented really well, and you seem pretty timely in responding to issues. We don't show our gratitude to open source developers nearly enough, and while I don't have much money at this point to donate, I thought I'd at least share my gratitude.

**Comment by alvarotrigo** [comment]
Thanks for it :) I'm glad you find it useful!
