### ISSUE TITLE
fitToSection only on sections without fp-auto-height

### ISSUE THREAD

**Issue by verybigelephants** [alvarotrigo/fullPage.js#1724]
fitToSelection=true is very cool and useful indeed

however, it loses its point if a section has "fp-auto-height" class, meaning it can be even larger than the viewport. the way it is right now you can be reading a section of a website, when the page just scrolls for you after fitToSelectionDelay

it would be very useful to have fitToSelection="fullpageonly" (or something similar), so the plugin wouldn't autofit the sections that are different size than the viewport. i think it's even better behavior to be by default

**Comment by tillsanders** [comment]
:+1:

**Comment by alvarotrigo** [comment]
Now you can turn it on and off yourself using `$.fn.fullpage.setFItToSectin(false)`;
You can do this in `onResponsive` callback for example, or `afterLoad` or `onLeave`.

**Comment by alvarotrigo** [comment]
`fp-auto-height` can be applied for smaller or bigger sections. 
I can imagine some people want still to use fitToSection on smaller sections. So I'll just make it to automatically turn off for sections larger than the viewport.

**Comment by alvarotrigo** [comment]
Fixed in the dev branch. Will get merged in fullPage.js 2.9.5
