### ISSUE TITLE
video is paused automatically when i scroll (leave) the section ?

### ISSUE THREAD

**Issue by pigerla** [alvarotrigo/fullPage.js#1725]
The video is playing on section three. When i scroll (leave) the section, The video is paused automatically. Why ? What can I do if I dont want to make the video be  paused ?

**Comment by alvarotrigo** [comment]
Add the attribute `data-ignore` to your video.

**Comment by pigerla** [comment]
Yes, you are right. thanks.

**Comment by johnharlan** [comment]
This didn't fix the issue for me

**Comment by Jesse1989pp** [comment]
@johnharlan This was addressed in another issue and the docs, https://github.com/alvarotrigo/fullPage.js#pause-on-leave
