### ISSUE TITLE
Change Url on the fly

### ISSUE THREAD

**Issue by glopglop98** [alvarotrigo/fullPage.js#1726]
Hi,

First, Thank you for your work. It's awesome. Thanks a lot.

I have a section with 2 slides.
First contain a list of links, and when I click on a link, I call second slide with ajax content.
But, I would like to change dynamically the URL following the link.

It's work first time, but not after, the Url stay with first change

I tried to place $.fn.fullpage.reBuild(); everywhere but without result.

Here's my code:
```javascript
$(document).ready(function() {
	$('#slide1 a').click(function (e) { 
		e.preventDefault();
		$("#slide2").attr("data-anchor", $(this).attr("href"));
		$.ajax({
			type: "POST",
			url: 'ajax.php',
			data:"id=" + $(this).attr("href"),
			success: function(html) {
				$("#slide2").html(html);
			}
		});
		$.fn.fullpage.moveTo('slide2', 1);
	});
});
```

Thanks a lot for your help

Marco

**Comment by alvarotrigo** [comment]
I don't  see anything in your code trying to change the url.

**Comment by glopglop98** [comment]
Hi
```javascript
$("#slide2").attr("data-anchor", $(this).attr("href"));
```
FullPage use date-anchor to force anchor in url.
It's work first time (click on a link in slide 1), but after closing the slide 2 and click another link in slide 1, the url not change.
I don't know why...it's bizarre.

Thanks for your help

Marco

**Comment by alvarotrigo** [comment]
The anchors are defined in the `anchors` option itself, not in the DOM elements.

**Comment by glopglop98** [comment]
Hi, 
Sorry, but it's possible.
Find "data-anchors" in documentation

Marc

**Comment by alvarotrigo** [comment]
> Sorry, but it's possible.

That's funny, if you know more than me then why you ask :)

**Comment by glopglop98** [comment]
Hi
Merry Christmas

Because I work only first time (click).
I hope soon put online a demo version of the site.

Have a nice day

**Comment by glopglop98** [comment]
Hi,

Here a demo:
http://www.amaramarama.com/v3

If you click on a image in section "projets", a new slide appears and URL change (example: http://www.amaramarama.com/v3/#projets/projet23

That's work !! cool.

But if you go click on  another picture, URL of slide don't change (....../projet23)

Thank's for your help

Marco

**Comment by alvarotrigo** [comment]
>But if you go click on another picture, URL of slide don't change (....../projet23)


As I said:

> You can not change the URL dynamically.

**Comment by glopglop98** [comment]
Hi,

Sorry and OK. I understand now.

Thanks a lot for your work, very good job.

Happy New Year, good health et all good things

Marco
