### ISSUE TITLE
IE11 does not scroll

### ISSUE THREAD

**Issue by Riggi** [alvarotrigo/fullPage.js#1727]
Hi,

Thank you for your great plugin - it helped me a lot!! I really appreciate your work! It's made in a smart way so i can really do what I wanted to with it.

I'm using it on this site http://www.ipeak.ch/tourismus-communicator/ and it's working well on all browsers but the IE11. I really tried googling the error but I can't find anything helpful.

The onLeave and afterLoad events do fire, but the 'big frame' does not slide.

Is there any way for a workaround?

Thanks for your time

Rick

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/) works on IE 11. You will have to provide an isolated reproduction in jsfiddle or codepen if you believe its a bug in fullpage.js. 

I'll close the issue until then.

**Comment by panther7** [comment]
I have same problem, 2.7.5 works, 2.7.6 does not :-/

**Comment by alvarotrigo** [comment]
@panther7 provide an isolated reproduction of the issue and specify which device and browser you are using.

**Comment by panther7** [comment]
In 2.7.5 does not works too, i think that problem with MouseWheelHandler(), i will try reproduction tomorrow.

**Comment by panther7** [comment]
#1778

**Comment by panther7** [comment]
Bug reproduced... try add CSS overflow(-x): hidden to "fullpage-wrapper".

**Comment by alvarotrigo** [comment]
> Bug reproduced... try add CSS overflow(-x): hidden to "fullpage-wrapper".

And why would you add `overflow-x: hidden`... It seems to me that's not a problem of the plugin but yours with the plugin and your setup.

**Comment by panther7** [comment]
Yes, problem is in finally implementation (css), but i did reproduced the problem, which is on the http://www.ipeak.ch/tourismus-communicator/ too. ;-)

**Comment by panther7** [comment]
But, stupid is, that works in FF and Chrome, not in IE11 (maybe lower)

**Comment by alvarotrigo** [comment]
I don't see why would you  need `overflow:hidden`

**Comment by panther7** [comment]
Easy, development, in past was useful, but after time, it was forgotten.
