### ISSUE TITLE
Auto-Height Section with PaddingTop Issue

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#1729]
Hi,

When the section is marked as auto-height and paddingTop feature is set, fullpage does not see the height correctly. The section goes down to the next section. You can check it here.
http://jsfiddle.net/6xwmjrtx/

Thank you for your help.

**Comment by meceware** [comment]
Thank you very much Alvaro,

**Comment by alvarotrigo** [comment]
Fixed in 2.7.7.
