### ISSUE TITLE
URI anchor will not scroll to section

### ISSUE THREAD

**Issue by studio174** [alvarotrigo/fullPage.js#1730]
Hi there,

It seems when a user is linked to a specific section such as:

http://garafraxamedia.com/#contactPage

fullpage.js will not scroll to that section.  Is there a property for this?

```
    /*
     * Full page
     */
    $('#fullpage').fullpage({
        // Navigation       
        anchors: ['topPage', 'folioPage', 'servicesPage', 'pressroomPage', 'workshopPage', 'contactPage'],
        navigation: true,
        navigationPosition: 'right',
        navigationTooltips: ['TOP', 'FOLIO', 'SERVICES', 'PRESSROOM', 'WORKSHOP', 'CONTACT'],
        showActiveTooltip: false,

        // content
        verticalCentered: true,

        // Scrolling
        responsiveWidth: 992,
        scrollOverflow: false, 
        keyboardScrolling: false,
        autoScrolling: true,
        fitToSection: false,
        scrollBar: false,
        fitToSectionDelay: 9999999999,
        touchSensitivity: 10,

        // video
        afterRender: function() {
            // play the video
            $('video').get(0).play();
        }
    });
```

**Comment by alvarotrigo** [comment]
I can not reproduce your issue in the [demo page](http://alvarotrigo.com/fullPage/) or any of the examples online available.
You are very probably doing something wrong. 

Please reproduce your issue in an isolated page, no external CSS or JS besides fullpage.js.

Also, add the licence to your scripts. fullpage.js can only be used freely if you keep the credits...  which you are not doing at the moment.
