### ISSUE TITLE
fullpage.js + iscroll.js handler, not working for iphones, android is ok.

### ISSUE THREAD

**Issue by navi88** [alvarotrigo/fullPage.js#1733]
I have a problem with iscroll handler for fullpage.js, after I added it, fullpage.js is not working only on iphones. If I remove the handler, fullpage.js works. It seems it fails to detect proper height in iphone browser.

Here is the url:

http://www.vinarijapantic.com/apps/onePage/

Any ideas?

**Comment by alvarotrigo** [comment]
fullpage.js doesn't provide support for iScroll.js yet.

**Comment by navi88** [comment]
ok, thank you Alvaro.
