### ISSUE TITLE
Making the tooltips text also navigate you to the correct section

### ISSUE THREAD

**Issue by milan92** [alvarotrigo/fullPage.js#1734]
So I'm using the vertical dots on the right hand side of the screen. I have the tooltips being shown as well and I would like them to navigate to the same place as the dots do. You can take a look at the site on 

www.milanmilutinovic.me/propergander

Thank you.

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any option for it at the moment. 
I'll mark it as an enhancement.

**Comment by alvarotrigo** [comment]
Fixed in 2.7.7.

**Comment by VIEWSION** [comment]
excellent! Thank YOU!
