### ISSUE TITLE
Weird behavior when $window.resize() is triggered by keyboard hide in Samsung Note10.1

### ISSUE THREAD

**Issue by PilockHulmes** [alvarotrigo/fullPage.js#1735]
I encountered an issue when using this splendid library.
I have an <input> in my page which using fullpage.js. After doing the following steps in Samsung Note(Android 4.1.2):
1. Touch the <input> and the keyboard show up.
2. Input some text, such as "hello word" or whatever.
3. Touch other parts of page so the keyboard slide out.  
And afterwards, the page will not resizing properly.  
It is the code below in function `resizeHanlder()` which caused this problem
```
// rebuild immediately on touch devices
if (isTouchDevice) {
  var activeElement = $(document.activeElement);

  //if the keyboard is NOT visible
  if (!activeElement.is('textarea') && !activeElement.is('input') && !activeElement.is('select')) {
    var currentHeight = $window.height();

    //making sure the change in the viewport size is enough to force a rebuild. (20 % of the window to avoid problems when hidding scroll bars)
    if( Math.abs(currentHeight - previousHeight) > (20 * Math.max(previousHeight, currentHeight) / 100) ){
      FP.reBuild(true);
      previousHeight = currentHeight;
    }
  }
}
```
In touch device, the page will resizing immediately after $window.resize() is triggered and at that time the keyboard of Samsung Note hadn't slid out, so the $window.height() will not get the proper height of window.

So could you please tell me why the resizeHandler() handles the touch device and personal computer differently?

Apologising for my poor English and Expression.

Thank you.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/145

> So could you please tell me why the resizeHandler() handles the touch device and personal computer differently?

You can guess that from the code itself.
This is not a place to ask why things are the way they are but a place to report issues or provide solutions.

If you have a better solution, feel free to commit a pull request.
