### ISSUE TITLE
Why not prohibit URL change, when the page scroll？

### ISSUE THREAD

**Issue by caiz** [alvarotrigo/fullPage.js#1736]
Thank for your fullPage.js,It is a good plug,bug I have a question:

I don't want to change the URL,when I scroll page.Because when I click the browser's back "history.back(-1)",and did not return to the previous page in history. But still on this page, but rolled previous up.I want to enter another page.How to set up?

So could you please tell me how to set up??

Apologising for my poor English and Expression.

Thank you.

**Comment by alvarotrigo** [comment]
Two options

- Do not use anchors
- Use the option `lockAnchors:true` as specified in the docs.

**Comment by caiz** [comment]
ok,thank you very much.
