### ISSUE TITLE
Problem with overflow - how to scroll up after change section

### ISSUE THREAD

**Issue by ygennew** [alvarotrigo/fullPage.js#1737]
// Fullpage.JS	
		$(document).ready(function() {
			$('#fullpage').fullpage({
				sectionsColor: ['white', 'white', 'white', 'white'],
				anchors: ['hunt', 'blazer_mod_1', 'blazer_mod_2', 'blazer_mod_3'],
				menu: '#navbar',
				loopTop: false,
				loopBottom: true,
				scrollOverflow: true,
				afterRender: function () {
					function makeTabs(contId) {
						var tabContainers = $('#'+contId+' div.tabs > div');
						tabContainers.hide().filter(':first').show();
						var tabContainer_select = $('#'+contId+' img#tab_img');				
		
						$('img#tab_img:first').attr('src', 'img/tab2.png');	
		
						$('#'+contId+' div.tabs ul.tabNavigation a').click(function () {
						tabContainers.hide();
						tabContainers.filter(this.hash).show();
						$('#'+contId+' div.tabs ul.tabNavigation a').removeClass('selected');
						tabContainer_select.attr('src', 'img/tab1.png');
						$(this).find('img').attr('src', 'img/tab2.png');			
						$(this).addClass('selected');
						return false;
						}); //.filter(':first').click();		
					}
	
					makeTabs('tabs-1');
					makeTabs('tabs-2');
					makeTabs('tabs-3');
                        }

When user go down, page. Then page come back on section0. And again use down scroll, on section1 i see that scroll is stay in down position. How can make that after change section it change scroll in up position?

Thank you.

**Comment by alvarotrigo** [comment]
fullpage.js doesn't provide a way to do it. You would have to do it by yourself.
