### ISSUE TITLE
Disable Scrolling effect for a section then reactivate it.

### ISSUE THREAD

**Issue by TiNyDGZz** [alvarotrigo/fullPage.js#1738]
Hi, first of all, thx for this plugin. I wanted to know if it is possible to disable the scrolling effect of fullPage.js during a section and scrolling normally like in the Normal scrolling, then, reactivate it for the next section?
I tried to manipulate : 
normalScrollElements

but it just stop scolling on my mouseover and not able the normal scrolling.

Thx for answer

**Comment by alvarotrigo** [comment]
You can activate and desdactivate the auto scrolling with the function [setAutoScrolling](https://github.com/alvarotrigo/fullPage.js#setautoscrollingboolean).
But it won't probably do what you expect.

The closer you can get is to use scrollOverflow. That's the purpose of it.  Check out [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).
