### ISSUE TITLE
"autoScrolling=false" on Android and sections not auto resizing

### ISSUE THREAD

**Issue by dsiglin** [alvarotrigo/fullPage.js#1739]
Issue: When "autoScrolling=false" the sections are not full page because the height is not recalculated once the address bar disappears. I've attached screenshots from http://alvarotrigo.com/fullPage/examples/normalScroll.html showing the problem.

Devices tested on:
Nexus 7 running Lolipop and stock  browser
Moto X (1st gen) running KitKat and stock browser

Initial page load:
![fullpage1](https://cloud.githubusercontent.com/assets/7239446/12028426/2f46b7e8-ada5-11e5-8cda-8ce834e48175.jpg)

If I scroll down enough for address bar to disappear, wait for "fitToSection" to fire and and this is what I get.
![fullpage2](https://cloud.githubusercontent.com/assets/7239446/12028431/34c0436a-ada5-11e5-9c24-f86ab4124295.jpg)

Scrolling down to the final (third) section you can see how the failure to resize effects the site (sorry for the volume indicator):
![fullpage3](https://cloud.githubusercontent.com/assets/7239446/12028433/3c1c9f64-ada5-11e5-8821-726494140137.jpg)

Now, when I rotate the phone to landscape and then rotate back to portrait the resize command fires and the section is the right size.
![fullpage4](https://cloud.githubusercontent.com/assets/7239446/12028437/4dd6b604-ada5-11e5-9268-1e98d6c14909.jpg)

So, that is the issue. What is a good work around so that the section height and width is checked when the height and width change or is there a more elegant solution? I don't know javascript enough to code a custom solution.

**Comment by alvarotrigo** [comment]
Already treated in these pull requests:
https://github.com/alvarotrigo/fullPage.js/pull/1660
https://github.com/alvarotrigo/fullPage.js/pull/1690

**Comment by dsiglin** [comment]
Gotcha, for now I'll use that Dev branch. Cheers.
