### ISSUE TITLE
Set "scrollbar: False" only on mobile devices

### ISSUE THREAD

**Issue by Niemel** [alvarotrigo/fullPage.js#1740]
Hi there!

I work with fullpage.js in combination with wow.js. The only way i can achieve this is to set the "scrollbar: true". 

On mobile and tablet it lags (because of the scrollbar: true setting). How can i achieve the scrollbar: false setting on mobile/tablet only? I pretty much don't care if the wow.js doesnt work on mobile/tablet.

Pardon my english...not a native dude here :)

**Comment by alvarotrigo** [comment]
There is no such thing as "tablet only". You will have to identify what you mean by that. 
The normal approach nowadays is to determine it by the `width` and `height` of the device. But it won´t assure you its a mobile or a tablet.

In any case, this is not something fullpage.js can deal with, you will have to distinguish between one or another device by yourself and then initialise the plugin in one or another way.

**Comment by Niemel** [comment]
This is maybe a better way of asking: is there somekind of media query for this in javascript? 

for example:

@media screen and (max-width: 44.75em) {
	.scrollbar {
		set: false;
	}
}

**Comment by alvarotrigo** [comment]
Nop. There's no function to turn the scrollBar on or off.

**Comment by Niemel** [comment]
Alright! Thank you for replying!
