### ISSUE TITLE
Restricts Arrow key navigation in pages

### ISSUE THREAD

**Issue by harshamv** [alvarotrigo/fullPage.js#1741]
I am using the plugin only in the homepage but since i have contacted all the plugins into one single file. even though i do not use the plugin in other files its restricting the scroll via arrow keys.

Any idea how to make this alright?

**Comment by alvarotrigo** [comment]
You should only initialise fullpage.js when you need to use it. If you are not using fullpage.js in other subpages, do not initialise it.

**Comment by harshamv** [comment]
Since the js file is the same it gets initialised but that particular class
is not present in those pages still it affects the navigation

On Tuesday 29 December 2015, Álvaro <notifications@github.com> wrote:

> You should only initialise fullpage.js when you need to use it. If you are
> not using fullpage.js in other subpages, do not initialise it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1741#issuecomment-167830713>
> .
>


-- 
Regards,
*Harsha M V*


http://mink7.com/

Cell: +91 0 99863 77561
Skype: harshamv22
LinkedIn: http://in.linkedin.com/in/harshamv
Follow us on twitter @mink_07 <http://twitter.com/mink_07>
Like us on Facebook <http://facebook.com/mink.seven>

**Comment by alvarotrigo** [comment]
As I said

> You should only initialise fullpage.js when you need to use it.
