### ISSUE TITLE
Firefox auto scrolls to textarea with autofocus and ruins plugin scroll

### ISSUE THREAD

**Issue by fdruzhinin** [alvarotrigo/fullPage.js#1743]
Hello.

I downloaded current version of the plugin and added to **demoPage.html** example this code to ```#section2```:

```php
<form method="post" action="" enctype="multipart/form-data">
    <textarea autofocus="autofocus"></textarea>
</form>
```

So we have this:
```php
<div class="section" id="section2">
	<div class="intro">
		<h1>Example</h1>
		<p>HTML markup example to define 4 sections.</p>
		<img src="imgs/example2.png" alt="example" />
		
		<form method="post" action="" enctype="multipart/form-data">
			<textarea autofocus="autofocus"></textarea>            
		</form>
	</div>
</div>
```

In Firefox 43.0.1 (on Windows 7) we got when we open page:
![autofocus](https://cloud.githubusercontent.com/assets/7509611/12071417/65762940-b0cd-11e5-8f3b-c641483153ff.png)

instead of 
![normal](https://cloud.githubusercontent.com/assets/7509611/12071416/6575f18c-b0cd-11e5-8d7b-6caabf11e263.png)

**Comment by alvarotrigo** [comment]
Why don't you just focus it with javascript or jQuery?
Any page would have that same problem with any autofocus in Firefox.

**Comment by fdruzhinin** [comment]
I really like this plugin, thanks for your work, I understand you and will use js, but I think should be better plugin's behaviour, at least fully scroll to page with control, but not partially as at screenshot. Is that possible?

**Comment by alvarotrigo** [comment]
Different browsers works in different ways, and there's no way for the plugin to know if the browser "scrolled" the page or not, so I guess this problem can not be solved. 

Same issue as this https://github.com/alvarotrigo/fullPage.js/issues/1237
