### ISSUE TITLE
skips section on vertical scrolling in IE11 on Win10

### ISSUE THREAD

**Issue by johannheyne** [alvarotrigo/fullPage.js#1744]
Skips section on vertical scrolling in IE11 on Win10.
Tested page: http://alvarotrigo.com/fullPage/ with browserstack.com and a Apple Magic Mouse on OSX. Maybe the Mouse is the problem here.

**Comment by alvarotrigo** [comment]
I think so. It seems to be working fine for me. 
Probably there's some lag using browserstack and using a magic mouse won't help.
