### ISSUE TITLE
Strange "jump" back to the top when navigating between slides and sections

### ISSUE THREAD

**Issue by tribou** [alvarotrigo/fullPage.js#1745]
I am trying to create a user experience that navigates down to a particular section, clicks a link, and opens up a set of slides on top of that section.  Then, they can close the slides to go back to the previous section.  I was able to produce the functionality here:

http://codepen.io/tribou/pen/GoreGw

However, there is a random glitch where every once in a while (not consistent), clicking `Close` sends you back up to the `One` section and then scrolls down to `Two` instead of initializing on `Two` as intended.

I was able to force the issue to surface by clicking the `Close` button rapidly (but I understand that is not the intended use).  Do you know what is causing the random jump back to the `One` section upon closing?

**Comment by alvarotrigo** [comment]
No idea, it seems sometimes the plugin gets initialized before the `active` class has been added. 
But I don't think this is a plugin's bug. It seems to me it is more about Javascript.
