### ISSUE TITLE
Possibility to move to the next slide instead of going down to the next section when user scrolls down?

### ISSUE THREAD

**Issue by bpyrate** [alvarotrigo/fullPage.js#1746]
Hi all,

when you build your fullPage website with sections and sliders in some sections, there might be the possibility that some users miss the slides because they do not recognize them and scroll down again.

Is there an option to move to the next slide within a section if the user scrolls down? I want the users to look at every section and every slide if they just scroll down or use the keybord down arrow.

Thanks for any help!

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/316

**Comment by alvarotrigo** [comment]
Possible now through [the fullpage.js extensions](http://alvarotrigo.com/fullPage/extensions/).
