### ISSUE TITLE
How to hide top nagivation for first slide

### ISSUE THREAD

**Issue by codinglover** [alvarotrigo/fullPage.js#1749]
I am using fullpage js in wordpress and trying tried to make it in different ways but failed. For the first slide the navigation bar will be disabled or hidden.

Any suggestion ?

**Comment by alvarotrigo** [comment]
This forum is not to treat wordpress issues but fullpage.js ones.
Have you tried the [fullpage.js theme for wordpress](https://goo.gl/HuFudq)?
