### ISSUE TITLE
Browser history without anchors

### ISSUE THREAD

**Issue by Ouadie** [alvarotrigo/fullPage.js#175]
Is there a way to use navigated sections to browser history without using `anchors`

**Comment by sc0rp1d** [comment]
Maybe add this feature, but default set it disabled or add fallback for IE8 and another old browsers?

**Comment by alvarotrigo** [comment]
@sc0rp1d yeah, that might be a possibility. The issue is kind of related with [this other one](https://github.com/alvarotrigo/fullPage.js/issues/950) which could also be solved using push state.

**Comment by xohail** [comment]
Hi,

Is there a way, the sections contain HTML from a different page like section#1 load page1.html and section#2 loads page2.html. I need them for different SEO values and Facebook OG tags. 

I am kind of stuck. fullpage.js does everything I need except this which I am looking for
