### ISSUE TITLE
adding external link to slides will only apply the first one

### ISSUE THREAD

**Issue by horans** [alvarotrigo/fullPage.js#1750]
when adding external link to slides in a section,

    <div class="section">
        <a href="page1.html"><div class="slide slide-1"></div></a>
        <a href="page2.html"><div class="slide slide-2"></div></a>
        <a href="page3.html"><div class="slide slide-3"></div></a>
    </div>

will resulted as,

    <div class="section">
        <a href="page1.html">
            <div class="fp-slides">
                <div class="fp-slidesContainer">
                    <div class="slide slide-1"></div>
                    <div class="slide slide-2"></div>
                    <div class="slide slide-3"></div>
                </div>
            </div>
        </a>
        <a href="page2.html"></a>
        <a href="page3.html"></a>
    </div>

which applies all the slides to first link.

======================
solution so far: write html as,

    <div class="section">
        <a href="page1.html">
            <div class="slide slide-1" data-link="page1.html"></div>
            <div class="slide slide-2" data-link="page2.html"></div>
            <div class="slide slide-3" data-link="page3.html"></div>
        </a>
    </div>

and within the initialization of `fullPage`,

    onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){
        //change slide link
        var sect = $('.full-page .section:eq(' + (index - 1) + ')');
        var next = sect.find('.slide:eq(' + nextSlideIndex + ')');
        sect.children('a').attr('href', next.data('link'));
    }

**Comment by alvarotrigo** [comment]
Adding a link to a `div` is semantically incorrect for HTML 4. Which means it shouldn't be used in old browsers. (IE <10).

In any case, I would go for something like this:

```html
<div id="fullpage">
  <div class="section">
    <div class="slide"><a href="#" class="full-link"></a>One 1</div>
    <div class="slide"><a href="#" class="full-link"></a>Two 2</div>
  </div>
</div>

```

```css
.slide{
    position:relative;
}
.slide a.full-link{
    position:absolute;
    width: 100%;
    height: 100%;
    display:block;
    z-index: 88;
    top:0;
    left:0;
}
```

[Example online](http://jsfiddle.net/97tbk/1029/)

**Comment by horans** [comment]
fair enough. thanks.
