### ISSUE TITLE
Content bigger than the height of section - affects anchor link in url (no slim scroll)

### ISSUE THREAD

**Issue by spindiesel** [alvarotrigo/fullPage.js#1751]
Hi,

I have uploaded an example of my site here http://scottmoselen.com/tests/brow101-full/#service_menu

Most of the sections on my site are larger than 100% height of the section, and I have auto scrolling:false set. When I scroll past the first section (where the content fits inside 100% height, the anchor link in the url bar changes at the correct time — half way between the sections (from #home   to #about).

However, after I scroll through the section where the content is bigger than the height of the section (from #about to #service_menu), the anchor link in the url changes too early. If scrolled slowly you will see if doesn't change half way between the sections, more like when only 1/4 of the next section is shown.

This problem occurs all the way down the site, as the user scrolls past the sections. I have experimented with adding an section where the content doesn't flow outside of the section, and that works fine. I have also experimented with removing all padding/margins etc on the content to see if it would have an effect, with no luck. I don't want to use slim scroll to have the user scroll within the section, I just want them to be be to scroll down the page naturally. 

I just wanted to know if there was a work around for this problem, as I need the anchor links in the url to change at the correct time.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/919

**Comment by alvarotrigo** [comment]
A solution has just been provided in this pull request: https://github.com/alvarotrigo/fullPage.js/pull/1752
You can try to implement the change by yourself until I examine it and consider it for the next release.

**Comment by spindiesel** [comment]
I just tried it now, seems to be working well! Can't believe the timing!
