### ISSUE TITLE
On Mobile - Page scrolls when your typing something

### ISSUE THREAD

**Issue by harshamv** [alvarotrigo/fullPage.js#1753]
When i am trying to write something on the mobile device. It starts scrolling and not allowing me to type the email address into the text box.

[Demo](http://creo.mink7.com)

On the landing page if you try to type the email address it starts scrolling on android devices.

**Comment by alvarotrigo** [comment]
I can type on iOS. The only problem there is that you don't see what you are typing. 
On Android I didn't see any problem on Browserstack with Android 4.4

**Comment by harshamv** [comment]
@alvarotrigo sorry i was trying out the responsive option. Can you try now. 

Any idea how to solve the issue of not able to see what am typing?

**Comment by alvarotrigo** [comment]
Same, I can still typing.

**Comment by harshamv** [comment]
you can type the content. But the page scrolls away to the next slide. I think i need to use the responsiveWidth to make this alright. i will test it out

**Comment by alvarotrigo** [comment]
> you can type the content. But the page scrolls away to the next slide.

Have you tried fullpage.js 2.7.4 ? Does it happens the same there? Can you please try it?

**Comment by harshamv** [comment]
no does not seem to work. trying to make it work with the responsiveWidth itself.

**Comment by alvarotrigo** [comment]
I would encourage you to get rid of auto scrolling by using the responsive options.

**Comment by harshamv** [comment]
yeah. thank you so much. i will try it out and reach out if i get stuck :)

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
