### ISSUE TITLE
Remove transforms from fullpage-wrapper on setAllowScrolling

### ISSUE THREAD

**Issue by renestalder** [alvarotrigo/fullPage.js#1754]
It seems that the transforms get removed on the slides, but not on the wrapper itself when setAllowScrolling is set to true. The translateZ hack used here can make problems with position fixed children.

**Comment by alvarotrigo** [comment]
Which translateZ are you talking about? fullpage.js only uses `transalte3d`.
Also, why do you mention setAllowScrolling? That only allows or denies the scrolling. It has no effect over any `translate property`.

**Comment by renestalder** [comment]
My fault. The setAllowScrolling has no effect on any translate value, you are right. 
What I meant with translateZ is the last value of translate3d. A setting of 0 is a setting (default is none). So hardware acceleration is activated, which is good during animations.

But I noticed the behaviour of position: fixed realigning occurs in all forms of transform properties. I just wondering if transform could be replaced with something different as long there is no animation happening which have to be accelerated, e.g. using top or a minus margin. That would solve any fixed position problem.

By now when I want to open a overlay modal in a section, I have to get the translate3d value of the fullpage.js wrapper, parse out the Y axis and put it on my fixed element e.g. a overlay. This works, but is a bit complex and maybe there could be a better solution.

```javascript
        var style = getComputedStyle(fullpageWrapper);
        var transform = style.transform || style.webkitTransform || style.mozTransform;
        var mat = transform.match(/^matrix3d\((.+)\)$/)
        if(mat) return parseFloat(mat[1].split(', ')[13])
        mat = transform.match(/^matrix\((.+)\)$/)
        var translateY = mat ? parseFloat(mat[1].split(', ')[5]) : 0
        mymodal.style.transform = 'translateY(' + translateY * -1 + 'px)'
```

I see plenty of topics here in the issue tracker about similar problems. But couldn't find a clean solution to this.

**Comment by alvarotrigo** [comment]
> I just wondering if transform could be replaced with something different as long there is no animation happening which have to be accelerated, e.g. using top or a minus margin. That would solve any fixed position problem.

Of course, just use `css3:false`.

**Comment by renestalder** [comment]
That would remove the hardware acceleration for anything even the scrolling. I guess the closed state is the sign for "I have to fix it for myself".

**Comment by alvarotrigo** [comment]
Why are you using a fixed positioned element? Why don't you just use an absoluted positioned one?

fullpage.js works with translate3d if you want hardware acceleration. There's no way to remove it if you want css3 animations.

**Comment by renestalder** [comment]
> Why are you using a fixed positioned element? Why don't you just use an absoluted positioned one?

Quite a good point. And it will work, but IMHO not fully progressive enhanced. If fullpage.js isn't initialise correctly, my overlay modals will also not show up as full page modals because they are positioned absolute and not fixed. The difference is clearly that with position fixed I can stick to bottom: 0 and top: 0 values while the position: absolute needs a container with height: 100% or a fixed pixel to height to work like this.

Or would you code a fullpage overlay with absolute position in any case?

> fullpage.js works with translate3d if you want hardware acceleration. There's no way to remove it if you want css3 animations.

Not sure my suggestion from my seconds post is a good solution, but I think the css transform is only needed during scrolling to get smooth experience via hardware acceleration. If the page isn't scrolled, wouldn't it be possible to set the position of the wrapper via margins and as soon scrolling occurs, replace it with transforms, then when scrolling ends, go back to margins? That sounds like a hack and want to know what possibly could go wrong.

**Comment by alvarotrigo** [comment]
Regarding your issue with modals, just use conditional CSS then.
If fullpage.js is initialized you will have the class `fp-enabled` in the `html` element. Therefore you can do this:

```css
.modal{
    position:fixed;
}
.fp-enabled .modal{
    position:absolute;
}
```

> If the page isn't scrolled, wouldn't it be possible to set the position of the wrapper via margins and as soon scrolling occurs, replace it with transforms, then when scrolling ends, go back to margins?

Not really.

**Comment by renestalder** [comment]
> Regarding your issue with modals, just use conditional CSS then.
I like that. That's a good solution. Thanks.

> Not really.

Why? When I make a quick test in Chrome Dev Tools I can't spot a visual difference. It will show the same active section.

**Comment by alvarotrigo** [comment]
> Why? When I make a quick test in Chrome Dev Tools I can't spot a visual difference. It will show the same active section.

You can't chage from transform to `margin` or `top` without a flicker. Plus it is just making things more complex when there's no need for it.

**Comment by renestalder** [comment]
> You can't chage from transform to margin or top without a flicker. Plus it is just making things more complex when there's no need for it.

I have to check how Velocity.js did its scroll handling because I hadn't these problems before. But I couldn't handle the periphery input correctly in my solution, that's why I changed to fullpage.js.

Anyway, thanks for your time. I'm just a very interested guy so I hope you didn't feel like I want to troll around. ;)
