### ISSUE TITLE
Next slide covers instead of pushing content up

### ISSUE THREAD

**Issue by lukehatfield** [alvarotrigo/fullPage.js#1755]
Hi. Thanks for the awesome plugin.

I'm building a site that should show the current slide getting covered up by the new page as the user scrolls down the page. Is it possible to do this with fullPage.js?

A little more description follows: 

Currently, a new section in the plugin fills a new screen area, and when you scroll down the page, it looks like the new sections push the previous sections up. What I'm trying to do is not push, but cover up the previous section. Hope that makes sense.

Thank you.

**Comment by alvarotrigo** [comment]
> Is it possible to do this with fullPage.js?

No, check out [pagePiling.js](http://alvarotrigo.com/pagePiling/) it might do what you want.
