### ISSUE TITLE
Trying to Make Arrow Next Prev instead dotted vertical navigation 

### ISSUE THREAD

**Issue by codinglover** [alvarotrigo/fullPage.js#1756]
Hello guys, I am completely new to fullpage just started few days ago, well everything seems to me is very perfect. But, I want something like arrow type next prev instead of the vertical dotted navigation of the page just like the slides so what is the possible way to make this. I am trying by my self but till now couldn't make it possible. So anyone can help me would be really great :)

**Comment by alvarotrigo** [comment]
> what is the possible way to make this. I am trying by my self but till now couldn't make it possible.

Create your own arrow elements with CSS or images or whatever.

Then assign to them the `$.fn.fullpage.moveSectionDown()` and `$.fn.fullpage.moveSectionUp()` events provided by fullpage.js.

If you don't know how to apply the events, just check one of the many demos online provided in the documentation which assign functions to buttons.

**Comment by codinglover** [comment]
Thank you for the help. Finally made it work now trying to hide the top navigation slider bar for the 1st slide. Any suggestion ?

Thanks once again

**Comment by alvarotrigo** [comment]
Same as before.

**Comment by codinglover** [comment]
alright thank you for reply backing. I am trying different things in case stuck in something again might need some help in future till than tc :)

**Comment by alvarotrigo** [comment]
I recommend you to ask in stackoverflow.com. This forum is not to treat javascript knowledge issues but only fullpage.js ones.

**Comment by codinglover** [comment]
Thank You :)
