### ISSUE TITLE
Configurable slimScroll.js

### ISSUE THREAD

**Issue by neil-s** [alvarotrigo/fullPage.js#1757]
When scrollOverflow is set to true, the scroll bar is always visible on sections with a lot of content. This is reproduced on your scrolling example page.

I'd like to have them only show up whilst scrolling, as is the default behavior in slimScroll. Would it be possible to add this as an option? Alternatively, are there any other workarounds you can suggest other than directly modifying my copy of fullPage.js at [this line](https://github.com/alvarotrigo/fullPage.js/blob/b21035962f78b1032f932947524ac26b890def3f/dist/jquery.fullpage.js#L2580)? I'm currently loading it from a CDN, so this would be less than ideal.

**Comment by alvarotrigo** [comment]
> Alternatively, are there any other workarounds you can suggest other than directly modifying my copy of fullPage.js at this line? I'm currently loading it from a CDN, so this would be less than ideal.

There are no other workarounds for now I'm afraid.

**Comment by alvarotrigo** [comment]
Changing to iScroll.js for the next release.
