### ISSUE TITLE
paddingTop option adds a gap between slides

### ISSUE THREAD

**Issue by yakareshka** [alvarotrigo/fullPage.js#1758]
Hi Alvaro,
I'm using a fixed header on my site with a paddingTop option for the sections, but this option adds a padding between sections instead of subtracting the height of my fixed header from the height of the sections, so I get a gap between my sections when scrolling the page down.

Here's what it looks like: https://jsfiddle.net/ya_kareshka/k8puc0tb/ (just scroll down).
 
The paddingTop option works now like this (in my case):
![current](https://cloud.githubusercontent.com/assets/10310866/12217787/23273d9a-b71c-11e5-8011-07ca14997d7c.png)
It doesn't decrease the height of the whole section, but it adds a top padding for the content inside of each section.
 
Why not get rid of top padding for each section content and just make the height of each section to fit the space under the fixed header?

This is what it would look like: 
![another](https://cloud.githubusercontent.com/assets/10310866/12217891/b62d84c0-b71f-11e5-89f5-6372d15b84c0.png)
Instead of adding paddin-tops for each section we just add a margin-top for the whole fullpage-wrapper (once) and derease the height of sections by the value of the paddingTop option.

Just take a look, no gaps between the sections:
https://jsfiddle.net/ya_kareshka/pad8z5zL/

**Comment by alvarotrigo** [comment]
If you have a better solution feel free to provide a pull request for it.

**Comment by yakareshka** [comment]
I'd love to, but unfortunately I'm not that good in JS. I just wanted to know what do you think about what I've written and to clear up for myself if the paddingTop is actually working properly or maybe my thoughts are not that bad.. :)

**Comment by alvarotrigo** [comment]
@yakareshka I believe it is working as it should. That's what a padding is.
