### ISSUE TITLE
How to use fullpage.js with angulrjs js? if yes what are steps and give example of that if possible

### ISSUE THREAD

**Issue by sagarjethi** [alvarotrigo/fullPage.js#1759]

**Comment by alvarotrigo** [comment]
Use the search for that:
https://github.com/alvarotrigo/fullPage.js/issues?utf8=%E2%9C%93&q=angular.js
https://github.com/alvarotrigo/fullPage.js/issues?utf8=%E2%9C%93&q=angular
http://stackoverflow.com/questions/28194672/fullpage-js-with-angular-js
http://stackoverflow.com/questions/24314414/how-to-full-page-with-angular-js

Not a question for this forum but for an angular one.

**Comment by sagarjethi** [comment]
hello @alvarotrigo  can we use this  : https://www.npmjs.com/package/angular-fullpage.js ??

**Comment by alvarotrigo** [comment]
No idea, you'd better ask there or in some other angular forum.

**Comment by alvarotrigo** [comment]
Update
===
A few angular directives are now available:

- https://github.com/meiblorn/ng2-fullpage
- https://github.com/hellsan631/angular-fullpage.js
- https://github.com/mmautomatizacion/angular-fullpage.js
