### ISSUE TITLE
Scroll to anchor on page load when using require.js

### ISSUE THREAD

**Issue by chuilee** [alvarotrigo/fullPage.js#1761]
Hi, i am using require.js to load fullpage.js. There's a problem that when i refresh my browser(url: localhost/index.html#page2).The page did't go to the second section.

**Comment by alvarotrigo** [comment]
Check out this and let me know if doing the change helps to solve the issue:  https://github.com/alvarotrigo/fullPage.js/pull/1396

**Comment by chuilee** [comment]
thx, it is helps. but <code>window.requestAnimFrame</code> would be undefined; i moved it forward;

**Comment by alvarotrigo** [comment]
Try moving this portion:

```javascript
        //IE < 10 pollify for requestAnimationFrame
        window.requestAnimFrame = function(){
            return window.requestAnimationFrame ||
                window.webkitRequestAnimationFrame ||
                window.mozRequestAnimationFrame ||
                window.oRequestAnimationFrame ||
                window.msRequestAnimationFrame ||
                function(callback){ callback() }
        }();
```
 Under 

```javascript
  displayWarnings();
```

**Comment by chuilee** [comment]
it is ok. : )
