### ISSUE TITLE
Scrolling up arrow hide but can't make it work ?

### ISSUE THREAD

**Issue by codinglover** [alvarotrigo/fullPage.js#1762]
I am trying to hide the arrow to go upwards for only 1st section but not working it still working. 

here is the code 
```javascript
  $.fn.fullpage({
      afterRender: function(){
           $('.fp-updown.up').hide();
      },
      afterLoad: function(anchor, index){
          if(index == 1){
               $('.fp-updown.up').fadeOut();
          }else{
               $('.fp-updown.up').fadeIn();   
          }
      }
  });	
```
Where  i am making the mistake ?

**Comment by alvarotrigo** [comment]
Provide a reproduction online in jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
Or feel free to ask in http://stackoverflow.com/. Your question is more for that forum than for this one.

**Comment by codinglover** [comment]
Alright alarotrgo thank you for all your quick replies :)
