### ISSUE TITLE
vertical-align: middle; -make section non-aligned?

### ISSUE THREAD

**Issue by Jonatan-r** [alvarotrigo/fullPage.js#1763]
Hello.
Awesome plugin. Thank you very much for making it!
I just have a little problem.. dunno if its just because I'm using webflow, and some weird css interference is happening? Anyways just to let u know. I think the screenshots explains it.

<img width="720" alt="skaermbillede_2016-01-12_kl__17_00_35" src="https://cloud.githubusercontent.com/assets/12435604/12268890/0cc41638-b94f-11e5-8d5d-c93ff78623d7.png">
<img width="721" alt="skaermbillede_2016-01-12_kl__17_00_39" src="https://cloud.githubusercontent.com/assets/12435604/12268940/491e4c70-b94f-11e5-9495-49ec3ac1f3da.png">

**Comment by alvarotrigo** [comment]
Use the fullpage.js option `verticalCentered:false`.
