### ISSUE TITLE
"Sticky" Footer Implementation (not fixed)

### ISSUE THREAD

**Issue by vdMark** [alvarotrigo/fullPage.js#1764]
Hi,

How would I be able to implement a "sticky footer"?

http://ryanfait.com/sticky-footer/
(Documentation: http://ryanfait.com/resources/footer-stick-to-bottom-of-page/ )

This kind of footer sticks to the bottom, but will always be located beneath the content.

I have tried to add the markup from the documentation (making the div#fullpage work as body), but it doesn't really work..

Best regards,
Christian Mark

**Comment by alvarotrigo** [comment]
Not a question for this forum. 
That's about javascript knowledge rather than about fullpage.js features / issues.
