### ISSUE TITLE
"touchSensitivity" does not appear to be working for iOS (tested with iOS 9.1 + iPhone 6)

### ISSUE THREAD

**Issue by dsiglin** [alvarotrigo/fullPage.js#1769]
I've been testing the mobile version of my site on Android 4.4 and iOS9.1 and while changing touchSensitivity setting works as expected on Android, it seems to be ignored on iOS. For instance I put touchSensitivity to "75" and as expected the Android device required a swipe equal to 75% of the screen. The iOS device seems to be using the default 5%.

I have tested with autoScrolling set to both "true" and "false". Android works, iOS does not. I would test using the sample page but I don't see any option to change touch sensitivity.

    <script type="text/javascript">
            
        $(document).ready(function() {
                $('#fullpage').fullpage({
            scrollingSpeed: 800,
            fitToSection: true,
            fitToSectionDelay: 500,
            css3: true,
            scrollBar: false,
            autoScrolling: false,
            touchSensitivity: 75,
            normalScrollElementTouchThreshold: 5,
            controlArrows: true,
            recordHistory: true,
            keyboardScrolling: true,
            animateAnchor: false,
            sectionSelector: '.section',
            slideSelector: '.slide',
            slidesNavigation: true,
            slidesNavPosition: 'bottom',
            sectionsColor : ['#1c1c1c', '#1c1c1c', '#1c1c1c', '#1c1c1c', '#1c1c1c', '#1c1c1c', '#1c1c1c',],
            verticalCentered: false,
            anchors:['Home', 'Mobile', 'Lifestyle', 'Street', 'Travel', 'Projects', 'Connect',],
            menu: '#mymenu'     
            }); 
        }); 
    </script>

**Comment by alvarotrigo** [comment]
Can you please try it again changing the following line ([944 in the latest fullpage.js 2.7.6](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L944))

```javascript
   if (Math.abs(touchStartX - touchEndX) > (window.outerWidth / 100 * options.touchSensitivity)) {
```
For the following one:

```javascript
   if (Math.abs(touchStartX - touchEndX) > (window.width() / 100 * options.touchSensitivity)) {
```

Do you still having the problem now?

**Comment by dsiglin** [comment]
Found the problem. I had to add `$` to `(window.outerWidth / 100 ...)` Either `window.outerWidth()` or `window.width()` will work. Btw - I noticed the height is set to `window.height` while the width is set to `window.outerWidth`.

**Comment by alvarotrigo** [comment]
> Found the problem.

I wonder where, because fullpage.js latest version has it right...

**Comment by alvarotrigo** [comment]
And if you are not using the latest... you really should :) 
It won't be any change for you if you are using 2.X. And the [list of solved bugs and improvements is quite big](https://github.com/alvarotrigo/fullPage.js/releases)...

**Comment by dsiglin** [comment]
I thought I had a vanilla version of 2.7.6 installed. I'll reinstall all the files then to make sure I have everything up to date.

**Comment by alvarotrigo** [comment]
> I thought I had a vanilla version of 2.7.6 installed

Nop, the vanilla version is in Beta version (0.0.8).

**Comment by dsiglin** [comment]
In beta 2.7.7 the `$` is missing along with the `()` - line 1152. I thought we shouldn't use the alphas because they aren't supported.

**Comment by alvarotrigo** [comment]
Nothing is missing. That's javascript, not jQuery.

**Comment by dsiglin** [comment]
Sorry I missed typed the line number, I meant 1052 not 1152. 

Hmm...well adding the `$` made it work for me so I'm happy either way, just wanted to be clear I was seeing the same problem in 2.7.7
