### ISSUE TITLE
Unable to get 'afterLoad' working...

### ISSUE THREAD

**Issue by notxalckram** [alvarotrigo/fullPage.js#1770]
Hi. 

I'm using the 'afterLoad' option which i've seen working in other examples 'callbacks.html' for example, but I can't seem to get it working. Can you help?

HTML
```HTML
        <div class="section" id="section2">
            <div id="macbook">
            </div>
        </div>
```

jQuery
```javascript
		$(document).ready(function() {
			$('#fullpage').fullpage({
				afterLoad: function(index){
					if(index == 2){
						$('#macbook').fadeIn(500);
					}
				},
			});
		});
```

**Comment by alvarotrigo** [comment]
Check [the example online](http://codepen.io/alvarotrigo/pen/XbPNQv) provided in the documentation.
