### ISSUE TITLE
Tooltip from HTML selector or data-attribute like anchors

### ISSUE THREAD

**Issue by VIEWSION** [alvarotrigo/fullPage.js#1771]
It would be great to define the tooltips within the HTML structure with a selector (for example ".title") or an additional data attribute like it is possible with anchors.

**Comment by alvarotrigo** [comment]
The navigation is created dynamically so unless you want to create the whole navigation yourself, this doesn't make much sense.

**Comment by VIEWSION** [comment]
Thank you for your quick replay... why does it not make sense as an option? I did it by collecting the tooltip array before like:

var tooltips = [];
$('.pnlSnap > div .title').each(function(){
   tooltips.push($(this).text());
});
	    
$('.pnlSnap').fullpage({
   //Navigation
   menu: '#menu',
   navigationTooltips: tooltips,
...

**Comment by alvarotrigo** [comment]
Mmm I don't know what is your `'.pnlSnap > div .title'` but I guess it can make sense if add them in the sections instead:

```html
<div class="section" data-anchor="First" data-tooltip="First"></div>
``

I rectify my previous answer, it makes sense that way :)

**Comment by VIEWSION** [comment]
great... .pnlSnap > div are my sections actually ;) data-tooltip is perfect! thx

**Comment by alvarotrigo** [comment]
Added in 2.7.7.
