### ISSUE TITLE
Fullpage.js website scrolls very slow and delayed on the mobile

### ISSUE THREAD

**Issue by Artegra** [alvarotrigo/fullPage.js#1775]
Hello and thank you very much for such an amazing plugin. I'm using it on my website, everything works perfect on desktop but on the mobile (phone & tablet) the sections are scrolling extremely slow and with delay. Not only the sections, overflowed sections with actual scrollbar are also scrolling very slowly inside. This is the case at least for the Android, I haven't tried it on iOS yet. I'm also not sure if the fullpage.js is the cause of this but other pages in my site without plugin doesn't have this problem. Also maybe worth mentioning that the slides doesn't have this problem, only the sections and vertical scrolling.

This is the link to my website: http://www.artegradesign.com

I'll be glad if you can help me with this issue, thanks!

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/506
