### ISSUE TITLE
Is it possible to end fullpage.js after a few sections?

### ISSUE THREAD

**Issue by Artegra** [alvarotrigo/fullPage.js#1776]
When scrollbar in enabled in fullpage.js it makes the website scroll extremely slow (almost unscrollable) on the mobile devices. Also slimscroll has the same problem, so I'm trying to find an alternative way. Without the scrollbar website works fine but I don't want to use slimscroll as well so I'm trying to put the scrollable divs out of the fullpage.js in the markup. But anything below the fullpage.js sections are not visible and I can't scroll down to view them. Is there any way to achieve this?

Thanks.

**Comment by alvarotrigo** [comment]
> When scrollbar in enabled in fullpage.js it makes the website scroll extremely slow (almost unscrollable) on the mobile devices.

I guess this depends on your site performance, [the provided example](http://alvarotrigo.com/fullPage/examples/scrollBar.html) seems to works totally normal.


> But anything below the fullpage.js sections are not visible and I can't scroll down to view them. Is there any way to achieve this?

Not without a scrollbar.

The only thing you can try to do is change slimScroll for iScroll.js, check out [this topic for it](https://github.com/alvarotrigo/fullPage.js/pull/1543) where you'll find the gist.
