### ISSUE TITLE
how to scroll horizontal

### ISSUE THREAD

**Issue by breathlife** [alvarotrigo/fullPage.js#1777]
sorry,after i read api,i don't konw how to scroll horizontal,anybody can tell me or author can add new opt to set horizontal scroll.thx

**Comment by alvarotrigo** [comment]
If you mean, horizontal scroll with the mouse wheel or trackpad, there's no such option.
[There's an open topic about it](https://github.com/alvarotrigo/fullPage.js/issues/316).

I'll close this one to keep only one.

**Comment by breathlife** [comment]
got it,i used pagepiling
