### ISSUE TITLE
[Question] Disable touch swipe gesture

### ISSUE THREAD

**Issue by bluufoox** [alvarotrigo/fullPage.js#1779]
Hi Alvaro, I'm planning to use fullpage.js but I'm searching a way to disable the touch swipe gesture (left to right) to navigate between slides (especially on mobile devices). I'm reading the docs but I can't find nothing. Do you have any idea?

Many thanks for your work Alvaro.

**Comment by alvarotrigo** [comment]
[setAllowScrolling(boolean, [directions])]https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions)

**Comment by bluufoox** [comment]
Hi Alvaro, I've assumed that this option does not include the "swipe gesture" (my bad).

This option helps me but the navigation arrow buttons "left and right" are also disabled. I'm looking for a way to disable this option only in windows with less than 900px resolution.

i'm working on this lines.

````javascript
if ($(window).width() > 900)  {
	$.fn.fullpage.setAllowScrolling(false, 'left, right');
}
````

but do nothing by now...

Many thanks for your time, your answer help me to find a way.

**Comment by alvarotrigo** [comment]
You'll have to ask in other place if you ask for javascript advise.
The plugin doesn't provide any shortcut for you in this matter.

**Comment by bluufoox** [comment]
Maybe it is useful to someone

````javascript
$(window).load(function(){
	if ($(window).width() <= 900){	
		$.fn.fullpage.setAllowScrolling(false, 'left, right');
	}	
});
````
