### ISSUE TITLE
After reinit fullpage mousewheel sliding go to last slide

### ISSUE THREAD

**Issue by codev0** [alvarotrigo/fullPage.js#1780]
Hi.
I have issue. After reinit fullpage mousewheel sliding go to last slide.
http://jsfiddle.net/s5huzx9p/2/
Try resize result frame.

**Comment by alvarotrigo** [comment]
Wrong way of reproducing your issue. 
[Check this out](http://jsfiddle.net/s5huzx9p/4/), it works as expected. The problem is not in fullpage.js but in your own javascript code.
