### ISSUE TITLE
Question - disabling fitToSection for fp-auto-height section

### ISSUE THREAD

**Issue by dsiglin** [alvarotrigo/fullPage.js#1781]
I'm using fp-auto-height for the opposite of what it was intended. Instead of allowing an elegant half-sized footer I'm using it to have a larger than screen-height footer. It works well except for one thing. I have fitToSection enabled and so after the fitToSection delay the browser scrolls so that the bottom of the fp-auto-height section is on screen. That forces the top part of the section off the screen. Is there currently any way to disable fitToSection for just one section? Thanks.

**Comment by alvarotrigo** [comment]
Try using [the version under development](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js). (2.7.7 Beta)

> Is there currently any way to disable fitToSection for just one section? Thanks.

And yeah, just use the method [`setFitToSection`](https://github.com/alvarotrigo/fullPage.js#setfittosectionboolean) within a callback.

**Comment by dsiglin** [comment]
Hey, so I think I *finally* have a solution for this. The problem is I don't know why it works. Would you mind explaining why this works. Here's what I have:

$(document).ready(function() {
    $('#fullpage').fullpage({
            fitToSection: true,

            onLeave: function(index, nextIndex, direction){
                //var destination = $('.fp-section');
                if(nextIndex == 6 && direction == 'down'){
                    return false;
                } else {
                    $.fn.fullpage.setFitToSection(true);
                }
            }

        }); 
});
