### ISSUE TITLE
Wrong index on `afterLoad`

### ISSUE THREAD

**Issue by dowsanjack** [alvarotrigo/fullPage.js#1782]
My testing site is: http://web2developer.in.md-in-26.webhostbox.net/themes/ideathemes/awesome-ideas/

After a few scrolls, the index is skipping by one.
I've made few logs in console, so that you can have a look. 

After the 3rd index, it is showing 5. Though the scroll is working fine. Even the `fp-viewing-` class is being skipped.

Can you please have a look, to determine the issue.

Thanks,

**Comment by alvarotrigo** [comment]
You would need to reproduce the issue in an isolated environment (no external JS and CSS). Ideally in jsfiddle or codepen.

**Comment by dowsanjack** [comment]
Sorry, could not be reproduced. Fiddle is working great. Any tip, where things might go awry, would be appreciated.
