### ISSUE TITLE
data-anchor attributes on div sections are set to default

### ISSUE THREAD

**Issue by ecabigting** [alvarotrigo/fullPage.js#1783]
Hi Alva!

Love your work! its awesome! But, im having a small problem, i want to customize the anchors shown in my URL. Example, http://example.com/index.html#home. I followed your guides and such and everything looks good, except when I use my links they dont scroll to the correct section, as in not scrolling at all. and then i noticed, the sections are given the default data-anchors ie: section1, section2. 

Thanks so much for your work. :)

ps. i uploaded my site in my repo: https://github.com/ecabigting/ecabigting.github.io :) so if you want to see for yourself.

**Comment by alvarotrigo** [comment]
> i noticed, the sections are given the default data-anchors ie: section1, section2.

There are no such thing as default `data-anchors`.

You are adding them in your initialization:
https://github.com/ecabigting/ecabigting.github.io/blob/master/js/superjs.js

**Comment by ecabigting** [comment]
ok, thats embarrassing. Thank you so much alva! cheers!
