### ISSUE TITLE
Rendering bug when transitioning from one slide to another

### ISSUE THREAD

**Issue by DovydasS** [alvarotrigo/fullPage.js#1785]
Hi there,

We are developing a website using your JS. (see here http://kemdu.lt/mangali/)

However, we noticed, that when transitioning from the first slide to another, the second slide's content moves to the right by 20% or more of the viewport, just for a split second before it is rendered properly. 

This is only found on Google Chrome browser (newest version Version 48.0.2564.82 m)

Any ideas as to why could this be happening?

**Comment by alvarotrigo** [comment]
Please reproduce the issue in an isolated environment (no external JS and CSS). Ideally in [jsfiddle](http://jsfiddle.net/97tbk/418/) or codepen.

**Comment by alvarotrigo** [comment]
I'll close the issue until the reproduction is provided.
