### ISSUE TITLE
[Request] Add paddingLeft and paddingRight to available options

### ISSUE THREAD

**Issue by NipSauce** [alvarotrigo/fullPage.js#1786]
Love this script! Great job!

I have now decided to put my header to the side instead of to the top of the page because of the flow of my website. The only issue is that your script allows for the options paddingTop and paddingBottom but not to the sides. It would be really nice if you could implement that in your next release.

Cheers!

**Comment by alvarotrigo** [comment]
My recommendation is that you don't make use of the `paddingTop` option and do it manually using CSS:

```css
#section3 .slide{
        padding-top: 90px;
}
```

**Comment by NipSauce** [comment]
Sorry if I didn't explain good enough.

I want padding on the left side, not from the top.
In this release you have the option "paddingTop: *value*". I wish something similar but for the sides, as in: the option "paddingLeft: *value*".

**Example**
```javascript
$('#fullpage').fullpage({
    paddingLeft: 100,
    someOtherOption: false
});
```

Do you understand me?

**Comment by alvarotrigo** [comment]
So again, why don't you go for CSS ?

The paddingTop option only exists because its easier to deal with `scrollOverflow:true` in case they use it.

**Comment by NipSauce** [comment]
Aw man, I just tried your tip and it worked perfectly. I guess my brain is tired, it's so simple! Hahah. I think I should take a break from coding now. Thank you!

You can close this issue now.

**Comment by faliqaiman** [comment]
good one
