### ISSUE TITLE
How to get slider to move to the right on last photo?

### ISSUE THREAD

**Issue by omarel1** [alvarotrigo/fullPage.js#1789]
I noticed that when you scroll through a slider that resides in a slide, when you reach the last image, instead of moving to the right and starting at photo 1 it quickly moves left going through all the photos. 

Is there  a way to make it just continue moving one slide to the right and just start back at the first photo?

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/124
