### ISSUE TITLE
Continuous Mode on Pure JS Version

### ISSUE THREAD

**Issue by willianjusten** [alvarotrigo/fullPage.js#1792]
Hi @alvarotrigo, it's to complicated to implement the continuous mode on pure version? I tried to move the last item to the top, each time that I scroll, but because of use of translate, doesn't work properly.

Do you know another way that I can do?

**Comment by alvarotrigo** [comment]
The documentation for the javascript version says:

> This light version of fullpage.js won't provide some options available in the jQuery version such as:
- scrollOverflow
- verticalCentered
 - **continuousVertical**
- ...

**Comment by alvarotrigo** [comment]
If you really need it, you can always [contact me](http://alvarotrigo.com/#contact-page) for a customization.
