### ISSUE TITLE
Slide elements appear just after resizing the browser's window

### ISSUE THREAD

**Issue by umbecanessa** [alvarotrigo/fullPage.js#1795]
Hey, first awesome js. i love it.

But now I'm facing an annoying problem, when i load the page the content of the slide under section doesn't show up, it appears just only after I resize the browser's window. I already try with css3:false and transform3d fix you suggest on a past question, but nothing.

**Comment by alvarotrigo** [comment]
Unless you are able to reproduce it in an isolated environment (in jsfiddle or codepen) i won't be able to help you. 
In any case, this seems a problem of design, not a fullpage.js one. 

I'll close the issue until the reproduction is provided. But I would suggest you to ask this questions in http://stackoverflow.com/ as this is probably not a fullpage.js issue.
