### ISSUE TITLE
Any chances to do submenu?

### ISSUE THREAD

**Issue by faliqaiman** [alvarotrigo/fullPage.js#1796]
Hello. Im not very strong with jquery/js. Any trick to do submenu and arrow navigate like image below?

![wfebwkuf](https://cloud.githubusercontent.com/assets/16832340/12571936/3641baa6-c421-11e5-9492-1a09092e97ac.jpg)

**Comment by alvarotrigo** [comment]
> Im not very strong with jquery/js. Any trick to do submenu and arrow navigate like image below?

The plugin doesn't provide a way to do it. You would have to do it by yourself.
