### ISSUE TITLE
Scroll to top of section instead bottom when using sections bigger than the viewport

### ISSUE THREAD

**Issue by thomaseilander** [alvarotrigo/fullPage.js#1797]
Hi!

I have three sections. My second section has more content then the height of the viewport. Section 1 and 3 have less content and have the same height as the viewport.

When I navigate from section 1 to section 2 (from the linked navigation menu), it scrolls till the BOTTOM of section 2 hits the BOTTOM of my screen. How can I let it stop scrolling when the TOP of section 2 hits the TOP of my screen??? I of course want my visiter to start reading at the top of section 2.

Stangly enough however, when I navigate from section 3 back to section 2 it DOES stop when the TOP of section 2 hits the TOP of my screen. 

Anyone???

**Comment by thomaseilander** [comment]
Link: http://www.santhos.nl/swbb/

Just hit 'Keurmerk'. You see it scroll down to far.

When you first navigatie to 'Leden' and then back to 'Keurmerk' it stops at the right place.

Hope someone can help.

**Comment by alvarotrigo** [comment]
It seems you are using a trackpad or a magic mouse kind of device:

Duplicated issue: https://github.com/alvarotrigo/fullPage.js/issues/1539

**Comment by thomaseilander** [comment]
Hi,

wow that was closed fast. I don't think you understood me right. I'm not
talking about scrolling on a mouse / trackpad or whatever. I don't even
have one.

did you follow the link?

http://www.santhos.nl/swbb/

When you 'click' on Keurmerk you can see it scrolls to the BOTTOM of
section 2 instead of the TOP.

Tnx!

Thomas

2016-01-26 15:52 GMT+01:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
Sorry, went too fast about it.
Did you have the same problem using the previous version fullPage.js 2.7.6?

**Comment by thomaseilander** [comment]
Ah, just tried with v2.7.6 and seems to work fine!

**Comment by alvarotrigo** [comment]
I solved it in [the development version (2.7.8)](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by thomaseilander** [comment]
Tnx!

**Comment by dsiglin** [comment]
Thanks for fixing this, this solved my problems described in issue 1781 and means I don't have to use my hack anymore.

**Comment by Taapo** [comment]
While in 2.7.8 this is solved when scrolling to the **bottom**, it's not solved when scrolling back up -- there is still scrolls to the bottom of the div. Can this be fixed?

**Comment by alvarotrigo** [comment]
@Taapo Please provide a reproduction of it so I can see what you mean.

**Comment by Taapo** [comment]
@alvarotrigo -- look here: http://fullpage.preview.taapo.com/

When you scroll down, every slide stops at the top of the slide - which is de intended outcome. When you are at the bottom, and you slide back up again, each slide stops at the "bottom" of the slide. Do you see what I mean?

**Comment by alvarotrigo** [comment]
> When you are at the bottom, and you slide back up again, each slide stops at the "bottom" of the slide. Do you see what I mean?

That's how it is suppose to work. If you have a long section you want them to see the bottom of it when you scroll up to it. That makes total sense to me.

**Comment by Taapo** [comment]
hmmm, ok - I can understand where you are coming from. But is this something that could be implemented as an option? Top/bottom/middle behaviour? Or is this outside the scope of what you want to do with it?

**Comment by ReneHetzel** [comment]
at first, thanks for 2.7.8. This version solves my problems with big content sections.
Now i have the same problem like Taapo. I use **$.fn.fullpage.moveTo(1)** to slide to the top of the page. If the section is bigger than the viewport it slides to the bottom of the first section instead of the top.

**Comment by alvarotrigo** [comment]
@ReneHetzel @Taapo there's no solution for it yet. If you are in a hurry, feel free [to ask for an urgent request](http://alvarotrigo.com/#contact-page).

**Comment by mlimasolucoes** [comment]
Hello alvorotrigo, first of all thanks for this fantastic plugin.
We have the same problem here, scroll snap back to top sounds like a more beautiful behaviour then actually is. []'s

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.8.

**Comment by ReneHetzel** [comment]
Hi, i included the new version 2.7.8 but it doesnt work for me.
The same problem when i click on the nav bar dots or if i use $.fn.fullpage.moveTo(1)
Is there is a new option which must be set?

**Comment by ReneHetzel** [comment]
@ frist ... sry for my bad english :( 

Is it possible to get the last beta 2.7.8 (19 days ago)? 
I unfortunately overwritten the file with the final version 2.7.8 :(

There is a new bug in the final version. Example: when the page is loaded the first time and i move down from section1 to section2 by using the nav bar or $.fn.fullpage.moveSectionDown(); it navigates to the top of the next section ... perfekt. But when i scroll or move back from section2 to section1 all move events after will navigate to the button of the selected section.

many thanks in advance

**Comment by alvarotrigo** [comment]
@ReneHetzel marked as an enhancement in https://github.com/alvarotrigo/fullPage.js/issues/1854

**Comment by sohrabzia** [comment]
hi, thanks for the plugin, It does not fixed the issue in 2.7.8. my section ( bigger then view port height ) is scrolling to the bottom automatically.

**Comment by alvarotrigo** [comment]
@sohrabzia there's [an open issue about this topic](https://github.com/alvarotrigo/fullPage.js/issues/1854).
The default at the moment now is:

> fullPage.js will animate to the top if you come from a section above the destination one.
It will animate to the bottom if you come from a section below the destination one.

**Comment by sohrabzia** [comment]
I got your point, I have section bigger then the view port height, when i navigate to that section it goes to top of that section but after a moment it automatically scrolls to bottom of same section. which is not enough time to see what is at the top of section as it scrolls up automatically.

**Comment by tomwatras** [comment]
Hi guys, I had had the same problem and finally I've found the way to fix it. The problem is with section that contains scrolling, so in scrolling method you need to add additional line of code: 

**$('.fp-scroller').css('transform','translate(0px, 0px) translateZ(0px)');**

```
$('a.page-scroll').bind('click', function(event) {
     $('.fp-scroller').css('transform','translate(0px, 0px) translateZ(0px)');
     $.fn.fullpage.moveTo('section1');
     event.preventDefault();
});
```
This fix reset transformation coordinates of scrolling object before move to specific section.
