### ISSUE TITLE
Swipe down to refresh 

### ISSUE THREAD

**Issue by avxto** [alvarotrigo/fullPage.js#1798]
On mobile browsers swipe down to refresh doesn't work when this jQuery plugin is initialized..

**Comment by alvarotrigo** [comment]
I'm not quite sure of which kind of plugin/componente, browser or OS you are talking about, but yep you are right. It probably won't work if it is something implemented in the browser. 

This plugin works blocking the default touch event of the page. 

The only solution I think of now would be adding your own touch handlers and detecting the direction yourself. But of course, this won't cause the elastic bouncing (if you have any...)

**Comment by alvarotrigo** [comment]
Closed as not enough information about the issue was provided.
