### ISSUE TITLE
Strange padding when using Bootstrap .row NOT inside a .container

### ISSUE THREAD

**Issue by ivanhalen** [alvarotrigo/fullPage.js#1800]
Hello, I need to have a full width content so I'm using Bootstrap .row directly into sections, not in a .container. I noticed a strange padding on bottom, and if you scroll down to following sections, the padding becomes on top

Here is a minimal example that shows the problem:
http://www.iwstudio.it/fullpage.php

Thank you

**Comment by alvarotrigo** [comment]
You'd better ask about it somewhere else such as http://stackoverflow.com/.
Your problem has nothing to do with fullpage.js.
