### ISSUE TITLE
Forget method on Javascript Pure version

### ISSUE THREAD

**Issue by willianjusten** [alvarotrigo/fullPage.js#1803]
Hey @alvarotrigo,

I'm using your Pure Version and I saw that you probably forgot to add the method `setAllowScrolling` [setMouseWheelScrolling - L684](https://github.com/alvarotrigo/fullPage.js/blob/master/pure%20javascript%20%28Alpha%29/javascript.fullPage.js#L684) on your revealing module.

This method is public on jQuery Version and works fine on Pure Version also.

**Comment by alvarotrigo** [comment]
I could add `setMouseWheelScrolling`, but to keep it consistent with the jQuery version I didn't do it.

There's no such method as `setAllowScrolling` in the javascript version and that's the method which disables both touch and mouse wheel handlers at the same time, which is probably what everybody will do.

I might add it in a near future without the direction options if that makes it faster for me.

**Comment by alvarotrigo** [comment]
fullPage.s version 3 doesn't require jQuery anymore. Therefore this problem doesn't exist anymore.
