### ISSUE TITLE
Change color on navigation circles

### ISSUE THREAD

**Issue by petkor** [alvarotrigo/fullPage.js#1804]
Hi, is it possible to change color on the circles in the navigation? It would be smooth.. =)

**Comment by alvarotrigo** [comment]
Of course, use CSS for it. If you don't know how, you'd better ask in other place such as http://stackoverflow.com/

**Comment by YvonneD** [comment]
In order to change the color of navigation dot, I overwrite css, but it doesn't work. Is that correct? How can I check why the color doesn't change.Thanks.
`#fp-nav ul li a span, .fp-slidesNav ul li a span{
	background: #fff;
}` @alvarotrigo

**Comment by alvarotrigo** [comment]
Use `!important` just in case. Anyways, this is a CSS knowledge question. you'd better ask in other place.

**Comment by Pedroluarez** [comment]
Hi Sir! @alvarotrigo how about, set the Active color of Navigation Dots.
Sample the base color of Navigation dots is white and Active color is Black.

I tried to use .active Selector but the color I set only appeared when I click then after a click the navigation dots turns to default color. I also add !important but I can't get what I want output.

**Comment by alvarotrigo** [comment]
That's just CSS. You can overwrite any default styles as you wish.
If you don't know how to, I would recommend you to ask in another place such as stackoverflow.com where they'll be able to help you much better regarding CSS.
