### ISSUE TITLE
Embed images from 500px in slides

### ISSUE THREAD

**Issue by mindkontrol** [alvarotrigo/fullPage.js#1805]
I'm thinking if somehow it's possible to embed images from 500px in slides. Just like this one:

`<div class='pixels-photo'>
  <p>
    <img src='https://drscdn.500px.org/photo/128726623/m%3D900/9b8d8995a1d91e4bbdcc556ecfcc21b9' alt='EL VY by Greg Chow on 500px.com'>
  </p>
  <a href='https://500px.com/photo/128726623/el-vy-by-greg-chow' alt='EL VY by Greg Chow on 500px.com'></a>
</div>
<script type='text/javascript' src='https://500px.com/embed.js'></script>`

Thanks.

**Comment by alvarotrigo** [comment]
I don't see why not: http://jsfiddle.net/97tbk/1059/

**Comment by mindkontrol** [comment]
Looks very good, but in this case is not possible to use text over the embed, right?
This was a problem too, but I forget to mention it earlier.

Thanks for your quick reply.

**Comment by alvarotrigo** [comment]
This is not a fullpage.js related issue. It has nothing to do with it.
