### ISSUE TITLE
Sections with scrollOverFlow not working well in firefox

### ISSUE THREAD

**Issue by arquadrado** [alvarotrigo/fullPage.js#1806]
Hello, it seems that sections with scrollOverFlow don't work well in firefox. When I ge there I can't use my mouse wheel to go over the section content nor to go to another section, I have to use my keyboard to get out of the section and click right in the scrollbar to go over the content. Is there a way to fix this?

Thanks

**Comment by alvarotrigo** [comment]
[The provided example](http://alvarotrigo.com/fullPage/examples/scrolling.html#3rdPage) seems to work fine in Firefox in Mac.

Can you provide more details and a reproduction of the issue?

**Comment by arquadrado** [comment]
The issue is due to a conflict between scrollOverFlow and the scrollBar in Firefox, I managed it by deactivating the scrollbar for firefox.

**Comment by alvarotrigo** [comment]
`scrollOverflow:true` won't work well with `scrollBar:true`if that's what you mean. It doesn't make sense to have 2 scroll bars. 

The plugin won't provide support for that.

**Comment by arquadrado** [comment]
It works on chrome. It's solved for now anyway thanks!
