### ISSUE TITLE
Soft keyboard on the android pop-up input after input content pages that will be over

### ISSUE THREAD

**Issue by zhibo59** [alvarotrigo/fullPage.js#1807]
First of all thank you have you the so a good thing, but have some problems on android, when the input input that the entire page will be over after, according to the following content is out of the half, I don't know whether there is a way to solve this problem? If there is one can be told about? Thank you very much

**Comment by alvarotrigo** [comment]
I don't really understand what you are trying to say. Try explaining it in another way or with images.

Possible related with https://github.com/alvarotrigo/fullPage.js/issues/145

**Comment by zhibo59** [comment]
all right thinks

**Comment by alvarotrigo** [comment]
Closed until provided a better explanation of the issue.
