### ISSUE TITLE
Enable left & right navigation in slides instead of the normal carousel effect

### ISSUE THREAD

**Issue by JorgeLopezMx** [alvarotrigo/fullPage.js#1810]
Hello and thanks in advance for any help anyone can offer. 

We have searched many forums and sites looking for a way to make this happen and could not find any solution, this is our last resort. Really hoping anyone can help. 

This is our site: www.mogtaller.com it is built on wordpress and we integrated the fullPage.js it works perfectly. 
The issue is the following: Right now you can only navigate between slides only to the right, if you clic left it has a carousel effect that takes you through the whole 3 slides. We would like for users to navigate either left or right without having to go through all of the slides. 

Hope we were clear, please see attached image for a visual representation of what we are looking to achieve. 

![mog_navigation_attempt](https://cloud.githubusercontent.com/assets/17055563/12802693/4daf27fc-caaa-11e5-93bd-4ee08d62748b.jpg)

So on vertical scrolling you should arrive to the first slide then click left go to the second click right and go back to the first slide, click right again and go to the 3d slide. 

Hope anyone can help! It would be greatly appreciated.

thanks in advance,
J.

**Comment by alvarotrigo** [comment]
As detailed in [the docs](https://github.com/alvarotrigo/fullPage.js#required-html-structure):

> If you want to define a different starting point rather than the first section or the first slide of a section, **just add the class active to the section and slide you want to load first.**
