### ISSUE TITLE
onLeave index incorrect when there's content before #fullpage

### ISSUE THREAD

**Issue by kangabell** [alvarotrigo/fullPage.js#1811]
I have a page with some regular content at the top and regular content at the bottom, with fullpage sections in the middle. I need to use the onLeave callback method for some things, but it seems that with this layout the function gets the index/nextIndex confused.

[codepen demo](http://codepen.io/kanga/pen/dGqgpq/)

If you remove the content above #fullpage, you will see that the logs make sense. However when it's there, it seems the function thinks that the stuff before #fullpage is index 1. Index of 1 should be the first section of #fullpage.

How do I get the function indexes to work properly?

**Comment by alvarotrigo** [comment]
I'll take a look at it at some point, but won't be high priority as fullpage.js is mean to be a FULL PAGE script and therefore nothing else is expected before or after the plugin wrapper (unless fixed elements).

**Comment by alvarotrigo** [comment]
This was probably fixed or not relevant anymore.
