### ISSUE TITLE
When trying to scroll back to top faster than animation it gets stuck at second section.

### ISSUE THREAD

**Issue by dara** [alvarotrigo/fullPage.js#1814]
This only happens with Safari 9 and css3 is option set to true. Please see [Apple example](http://alvarotrigo.com/fullPage/examples/apple.html).

**Comment by alvarotrigo** [comment]
Duplicated. https://github.com/alvarotrigo/fullPage.js/issues/1812

**Comment by dara** [comment]
Please do not close the issue yet. I don't think this is a duplicate.

**Comment by alvarotrigo** [comment]
> There's a strange problem in Safari 9 – when trying to scroll back to top faster than animation goes, scrolling gets stuck at section two – even though there's .fp-viewing-firstPage class on .
It seems that translate3D gets stuck at wrong value.

Sounds like so.
