### ISSUE TITLE
Auto scroll with scroll inside sections

### ISSUE THREAD

**Issue by alfgago** [alvarotrigo/fullPage.js#1815]
Hi, I'm loving your fullPage.js, just one usage question that I didn't find in manuals. How can I accomplish something like this?
http://newageironworks.net/

In that sample, on mobile you see how not everything fits in mobile, so they add an inner scroll inside some sections, and then auto scroll to the next section when it is finished. How can I do this?

Also, similar question, is there any way to make something like http://alvarotrigo.com/fullPage/examples/oneSection.html but with auto scroll only on the first section? 

Thank you, great script

**Comment by alvarotrigo** [comment]
It is detailed in the docs:

> scrollOverflow: (default false) defines whether or not to create a scroll for the section in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor plugin jquery.slimscroll.min and it should be loaded before the fullPage.js plugin. For example:

And you have an [example online](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by alvarotrigo** [comment]
> Also, similar question, is there any way to make something like http://alvarotrigo.com/fullPage/examples/oneSection.html but with auto scroll only on the first section?

You can try using a new option which haven't been yet tested: `hybrid:true` in combination with the addition of the class `fp-normal-scroll`in the sections you want to have normal scrolling.

[Example online](http://jsfiddle.net/97tbk/1062/).

**Comment by MikeThomasDev** [comment]
Thank you for the awesome plugin. In your answer here you refer to slimscroll.min, but in the fullpage.js docs you refer to scrolloverflow.min.js, does in matter which one I use?

**Comment by alvarotrigo** [comment]
slimscroll was replaced by scrolloverflow.min.js.

**Comment by MikeThomasDev** [comment]
Thank you Sir!

**Comment by liujoshua** [comment]
If you're using `hybrid:true` in combination with `fp-normal-scroll`, I recommend also setting `fitToSection: false`. 

Without `fitToSection: false`, the scroll will snap to the next slide after about two seconds. With  `fitToSection: false`, the scroll is entirely controlled by the user.

**Comment by Sylwia777** [comment]
Hi, firstly I would like to thank you for such a useful tool, I love fullPage.js
I have used hybrid:true in combination with fp-normal-scroll class on my website to achieve autoscroll only in first section and it works great

One question: there is autoscroll on first section -  while scrolling down, but when I scroll up it doesnt autoscroll back to section one. How can I achieve this - to auto scroll up? Here is an example:
http://ruya.ae/work/al-erkyah-city/

Many thanks,
Sylwia

**Comment by alvarotrigo** [comment]
@Sylwia777 sun away from the `hybrid` option and `fp-normal-scroll`. It is not supported. Expect bugs in certain cases.

**Comment by ecourdoisy** [comment]
Hi, thanks for your plugin ! I've a question about scroll navigation, I need to have one page but with two parts, like this for example : http://melaniedaveid.com/
Is it possible ?
Regards

**Comment by alvarotrigo** [comment]
@ecourdoisy many things are possible with the right knowledge, unfortunately fullpage.js doesn't provide what you want out of the box.
