### ISSUE TITLE
Slide directly to slideIndex of previous section

### ISSUE THREAD

**Issue by lakilevi** [alvarotrigo/fullPage.js#1819]
Hey!
I have 4 sections with 3 slides in each. 
What I want to make is that if I slide to the 2nd slide in the first section, and I scroll down, than in the next section I would jump to the 2nd slide directly. So the slideIndex from the previus section should match the slideIndex of next section. Is this possible?

I tried:
```
afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){           
            last_view_slideIndex=slideIndex;
        },
afterLoad: function( anchorLink, index){
            jQuery.fn.fullpage.moveTo(anchorLink, last_view_slideIndex);            
        },
```
but in this way, still loads first the first slide than jumps to the slide I want. So it is not sliding to the desired slide directly.
Is it a way to do this?

thanks a lot!

**Comment by alvarotrigo** [comment]
> So the slideIndex from the previus section should match the slideIndex of next section. Is this possible?

Unfortunately fullPage.js doesn't provide a way to do it and the way the plugin is designed won't allow you to scroll a slider while scrolling sections or any other slider at the same time.

**Comment by lakilevi** [comment]
Thank you very much for your answer!

**Comment by alvarotrigo** [comment]
Possible now with the [interlocked slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html).
