### ISSUE TITLE
Problems with fitting a section to viewport

### ISSUE THREAD

**Issue by noczesc** [alvarotrigo/fullPage.js#1820]
Example - blue section on a 1920x1080 monitor - http://codepen.io/noczesc/pen/NxExxY.

When I scroll and stop like this -> http://prntscr.com/a0xri5, fullpage.js resizes (good thing) scrolls to the bottom of the page automatically (bad thing) and then goes up to the beginning of the section. Is this a bug in my code or in the lib itself?

PS. Don't pay attention to the spaghetti code, it's a pre-alpha version of my first website.

**Comment by alvarotrigo** [comment]
You can not use `fitToSection` when you have section bigger than the viewport. It just doesn't make sense as there's no proper way to fit a bigger section. 

Just use `fitToSection:false`.
