### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by Dorababu743** [alvarotrigo/fullPage.js#1821]
I would like to add up and down arrows to so that when I click on down arrow it should open the next section.

**Comment by alvarotrigo** [comment]
Use the fullpage.js functions `moveSectionUp` and `moveSectionDown` as detailed in the docs.

Regarding the arrows, that's something you will have to do by yourself with CSS and HTML, the plugin doesn't provide such options.

**Comment by Dorababu743** [comment]
If i add the arrows bottom and down will it work with the functions that specified

**Comment by alvarotrigo** [comment]
Not by magic. You'll need to assign the functions to them by using javascript or jquery.

**Comment by alvarotrigo** [comment]
Take a look at the provided demos: https://github.com/alvarotrigo/fullPage.js#movesectionup

**Comment by Dorababu743** [comment]
Thanks alvarotrigo I got the required one
