### ISSUE TITLE
Window.resize fn.destroy throws - Uncaught TypeError: $.fn.fullpage.destroy is not a function

### ISSUE THREAD

**Issue by gorankrgovic** [alvarotrigo/fullPage.js#1822]
I'm using the following function to destroy the fullPage on window size smaller than 1024px using Modernizr.mq

```
var fullPageInit = function(){
    if (Modernizr.mq('(max-width: 1024px)')) {
       // Remove full page
        if ( $('.full-page').length ) {
	    // Destroy all	
            $.fn.fullpage.destroy('all');
        }

    } else {
        if ( $('.full-page').length ) {
            $('.full-page').fullpage({
                autoScrolling: false,
                fitToSection: false
            });
        }
    }
}

$(function() {
    // Call on every window resize
    $(window).resize(fullPageInit );
    // Call once on initial load
    fullPageInit();
});
```
Everything works fine when you are loading the site with larger screen size than 1024px. But if you try to load the site from a smaller device (mobile, or whatever) as defined in function - the console throws an error 

`Uncaught TypeError: $.fn.fullpage.destroy is not a function`

The quick & dirty solution for me was to init the fullpage and then to destroy it like this:

```
var fullPageInit = function(){
    if (Modernizr.mq('(max-width: 1024px)')) {
       // Remove full page
        if ( $('.full-page').length ) {
            // Init
            $('.full-page').fullpage({
                autoScrolling: false,
                fitToSection: false
            });
            // And then destroy...
            $.fn.fullpage.destroy('all');
        }

    } else {
        if ( $('.full-page').length ) {
            $('.full-page').fullpage({
                autoScrolling: false,
                fitToSection: false
            });
        }
    }
}
```

Is there a somewhat cleaner solution than this? The fullpage destroy function fails because it cannot find any initialized element on the page. 

Thanks

**Comment by alvarotrigo** [comment]
How are you going to destroy a plugin that was not initialized in the first instance ?
You are only initializing fullpage.js if the width resolution is larger than 1204px. But you said you have the problem width smaller resolutions, which makes total sense, the plugin was not initialized, you can not call a function that doesn't exist. ]

My recommendation is to check if the plugin was initizlied using one of the [**state classes**](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) added by fullpage.js: `fp-enabled`.

```javascript
  if (Modernizr.mq('(max-width: 1024px)')) {
       // Remove full page
        if ( $('.fp-enabled').length ) {
            // Destroy all  
            $.fn.fullpage.destroy('all');
        }

    } else {
```

**Comment by gorankrgovic** [comment]
Yup I know it's not initialized, that's why I initialized it at first for the smaller screen sizes. But your answer with checking for the state classes is a go for me :). Thank you very much
