### ISSUE TITLE
Unable to properly use the library with wordpress

### ISSUE THREAD

**Issue by nickimola** [alvarotrigo/fullPage.js#1824]
HI, i don't know if it's just me doing something odd, or if there's an issue with the library..
basically, i've added this into a wordpress website, and everything works properly (menus, adding active class, sliding, sections and so on...)

Now, i need to have my wordpress website multilanguage, and so i've installed a plugin called [polylang](https://en-gb.wordpress.org/plugins/polylang/). With this plugin, to have the multilang functionality, you have to create different pages for each language you need to use. So i created all the different pages but, the plugin works only for "english" (the default language) and not with the others..well, it look like it's blocked somehow (if i click on a menu item, the sliding to section using url works, but if i try to scroll, i can't)..

Any thought about it?

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue I'm afraid. Ask in other place.
