### ISSUE TITLE
Background color is working but not background images? 

### ISSUE THREAD

**Issue by adiajit** [alvarotrigo/fullPage.js#1825]
Hey Alvaro I'm really enjoying fullpage.js so far, I've been having some trouble applying background images to a section. The odd thing is that the background color property works fine.

```
<div class="section" id="bio-page">

</div>
```
I commented out everything inside the section to make sure nothing wonky is going on inside the section

```
#bio-page {
	//background-color: yellow; 
	background-size: cover; 
	background-image: url("img/mountainstars.png");
}
```
is the relevant stylesheet section

```
  $(document).ready(function() {
    $('#fullpage').fullpage({
      anchors: ['top', 'bio', 'skills', 'projects', 'contact'],
      menu: '#menu',
      paddingTop: '4vh'
```

Is my initialization of full page, everything else seems to be working fine. Is there some case where background-images will not be loaded?

**Comment by alvarotrigo** [comment]
Check out the availalbe [example online](http://alvarotrigo.com/fullPage/examples/backgrounds.html) and [the one included with the plugin itself](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

It is definetelly not a fullpage.js issue, so if you still having troubles you'd better ask with the `css` tag in http://stackoverflow.com/
