### ISSUE TITLE
Nesting Modals inside Sections with URL change

### ISSUE THREAD

**Issue by dobromir-hristov** [alvarotrigo/fullPage.js#1827]
So I have to use fullPage with some kind of modals that are triggered on some of the sections. Pretty straight forward that, and Nesting modals are also not that hard, allot of plugins out there that do that. I`m more concerned about the URL change. Has to simulate a SPA application, so of you open a modal, the modal has to change the URL. As fullPage is using hashtags # to keep track of sections, and nested slides with a slash /, how should I keep track of the opened modals, so going back would close them and so on?
I know this is not directly related to fullPage, but I dont know how this could interfere with its url parser.

**Comment by alvarotrigo** [comment]
> As fullPage is using hashtags # to keep track of sections, and nested slides with a slash /, how should I keep track of the opened modals, so going back would close them and so on?

Try using the method `$.fn.fullpage.lockAnchors`. Read about it in the docs.
