### ISSUE TITLE
Slider no touch on mobile, when use <iframe> tag

### ISSUE THREAD

**Issue by brunotrocoli** [alvarotrigo/fullPage.js#1828]
Hello!
I am creating an HTML5 framework with FullPage.js.
So I have this link with preview > http://brunotrocoli.github.io/ziiro/

When i open the site on mobile, in Google Chrome, the iFrame areas not working with touch moves in horizontal.

Code here:
https://github.com/brunotrocoli/ziiro

Thanks!

**Comment by alvarotrigo** [comment]
Probably related with https://github.com/alvarotrigo/fullPage.js/issues/803. 
Do not use iframes, they are not usually friendly... 

I dont think we can have access to iframe touch events for security reasons. I'll close the issue.

**Comment by brunotrocoli** [comment]
Thanks for support
