### ISSUE TITLE
Enable touch device incremental scrolling

### ISSUE THREAD

**Issue by alleluu-deployments** [alvarotrigo/fullPage.js#1829]
How can I enable the standard touch device incremental scrolling behavior when swiping between slides? See http://fantasy.co for instance on touch device. Pressing down and moving your finger up or down slowly will animate the slides to move with your finger. See https://github.com/darsain/sly/blob/master/docs/Options.md elasticBounds option for instance.

**Comment by alvarotrigo** [comment]
You can't yet. This would be a feature requests. 
I'll add it as an enhancement for the future. 

The most you can do now is using `autoScrolling:false` and `fitToSection:true`. This way the user will be moved to the nearest section if they ended up in between sections. You can adjust the delay by using the option `fitToSectionDelay `.

**Comment by alvarotrigo** [comment]
If you really need this feature as soon as possible [contact me](http://alvarotrigo.com/#contact-page) for an urgent request.

**Comment by alvarotrigo** [comment]
This was implemented in the [Drag And Move extension](http://alvarotrigo.com/fullPage/extensions/dragAndMove.html).
