### ISSUE TITLE
Required doctype declaration 

### ISSUE THREAD

**Issue by anandchakru** [alvarotrigo/fullPage.js#1831]
This is not really problem with fullPage.js (@alvarotrigo, I'm a fan of yours, you may close it)
This is a problem with jquery, in case someone finds it that the fullPage is rendering the page really really long, with `windowsHeight = 1603px` or 50px I realized the issue was with Jquery's `$window.height();` This cannot work correctly if you don't have `<!DOCTYPE html>` in your html. Reference: http://viralpatel.net/blogs/jquery-window-height-incorrect/

_Adding it here, thinking it might be useful for others._

**Comment by alvarotrigo** [comment]
Yeah, exactly.
But note that the `DOCTYPE` declaration [is compulsory](http://www.corelangs.com/html/introduction/doctype.html). It defines the document type definition and every developer should add a doctype in their websites. 

Quoting your link:

> Our HTML document doesn’t have DOCTYPE declaration. **So it’s not a valid HTML so to speak.**

It doesn't have to be the HTML 5 doctype, it can be any other. 

But I guess I'll have to add it in the documentation somehow, it seems other people also had the same problem. I'll add it as a documentation enhancement. Thanks for pointing it out.

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.8.
