### ISSUE TITLE
Fullpage and animate css

### ISSUE THREAD

**Issue by rrhussain** [alvarotrigo/fullPage.js#1834]
Hi alvarotrigo 
I tried your method it is good for bounce animation. I want fadeInUp and fadeOutUp effect. I am making a slider with this I have caption on left side I want to fadeInUp on wayin and fadeOutUp on wayout.

Your method applies only when section loaded. I want when slide comes in progressive way.

Alvarotirgo made a great plugin

here is jsfiddle code

https://jsfiddle.net/sd16syz9/11/

Note: please expand window to see the caption on left side.

many thanks

**Comment by alvarotrigo** [comment]
I don't really understand what you are talking about, or what "my method" is. But fullpage.js doesn't provide any fading effects. 

You'd better ask somewhere else, yours is definitely not a fullpage.js issue.

**Comment by rrhussain** [comment]
Thanks for your quick response.

Actually I would like to add animate.css animation in my caption text in my slider. So the method you have in DOCS.

onLeave: function(index, nextIndex, direction){$('.mycaption').removeClass('animated fadeInUp');},
afterLoad: function(anchorLink, index){$('.mycaption').addClass('animated fadeInUp');},
afterRender: function(){$('.mycaption').addClass('animated fadeInUp');},

I was trying to add these classes into my caption text however these methods only applies after slide loaded but I want when slide comes up or goes down. I meant to say in progressive way.

I hope it makes sense .

here is jsfiddle code

https://jsfiddle.net/sd16syz9/11/

Note: please expand window to see the caption on left side.

This is the example site which have the effect I want to achieve through your plugin.

http://nicolas-bussiere.fr/

Many thanks

**Comment by alvarotrigo** [comment]
`onLeave` will get fired when leaving the section, not when it has been loaded.
