### ISSUE TITLE
lazy load images above background gradient

### ISSUE THREAD

**Issue by ctf0** [alvarotrigo/fullPage.js#1837]
mostly what am after is something like the behavior in 
https://www.yourprimer.com/

right now the plugin have can set a background gradient to the sections which is good, so it there any chance we can also add to this functionality by adding an option to lazy load an image or group of images lets say after 500ms after finishing scrolling to that section ?

**Comment by alvarotrigo** [comment]
You can probably do that using callbacks. No need to include such specific things in the plugin.

**Comment by ctf0** [comment]
can u plz give me a code sample for doing such a thing ?

**Comment by alvarotrigo** [comment]
You'd better ask for those things in another place such as http://stackoverflow.com/. 
I only provide support for fullpage.js issues or questions and yours is about a very specific feature of your site that is not directly related with fullpage.js.

If you need my help you can always contract my services for those things.

**Comment by alvarotrigo** [comment]
Regarding lazy loading, make sure you read [the documentation](https://github.com/alvarotrigo/fullPage.js#lazy-loading) about it and topics [like this one](https://github.com/alvarotrigo/fullPage.js/issues/1488).

**Comment by ctf0** [comment]
fair enough, many thanx for ur help :+1:
