### ISSUE TITLE
Fade in the first section from bottom when script finished loading

### ISSUE THREAD

**Issue by bpyrate** [alvarotrigo/fullPage.js#1838]
Hi there, 

is there a possibility to fade in the first section from bottom? See here for this behaviour: http://facultydept.com/

The first section comes into the viewport like the normal section scrolling in fullpage. An invisible section "zero" shows a logo and disappears when the page finished loading. This animation help people to recognize the function of fullpage and might be a nice design feature.

How can this behaviour be achieved by fullpage?

Thx!

**Comment by alvarotrigo** [comment]
> is there a possibility to fade in the first section from bottom?

 Nop. The plugin won't provide such feature. You might be able to accomplish it somehow, but it is not integrated in the plugin.

> How can this behaviour be achieved by fullpage?

You'd better ask somewhere such as http://stackoverflow.com/ else for those kind of questions.
