### ISSUE TITLE
Trying to turn auto scroll and mousewheel on off after slideload and slide leave

### ISSUE THREAD

**Issue by codinglover** [alvarotrigo/fullPage.js#1839]
I am trying to do something like when the slide loads the autoscrolling and auto mousewheelscrolling will turn off but when someone leaves the slides and go to section again autoscrolling and mousewhell scrolling will be turned on. 

So, what will be the possible way to do that ?

So far i have done turning it off by : `fullpageAfterSlideLoad = function( anchorLink, index, slideAnchor, slideIndex ) {

			fullpageStopParallaxX();

			var slide = fullpageSectionsEl.eq( index -1 ).find( '.slide' ).eq( slideIndex );
			
			if(slideIndex === 0) { $( '.fp-slidesNav' ).hide( 'fast' ) }
else { $( '.fp-slidesNav' ).show( 'fast' ) 
    $.fn.fullpage.setMouseWheelScrolling(false);
    $.fn.fullpage.setAllowScrolling(false);
}
            

			fullpageSetBackground( slide );

			fullpageSetActiveMenuItem();

			fullpageConsoleLog( 'fullpageAfterSlideLoad' );

		}`

But when i am going back to section the scroll is turn off. anything that i am missing or need to add ?

I tried by adding turn them on inside slideleave but not working properly.

**Comment by alvarotrigo** [comment]
You'd better ask for those kind of questions in stackoverflow.com 
This forum is to treat fullpage.js issues and bugs and not to answer specific usages of the plugin. 

In any case, I don't see anything about `autoScrolling` in your code...
