### ISSUE TITLE
css animations

### ISSUE THREAD

**Issue by Khanatox** [alvarotrigo/fullPage.js#184]
Hello,

First of all, i want to thank you that you made possible for us to use your awesome creation.

I have a quick question concerning the css animations (this is what i'm using = http://daneden.github.io/animate.css/).

When i setup multiple animations on different slides, it all loads at the same time.

Is it possible to execute the animation when i go to slide 3 separately from the other slides?

Thank you very much.

**Comment by sic0211** [comment]
I made it work like this

        onLeave: function(index, nextIndex, direction){$('#myID').removeClass('animated bounce');},
        afterLoad: function(anchorLink, index){$('#myID').addClass('animated bounce');},
        afterRender: function(){$('#myID').addClass('animated bounce');},

Note sure why addClass() is required in both afterLoad and afterRender

**Comment by sic0211** [comment]
And do not add any classes to HTML markup, only do callbacks from js

**Comment by rrhussain** [comment]
Hi sic0211,
I tried your method it is good for bounce animation. I want fadeInUp and fadeOutUp effect. I am making a slider with this I have caption on left side I want to fadeInUp on wayin and fadeOutUp on wayout.

Your method applies only when section loaded. I want when slide comes in progressive way.

many thanks
