### ISSUE TITLE
silentMoveTo on scroll event only between some sections

### ISSUE THREAD

**Issue by jeffceriello** [alvarotrigo/fullPage.js#1840]
Hi Alvaro, thank you for your amazing plugin.

Is it possible to instantly move on scroll only between some sections?

I need to have "section1", "section2" and "section3" to scroll without animation (to just jump from one to the other) and to have all the other sections animating normally.

I know there is the $.fn.fullpage.silentMoveTo('anchor-link', 'slide'); function and I am trying to use it in this way but it doesn't work:

```
onLeave: function(index, nextIndex, direction){
    if(nextIndex == 1){
        $.fn.fullpage.silentMoveTo('introduction1');
    } else if(nextIndex == 2){
        $.fn.fullpage.silentMoveTo('introduction2');
    } else if(nextIndex == 3){
        $.fn.fullpage.silentMoveTo('introduction3');
    }
}
```
I believe it might only work when an event is triggered, like on click.
Is there a way to do what I need to achieve?

Thank you,
Jeff

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any shortcut to do that, and if you try it with `setScrollingSpeed` in some callback then you have the problem of scrolling multiple sections with a single scroll wheel movement.
