### ISSUE TITLE
Scroll event not detected on normal scroll mode

### ISSUE THREAD

**Issue by JuZED** [alvarotrigo/fullPage.js#1841]
[fullPage.zip](https://github.com/alvarotrigo/fullPage.js/files/139748/fullPage.zip)

Hi,

I noticed that in normal scroll mode, when in the first section, a slide has a scroll overflow, the scroll is not triggered until you display this particular slide. Did not find where it comes from.

Take a look at the `fullPage/examples/normalScroll.html` in the attached zip to see it.

Regards,

Julien

**Comment by alvarotrigo** [comment]
> I noticed that in normal scroll mode, when in the first section, a slide has a scroll overflow,

You are not suppose to use `scrollOverflow:true` with `autoScrolling:false`. It is not designed for it.
