### ISSUE TITLE
setAllowScrolling(false) doesn't work when using mouse middle button but scroll

### ISSUE THREAD

**Issue by maniek910** [alvarotrigo/fullPage.js#1844]
Hello
I have small problem with disable scroll, if i used $.fn.fullpage.setAllowScrolling(false) it's work fine if i normal scroll, but if I scrolling while holding down the button(on mouse) and the mouse movement down or the top it's don't work.

It's normal ?

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
That's a bug!

**Comment by alvarotrigo** [comment]
Fixed on [development version 2.7.8](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by alvarotrigo** [comment]
Solved in 2.7.8

**Comment by maniek910** [comment]
Hello!

 

You have a new message, please read <http://llarmanelpujades.agape.org/coat.php?mek6k>

 

janczakpawel@op.pl
