### ISSUE TITLE
How Jump on particuler slide  when click on  custome button click event.

### ISSUE THREAD

**Issue by sagarjethi** [alvarotrigo/fullPage.js#1847]
Hello @alvarotrigo 
I need to make functionality
In First slide I have  **3 three button** .
on click of each button click event  I want to open   specific  slide,
where and how write code  that make this functionality working

**Comment by alvarotrigo** [comment]
Use the provided functions of fullpage.js such as `$.fn.fullpage.moveTo`. More about them and their usage [in the docs](https://github.com/alvarotrigo/fullPage.js#movetosection-slide).
