### ISSUE TITLE
No scrolling up to the first section in Safari when scrolling fast

### ISSUE THREAD

**Issue by TheodoraN** [alvarotrigo/fullPage.js#1848]
I am implementing fullpage js on a site and I'm using the arrows controls to jump from one section to other. When scrolling fast, on Safari, it doesn't go upper than the second section, even though the anchor changes to the right one. The page I'm working on is live at: http://montgomery.dk/

Thank you!

**Comment by alvarotrigo** [comment]
I guess you are talking about scrolling **down** fast **with the trackpad**, and then trying to go back to the previous section by using the up keyboard arrow?

**Comment by alvarotrigo** [comment]
Can you reproduce it [on the demo site](http://alvarotrigo.com/fullPage/)?

**Comment by kejriwalrahul** [comment]
Even I'm having a similar issue on my page. I'm unable to scroll up beyond the second section although the anchor changes to the correct one.

**Comment by alvarotrigo** [comment]
@kejriwalrahul again, I need a way to reproduce it. Can you do it on the demo site? If so, specify the steps to follow.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.

**Comment by marekm4** [comment]
I'm having the same issue. When I'm on third slide and press arrow up two times page get stuck on second slide. It only happens on Safari and only when going up. A was unable to reproduce it on demo site.

**Comment by wisam22** [comment]
Hey, if anyone is still having this issue, this might help. For me, I was attempting to set a top/bottom margin on the sections, via CSS. After removing that the issue went away.
