### ISSUE TITLE
iframe in slider Fullpage.js

### ISSUE THREAD

**Issue by razenit** [alvarotrigo/fullPage.js#1849]
Hi,
I am using fullpage.js for a site, but i have a problem with iframes in sliders.
On page 4 I fix the problem by adding ScrollBar: true, but on the next slides it doent work. 
This is site adress: http://onlinecatalogues.ra-zenit.com/#page4

Any suggestions?
Also if someone knows how to make it work without scrollbat true?

Thanks!

**Comment by alvarotrigo** [comment]
That's because your flash object is catching the mouse wheel events and doesn't allow them to be propagated to fullpage.js.

Nothing that fullpage.js can do to solve it.
