### ISSUE TITLE
Click on Button to Scroll doesn't work when using Skrollr on Ipad or Mobile Devices

### ISSUE THREAD

**Issue by deepakkumarv** [alvarotrigo/fullPage.js#1850]
Everything seems to work absolutely fine until its on Ipad or Mobile. The anchor tags fail to move the body to the respective position on Ipad or mobile devices. Please can you let me know if I am doing something wrong from my end? @alvarotrigo 

`<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>SCube Digital Media</title>
	<style type="text/css">
	.scube-rocket {
    max-width: 250px;
    padding: 10%;
    position: fixed;
}
#fullpage {
    width: 60%;
    float: right;
}
.smoke {
	max-width: 46%;
    padding: 10% 0% 10% 0%;
    position: fixed;
    display: none;
    margin-left: -4%;
}
@media all and (max-width: 768px) {
	#fullpage {
    	width: 100%;
	}
	.scube-rocket {
    padding: 0 33.5%;
    z-index: 9;
    background: #fff;
}
.fp-tableCell {
    padding-top: 25%;
}
}
</style>
    <link rel="stylesheet" type="text/css" href="file:///Users/third/Desktop/skrollr-menu%20plugin_files/example3.css">
<style>
		/* Sections
		 * --------------------------------------- */
		#section0 img,
		#section1 img{
			margin: 20px 0 0 0;
		}
		#section2 img{
			margin: 20px 0 0 52px;
		}
		#section3 img, #section4 img, #section5 img, #section6 img{
			bottom: 0px;
			position: absolute;
			margin-left: -420px;
		}
		.intro p{
			width: 50%;
			margin: 0 auto;
			font-size: 1.5em;
		}
		.twitter-share-button{
			position: absolute;
			z-index: 99;
			right: 149px;
			top: 9px;
		}
	</style>
	
</head>
<body>
<img class="smoke" src="http://dev.thescube.com/wp-content/uploads/2016/02/animation1-1.gif" data-0="display:none;" data-550p="display:block;"/>
<svg version="1.1" id="Layer_1" class="scube-rocket" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 325.3 637.4" style="enable-background:new 0 0 325.3 637.4;" xml:space="preserve" data-0p="display:block;" data-550p="display:none;">
<style type="text/css">
	.st0{fill:#E6E6E6;}
	.st1{fill:#F2F2F2;}
	.st2{fill:#00CCCC;}
	.st3{fill:#00E5DF;}
	.st4{fill:#1A1A1A;}
	.st5{fill:#4D4D4D;}
	.st6{fill:#333333;}
	.st7{fill:#E5B12E;}
	.st8{fill:#FFD62D;}
	.st9{fill:#5BB24C;}
	.st10{fill:#7AC943;}
	.st11{fill:#FFFFFF;}
	.st12{fill:#312F30;}
	.st13{fill:#0F9CD8;}
	.st14{fill:#43B7FF;}
	.st15{fill:#3FA9F5;}
	.st16{fill:#CCCCCC;}
	.st17{fill:#9966CC;}
	.st18{fill:#8D62BF;}
	.st19{fill:#A976E5;}
</style>
<g>
	<g>
		<g data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(-500%, 500%);" data-200p="transform:translate(0%,0%)";>
			<rect x="50.6" y="582.2" class="st0" width="58.3" height="15.6"/>
			<path class="st1" d="M119.2,569.9c0,8.9-7.3,16.2-16.2,16.2H42.1c-8.9,0-16.2-7.3-16.2-16.2l0,0c0-8.9,7.3-16.2,16.2-16.2H103
				C112,553.7,119.2,561,119.2,569.9L119.2,569.9z"/>
		</g>
		<g data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(500%, 500%);" data-200p="transform:translate(0%,0%)";>
			<rect x="217.8" y="582.2" class="st1" width="58.3" height="15.6"/>
			<path class="st0" d="M286.4,569.9c0,8.9-7.3,16.2-16.2,16.2h-60.9c-8.9,0-16.2-7.3-16.2-16.2l0,0c0-8.9,7.3-16.2,16.2-16.2h60.9
				C279.2,553.7,286.4,561,286.4,569.9L286.4,569.9z"/>
		</g>
	</g>
	<g>
		<g>
			<g data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(0%, -600%);" data-500p="transform:translate(0%, 0%);">
				<g>
					<path class="st2" d="M162.9,0c-50.4,6-59.2,94-59.2,112v375.5l59.2,0V0z"/>
					<path class="st3" d="M162.9,0c50.6,6.1,59.4,94.1,59.4,112.1v375.5h-59.4V0z"/>
				</g>
				<g>
					<rect x="103.7" y="260.8" class="st4" width="59.4" height="6.9"/>
					<rect x="162.9" y="260.8" class="st5" width="59.4" height="6.9"/>
				</g>
				<g>
					<rect x="103.7" y="137.2" class="st4" width="59.4" height="6.9"/>
					<rect x="162.9" y="137.2" class="st5" width="59.4" height="6.9"/>
				</g>
			</g>
			<g data-0p="transform:translate(0%, 0%) rotate(0deg);" data-100p="transform:translate(-3500%, 100%) rotate(-180deg);" data-400p="transform:translate(0%, 0%) rotate(0deg);">
				<g>
					<path class="st6" d="M44.4,490.1h27.5V73.3C69,74,64,77.4,58.4,90.8C49.7,111.3,42.2,135,41,154.2c-5.5,87.1,0,335,0,335
						L44.4,490.1z"/>
					<path class="st5" d="M99.3,490.1l3.4-0.8c0,0,5.5-248,0-335c-1.2-19.2-8.7-42.9-17.4-63.5C79.6,77.4,74.6,74,71.8,73.3v416.7
						H99.3z"/>
				</g>`
				<g>
					<path class="st7" d="M71.8,362.5v-8.1h-33c0,2.7,0,5.4,0,8.1H71.8z"/>
					<path class="st8" d="M104.9,362.5c0-2.7,0-5.4,0-8.1h-33v8.1H104.9z"/>
				</g>
				<g>
					<path class="st7" d="M71.8,268.7v-8.1H38.5c0,2.7,0,5.4,0,8.1H71.8z"/>
					<path class="st8" d="M105.2,268.7c0-2.7,0-5.4,0-8.1H71.8v8.1H105.2z"/>
				</g>
				<g>
					<path class="st7" d="M71.8,171.9v-7.8l-31.7-0.1c-0.2,2.7-0.3,5.3-0.3,8H71.8z"/>
					<path class="st8" d="M103.8,171.9c0-2.6-0.1-5.3-0.1-7.9l-31.9,0v7.8H103.8z"/>
				</g>
			</g>
			<g data-0p="transform:translate(0%, 0%) rotate(0deg);" data-100p="transform:translate(3500%, -100%) rotate(180deg);" data-400p="transform:translate(0%, 0%) rotate(0deg);">
				<g>
					<path class="st6" d="M226.1,490.1h27.5V73.3c-2.8,0.7-7.8,4-13.5,17.4c-8.7,20.6-16.2,44.3-17.4,63.5c-5.5,87.1,0,335,0,335
						L226.1,490.1z"/>
					<path class="st5" d="M281,490.1l3.4-0.8c0,0,5.5-248,0-335c-1.2-19.2-8.7-42.9-17.4-63.5c-5.7-13.4-10.7-16.7-13.5-17.4v416.7
						H281z"/>
				</g>
				<g>
					<path class="st7" d="M253.6,362.5v-8.1h-33c0,2.7,0,5.4,0,8.1H253.6z"/>
					<path class="st8" d="M286.6,362.5c0-2.7,0-5.4,0-8.1h-33v8.1H286.6z"/>
				</g>
				<g>
					<path class="st7" d="M253.6,268.7v-8.1h-33.3c0,2.7,0,5.4,0,8.1H253.6z"/>
					<path class="st8" d="M286.9,268.7c0-2.7,0-5.4,0-8.1h-33.3v8.1H286.9z"/>
				</g>
				<g>
					<path class="st7" d="M253.6,171.9v-7.8l-31.7-0.1c-0.2,2.7-0.3,5.3-0.3,8H253.6z"/>
					<path class="st8" d="M285.5,171.9c0-2.6-0.1-5.3-0.1-7.9l-31.9,0v7.8H285.5z"/>
				</g>
			</g>
		</g>
		<g>
		<g class="rocket-stem" data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(0%, -100%);" data-200p="transform:translate(0%, 0%);">
					<g>
				<path class="st0" d="M106.8,346.5c-11.3,74.8-59.4,114.6-84.2,134.9c-24.8,20.3-19.1,53.8-19.1,53.8H0v16.4l122.3,32V256v-3.9
					C118.8,271.6,106.8,346.5,106.8,346.5z"/>
				<path class="st9" d="M91.1,395c-14.5,28.3-38.6,58.5-63.5,79.3C-3.1,500.1,1.4,527,3.1,533.6h6C7.5,498.5,33.2,479,33.2,479
					C70,446.1,89.1,416.6,99,395H91.1z" data-0p="transform:translate(0%, 0%) rotate(0deg);" data-100p="transform:translate(-1250%, -150%) rotate(90deg);"data-300p="transform:translate(0%,0%) rotate(0deg);"/>
				<rect x="57.3" y="509.4" class="st1" width="33.2" height="7.8"/>
				<rect x="48.1" y="519.6" class="st1" width="42.4" height="7.8"/>
			</g>
			<g>
				<path class="st1" d="M218.5,346.5c11.3,74.8,59.4,114.6,84.2,134.9c24.8,20.3,19.1,53.8,19.1,53.8h3.5v16.4l-122.3,32V256v-3.9
					C206.5,271.6,218.5,346.5,218.5,346.5z"/>
				<path class="st10" d="M297.8,474.4c-24.8-20.8-49-51-63.5-79.3h-7.9c9.9,21.5,28.9,51.1,65.8,84c0,0,25.8,19.4,24.1,54.6h6
					C324,527,328.5,500.1,297.8,474.4z" data-0p="transform:translate(0%, 0%) rotate(0deg);" data-100p="transform:translate(1250%, 150%) rotate(-90deg);" data-300p="transform:translate(0%, 0%) rotate(0deg);"/>
				<rect x="234.8" y="509.4" class="st0" width="33.2" height="7.8"/>
				<rect x="234.8" y="519.6" class="st0" width="42.4" height="7.8"/>
			</g>
			<g>
				<path class="st1" d="M141.4,136.5c-0.4,1.1-0.7,2.2-1.1,3.4c-22.6,70.7-19.8,145.5-19.8,145.5V589h42.4V136.5H141.4z"/>
				<path class="st11" d="M185.5,140c-0.4-1.2-0.8-2.4-1.2-3.6h-21.5v452.6h42.4V285.6C205.3,285.6,208.2,210.7,185.5,140z"/>
			</g>
			<g>
				<path class="st0" d="M162.9,239.7v-5.2h-40.6c-0.2,1.8-0.3,3.5-0.4,5.2H162.9z"/>
				<path class="st0" d="M203.9,239.7c-0.1-1.7-0.3-3.4-0.4-5.2h-40.6v5.2H203.9z"/>
			</g>
			<g>
				<rect x="120.4" y="305.2" class="st0" width="42.4" height="6.2"/>
				<rect x="162.9" y="305.2" class="st0" width="42.4" height="6.2"/>
			</g>
			<g>
				<rect x="120.4" y="376.2" class="st0" width="42.4" height="6.2"/>
				<rect x="162.9" y="376.2" class="st0" width="42.4" height="6.2"/>
			</g>
			<g>
				<rect x="120.4" y="447.2" class="st0" width="42.4" height="6.2"/>
				<rect x="162.9" y="447.2" class="st0" width="42.4" height="6.2"/>
			</g>
			<g>
				<rect x="120.4" y="518.3" class="st0" width="42.4" height="6.2"/>
				<rect x="162.9" y="518.3" class="st0" width="42.4" height="6.2"/>
			</g>
			<circle class="st0" cx="251.4" cy="486.6" r="15.2"/>
			<g>
				<rect x="158.7" y="234.6" class="st0" width="3.9" height="355"/>
				<rect x="162.6" y="234.6" class="st0" width="3.9" height="355.1"/>
			</g>
		</g>
			<g data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(0%, -5000%);" data-200p="transform:translate(0%, 0%);">
				<path class="st13" d="M162.9,204.3v-37.1c-16.7,0.3-22.1,6.7-24.5,13.2c-2.1,5.7-3.9,23.9-3.9,23.9H162.9z"/>
				<path class="st14" d="M191.3,204.3c0,0-1.9-17.1-3.8-22.5c-2.4-6.7-8.4-14.3-24.5-14.5v37H191.3z"/>
			</g>
			<g data-0p="transform:translate(0%, 0%);" data-100p="transform:translate(0%, -5000%);" data-200p="transform:translate(0%, 0%);">
				<path class="st15" d="M162.9,139.9v-34.3c-6.4,0-12.1,1.4-22.6,34.3H162.9z"/>
				<path class="st14" d="M162.9,139.9v-34.3c5.7-0.2,12.1,1.4,22.6,34.3H162.9z"/>
			</g>

			<g class="first-view" data-0p="transform:scale(1) translate(0%,0%);transform-origin:center;" data-100p="transform:scale(2.5) translate(0%,-100%);" data-200p="transform:scale(1) translate(0%,0%);">
			<rect x="115.5" y="607.2" class="st12" width="47.1" height="15.6"/>
			<rect x="162.7" y="607.3" class="st12" width="47.1" height="15.6"/>
			<path class="st16" d="M106.1,612.9h56.6v-81.1c0,0-56.6-6.2-56.6,26V612.9z"/>
			<path class="st0" d="M219.3,613h-56.6v-81.1c0,0,56.6-6.2,56.6,26V613z"/>
			<g>
		<rect x="118.1" y="627.7" class="st17" width="36.2" height="9.7"/>
		<path class="st18" d="M159.7,620.1c0,4.5-3.7,8.2-8.2,8.2h-30.7c-4.5,0-8.2-3.7-8.2-8.2l0,0c0-4.5,3.7-8.2,8.2-8.2h30.7
			C156.1,611.9,159.7,615.5,159.7,620.1L159.7,620.1z"/>
	</g>
	<g>
		<rect x="170.6" y="627.6" class="st19" width="36.2" height="9.7"/>
		<path class="st17" d="M212.3,620c0,4.5-3.7,8.2-8.2,8.2h-30.7c-4.5,0-8.2-3.7-8.2-8.2l0,0c0-4.5,3.7-8.2,8.2-8.2h30.7
			C208.6,611.8,212.3,615.5,212.3,620L212.3,620z"/>
	</g>

			</g>
		</g>
	</g>
	
</g>
</svg>

<ul id="menu">
	<li data-menuanchor="firstPage"><a href="#firstPage">All</a></li>
	<li data-menuanchor="secondPage"><a href="#secondPage">Graphic</a></li>
	<li data-menuanchor="3rdPage"><a href="#3rdPage">Web</a></li>
	<li data-menuanchor="4thpage"><a href="#4thpage">Marketing</a></li>
	<li data-menuanchor="5thpage"><a href="#5thpage">New Tech</a></li>
	<li data-menuanchor="6thpage"><a href="#6thpage">Consultation</a></li>
	<li data-menuanchor="7thpage"><a href="#7thpage">Take Off</a></li>
</ul>

<div id="skrollr-body">
<div id="fullpage">
	<div class="section " id="section0">
		<h1>fullPage.js</h1>
		<p>Create Beautiful Fullscreen Scrolling Websites</p>
		<img src="./imgs/fullPage.png" alt="fullPage" />
	</div>
	<div class="section" id="section1">
	    <div class="slide">
			<div class="intro">
				<h1>Create Sliders</h1>
				<p>Not only vertical scrolling but also horizontal scrolling. With fullPage.js you will be able to add horizontal sliders in the most simple way ever.</p>
				<img src="./imgs/slider.png" alt="slider" />
			</div>

		</div>
	    <div class="slide">
			<div class="intro">
				<img src="./imgs/1.png" alt="simple" />
				<h1>Simple</h1>
				<p>Easy to use. Configurable and customizable.</p>
			</div>
		</div>
	    <div class="slide">
			<div class="intro">
				<img src="./imgs/2.png" alt="Cool" />
				<h1>Cool</h1>
				<p>It just looks cool. Impress everybody with a simple and modern web design!</p>
			</div>
		</div>
	    <div class="slide">
			<div class="intro">
				<img src="./imgs/imgs/3.png" alt="Compatible" />
				<h1>Compatible</h1>
				<p>Working in modern and old browsers too! IE 8 users don't have the fault of using that horrible browser! Lets give them a chance to see your site in a proper way!</p>
			</div>
		</div>
	</div>
	<div class="section" id="section2">
		<div class="intro">
			<h1>Example</h1>
			<p>HTML markup example to define 4 sections.</p>
			<img src="file:///Users/third/Desktop/skrollr-menu%20plugin_files/imgs/example2.png" alt="example" />
		</div>
	</div>
	<div class="section" id="section3">
		<div class="intro">
			<h1>Working On Tablets</h1>
			<p>
				Designed to fit to different screen sizes as well as tablet and mobile devices.
				<br /><br /><br /><br /><br /><br />
			</p>
		</div>
		<img src="file:///Users/third/Desktop/skrollr-menu%20plugin_files/imgs/tablets.png" alt="tablets" />
	</div>
	<div class="section" id="section4">
		<div class="intro">
			<h1>Working On Tablets</h1>
			<p>
				Designed to fit to different screen sizes as well as tablet and mobile devices.
				<br /><br /><br /><br /><br /><br />
			</p>
		</div>
		<img src="file:///Users/third/Desktop/skrollr-menu%20plugin_files/imgs/tablets.png" alt="tablets" />
	</div>
	<div class="section" id="section5">
		<div class="intro">
			<h1>Working On Tablets</h1>
			<p>
				Designed to fit to different screen sizes as well as tablet and mobile devices.
				<br /><br /><br /><br /><br /><br />
			</p>
		</div>
		<img src="file:///Users/third/Desktop/skrollr-menu%20plugin_files/imgs/tablets.png" alt="tablets" />
	</div>
	<div class="section" id="section5">
		<div class="intro">
			<h1>Working On Tablets</h1>
			<p>
				Designed to fit to different screen sizes as well as tablet and mobile devices.
				<br /><br /><br /><br /><br /><br />
			</p>
		</div>
		<img src="file:///Users/third/Desktop/skrollr-menu%20plugin_files/imgs/tablets.png" alt="tablets" />
	</div>
</div>
</div>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.7.8/jquery.fullPage.min.css" />

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage({
				sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', '5thpage', '6thpage', '7thpage', 'lastPage'],
				menu: '#menu',
				scrollingSpeed: 2000,
				scrollBar:true
			});
		});
	</script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.7.8/vendors/jquery.easings.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.7.8/vendors/jquery.slimscroll.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.7.8/jquery.fullPage.min.js"></script>

<script type="text/javascript" src="file:///Users/third/Desktop/skrollr-master/dist/skrollr.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<script>
      var s = skrollr.init();
</script>

</body>
</html>`

**Comment by alvarotrigo** [comment]
Please read the [reporting issues](https://github.com/alvarotrigo/fullPage.js#reporting-issues) section of the docs and proceed accordingly. 

I'll close the topic until an isolated reproduction is provided.
