### ISSUE TITLE
Skrollr and Fullpage doesn't work properly on Ipad and Smaller devices

### ISSUE THREAD

**Issue by deepakkumarv** [alvarotrigo/fullPage.js#1851]
Hi,
I have used Skrollr and Fullpage for animating the elements. Everything works perfect until on screen devices smaller than 768px.

Either the buttons doesn't anchor to the correct section or the the scroll effect of the skrollr doesn't work.

Please can you have a look at this @alvarotrigo 

External Source - http://dwebsight.com/fullpage.html

PS: Sorry about the last issue having a lot of code in it.

**Comment by alvarotrigo** [comment]
Your sections won't become smaller if the content on it doesn't allow it. 
Remove any text from the sections and the sections will resize correctly.
