### ISSUE TITLE
In slide  on button click event page automatic scroll 

### ISSUE THREAD

**Issue by sagarjethi** [alvarotrigo/fullPage.js#1853]
Hello @alvarotrigo 
  I  have used slide  function in my  project .
  In project  slide part there is  2 slide.
`   I am easily move  to particular using  $.fn.fullpage.moveSlideRight() and  $.fn.fullpage.moveSlideLeft`()       

**But my  second slide dynamic question list. in that i have  next and previous button for move to  particular  question.    when click on that button page automatic scroll.**

so ,In section slide  my  contain  only change.but page  scroll automatic.

**Comment by alvarotrigo** [comment]
Please read the [reporting issues](https://github.com/alvarotrigo/fullPage.js#reporting-issues) section in the docs and act accordingly.  (point 4)

I'll close the issue until an isolated reproduction is provided.
