### ISSUE TITLE
Flickering when scrolling images

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#1862]
Hi guys,

I'm a super happy fullpage.js user. It really made my website looking beautiful.

The only thing I'm trying to sole is that annoying flickering I have everytime I scoll from one slide to another. Is there an easy js or css solution for this?

You can test it here: http://www.thisisfed.com

Thanks in advance.

**Comment by Maciekp** [comment]
Have you tried turning on hardware acceleration on the slides or maybe, better for performance only on these images? 

http://blog.teamtreehouse.com/increase-your-sites-performance-with-hardware-accelerated-css

**Comment by thisisfed** [comment]
@Maciekp yes, I'm using:

.fp-slidesContainer,#fullpage {
-webkit-transition: all 600ms cubic-bezier(0.77, 0, 0.175, 1) !important;
transition: all 800ms cubic-bezier(0.77, 0, 0.175, 1) !important;
}

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction of it in jsfiddle or codepen as per [the reporting issues rules](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

Also, specify which browser you are using and its version and the OS.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
