### ISSUE TITLE
Flickering navigation on safari

### ISSUE THREAD

**Issue by Maciekp** [alvarotrigo/fullPage.js#1863]
Hi,
I've tested my site on many computers, and on safari 9 on some of macs, when click on navigation, navigation's colors change their color. I've checked all styles and scripts, and found no real cause of this, as color changing occurs in random way. 
I think it may be some safari rendering bug. Do you have any ideas what it may be?

before click:
![12751990_10208772653543058_1110112258_o](https://cloud.githubusercontent.com/assets/702066/13395921/fe9a496a-def1-11e5-86ef-53a7019e8ef1.jpg)

after click:
![12787557_1138760569481936_506651956_o](https://cloud.githubusercontent.com/assets/702066/13395919/fdc31f26-def1-11e5-929d-1fe2956cf2a4.jpg)

It seems that orange is negative of this blue color. When I changed the colors, and removed transparency, bug still occured but it no longer changed to orange, but some other colors.

Thanks for help

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction of it in jsfiddle or codepen as per [the reporting issues rules](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by alvarotrigo** [comment]
Closed until provided a reproduction.

**Comment by MikitaLisavets** [comment]
@alvarotrigo reproduction on safari 9.0.3 osx El Capitan on [fullpage examples](http://alvarotrigo.com/fullPage/examples/navigationV.html). If you change dot's background to red color and hover on them, then sometimes dots will change background to blue color.

**Comment by mmckp** [comment]
I'll create jsfiddle this week

**Comment by mmckp** [comment]
Reproduction: https://jsfiddle.net/a69q2b6r/

**Comment by alvarotrigo** [comment]
I've [reported it in stackoverflow](http://stackoverflow.com/questions/36330569/bug-in-safari-9-adding-blue-color-to-links-border), sounds like a Safari bug.
