### ISSUE TITLE
small bug in slides callback function

### ISSUE THREAD

**Issue by fietstouring** [alvarotrigo/fullPage.js#1864]
the callback "afterSlideLoad" provides the slide object of the current slide when scrolling to it from the previous and following section but **only for the first slide** of a slides set.
when navigating to another slide which is not Slide #1 and then scrolling up or down and back to the slide, the function does nothing.

http://codepen.io/webdesignwien/pen/JXoGLd

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1309
