### ISSUE TITLE
Turning the phone in landscape and turning back to portrait cause serious img squeezing

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#1865]
Hi,

when I turn my phone in landscape mode and then portrait again, the section I was viewing results squeezed, the image in distorted and so the previous and next section are affected by the same problem.

Anyone else?

**Comment by alvarotrigo** [comment]
I can not reproduce it on the [demo site](http://alvarotrigo.com/fullPage/). 
Please add an isolated reproduction of it in jsfiddle or codepen as per the reporting issues rules.

Also, specify which browser you are using and its version and the OS.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
