### ISSUE TITLE
Mutiple auto sliders bug

### ISSUE THREAD

**Issue by Kennersky** [alvarotrigo/fullPage.js#1866]
I just want two slides auto change using "$.fn.fullpage.moveSlideRight();" . This method will cause the slide change faster and faster when I leave that slide and then back. I do not know what the problem is. Code like bellow:[https://jsfiddle.net/fiddleoutout/9z4yn9hb/12/](url)
![1](https://cloud.githubusercontent.com/assets/2129521/13447948/3da2caec-e05a-11e5-8302-a572b0567a34.png)

I defined four seconds to change slide,but it's not working when leave it and then back,it seems turn more faster. Like one second change one slide.

@alvarotrigo

**Comment by nhylated** [comment]
The interval should be cleared on each section load. If section 3 is never loaded, no intervals will be cleared and multiple, new intervals will keep on adding thereby increasing the net frequency of moveSlideRight().

I've updated JS code of the fiddle: https://jsfiddle.net/9z4yn9hb/14/

**Comment by Kennersky** [comment]
@nhylated  Thanks for your help! Problem solved! excellent!
