### ISSUE TITLE
Content disappears below fixed header when scrolling up

### ISSUE THREAD

**Issue by adamf321** [alvarotrigo/fullPage.js#1868]
When scrolling down it works as expected. However, when scrolling back up the introduction section is displaced 64px upwards, which hides the title below the menu.

See video: http://snaps.getmoxied.net/2r3Y421R291J

Live code on http://moxienyc:moxistaging101@staging.nptrust.org

Fullpage setup:

```
 $('#fullpage').fullpage({
    onLeave: onLeave,
    afterLoad: afterLoad,
    scrollingSpeed: 1000,
    paddingTop: '64px',
    fixedElements: 'header',
    css3: true
  });
```

**Comment by nacho87** [comment]
I test in mobile to desktop and the same thing happens to me

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction of it in jsfiddle or codepen as per the reporting issues rules.

Also, specify which browser you are using and its version and the OS.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
