### ISSUE TITLE
scrollOverflow on explicit sections

### ISSUE THREAD

**Issue by KingSora** [alvarotrigo/fullPage.js#1869]
Hi!

I want to request a feature. Is it possible to change the "scrollOverflow" option from a boolean to a jQuery object array, so you could apply the scrollOverflow option on specific sections?

Currently I've 2 different sections with known overflow, but I only want one of them to scroll, and thats the problem. This scenario is currently not possible, because the option only allows scrollOverflow on all sections.

Would really appriciate it, if you decide to change the option or create a new option with this kind of functionality.

Best regards,
Sora

**Comment by alvarotrigo** [comment]
The scroll bar is only applied to sections which content is bigger than the viewport. 
Why would you have bigger content than the viewport in a section that won't be accessible for the users?

Why not use absolute positioned elements for those overflowing elements?

**Comment by KingSora** [comment]
The overflowing elements are absolute, but the scrollbar is still appearing.

**Comment by alvarotrigo** [comment]
> The overflowing elements are absolute, but the scrollbar is still appearing.

Can you provide an isolated reproduction of the issue? Fullpage.js doesn't take absolute elements into account to calculate the height of the section.

**Comment by KingSora** [comment]
Yeah, check this fiddle: http://jsfiddle.net/9fq8vseu/
:)

**Comment by alvarotrigo** [comment]
Thanks for it, I'll have to investigate it.

**Comment by joeygaskin** [comment]
Hi Álvaro,

I'm posting here because I believe I may have the same question.

I'm currently using auto height on a section. Within this section, some slides have a greater height than others (due to content). This appears to create a problem for mobile responsiveness, making the section always the greatest height and never adjusting for the smaller, leaving a ton of space towards the bottom. Would you happen to have any suggestions? Thanks in advance.

**Comment by joeygaskin** [comment]
@King Sora you may just want to use "overflow-y: scroll" on your div container, and make scrolloverflow false. That seemed to solve my problem! Hope it helps someone.

**Comment by KingSora** [comment]
@joeygaskin Thanks! Unfortunetly this doesnt solve my problem... I've tried it but without any results. :(

**Comment by alvarotrigo** [comment]
Available now in 2.8.0.
Just use the class `fp-noscroll` to prevent the scrollbar to be created.
