### ISSUE TITLE
Bootstrap - Mobile Menu Toggle Issue

### ISSUE THREAD

**Issue by digitalprecision** [alvarotrigo/fullPage.js#1870]
http://stackoverflow.com/questions/35753718/bootstrap-fullpage-js-mobile-menu-toggle-issue

Just wondering if there is a fix for this?

**Comment by tmertz** [comment]
That question is gone. But I'm also experiencing an issue where Bootstrap 3 will collapse, even though there's plenty of width available.

**Comment by digitalprecision** [comment]
I ended up deleting it. I was using a transparent background so I just needed to add a background color for when the navbar was fixed and it would override the page content.
