### ISSUE TITLE
Links not navigating to different section

### ISSUE THREAD

**Issue by RohitDeorey** [alvarotrigo/fullPage.js#1871]
Hi,

I have more than one sections and I want to navigate from links in one section to other section on the same page. But when I am passing id or anchor values, it is changing the URL but not navigating to that section. Can anyone please help.

`<div id="section1" class="section">
    <a href="#page2">This is not navigating to page2</a>
</div>`

And here is my setting:

`$('#fullpage').fullpage({
                anchors: ['page1', 'page2'],
                sectionsColor: ['white', 'red'],
                scrollBar: true,
                verticalCentered: false,
                css3: true,
                menu: '#menu',
                loopTop: true,
                loopBottom: true
            });`

**Comment by RohitDeorey** [comment]
@alvarotrigo can you please help.

**Comment by alvarotrigo** [comment]
Can you reproduce it on the [demo site](http://alvarotrigo.com/fullPage/)?
If not, please add an isolated reproduction of it in jsfiddle or codepen as per the reporting issues rules.

Also, specify which browser you are using and its version and the OS.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
