### ISSUE TITLE
Android soft keyboard popup does not push screen up (bug)

### ISSUE THREAD

**Issue by craigstar** [alvarotrigo/fullPage.js#1872]
in our site http://www.floandfrank.com/users/sign_up. (first, click email sign up, and then you can see inputs). Android phone does not put screen up when inputs are focused and soft keyboard pops up while iphone pushes screen up as we expected.

**Comment by alvarotrigo** [comment]
> Android phone does not put screen up when inputs are focused and soft keyboard pops up while iphone pushes screen up as we expected.

Developers don't have control over those elements I'm afraid.
