### ISSUE TITLE
Reload only section, not whole page.

### ISSUE THREAD

**Issue by maniek910** [alvarotrigo/fullPage.js#1874]
Hello

I have small problem and to solve it, I need reload only section after click in "button", not whole page. I tried use $("#idSection").load(location.href + " #idSection"); but this doesn't work. It's possible doing something like this in this plugin ? 

Maybe i should add what kind problem i try solve. I use scrollOverflow: true and it's work pretty nice (on mobile device), but when I fadeIn() "wrap" in section and after fadeOut() this wrap, scrollOverflow doesn't work good, and this section need reload to work good again .

I will appreciate any help and I hope so you understand my problem.

Best regards,
Paweł

**Comment by alvarotrigo** [comment]
> It's possible doing something like this in this plugin ?

The plugin doesn't provide any way to do it, you should use jQuery or Javascript for that.

> Maybe i should add what kind problem i try solve. I use scrollOverflow: true and it's work pretty nice (on mobile device), but when I fadeIn() "wrap" in section and after fadeOut() this wrap, scrollOverflow doesn't work good, and this section need reload to work good again .

Use the [reBuild method](https://github.com/alvarotrigo/fullPage.js#rebuild) for it.
