### ISSUE TITLE
fullPage.js with scroll inside sections & sticky element

### ISSUE THREAD

**Issue by adrien-be** [alvarotrigo/fullPage.js#1876]
Hi all, 

Here is something I'm trying to do when using **fullPage.js _with_ scroll inside section**:
1. add a kind of “sticky" element
2. this element must have an absolute position when within a section, so that if it is very long (higher than your viewport), one can see the rest of it when scrolling within section
3. this element must slide to the next section whenever you scroll to another section
4. after sliding to another section, this element must come back to an absolute position like mentioned in step 2

#### So I did this step by step
1st implementation: scrollable sections & fixed element http://jsfiddle.net/AdrienBe/rjxfejgd/
2nd implementation: scrollable section & repeatable element in it http://jsfiddle.net/AdrienBe/7f2qpwvd/
3rd implementation: scrollable sections & sticky element (beta 1) https://jsfiddle.net/AdrienBe/f6f2nhch/

As you can see, the 3rd implementation works nicely when you are "from up to down" between sections. But it's kind of buggy when scrolling "from down to up".

Anyone would know how to improve this? I feel I may have a breakthrough myself but I'm guessing someone might already have implemented this :)

Thanks in advance

**Comment by adrien-be** [comment]
4th implementation: scrollable sections & sticky element (beta 2), I came up with a quick fix for the issue when scrolling back up. https://jsfiddle.net/AdrienBe/r2b6q4w1/

**Another approach** could be to force the section to go to the top of the next section when scrolling "from bottom to up". This way I believe the 3rd implementation could be left "as is" & work.

**Comment by alvarotrigo** [comment]
I would encourage you to ask in http://stackoverflow.com/ for this kind of questions. 
This forum is to treat directly related issues with fullpage.js.
