### ISSUE TITLE
When section  contain large then windo then scrolll is comeing  but that scroll not working smoothlly?

### ISSUE THREAD

**Issue by sagarjethi** [alvarotrigo/fullPage.js#1877]
contain is  large then window  size then scroll is coming. that scroll not working smooth. any   idea is solution of that any property we have set??
it  is very hard to scrooll

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/506

**Comment by sagarjethi** [comment]
Hello @alvarotrigo   i have  change in this
jquery.fullpage.js

in function =createSlimScrolling(element)
following value i have changed
 element.find(SCROLLABLE_SEL).slimScroll({
                        allowPageScroll: true,
                        height: scrollHeight + 'px',
                        size: '10px',
                        alwaysVisible: true,
                        wheelStep :5,   //this varible make scroll soomth
                        touchScrollStep:8
                    });

thank for your support
