### ISSUE TITLE
Not adding the data-menuanchor as expected

### ISSUE THREAD

**Issue by peerfischer** [alvarotrigo/fullPage.js#1878]
Hello,

I've a WP nav with this markup:
```html
<nav>
<div class="menu-hauptmenu-container">
    <ul id="primary-menu" class="menu">
        <li id="menu-item-20" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-20"><a href="#sektion+2">Sektion 2</a></li>
    </ul>
</div>
</nav>

```

I call fullpage.js with
`menu: '#primary-menu',`

but no data-menuabchor is added ...

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction of it in jsfiddle or codepen as per [the reporting issues rules](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
