### ISSUE TITLE
fullpage transition

### ISSUE THREAD

**Issue by faliqaiman** [alvarotrigo/fullPage.js#1880]
How to create a transition when we scroll to next section, some effect like fade in/out, 3x box rotating ect.. and go to next section.

**Comment by alvarotrigo** [comment]
Not a question for this forum.
This is to treat fullpage.js issues and directly related questions. Yours is a basic javascript / css knowledge question. You'd better ask in other place such as http://stackoverflow.com/ with the appropriate tags.
