### ISSUE TITLE
create another section if height of my content is bigger than viewport

### ISSUE THREAD

**Issue by Fattouh92** [alvarotrigo/fullPage.js#1881]
how to create dynamic section based on content height.
I want to show images of my team in website and I am using bootstrap and media queries to handle columns width and font adn everything but on my mobile maybe a section can only take 4 images while on ipad portrait can take a lot more of images and desktop is different

**Comment by alvarotrigo** [comment]
> how to create dynamic section based on content height.

The plugin doesn't provide any option for it. You'll have to do that by yourself.
