### ISSUE TITLE
animation delay issue

### ISSUE THREAD

**Issue by ing2l** [alvarotrigo/fullPage.js#1883]
Hi..  Can we set animation-delay css3 on fullpage.js?
Before, I have already used other animation css3 on my page and it was success.. But, when I put "animation-delay" on its css, my animation box still moving without delay. Can you help? thanks... I have put the script on attachment :)
[sample.zip](https://github.com/alvarotrigo/fullPage.js/files/162554/sample.zip)

**Comment by alvarotrigo** [comment]
You would have to be more specific with your issue. 
And following the [reporting issues rules](https://github.com/alvarotrigo/fullPage.js#reporting-issues), provide an isolated reproduction online.

I'll close the topic unless a reproduction online is provided.
