### ISSUE TITLE
Invert navigation menu

### ISSUE THREAD

**Issue by azirer** [alvarotrigo/fullPage.js#1884]
This project is fascinating! I was wondering if on this example http://alvarotrigo.com/fullPage/examples/navigationV.html is possible to invert the navigation dots only?

Meaning instead of 
```
<div id="fp-nav" class="right">
    <ul>
        <li><a href="#firstPage" class="active"><span></span></a>
            <div class="fp-tooltip right">First</div>
        </li>
        <li><a href="#secondPage"><span></span></a>
            <div class="fp-tooltip right">Second</div>
        </li>
        <li><a href="#3rdPage"><span></span></a>
            <div class="fp-tooltip right">Third</div>
        </li>
    </ul>
</div>
```

have this 

`<div id="fp-nav" class="right">
    <ul>
        <li><a href="#3rdPage" class=""><span></span></a>
            <div class="fp-tooltip right">Third</div>
        </li>
        <li><a href="#secondPage"><span></span></a>
            <div class="fp-tooltip right">Second</div>
        </li>
        <li><a href="#firstPage"><span></span></a>
            <div class="fp-tooltip right">First</div>
        </li>
    </ul>
</div>`

and keep everything else the same
Thank you!

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any way to do it. You would have to do it yourself with the provided fullpage.js functions and your own imagination.

Check out [this answer](http://stackoverflow.com/questions/35803439/how-can-i-assing-a-navigation-link-to-multiple-sections-in-fullpage-js/35848570#35848570) about how to create your own navigation system.
