### ISSUE TITLE
How can i make my navigation buttons highlight depending on page

### ISSUE THREAD

**Issue by Jongranberg** [alvarotrigo/fullPage.js#1886]
I can click my buttons and when i click them my float shows and stays on due to `.grey a:focus;` `.orange a:focus`... etc. But they dont highligt what page im on if i scroll instead of navigating by clicking. How can i fix that?
    
`    <div class="nav-bar">`
          ` <ul class="nav">`
           ` <li><a href="#firstPage" title="Acino knapp" id="range-logo">Texttttttttt</a></li>`
            `<li class="grey "><a href="#secondPage">FILOSOFI</a></li>`
            `<li class="orange"><a href="#3rdPage">UPPDRAG</a></li>`
            `<li class="green"><a href="#4thpage">KARRIÄR</a></li>`
            `<li class="yellow"><a href="#5thpage">ACADEMY</a></li>`
            `<li class="orange"><a href="#lastPage">KONTAKT</a></li>`
        `</ul>`
    `</div>`

**Comment by alvarotrigo** [comment]
Read about the use of the `menu` option in [the docs](https://github.com/alvarotrigo/fullPage.js#options):

> **menu:** (default false) A selector can be used to specify the menu to link with the sections. This way the scrolling of the sections will activate the corresponding element in the menu using the class active. This won't generate a menu but will just add the active class to the element in the given menu with the corresponding anchor links. In order to link the elements of the menu with the sections, an HTML 5 data-tag (data-menuanchor) will be needed to use with the same anchor links as used within the sections. Example:
```html
<ul id="myMenu">
    <li data-menuanchor="firstPage" class="active"><a href="#firstPage">First section</a></li>
    <li data-menuanchor="secondPage"><a href="#secondPage">Second section</a></li>
    <li data-menuanchor="thirdPage"><a href="#thirdPage">Third section</a></li>
    <li data-menuanchor="fourthPage"><a href="#fourthPage">Fourth section</a></li>
</ul>
```
```javascript
$('#fullpage').fullpage({
    anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'lastPage'],
    menu: '#myMenu'
});
```

You have examples available on [the plugin files](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) or even [online](http://alvarotrigo.com/fullPage/).

**Comment by Jongranberg** [comment]
Im sorry but i have no idea of how to do this can you maby explain what i need to add and where?

`    <div class="nav-bar">
        <ul class="menu">
            <ul class="nav">
                <li><a href="#firstPage" title="Acino knapp" id="range-logo">Texttttttttt</a></li>
                <li class="grey"><a href="#secondPage">FILOSOFI</a></li>
                <li class="orange"><a href="#3rdPage">UPPDRAG</a></li>
                <li class="green"><a href="#4thpage">KARRIÄR</a></li>
                <li class="yellow"><a href="#5thpage">ACADEMY</a></li>
                <li class="orange"><a href="#lastPage">KONTAKT</a></li>
            </ul>
        </ul>
    </div>
    <div id="fullpage">
        <div class="section">
            <div class="slide">
                <div class="main">
                    <div class="headmain">
                        <h1>KÄRNAN I DIN IT-VERKSAMHET</h1>
                    </div>
                    <div class="midmain">
                        <p>Behöver ni någon som kliver in och tar ansvar för ert IT-projekt eller kanske bara stöttning?</p>
                    </div>
                </div>

            </div>
        </div>
        <div class="section">
            <div class="slide">
                <div class="mainfilo">
                    <div class="bildfilo"></div>
                    <div class="headfil">
                        <h3>FILOSOFI</h3>
                    </div>
                    <div class="midfil">
                        <p>Trivs du med att arbeta agilt, med prestigelöshet och i en platt organisation där dina prestationer syns och uppmärksammas? Då kan Acino vara företaget för dig. Just nu har vi öppningar på följande positioner men vi är alltid intresserade av nya talanger </p>

                        <p>Trivs du med att arbeta agilt, med prestigelöshet och i en platt organisation där dina prestationer syns och uppmärksammas? Då kan Acino vara företaget för dig. Just nu har vi öppningar på följande positioner men vi är alltid intresserade av nya talanger</p>
                    </div>
                </div>

            </div>`

**Comment by Jongranberg** [comment]
Im sorry but i have no clue on where to begin. what should i add and where should i put it? Can you maby show me an example of the section div and navigation div?

`<div class="section">`
            `      <div class="slide">`
                `          <div class="mainfilo">`
                    `             <div class="bildfilo"></div>`
                    `             <div class="headfil">`
                        `         <h3>FILOSOFI</h3>`
                   `</div>`

**Comment by alvarotrigo** [comment]
For basic javascript knowledge you'd better ask somewhere like in stackoverflow.
