### ISSUE TITLE
canno't scroll long content with keyboard 

### ISSUE THREAD

**Issue by maxwell16** [alvarotrigo/fullPage.js#1887]
Hi alvaro
Sorry for my english, I do not speak very well english.
 I have a problem that i canno't fixe myself.
 Scrolling long content inside a section with mouswheel work very well when scrollOverflow is set to true but I would scroll the longest content with keyboard too but on keyup or keydown it bring me to anothers sections instead the longest content.
I try to element to do this with focus element but it don't work

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/1065

**Comment by maxwell16** [comment]
Thank you for the quick reply.

I know that slimscroll don't support keyboard scroll but I embed a new release of this package that handle this but keyboard for fullpage and slimscroll are mixing up.

but not important. i will wait you release about...

Thank a  lot
