### ISSUE TITLE
How to use data-menuanchor tag with dynamic data-anchor tag

### ISSUE THREAD

**Issue by Jekyll4k** [alvarotrigo/fullPage.js#1889]
> In order to link the elements of the menu with the sections, an HTML 5 data-tag (data-menuanchor) will be needed to use with the same anchor links as used within the sections.

I use fullpage.js for my worpress template. When I use static `anchors` and the given values for the `data-manuanchor` tag in a custom menu, everything works fine. Now I´m using the `data-anchor` tag with wordpress functions such as `$category->name` for the sections and `the_title` for slides when I query for posts. I would like to use those dynamically set `data-anchor` values for the `data-menuanchor` tags.

Can you help me?
Thanks for the great plugin!

**Comment by alvarotrigo** [comment]
And where is the problem? What have you tried so far?
Just use the `data-anchor` tag in each section and it should be alright.

**Comment by Jekyll4k** [comment]
Thanks for the quick response. The links to sections and slides work fine. My problem is to set up the data-menuanchors to apply the active class to the current section. As i read in the documentation it needs those data-menuanchors for this, doesn´t it?

**Comment by alvarotrigo** [comment]
Yeah, just create them dynamically as well.

**Comment by Jekyll4k** [comment]
I am trying to create them, maybe I find a way to not have to loop for the posts again in the navigation just to get the anchors in the right order. Plan B is using CSS and the fp-viewing class to style the menu items. As I am a beginner I tend to plan b. Thank you for your advice, keep up the good work!

**Comment by alvarotrigo** [comment]
You'd better ask in other place such as stackoveflow.com. This forum is just to treat directly related fullpage.js issues and not PHP or wordpress ones.

**Comment by Jekyll4k** [comment]
I will keep this in mind.


Sent from a mobile device.

**Comment by mac2net** [comment]
Hi Jekyll4k
I have done a lot of work with fullpage.js and wordpress.
If you would like some help please tweet me either at @MacsandMoreDH or @5docorg.

Cheers
Mike

**Comment by Jekyll4k** [comment]
Hi Mike,

thanks for the offer, I appreciate it. Read my tweet :)


Sent from a mobile device.
