### ISSUE TITLE
Issue with footer and setAutoScrolling(false)

### ISSUE THREAD

**Issue by azirer** [alvarotrigo/fullPage.js#1890]
Hi here is the issue: http://codepen.io/anon/pen/vGGZJe

When setting setAutoScrolling(false) and scrolling down to footer it doesn't stay there.

How can this be done?

**Comment by alvarotrigo** [comment]
Because by default fullpage.js uses `fitToSection: true`. Just turn it to `false` by using the option or the method fullpagej.s provides.
