### ISSUE TITLE
One section doesn't scroll on mobile versione

### ISSUE THREAD

**Issue by ilPas** [alvarotrigo/fullPage.js#1891]
Good morning at all!
I have used fullpage.js in a project but i have a problem with scrolling on mobile version.
When i arrive in a specified tab i can't scroll down with touch, only with link, by the way on desktop it's all ok

The link is http://www.hikkaduwabrand.com on fourth section

Thanks a lot

**Comment by alvarotrigo** [comment]
If you believe it is a fullpage.js bug you will have to reproduce the issue in an isolated environment such as jsfiddle or codepen with the minimum external css and js. 

Otherwise, I'm afraid this forum is not to provide support for specific websites, but for the plugin itself.
