### ISSUE TITLE
fullpage.js not working in wordpress (i am not using wp-fullpage)

### ISSUE THREAD

**Issue by rishinhr** [alvarotrigo/fullPage.js#1892]
I have created an website using fullpage.js with bootstrap now i want to convert it into a Wordpress theme. I have done a lot of work making the website but for some reason i want to convert the whole website into a Wordpress theme. I have checked Questions asked before but none of them helped me.

So, here we go... the code below are the code of wordpress theme i made so far it is not the whole code, the possible error may be i am defining the sections in a wrong way. the sections are not working neither auto-scrolling in wordpress.

index.php

<?php get_header(); ?>

  

      <div id="fullpage">
        <div class="section" id="section0">
            <div class="home_text" >
                    <h1>Section 1</h1>
                 </div>
        </div>

        <div class="section" id="section1">
            <div class="home_text" >
                    <h1>Section 2</h1>
                 </div>
          </div>

      </div>
  

<?php get_footer(); ?>

header.php

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>My Website</title>
  </head>

  

  <body>
  

    <div id="header">

      <div id="header_logo">
        <a href="index.html"><div id="header_logo_img"></div></a>
      </div>
  </div>

  

footer.php

        <?php wp_footer(); ?>
  </body>
</html>

functions.php

<?php 

    function biscuits_enqueue() {
        wp_enqueue_script( 'jquery-ui', 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.js', array( 'jquery') );
        wp_enqueue_script( 'bootstrap', get_template_directory_uri(). '/js/bootstrap.min.js', array( 'jquery' ) );
        wp_enqueue_script( 'fullpage', get_template_directory_uri(). '/js/jquery.fullPage.js', array('jquery'));
        wp_enqueue_script( 'sidemenu', get_template_directory_uri(). '/js/sidemenu.js', array( 'jquery' ) );
        wp_enqueue_script( 'fastclick', get_template_directory_uri(). '/js/fastclick.js', array( 'jquery' ) );
        wp_enqueue_script( 'app', get_template_directory_uri(). '/js/app.js', array( 'jquery' ) );
        wp_enqueue_script( 'modernizer-ui', 'http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js', array( 'jquery') );
    }
    add_action('wp_footer', 'biscuits_enqueue');

?>

i have checked the fullpage.js is importing in the page but not working maybe i am defining the sections in a wrong way.

**Comment by alvarotrigo** [comment]
This is not a forum to treat wordpress problems but only fullpage.js ones. 
I can only help you with the plain HTML resulting of your PHP code. 

Reproduce the issue in jsfiddle or codepen if you believe its a fullpage.js issue and not a PHP one.

**Comment by rishinhr** [comment]
Okay thanks for the help, sorry for posting it here.
