### ISSUE TITLE
Conditional paddingTop

### ISSUE THREAD

**Issue by lecollective** [alvarotrigo/fullPage.js#1894]
As the screen gets wider, I'd like to change the height of the header, which means updating the PaddingTop attribute, but the issue is, if I do an on resize if else statement fullpage.js does not like multiple instances being called.

Any other way of doing this?

**Comment by lecollective** [comment]
Tried this:


`
		$(window).on('resize', function() {
			if ($(window).width() > 850) {
				console.log('More than');
                $('.fullPageLargeInit').fullpage();
				
			} else {
				console.log('Less than');
				$.fn.fullpage.destroy('all');
				$('.fullPageSmallInit').fullpage();
				
				
			}
		});
		
		function fullPageLargeInit() {
            if ($(window).width() > 850) {
				$.fn.fullpage.destroy('all');
				$('#page').fullpage({
					fixedElements: '#header, #landscape',
					paddingTop: '47px',
					verticalCentered: true,
					fitToSection: true,
					controlArrows: false
				});
            }
        }
		function fullPageSmallInit() {
            if ($(window).width() < 850) {
				$.fn.fullpage.destroy('all');
				$('#page').fullpage({
					fixedElements: '#header, #landscape',
					paddingTop: '22px',
					verticalCentered: true,
					fitToSection: true,
					controlArrows: false
				});
            }
        }
		`


Doesn't seem to recognise $.fn.fullpage.destroy('all');

**Comment by lecollective** [comment]
This has it on initial load, but can't figure resize out

`if ($(window).width() < 860) {
					var fullPageCreated = false;
					createFullpage();
				}
				else {
					
					var fullLargePageCreated = false;
					createLargeFullpage();
				}
				
				$(window).resize(function() {
				if ($(window).width() < 860) {
					console.log('Less than');
					var fullPageCreated = false;
					$.fn.fullpage.destroy('all');
					createFullpage();
				}
				else { 
					console.log('More than');
					var fullLargePageCreated = false;
					$.fn.fullpage.destroy('all');
					createLargeFullpage();
				}
				});
						
			
				function createFullpage() {
				if(fullPageCreated === false) {
				fullPageCreated = true;
					$('#page').fullpage({
						fixedElements: '#header, #cat-menu',
						paddingTop: '82px',
						verticalCentered: false,
						fitToSection: true,
						controlArrows: false,
					});
				}}
				
				function createLargeFullpage() {
				if(fullLargePageCreated === false) {
				fullLargePageCreated = true;
					$('#page').fullpage({
						fixedElements: '#header, #cat-menu',
						paddingTop: '122px',
						verticalCentered: false,
						fitToSection: true,
						controlArrows: false,
					});
				}}`

**Comment by alvarotrigo** [comment]
I would recommend you to deal with padding by yourself by using CSS. Just create a container in the section and use the padding you want for it. 

The paddingTop option was mainly created to deal with scrollOverflow. But I always recommend people to deal with it by themselves if they can. 

I won't add a conditional padding option. I believe that's belong the plugin's scope and the paddingTop option is just for people who don't know CSS or who want to deal with scrollOverflow.

**Comment by lecollective** [comment]
Thanks alvarotrigo yeah, I just figured that would be the best route!
