### ISSUE TITLE
Change navigation from a div to a nav element

### ISSUE THREAD

**Issue by Jekyll4k** [alvarotrigo/fullPage.js#1899]
Hi Alvaro,

 I wondered why the navigation for horizontal slides and vertical sections do not use the `<nav>` element.

In the unminified fullpage.js.min I changed line 137
from
`On.append('<div id="' + R + '"><ul></ul></div>');`
to
`On.append('<nav id="' + R + '"><ul></ul></nav>');`
to appy the `<nav>` class to the vertical navigation.
For the horizontal navigation I changed line 661
from
`e.append('<div class="' + N + '"><ul></ul></div>');`
to
`e.append('<nav class="' + N + '"><ul></ul></nav>');`

I´m telling you this only to make sure that I dont break any functions used by the plugin. Are you ok with the modification?

**Comment by alvarotrigo** [comment]
> I wondered why the navigation for horizontal slides and vertical sections do not use the <nav> element.

Not supported by older versions of IE.
