### ISSUE TITLE
full background image version bug in firefox?

### ISSUE THREAD

**Issue by antonret** [alvarotrigo/fullPage.js#1900]
Hi,
in full background images version ( http://alvarotrigo.com/fullPage/examples/backgrounds.html ) sections jump over... 

for example: 
I'm on a section 1 making scroll and it scrolls to section 2 and then automatically to section 3.

Same issue in both directions (scrolling up or down)

Both trackpad and mouse
OS X El Capitan.
FF 45.0

Thank you,
Anton.

**Comment by alvarotrigo** [comment]
Not able to reproduce it I'm afraid. The backgrounds example has technically nothing different from the [main demo](http://alvarotrigo.com/fullPage/) so I see no reason why you should have issues only on it.

**Comment by lcl-101** [comment]
hello,thank you,it is very important to me.
https://www.wenjf.com  
you can look, it is my example.
what do you think of?

**Comment by FreshFlesh** [comment]
I am afraid i have the same issue with the above example page. 

Os X El Capitan
Firefox 47.0

**Comment by alvarotrigo** [comment]
> Main demo is ok.

Then I don't anything else to add. Not a fullpage.js issue.
