### ISSUE TITLE
Fixed header and footer - Contain image to div between

### ISSUE THREAD

**Issue by billymedia** [alvarotrigo/fullPage.js#1901]
I have a fixed header of 100px high, and a fixed footer of 150px high, between is a div with a background image, the bg image gets displayed fullscreen, is it possible to have it only apply to the div that sits between the header and footer? Problem is that some of the image is getting hidden behind the header and footer.

**Comment by alvarotrigo** [comment]
> is it possible to have it only apply to the div that sits between the header and footer?

Create a container and apply the background image to it, not to the section itself.
