### ISSUE TITLE
Using anchors seems to disable the active class

### ISSUE THREAD

**Issue by dtrinh50** [alvarotrigo/fullPage.js#1902]
I am using the dot navigation option. The active class is applied when I don't have any anchors, but when I add anchors to the web app, then the active class no longer gets assigned to the active navigation dot.

Is there a way that I can get around this issue?

**Comment by alvarotrigo** [comment]
As per https://github.com/alvarotrigo/fullPage.js#reporting-issues, provide a reproduction of it. It doesn't take place on the demo pages and therefore it seems to be your own problem not a fullpage.js one.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
