### ISSUE TITLE
Background Video

### ISSUE THREAD

**Issue by brz1na** [alvarotrigo/fullPage.js#1903]
Hi gays love the plugin.

But the autoPlay is not working for me on the Phones (any android or iphones).
and i still see the controls which you will see in the examples below i put to false.
If i remove the controls option the video won't even start on the phones on desktop is fine.
Examples :

js:
```
afterRender: function () {
        $('video').get(0).play();
      }
```

html:
```
<video autoplay loop muted controls="false" id="myVideo">
<source src="imgs/Comp_1.mp4" type="video/mp4">
<source src="imgs/Comp_1.webm" type="video/webm">
</video>
```
css:
```
#myVideo{
		position: absolute;
		right: 0;
		bottom: 0;
		top:0;
		right:0;
		width: 100%;
		height: 100%;
		background-size: 100% 100%;
  		background-position: center center;
  		background-size: contain;
   		z-index:3;
	}
```

DEMO:
http://hellermann.com/testzone/

Can you tell me what am i doing wrong?
ty in advance!
A desperate dev!

**Comment by alvarotrigo** [comment]
> But the autoPlay is not working for me on the Phones (any android or iphones).

[It never does](https://www.aerserv.com/why-does-video-autoplay-on-mobile-devices-not-work/), no matter if you use fullpage.js or not.

**Comment by isaacloft** [comment]
Never works on mobile?? Mine is working fine. I think palysinline is key and preload
` <video id="header_video" class="header_video" muted playsinline preload="auto" autoplay loop data-keepplaying>
                            <source data-src="./video/index.mp4" type="video/mp4">
                            <source data-src="./video/index.webm" codecs="vp8, vorbis" type="video/webm" media="all and (max-width: 1200px)" />
                        </video>`
