### ISSUE TITLE
conenteditable compatibility

### ISSUE THREAD

**Issue by filipeperdigaosousa** [alvarotrigo/fullPage.js#1904]
in order to work with contenteditable elements, you can add a new rule to check if element is has contenteditable attribute, allowing to use the key controls

```javascript
function keydownHandler(e) {

            clearTimeout(keydownId);

            var activeElement = $(':focus');

            if(!activeElement.is('textarea') && !activeElement.is('input') && !activeElement.is('select') &&
                options.keyboardScrolling && options.autoScrolling){
                var keyCode = e.which;

                //preventing the scroll with arrow keys & spacebar & Page Up & Down keys
                var keyControls = [40, 38, 32, 33, 34];
                if($.inArray(keyCode, keyControls) > -1){
                    e.preventDefault();
                }

                controlPressed = e.ctrlKey;

                keydownId = setTimeout(function(){
                    onkeydown(e);
                },150);
            }
        }
```

**Comment by alvarotrigo** [comment]
Please explain what you've added, why and what problem does it solve.

**Comment by filipeperdigaosousa** [comment]
I didn't add anything to your code but if you change it to something like 

"
 if(!activeElement.is('textarea') && !activeElement.is('input') && !activeElement.is('select'),  &&
                options.keyboardScrolling && options.autoScrolling && !activeElement.hasAttr('contenteditable')){
"

it allows you to not prevent default behaviours for those keys in contenteditable elements.

If you dont know, content editable elements allows to edit inline content without inputs or text areas.
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_Editable

With your conditions we can use content editable elements but spaces are ignored because you prevent space key default behaviour

**Comment by alvarotrigo** [comment]
Interesting... I didn't know about that HTML5 attribute.

I guess we also have to check if it is not set to `false`.

**Comment by filipeperdigaosousa** [comment]
You are really awesome if you do those changes today.  Seems to be a simple
change that can help me so much
Em 17/03/2016 11:31 da tarde, "Álvaro" <notifications@github.com> escreveu:

**Comment by alvarotrigo** [comment]
Solved on the `dev` branch.

**Comment by alvarotrigo** [comment]
Done in 2.7.9.
