### ISSUE TITLE
Slides' menu

### ISSUE THREAD

**Issue by panczarny** [alvarotrigo/fullPage.js#1905]
Hello,
there's a _menu_ option https://github.com/alvarotrigo/fullPage.js#options for each **.section** with anchors, how can I make the one for each **.slide** in **.section**?
What I want is to add an **.active** class to corresponding **li** or **a** item in **#slide_menu**
Here is an example
http://codepen.io/panczarny/pen/dMNbZj

Cheers

**Comment by alvarotrigo** [comment]
> how can I make the one for each .slide in .section?

The plugin doesn't provide such option.
You'll have to create the menu by yourself by using the plugin function `moveTo` and activate or desactivate the menu elements by using callbacks such as `onLeave` or `afterLoad`.

Check out this: http://blogs.candoerz.com/question/77283/fullpagejs-how-to-add-css-class-quotactivequot-to-slide-anchor.aspx
