### ISSUE TITLE
On mobile, try to focus on an input field, instantly unfocuses. Cannot use the input field

### ISSUE THREAD

**Issue by vkaratzi** [alvarotrigo/fullPage.js#1908]
Hello, this is the site:

http://www.alexioslizos.com/#contact

On mobile ONLY (have checked chrome, firefox, opera on android 6.0.1) Whenever i try to tap the input field, it focuses for some milliseconds, and instantly unfocuses. 

This is the javascript initialization code for fullpage:

$('#fullpage').fullpage({
        sectionsColor: ['transparent', 'transparent', 'transparent', 'transparent', 'transparent'],
        anchors: ['home', 'bio', 'ensembles', 'calendar', 'recitals', 'teaching', 'contact'],
        menu: '#menu',
        scrollingSpeed: 1000,
        continuousVertical: false,
        navigation: true,
        scrollingSpeed: 600,
        responsive: 100,
        css3: true,
        slidesNavigation: true
    });

I believe that this is because the site detects a change in height, causes a resize - redraw, and that takes away the focus from the input fields. How could I fix it? Can we somehow on touchstart disable the resize event so that it does not trigger a redraw?

I haven't found a solution by myself. fullpage version is 2.7.4.

Thank you.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/145

**Comment by vkaratzi** [comment]
Hello again, I have read the whole thread, 
the problem isn't that the content scrolls, it's that the keyboard disappears (it shows then vanishes)
along with the content being shrunk, because of the reduced height, because of the keyboard.

I have tried both the 

$('input').focus(function() { $.fn.fullpage.rebuild; })
$('input').blur(function() { $.fn.fullpage.rebuild; })

and the

$('input').focus(function() { $.fn.fullpage.setAutoScrolling(false); })
$('input').blur(function() { $.fn.fullpage.setAutoScrolling(true); })

but those commands don't work. I see you have list it as bug/unfixable, is there no fix for this?

I cannot seem to find any further info to help me in #145

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction with the less possible external CSS or JS.

**Comment by vkaratzi** [comment]
The site has not been developed by me, I was lost in a css file of 3000 lines. This was a media query css error with input and form shown as display: none. I just found out.

Thank you, sorry for any inconvenience. I will now close the issue.
