### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by brz1na** [alvarotrigo/fullPage.js#1914]
Hey ,

I wont to use parallax on the background of each slide.
Can anyone suggest the best plugin to solve these.
and are there any parameters of fullpage.js that i have to configure?

Want to achieve something like these
http://www.sony-asia.com/microsite/mdr-10/#aboutPage

on these web:
http://hellermann.com/testzone/

ty in advance...

**Comment by alvarotrigo** [comment]
Check the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
