### ISSUE TITLE
Problem with Angular

### ISSUE THREAD

**Issue by mmautomatizacion** [alvarotrigo/fullPage.js#1918]
Hi,
I'm trying to use fullpage.js in a Angular App. For do that, I have to disable the routing of Angular, and fullpage.js seems to works correctly. The problem is when I go to a concrete section (anchor) throw URL. It goes to first section instead the section defined in url. 
![screen](https://cloud.githubusercontent.com/assets/16716255/13918072/22edd862-ef65-11e5-8a41-317841d51a86.png)

It occurs when I use the ng-include directive of Angular. This directive includes the content of a HTML file inside a element. Here is the code of index file and included file:

**index.html**
`<body>
    <div ng-include="'content.html'"></div>
<body>`

**content.html**
`<div class="full-page">
    <div data-anchor="section1">Section 1</div>
    <div data-anchor="section2">Section 2</div>
    <div data-anchor="section3">Section 3</div>
    <div data-anchor="section4">Section 4</div>
</div>`

This code works correctly but always show first the section 1, even when the url is "http://url/#/section3"

What can I do?

Thanks

**Comment by alvarotrigo** [comment]
Have you took a look at this repo? [fullpage.js angular directive](https://github.com/hellsan631/angular-fullpage.js)

**Comment by mmautomatizacion** [comment]
Thanks @alvarotrigo, but I tried it and has the same problem. The example made by the author works even worst, cause the url doesn't change on section change. You can test it here: [example of Angular full-page](http://hellsan631.github.io/angular-fullpage.js/#/main)

**Comment by alvarotrigo** [comment]
Can you provide a reproduction online so I can see it?
Also, make sure you are not using the `active` class in any section.

**Comment by mmautomatizacion** [comment]
Sure, [here](https://plnkr.co/edit/5p1Cio7v7KFpZzKN1kLl?p=preview) you can access to a example in  plunker. In the "index.html" file you can see a div with ng-include directive. With this code the problem appear. If you comment this line, and uncomment the sections divs, the page works correctly. Result: if I use ng-include directive, fullpage.js doesn't init correctly.

**Comment by alvarotrigo** [comment]
Sorry but I can not help you with it. I do not have the necessary angular knowledge. 
I would recommend you to ask in http://stackoverflow.com/

**Comment by mmautomatizacion** [comment]
Hi Alvaro,
I have developed a directive of fullPage.js for work with Angular.js. It's a very quick and crude version, but It works! If someone need it, can found it here: [Angular fullPage.js](https://github.com/mmautomatizacion/angular-fullpage.js)

**Comment by alvarotrigo** [comment]
Thanks! Feel free to commit a change in the Readme on the `dev` branch.
You can add it in the Resources llist, ad the end.

**Comment by hellsan631** [comment]
Heyo. I'm the author of the angular repo alvarotrigo linked. If possible I would like a crack as solving this. It might be related to using ng-include instead of using views, depending on whats going on during angular's digest cycle, if the find selectors in the link function are working on the dynamic content loaded in.

**Comment by mmautomatizacion** [comment]
Hi Hellsan631, thnaks for the answer. The problem of use views is that you are using routing. Angular routing is not compatible with hash management of fullPage.js (If the url change, the route change, the views change too). The best way, I think, is discard using of Angular routing, and adapt the library for Angular. [Here](https://github.com/mmautomatizacion/angular-fullpage.js) you have the code adapted for work with Angular.
