### ISSUE TITLE
Knowing issue with Bootstrap 3 Modal?  

### ISSUE THREAD

**Issue by hughred22** [alvarotrigo/fullPage.js#192]
Hi, 

Here is the demo page: http://hughdesign.net/radco-v2/home-2.html
Click the buy button will call a BS Modal window. You can see the window is on top right of the page under the dark bg overlay. And the overlay is unclickable and can not be closed :( 

How to address the code to make this AWESOME AWESOME plug-in work with Bootstrap Modal (since my entire site is power by Bootstrap)

**Comment by sbellver** [comment]
Same here. I need disable css3:true or modal it's not showed :(
