### ISSUE TITLE
Skipping a section when scrollingtop ( or down )

### ISSUE THREAD

**Issue by elPimps** [alvarotrigo/fullPage.js#1920]
Hi
the js works like a charm but i need a specific thing for my website.
Actually i need to skip a section only when scrolling top. That's because i have the second section with auto-height and i don't want to see it when scrolling top ( it's to be seen only when scrolling down ).

Is this possible ?

**Comment by alvarotrigo** [comment]
The plugin doesn't provide a shortcut for it. You might be able to do it somehow, but that's not part of the plugin.

**Comment by elPimps** [comment]
Do you think it's possible? Any hint where i can start testing?

**Comment by alvarotrigo** [comment]
Look at [the answer I provided on stackoverflow](http://stackoverflow.com/a/35335858/1081396).

I'll copy it here:

**You can't do that**. Fullpagejs will only expect sections between sections.

What you can do instead is playing with fullpage.js options. Use them as sections, use the `fp-auto-height` class for them so they won't be full screen, and use some callback to force fullpage.js to jump them when you are about to arrive to them:

```javascript
    $('#fullpage').fullpage({
        sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
        onLeave: function(index, nextIndex, direction){
            var destinationToIgnore = $('.section').eq(nextIndex -1).hasClass('ignore');
    
        	if(destinationToIgnore){
            	var destination = (direction === 'down') ? nextIndex + 1 : nextIndex - 1
                $.fn.fullpage.moveTo(destination);
            }
        }
    });
```

I've coded this script in a way that you just need to use the class `ignore` in your section to force fullpage.js to ignore it, for example:

```html
    <div class="section fp-auto-height ignore">
        <div class="parallax">
            PARALLAX
        </div>
    </div>
````
[Reproduction online](http://jsfiddle.net/97tbk/1067/)

**Comment by elPimps** [comment]
Mhhh i see, but i cannot skip that section cause it have text ecc...
My goal would be fitting the section on the bottom of viewport instead on top then.

**Comment by alvarotrigo** [comment]
Work out your logic in the callback. That's up to you.

**Comment by elPimps** [comment]
(last question)
so there isn't a way to force the plugin to display all sections fixed on the bottom of viewport (sections with auto-height too )?
(actually when scrolling down the section is displayed on the bottom, when scrolling top it's fixed on the top of viewport)

**Comment by alvarotrigo** [comment]
The plugin doesn't provide a way to do it. Not easy to do in any case.

**Comment by elPimps** [comment]
Thanks anyway!

**Comment by elPimps** [comment]
$(document).ready(function() {

    $('#application').fullpage({

    onLeave: function(index, nextIndex, direction){
        var destinationToIgnore = $('section').hasClass('ignore');

        if(destinationToIgnore){
            var destination = (direction === 'down') ? nextIndex + 1 : nextIndex - 1
            $.fn.fullpage.moveTo(destination);
        }
    },


    afterLoad: function(anchorLink, index){
        var loadedSection = $(this);

        if(index == 1){
         $('.section-intro').removeClass('ignore');            
        }
        if(index == 3){
         $('.section-intro').addClass('ignore');            
        }

    }

    });


});

so far i got into this solution but when i reach section 3 then i'm unable to scroll back to section 1.
any hint?
