### ISSUE TITLE
afterSlideLoad is not fired if slide is loaded after a section change

### ISSUE THREAD

**Issue by bpyrate** [alvarotrigo/fullPage.js#1921]
See your callbacks example: http://alvarotrigo.com/fullPage/examples/callbacks.html

If you are moving to section two which includes slides only the afterLoad callback is fired, but not the afterSlideLoad which should be fired also, because you are going to a slide.

Usage example: if you change e.g. fixed header styles depending on sections and(!) slides background, you would like to use the afterLoad and/or afterSlideLoad callbacks to identify the current loaded slide to change the header style. That works for slides when you change them (moving left or right) but not if you are landing on a slide via a section change (moving up or down).

afterSlideLoad should be fired whenever a slide is loaded, even if you change to a section that contains slides.

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/1124
