### ISSUE TITLE
Request/Question: scroll directly to target page without seeing all in-between pages

### ISSUE THREAD

**Issue by crizpeecritter** [alvarotrigo/fullPage.js#1922]
Hi. I'm building a portfolio site. I want 3 sections that scroll vertically. Section 1 will have a slider with numerous slides showing art projects. Section 1, slide 1 will contain a bunch of thumbnails with links for all the art projects, and when you click on one of the thumbs, you will scroll to the corresponding slider page for that project.

The normal behavior for fullpage is to scroll past all of the slides and stop on the target slide. What I would like to do is scroll to the target slide directly. For example, let's say you click on thumbnail 25 on the first slide. Normal behavior is to scroll to the right and past 24 slides and stop on slide 25. I would like it to scroll right but for only one slide. I know you can do this be disabling animations, but I want to keep the animation, just have it appear that the target slide is always only one slide away.

Is this possible? I've gone through all the documentation and the issues/requests, and I can't see how it might be done. If not currently possible, could the feature be added to fullpage at some point? Thanks in advance!

**Comment by alvarotrigo** [comment]
> but I want to keep the animation, just have it appear that the target slide is always only one slide away.

Nop.
