### ISSUE TITLE
Problem with first section - can't scroll to 1st section (or it doesn't show)

### ISSUE THREAD

**Issue by emmasalmon** [alvarotrigo/fullPage.js#1923]
Thanks for a great plugin!

I'm stuck and can't find the error myself... I have problems with the first section. It's visible when the page first loads, but after scrolling down to other sections I can't scroll back to 1st section. I'm using loopBottom and the first section isn't shown then either (when it goes back to the top). The url is showing the anchors correctly, so it's "domain.com.../#section-1" even if the section isn't visible.

Any tips or tricks..? I would be SO grateful!

http://dev.u8448419.fsdata.se/shapeofmind/
To view the page, use
user: kund
pw: MildredsKund
(this is just a protection to make this dev folder not public)

**Comment by alvarotrigo** [comment]
It's working for me. Also, the anchor is not `section-1` but `p1`
