### ISSUE TITLE
Does not work in Firefox or IE

### ISSUE THREAD

**Issue by zinggimaging** [alvarotrigo/fullPage.js#1929]
I finished my site using fullpage.js and it looks good in Safari but it does not work at all in Firefox or IE. Chrome is ok (but for some reason it does not load my background image). If anyone can help please, I am not skilled enough in this area to find the problem. Please help, Thanks!
Melinda
Switzerland
www.zinggimaging.com

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue. I would encourage you to ask in http://stackoverflow.com/
