### ISSUE TITLE
Implementation with particles.js causes lag in both particles and moving slide on mobile.

### ISSUE THREAD

**Issue by johnkorhel** [alvarotrigo/fullPage.js#1930]
Hi. So I'm working on a website for my high school Webmaster competition. There is one problem I just can't seem to crack.

 I was able to use fullpage.js and particles.js flawlessly together. If you don't know, particles.js is a lightweight particles library that can give your site a kind of molecule affect. 

Now, I believe my problem is associated with the table cell layout. As I view it on mobile, the table cell goes to incredible heights, especially on my 1440p phone. This did not happen before without fullpage.js. Is there anyway I can completely disable the table-cell so that the height is fixed and it does not scale to whatever resolution the screen is? 

My site is [here](http://tsa.johnkorhel.com/). You'll notice that the site works the way I want it to when just scaling the site, but when you go into the responsive test in inspect element, it basically zooms out the site on most mobile devices. Actually testing it on a mobile device, the particles and transitions between my pages are laggy. Any idea what's causing this? Thanks.

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue I'm afraid. You did good asking first on stackoveflow.
