### ISSUE TITLE
scrollOverflow is under the fixed header and footer

### ISSUE THREAD

**Issue by lininu** [alvarotrigo/fullPage.js#1931]
I want to make scrollOverflow shown in the above of the fixed header and footer. (The scrolling bar is shown in the above of fixed div.)
But in examples, the scrollOverflow is under header and footer even I change the z-index of header and footer. I hope it 's clear to see, so I want to fixed it.
Do you have any solution to solve this problem? Thank you.
P.S. I make the under case of scrollOverflow:true and fixed header in CodePen: http://codepen.io/Inu/pen/RagBBE

**Comment by alvarotrigo** [comment]
Use the `paddingTop` and `paddingBottom` options to solve the problem.

**Comment by lininu** [comment]
I found these options. Thank you very much!
