### ISSUE TITLE
silent move from another url?

### ISSUE THREAD

**Issue by kevhil** [alvarotrigo/fullPage.js#1932]
Hey I have a fullpage site with 7 sections.
all works fine and the move animations to every sections works also.
i have some links which goes to other intern urls.
on these sites i've made a back-button which goes back to the specific anchor.

example: on "index2.html" is a back-button which goes back to "index1.html#section3"

what i want to do is a silentMoveTo this anchor. from one url to other url. but how could i realize that when that function can't interact between urls?  i want to keep the normal animation.  but on backbutton there should be a silentmove

**Comment by alvarotrigo** [comment]
> but on backbutton there should be a silentmove

The plugin doesn't provide such an option.
