### ISSUE TITLE
fp-auto-height footer unwanted behaviour on resize

### ISSUE THREAD

**Issue by dannygiolo** [alvarotrigo/fullPage.js#1933]
If you are on your last section set on fp-auto-height (to mimic a footer) and then switch orientation from portrait to landscape the section fills up the whole viewport (footer gets moved to the top leaving the whole blank area below visible).

The orientation switch is what trigger this behaviour on both mobile and desktop, but it also happens on desktop when you just resize vertically.
Scrolling up and the down again fixes the issue.

This can be tested on your website: [http://www.alvarotrigo.com/fullPage/examples/autoHeight.html#3rdPage](url)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by alvarotrigo** [comment]
Solved in the `dev` branch in fullpage.js 2.7.9.

**Comment by alvarotrigo** [comment]
Fixed in 2.7.9
