### ISSUE TITLE
scrollOverflow Issue on Ember js app

### ISSUE THREAD

**Issue by SamBaqai94** [alvarotrigo/fullPage.js#1936]
Hi
I am making an Ember app and I am using fullpage as a main plugin. Everything works well except scrollOverflow. I have four templates and two of them have scrollOverflow. Everytime I refresh my app from different template and then go to that specific template, scrollOverflow doesn't appear but when refresh from same template then it appears.

**Comment by alvarotrigo** [comment]
Sounds like you need to use the `reBuild` function every time you update your view.

**Comment by SamBaqai94** [comment]
any idea where should I put this rebuild this is code right now:
import Ember from 'ember';


export default Ember.Component.extend({
	didInsertElement: function(){
		try{
			$.fn.fullpage.destroy('all');
		}catch (err) {
			// do nothing
		}
		// setup fullpage
		this.$('#fullpage').fullpage({
			sectionsColor: ['#ffffff', '#ffffff', '#ffffff', '#ffffff'],
			anchors: ['services', 'app-development', 'system-integration', 'cms-implementation'],
			css3:true,
			scrollOverflow:true,

			easingcss3: 'cubic-bezier(0.755, 0.050, 0.855, 0.060)',
			touchSensitivity: 50,
			afterLoad: function(anchorLink, index, eview){
					$.fn.fullpage.reBuild();


				if ( $("#service-summary-1") ) {
			   $('#service-summary-1').click(function(){

					 $.fn.fullpage.silentMoveTo('app-development');
				 });
				}
				if ( $("#service-summary-2") ) {
			   $('#service-summary-2').click(function(){
					 $.fn.fullpage.silentMoveTo('system-integration');
				 });
				}
				if ( $("#service-summary-3") ) {
			   $('#service-summary-3').click(function(){
					 $.fn.fullpage.silentMoveTo('cms-implementation');
				 });
				}
		}

		});


		//setup mouse and key events
		$('.service #section-summary').bind('mousewheel', function(e){
			if(e.originalEvent.wheelDelta /120 > 0) {
				e.stopPropagation();
				$(".nav-index")[0].click();
			}

		});
    //#section-summary starts
		/*$('.service #section-summary').bind('keyup', function(e){
			var x = e.which;
			if (x==38) {
				e.stopPropagation();
				$(".nav-index")[0].click();
			}
		});
		$('.service #section-summary').bind('keydown', function(e){
			var x = e.which;
			if (x==40) {
				  $(".service #section-summary").blur();
			}
		});*/
		//#section-summary ends

		$('.service #section-cms-implementation').bind('mousewheel', function(e){
			if(! (e.originalEvent.wheelDelta /120 > 0)) {
				e.stopPropagation();
				$(".nav-work")[0].click();
			}
		});
   //#section-cms-implementation starts
		/*$('.service #section-cms-implementation').bind('keydown', function(e){
			var x = e.keyCode;
			if (x==40) {
				e.stopPropagation();
				$(".nav-work")[0].click();
			}
		});
		$('.service #section-cms-implementation').bind('keyup', function(e){
			var x = e.keyCode;
			if (x==38) {
		     $(".service #section-cms-implementation").blur();
			}
		});*/

		//.service #section-cms-implementation ends

	},
	willDestroyElement:function(){
		// do nothing
	}
});

**Comment by alvarotrigo** [comment]
> any idea where should I put this rebuild this is code right now:

You should better ask that in another place where they know about Ember.js.
As i said, you should use it after you update your view dynamically.
