### ISSUE TITLE
Navbar and controlArrows

### ISSUE THREAD

**Issue by Alpha4** [alvarotrigo/fullPage.js#1937]
Hello,

When setting both navigation and controlArrows options to true the controlArrows and the navigation bar overlap when slides are used.

As can be seen in your example [http://alvarotrigo.com/fullPage/examples/navigationV.html#secondPage](url), is this the normal/intended behavior ? 

What do you propose to remedy to this problem ?

Thank you in advance :)

**Comment by alvarotrigo** [comment]
Just override the CSS style as you wish.
Trying to fix it will make rather the bullets or the arrows to look very far from the margin.

**Comment by Alpha4** [comment]
Exactly what I was doing but I'm not quite satisfied with out it looks as you mentioned.

For my purpose I think I'll try to have the navigation show up only on first slides of each section.

Thank you !
