### ISSUE TITLE
visual composer not works properly

### ISSUE THREAD

**Issue by ehsanpro2** [alvarotrigo/fullPage.js#1939]
Hi
it seems this plugin have a conflict when we use visual composer plugin .
visual composer element's settings works in section page but doesn't work in fullpage.
This is my section page with all setting execution :
http://kambizfood.ir/fullpage-section/section-2/

and this is the FullPage :
http://kambizfood.ir/fullpage/homepage/

you can see that any settings could not be loaded.
what should I do with this problem?
Thanks

**Comment by alvarotrigo** [comment]
Not a fullpage.js problem a a visual composer one.

**Comment by ehsanpro2** [comment]
Hi 
Thanks for your response ,my section page has  all settings and effects of VC such as parallax imagae ,but it not work when switch to fullpage .
Did you see my above links ?

regards

**Comment by alvarotrigo** [comment]
If you believe it is a fullpage.js bug, please reproduce it in an isolated environment without any external CSS or JS.
