### ISSUE TITLE
Making touch scroll work on Windows Phone 8

### ISSUE THREAD

**Issue by philrees** [alvarotrigo/fullPage.js#194]
I have been able to make touch scrolling work in IE on my Windows Phone 8 phone.

I added this to the css:

``` CSS
  #superContainer {
    -ms-touch-action: none;
 }
```

In jquery.fullPage.js, I replaced lines 340 341 with:

``` javascript
                    if (event.type=='MSPointerMove'){
                        touchEndY = e.pageY;
                        touchEndX = e.pageX;
                    }
                    else {
                        touchEndY = e.touches[0].pageY;
                        touchEndX = e.touches[0].pageX;
                    }
```

and, similarly, I replaced lines 398 399 with:

``` javascript
                    if (event.type=='MSPointerDown'){
                        touchStartY = e.pageY;
                        touchStartX = e.pageX;

                    }
                    else {
                        touchStartY = e.touches[0].pageY;
                        touchStartX = e.touches[0].pageX;
                    }
```

**Comment by karogab** [comment]
do you know something about eschool.am

**Comment by karogab** [comment]
Why don't you answer

**Comment by karogab** [comment]
answer pls

**Comment by alvarotrigo** [comment]
@karogab please create a new issue if you think there's a bug in fullPage.js or if you have any questions regarding its usage.

This issue is from 2014 and makes no sense to continue the conversation here. 
The 2014 version is far outdated and has very little in common with the current one.

**Comment by karogab** [comment]
I did not notice that it was in 2014, but I found this link in the code of this site and by clicking on it I found this site

**Comment by karogab** [comment]
We can continue the conversation on Twitter or Instagram

**Comment by karogab** [comment]
Please respond

**Comment by alvarotrigo** [comment]
No, I'm not related. 
They use a third-party component that is fullPage.js. That's all.

**Comment by karogab** [comment]
this code is not yours

**Comment by alvarotrigo** [comment]
@karogab if you need any support for the fullPage.js implementation consider getting a Business license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>.

**Comment by karogab** [comment]
They bought this code from you

**Comment by karogab** [comment]
they pay you
