### ISSUE TITLE
Scroll position for auto-height sections

### ISSUE THREAD

**Issue by Dolampochki** [alvarotrigo/fullPage.js#1940]
Hi
I have an auto-height section in the middle of a webpage (not footer). By scrolling down this section appears on a bottom of the screen and by scrolling up it appears on the top of the screen. Where can I set this section to appear always on top?

<img width="1098" alt="screen shot 2016-04-03 at 4 29 47 pm" src="https://cloud.githubusercontent.com/assets/18244980/14232643/567a71b4-f9b9-11e5-8bc8-91c31d64a275.png">

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1854
There's no way to do it now.
