### ISSUE TITLE
Scroll through sections with custom scrollbar

### ISSUE THREAD

**Issue by vanelizarov** [alvarotrigo/fullPage.js#1941]
I have implemented div, which is some kind of vertical scrollbar. Can I scroll through sections using my custom scrollbar like I'm doing it with "scrollBar" option enabled?
My custom sliders is a combination of two divs: container, and a smaller div inside of it, which can be moved with "omousemove" event. When it scrolls, it returns an offset value. And I was thinking, how can I pass this offset value to fullpage's scrollHandler or similar function.

**Comment by alvarotrigo** [comment]
> Can I scroll through sections using my custom scrollbar like I'm doing it with "scrollBar" option enabled?

fullpage.js doesn't provide a way to do it, you'll have to implement it by yourself.
