### ISSUE TITLE
Prevent scroll on fullPage when scroling into a child fixed element

### ISSUE THREAD

**Issue by aidared** [alvarotrigo/fullPage.js#1942]
How can I prevent fullPage to scroll when the user scrolls into an internal scrollable div.
Current behavior is when the user scrolls into the child fixed div, the scroll is applied on the full page as well.

Thankful in advance!

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements` provided in fullpage.js. Read more about it in the docs.

**Comment by carlosnpz** [comment]
Same problem here, but it's happening only on Apple devices (Safari or Chrome). I noticed, as well, that even if divs are listed in "normalScrollElements", this bug occurs.
