### ISSUE TITLE
Scroll Up won't scroll to the top

### ISSUE THREAD

**Issue by Macxim** [alvarotrigo/fullPage.js#1943]
[Here](https://github.com/alvarotrigo/fullPage.js/issues/1894) you said:
> I would recommend you to deal with padding by yourself by using CSS. Just create a container in the section and use the padding you want for it. 

When I add some padding to, let's say, the first section, and then I scroll down to another section, and then I scroll back up, it won't scroll to the top. Some pixels are always scraped out I get `transform: translate3d(0px, -105px, 0px);`

I will try to provide a fiddle as soon as possible.

**Comment by alvarotrigo** [comment]
Waiting for the reproduction.

**Comment by Macxim** [comment]
The issue is here http://alphanetworks.be/testimonials/testimonial-of-victor, especially on smaller resolutions (for example 1366 x 768).
As you can see, it's not possible to scroll back to the top.

Any idea what might cause this? I tried to reproduce it in a fiddle but no luck so far.

**Comment by alvarotrigo** [comment]
As i said, I'll wait for the isolated reproduction in jsfiddle or codepen. With no external CSS or JS.

**Comment by Macxim** [comment]
What about this ? http://jsfiddle.net/v3eksoxg/1/

**Comment by alvarotrigo** [comment]
You are not even using the `padding` class anywhere in your HTML http://jsfiddle.net/v3eksoxg/3/
Seems the problem is that you are using an image that is making the section bigger than the viewport. 

Not a fullpage.js bug. Use a background image instead or find other approach.

**Comment by Macxim** [comment]
Alright, thanks for taking the time to look into it.
