### ISSUE TITLE
Deactivating scrolling when lightbox is active

### ISSUE THREAD

**Issue by JensNielsen81** [alvarotrigo/fullPage.js#1944]
Hi, First off, thanks for a great script :)

I have, maybe a little strange, question.
Is it posible to deactivate the scrolling, when a Lightbox is active/open(something like fancybox or Lightcase)?

I have content in these lightboxes that is scrollable, but when you get to the end or top, when scrolling, the slide in the background changes.

**Comment by alvarotrigo** [comment]
From the docs:

```javascript
//disabling scrolling
$.fn.fullpage.setAllowScrolling(false);
```
