### ISSUE TITLE
Do not set height on divs, but still animate between them.

### ISSUE THREAD

**Issue by zubairalam** [alvarotrigo/fullPage.js#1945]
I have 4 continuous divs whose height varies from one another (do not treat them as same height slides, on a viewport 2 or more slides may appear vertically).
Also vertical scroll animation must be done between first 2 divs only, so if we go from div2 to div3, we scroll normally and by fullpage.js animation.
Will appreciate for some guidance.

**Comment by alvarotrigo** [comment]
Use the auto heigh sections as in [this example](http://alvarotrigo.com/fullPage/examples/autoHeight.html).
More info about how to create smaller sections [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections).
