### ISSUE TITLE
Need to Load a section completely to move to the other sections?

### ISSUE THREAD

**Issue by fdsbrian** [alvarotrigo/fullPage.js#1946]
Hi Alvaro,

Thanks for sharing this plugin. nice work!

I have a question about scrolling delay. I have 5 sections and all these sections have simple fly-in animations. I do not want the user to go to the next slide without completing the animation of the current slide that he is in.

Something like this site - https://la24.org/ 

Any solution? Thanks.

**Comment by alvarotrigo** [comment]
Check out the documentation regarding [how to cancel the movement before it takes place](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place)

Add your logic there.

**Comment by fdsbrian** [comment]
Thanks a ton! that was quick too..
