### ISSUE TITLE
Confused about scrollOverflow?????

### ISSUE THREAD

**Issue by SamBaqai94** [alvarotrigo/fullPage.js#1947]
Hi there 
it say this about scrollOverflow on main page
"scrollOverflow: (default false) defines whether or not to create a scroll for the section in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor plugin"
does this mean we should do this like this:
$("#fullpage").fullpage*({

afterLoad:function(){
scrollOverflow:true;
}
};
any help

**Comment by alvarotrigo** [comment]
Mmm no, why?
Look at [the available example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrolling.html).
