### ISSUE TITLE
scrollOverflow and responsiveWidth generate double Scrollbar on small devices

### ISSUE THREAD

**Issue by Tibicenas** [alvarotrigo/fullPage.js#1948]
Hi
- I have sections and sections with slides
- Some sections and slides has large content, so i need scroll in that sections.
- But i also need disable automatic scroll on small resolutions (want normal navigation)

```javascript
$('#fullpage').fullpage({
      anchors: [
        'section1',
        'section2XL',
        'section3',
        'sectionWithSlidesXL',
        'section'
      ],
      scrollOverflow: true,
      responsiveWidth: 740
    });
```
 [in your example](http://alvarotrigo.com/fullPage/examples/scrolling.html#secondPage/2) you have `scrollOverflow: true`  but if i add the responsiveWidth: 740, i get  doubleScrolling in the XL sections & slides when go to smallDevices

**Comment by alvarotrigo** [comment]
Duplicated : https://github.com/alvarotrigo/fullPage.js/issues/958
