### ISSUE TITLE
Vertically align <div> and <span>

### ISSUE THREAD

**Issue by akerbabber** [alvarotrigo/fullPage.js#1952]
I can't align this text to the logo in a header. Here is the code:

`.logo {
  width: 100%;
  height: 130%;
}
.header {
  /*display: table;*/
  height: 15%;
  overflow: hidden;
}
.menu_link {
  position: relative;
  height: 100%;
  background: tomato;
  display: inline-block;
  vertical-align: middle;
  text-align: center;
}`

`<div class="header">

  <span class="col-3 menu_link">
    <img class="logo" src="http://lorempixel.com/image_output/technics-q-c-300-120-4.jpg"  />
  </span>

  <span class="menu_link col-2">
    How it works
  </span>
  
</div>`

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue.
You should ask for those questions in other places such as stackoverflow.com

**Comment by akerbabber** [comment]
`

<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Yenetics</title>
    <link rel="stylesheet" type="text/css" href="jquery.fullPage.css" />
    <link rel="stylesheet" type="text/css" href="style.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    
    <script src="vendors/jquery.easings.min.js"></script>


    
    <script type="text/javascript" src="vendors/jquery.slimscroll.min.js"></script>

    <script type="text/javascript" src="jquery.fullPage.js"></script>

</head>
<body>
<script>
$(document).ready(function() {
$('#fullpage').fullpage({
//Navigation
menu: '#menu',
lockAnchors: false,
anchors:['firstPage', 'secondPage'],
navigation: true,
navigationPosition: 'right',
navigationTooltips: ['firstSlide', 'secondSlide'],
showActiveTooltip: false,
slidesNavigation: true,
slidesNavPosition: 'bottom',

//Scrolling
css3: true,
scrollingSpeed: 700,
autoScrolling: true,
fitToSection: true,
fitToSectionDelay: 1000,
scrollBar: false,
easing: 'easeInOutCubic',
easingcss3: 'ease',
loopBottom: false,
loopTop: false,
loopHorizontal: true,
continuousVertical: false,
normalScrollElements: '#element1, .element2',
scrollOverflow: false,
touchSensitivity: 15,
normalScrollElementTouchThreshold: 5,

//Accessibility
keyboardScrolling: true,
animateAnchor: true,
recordHistory: true,

//Design
controlArrows: true,
verticalCentered: true,
resize : false,
sectionsColor : ['#ccc', '#fff'],
paddingTop: '0px',
paddingBottom: '0px',
fixedElements: '#header, .footer',
responsiveWidth: 0,
responsiveHeight: 0,

//Custom selectors
sectionSelector: '.section',
slideSelector: '.slide',

//events
onLeave: function(index, nextIndex, direction){},
afterLoad: function(anchorLink, index){},
afterRender: function(){},
afterResize: function(){},
afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){},
onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex){}
});
});
</script>

<div class="header">

    <span class="col-3 menu_link">
<img class="logo" src="img/Logo_Yenetics-01.png"  />
    </span>

    <span class="menu_link col-2">
How it works
    </span>

    <span class="menu_link blogNews">

    </span>

    <span class="menu_link about">

    </span>

    <span class="menu_link contact">

    </span>
            <span class="social">

                <span class="icons">

                </span>
                <span class="search">

                </span>
            </span>


</div>


<div id="fullpage">

    <div class="section">
        <div class="slide jumbotron">
            <span>
        <h1 id="jubotron-title"></h1>
        </span>
            <span><h3 id="jumbotron-content"></h3></span>
            <spam>immagine donna incinta</spam>
        </div>

        <div class="slide"></div>
        <div class="chat-btn"></div>
    </div>
    <div class="section">
        <div class="title-pag2"></div>
        <div class="content-pag2">
            <span>blood sample</span>
            <span>analysis</span>
            <span>report</span>
        </div>

        <div class="chat-btn"></div>
    </div>

    <div class="section">
        <div class="titolo-pag3">

        </div>
        <div class="content-pag3">
            <div class="desc-pag3"></div>
            <div class="btns-pag3">
                <span>blog</span>
                <span>brochure</span>
                <span>seguici</span>
            </div>
        </div>

        <div class="chat-btn"></div>
    </div>
    <div class="section">
        <div class="title-pag4"></div>
        <div class="aboutUs">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </div>
        <div class="desc-pag4"></div>
        <div class="chat-btn"></div>
    </div>
    <div class="section">
        <div class="title-pag5">

        </div>
        <div class="form-pag5"></div>
    </div>
    <div class="chat-btn"></div>
    <div class="footer">
        <span class="logo"></span>
        <span class="social-btns"></span>
    </div>
</div>


</body>
</html>
`

**Comment by alvarotrigo** [comment]
Good luck then!
