### ISSUE TITLE
add mousewheel direction as fourth parameter  on onLeave function

### ISSUE THREAD

**Issue by shynome** [alvarotrigo/fullPage.js#1953]
My English is not good, please more inclusion.
In some cases, I need the direction of mousewheel to decide how to toggle section.So,I add mousewheel direction as fourth parameter  on onLeave function.
I add `//wheel_change` after I had changed
[jquery.fullPage.txt](https://github.com/alvarotrigo/fullPage.js/files/207554/jquery.fullPage.txt)

**Comment by alvarotrigo** [comment]
Thanks for it, but I won't I do not see the point on it having the `direction` parameter.
