### ISSUE TITLE
Vertical scrolling to also scroll horizontal sections?

### ISSUE THREAD

**Issue by locksoft** [alvarotrigo/fullPage.js#1954]
This is not a bug, just an enhancement suggestion (hoping there's not already there and I've missed it).

It would be nice to have an option to activate a sort of "continue scrolling". Normally, with mouse wheel, the pages scroll vertically, but it would be nice to have the same gesture to scroll horizontal slides as well, and then keep scrolling vertically when you reach the last slide.

See this example: three pages, the second with 3 slides:
1
2.1 2.2 2.3
3

You just keep scrolling the mousewheel down and you'll go thru this sequence:

1 2.1 2.2 2.3 3

Is it that possible? :)

**Comment by locksoft** [comment]
Hmmm... thinking more carefully it doesn't seems a good idea to force users to follow a fixed path.
It would be better to have an horizontal mouse gesture to scroll horizontally inside slides.
It works on touch devices (of course) and with keyboar arrows, but it seems not working on my mouse (magic mouse + Safari). I'm forced to use arrows on the screen or the dots to navigate slides.
Is it normal or a bug?

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1134

**Comment by alvarotrigo** [comment]
This is now possible using the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).
