### ISSUE TITLE
afterRender + moveTo => Uncaught ReferenceError: requestAnimFrame is not defined

### ISSUE THREAD

**Issue by ligne13** [alvarotrigo/fullPage.js#1955]
Hi,  
I need to call $.fn.fullpage.moveTo in the afterRender event callback but I get the following error in the console :

Uncaught ReferenceError: requestAnimFrame is not defined

thanks

**Comment by alvarotrigo** [comment]
Please add a reproduction in jsfiddle or codepen as detailed in [the reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by ligne13** [comment]
Sure, here it is : http://codepen.io/ligne13/pen/BKJrww

look at the console : 

Uncaught ReferenceError: requestAnimFrame is not defined

the errors occurs because of this :

afterRender:function() {
    $.fn.fullpage.moveTo(2);
  }

thanks

**Comment by alvarotrigo** [comment]
The issue won't get solved, as on the dev version fullpage.js got rid of the function `requestAnimFrame`.

You can use [the development version 2.7.9](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js). You would have to minify it by yourself as that hasn't been done on the dev branch.

In any case, I believe you won't get the result you expect from the call. I guess you want to show the animation from the default section to the one in `moveTo` right?
Right now it won't show any.

**Comment by ligne13** [comment]
OK thanks.
