### ISSUE TITLE
Option to normal scroll in only one axis

### ISSUE THREAD

**Issue by dhoepelman** [alvarotrigo/fullPage.js#1956]
Hi!

For our use case we have a section with slides, and we have some normal scroll elements in some of the slides which take up most of the screen. ([example](http://www.codestar.nl/#team/galleryA))

This works as expected for vertical scrolling, but also disables horizontal scrolling. On desktop browsers this is acceptable (keyboards and arrow navigation still works), but prevent swiping on mobile unless you start the swipe from outside of the normal scroll element. This is a problem if the normal scroll element takes up most of the screen.

It would be awesome if you independently could enable normal scrolling on the x or y axis.

**Comment by alvarotrigo** [comment]
fullpage.js provides the option `scrollOverflow:true` for those cases in which the content is bigger than the viewport.

**Comment by dhoepelman** [comment]
Ah that seems perfect, but I missed it. Thanks!
