### ISSUE TITLE
scroll intensitivity trackpad

### ISSUE THREAD

**Issue by JanaVanMaele** [alvarotrigo/fullPage.js#1960]
First of all, thank you for sharing your plugin.

I use the plugin with following option:
'scrollingSpeed: 0'

I encountered the problem with the way too fast scrolling animation of the trackpad.

For my case, i added the following to the plugin.
defined var scrollIntensitivity in at the beginning of the plugin
var scrollIntensitivity = options.scrollingSpeed;

In 'MouseWheelHandler' function
//define scroll intensitivity using trackpad (e.wheelDeltaY == 'very low number' )
scrollIntensitivity = typeof e.wheelDeltaY !== 'undefined' && e.wheelDeltaY > -10 && e.wheelDeltaY < 10 ? 300 : originals.scrollingSpeed;

in 'performMovement' function
do the setTimeout without the check 'if(options.scrollingSpeed){'

**Comment by alvarotrigo** [comment]
Reported already here: https://github.com/alvarotrigo/fullPage.js/issues/1654
