### ISSUE TITLE
scroll down but move slides

### ISSUE THREAD

**Issue by harshagopalkrishna** [alvarotrigo/fullPage.js#1962]
Hi Alvarotrigo,

Huge fan of fullpage.js. I was working on project where i have only one section and around 7 Slides. Basically Client asked me to convert vertical site to horizontal. Everything is working fine. I need to know how can make vertical scroll to change slides. Instead of changing section here it should change slides.
Any solution would apprciate.

Link which am working on.

http://www.analyticideation.com/projects/mag/horizontal/

**Comment by alvarotrigo** [comment]
Not possible I'm afraid. Not the way fullpage.js works. 
You can try using some kind of parallax library for that.

**Comment by alvarotrigo** [comment]
If by `make vertical scroll` you mean using the mouse wheel for that. fullpage.js doesn't provide a way to do it but it is possible. 
[Read this open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/316)
