### ISSUE TITLE
Scrolling on Mobile

### ISSUE THREAD

**Issue by sogen1us** [alvarotrigo/fullPage.js#1963]
Hi all,

I just recently launched my site using fullpage.js. However when I navigate the site using a mobile device, the scroll isn't fluid. It actually take about 4-6 scrolls to get to the top or bottom. Is there a way we can have a smoother scroll?

You can check out the site here: [www.sogenius.io](www.sogenius.io)

You help is much appreciated...

**Comment by alvarotrigo** [comment]
I guess you are speaking about the section with `scrollOverflow:true`.
Duplicated issue: https://github.com/alvarotrigo/fullPage.js/issues/506

**Comment by alvarotrigo** [comment]
> Is there a way we can have a smoother scroll?

You can try implementing iScroll.js as suggested [in this topic](https://github.com/alvarotrigo/fullPage.js/pull/1543). But right now fullpage.js doesn't provide with any built in function to substitute the vendor slimScroll.js

**Comment by sogen1us** [comment]
Awesome. I'll remove it from the site and see what happens.

**Comment by sogen1us** [comment]
Hey @alvarotrigo just tried to implement that iscrollHandler... and now I cannot scroll at all. It scrolls o the next section everytime. Is there something I'm missing?

**Comment by alvarotrigo** [comment]
@sogen1us probably, but I'm afraid I only provide support for the public version.
