### ISSUE TITLE
window.getComputedStyle() returns null inside an iframe with display: none in Firefox(version 45.0.1)

### ISSUE THREAD

**Issue by ly2015** [alvarotrigo/fullPage.js#1964]
The position of this problem: Line **2334** in file _jquery.fullPage.js_

**Comment by alvarotrigo** [comment]
Can you be more specific with your issue? What is the problem it generates for the end user?
Where is your iframe? Are you loading fullpage.js inside it? Why?

**Comment by ly2015** [comment]
Yes, you are right.
The iframe I have put inside my web page is not full screen. And, I load the fullpage.js inside the iframe.
Value of the _"display"_ property of the iframe is _"none"_ when the page is loading.
I want to show the iframe after the web page has been loaded.

However, when the page is loaded, the problem appeared：

**1. there is no animation any more
2. the "#fp-nav" does not appear**

**Comment by alvarotrigo** [comment]
fullpage.js won't suppor that case.

**Comment by alvarotrigo** [comment]
It is a firefox bug: 
https://bugzilla.mozilla.org/show_bug.cgi?id=548397
https://bugzilla.mozilla.org/show_bug.cgi?id=795520

**Comment by ly2015** [comment]
I get  it. Thanks.
