### ISSUE TITLE
Remove first section after entering second section

### ISSUE THREAD

**Issue by WitchcraftBerlin** [alvarotrigo/fullPage.js#1965]
Hello,
First of all, I absolutely love your plugin. Thanks for the great work.
Maybe you can help me with an customization issue. I would like to know, if there is an opportunity to remove the first section after entering the second section?
Greetings, Katharina

**Comment by alvarotrigo** [comment]
No. Why would you do that? 
Just prevent the scrolling back to the 1st section by using `setAllowScrolling(false)` inside the `afterLoad` callback.

Read the documentation about [how to use callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) and the method `setAllowScrolling`.

**Comment by WitchcraftBerlin** [comment]
That was exactly what I was looking for. Thank you so much.
