### ISSUE TITLE
Weird scroll behaviour even with $.fn.fullpage.setAutoScrolling(false);

### ISSUE THREAD

**Issue by Macxim** [alvarotrigo/fullPage.js#1966]
Hi Álvaro,

In my code, I set $.fn.fullpage.setAutoScrolling(); to `false` if there is a specific class on the page.
When I start scrolling and I stop, the page scrolls on its own and repositionate the scroll bar to the top or the bottom of the slide. I want the scroll bar to stay still.

How can I prevent this?

See http://jsfiddle.net/xeao0s0r/

**Comment by alvarotrigo** [comment]
`fitTosection:false`. Read more about it in the docs.
