### ISSUE TITLE
The anchor link to the middle of the section when I have a lot of content

### ISSUE THREAD

**Issue by 5ch1ll1ng** [alvarotrigo/fullPage.js#1967]
If I have more content and it exceed the section, My section will be displayed at the middle when I click on the anchor.
How can I do to link the anchor to the top of the section?

Thank you very much, best,

Pierre

**Comment by alvarotrigo** [comment]
Duplicated of: https://github.com/alvarotrigo/fullPage.js/issues/1854

**Comment by 5ch1ll1ng** [comment]
Oh thank you, thank you very much, I hadn't seen this and it worked perfectly!
By the way, your plugin is fantastic.

Best,
Pierre
