### ISSUE TITLE
Responsive width containers on mobile

### ISSUE THREAD

**Issue by pfried** [alvarotrigo/fullPage.js#1969]
Hi Alvaro,

i am currently trying to get fullpage working on mobile devices, therefore i used the `responsiveWidth` property and hoped that it will solve my problem.

But actually it does some strange things depending on the browser.

I have some containers which are not fitting the viewpoint on mobile. If the `responsiveWidth` property is set the containers are all set to the same size (altough they would need different sizes as there is a different amount of content in them) causing them to overlap, which is a mess. Scroll down to see the first container behind the next ones overlapping.

On firefox you can see it instantly on chrome i had to resize the browser window to see it.

[CodePen](http://codepen.io/anon/pen/dMewzY)

Another thing i noticed: If i put an element in the first container with a margin (e.g. `<h1>`) the whole fullpage container gets an offset. In the codepen try setting the border to 0 as the border alters the behaviour. No idea why acutally

**Comment by alvarotrigo** [comment]
Check [this topic](https://github.com/alvarotrigo/fullPage.js/issues/1852).
