### ISSUE TITLE
Normal Scroll remove auto scrolling

### ISSUE THREAD

**Issue by ajmaurya99** [alvarotrigo/fullPage.js#1971]
I want  a normal scrolling on my website. The only problem is when i scroll between the sections and leave the mouse it auto slides and adjust to fit the screen section. I dont want that,
Refrence Link - http://dilsedigital.com/beta/#sj-video-playlist

**Comment by alvarotrigo** [comment]
Use `  fitToSection: false`. Read more about it in the docs.
