### ISSUE TITLE
responsiveWidth: 768 has no affect

### ISSUE THREAD

**Issue by rocko2** [alvarotrigo/fullPage.js#1972]
I assume if set responsiveWidth: 768, it will scroll normally when width is equal or less than 768px, but it doesn't, it remains autoscroll, fit to section,...

I have version fullPage 2.6.2.

If i want to scroll normally i have to change:
scrollOverflow: false,
autoScrolling: false,
fitToSection: false

But this drives me to problem, because site in desktop mode,... we would like to autoscroll, fit to section ,..etc

Do we miss something or is something not working like it should.

Rok

**Comment by alvarotrigo** [comment]
Only the latest version provides support. Use 2.7.9

**Comment by rocko2** [comment]
Upgraded to 2.7.9.

It is the same, responsiveWidth: 768 has no affect.

**Comment by alvarotrigo** [comment]
Working as expected in [the demo page](http://alvarotrigo.com/fullPage/examples/responsive.html)

Provide an isolated reproduction if you believe its a bug.

**Comment by rocko2** [comment]
Oh, i had jquery.fullPage.min.js included which was still 2.6.2., now i have 2.7.9. and it works, sorry.

Only one thing is, i can see in your demo,... on page refresh it nicely jumps to slide provided in url hash ..#secondPage, ... my page doesn't jump... it always starts at beginning. For example if someone copies url with particular slide in anchor and sends it with email to someone, one who clicks on link always lands on first slide, not on one which is provided through url hash.

This is our site: http://www.chagall-rovinj.com/

**Comment by alvarotrigo** [comment]
> Only one thing is, i can see in your demo,... on page refresh it nicely jumps to slide provided in url hash ..#secondPage, ... my page doesn't jump... it always starts at beginning.

Sounds like you are doing something wrong. Take a look at the example which is available here in github in the `examples` folder.
If you believe its a bug please provide an isolated reproduction without any external CSS and JS.

**Comment by rocko2** [comment]
Uh trying for an hour now and,.. Ok thank you very much anyway.
