### ISSUE TITLE
how fixedElements supposed to work?

### ISSUE THREAD

**Issue by sk29110** [alvarotrigo/fullPage.js#1974]
I am not sure how fixedElements supposed to work? I have set up my site here but it doesn't do anything.
I was hoping to have footer display when going to about page

http://a47.fb7.myftpupload.com/

**Comment by alvarotrigo** [comment]
You don't really need to use it anymore as long as you place your fixed elements outside the plugin's wrapper and use position:fixed in their css properties.

**Comment by dideriksn** [comment]
Hi Alvaro, but is there a way to get the Fullpage container to subtract fixedElements from it's rendered height, and essentially have a 'top: header-height'? 
Otherwise fullpage section's content is hidden behind fixed elements...

**Comment by alvarotrigo** [comment]
@dideriksn that has nothing to do with the title of this topic, but yeah, you can use the option `paddingTop` or just create your own wrapper around your section or slide content and add a margin or padding to it in your css stylesheet.

**Comment by dideriksn** [comment]
Sorry, I kind of thought it did because it would give meaning to the option FixedElements :) 

Giving a section padding-top will not keep background images from being cut. Moving the image into a container within the section - creates a white area (the top-padding), visible during a scroll.

**Comment by alvarotrigo** [comment]
> Giving a section padding-top will not keep background images from being cut.

Then just use the `background-position` property

**Comment by dideriksn** [comment]
Ah yes, but what I meant was, that part of the background image gets hidden/cropped behind a fixed header for example.

**Comment by alvarotrigo** [comment]
I repeat again:

Then just use the `background-position` property.

**Comment by dideriksn** [comment]
hmm.. maybe we're not speaking about the same thing.

I've made a fiddle!
https://fiddle.jshell.net/kemtmm9a/11/

Cat in section - partly hidden behind header.
Cat in section three - not hidden, but also not aligned to top creating a green space visible on scroll. 

How can I use a background-position to have a full viewable image, but without creating a padding space?

**Comment by alvarotrigo** [comment]
As expected, I don't see your `background-position` css property anywhere.

**Comment by alvarotrigo** [comment]
You'd better ask in stackoverflow.com for CSS knowledge questions. This is not the place for it.

**Comment by dideriksn** [comment]
This really doesn't have anything to do with the background-position property. The background-position defines how an image is placed within a container. I would like the fullpage container to stop at the header bottom instead of the header top/browser top - so content doesn't get cropped. That's what my fiddle shows - sections in full height, but cropped by a fixed header. 

But lets close the conversation here - we're clearly not agreeing on the issue :)
Fyi, I've used your plugin numerous times, and I will continue to do so. This issue just comes up everytime, and I thought I'ld ask this time...

Thankyou for your time.

**Comment by alvarotrigo** [comment]
> so content doesn't get cropped

Your content is not being chopped as you can see [here](https://fiddle.jshell.net/kemtmm9a/12/). Just the background. As you are using `paddingTop`.
Thus, changing the background solution would solve all your problems.

> sections in full height, but cropped by a fixed header.

Section is full height ,but has a padding top, therefore content won' get chopped.

> This issue just comes up everytime, and I thought I'ld ask this time...

I hope that solves your issue :)
