### ISSUE TITLE
Navigation dots + Scrollbar

### ISSUE THREAD

**Issue by johannes69** [alvarotrigo/fullPage.js#1975]
Hi how can I have a navigation dots with a scroll bar? When I put in scrollbar: true, it distorts the whole page

**Comment by alvarotrigo** [comment]
It shouldn't. See [this example online](http://jsfiddle.net/97tbk/1206/).
You are doing something wrong. If you believe it is a bug, please reproduce it in jsfiddle or codepen. Meanwhile, I'll close the issue.
