### ISSUE TITLE
Make spacebar scrolling bar optional on HTML5 videos

### ISSUE THREAD

**Issue by appsforartists** [alvarotrigo/fullPage.js#1977]
Would you be open to a PR to make fullPage's spacebar control optional and/or adds the video element to the list of elements that it ignores?  Right now, it breaks play/pause with the spacebar on sites that both include fullPage.js and use HTML videos.

**Comment by alvarotrigo** [comment]
What about just ignoring the space bar if the video is on focus? Like what happens with youtube ?

**Comment by appsforartists** [comment]
That's what I meant with the second half of my question.  😃

**Comment by alvarotrigo** [comment]
I'll mark it as an enhancement. 
Meanwhile, you might want to disable the keyboard actions with `setKeyboardScrolling(false)` whenever the video gets focused.

**Comment by alvarotrigo** [comment]
Fixed on 3.0.6!
Now when a video/audio is focused the spacebar won't cause scroll.

**Comment by alvarotrigo** [comment]
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️
