### ISSUE TITLE
Is it possible to grow section out of view port area?

### ISSUE THREAD

**Issue by sk29110** [alvarotrigo/fullPage.js#1978]
I was wondering if it's possible to have section grows out side of view port? 
If you have the page with blog items it might get really long and the scrollbar within the section is not easy to use( you can jump to another section easily )

**Comment by alvarotrigo** [comment]
You have 4 options:

- [`overflowScroll:true`](http://alvarotrigo.com/fullPage/examples/scrolling.html)
- [`fp-auto-height`](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections) with `autoScrolling:false`
- Use the beta feature `hybrid:true` as detailed [in this answer](http://stackoverflow.com/a/36618771/1081396). (notice the feature won't get support at this state yet)
- Do not use fullpage.js. Sometimes it makes no sense with large content.
