### ISSUE TITLE
Responsive reBuild

### ISSUE THREAD

**Issue by kayaz** [alvarotrigo/fullPage.js#1979]
This is my code:
```
	function initialization(){
		$("#main").fullpage({
			lockAnchors: false,
			anchors: ["page"],
			loopHorizontal: false,
			easing: "easeInOutCubic",
			easingcss3: 'ease',
			menu: "#mymenu",
			animateAnchor: false,
			afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
				$("#mymenu li").removeClass('active');
				$("li[data-menuanchor=" + slideAnchor + "]").addClass("active");
			}
		});
	}
	
	$(document).ready(function(){
		initialization();
	
		var windowW = $(window).width();
		var windowH = $(window).height();
		if(windowW < 1367) {
			$.fn.fullpage.destroy('all');
			$('.home').css({"height": windowH});

			$(function() {
				$('#mymenu li').bind('click', function(event) {
					var anchor = $(this).attr('data-menuanchor');
					console.log(anchor);
					
					$('html, body').stop().animate({
						scrollTop: $('div[data-anchor=' + anchor + ']').offset().top
					}, 1500, 'easeInOutExpo');
					event.preventDefault();
				});
			});
		}
	});
```

Below 1366px i change site view to one-page scroll down, but when i want back to fullPage

```
	$( window ).resize(function() {
		var windowW = $(window).width();
		var windowH = $(window).height();
		$.fn.fullpage.destroy('all');
		
		if(windowW < 1367) {
			$('.home').css({"height": windowH});

			$(function() {
				$('#mymenu li').bind('click', function(event) {
					var anchor = $(this).attr('data-menuanchor');
					console.log(anchor);
					
					$('html, body').stop().animate({
						scrollTop: $('div[data-anchor=' + anchor + ']').offset().top
					}, 1500, 'easeInOutExpo');
					event.preventDefault();
				});
			});
		} else {
			initialization();
			$.fn.fullpage.reBuild();
		}
	});
```
fullPage is not working.

1. How to check if fullPage is already initiated?
2. Try make like in Owl Carousel script: responsive with breakpoint key like this:

```
responsive : {
    // breakpoint from 0 up
    0 : {
        option1 : value,
        option2 : value,
    },
    // breakpoint from 480 up
    480 : {
        option1 : value,
        option2 : value,
    },
    // breakpoint from 768 up
    768 : {
        option1 : value,
        option2 : value,
    }
}
```

**Comment by alvarotrigo** [comment]
> How to check if fullPage is already initiated?

Check for the [state class](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) `fp-enabled` added by fullpage.js in the `html` element.

Regarding the responsive problem you have, I'm afraid I do not understand it and in any case, it doesn't sound like a fullpage.js bug but just a very specific use case. I would encourage you to ask in http://stackoverflow.com/ instead.

**Comment by kayaz** [comment]
It is not bug but just question: how to disable fullPage after resize below some width and enable back after resize to up some width.

**Comment by alvarotrigo** [comment]
Maybe you do not need to destroy it. Have you taken a look at the `responsiveWidth` and `responsiveHeight` options?

And if you need to, just listen to the resize event and use `$.fn.fullpage.destroy`. Then initialize it again when necessary.

**Comment by kayaz** [comment]
using `$.fn.fullpage.destroy` and initialize it again its working but menu links dont work. Keyboard navigation working good but not menu.

**Comment by alvarotrigo** [comment]
Then you are doing something wrong :)

**Comment by DaveCanucot** [comment]
Awesome plug-in fullpage.js. I have some question sir.
I am trying to add a new options when the screen width is equal or below to 768px. isn't possible to add?

**Comment by alvarotrigo** [comment]
> I am trying to add a new options when the screen width is equal or below to 768px. isn't possible to add?

Ask in a new issue please. And tell exactly which option.
