### ISSUE TITLE
How to overwrite generated height in section ?

### ISSUE THREAD

**Issue by samarthpathak3** [alvarotrigo/fullPage.js#1980]
Hello I want to use gmap with fullpage.js but as its basic functionality is vertical align middle. I want to overwrite its generated height or there is any other way to use gmap with fullpage.js. I am using bootstrap and the section devided in 2 half 6 columns. one column for map and another column for form. I want to cover half column with map. Has anyone got the same issue.

Thanks,
Samarth

**Comment by alvarotrigo** [comment]
I have no idea what gmap is and I'm don't really know what issue you are having. 

Provide a reproduction of the issue if you want to make things easier. 

In any case, you can always overwrite the height using `fp-auto-height` as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections) or by using css with the `!important` tag on it.

Oh,and fulpage.js doesn't deal with columns, it seems yours is more a CSS issue than a fullpage.js one. You'd better ask in http://stackoverflow.com/ for those things.
