### ISSUE TITLE
lazy loading images don't load when deep linking to below the fold

### ISSUE THREAD

**Issue by pirco** [alvarotrigo/fullPage.js#1983]
changed "src" attribute to "data-src" on images placed (way) below the fold. 
lazy loading as expected when you start at the top and scroll down.
but when deeplinked to the bottom section, the images don't load until you start scrolling 1px

(temporary deep link: http://dev.marinersinncambria.com/#Lifestyle )

**Comment by alvarotrigo** [comment]
> (temporary deep link: http://dev.marinersinncambria.com/#Lifestyle )

Which section are you talking about? 

Steps to reproduce the problem required.

**Comment by pirco** [comment]
sorry, the link was VERY temporary... 
I re-enabled it and now the issue can be recreated by clicking the link.

http://dev.marinersinncambria.com/#Lifestyle

note: the div.section with lazyloading images is currently the last. when moved up one or two sections the images load as expected. tested on mac safari 9.0.3, chrome 49.0.2623, FF 45.0.2

**Comment by alvarotrigo** [comment]
It will be solved with in a future version of fullpage.js once a better lazy loader is implemented. 
One that will also lazy load adjacent sections and slides.

**Comment by alvarotrigo** [comment]
I'll close the issue as we are treating that new lazy loading enhancement [here](https://github.com/alvarotrigo/fullPage.js/issues/1973).
