### ISSUE TITLE
Safari Mobile showing browser scrollbars?

### ISSUE THREAD

**Issue by partTimeCrazy** [alvarotrigo/fullPage.js#1986]
I'm using an iphone 6 plus and when viewing your demo site I can tap and drag on the screen and it shows the browser's vertical scrollbar instead of the next slide as the content is too big. Essentially the page goes behind the address bar and the tabs so the height of the content is actually more than what you can see. Is there a solution for this as i'ts happening on my site as well.

Cheers!

**Comment by alvarotrigo** [comment]
> your demo site

You mean here? http://alvarotrigo.com/fullPage/
Which brower are you using? I can not reproduce your issue on iPhone 6 with iOS 9 on browserstack.


Try to provide a way to reproduce your problem or a video showing the problem on the fullpage.js demo site.

**Comment by partTimeCrazy** [comment]
yeah that page. i've worked out that if you tap and drag on the "fork me on github" image you get the browser scrollbars. might have something to do with the position of the image? is there any way to make fullscreen the correct size i.e. not including the area behind the address bar and tabs?

**Comment by alvarotrigo** [comment]
> i've worked out that if you tap and drag on the "fork me on github" image you get the browser scrollbars.

Yeah, not a problem of fullpage.js itself then. Nothing we can do about it.

> is there any way to make fullscreen the correct size

I guess you are talking when using the phone in landscape mode. 
That depends on the OS and the browser you are using. If you use Chrome, for example, you won't see that happening. And nop, there's no proper solution for it right now.

I would suggest you to use the `responsive` options in those cases to avoid problems.
