### ISSUE TITLE
Horizontal Scroll With Trigger

### ISSUE THREAD

**Issue by handydannu** [alvarotrigo/fullPage.js#1987]
How to make horizontal scroll with navigation trigger ? I also want to change slide-bullet with text

**Comment by alvarotrigo** [comment]
> How to make horizontal scroll with navigation trigger ?

I do not understand very well what you mean by that, but you probably want to use the fullpage.js methos such as `moveTo` for that.

> I also want to change slide-bullet with text

Read this: http://stackoverflow.com/a/36852660/1081396
