### ISSUE TITLE
Fixed Elements

### ISSUE THREAD

**Issue by rahisarm** [alvarotrigo/fullPage.js#1988]
Hi.Im really happy to use your plugin.I have some divs.I want to place these divs above the sections.And it have to be fixed.Just like the slide arrow controls.They have to be remain fixed even if slide changed or not.Any help will be appreciated.

**Comment by alvarotrigo** [comment]
Just use CSS to fix then and place them outside the plugin's wrapper. Just as the menu is in any of the [provided examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples). 

If you still don't know how to do it, you'd better ask in http://stackoverflow.com/ as yours is a CSS knowledge question and not a fullpage.js one.

**Comment by cloudsoh** [comment]
Hello @alvarotrigo, may I know what is the fixedElements options for? Can you give me an example code? I have to wrap the fixed elements inside the Fullpage's plugin, because they don't always appear and they appear at certain section. (I use it in the scrolloverflow section).  
Thanks.

**Comment by alvarotrigo** [comment]
Sure:

> **fixedElements:** (default null) Defines which elements will be taken off the scrolling structure of the plugin which is necessary when using the css3 option to keep them fixed. It requires a string with the jQuery selectors for those elements. (For example: fixedElements: '#element1, .element2')

**Comment by alvarotrigo** [comment]
You can not use fixed elements within elements using `translade3d` transformations. If they didn't change it Chrome won't deal with them properly and they won't get fixed. You need to place them outside the plugin's structure.

**Comment by garcia559** [comment]
Good afternoon friend, excellent work with this plugin. I have a question, I'm using fixedElements to position a form on the side of the view, but in responsive I need to remove this property and I do not know how to do it. I hope you can help me, thank you very much.

**Comment by alvarotrigo** [comment]
@garcia559 the only single thing `fixedElements` does is place the element outside the fullpage.js wrapper. 

Just move it inside whenever you need by using Javscript or jQuery.
