### ISSUE TITLE
responsiveWidth not working with js minified version

### ISSUE THREAD

**Issue by silviaaimone** [alvarotrigo/fullPage.js#1989]
When using the last version of jquery.fullPage.min.js, the responsive behaviour is triggered on iPad portrait even though the responsiveWidth option is set to 768.
The problem is not present if using the non-minified version of the script.
Tested on Chrome and Safari, iPad Air 1.

**Comment by alvarotrigo** [comment]
It doesn't seem to make much sense. Both versions should work in the same way>
A prove of it is the [responsive demo page](http://alvarotrigo.com/fullPage/examples/responsive.html) which is working as expected and it is using the minified version.

Please provide a reproduction of the issue so we can test what you say.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
