### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by webdrifter** [alvarotrigo/fullPage.js#1990]
Thank you for a great plugin. I have some comments:

1) Fixed header and footer can have different heights in different breakpoints.
Maybe it would be possible to set responsive queries along with padding bottom and padding top in js - had to use !important in CSS.

2) It would be really helpful to have a possibility to set offset? I mean it would be very user friendly in mobile phones to scroll in next slide little bit. Like in http://projects.lukehaas.me/scrollify/

3) Scrolling inside sections: http://alvarotrigo.com/fullPage/examples/scrolling.html. 
I have slides that are containing lot of content. I had to use scrollOverflow: true.
How is resposniveHeight (resposniveHeight:500 for example) supposed to work with 
scrollOverflow: true? Some pages contain lot of content and because there was not a way to enable 
displaying a bit of next slide in I figured why not to use responsiveHeight, but it seems using it together with scrollOverflow:true is not going to work.

Best regards,
Kristjan

**Comment by alvarotrigo** [comment]
1) That's a matter of CSS, nothing to do with fullpage.js

2) Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1627

3) Not working well together. See https://github.com/alvarotrigo/fullPage.js/issues/958
A real responsive site shouldn't be using those tricks. I always recommend to use bigger sections as detailed in [this post](https://github.com/alvarotrigo/fullPage.js/issues/1852). 
Which will be even easier with [the new feature introduced in the dev branch](https://github.com/alvarotrigo/fullPage.js/pull/1968).
