### ISSUE TITLE
Responsive not working!

### ISSUE THREAD

**Issue by AmeliePoulain92** [alvarotrigo/fullPage.js#1991]
i have this 

 $('#wrapper').fullpage({
        menu: '.fullpage-menu',
        anchors: ['firstSection', 'secondSection', 'thirdSection', 'fourthSection', 'fifthSection', 'sixSection'],
        loopTop: true,
        loopBottom: true,
        autoScrolling:false,
        responsiveWidth: 1200,
        easingcss3: 'cubic-bezier(0.175, 0.885, 0.320, 1.275)'
    });

and responsive is still not working!

**Comment by alvarotrigo** [comment]
[The demo](http://alvarotrigo.com/fullPage/examples/responsive.html) is working as expected. 

Provide an isolated reproduction in jsfiddle or codepen as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

I'll close the issue until then.
