### ISSUE TITLE
IE independently loads "jquery.fullpage.min.js.map" and fails (404)

### ISSUE THREAD

**Issue by Jekyll4k** [alvarotrigo/fullPage.js#1992]
Do I need to include the file for IE? I thought its for debugging reasons.
Can be seen on Demo site when inspecting "network" tab in IE Edge dev tools.

**Comment by alvarotrigo** [comment]
You dont need to. Just for debugging.

**Comment by alvarotrigo** [comment]
You have 3 options:

- Remove the line `//# sourceMappingURL=jquery.fullpage.min.js.map`in the minified file.
- Upload the map file so it won't fail
- Just do not open the console, it won't load and threfore fail at all. 

See http://stackoverflow.com/questions/18499930/missing-map-resource

**Comment by Jekyll4k** [comment]
Thank you. Will put more effort in investigation before stealing your time again :)
