### ISSUE TITLE
Autoheight not working in responsive footer

### ISSUE THREAD

**Issue by Ravenna** [alvarotrigo/fullPage.js#1994]
I am sharing the url of this site for reference to my issue.  I am using 2.7.9

http://crp.ravennainteractive.com/

I have a footer which is shorter than the rest of the 100vh sections.  height: auto !important; is being applied due to adding fp-auto-height.

when I scroll to the footer on a desktop, it won't allow me to scroll to the full bottom of the page, there is 20px of margin on the bottom to pull the copyright info off the very bottom.

Also in responsive it won't let me reach the bottom.

I have tried resetting and doing this as many ways as I can think of but still can't fix.  Any ideas on either what I am doing wrong or how we could improve your script?

thanjks

**Comment by Ravenna** [comment]
Ok as an update I was able to partially solve this issue.  On all devices except mobile phones.  The issue on all other screen sizes was that I hadn't cleared a float that was making the height not calculated right.

Now the issue is that on mobile the footer is taller than full screen due to stacking.  But I can't scroll up/down since the plugin hijacks the scroll.  

What can be done for a responsive stacking footer that is taller than full height.

**Comment by alvarotrigo** [comment]
> What can be done for a responsive stacking footer that is taller than full height.

Use the responsiveWidth or responsiveHeight options. Otherwise you should go for scrollOverflow, but I wouldn't recommend it until the next release of fullpage.js. (and because it is not really a good responsive technique anyways)
