### ISSUE TITLE
setAllowScrolling(false) not disabling scroll for mousewheel or double finger on touchpad

### ISSUE THREAD

**Issue by Ravenna** [alvarotrigo/fullPage.js#1995]
Using 2.7.9 setAllowScrolling(false) is not disabling scroll.  

I have a fullscreen nav that comes up when you click an icon.  I added the 		$.fn.fullpage.setAllowScrolling(false);

to the click handler and the site still scrolls underneath. 

the: $.fn.fullpage.setAllowScrolling(false); also returns undefined in the chrome inspector console, but that may be user error.

**Comment by Ravenna** [comment]
@alvarotrigo Why Invalid?

**Comment by Ravenna** [comment]
I also tried: $.fn.fullpage.reBuild(); after a destroy and that wouldn't work either.

http://codepen.io/anon/pen/EKGxLa

**Comment by alvarotrigo** [comment]
> Why Invalid?

You close it yourself.

**Comment by alvarotrigo** [comment]
Regarding your 1st problem, you would have to reproduce it in jsfiddle or codepen, as the available [demo online](http://alvarotrigo.com/fullPage/examples/methods.html) as well as [the one in codepen](http://codepen.io/alvarotrigo/pen/EjeNdq) provided in the documentation works as expected. 

> I also tried: $.fn.fullpage.reBuild(); after a destroy and that wouldn't work either.

Rebuild doesn't do what you expect. Read the docs: 

> Updates the DOM structure to fit the new window size or its contents. Ideal to use in combination with AJAX calls or external changes in the DOM structure of the site.

You will have to initialize fullpage.js again after destroying it. Rebuild is only used to deal with scrollOverflow and update the sections and slides dimensiones.

**Comment by Ravenna** [comment]
I appreciate your responses. I will see what I can do about the $.fn.fullpage.setAllowScrolling(false);
