### ISSUE TITLE
JS image resize compatible with fullPage.js

### ISSUE THREAD

**Issue by babybackart** [alvarotrigo/fullPage.js#1996]
I am trying to integrate this code : http://codepen.io/babybackart/pen/GZPjJd on a section of a website using fullpage.js.
The aim is to "contain" the image on its container ".plancheBox" without cuting it.
In this example, the cat picture's dimensions are driven by the container using this first javascript code: 

```
var calculateImageDimension = function() {

  $('.plancheBox img').each(function() {

    var $img = $(this),
      $plancheBox = $img.closest('.plancheBox');

    $img.css({
      'max-height': $plancheBox.height() + 2,
      /* (+2px) prevent thin margins due to rendering */
      'max-width': $plancheBox.width()
    });

    $img.closest('.container').css({
      'position': 'relative'
    });

  });
}

calculateImageDimension();
```

In order to set these dimensions instantaneously (without a page refresh), I am using this second javascript code: 

```
var resizeEnd;
$(window).on('resize', function() {
  clearTimeout(resizeEnd);
  resizeEnd = setTimeout(function() {
    $(window).trigger('resize-end');
  }, 200);
});

$(window).on('resize-end', function() {

  $('.plancheBox img').css({
    'max-height': 'none',
    'max-width': 'none'
  })
  $('.plancheBox .container').css({
    'position': ''
  });

  calculateImageDimension();
});

```

As you can see in the first example, it works without fullpage.js.

I managed to insert the first JS code in a fullpage.js website : http://codepen.io/babybackart/pen/ONrbEN but I don't really manage to insert the second one. 

I'm not actually a JS coder so I wanted to know what I needed to do to insert this code, if it was possible to do this with fullpage.js and if there were any conflict between both codes. 

Thank you for your answer !

**Comment by alvarotrigo** [comment]
Not a direct fullpage.js issue. Please ask in other place such as http://stackoverflow.com/

Notice fullpage.js provide a resize callback. Maybe you want to use it instead.

**Comment by babybackart** [comment]
Ok alvarotrigo, sorry for the mistake, Thank you again for your code, it's really helpful !
