### ISSUE TITLE
Enable scrolling on full screen lightbox div

### ISSUE THREAD

**Issue by Christonit** [alvarotrigo/fullPage.js#1997]
Hi there!

Right now I've been trying to 'on click' AJAXy load some content on top of my section containers(the ones defined for the plugin) like a lightbox. The content is loaded and has overflow but the scroll aint working for the new content but it works for the section below. Any idea on how pull this off?
`
`
			`$('#fullpage').fullpage({`
				
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage', '5thPage'],
				menu: '#menu',
				scrollingSpeed: 1200,
				overflowScroll:true,
                touchSensitivity: 1,
                normalScrollElementTouchThreshold: 5,
        normalScrollElements:['#section4','.project-contenedor'],
				css3:false,

  
				afterLoad: function(anchorLink, index){
					if(index == 1){
              /*  slidesNavigation: true*/
              		  $('#landingInfo').removeClass(" hidden fadeOut").addClass('animateTitle fadeInTitle ');
            
       				 }
            		if(index == 2){
              /*  slidesNavigation: true*/
              		  $('#section2').removeClass(" hidden fadeOut").addClass('animated fadeInRight ');
            
       				 }

       				 if(index == 3){
              /*  slidesNavigation: true*/
              		  $('#section3').removeClass(" hidden fadeOut").addClass('animated fadeInRight ');
            
       				 }
       				 if(index == 4){
              /*  slidesNavigation: true*/
              		  $('#section4').removeClass(" hidden fadeOut").addClass('animated fadeInRight ');
            
       				 }

       				 if(index == 5){
              /*  slidesNavigation: true*/
              		  $('#contact-animatable').removeClass(" hidden fadeOut").addClass('animated fadeInRight ');
            
       				 }

    		},onLeave: function(index, nextIndex, direction){
             if(index == 1){
            	
                $('#landingInfo').addClass('fadeOut');
    
            }

            if(index == 2){
            	
                $('#section2').addClass('hidden fadeOut');

            }

            if(index == 3){
            	
                $('#section3').addClass('hidden fadeOut');

            }
            if(index == 4){
            	
                $('#section4').addClass('hidden fadeOut');

            }
            if(index == 5){
            	
                $('#contact-animatable').addClass('hidden fadeOut');

            }

        },afterRender: function(){
             $(".project").click(function(){
              var projectLink = $(this).attr('data-project');

                   $(".portfolio").load("content/" + projectLink + ".html",function(){

                          /*$(".project-container").show();*/
                        TweenMax.to(".project-container",0.4,{zIndex:9998,x:0,y:0,opacity:1});

                             $(".project-btn").click(function(){
                               // TweenMax.to(".project-contenedor",0.3,{zIndex:-1,yPercent:100,opacity:0});
                                 $(".project-container").remove();     
                                  $(".portfolio").load("content/portfolio.html");   
                            });
                              
                     return false;

                    });

                  /*    });*/

               /* $(".project-container").show(function(){
                });*/

               
            });

        }
			});

		});

`

As you can see, I've tried the afterRender and the  'normalScrollElements' method but it aint working.

I made my website on top of your plugin but I've been trying this new stuff for an UX community project.

I apologize in advance, I am new to Javascript/jQuery.

**Comment by alvarotrigo** [comment]
If `normalScrollElements` doesn't work for you or some reasonm, you can always use `setAllowScrolling` and turn it off and on whenever you want.

In your case just turn it of when opening the popup and on when closing it.

**Comment by alvarotrigo** [comment]
Btw, you can not use `normalScollElements` for a whole section like you are doing with `'#section4'`
