### ISSUE TITLE
Anchor for sections

### ISSUE THREAD

**Issue by levipadre** [alvarotrigo/fullPage.js#1998]
Hi,

Can I specify the name of the anchors for the sections?

**Comment by alvarotrigo** [comment]
I dont see why not. Read the [docs](https://github.com/alvarotrigo/fullPage.js).

**Comment by levipadre** [comment]
Sorry, slides!

**Comment by alvarotrigo** [comment]
Yeah. Again, read the docs. It is detailed in there.

**Comment by levipadre** [comment]
Thanks Álvaro!
