### ISSUE TITLE
Is there a way to invert vertical and horizontal scrolling

### ISSUE THREAD

**Issue by lmeyer** [alvarotrigo/fullPage.js#200]
Hello, 

This plugin is awesome and works great.
I was wondering if it was possible to invert vertical and horizontal scrolling.

Sections would have the slides behaviour.
Slides would scroll vertically.

Look at the image to understand my poor explanation.

If there is a solution, i would be happy to know it.

Cheers

![example](https://f.cloud.github.com/assets/572469/2029319/dc32c086-88e1-11e3-9687-eddf4ac08e14.png)

**Comment by siddharth251189** [comment]
Hi,

I want make an one page  horizontal scrolling website. is fullpage.js helpfull and if yes than how please advise me.


Thanks

**Comment by gsvavarsson** [comment]
@jppag did you get this to work? Do you have an example?

**Comment by alvarotrigo** [comment]
This is now possible using the [Interlocked Slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html) of fullpage.js.

The behaviour can be now emulated by using it combined with `setAllowScrolling` and `setKeyboardScrolling` in order to disable horizontal scrolling for any other level of slides rather than the first one.

**Comment by noiwid** [comment]
Hi Alvaro,
I would like to do exactly how it's explain by Imeyer upper. I'm ready to buy the Interlocked Slides Extension but I can't see any working demo that show me it can works as expected:
- Sections would have the slides behaviour (left to right)
- Slides would scroll vertically (they will react as one-page...)

Do you have a live demo that showcase the plugin in this way ?
Thanks a lot for your feedback.

Benoit

**Comment by alvarotrigo** [comment]
> Do you have a live demo that showcase the plugin in this way ?

No sorry. Won't provide such example as that's a very specific task for the extension. 
You do not need to code it to see that it is in fact possible. Just suppose the slides moves accordingly and figure out what calls to `setAllowScrolling` and `setKeyboardScrolling` you'll need to do.

I can tell you it works. I've coded such behavior with the extension previously. But of course, you need some JavaScript knowledge from your side to use the callbacks and call the appropriate methods. If you want me to code it for you [contact me](http://alvarotrigo.com/#contact-page) and I'l provide you with a quote for it.

**Comment by karoomii** [comment]
Hey Alvaro, I'm trying to achieve what the people above are wanting. I know you don't have a showcase for the plugin in this way, but do you happen to have the lines of code for it?

**Comment by alvarotrigo** [comment]
@karlcarstensen no, but as I said, this is possible using the interlocked slides extension and using callbacks to enable or disable the scrolling to certain sides.

**Comment by Charly1701** [comment]
Hello Alvaro, 

Thanks for your cool plugin and all the explanations. 

I was wondering, if my (hopefully selfexplaining) concept below will be working with your plugin too?

![konzept](https://user-images.githubusercontent.com/30038513/28007569-38bec5be-6554-11e7-9c73-204a33093eb4.jpg)

It is very important, that 
a) the start page is the middle one and
b) if you scroll to left or right/change slider, you will get back to the top sections.

If there is a solution, I would be very happy to know it.

Cheers

**Comment by alvarotrigo** [comment]
@Charly1701 many things are possible with the right knowledge of Javascript and making use of the fullPage.js functions. I haven't tried your scenario before, but take  a look at the docs and you might be able to get something working.

**Comment by wi-holzem** [comment]
has anybody already done to change the orientation that section slides horizontal and slides vertical?

[Section1] ► [Section2] ► [Section3]
      ▼                ▼                  ▼
[Slide 1.2] ► [Slide 2.2] ► [Slide 3.2]
      ▼                ▼                  ▼
[Slide 1.3] ► [Slide 2.3] ► [Slide 3.3]

Cheers

**Comment by alvarotrigo** [comment]
@wi-holzem as I said previously, that structure can be achieved by using the [Interlocked Slides extension](https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html) of fullpage.js.

The behaviour can be now emulated by using it combined with `setAllowScrolling` and `setKeyboardScrolling` in order to disable horizontal scrolling for any other level of slides rather than the first one.

**Comment by wi-holzem** [comment]
i do not get the logic behint it yet.
is to change scrolling directions?
down/up = right/left => down/up changes slide
right/left = down/up => right/left scrolling section

**Comment by alvarotrigo** [comment]
Nah. You can make use of the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html) to scroll horizontally with the moues wheel.

**Comment by wi-holzem** [comment]
okay thats not what i needed
