### ISSUE TITLE
setOptionsFromDOM() not working when sectionSelector has comma-separated selectors

### ISSUE THREAD

**Issue by esoniq** [alvarotrigo/fullPage.js#2001]
Lines 580 and 587 use this code to select elements with data-anchor attribute:

`$(options.sectionSelector + '[data-anchor]')`

In case if there are comma separated values like 'header, section', the resulting selector will be 'header, section[data-anchor]'). In this case elements without data-anchor attribute will be selected and this will cause an error on lines 581 and 588:

> Cannot read property 'toString' of undefined

**Comment by alvarotrigo** [comment]
I don't see why would you use a comma separated selector.

If you have the following HTML for each section:

```html
<div class="header section" data-anchor="demo"></div>
```

Just use a single selector in fullpage.js selector option:

```javascript
sectionSelector: '.section',
```

**Comment by esoniq** [comment]
Yes, I agree, that it is not very common use case. But that would make more bullet-proof code. Or at least it is worth to mention about it in the docs.

**Comment by alvarotrigo** [comment]
> the resulting selector will be 'header, section[data-anchor]').

The resulting selector would be `header.section`, not comma in between in any case. So it shouldn't be a problem.

**Comment by esoniq** [comment]
Why? 

`options.sectionSelector + '[data-anchor]'`

, where **options.sectionSelector** is _'header, section'_

**Comment by alvarotrigo** [comment]
Nop.

**Comment by alvarotrigo** [comment]
options.sectionSelector should be ` .header.section`

**Comment by esoniq** [comment]
That will select elements, that have both _header_ and _section_ classes. That is not what I was talking about in original post.

**Comment by alvarotrigo** [comment]
> That is not what I was talking about in original post.

Your original post wasn't very explanatory. Please add the HTML markup you are referring to.

**Comment by esoniq** [comment]
Ok. fullPage has and option to put custom section selector called _sectionSelector_. Users might expect to be able to put there any selector unless it is stated otherwise in the docs. If someone has HTML markup like the one bellow:

```
<div class="section-foo">...</div>
<div class="section-foo">...</div>
<div class="section-bar">...</div>
<div class="section-bar">...</div>
<div class="section-foo">...</div>
```
, and wants both classes _section-foo_ and _section-bar_ to be treated by fullPage as sections, his selector will look like:

`.section-foo, .section-bar` (contains comma in it)

_setOptionsFromDOM()_ modifies this selector by adding attribute part '[data-anchor]'. Now we have:

`.section-foo, .section-bar[data-anchor]`

This will get all elements with class _section-foo_ (either with _data-anchor_ attribute or not) and all elements with class _section-bar_ and _data-anchor_ attribute. But the code that follows expects all elements with _data-anchor_ attribute and throws TypeError in this case. The correct selector would be:

`.section-foo[data-anchor], .section-bar[data-anchor]`

**Comment by alvarotrigo** [comment]
I see what you mean. 
But not planning to take any action in the code regarding it. 

Feel free to commit a PR to modify the documentation regarding `sectionSelector` and `slideSelector` options.

**Comment by esoniq** [comment]
Why? Solution is very simple. jQuery provides _.filter()_ method. So, Instead of concatenating selectors:

`$(options.sectionSelector + '[data-anchor]')`

, just use the original and _.filter()_:

`$(options.sectionSelector).filter('[data-anchor]')`

Anyway, its up to you!

**Comment by alvarotrigo** [comment]
> just use the original and .filter():

Sounds good to me. It seems they are only being used in a couple of lines as you said. I though it could have a bigger repercussion. 

Want to create a PR for it?

Also, i suggest using the container to prevent security issues:

```
container.find(options.sectionSelector).filter('[data-anchor]')
```
