### ISSUE TITLE
Reload CSS Animation when scrolling back to the section?

### ISSUE THREAD

**Issue by shuhu3** [alvarotrigo/fullPage.js#2006]
Hello!

Thank you for making this great plugin. I'm using it for my class final and everything worked well so far.

One thing that got me stuck is that after a CSS animation is played on a section, I can't make CSS animations play again when I scroll back from other sections.

By the way, I'm using [animate.css](https://daneden.github.io/animate.css/) to achieve the effects.

```
onLeave: function(index, nextIndex, direction){
$('#element').removeClass('animated slideInLeft');
$('#element').addClass('animated slideOutRight');
afterLoad: function(anchorLink, index){
$('#element').removeClass('animated slideOutRight');
$('#element').addClass('animated slideInLeft');
```

Is there anyway that can make the CSS animation repeat? Thank you.

**Comment by mtbrisc** [comment]
@shuhu3 I also used animate.css with fullPage.js - and wanted to have the animations reset upon revisiting a section.

What I ended up doing to reset the animations was in the afterLoad function - use jQuery **clone** to identically duplicate the objects with the class **animated** and then remove / re-append them ( as detailed in this post: [CSS-Tricks: Restart CSS Animation](https://css-tricks.com/restart-css-animation/)

This achieves the desired animation repeat that you're looking for.

**Comment by alvarotrigo** [comment]
Not a topic for this forum. You'd better ask in http://stackoverflow.com/ as yours is not a fullpage.js issue nor a bug.
