### ISSUE TITLE
full page canvas

### ISSUE THREAD

**Issue by PeterTheobald** [alvarotrigo/fullPage.js#2007]
I am having a hard time putting a full page width and height canvas in a slide.

```
<div id="fullpage">
	<div class="section active" id="section0">
        <div class="slide " id="leftpanel"><canvas id="leftcanvas" style="border:1px solid #000000;"></canvas></div>
	    <div class="slide active"><h1>Center Panel</h1></div>
	    <div class="slide"><h1>Right Panel</h1></div>
    </div>
</div>
```

This canvas occupies a very small area in the center of the page. I tried forcing it in many different ways. Here is my latest unsuccessful attempt:

```
var pagewidth=document.body.clientWidth;
var pageheight=document.body.clientHeight;

var leftdiv=getElementById('leftpanel');
leftdiv.setAttribute("style","width:"+pagewidth);
leftdiv.style.width=pagewidth;
leftdiv.setAttribute("style","height:"+pageheight);
leftdiv.style.height=pageheight;

var canvas = document.getElementById("leftcanvas");
canvas.style.width =pagewidth;
canvas.style.height=pageheight;
// ...then set the internal size to match
canvas.width  = canvas.offsetWidth;
canvas.height = canvas.offsetHeight;
```

I have included the 'example.css' from the examples, but I don't see anything in there that would stop the canvas from being full size. Any tips on making this canvas occupy the entire page?

**Comment by alvarotrigo** [comment]
Not a topic for this forum as yours is not a fullpage.js issue nor a bug. You'd better ask in http://stackoverflow.com/ where they'll be able to help you much better.
