### ISSUE TITLE
fixed width and height if window width smaller than 700

### ISSUE THREAD

**Issue by olouthe** [alvarotrigo/fullPage.js#2009]
Hello, I'm new to developing therefore i apologise if my question is too basic.
Is it possible when you're resizing the window that the page to be fixed at let's say 700x300?
And for windows smaller than that will you be able to view the whole page by navigating
using sidebars?

Thank you in advance :)

**Comment by alvarotrigo** [comment]
> Is it possible when you're resizing the window that the page to be fixed at let's say 700x300?

The plugin doesn't provide any way for that.
