### ISSUE TITLE
In responsive mode bug with scroll after close modal window

### ISSUE THREAD

**Issue by dastiw1** [alvarotrigo/fullPage.js#2010]
if **fp-responsive** class added to the body, when close modal window ( based on magnefic popup )
scrolling with mouse-wheel will not working.
My fullpage.js configuration: 
```javascript
{
sectionSelector: 'section',
        scrollingSpeed: 1000,
        scrollBar: true,
        verticalCentered: false,
        menu: '#menu',
        lockAnchors: false,
        anchors: ['Ceh', 'Kollernaja', 'Oborudovanie', 'Rezultaty', 'Komanda', 'Kontakty', 'Kommenty'],
        fixedElements: 'aside',
        normalScrollElements: 'aside, .modal, #section-6',
        scrollOverflow: false,
        fitToSection: false,
        responsiveWidth: 1023,
        responsiveHeight: 767,
}
```

Site hosted at: [http://demo.ice-tc.kz](url)
*click to the main icon at center to open modal popup

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction without any external CSS or JS in jsfiddle or codepen as detailed in [the reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by dastiw1** [comment]
I found resolution of my question)
Magnefic popup remove **overflow: visible**  style from html tag. 
Need to add  **overflow: visible**  after modal popup closed
