### ISSUE TITLE
Slider scrolling query

### ISSUE THREAD

**Issue by aits-suvash** [alvarotrigo/fullPage.js#2011]
While doing scrolling in slider in any section, after last slide, if it tried to go to first slide it displays all the slide and goes to first one. I mean all the slide from  first to last is displayed. The effect is nice with fewer slide, but with more slides, it is little awkward.

Can we change the effect as the other slide change. I mean changing from last to first only displays the first?

**Comment by alvarotrigo** [comment]
Make sure you use the latest version of fullpage.js 2.7.9 because that's not a default behavior and as you can see won't take place on the [demo page.](http://alvarotrigo.com/fullPage/)
