### ISSUE TITLE
Extra Space at Top On Certain Displays/Browsers

### ISSUE THREAD

**Issue by Efyl** [alvarotrigo/fullPage.js#2012]
(FYI: I'm still fairly new to fullPage). I've noticed cases where extra space is added at the top of each page. It's most noticeable on my first page just because of my design. I do not notice this not on my 1920x1080 Windows 10 laptop but rather on my 1280x1024 (more square) external monitor. I've also noticed it on an iMac. 

On my external display I see it in Chrome Version 50.0.2661.94 m but not in Firefox 46.0.1. I did notice on Chrome, however, if I increase the zoom to 125%, it goes away. If I zoom out in Firefox a fair amount, I get the extra space occurring their as well.

Can anyone help me understand the spacing issues and whether or not there are easy tweaks I can try? Thanks in advance...

**Comment by alvarotrigo** [comment]
Sounds like a problem with your styles or markup.
Not taking place in the [demo page](http://alvarotrigo.com/fullPage/) as far as I can test.

I'll close the issue until an isolated reproduction without external CSS or JS is provided.
