### ISSUE TITLE
BackgroundFixed is not working for ios safari and chrome in ipad and iphone

### ISSUE THREAD

**Issue by samarthpathak3** [alvarotrigo/fullPage.js#2013]
Hello,

I am using fullpage.js in one of my project. It is working completely fine in all the browsers and PCs. It is  only creating issue in Safari and Chrome for iPad and iPhone. I am using the same property written in the example files. The image is getting stretched out.

Here is the link of my project.
http://themes.themecurator.org/aventa1/

Please help me out with this issue.

Thanks,
Samarth

**Comment by alvarotrigo** [comment]
This is not a fullpage.js bug in some browsers with translate3d and fixed elements.
http://stackoverflow.com/questions/23236158/how-to-replicate-background-attachment-fixed-on-ios

**Comment by samarthpathak3** [comment]
But the example you provided is working completely fine. The same thing I have applied in my project.

**Comment by alvarotrigo** [comment]
> But the example you provided is working completely fine. The same thing I have applied in my project.

Then it seems something is definitely different in your project :) 
For example, you are using `scrollBar:true` and the example isn't. 

Try to play "see the differences" until you discover which one is affecting your results.
