### ISSUE TITLE
Getting an error when trying to go to anchor from external link

### ISSUE THREAD

**Issue by JoshCarey** [alvarotrigo/fullPage.js#2015]
Hi there,

I'm just wondering why I'm getting the error:  "Uncaught TypeError: Cannot read property 'top' of undefined".  I have a page (http://www.coffeerepublic.com.au/products/cafina/) that I'm trying to have the "Enquire" link go into the product (post), and scroll down to the #enquire (Enquiry form).  When the Enquire link is clicked on the product list page, it does (sort of) scroll down to the proper anchor tag, but it doesn't have a scroll animation, like its supposed to.  I have a bit of script that will automatically animate the scroll from the top of the page to the anchor when a hashed anchor link is clicked.  I tested it on another page that doesn't have Fullpage.js and I'm not getting an error.  It also had the proper scroll animation.

So I guess my question is, how can I have a scroll animation to get to the #enquire element on the page?  I won't be able to use the "index" or "data-anchor" (at least I don't think?) because the #enquire form isn't always at the same index or section number for every product page.

Anyone have any input?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the problem without any external JS or CSS as detailed in [the reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

I'll close the issue until then as it seems a problem in your side and not really a fullpage.js bug or issue.

**Comment by JoshCarey** [comment]
Maybe I can go about it another way, as to stay specifically within fullpage.js.

How would I be able to use data-anchor to link to section with dynamic sections above the target anchor?

For example on the page () there are a dynamic number of snapping sections above my Enquiry form.  How would I be able to anchor to specifically the "Enquiry" section without having a defined number of data-anchors above, and having those populated in the "anchors" array?

**Comment by alvarotrigo** [comment]
Using anchors in the URL, like in any other site. 
For example: http://alvarotrigo.com/fullPage/#3rdPage

**Comment by JoshCarey** [comment]
Sorry, could you please being a little more specific to how fullpage needs to be setup?

For instance, in the fullpage function, do I need to define any anchors?  Then in my page markup, do I simply add a "data-anchor" to my "enquire" section?  because that's what I have setup at the moment, but there's no scrolling or anchoring happening.

**Comment by alvarotrigo** [comment]
> Sorry, could you please being a little more specific to how fullpage needs to be setup?

Sure, just read this: 
https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides

**Comment by JoshCarey** [comment]
Thanks, but I've already ready through that... what I'm not understanding is:  Ok, so my initialization is as follows:

$('.fullpage').fullpage({
          hybrid: true,
          sectionSelector: '.fullSection',
          verticalCentered: false,
          fitToSection: false,
          responsiveWidth: 769,
          paddingTop: headerHeight,
....

Note, I haven't defined any anchors.  If I do define just the "enquire" anchor,  Along with my html like so:
<div class="enquire-section fullSection fp-normal-scroll fp-auto-height" data-anchor="enquire">

nothing is happening...  there's no scroll or anchoring going on.

**Comment by alvarotrigo** [comment]
Then see [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) folder and see how the [demoPage.html](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/demoPage.html) works, which is the one used in the [main fullpage.js page](http://alvarotrigo.com/fullPage/).

**Comment by JoshCarey** [comment]
Ok, thanks so much for your time and patience with me...  but I don't think you're understanding me properly...  If I did what you're asking, it looks like the "anchors" array needs to actually have all of the sections with a "data-anchor="xxx" defined.  My problem is that there is a dynamic number of sections above, or in front of my "enquire" section..  So I can't setup my "anchors" array like:
anchors: ['section1', 'section2', 'section3', 'enquire', 'sectionXYZ']

right?  Cause a particular page might only have 2 sections before "enquire" or 4 or 5...

**Comment by alvarotrigo** [comment]
> right?

Not really. Just add the attribute `data-anchor` to each of the dynamically generated section. 
If you can create dynamic sections, I do not see why can't you just modify their attributes.

**Comment by JoshCarey** [comment]
Ah... ok, so I've got a loop going, and I've incremented my data-anchor for each one:
data-anchor="productFullSection-<?php echo $dataAnchorIndex; ?>"

and its looping just fine now.  Also the external and internal anchors are working...
Thanks you so much for sticking with me - I greatly appreciate it.

Except now I have one more question that you might be able to help with...  The anchor is going to the proper location... however, this section DOESN'T have the "padding-top" being applied for layout and design purposes...  So the scroll position is actually at the top of the browser window, and not taking into account theIs it possible to somehow scroll to that anchor, but minus a particular amount (for my sticky, floating header)  via callback or another method?

**Comment by alvarotrigo** [comment]
> via callback or another method?

No, but you can always do it all yourself using javascript. 
Detect the anchor in the URL, look for it, and scroll to it. But that's not a fullpage.js question anymore.

**Comment by JoshCarey** [comment]
Ok, I'll keep looking.

I looked through the documentation again, and searched.. but I can't find it...  Is there a way to disable the URL hash changes so that each section doesn't reflect the data-anchor in the URL?  I have the recordHistory: false, set, but the URL is changing... any way to disable that?

**Comment by JoshCarey** [comment]
Thanks again, @alvarotrigo for your help :)

Still wondering if there's a way to disable or hide the URL hash changes...?

I'll just add a summary of my solution...  (and here is the page, if anyone is interested in seeing:  http://www.coffeerepublic.com.au/products/cafina/  -  just click on any of the "Enquire" buttons to see the anchor working)

Basically, I needed to go through the loop of my "product detail" sections that appear above the "Enquiry" form section.  While the loop is going, I needed to add an incrementing "data-anchor" property to each section.  Once that was incrementing and adding a "data-anchor="product-detail-x" to each one, then I could effectively link to the "enquiry" section (data-anchor="enquiry").  There was no need for an array of anchors in the "anchors" property of the fullpage.js function.

So then because of my floating sticky header, (and the fact that fullpage.js wants to scroll so that the bottom of the anchored section hits the bottom of the viewport) - I needed to add a custom function in the "afterLoad" callback:

`var loadedSection = $(this);

if( loadedSection.is('#enquire-section') ) {
  $('html,body').animate({
    scrollTop: $("#enquire-section").offset().top - headerHeight
  }, 600);
}`

The enquire section needed a unique ID different than the (data-anchor="enquiry") on that section in order for me to run a scrollTop on it.
Also, "headerHeight" is obviously a variable that is set higher up - which basically takes a reading on how tall the header is.

I don't know if that will help anyone, but that's what I had to do to get it to work.

**Comment by alvarotrigo** [comment]
> This isn't quite the intention. Is there a setting for this?

No. See https://github.com/alvarotrigo/fullPage.js/issues/1854



> Is there a way to disable the URL hash changes so that each section doesn't reflect the data-anchor in the URL?

Use `lockAnchors` as detailed in the docs.

**Comment by JoshCarey** [comment]
The docs verbiage for `lockAnchors` is a little confusing because the first time I read this:
`You can still using anchors internally for your own functions and callbacks, but they won't have any effect in the scrolling of the site.`
I thought that meant that it wouldn't auto-scroll, but that anchors would still provide some functionality for other functions.

I just tried using `lockAnchors` and it didn't quite work.  The URL's are gone - however if I click the "enquire" anchor link at the top of the page, it doesn't autoscroll to that section. (it does auto scroll when coming from the external page though.)  I might be able to javascript a solution for it to auto scroll on the internal page.

**Comment by alvarotrigo** [comment]
If you want to scroll given an anchor. Then you need anchors in the URL. 
There's no other option.

You have to choose or rather develop the anchor detection yourself and deal with it from your side.
