### ISSUE TITLE
Animation effect

### ISSUE THREAD

**Issue by hassanasad** [alvarotrigo/fullPage.js#2016]
Hi, I wanted to know if i can somehow change the effect of the scroll – perhaps like a roll-over affect instead of scroll effect? If not, can you please give me a few pointers on where i should look to see if its possible for me to make it that way

**Comment by alvarotrigo** [comment]
Not possible I'm afraid.
But feel free to take a look at my other plugin [pagePiling.js](http://alvarotrigo.com/pagePiling)

**Comment by hassanasad** [comment]
Ah - Thanks for pointing me to it - Its almost what i want. Just the animation inverted.
