### ISSUE TITLE
Conflict with Owl Carousel 2

### ISSUE THREAD

**Issue by juanmata09** [alvarotrigo/fullPage.js#2018]
Hi

I've just added Owl Carousel 2 to my site and although it works, when the page slides down to the next page, the owl carousel 2 slider rewinds to slide 1.

i.e. If i slide to slide 7 on owl carousel, when I go to the next page and it slides down, i go back up and it;s back on slide 1, I want it to remain on slide 7.

Any ideas?

**Comment by alvarotrigo** [comment]
Seems like a problem of owl carousel and not of fullpage.js.
You'd better ask in their forum.

If you believe it is a fullpage.js bug, please provide an isolated reproduction of the problem without any external JS or CSS and with the less possible code as detailed in [the reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by juanmata09** [comment]
Hi

Thanks for the reply.

I have created 2 code pens, one with fullpage.js and one without.

with fullpage.js
http://codepen.io/juanmata/pen/PNMGyz

You'll notice when scrolling through the slider i.e to the 7th slide and then scroll down, the slider will go back to slide 1, it should stay on slide 7.

without fullpage.js
http://codepen.io/juanmata/pen/dMxpBy

You'll notice when scrolling through the slider i.e to the 7th slide and then scroll down, the slider will go stay on slide 7, this is how it should work but i want to use fullpage.js.

Thanks for looking.

**Comment by alvarotrigo** [comment]
I would recommend asking in Owl github issues forum. 
Fullpage.js has nothing to do with it. It seems to be a side and a bug or issue of owl.

**Comment by dczerwonski** [comment]
Hey,
owl.carousel.js, v.2.0.0, line 3029:
`// register event listener for hash navigation
$(window).on('hashchange.owl.navigation', $.proxy(function() {
			var hash = window.location.hash.substring(1),
				items = this._core.$stage.children(),
				position = this._hashes[hash] && items.index(this._hashes[hash]) || 0;

			if (!hash) {
				return false;
			}

			this._core.to(position, false, true);
		}, this));`

This is causing this problem. I didn't need hash navigation at all so I've just removed it.

**Comment by alvarotrigo** [comment]
@dczerwonski you could also try using the fullPage.js option `lockAnchors:true`.
