### ISSUE TITLE
Custom URLs / Permalinks

### ISSUE THREAD

**Issue by bdkaat** [alvarotrigo/fullPage.js#2022]
Hello,

I'd like to customize the URLs for both vertical and horizontal navigation.

Instead of anchor links for the sections (example.com/#sectionname) and numbers for horizontal slides (example.com/#sectionname/1), I would like custom permalinks for everything. What I mean is that I want to name the slides whether it's vertical or horizontal navigation so that the permalinks are just custom names without hashtags or numbers. (example.com/sectionname, and example.com/sectionname/differentsectionname)

Any idea how I can achieve this?

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such option I'm afraid.
