### ISSUE TITLE
Getting fullpage.js to play with stellar.js

### ISSUE THREAD

**Issue by fluxxus** [alvarotrigo/fullPage.js#203]
I am trying to add some parallax effect to the fullpage slides. I am using stellar.js, which is very popular and fairly easy script to have some parallax on your site.

I am calling stellar.js inside afterRender function, but the parallax effect is not there. I know that stellar is fired, because if I make some changes to it, they happen. It is just that the parallaxed element stays on the screen, not reacting to the scrolling on the website.

Here is a simple demo, in the third section there is one absolutely positioned black div, which should move a little slower than the user scroll.

http://madebym.me/test/FullPageTest/backgrounds.html

Has anyone managed to make fullpage work with stellar.js, or maybe some other parallax library?

**Comment by 24Degrees** [comment]
Did anyone succeed in using a parallax effect with fullpage.js ?

**Comment by alvarotrigo** [comment]
Did you read my answer just above yours? Use `scrollBar:true` and you'll have no problem.

**Comment by alvarotrigo** [comment]
Now you can make use of the [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to get some parallax effect.
