### ISSUE TITLE
Impossible to scroll down

### ISSUE THREAD

**Issue by KolaCaine** [alvarotrigo/fullPage.js#2030]
Hi everyone,

I have a problem with my project, i use the fullpage for the structure of my website. 

I join a JSFiddle with a part of my code, and if you want more ask me if you dont understand. 

> https://jsfiddle.net/13hjLe0h/1/

So.. I try to explain, in a HTML i create some section with my text inside OK ! 
In my CSS, i have create some id and class for configuration html. 
in result all of this the base is fullpage and inside you have a div, and inside i make some text, and the user if i want read of all the article he can scroll the page, but with the element : normalScrollElement: ["p"]; 

this line block the slide mouse(?! You understand ? not sure ^^), he can only slide with keyboard. 

I search a solution for using the normalScrollElement with mouse also. 

Thanks for helping me

**Comment by alvarotrigo** [comment]
Your fiddle has only one section. I don't see the problem there.
