### ISSUE TITLE
Impossible to scroll down

### ISSUE THREAD

**Issue by KolaCaine** [alvarotrigo/fullPage.js#2031]
Here is a THE NEW fiddle : https://jsfiddle.net/aefun7pu/

How to reproduce the slide with JSFiddle, i paste jquery.fullpage.js ? 

Indeed, in my website i have a page with you script, and the content of the page have make a div. Inside there is some text, but the text was to big, i use overscroll-y: scroll. 

But ! The real problem is when i scroll the page, go to in second slide. I use your option : normalScrollElements: [‘p’] and it’s ok !! Super !! 

But no.. Now it’s block and if i want scroll for go to second slide, its only with keyboard and no with mouse.

**Comment by alvarotrigo** [comment]
Do not open a new topic. Please keep replying in the origional one: https://github.com/alvarotrigo/fullPage.js/issues/2030

And your fiddle still failing. Fullpage.js is not initialized because you are not even importing jQuery.
