### ISSUE TITLE
Manual Lazyload Method

### ISSUE THREAD

**Issue by yeomann** [alvarotrigo/fullPage.js#2033]
For some reason after ajax call, images under gallery were not loaded so, this lead me to ask, how about having manual lazyload method? which could simply replace data-src to src? 
Well, for that particular problem, i figured it out by reading your script source and this worked  for me

```
var deployed = $mainContent.html(data).animate({opacity: "1"});
/* initialize lazy load */
var lazyimg = deployed.find('[data-collection-overlay] img[data-src]');
  lazyimg.each(function() {
  $(this).attr( 'src', $(this).data('src') );
  $(this).removeAttr('data-src');
});
```

But I think, it would be nice to have some something like `lazload()` which could re-read refreshed DOM for data-src and do the magic.

**Comment by alvarotrigo** [comment]
It just doesn't make any sense to use `data-src` in dynamically created elements. 
They are already lazy loaded by its own definition. 

Just use normal `src` for those ajax loaded elements.
