### ISSUE TITLE
Mobile Responsive (Slides aren't centered)

### ISSUE THREAD

**Issue by lkfranklin** [alvarotrigo/fullPage.js#2034]
### Description
Hi,
I have fullpage.js setup correctly and its all functioning fine and when it hits mobile i have it setup to remove the height so that it turns into a normal scrolling section which is fine. However I have slides inside my sections and if you've scrolled down the content of the  first slide and then navigate to the second the content is nowhere to be seen as it's only a small amount of content so, therefore you have to scroll back up. Is there an existing piece of functionality that dynamically calculates the height of each section so that the height attribute can still be set while the page is a scrolling page to ensure that embedded slides are still vertically centered?

Thanks,

**Comment by alvarotrigo** [comment]
You should be using `scrollOverflow:true` for the scrollable slides.

**Comment by lkfranklin** [comment]
Thanks for your reply and by the way this plugin really is great.

I just tried setting to scrollOverflow: true though and it hasn't seemed to fixed the issue. To get a better idea of what I mean feel free to have a look at the site
http://dev.olsen.marketing/knowlge/maneno#secondPage 
If you're prompted for a password then the password is `Knowlge` (Spelt incorrectly)
If you respond down to a tablet/mobile view (yes its messy at the moment) when you switch to slide 2 on the second section you'll see that you then have to scroll back up in order to view the content of that slide. 

My Call looks as follows:
`
// Full Page
	$('#fullpage').fullpage({
		scrollingSpeed: 1000,
		scrollOverflow: true,
		controlArrows: false,
		scrollBar: true,
		autoScrolling: false,
		fitToSection: false,
		verticalCentered: true,	
		responsiveWidth: 1281,

		afterRender: function(){
			new WOW().init();
		}

	});
`

Thanks,

**Comment by alvarotrigo** [comment]
Please reproduce your issue in jsfiddle or codepen. That'd make things easier.

**Comment by alvarotrigo** [comment]
Also, you are not using scrollOverflow as per the errors in your javascript console and neither you are using the latest fullpage.js version (which works with iScroll.js instead of slimScroll.js for overflowScroll)

**Comment by lkfranklin** [comment]
Thanks I think you've pointed me on the right path. I'll have a play around shortly and report back the fix incase anyone else runs into the same problem, but it seems like use error more than likely!
