### ISSUE TITLE
How to know that I'm scrolling?

### ISSUE THREAD

**Issue by mariamargarida** [alvarotrigo/fullPage.js#2036]
Is there a way to know that I'm scrolling?
Example: When I'm scrolling (up or down) something moves in my page.

**Comment by alvarotrigo** [comment]
See [the callbacks documentation](https://github.com/alvarotrigo/fullPage.js#callbacks) and [their examples](http://codepen.io/alvarotrigo/pen/XbPNQv).

Also the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) particulary `fp-viewing-x-y`.
