### ISSUE TITLE
When scrolling to top, getting stuck on second section, happens occasionally

### ISSUE THREAD

**Issue by juanmata09** [alvarotrigo/fullPage.js#2037]
Hi

I am playing about with fullpage.js and while i must say what a great script, i've found an issue which makes it a little unusable.

On mobile devices (IOS) when you scroll down the page and back up, you sometimes get stuck on section 2, I believe it could be the same issue as #1812 & 1814

### Steps to reproduce it
1. Go to www.ukdevelopment.co.uk/test1 on an iOS device using either chrome or safari
2. Scroll down 3 times, scroll up 3 times then repeat,  scroll down 3 times, scroll up 3 times
3. You should be stuck on section 2 which is a slide show, to get to the top you'll need to scroll down then back up again.

### Versions 
2.8.0
IOS Safari & Chrome

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and in the issues skeleton. 

Closed until then.

**Comment by alvarotrigo** [comment]
Just noticed your demo is isolated.

**Comment by alvarotrigo** [comment]
No external JS please.

**Comment by cookies5127** [comment]
sometimes, transform is confused.This is happened only occur css3
