### ISSUE TITLE
Disable section scroll but keep slides

### ISSUE THREAD

**Issue by leamcg** [alvarotrigo/fullPage.js#2040]
Hi!
I have a problem with trying to disable fullpage for mobile. I want to be able to scroll normally on mobile, but to still keep the slider working. I tried removing the class="section" on mobile but it just blocks the scrolling entirely.
Is there a way to just disable the fullpage option, but keep the slider?

**Comment by alvarotrigo** [comment]
Yeah, just use [`setAutoScrolling(false)`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) to remove the autoScroll behaviour for sections. 

Or better yet! Use the responsiveWidth and responsiveHeight options where you can set up a breaking point.

**Comment by leamcg** [comment]
Hi! Thanks for your quick answer! When I add autoScrolling false, there is an horizontal scrollbar on the website, even though you shouldn't be able to scroll horizontally because there is no content on the side. It seems to be caused by the div#fullpage. Any way to fix this?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen without any external JS or CSS.

fullpage.js never creates horizontal scroll bars as you can see in the [autoScrolling:false demo](http://alvarotrigo.com/fullPage/examples/normalScroll.html) or in the [resposive one](http://alvarotrigo.com/fullPage/examples/responsive.html). Both of them available in [the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples). 
`setAutoScrolling` is also available through the [codepen demo](http://codepen.io/alvarotrigo/pen/rVZWrR).
