### ISSUE TITLE
Reduce DOM elements

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2041]
Fullpage is an awesome script. 
The problem with it is that when you have 40 and more sections, the page load may end up being quite slow even when your website is Grade A and you take advantage of the lazy load.

The problem, according to me, is that there should be a way to reduce DOM elements.
Maybe hiding all the sections that are not active and showing them just when you scroll can be an idea?

F.

**Comment by alvarotrigo** [comment]
> The problem with it is that when you have 40 and more sections, the page load may end up being quite slow

That's not a fullpage.js issue but an issue with your very specific scenario. 
You should be using AJAX to load content in that case. You can keep 40 empty sections and you won't suffer from any lag as you can see [here](http://jsfiddle.net/97tbk/1287/).

Using `display:none` won't work. Fullpage.js needs to where where the destination section is.
It seems much easier to solve it from your side.
