### ISSUE TITLE
How can I have each section a full page image?

### ISSUE THREAD

**Issue by greenuns** [alvarotrigo/fullPage.js#2042]
Hello,
I've been trying to have each section a full page image and not a background color.
I'm not having any luck with background:cover on each section.
Only the first section shows me the image and the rest of the sections don't work.
Is there a way to achieve this like in the british airways example?

thank you

**Comment by alvarotrigo** [comment]
See the example backgrounds.html available in [the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

You have it online [here](http://alvarotrigo.com/fullPage/examples/backgrounds.html).

If you still not understand it, you'd better ask in another place such as stackoverflow.com as this is a CSS knowledge question an not a fullpage.js one.

**Comment by greenuns** [comment]
ah I see how it's done.
thank you for the help.
this is a great plug in!


On Mon, May 30, 2016 at 10:36 PM, Álvaro <notifications@github.com> wrote:

> See the example backgrounds.html available in the examples folder
> <https://github.com/alvarotrigo/fullPage.js/tree/master/examples>.
>
> You have it online here
> <http://alvarotrigo.com/fullPage/examples/backgrounds.html>.
>
> If you still not understand it, you'd better ask in another place such as
> stackoverflow.com as this is a CSS knowledge question an not a
> fullpage.js one.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/2042#issuecomment-222494223>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHTz9mZIeDLQPG-52b8TczFjqNXkFtTDks5qGufugaJpZM4IpyU3>
> .
>



-- 
Sent from my desktop!
