### ISSUE TITLE
Chrome display bgimage problem

### ISSUE THREAD

**Issue by DaftDane** [alvarotrigo/fullPage.js#2043]
I added an extra "page" to my website but when i scroll down Chrome doesnt display the bg image for the last page.
It works in FF, IE and Edge.
When i open the Chrome Dev Tool the image is shown, but after i close the dev tool again it vanishes again.
Do you or anyone else have an idea to solve the problem

You can see the test at http://www.daftdne.dk/test/

Yours DaftDane aka Bernd Bachmann

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen with no external CSS or JS.
Closed until then.
