### ISSUE TITLE
Multiple sections assigned to one anchor

### ISSUE THREAD

**Issue by LukSkywookie** [alvarotrigo/fullPage.js#2046]
Hi. Is there simple way to assign many pages to one anchor? 
For now when i'm scrolling there are moments when not even one menu anchor is active.
Thanks :).

**Comment by alvarotrigo** [comment]
> Hi. Is there simple way to assign many pages to one anchor?

Nop. Each anchor should be unique.

**Comment by LukSkywookie** [comment]
Ok, thx.
