### ISSUE TITLE
No slide control 

### ISSUE THREAD

**Issue by KatsanKat** [alvarotrigo/fullPage.js#2049]
Hello Alvaro,

So, i would like to put a slider but not on the entire .section div.
But when i do this : 

```html
<div class="section" id="thirdSection">
            <div class="col-md-12 conviction-container">
                <div class="conviction-content">
                    <div class="num">02</div>
                    <h2>Nos convictions</h2>
                    <div class="slide">
                        <div class="leader-content">
                            <p>Être leader de soi, pour être leader des autres</p>
                        </div>
                    </div>
                    <div class="bouton"><a href="#">En savoir plus</a></div>
                </div>
            </div>
</div>
```

There's no slider controls that appears.
When i check the code, the controls aren't generated, there's no “fp-controlArrow” div as you can see here : [http://hpics.li/8db636d](url)
But it works on my first slider at the header of the page and i don't know why.

If you could help me on this that'd be great :) !

(Tell me if you don't understand my demand, i'm french)

**Comment by alvarotrigo** [comment]
It doesn't seem to be a fullpage.js issue but a very specific problem with your usecase.
If you believe its a bug in fullpage.js please provide an isolated reproduct in jsifiddle or codepen.

I'll close the issue until then.

**Comment by KatsanKat** [comment]
Oh... Dumb issue, i've just put only one .slide div, so there was no reason to have control buttons.
Juts added another .slide div and now it work.

Thanks
