### ISSUE TITLE
onLeave index value incorrect

### ISSUE THREAD

**Issue by highree** [alvarotrigo/fullPage.js#2050]
Hi,

if you have 5 sections and scroll from your first section to the next section with 

"$.fn.fullpage.moveSectionDown();"

or just scroll you will get index number "1"

if you then scroll up (to the) initial section you get index number "2"

am im doing anything wrong? 

`onLeave: function(index, nextIndex, direction){
	            var leavingSection = $(this);
				alert(index)`

### Versions 
OS X latest and latest browsers tested safari, chrome, ff.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen.
[The demo page](http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage) is working as expected.
