### ISSUE TITLE
How to hide Hashtag addition  on address bar on clicking navigation menu links

### ISSUE THREAD

**Issue by vishnu1212** [alvarotrigo/fullPage.js#2053]
How to hide the slide id (ex: website.com/#5thPage) from appearing in address bar on clicking the navigation menu links.

**Comment by alvarotrigo** [comment]
Few options:

- Do not use the `anchors` option or the `data-anchor` attributes [Demo](http://alvarotrigo.com/fullPage/examples/noAnchor.html)
- Use `lockAnchors: true` [Demo](http://alvarotrigo.com/fullPage/examples/methods.html) (just click `setLockAnchors(true)` to test it)

**Comment by vishnu1212** [comment]
Thanks for the reply. But i need to use the menu links for navigation. 
And while clicking on nav links, the Slide ID should'nt  appear on address bar. 
Kindly help if it is something under your control. -Thanks

**Comment by alvarotrigo** [comment]
As I said, use lockAnchors.

**Comment by vishnu1212** [comment]
Sorry, After using _lockAnchors_, the top menu links(first slide, second slide, third slide...) in the methods.html is not working. only the vertical navigation dots are working. Any way to keep those top menu navigation links still usable(but they should not add ID name to address bar)?

**Comment by alvarotrigo** [comment]
> Any way to keep those top menu navigation links still usable

Just create your own menu and attach to it the fullpage.js function `moveTo`.
