### ISSUE TITLE
In safari, mousewheel

### ISSUE THREAD

**Issue by cookies5127** [alvarotrigo/fullPage.js#2054]
### Link to isolated reproduction with no external CSS / JS
[in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Non sense issue body :)

**Comment by justinferrell** [comment]
I'm seeing this issue as well. In Safari on OS X, it will occasionally (seemingly at random) scroll 2-3 sections at once.

**Comment by alvarotrigo** [comment]
@justinferrell probably due to the scroll inertia or your fast scrolling speed. 
Not a big deal in most cases when using the default scrolling speed (700) or the one used in the demo page (1000).
