### ISSUE TITLE
"Pause on Leave" problem with multiple videos hide/show by links

### ISSUE THREAD

**Issue by jodycyh831** [alvarotrigo/fullPage.js#2055]
Hello Alvaro,

Thank you so much for creating this wonderful plugin. 
The problem I have is about the "pause on leave" feature of video.
In one of the sections, I have embedded multiple youtube videos. Each of them is put inside a div that can be hide/show by the links corresponding to each video.

When I play the first video and scroll to the next section, the video stopped as expected. 
But if I play the other video that is shown by clicking its corresponding link, the video didn't stop after scrolling to the next section.

Please check out the codepen [here](http://codepen.io/jodycyh831/pen/ZOYZVO)

And you may try following the steps to reproduce the problem.

1. [click link "vid2" or "vid3]
2. [play the video]
3. [scroll to next section]
4.[p.s. if scroll back up, click vid1 to play, and scroll back down; vid1 wouldn't stop as well]

Appreciate your help :)

**Comment by alvarotrigo** [comment]
Youtube videos can only be paused or played using javascript when they are loaded with the parameter `enablejsapi=1`. 

fullpage.js deals with this by adding automatically the parameter in any youtube iframe src by using the the [function `enableYoutubeAPI`](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L841)

It seems you are somehow modifying the `src` attribute of the videos and you are removing the required `enablejsapi=1` parameter.
