### ISSUE TITLE
ReferenceError: Can't find variable: IScroll

### ISSUE THREAD

**Issue by curricula** [alvarotrigo/fullPage.js#2057]
Im getting a "ReferenceError: Can't find variable: IScroll" in both Safari and Chrome when exiting a fullscreen video. In my case it's an embedded Vimeo video.

Im my case I'm getting a bunch of layout issues happening after this happens but I'm not sure they are related.

### Steps to reproduce it
1. Put any embedded Vimeo video code into a section.

ex. <iframe id="video" src="https://player.vimeo.com/video/104641191?api=1" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

2. Click the fullscreen icon on the player. Then push escape to exit.

### Versions 
Safari 9.1.1, Chrome 50.0.2, fullPage 2.8.0

**Comment by alvarotrigo** [comment]
I guess you are using scrollOverflow:true?

Include the vendor scrolloverflow.js before fullpage.js.
Or use the [dev version](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by curricula** [comment]
Thanks! Problem Solved.
