### ISSUE TITLE
fourth value was skipping while adding the data-menuanchor in fullpage anchor attribute

### ISSUE THREAD

**Issue by uniquesuzan** [alvarotrigo/fullPage.js#2058]
I am trying to apply this js in wordpress dynamically.For that I have fetch the Id of widget in wordpress menu and the menu id was stored in the array for using in the full-page anchor attribute.Whenever I tried to add the widgets in widget area the fourth value of data-anchor was skipped.But the console.log was showing the array value perfectly.
```

jQuery(document).ready(function() {

   			jQuery.noConflict();
		 	jQuery('#nav li').filter(function() {
		    	jQuery(this).attr('data-menuanchor', this.children[0].hash.replace(/#/, ""));
		  	});

		  	var fullpageAnchors = [];
			jQuery('#nav li').each(function(){
				 fullpageAnchors.push(jQuery(this).find('a').attr('href').replace(/\#*/g, ""));
			});

		   	jQuery('#fullpage').fullpage({
		   		anchors:  fullpageAnchors,
				menu: '#nav',
		   	});
		   	console.log(fullpageAnchors);
		});
```

### fullPage 2.8.1
[firefoxe,chrome,ie,safari, windows]

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of the issue in jsfiddle or codepen or otherwise in your own website BUT without any external CSS or JS and with the very basics to just reproduce the problem.

I'll close the issue until then.

**Comment by alvarotrigo** [comment]
Also, do not forget to check the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)
