### ISSUE TITLE
Mobile devices menu active state issue

### ISSUE THREAD

**Issue by LukSkywookie** [alvarotrigo/fullPage.js#2059]
Hi :).

Menu active state work great on desktop devices, but if im trying to achive same effect on mobile I have some issue.
In my case i have 4 menu items and 11 sections. 
I was trying to do something like this:
```javascript
if ( $('.section1').hasClass('active') || $('.section2').hasClass('active') ) {
                        $('.listing-menu li:first').addClass('active');
                    }
```
When section2 is active first menu item is not highlighted.
Do you have any idea how to solve this?
Regards, Luk.

**Comment by alvarotrigo** [comment]
Use the plugin callbacks such as `onLoad` or `onLeave` or even the state class added to the body. 
See [this tutorial](https://www.youtube.com/watch?v=qiCVPpI9l3M).
