### ISSUE TITLE
Can't scroll back to first slide in Safari browser

### ISSUE THREAD

**Issue by SpaceCowboy2071** [alvarotrigo/fullPage.js#2060]
### Description
When using the arrow keys to scroll a FullpageJS site vertically, pressing down several times and then up several times in quick succession, the site refuses to go back to the first section.  This only happens in Safari browser for Mac OSX.  It appears that the URL is updated in the address bar correctly, but the position of the `fullpage-wrapper` isn't correct.

I've provided an example below.  If there's a solution or issue with my code, please let me know!  Thanks!

This is a duplicate of issue #1848 

### Link
http://files.fuelintegrated.com/examples/fullpage/index.html

### Steps to reproduce it
1. Load link in Safari browser.
2. Press down arrow key several times in quick succession.
3. Press up arrow key several times in quick succession.
4. Continued pressing of up arrow key results in no action.

### Versions 
Safari Version 9.1 (11601.5.17.1), Mac OS X El Capitan 10.11.4 (15E65)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction (ideally in jsfiddle or codepen) is provided with no external CSS or JS.
