### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by maitets** [alvarotrigo/fullPage.js#2062]
It has happened when not having menu navigation and trying to go by URL with hashtag, for example, localhost/index.html#1. I reproduce the error in scrolling example putting an id in a <p> tag like this:

```html
<p id="test">Eu nec ferri molestie consequat, vel at alia dolore putant. Labore philosophia ut vix. In vis nostrud interesset appellantur, vis et tation feugiat scripserit. Te nec noster suavitate persecuti. Diceret erroribus cu vix, alii omnes ei sit. Sea an corrumpit patrioque, virtute accumsan nominavi et usu, ex mei dolore vocibus incorrupte.</p>
````
Them I put in my browser http://localhost/scrolling.html#test and the page appear cut on top.

I'm triying to reproduce the error in jsFiddle but it doesn't work (https://jsfiddle.net/pc5he07b/). Could you please check this. Thanks

**Comment by alvarotrigo** [comment]
fullpage.js doesn't support hashtags in the URL which are not part of the anchor tags of fullpage.js.
Not unless you use `scrollOverflow:false`.

**Comment by Herz3h** [comment]
Hello i have this issue, unfortunately i cannot remove the hashtags from the url, since i use a framework which does teh routing, isn't there a workaround ?

**Comment by alvarotrigo** [comment]
Use `lockAnchors:true`.

**Comment by Herz3h** [comment]
It still gives me the error

**Comment by alvarotrigo** [comment]
Sorry can't help you without a reproduction. Make sure you use the latest fullpage.js version 2.8.4.

**Comment by Herz3h** [comment]
Ok i moved the line that initializes the plugin down a few lines, looked like it tried to init the plugin when the page was not fully loaded. Anyway problem fixed, thanks !

**Comment by cjweb2013** [comment]
This directive for angular fullpage.js has solved the problem for me: https://github.com/hellsan631/angular-fullpage.js
