### ISSUE TITLE
Video playing on pageload

### ISSUE THREAD

**Issue by taychau** [alvarotrigo/fullPage.js#2064]
I have an .mp4 video loaded into an html section of my fullpage.js site

As soon as my site is loaded, the video and it's audio immediately begin playing before I reach its section. I have applied the 'data-autoplay' tag to the video source, but its not having any effect. Once I reach the page, the video is halfway through playing, and after I scroll past the page, the video is paused and doesn't respond once I scroll back up to it. 

The only changes I have made to the original video is in the css so that it's borders do not overflow to the sections above and below it. I am really not sure why this is happening.

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
