### ISSUE TITLE
If image is longer than the current screen height, after scroll down and scroll back top again, the image is cropped and only showing the bottom portion. 

### ISSUE THREAD

**Issue by okstmtcc** [alvarotrigo/fullPage.js#2065]
If image is longer than the current screen height, after scroll down and scroll back top again, the image is cropped and only showing the bottom portion. 

This is my setting for the plugin.

`    
    	var total_scroll_slide = $('#products-left .scroll_section').length;

		$('#products-left').fullpage({
			// anchors: ['1', '2', '3'],
			sectionSelector: '.scroll_section',
			navigation: true,
			navigationPosition: 'left',
			// responsiveWidth: 900,

	        onLeave : function(anchorLink, index){
	            var loadedSection = $(this);

	            //last slide
	            if(index == total_scroll_slide){
	                $("#products-right").css('z-index','21');
	                $("body").css('background','#FFFFFF');
	            }else{
	            	$("#products-right").css('z-index','23');
	            	$("body").css('background','#EBEBEB');
	            }
	        }
		});

`

**Comment by okstmtcc** [comment]
May I know how to fix thi sissue?

First load the page:
![1](https://cloud.githubusercontent.com/assets/1691319/15804733/77821692-2b45-11e6-9ff9-0584933ac4be.png)

After sroll down, and scroll back top again:
![2](https://cloud.githubusercontent.com/assets/1691319/15804732/777caa04-2b45-11e6-9a3d-7f8ab258f139.png)

**Comment by alvarotrigo** [comment]
Closed until a reproduction is provided.
