### ISSUE TITLE
Adjust height due to border more quickly

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2066]
I want to add upper border to most of my sections so there is some space while scrolling. I've added a `border-top` of 30px and I've just noticed that this amazing plugin readjusts its height after scrolling is done (which is amazing and exactly what I need actually) - however it takes like 1s or more to do so, any way to speed it up, more or less instantly?

Great plugin and the best of its kind regardless! 

### Versions 
2.8.1

**Comment by alvarotrigo** [comment]
The plugin doesn't provide anyway to do so due to performance reasons. 

But if you still want to do it by modifying the plugin, just change the value in [line 1942 of fullpage.js 2.8.1](https://github.com/alvarotrigo/fullPage.js/blob/2.8.1/jquery.fullPage.js#L1940)
