### ISSUE TITLE
OnSlideLeave, direction down?

### ISSUE THREAD

**Issue by holabadola** [alvarotrigo/fullPage.js#2070]
Hi i'm using OnSlideLeave is it possible to make it work when i'm scrolling down to a new section? I've tried direction == 'down' but it didn't work.

**Comment by alvarotrigo** [comment]
Not sure what you are asking for. 
The callback direction parameter works as expected as you can see in [this demo](http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage). 

Closed until a better explanation or a reproduction is provided.
