### ISSUE TITLE
Disable AutoScroll on mobile devices

### ISSUE THREAD

**Issue by danieledastoli** [alvarotrigo/fullPage.js#2072]
### Description

Hi, i was trying to disable the autoscroll function only for mobile/touch devices (or under a certain resolution) without any results.
The main problem of this amazing plugin is that really often small devices can't fit all the content i've put in a single section, so i'd like to deactivate the autoscroll to make sections longer than the screen height and scroll through them.

Is it possible to do?

**Comment by alvarotrigo** [comment]
Check the `responsiveWidth` and `responsiveHeight` options and [this example](http://alvarotrigo.com/fullPage/examples/responsive.html).

**Comment by danieledastoli** [comment]
Thanks a lot, it was easier than i thought!
Is it possible to do the same with responsivewidth and responsiveheight both? I've just tried but it's not working...

**Comment by alvarotrigo** [comment]
> Is it possible to do the same with responsivewidth and responsiveheight both?

I don't understand your question.

**Comment by danieledastoli** [comment]
something like this:

> $(document).ready(function() {
$('#fullpage').fullpage({
anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage', '5thPage', 'lastPage'],
sectionsColor: ['#fff', '#442f60', '#442f60', '#fff', '#442f60', '#fff'],
responsiveWidth: 768
responsiveHeight: 600
});
});

**Comment by alvarotrigo** [comment]
Of course you can.

**Comment by danieledastoli** [comment]
It's not working actually, it's like if some of the css is missing when i try to add responsiveHeight, the code is exactly the same i've posted above.

**Comment by alvarotrigo** [comment]
> the autoscroll is switched off

That's all it has to do. So it seems to be working as expected.
Anything else will be from your side

**Comment by rijosh** [comment]
How can i disable the full page js on mobile, i don't want the extra sections in mobile (section1 , section2 etc). completely disable the full page js

**Comment by alvarotrigo** [comment]
@rijosh  Read about the responsive options in the docs.

**Comment by sanju9987793650** [comment]
[index.zip](https://github.com/alvarotrigo/fullPage.js/files/1983676/index.zip)
i dont know how to disable fullpage script for this files for mobile view ,which are pretty messed up bt,plz can u tell me the solution asap

**Comment by alvarotrigo** [comment]
@sanju9987793650 use the responsive options detailed in the docs. See the [responsiveWidth.html example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/responsiveWidth.html) provided on the repository.

**Comment by sanju9987793650** [comment]
its not wrking yet

**Comment by sanju9987793650** [comment]
i hv used

<script> if (screen && screen.width > 768) { document.write('<script type="text/javascript" src="js_xd/jquery.fullPage.js"></script>');
}
</script>

<script type="text/javascript"> (function($) { $('#fullpage').fullpage({ anchors: ['firstPage', 'secondPage', 'thirdPage', 'forthPage', 'fifhPage', 'sixthPage'], css3: true, fitToSection: false, autoScrolling: true, scrollOverflow: true, scrollOverflowOptions: { scrollbars: true, mouseWheel: true, hideScrollbars: false, fadeScrollbars: false, disableMouse: true } }); })(jQuery); //END </script>
and in fullpge.js file changes which i made are

/**
* Turns fullPage.js to normal scrolling mode when the viewport width or height
* are smaller than the set limit values.
*/
function setResponsive(active){
var isResponsive = $body.hasClass(RESPONSIVE);

        if(active){
            if(!isResponsive){
                setAutoScrolling(true, 'internal');/*here i made it true instead of false*/
                setFitToSection(false, 'internal');
                $(SECTION_NAV_SEL).hide();
                $body.addClass(RESPONSIVE);
                $.isFunction( options.afterResponsive ) && options.afterResponsive.call( container, active);
            }
        }
        else if(isResponsive){
            setAutoScrolling(originals.autoScrolling, 'internal');
            setFitToSection(originals.autoScrolling, 'internal');
            $(SECTION_NAV_SEL).show();
            $body.removeClass(RESPONSIVE);
            $.isFunction( options.afterResponsive ) && options.afterResponsive.call( container, active);
        }
    }


bt now in small screens it is responsing to touch bt not stoping till it reaches completly at the end of section
can u tell me whr it is wrong asap
