### ISSUE TITLE
Can't reinitialize the plugin after calling destroy() 

### ISSUE THREAD

**Issue by rajjoshi22** [alvarotrigo/fullPage.js#2075]
### Description
I've been using fullPage.js to build out my own personal site for the last couple days and I ran into an issue where disabling the plugin using destroy() made the plugin completely inactive on a given page until the page was reloaded. 

### Link to isolated reproduction with no external CSS / JS
[www.rajjoshi.site/isolated](url)
Above is a live link to a completely isolated reproduction of the issue on my website (I've never shared code on codepen or jsfiddle yet so this was more convenient). It contains no CSS or JS whatsoever except jQuery version 1.8.1 and non-minified fullPage.js version 2.7.9.

### Steps to reproduce this error on your sites
1. Call ".destroy()" on the fullpage plugin container for whatever reason. 

### Versions 
Tested on the latest versions of Chrome and Microsoft Edge.

**Comment by alvarotrigo** [comment]
reBuild is not the same as "initialise".

> Updates the DOM structure to fit the new window size or its contents. Ideal to use in combination with AJAX calls or external changes in the DOM structure of the site.

Just put your initialization inside a function and call it again.
