### ISSUE TITLE
Is there any option to callback when scrolling started

### ISSUE THREAD

**Issue by athimannil** [alvarotrigo/fullPage.js#2077]
I am adding `opacity:0;` when the div has bot classes `.active` and `.fp-completely` 

```
.active{
  opacity:0;
}
.active.fp-completely{
  opacity: 1;
}
```
but unfortunately I am not able to make `opacity:0` when scrolling started. Is there any option to do that ?

**Comment by alvarotrigo** [comment]
> Is there any option to do that ?

Nop. You'll have to use the plugin callbacks or state classes for that.

**Comment by athimannil** [comment]
@alvarotrigo thank you very much for your quick response. Is there any demo for that which to refer ?

**Comment by alvarotrigo** [comment]
You can find demos of how to use the callbacks in the documentation. 
State class tutorial [here](https://www.youtube.com/watch?v=qiCVPpI9l3M).
