### ISSUE TITLE
not scrolling on mobile galaxy s6 android,  chrome browser

### ISSUE THREAD

**Issue by vk011** [alvarotrigo/fullPage.js#2080]
### Description

Hello again.

The plugin does not seem to be scrolling on mobile, Galaxy S6 Chrome browser. On iphone it seems to work fine. I am testing on browsertack so if you have an account and are willing to look at it I can give you the url to it, but maybe it's something in the options - 

```
$('.main').fullpage({
                    scrollingSpeed: 500,
                    scrollOverflow: true,
                    easing: 'easeInOutQuint',
                    css3: false,
                    scrollBar:true,
                    sectionSelector: '.section2',
                    fixedElements: 'header',
                    slidesNavigation: true,
                    navigation: true,
                    navigationPosition: 'right',
                            afterResize: function(){
                                $.fn.fullpage.reBuild();
                            },
                            onLeave: function(current, next) {
                                // $($('.nbhd')[current]).addClass('needborder');
                            },
                            afterLoad: function (anchorLink, index) {
                                //section 2 loaded
                                fullPageSideNav();
                                if (index == 2) {
                                    //adding active class to the 1st element in the slide menu
                                    $('#fp-nav').find('li').eq(0).addClass('active');
                                }
                            },

                            //
                            afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {

                                //only for slides in section 2
                                if (index == 2) {
                                    $('#fp-nav').find('li.active').removeClass('active');
                                    $('#fp-nav').find('li').eq(slideIndex).addClass('active');
                                }
                            }
                });
```

### Versions 
2.8.1

**Comment by alvarotrigo** [comment]
Can't help you without a reproduction.
The most I can say is: make sure to use the latest version of fullpage.js 2.8.1, to use the [vendor scrolloverflow.js](https://github.com/alvarotrigo/fullPage.js/tree/master/vendors) instead of the old slimScroll.js  and to include scrolloverflow.js before fullpage.js file.

I'll close the issue until a reproduction is provided.

**Comment by vk011** [comment]
Hello again good sir,

I seem to have all the 3 things covered, would a live url suffice instead of a reproduction?

https://dev2.oshinstudio.com/valia/

**Comment by alvarotrigo** [comment]
> https://dev2.oshinstudio.com/valia/

Tested on browser stack on Chrome using Samsung Galaxy S6. Working as expected.

**Comment by vk011** [comment]
That's weird, I am still not getting anything, though it would be weird for chrome to not work ( as I said testing iphone on browserstack works fine). OK I'll try testing on an actual phone then, thank you for the effort!

**Comment by vk011** [comment]
Sorry for bothering you again but can you just confirm you tested on the phone from the image (samsung galaxy S6), because I tried also on S5 and it works fine, but on S6 it does not.

S6 is chrome 49 on android lollipop (and for me it does not work there), and S5 where it works is chrome 49 android kitkat.

Sorry again for bothering you but it just does not make sense.

![image](https://cloud.githubusercontent.com/assets/16360732/15898749/b732056c-2d99-11e6-8e38-a7bca2a04437.png)

**Comment by alvarotrigo** [comment]
> Sorry for bothering you again but can you just confirm you tested on the phone from the image (samsung galaxy S6)

I did. 

![demo22](https://cloud.githubusercontent.com/assets/1706326/15899165/c4c291d0-2d92-11e6-84cd-0e7b6aaebff6.JPG)
