### ISSUE TITLE
moveSectionDown() doesn't work when scrollOverflow: true

### ISSUE THREAD

**Issue by syampolskiy** [alvarotrigo/fullPage.js#2082]
moveSectionDown() doesn't work when scrollOverflow: true
when scrollOverflow: true and scrollbar is not active (content of section goes in), function $.fn.fullpage.moveSectionDown(); works, but when scrollbar is active (content of section is bigger than section height) moveSectionDown() does not work

```javascript
$('#block_for_scroll').fullpage({
		menu: ".nav_list",
		anchors: ['theplatform', 'yourbenefits', 'testimonies','contactus'],
		scrollOverflow: true,
		paddingTop: '87px',
		scrollOverflowOptions: {
			scrollbars: true,
	        mouseWheel: true,
	        hideScrollbars: false,
	        fadeScrollbars: false,
	        disableMouse: true,
	        interactiveScrollbars: true
		}
	});
```

**Comment by alvarotrigo** [comment]
Working as expected as you can see here:http://jsfiddle.net/97tbk/1299/

Closed until a reproduction is provided.
