### ISSUE TITLE
Destroy if window size is below...

### ISSUE THREAD

**Issue by lkfranklin** [alvarotrigo/fullPage.js#2084]
Apologies if this is not the correct place to post..

This is not an issue with the plugin as I can confirm this works perfectly find as a click event however I'm trying to destroy all on window resize and it's just destroying all of my jQuery along with it, basically erroring my jQuery.

The code I have is:

function myFunction() {
		if($(window).width() <= 1280)
		{   
			$.fn.fullpage.destroy('all');
			console.log('Less than 1280');
		}
		else
		{
			console.log('More than 1280');
		}
	}

Am I doing something wrong in the destroy function call by placing it here? 

Thanks,

**Comment by alvarotrigo** [comment]
Why dont use the `responsiveWidth` and `responsiveHeight` options?

Regarding your question, the `resize` event gets called hundreds of times on resize. You'll have to know when to call the function and when not as you won't be able to call it again after you destroyed it.

But that's more a matter of Javascript knowledge and you should ask those questions in stackoverflow.com.
