### ISSUE TITLE
scrollOverflow + Anchors

### ISSUE THREAD

**Issue by lkfranklin** [alvarotrigo/fullPage.js#2085]
Not sure if that has been previously raised but there seems to be an issue with data anchors not working correctly on sections/slides that have the iscroll plugin activated on them. If scrollOverflow is set to false then it works fine. 

I've tested this also on the scrolling.html example provided by just adding in an anchor to '#secondPage/1'.

**Comment by lkfranklin** [comment]
Setting scrollOverflowOptions with click set to 'false' seems to have fixed it.

scrollOverflowOptions: {
			scrollbars: true,
			mouseWheel: true,
			hideScrollbars: false,
			fadeScrollbars: false,
			disableMouse: true,
			click: false
		}

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction ideally in jsfiddle or codepen as stated in the issue skeleton and in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

**Comment by lkfranklin** [comment]
No worries I fixed it with my above reply.

To be fair though your demo page doesn't actually have an anchor link aside from the control arrows.

**Comment by alvarotrigo** [comment]
> To be fair though your demo page doesn't actually have an anchor link aside from the control arrows.

It does. Each section and each slide has an anchor.

**Comment by alvarotrigo** [comment]
> click set to 'false'

Be careful, your links won't work using that configuration That's [a known bug in iScroll.js](https://github.com/cubiq/iscroll/issues/955)

**Comment by lkfranklin** [comment]
Apologises, I mean an anchor tag to an anchored section or slide. 
ie: <a href="#secondPage/1">Click</a>

Ahh ok, I haven't tried it on mobile for tap responses yet... I take it there's currently no work around in that case?

**Comment by alvarotrigo** [comment]
> I take it there's currently no work around in that case?

I would suggest getting rid of scrollOverflow as a real responsive site shouldn't need it. 
Using `fp-auto-height` or `fp-auto-height-responsive` seems like a much better option to me together with `responsiveWidth` and `responsiveHeight`.

Otherwise you can always find some tricks as the one suggested [here](https://github.com/alvarotrigo/fullPage.js/issues/2035#issuecomment-224549092).
