### ISSUE TITLE
Last Section Active - is there a way to tell?

### ISSUE THREAD

**Issue by JoshCarey** [alvarotrigo/fullPage.js#2086]
I've read through the documentation, and I'm only finding the way to see what the "current" section is by seeing the body class change.  This would work fine if I had a static number of sections, but this site has a dynamic number of sections.

Is there any way to tell if the last section on the page is currently being viewed?

**Comment by JoshCarey** [comment]
Actually, I think I may have found a solution, although I'm not sure if its the most proper way...
Finding the last child, then adding a "last-section" class to it:
```
var lastSection = $('.homeScrollSnap .panel:last-child');
lastSection.addClass('last-section');
```
Then using the `afterLoad` function:
```
afterLoad: function() {
  if (lastSection.hasClass('active')) {
    // do what I need to do
  }
}
```

**Comment by alvarotrigo** [comment]
Use [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) such as `afterLoad` or just the the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) ('active') for the active section or `fp-viewing-X-Y`

**Comment by eh-am** [comment]
Is a function like 'isLastSection' easy enough to implement? In my case it would be very handy :)

**Comment by alvarotrigo** [comment]
> Is a function like 'isLastSection' easy enough to implement? In my case it would be very handy :)

No. But you can figure it out using the afterLoad or onLeave callbacks and basic javascript logic. 

```javascript
var  isLastSection = (index === lastIndex)
```
where lastIndex is the number of sections of your site.
