### ISSUE TITLE
Can't detect when User scrolls using jquery scroll()

### ISSUE THREAD

**Issue by cmitides89** [alvarotrigo/fullPage.js#2087]
Hi Alvarotrigo, 

First I want to really thank you for making such an amazing library! 

Unfortunately I can't seem to animate my inner divs when the user is within a specific section.
for example, I want to fade in my section's children only when the user has that section within their view. 
Currently they animate immediately when the page loads and by the time i scroll down to that section they have already animated into the view.

I have noticed that your code changes the body's id to `fp-viewing-**sectionClassChangesOnScroll**`   

Because of this I thought I could do this:
```
$(window).scroll(function(){ 
  //getBody's ID 
    //if ID == fp-viewing-sectionclass{
   //animate children of that section
 }
});
```
However the scroll function does not fire, I am assuming this because the browser views the site as a single page? - (I am not really sure why) 

I was really hoping you could give me some advice as to how I can animate those children.

Thank you very much in advance.
### Versions 
[Google Chrome, OSX, MacBookPro]

**Comment by alvarotrigo** [comment]
Read the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) where it is explained.

Use callbacks or state classes to fire your actions.

**Comment by cmitides89** [comment]
Great, thank you for the link!
