### ISSUE TITLE
Set container for slideNavigation 

### ISSUE THREAD

**Issue by thecheshirecat** [alvarotrigo/fullPage.js#2090]
It's not an issue actually, but I would like to know one thing of slideNavigation.

It is possible to put the dots into a specified container instead of the bottom of the section? 

I'm asking it because of the design I have, they should be below a box, but if positioned with an absolute position, when it goes smaller the height of the window, it will overlap other elements in the page.

**Comment by alvarotrigo** [comment]
The plugin doesn't provide any way to do so. 
But you can always create your own navigation bar and assign to it the fullpage.js events such as `moveTo`.

**Comment by thecheshirecat** [comment]
Thanks, will take that in mind instead.
