### ISSUE TITLE
Weird behavior with carousel

### ISSUE THREAD

**Issue by mihaai** [alvarotrigo/fullPage.js#2091]
Hello,

Congrats on the great plugin and support.

Here is a barebones version of my project:
http://www.sapioconcept.ro/issue/index-display.html
http://www.sapioconcept.ro/issue/index-no-display.html

I'm getting some weird behavior in combining fullpage.js with owl carousel.

The difference between the two is that in "index-display" I've added "display:block" to the "owl-carousel" container.

In the first one, on desktop and on mobile, the second section gets some extra space at the bottom and if you scroll between sections 2 and 3 the space gets bigger.

In the second one, in mobile mode (desktop, floating browser window) the second section gets stuck at the bottom but if you resize the window just a little bit it updates and shows ok,  while if the browser window is maximized, it works ok.

Any thoughts would be greatly appreciated.

Thanks!

**Comment by alvarotrigo** [comment]
If you believe it is a bug in fullpage.js please reproduce the issue without OWL library.
I'll close the issue until then.
