### ISSUE TITLE
.fp-viewing + visibility: hidden; Not working if the section has slides

### ISSUE THREAD

**Issue by randomjumble** [alvarotrigo/fullPage.js#2092]
### Description
hi

I am trying to hide certain sections using "visibility: hidden;" and with combination of .fp-viewing-1  or .fp-viewing- 2 etc.

This works well -
ex: 
```
.fp-viewing-1 .title.fixed {
    visibility: hidden;
}
```

if the section does not have slide enabled, meaning only

<div class="section">
</div>

it fails if 

```
<div class="section">
<div class="slide>
</div>
</div>
```

see example at 

http://codepen.io/anon/pen/yJOyqQ

in the example I have

```
.fp-viewing-1 .title.fixed {
    visibility: hidden;
} /* has slides */

.fp-viewing-3 .title.fixed {
    visibility: hidden;
} /* does not have slides */

```
and 

```
.fixed {
  position: fixed;
  bottom: 20px;
}

.title {
  z-index: 2;
  background-image: url("http://dummyimage.com/500x100");
  width: 100%;
  height: 64px;
    overflow: hidden;
  background-repeat: no-repeat;
  background-position: 50% 50%;
}
```

the footer is hidden but only in the section that does not have slides.

essentially I am trying to hide footer icons when I use the slide option to show the navigation bullets.

### Link to isolated reproduction with no external CSS / JS

http://codepen.io/anon/pen/yJOyqQ

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
latest from cdnjs

**Comment by alvarotrigo** [comment]
Check your developer tools, the class you have to apply is `fp-viewing-1-0` because you are in the slide 0.
