### ISSUE TITLE
IE8 navigation only visible after resizing

### ISSUE THREAD

**Issue by dmarcos89** [alvarotrigo/fullPage.js#2093]
Hi, whats up?
This plugin is awesome, great work!
I am having this weird error, which is causing the nav dots to only appear after resizing... (IE8)
You can check the code here: http://dev.baummstudio.com/clients/bps/Generica.html
Thanks!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen without any external CSS or JS as detailed in the [reporting issues](https://github.com/alvarotrigo/fullPage.js#reporting-issues) guidelines and the issue skeleton. 

I'll close the issue until then.
