### ISSUE TITLE
A simple WordPress implementation overview?

### ISSUE THREAD

**Issue by paaljoachim** [alvarotrigo/fullPage.js#2094]
Could you please add a simple WordPress implementation overview?

I am checking out Themifys Full Pane theme and learning from that as well.
Thank you.

**Comment by alvarotrigo** [comment]
> Could you please add a simple WordPress implementation overview?

Not really. I do not do Wordpress stuff :)

**Comment by paaljoachim** [comment]
Ok. Thanks for the quick reply..:)
