### ISSUE TITLE
Navigation does not work properly in IE 11

### ISSUE THREAD

**Issue by rscharfer** [alvarotrigo/fullPage.js#2095]
### Description

Navigation does not work properly in Internet Explorer 11.  Using the navigation (with the navigation burger) will overshoot the anchor tag or miss it completely.  I assume it does not work properly in other versions of IE, but I haven't been able to test that.  In Edge, it presumably works fine.

### Link to isolated reproduction with no external CSS / JS
http://www.p-didakt.de/  (Sorry, I tried making a isolated reproduction on CodePen, but I can't find links to all of the external files which are used.)
### Versions 
It works fine in Chrome and Firefox.

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/) is working as expected in all versions of IE > 7.

I'll close the issue until you manage to reproduce **a simplified version of the issue** in jsfiddle or codepen. (no burger menu to start with)
