### ISSUE TITLE
Jump over slides

### ISSUE THREAD

**Issue by andylaci** [alvarotrigo/fullPage.js#2096]
Hello, I would like to suggest nice feature ->
when you have navigation, you should be able to scroll from last to first with "single slide animation". It looks better at some points, just suggestion. Correct me, if its possible.

**Comment by alvarotrigo** [comment]
> when you have navigation, you should be able to scroll from last to first with "single slide animation".

Not possible with fullpage.js. Try [pagePiling.js](http://alvarotrigo.com/pagePiling/) for that.
