### ISSUE TITLE
clicks not working with scrollOverflow:true and v2.8.1

### ISSUE THREAD

**Issue by pikilipita** [alvarotrigo/fullPage.js#2097]
On version 2.81,
while using scrollOverflow:true, dom elements are not clickable anymore on sections taller than the screen size.

when reverting to 2.8.0, those elements are clickable as usual.
when using 2.8.1 but with the parameter scrollOverflow:false, clicks are also working as usual.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2047
