### ISSUE TITLE
Ios scrolling / vertical offset Issue

### ISSUE THREAD

**Issue by kiroukou** [alvarotrigo/fullPage.js#2099]
Hello !

I've been working on a simple page website and I encountered a strange issue with iOs devices (iPad+iPhone 5/6, chrome&Safari)

The scrolling is completely crazy, and a blank white screen is displayed.
You can see it in action here: lagrandebouffe.co.uk

I really do not understand what is happening since it does work pretty well everywhere else (android phones, OSX browsers etc..)

I'm using Bootstrap as well, but the behaviour I'm seing does not correspond to a bootstrap issue in my opinion, hence the issue here.

Is anyone here has an idea of what's happening?  

Thanks in advance.

**Comment by kiroukou** [comment]
FYI, I've made a small change in the sample page, so that i'm using now the CDN version instead of current last github one.
It seems a bit better, since I can see now a part of the section on the viewport. The scrolling works correctly, execpt that strange padding on top...

**Comment by alvarotrigo** [comment]
Working fine for me on iPhone 6S
![iphone](https://cloud.githubusercontent.com/assets/1706326/16074449/7480b26a-32e2-11e6-9ee7-d57d51a195f3.JPG)

I'll close the issue until a reproduction is provided. Also, you should not be using a `frameset`. which is not even supported in HTML5.

**Comment by kiroukou** [comment]
Yes I'm currently working on the problem. 
I should have created a fiddle before so that the problem remains reproductable.

Thanks for the tip. I'll let you know once the problem correctly isolated.

**Comment by kiroukou** [comment]
The problem was due to the instagram && facebook  web embed code...
Not sure why exactly why so far.
