### ISSUE TITLE
fullPage demo in Internet Explorer possibly not correct

### ISSUE THREAD

**Issue by rscharfer** [alvarotrigo/fullPage.js#2101]
### Steps to reproduce it

Hello.  On this page http://alvarotrigo.com/fullPage/#4thpage, the tablets are off-center in IE 11.  This "issue" was visible on two different computers in my office.  Both computers were viewing the demo with IE 11.  I am not sure it is a bug, but probably.  

### Versions 
IE 11

**Comment by alvarotrigo** [comment]
True. 
Thanks for reporting it! I'll take a look whenever I have time.

In any case, I'll close the issue as this is not a fullpage.js problem but a CSS one.
