### ISSUE TITLE
Load section or slide immediately, if not the first

### ISSUE THREAD

**Issue by levipadre** [alvarotrigo/fullPage.js#2102]
Is there a way to jump to the given section or slide when I load/reload the page? For example the url would be domain.com/#section3
The problem is: the very first section always appears for a sec, even if animateAnchor is false.

**Comment by alvarotrigo** [comment]
> even if animateAnchor is false.

That's probably because you are including the library at the end of the `<body>` instead of in the `<head`> as in [all the examples provided in fullpage.js](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

**Comment by levipadre** [comment]
Thanks for the answer, but it did not help. I keep trying.

**Comment by alvarotrigo** [comment]
In the examples it work as expected.
