### ISSUE TITLE
Goin to specific URL it gets me to homepage

### ISSUE THREAD

**Issue by roksamsa** [alvarotrigo/fullPage.js#2103]
When I click to specific url with anchor, web page goes to homepage. Can you help me??

For example, when I type url http://dlightjewels.roksamsa.com/#white-magic, it doesn't go to this section, but it goes to top section http://dlightjewels.roksamsa.com/#home.

I really need help :(

**Comment by alvarotrigo** [comment]
[Demo page](http://alvarotrigo.com/fullPage/#3rdPage) works as expected. 

I'll close the issue until you manage to reproduce the issue in an isoalted environment with no external CSS or JS.

**Comment by alvarotrigo** [comment]
Not able to do so? [Contact me](http://alvarotrigo.com/#contact-page) if you want to contract my services.
