### ISSUE TITLE
Cannot Scroll At All After Destroying Fullpage.js

### ISSUE THREAD

**Issue by RealMakAttak** [alvarotrigo/fullPage.js#2105]
Hello All,

I would like to destroy fullpage.js for mobile, however when I run the destroy method ($.fn.fullpage.destroy('all');) - whilst doing what it is supposed to (basically destroying all of the fullpage functionality), I cannot actually scroll at all anymore, even though the content is extending well below the viewport - there is no scrollbar and no way of scrolling down! 

Can anyone help me, I was under the impression after i destroyed fullpage.js I would just get normal functionality back as though fullpage.js never existed.

Many thanks,

Mak

**Comment by alvarotrigo** [comment]
Probably your own css? 

I can not reproduce it on the [demo page](http://alvarotrigo.com/fullPage/examples/methods.html) after using `destroy(all)`.

I'll close the issue until a reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by RealMakAttak** [comment]
Hello Alvaro,

Thank you for that, I played around with my css a little more and found the reason why, I stupidly had overflow: hidden on the html element. Apologies for wasting your times.

Thanks again,

Mak
