### ISSUE TITLE
Scrolling does not work, if Swipebox modal closed with "ESC"

### ISSUE THREAD

**Issue by arnisjuraga** [alvarotrigo/fullPage.js#2106]
### Description
See http://jsfiddle.net/a60vw9Lj/1/ 

if I set `normalScrollElements: '#swipebox-slider'`
1. Scroll to slide 2
2. Click on "My image 1"
3. Close window with `Esc` (I am using Windows Chrome)

Modal window closes and mouse scroll will not work anymore.

But If You click on "x" to close the modal, mouse scrolling will not break.

With removed `normalScrollElements: '#swipebox-slider'` and using jQuery to disable mouse wheel in opened modal, scrolling works both - modal closed with `Esc`  or mouse click.
See: http://jsfiddle.net/a60vw9Lj/3/

Is it Swipebox issue or Fullpage?

**Comment by alvarotrigo** [comment]
Just use the function `setAllowScrolling` instead whenever you open or close the modal.

`normalScrollElements` can't detect if you are leaving your scrollable element without a mouseout movement. Not ideal for dynamically generated elements.
