### ISSUE TITLE
SetAllowScrolling:false during window.load not working properly

### ISSUE THREAD

**Issue by chrisamsterdam1986** [alvarotrigo/fullPage.js#2107]
Hello all,

I'm trying to disable scrolling for the user during my page load (window.load()) by adding the (I believe) right callback function: SetAllowScrolling. My website is: www.happiness-design.com (still working on it ...)

I now have it set up as the following: 
![screen shot 2016-06-20 at 9 05 29 am](https://cloud.githubusercontent.com/assets/17320007/16185733/50da6710-36c6-11e6-9759-58a848dfc4bc.png)

However, I already figured out that it doesn't work because the Fullpage JS isn't initialized before the window.load. However, this is where I get stuck. Because I'd rather not place it before the window.load() because the window.load() should be first after the document.ready(). But now it is not working, and I can't really figure out why. 

I also already checked your codepen (https://codepen.io/alvarotrigo/pen/EjeNdq) that should describe it, but also in this example I see that the Fullpage JS is initialized before the callback function. 

I hope I made myself clear, if not, please let me know. I feel like I'm really close, but I just don't have the exact knowledge to make this fix myself.

As always, your help is very much appreciated :-)

Chris

**Comment by alvarotrigo** [comment]
> because the window.load() should be first after the document.ready(

Window load will always fire after document ready. If you want to remove the scroll bar while the site is loading, you'll have to do it on document ready, not on windows load. And threfore between the `<head>` elements of your site. 

You can do it with CSS or your own javascript.

Or easier, just take a look at all the fullpage.js examples provided here. Use fullpage.js on document ready on the header, not before the closeing '<body>' (which is after the site has loaded)

**Comment by chrisamsterdam1986** [comment]
Hi @alvarotrigo,

Thank you. I figured it out with your help, again. I know I'm not the most experienced coder in the world, that's why I so much appreciate your help and fast replies.

I wish you all the best,
Chris
