### ISSUE TITLE
Video stops working after I scroll to next section

### ISSUE THREAD

**Issue by anetk** [alvarotrigo/fullPage.js#2108]
Video stops working after I scroll to next section
When i refresh it - it works, but after scroll when I come back to that section it stops...
Let me know if you need examples but this is my html:
`         <video id="bgvid" autoplay loop >
          
          <source src="https://s3.amazonaws.com/blossm/Final_Blossm_Video_1.webm" type="video/webm">
          <source src="https://s3.amazonaws.com/blossm/Final+Blossm+Video_1.mp4" type="video/mp4">
        </video>`

### Versions 
Any browser....

**Comment by alvarotrigo** [comment]
> Video stops working after I scroll to next section

From [the docs](https://github.com/alvarotrigo/fullPage.js#pause-on-leave):

> Embedded HTML5 <video> / <audio> and Youtube iframes are automatically paused when you navigate away from a section or slide. **This can be disabled by using the attribute data-keepplaying. For example:**

```html
<audio data-keepplaying>
    <source src="http://metakoncept.hr/horse.ogg" type="audio/ogg">
</audio>
```

**Comment by konjusina** [comment]
Dear Alvaro,
thank ou very much for the excellent plugin. Pagepiling is really a big one.
Im just trying something out with it and it works well.
Here is my page (which is more a playground than a webpage at this time)
http://stage.interstanding.com/test-2/
The only thing i really can´t solve – and i hope that you may have an idea – is:
When i scroll to the second section and start the video, the scroll navigations stops to work.
Is there a way to keep teh navigation on, while teh video is playing?
Bester regards and keep up teh good work
Robert

**Comment by ahmad-techverx** [comment]
amazing, @alvarotrigo
