### ISSUE TITLE
ScrollOverflow and ResizeWindow

### ISSUE THREAD

**Issue by netzego** [alvarotrigo/fullPage.js#2109]
### Description
When I using scrollOverflow and make the window smaller, so that the scrolloverflow action starts, the fullpage.js worked as expected. But when i make the window big again, scrolling stop working at all.

(on every step i try to scroll thru all sections)

### Link to isolated reproduction
please have a look: [fiddle](https://jsfiddle.net/netzego/5q9y729r/6/)

### Steps to reproduce it
1. start and scroll to the bottom
2. resize the window (make it small enough to let the scrolloverflow script starts)
3. scroll thru all sections
4. resize the window (make it big again)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll take a look these days.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2
