### ISSUE TITLE
Adding/removing data-src when building/destroying fullpage.js

### ISSUE THREAD

**Issue by RealMakAttak** [alvarotrigo/fullPage.js#2110]
Hello All,

Thanks for this plugin Alvaro and hope someone can help:

I have fullpage.js set to destroy for mobile, however, the data-src tags I put in for lazy-loading images when on desktop are then stopping my images from being called on mobile as they are no longer recognised.

I know this might not be a strict fullpage.js question but what is the recommended way to deal with this?

Thanks,

Mak

**Comment by alvarotrigo** [comment]
I guess you would like them to load them all on mobile? 
No lazy loading?

**Comment by RealMakAttak** [comment]
I'd love to lazy-load them but I don't really have the skills to do that at present, if there was a resource you knew I could learn about how to do that I would be more than happy to look at it but if not then yes, just to normally load them would be fine.

Thank you for your help.

**Comment by alvarotrigo** [comment]
If you destroy fullpage.js, fullpage.js shouldn't do anything in your code. The most it can do is just load ALL images when destroying it, changing the attributes `data-src` for `src`.

**Comment by RealMakAttak** [comment]
Ok then, so I'll just change data-src to src with jquery or javascript after when I destroy fullpage.js. 

Thank you.

**Comment by alvarotrigo** [comment]
Yep. That's an option.
But I'll mark it as an enhancement for future releases. fullpage.js should turn all `data-src` to `src` on destroy.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2
