### ISSUE TITLE
auto-height on responsive only

### ISSUE THREAD

**Issue by teolaz1990** [alvarotrigo/fullPage.js#2111]
This is not a bug, this is more a request...
Is it possible to unbind the plugin (and the height calculation for sections) without destroying it only on certain screen formats?
As i can see, for now it's only possible to unbind the autoscroll with the "responsiveWidth" parameter, but nothing else.
I also tried to add an "fp-auto-height" on screen resize on all sections, but it's too late, cause plugin already assigned the height, and... well there's no event handler which starts only after the screen is resized but before the plugin is reinitialized.
Thanks
Teo

**Comment by alvarotrigo** [comment]
> As i can see, for now it's only possible to unbind the autoscroll with the "responsiveWidth" parameter, but nothing else.

Wrong. You can always use the method `setAutoScrolling(false)`

> I also tried to add an "fp-auto-height" on screen resize

No need for that trick. Use the class `fp-auto-height-responsive`.
Needs documentation but its there for you to use. 

What it does is apply auto-height only on responsive mode.

**Comment by teolaz1990** [comment]
Maybe you misunderstood:

> Is it possible to unbind the plugin (and the height calculation for sections) without destroying it only on certain screen formats?
As i can see, for now it's only possible to unbind the autoscroll with the "responsiveWidth" parameter, but nothing else.

I tried to say that there's nothing that could be used to unbind the height calculation...
As there's the "responsiveWidth" parameter to unbind the autoscroll, i was wandering if there's something you can add to unbind even the autoheight event.

> No need for that trick. Use the class fp-auto-height-responsive.
> Needs documentation but its there for you to use.

Well, i don't think it's a good idea to use it directly on code... you assigned everything with plugin, best way is to continue assigning classes with it, don't you agree?
My proposal is to add a parameter as the "responsiveWidth" one, to unlock the fixed height and add your class only below the parameter value (i.e. 768px).

**Comment by alvarotrigo** [comment]
> As there's the "responsiveWidth" parameter to unbind the autoscroll, i was wondering if there's something you can add to unbind even the autoheight event.

Just overide it with CSS:
```css
.removeFixedheight,
.removeFixedheight.fp-slide,
.removeFixedheight.fp-tableCell{
    height: auto !important;
}
``` 
You just have to add the class dynamically using javascript or jQuery.

> Well, i don't think it's a good idea to use it directly on code... you assigned every "fp-" class with plugin, best way is to continue assigning classes with it, don't you agree?

No, I do not agree. That's the whole purpose of that class. It is not used by the library otherwise.
`fp-` classes are just prefixed like so to avoid interference with any external library or developer classes. But they are mean to be used when necessary as stated in the docs.

**Comment by teolaz1990** [comment]
> No need for that trick. Use the class fp-auto-height-responsive.

On which breakpoint this will affect the height precisely?

> But this way you will only be duplicating CSS code as that's exactly what fp-auto-height provides.

No, i'm just asking a development request, as you can develop a small update that could help us with this thing... it's not just for me, it's for everybody :) as the "fp-auto-height" class needs to be inserted on window resize by me, and not by a small new feature of your plugin.

**Comment by alvarotrigo** [comment]
> On which breakpoint this will affect the height precisely?

On the one you specify on the `responsiveWidth` or `responsiveHeight` options.

**Comment by faliqaiman** [comment]
@teolaz1990 not all users would like to have that `fp-auto-height` on each section when it's in a device viewport. That's why you need to insert those `fp-auto-height` by yourself. Or you can try to add those `fp-auto-height` by using `addClass` function.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2
