### ISSUE TITLE
Going from destroyed on mobile to active on desktop - section transition problem

### ISSUE THREAD

**Issue by RealMakAttak** [alvarotrigo/fullPage.js#2112]
Hello All,

Here is the problem:

Let's say that I have set (with matchMedia) for fullpage.js to destroy when the browser viewport is width <800px. 

Then I open a fullpage.js site at width <800px, fullpage.js is destroyed, and I scroll down as normal in between sections but then stop so that in the viewport, say, half of Section 1 is showing and half of Section 2. 

Then I resize my browser upwards, width >800px, same height for example, fullpage.js becomes active, however, the screen is now stuck showing the half of section 1 and 2, or 2 and 3 etc, when translating up and down.

I know this might be a little nitpicky but people could easily resize back and forth and it would be an unpleasant experience. 

Can anyone suggest what I could do to fix this? 

Many thanks,

Mak

**Comment by alvarotrigo** [comment]
Why are you using matchMedia? Why not the `responsiveWidth` or `responsiveHeight` options?

**Comment by RealMakAttak** [comment]
Hello Alvaro,

In all honesty I had forgot the option existed and it completely solves the problem. I could have sworn there was a reason why I used destroy instead but I can't remember why now. 

Anyway many thanks,

Mak

**Comment by RealMakAttak** [comment]
@alvarotrigo I think I posted my amended comment above literally as you closed this.

Anyhow, that was the reason I destroyed it using matchMedia, all of the height and table-cell stuff was being imposed which was a little frustrating. I've just overriden it with CSS as necessary.

Would that be your recommended approach or is there an option I am missing?

**Comment by alvarotrigo** [comment]
> all of the height and table-cell stuff was being imposed

Nothing is imposed. 

Don't want imposed height? Use `fp-auto-heigh` or `fp-auto-height-responsive`.
Don't want table-cell? Use `verticalCentered:false`.

**Comment by RealMakAttak** [comment]
Ok then Alvaro, excellent stuff, thank you for drawing my attention to those options.
