### ISSUE TITLE
Fade Animation

### ISSUE THREAD

**Issue by MehryarS** [alvarotrigo/fullPage.js#2113]
How can I use fade animation instead of slide effect for transition between two section?!

**Comment by alvarotrigo** [comment]
You can't. This is a sliding library.

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
