### ISSUE TITLE
Can't scroll to another section with condition

### ISSUE THREAD

**Issue by drianautz** [alvarotrigo/fullPage.js#2118]
Hello, actually can i make some condition like

i canot go to section 2 if i am not click one or two buttons in section one, but if that section button clicked, it will allow

Thanks

Warmly

**Comment by alvarotrigo** [comment]
Yeah. Just use `setAllowScrolling(false)` to disable it and `setAllowScrolling(true)` to enable it.

**Comment by vincentism** [comment]
so what should i do if i just want to scroll to one direction, i noticed onLeave function, but return false doesn't work ethier

**Comment by alvarotrigo** [comment]
I don't understand what you are asking for.

**Comment by vincentism** [comment]
I mean if,  on section 2, disable slide down, you can slide up, on the other sections, u can slide to both up and down, how to realize it

**Comment by alvarotrigo** [comment]
Just use `setAllowScrolling`. See the docs for more info.
You can also return false in `onLeave`.

**Comment by vincentism** [comment]
sorry don't know if it's just me, seems return false in onLeave cannot stop scroll sections?

**Comment by alvarotrigo** [comment]
You'll have to prove it.
