### ISSUE TITLE
Responsive fails on hard rebuild (fp-responsive class is not getting removed)

### ISSUE THREAD

**Issue by KammererTob** [alvarotrigo/fullPage.js#2119]
### Description
If you destroy the fullpage.js instance with an active responsive option (fp-responsive class added to body) the the class is not removed with it (even when using the 'all' argument).
This causes another created instance (with the same responsive option) to be non-responsive and thus still having the auto-scrolling active. Is this a bug or intended?
This happens because the `setResponsive` function only disables auto-scrolling if the class is not already present: 
```
FP.setResponsive = function (active){
    var isResponsive = $body.hasClass(RESPONSIVE);

    if(active){
          if(!isResponsive){
             FP.setAutoScrolling(false, 'internal');
             FP.setFitToSection(false, 'internal');
             $(SECTION_NAV_SEL).hide();
             $body.addClass(RESPONSIVE);
         }
    }
    else if(isResponsive){
        FP.setAutoScrolling(originals.autoScrolling, 'internal');
        FP.setFitToSection(originals.autoScrolling, 'internal');
        $(SECTION_NAV_SEL).show();
        $body.removeClass(RESPONSIVE);
    }
}
```

### Link to isolated reproduction with no external CSS / JS
https://plnkr.co/edit/5hRk5ecnhsWFtMJByrki?p=preview

### Versions 
Only used the newest version, but should affect all of them

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2
