### ISSUE TITLE
ScrollOverflow: prevent direct jump to other section

### ISSUE THREAD

**Issue by ajben** [alvarotrigo/fullPage.js#2122]
### Description
When the user is scrolling inside a section (with ScrollOverflow) and he reaches the end of the section, the plugin directly jumps to the next section (to fast). Is there a way to prevent that? eg. with a delay or smth?

It certainly would help making a big padding on the bottom, but then it's ugly when you scroll back/up.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/15s3rjjn/2/

### Steps to reproduce it
just scroll down. make sure your sections (in result window in jsfiddle) are bigger than the window.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/941

No solution was found due to kinetic scrolling.
