### ISSUE TITLE
1px wide view of next slide on slides

### ISSUE THREAD

**Issue by eamonwhiter73** [alvarotrigo/fullPage.js#2123]
### Description
I found a problem, and a solution to it - I just don't know if it is a good one. For a given slide, I could see 1px of the next slide on the right.

My solution was to change:

var sliderWidth = numSlides * 100;

to:

var sliderWidth = numSlides * 100.1;

Is this ok?

### Link to isolated reproduction with no external CSS / JS
[in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided]

### Steps to reproduce it
1. Install
2. Setup slides
3. View slides

### Versions 
chrome

**Comment by alvarotrigo** [comment]
A reproduction is required. 
I'll close the issue until one is provided.
