### ISSUE TITLE
AddClass/removeClass on Leave

### ISSUE THREAD

**Issue by sbellver** [alvarotrigo/fullPage.js#2125]
I try to addClass ore remove when leave a section to change menu opacity.

```javascript
...
onLeave: function(index, nextIndex, direction){
                        var leavingSection = $(this);

                        if(index == 1 && direction =='down'){
                            $('#menu-nav').addClass('active');
                        }

                        else if(index == 2 && direction == 'up'){
                            $('#menu-nav').removeClass('active');
                        }
                    },
...
```
But nothing happend into my div class="menu-nav" when i leave first section.

If i set an alert, it's show ok, but nos addClass/removeClass

**Comment by alvarotrigo** [comment]
You'd better ask this question in stackoverflow. 
Yours is a javascript knowledge question and it is not directly related with fullpage.js.
