### ISSUE TITLE
Hiding arrows on first and last slide.

### ISSUE THREAD

**Issue by danfox** [alvarotrigo/fullPage.js#2126]
Is it possible to hide the left arrow on the first slide and the right arrow on the last slide?

**Comment by tcbisthewaytobe** [comment]
afterRender: function(){
$('.fp-controlArrow.fp-prev').hide();
},

afterLoad: function(anchor, index){
if(index == 1){
$('.fp-controlArrow.fp-prev').fadeOut();
}else{
$(.fp-controlArrow.fp-prev').fadeIn();   
}
},

Place this is your **$(document).ready(function() {** initiation of the page to hide the left arrow on the first slide. You can copy and paste the whole thing again and change it to **.fp-controlArrow.fp-next** to hide the right arrow. Change the number in **if(index == 1)** to the corresponding section number. Tested on my site and seemed to work.

**Comment by tcbisthewaytobe** [comment]
//first slide of the second section
            if(anchorLink == 'secondPage' && slideIndex == 1){
                $('.fp-controlArrow.fp-prev').fadeOut();
            }else{
                $(.fp-controlArrow.fp-prev').fadeIn();
           }

try playing around with this. Of course change the slide **anchorLink** and **slideIndex** as needed and the **fp-controlArrow** to **prev** or **next** as needed.

**Comment by alvarotrigo** [comment]
> Is it possible to hide the left arrow on the first slide and the right arrow on the last slide?

Use `loopHorizontal:false`.
