### ISSUE TITLE
autoScrolling: true, locking mousewheel scrolling

### ISSUE THREAD

**Issue by SilvanTheuma** [alvarotrigo/fullPage.js#2127]
When I am setting autoScrolling to true, the mousewheel and trackpad scrolling will not work. How can I resolve this please.

Thanks

**Comment by alvarotrigo** [comment]
Working as expected on the [demo page](http://alvarotrigo.com/fullPage/). 
I'll close the issue until an isolated reproduction in jsfiddle or codepen is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by SilvanTheuma** [comment]
HI Alvaro,

Can you please check out this link.

http://www.silvantheuma.com/bhu/

Just go to the developer tools, then click on sources --> wp-conten -->
themes/brass-house-unit --> js --> jquery.fullPage.js

Then change the autoScrolling to true and check out what happens.

Thanks
Silvan

**Comment by alvarotrigo** [comment]
> Can you please check out this link.

As detailed in the issue skeleton:

> link to personal websites won't be reviewed unless isolated reproductions are provided]

**Comment by SilvanTheuma** [comment]
Hi Alvaro,

I have created a codepen regading this issue. Below you can find the link.

Currently the autoScrolling is set to true. Thus scrolling with the
mousewheel or arrows will not work. If you set the autoScrolling to false,
the normal scrolling should work. I can't seem to find the problem and it
works perfectly in your demos.

Please let me know if you can help me solve the issue.

http://codepen.io/SilvanTheuma/pen/vKpbrk

Thanks and best regards
Silvan

**Comment by alvarotrigo** [comment]
Your Javascript console is full of errors. Correct them and come back with a clean reproduction.

**Comment by alvarotrigo** [comment]
This said, your issue is very probably in your side. As any other [demo using autoScrolling:true](http://alvarotrigo.com/fullPage/) (which is the default) work as expected and nobody else complained about it.

**Comment by SilvanTheuma** [comment]
Hi Alvaro,

I am very sorry about the errors, I have cleaned it up.

http://codepen.io/SilvanTheuma/pen/vKpbrk

Thanks
Silvan

**Comment by alvarotrigo** [comment]
You are not following the required structure. Check the docs for more info.

You should delete any element between sections such as `<a name="anchPage3"></a>`.
Also, use the latest fullpage 2.8.2

**Comment by SilvanTheuma** [comment]
Hi Alvaro,

Many thanks for your help. I am sorry I missed that. I will use the latest
update as well.

Thanks and best regards
Silvan

**Comment by SilvanTheuma** [comment]
Hi Alvaro,

Is it possible to call the afterSlideLoad callback within the afterLoad,
when using fullpage.js?

I need to check which slide the user is on so that if it is the first or
last slide I would be able to hide the prev or next arrow. I managaed to do
this with the afterSlideLoad callback. However when the ection is loaded,
the first slide is not detected thus the arrow will not be hidden. Because
of this I used the afterLoad callback so when the section loads, it will
automatically hide the prev arrow. However if the user goes another slide
and scrolls to another section, when the user scrolls to the slider section
again, the prev arrow will be hidden even if the user is not on the first
slide. This is why I would like to know if it is possible to nest the
callbacks, or if there is any way of doing this

Thanks
Silvan

**Comment by alvarotrigo** [comment]
No, callbacks are independent from each other. 
Both will get fired in some scenarios. 

> I would be able to hide the prev or next arrow. I managaed to do
> this with the afterSlideLoad callback

You can do it easier with CSS by using the fp-viewing-X-Y class added to the body element.
If you use the default arrows, just use `loopHorizontal:false` to make the arrows disappear in the 1st and last slides.

**Comment by SilvanTheuma** [comment]
Hi Alvaro,

Thanks a lot managed to do it using the CSS class.

Regards
Silvan
