### ISSUE TITLE
'normalScrollElements' will force scrolling to stop where there's an overflow:auto

### ISSUE THREAD

**Issue by VirtualVirtuoso** [alvarotrigo/fullPage.js#2128]
### Description
In my application, I've got a series of sections. These scale to the size of the screen. Inside each of these sections, there's an inner-div, which has a `overflow-y: auto'`.

This means that if there's more content than the box will support, then it will turn into a scroller. However, most of the time, the scrollbar is not visible. 

I'm currently using `normalScrollElements: '.section-main'` to pause when there's a scrollbar. However, this also seems to pause when there's a div with overflow-y: auto. This means that if an end-user has their mouse over this div, and there's no scrollbar, there will be no scrolling action. I understand this behaviour, but they might not.

![Scrolling Example Gif](http://g.recordit.co/51NdBR2roA.gif)

Any help would be appreciated!

Thanks

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by VirtualVirtuoso** [comment]
Ah, my apologies. 

### Description
Scrolling is locked when cursor is over a section with `overflow-y: auto` defined. Scrolling will also not commence after the user has scrolled to the bottom of said container.

### Link to isolated reproduction with no external CSS / JS
http://codepen.io/Strubo/pen/dXRzRN

### Steps to reproduce it
1. Place cursor within inner white box in any section
2. Try to scroll the cursor

### Versions 
Chrome 51, Windows 10 PC

Thanks :+1:

**Comment by alvarotrigo** [comment]
> This means that if an end-user has their mouse over this div, and there's no scrollbar, there will be no scrolling action.

That's how it is suppose to work in any case. There's no way for fullpage.js to know if you want to use an scrollable element or use normal scroll elements for any other reason. 

You'll have to add a class to elements depending on your needs and add that element in the normalScrollElements. 
In your example, you should only have the class `.section-main` in the element that you want to prevent auto scrolling.

**Comment by VirtualVirtuoso** [comment]
Ah, I see. If I were to define `normalScrollElements: '.scroll-active'`, and then dynamically add that class with JavaScript to elements I want to scroll, would fullPage.js handle that?

Also, thanks for the help so far :) Sending my regards from Chesterton

**Comment by VirtualVirtuoso** [comment]
I ended up managing to solve my problem with the following:

    $(document).ready(function() {
    
        $('#fullpage').fullpage({
            ...
            normalScrollElements: '.scroll-active',
        });

        $(window).resize(function(){
            updateScrollingClasses();
        });

        $(window).bind('mousewheel', function(){
            updateScrollingClasses();
        });
    
        updateScrollingClasses();
    });

Updating function:

    function updateScrollingClasses(){
        $('.section-main').each(function(index) {
            var element = $(this);
            if (element.hasScrollBar()) {
                element.addClass('scroll-active');
            } else {
                element.removeClass('scroll-active');
            }
        });
    }


Scrollbar detection:

    (function($) {
        $.fn.hasScrollBar = function() {
            return this.get(0).scrollHeight > this.height();
        }
    })(jQuery);


Thanks for the help you've provided. I appreciate your time :)
