### ISSUE TITLE
URL With Slash

### ISSUE THREAD

**Issue by apositivo** [alvarotrigo/fullPage.js#2133]
hi !   @alvarotrigo alvarotrigo ,  excelent library fullpage.js ! 

a question . . . .  i have ...

```html
<ul id="menu">
	<li data-menuanchor="firstPage/Test1"><a href="#firstPage/Test1">First lide</a></li>
	<li data-menuanchor="secondPage/Test2"><a href="#secondPage/Test2">Second slide</a></li>
	<li data-menuanchor="3rdPage/Test3"><a href="#3rdPage/Test3">Third slide</a></li>
</ul>

<div id="fullpage">
	<div class="section " id="section0" data-anchor="firstPage/Test1">
		<h1>fullPage.js</h1>
		<p>Configure the scrolling speed!</p>
		<img src="imgs/fullPage.png" alt="fullPage" />
	</div>
	<div class="section" id="section1" data-anchor="secondPage/Test2">
	    <div class="slide">
			<div class="intro">
				<img src="imgs/1.png" alt="Cool" />
				<h1>Slow scrolling speed</h1>
				<p>In case we want to make a site for old people, for example :)</p>
			</div>
		</div>
	    <div class="slide">
			<div class="intro">
				<img src="imgs/2.png" alt="Compatible" />
				<h1>Landscape too</h1>
				<p>Also applied to landscape slides. Great uh?</p>
			</div>
		</div>
	</div>
	<div class="section" id="section2" data-anchor="3rdPage/Test3">
		<div class="intro">
			<h1>Slooooooww</h1>
			<p>Now you can try other demos!</p>
		</div>
	</div>
</div>
```

in my URL i want ( if this is possible) 
www.mydomain.com/#firstPage/Test1
www.mydomain.com/#secondPage/Test2
and 
www.mydomain.com/#3rdPage/Test3

what do you Think? ,    in this case (  is possible ),  what are the change  ?

disable bodyclass() ?  delete the replace in  windows.location ...

you can help me please ? , ,, , any ideas ?

**Comment by vikaskyadav** [comment]
i don't think you would be able to do that. It would still be a single page inside the <div id="fullpage"></div>,i guess so..

**Comment by apositivo** [comment]
hi @vikaskyadav    hello, thanks for writing, hopefully the opinion of the creator of the plugin @alvarotrigo

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2000
