### ISSUE TITLE
Pin Elements with scrollMagic using fullPage

### ISSUE THREAD

**Issue by damienroche** [alvarotrigo/fullPage.js#2134]
Hi guys,

First, thanks for this awesome plugin.

## Description
I'm trying to use fullPage with somes overflowed sections.
In each of this sections, I would like to fix some divs while user scroll the section by using scrollMagic.js
I make an example here : [http://codepen.io/ramien/pen/akwYKr]
(I don't know why but you have to change the order of scrolloverflow.min.js plugin by put it over fullPage.min.js, when I save my pen, it's not taken into account]

Because fullPage is using iScroll to manage the overflow, fixed elements or not placed in the right place. However scrollMagic can also deals with iScroll by getting the Y position. 
There is an example here : 
[http://scrollmagic.io/examples/expert/mobile_advanced.html]

## My question : 
There is a way to know this Y position when user scrolls the section ?

Cheers,
Damien

**Comment by alvarotrigo** [comment]
> There is a way to know this Y position when user scrolls the section ?

fullpage.js doesn't provide such option. 

If you are talking about the scrolling within the scrolloverflow functionality, you should check the [documentation for iScroll.js](http://iscrolljs.com/)
