### ISSUE TITLE
autopause doesn't work when autoScrolling is false

### ISSUE THREAD

**Issue by damienroche** [alvarotrigo/fullPage.js#2135]
If my fullPage is set with auto Scrolling: false and if I embed a video from youtube on a section.
fullPage doesn't automatically pause the video when I scrolled down on another section.

**Comment by alvarotrigo** [comment]
I'll close the issue until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2
