### ISSUE TITLE
Back to first section when scrolling on mobile

### ISSUE THREAD

**Issue by KatsanKat** [alvarotrigo/fullPage.js#2136]
Hi Alvaro !

First of all, thank you for this great plugin :) 
I have a strange issue on my website.

I've made some Js to destroy the plugin when i'm on mobile because my content doesn't fit in one screen. But i think that i've made a mistake or something.
When i scroll down or up on mobile, it automatically take me back to the top of the page i don't know why :/

Here's the code :

Js
`$(document).ready(function () {

			function getWindowHeight(){
			  return window.innerHeight ? window.innerHeight : $(window).height();
			}
            $('#fullpage').fullpage({
                verticalCentered: false,
				lockAnchors: true,
                anchors:['accueil', 'empreinte', 'convictions', 'metier', 'personnalite', 'references', 'contact', 'footer'],
				css3: false,
                autoScrolling: true,
                fitToSection: false,
                scrollOverflow: false,
                afterRender: function () {
                    //on page load, start the slideshow
                    slideTimeout = setInterval(function () {
                    	$.fn.fullpage.moveSlideRight();
                    }, 7000);

					$(".fp-controlArrow").click(function(){
						clearInterval(slideTimeout);
					});
                }

            });

			var iWindowsSize = $(window).width();
			if (iWindowsSize  < 992){
			  $.fn.fullpage.destroy();
			};
			$( window ).resize(function() {
			  $.fn.fullpage.destroy();
			});
        });`

I'm on Android if it can help.
Thanks again for this plugin, hope you can help me :)

(Sorry if i've made some mistakes, i'm not native)

**Comment by alvarotrigo** [comment]
> I've made some Js to destroy the plugin when i'm on mobile because my content doesn't fit in one screen

No need to destroy it.
You can always use `fp-auto-height-responsive` and the `responsiveWidth` or `responsiveHeight` options.

I'll close the issue until an isolated reproduction is provided as detailed in the reporting issues guidlines and the issue skeleton.
