### ISSUE TITLE
Chrome scales down images 50% on dev system only

### ISSUE THREAD

**Issue by bvesd** [alvarotrigo/fullPage.js#2137]
All images (and fonts) are scaled down around 50% when using Chrome on local dev system.
If I go into developer tools and use the screen emulator set to responsive, everything looks normal.
Checked in Firefox and on phone and there it all looks fine as well.
Uploaded everything to an external webserver and it's fine as well.

Tested with and without added custom css styling, with and without added images.
Also tested using the most basic initialization options.

So it seems there is something in Chrome on my dev system causing this.

I am on Xubuntu 14.04
Chrome 51.0.2704.106 (64-bit)
jQuery 3.0 (started with 2.2.0 but upgraded)
fullPage.js 2.8.1
Apache 2 with basic configuration

This might be too specific, but maybe somebody has an idea? thanks.

**Comment by alvarotrigo** [comment]
> All images (and fonts) are scaled down around 50% when using Chrome on local dev system.

fullpage.js doesn't touch images sizes at all.

Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.
