### ISSUE TITLE
normalScrollElements

### ISSUE THREAD

**Issue by thecheshirecat** [alvarotrigo/fullPage.js#2138]
Hello,

I'm trying to stop the autoscrolling using 'normalScrollElements' on a section with an id.

Example:

<div class="section" id="webs">
    ...
</div>

$("#fullpage).fullpage({
    normalScrollElements: "#webs"
});

But it is scrolling to the next section. I'm doing it right or it's a bug?

My point is, that in this section, the autoscroll stops due to some slides that are inside, and when the last slide is shown, then autoscroll to the next section.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by thecheshirecat** [comment]
Well, I tried adding the js file before the bootstrap js and now it's working.
