### ISSUE TITLE
Can't use audio controls in IE when using scrollOverflow

### ISSUE THREAD

**Issue by mschmitz89** [alvarotrigo/fullPage.js#2139]
When using html 5 audio element on a page with fullPage.js and scrollOverflow is active, the control-buttons can't be clicked in current Firefox or Internet Explorer. But Chrome works.

Link to fullPage.js example site with an audio elment integrated: http://codepen.io/anon/pen/bZAaBY

**Comment by alvarotrigo** [comment]
It seems to work with the `dev` version.
Substitute your JS file or [this one](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/jquery.fullPage.js) and let me know if it works.

I'll mark it as fixed. Let me know if it works ok for you.

**Comment by mschmitz89** [comment]
Works like a charm! Thank you very much for your fast feedback! :)

**Comment by mschmitz89** [comment]
Edit: Doesn't work in IE11

**Comment by alvarotrigo** [comment]
Probably related with the `click` event not being propagated... 
I'll try to simplify the reproduction of the issue later on.

**Comment by alvarotrigo** [comment]
This is actually [a bug of the vendor library iScroll.js](https://github.com/cubiq/iscroll/issues/1078), which fullpage.js uses when using scrollOverflow:true.

**Comment by alvarotrigo** [comment]
Fixed in v4! 👍
