### ISSUE TITLE
Scroll-up locked after using anchor to get to #n page

### ISSUE THREAD

**Issue by lnicolet** [alvarotrigo/fullPage.js#2140]
### Scrollup being locked.
I got a problem implementing fullPage.js, whenever i click on a menu-anchor it works perfectly, but it then get stuck and i cannot scroll up from that page anymore, like the anchor become the first thing in my page.

### Script to enable it:
```javascript
$(document).ready(function() {
			$('#fullpage').fullpage({
				sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
				anchors: ['first', 'second', 'third', '4th', '5th'],
				menu: '#menu',
			});
		});
```
 I then have a simple ul menu, and normal sections.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.
