### ISSUE TITLE
Fullpage.js and Wordpress: Block Scroll on Modal

### ISSUE THREAD

**Issue by antisnerd** [alvarotrigo/fullPage.js#2141]
### Description
I am tring here http://ap.nowcommu.myhostpoint.ch/ to use a Modal with fullPage.js without results.
On mobile it works, but on desktop, when you scroll inside the Modal Window the fullpage did not block the scroll. 

**I need to block the page scroll on Modal Open.**

Actually i am running fullPage.js with Wordpress using this plugin https://codecanyon.net/item/smart-one-page-navigation-addon-for-visual-composer/14445813

For the Modal i am using this plugin https://codecanyon.net/item/visual-composer-extensions/7190695

### Steps to reproduce it
1. Click on the orange + icon
2. Scroll the modal Window

**Comment by alvarotrigo** [comment]
> I need to block the page scroll on Modal Open.

Use the fullPage.js function `setAllowScrolling(false)`

**Comment by antisnerd** [comment]
Sorry could you please give me a complate example?

**Comment by alvarotrigo** [comment]
```javascript
$('#demo').click(function(){
    $.fn.fullpage.setAllowScrolling(false);
});
```

If you still don't understand it you'd better ask in other place. This is basic javascript knowledge and this forum is not to treat those basics.

**Comment by antisnerd** [comment]
In my case i tried this
`<script type="text/javascript"> 
$(document).on('click', '.ts-awesome-plus', function() {
$.fn.fullpage.setAllowScrolling(false);
$.fn.fullpage.setKeyboardScrolling(false);
}); 
</script>`

Without resutls

**Comment by alvarotrigo** [comment]
As I said, this i not the place to ask.
If you believe it is a bug in fullpage.js you should proceed to create an isolated reproduction in jsfiddle or codepen to prove it.
