### ISSUE TITLE
Fullpage.js and the IScroll object

### ISSUE THREAD

**Issue by Taigistal** [alvarotrigo/fullPage.js#2143]
### Thanks
Thank you for this amazing piece of Code!

### Problem
I want to use the IScroll object that was created with fullpage.js.
var myScroll = new IScroll(wrapper);

I see that there is a function to generate all the IScroll objects, but i have no idea how to use it in my scripts.js (loaded after scrolloverflow and fullpage.js) to use something like:

myScroll.x;

or

myScroll.scrollTo();

best regards from germany ;-)

**Comment by alvarotrigo** [comment]
Not an issue of fullpage.js.
You'd better ask in other place such as stackoverflow for those general Javascript questions.
