### ISSUE TITLE
Page Load Scroll Current Section Issue

### ISSUE THREAD

**Issue by vpjm** [alvarotrigo/fullPage.js#2145]
I have fullPage.js working for the most part on my website, however there is one big issue that I can't seem to find a solution for. I am trying to the the animateAnchor option with a value of false but this doesn't seem to be having any effect at all. The site still loads to the first section and then scrolls down to the current section. With some sections, it seems like it isn't even scrolling properly, as the full section doesn't take the full height of the browser window. 

Here is an example of a section that at least displays properly but the animateAnchor: false option isn't working: http://citizensforpritchard.b-v.design/#home3

Here is an example of a section that really gets messed up when the page is loaded to this section: http://citizensforpritchard.b-v.design/#about

The problem only happens on page load, scrolling is fine once the page is loaded.

This issue is happening in Chrome, Firefox, MS Edge.

I am including the library in the header and making the initialization call in the header as shown in the examples.

Any help you can give would be appreciated.

**Comment by alvarotrigo** [comment]
>in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided. Reported issues without a reproduction might be closed.

Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.
