### ISSUE TITLE
Fullpage and wow

### ISSUE THREAD

**Issue by isisCode** [alvarotrigo/fullPage.js#2146]
Hi. Thank you for the awesome script.

I have a question. I'm using both fullpage.js and wow.js. It works fine, but on tablet  when the page is longer and you must scroll to see it, it only animates the content that is visible from the beggining and not the one is revealed after the scrolling (actually that content is totally hidden, only when I start browsing the website that page displays the whole content).

Also, I would like to have animation on the inner sliders also, but I guess the onLoad event or something sees that the page was already loaded from the first slide and doesn't do the animation when scrolling inside section.

I hope my message is some how clear, pretty hard to explain. :)

Thank you in advance for your response!

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/249

**Comment by isisCode** [comment]
Thank you! I read that post, but it didn't solved my problem, plus I get this warning when I add scrollBar: true, "Option `scrollBar` is mutually exclusive with `scrollOverflow`. Sections with scrollOverflow might not work well in Firefox". Anyway I am trying to give up to wow.js and just use afterSlideLoad function.

Thanks again for the quick response.
