### ISSUE TITLE
fancybox does not work with scroll overflow?

### ISSUE THREAD

**Issue by barzioni** [alvarotrigo/fullPage.js#2147]
Hi Alvaro,

First of all thank you for your awesome plugin! it is really amazing!

unfortunately i have an issue caused with the option scroll-overflow and fancybox plugin:

on my second slide i placed some images with a fancybox link, including the option scroll-overflow and it worked well,

but when i resize my window (for mobile view-images is one above the other) and the scroll-overflow take place the fancybox plugin is not responding.

any way to fix it?

the js code:

$(document).ready(function() {
$('#fullpage').fullpage({
anchors: ['firstPage', 'secondPage', 'thirdPage'],
sectionsColor: ['#000000', '#eeeeee', '#ffffff'],
slidesNavigation: true,
menu: '#menu',
resize: false,
loopHorizontal: false,
scrollOverflow: true,
scrollOverflowOptions: null,
scrollOverflowOptions:{
scrollbars: true,
mouseWheel: true,
hideScrollbars: false,
fadeScrollbars: false,
disableMouse: true
}
});

$(".fancybox").fancybox();

thank you for your support, and sorry if i sound a bit rookie its all new for me! (:

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by barzioni** [comment]
sorry, but i didn't understand, what is "Reproduction required" means? do i need to write the issue once again without the code?

**Comment by alvarotrigo** [comment]
> sorry, but i didn't understand, what is "Reproduction required" means?

As specified in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) you have to reproduce the issue ideally in jsfiddle.net or codepen.io without any external CSS or JS unless required for the reproduction.
