### ISSUE TITLE
scrolloverflow not working with fancybox

### ISSUE THREAD

**Issue by barzioni** [alvarotrigo/fullPage.js#2148]
Have an issue caused with the option scroll-overflow and fancybox plugin:
on my second slide i placed some images with a fancybox link, including the option scroll-overflow and it worked well,

but when i resize my window (for mobile view-images is one above the other) and the scroll-overflow take place the fancybox plugin is not responding.

any way to fix it?

thank you for your support

**Comment by alvarotrigo** [comment]
Duplicated: https://github.com/alvarotrigo/fullPage.js/issues/2147
