### ISSUE TITLE
Can't submit form  when using scrollOverflow

### ISSUE THREAD

**Issue by piaomiao** [alvarotrigo/fullPage.js#2150]
### Link to isolated reproduction with no external CSS / JS
[in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided. Reported issues without a reproduction might be closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by timgaines** [comment]
I am experiencing this same issue.

[Codepen Reproduction](http://codepen.io/timdoes/pen/vKwmZr)

**Comment by timgaines** [comment]
If the `<input type="submit" />` is the issue. If it is changed to a `<button type="submit" />` the form submits.

**Comment by alvarotrigo** [comment]
@timgaines your codepen works as expected to me. Change  `action="#submitted"` for `action="submited.php"` to see it working as expected.

**Comment by j4k3** [comment]
Same behaviour for me on Android and iOS.
