### ISSUE TITLE
Multiple vertically centered columns

### ISSUE THREAD

**Issue by jameslavine** [alvarotrigo/fullPage.js#2151]
Hi, I'm wondering if you have the intention of expanding this to support multiple columns of content, where each individual column would also be vertically centered on the page, regardless of height differences between the columns.

This is what currently happens with multiple columns: https://dl.dropboxusercontent.com/u/92804018/Vertical%20Alignment%20%3E%20Incorrect.jpg

This is the desired effect: https://dl.dropboxusercontent.com/u/92804018/Vertical%20Alignment%20%3E%20Correct.jpg

Maybe there's already a way to do this that I'm just missing! Looking forward to hearing your thoughts.

Thanks,
James

**Comment by alvarotrigo** [comment]
> Hi, I'm wondering if you have the intention of expanding this to support multiple columns of content

Nop. 
This is a CSS issue that should be taken care of outside fullpage.js.
