### ISSUE TITLE
Scrolling to anchors and fixed elements.

### ISSUE THREAD

**Issue by Samovarus** [alvarotrigo/fullPage.js#2153]
### Description
In mobile version (site is responsive):
If using css:false, i can't set position fixed to popups in clients section.
Link to site: http://demo.mir-360.ru/tmd/#clients 

And on the other case if i am setting css3:true, then opening site scrolling by anchors to wrong position.

### Versions 
Chrome in developer tools mode, iphone 5 emulation.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the issue skeleton.
