### ISSUE TITLE
Scroll to Top of Section/Slide on Click

### ISSUE THREAD

**Issue by accurate** [alvarotrigo/fullPage.js#2155]
### Description
In another site I have a fixed menu with anchored links to sections, when you click on these links it scrolls to the spot where you left off in that section/slide. I'm trying to make it so when you click on it, it scrolls to the top of the section/slide instead or reset the anchor position. See link below for a similar reproduced example.

### Link
http://jsfiddle.net/gxkf47ce/

### Steps to reproduce it
1. Click on the anchored link on top
2. Scroll in the middle-ish
3. Click on arrows to go somewhere else
4. Click again on the anchored link (goes back to the same spot, ideally it should go on top of the div)

### Versions 
Chrome v51 Mac

**Comment by alvarotrigo** [comment]
It behaves as any other element with the CSS property `overflow:scroll` would do.

Because fullpage.js uses a fork of iScroll.js you can take a look at [its documentation ](http://iscrolljs.com/) and find a way to do it in a callback such as `afterSlideLoad` or `onSlideLeave`.

Fullpage.js won't change that behaviour.

**Comment by accurate** [comment]
I have a feeling I'm almost there, but I wanted to check with you to see if there is a function I can use to call iscroll on leave or if I have to do a new call, do I make it on the fp-scrollable div? In your code I found "iScrollInstance", can I use that somehow?

`			onLeave: function(index, nextIndex, direction){
				var section_id = '#'+jQuery('.section')[nextIndex-1].id;
				
				myScroll = new IScroll(section_id+' .fp-scrollable');
				myScroll.scrollTo(0,0); 
			},
`

Thanks for your help!

**Comment by alvarotrigo** [comment]
You can extract the iscroll instance for each section / slide by doing this:

```javascript
//suppossing you have no slides in the section
var scrollable = $('.fp-section').find('.fp-scrollable'); 

var iScrollInstance = scrollable .data('iscrollInstance');
```

If you have slides then you would have to iterate through the slides and find the one you want to extract the iscroll instance.

**Comment by accurate** [comment]
Awesome! That worked perfectly and thank you for the amazing support :)

**Comment by mavnyin88** [comment]
Hey thanks much for this guys - is it possible to see a working example of this? a bit stuck right now

**Comment by squalvj** [comment]
an example would be great

**Comment by AmanSahota** [comment]
Does anyone have a working example of this?
