### ISSUE TITLE
"Cannot read property 'top' of undefined" error stopping waypoint.js from working

### ISSUE THREAD

**Issue by FTA-RBeaney** [alvarotrigo/fullPage.js#2157]
### Description
fullPage.js is throwing a "Cannot read property 'top' of undefined." in the console which is stopping waypoints.js from working.

### Link to isolated reproduction with no external CSS / JS
http://weareshard.com/abstract/scrolltest/index.html

(Sorry, wasn't sure how else to put this up)

### Steps to reproduce it
1. Load page
2. Scroll down. Items are supposed to slide in from the side in the green section.
3. Open console in the developer tools and you can see the error.

### Versions 
Chrome Version 50.0.2661.102 (64-bit)

**Comment by alvarotrigo** [comment]
You'll have to use the uncompressed version of fullpage.js for me to help you.

**Comment by alvarotrigo** [comment]
Well, it looks the reason is you forgot to use an anchor for that section. You are only using two and you have more than two sections:

`anchors:['firstPage', 'secondPage'],`
