### ISSUE TITLE
Ajax load and reBuild()

### ISSUE THREAD

**Issue by AndreaLOKO** [alvarotrigo/fullPage.js#2159]
### Description
I'm loading slides content via ajax successfully, and I make $.fn.fullpage.reBuild() as well.
Everything works fine in all browsers.

From the slide I load other ajax contents but the function it's not inside jQuery('.fullpage').fullpage(...
The ajax call work fine and I load the content in the slide but here I can't update the height with reBuild() because (obviously) the function id outside fullpage() (that I can't load twice).

Can I externally trigger a reBuild to fullpage? In alternative, is it possible to update the height of fp-scroller?

If you need to analyze it I'll give you the progress URL

Thank you!!

**Comment by alvarotrigo** [comment]
> Can I externally trigger a reBuild to fullpage?

Of course you can, just call `$.fn.fullpage.reBuild();` wherever you want. It will always work if fullpage.js was initialized.

**Comment by AndreaLOKO** [comment]
Hi, thanks for the quick answer!

Ok I got it with reBuild() and ajax!

The only issue is that sometimes, reBuilding, on the first mouse scroll you get at the bottom of the page, then it goes fine.

I would be glad to share the link to my script but, for the moment, I can only let you see it in private.
Would you like to see it?

Thank you!

**Comment by alvarotrigo** [comment]
> Would you like to see it?

Sorry I don't provide support for specific websites. 
If you believe there's a bug in the library please reproduce it in an isolated environment such as jsfiddle or codepen and proceed to create an issue with the steps to recreate it.

**Comment by cvaraj** [comment]
@AndreaLOKO i have to same issue, i can't find solution for what you do for that ajax load more issue .. u got any solutions?..

**Comment by alvarotrigo** [comment]
@cvaraj check [my answer in stackoverflow](http://stackoverflow.com/a/36643702/1081396). Very easy to find by looking on google "load dynamic section fullpage.js stackoverflow"
