### ISSUE TITLE
Questions about Slide and CSS3 Transition

### ISSUE THREAD

**Issue by accurate** [alvarotrigo/fullPage.js#2161]
Got a few questions:
1. I saw you can cancel the scroll, but can you pause it, do something and then make it scroll?
2. Is it possible to disable mouse and keyboard during scrolls CSS3 transitions? Since I can fool the code if I scroll quickly between sections. For example, I added some code on leave to target the next section, but I switch sections during the transition, that code is ignored. Or I was thinking to probably make the transitions faster to decrease the chances of this happening. 

### Versions 
Chrome Mac

**Comment by alvarotrigo** [comment]
> but can you pause it, do something and then make it scroll?

Of course, just use the method `moveTo` whenever you want to. That's more a Javascript question than a fullpage.js one. You'd better ask in other place such as stackoverflow.com

2- No idea what you are talking about. Provide a reproduction in jsfiddle or codepen.
