### ISSUE TITLE
Multiple snap scrolls

### ISSUE THREAD

**Issue by anetk** [alvarotrigo/fullPage.js#2163]
Am I able to do multiple snap scrolls with id full page and a different class?
Like I want whole different snap scroll with another options but on the same page?

One more issue: so I have disable snap scroll cause I ended up not using it but have an issue on mobile. SCROLL is really really bad. Anything I can do to improve it?

**Comment by alvarotrigo** [comment]
Not possible I'm afraid.

**Comment by anetk** [comment]
So I want one snap scroll on the page and one separate one on the same page with different options. I want to basically turn it off on desktop and turn it ON on mobile. 

Did you ever have an issue with scrolling on phone when it's disabled?

**Comment by alvarotrigo** [comment]
> So I want one snap scroll on the page and the separate one on the same page with different options

Not possible.

**Comment by alvarotrigo** [comment]
> I want to basically turn it off on desktop and turn it ON on mobile with different content.

Use the `responsiveWidth` option or the method `$.fn.fulpage.destroy`.
