### ISSUE TITLE
Inform about current destination slide, "asynchronous listening to next slide-change"

### ISSUE THREAD

**Issue by arjamizo** [alvarotrigo/fullPage.js#2164]
let's say if I have 10 slides and animation for transition from one to another one takes `1s`, I need to keep scrolling for at least 10s. 

I think I should be able to scroll as much as I want and slides should be come one after another ASAP.

**Comment by alvarotrigo** [comment]
> I think I should be able to scroll as much as I want and slides should be come one after another ASAP.

That's call normal scroll :) 
Just use `autoScrolling:false` for that. Then using `fitToSection` you'll be able to land in the right section.

And if you still want snap scrolling, I'm afraid that's not possible due to kinetic scrolling on trackpads and Apple devices.

**Comment by arjamizo** [comment]
@alvarotrigo hmm, like this? http://codepen.io/xadi/pen/wWmmZj

**Comment by alvarotrigo** [comment]
Exactly.

**Comment by alvarotrigo** [comment]
You can also adjust the `fitToSectionDelay` time.

**Comment by arjamizo** [comment]
so I think I am missing parameter like `oneWheelScrollScrollsOneSlide` :)

example: 

```$('#fullpage').fullpage({
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
  autoScrolling: false, 
  fitToSection: true,
  fitToSectionDelay: 100,
  // oneWheelScrollScrollsOneSlide: true
});```

By having this one could scroll through thousands of slides very fast! 
but this is just a suggestion

**Comment by alvarotrigo** [comment]
> but this is just a suggestion

Thanks, but it is not possible as I said before due to the nature of kinetic scrolling.
