### ISSUE TITLE
installing fullpage with bower

### ISSUE THREAD

**Issue by CYFERIOUS** [alvarotrigo/fullPage.js#2165]
i am installing your library on my project, but this time this happen, so i dont know if its an error of mine; (but another libraries download without problem) or yours

thanks

`$ bower install https://github.com/alvarotrigo/fullPage.js.git
bower fullPage.js#*         not-cached https://github.com/alvarotrigo/fullPage.js.git#*
bower fullPage.js#*            resolve https://github.com/alvarotrigo/fullPage.js.git#*
bower fullPage.js#*           checkout 2.8.2
bower fullPage.js#*            ECMDERR Failed to execute "git clone https://github.com/alvarotrigo/fullPage.js.git -b 2.8.2 --progress . --depth 1", exit code of #128 Cloning into '.'... remote: Counting objects: 92, done.         remote: Cremote: Compressing objects: 100% (88/88), done.         remote: Total 92 (delta 22), reused 46 (delta 2), pack-reused 0         Checking connectivity... done. Note: checking out '6575f1f3b8254d8dca577973c028b0219c78a122'.  You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by performing another checkout.  If you want to create a new branch to retain commits you create, you may do so (now or later) by using -b with the checkout command again. Example:    git checkout -b <new-branch-name>  error: unable to create file examples/imgs/horse.mp3: Permission denied fatal: unable to checkout working tree warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry the checkout with 'git checkout -f HEAD'

Additional error details:
Cloning into '.'...
remote: Counting objects: 92, done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 92 (delta 22), reused 46 (delta 2), pack-reused 0
Checking connectivity... done.
Note: checking out '6575f1f3b8254d8dca577973c028b0219c78a122'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

error: unable to create file examples/imgs/horse.mp3: Permission denied
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'`

**Comment by alvarotrigo** [comment]
Juse use the following as pointed out in the docs:

````shell
bower install fullpage.js
```
