### ISSUE TITLE
TypeError: Cannot read property 'childNodes' of undefined

### ISSUE THREAD

**Issue by CYFERIOUS** [alvarotrigo/fullPage.js#2166]
### well good morning im implementing your library with D3.js and angular.js, but im getting this error.

TypeError: Cannot read property 'childNodes' of undefined

the library works but the d3 graphics disappear.

im testing this on chrome and firefox and its the same in both cases.

thanks

fernando

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
