### ISSUE TITLE
Can't skip to next section inside ScrollOverflow section using mouseWheel, keyboard is working propertly

### ISSUE THREAD

**Issue by jatovar** [alvarotrigo/fullPage.js#2172]
### Description
When using mouse wheel in a section with scrollOverflow the event onLeave is not triggered, so its not going to the next section unless I use the navbar option.

In the mobile version its working property.

I used this initialization

`        scrollOverflow: true,` 
`         scrollOverflowOptions: {` 
`            scrollbars: true,`
`           mouseWheel: true,`
`           hideScrollbars: true,`
`            fadeScrollbars: true,`
`            disableMouse: true`
`       }`

### Link
http://eltor.mx/#about

### Steps to reproduce it
Go to section (#about) (section with scrollOverflow) and try to scroll to the next section (#services)

### Versions 
[Chrome]

**Comment by meceware** [comment]
It might be about mousewheel. Because sections can be changed via keyboard.

**Comment by jatovar** [comment]
Sorry it was my mistake when I copied the initialization, I used mouseWheel: true.
