### ISSUE TITLE
How to disable switching anchors when current anchor is selected?

### ISSUE THREAD

**Issue by enkhtulga** [alvarotrigo/fullPage.js#2173]
Hello,

I've a option:
1. autoScrolling: false,
2. anchors: ["firstPage", "secondPage", "anchor3"],
3. fitToSection: false

Issue:

When i start scrolling 60% of current "firstPage" section, "secondPage" is coming on the URL.

What i want:

I want to scroll "firstPage" to 100% then "secondPage" is coming on the URL automatically.

Screenshots:
1. #firstPage anchor --> http://d.pr/i/SC6b
2. #secondPage anchor --> http://d.pr/i/14lkv

What I want screenshot:
1. I want to be #firstPage still here --> http://d.pr/i/H2ye not $secondPage anchor.
2. And now to will be $secondPage --> http://d.pr/i/1fIDW

Thank you,
Enkhtulga

**Comment by alvarotrigo** [comment]
I'm afraid that's not an option and it would led to problems when using `fp-auto-height` or `fitToSection:true`.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2209
