### ISSUE TITLE
delay in initial load of background image with fullpage

### ISSUE THREAD

**Issue by bxlxux** [alvarotrigo/fullPage.js#2174]
Hello - first, love the utility of this and much appreciated! I'm sure the issue is more on my implementation than the actual code itself. On initial load of the site the sections are more jumbled at first, but then within a couple seconds the background-image: cover kicks in, and all other sections resize to their appropriate sizes. I've tried putting the fullpage code directly in the index file, the cdn vs. local, but still no luck in eliminating the delay. 

The site is [here](https://gispub.epa.gov/air/trendsreport/2016/)

Can be seen in various browsers, my primary is Chrome. Thanks in advance for taking a look!

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
