### ISSUE TITLE
Angular 2 support

### ISSUE THREAD

**Issue by aamir1995** [alvarotrigo/fullPage.js#2175]
I have a website built with angular 2, After correctly initializing fullpage.js, it is not working and also not giving any errors in console. Do you have any working sample/code snippet with angular 2 ???

**Comment by alvarotrigo** [comment]
See the [resources section](https://github.com/alvarotrigo/fullPage.js#resources) of the docs for angular components and directives.

**Comment by aamir1995** [comment]
Thanks :)
