### ISSUE TITLE
npm package for pure javascript version

### ISSUE THREAD

**Issue by voanhcuoc** [alvarotrigo/fullPage.js#2177]
Is pure javascript version written to better support umd ? So please publish it to npm. Thanks.

**Comment by davejohn** [comment]
Second this, would be great feature!

**Comment by alvarotrigo** [comment]
There are two ways that can be done:

- Creating a new repository for it
- Adding it in the folders that come with the existent fullpage.js npm package

**Comment by alvarotrigo** [comment]
The problem is, it is an Alpha version and will probably contain bugs...

**Comment by peteringram0** [comment]
+1 Would love to see this within NPM.

**Comment by alvarotrigo** [comment]
Now fullpage.js version 3 doesn't require jQuery at all.
You can find it in npm version 3.0.1
