### ISSUE TITLE
Table-responsive's Bootstrap doesn't work on mobile

### ISSUE THREAD

**Issue by dieabra** [alvarotrigo/fullPage.js#2179]
Hi everyone, how are you?

I have an issue with the table-responsive class on mobile. The matter is that i can't scroll on a smartphone.

Anyone knows why i that?

Thanks all

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
