### ISSUE TITLE
Easing value does not change anything

### ISSUE THREAD

**Issue by Le-future** [alvarotrigo/fullPage.js#2181]
Hello Álvaro!

As I said so many times, thanks a lot for this awesome plugin!

Just have a request, I tried to change the easing value in the js core file but whatever the transition chosen like, easeInOutCubic, easeInOutBounce etc... There is no difference when I scroll my page.

What could be the reason in your opinion?

Thanks a lot for any help

**Comment by alvarotrigo** [comment]
You don't need to change anything in the core file.
Just use the options `easing` or `easingcss3` as specified [in the docs](https://github.com/alvarotrigo/fullPage.js#resources).

**Comment by Le-future** [comment]
Alright, thanks for the information ;-)
