### ISSUE TITLE
Mouse dragging sections

### ISSUE THREAD

**Issue by DominikLevitsky** [alvarotrigo/fullPage.js#2182]
Question: can fullPage.js somehow be setup to support mouse dragging for the sections? Like here, for example http://chulakov.com

**Comment by alvarotrigo** [comment]
Not possible at the moment. I'll mark it as a possible enhancement for the future.

**Comment by alvarotrigo** [comment]
This is not possible with the [Drag And Move extension](http://alvarotrigo.com/fullPage/extensions/dragAndMove.html) which also improves the swipe in touch devices.
