### ISSUE TITLE
mozilla firefox getting problem

### ISSUE THREAD

**Issue by suraj-ankola** [alvarotrigo/fullPage.js#2183]
### href="#services/slide3" 
`<a href="#services/slide3" class="waves-effect waves-light btn grey lighten-5"> Continue reading...</a>`
we added above tag button navigate to 3rd (any) slide.this was working fine in safari mozilla and chrome but when i added "scrollOverflow: true," in script at the time scroll overflow function working in all browser but at the same time mozilla not navigating to any slide when i click that button but it is working fine in safari and chrome ]

### Versions 
[mozilla firefox,materialize css]

thank you

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
