### ISSUE TITLE
Css3 with background-attachment:fixed

### ISSUE THREAD

**Issue by gy134340** [alvarotrigo/fullPage.js#2189]
### Link to isolated reproduction with no external CSS / JS
[in jsfiddle.net or codepen.io if possible, link to personal websites won't be reviewed unless isolated reproductions are provided. Reported issues without a reproduction might be closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by gy134340** [comment]
I made lots of effect to add the section with style "background-attachment:fixed" but did not work,finally found that's the  default  attributes "css3:true",Would you like make a hint with this attribute?thanks

**Comment by alvarotrigo** [comment]
That's a bug of some browsers that won't support the css3 property translate3d over fixed elements. It is clearly not a fullpage.js bug. 
See [this answer](http://stackoverflow.com/questions/23571578/chrome-issue-with-background-attachment-fixed-and-position-fixed-elements) in case it helps.

**Comment by gy134340** [comment]
Sorry for that,thanks.
