### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by indieveed** [alvarotrigo/fullPage.js#219]
i've got an error in my console in latest Chrome on Mac

have this html inside the `body`

```
    <div class="section">1</div>
    <div class="section">2</div>
    <div class="section">3</div>
    <div class="section">4</div>
    <div class="section">5</div>
    <div class="section">6</div>
```

and js

```
  $(document).ready(function() {
      $.fn.fullpage();
  });

```

So i got this error 
`Uncaught TypeError: Cannot read property 'top' of undefined 
at jquery.fullPage.js:551`

here is that 551 line
`var dtop = dest !== null ? dest.top : null;`
I suppose we need to add a check for undefined there or just use this `!=` operator, as `undefined != null` is `false`, while `0 != null` is `true`.

This error seems not to affect the plugin behavior, but I don't think that having an uncaught  error is a good idea.

**Comment by maddles** [comment]
Hi @alvarotrigo, I'm seeing this issue again. Same repro, in fullPage 2.8.8

**Comment by alvarotrigo** [comment]
@maddles please provide an isolated reproduction.

**Comment by alvarotrigo** [comment]
@maddles please provide an isolated reproduction.

**Comment by sschueller** [comment]
I have the same issue on Chrome for android:

```
jquery.fullPage.min.js:8 Uncaught TypeError: Cannot read property '0' of undefined
    at Jn (jquery.fullPage.min.js:8)
    at HTMLDivElement.De (jquery.fullPage.min.js:8)
    at HTMLDivElement.dispatch (jquery-latest.min.js:3)
    at HTMLDivElement.i (jquery-latest.min.js:3)
```

**Comment by alvarotrigo** [comment]
@sschueller please provide an isolated reproduction.
