### ISSUE TITLE
Why scrolling is not smooth while having large content in section?

### ISSUE THREAD

**Issue by qadriinfotech** [alvarotrigo/fullPage.js#2191]
Hello,

I implemented fullpage.js on one of my client's website. We have 5 sections of which 4 are images and in the 5th section, we have portfolio, blog, and contact form. This section has large content so we required scrollbar so I added a script for that but it's not working smooth on desktop and iPhone devices as it should.

Can you please check my script and let me know if I did something wrong?
Website URL is: http://demos.flickdevs.com/eskor/

Scroll to 5th section and look and feel the scrollbar transition. Can you please tell me how I make scrolling smooth?

Thank you in advanced :)

**Comment by alvarotrigo** [comment]
Working perfectly for me in Chrome. 

I'll close the issue until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by qadriinfotech** [comment]
Did you checked in iPhone 4s and iPhone 5s with safari browser? Please check and feel the scrolling of the website http://demos.flickdevs.com/eskor/ 

Here is my code: Please don't close this as the issue is with the slider scrolling issue and it's not working for me even I added valid code.

                        var tot_slid = $("#slider .section").length;
			$('#slider').fullpage({
				bigSectionsDestination: 'top',
				scrollOverflow:true,
				scrollOverflowOptions: {
					scrollbars: true,
					mouseWheel: true,
					interactiveScrollbars: true,
					shrinkScrollbars: 'scale',
					fadeScrollbars: true,
					bounceEasing: 'elastic', 
					bounceTime: 1200,
					scrollbars: 'custom',
					useTransform:true,
					useTransition:true,
					HWCompositing:true,
				},
				navigation: true,
				navigationPosition: 'right',
				menu: '#menu',
                sectionsColor: ['#C63D0F', '#1BBC9B', '#7E8F7C'],
				onLeave: function(index, nextIndex, direction){
					var leavingSection = $(this);
					//after leaving section 2
					if(index == (tot_slid-1) && direction =='down'){
						jQuery("#fp-nav").fadeOut("fast");
						jQuery(".arrow-button").fadeOut("fast");
					}
					if(index == tot_slid && direction == 'up'){
						//alert("Going to section 1!");
						jQuery("#fp-nav").fadeIn("fast");
						jQuery(".arrow-button").fadeIn("fast");
					}
				}
			});

**Comment by qadriinfotech** [comment]
I created jsfiddel for you to check the smooth isroll scrolling on large section. Just let me know why the scrollbar on large content is not smooth like iScroll's examples?

http://jsfiddle.net/shaikhaezaz80/ptwvo10p/2/

**Comment by alvarotrigo** [comment]
Your fiddle contains much more than the basics to reproduce the issue.
Please remove any CSS, HTML and Javascript which is not necessary for an isolated reproduction of the issue. 
This is: keep it as simple as possible and add only the necessary to reproduce your issue. 

Then name the version of iOS where you are testing it as well as the browser you are using to do it.
