### ISSUE TITLE
Custom navigation : Two separate and independent columns

### ISSUE THREAD

**Issue by meneldil** [alvarotrigo/fullPage.js#2192]
Hello,

I wanted to know if it was possible natively (or using a trick) to make two separate and independent columns?

I made a drawing to facilitate understanding. :)
The black square represents the screen.

![schema](https://cloud.githubusercontent.com/assets/8545547/17443900/70b36546-5b3d-11e6-8578-19200707d7b0.jpg)

Tell me if this is not clear.

**Comment by meceware** [comment]
I think you can use events for these. For example, if the user goes to the slide on the right, you can add active class to all the slides on the right (and vice versa), so when user goes to the next section, slide on the right of that section will be active. I didn't try this, but it might work.

**Comment by alvarotrigo** [comment]
fullpag.js doesn't provide such option. Feel free to [ask for a customisation](http://alvarotrigo.com/#contact).

**Comment by meneldil** [comment]
Or a good idea for [extensions](http://alvarotrigo.com/fullPage/extensions/). ;)

**Comment by alvarotrigo** [comment]
@meneldil you can already achieve that using the [interlocked slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html)

**Comment by meneldil** [comment]
@alvarotrigo That's what I told myself afterwards.
I'll look at that! :)
