### ISSUE TITLE
Mozilla browser compatibility

### ISSUE THREAD

**Issue by suraj-ankola** [alvarotrigo/fullPage.js#2193]
we added "continue reading" and "back" button, navigate to  slide. this was working fine in safari Mozilla and chrome but when I added "scrollOverflow: true," in a script scroll overflow function working in all browser but at the same time Mozilla not navigating to any slide when I click  "continue reading" and "back" button. 

on more problem in a slide, we added right side menu buttons are one, two, three, four, when I click that button its navigate within a below slide it's fine, but when to scroll up it's not showing all content.

<a href="http://codepen.io/vikram_e22/pen/OXBxgo" target="_blank">problem link</a>

please help me
thank you

**Comment by alvarotrigo** [comment]
> Mozilla not navigating to any slide when I click "continue reading" and "back" button.

The first "continue reading" is working as expected to me in the latest Chrome 52.0.2743.116 m
Other "continue reading" text have links to slides that simply don't exist, which of course won't link you anywhere.



> on more problem in a slide, we added right side menu buttons are one, two, three, four, when I click that button its navigate within a below slide it's fine, but when to scroll up it's not showing all content.

You can not use internal anchors inside a scrollOverflow section. That's actually a [iscroll.js issue](https://github.com/cubiq/iscroll/issues/5) and not a fullpage.js one.

**Comment by suraj-ankola** [comment]
Thanks alvarotrigo. that link works fine in chrome, safari, IE but not in Mozilla firefox 49.0v and I gave only one slide and one "continue reading" link in codepen.io 

please check once again in Mozilla firefox any version

**Comment by alvarotrigo** [comment]
> Mozilla firefox 49.0v

The latest stable version is 48.0. And it works ok in it.
You are using the Firefox developers version which might content bugs.

**Comment by suraj-ankola** [comment]
thanks Álvaro
