### ISSUE TITLE
JavaScript error with pure JavaScript version on mobiles

### ISSUE THREAD

**Issue by SiamKreative** [alvarotrigo/fullPage.js#2194]
### Description
Hi there,

Please check out [my website](https://studio.siamkreative.com/) on mobile using Chrome Developer Tools. You'll notice I use the pure JavaScript version. For some reasons, only on mobiles, the following JS error shows up and scrolling is not working: `Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`

The same issue shows up on the demo: http://alvarotrigo.com/fullPage/pure-javascript/.

I'm aware that the JavaScript version is in a beta, but I'm hoping I can get some help to fix it. If not, is there another library that you would recommend?

### Link to isolated reproduction with no external CSS / JS
https://studio.siamkreative.com/

### Versions 
All modern browsers on Windows 10.

**Comment by alvarotrigo** [comment]
Steps to reproduce it?

I can't see any error in the console in neither [your site](https://studio.siamkreative.com/) or the [demo one](http://alvarotrigo.com/fullPage/pure-javascript/#firstPage).

**Comment by alvarotrigo** [comment]
Steps to reproduce it?

I don't get any error in Windows 10 in Chrome using the [demo site](http://alvarotrigo.com/fullPage/pure-javascript/).

**Comment by alvarotrigo** [comment]
Closed until a way to reproduce it is provided.

**Comment by SiamKreative** [comment]
1. Go to http://alvarotrigo.com/fullPage/pure-javascript/ using Chrome Version 52.0.2743.116 m (64-bit) on Windows 10.
2. Open Chrome Developer Tools and click on "Toggle device toolbar"
3. Choose a mobile device, for instance "iPhone 6 Plus"
4. Reload the page
5. Check out the console and see `javascript.fullPage.js:1914 Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.`

**Comment by alvarotrigo** [comment]
You are not using the latest version of pure javascript fullpage.js.
Use v.0.0.8 (Alpha) 

It seems I forgot to use the latest one in the demo page.

**Comment by SiamKreative** [comment]
Thanks for the quick follow up! I'll update and try.
