### ISSUE TITLE
how to imlement scroll down that triggers scroll sideways

### ISSUE THREAD

**Issue by eddiefangdaqri** [alvarotrigo/fullPage.js#2195]
Hi!

Can fullpage.js implement something like this http://laurenwickware.com/ where scrolling down will trigger scrolling sideways on the right side of the page?  (with possibly different speeds)

Thanks!

Eddie

**Comment by alvarotrigo** [comment]
Define what you mean by "sideways"

**Comment by eddiefangdaqri** [comment]
scrolling sideways :)

**Comment by alvarotrigo** [comment]
The link you posted showed me the wrong website. I had to remove the hash.

**Comment by eddiefangdaqri** [comment]
apologies! edited :)

**Comment by alvarotrigo** [comment]
fullpage.js doesn't provide a way to do it, but you can probably accomplish it using some of the library functions or features.

**Comment by eddiefangdaqri** [comment]
thanks for the reply! :)

**Comment by alvarotrigo** [comment]
This is now possible with the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).
