### ISSUE TITLE
scrollReveal.js in combination of fullpage.js

### ISSUE THREAD

**Issue by grzesiek77** [alvarotrigo/fullPage.js#2196]
I use scrollReveal.js in combination of fullpage.js.
I need that the page scrolls like a fullpage but, show the elements like a scrollreveal when scrolls to another section.
I have scrollBar: true but unfortunately, does not work.
Only first section animated is ok. Preview: http://alexandersevenstones.com/nowy/przewijanie.html
How do I proceed?
Best regards

**Comment by alvarotrigo** [comment]
See the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)

I'll closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
