### ISSUE TITLE
Can't add extra section after a section with bootstrap

### ISSUE THREAD

**Issue by itsRAXO** [alvarotrigo/fullPage.js#2198]
### Description
I have some issues with not displaying a fourth section after a big one
### Link to isolated reproduction with no external CSS / JS
Here is my code of the index.php and main.css. (I am new to coding so correct me anywhere where I am wrong)

http://pastebin.com/in9xq3Jc

### Steps to reproduce it
1. Add a fourth section
2. Add a lot of content in section 3
3. When seeing the page you can't scroll down to the fourth section

### Versions 
2.8.2

**Comment by alvarotrigo** [comment]
You should validate your HTML. There are errors in it causing the problem.
