### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by dmlb** [alvarotrigo/fullPage.js#2201]
### Description
Example links on http://alvarotrigo.com/fullPage/ lead to broken pages.

### Steps to reproduce it
1. Click on example in bottom menu on http://alvarotrigo.com/fullPage/
2. Click on an example link

### Versions 
Chrome Version 52.0.2743.82

![screen shot 2016-08-15 at 1 52 33 pm](https://cloud.githubusercontent.com/assets/4835191/17673590/cac26186-62ef-11e6-99c0-411182cba7ce.png)
![screen shot 2016-08-15 at 1 52 41 pm](https://cloud.githubusercontent.com/assets/4835191/17673591/cac6d1b2-62ef-11e6-935a-f693eecd5d1f.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Solved!
