### ISSUE TITLE
Cannot scroll in IE8

### ISSUE THREAD

**Issue by dongli** [alvarotrigo/fullPage.js#2202]
### Description
Just to test in IE8 for my BOSS, he wants the web page looks the same on IE8! Since I used fullPage, so I opened the homepage of it in IE8, and it looks no good. The page cannot be scrolled.

### Steps to reproduce it
1. Just open `alvarotrigo.com/fullPage/` in IE8.

### Versions 
IE8, Windows 7

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/) works properly in IE 8.
It seems you are doing something wrong.
