### ISSUE TITLE
Bug on mozilla firefox 48

### ISSUE THREAD

**Issue by maliyshock** [alvarotrigo/fullPage.js#2206]
### Description

When u scroll sections on trackpad event that says to "scroll-down" on 2 of 7 sections triggered twisely, so on this sections u have double scroll-down effect, but sometimes it is just no happens

### Link to isolated reproduction with no external CSS / JS
Can`t put link here, the project is still developing

### Steps to reproduce it
So  we have 3 full scroll pages 2 of them with 4 sections, and one with 7. This issue happens only on ff only on mac and only on page with 7 sections.
Also i noticed, that if i decrise time transition from 700 to 500 , this issue happens on other pages to

### Versions 
Mac os El capitan, mozila ff 48

**Comment by alvarotrigo** [comment]
That's just the mouse inertia caused by a fast scrolling on your trackpad. 
Keep the scrollingSpeed option in 700 to avoid problems. Or even higher. Don't go lower as it won't be safe against fast kinetic scrollings.
