### ISSUE TITLE
IE is scrolling to next section when scrolling inside <select>

### ISSUE THREAD

**Issue by timgaines** [alvarotrigo/fullPage.js#2208]
### Description
When having to scroll through the options of a `<select>` tag, IE is scrolling to the next section.

I have tried adding:

```
startScroll() {
  $.fn.fullpage.reBuild();
  $.fn.fullpage.setAutoScrolling(true);
}

stopScroll() {
  $.fn.fullpage.setAutoScrolling(false);
}
```

to the onFocus and onBlur events but it makes clicking on the forms in other sections on my personal project hide all content in the slide.

### Link to isolated reproduction with no external CSS / JS
http://codepen.io/timdoes/full/GqZXRB/

### Steps to reproduce it
1. Click the select field to view options.
2. Scroll to view bottom options
3. Fullpage.js moves to Section 2

### Versions 
PC, Windows 7, IE 11.0.9600.18426

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1473
