### ISSUE TITLE
Scroll overflow do not work

### ISSUE THREAD

**Issue by wfabian** [alvarotrigo/fullPage.js#2210]
Hi,
i have a long section/slide on my page.
On mobile devices there have to be a scroll, but the scroll is not created correctly.

Example:
My div with content is 1333px high.
My window is just 773px high.

Container "fp-fp-scrollable" and "fp-scroller" are created automatically.
But I'm not able to scroll.
Both are 773px high.

scrolloverflow.min.js was included before fullPage.js.

On large devices i'm using position:absolute.
On small devices i change it to position:inherit.

Could that be a problem?
Can anyone help?

**Comment by wfabian** [comment]
In plug-in "scrollOverflow" was set to true.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by wfabian** [comment]
Tried to reproduce in jsfiddle.
Everything worked fine.

After that I found the problem myself.
Everything seems to be working :-)
