### ISSUE TITLE
Use scrollreveal js in a big section

### ISSUE THREAD

**Issue by alizeear** [alvarotrigo/fullPage.js#2211]
Hello !

I created one full page with your plugin and it's works very good. 
I used 2 basics full pages section and one big section with this code : 
```
$('.fullpage').fullpage({
		anchors: ['section1', 'section2', 'section3'],
		paddingBottom: '24px',
		paddingTop: '24px',
		scrollbar: true,
		scrollOverflow: true,
		slideSelector: '.slidefullpage',
		scrollOverflowOptions: {
			scrollbars: true,
	                mouseWheel: true,
	                hideScrollbars: false,
	                fadeScrollbars: false,
	                disableMouse: true
		},
        afterRender: function(){
    	    /* scroll reveal js */
		    window.sr = ScrollReveal();
		    sr.reveal('.content-bloc');
		    sr.reveal('.slider');
        }
	});
```
Can you help me to use ScrollReveal.js in my third big section ? Because i saw your previous posts and i have added scrollbar: true and the declaration of ScrollReveal in afterRender() but it don't work...

The elements I want to animate stay with opacity 0, the scroll is not detected, probably because of the fake scroll to the section but i have no solution !

Thanks ! 

Alizée

**Comment by alvarotrigo** [comment]
I guess you are talking about using scrollReveal on a section using scrollOverfow? 
In that case I can only recommend you to check the [iScroll.js docs](http://iscrolljs.com/#custom-events).

You might have to change the scrolloverflow.js file for scroll-probe.js and [modify it in the same way I did with iScroll.js to fix the problem in IE](https://github.com/cubiq/iscroll/issues/1041)
