### ISSUE TITLE
Problem with sections. Help Please.

### ISSUE THREAD

**Issue by UsamaHameed** [alvarotrigo/fullPage.js#2212]
### Description
I am trying to make my portfolio page. The problem I am having is that I have defined the anchors as <code>anchors:['section1', 'section2', 'section3,'section4']</code> but the scroll jumps directly from the section1 to the section3.
### Link to isolated reproduction with no external CSS / JS
http://usamahameed.github.io/
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Versions 

Using Chrome on WIn 10

**Comment by alvarotrigo** [comment]
See the [fullpage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) and check the javascript console.
It seems you are doing something wrong.
