### ISSUE TITLE
One section skipped

### ISSUE THREAD

**Issue by UsamaHameed** [alvarotrigo/fullPage.js#2213]
Description

I am trying to make my portfolio page. The problem I am having is that I have defined the anchors as anchors:['section1', 'section2', 'section3,'section4'] but the scroll jumps directly from the section1 to the section3.

Link to isolated reproduction with no external CSS / JS

http://usamahameed.github.io/
You told me to look at the docs. I had a look.  None of my classes or ids is named section1, section2, section3 or section4. 
````
<script type="text/javascript">
$('#fullpage').fullpage({
        anchors:['section1', 'section2', 'section3', 'section4'],
        menu: '.nav',
        css3: true
    });
</script>
````
Versions

Using Chrome on Win 10

**Comment by alvarotrigo** [comment]
Duplicated of #2212

Your reproduction is far from being isolated. Remove any external CSS orJS from yoru site and remove any unnecessary HTML elements and texts.

**Comment by dideriksn** [comment]
I had the same issue. However I found out that the solution you answered here: https://github.com/alvarotrigo/fullPage.js/issues/72  - worked.
If data-menuanchor and the anchor are the same - it skips a section.

**Comment by dideriksn** [comment]
This was an issue for me too - until I made sure that sections/slides did not have the same ID as an anchor - and that I had declared the anchor tags in options.
