### ISSUE TITLE
slide easing

### ISSUE THREAD

**Issue by milka1701** [alvarotrigo/fullPage.js#2215]
Is it possible  to set easing for slides?

**Comment by alvarotrigo** [comment]
I don't understand your question. 

If you mean, using easing for sections and slides, you can use the options  `easing` or `easingcss3`.

If you want to change the scrolling speed for only hoizontal slides, the answer is no. See https://github.com/alvarotrigo/fullPage.js/issues/1068

**Comment by milka1701** [comment]
I want to make transition beetwen slide longer,cause now it's just a 10-20 ms.So to make my question clearer ,can I make that transition longer?

**Comment by alvarotrigo** [comment]
Use the `scrollingSpeed` option as detailed in the docs.

**Comment by milka1701** [comment]
I did it a minute ago,without using scrolling speed.I added a transition-duration to some class(I forgot the class).If you want I can send you the class tommorow in case somebody else asks the same question.

**Comment by alvarotrigo** [comment]
No thanks. 
If you believe it is a bug in fullpage.js, provide a reproduction.
Otherwise I'll just point you to the docs.

**Comment by milka1701** [comment]
Can I ask you a qestion here,or I need to write it in issue section?

**Comment by alvarotrigo** [comment]
You can do it here. But a reproduction in jsfiddle or codepen will be required for further review.

**Comment by milka1701** [comment]
I think that you've done awesome job with fullpage.js just one thing looks bad to me.I set scrollingSpeed to 650 and it's perfect when I'm going one section up or down,but when I click in menu to go to some section which is 2 or 3 sections away it's to fast.Is there a way to make scrollingSpeed greater if distance between section a section to which window needs to scroll is greater.

Something like if( index==1 ){
$(".button-for-section-3").click(function (){
$.fn.fullpage.setScrollingSpeed(1300)
})
}


There is one website which also have sections like fullpage.js and can do what I want but their code is too complicated.On their website section buttons are circles on right side   http://atieva.com

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such option.

Feel free to do it yourself by using `$.fn.fullpage.setScrollingSpeed` inside callbacks or in your own events.

**Comment by milka1701** [comment]
Hah,everytime I ask you I solve problem in 5-10 minutes,this feature is really nice thing to have and the transition between sections looks much better and smoother,definitely thing to add in some of next versions,I did it with a relly simple and short code,and I'm sure you can do it much much better than me.Thanks again and here's how I did it.
