### ISSUE TITLE
Section cut off on mobile and problem with other plugin

### ISSUE THREAD

**Issue by cindyvriend** [alvarotrigo/fullPage.js#2216]
### Description
Love the plugin it's absolutely fab!
I got two problems:

1. . I'm really a js noob... There's a problem with the loading of an other plugin I use: MasterSlider Pro.. I get: Uncaught TypeError: Cannot read property 'call' of undefined
I understand I have to do something with after render to load the plugin or it's js files? But how do I do that I already got:

`<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage({
autoScrolling: false,
anchors: ['home', 'project1', 'project2', 'project3', 'project4', 'project5', 'project6', 'project7', 'project8', 'project9', 'project10', 'project11', 'project12', 'project13', 'project14', 'project15']
		});
		});
	</script>`
2. On mobile and tablet when I scroll, the sections get cut off at the top, so basically they scroll up too much. Is this something I can fix with a setting in fullpage.js or is it related to something else like CSS (which in that case you don't need to answer of course...

this is the link to the preview of the site: http://tomesen.archi/wordpress/

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
I'm afraid this forum's purpose is only to treat fullpage.js issues. Not external problems to it.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
