### ISSUE TITLE
Flexbox compatibility question

### ISSUE THREAD

**Issue by KayJay89** [alvarotrigo/fullPage.js#2218]
Hi all,

First of all, wonderful plugin been having lots of fun with it.

However I do want to ask a question which might or might not be a bit silly, as I am relatively new to javascript plugins. I can't seem to find a question about it so here goes:

Is Flexbox incompatible with this plugin? It would appear as if my entire layout in set in CSS is being disregarded, as of the moment I incorporate the plugin in my project.

**Comment by alvarotrigo** [comment]
Flexbox is just a CSS technique. 
You can apply it inside seach section or slide as you wish. The only thing fullpage.js does is creating the sections and slides height and width or centering it if you use `verticalCentered:true`

**Comment by shezankazi** [comment]
I also have this problem to be honest. Flexbox layouting is somehow disturbed..

**Comment by alvarotrigo** [comment]
@shezankazi you'd better ask in other place such as stackoverflow.com to know more about how to solve it. 
It shouldn't be related with fullpage.js at all.

**Comment by kwiat1990** [comment]
My layout was disturbed by this plugin too. What has helped me, was to change the value of `verticalCentered` to `false`.

**Comment by Dan-Traian** [comment]
This has fixed the problem in my case as well. Thanks for the info :)

**Comment by atrimn** [comment]
Hey guys just go one level down. If fullpage is targeting section #s1 put a display flex div inside of it

**Comment by AdelinaLipsa** [comment]
@kwiat1990 I've spent 2 hours trying to figure it out. Your solution worked for me too. Thank you :)
