### ISSUE TITLE
Background image (and colors) for sections in HTML

### ISSUE THREAD

**Issue by DriftingSteps** [alvarotrigo/fullPage.js#2219]
Great plugin, alavarotrigo.

Is it possible to add image links (and colors) right on a section's HTML instead of using the `style="background: url();"` attribute, preferably via `data-src=""` or something similar?
This feature would give programmers a lot of ease along with being cleaner compared to the `style=""` attribute.

Thanks.

**Comment by alvarotrigo** [comment]
Background images can only be added with CSS. With inline or external styles. This is not a fullpage.js restriction but how background images work anywhere. 

Same for colors.

You can always use whatever attribute you want and process it with javascript to assignt it as a style. But that's not something fullpage.js will deal with.
