### ISSUE TITLE
Disable Scrolling on Page Load

### ISSUE THREAD

**Issue by gavsim** [alvarotrigo/fullPage.js#222]
Hi,

We are using this plugin, it's great! One of the requirements our customer has is to not scroll down to the initial section / slide on page load, so it would just "jump" straight to that section/slide and scroll as normal when they continued navigating.. 

@alvarotrigo do you have any suggestions on how we might tackle this? I can see where the call to scrollToAnchor() is being made on page load, is there an option to disable the scrolling animation temporary perhaps? Any help is greatly appreciated.

**Comment by jayanthbabu3** [comment]
Hai Alvaro, Iam using video in first section, I would like to disable the user to move to other sections from first section until the page completely loads(i mean until the video also load)

**Comment by jayanthbabu3** [comment]
can u help me please
