### ISSUE TITLE
Want to Call onLeave Function after calling moveTo

### ISSUE THREAD

**Issue by priyankamotiani** [alvarotrigo/fullPage.js#2222]
### Description
Hi,

I am developing a page having full height sections and in which different kind of animation occurs and it is interdependent and i have written my code in onLeave function. Now if i am scrolling the page normally i.e one after other section then it is working fine but when i am using anchors to move from one section to other, i want to call onLeave Function for each and every section which comes in between my current section and my destination section. So that animation occurs for each and every section rather then just trigger onLeave function for destination section.

Here is the Example 

In this [example ](http://codepen.io/PriyankaM/pen/NAVzwx)- there is a string in LHS which inputs the index of section. Over here i want to index of each and every section that comes in between if move from Section 1 to Section 5 rather than just showing 1-2 index

**Comment by alvarotrigo** [comment]
You can accomplish it in this way:

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    scrollOverflow:true,
    navigation: true,
    onLeave: function(index, nextIndex, direction){
		for(var i = index; i < nextIndex; i++){
        	myOnLeave(i, nextIndex, direction);
        }
    },
});

function myOnLeave(index, nextIndex, direction){
	console.log("leaving..." + index);
    
	if(index ===1){
    	//whatever
    }
    else if(index === 2){
     	//whatever
    }
}
```

[Example online](http://jsfiddle.net/97tbk/1401/)
