### ISSUE TITLE
Scroll to First Section on Last Section

### ISSUE THREAD

**Issue by patriziavergassola** [alvarotrigo/fullPage.js#2223]
Hello,

I have a problem: when I reach the last section I want the user to click on the arrow and go back to the first section, not the previous one.
I tried everything, but with this code:

function tornaSU(section_number, index) {
			if(index==section_number){
            $j.fn.fullpage.moveTo(1);
			}
			else $j.fn.fullpage.moveSectionUp();
			alert($j('div.vc_row').hasClass('active'));
            return false
        }

$j('#up_fs_button').on('click', tornaSU);

index is undefined.
Anyone can help me???

Thank you in advance,
Patrizia

**Comment by alvarotrigo** [comment]
Use 
```javascript
$.fn.fullpage.moveTo(1);
```

Not `$j.fn.fullpage.moveTo(1);` that is what you are using.
