### ISSUE TITLE
Whites space browser size 

### ISSUE THREAD

**Issue by ulyssedoris** [alvarotrigo/fullPage.js#2226]
### Description

I am trying ti figure out how to remove the white spaces between the images 

When the browser is resized to lets say a mobile device or used on a tablet horizontally you can see spaces between the images.Its the element.style that is 803px . tried changing the height with customized css and that was not the solution 

This is while using fullpage.js on joomla> Gantry5> hydrogen template
![screen shot 2016-08-25 at 8 18 23 am](https://cloud.githubusercontent.com/assets/13663636/17968771/a3b86680-6a9c-11e6-8a49-edec5aa961d3.png)
![screen shot 2016-08-25 at 8 18 57 am](https://cloud.githubusercontent.com/assets/13663636/17968776/aa457eb6-6a9c-11e6-89b5-cfb5c8a8b9bd.png)
![screen shot 2016-08-25 at 8 23 50 am 2](https://cloud.githubusercontent.com/assets/13663636/17968891/4e35f8e8-6a9d-11e6-83f0-36335027e8b2.png)

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Nothing to do with fullpagej.s. That's a matter of CSS knowledge. 
You'd better ask in other places such as http://stackoverflow.com/

**Comment by ulyssedoris** [comment]
Ok thank you for pointing me in the right direction. I love this plugin keep it up !
