### ISSUE TITLE
Latest version on Safari with magic maouse and trackpad on Mac

### ISSUE THREAD

**Issue by EddieVersoAndrea** [alvarotrigo/fullPage.js#2227]
Hi,
I noticed that with Safari and magic mouse you have to scroll using 2 fingers. With a normal
mouse the wheel works fine. With the trackpad you can'scroll neither with two fingers.

I have no isolated reproduction, the website is www.dennisfoggia.com

It happens with ALL versions of Safari on Osx.

**Comment by alvarotrigo** [comment]
> With the trackpad you can'scroll neither with two fingers.

The [demo page](http://alvarotrigo.com/fullPage/) works as expected scrolling with a Mac trackpad. (or any other kind)

> I noticed that with Safari and magic mouse you have to scroll using 2 fingers.

Is this relevant for the question ? Why do you mention the magic mouse ?

**Comment by EddieVersoAndrea** [comment]
Hi, thank you for the quick answer.
I mean the scrolling within a slide. The site you see is only one section with horizontal slides.
I'm using scrollOverflow: true:

`scrollOverflow: true,
            scrollingSpeed: 700,
            touchSensitivity: 5,
            menu: '#menu',
            css3: false,
            easing: 'easeInOutSine',
            fixedElements: '#bottom_bar, #footer',
            normalScrollElements: '.innersection',
            autoScrolling: true,
            responsiveHeight:20000,
            keyboardScrolling: true,
            normalScrollElementTouchThreshold: 5,
            
            scrollOverflowOptions: {
				scrollbars: true,
			    mouseWheel: true,
			    hideScrollbars: false,
			    fadeScrollbars: false
            }`

In every slide there's a normalScrollElement (.innersection).

I mentioned the magic mouse because safari has many mouse functionality with the last osx update.
So I have to scroll with to fingers with it (it's so weird) but if I plug a normal mouse the wheel works fine. Maybe it's a issue due to the translateY property (css3) that in your library replaced the normal scroll event.

I hope my explanation is enough for you.

Thank you again

**Comment by alvarotrigo** [comment]
What is exactly what you can't do with the trackpad? 
Scroll inside the slide to see the overflowed text or scroll to another slide?

I believe the [scrolling example page](http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage) works as expected with the trackpad.
Let me know if the demo page works well for you.

**Comment by alvarotrigo** [comment]
I've tested it on Safari in Mac and I can see the problem in your website.
Unfortunately I'll have to close the topic until an isolated reproduction is provided for further investigation. 

The [scrolling example page](http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage) works as expected in Safari in Mac.

**Comment by EddieVersoAndrea** [comment]
How can I give you a reproduction?
The structure works with php/wordpress so I can't give you a reproduction?

Maybe I could duplicate the website giving you a static html... give me a couple of days.
Thank you for the great support!

**Comment by alvarotrigo** [comment]
You need to isolate the problem to the very basics of it removing any secondary and unnecessary elements. Ideally in jsfiddle or codepen. 
No external CSS or JS to start with. 
Remove your real elements and replace them for simple texts or empty divs. Remove any images. Remove any unnecessary classes.
