### ISSUE TITLE
Option to disable horizontal slide on small screens

### ISSUE THREAD

**Issue by pedroroccon** [alvarotrigo/fullPage.js#2228]
Hello people!

There is an way to disable the horizontal scrolling when we are with small screens?
Check this URL [http://alvarotrigo.com/fullPage/examples/responsive.html#firstPage](at the FullPage.JS demo page). The second page has a horizontal slide. If I resize my window the slide keeps working. I want to know if there is some way to put all those horizontal sections of the slides one above of the other, without making a horizontal scroll. Someone know is a way?

Thank you!

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1919

Short answer. Nop. The issue still open marked as an enhancement.

**Comment by pedroroccon** [comment]
Thanks for the asnwer! @alvarotrigo

**Comment by alvarotrigo** [comment]
This is possible now with the [new fullpage.js extension Responsive Slides](http://alvarotrigo.com/fullPage/extensions/responsiveSlides.html) and the option `responsiveSlides`.
