### ISSUE TITLE
Cursor over Youtube Iframe disable scroll

### ISSUE THREAD

**Issue by mmalikov** [alvarotrigo/fullPage.js#2229]
### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/q884Lv0a/

### Steps to reproduce it
1. Scroll to the third section
2. Put the mouse cursor over youtube iframe
3. Try to scroll

### Versions
OS X El Captain 10.11.5
 - Chrome  52.0.2743.116 (64-bit)
 - Firefox 48.0

iOS 9.3.4
 - Safari

**Comment by alvarotrigo** [comment]
Sounds like [a bug of the browsers](https://bugzilla.mozilla.org/show_bug.cgi?id=1084121) which doesn't propagate the scroll event inside iframes.
More info in [this question](http://stackoverflow.com/questions/31418920/vimeo-iframe-stealing-mouse-wheel-event-on-firefox) too.

**Comment by 4z5lz** [comment]
@alvarotrigo 
Btw, in your example http://jsfiddle.net/q884Lv0a/3/ I can scroll the window

**Comment by alvarotrigo** [comment]
@4z5lz of course you can. But you can't get the mouse wheel event as you can see in the Javascript console. Which is the problem here.

**Comment by qwik3r** [comment]
Soooo no solution on this?

**Comment by amityweb** [comment]
Anyone have a solution to this? I initially got excited by putting a transparent element over the top of the video, then scroll works, but buttons do not work underneath. So i then added pointe-events: none to the transparent layer, so clicking play button works, but that stops scroll again.

**Comment by alvarotrigo** [comment]
> but buttons do not work underneath.

Use the youtube API. Bind a click event to the transparent one so when you click on it, it starts playing the video and removes the transparent element.
When stopping it, add the transparent element.

**Comment by amityweb** [comment]
I am using Smart Slider 3 to insert sliders and have inserted a video as a background video using that. I may be able to link buttons to events in it, but to be honest I dont have the time, so I have had to resort to a YouTube pop up in a lightbox due to not being able to scroll over a background one, which is a real shame.

**Comment by VictorChen** [comment]
Hi, I have the same problem. Is there a workaround if I can control the content of the iframe?

**Comment by webdevyaros** [comment]
Try my solution: https://jsfiddle.net/th0LxLbv/2/ - seems it works.

**Comment by alvarotrigo** [comment]
@webdevyaros it does not work in fullPage.js? See this http://jsfiddle.net/q884Lv0a/26/

**Comment by JohnConstantin** [comment]
Hi guys, 
what you think about: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe,
https://www.w3schools.com/tags/att_iframe_scrolling.asp, 
`The <iframe> scrolling attribute is not supported in HTML5. Use CSS instead.`,
`scrolling`,
`
iframe {
    scrolling:yes;
}
`
I know by dev.mozilla, `Deprecated. Not for use in new websites.`.
