### ISSUE TITLE
onLeave and afterLoad functions parallel?

### ISSUE THREAD

**Issue by karzol73** [alvarotrigo/fullPage.js#2230]
I would like to customize the awesome fullpage.js plugin on my website. It is not clear for me, however, if it is possible to use onLeave and afterLoad functions parallel or not. Thank you!

I use the following code but it does not work. Am I wrong anything?

```javascript
$(document).ready(function(){
    $('#fullpage').fullpage({
        afterLoad: function(anchorLink, index){
                //do something
        }
        onLeave: function(index, nextIndex, direction){
                //do something
        }
     });
});
```
Thank you for your help!

**Comment by alvarotrigo** [comment]
You can see the order in which they are being executed in [the callbacks example online](http://alvarotrigo.com/fullPage/examples/callbacks.html). 

And as stated in the docs.

> afterLoad: Callback fired once the sections have been loaded, after the scrolling has ended. Parameters:

> onLeave: This callback is fired once the user leaves a section, in the transition to the new section. Returning false will cancel the move before it takes place.

**Comment by karzol73** [comment]
Thank you!
