### ISSUE TITLE
Navigating on sections

### ISSUE THREAD

**Issue by DavidGC** [alvarotrigo/fullPage.js#2231]
So im working on [this website](http://costa.io/proyectos/probastypicalofficemobil/) using ur fullPage.js (Im not very good at js), and I have a random number of sections.

My issue is that i dont know how to edit the scroll, so it goes through all of the sections.

It works if i got 5 sections but stops working on more than 5.

Probably im doing so much mistakes...

Thanks anyway for your work!

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by DavidGC** [comment]
Dont worry i got no clue how to explain, sorry for my bad post.

Thanks
