### ISSUE TITLE
Responsive Padding Top and Bottom - Height Doesn't AutoCalculate

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#2232]
Hi Alvaro,

When setting padding top and bottom options of fullpage, everything works great, but sometimes fixed headers have responsive heights. When setting padding top of sections with CSS, section height is autocalculated by the browser since it's padding and box sizing is set, but the inner table height isn't autocalculated and remains the same as full height, (instead of full height - padding top). Since then, vertical align middle doesn't work as expected. 

You can see the problem here:
http://codepen.io/anon/pen/qaWRpJ

As you can see on the codepen, even though the browser is sized under 960px, the text "ONE" doesn't move up as expected. 

Is there a way to autocalculate inner table height according to CSS?

I might suggest two options here, first one is adding a new responsive padding option, the second one is changing the **getTableHeight** function return value for inner heights. 

Thank you for your help,

**Comment by alvarotrigo** [comment]
Just use CSS to set your own padding top:

```css
.section{
     padding-top: 50px;
}``

This way you have the freedom to do whatever you want with it. 
Fullpage.js only provides the paddingTop option for basic users.

**Comment by meceware** [comment]
Yes, even if I add the padding top CSS, inner table height doesn't change and vertical align middle of inner table shifts down. 

Let me give you an example. I updated the codepen a little with the true paddings.
http://codepen.io/anon/pen/qaWRpJ

As you see, the content is in the middle vertically,

![image](https://cloud.githubusercontent.com/assets/16402717/18101894/31c944de-6ef9-11e6-9804-b2b05b977bf4.png)

Now, remove paddingTop option of fullpage, and try again, as given in this codepen. (everything is the same but paddingTop option of fullpage is removed.)
http://codepen.io/anon/pen/ORLjgm

Even though the content is in the middle, since the inner table height is full screen, the content is shifted.

![image](https://cloud.githubusercontent.com/assets/16402717/18102003/a8ee059a-6ef9-11e6-9fcc-2b160371434b.png)

This happens because of "fp-tableCell" div height is full screen, instead paddings should be subtracted from the height. It is calculated in getTableHeight function, which only considers the paddingTop and paddingBottom options only, instead of the CSS.

**Comment by alvarotrigo** [comment]
See the last comment in this topic: https://github.com/alvarotrigo/fullPage.js/issues/1319

Use a wrapper for your content.

**Comment by meceware** [comment]
Anyway, it was just a mere suggestion to remove dependency from height calculation.

Thank you,

**Comment by alvarotrigo** [comment]
> it was just a mere suggestion to remove dependency from height calculation.

It is a topic that was treated in the past. If I remember correctly it was something necessary for IE 8 or Opera 12 when dealing with scrolloverflow:true. Not sure about now.

Something to check in the future anyways.

**Comment by alvarotrigo** [comment]
> It is a topic that was treated in the past. If I remember correctly it was something necessary for IE 8 or Opera 12 when dealing with scrolloverflow:true. Not sure about now.

I found it. 
Its related with `verticalCentered` and Firefox and IE:
http://stackoverflow.com/questions/19428121/height100-inside-table-cell-not-working-on-firefox-and-ie

**Comment by Jishnuparakkat** [comment]
i want to give padding only for first section in fullpage Js,
What i have to do @alvarotrigo

**Comment by alvarotrigo** [comment]
@Jishnuparakkat you'd better ask somewhere else such as stackoverflow.com. That's more of a CSS knowledge question.
