### ISSUE TITLE
sequence of events

### ISSUE THREAD

**Issue by maliyshock** [alvarotrigo/fullPage.js#2234]
### Description
I working on web aplication, and we have mobile version of it. So we use ur library and we have sections that have full screen size. In mobile devices with landscape orientation we can`t use full screen size of sections, cause of small height - our content does not fit. So for landscapes we decide switch off autoscroll between sections with $.fn.fullpage.setAutoScrolling(false); and set height to sections the same as portrait orientation, so our content fit well.

So we look at event orientationchange, and when is triggered, we check this is landscape or not?
When it become landscape, we remember the hash. And afterResize event (this is full page js event)  we change height of sections and go to section with hash that we have remembered earlier.

On android devices - is all right.

The problems come true in Ios devises, like iPhone 6s. The event afterResize is triggered earlier then orientationchange event. And this is crazy, cause orientationchange must trigger 
instantly when we change the device orientation. And afterResize must trigger, when the ful page js done resizing (This callback is fired after resizing the browser's window. Just after the sections are resized.)

I made workaround of that problem by setting the timeout in afterResize callback function. Also i create new variable for landscape mobile hash, that can`t be change when the section is not correct. That var get value only when we  change orientation on our mobile device.

### Link to isolated reproduction with no external CSS / JS
[script.js.tar.gz](https://github.com/alvarotrigo/fullPage.js/files/445369/script.js.tar.gz)

### Steps to reproduce it
1. [First step] - take ios device, like iPhone 6s
2. [Second step] - turn to landscape
3. [and then...] - u go to the dark screen or to the first slide, cause events goes wrong.

Also we have swiper slider on our page, but i don`t think that it give any matter.

### Versions 
iPhone 6s

**Comment by alvarotrigo** [comment]
Why not use the `responsiveHeight` option ?

**Comment by maliyshock** [comment]
Because it just stop autoscrolling. The problem is that content does not fit to the sections on mobile devices in landscape orientation. Fullpage forcibly change height sections to device height.
So we we needed to change that.

**Comment by alvarotrigo** [comment]
> Because it just stop autoscrolling.

I'm lost. You just said you want to turn it off on landscape:

>   So for landscapes we decide switch off autoscroll between sections with $.fn.fullpage.setAutoScrolling(false);

**Comment by alvarotrigo** [comment]
So, my suggested solution is:

- Use the `responsiveHeight` option.
- Use the class `fp-auto-height-responsive` for those sections. Read more about it in the docs.

**Comment by maliyshock** [comment]
Sorry i`ve misspoked

> You just said you want to turn it off on landscape:

 yes 

> and set height to sections the same as portrait orientation, so our content fit well.

So we could save our portrait height of sections on landscape orienttation

Ok. Thank u. I will try.
