### ISSUE TITLE
fp-noscroll still adds scroll to element when fp-responsive

### ISSUE THREAD

**Issue by Bondra** [alvarotrigo/fullPage.js#2236]
Hi!

I've responsiveWidth:1100px and scrollOverflow:true. When reaching 1000px and below fp-noscroll doesn't seem to have any effect. A scroller is still being created.

Is this a bug or have I just missed a setting? 
`  // Fullpage scroll
        $('.page-scroll').fullpage({
            //Navigation
            menu: '#menu',
            lockAnchors: false,
            anchors:['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'fifthPage', 'sixthPage', 'seventhPage', 'eighthPage', 'ninethPage', 'tenthPage', 'eleventhPage', 'twelfthPage', 'thirteenthPage', 'fourteenthPage', 'fifteenthPage', 'sixteenthPage', 'seventeenthPage', 'eighteenthPage','nineteenthPage','tweentyPage'],
            navigation: false,
            navigationPosition: 'right',
            navigationTooltips: ['firstSlide', 'secondSlide'],
            showActiveTooltip: false,
            slidesNavigation: true,
            slidesNavPosition: 'bottom',

            //Scrolling
            css3: true,
            scrollingSpeed: 500,
            autoScrolling: true,
            fitToSection: true,
            fitToSectionDelay: 500,
            scrollBar: false,

            easing: 'easeInOutCubic',
            easingcss3: 'ease',
            loopBottom: false,
            loopTop: false,
            loopHorizontal: false,
            continuousVertical: false,
            scrollOverflow: true,
            scrollOverflowOptions: {
                scrollbars: true,
                mouseWheel: true,
                hideScrollbars: false,
                fadeScrollbars: true,
                disableMouse: false
            },
            touchSensitivity: 15,
            normalScrollElementTouchThreshold: 5,

            //Accessibility
            keyboardScrolling: true,
            animateAnchor: false,
            recordHistory: true,

            //Design
            controlArrows: true,
            verticalCentered: true,
            responsiveWidth: 1100,
            responsiveHeight: 800,

            //Custom selectors
            sectionSelector: '.section',
            slideSelector: '.slide',

        });`

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Bondra** [comment]
I'll reproduce it using fiddle. I found out what the problem is. Content wrapped with .slide.

Btw a quick wondering. Is there any built in parameteer to set fp-noscroll responsively? Say I want it to kick in at 600px?
