### ISSUE TITLE
Scrolling top on page load, sets the last section active and changes the url.

### ISSUE THREAD

**Issue by sabrinaorban** [alvarotrigo/fullPage.js#2237]
### Description
This is my fullpage.js initialisation:
$('#fullpage').fullpage({
        menu: '#sideMenu',
        responsiveHeight: 700,
        responsiveWidth: 980,
        normalScrollElements: '.social-feed, .main-nav.visible',
        loopTop: false,
        loopBottom: false,
        continuousVertical: false,
        onLeave: function(index, nextIndex, direction) {
            if ($(window).width() > 980 && $(window).height() > 700) {
                $('#socialFeed:not(.visible) #feedBtn').fadeOut(100);
                $('header').fadeOut(100);
            }
        },
        afterLoad: function(anchorLink, index){
            if ($(window).width() > 980 && $(window).height() > 700) {
                $('header').fadeIn(500);
                $('#socialFeed:not(.visible) #feedBtn').fadeIn(500);
            }
        }
    });

On homepage, for example, If you resize the window under 980px width, and refresh the homepage, and scroll to top the remaining pixels, the last section, which is footer, will be set to 'active' and the url will change to: http://www.newhaircut.com/#footer

### Link to isolated reproduction with no external CSS / JS
http://www.newhaircut.com/

### Steps to reproduce it
1. Go on http://www.newhaircut.com/
2. Resize the window to have less than 980px width
3. Scroll to next section so the url changes to: http://www.newhaircut.com/#services
4. Scroll back to top, see that after it changes to http://www.newhaircut.com/#hero (which is the first section), you can scroll top about 20 more px, and the url changes to the last section: http://www.newhaircut.com/#footer

**Comment by alvarotrigo** [comment]
See your javascript console. You have an error there:

> fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!showError @ jquery.fullPage.js:2841

Solve it and probably your problem will get solved.

**Comment by sabrinaorban** [comment]
Hello, I removed the other initialisation of the plugin, the problem still persists. Any other ideas? Thank you!

**Comment by alvarotrigo** [comment]
I still get the error in the link you provided.

**Comment by sabrinaorban** [comment]
That is the live url, where at the moment it needs both initialisations to
work the way it was requested. I removed the other initialisation on my
local machine, and I tested, still had the same problem. Tomorrow, when
I'll be back in office, I'll deploy the site with one initialisation on the
qa server and I will send you the link to test it.
Thanks!

Have a great evening!

**Comment by sabrinaorban** [comment]
http://www.newhaircut.com/
You can test now
Thank you!

**Comment by alvarotrigo** [comment]
You still have errors in the console. Please clean them all.

**Comment by alvarotrigo** [comment]
@sabrinaorban as detailed in the docs, make sure you use the compulsory DOCTYPE at the very start of your document: `<!DOCTYPE html>`

> Start your HTML document with the compulsory HTML DOCTYPE declaration on the 1st line of your HTML code. You might have troubles with sections heights otherwise. The examples provided use HTML 5 doctype <!DOCTYPE html>.
