### ISSUE TITLE
Section taller than viewport and normally scrolled

### ISSUE THREAD

**Issue by pdechery** [alvarotrigo/fullPage.js#2238]
Hi,

What I have is not an issue but a question. I hope the author answers it even if it's not formatted in the proper Issue way (sorry about that!). Here it goes:
 
Is it possible to have a section: 1) taller than the viewport and 2) normally scrolled (and I don't mean with a scrollbar, just without the 'fast' scroll)?

I'm working in [this](http://dapp.cloud.fgv.br/validar/observatorio-do-rio/) prototype, which will soon become a project. I wish I could use fullPage.js in it since I've already used the plugin many other times and I'm a big fan of it.

The problem is, in any of the examples and Issues found here I'd found a situation like this one. So I'm asking myself it fullPage.js is the right choice for this project. (currently the scrolling effect is done with other plugin).

Thanks a lot,

Pierre

**Comment by alvarotrigo** [comment]
> Is it possible to have a section: 1) taller than the viewport and

Yeah. When using autoScrolling:false you can use `fp-auto-height` to create smaller or bigger sections as pointed out in [Creating smaller or bigger sections](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections)

If you want to keep autoScrolling, the only option is using scrollOverflow:true as [in this demo](http://alvarotrigo.com/fullPage/examples/scrolling.html).

The other option is you can yourself create an scrollable element, assign to it the `normalScrollElements` option and then with your own javascript code if the user reached the top or bottom of it so you can manually call `moveSectionUp` or `moveSectionDown`.
This last option might not work as well for touch devices tough.

**Comment by pdechery** [comment]
Hi Alvaro, thanks for the response.

I've tried what you've said and it did work. It didn't allow for `fp-auto-height` though. Instead, it turned my section in 100% height and made the content scrollable with an invisible scrollbar, as I wanted. In the end it did look good and I may stick with that. You can see [here](http://dapp.cloud.fgv.br/validar/observatorio-do-rio/) the results.

Just for note, I've tried to put `fp-auto-height` in the content sections (to let them be taller than the viewport) and set `normalScrollElements` to that same sections in the script, hoping they will be scrolled normally but it didn't work. Everything was auto scrolled. I guess maybe `normalScrollElements` isn't meant for that.

Thanks again,

Pierre

**Comment by alvarotrigo** [comment]
> I guess maybe normalScrollElements isn't meant for that.

That's it.
