### ISSUE TITLE
require() scrolloverflow.js issue

### ISSUE THREAD

**Issue by pdechery** [alvarotrigo/fullPage.js#2239]
When trying to `require` scrolloverflow.js, in order to let the `scrollOverflow` option work, I'm facing the following error, which breaks all the script:

`Cannot read property '0' of undefined`

I'm using browserify and my 'require' order is like so:

```
jQuery = require('jquery')
require('../vendor/jquery.fullpage.min.js')
require('../vendor/scrolloverflow.min.js')(jQuery)
```
Everything was working fine until I add the last line.

Thanks,

Pierre

**Comment by alvarotrigo** [comment]
Looks more like a question for stackoverflow with a `require.js` tag in it.
Fullpage.js requires scrolloverflow before it loads.

**Comment by pdechery** [comment]
Ok, I'll do that. Thanks.

**Comment by alvarotrigo** [comment]
In which file or line is the error anyways?

**Comment by pdechery** [comment]
It's right on the start of the file. You can check for yourself [here](http://dapp.cloud.fgv.br/validar/observatorio-do-rio/) if you want.
