### ISSUE TITLE
about the onLeave callback

### ISSUE THREAD

**Issue by B1anker** [alvarotrigo/fullPage.js#2240]
### Description
When I quickly switched the page，the page would have some bugs.
For example:
       When I moved the page (by click the menu) from the 4th(Contact) to the 2nd(Resume),I select the 1st(Profile) at the same time,the page will stop on 2nd but not 1st.And strangely,the stylesheet has changed.

[My Demo](https://b1anker.github.io)

### Versions 
[Browser, operative system, device...]
safari(mac os 10.11)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
