### ISSUE TITLE
Additional sections outside of fullPage scrolling

### ISSUE THREAD

**Issue by sccr410** [alvarotrigo/fullPage.js#2242]
Trying to use fullPage to build a layout similar to http://www.hugeinc.com/

Basically the first several sections we want to use fullPage, but after that we want normal scrolling sections.

Is this possible?

**Comment by alvarotrigo** [comment]
Check out [this article I wrote about it]()http://www.onextrapixel.com/2015/04/09/how-to-create-a-beautiful-fullscreen-single-scrolling-page-like-huge-inc/.
