### ISSUE TITLE
Panels in overflowing section not clickable

### ISSUE THREAD

**Issue by haxxorsid** [alvarotrigo/fullPage.js#2243]
[Code of webpage](http://pastebin.com/2Bs3nGef)

I am using **Bootstrap** and **fullPage.js** libraries. 

In section3 "Audit Courses", the panels are overflowing, so _scrollOverflow_ and _scrollOverflowNavigation, scrollOverflowOption_ is set **True**.

The scroll is working in that section. But in Section3 (Audit Courses) **panels when clicked**, it **doesn't do any action** (doesn't open PDFs) like the rest of the panels on other sections.

Please help me solve this problem .

**Comment by alvarotrigo** [comment]
> scrollOverflowOption is set True.

You should not touch `scrollOverflowOptions` unless you want to edit the iscroll options.
Just remove it and use the default fullpage.js uses.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by haxxorsid** [comment]
Thanks alot it fixed my problem. It was silly.
You're doing a great job.

**Comment by amanbthakkar** [comment]
Nice work getting it running
