### ISSUE TITLE
Header and footer overlaps Sections/slides

### ISSUE THREAD

**Issue by haxxorsid** [alvarotrigo/fullPage.js#2245]
I tried using Header and footer divs in webpage, I got a problem that both are overlapping some of the content of sections/slides .
Any solution for it ?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by haxxorsid** [comment]
This is my webpage: codearena.me
I tested it using browserstack Screenshot: http://prntscr.com/ceccdr.
Same thing happens in newer Windows Version when a window size is low, the header and footer overlaps the content of the section/slide.

**Comment by alvarotrigo** [comment]
Yours is a CSS knowledge question. Not related with fullpage.js. 
You'd better ask in stackoverflow.com with the css tag.

**Comment by haxxorsid** [comment]
ok.thanks
