### ISSUE TITLE
z-index : fixed element sits above sections despite lower value

### ISSUE THREAD

**Issue by evvvritt** [alvarotrigo/fullPage.js#2246]
Hi, I'm trying to have a fixed element appear above and then below different sections. However, the fixed element just sits above the `#fullpage` element altogether despite some `.fp-sections` having higher z-index values.

[jsfiddle](https://jsfiddle.net/evvvvritt/fn7ksa38/7/)

* open the jsfiddle
* scroll down inside the 'result' pane
* "fixed element" should appear above green sections and behind red sections based on z-index 

**Versions**
jQuery 3.0.11
Mac Book Pro / OSX El Capitan / 10.11.6 (15G31)
Chrome: Version 52.0.2743.116 (64-bit)
Safari: Version 9.1.2 (11601.7.7)

*Thank you for developing this plugin, any guidance greatly appreciated!*

**Comment by alvarotrigo** [comment]
That's a CSS knowledge question. You'd better ask in stackoverflow.com
Take into account that your header is fixed and the fullpage.js elements are not. 

Reproduced without fullpage.js:
https://jsfiddle.net/fn7ksa38/8/

**Comment by evvvritt** [comment]
True, but the fp elements have `position:relative` from the `.fp-section` which means they are affected by z-index.

From this [SO](http://stackoverflow.com/questions/24658232/z-index-on-fixed-element-outside-of-fullpage-js) I managed to get the effect I desired by using the `css3: false` flag ([jsfiddle](https://jsfiddle.net/evvvvritt/zL5rhkq5/))

But it would be preferable to use CSS transitions if possible?

**Comment by alvarotrigo** [comment]
> But it would be preferable to use CSS transitions if possible?

Yeah, always smother in desktop and mobile.

**Comment by evvvritt** [comment]
Exactly, unfortunately I still think this is a bug in FP.js

Your 'reproduced without fullpage.js' jsfiddle is missing that position:relative rule that FP.js applies, with the rule included (and FP.js still excluded) the fixed element is behind the relative one, as expected: [updated jsfiddle] (https://jsfiddle.net/evvvvritt/fn7ksa38/10/)

**Comment by alvarotrigo** [comment]
> Exactly, unfortunately I still think this is a bug in FP.js

Nop. It is a well known browser's bug in any case.

Here you have it again without fullpage.js. See the translate3d:
https://jsfiddle.net/fn7ksa38/11/

**Comment by evvvritt** [comment]
Ahh ok, maybe not so much a browser bug but the behavior of ['stacking contexts'](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/) — seems transforming an element (in this case the #fullpage) creates a new stacking context for it's children and thus reformats them as a flattened layer. 

I even tried changing all the `translate3d`'s to `translateY` and `translateX` with `transform-style:preserve-3d` on #fullpage but that didn't preserve the z-indexing of it's child sections either :( — maybe one day

I'm just going to hide the fixed elements during the 'higher' sections with `onLeave`

Thanks for your quick replies!

**Comment by alvarotrigo** [comment]
> Ahh ok, maybe not so much a browser bug but the behavior of 'stacking contexts'

Seems to work fine without the translate3d:
https://jsfiddle.net/fn7ksa38/12/

**Comment by evvvritt** [comment]
Not when applied to the .container though, .four is absorbed into the .container z-layer 
https://jsfiddle.net/evvvvritt/fn7ksa38/13/

**Comment by alvarotrigo** [comment]
That's my point. The issue is on using the `translate3d property. Possibly related with http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d
