### ISSUE TITLE
Autoplay video not working

### ISSUE THREAD

**Issue by rorc** [alvarotrigo/fullPage.js#2248]
Autoplay `<video>` on slide load are not working even with `data-autoplay` attribute.

And in general, why plugin stops playing video hardcoded? This can handle with native things with `preload="metadata"` attribute or using callback.

**Comment by alvarotrigo** [comment]
> Autoplay <video> on slide load are not working even with data-autoplay attribute.

Working as expected in this reproduction:
http://jsfiddle.net/97tbk/1428/

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by rorc** [comment]
Sorry, not slide load, on section load...

**Comment by alvarotrigo** [comment]
> And in general, why plugin stops playing video hardcoded?

Design decision. You can always turn it off using  `data-keepplaying`

**Comment by alvarotrigo** [comment]
> Sorry, not slide load, on section load...

You'll have to provide a reproduction I'm afraid as detailed in the reporting issues guidelines.

**Comment by rorc** [comment]
Oh, sorry, i am trusted https://www.jsdelivr.com/projects/jquery.fullpage where last version is 2.5.9 :)
