### ISSUE TITLE
Add argument "previous section" into afterLoad callback

### ISSUE THREAD

**Issue by rorc** [alvarotrigo/fullPage.js#2249]
Will be nice add argument previous section container/index into afterLoad callback.
I need rewind video on current section after she leave, that play video again at start if visit this section again.
But now, if i do this across onLeave, i got unpleasant effect of cutting change video frame.

**Comment by alvarotrigo** [comment]
Just use `onLeave` to get the previous index.

**Comment by rorc** [comment]
Written, that is inconvenient, because
> But now, if i do this across onLeave, i got unpleasant effect of cutting change video frame.

**Comment by alvarotrigo** [comment]
I don't understand what your problem is.
Please provide an isolated reproduction in jsfiddle or codepen for more help.

**Comment by rorc** [comment]
I need rewind video to start only after this section leave (not visible).

**Comment by alvarotrigo** [comment]
As I said, use onLeave. Sorry but can't help you more without a reproduction.
