### ISSUE TITLE
Full screen backgrounds not working properly on slides.

### ISSUE THREAD

**Issue by njburrett** [alvarotrigo/fullPage.js#225]
The background images display correctly at full width on all sections, but the slides do not. On the slides no matter what I do it seems to only display at the original image size with no scalling to fit the page. This error is in the downloaded fullPage.js source files. 

I am trying to use CSS background-size: cover for the slides but it has no effect. How do I fix this issue?

Thanks.

**Comment by rafiki52** [comment]
Hi Create one more page using fullpage js. But screens shows emplty on click, top - height happen
