### ISSUE TITLE
Scroll will stop scrolling if .section is nested inside element

### ISSUE THREAD

**Issue by user928** [alvarotrigo/fullPage.js#2251]
Hello, thanks for this great plugin!

### Description
I am having problems to scroll if there are nested .sections in page layout

```html

<div class="mainWrapper">

  <div class="InnerSectionWrapper">
      <div class="section" data-anchor="inner-four">#4 Inner section</div>
      <div class="section" data-anchor="inner-three">#3 Inner section</div>
  </div>
 
   <div class="section" data-anchor="two">#2 Outer section</div>
   <div class="section active" data-anchor="one">#1 Outer section</div>

</div>

```

link to codepen demo:
http://codepen.io/user928/pen/xEGBmd 

### Steps to reproduce it
1.go to demo link
2. try to scroll up until you reach 2nd section

### Versions 
Present on all browsers

**Comment by alvarotrigo** [comment]
That's by design.
See the ["Required HTML structure"](https://github.com/alvarotrigo/fullPage.js#required-html-structure) section of the docs.

**Comment by user928** [comment]
Ok, thanks! I wanted to achieve something like this: http://take.ms/54q8Z but without slicing the upper image into two. I guess that is the only way?

**Comment by alvarotrigo** [comment]
> I guess that is the only way?

I'm quite sure it is not the only way :D 

But that's not a question for this forum as it is a CSS knowledge question one. You'd better ask in http://stackoverflow.com/

**Comment by user928** [comment]
Ok, thanks for the help!
