### ISSUE TITLE
 Future events missing?

### ISSUE THREAD

**Issue by APlusDesign** [alvarotrigo/fullPage.js#2252]
I don't think this needs a codepen, but I have a specific case where I want to know what slide I'm entering before the animation has finished, long before afterLoad is called.

I can't seem to find any events to get the page I'm going to. Sure I could bind more events to the anchor buttons outside of the plugin, but would it not be better to have an event fired for where we know the user is heading based off their click, it would really only need to return the index?

**Comment by alvarotrigo** [comment]
See the [`onLeave` callback](https://github.com/alvarotrigo/fullPage.js#onleave-index-nextindex-direction) that uses the nextIndex parameter.
