### ISSUE TITLE
Responsive scroll anchoring causes scrolling issues on some mobile browsers

### ISSUE THREAD

**Issue by TeamHFOH** [alvarotrigo/fullPage.js#2253]
Hi Alvarotrigo

First of all, got to say we love your work ... keep it up.

New versions of Chrome and Firefox browsers on Android mobile devices (eg Samsung Galaxy S7), do this silly thing where the address bar drops down or hides when you change scrolling direction. This has the effect of changing the browser height.

So when FullPage is running in responsive mode on these devices, we observe an issue where the first scroll in a direction, causes the address bar to appear/hide, which then causes FullPage to try to re-anchor. This results in a disrupted scroll from a user perspective.

you can see this on your demo when run using one of these new style browsers: http://www.alvarotrigo.com/fullPage/extensions/responsiveSlides.html#firstPage2

Maybe we've missed a pre-existing switch in your initialisation settings. But it would be great if we could set an switch on FullPage instantiation to prevent re-anchoring of pages when in responsive mode.

Thanks again.

Edit 1: Oh I should have added, we're now on your latest version 2.8.6.

**Comment by alvarotrigo** [comment]
> you can see this on your demo when run using one of these new style browsers: http://www.alvarotrigo.com/fullPage/extensions/responsiveSlides.html#firstPage2

I guess you can also reproduce it in this other demo?
http://alvarotrigo.com/fullPage/examples/normalScroll.html

> which then causes FullPage to try to re-anchor. This results in a disrupted scroll from a user perspective.

What do you mean by re-anchor? What kind of scroll disruption do you suffer from?
fullpage.js does not resize unless the change of the viewport is more than 20% in mobile devices.

Could you provide a video?
Are you sure you are not talking about the option `fitToSection`?

**Comment by TeamHFOH** [comment]
Oh ok ... so to show you an example, you can reproduce the behaviour on a desktop.

1. Go to the link above
2. Resize the screen to responsive mode ... similar to the size of a mobile browser
3. scroll the half way between slide 1.2 and 1.3 ... so the text 1.2 is disappearing of the top of the page and 1.3 is just appearing at the bottom of the page
4. Now resize the vertical hight of the window by just a couple of pixels.
5. The resulting behaviour is that the nearest slide is centered on the window again.

So now imagine your on a mobile device scrolling down and the address bar dissappears, increasing the size of the window. Now the scroll gets interrupted as Full page tries to centre the nearest content on the page.

Hope that makes sence

**Comment by alvarotrigo** [comment]
The example is using fitToSection:true. 
Just turn it off.

**Comment by TeamHFOH** [comment]
Our code already has fitToSection: false. For completeness ... we set the following initialisation in our code:

            slidesNavigation: true,
            autoScrolling: true,
            controlArrows: true,
            scrollOverflow: true,
            responsiveWidth: 991,
            bigSectionsDestination: top,
            animateAnchor: false,
            fitToSection: false,
            resetSliders: true,
            loopHorizontal: false,

**Comment by alvarotrigo** [comment]
Then please provide an isolated reproduction I can use to test your case.

**Comment by TeamHFOH** [comment]
Hi alvarotrigo

Ok done. How would you like me to send it to you?

**Comment by alvarotrigo** [comment]
> Ok done. How would you like me to send it to you?

I don't want you to send me anything. 
Just a link to an isolated reproduction in jsfiddle, codepen, or your own hosting. No external JS or CSS if possible.

**Comment by alexandrecanuto** [comment]
@TeamHFOH Any luck figuring this out? I have the same issue.

**Comment by alvarotrigo** [comment]
@agusgarcia provide an isolated reproduction as detailed in the [Reporting Issues section](https://github.com/alvarotrigo/fullPage.js#reporting-issues). Without isolated reproduction I can't help.
