### ISSUE TITLE
iScroll.js with parallax

### ISSUE THREAD

**Issue by ipbebnev** [alvarotrigo/fullPage.js#2254]
Hello and thanks for your code.

I need to create parallax effect inside of each section. Any parallax libraris is not working - like Scrollr.js. But i see into iScroll documentation these: http://iscrolljs.com/#indicators. And is there any methods or events to get scroll position of current section? I need to get position of scroll and compare that with my animated element.

**Comment by alvarotrigo** [comment]
See [this answer](http://stackoverflow.com/a/39369282/1081396)
