### ISSUE TITLE
how do i swich the color of the fp-nav when it's on dark background ?

### ISSUE THREAD

**Issue by naouibelgacem** [alvarotrigo/fullPage.js#2258]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Using CSS and the state class added to the body. 

For example:
```css
.fp-viewing-1-3 #fp-nav ul li span{
    background: #f00;
}
```

Or adding a class using the fullpage.js callbacks.
