### ISSUE TITLE
Responsive functionality not working in the pure javascript version of this script

### ISSUE THREAD

**Issue by btlynch** [alvarotrigo/fullPage.js#2259]
I want to say thanks for the great plugin!

Does this functionality not exist for the pure javascript version?  It is not mentioned as one of the features that is not included in that version, but when I search the .js file, the setResponsive() function is not defined.

Thank you

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 

The functionality was never added and will not be added for the moment. 
I'll add it as documentation issue and I'll add it to its docs.

**Comment by alvarotrigo** [comment]
Solved in 2.8.7
