### ISSUE TITLE
 afterRender to enable fancybox

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#226]
I've been tearing my hair out trying to get fancybox to work on a couple slides, but i don't know how to code jquery so i have no idea where to put the afterRender.

Any help would be really appreciated.

**Comment by faliqaiman** [comment]
Dear @alvarotrigo, can you come out one reproduction for this `fullpage.js` and `fancybox.js` sample bcs Im having issue on IE's where when I close the `fancybox`, it's jump to others sections. But when open with Chrome or any modern browser it's 100% working. I try so many times and already asked at stackoverflow but not respon at all. 

Any help would be really appreciated.

Here's my previous reproduction. [jsfiddle](https://jsfiddle.net/1dw1ws1a/)

**Comment by alvarotrigo** [comment]
@faliqaiman use `setAllowScrolling`, not `setAutoScrolling`.

**Comment by faliqaiman** [comment]
@alvarotrigo thanks, it works..
