### ISSUE TITLE
Pressing "back" wont show 1st section

### ISSUE THREAD

**Issue by zholy9** [alvarotrigo/fullPage.js#2261]
Hi ... I'm using the WP fullpage plugin, contacted the author of the plugin and been told to ask it here as the same problem is present on "your website as well".

Just wanted to ask if you have managed to find a solution for the BACK button, please ? After I've posted here the question (first time on GitHub)  ... I've noticed people already asked this, thought it was a while ago. Could this be somehow corrected please ?

Thank you in advance. Zdenek

**Comment by alvarotrigo** [comment]
It is an already known issue without solution so far.
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/950
