### ISSUE TITLE
Can this be used for only horizontal transitions between pages?

### ISSUE THREAD

**Issue by dreadedhamish** [alvarotrigo/fullPage.js#2262]
Before I embark on the journey of integrating this on my site, I was hoping someone could reassure me it's going to be a fruitful endeavour.

I want to integrate this with a wordpress site, on varying length articles, to give horizontal transitions between pages.
I have it somewhat working using SwipeView (https://github.com/cubiq/SwipeView) but it's somewhat limited and a little buggy in my implementation.

I would run an archive loop, so that the front page would 5-10 fulllength articles, each wrapped in a `<DIV>` to form the structure of the different pages.  These would transition horizontally, with each article being a different length that should scroll vertically for as long as the article is.

Will this be all good with fullPage.js?

**Comment by dreadedhamish** [comment]
Additionally - each horizontal page/section transition should go to the top of the next page/section.

**Comment by alvarotrigo** [comment]
I dont see why not. 
You can use horizontal slides for it using the feature scrollOverflow as [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html)

Then you can have whatever you want underneath in another scrollable section.

You'll probably might have some troubles on the way and need to do things such initializing plugins on the `afterRender` callback or using the `reBuild` function depending on your content.
