### ISSUE TITLE
lock anchors javascript

### ISSUE THREAD

**Issue by milka1701** [alvarotrigo/fullPage.js#2263]
Is it possible to lock anchors in javascript version?

**Comment by alvarotrigo** [comment]
Nop.

**Comment by milka1701** [comment]
Acctualy it can be done just be removing line 1259 where you are calling function setState,I think that you should include it cause is very simple to integrate,just use if(lockAnchors== false){
setState()
}

**Comment by alvarotrigo** [comment]
Feel free to commit a pull request.

**Comment by milka1701** [comment]
Don't know what that is?

**Comment by milka1701** [comment]
Oh ok,I will

**Comment by milka1701** [comment]
Ok so cause I'm not so familiar with GitHub and don't understand why when I click "New Pull Request"  "Create Pull Request" gray button shows, which does nothing when I click, I'm going to say what I think you can/should change here.

In javascript version of fullpage.js there is no option to lock anchors like in the jquery version.So I just deleted 1259th line on which you are calling setState function, and anchors are Locked.
So you can add variable called LockAnchors and give a value false just like in jquery version and on line 1259 write this
if(LockAnchors==false){
setState(slideIndex, slideAnchorLink, v.anchorLink, v.sectionIndex);
}
You can see the problem with LockAnchors=false on mobile devices ,especially in landscape ,every time when user changes section all bars show up,and than the window.width is almost 2 times the window.height and the website looks awfully.
