### ISSUE TITLE
Android soft-keyboard covering input field

### ISSUE THREAD

**Issue by digitalprecision** [alvarotrigo/fullPage.js#2264]
On Chrome Android the soft-keyboard is covering some elements of the page due to the way they are centered vertically. iOS pushes the content up correctly but android does not.

I tried 

`$('#input1').blur(function { $.fn.fullpage.setAutoScrolling(false); });`

which works, but then the content bounces back to the middle after a few seconds and is once again hidden by the soft-keyboard. Is there a way to keep the content pushed up until focus()?

**Comment by alvarotrigo** [comment]
> but then the content bounces back to the middle after a few seconds

Turn `fitToSection` to false. You can use `setFitToSection(false)` or just initialise fullpage.js with the option set to false.

**Comment by digitalprecision** [comment]
Ok that worked for focus(), but when I do the following for blur(), the slide doesn't reset:

`
$.fn.fullpage.setAutoScrolling(true);
$.fn.fullpage.setFitToSection(true);`

I even tried:

`$.fn.fullpage.reBuild();`

**Comment by alvarotrigo** [comment]
Try calling `moveTo` to the active section or slide.
