### ISSUE TITLE
Safari: can't mouse-scroll down past 'scrollOverflow: true' section.

### ISSUE THREAD

**Issue by sergeitatarinov** [alvarotrigo/fullPage.js#2265]
### What doesn't work
We've got a section with 'scrollOverflow: true' and can't scroll past it with a mouse.

### What works
Using keyboard arrow down or FP nav anchor link works.
Resizing browser fixes the issue **(!)**.

### See it in action on a live site
1. Go to www.stratim.com/#deliver-value in Safari
2. Try scrolling down with your mouse
3. Try resizing your browser window (no matter how much), and then scrolling down from that section

### Versions 
Safari iOS

**Comment by alvarotrigo** [comment]
Working totally fine for me at Safari in iOS.
You can test it yourself in browserstack.com

**Comment by sergeitatarinov** [comment]
@alvarotrigo my bad. Don't know what got in my head, but I wasn't meaning to say 'iOS'. As you can tell, I've mentioned 'mouse' scroll multiple times.

Check it in Safari on desktop please.

Thanks!

**Comment by alvarotrigo** [comment]
> Check it in Safari on desktop please.

I couldn't find any problem there either. 
You can double check it in browserstack.

**Comment by alvarotrigo** [comment]
> But it doesn't work for a lot of people, on actual devices (MBPs, iMacs).

Right... that's odd. Which Safari version are they using ? Which OS ?

**Comment by alvarotrigo** [comment]
I would encourage you to create an isolated reproduction ideally in jsfiddle or codepen so we can make sure the problem is actually in fullpage.js and not in some external script / css in your side.

**Comment by psr1919plus21** [comment]
Do you got any conclusions about this issue?

**Comment by alvarotrigo** [comment]
I was never able to reproduce the issue. Neither in my own Macbook Pro or in any provided by browserstack.com
