### ISSUE TITLE
individual scrollOverflowOptions for each section

### ISSUE THREAD

**Issue by janein** [alvarotrigo/fullPage.js#2266]
Hi,

I've stumbled across a problem which I think would be very nice to have.
So this is more like a feature proposal.

I am very happy with the implementation of iScroll and as I started using this feature I came across this:
I want to use i.e. the `snap` option in `scrollOverflowOptions`.
As all my sections are structured differently I only need/want this snap in one section.
If I now pass a selector in snap, iScroll starts to look in every(!) scroller for there objects and throws an error if it can't find any.
So what do you think about different scrollOverflowOptions for each scroller?
Or alternatively pass a function which returns a string.

What are your thoughts about this or do you think there would be a better way of resolving this problem?

thank you for your time,
janein

P.S: even if I don't like the fullpage-concept very much I am really thankful for your work on this plugin because designers do not ask for my opinion most of the time :laughing:

**Comment by alvarotrigo** [comment]
> If I now pass a selector in snap, iScroll starts to look in every(!) scroller for there objects and throws an error if it can't find any.

Can you please provide an isolated reproduction of the issue?

**Comment by janein** [comment]
http://codepen.io/janein/pen/QKEEvq

note the `scrolloverflow.min.js:44 Uncaught TypeError: Cannot read property 'length' of undefined` wrror message.
This origins in `.overflow-section` not being present in all sections which are overflowing.

**Comment by alvarotrigo** [comment]
Not possible at the moment and to be honest I don't I'll add this feature in a near future. Therefore I'll close the issue. 

My recommendation to you is to destroy fullpage.js and reBuild it again without the  `snap` option whenever you land in a page which is not the one with the snapping scrolling. (or the other way around, just do it for that single section)
This should be transparent for the end user. 

You can take a look at [my answer here](http://stackoverflow.com/a/36643702/1081396) to get inspired.

**Comment by janein** [comment]
Ok thanks I'll give it a try.

**Comment by janein** [comment]
Well I think this won't work.
Beside other problems with rebuilding (scrolls down from top every time) I think this will not prevent the error to be thrown as all scrollers are initialized when fullpage is build and not when the section is loaded.

So i.e. if I have my snapping-markup only in the first section I still get the error for all other overflowing sections.

I also tried to only update iScroll but it seems that it isn't possible to change the snap-option dynamically.

Looks like this problem can not be solved easily.
Is there another way the prevent a section-change by mistake when scrolling to the end of a scrollable section?
I thought the iScroll workaround might be a solutions for this: #941 ...

**Comment by alvarotrigo** [comment]
> Is there another way the prevent a section-change by mistake when scrolling to the end of a scrollable section?

Do you see any option in iScroll that might help on this regard ?

**Comment by janein** [comment]
In my case I used the iScroll "snap" option to stop the scrolling a few pixels before the end of the section. This way the next scroll would trigger the section-change.
Of course this only works if you can divide your acrollable section into snap-pages that make sense.
