### ISSUE TITLE
Anchors is ignored when section is too narrow in fp-responsive mode

### ISSUE THREAD

**Issue by Bondra** [alvarotrigo/fullPage.js#2267]
First, I wasn't able to make a reproduction of this on JSfiddle since it seems like the permalink in the adressfield is not updated when scrolling through sections. Have a look over here though: https://goo.gl/2iMQ3q

1. Narrow the window down til it reaches fp-responsive mode below 1100px
2. Scroll down and back to the first section #firstsection... 
3. Since the first section is too narrow in height #firstsection won't be recognized :(

Any solutions to this besides making the actual section bigger than the following section?

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 
I'll take a look for the next release.

**Comment by alvarotrigo** [comment]
Fixed on dev 2.8.8

**Comment by alvarotrigo** [comment]
Merged in 2.8.8
