### ISSUE TITLE
Issues with scrolling when scrollOverflow is set to true

### ISSUE THREAD

**Issue by markonose** [alvarotrigo/fullPage.js#2268]
Hello.

Using your plugin there's an issue when scrolling on an android tablet(works fine on a phone), it scrolls really slowly with scrollOverflow set to true. Could you help me with the issue or is it better to write about it on the iScroll github page?

**Comment by alvarotrigo** [comment]
> Could you help me with the issue or is it better to write about it on the iScroll github page?

Yeah better to do that. 
Also, check [its docs](http://iscrolljs.com/). There's probably an option to change the sensitivity.
