### ISSUE TITLE
Unknown amount of sections but last section always have specific backgroundcolor

### ISSUE THREAD

**Issue by frankmacd1** [alvarotrigo/fullPage.js#2269]
I know that you can set the color of each section using
sectionsColor : ['#ccc', '#fff'],

but my question is this, Let's say you are building the sections dynamically from a list and depending on each page there may be a different amount of sections. Is there are to set all sections one color, but the last section a different color?

Right now I am building my sections using AJAX from a SharePoint list for different pages, and I have a footer pulled in using a JS .load .....   I want the footer section to be #121212 but all sections before that have a different color based on which page the visitor is at.

**Comment by alvarotrigo** [comment]
Just use the `:last-child` CSS selector:
https://jsfiddle.net/kaj5Lrru/
