### ISSUE TITLE
afterLoad event firing twice 

### ISSUE THREAD

**Issue by jjso** [alvarotrigo/fullPage.js#2271]
Hi ! 

I'm on Chrome and I have this wierd bug where the afterLoad events randomly fires twice (for the same fold) while scrolling. 

The page then skips a fold (whether up or down) and stops on the next one. 

It does happen often enough to be an actual problem, so I was wondering if you had an idea what the cause might be;

I am not using anchor links as IDs, but some classes have the same name as anchor links ..

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
