### ISSUE TITLE
Is it possible to use verticalCentered differently for certain sections?

### ISSUE THREAD

**Issue by connoisseurli** [alvarotrigo/fullPage.js#2273]
VerticalCentered: true is fine for my sections that don't extend beyond the viewport, but for my sections that use the scrollOverflow, the verticlalCentered option is causing the section to automatically shift down when you arrive to it. Is it possible to only use verticalCentered: true for select sections and if not, is there someway to prevent a section with scrollOverflow in use from shifting down automatically?

**Comment by alvarotrigo** [comment]
Just use CSS to turn it off:

```css
#mySection .fp-tableCell{
   vertical-align: top;
}
```
