### ISSUE TITLE
disable scroll to next section in onLeave call back JAVASCRIPT VERSION

### ISSUE THREAD

**Issue by milka1701** [alvarotrigo/fullPage.js#2274]
How to disable scroll to next section in onLeave callback in javascript version?
I tried -->
if (nextIndex==6){
return false 
}
This was working in jQuery version,

**Comment by alvarotrigo** [comment]
> This was working in jQuery version,

It was never implemented in the Javascript version.
It hasn't been updated since a year ago.

**Comment by milka1701** [comment]
Is there a way to block scroll to next section?

**Comment by alvarotrigo** [comment]
Probably a hacky one. Try removing the `fp-section` class of it.

**Comment by milka1701** [comment]
Doesn work but acctualy that was not the main problem,I was trying to solve the main problem that way.I have 5 sections and when go to the 5th and scroll down I get some errors in console and the hash "myurl#null" and nothing works until I reload the site,so I tried to make one "fake section" to be the last one and when I scroll to the 5th and don't allow scroll to 6th section using onLeave callback if nextIndex ==6 don't allow scroll to the 6th(fakeSection).
I get these error in console when I go to the last section and scroll down.

**Comment by alvarotrigo** [comment]
@milka1701 I would suggest you to use the jQuery version. The Javascript version is the Alpha version and contain some bugs. 

As stated in the docs:

> This is in Alpha version and support for it won't be provided yet.

**Comment by milka1701** [comment]
ok thanks,but I won't jQuery version cause I need 10,000 lines long stupid library

**Comment by alvarotrigo** [comment]
@milka1701 if you really need it I could work on the Javascript version to solve the problem for some price. Just [let me know](http://alvarotrigo.com/#contact-page) if you are interested and I'll provide you with a quote.

**Comment by milka1701** [comment]
Actually I'm experimenting with your plugin,and I really need to know how you controll scroll,cause I would do the different things on "touch-events"(mouse-scroll).I would only need something like this-->THIS IS EXAMPLE(human normal words)when I'm on first section and (touch-event>5) do element.style.transform="translateY(-100%)".THAT KIND OF THING.How much money I would need to pay you to get the code that controls mouse scroll.Thats the thing I really need.Now I have 5 blank sections.5 divs with content(they are positioned-fixed).1st one is top:0%,2nd is top:100%,3rd is top:200%,4th is top:300%,5th is top:400%.And I use onLeave callback.to move them up.For example if nextFullpage section is 2 ,move 100% up my section.It really hard to undersant but it working,only have the problem with errors when scroll down on last section.But it can be smoother if I use function on touch-event insted of if nextIndex is move section up...

**Comment by alvarotrigo** [comment]
I though you had troubles with the Javascript version. I can provide you help with the bug you found. Not interested in the rest.

**Comment by milka1701** [comment]
Sorry but then I'm not interested in your help,cause even if you solve the bug the transition between my section's won't be smooth enough for big screens.Only interested in disabling scroll and controlling user scroll

**Comment by alvarotrigo** [comment]
No worries.
