### ISSUE TITLE
Fullpage.js can only be initialized once and you are doing it multiple times

### ISSUE THREAD

**Issue by ben4523** [alvarotrigo/fullPage.js#2275]
### Description
Hy,

I have some problem with this plugin. he work perfctely but in console i show this message i dont know why : 

fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!Pn @ jquery.fullPage.min.js:8zn @ jquery.fullPage.min.js:8e.fn.fullpage @ jquery.fullPage.min.js:8(anonymous function) @ main.js:216j @ jquery-1.11.0.min.js:2fireWith @ jquery-1.11.0.min.js:2ready @ jquery-1.11.0.min.js:2K @ jquery-1.11.0.min.js:2
jquery.fullPage.min.js:8fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!Pn @ jquery.fullPage.min.js:8zn @ jquery.fullPage.min.js:8e.fn.fullpage @ jquery.fullPage.min.js:8(anonymous function) @ main.js:227j @ jquery-1.11.0.min.js:2fireWith @ jquery-1.11.0.min.js:2ready @ jquery-1.11.0.min.js:2K @ jquery-1.11.0.min.js:2

My web site is http://beta.lettershop.fr

Thanks so much

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
