### ISSUE TITLE
On mobile chrome, trying to scroll up causes page reload

### ISSUE THREAD

**Issue by joshuaohana** [alvarotrigo/fullPage.js#2276]
iOS mobile Chrome browser.

I have a multi section page using fullPage.js, works perfect in every situation except mobile Chrome browser due to Chrome's "pull down to reload page" feature.

If you try to scroll up (by sliding finger down) it will reload to the page. If you play with it some you'll find that sliding fast will allow you to scroll normally, but if you slide in a more natural way like someone used to scrolling on a website, it'll "stick" at first then just reload the page, instead of sliding up to the next page.

It causing an exceedingly poor user experience as any time the user tries to scroll up they see that little chrome menu bar with the reload/close/back buttons.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by joshuaohana** [comment]
sorry, re-created following guidelines and using issue skeleton, #2277
