### ISSUE TITLE
IScroll  is undefined

### ISSUE THREAD

**Issue by shynome** [alvarotrigo/fullPage.js#2281]
when I use requirejs load fullpage & scrolloverflow , it appears.
But I can't found where fullpage require 'scrolloverflow' or other name  to use it

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2250

The problem when using `require` is that makes dependencies compulsory as far as I know. 
And scrollOverflow shouldn't be compulsory.

It seems to be [some kind of trick](http://stackoverflow.com/questions/14164610/requirejs-optional-dependency), but I didn't look at it very much to be honest.

I'll close the issue to keep a single open threat about it. (https://github.com/alvarotrigo/fullPage.js/issues/2250)

**Comment by shynome** [comment]
Thanks

Álvaro <notifications@github.com>于2016年9月22日周四 下午5:06写道：

**Comment by AQwebDev** [comment]
scrolloverflow is amd compatible and can be used with requirejs. But fullpage does wrong define definition for amd. it defines jquery as dependency but not scrolloverflow. Therefore it is inknown within define and factory. To fix this issue for amd the fullpage.js needs to be refactored therefore.

**Comment by alvarotrigo** [comment]
> But fullpage does wrong define definition for amd. it defines jquery as dependency but not scrolloverflow.

If you read my previous answer you'll see why's that.

>The problem when using require is that makes dependencies compulsory as far as I know.
And scrollOverflow shouldn't be compulsory.
