### ISSUE TITLE
Custom section

### ISSUE THREAD

**Issue by palanisamym14** [alvarotrigo/fullPage.js#2283]
### Hi team/

I have 3 more section(A, B, C,..) . In  A section have place 50% display and remaining 50% fill with (B) second section. while scroll down the section B section display fully in the viewport, How to implement the section using fullpage js.

**Comment by alvarotrigo** [comment]
Have you read the section [creating smaller or bigger sections](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections) from the docs?
