### ISSUE TITLE
iOS 10 prevent top and bottom window bounce

### ISSUE THREAD

**Issue by giacomoalonzi** [alvarotrigo/fullPage.js#2285]
### Description
Hello, on iOS10 when the page scroll, the window have a standard ios bounce effect (you know?).
Window doesn't stay "fixed".
This happen only on iOS10. On iOS 9.3 all works perfectly.

Any help?

### Versions 
Safari 10, iOS 10.1 Beta, iPad Mini 2/ Simulator

**Comment by alvarotrigo** [comment]
Please provide information about your fullpage.js initialization.

**Comment by giacomoalonzi** [comment]
Hi @alvarotrigo the config is the config:
`$('#mainSlider').fullpage({
			menu: '#nav',
			lockAnchors: false,
			navigation: false,
			navigationPosition: 'right',
			showActiveTooltip: false,
			slidesNavigation: false,
			allowPageScroll: true,
			resize: false,
			verticalCentered: false,
			touchSensitivity: 15,
			autoScroll: false,
			keyboardScrolling: true,
			sectionSelector: '.inner-wrap.section',
			css3: true,
			fitToSection: true,
			onLeave: App.ScrollOnleave,
			afterLoad: App.ScrollOnEnter,
		});`

There's a possible relation with this?  http://stackoverflow.com/questions/37808180/disable-viewport-zooming-ios-10-safari

**Comment by alvarotrigo** [comment]
`allowPageScroll` is not a fullPage.js function. 
I do not provide support for fullpage.js modifiactions.

**Comment by alvarotrigo** [comment]
If you think you can reproduce the problem with the official fullpage.js version (version 2.8.6) . Provide the initialization settings for it.

**Comment by giacomoalonzi** [comment]
@alvarotrigo if I remove that string, the results is the same.

**Comment by alvarotrigo** [comment]
@giacomoalonzi it is not about those strings or those options.
I can not be sure you are using the official fullpage.js 2.8.6  and therefore I can't provide support for what can be a modification of fullpage.js.

If you believe the issue is in the official fullpage.js. Please download the latest version and provide a link with a reproduction.

**Comment by giacomoalonzi** [comment]
@alvarotrigo i'm using "fullpage.js": "^2.8.6" installed with bower.

**Comment by alvarotrigo** [comment]
@giacomoalonzi if you have the official version, then `autoScroll: false,` won't have any effect and will still autoScroll the site... 
Are you telling me you are in fact using `autoScrolling:true` ? ,

**Comment by giacomoalonzi** [comment]
maybe wrong copy-paste, now I've removed all no fpjs option.

**Comment by alvarotrigo** [comment]
So... you are using `autoScrolling:true` to reproduce the issue?

**Comment by giacomoalonzi** [comment]
this is my code updated, the issue on ios 10 is still present.

`Scroll: () => {
		$('#mainSlider').fullpage({
			menu: '#nav',
			lockAnchors: false,
			navigation: false,
			navigationPosition: 'right',
			showActiveTooltip: false,
			slidesNavigation: false,
			resize: false,
			verticalCentered: false,
			touchSensitivity: 15,
			keyboardScrolling: true,
			sectionSelector: '.inner-wrap.section',
			css3: true,
			fitToSection: true,
			onLeave: App.ScrollOnleave,
			afterLoad: App.ScrollOnEnter,
		});
	},`

**Comment by alvarotrigo** [comment]
There's no `resize` option either...

**Comment by alvarotrigo** [comment]
Your initialization looks very similar to the one used on the [demo site](http://alvarotrigo.com/fullPage/).
Can you reproduce the issue there?
Because I can't in iOS 9.

**Comment by alvarotrigo** [comment]
Mmm I was able to reproduce it now when swiping down from the top of the screen.

**Comment by giacomoalonzi** [comment]
Also in your demo, the problem only exists on ios 10. No problem on ios9.

**Comment by formlessde** [comment]
Same problem here, window is bouncing on IOS10 and scrollbars are visible while scrolling ..
Worked perfectly on IOS9 ..

**Comment by alvarotrigo** [comment]
Confirmed. I'll take a look at it.

**Comment by alvarotrigo** [comment]
@formlessde @giacomoalonzi  I believe I might have fixed it. Can you please try the [dev version of fullpage.js](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js) and let me know if that works well for you?
It seems to be working for me. I'm also going to test it now in other devices with Android and previous iOS versions.

**Comment by formlessde** [comment]
works for me on Safari, IOS10, thank you!
I'm going to test it on chrome mobile tomorrow ..

**Comment by giacomoalonzi** [comment]
Hi @alvarotrigo thank you for your time. 
The problem for me is still here. On iOS 10. Can I send you a private link of the project?

Thank you.

**Comment by alvarotrigo** [comment]
@giacomoalonzi are you using the dev version I mentioned? 
No private links, just isolated reprodroductions.

**Comment by alvarotrigo** [comment]
Solved in 2.8.7
