### ISSUE TITLE
reload favicon.ico on each scroll

### ISSUE THREAD

**Issue by ArturLyapin** [alvarotrigo/fullPage.js#2286]
Hello. Thanks for this plugin.
I have one problem:

Steps
1) I add favicon.ico to my page.  `<link href="/favicon.ico" rel="icon">`
2) Set `scrollBar: true`.
3) When I do scrolling with mousewheel my `favicon.ico` is reloaded on each scrolling.(disappears and appears in browser tab)
 
- if I set `scrollBar: false` it works ok, but `scrollBar: true` is necessary for my site.
I reproduce this on Google 51, and other modern browsers.

I can't create https://jsfiddle.net, because I can't add favicon to fiddle.
If it will be necessary I can create isolated html/css/js files for this case

it is important feature for me and my project.
Please, help :)

PS. sorry for my english.

**Comment by alvarotrigo** [comment]
> I can't create https://jsfiddle.net, because I can't add favicon to fiddle.
> If it will be necessary I can create isolated html/css/js files for this case

Can you then reproduce it in your own website and provide a link?

**Comment by ArturLyapin** [comment]
Yes, you can see it here http://iconstudios.ru/
it is our beta version of site

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue but a browser's one. It takes place in any website when changing the anchor name in the URL. 

See [this post](http://stackoverflow.com/questions/13128045/browser-displayed-favicon-blinks-on-hash-change) for a solution.
