### ISSUE TITLE
Automatically adding api=1 to vimeo videos causing conflicts when using the new vimeo API

### ISSUE THREAD

**Issue by LetterAfterZ** [alvarotrigo/fullPage.js#2288]
There's a function in the script that was adding api=1 to vimeo videos. (Took me ages to work out this plugin was adding it!)

It's an issue as the new Vimeo API doesn't work correctly if api=1 is set.

Recommend disabling this hook and replacing it with instructions to include api=1 if you're using the froogaloop api.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! Could you be more specific about the issue that its causing to you? 
Any link to a reference about it?

In any case, I'll remove the `api=1` for vimeo videos. fullPage.js is not even able to `autplay` or `autopause` them, so it makes no sense to manipulate the source URL in any case.

**Comment by LetterAfterZ** [comment]
No problems @alvarotrigo, thanks for the quick response.

The thread is here:
https://github.com/vimeo/player.js/issues/34

Basically this replaced froogaloop: https://github.com/vimeo/player.js

**Comment by alvarotrigo** [comment]
Fixed in the dev version.

**Comment by alvarotrigo** [comment]
Solved in 2.8.7
