### ISSUE TITLE
is it possible to PIN slides to top? 

### ISSUE THREAD

**Issue by sandrodz** [alvarotrigo/fullPage.js#2289]
I'm currently using magicsroll.io to achieve pinning effect, but library is not optimized and behaves really bad on safari/osx.

I'm considering dropping it in favor of smooth fullpage.js experience. 

Any way to achieve similar effect? : https://static.weare.de.com/

**Comment by alvarotrigo** [comment]
Check the option `fitToSection` of fullpage.js.
