### ISSUE TITLE
Prevent iscroll from scrolling in an inactive section?

### ISSUE THREAD

**Issue by Bondra** [alvarotrigo/fullPage.js#2290]
Hi!

Is there a way to prevent iscroll from scrolling if the section is not active? The problem I have is when I hover an inactive section that uses iscroll and scroll it both the section and iscroll will move. It makes the experience kind of buggy.

See reproduction:
https://jsfiddle.net/15s3rjjn/3/

**Comment by alvarotrigo** [comment]
> Is there a way to prevent iscroll from scrolling if the section is not active?

Not at the moment. I'll mark it as a possible enhancement for the future.

**Comment by alvarotrigo** [comment]
Fixed on dev.

**Comment by alvarotrigo** [comment]
Merged in 2.8.8

**Comment by Bondra** [comment]
Hmm it seem like the mousewheel scrolling is ignored now? Doesn't work any longer with the new version...

**Comment by alvarotrigo** [comment]
@Bondra you'll have to be more specific.
Working perfectly [in the demo](http://alvarotrigo.com/fullPage/examples/scrolling.html#secondPage) and [in your example](https://jsfiddle.net/15s3rjjn/4/).

**Comment by Bondra** [comment]
I wasn't sure at first but now I can replicate the problem: If a section that uses iscroll is first the mousewheel stops working. I removed the first section at let the one with the scroll be the first one:
https://jsfiddle.net/15s3rjjn/5/

**Comment by alvarotrigo** [comment]
Right. Can you please open a new topic with that?

**Comment by Bondra** [comment]
Yes! I made a new one.
