### ISSUE TITLE
Changes page on iScroll enabled slide when scroll area is too small

### ISSUE THREAD

**Issue by liberat0r** [alvarotrigo/fullPage.js#2291]
### Description
In a slide with iScroll enabled scrolling just once towards a direction where there is scrollable space is causing a change of slide possibly because the mouse is scrolling a bit too much. Is it possible to maybe ignore the scroll triggered from the mouse once before scrolling out of a slide when iScroll is enabled?

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/liberat0r/nj9fht45/1/

### Steps to reproduce it
Scroll down to attempt to view the bottom 2vh of the first slide

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/941
