### ISSUE TITLE
Feature: Support für data-navigationtooltips

### ISSUE THREAD

**Issue by landwire** [alvarotrigo/fullPage.js#2292]
### Description
It would be nice to be able to set the navigationtooltips equivalent to the data-anchor attribute.

**Comment by alvarotrigo** [comment]
That's already possible.  Just add `data-tooltip="xxx"` in each section .
See [this example](http://jsfiddle.net/97tbk/1344/).

**Comment by alvarotrigo** [comment]
I'll mark it as a documentation issue. As I've released it is not documented.

**Comment by alvarotrigo** [comment]
Solved in 2.8.7
