### ISSUE TITLE
When data-anchor not set it returns undefined

### ISSUE THREAD

**Issue by landwire** [alvarotrigo/fullPage.js#2293]
### Description
I am using the data anchor attribute. But for the last slide, a footer area only with the class "fp-auto-height", I am not setting a data-anchor attribute. Unfortunately the URL then looks like this:
www.example.com#undefined

### Link to isolated reproduction with no external CSS / JS

```
<section class="section document-section__one" data-anchor="one">
     ONE
</section>
=> www.example.com#one
<section class="section document-section__two" data-anchor="two">
    TWO
</section>
=> www.example.com#two
<section class="section fp-auto-height document-section__footer">
    FOOTER
</section>
=> www.example.com#undefined
 
```

Is there a way to just not show an anchor at all for the last slide?
Setting data-anchor="" still creates www.example.com#

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).


> Is there a way to just not show an anchor at all for the last slide?

No. The most you can do is use `setLockAnchors`.
