### ISSUE TITLE
Fading Effect Plugin

### ISSUE THREAD

**Issue by joshgarth22** [alvarotrigo/fullPage.js#2298]
Ok, so I purchased the fading effect plugin but it breaks fullPage.js

I added the script BEFORE fullPage.js per your instructions in documentation but when I do that it completely breaks the plugin.  When I remove the fading effect script, the plugin works just fine.

Any ideas on what may be causing this?

**Comment by alvarotrigo** [comment]
[Contact me](http://alvarotrigo.com/#contact-page) and send me a link with the reproduction please.
