### ISSUE TITLE
Impossible to modify Menu behavior through callbacks

### ISSUE THREAD

**Issue by AuHau** [alvarotrigo/fullPage.js#2299]
### Description
I needed to group several pages under same Menu item. I searched a bit how to approach it and found Issue with the same problem (#1354), where it was recommended to use callbacks to achieve this. So I started to work on it, but I found out that with the order of calls of the callbacks it is not really possible to implement it.

The thing is that `activateMenuAndNav()` is called after the callbacks are fired, which completely cancel out effects on active class on Menu of `onLeave()` callback (which I think is natural place to put such a code to). If you use `afterLoad()` callback than it works, but there is really ugly moment when the Menu item doesn't have Active class assigned during animation period, which is not really possible to use such a solution.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/AuHau/gc3gnb7c/

### Steps to reproduce it
1. Go to next page
2. The first menu item, should stay active, but there is small period when it blinks "off" and "on".

### Versions 
Linux, Chrome, fullPage.js edge

### Proposed solution
Since I was going through the code I immediately wrote a fix for my webpage and I would like to make PR with the fix, but I didn't really managed to cover all cases.
[Here is link](https://github.com/AuHau/fullPage.js/commit/c21c993cc335662c820ae8025fa861e5b2577e4a) to my commit. 

I reordered the `activateMenuAndNav()` and now it works for cases when the `autoScrolling = true`, then it also works as expected when `autoScrolling = false` and `fitToSection = false`, but with `autoScrolling = false` and `fitToSection = true` there is an issue that when the `scrollPage()` is called in the `fitToSection` phase, the callbacks are not fired. That will again delete the active class from the Menu item. Since I don't really know the code by heart, I am not sure how to fix it, so suggestions would be appreciated.

**Comment by alvarotrigo** [comment]
Simple do not use the ´menu´ option at all and create your own navigation system.

**Comment by AuHau** [comment]
Hmm alright, it might have been overkill from my side and I didn't really think of this option.
But I think it could be still valid point for a change, but yeah that is your decision to make. I will be happy to send the PR.

Anyway thanks a lot for suggestion and work done on this plugin! :smiley:
