### ISSUE TITLE
moveSectionDown() takes the control to the last section on firefox

### ISSUE THREAD

**Issue by vagu71** [alvarotrigo/fullPage.js#2300]
Hi Alvaro,

Found a bug with the latest code. Basically, what's happening is that on firefox, moveSectionDown() takes the flow to the last slide whereas it should be taking the control to the next slide. 

Below is the code I'm using: 

                    $('.arrow-down.down').on('click', function() {
                        $.fn.fullpage.moveSectionDown();
                    });

Thanks,
V

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
