### ISSUE TITLE
Works autoscroll only in one-way ( and not its reverse )

### ISSUE THREAD

**Issue by salvatorecriscioneweb** [alvarotrigo/fullPage.js#2301]
### Description
Implementing fullpage with 2 separate section ( one fullpage and one auto-height ) autoscroll only in oneway ( scroll from section 1 to 2) and not his reverse ( scroll from section 2 to 1 doesn't trigger autoscroll ).

### Fullpage Configuration
```
`$('#fullpage').fullpage({
    autoScrolling: true,
    fitToSection: false,
    scrollBar: true,
    fitToSectionDelay: 0,
    controlArrows: false,
    normalScrollElements: '#section-content'
})`
```

### HTML Markup
```
<div id="fullpage">
   <div class="section" id="section-header">
       ....
   </div>
   <div class="section contained fp-normal-scroll fp-auto-height" id="section-content">
       ....
   </div>
</div>
```

### Temp workaround

At the moment i wrote a temporary workaround, but it trigger always at half of section 1 's scroll

```
onLeave: function(index, nextIndex, element) {
      if ( nextIndex === 1 ) {
        $("body").animate({
          scrollTop: 0
        })
     }
}
```

Some help? it's a bug or just by fullpage.js design? I understand i'm forcing it over fullpage philosophy

### Notes
Removing scrollable autoheight section it works flawless

**Comment by alvarotrigo** [comment]
normalScrollElements should never be used in the section element.
I'll mark the issue as a documentation one, as I guess I'll have to clearly specify that in the docs.

**Comment by salvatorecriscioneweb** [comment]
Thanks for fast answer and your time, but it is possible achieve this?
I removed normalScrollElements configuration but it's still broken.

I made a codepen with issue : http://codepen.io/anon/pen/amLAmV

As you can see scroll up is not animated in any way.

**Comment by alvarotrigo** [comment]
@salvatorecriscioneweb `fp-normal-scroll` is not a documented option. And in this case for a reason :)

**Comment by salvatorecriscioneweb** [comment]
@alvarotrigo thanks for answer this issue is closed, i know i was forcing fullpage.js philosophy and it's not designed to do this :)

Thanks anyway for answers :) have nice day!

**Comment by alvarotrigo** [comment]
So, answering your question. No.
The most you can do is make use of `scrollOverflow:true` to get something [like this](http://alvarotrigo.com/fullPage/examples/scrolling.html) in your 2nd section.
