### ISSUE TITLE
Browser redraw and viewport change

### ISSUE THREAD

**Issue by maxdd** [alvarotrigo/fullPage.js#2302]
I hope it is fullpage.js related issue.
My 3rd sections contains canvas/graph and images.
When i download a file from my site, the download bar of the browser pops out in the bottom leading to a redraw of the content which is cut out due to the small space.
The same happens if i resize manually the window.
How can i avoid this? Is there a way to block it?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
