### ISSUE TITLE
Data-src on videos not working in Chrome?

### ISSUE THREAD

**Issue by partTimeCrazy** [alvarotrigo/fullPage.js#2303]
Trying to lazy load an mp4 and it doesnt seem to work in Chrome on iOS 10. I can see the 'Play' button but nothing happens when pressed. Works fine in Safari though... any ideas?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
