### ISSUE TITLE
how can I add big section scrolling functionality without making the scrollbars visible

### ISSUE THREAD

**Issue by praks234** [alvarotrigo/fullPage.js#2304]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Check the [iScroll.js options](http://iscrolljs.com/).
You  might be able to do it using `scrollOverflow:true`.

**Comment by praks234** [comment]
Setting scrolloverflow to true is adding two scrollers. One because of the scrolloverflow:true and second because of the IScroll. 
var myScroll = new IScroll('#fullpage', {
        mouseWheel: true,
        scrollbars: true,
        scrollX: false, 
        scrollY: false
    });

if i set overflow:hidden to the class(fp-scrollable) which gets added because of scrolloverflow:true then only vertical scrollbar of IScroll come up but it does not scroll down to the entire section.
Even the autoscrolling stops because of this.

**Comment by alvarotrigo** [comment]
As I said, you can check the iScroll options to see if they provide a way to hide the scroll bar.

**Comment by praks234** [comment]
Hi ,
I am attaching a screenshot for my issue. As soon as i change scrollOverflow to true, inner scrollers gets visible even though i see IScroll is not defined error in the console. when i add scrolloverflow.js then two scrollbars get added. please do let me know why those inner scrollbars are getting created.
![scrolloverflow_true](https://cloud.githubusercontent.com/assets/21304653/19143190/c78aba9c-8bbf-11e6-91d7-4b1b96935daf.png)

**Comment by alvarotrigo** [comment]
@praks234 I will need an isolated reproduction from you in jsfiddle or codepen.
