### ISSUE TITLE
How can we have in section scroll if we would need to fit more content in each section

### ISSUE THREAD

**Issue by ssunagar** [alvarotrigo/fullPage.js#2305]
How can we have in section scroll if we would need to fit more content in each section

### Steps to reproduce it
1. [go to section1
2. scroll down, this should scroll the contents within the same section
3. Scroll should not visible

**Comment by alvarotrigo** [comment]
It's detailed in the documentation. Use `scrollOverflow:true` as in [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).
