### ISSUE TITLE
Twitter Browser using wrong height

### ISSUE THREAD

**Issue by CHEWX** [alvarotrigo/fullPage.js#2306]
### Description

When clicking a link from Twitter on mobile and it opens up in their own browser, the fixed height fullpage.js applies is incorrect. This makes anything that is sat at the bottom of the div within hidden or part hidden.
### Link to isolated reproduction with no external CSS / JS & Steps to reproduce it

Go to @imac2 on Twitter and click the link in his bio. This will open http://alvarotrigo.com/fullPage/ in the Twitter browser and you will be able to replicate the issue.

Thanks

**Comment by alvarotrigo** [comment]
Thanks for reporting it, but probably there's nothing we can do about it.
I'll mark it as "might not be possible".

**Comment by thisisfed** [comment]
Actually I have the same annoying problem with Instagram and Facebook browsers. 
I'm not sure if it's possible to detect those browsers with some extra js or media queries?

**Comment by Acovendesigns** [comment]
I'm having the same issue over here with Instagram browser.

**Comment by Acovendesigns** [comment]
Also could be worth looking at updating 
all instances of
window.height
to
window.innerHeight

**Comment by thisisfed** [comment]
Any news about this annoying issue?
I literally can't browse my website in any (Facebook, Instagram, Twitter browser.

![img_7547](https://user-images.githubusercontent.com/14325884/29181771-a5eb6370-7dfc-11e7-984d-1a55f13dabfd.PNG)

**Comment by MadanBhandari** [comment]
btw it's working as expected with me on OnePlus 5T, Android 8.10 Twitter 7.72.0-release.16

**Comment by CHEWX** [comment]
Yep, looks like Twitter updated their browser.

**Comment by alvarotrigo** [comment]
Awesome!
