### ISSUE TITLE
Video autoplay doesn't work without data-autoplay tag

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#2308]
Hi Alvaro,

Video autoplay tag doesn't work if data-autoplay is not used.

You can find the isolated reproduction here:
http://codepen.io/anon/pen/PGEzGq

In the example, there is a video on the second section which has the autoplay tag. It should play automatically when the page loads but doesn't.

(I found out the problem might be about the code in addTableClass function.)

Is there a non-script solution to this ?

Thank you for your help,

**Comment by alvarotrigo** [comment]
Just play it yourself in the `afterRender` callback. 
Or, use `verticalCentered:false` and center the content by yourself.  Take a look [at the FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) to know why this is happening.
