### ISSUE TITLE
Avoid travelling throught the full web when refreshing.

### ISSUE THREAD

**Issue by ppaaccoo** [alvarotrigo/fullPage.js#2309]
Hi Álvaro!

Wonderful plugin!
Is it any way to avoid travelling throught the full web when refreshing any section that is not the first?

I've been searching for the solution in the previous issues, but if I have found it I haven't recognized it.

Thanks in advance for your attention.

**Comment by alvarotrigo** [comment]
Use `animateAnchor: false,`

**Comment by ppaaccoo** [comment]
Thanks Álvaro!
