### ISSUE TITLE
Preserve native horizontal scroll.

### ISSUE THREAD

**Issue by badstorm** [alvarotrigo/fullPage.js#2310]
There is any way to preserve the native horizontal scoll? I build an app with an horizotnal carousel and inside there are webviews with fullPage. But when fullPage is enable, I cannot sroll left/right to the next page in the app, I can only scroll down (the fullPage html content).

**Comment by alvarotrigo** [comment]
Try using the function `setAllowScrolling` on the `afterRender` callback and turn the scrolling off for right and left.

Read more about how to use the function [in the docs](https://github.com/alvarotrigo/fullPage.js#setautoscrollingboolean)

**Comment by badstorm** [comment]
Thanks for your answer, but what about the pure javascript version? I'll see in the code that there is no "setAllowScrolling" function.

**Comment by alvarotrigo** [comment]
@badstorm maybe not possible then.
