### ISSUE TITLE
Handling of 'wheel' input event was delayed for 122 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.

### ISSUE THREAD

**Issue by kumar0521** [alvarotrigo/fullPage.js#2311]
### Implemented the fullpagejs on homepage of my app it work prefect but when user navigate again same page with another link there is delay in wheel animation. it appear only in chrome 53 browser.

following message shows in console 
"Handling of 'wheel' input event was delayed for 122 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive."
### Versions

[Chrome 53, macOS, browser]

**Comment by alvarotrigo** [comment]
I'll take a look at it once I get home. It seems to be a new warning due to the new Chrome version.
In any case, this is not an error but a warning. Your site will survive so far :) 

It will very probably get solved for the next release.

**Comment by kumar0521** [comment]
I know this is warning but due to delay in section loading . App behaving differently in chrome. 
Please guide me any alternative solution for that problem. if you have find any thing.

Thanks

**Comment by alvarotrigo** [comment]
> Please guide me any alternative solution for that problem. if you have find any thing.

The alternative is  you waiting for the new release :) 
If you really need a fix as soon as possible [contact me](http://alvarotrigo.com/#contact-page) for an urgent fix request and I'll provide you with a quote.

**Comment by alvarotrigo** [comment]
I am not able to reproduce the issue in the fullpage.js [demo page](http://alvarotrigo.com/fullPage/). 
Please provide a reproduction in jsfiddle or codepen with the isolated reproduction and no external JS or CSS.

**Comment by alvarotrigo** [comment]
Ok, nevermind. Found a reproduction in this other demo:
http://alvarotrigo.com/fullPage/examples/normalScroll.html#3rdPage

**Comment by alvarotrigo** [comment]
This might not have a solution in case of using `scrollBar:true` as fullPage.js prevents the default wheel action [here](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1245).

According to the [Passive event listeners explanation](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md) the passive events only make sense when not calling `preventDefault`.

> Smooth scrolling performance is essential to a good experience on the web, especially on touch-based devices. All modern browsers have a threaded scrolling feature to permit scrolling to run smoothly even when expensive JavaScript is running, but this optimization is partially defeated by the need to wait for the results of any touchstart and touchmove handlers, which may prevent the scroll entirely by calling preventDefault() on the event. While there are particular scenarios where an author may indeed want to prevent scrolling, analysis indicates that the majority of touch event handlers on the web never actually call preventDefault(), so browsers often block scrolling unneccesarily. 

And I guess they prefer to show a warning when calling preventDefault ?

**Comment by alvarotrigo** [comment]
This was solved in newer versions of Chrome.
