### ISSUE TITLE
Fullpage js onleave not working in responsive

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2312]
events not working in responsive while enabling responsivewidth:768px;, onleave and afterLoad not working . i'm using fullPage 2.6.4 version is this problem ah?..

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
> i'm using fullPage 2.6.4 version

Support is only provided for the latest version 2.8.6.

**Comment by cvaraj** [comment]
what can i do for lower version ..

**Comment by alvarotrigo** [comment]
@cvaraj why not update to the latest? It is not a major update, Still in version 2, which  means it will be totally compatible.
