### ISSUE TITLE
Fullpage js in responsive onLeave and afterLoad not working 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2314]
Fullpage js in responsive onLeave and afterLoad not working , 

while i'm declare responsiveWidth is 768, afterLoad and onLeave not working

sorry for my english

$('#fullpage').fullpage({
				responsiveWidth:768,
				afterLoad: function(anchorLink, index){
					alert(index);
				},
				onLeave: function(index, nextIndex, direction){
					alert(nextIndex);
				},
				
			 });

**Comment by alvarotrigo** [comment]
Duplicated https://github.com/alvarotrigo/fullPage.js/issues/2312

**Comment by cvaraj** [comment]
@alvarotrigo  please tell some solution for that ..

**Comment by alvarotrigo** [comment]
@cvaraj update to 2.8.6.
If you still have the problem provide a link to an isolated reproduction in jsfiddle or codepen.
