### ISSUE TITLE
onleave in responsive 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2315]
onleave not working in responsiveWidth

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
