### ISSUE TITLE
Hi, I just bought your fading extension but cant get it to work. Checking the code of it, it looks pretty wired. Maybe your download file is corrupt?

### ISSUE THREAD

**Issue by tomfing** [alvarotrigo/fullPage.js#2317]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
You might be doing something wrong. 

Make sure you include it before fullpage.js as detailed [in the documentation](https://github.com/alvarotrigo/fullPage.js#use-extensions).
Then make sure you use the option `fadingEffect:true`.

If you still having troubles [contact me](http://alvarotrigo.com/#contact-page) and provide me a link with the site having the issue.
