### ISSUE TITLE
fullscreen Video-Background not working on Mircosoft Edge

### ISSUE THREAD

**Issue by wfabian** [alvarotrigo/fullPage.js#2318]
I like to have a fullscreen Video-Background on a section/slide.
Everything is fine on Mac and on Google Chrome on Windows.
But in Mircosoft Edge (Windows 10) it doesn't work. The video is fitted to the height/width of the browser.
A screenshot is attached. 
This is my test: http://alvarotrigo.com/fullPage/examples/videoBackground.html

Is there anyway to fix that problem?

![screenshot](https://cloud.githubusercontent.com/assets/6770572/19236049/83ac9028-8ef5-11e6-8c3c-166f1493fb48.png)

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue. But a browser and CSS one. You'd better ask in other place such as http://stackoverflow.com/
