### ISSUE TITLE
fadingEffect toggle is broken

### ISSUE THREAD

**Issue by ElectricEnjin** [alvarotrigo/fullPage.js#2319]
When using the fadingEffect extension on (2.8.6), calling the $.fn.fullpage.fadingEffect.turnOff() or turnOn() results in an error:

fadingEffect.html:42 Uncaught TypeError: $.fn.fullpage.fadingEffect.turnOff is not a function

to reproduce, just try the demo link:
http://alvarotrigo.com/fullPage/extensions/fadingEffect.html

**Comment by alvarotrigo** [comment]
@ElectricEnjin thanks for reporting it. It seems I updated the example file before releasing the new version of the extension.

I'll update it tomorrow and you'll get notified by mail in order to get the new version of the extension.

**Comment by alvarotrigo** [comment]
[The demo](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html) was updated. And now it works as expected.

A new version of the Fading Effect extension has been sent to everyone who bough it including this two new features to turn on and off the effect.
