### ISSUE TITLE
Double scroll with scrollOverflow: true on normalScrollElements [videos]

### ISSUE THREAD

**Issue by reddo** [alvarotrigo/fullPage.js#2321]
I'm using fullPage v 2.8.7 (dev version) and I have an overflow element (also initialized with iScroll) inside a section, it's added to normalScrollElements, but when I scroll over the element the whole section scrolls with it; see this video: https://drive.google.com/open?id=0B43KK3gJHYn4OFI3SENzWDZmRXM

It also happens on normal overflow elements, not initialized with iscroll: https://drive.google.com/open?id=0B43KK3gJHYn4UF9sdmtNNnpwYUE

Any idea what might be causing this?

I'm setting up a jsfiddle example, I'll post the link when I'm done.

**Update:** here's the jsfiddle link: http://jsfiddle.net/reddo/0y6kh4eL/2/ - try scrolling over the .left element and see that the whole section scrolls.

**Comment by alvarotrigo** [comment]
> It also happens on normal overflow elements, not initialized with iscroll:

Your fiddle works perfectly when removing the option `scrollOverflow:true`. 
Therefore the problem seems only be whe nusing both scrollbars together. 

I'll update the title of the issue, but I don't consider it a  high priority.
I'll mark as an enhancement.

**Comment by alvarotrigo** [comment]
This is no longer a problem on fullPage.js version 4 🥳
