### ISSUE TITLE
JS order is mandatory but not declared

### ISSUE THREAD

**Issue by yudircks** [alvarotrigo/fullPage.js#2322]
According to documentation in github you are adding `scrolloverflow.js` before the `jquery.fullPage.js` but if this order is mandatory then it should be notified. If you guys try to add `scrolloverflow.js` after `jquery.fullPage.js` then it is throwing error if you try to go back to previous slide.

**Comment by alvarotrigo** [comment]
> but if this order is mandatory then it should be notified

What do you mean?  Notified where? In the JS console?
It is quite clear in the docs.

**Comment by yudircks** [comment]
This thing is no where mentioned that `scrolloverflow.js` should be kept before `jquery.fullPage.js`

**Comment by alvarotrigo** [comment]
Yep, here you have it:

> **scrollOverflow:** (default false) defines whether or not to create a scroll for the section/slide in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor library scrolloverflow.min.js and **it should be loaded before the fullPage.js plugin**. For example:
```html
<script type="text/javascript" src="vendors/scrolloverflow.min.js"></script>
<script type="text/javascript" src="jquery.fullPage.js"></script>
```

**Comment by yudircks** [comment]
appologies.
