### ISSUE TITLE
Customised Vertical Slider Scrollbar

### ISSUE THREAD

**Issue by valenciayu** [alvarotrigo/fullPage.js#2324]
Is it possible to have a customized vertical scrollbar that is similar as the one found on this website http://fantasy.co/?

The scrollbar corresponds to the number of slides on each page. It will resize with the browser, and also works on mobile devices.

**Comment by alvarotrigo** [comment]
I don't see why not. You just have to create it yourself :) 
I'll close the issue and its not directly related with fullPage.js.

**Comment by alvarotrigo** [comment]
It seems that site is making use of iScroll.js.
