### ISSUE TITLE
Unable to click links on ios

### ISSUE THREAD

**Issue by scottwvw** [alvarotrigo/fullPage.js#2327]
While using the fullpage plugin, with the fade extenstion (although I get the same issue without the extension) I'm unable to click the links/content within each section on mobile (only tested on ios)

here's a link to my project
http://www.scottvanwinden.com/dirtysouth/

Does anyone know how to solve this issue?

Thanks

**Comment by alvarotrigo** [comment]
That's weird. Can you please reproduce it i in jsfiddle or codepen with the standard fullPage.js.?

**Comment by scottwvw** [comment]
Oh hang on, the bandsintown plugin was conflicting with it. seems to be all sorted now.
