### ISSUE TITLE
destroying problem 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2328]
while using ajax loadmore, first  i will destroy the fullpage js and then initialize, after that it will take to top of the page but i need to be page in same position . why it will took to top

jQuery('#fullpage').fullpage.destroy('all');
triggerfullwidth();

**Comment by alvarotrigo** [comment]
That's not fullPage.js responsibility but your own.
You'd better ask in http://stackoverflow.com/
