### ISSUE TITLE
ajax load more issue 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2329]
i have using ajax load more i can update height of scroll bar using Rebuild method but when i scroll first time it wil goes to bottom of the page after that it will comes to top and working fine.. what to do for that first scroll .

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
