### ISSUE TITLE
Scroll Sensitivity Extremely High for iScroll within Slide on Desktop

### ISSUE THREAD

**Issue by aksperiod** [alvarotrigo/fullPage.js#2330]
### Scroll Sensitivity Extremely High for iScroll within Slide on Desktop
It is basically unusable. Why is this happening, and why is it working fine on mobile?

### Link to isolated reproduction with no external CSS / JS
[Demo](https://aksperiod.github.io/london/demo.html)

### Versions 
Chrome 53, Safari (works fine on mobile)

**Comment by alvarotrigo** [comment]
You are using some `iscroll-snap` feature that is not of fullPage.js but of iScroll.js. You'd better ask in their issues forum.

**Comment by aksperiod** [comment]
But this feature obviously works in vanilla iScroll, also this seems like an important bug in fullPage.js

**Comment by alvarotrigo** [comment]
@aksperiod fullPage.js requires of iScroll.js for a very specific purpose. This means fullpage.js assures the correct behavior of iScroll for that specific feature in fullPage.js, but this doesn't mean that fullPage.js is totally compatible with all features of iScroll.js.

fullpage.js was never tested using the snaps functionally (or the other 80% of iScroll options) and nowhere in the fullPage.js documentation this feature is said to be supported.

**Comment by aksperiod** [comment]
Okay, I see now, plus I think that iScroll's snap feature is actually broken with the mousewheel, as there are no working examples online. Sorry for blaming fullpage.
