### ISSUE TITLE
chrome mousewheel scrolling issue 

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2331]
when i use page transition animation for redirect page without reload its working fine but while scrolling in chrome using mousewheel it struck for 1 or 2 milleseconds, but keyboard scrolling  working fine its only in chrome . like this popstate also same issue when i click browser back button without page reloading its same problem is coming ..

is there any solution for this ..

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
