### ISSUE TITLE
add scrolloverflow while using afterRender callbacks

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2332]
can i  use scrolloverflow:true while using afterRender callback function.. is this possible ?..

**Comment by alvarotrigo** [comment]
Not quite sure to understand your question.... 

`scrollOverflow` loads on page load. Always. It needs to be that way to be able to deal with images and other content that won't be loaded on document ready.

You can try using the `reBuild` function inside afterRender if you want to fire it on document ready. But not sure about the result.
