### ISSUE TITLE
Unable to click on buttons and links in mobile devices (IPhone 6S Safari Browser)

### ISSUE THREAD

**Issue by manorepo** [alvarotrigo/fullPage.js#2333]
### Description
I tried with the demo site http://www.alvarotrigo.com/fullPage/
I am unable to select the Download button in the first section.

### Link to isolated reproduction with no external CSS / JS
http://www.alvarotrigo.com/fullPage/

### Steps to reproduce it
Try to click on Download button in the first section
### Versions 
fullPage - 2.8.7
Device - IPhone 6S

Many Thanks,
Mano

**Comment by alvarotrigo** [comment]
> Try to click on Download button in the first section

The download button links a file to download. Which it is never handled by iOS browsers when its a `zip` file as there's no way to store that in iOS.

Any other link works as expected. Examples, documentation, wordpress theme...

**Comment by manorepo** [comment]
Hi
Thank you for looking into this. I observe that those Examples, documentation, WordPress theme... are outside of fullpage sections. The links/Buttons inside the sections are not working.

Please find below URL as an example,  try to open it in mobile and click on the 2 buttons (one inside the section and another outside the sections). The button inside the section is not triggering the event.

https://jsfiddle.net/manoharkotapati/dq81a2c0/4/
