### ISSUE TITLE
Fullpage not working on mobile

### ISSUE THREAD

**Issue by asalimzhanov** [alvarotrigo/fullPage.js#2335]
I cannot make it work on mobile. On mobile devices the website even is not scrolled by fingers. I have looked at the example here http://alvarotrigo.com/fullPage/examples/responsive.html. The same behaviour. I don' know what is wrong

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 
Fixed [in dev](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by digitalprecision** [comment]
Will this fix the issue when viewing a site with fullpage.js via a webview api wrapper on android? On page load it only shows a small slice of the top of the page.

**Comment by alvarotrigo** [comment]
> Will this fix the issue when viewing a site with fullpage.js via a webview api wrapper on android?

No idea, you'll have to try it yourself :) 
Just make sure to use the `dev` file and not the production one.

**Comment by allienworks** [comment]
I had the same issue, `jquery.fullpage.extensions.min` from dev branch fixed it; thanks much!

**Comment by alvarotrigo** [comment]
Merged in 2.8.8
