### ISSUE TITLE
Fullpage extensions min js does not auto-pause html5 video on section leave

### ISSUE THREAD

**Issue by wollamooloo** [alvarotrigo/fullPage.js#2336]
### Description
**For a project we needed the resetSLides plugin. In order for this to work we included the fullpage.extensions.min.js. This caused HTML5 video's to keep playing after you switch sections (vertical). It pauses the video's when you shift slides (horizontal).**

### Steps to reproduce it
1. Used standard code for HTML5 video using the fullpage docs data-src and data-autoplay features with fullpage.js included > everything works fine.
2. Included fullpage.resetSliders.min.js and fullpage.extensions.min.js > video's do not pause anymore on section leave only on slide leave
3. Switched back to fullpage.js (with fullpage.resetSliders.min.js) > everything back to normal
4. Back to extensions.min.js > Switched off concatenation and minifying just to be sure > video pausing issue re-ocurred.

### Versions 
[Chrome, OSX 10.12, MacbookPro mid 2015, Codekit2, Coda2]

Thank you in advance.

**Comment by alvarotrigo** [comment]
Fixed in the dev branch. You can now download the [dev extensions file](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js) to solve the issue.

**Comment by alvarotrigo** [comment]
@wollamooloo sorry, forgot to update the file for the extension. I've sent a mail to all buyers now.

**Comment by wollamooloo** [comment]
Yisss! :) Everything's working beautiful! Thank you again!

**Comment by alvarotrigo** [comment]
Merged in 2.8.8
