### ISSUE TITLE
touch Event

### ISSUE THREAD

**Issue by jbsness** [alvarotrigo/fullPage.js#2337]
Hi and thanks for your work.

For touch device, all click event inside the fullpage container does not work. I tried to use normalScrollElements but without success.

Ex: In your [demo page](http://alvarotrigo.com/fullPage/) the download button int the first section does not work on mobile or tablet.

Is there a solution to do this ?

Thanks,
Jules

**Comment by alvarotrigo** [comment]
Duplicated https://github.com/alvarotrigo/fullPage.js/issues/2333
