### ISSUE TITLE
Event touch (verified)

### ISSUE THREAD

**Issue by jbsness** [alvarotrigo/fullPage.js#2338]
Hi,
sorry to insist but there is an issue on touch device : unable to click on buttons and links with the latest version (2.8.7)

Check these two links and click on the button, the only thing I changed is the link to the version

[version 2.8.6](http://www.maquette.jbsness.fr/github/) (works on touch device)

[version 2.8.7](http://www.maquette.jbsness.fr/github_new/) (does not works)

Thanks,
Jules

**Comment by alvarotrigo** [comment]
Can you change the minified fullPage.js file for the unminified one please?
That'd help to debug.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! Now it makes sense. We are not talking about links about about click / touchstart events.

Related with https://github.com/alvarotrigo/fullPage.js/issues/2285

The preventing of the default behavior [here](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1183) is causing the issue.

Mmm... it seems I'll have to try to look for another solution.

**Comment by alvarotrigo** [comment]
Let me know if it has been fixed for you in the [dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js).

**Comment by jbsness** [comment]
Hi,
perfect it's works !

Thanks,
Jules

**Comment by reddo** [comment]
Niether scrolling, nor clicking on buttons was working for me either before the fix. 

I confirm it's fixed on dev though.

**Comment by dogee** [comment]
Hi, 
I build a responsive project and I have issues too with touch events.
The select fields are not working on my device (OnePlus X) and on my computer with chrome device toolbar.
But this is working fine on desktop mode.

Here is a link to my [project](http://clients.pointligneplan.fr/chanel/coe/watch#page3)
I put the latest dev version of fullpage.js.

Thanks.

**Comment by alvarotrigo** [comment]
@dogee please be more specific or provide a reproduction in jsfiddle or codepen without external CSS or JS files and the minimum code required for it.

Which events are not working? Link? click event? touch start? Where are you applied them? 
Which code are you using the apply it? Over which HTML elements?

**Comment by alvarotrigo** [comment]
@dogee can you please try again? I've updated the dev version again with another change which I believe might solve the issue in a much better way.

**Comment by dogee** [comment]
Hi alvarotrigo,

Sorry for the delay. I try your latest version but this is not working yet.

I create a codepen. In this codepen, I use only the fullpage script (css and js). And of course the script to initialize the fullpage.

[Editor view](http://codepen.io/dogee/pen/rrQQaG)

[Debug view](http://s.codepen.io/dogee/debug/rrQQaG)

Again, this is working in desktop mode but not in device mode. When you click on a select field, the dropdown is not showing.

For me, I don't need the scroll touch thing, so if there is a way to disable the scroll system, I'll take it. But anyway there is a bug :)

**Comment by alvarotrigo** [comment]
> When you click on a select field

I don't see any "select field" text anywhere. 
The dropdowns are working fine for me in my iphone iOS and I can see them working as well in Chrome dev tools on device mode.

**Comment by dogee** [comment]
[screenshot](https://clients.pointligneplan.fr/chanel/select-bug.png)

This happen on my boss computer too.

**Comment by alvarotrigo** [comment]
@dogee sorry but I don't understand what your image is trying to say. What's that black thing? 
You didn't answer my questions. Device, browser, OS version?

**Comment by dogee** [comment]
Alright I run some tests on my android and on an iPhone and it's working.
So I think my chrome isn't working as expected.

Sorry for that.
Please let this thread open until tomorrow in case I found something more.

Thanks a lot for your availabilty.

**Comment by mktweb** [comment]
Hi @alvarotrigo,
I encountered the same problem when I insert a link only with plain text, ie desktop works correctly, but mobile, the links are not touchable.
The strange thing is that I insert the link in image form, everything works perfect.
Do you have any idea what is this bug?

**Comment by alvarotrigo** [comment]
> P.S. I`m using dev branch

I need a reproduction online to help you.

**Comment by mktweb** [comment]
You can see in [this link](http://www.4exalt.com.br/incomparavel/teste.php)

I`m testing in minified and unminified and both results are equal... Currently is unminified version.

**Comment by alvarotrigo** [comment]
@mktweb  you are not using the latest extensions file. Download it again. I changed it hours ago.

**Comment by mktweb** [comment]
Wow, perfect!!!
It is working perfectly!!!

I'm so gratefull to your help...

**Comment by alvarotrigo** [comment]
Merged in 2.8.8

**Comment by jbsness** [comment]
Hi,
I updated the last version 2.8.8
I think you have an issue with your minified js file because it does not works with it but works with the unminified

**Comment by alvarotrigo** [comment]
@jbsness link with a reproduction.

**Comment by jbsness** [comment]
here it is :
- [minified 2.8.8 version](http://www.maquette.jbsness.fr/github_2-8-8-min/)
- [unminified 2.8.8 version](http://www.maquette.jbsness.fr/github_2-8-8/)

**Comment by jbsness** [comment]
oh it's still the version 2.8.7 for the minified version in your zip file

**Comment by alvarotrigo** [comment]
@jbsness it was updated a few minutes later. Probably wasn't updated in npm. But you can get it from the dist folder. Which is the one you should be using anyways.

**Comment by jbsness** [comment]
Ok perfect,

Thanks
