### ISSUE TITLE
Is it possible to lazyload slides within a section?

### ISSUE THREAD

**Issue by nanc4t** [alvarotrigo/fullPage.js#234]
Hi, I read through a similar bug but can't figure out lazyload-ing individual slides within a section like you had mentioned in: 
https://github.com/alvarotrigo/fullPage.js/issues/46#issuecomment-26509996

Advice is much appreciated, and thanks for building this!!

**Comment by alvarotrigo** [comment]
Now you can lazy load images, videos and audio elements by using the new functionality introduced in fullpage.js 2.6.6:

https://github.com/alvarotrigo/fullPage.js#lazy-loading

**Comment by monolux** [comment]
If my slide HTML looks like this
```
<div class="slide" id="slide2" data-anchor="slide2">
            <h1>Slide 2</h1>
</div>`
```

and the CSS like this
```
#slide2{
		background-image: url(../img/img-002.jpg);
		padding:0;
		margin:0;
}
```
how or better where would I put the `data-src` attribute?

Or do I have to follow the HTML markup like shown in the [demo for lazy loading](http://codepen.io/alvarotrigo/pen/eNLBXo) **of slides** to be properly working?
```
    <div class="section">
       <div class="slide" data-anchor="slide1">
       <img src="" data-src="https://raw.githubusercontent.com/alvarotrigo/fullPage.js/master/examples/imgs/iphone-blue.png" />
       </div>
        <div class="slide" data-anchor="slide2">Two 2</div>
    </div>
```
Thank you for helping me understand this better.

**Comment by honeyamin** [comment]
hi there.
1-i use envira gallery plugin in wordpress 
2- i make a masonry gallery that will load images when you scroll (lazy load)
issue: when scroll to end of section it doesn't go to next section, i use scrollOverflow:true and there isn't any way that i use "rebuild" because i don't know that when last image loade.
tnx for your help
