### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by kikeestrada** [alvarotrigo/fullPage.js#2340]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by kikeestrada** [comment]
Hi It's possible use the conticontinuous Horizontal Slider?

I can use Just in Vertical but not in Horizontal

Best Regards!

**Comment by alvarotrigo** [comment]
Read the docs...

> **continuousHorizontal:** (default false) [Extension of fullpage.js](http://alvarotrigo.com/fullPage/extensions/). Defines whether sliding right in the last slide should slide right to the first one or not, and if scrolling left in the first slide should slide left to the last one or not. Not compatible with loopHorizontal. Requires fullpage.js >= 2.8.3.

You need to get the extension first.
