### ISSUE TITLE
Background attachment fixed not working - for scrollbar:false

### ISSUE THREAD

**Issue by priyankamotiani** [alvarotrigo/fullPage.js#2341]
Hi,

Background-attachment: fixed property of CSS doesnt work with - scrollbar:false.

I have 2-3 sections having same background and want to look like its a same section - only text changes and not background.

Any idea whats the issue.

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue but a browsers bug when using transform3d and fixed elements.
See this: http://stackoverflow.com/questions/23571578/chrome-issue-with-background-attachment-fixed-and-position-fixed-elements
