### ISSUE TITLE
About Slides Navigation

### ISSUE THREAD

**Issue by enkhtulga** [alvarotrigo/fullPage.js#2343]
Hello,

Is it possible to set text instead of slide navigation circles? I wonder that how to know next slide url while clicking a tag with #. And how to know how many slides are there.

for example:
I have 4 slides. I used * instead of small circles.

Now: * * * *
What i want:         Slide One    Slide Two      Slide Three     Slide Four

When i click text it will switch to current slide.

Thank you,
Enkhtulga.G

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide such option. 
The more you can do is use `showActiveTooltip` that will show not only the bullets but also the tooltip text of the current active section.

Your solution can be overwriting the CSS applied to the tooltips and make them always visible. Then, hide the bullets.

Easy uh? :)

If you do not know how to do it, you'd better ask in other place such as stackoverflow.com for questions regarding CSS knowledge.

**Comment by enkhtulga** [comment]
Hello,

Thank you. I have solved another way.
