### ISSUE TITLE
Extension license key not working

### ISSUE THREAD

**Issue by CorpusCallosum** [alvarotrigo/fullPage.js#2345]
### Description
I have purchased the license for the continuousHorizontal extension, and I have added the extension and key to my app. It is working fine when I test it locally, however when I upload and test the site remotely, I am getting a notification in the upper-left corner that says "Unlicensed fullpage extension". Not sure what I am doing wrong here?

### Link to isolated reproduction with no external CSS / JS
https://corpuscallosum.github.io/mcny-core-g3/neighborhoods.html

### Versions 
Same problem on desktop Chrome and iPad Safari

**Comment by alvarotrigo** [comment]
[Contact me](http://alvarotrigo.com/#contact) and provide me with the email you used to buy the extension.
You are using the license key, not the activation key.
A mail was sent to you when buying the extension (or later if bough it more than a week ago) with the link and instructions of how to get the activation key from the license key.
