### ISSUE TITLE
Scrolling bug with new install of fullpage.js

### ISSUE THREAD

**Issue by Prawx** [alvarotrigo/fullPage.js#2347]
When scrolling down, it seems to scroll past my last page ONLY when I set a background for it, or the page before. Since that probably sounds confusing, here's a video of it occuring
https://drive.google.com/file/d/0BzHs8dwa7fEsUDg4UGNHbzQyajQ/view?usp=sharing
or just visit www.villarosano.com/home.php and view it live
to explain that video, the painting is the last page, but when you scroll to it, it scrolls past it and pretends like there is a blank empty page as the last page. To view the page, I have to scroll back up and then back down, or click on the page on the menu.

Please help! Thanks

**Comment by Prawx** [comment]
here is a pastebin of my settings, html, and css
http://pastebin.com/jR0G9KV4

**Comment by alvarotrigo** [comment]
Look your javascript console. It is full of errors:

> jquery.fullPage.js:2850 fullPage: data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).showError @ jquery.fullPage.js:2850
> jquery.fullPage.js:2850 fullPage: "intro" is is being used by another element `id` property
