### ISSUE TITLE
section separator

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#2349]
say, is there a way to add a separator line between two sections in a div or somehow, which could only be seen whilst transition animation is happening?

thanks!

**Comment by alvarotrigo** [comment]
Not at the moment. 
Related with https://github.com/alvarotrigo/fullPage.js/pull/85

**Comment by asdangus** [comment]
thanks for the answer, will be waiting for a possible update ..
my usage scenario is that two pages are of similar color, which when put together side by side produce ugly contrast, - got to separate them. fp-auto-height seems right for it, so it would be real neat if certain sections could be assigned to be ignored when scrolling, or that all sections that are to be scrolled through would be listed in js, ignoring the rest ..

**Comment by alvarotrigo** [comment]
There's a workaround. 
See [this response](https://github.com/alvarotrigo/fullPage.js/issues/2052#issuecomment-223256222) and the example in it.

**Comment by asdangus** [comment]
oh cool, that's almost perfect! but is there a way to skip that section when scrolling back up? sorry i'm real bad in JS ..

**Comment by alvarotrigo** [comment]
Just modify the code in the callback.

**Comment by asdangus** [comment]
what can't one do with a little bit of encouragement! thanks it worked. nice weekend there ..
