### ISSUE TITLE
don't work in IE8

### ISSUE THREAD

**Issue by tangjion** [alvarotrigo/fullPage.js#2350]
I copy this URL in IE8 "http://alvarotrigo.com/fullPage/",It's not work,what can I do?Place give me a help?Thanks!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.8.9

**Comment by tangjion** [comment]
thanks for your reply

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9
