### ISSUE TITLE
Menu only works on mobile if fixed

### ISSUE THREAD

**Issue by Prawx** [alvarotrigo/fullPage.js#2351]
I have a menu on my first page that I do not want to be fixed, and it works fine on all devices other than mobile.

Removing this: http://pastebin.com/iYshmCcC allowed me to have a non-fixed menu. However, every anchor in my menu goes nowhere on mobile devices if I don't have position: fixed set on the menu. 

my settings: http://pastebin.com/7ztGPEE6

my menu html: http://pastebin.com/zuRxXGVg

I understand that the instructions advise against having a menu inside of a section, but there's no reason that it should work perfectly fine on desktop but not on mobile. please help! thank you, i'll consider donating to fullpage.js once I'm finished with my project for all the help, very much appreciate you man.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Prawx** [comment]
Okay, I'll reproduce it. Go here and see that the menu works on desktop:
http://villarosano.com/example.html
and then go to it on your phone and see that the menu does not work.

Here is the html file of that exact page:
http://pastebin.com/6X7VFBCy
 Once again, the only other change I made that is not in the above html file is removing this code:
http://pastebin.com/iYshmCcC
from line 792 of jquery.fullPage.js

The reproduction of the problem is in the first pastebin.
I simply:

- Setup fullpage.js as you normally 

- Used the settings in the pastebin

- Fullpage.js worked fine, I created a new list on the first page with id="nav"

- I set #nav as the menu in fullpage.js

- I created a list item for every page other than the first page (the one the list is on)

- I added the corresponding data-menuanchor to every list item as well as href="#pageAnchor"

-  I used the menu on my computer, it worked fine. I used it on my phone, none of the buttons go anywhere, even if i try making them links to a different site.

I appreciate it if you help me, I'm almost done with my site and this is one of the things really delaying me right now. Thank you!

**Comment by Prawx** [comment]
So on http://villarosano.com/fixed.html

I added position: fixed; to #nav

and added `            //moving the menu outside the main container if it is inside (avoid problems with fixed positions when using CSS3 tranforms)
            if(options.menu && options.css3 && $(options.menu).closest(WRAPPER_SEL).length){
                $(options.menu).appendTo($body);
            }`

back to fullpage.js and it works fine on mobile when it's fixed...
whatever it is that prevents non-fixed elements from functioning properly is what's causing the problem. there's no reason it should work on desktop just fine but not on mobile. I can't have it fixed, my menu needs to be just on the first page on mobile.

**Comment by alvarotrigo** [comment]
Please use the latest fullPage.js 2.8.8.
If you still having the problem I'll re-open the issue.

**Comment by Prawx** [comment]
http://pastebin.com/biKiRqW5

updated and it works, thank you for pointing out that i wasn't on the latest version.
phew.
