### ISSUE TITLE
Unable to override touch action in css file

### ISSUE THREAD

**Issue by vignesh-subash** [alvarotrigo/fullPage.js#2352]
I am trying to give some effects (sketch.js) to the background but we cant able to implement that  js effect with current touch-action css property. how to override the css property?

I am trying use below bg effect to the current full page website.i want those effect only on Margin of top, left, right with 60px size. 
http://soulwire.github.io/sketch.js/examples/particles.html

**Comment by alvarotrigo** [comment]
> how to override the css property?

That's a CSS knowledge question.

Use `!important`. If You don't know how, ask in other place such as stackoverflow.com.

**Comment by vignesh-subash** [comment]
Thanks for the reply and we found out the solution inside your jquery.fullpage.js and not in the css file.! :) :) Thanks for the great work and keep creating wonderful js works.
