### ISSUE TITLE
iScroll on page load scrolling not working

### ISSUE THREAD

**Issue by Bondra** [alvarotrigo/fullPage.js#2353]
Hi!

In the latest version of fullpage.js the iScroll Mousewheel scrolling won't work if it's applied to a section that comes first in the DOM.

When it's first (not working)
https://jsfiddle.net/15s3rjjn/5

When it's not first (working)
https://jsfiddle.net/15s3rjjn/4/

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 
The problem has been fixed on the dev branch version 2.8.9.

Will be merged for the next release.

**Comment by Bondra** [comment]
No problemo! Thank you for a fantastic plugin!

**Comment by makito** [comment]
The same window size after change

**Comment by alvarotrigo** [comment]
@makito I dont understand your comment at all :)

**Comment by makito** [comment]
Sorry for my English :)
The same after change window height.

**Comment by alvarotrigo** [comment]
@makito sorry but I still don't understand what you are talking about.

**Comment by Bondra** [comment]
Alvarotrigo when will this fix be released? :)

**Comment by alvarotrigo** [comment]
@Bondra whenever I can :) Hopefully today.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9
