### ISSUE TITLE
Vertical en horizontal scrolling

### ISSUE THREAD

**Issue by Dylannjs** [alvarotrigo/fullPage.js#2354]
Hi i have a question.

Is it possible to make a website like [this](https://www.activeview.nl/#!/).

it is almost the same as your fullpagejs but the head items in the menu have to be scrolling horizontal and the "slides" has to be vertical.

thanks in advance.

**Comment by alvarotrigo** [comment]
> Is it possible to make a website like this.

Nop. 

The most you can do is something like what suggested in [this topic](https://github.com/alvarotrigo/fullPage.js/issues/200) by using the interlocked slides extension. 
But in any case, you will never be able to go from slide 2 section 3 to slide 3 section 1. (slides are the horizontal ones and sections the vertical ones) 
You'll always have to move on the same section level if you want to turn right or left.
