### ISSUE TITLE
Disable keyboard up and down on slides

### ISSUE THREAD

**Issue by gNesh01** [alvarotrigo/fullPage.js#2356]
Hi, 
Thanks for the great plugin and fast response! 

I would like to disable up and down mouse and keyboard scroll on slides. I saw similar question back in 2013. but with new features, I guess its doable.

I have simple structure:
```
<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">
        <div class="slide"> Slide 1 </div>
        <div class="slide"> Slide 2 </div>
        <div class="slide"> Slide 3 </div>
        <div class="slide"> Slide 4 </div>
    </div>
    <div class="section">Some section</div>
</div>
```

1) Scroll down get me to Section 2 - slide 1
2) Scroll right  gets me to Section 2 - slide 2
3) Scroll down and up now shoudn't do anything! 

So, on slides, more then 1, I would like just to left and right to work. My wish is when user gets in slide 2, he can go left and right, but when on slide 1, he again can go up and down.

In your docs I've found:
```
$.fn.fullpage.setAllowScrolling(false, 'up, down');
$.fn.fullpage.setKeyboardScrolling(false, 'up, down');
```

But I have no idea how to initialize it.

Thanks

**Comment by alvarotrigo** [comment]
> But I have no idea how to initialize it.

Like this:

```javascript
$('#demo').click(function(){
    $.fn.fullpage.setKeyboardScrolling(false, 'up, down');
});
```

In your case you might want to use it in the callbacks provided by fullPage.js](https://github.com/alvarotrigo/fullPage.js#callbacks).

If that's not enough for you, then you need to learn Javascript / jQurery. You'd better ask in other place such as http://stackoverflow.com/ for basic Javascript knowledge.

**Comment by gNesh01** [comment]
Callbacks did the trick. Thanks!

Here is my solution if someone needs it:

```
afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
    var loadedSlide = $(this);

    if(slideIndex === 0){
        $.fn.fullpage.setAllowScrolling(true, 'up, down, left, right');
        $.fn.fullpage.setKeyboardScrolling(true, 'up, down, left, right');
    }
    if(slideIndex === 1 || slideIndex === 2){
        $.fn.fullpage.setAllowScrolling(false, 'up, down');
        $.fn.fullpage.setKeyboardScrolling(false, 'up, down');
    }
}
```
