### ISSUE TITLE
Normal scroll mode does not work on ios.

### ISSUE THREAD

**Issue by claytonmeador** [alvarotrigo/fullPage.js#2357]
### Description
Normal scroll mode does not work on ios.

http://alvarotrigo.com/fullPage/examples/normalScroll.html

### Steps to reproduce it
1. visit http://alvarotrigo.com/fullPage/examples/normalScroll.html
2. Touch scroll up or down
3. feel bad.

### Versions 
[ ios v. 10.0.1 - Safari - iPhone 6s ]

**Comment by alvarotrigo** [comment]
The demo page was not using the latest version 2.8.8.
Solved.

**Comment by claytonmeador** [comment]
Thanks!
