### ISSUE TITLE
What is the preferred for conditional use based on window size?

### ISSUE THREAD

**Issue by sheriffderek** [alvarotrigo/fullPage.js#2358]
### Description
What is the preferred for conditional use based on window size?
If the plugin should only function when width > x etc. for proper cleanup on browser resize?

### Link to isolated reproduction with no external CSS / JS
n/a

### Steps to reproduce it
n/a

### Versions 
n/r

**Comment by alvarotrigo** [comment]
Check the following options:

 - responsiveWidth
- responsiveHeight
- responsiveSlides

**Comment by sheriffderek** [comment]
Excellent. Thank you. There are so many options, that it's hard to navigate the readme. "Responsive width" could mean many things. It's also hard to tell if this just disables the functionality of if it actually tears down the plugin. If I were to create and Emberjs component, I would need to fully tear down the plugin, for example. I would consider adding a more explanatory heading. Thanks. : )

**Comment by alvarotrigo** [comment]
> I would need to fully tear down the plugin, for example

Then use `destroy`.

**Comment by sheriffderek** [comment]
In case anyone else finds this thread:

```
(function($) {
  'use strict';

  var setupFullPageScroll = function() {
    if ( $(window).width() > 1100 && $(window).height() > 680 ) {
      $('#fullpage').fullpage({
        sectionSelector: '.container'
      });
    } else {
      $.fn.fullpage.destroy('all');
    }
  };

  $(window).resize( function() {
    setupFullPageScroll();
  }).trigger('resize');

})(jQuery);
```
