### ISSUE TITLE
Keyboard down disabled and iScroll keyboard scroll enabled

### ISSUE THREAD

**Issue by gNesh01** [alvarotrigo/fullPage.js#2360]
Hi,
Is there anyway to scroll slide (up and down) with keyboard while setKeyboardScrolling (up and down) is set to false.

Here is my https://jsfiddle.net/6wcw8wgq/2/

As you can see on slide 1.2, 2.2 and 3.2 I have iScroll, also I've disabled any up and down scrolling. Thats fine.
Mouse scroll works perfect on 1.2, 2.2 and 3.2 slides and I would like for keyboard scroll works the same BUT not to change sections.

I've tried: `normalScrollElements` but with no luck.

Thanks

**Comment by alvarotrigo** [comment]
See the [iScroll options](http://iscrolljs.com/) to see if they provide keyboard scrolling and use the fullPage.js option `scrollOverflowOptions` to pass any custom ones.

**Comment by gNesh01** [comment]
Thanks! That was it!
