### ISSUE TITLE
onSlideLeave direction down

### ISSUE THREAD

**Issue by mibisc** [alvarotrigo/fullPage.js#2361]
Hi Alvaro

I have the extensions interlockedSlides and fadingEffect.

I would like to the following:
When I want to scroll down and I’m on the third slide in section 2, I want to return false (not allow to go further down) or go back to the third slide in section 1.
When I want to scroll down and I’m on the first slide in section 4, I want to return false (not allow to go further down) or go back to the first slide in section 1.

I tried with onSlideLeave, but there I don't have the direction down and up.
And I tried with onLeave and trying to find out the current slide and add cases.

Thanks for your answer.

**Comment by alvarotrigo** [comment]
> I tried with onSlideLeave, but there I don't have the direction down and up.

Becuase `onSlideLeave` is only for slides. Not for sections. 
You need to use `onLeave` instead.

Or I would probably recommend you to call `$.fn.fullpage.setAllowScrolling(false, 'down');` and `$.fn.fullpage.setAllowScrolling(false, 'up');`. on the callback `afterSlideLoad`. Maybe easier.

**Comment by mibisc** [comment]
Thank you for you answer, I already tried like that:
```
$('#fullpage').fullpage({
				anchors: ['firstpage','secondpage','thirdpage','pagefour','pagefive'],
				lockAnchors: false,
				scrollingSpeed: 1000,
				controlArrows: false,
				slidesNavigation: false,
				slidesNavPosition: 'bottom',
				loopBottom: true,
				fadingEffect:true, 
				fadingEffectKey: 'YXRlbXN0dWRpb3MuY2hfWTlFWm1Ga2FXNW5SV1ptWldOMGZoZA==',
				interlockedSlides: true,
				interlockedSlidesKey:'YXRlbXN0dWRpb3MuY2hfV3Q1YVc1MFpYSnNiMk5yWldSVGJHbGtaWE09MEdH',
        		afterLoad: function(anchorLink, index){	        		
					var loadedSection = $(this);
		            if(index == 2 || index == 3 || index == 4 || index == 5){
			            $.fn.fullpage.setAllowScrolling(false, 'left, right');
						$.fn.fullpage.setKeyboardScrolling(false, 'left, right');
						
		            }else{
			            $.fn.fullpage.setAllowScrolling(true, 'left, right');
			            $.fn.fullpage.setKeyboardScrolling(true, 'left, right');
		            }  
		        }
		        afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
					var loadedSlide = $(this);
					console.log(slideAnchor);
		            
		            if (index == 2 && slideIndex == 2){
			            $.fn.fullpage.setAllowScrolling(false, 'down');
						$.fn.fullpage.setKeyboardScrolling(false, 'down');
		            }
		        }
		    });
```


		            
Can it be, that when extensions interlockedSlides are true, anchorLink, index, slideAnchor in afterSlideLoad do not work?

**Comment by alvarotrigo** [comment]
@mibisc callbacks are working as expected when using the extension.
