### ISSUE TITLE
With responsiveHeight set, window height is still added to the sections

### ISSUE THREAD

**Issue by sheriffderek** [alvarotrigo/fullPage.js#2363]
### Description
With responsiveHeight set, window height is still added to the sections.

### Link to isolated reproduction with no external CSS / JS
http://codepen.io/sheriffderek/pen/xEZAAL

### Steps to reproduce it
1. Use fullPage
2. add responsiveWidth: 900, to the hash
3. view below 900

Thanks!.

**Comment by alvarotrigo** [comment]
> With responsiveHeight set, window height is still added to the sections.

Of course it does. It is suppose to work that way. 
The only difference is the autoScrolling is turned off as detailed in the docs:

> **responsiveHeight:** (default 0) **A normal scroll (autoScrolling:false) will be used under the defined height in pixels**. A class fp-responsive is added to the body tag in case the user wants to use it for his own responsive CSS. For example, if set to 900, whenever the browser's height is less than 900 the plugin will **scroll like a normal site.**

You might want to check the [`fp-auto-height-responsive`](https://github.com/alvarotrigo/fullPage.js#responsive-auto-height-sections) feature.
