### ISSUE TITLE
What are the .map files for?

### ISSUE THREAD

**Issue by digitalprecision** [alvarotrigo/fullPage.js#2364]
What are the .map files for? I noticed there are only minified versions, do they need to be included if the minified versions of fullpage and fullpage extensions are included?

**Comment by alvarotrigo** [comment]
[This](http://stackoverflow.com/questions/21719562/javascript-map-files-javascript-source-maps) answers your question.

Map files only make sense on the minified files. And no, they dont need to be added if you dont want to. They are only for developing purposes.

**Comment by digitalprecision** [comment]
Copy that. Thanks.
