### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by geraldasd** [alvarotrigo/fullPage.js#2365]
Hello, while I am trying to do the responsiveness between media queries. I noticed that the there is a delay in contents upon resizing.

![screen shot 2016-10-27 at 4 56 21 pm](https://cloud.githubusercontent.com/assets/20329027/19760986/9d264a48-9c66-11e6-8b7d-39b1c4d67ac0.png)
![screen shot 2016-10-27 at 4 56 23 pm](https://cloud.githubusercontent.com/assets/20329027/19760987/9d2d0ffe-9c66-11e6-8f34-e647d74a6fd0.png)
![screen shot 2016-10-27 at 4 56 24 pm](https://cloud.githubusercontent.com/assets/20329027/19760989/9d353350-9c66-11e6-8143-25b44ad4a94b.png)
![screen shot 2016-10-27 at 4 56 26 pm](https://cloud.githubusercontent.com/assets/20329027/19760988/9d2e5f30-9c66-11e6-9150-b64b9e125772.png)

**Comment by alvarotrigo** [comment]
Please provide a link to a reproduction.

**Comment by geraldasd** [comment]
Thanks for replying. I changed the background colour of the html, hence it will compliment the transitions. This didn't give me any problem anymore. Cheers.
