### ISSUE TITLE
Anchors option not functioning as expected

### ISSUE THREAD

**Issue by ahudson87** [alvarotrigo/fullPage.js#2366]
### Description
Have I misunderstood how the anchors option is supposed to work? I am using the anchors option inside the fullpage init function, trying to add an anchor point specifically to the second slide. Sections are generated dynamically (WordPress), so I can't hard-code the data-anchor into each section. I do know that I want my anchor to be the second section though, so there's no need for any anchors on any other section.

$('#fullpage-slider').fullpage({
...
anchors:['fullpage-home, fullpage-featured-homes-anchor'],
...
});

This configuration seems to add a data-anchor only to the first section:
data-anchor="fullpage-home, fullpage-featured-homes-anchor"
...but nothing added to subsequent sections.

I thought the second comma-separated value in this option would be applied to the second section, etc as more values are added.

It also throws an unexpected error:
Uncaught TypeError: Cannot read property 'top' of undefined

Any insight? Thanks-

### Link to isolated reproduction with no external CSS / JS
http://mls.liquinas.com/

**Comment by alvarotrigo** [comment]
> This configuration seems to add a data-anchor only to the first section:
> anchors:['fullpage-home, fullpage-featured-homes-anchor'],

This is like the game "count the differences". How many quotes do you see here and how many in yours?

    anchors:['firstPage', 'secondPage', 'thirdPage']

**Comment by alvarotrigo** [comment]
> Sections are generated dynamically (WordPress),

In this case you'd better use the attribute `data-anchor` in the section itself as detailed in the docs.

**Comment by ahudson87** [comment]
Hi Álvaro,

Thanks for pointing out my careless mistake. Works as-expected when I correct the quotations.

I'm still struggling with a solution though, because the way this page works is:
1st Section = Hero
2nd Section = Start of Dynamic Sections (this is the location I want to anchor to)
... As many sections as generated by WordPress (each would have the same data-anchor if added to mark-up, as it is part of the WordPress loop)
Last Section = Footer

So if I add the data-anchor to the 2nd section, which is where I want my page to slide to, that anchor is getting repeated and makes the anchor system fail.

I suppose what would be ideal is to just be able to put the anchor in the init options for section 1 and 2 (or even just section 2) because this much is always reliable, while the following sections will be variable. Seems that this throws errors if the option setting is not complete with all sections.

I may try to add a loop inside the init options which iterates over all sections after they render. Not sure if it will work but seems like a possible option.

Any other thoughts? Thanks again already-

**Comment by alvarotrigo** [comment]
> As many sections as generated by WordPress (each would have the same data-anchor if added to mark-up, as it is part of the WordPress loop)

That's no excuse to not provide a different anchor for each dynamic section/slide. 
But that's about PHP knowledge. So not a topic for this forum I'm afraid.
