### ISSUE TITLE
Scroll Slides Vertically

### ISSUE THREAD

**Issue by Divanvant** [alvarotrigo/fullPage.js#2369]
Hi There,

Thanks for creating this fantastic plugin!

I am trying to create a site where the sections scroll vertically and the slides also scroll vertically.

I have disabled scrolling so the site is navigated through two menus. The main menu for sections and a secondary menu that pops up on the section with the slides. When I reach this section I want the secondary menu to trigger the same vertical effect on the slides as the main menu triggers on the sections.

I hope this makes sense?

**Comment by alvarotrigo** [comment]
Use the `moveSectionDown` or `moveSectionUp` functions.
You might want to use the [interlocked slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html).
