### ISSUE TITLE
Broken in IE 9

### ISSUE THREAD

**Issue by adaptifyDesigns** [alvarotrigo/fullPage.js#237]
Hi, I couldn't find any browser compatibility documentation about fullPage.js.

I've developed a page http://www.safetec.net/know-your-chemicals-test/

It's working (as long as you don't try to open/close popup windows with the Learn More buttons, I'm still working on that), in modern browsers, but when I test in IE 9 (on browserstacks.com simulator) two things:
1. the fixed navigation element is nowhere to be seen. Not sure what that is about.
2. the scrolling functionality is completely broken. Neither clicking the next page arrow at bottom, or scrolling, nor clicking the down arrow on my keyboard will initiate a scroll to the next page.

I tested your demo page in the same browserstacks.com IE 9 simulator, and the scrolling functionality works just fine. But my page doesn't. Is there anything you can see in my config (found below the footer) that would be causing this? Thanks!

**Comment by sanjatubak** [comment]
Hi.
Even after including the jqueryui library I keep getting an error in IE9:
"Object doesn't support property or method 'easeInOut'"
Any ideas why?

**Comment by alvarotrigo** [comment]
@sanjatubak because `easeInOut` doesn't exist: http://jqueryui.com/easing/

**Comment by sanjatubak** [comment]
OMG, thanks. Somehow I missed it.
