### ISSUE TITLE
autoScrolling not working

### ISSUE THREAD

**Issue by vageliskatsiotis** [alvarotrigo/fullPage.js#2370]
### Description

Autoscrolling not working. Mouse scrolling works normally. All browsers.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
