### ISSUE TITLE
Resizing the window from the second slide cause the slide to move left outside the viewport

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2376]
### Description

- If you resize the window when on the first slide, the slide does not move, just its content resizes.
- If you do that from the second slide, that causes the slide to slip on the left outside the viewport before re-centering again.

Is there any solution to have every slide behaving like the first one?

### Link to isolated reproduction with no external CSS / JS
http://www.alvarotrigo.com/fullPage/#secondPage

**Comment by alvarotrigo** [comment]
> Is there any solution to have every slide behaving like the first one?

Nop.
FullPage.js needs to calculate the width and height of each section and slide, and then fix the position of the slides in the slider. 
This is done every [300 milliseconds](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L2067) to improve performance. 
You can try to change it to 0, but manually resizing the window will create a laggy experience (most noticeable yet in old or slow computers ).
