### ISSUE TITLE
Couldn't submit button and precheck checkbox

### ISSUE THREAD

**Issue by Gnomylka** [alvarotrigo/fullPage.js#2379]
### Description
Hi Alvaro,

I am using the plugin and I have the submit form on the page first before I update the plugin for current one I couldn't even click inside the input field, now i can but I couldn't check the checkbox and submit the sent button an issue only happening on Mobile and Tablet devices on iOS. also the section where I have the form has Scroll Overflow.
Could you please help me.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
