### ISSUE TITLE
Not work scrolling inside sections (first screen)

### ISSUE THREAD

**Issue by csscoderRU** [alvarotrigo/fullPage.js#2380]
### Description
I open http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage, scroll not work. After I key 'down' and scroll next screen and back to first screen - scroll work

I found this (Is it necessary?)

    //off by default until the section gets active
     iScrollInstance.wheelOff();

### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage

### Versions (fullPage.js 2.8.8)
[Chrome Version 54.0.2840.87 (64-bit), Mac OS 10.12.1, iMac]

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2353
