### ISSUE TITLE
Can't scroll with TrackPad or Mousewheel

### ISSUE THREAD

**Issue by sah-comp** [alvarotrigo/fullPage.js#2383]
I can't scroll (within) the section with trackpad or mousewheel on the demo page http://www.alvarotrigo.com/fullPage/examples/scrolling.html

When directly dragging the scrollbar I can scroll past the section and back. Once after doing so scrolling with trackpad or mousewheel works as expected.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2353
