### ISSUE TITLE
how to use bigSectionsDestination

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2385]
how to use bigSectionsDestination, i used this but i didn't see any changes in scrolling

**Comment by alvarotrigo** [comment]
Read the docs:

> bigSectionsDestination: (default null) Defines how to scroll to a section which size is bigger than the viewport. By default fullPage.js scrolls to the top if you come from a section above the destination one and to the bottom if you come from a section below the destination one. Possible values are top, bottom, null.

**Comment by cvaraj** [comment]
its not working,  have to give like this
$('#fullpage').fullpage({
   bigSectionsDestination:'top'
});

or 
$('#fullpage').fullpage({
   bigSectionsDestination:top
});

need to give inside quotes?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction of it (no external css or js) in jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
First one. with quotes.

**Comment by cvaraj** [comment]
https://jsfiddle.net/ht8q00kv/11/

here the jsfiddle path but i don't know how to add files , i created what i know,

**Comment by alvarotrigo** [comment]
@cvaraj fullPage.js is not working in it. Can't review it. Feel free to use codepen instead or a page in your own server without external files to fullPage.js.

**Comment by alvarotrigo** [comment]
Working as expected in this fiddle: http://jsfiddle.net/97tbk/1537/

**Comment by cvaraj** [comment]
ok thanks @alvarotrigo  , its working 

but i have one more doubt, shall we use same concept in scroll overflow sections, while bottom to top scroll its can always go to top of the section ?..

**Comment by alvarotrigo** [comment]
> shall we use same concept in scroll overflow sections

Not possible at the moment.

**Comment by cvaraj** [comment]
oh ok thank you @alvarotrigo  for supporting

**Comment by alvarotrigo** [comment]
@cvaraj if you really need it [contact me](http://alvarotrigo.com/#contact-page) for a customization and I'll provide you with a quote for it.

**Comment by cvaraj** [comment]
ok @alvarotrigo  i need it

**Comment by alvarotrigo** [comment]
As I said, contact me.

**Comment by cvaraj** [comment]
ok putted mail
