### ISSUE TITLE
Links and Buttons not clicking when scrolling exists in a page

### ISSUE THREAD

**Issue by antoinefaddoul** [alvarotrigo/fullPage.js#2386]
### Description
When I have a page that contains Links and Buttons, and it is opened using Chrome for Android, I am facing the following issues:

When the page contains scrolling & scrollOverflow = true & scrollOverflowOptions.click = false ==> The Links are Not Clickable but the Buttons are Clickable!

When the page contains scrolling & scrollOverflow = true & scrollOverflowOptions.click = true ==> The Links are Clickable but the Buttons are Not Clickable!

Note that the above issues are not occurring in case I don't have scrolling in my page.

Any idea???

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/antoinefaddoul/wexpmhmn/

### Steps to reproduce it
1. Navigate to the screen Contact (Last Screen) that contains Links and Buttons and try the issue.
Note that The button name is "Send", the Link name is "Locate Us". 

### Versions 
Chrome for Android

**Comment by alvarotrigo** [comment]
Sorry, the link to the isolated reproduction has to be online. No a file to download.

**Comment by antoinefaddoul** [comment]
Ok Done

**Comment by alvarotrigo** [comment]
There's plenty of external JS to fullPage.js. 
Get rid of all the unnecessary and move the external files like jQuery or fullpage.js into the External resources panel on the left. 

The Javascript panel should only contain the initialization of fullpage.js and the possible actions related with your button (if any).

**Comment by alvarotrigo** [comment]
Also, the HTML contains errors in red. Please fix them.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by TheZanBoy** [comment]
I had the same problem, this worked for me
```javascript
$('#fullpage').fullpage({
    scrollOverflow: true,
    scrollOverflowOptions:{
        click: true,
        preventDefaultException: { tagName:/^A/ },
        //or
        click: false,
        preventDefaultException: { tagName:/.*/ },
    },
});
```

**Comment by antoinefaddoul** [comment]
**That worked perfectly**
`$('#fullpage').fullpage({
    scrollOverflow: true,
    scrollOverflowOptions:{
        click: false,
        preventDefaultException: { tagName:/.*/ },
    },
});`
**Thank you**
