### ISSUE TITLE
Clips start playing when window is resized

### ISSUE THREAD

**Issue by okgojoe** [alvarotrigo/fullPage.js#2388]
I came across the following issue with Alvaro's **autoplayVideoandAudio.html** template and Firefox 49.0.2.
(please see attached file)
[autoplayVideoAndAudio_issue.zip](https://github.com/alvarotrigo/fullPage.js/files/579550/autoplayVideoAndAudio_issue.zip)

### Steps to reproduce it
1. first scroll down to the Audio (Horse) slide 
2. and then go back the first section, 
3. resize the browser window (I'm using Firefox 49.0.2)
* the horse.mp3 clip starts playing by itself even when you're not on the slide.

### Versions 
Windows 10, Firefox 49.0.2

thanks for your help!

**Comment by alvarotrigo** [comment]
Please provide a link for the isolated reproduction. I won't review files to download.

**Comment by okgojoe** [comment]
sure thing:
https://jsfiddle.net/okgojoe/jvb8v0rs/1/

**Comment by alvarotrigo** [comment]
@okgojoe I'm afraid that's not enough. I can' see fullPage.js working on it and the Javascript console is full of errors.
Please add the external files through the panel in the left. The Javascript panel should only contain the fullPage.js initialization and any required javascript to run the reproduction.

**Comment by okgojoe** [comment]
you're fast! :)
updated, let me know if it works.

I just noticed that the issue I mentioned happens with your **original** unmodified **autoplayVideoAndAudio.html** template file.

- Open the html file if Firefox
- Scroll down to HTML 5 videos section
- Unmute the audio.
- Scroll up to first section, resize Firefox window, the bunny video starts playing by itself.

**Comment by alvarotrigo** [comment]
Thanks for it. 
Also taking place in other browsers such as Chrome.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.8.9

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9
