### ISSUE TITLE
Going to second section by default

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/fullPage.js#2389]
Hey Alvaro! 

How's going? Hope ok...

Look... I just started to create a new website today using your Fullpage and I stumbled in a, let's say, weird and dumb question. 

Well... I copied 'ipsis literis' the code from the demo, no changes has been done, at all, and the page is going to the second section by default. Please check this pen for instance 

http://codepen.io/tofanelli/pen/Mbamyd

As you can see, I only copied the code from your demo. What I did wrong?

Cheers =)

**Comment by alvarotrigo** [comment]
You are using the `active` class in the 2nd section. Just remove it.
