### ISSUE TITLE
 continuousVertical doesn't work with autoScrolling: false 

### ISSUE THREAD

**Issue by turboamerica** [alvarotrigo/fullPage.js#2390]
Hi, great work!
Is it possible to have a continuousVertical without autoScrolling?

autoScrolling: false,
fitToSection: false,
continuousVertical: true,

Thnks

**Comment by alvarotrigo** [comment]
Yep, not suppose to work with scroll bar.
I'll mark it as a documentation issue. It seems it is not specified in the docs.

I'll also mark it as an enhancement [as right now](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L2846) fullPage.js throws a javascript warning when using `continuousVertical:true` and `scrollBar:true`, but it doesn't when using `autoScrolling:false`. 
So I'll add a warning there too.

**Comment by turboamerica** [comment]
Is there a way to make ti work?

**Comment by alvarotrigo** [comment]
> Is there a way to make ti work?

As I saidÑ

>But to leave it clear. **Those two options won't going to work together.** And I'm not planning to do anything for that.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9
