### ISSUE TITLE
Horizontal dots navigation in wrong place

### ISSUE THREAD

**Issue by tofanelli** [alvarotrigo/fullPage.js#2391]
Hi Alvaro (once again =)... )

Quick question once again...

When I set 'SlidesNavigation' to true, the horizontal dots goes to the 'section0' instead of 'section1', where the slides are.

Any idea?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
