### ISSUE TITLE
jQuery plugins conflict with fullPage - on scroll triggers affected?

### ISSUE THREAD

**Issue by radeson** [alvarotrigo/fullPage.js#2392]
Hi Alvaro,

I love your plugin and I would like to use it on our website. Everything works perfectly to me except other jQuery plugins which apparently have issues with their triggers that are not being fired. 

Specifically, the plugins which should do an action on scroll, e.g. number counter which starts counting when you scroll down to it. Or the similar animations... 

you can see it in this short [screen capture](https://drive.google.com/file/d/0B82dmrWl19iSMXFIZlNRbXN0Q0k/view)

It works fine on the first scroll screen, but on the others not.  However, if you for example try to zoom in 
and increase the font size, it starts. There is probably a conflict with fullPage and other jQuery plugins which have onscroll triggers. Do you have any idea how to fix it?

The page is [here](http://marketingo.cz/domains/new-marketingo.cz-3)

Thanks :)

**Comment by alvarotrigo** [comment]
Please read the (Frequently Answered Questions)[https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions]
