### ISSUE TITLE
compatibility issue with photoswipe.js

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#2394]
hello there,

I have this issue with picture viewer within fullPage.js on desktop browsers. When photoswipe.js is open and i scroll down or up, the whole page scrolls in the background and the photoswipe.js hangs.

Am not sure how to jsfiddle it with all them scripts, but you can see it here (just click menu / DONE, hover over a piece, click it and scroll up or down): http://www.doublescreen.studio - neither escape, nor the close button will work anymore.

Had to put swiper.js inside fullpage.js .. photoswipe.js works fine with swiper (left/right) - it fades photoswipe out. so i wonder, has it more to do with fullPage.js or photoswipe.js and is there a simple solution to this?

**Comment by asdangus** [comment]
pls refresh, forgot to update the files :|

**Comment by alvarotrigo** [comment]
> When photoswipe.js is open and i scroll down or up, the whole page scrolls in the background and the photoswipe.js hangs.

Use the option `scrollOverflow` or the fullpage.js function `setAllowScrolling` to toggle the scroll when using the other library.

Regarding close button. Make sure you are using the lastest fullpage.js 2.8.8.

And the esc key. Use `setKeyboardScrolling` to toggle it.
