### ISSUE TITLE
Humburger menu not scrolling while open on Mobile

### ISSUE THREAD

**Issue by Gnomylka** [alvarotrigo/fullPage.js#2395]
### 
on Mobile humburger menu overlay with scroll bar if you have autoScrolling: true, for some reason frozen the overlay and I ma not able to scroll anymore inside overlay. 
I am using  * fullPage 2.8.8, my config: as you can see I added to normalScrollElements my navigation class but still doesn't work.
		                css3: true,
			        scrollingSpeed: 700,
			        autoScrolling: true,
			        fitToSection: true,
			        fitToSectionDelay: 1000,
			        scrollBar: false,
			        easing: 'easeInOutCubic',
			        easingcss3: 'ease',
			        loopBottom: false,
			        loopTop: false,
			        loopHorizontal: false,
			        continuousVertical: false,
			        continuousHorizontal: false,
			        scrollHorizontally: false,
			        interlockedSlides: false,
			        resetSliders: false,
			        fadingEffect: false,
			        normalScrollElements: '.new-minicartcontent, .navbar, .checkoutminicart, #sport-signup-popup-container',
			        scrollOverflow: true,
			        scrollOverflowOptions: null,
			        touchSensitivity: 5,
			        normalScrollElementTouchThreshold: 5,
			        bigSectionsDestination: null,

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
All Mobile and Tablet devices

**Comment by Gnomylka** [comment]
Hi Alvaro,
I found the line in your script which is causing this issue
$body.off('touchmove ' + MSPointer.move).on('touchmove ' + MSPointer.move, preventBouncing);
when I commented out, everything is working perfect!

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2372
