### ISSUE TITLE
chrome mousewheel issue

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2396]
sometimes in chrome mouse wheel scrolling, scroll will delay for 4 to 5 milliseconds to scroll, safari also having same issue

**Comment by alvarotrigo** [comment]
You'll have to provide a prove of it. Ideally a video.
And explain what you exactly mean by that.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
