### ISSUE TITLE
ie8 compatibility problem

### ISSUE THREAD

**Issue by bluemind7788** [alvarotrigo/fullPage.js#2397]
### Description
In ie8, a error of compatibility throw out.
### Link to isolated reproduction with no external CSS / JS
Search in the fullsreen.js with 'extensions.forEach(function(extension){', this is the cause.

### Versions 
ie8

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2350
It was fixed on dev.
