### ISSUE TITLE
scroll overflow issue

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2398]
whenever i used rebuild methods it will affect the scrolloverflow function, i will not update the height of inner scroll,

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
