### ISSUE TITLE
is there a way to get the background-image attribute for each section? 

### ISSUE THREAD

**Issue by johnsonreyliu** [alvarotrigo/fullPage.js#2400]
### Description

i want to be able to dynamically change the background image to a mobile optimized one. Is there a way to dynamically get it? I do not see it when i try to get attribute by id

> console.log(document.getElementById('section0'));

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
It doesn't sound like a fullPage.js issue anyway but more about Javascript knowledge.
