### ISSUE TITLE
QUESTION: Lazy loading with fade effect.

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2401]
Is it possible to add a `.fadeIn()` effect to the images when using `lazyLoading:true`

I tried this code but the boring thing is that I have to style every first image. 
I'm sure there's an easier way.

CSS
`img {display: none;}`

JS
`afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){var loadedSlide = $(this).find('img');loadedSlide.fadeIn();}`

Thanks.
F.

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any fade in effect.
But you are free to try to implement it if you think you can.
