### ISSUE TITLE
Can a slider have a dedicated section?

### ISSUE THREAD

**Issue by terasue** [alvarotrigo/fullPage.js#2403]
Hey I have a very stupid question: Is it possible to have different sections corresponding to a slide?
My plan is to make a full screen slider (horizontally) and when you scroll down you get to a section.
Every slide should have their own section.

![image](https://cloud.githubusercontent.com/assets/23459488/20276147/63974cf8-aa9b-11e6-9f6d-fafcdb02b636.png)

Can you give me a short example?
Thank you!

**Comment by alvarotrigo** [comment]
You can probably achieve that by using the [Interlocked Slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html) .
Then you can use `setAllowScrolling`  and `setKeyboardScrolling` to deny the right or left scrolling when you are not on the 1st level.

You can use those functions on the callbacks.
