### ISSUE TITLE
effets jquery sur section

### ISSUE THREAD

**Issue by vedrenne** [alvarotrigo/fullPage.js#2405]
Bonjour,

je suis débutant dans le code et je souhaiterai savoir comment on ajoute des effets jquery quand on scroll sur une section?

Je souhaiterai aussi savoir comment on change une image des que l'on arrive sur une section?

Merci

**Comment by alvarotrigo** [comment]
Bonjour,

English please.

**Comment by vedrenne** [comment]
Hello,

I how does one make will wish to know to add jquery effects as soon as a section is charged?

 would also like to know how to change an image as soon as I scroll on a section. I am a beginner and as the scrolltop is not recognized with the fullpage, I am lost. thank you very much

**Comment by alvarotrigo** [comment]
You can make use of the fullpage.js callbacks as you can see in this [the callbacks example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/callbacks.html).

[Here you have another example online](http://alvarotrigo.com/fullPage/examples/callbacks.html#secondPage) and all you need to know its detailed in [the docs](https://github.com/alvarotrigo/fullPage.js#callbacks).

You can also make use of [the state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) if you prefer to go for CSS animations and transitions.

> would also like to know how to change an image as soon as I scroll on a section. I am a beginner and as the scrolltop is not recognized with the fullpage, I am lost. thank you very much

Read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) to know why scrolltop won't work and how to solve it.

**Comment by vedrenne** [comment]
Thank you very much for your quick replies .. I'm sorry but I do not understand all the code. Could give you a concrete example.

I will wish when I arrive on section 2 my picture # Nav2 is attr images/boutonProfilCouleur.png.
Voici ce que j'ai fait mais ça ne marche pas:
afterLoad: function(anchorLink, index){
					//section 2
					if(index == 2){
						//moving the image
                  $('#section2').find('#bNav2').attr('src','images/boutonProfilCouleur.png');
				
						}
					}
				
				})
			});

thanks you so much

**Comment by alvarotrigo** [comment]
> Could give you a concrete example.

Sure. [Download the zip file from github](https://github.com/alvarotrigo/fullPage.js/archive/master.zip) and see the callbacks example in the examples folder.

**Comment by vedrenne** [comment]
Sorry to insiter
I have already download the fullpage pack. I tried by example to change my image # Nav2 by another:

AfterLoad: function (anchorLink, index) {
// section 2
If (index == 2) {
// moving the image
$ ( '# Section2'). Find ( '# bNav2') attr ( 'src', 'images / buttonProfileColor.png');

                     }
                 }

             })
         });

I just want to know what's wrong with this code.
I count on you because I need to understand because I use the fullpage for my exam.
Once i understand the callback, i will be doing the rest.

thank you

**Comment by alvarotrigo** [comment]
> I just want to know what's wrong with this code.

Unfortunately this is not the place to ask for Javascript knowledge questions. 
The example works as expected and you in the docs you have all you need to know about callbacks and how to use them.

If you still don't understand it or you don't manage to make it work for you, you'd better ask in other place such as stakcoverflow.com about generic Javascript questions. Just don't forget to use the Javascript tag in it :)

If you still want my help, feel free to [contract my services](http://alvarotrigo.com/#contact-page) for support purposes.

**Comment by vedrenne** [comment]
I thought you could help me and that you knew the subject. It was just a question. I did not know that you had to pay for a little help. thanks anyway

**Comment by alvarotrigo** [comment]
I can help you with fullPage.js issues and questions. 
But what I can not do is provide personal support to everybody who has any basic questions of HTML, Javascript or any other web technology. 
There's plenty of people asking me for help outside fullPage.js and I don't have the time for it. I'm a normal person with a full time job and a life outside fullPage.js :)

**Comment by vedrenne** [comment]
I understand and I will not trouble you any more. I will seek by myself. I have no choice I have an exma in 2 weeks and understanding the callback is important to me. Good night
