### ISSUE TITLE
'touchmove' event no longer fired after onSlideLeave return false

### ISSUE THREAD

**Issue by AtlantasiuS** [alvarotrigo/fullPage.js#2406]
### Description
When preventing the sliding from happening (`onSlideLeave: return false`) 'touchmove' events are no longer fired on touch devices/screens.

### Link to isolated reproduction with no external CSS / JS
Here is a jsfiddle inspired from examples code [https://jsfiddle.net/txjkp03h/](https://jsfiddle.net/txjkp03h/)

### Steps to reproduce it
1. Added code to prevent SlideLeave
`if (this[0].id == "slide1.2" && direction == "right") return false;`
2. test on a touch device or emulate one on browser
3. Slide 'right' (with touchmove) from "Section 1" to "Slide 1.2" : no problem
4. Slide 'right' (with touchmove) on "Slide 1.2", nothing happens as expected
5. 'touchmove' event is no longer fired in any direction, until click on slide arrow (previous of course)

Same issue when click on slide arrow next on "Slide 1.2", blocks 'touchmove'.

### Versions 
- fullPage 2.8.8
- jQuery 1.12.4
Tested on Firefox and Chrome, same result.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch. [Reproduction online](https://jsfiddle.net/txjkp03h/2/)
Replace your fullpage.js file for [this new one](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/jquery.fullPage.js).

You can't test the touch horizontal scrolling when using the responsive mode if you are not in a real touch device.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9
