### ISSUE TITLE
Manually scrolling to another div

### ISSUE THREAD

**Issue by nikssardana** [alvarotrigo/fullPage.js#2408]
I am using bootstrap and fullpagejs. I want to have a div in which, if  the user scrolls to top, after that on further scrolling he will be taken to the previous div. How to achieve this effect?

Is adding and removing the active class from the sections enough? Because it is not working properly in my case. Thanks!

**Comment by alvarotrigo** [comment]
Use the `moveSectionUp`, `moveSectionDown` or `moveTo` functions detailed in the docs.
You can find them working on [this example](http://alvarotrigo.com/fullPage/examples/methods.html#firstPage).

**Comment by nikssardana** [comment]
Thanks @alvarotrigo it worked!
