### ISSUE TITLE
ScrollOverflow reset to top

### ISSUE THREAD

**Issue by thomasbrodin** [alvarotrigo/fullPage.js#2417]
Hi there,

Thank you in advance for your help and your great plugin!

I was wondering if there was a way to accomplish something using FullPage with the Scrolloverflow options for a larger section. I have a few sections and some of them are scrollable;

http://jsfiddle.net/photous/qn084vmn/

- If I scroll down sections, everything works as expected, autoScrolling is on, I jump from section to section and scroll within a section when it is a larger section. So far so good! :)
- The issue is as follow; When I use the anchor or the navigation to move to the last section for example after fullPage has rendered. And then scroll back up to the scrollable section, it doesn't show the entire section from the bottom but hides a part outside the scrollable element and start the section from the top... 

I would love to be able basically to when we jump to a section below the scrollable section using the anchors or navigation, and then scrolling up, we would start the scrollable section from the bottom.

Let me know if I am missing something, or if there is a way to accomplish this.
-Thomas.

**Comment by alvarotrigo** [comment]
Thanks for the suggestion. I'll mark it as a possible enhancement for the future.

**Comment by thomasbrodin** [comment]
Thanks for your quick reply! Any hint on how to accomplish this in the meantime?...
I tried to force the css transform but it doesn't seem to work?...
http://jsfiddle.net/photous/qn084vmn/3/

**Comment by alvarotrigo** [comment]
You would have to use the iScroll functions to scroll it up. 
And [get the iScroll instance](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L3034) from any previous section/slide.

**Comment by thomasbrodin** [comment]
Hey Alvaro,
I manage to make it work using the `onLeave` callback. 
I am struggling to get the next Section though. Is there a way to get the next Section object using the `nextIndex` maybe?...

http://jsfiddle.net/photous/qn084vmn/

Thanks in advance!
-T.

**Comment by alvarotrigo** [comment]
You'd better ask those kind of Javascript question in other place. Getting an element for its index.

**Comment by thomasbrodin** [comment]
Hi Alvaro,

Thank you for the suggestion. The following worked for me.
It is basically checking if the next section or previous is 'scrollable' and then make sure to scroll to top or bottom...

http://jsfiddle.net/photous/qn084vmn/

**Comment by rulloliver** [comment]
Anyone looking for a solution online, the following worked for me: 
```
var myFullpage = new fullpage('#pagepiling', {
        scrollOverflow: true,
        menu: '#menu',
        responsive: 780,
        onLeave: function(origin, destination, direction, trigger){
          if(direction == 'up'){
            setTimeout(function () {
                var instance = fullpage_api.getActiveSection().item.querySelector('.fp-scrollable').fp_iscrollInstance;
                instance.scrollTo(10, -10000, 1000);
                instance.refresh();
                console.log('we went down from the menu and are scrolling up while also scrolling the sections to bottom');
            }, 0);
        }
      },
```
