### ISSUE TITLE
moveTo as it would be the next slide

### ISSUE THREAD

**Issue by MickL** [alvarotrigo/fullPage.js#2421]
Lets say im at `(0,0)` and call `moveTo(0, 5)`: As by design it will overscroll the 3 slides in between. Is there a option to move to a slide as it would be the next one? Like `silentMoveTo()` does, but with animation.

Or any idea of a workaround?

**Comment by alvarotrigo** [comment]
> Is there a option to move to a slide as it would be the next one?

No. Use my other library [pagePiling.js](http://alvarotrigo.com/pagePiling/) for that.
