### ISSUE TITLE
On enter/load event?

### ISSUE THREAD

**Issue by yellow1912** [alvarotrigo/fullPage.js#2422]
### Description
I wonder if there is any event that triggers when we enter a particular section (after the section has been completely in place?)

I understand that I can cheat with onLeave and timeOut but I just wonder if there is any other solution I don't know of?

**Comment by alvarotrigo** [comment]
[`afterLoad`](https://github.com/alvarotrigo/fullPage.js#afterload-anchorlink-index) ?

**Comment by yellow1912** [comment]
Not sure how I could miss it, very sorry *_*. On a side note, I wonder if this plugin can be used together with your https://github.com/alvarotrigo/multiscroll.js plugin? For example, Can I have several sections scroll as full page, then hit several sections scroll as multi scroll, then go back to full page?

**Comment by alvarotrigo** [comment]
I haven't tried so I can't tell you. 
But I personally do not provide support for such thing.
