### ISSUE TITLE
Console WARNING about 'wheel'

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2425]
### Description
Sometimes when I first open my website and try to scroll down from the first to the second section, I get this warning message on the website console.

**Handling of 'wheel' input event was delayed for 106 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.**

And it refers to this line of code:

    function MouseWheelHandler(e) {
    var curTime = new Date().getTime();

Don't know if it's something easily fixable or it's something I shouldn't care at all.

### Versions 
fullPage 2.8.9 running on Chrome 54.0.2840.98

**Comment by alvarotrigo** [comment]
Duplicatd of https://github.com/alvarotrigo/fullPage.js/issues/2311
