### ISSUE TITLE
Problem with translate value in responsive

### ISSUE THREAD

**Issue by TheZanBoy** [alvarotrigo/fullPage.js#2426]
Description

If you go to the last section and trigger responsive you will find that the translate value in fullpage wrapper is not changing

Link to isolated reproduction with no external CSS / JS

http://alvarotrigo.com/fullPage/examples/responsive.html#3rdPage

**Comment by alvarotrigo** [comment]
Thanks for reporting it. 
My mistake! I introduced it in the previous release.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch.

**Comment by alvarotrigo** [comment]
Fixed in the latest version 2.9.0
