### ISSUE TITLE
Scrolling up effect as scrolling down

### ISSUE THREAD

**Issue by Madeirense** [alvarotrigo/fullPage.js#2427]
Hi, great plugin. 

I was wondering though if there is a way to scroll sections up in the same way they scroll down. At the moment I have tried to add this functionality and although it kind of works when i scroll up from the third section with the tiles here for example https://dashnimorad.com/ scrolling only stops in the first section skipping second section completely. Would be great if the plugin would snap up and down on scroll instead of just down. What would be thew best way to achieve this and make it behave exactly like when scrolling down? Thank you very much!

**Comment by alvarotrigo** [comment]
I don't understand whats the problem.
fullPage.js scrolls up and down as seen in the [example page](http://alvarotrigo.com/fullPage/). Be more specific and ideally create a jsfiddle or codepen with your sissue.

**Comment by Madeirense** [comment]
If you look at my music page here https://dashnimorad.com/music/ I have 4 sections that scroll perfectly up and down because they are all the same dimensions. However, when I need sections to have flexible heights  I need to add custom code to add a scrolling up effect like the below which I have on my home page to scroll up from the tiles section to the intro section to the video:


onLeave: function(index, nextIndex, direction) {
        if ($("body").hasClass("home")) {
         if(index == 2 && direction =='up'){
           $('html, body').stop().animate({
               scrollTop: $('body').offset().top
           }, 1100, 'easeOutExpo');
           event.preventDefault();
         } else if(index == 3 && direction =='up') {
            $('html, body').stop().animate({
                scrollTop: $('#home-intro').offset().top
            }, 1100, 'easeOutExpo');
            event.preventDefault();
         }
        } else  {
        if(index == 2 && direction =='up'){
          $('html, body').stop().animate({
              scrollTop: $('body').offset().top
          }, 1100, 'easeOutExpo');
          event.preventDefault();
       }


So the above kind of works but when scrolling up from the third section with the tiles to the second with the picture it snaps to the first with the video. What I am looking for is for the effect on scrolling up here to be perfect as when sections are all the same height as in this page https://dashnimorad.com/music/


Thank you


________________________________
De: Álvaro <notifications@github.com>
Enviado: quarta-feira, 23 de novembro de 2016 17:18
Para: alvarotrigo/fullPage.js
Cc: madeirense; Author
Assunto: Re: [alvarotrigo/fullPage.js] Scrolling up effect as scrolling down (#2427)


I don't understand whats the problem.
fullPage.js scrolls up and down as seen in the example page<http://alvarotrigo.com/fullPage/>. Be more specific and ideally create a jsfiddle or codepen with your sissue.

-

**Comment by alvarotrigo** [comment]
fullPage.jsj doesn't provide any build in feature to solve it.

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/614

**Comment by alvarotrigo** [comment]
> . However, when I need sections to have flexible heights  I need to add custom code to add a scrolling up effect like the below

You don't need to. You want to.
You can always use the `fp-auto-height` feature as in [this example](alvarotrigo.com/fullPage/examples/autoHeight.html#secondPage)

**Comment by Madeirense** [comment]
That is not like my example. My third section on my home page needs to have a flexible height and cannot snap on scrolling. And it what is causing the problem because if sections occupy the full viewport like in the music page everything works really well.  I just need the first and section of that page to snap up and down as the music page do.

________________________________
De: Álvaro <notifications@github.com>
Enviado: quarta-feira, 23 de novembro de 2016 17:40
Para: alvarotrigo/fullPage.js
Cc: madeirense; Author
Assunto: Re: [alvarotrigo/fullPage.js] Scrolling up effect as scrolling down (#2427)


. However, when I need sections to have flexible heights I need to add custom code to add a scrolling up effect like the below

You don't need to. You want to.
You can always use the fp-auto-height feature as in this example<alvarotrigo.com/fullPage/examples/autoHeight.html#secondPage>

-

**Comment by alvarotrigo** [comment]
I was just giving you an example. Use the class `fp-auto-heigh` if you don't want a full viewport section.

If that doesn't work for you, I'm afraid fullPage.js doesn't provide any feature to do what you want.

**Comment by Madeirense** [comment]
Ok, will have a better look. Just one last thing. There on the home page https://dashnimorad.com/ When I scroll up from the tiles section trying to snap to the 2nd section it snaps up to the first skipping the 2nd. Would you know why it is causing that?

________________________________
De: Álvaro <notifications@github.com>
Enviado: quarta-feira, 23 de novembro de 2016 17:51
Para: alvarotrigo/fullPage.js
Cc: madeirense; Author
Assunto: Re: [alvarotrigo/fullPage.js] Scrolling up effect as scrolling down (#2427)


I was just giving you an example. Use the class fp-auto-heigh if you don't want a full viewport section.

If that doesn't work for you, I'm afraid fullPage.js doesn't provide any feature to do what you want.

-

**Comment by alvarotrigo** [comment]
> Would you know why it is causing that?

Your code :) 
It is something you coded in the callback, not something fullPage.js provides. There's no proper solution to that, not that I know. So dont lose the time in it :)

**Comment by Madeirense** [comment]
This behaviour really isn't ideal. Ok, thanks for your advise. I'll look for some other plugin that might be more  suited for what I am trying to archive.


Take care


________________________________
De: Álvaro <notifications@github.com>
Enviado: quarta-feira, 23 de novembro de 2016 17:57
Para: alvarotrigo/fullPage.js
Cc: madeirense; Author
Assunto: Re: [alvarotrigo/fullPage.js] Scrolling up effect as scrolling down (#2427)


Would you know why it is causing that?

Your code :)
It is something you coded in the callback, not something fullPage.js provides. There's no proper solution to that, not that I know. So dont lose the time in it :)

-

**Comment by alvarotrigo** [comment]
Sorry but I can't provide you any solution.
I'm being honest. I already spent time trying to solve those kind of situations and didn't find a solution.

You'll find that exact same response on the related topic i linked. 

Good luck!

**Comment by Madeirense** [comment]
Hi Alvaro,


Loosing my mind over this.. I have done a lot of research, tried forums for help but had no luck.. I have done this whole website based on fullpage.js and it would really be a pain to change it all for something else now. The main problem is in the snap scrolling up in the home page. I need this to snap scroll up as perfectly as it snap scrolls down without skipping any sections. One other thing I'd like to achieve is to have an offset on the top so the fixed header does not overlap sections.  I was wondering if you would be willing to have a look into this for me and how much would you charge for it.


Thank you very much.


Paulo

________________________________
De: Álvaro <notifications@github.com>
Enviado: quarta-feira, 23 de novembro de 2016 18:09
Para: alvarotrigo/fullPage.js
Cc: madeirense; Author
Assunto: Re: [alvarotrigo/fullPage.js] Scrolling up effect as scrolling down (#2427)


Sorry but I can't provide you any solution.
I'm being honest. I already spent time trying to solve those kind of situations and didn't find a solution.

You'll find that exact same response on the related topic i linked.

Good luck!

-

**Comment by alvarotrigo** [comment]
> Loosing my mind over this.. I have done a lot of research, tried forums for help but had no luck..

I suggested you not to spend time in it...

> So dont lose the time in it :)

>   I was wondering if you would be willing to have a look into this for me and how much would you charge for it.

As I said:

> There's no proper solution to that, not that I know.

So I can't help you with it I'm afraid.

**Comment by alvarotrigo** [comment]
The only proper solution to your problem is to think about another solution for it. 
Why don't you just use `scrollOverflow:true` and use it in your bigger section instead? That's the main purpose of this feature: to enable the use of bigger sections.

See [the example here](http://alvarotrigo.com/fullPage/examples/scrolling.html).
