### ISSUE TITLE
Hidden slides are counted as visible slides

### ISSUE THREAD

**Issue by ageurts** [alvarotrigo/fullPage.js#2432]
First of all; great and very versatile plugin! That said, I have an issue with hidden slides.

When navigating slides in a section, a hidden slide is counted as visible in the AfterSlideLoad function. And the loopHorizontal: false option does not work anymore; the first slide will be displayed after trying to navigate to the 'hidden' slide.

### Link to isolated reproduction with no external CSS / JS
Check this fiddle: http://jsfiddle.net/97tbk/1557/

Steps to reproduce:
1. Create a section with a few slides.
2. Set the last slide to "display: none".
3. Add the afterSlideLoad function a log the slideIndex to the console.
4. Navigate to the last slide before the hidden one and then try to go to the hidden slide.
5. The first slide will be displayed with the slideIndex of the hidden slide.

**Comment by alvarotrigo** [comment]
Duplicated of the open issue https://github.com/alvarotrigo/fullPage.js/issues/2098

fullPage.js will still think the sections are there.
