### ISSUE TITLE
fp-normal-scroll going forward

### ISSUE THREAD

**Issue by MikeiLL** [alvarotrigo/fullPage.js#2433]
Hi man.

We are implementing a huge footer with dropdown elements and I'm using `fp-normal-scroll ` with `hybrid: true` as referenced [here](https://github.com/alvarotrigo/fullPage.js/issues/614).
 
 * Does `hybrid: true` mean we're combining _scrolling_ and _non-scrolling_ sections in the same FP instance?
 * Do you plan on continuing to support `fp-normal-scroll `?

**Comment by alvarotrigo** [comment]
> Does hybrid: true mean we're combining scrolling and non-scrolling sections in the same FP instance?

It does.

> Do you plan on continuing to support fp-normal-scroll?

I would have to start it, because I never provided support for it. But so far, no plans on it.

As I said in the post you linked:

> This is a feature under testing and therefore it is not perfect and will probably have bugs.

I'll close the issue as it is not a feature I support yet.

**Comment by MikeiLL** [comment]
OK Thank you.
