### ISSUE TITLE
Turn off fullpage sections for certain resolutions.

### ISSUE THREAD

**Issue by doozius** [alvarotrigo/fullPage.js#2434]
Hello. 

I would like to turn off sections, and let the page scroll normally like in mobile, for certain resolutions e.g. 1366 x 768. Could you please guide me how to do this? Thanks.

**Comment by alvarotrigo** [comment]
Have you checked the responsive options and the [fp-auto-height-responsive feature](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections)?
Use `responsiveWidth` or `responsiveHeight` and then use `fp-auto-height-responsive` class in the sections that you don't want to take the whole viewport.
