### ISSUE TITLE
Scroll Overflow Issue on Responsive

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#2435]
Hi,

I have a question with scroll overflow on responsive views. I set the responsive view and on mobile views since scroll overflow is enabled at the first section and inner scroll is visible, the section does not go to the next.

I know responsive auto height kind of solves this issue but I want to suggest an alternate way. If responsive mode is activated and the height already exceeds the window height, it should be converted to auto height. I guess it comes to disabling inner scroll when responsive view is activated.

Is there an alternative for this ?

Isolated Reproduction:
http://codepen.io/meceware/full/BQwPeg/
Check the page on mobile and try to go to the next section with swiping down.

Thank you for the great plugin and highly appreciated.

**Comment by alvarotrigo** [comment]
> If responsive mode is activated and the height already exceeds the window height, it should be converted to auto height.

I agree.
There's an open issue about that same request https://github.com/alvarotrigo/fullPage.js/issues/958

I'll close this issue as duplicated.
