### ISSUE TITLE
Rebuild section after send form

### ISSUE THREAD

**Issue by Rippler** [alvarotrigo/fullPage.js#2437]
Rebuild section after submit form

I created a form with jqueryform builder and I inserted it in a section. 
When I click submit I should see the message and return to form after 5 seconds but doesn't work. I can only see a blank section.

How to fix a problem?

Thank you in advance.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
