### ISSUE TITLE
Horizontal scroll with horizontal gesture

### ISSUE THREAD

**Issue by lucasdchamps** [alvarotrigo/fullPage.js#2438]
### Description

There is already [horizontal scrolling](http://alvarotrigo.com/fullPage/extensions/scrollHorizontally.html#firstPage) but it is trigerred by a vertical gesture.

Would be nice to have the same feature with a horizontal gesture.

I'm thinking about mobile users browsing horizontal slides with hand gesture. The horizontal gesture is more natural.

**Comment by alvarotrigo** [comment]
> I'm thinking about mobile users browsing horizontal slides with hand gesture. The horizontal gesture is more natural.

Haven't you tried the [Drang And Move extension](http://alvarotrigo.com/fullPage/extensions/dragAndMove.html)?
It does exactly what you are looking for when using `dragAndMove: `fingersonly`.`

**Comment by lucasdchamps** [comment]
Thanks! I will try and report if it covers my use case ;)
