### ISSUE TITLE
Using scrollbar to scroll causes layout to jump up and down rapidly.

### ISSUE THREAD

**Issue by ImranBug** [alvarotrigo/fullPage.js#2439]
Hi,
If a user uses scrollbar a little roughly/fast it causes the layout to go on a frenzy for a moment!
This issue sometimes occurs even when using scrollbar normally.

Here is a [video](https://www.youtube.com/watch?v=fuI6CEeYSFk&feature=youtu.be) of the issue in action.

**Comment by alvarotrigo** [comment]
I have exactly the same problem in any other page, such as the http://www.bbc.co.uk/.
As long as your mouse is not hover the scroll bar.

It seems a Chrome issue.
