### ISSUE TITLE
Height determination

### ISSUE THREAD

**Issue by pipi999** [alvarotrigo/fullPage.js#2440]
Code snippet: $body.height()
Problem: returns the height of viewport not the actual height of document
File: https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L922
Browser: IE 11

Recommendation: instead use $(document).height()

**Comment by alvarotrigo** [comment]
Can you please explain what is the problem that you are getting from it? 
 Isolated reproduction? Steps to reproduce it?

**Comment by pipi999** [comment]
Problem is caused by the mentioned code snippet that makes the variable "isAtBottom" get wrong value.
For example when the document height is 2000 pixels and the window height is 1000 pixels the named code snippet return 1000 pixels.
Continuing the example when the scroll is on top of the page the evaluation of the formula is like this:
1000 - 1000 === 0 ($body.height() - $window.height() === currentScroll)
After the evaluation the "isAtBottom" variable gets the "true" boolean value which is incorrect.

**Comment by alvarotrigo** [comment]
Maybe  I didn't express myself properly.

I'm asking you to show me a use case where this leads to any kind of bug or issue. 
Isolated reproduction of it? jsfifdle? Codepen?

**Comment by pipi999** [comment]
I investigated the problem further and discovered the real source of problem.
Here is the test code: https://jsfiddle.net/m3wp4uo4/4/
So the basic problem is: The initial keyword is not supported in Internet Explorer 11 and earlier versions.
When the plugin is switching to scroll view the code sets the html and body height to initial but IE doesn't support it and leaves the height: 100% css setting;
In the linked test code you will see the result of height: 100% setting and the problem caused by it.

**Comment by alvarotrigo** [comment]
What do you mean by *initial keyword* ?
In any case, I'm expecting to see a reproduction of it making use of fullPage.js, So I'll wait for it from you.

**Comment by pipi999** [comment]
Answer for your first question: http://www.w3schools.com/cssref/css_initial.asp

I have no time making a full example for you and for the current project i don't have permission to show it.
I fixed the problem in our project with the solution i mentioned in first message.

If you have interest fixing the problem you can understand it by using the examples i given.

**Comment by alvarotrigo** [comment]
Using `height:auto` seems a much easier solution? 
http://stackoverflow.com/questions/20823105/use-initial-width-for-element-not-working-in-ie

**Comment by pipi999** [comment]
Yes that would be proper solution for all earlier IE browsers.

**Comment by alvarotrigo** [comment]
Feel free to commit the change in a new PR and I'll merge it. 

I guess this solves the problem when changing from `autoScrolling:true` to `autoScrolling:false` (due to responsive options, for example) in case o using non full screen sections?
