### ISSUE TITLE
Normal scroll on selected element seems not working.

### ISSUE THREAD

**Issue by claide** [alvarotrigo/fullPage.js#2441]
Hi, First I would like to thank you for a life saving plugin of yours. Now, regarding about the issue, I tried to have a section where scrolling is normal. in short disable the fullpage scroll on the specific element. 

I tried:
`normalScrollElements: '.navbar-footer, .content-seven',`

HTML:
```
<div class="section container-fluid content-seven">
Some content here...
</div>
```

Still it scrolls or shall we say it moves to fit the section.
To see it in action kidly visit this [site](http://wearewhatweare.info/) and look for the last section with sign-up form.

Thanks!

**Comment by alvarotrigo** [comment]
As detailed in the docs regarding `normalScrollElements`:

> This option should not be applied to any section/slide element itself.

Why don't you use `scrollOverflow:true`? As [in this example?](http://alvarotrigo.com/fullPage/examples/scrolling.html)

**Comment by claide** [comment]
Tried it but 2nd scrollbar is showing up. I set the scrollbar to true. Would it be possible to disable the scrollbar made by the `scrollOverflow:true` ?

Thanks!

**Comment by alvarotrigo** [comment]
Please add an isolated reproduction if you think its a fullPage.js issue. 
As you can see in the example I provided you should only get 1 single scroll bar.
