### ISSUE TITLE
Backgrounds.html not scaling as intended

### ISSUE THREAD

**Issue by LoutK** [alvarotrigo/fullPage.js#2446]
### I've made a page which looks great on a fullsize screen, but when I open the website on my phone the scaling is ( I believe) not as intended.

You can see the difference with a nicely scaling website (navigationV.html) and a not nice scaling website (backgrounds.html). Is it intended that the background page doesn't scale with the screen resolution? You can see this for example when looking at the text. 

### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/examples/backgrounds.html 
http://alvarotrigo.com/fullPage/examples/navigationV.html#firstPage

### Steps to reproduce it
1. Open the navigationV.html and pop up the Debugger while putting it at the bottom of the page
2. Increase and decrease the size of the Debugger
3. The text will align nicely in the center of the scaled page.
4. Open the backgrounds.html and pop up the Debugger while putting it at the bottom of the page
5. Increase and decrease the size of the Debugger
6. The text will disappear from the screen and is moved below the 2nd section

### Versions 
Windows 7
Chrome Version 54.0.2840.99 m (64-bit)

Thanks in advance

**Comment by alvarotrigo** [comment]
That has nothing to do with fullPage.js.
It is all about the styles used for the example. Change them as you wish. 
This was done as an example of the use of backgrounds and the text was totally secondary. 

You can see the section is using `padding: 30% 0 0 0;`. 
Change it and place it where you want.

**Comment by alvarotrigo** [comment]
I've solved it in the [demo online](http://alvarotrigo.com/fullPage/examples/backgrounds.html) and in the examples folder in the dev version.
