### ISSUE TITLE
Keypress fires prematurely

### ISSUE THREAD

**Issue by publicJorn** [alvarotrigo/fullPage.js#2448]
### Description
Intended effect is not achieved, because keypress is already activated while sections are still moving.

See [jsfiddle](http://jsfiddle.net/publicJorn/s17s35k5/1/) for reproduction of the issue

### Steps to reproduce it
- After fiddle loads, click once on the result window to give it focus
- Normal flow:
  - Press down arrow once (fullpage will move to next section)
  - Press down arrow again (fullpage will move to next section)
  - Press up again until you are back at the top
- Errorneus flow:
  - At the top, press down arrow multiple times, quickly after each other
  - The intended effect is not achieved
  - Now, make sure you are at slide nr 3 or 4.
  - Quickly after each other, press up multiple times
  - Also, the wanted effect is not achieved

### Versions
fullPage 2.8.9
Any browser or os

Fix for issue is here: https://github.com/alvarotrigo/fullPage.js/pull/2443

**Comment by alvarotrigo** [comment]
Fixed in the latest version 2.9.0
