### ISSUE TITLE
Images in Body Section

### ISSUE THREAD

**Issue by agentlucky** [alvarotrigo/fullPage.js#2449]
### Images in Body Section

is it possible to to call the slide images in the body section instead of calling them in the stylesheet due to seo-reasons? I guess calling the images in the stylesheet, google won't find them as good as directly in the body of the page?!
I tried to call them with maximage.js but there is some conflict with fullpage. Unfortunately i'm not really into javascript. I found a page which did it like i want... www.enooa.com
thanks for any help

**Comment by alvarotrigo** [comment]
Yeah it is.
But this is not a fullPage.js specific issue. You'd better ask in other place such as stackoverflow.com
