### ISSUE TITLE
Javascript version - Getting undefined on nextSlideIndex from onSlideLeave event

### ISSUE THREAD

**Issue by a-p-co** [alvarotrigo/fullPage.js#2450]
Hi, I'm using the FullPage Pure Javascript and all is working good right now, but I receive undefined from the nextSlideIndex, all the rest output good on the console, any idea why?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by a-p-co** [comment]
Hi @alvarotrigo, sorry, totally right, I have isolated the problem on this codepen, you can check the console log.

http://codepen.io/adrianperez/pen/ObEQJE

**Comment by alvarotrigo** [comment]
That's the demo that it is included in the github folder. What did you change? 
Steps to reproduce it?  Browser and device?

**Comment by a-p-co** [comment]
Hi @alvarotrigo, I didn't need to change anything, just added the onSlideLeave event to console the nextSlideIndex, if you saw the console you will see the undefined value.

You need to go to the slider in order to have the error.

**Comment by alvarotrigo** [comment]
> You need to go to the slider in order to have the error.

That's what I was missing :) 

Docs are not updated. The Javascript version doesn't provide that parameter as can be seen in [the code](https://github.com/alvarotrigo/fullPage.js/blob/master/pure%20javascript%20(Alpha)/javascript.fullPage.js#L1533).

Feel free to create a PR to add the parameter. It is basically adding `slideIndex`.

**Comment by a-p-co** [comment]
Ok @alvarotrigo! I will do that, thanks.

**Comment by alvarotrigo** [comment]
Fixed in the latest version.
