### ISSUE TITLE
page structure breaks and becomes unusable upon screen resize

### ISSUE THREAD

**Issue by Inayat-C** [alvarotrigo/fullPage.js#2451]
### Description

I am using fullpage.js on a page of a site i'm building. Everything is working as intended and i've been very happy with the experience thus far. However, i've ran into one small issue which i can't seem to resolve.

I've set the responsiveWidth: 961 so when the screen size is below 961px, the slider feature is disabled. Now when trying to resize the screen (up and down) on the FIRST slide (labelled: properties) past the above mentioned breakpoint, everything is fine.
However when trying to resize the screen when the viewport is on the second (and above) slides, the html structure completely breaks below width 961px.

Now you may say in a real world scenario, no user is going to be playing around with the dev tools and resizing the window. However, when on a tablet (tested on an iPad) and you turn to landscape mode, it triggers this issue. 

Thank you in advance!

### Link to isolated reproduction with no external CSS / JS

http://jsfiddle.net/3fbub0he/

### Steps to reproduce it
1. Position viewport on second or third slide
2. resize window below 961px
3. [and so on...]

### Versions 
Chrome, iMac Late 2013, OSX El Capitan.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2447 and I already ansswered you [in stackoverflow](http://stackoverflow.com/a/41057062/1081396).
