### ISSUE TITLE
Youtube doesn't pause when going to other slide.

### ISSUE THREAD

**Issue by ppaaccoo** [alvarotrigo/fullPage.js#2452]
Hi Álvaro! 

I am having the following problem: Youtube window doesn't pause when I go to other slides.

Here is a link to the jsfiddle isolation, but I don't know why I cannot make it work (I am new in all of this).
I hope the problem is still visible: https://jsfiddle.net/xo1dxrbd/

It happens in all browsers.

Sorry for the poor isolation, I've been checking others and I cannot figure out what is wrong with this one...

**Comment by alvarotrigo** [comment]
Your reproduction doesn't work at all. See the console full of errors.

**Comment by ppaaccoo** [comment]
Hi! Thanks for the prompt response.

    Ok, no errors now.
    But I don't know why the videos still doesn't load. They do on my web, tho.

    Here is the new link: http://jsfiddle.net/qn084vmn/52/

    Grab my hand and imagine than they were loading (faith jump).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ppaaccoo** [comment]
Well, I have just checked after downloading the latest version of the plugin that what worked until yesterday, the lazy load of videos, doesn't work anymore. Now it happens to me the same it happened in jsfiddle.

Is there any way to access previous versions of the plugin?

**Comment by ppaaccoo** [comment]
Description: Youtube doesn't pause when you navigate away from a section or slide.

Link to isolated reproduction with no external CSS / JS: http://jsfiddle.net/qn084vmn/59/

Steps to reproduce it:

[First step]: Click on the video.
[Second step]: Move to another slide.
[Third step]: Keep hearing the music because the video has not paused.

[Browser: chrome, operative system: windows, device: laptop, temperature: room temperature]

**Comment by alvarotrigo** [comment]
Add `&enablejsapi=1` at the end of the video URL.
Use this instead:

````javascript
        var embed = "https://www.youtube.com/embed/ID?autoplay=1&enablejsapi=1";
```

fullPage.js adds it by default to all video elements present on page load. Yours isn't. And that's the reason why its failing to pause.

**Comment by ppaaccoo** [comment]
Fuck yeah!

You are the best, man.

Many, many thanks.
