### ISSUE TITLE
Possible to have parallax scroll implement for section when it becomes in viewport

### ISSUE THREAD

**Issue by whnunlife** [alvarotrigo/fullPage.js#2453]
Working on a design, where we want to utilize the parallax effect, but the sections above or below it, need to scroll normally.

So the use case is, the user lands the page and are able to scroll down normally thru various sections that are not part of the parallax effect. But once the parallax section comes into viewport, then parallax effect is implemented.

Once the user get's to the last section of the parallax, they then can continue to scroll down the page normally.

Curious if this is possible?

**Comment by alvarotrigo** [comment]
Difficult to say with your description. Just try and come back if you face any problem. 
You can only achieve normal scrolling by using `scrollOverflow:true` as in [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html) or by using `autoScrolling:false`as in [this other one](http://alvarotrigo.com/fullPage/examples/normalScroll.html).

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
