### ISSUE TITLE
destroy() and 'active' class

### ISSUE THREAD

**Issue by niccolomineo** [alvarotrigo/fullPage.js#2455]
I am creating sort of a plugin for my website and I need to extend fullpage.js' default properties. I am using the destroy('all') method which destroys the markup and therefore removes the 'active' class as well.

Doing something like `$('#section_name').addClass('active');` after reinstantiating fullpage.js overrides direct linking to in-page anchors (which I am also using).

Reinstantiating after using the destroy() method (without the 'all' parameter passed) generates the error `fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!`. So that also appears to be a no go. 

### Description
1. instantiate fullpage.js
2. destroy('all') / destroy() fullpage.js
3. extend fullpage.js' default properties
4. reinstantiate fullpage.js

### Versions
Fullpage 2.8.9

**Comment by alvarotrigo** [comment]
Easy.
Destroy('all'), then initialize it, then add the `active` class manually by yourself to the section or slide that you want to.

**Comment by alvarotrigo** [comment]
See this answer of mine for an example of it: http://stackoverflow.com/a/36643702/1081396

**Comment by niccolomineo** [comment]
Hi, like I wrote in the OP, I tried already with a simple `$('#MY_SECTION').addClass('active');` but the very fist section still stays active (I have now both the first section and MY_SECTION active at the same time).

**Comment by alvarotrigo** [comment]
As i said, check the jsfiddle I provided in the stackoverflow answer.

**Comment by niccolomineo** [comment]
Great, I didn't know about the index() method, thanks! Now the active class is being added correctly. But #fullpage div's translate3D y-axis value won't change from 0. Is there any "orthodox" solution instead of getting the translate3D y-axis value from the previous (now destroyed) instance??

**Comment by niccolomineo** [comment]
... which I just tried and it does override link anchors too, so it would not be a good solution anyway.

**Comment by alvarotrigo** [comment]
All you need its done in the fiddle I created for the answer. As you can see its not 0 in there.

**Comment by niccolomineo** [comment]
This is what I have, incorporating things from your solution (I left out the slide related bits since I don't need them)... Translate3D does not change from 0... :\
```
    //remembering the active section
    var activeSectionIndex = $('.fp-section.active').index();

    // Extend fullpage.js' options
    fullpageOptions = $.extend({}, fullpageOptions, fullpageExtendedOptions);

    // Remove previous instance of fullpage.js
    $.fn.fullpage.destroy('all');

    // Create new instance of fullpage.js
    $('#fullpage').fullpage(fullpageOptions);

    $('.fp-section').eq(activeSectionIndex).addClass('active');
```

**Comment by alvarotrigo** [comment]
@niccolomineo nop. My solution initializes fullPage.js after adding the active class and not before.

**Comment by niccolomineo** [comment]
@alvarotrigo sorry, edited, but still no luck with getting this to work...

**Comment by niccolomineo** [comment]
In the code, it's still the first section / menu's first list item anchor showing up as active.

**Comment by alvarotrigo** [comment]
@niccolomineo lets not spam more this topic. Please open an issue in stackoverflow about it together with a reproduction of it in jsfiddle or codepen.

**Comment by niccolomineo** [comment]
Solved. After destroying the instance, I was targeting `.fp-section`, which doesn't exist yet, before reinstantiating. I used another selector and now it works. Thanks for your support!

**Comment by niccolomineo** [comment]
But your solution doesn't seem to take into account anchor links...
