### ISSUE TITLE
Use continuousHorizontal inside iframe

### ISSUE THREAD

**Issue by romanovma** [alvarotrigo/fullPage.js#2457]
Hi, is it possible to use continuousHorizontal plugin inside iframe? I think I did everything according to instruction(https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension) but still have `Unliscensed fullPage.js Extension` label. Thanks.

**Comment by romanovma** [comment]
Looks like it doesn't work even if it is not inside iframe.

**Comment by alvarotrigo** [comment]
Have you closed it for any reason?

**Comment by romanovma** [comment]
Yep, I just don't know the reason why it is not working even locally. Decided to investigate little bit more before posting.

**Comment by alvarotrigo** [comment]
You won't get amazing results in iframes :) 

It has been treated multiple times:
https://github.com/alvarotrigo/fullPage.js/issues/2444
https://github.com/alvarotrigo/fullPage.js/issues/2229
https://github.com/alvarotrigo/fullPage.js/issues/1621

It is a browser's limitation. Events won't get propagated.
