### ISSUE TITLE
scrollOverflow  In ie8 is invalid， The problem of Scrolloverflow. js?

### ISSUE THREAD

**Issue by zhangtian4330523** [alvarotrigo/fullPage.js#2459]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by zhangtian4330523** [comment]
The test many times, failure

**Comment by alvarotrigo** [comment]
scrollOverflow:true is not supported on IE 8 due to the vendor library (iScroll.js) not supporting it. 

I'll mark it as a documentation issue.

**Comment by alvarotrigo** [comment]
Fixed.
