### ISSUE TITLE
Keyboard scroll in scrollOverflow section

### ISSUE THREAD

**Issue by gregegan** [alvarotrigo/fullPage.js#2460]
### Description
I have seen a few issues discussing a related problems, but have not seen a clear solution. If I am mistaken, please direct me to the answer.

In the fiddle below, I have a `scrollOverflow:true` fullpage.js initialization. For accessibility reasons I need to allow the user to keyboard press the arrows to step through the sections. When using the keyboard, it just "jumps" to each section without the ability to scroll through a overflow section of long content.

How can I resolve this issue to have the keyboard presses emulate a scroll action when within a overflow section?

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/ck74t6ft/2/

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1065
fullPage.js doesn't yet provide a solution for that.

**Comment by gregegan** [comment]
Thank you for clarification & link to master issue.
