### ISSUE TITLE
Slides navigation going to other pages

### ISSUE THREAD

**Issue by rossparsons** [alvarotrigo/fullPage.js#2461]
I'm having an issue where when I navigate between slides in a section, the url updates to remove the hash, which causes the browser to navigate away, since it's creating a new, anchorless url. This happens with both arrows and dots navigation. Can't figure out if this is a Javascript issue or if I messed up the markup.

If you need my code, which pieces should I provide, and should I strip it of identifying materials?

**Comment by alvarotrigo** [comment]
> If you need my code, which pieces should I provide, and should I strip it of identifying materials?

All of them.
As detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues):

> An isolated reproduction of the issue will be required. Make use of jsfiddle or codepen for it if possible.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
