### ISSUE TITLE
Continuous horizontal not working in responsive mode

### ISSUE THREAD

**Issue by mikesmith93** [alvarotrigo/fullPage.js#2462]
I have searched for this issue and I cannot find any reference to it elsewhere but I apologise if this is a known issue that has already been dealt with.

I have a problem where the continuous horizontal extension works fine normally but seems to break when responsive mode is initialized. I set the plugin to enter responsive mode at a width of 767px and at this point it seems as though the continuous horizontal sliders return to the default behaviour of looping back to the start.

I have a link to a fiddle replicating the problem however as it is a paid extension and the fiddle contains my license key I would like to message you privately with the link to this. Please let me know how best to send this

1. Click on navigational arrows to ensure that the continuous horizontal scroll is working correctly
2. Resize the browser to below 767px wide to initialise responsive mode
3. See that the slides now loop back to the start (right to left) instead of being continuous as they were before

Seems to be present across all browsers and devices. I am running OX X Yosemite 10.10.5 and the issue is present in Safari, Chrome and Firefox. I also receive the same issue when testing from Safari on ios.

Any help would be greatly appreciated

**Comment by alvarotrigo** [comment]
> I would like to message you privately with the link this. Please let me know how best to send this

Contact me through my mail or through [the contact form in the website](http://alvarotrigo.com/#contact).

**Comment by alvarotrigo** [comment]
The issue has been solved and updated for future buyers.
