### ISSUE TITLE
how to apply fitToSection . when scroll is middle of a two sections

### ISSUE THREAD

**Issue by avinashdvv** [alvarotrigo/fullPage.js#2463]
In my website i have
1. fixed nav bar
2. scrollbar
 how can i apply fitToSection when scroll is middle of a two sections on scrolling

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
