### ISSUE TITLE
Center images in body section

### ISSUE THREAD

**Issue by agentlucky** [alvarotrigo/fullPage.js#2470]
Due to seo-reasons i put my images into the bodysection rather than as background pictures like so:

`<div id="fullpage">`
`<div class="slide" ><img class="l-cover" data-src="imagelink1"></div>`
`<div class="slide" ><img class="l-cover" data-src="imagelink2"></div>`
`<div class="slide" ><img class="l-cover" data-src="imagelink3"></div>`
`</div>`
 
I gave the img tag the l-cover-class with the following style:

`img.l-cover {
	display:block;
	width:100vw;
	min-height:100vh;
	min-width:calc(100vh * 3 / 2);
}`

Everything is fine but i want the pictures to center, when the screen gets smaller. right now the pictures stay fix at the left side. 
Can anyone help me?

Thanks

**Comment by alvarotrigo** [comment]
That's a CSS or HTML question. You'd better ask in other places such as  http://stackoverflow.com/
