### ISSUE TITLE
Resize browser = video pauses (only on second slide and upward)

### ISSUE THREAD

**Issue by RedRooster1234** [alvarotrigo/fullPage.js#2471]
Hi - great plugin - thank you.

When I resize browser, the video pauses. This seems to be the case for both locally hosted (html 5) and youtube videos.

This only seems to happen second slide and up, ie a video on the first slide works as expected (carries on playing on a resize)

Isolated issue here:
https://codepen.io/marklawrencedesign/pen/JbVaOG

I wrote some text on each slide as an instruction to articulate what I mean - is this a bug or am I missing something?

I tried in Chrome, FF & Safari, all OSX.

Thanks

**Comment by RedRooster1234** [comment]
just to add, I am using the latest version fullPage 2.9.2 and still the same issue

**Comment by alvarotrigo** [comment]
Thanks for reporting it. I'll investigate it whenever I find some time these days for the next release.

**Comment by RedRooster1234** [comment]
Sure - no problem.

I had a dig around in your code :)

if I comment out line 1427, the call to the stop function:

`stopMedia(v.activeSection);`

...it stops the issue, but obviously I loose the lovely functionality I need.

Fantastic work on this - has blown my mind the amount of work you have invested.

**Comment by RedRooster1234** [comment]
I may be speaking too soon, but have managed to secure my own workaround utilising your stopMedia function, and firing my own check function within the onLeave parameter.

Thanks again!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.9.4

**Comment by alvarotrigo** [comment]
Fixed in the latest release 2.9.4
