### ISSUE TITLE
Can i use fullpage.js with angularjs

### ISSUE THREAD

**Issue by awsomedesigner** [alvarotrigo/fullPage.js#2474]
### 
I want to use fullpage.js with angulajs. So can i use it with angular js ?

### Versions 
Angularjs  V1.5.0
Bootstrap V3.3.6

**Comment by alvarotrigo** [comment]
You can try [googling "angular fullpage.js"](https://www.google.es/search?q=angular+fullpage.js&oq=angular+fullpage.js&aqs=chrome..69i57j0l3j69i60l2.277j0j7&sourceid=chrome&ie=UTF-8) and you'll find many results :)
Also, here in the docs [you'll find links to angular directives for it](https://github.com/alvarotrigo/fullPage.js#resources).

**Comment by awsomedesigner** [comment]
Is there any option for responsive height in full page js for angular ?

**Comment by alvarotrigo** [comment]
I'm not the author of any angular directive or component. 
I can only refer you to [the fullPage.js docs](https://github.com/alvarotrigo/fullPage.js) where you can find the option `responsiveHeight`
