### ISSUE TITLE
Trying connect fullPage with Parallax on css3

### ISSUE THREAD

**Issue by VanIvano** [alvarotrigo/fullPage.js#2475]
Hey! 
Im trying to get work pure css3 Parallax on FullPage.js, and its doesn't work.

I took [this one](http://keithclark.co.uk/articles/pure-css-parallax-websites/), spent 4 hours, but still its doesn't work.

whats a problem? whats  wrong with it? in fullPage.js's file `scrollbar:true` `css3:true`

P.s. so sorry for my english.. im russian.

**Comment by alvarotrigo** [comment]
See the [FAQs regarding parallax](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#parallax-doesnt-work-with-fullpagejs).

**Comment by alvarotrigo** [comment]
If you still having problems using `scrollBar:true`, then the issue is not in fullPage.js but in your own external code. You'd better ask about it in other place such as stackoverflow.com

**Comment by VanIvano** [comment]
Alvaro, could you give me advice which one parallax is a best to working with your FullPage?
Mb you allready have some practic with this, and know some good parallax script or something for your fullpage?

**Comment by alvarotrigo** [comment]
> Alvaro, could you give me advice which one parallax is a best to working with your FullPage?

Nop. I haven't even tried it.

**Comment by acitjazz** [comment]
hi  @VanIvano ,
i have an idea to create simple paralax with css animation , please check my pen
http://codepen.io/acitjazz/pen/wgwLyN
