### ISSUE TITLE
Scrolling just works for the first section

### ISSUE THREAD

**Issue by HabelStefan** [alvarotrigo/fullPage.js#2476]
Hello,

i fixed the problem below as it was a problem with the naming in my theme.

For some reasons i do have to create a full page with several sections that cover in sum the complete height. But i would like to scroll only to the top section.
But if i do the following

section 1 <- scroll to
section 2
section 3
section 4 <- scroll to
section 5
section 6

and so on

i does not work.

Additionally, the padding top does not show any effect. My header header is 100px but when i add

PaddingTop:100px i completely stops working
PaddingTop:100 does nothing

Any ideas?

### Description

My problem is that scrolling does only work for the first to second section.
The sections itself are recognized (#sectioname added to url corretly) and after waiting in that section the section is aligned correctly.
But when scrolling to that section i can scroll freely.

If you like please visit 

https://bqtygd2v.myraidbox.de/anfrage-3/#firstPage

login with

rb/wetunizo

Thank you!
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

No external CSS or JS files.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
