### ISSUE TITLE
FullPage section between regular sections?

### ISSUE THREAD

**Issue by JeffAspen** [alvarotrigo/fullPage.js#2477]
Is it possible have FullPage sections between regular website scrolling sections? So my page would have a top section of copy not using FullPage, then the FullPageJS section and last another copy section not using FullPageJS. 

Here is a copdpen to demonstrate it.
http://codepen.io/JeffAspen/pen/XNvEmj

**Page Layout**
1. [Non FullPage section (regular scrolling)]
2. [FullPage Section with Navigation]
3. [Non FullPage section (regular scrolling)]

I also don't want the navigation to display on the non FullPage section

**Comment by alvarotrigo** [comment]
No. 
The most you can do is make use of `scrollOverflow:true` as in [this example](http://alvarotrigo.com/fullPage/examples/scrolling.html). 
This way you can emulate the behaviour of a normal site with scroll bar in any section you need to.

**Comment by alvarotrigo** [comment]
> I also don't want the navigation to display on the non FullPage section

You can hide it using callbacks.

**Comment by JeffAspen** [comment]
@alvarotrigo Cool thanks for the quick reply! I'll try that. Can you have navigation on the side, but not have anchor links in the url?

**Comment by JeffAspen** [comment]
@alvarotrigo Can you have navigation on the side, but not have anchor links in the url?

**Comment by alvarotrigo** [comment]
> Can you have navigation on the side, but not have anchor links in the url?

Of course. Read the docs and see the examples available. 
Just don't use the `anchors` option or use `lockAnchors`.
