### ISSUE TITLE
Question about autoplay slides in combination with HTML5 page visibility API

### ISSUE THREAD

**Issue by sneakyvince** [alvarotrigo/fullPage.js#2478]
Hello,

I'm trying to modify the autoplay slides method seen at #532 to stop when the user switches away to another tab. 

The HTML5 visibility API function should look something like this:

```
document.addEventListener("visibilitychange", function() {
    
if (document.hidden) {     
//stops the autoplay slider

} else {
//resumes the autoplay slider
}});
```

Thus far I've tried simply adding a variable where the "15000" number should be but this approach doesn't work.

```
afterRender: function () {
        slideTimeout = setInterval(function () {
             $.fn.fullpage.moveSectionDown();
            }, 15000);

        }
```

Is there any way to get this working?

Thanks in advance

**Comment by alvarotrigo** [comment]
That's a Javascript question and not a fullPage.js one. 
Use the `clearTimeout` function of Javascript whenever you want to clear it.

**Comment by alvarotrigo** [comment]
See this question too: http://stackoverflow.com/questions/35296112/autoplay-for-slides-in-fullpage-js
