### ISSUE TITLE
owl 2 with fullpage.js conflict

### ISSUE THREAD

**Issue by joylord** [alvarotrigo/fullPage.js#2479]
HI
I use the plugin on your site fullpage.js and I have a conflict with [Owl 2 Carousel](https://github.com/OwlCarousel2/OwlCarousel2).
If on one screen, I scrolling to the center carousel, then going to the next screen, my carousel begins again with the first object.
How can I fix this bug and make the the carousel was always in the right place?
I will be grateful for your reply.

in this video I showed this bug
https://youtu.be/1q5mtMqB4yU

link to my site
http://juscutum.osadchy.pp.ua/

**Comment by alvarotrigo** [comment]
Definitely not a fullPage.js issue as fullPage.js has no action over the OWL carousel.
