### ISSUE TITLE
Orientation change on somet tablets

### ISSUE THREAD

**Issue by Rabauken** [alvarotrigo/fullPage.js#248]
On the tablet websites do not display and do not scale well. In portrait orientation shows more than one section, while in landscape orientation section is cut off. On my 8 inch tablet problem occurs on all browsers except Chrome on another 7-inch tablet, the problem also appears on Chromie. If you refresh the page, the error disappears, but when you change the orientation back again.

**Comment by RikuAnsem** [comment]
Hi.
Alvarotrigo, thanks for the script and for the fix:

```javascript
var isTouchDevice = navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry|BB10|Windows Phone|Tizen|Bada)/);
var supportsOrientationChange = "onorientationchange" in window,
orientationEvent = supportsOrientationChange ? "orientationchange" : "resize";

$(window).bind(orientationEvent , function() {
	if(isTouchDevice){
		$.fn.fullpage.reBuild();
	}
});
```

It works for me (and... everybody?)
Regards!

**Comment by alvarotrigo** [comment]
@RikuAnsem why would you do that? Were you having any problem with fullPage.js 2.5.6 ?

**Comment by RikuAnsem** [comment]
Well... I don't very sure why I have problems, but is the main problem, on rotating in android it don't recognize width and height.
ResizeHandler is 'resize': true?
It seems not work...

**Comment by alvarotrigo** [comment]
@RikuAnsem are you using the latest version 2.5.6? And, what do you mean with "it doesn't recognize with and height"? What's exactly the problem? Could you add some pictures?

**Comment by alvarotrigo** [comment]
@RikuAnsem does the [demo page](http://alvarotrigo.com/fullPage/) works well for you on your device?

**Comment by RikuAnsem** [comment]
First of all, sorry for my bad english.
I'm using Nexus 5.

The problem when moving to the upright position (also if loaded horizontally)

I'm using too:
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```
Link (without fixed "plugin" and "resize" disabled... I'm using "fixed" trhough css like the example): http://test.emosistemas.com/


Some screnshots (sorry for the big resolution):

![1rst-load](https://cloud.githubusercontent.com/assets/3286840/5975058/ecfed728-a87b-11e4-98c8-498f8119d244.jpg)
![2nd-rotate](https://cloud.githubusercontent.com/assets/3286840/5975060/ed267c2e-a87b-11e4-8d98-1f7ba04b2b4a.jpg)
![3rd_b-scrollingverticalbugued](https://cloud.githubusercontent.com/assets/3286840/5975059/ed2639d0-a87b-11e4-9470-ffc54f770852.jpg)
![3rd-returnverticalposition](https://cloud.githubusercontent.com/assets/3286840/5975061/ed27af0e-a87b-11e4-839e-6ae096de3141.jpg)

**Comment by alvarotrigo** [comment]
@RikuAnsem does the [demo page](@RikuAnsem does the demo page works well for you on your device?) works well for you on your device?

**Comment by alvarotrigo** [comment]
@RikuAnsem  ok, the problem dioesn't seem to be in fullpage.js, but in the images you are using. They don't get resized properly. It might be the fault of any other external plugin you are using. 

Try removing the external plugin.

**Comment by RikuAnsem** [comment]
I'm not using currently any script, only JQuery and fullpage.
The demo page seems to work correctly.
Don't worry about it, If I have problems in the future I try to fix or comment here.

A lot of thanks and regards

**Comment by alvarotrigo** [comment]
@RikuAnsem I still looking the issue. Trying to figure out what's going on.

**Comment by alvarotrigo** [comment]
@RikuAnsem it seems the problem is related with the use of images. I created [this basic example](http://alvarotrigo.com/fullPage/aaaa.html) to test it.

**Comment by RikuAnsem** [comment]
Thanks, I'm trying to copy this system: http://www.newjumoconcept.com/en/#studio-photos
In my phone it seems work correctly (I tried to use some options and enable "responsive", but it still fails).

I have other problem, I've reuploaded the web fixed (with the plugin) and some addons... In the mobile, when you click "textarea" it crashes the fullPage script (only if is the last element of the form before submit button).
¿Any idea?

http://test.emosistemas.com/

Thanks in advanced.

**Comment by alvarotrigo** [comment]
They are using the version 2.1.8. Try with it and let me know:
https://raw.githubusercontent.com/alvarotrigo/fullPage.js/171b919c8a0ebfd87de24df15245b319833e4dab/jquery.fullPage.js

**Comment by RikuAnsem** [comment]
Thanks, I will test it on Monday
Regards

**Comment by RikuAnsem** [comment]
Hi again.
I tried to use 2.1.8 version, but still fails, when you clic in the "textarea" the page is resized and it broke all upper images.
I have to do a fix with javascript because I would like to do the second page (contact form) with native scroll in mobile.

If in the future is fixed I will try to update it.

Thanks for all and regards.

**Comment by alvarotrigo** [comment]
> I tried to use 2.1.8 version, but still fails, when you clic in the "textarea" the page is resized and it broke all upper images.

Here you are talking about another problem. I would recommend you to open a new issue. Possibly very related with [this one](https://github.com/alvarotrigo/fullPage.js/issues/145).

**Comment by RikuAnsem** [comment]
I thought the problem was the same.
Sorry and thanks for all!
