### ISSUE TITLE
Unable to shift section back in iOS mobile phone 

### ISSUE THREAD

**Issue by horwengliang95** [alvarotrigo/fullPage.js#2480]
###Description
After test in browser Google Chrome in desktop, all works well. For Android phone, it can work well also. But, when try to test in iOs mobile phone, it can load the webpage, when it shifts one section down, user couldn't shift up back or down to other section. It jams at the second section only.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Versions 
[Google Chrome, Safari, iOs 10.2, Android 6.0.1]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
