### ISSUE TITLE
IE9 scroll does not work well

### ISSUE THREAD

**Issue by edwardfhsiao** [alvarotrigo/fullPage.js#2481]
Hi Álvaro

in 
```js
        function prepareDom(){
            container.css({
                'height': '100%',
                'position': 'relative'
            });
```
you set container's position to 'relative', but it does not work well in IE9. Two sections are fine, however if there were more than 2 sections, no matter how you scroll, it will still stay on section 2.

change it to 'absolute' can fix the problem;
```js
        function prepareDom(){
            var position = 'relative';
            if (!options.css3){
                position = 'absolute';
            }
            container.css({
                'height': '100%',
                'position': position
            });
```

though IE9 does not support css3, it still works with 2d, hope you can use it
```js
 var translate3d = 'transform:translate(0px, -' + Math.round(v.dtop) + 'px)\9'; //still works
```

**Comment by alvarotrigo** [comment]
I can not reproduce it in any of the examples online.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
