### ISSUE TITLE
Drag And Move Extension: dragging inside scroll:overflow element

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2482]
I think this has not been fixed in the jquery.fullpage.extensions.min.js

**Link to isolated reproduction with no external CSS / JS** 
https://jsfiddle.net/0hLzxrea/86/ — fullPage 2.9.2 - Extensions 0.0.6

**Steps to reproduce it** 
If you try to scroll the text inside the white box it won't scroll.  

**Versions** 
iPhone 6s iOS 10.2

**Comment by alvarotrigo** [comment]
You are using the css of version 2.6.6?

**Comment by thisisfed** [comment]
No you can try with the latest and I think it will be the same. I just took an old Jsfiddle and updated with just the extensions.js.

**Comment by thisisfed** [comment]
You fixed it in the 2.8.8 maybe not in the extensions version?
https://github.com/alvarotrigo/fullPage.js/issues/2482

**Comment by alvarotrigo** [comment]
It doesn't work in 2.9.2 normal version either:
https://jsfiddle.net/0hLzxrea/90/

You can even try with the unminified one. You'll get the same result. So that's something that needs to be checked.

**Comment by thisisfed** [comment]
It works to me with the 2.9.2, I'm currently using it in my webpage and it works perfectly.

**Comment by alvarotrigo** [comment]
I can't reproduce that in jsfiddle.

**Comment by thisisfed** [comment]
Here it is: https://jsfiddle.net/0hLzxrea/95/

**Comment by alvarotrigo** [comment]
Then here you have it working with the extensions file:
https://jsfiddle.net/0hLzxrea/104/

**Comment by thisisfed** [comment]
If you try and add the "drag and move" extension then, it won't work. I just don't know how to use it on jsfiddle without the license key.

**Comment by alvarotrigo** [comment]
@thisisfed you didn't mention anything about this extension before. 
That's a totally different issue. In fact, I would say it is not possible at the moment.

The [demo page](http://alvarotrigo.com/fullPage/extensions/drag-and-move.html) states sections with scrollOverflow won't be scrolled by dragging. 
And I would say neither any other `overflow:scroll` element. I'll add it into the demo whenever I can.

[Contact me](http://alvarotrigo.com/#contact) if you want a refund.

**Comment by thisisfed** [comment]
My fault, I thought it was an extensions problem. I?ll drop you a line and I'll buy again if this thing will be fixed. I loved it!

**Comment by alvarotrigo** [comment]
More specific docs added to the demo page.

**Comment by alvarotrigo** [comment]
> The [drag and move demo page](http://alvarotrigo.com/fullPage/extensions/drag-and-move.html) states that sections with scrollOverflow won't be scrolled by dragging.

This is not the case anymore on fullPage.js 4.0.37
Now you can use dragging inside scrollOverflow. And it works as expected! 🥳
