### ISSUE TITLE
SideNav is appearing above a higher z-indexed element

### ISSUE THREAD

**Issue by AlcuinGuest** [alvarotrigo/fullPage.js#2483]
![screenshot 25](https://cloud.githubusercontent.com/assets/17879993/21590199/8a72c362-d0f1-11e6-95ee-2ea4e416d94c.png)
![screenshot 26](https://cloud.githubusercontent.com/assets/17879993/21590200/8a77a742-d0f1-11e6-986e-f78980716913.png)
![screenshot 27](https://cloud.githubusercontent.com/assets/17879993/21590201/8a7dd252-d0f1-11e6-9c78-47d776f95651.png)

Firstly, absolutely love fullPage.js. It is really something special.

However, the sideNav (#fp-nav), which has a z-index of 100 (from jquery.fullPage.css), is appearing above my fullscreen div of z-index 200+. The div is positioned absolutely, and i cannot for the life of me figure out why this is happening. 

If anyone has had this problem before or has an idea of what might be happening, please let me know!

**Comment by thisisfed** [comment]
http://jsfiddle.net?

**Comment by AlcuinGuest** [comment]
Its a huge project, making a jsfiddle would be incredibly time consuming. Just interested to see if anybody knows what this might be. The CSS doesn't make sense?

**Comment by thisisfed** [comment]
Have you tried to add the "!important" to the fullscreen div?

**Comment by alvarotrigo** [comment]
You'd better ask in another place such as stackoverflow.com with the CSS tag.
This is clearly a CSS issue and not a fullPage.js one.
