### ISSUE TITLE
*ngFor for angular2

### ISSUE THREAD

**Issue by mafav** [alvarotrigo/fullPage.js#2484]
Hi,

Duplication of this issue in [ng2-fullpage](https://github.com/meiblorn/ng2-fullpage/issues/180)

Wondering if there is going to be support for Angular2 directives like *ngFor.

The author of ng2-fullpage has gone MIA so wondering if you have any insight.

**Comment by alvarotrigo** [comment]
I'm afraid I do not provide support for any angular directive or module and this forum is only to treat issues directly related with fullPage.js code.
