### ISSUE TITLE
class="active" added to <a element

### ISSUE THREAD

**Issue by motylanogha** [alvarotrigo/fullPage.js#2487]
### Description
Hi, 
Would it be possible to add class="active" to <li element, not <a please?

Thank you,
Kind regards, 
Mariusz

### Versions 
chrome, newest FullPage

**Comment by alvarotrigo** [comment]
Should I assume you are talking about the bullets elements? 
If so, no. It is not possible I'm afraid.

**Comment by motylanogha** [comment]
Yes, it regards of bullets. What a pity. There's no way to style active text at the bullet that way :(

**Comment by alvarotrigo** [comment]
> There's no way to style active text at the bullet that way

There's always one :) 

1 - Use the state class added to the body 
2- Use callbacks

For both, check the docs.

**Comment by motylanogha** [comment]
I did not notice <body class added. Thank you!
