### ISSUE TITLE
JS just in active section

### ISSUE THREAD

**Issue by agentlucky** [alvarotrigo/fullPage.js#2488]
I have several Sections and on every Section there is a Button for calling a Text description via toggleClass JavaScript. 

`<script>
$('.info').on('click', function (e) {
  e.preventDefault();
  $('.description').toggleClass('description--active');
});
</script>
`

The descriptions on every Section got the same class. On small Devices it happens sometimes that the Description of the Last Section reaches into the current one, cause obviously with every click on the Buttons all the description are called. 
Is there a way just to call the Description on the current Section?
Thanks

**Comment by alvarotrigo** [comment]
Some options:

1 - Use a different class for each button
2- Take advantage of [the state classes fullpage.js provides](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs)
