### ISSUE TITLE
Can't select text by click-and-drag when using scrollOverflow

### ISSUE THREAD

**Issue by ryoarmanda** [alvarotrigo/fullPage.js#2489]
Cannot select text by click-and-drag when `scrollOverflow=true`, the movement however drags the section. The problem does not reproduce when `scrollOverflow=false`. Selecting text by Ctrl-A or Shift-Arrow Key is still possible (only inside focus-able elements like `<textarea>`). Please make a fix on this.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/7f58uoyw/
(jQuery 3.1.1, fullPage.min.js 2.9.2, scrolloverflow.min.js 2.9.2)

### Steps to reproduce it
Try to select any text by clicking and dragging the cursor.

### Versions 
Chrome Version 55.0.2883.87 m

**Comment by alvarotrigo** [comment]
Try using the following fullPage.js option:

```javascript
    scrollOverflowOptions: {
    	preventDefault: false
    },
```

Not sure of the consequences this might have on some devices, but let me know if you find any.

**Comment by magnussuther** [comment]
`preventDefault: false` didn't do it for me, and as you can see in your jsfiddle, it is pretty difficult to select multi-line text in the orange section. 

`scrollOverflowOptions: { disablePointer: true, },` however solved my particular problem.

**Comment by mikelui** [comment]
None of the aforementioned options exist anymore as of version 3.0.1. `dragAndMove` has been added and requires a license.

Are the easiest ways to select text w/ scrollOverflow just using an older version or buying a license?

**Comment by alvarotrigo** [comment]
> None of the aforementioned options exist anymore as of version 3.0.1.

Sure they do. Those options are for iScroll, the vendor library used when using scrolloverflow, and therefore has nothing to do with the new fullPage.js version.

See [this demo](https://jsfiddle.net/1kyuL4em/96/).

**Comment by alvarotrigo** [comment]
> dragAndMove has been added and requires a license.

Drag And Move has nothing to do with scrollOverflow. In fact, they are not fully compatible.

**Comment by Korveld** [comment]
@magnussuther Thank you man! you're a lifesaver)

**Comment by alvarotrigo** [comment]
This is no longer a problem on fullPage.js version 4:
https://codepen.io/alvarotrigo/pen/oNroZqX
