### ISSUE TITLE
How to define the slider speed

### ISSUE THREAD

**Issue by blank-tree** [alvarotrigo/fullPage.js#2490]
I'm using fullpage.js with a lot of slides. But we don't need the animation from right to left, just an instant switch when you click on the arrow. How can I remove the animation completely or set it to 0ms?

I used for the moment 
`.fp-slidesContainer {
  transition: all 0ms !important;
}`

But with this the problem remains, that you can't switch fast between slides, because the buttons are deactivated for the same amount of time it would normally take to complete the slide animation

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1068

You can try creating your own arrow elements and do this:
