### ISSUE TITLE
Scrolling sections not working in IE

### ISSUE THREAD

**Issue by sarabarrerariano** [alvarotrigo/fullPage.js#2491]
### Description
Scrolling in Internet explorer 11 is not working, I tested it with http://alvarotrigo.com/fullPage/ too.

### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/

### Steps to reproduce it
Just scroll

### Versions 
IE11

**Comment by alvarotrigo** [comment]
The demo site was not using the latest fullpage.js 2.9.2. Make sure to always use the latest version. 

Nevertheless, I can see it working as expected. Tested using Browserstack.com in IE 11 in windows 8 and in windows 10 latest IE.
