### ISSUE TITLE
Inline styles to be moved inside the external css?

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2492]
### Description
I was wondering: isn't it better to remove all the inline styles from the .js and move them inside the .css? Cause if someone want to customize the appearance it will be much easier to use the minified version without looking for all the inline css inside.

**Comment by alvarotrigo** [comment]
Be more specific.

**Comment by alvarotrigo** [comment]
Closed as no further details were provided.

**Comment by thisisfed** [comment]
I was referring to this i.e.
`            $(SECTION_NAV_SEL).css('margin-top', '-' + ($(SECTION_NAV_SEL).height()/2) + 'px');
`
I'm sure there's a css way (using tables?) to vertically centering the dots instead of adding inline css.
