### ISSUE TITLE
Scroll after refresh.

### ISSUE THREAD

**Issue by kayaz** [alvarotrigo/fullPage.js#2495]
I have 100 slides and i navigate between them using [next] and [prev] buttons. When i go to item number 80 and refresh site script scroll slide by slide to this 80. Is any way to detect in URL what number is and open directly this slide

**Comment by alvarotrigo** [comment]
You can use `animateAnchor:false`, but that will get applied to all sections and it won't show the animation in any case.

But you can do something like the following:

```javascript
$('#fullPage').fullPage({
    animateAnchor: parseInt( window.location.hash.replace('#', '') ) < 10
})
```

Supposing your anchors are numbers ( from 1 to X ), then I'm saying that i only want to use the scrolling animation on sections below number 10.

**Comment by kayaz** [comment]
Oh man thank you. This is working good, animation working with buttons (next/prev) but when i refresh site is load first then just jump to this section. Im gonna make some preloader when refresh site and after load slider hide it.

**Comment by alvarotrigo** [comment]
> but when i refresh site is load first then just jump to this section.

I already told you how to solve it.

**Comment by kayaz** [comment]
I have one section and 100 slides (News articles). And whit `animateAnchor:false` now is working good. But when i refresh site i see first slide and after few ms it jump to this slide like i want. But i want hide this "jump effect" and im gonna make some loader to do this. :)

**Comment by alvarotrigo** [comment]
If you believe it is a bug please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
