### ISSUE TITLE
Same background, multiple sections

### ISSUE THREAD

**Issue by yesiamben** [alvarotrigo/fullPage.js#2496]
Álvaro - really great plugin. 

Have read through the docs and a bunch of the issues, can't find anything that answers this, and playing around I can't seem to do it. If possible, a pointer would be fantastic.

Is it possible to keep the same background (colour here used for simplicity, but it would actually be a video or image) across multiple sections - I suppose almost like fullpage within fullpage. For instance:

```
<div id="fullpage">
    <div class="section" style="background-color: #c00">section 1</div>
    <div  style="background-color: #00c">
        <div class="section">section 2</div>
        <div class="section">section 3</div>
    </div>
    <div class="section"  style="background-color: #333">section 4</div>
    <div class="section"  style="background-color: #fff">section 5</div>
</div>
```

Obviously this doesn't work, but you can see what I'm trying to achieve.

Thanks!

**Comment by alvarotrigo** [comment]
Why don't you use a fixed background? Or a fixed element with a video? 
Check the [backgroundsFixed](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) example contained in the library.

**Comment by yesiamben** [comment]
Thanks Álvaro - if I don't slide on the section this works fine with images, but I can't see how I can get it to work with videos and lazy loading.

So if I wanted a video as the background of 3 slides, for instance:

```
<div id="fullpage">
    <div class="section" style="background-color: #c00">section 1</div>
    <div  class="video-background">
        <div class="section">section 2</div>
        <div class="section">section 3</div>
        <div class="section">section 4</div>
    </div>
    <div class="section"  style="background-color: #333">section 5</div>
    <div class="section"  style="background-color: #fff">section 6</div>
    <div  class="picture-background">
        <div class="section">section 7</div>
        <div class="section">section 8</div>
    </div>
    <div class="section"  style="background-color: #fff">section 9</div>
</div>
```

Make sense?

All I can think is leave the slide background transparent and create the element behind the fullpage div and load/fade them in when scrolling into the area before it?

```
<div id="video-to-fade-in"></div>
<div id="picture-to-fade-in"></div>
<div id="fullpage">
    <div class="section  fade-in-the-video-here" style="background-color: #c00">section 1</div>
    <div class="section">section 2</div>
    <div class="section">section 3</div>
    <div class="section">section 4</div>
    <div class="section fade-out-the-video-here"  style="background-color: #333">section 5</div>
    <div class="section fade-in-the-picture-here"  style="background-color: #fff">section 6</div>
    <div class="section">section 7</div>
    <div class="section">section 8</div>
    <div class="section fade-out-the-picture-here"  style="background-color: #fff">section 9</div>
</div>
```

Thanks!

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any feature for that.
You'll have to do it by yourself somehow. 

You'd better ask in other place such as stackoverflow.com for those kind of generic questions.

**Comment by yesiamben** [comment]
No worries. I'll figure something out! Thanks @alvarotrigo !

**Comment by childproof** [comment]
Can you let me know your progress? @yesiamben

**Comment by yesiamben** [comment]
Sure, @childproof - I wrote something to preload video a few slides before I needed it, and then gave each slide either a transparent background or a white background. The videos are in fixed block elements which then fade in and out as necessary, called as the slide appears / disappears. It worked pretty well and meant I could have multiple slides over the same background.

**Comment by childproof** [comment]
Any way you can share the code with me?
