### ISSUE TITLE
Issue with fullPage only in wrapper

### ISSUE THREAD

**Issue by queczax** [alvarotrigo/fullPage.js#2497]
I wanna use fullpage to switch between sections in wrapper, body is "overflow: hidden". It's hard to explain. Just check out the codepen
http://codepen.io/qurczax/full/LxVwdz/

**Comment by alvarotrigo** [comment]
fullPage.js is mean to be a full screen script I'm afraid.

**Comment by alvarotrigo** [comment]
The most I can suggest is the use of fixed elements around it. And the use of padding within fullPage.js.
