### ISSUE TITLE
Not working with full width iframe content

### ISSUE THREAD

**Issue by qwik3r** [alvarotrigo/fullPage.js#2498]
I'm embedding a full width iframe that has a mp4 (looping Cinemagraph) that is full width and height. It takes over the entire screen minus a small sliver a the top. If you try to scroll it won't do anything. If i mouse over the small sliver and scroll then it works. I suspect there is an issue with the iframe and script not playing nice together, not allowing me to scroll if it's just the iframe in the viewport. Any ideas would be great. Thanks.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2229
