### ISSUE TITLE
Scrolling issue on mobile

### ISSUE THREAD

**Issue by qwik3r** [alvarotrigo/fullPage.js#2500]
I'm experiencing a scrolling issue on mobile emulation (Chrome) in which a section that has content that extends past the view port on vertical view will auto scroll to the bottom and not allow me to actually see what's in the middle. https://cl.ly/252l062w1g42. It actually will scroll to the top, then if I manage to freely scroll to see the cut off portion after a second or so it will scroll to the very bottom.  

I've tried invoking the scrollBar option as well as the fitToSection: false in hopes it wouldn't try to scroll up but no avail. 

Any insight into this would be great, thank you.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
