### ISSUE TITLE
Suggestion: adding class ".visited" to the visited sections/slides and fp-tooltip.

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2501]
**Description**
I know this is something to be asked on Stackoverflow but I would love to add a class (.visited) to the visited sections when scrolling past them. Specifically to the fp-tooltip so that I can style them differently. I'm sure it's an easy trick.

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide such option. You'll have to code it yourself. Probably using the `afterLoad` function.
