### ISSUE TITLE
"background-attatchment:fixed;" does not fix all the section backgrounds

### ISSUE THREAD

**Issue by hormigaz** [alvarotrigo/fullPage.js#2503]
### Hi, I am trying to get fixed a background image into a section but I get some issues that I don't understand why...

If you check the codepen, you will see what I'm saying. You will see only the first background but not the other ones... But if you enable the option "scrollBar: true" in the JS screen then you will see all backgrounds fixed. Why is this happening? Can I get all backgrounds fixed whitout enabling scrollBar?

Another alternative is disabling scrollBar and modifying the line 93 of CSS screen. Change 'fixed' by 'scroll' and all backgrounds will appear... but not fixed, of course.

**I would like to achieve all fixed backgrounds with the scrollBar option disabled.**

**Comment by alvarotrigo** [comment]
That's a bug of some browsers that won't support the css3 property translate3d over fixed elements. It is clearly not a fullpage.js bug. 
See [this answer](http://stackoverflow.com/questions/23571578/chrome-issue-with-background-attachment-fixed-and-position-fixed-elements) in case it helps. Or [this other](http://stackoverflow.com/questions/20268962/fixed-attachment-background-image-flicker-disappear-in-chrome-when-coupled-with).

**Comment by alvarotrigo** [comment]
Asked multiple times: https://github.com/alvarotrigo/fullPage.js/issues?q=is%3Aissue+background-attachment+is%3Aclosed

**Comment by hormigaz** [comment]
Ok, thank you for the fast response! I'll be waiting for that extension. Gracias!
