### ISSUE TITLE
How can i disable the autoscrolling when a put the cursor bethween two page.

### ISSUE THREAD

**Issue by martin2630** [alvarotrigo/fullPage.js#2504]
I need to disable the scrolling to next section when i put the cursor between two pages/sections 
How can i do this?

Regards.

**Comment by alvarotrigo** [comment]
When you put the cursor? What do you mean? Are you talking about the option `fitToSection`? 
Just use `fitToSection:false` as detailed in the docs.

**Comment by martin2630** [comment]
Thank you for replying. 👍  it´s work for me.
Regards!
