### ISSUE TITLE
[Question] Best way to set up two websites with fullPage

### ISSUE THREAD

**Issue by mitfry** [alvarotrigo/fullPage.js#2505]
### Description
I need help finding the best suited way to properly setup my website using fullPage. 
My current setup is as below:
```
<wrapper>
   <section>
      <top menu> header of landing page based on Bootstrap so it's visible on both slides for navigation back and forth </top menu>
      <slide> (rest of) Landing Page based on Bootstrap here </slide>
      <slide> iFrame which loads my phpBB forum from /forum directory </slide>
   </section>
</wrapper>

```

### Current problems:
1. White space below forum on second slide since the page/slide height is a lot less than the landing page in bootstrap.
2. iFrame height doesn't always change properly so content sometimes gets cut off. I use javascript to constantly resize the iFrame on content or window changes.
3. scrollOverflow true fixes the white space, but breaks scrolling on the second slide only.

### What to achieve?
My goal is to use fullPage to horizontally switch/slide between both the website and the forum. Content sizes shouldn't matter as scrolling should simply become automatically possible as soon as the content of the page extends the max height of the users' screen. Except it for some reason won't work like that OR I've setup the use of fullPage uncorrectly.

### Questions
1. What settings do I need to pass with the fullPage initalisation?
2. Do I need to add extra CSS options to the body of either parts of the website like fp auto height?
3. Could fullPage work with iFrames at all?
4. What else am I forgetting / doing in a wrong way?

Your help is greatly appreciated.

Mitfrey

**Comment by alvarotrigo** [comment]
> What settings do I need to pass with the fullPage initalisation?

'scrollOverflow:true'

> Do I need to add extra CSS options to the body of either parts of the website like fp auto height?

That depends on what you want to achieve.

> Could fullPage work with iFrames at all?

No

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by mitfry** [comment]
Thank you for replying. I do however wonder if you read what I posted at all. Are you here to provide some form of support or am I at the wrong place, since this is not about a bug?

> That depends on what you want to achieve.

I explained exactly what I want to achieve in my post above. I think the way I want to set this up is 5 minutes work for you tops. But I can't find the right fullPage settings to get this to work properly without having to find a workaround for a workaround over and over again. **There's a reason I'm asking you for a little bit of support here..**

Would you please comment on the problems I am encountering and point me in the right direction as far as my page setup and fullPage go?

**Comment by alvarotrigo** [comment]
I might be able to help you if you provide an isolated reproduction in jsfiddle or codepen of the issue in question. That makes things easier for all of us instead of talking in abstract terms.
 I'm afraid I do not provide support for specific websites or very specific scenarios which are not directly related with fullPage.js issues. 

> 3. scrollOverflow true fixes the white space, but breaks scrolling on the second slide only.

You'll have to provide a reproduction of that and then I'll be able to investigate and answer you. Without a reproduction I can not guess what's going on there.
