### ISSUE TITLE
Chrome 55 touch throw error when using scrollBar:true

### ISSUE THREAD

**Issue by higimo** [alvarotrigo/fullPage.js#2507]
### Description
script throw error TypeError: Cannot read property '0' of undefined.

### Steps to reproduce it
1. Start Chrome version 55.0.2883.87 m.
2. Go to http://codepen.io/higimo/pen/YNGBpp
2. Open Developer Tools (Ctrl + Shift+J)
3. Open Device Toolbar (Ctrl+Shift+M on Developer Tools)
4. Touch move to next slide.
5. ????
6. PROFIT!

I tried it on iPad Air in Safari and the same error.

### Versions 
Chrome version 55.0.2883.87 m
Windows 8.1
iPad Air Safari

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!
Interesting... I'm surprised no one found it before. Might it be a recent change in Chrome now detecting `pointerdown` event too? 

Anyways, I've solved it in the dev branch. Will get merged in the next release. Meanwhile, feel free to use the dev version.

**Comment by alvarotrigo** [comment]
Yeap, Confirmed. It only takes place in Chrome > 54. Current being 55.

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.3
