### ISSUE TITLE
scrollOverflow: true not working properly

### ISSUE THREAD

**Issue by perusoa** [alvarotrigo/fullPage.js#2508]
Hi!

I am trying to use the scrollOverflow: true so that on the section that is larger than the viewport, it will become scrollable. I used the scrollOverflow option as well as added the slimScroll plugin. It operates just as I expected, but what is happening is once i get to that section, it doesnt allow me to scroll any further down the page. Is there possibly an option or step I am missing?

Thanks so much!
Anthony

**Comment by alvarotrigo** [comment]
> the slimScroll plugin.

Read the docs. You won't find anywhere that you need to add slimScroll.

**Comment by perusoa** [comment]
http://alvarotrigo.com/fullPage/examples/scrolling.html

This demo says at the top to use scrollOverflow and add the slimScroll plugin. Without the slimScroll plugin the scrollOverflow option does not work. What could I be missing?

**Comment by alvarotrigo** [comment]
The text on demo page needs to be updated. Look at its source code and you'll find no slimScroll anywhere. 
And as I said, refer always to the documentation when looking for info.
