### ISSUE TITLE
creating parallal sections/slides?

### ISSUE THREAD

**Issue by Digital-Banana** [alvarotrigo/fullPage.js#2511]
I'm having issues figuring out how Fullpage.js does this -- I'll just use a picture to explain what I'm trying to go for. Does anyone know how this is possible? I found a great example of what I'm looking for -- here: http://www.sony-asia.com/microsite/mdr-10/#homePage-- yet the code of this website is beyond me and I'm having troubles trying to replicate it.

Illustration of what I'm trying to make:

![](https://i.stack.imgur.com/Mh948.jpg)

**Comment by alvarotrigo** [comment]
That's a matter of CSS knowledge. 
If you examine the SONY website you'll see how they are using single vertiacl sections, then somehow they create this effect of having 2 panels in a single section and dependin gon the chosen option they'll show one or another thing in the section below.

That can all be accomplish by making use of the library functions. But the logic depends on you and in your skills as well as how imagination you have. 

I'll close this topic as it doesn't represent any issue in fullPage.js and it is such a broad question.
