### ISSUE TITLE
Section background color acording to slides

### ISSUE THREAD

**Issue by Welleee** [alvarotrigo/fullPage.js#2512]
I have 2 section with 4 slides each one. 

Is it possible with this plugin to change the background color of the section acording to the slide active?

For example:
in section 1 slide 0: backgroundColor: red
in section 2 slide 0: backgroundColor: green

in section 1 slide 1: backgroundColor: red
in section 2 slide 1: backgroundColor: purple

...

**Comment by alvarotrigo** [comment]
Of course, but that's a matter of your Javascript or CSS knowledge. 
Please check [the docs](https://github.com/alvarotrigo/fullPage.js) where you'll find all you need to know to accomplish this, from callbacks, to state classes. 

For example:

```css
.fp-viewing-section1-slide1 #section1{
    background:red;
}
```

Or using a callback:

```javascript
$.('#fullpage').fullpage({
       afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
            //section 1 & slide 2
            if(index === 1 && slideIndex ==2){
                $('#section1').css('background', 'red');
            }
      }
}
```

If you still don't understand them, please ask about it in other place such as stackoverflow.com where they'll be able to answer you specific questions about Javascript or CSS knowledge.

**Comment by Welleee** [comment]
Alvaro, thanks for your answer. 

Yes, first I did using the callback and works fine but the color changes after the slide load.

I 'd like to do with CSS so when the user loads the slide the background is already loaded.
But with the class fp-viewing-home-slide1 (in my case) doesn't change the background color. Any idea why?
