### ISSUE TITLE
fadingEffect plugin.  How to specify which slides to fade?

### ISSUE THREAD

**Issue by raymundbiddi** [alvarotrigo/fullPage.js#2513]
Hai comrades,
Sorry for bad english.  I can't seem to specify slides that should fade.   Is it possible with any setting?  or do we need to manually turn it on?  $.fn.fullpage.fadingEffect.turnOn(0);
**fadingEffect: ['slide5', 'slideQuestion1']** and  **fadingEffect: 'slide5, slideQuestion1'** does not seem to work.

Thanks.

**Comment by alvarotrigo** [comment]
As detailed in the docs:

> . Possible values are `true`, `false`, `sections`, `slides` It can therefore be applied just vertically or horizontally, or to both at the time. 

If you want to only enable it for some slides and not for others, then yeah, you'll have to make use of the functions `$.fn.fullpage.fadingEffect.turnOn();`  and `$.fn.fullpage.fadingEffect.turnOff();`.
