### ISSUE TITLE
Changing dot colors

### ISSUE THREAD

**Issue by onlyandrewn** [alvarotrigo/fullPage.js#2514]
Question:
What is the best way to override the default color styles of the navigation dots with Javascript?

The expected behavior with this snippet is that on panels with the anchor of #intro, the dots will change from their default grey color to white. But this only seems to work when I type it into the console after the page has loaded. 

```
	if (window.location.href.indexOf("#intro") > -1) {
		$("#fp-nav").find("span").css("background", "#fff");
	}

```

**Comment by alvarotrigo** [comment]
Using [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs). 
See the docs and [the examples available](http://alvarotrigo.com/fullPage/examples/callbacks.html).
