### ISSUE TITLE
fadingEffect unlicensed fullPage.js extension

### ISSUE THREAD

**Issue by raymundbiddi** [alvarotrigo/fullPage.js#2515]
**Unlicensed fullPage.js extension** is still visible even when a license key for fading Effect is specified.  
I am assuming that the key is assigned to a website during purchase, but **how do we move** the license to another one?  The key was bought in @alvarotrigo Gumroad page.

**Comment by alvarotrigo** [comment]
Make sure to use the activation key and not the license key.
You'll need to follow the instructions that were giving the mail you used to purchase the extension.

Any problem, [contact me](http://alvarotrigo.com/#contact)
