### ISSUE TITLE
turn content div's into slides

### ISSUE THREAD

**Issue by aeros0ul** [alvarotrigo/fullPage.js#2516]
hi there

i have three div boxes (flex row) inside a section and need to programmatically turn them into slides (to switch from flex to slides on breakpoints).
could somebody please point me to how this can be done.

thanks in advance!

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any way to do it.

You  would probably have to destory fullPage.js and initialize it again with the new slides. Check [my answer here](http://stackoverflow.com/a/36643702/1081396) for more info about that.
