### ISSUE TITLE
Disable FullpageJS for desktop (but keep for mobile)

### ISSUE THREAD

**Issue by AlcuinGuest** [alvarotrigo/fullPage.js#2517]
I'd like to disable Fullpage once the browser width is above 1000px.

Is there any way to do this?

(Sorry, not sure if this really is an issue with fullpage functionality or just an issue with my ability to find the functionality).

Much appreciated!

**Comment by alvarotrigo** [comment]
Check the responsive options detailed [in the docs](https://github.com/alvarotrigo/fullPage.js). `responsiveWidth`, `responsiveHeight` and `fp-auto-height-responsive`.

**Comment by daviddelusenet** [comment]
@alvarotrigo I have the same question. So I wan't to use Fullpage.js on mobile but disable it on screens wider than 800 pixels. 

The docs only speak about disabling Fullpage on mobile, not the other way around. I can manually trigger the responsive mode with the `setResponsive` method but this seems weird.

Is there another way I can achieve the desired effect? Thanks!

**Comment by alvarotrigo** [comment]
Right, it seems I read the question very fast and I though it was the other way around.
Ok, here you go:

```javascript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    autoScrolling:false,
    responsiveWidth:500

    //events
    afterResponsive: function(isResponsive){
        $.fn.fullpage.setAutoScrolling(isResponsive);
    }
});
```

[Demo online](http://jsfiddle.net/97tbk/1794/)

**Comment by daviddelusenet** [comment]
Thanks again!
