### ISSUE TITLE
Full Page Video Section Preventing Scroll

### ISSUE THREAD

**Issue by peterlunglum** [alvarotrigo/fullPage.js#2518]
I have a full section video using full page js. I've made the video responsive, to fit the whole section, however, I've found that disables scroll on trackpad or through gestures while the mouse/cursor is over the video. The only way to go between sections is to use the directional keys or the slide navigation.
Is there any way to re-enable scrolling?
[FilmTemplate1.zip](https://github.com/alvarotrigo/fullPage.js/files/720151/FilmTemplate1.zip)

**Comment by alvarotrigo** [comment]
Check [this example online](http://alvarotrigo.com/fullPage/examples/videoBackground.html) to see how to integrate a full screen video.

If your video is within an iframe, then it won't be possible due the browser limitations. See this topic https://github.com/alvarotrigo/fullPage.js/issues/2473

**Comment by AmanSahota** [comment]
Hi there, was there ever a solution for using an iframe? I am using videos on different slides and everytime you scroll over it stops..

**Comment by alvarotrigo** [comment]
Look through the open and closed issues for the "iframe" keyword. It has been treated multiple times:
https://github.com/alvarotrigo/fullPage.js/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+iframe

Specially this one:
https://github.com/alvarotrigo/fullPage.js/issues/2229

No proper solution. Browser limitation :)
