### ISSUE TITLE
How to hide/remove previous section after scroll to next section?

### ISSUE THREAD

**Issue by faliqaiman** [alvarotrigo/fullPage.js#2520]
I'm trying to create a splash screen for the 1st section, and after user scroll to the next section, the 1st section will be hide/remove/destroy directly after the 2nd section in `active` mode. 

Try with `afterLoad` callback but it jump to 3rd section instead. ([afterLoad reproduction](https://jsfiddle.net/97tbk/1671/))

But when use `onLeave`, the 1st section will disappear in a fast way.  ([onLeave reproduction](https://jsfiddle.net/97tbk/1672/))

Kindly need expert for this matter. Thanks.

**Comment by alvarotrigo** [comment]
Why not just using `setAllowScrolling` and `setKeyboardScrolling` to prevent accessing to it?

**Comment by faliqaiman** [comment]
Thanks. Sorry didn't notice this [setAllowScrolling](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) setting.
