### ISSUE TITLE
Mapbox conflicts with fullPage

### ISSUE THREAD

**Issue by davidvandelden** [alvarotrigo/fullPage.js#2522]
Hi there,

I'm trying to incorporate fullpage with a Mapbox interface that I'm trying to build.
What it does is basically.. whenever you scroll and reach a certain section.. the map flies to a specific LatLong. 

So I wanted to add fullPage to the scrolling part. The map gets triggered by: window.onscroll = function(). This ofcourse does not work with fullPage. So I added the option scrollBar: true.

And this only works for the first section (to see other sections actually grab the scrollbar and drag down). After that I get this in Chrome console:

Uncaught TypeError: Cannot read property 'top' of undefined
    at isCompletelyInViewPort (jquery.fullPage.js:1029)
    at scrollHandler (jquery.fullPage.js:951)
    at dispatch (jquery.min.js:2)
    at u (jquery.min.js:2)

Here's a link http://ngrane.com/mapbox/curmap.html

**Comment by alvarotrigo** [comment]
It seems you are somehow playing with the classes of the section 6.
You should have a `fp-section` class assigned to section 6 and you don't. 

The error is in your code and not in fullPage.js
