### ISSUE TITLE
Error when someone clicks on a link, and horizontal scroll changes slide before new page is loaded.

### ISSUE THREAD

**Issue by BelletristApps** [alvarotrigo/fullPage.js#2523]
Hi

I have an issue where we are using FullPage to create a slider on the home page. When someone clicks on a link to a new page, if the next slide loads before the new page loads, the visitors "instruction" to go the the new page is lost, when the new /# link is called.

See here: http://staging.iconicafricasafaris.co.za/

### Steps to reproduce it
1. Click on internal link in menu or on home page. NB about 9 seconds after slide loads.
2. New slide loads on home slider.
3. internal link instruction is cancelled when /#slide number is called.

All Browsers.

**Comment by alvarotrigo** [comment]
Your site requires user and password.

**Comment by BelletristApps** [comment]
Oh sorry

username/password is staging/staging

I forgot to add that I have also bought and added the continual scroll extension.

THanks

**Comment by alvarotrigo** [comment]
Please be more specific with your steps. Detail which menu should I click and in which page.

**Comment by BelletristApps** [comment]
It doesn't really matter which link you click, as long as the page hasnt loaded before the next slide loads. It is tricky to get the timing right.

I will decrease the time each slider is there so it is easier to see.

But try destinations/botswana/selinda explorers camp

**Comment by BelletristApps** [comment]
It is down to 1 second now, so you will see you pretty much will not be able to click on any link and actually go to that page.

**Comment by alvarotrigo** [comment]
Have you tried using `lockAnchors:true` ?
Or just not using anchors at all?

**Comment by BelletristApps** [comment]
Thanks. I think the lockAnchors: true will work for me. I appreciate the assistance.
