### ISSUE TITLE
Uncaught TypeError: $(...).fullpage is not a function

### ISSUE THREAD

**Issue by Bella-Mon** [alvarotrigo/fullPage.js#2525]
Hi Guys,

I have problem Uncaught TypeError: $(...).fullpage is not a function in my wordpress site.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Bella-Mon** [comment]
Now Ok. Thank you.
