### ISSUE TITLE
Auto-height footer being placed at top of viewport

### ISSUE THREAD

**Issue by timgrohmann** [alvarotrigo/fullPage.js#2527]
### Description
Greetings!
I wanted to place a footer at the bottom of a full page site with auto-height. The footer's height is displayed properly, but if you scroll from the last section to the footer, you don't see anything of the last slide, the footer at the top of the window, and a lot of whitespace below that.

I reviewed many examples about fullPage.js footers and I still can't get it to work the way it does everywhere else. And I have no clue at all where the issue originates from :/

Am I missing something obvious?

### Versions 
Using the newest version of fullPage and jQuery, issue occurs on all browsers I was able to test.

Thank you very much for your time in advance.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Working as expected in the [demo page](http://alvarotrigo.com/fullPage/examples/autoHeight.html#3rdPage) and in [this fiddle using the minified version](http://jsfiddle.net/97tbk/1695/).
