### ISSUE TITLE
 Not working license key for scrollOverflowResetKey

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2529]
I bought a key for scrollOverflowResetKey, but it does not work. Connect as written in the documentation and in the example of your site. Please tell me what could be the problem and how to fix it)

**Comment by alvarotrigo** [comment]
You probably didn't follow the instructions sent to the mail used for the purchase.
Check the SPAM folder too. 

If you stil lhaving issues [contact me](http://alvarotrigo.com/#contact) in private and let me know which email you used for the purchase.
