### ISSUE TITLE
Vertical Navigation Dots starting from 2nd slide?

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#2532]
hi there,

i'm trying to put a five vertical slide page, three in the middle of which would be joined by dotted navigation, because it's one link spreading across three slides. is it possible for those dots to appear only within those 3 slides?

thanks!

**Comment by alvarotrigo** [comment]
Use [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [fullpage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to hide or show them whenever you want.

**Comment by asdangus** [comment]
i've tried to study both options, but my javascript skills are next to none. even if i could hide it in first and last section, would it show only three dots among those three remaining sections? it's just that i can't use scrollOverflow on this design. anyways i appreciate your product much, good luck!

**Comment by alvarotrigo** [comment]
> but my javascript skills are next to none

Then you should be asking in other place such as http://stackoverflow.com in order to learn the Javascript you need to use fullPage.js.

You can find examples of the use of callbacks in [the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) under the name `callbacks.html` and `callbacks2.html`

If you download fullPage.js from Github you'll get the folder and you'll be able to play and learn with them.

**Comment by alvarotrigo** [comment]
You also have another example [at codepen](http://codepen.io/alvarotrigo/pen/XbPNQv) as stated in the docs.

**Comment by asdangus** [comment]
hi, please one last thing regarding bullets:
right now it hides them from 768px downwards. i require them to stay on always, but want to hide
arrows from 768px downwards. tried that thru media quieries in your css, didn't work, then searched high and low in your .js to no avail .. please, can you help me out?

**Comment by alvarotrigo** [comment]
Sure. Please provide a reproduction of your issue in jsfiddle or codepen and I'll take a look at it.

**Comment by asdangus** [comment]
i've managed to get rid of arrows below 768px width, but can't have bullets back. i'll do the fiddle, although all i require is a clue of how to remove the responsive restriction from horizontal slide bullets, so that they don't get removed for phones and tablets ..

**Comment by alvarotrigo** [comment]
As I said, I need a reproduction in order to help you.

**Comment by asdangus** [comment]
here's the site: http://www.alliancejobsconsult.com/
and here's the pen: http://codepen.io/anon/pen/vgRVBB?editors=0100

If you're viewing pen, please browse to "HOW WE WORK" or click on "FIND OUT MORE"

so all i require is that those bullets would stay on all the time, even below 768px width.

thanks!!

**Comment by alvarotrigo** [comment]
I'm afraid that has nothing to do with fullPage.js but with your own CSS stylesheet. You'd better ask somewhere else. Definitely not a fullpage.js issue.

**Comment by asdangus** [comment]
ouch, i thought it's the default of your script. no worries, will find the prob., thanks.
