### ISSUE TITLE
media doesn't work

### ISSUE THREAD

**Issue by webspecialist** [alvarotrigo/fullPage.js#2533]
Media cannot auto play even by data-autoplay or data-keepplaying in my code. ( I searched in to documentation) 

That is my code.
```html
<audio id="audio" data-autoplay>
        <source src="/css/west.mp3" type="audio/mpeg">
    </audio>
    <div id="mute-toggle" class="pull-left"><i class="fa fa-volume-up" aria-hidden="true"></i></div>
```
This is out of fullpage id div.

jquery code:
```javascript
    $(document).ready(function () {
    //start 1st plugin full page
    $.fn.fullpage({
        slidesColor: ['black', 'black', 'black', 'black'],
        anchors: ['page1', 'page2', 'page3', 'page4'],
        menu: '#menu'
    });

   //starts 2nd plugin music

     var audio = document.getElementById("audio");

    audio.autoplay = true;    

    audio.loop = true;    

    $("#mute-toggle").click(function(){ // on toggle click
        if($(this).hasClass("toggled")){ // if toggle has class "toggled"
            audio.muted = false; // unmute audio
            $('#mute-toggle i').attr('class', 'fa fa-volume-up');
        } else { // vice versa
            audio.muted = true;
            $('#mute-toggle i').attr('class', 'fa fa-volume-off');  
        }

        $(this).toggleClass("toggled"); // toggle class "toggled"
    });

    });
```

The problem I face is:

The music didn't start playing when I put these two parts(plugins) of code together.

Comments:

1) When I put them together the first plugin played and the second no. 2) Only if I removed the code of 1st plugin the music can play. 3) I don't have any console errors! 4) jquery version 1.9.1
5) chrome latest version (pc-windows)

What Can I do?

**Comment by alvarotrigo** [comment]
> When I put them together the first plugin played and the second no

What two plugins? What other plugin are you using besides fullPage.js?

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by webspecialist** [comment]
I meant the 2 parts of code. The first part is the fullpage and the second is the button I created mute/unmute the music.
I don't know why but the code of:

$.fn.fullpage({
        slidesColor: ['black', 'black', 'black', 'black'],
        anchors: ['page1', 'page2', 'page3', 'page4'],
        menu: '#menu'
    });

blocks the music to start. Any ideas? If you want some further details pls tell me.

**Comment by alvarotrigo** [comment]
Sorry but I can not help you without a reproduction.  Try to reproduce it in jsfiddle or codepen.

**Comment by tentonaxe** [comment]
`$.fn.fullpage(` is incorrect, is it not?

**Comment by alvarotrigo** [comment]
No. Read the docs and see the examples.

**Comment by tentonaxe** [comment]
@alvarotrigo none of your examples or documentation have any mention of executing `$.fn.fullpage` directly rather than calling it on an element such as `$("#someid").fullpage(...)` unless it's hidden somewhere i haven't searched yet,

**Comment by alvarotrigo** [comment]
Yeah well, that happens when you use a 3 years old version of fullPagel.js :D 
Just update to the latest 2.9.2 :)

**Comment by webspecialist** [comment]
Mr. @alvarotrigo ,
Would you prefer to upload it as subdomain(of my personal page) and see that from there? 
1) It is easiest for me,
2) It is complicate app and jsfiddle didn't support it or something did wrong.
3) Codepen need money.

Is my version old? Ok I will update it.

**Comment by alvarotrigo** [comment]
1 - Update your version to the latest, I do not provide support for older versions.
2- Codepen is free... 

Just give me a URL or something and I'll let you know what can I do.

**Comment by webspecialist** [comment]
With the latest version the problem fixed!!!!

Ιf you're curious about ... my page is http://onroad.vtsoulis.gr/all-categories-demo
Is not completed yet... but thank you @alvarotrigo my part of my page will be awesome thanks to fullpage.js and you!!!!
I am an unemployed web designer / developer ... I wish to had money to donate to your awesome work!!!
Now the case is closed!
