### ISSUE TITLE
Responsive height

### ISSUE THREAD

**Issue by CXHub** [alvarotrigo/fullPage.js#2534]
### Responsive height

Hi There,

First of all, great plugin! 

I'm using the latest version of fullpage.js and i've got a question about the responsive settings.

When using _**responsiveWidth**_ in combination with _**fp-auto-height-responsive**_, the mobile version still has an calculated height at the element (inline style). The sections still have a height of 100%. Next to disableing the plugin, I would also like to remove the calculated height and change it to auto for example.

Is this possible?

Thanks in advance!

**Comment by alvarotrigo** [comment]
`fp-auto-height-responsive` will adjust the size of the section to the size of your content as long as it is not fixed or absoluted positioned.

The inline style will get overwritten by the CSS style, as it uses `!important`.

Without a reproduction of your issue I can not provide you a more accurate answer to why it is not working in your specific case. 
Please provide a reproduction if you believe it is a bug.
