### ISSUE TITLE
Put fullpage extensions on CDN

### ISSUE THREAD

**Issue by xpluscal** [alvarotrigo/fullPage.js#2535]
Can you put the jquery.fullpage.extensions.min.js on a CDN as well?

That would be great.
Thanks.

**Comment by alvarotrigo** [comment]
Thanks for the suggestion!

I requested the addition of it. 
I'll let you know whenever its available.

**Comment by xpluscal** [comment]
Thanks!

**Comment by alvarotrigo** [comment]
This was done time ago. Available here:
https://cdnjs.com/libraries/fullPage.js
