### ISSUE TITLE
Console.log on continuous Horizontal extension

### ISSUE THREAD

**Issue by xpluscal** [alvarotrigo/fullPage.js#2536]
Just a small detail, but there is a log "va1" on the continuous Horizontal extension.

<img width="462" alt="screen shot 2017-02-02 at 09 52 08" src="https://cloud.githubusercontent.com/assets/3706722/22542681/52831fa2-e92d-11e6-969e-1d45e801ca1d.png">

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I've removed it. Feel free to download the extension again from the link you got in your mail after the purchase.
