### ISSUE TITLE
Menu not working in Firefox

### ISSUE THREAD

**Issue by mqasim1990** [alvarotrigo/fullPage.js#2537]
The code of my menu is following 

its working on other browsers perfectly accept Firefox . how can i fix it ?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
