### ISSUE TITLE
Conflicts with Bootstrap modal

### ISSUE THREAD

**Issue by GasparSukk** [alvarotrigo/fullPage.js#2541]
Bootstrap 3.3.7
fullPage 2.9.2

Problem 1.
If Bootstrap modal is inside the section it doesn't work/display correctly. Only backdrop works.
Temporary solution is to place modal elements outside of the sections for Bootstrap modals to work correctly.
Is it possible to fix this without not messing up the logical order of the information?

Problem 2.
Background keyboard navigation and screen scrolling are still attached to fullPage elements.

**Comment by alvarotrigo** [comment]
> Temporary solution is to place modal elements outside of the sections for Bootstrap modals to work correctly.
And that's the correct way of doing it. Fixed elements outside fullpage.js wrapper. 
That's because of [browsers' bugs](http://stackoverflow.com/a/15256339/1081396) dealing with translate3d elements and fixed elements. 

> Problem 2.
> Background keyboard navigation and screen scrolling are still attached to fullPage elements.

Totally normal. You'll have to disable them yourself by using the fullPage.js functions such as `setAllowScrolling(false)`.

**Comment by GasparSukk** [comment]
Thanks!

**Comment by trainoasis** [comment]
@alvarotrigo ty that helped me as well. Any thoughts on why  `padding-right: 15px;` is added to the body when modal is opened?    
Otherwise, a good plugin, love it so far :)

**Comment by wenmin92** [comment]
https://github.com/alvarotrigo/fullPage.js/issues/3611 also relates to Problem 2 when the modal needs to be scrollable.

**Comment by wenmin92** [comment]
@alvarotrigo  Thank you for your kind reply, I had similar problems with the latest version and managed to solve them using the method mentioned here. I just left a comment just so that people who encounter the same problem later can see the solution quickly.

**Comment by alvarotrigo** [comment]
@wenmin92 thanks for that! 👍
