### ISSUE TITLE
Use extension in local environment

### ISSUE THREAD

**Issue by dougaraujos** [alvarotrigo/fullPage.js#2542]
Hi, I bought a extension for up to 1 website. But I need to use extension in local environment for testing.

This is possible?

**Comment by alvarotrigo** [comment]
Sure. They will work as expected in localhost and 127.0.0.1. 
If you are using a dev domain before moving it to the production domain, then you'll have to ask me for a license for that specific domain or get the activation key for that one and ask me later for another one once you move it to production.
