### ISSUE TITLE
offsetSections JS Error preventing carousels from swiping

### ISSUE THREAD

**Issue by tarasiegel** [alvarotrigo/fullPage.js#2543]
Hey there. I am using the offsetSections extension for a project.  I'm essentially making 6 carousels in a row at 85% height.  I have an image overlay on top of each carousel that has a like "click to view" button that then reveals the carousel.  It works beautifully on desktop but on actual mobile devices I keep on getting this JS error "TypeError: undefined is not an object (evaluating 't.position')".  It doesn't happen all of the time but when it does it prevents any of the carousels from working.

It looks like its happening in this chunk of code in fullpage.extensions.min.js : 
```
function Tn(n, t, o) {
            var i = n.closest(y),
                r = {
                    slides: n,
                    destiny: t,
                    direction: o,
                   destinyPos: t.position(), <-- this line is getting an undefined is not an object 
                    slideIndex: t.index(),
                    section: i,
                    sectionIndex: i.index(y),
                    anchorLink: i.data("anchor"),
                    slidesNav: i.find(j),
                    slideAnchor: qn(t),
                    prevSlide: i.find(D),
                    prevSlideIndex: i.find(D).index(),
                    localIsResizing: Mt
```

Settings Im using: 
```
$('#fullpage').fullpage({
        lockAnchors: false,
        anchors:['intro', 'intro-text', 'carousel--1', 'carousel--2', 'carousel--3', 'carousel--4', 'carousel--5', 'carousel--6', 'carousel--7', 'video', 'related', 'footer'],
        css3: true,
        autoScrolling: false,
        scrollingSpeed: 500,
        touchSensitivity: 10,
        fitToSection: false,
        offsetSections: true,
        offsetSectionsKey: 'my key',
        easingcss3: 'ease',
        loopHorizontal: false,
        continuousHorizontal: false,
        bigSectionsDestination: top,
        keyboardScrolling: true,
        controlArrows: true,
        verticalCentered: true,
        responsiveSlides: true,
        lazyLoading: true
    });
```

I can send you a link to the page I'm working on privately, but its for a client and I cant put a public link here.

### Steps to reproduce it
1. Click into carousel, start swiping
2. Move down to next carousel click into it, JS error throws
3. Carousel is now unclickable/swipeable

### Versions 
Mobile Devices, iOS in particular

Im in a bit of a time crunch, so any help would be much appreciated. If theres any way to just get an un-minified version of extensions so I can add a check for undefined, that could possibly work in my situation.

**Comment by alvarotrigo** [comment]
> I can send you a link to the page I'm working on privately, but its for a client and I cant put a public link here.

Sorry I do not provide free support for personal websites. 
If you believe its a bug in fullPage.js please proceed to create an isolated reproduction in jsfiddle or codepen.
