### ISSUE TITLE
FadingEffect extended question.

### ISSUE THREAD

**Issue by l2zeo** [alvarotrigo/fullPage.js#2544]
Can I use scrolling magic with fadingEffect?

http://alvarotrigo.com/fullPage/extensions/fading-effect.html

**Comment by alvarotrigo** [comment]
No. when using the fading Effect extension there's no scroll bar and therefore there's no scroll even being propagated. 
You should be using [fullpage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to create animations. See [this video tutorial](https://www.youtube.com/watch?v=qiCVPpI9l3M) 

And check the [callbacks examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) as well as [the online one](http://alvarotrigo.com/fullPage/examples/callbacks.html).
