### ISSUE TITLE
Questions about implementing Parallax

### ISSUE THREAD

**Issue by l2zeo** [alvarotrigo/fullPage.js#2546]
When I scroll down in section 1, can I show other elements in section 1 instead of moving to section 2?

Like the site below.

[site](https://sharp.vn/vn/cong-nghe-long-giat-khong-lo/)

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2494
See the last comment there where I proposed a solution to it.

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
