### ISSUE TITLE
Parallax effect only on 1 section

### ISSUE THREAD

**Issue by vinylroads** [alvarotrigo/fullPage.js#2547]
Hello,

Thank for this really nice plugin. It’s the 1st time i use it.

You can see the website here (It’s not completely finished) :
https://www.lereseauhumain.com

I would like to have your opinion on this :
Is it possible to have some parallax effect only for the 1st section. I would like to make section2 scroll over section 1 (i know how to do this) but i would like to add somme parallax effect, like the section 1 scroll up at a different speed disappearing behind section2.

Do you think it is possible ?

I've read several post about parallax but it didn't answer my question (i don't want to use `scrollBar: true`, because i'd like to keep full page.js scroll  (not the normal scroll)

Regards,

Sébastien

**Comment by alvarotrigo** [comment]
Planning to release [a parallax extension this week](vinylroads) :)

**Comment by vinylroads** [comment]
Hi, interesting.

What would be the exact purpose of this plugin ?

**Comment by alvarotrigo** [comment]
> What would be the exact purpose of this plugin ?

Parallax backgrounds giving the impression of having one section scrolling over the other for a configurable percentage.

**Comment by vinylroads** [comment]
I guess it is what i'm looking for ;-) 

Would it possible to apply the parallax effect only on certain section ?

**Comment by alvarotrigo** [comment]
@vinylroads I guess you could do that by using a callback such as `afterLoad` and change the parallax percentage to 0.
I might think about an easier way to do that for the next version of it.

**Comment by alvarotrigo** [comment]
Well, now that I think about it. You wouldn't even need to to that :D 
Just adding no background or having it without certain class should do it :)

**Comment by vinylroads** [comment]
Yes, nice and easy solution ;-)

Hope to test soon the parallax extension !

For now, what i can achieve : i create a section outside the `<div id="fullpage">` like this

```
<div id="#section1" class="section">Section with paralax effect</div>
<div id="fullpage">
    
    <div  id="#section2" class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>
```

This way, i ca make `#section2` scroll over `#section1`
Now i have to add a parallax effet on `#section1`. I’ve tried to use a parallax plugin but for now the effect doesn’t apply. I need to search a little more ;-)

**Comment by alvarotrigo** [comment]
> I’ve tried to use a parallax plugin but for now the effect doesn’t apply

They won't work unless you use `scrollBar:true` I'm afraid.

**Comment by vinylroads** [comment]
> They won't work unless you use scrollBar:true I'm afraid.

That’s also my conclusion.  Thank you very much for this clarification. 

Maybe with some js, i can make this 1st  section moving up and create a sort of parallax effect when user scroll to section2. But it would be a weird approach…

**Comment by alvarotrigo** [comment]
Now you can create parallax effects with the [parallax extension](alvarotrigo.com/fullPage/extensions/parallax.html). Feel free to check it out!
