### ISSUE TITLE
extensions resetslides doesn´t work with dragandmove

### ISSUE THREAD

**Issue by spaszwerg** [alvarotrigo/fullPage.js#2549]
The extensions resetSlides and dragandmove do not work with another.

My customer wants to use those two extensions.
Now, that i got the files from your shop I recognize, that resetSlides works when using the scrollwhell but not when using dragandmove.

Is that correct? Or should they got together?

### Versions 
Win 10 Chrome 56, Firefox 51

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

The bug has been solved in the dev branch. Please feel free to use [the dev version of the extensions file](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js) until it gets merged in the next release.

**Comment by spaszwerg** [comment]
Perfect. Thanks a lot.

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.3
