### ISSUE TITLE
Navbar problem

### ISSUE THREAD

**Issue by Philimono** [alvarotrigo/fullPage.js#2550]
### Description
i used your fullpage plugin but i have problem on my navbar when i go to any section of it it always gets me to the last one, and then it works normally, but always at the first time sends me to the last section, can you please tell me how can i fix this?

### Link to isolated reproduction with no external CSS / JS
here is a link to the website
https://hesham-al-mekkawi.firebaseapp.com

### Versions 
Browser

**Comment by alvarotrigo** [comment]
I guess you are talking about the horizontal sliders in your site?
They are using another external carousel that does not belong to fullPage.js You'd better ask in other place or in the carousel library forum.
