### ISSUE TITLE
dragAndMove:true with fp-auto-height

### ISSUE THREAD

**Issue by spaszwerg** [alvarotrigo/fullPage.js#2551]
Hi again,
I stumbled upon a strange behaviour when using the dragandmove extension in combination with an fp-auto-height footer.

If the extension is active and I use the mousewheel to navigate, the page will scroll far below the footer showing blank space (footer is the on top of the viewport).
If I drag down to the footer, the footer is shown as expected, but the navi on the right is showing that I´m not on the footer section (thinks I´m on Page3). If I now drag up, it will scroll over the section before the footer (over Page3 to Page2).

I created a fiddle here:
[Removed]

### Versions 
Win 10 Chrome 55

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll take a look at it whenever I can.

**Comment by alvarotrigo** [comment]
> If the extension is active and I use the mousewheel to navigate, the page will scroll far below the footer showing blank space (footer is the on top of the viewport).

I've just fied this issue in the dev version. Feel free to use [the dev file](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js) to solve it until its get merged in a new release.

Still need to solve the other issue.

**Comment by spaszwerg** [comment]
OK, thanks.

**Comment by spaszwerg** [comment]
Hi Alvaro, is there a fix for the second issue now?

**Comment by alvarotrigo** [comment]
Not yet

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.3
