### ISSUE TITLE
Keep autoScrolling:true, but enable div scroll while on it

### ISSUE THREAD

**Issue by munjiza** [alvarotrigo/fullPage.js#2552]
I want to use autoScrolling option but when it is scrolled to a div#content, which have overflow-y: scroll; I want to be able to scroll through content before autoScrolling continue. Is this possible ? 

Fiddle: https://jsfiddle.net/Ldes3d9n/1/

**Comment by alvarotrigo** [comment]
See the `normalScrollElements` option.

**Comment by munjiza** [comment]
@alvarotrigo I did it in another way. 

    if (...) { 
        $.fn.fullpage.setAllowScrolling(true); 
    } else {
        $.fn.fullpage.setAllowScrolling(true); 
    };

This way everything is working as expected on desktop and also on mobile emulators (for example from Chrome Dev. Tools), but on real device (android or iOS phone) I am still not able to scroll content inside of that div.

Any suggestions?

**Comment by alvarotrigo** [comment]
> Any suggestions?

Yeah, try `normalScrollElements` option.
