### ISSUE TITLE
Scroll step on the scrollOverflowReset

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2553]
Hello! Prompt, whether it is possible to reduce the scrolling step in using scrollOverflowReset function. The documentation on this subject I found nothing

**Comment by alvarotrigo** [comment]
Use `scrollOverflowOptions` to pass any option to it. 
You'll find all possible options in the [iScroll.js documentation](http://iscrolljs.com/), which is the vendor library used for that feature.
