### ISSUE TITLE
Problem with recordHistory option

### ISSUE THREAD

**Issue by Becherman** [alvarotrigo/fullPage.js#2555]
Hi! Not so long ago i start using fullpage.js and collided with some problem with historyRecord option. When i refresh browser fullpage return my state to last block where i  finished. After reading docs i find recordHistory option which must disable this functionality. I set it to false, but nothing change at all. This results a reproduced in Chrome, Firefox and Edge. Operative system Ubuntu LTE 14.04. Maybe someone can help me find solution? 

https://jsfiddle.net/Becherman/1dsa51qj/

**Comment by alvarotrigo** [comment]
The easy solution is to avoid using anchors if you are not planning to use them as they should. 

If for any reason you still want to use them internally, you can do this:

```javascript 
lockAnchors: true,
recordHistory:false,
```

But of course, no anchors will be shown in the URL. Anchors in the URL should only be used if you are planning to have a linkable section.

**Comment by Becherman** [comment]
Thanks for the detailed response. I think i will refuse from the idea to abolish the history in  favor of the anchors!
