### ISSUE TITLE
Fix width / height !?

### ISSUE THREAD

**Issue by l2zeo** [alvarotrigo/fullPage.js#2556]
I want to fix the width and height so that I do not become responsive.

Is there a way?

**Comment by alvarotrigo** [comment]
What do you mean? So you do no become responsive?

**Comment by l2zeo** [comment]
@alvarotrigo  
Hello.

ResponsiveSlides: false

How do I not use responsive in sections like slides?
I want to set the width / height to a fixed value.

**Comment by alvarotrigo** [comment]
Read [the docs](https://github.com/alvarotrigo/fullPage.js) and see [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) regarding `responsiveHeight`, `responsiveWidth` and `fp-auto-height-responsive`
