### ISSUE TITLE
Pure JS demo doesn't work on iPhone 6 with iOS 10

### ISSUE THREAD

**Issue by daviddelusenet** [alvarotrigo/fullPage.js#2557]
When you open the Pure JS demo on a iPhone with iOS 10 (http://alvarotrigo.com/fullPage/pure-javascript/) it breaks after the first slide.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Unfortunately the support I provide for the vanilla JS version is limited due to my lack of time to maintain it.
I'll take a look at it at some point, but I'm afraid to say I'll take it as a low priority task and might take a while for me to provide a fix.

**Comment by stijnimanbik** [comment]
Still a problem, sorry to hear it. I just made a full website based on your full javascript version. Should've checked the compatability issues. I'm also having problems with iOS and Safari

**Comment by alvarotrigo** [comment]
That version has been replaced by fullpage.js v3.
Now jQuery is no longer required on fullpage.js!
