### ISSUE TITLE
An issue with the bootstrap grid, image goes out of column

### ISSUE THREAD

**Issue by hieverest** [alvarotrigo/fullPage.js#2558]
Hi, thank you for you plugin firstly. It is so beautiful to render my resume which I am trying make at present. But I met a problem which is described as the title. I tried to put image in `<div class="col-md-4"> `with the class: img-responsive, but the image goes out of the `<div>`. The html markup works fine in a new pen without fullpage.js. So I am wondering it is somewhat conflicted with fullpage.js.

The link is here: http://s.codepen.io/hieverest/debug/dNgGjN/wQMPoPeaJyPk#3rdPage
The editor view: http://codepen.io/hieverest/pen/dNgGjN?editors=1010
The markup works fine in a new pen: http://codepen.io/hieverest/pen/MJzbRe?editors=1010

Thank you in advance!

**Comment by alvarotrigo** [comment]
Seems like a CSS question. I would recommend you to ask in other place such as stackoverflow.com
It has nothing to do with fullPage.js.

**Comment by DGtalDesign** [comment]
Awesome script but I have a problem with it when it comes to CSS grids. It automatically adds styles to hide the grids and disables the CSS animations assigned to the grids. Know how to fix this?
