### ISSUE TITLE
play YouTube video on a slide.

### ISSUE THREAD

**Issue by l2zeo** [alvarotrigo/fullPage.js#2559]
I want to play YouTube video on a slide.

I want to be able to play again when the section goes over and comes back.

It does not work out well.

`
afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex) {
      var loadedSlide = $(this);
      var tl = new TimelineMax();
      console.log("slideLoad--" + "anchorLink: " + anchorLink + " index: " + index + " slideAnchor: " + slideAnchor + " slideIndex: " + slideIndex);

  if (index == 6 && slideIndex == 1) {
          tl.to(".two-video", 1, {backgroundColor:"#292828", opacity: 0.8, ease:Power3.easeOut})
          onYouTubeIframeAPIReady()
 }
},
onSlideLeave: function( anchorLink, index, slideIndex, direction, nextSlideIndex){
    if(index == 6 && slideIndex == 0 && direction == 'right'){
        //onYouTubeIframeAPIReady();
      $(document).ready(function() {
        loadYouTube();
      });
    }
}
`

**Comment by alvarotrigo** [comment]
See the [auto play embedded data section in the docs](https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media).

**Comment by alvarotrigo** [comment]
And [the example autoplayVideoAndAudio.html](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/autoplayVideoAndAudio.html)
