### ISSUE TITLE
Remove the anchor from the first section

### ISSUE THREAD

**Issue by meneldil** [alvarotrigo/fullPage.js#2560]
Hi everybody,

Is it possible to remove the anchor from the very first section (and slide), as when we arrive the first time on the page?

For example on this page, delete `#firstPage`:
`http://alvarotrigo.com/fullPage/` instead of `http://alvarotrigo.com/fullPage/#firstPage`

Thanks!

**Comment by alvarotrigo** [comment]
The anchor is not visible on page load on the URL you mentioned. 
http://alvarotrigo.com/fullPage/

Only when going back to the 1st section from any other section. 
And in that case it is not possible.  The most you can do is use an empty anchor: `''`.
So you can end up with:
`http://alvarotrigo.com/fullPage/#`

**Comment by meneldil** [comment]
Yes, I was talking about the case where we were coming back from another slide.
Okay, it will be an empty anchor (always better than nothing)

Thank you!

**Comment by alvarotrigo** [comment]
If you really want to remove it, you can probably play with the browser History API when supported. Play a bit with it and test if this would fit your needs. 

```javascript
afterLoad: function(anchorLink, index) {
    if (index === 1) {
        if (history.pushState) {
            window.history.replaceState("", document.title, window.location.pathname);
        }
    }
}
```
