### ISSUE TITLE
use scrollOverflowOptions

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2561]
Hello! Can you please throw example of fullpage with iscroll.

**Comment by alvarotrigo** [comment]
There's a folder called "examples" which contains examples, one of them is using the scrollOverflow option.
Feel free to check it.

**Comment by alvarotrigo** [comment]
As detailed in the docs, check the iScroll options in [its documentation](http://iscrolljs.com/).

Then just pass them this way:

```javascript
scrollOverflowOptions:{
    //any iScroll options here.
}
```
