### ISSUE TITLE
 soft scrolling scrollOverflowReset

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2562]
Hey. Prompt please, whether it is possible when using scrolloverflowreset soften the scroll? documentation on this subject is nothing. Using iscroll not suitable (because scrollOverflowReset function does not work correctly)

**Comment by alvarotrigo** [comment]
> Using iscroll not suitable (because scrollOverflowReset function does not work correctly)

Can you elaborate that? 
The [demo page](http://alvarotrigo.com/fullPage/examples/scrolling.html) works as expected, as well as when using the scrollOverflowReset extension as can be seen [in this other demo](http://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html).

The documentation clearly states:

scrollOverflowOptions: when using scrollOverflow:true fullpage.js will make use of a forked and modified version of [iScroll.js libary](https://github.com/cubiq/iscroll/). You can customize the scrolling behaviour by providing fullpage.js with the iScroll.js options you want to use. Check [its documentation](http://iscrolljs.com/) for more info.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
I explained to you how to use it the other day in https://github.com/alvarotrigo/fullPage.js/issues/2561
