### ISSUE TITLE
It doesn't set active to slide in IE9

### ISSUE THREAD

**Issue by jas-chen** [alvarotrigo/fullPage.js#2564]
### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/#secondPage

### Steps to reproduce it
Navigate between slides, `active` class is not set to the slide that actually shown.

### Versions 
IE9 on Win7

**Comment by jas-chen** [comment]
![2017-02-15 3 41 01](https://cloud.githubusercontent.com/assets/2928661/22964767/38ef5da4-f395-11e6-9ea1-b21898a278e8.png)

**Comment by alvarotrigo** [comment]
IE 9 doesn't update the DOM inspector in real time.
But you can see it adds the class as expected when adding this on the console:

```javascript
$('.section.active').find('.slide.active').text(); 
```

Also, by using any CSS rule based on the `active` class for the slide.
