### ISSUE TITLE
video background does not play on a mobile phone

### ISSUE THREAD

**Issue by worldwildweb** [alvarotrigo/fullPage.js#2565]
### Description
The video background does not play on a mobile phone

### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/examples/videoBackground.html
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
with a mobile access http://alvarotrigo.com/fullPage/examples/videoBackground.html
2. [Second step]
The video on the 1st section is not playing
3. [and so on...]

### Versions 
[Browser, operative system, device...]
Device : nexus 5x 
Browser: chrome beta 57.0.2987.38

**Comment by alvarotrigo** [comment]
Are you able to play a background video **without** fullpage.js? 
Please test that first.

**Comment by worldwildweb** [comment]
indeed! :) you can close the issue.
