### ISSUE TITLE
step to scroll when using scrollowerflowreset

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2566]
Hello! I use scrolloverflowreset  in site.. Connection structure is the same as in the documentation. Tell me, is it possible to change the step of scrolling on the section to which was applied scrollowerflowreset. The documentation iscroll nothing written about it.

**Comment by alvarotrigo** [comment]
As I told you before [twice](https://github.com/alvarotrigo/fullPage.js/issues/2562#issuecomment-279733915) already, you can pass any iScroll options to fullPage.js by using the option `scrollOverflowOptions`. 

scrollOverflowReset is totally irrelevant here.
