### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by polyamide** [alvarotrigo/fullPage.js#2567]
### Description

Got this error when click anywhere on the page when using an Android Chrome or a Desktop Chrome with mobile emulation.

```
Uncaught TypeError: Cannot read property '0' of undefined
    at getEventsPage (jquery.fullPage.js:2610)
    at HTMLDivElement.touchStartHandler (jquery.fullPage.js:1190)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.r.handle (jquery.min.js:3)
```

### Link to isolated reproduction with no external CSS / JS

http://s.codepen.io/polyamide/debug/QdPNvq/xnrabdozjWJA

### Steps to reproduce it
1. Open the isolated reproduction link
2. Enable Chrome's Mobile emulation. (or a real android device)
3. Scroll down a couple section
4. Refresh the page
5. Click anywhere on the page

### Versions 

macOS 10.12.3
Chome 56.0.2924.87
jQuery 1.11.1/1.8.3
fullpage 2.9.2

**Comment by alvarotrigo** [comment]
Nothing to worry about, it won't happen in the real device. 
It is due to the emulation mode not retrieving the `e.touches` value on touch start and touch move events. 

A similar discussion can be seen here: https://github.com/guylabs/ion-autocomplete/issues/31

**Comment by polyamide** [comment]
Thanks for replying so quickly. But actually, I got the same error message on a actual Android device (android 7.0.0, chrome 56.0.2924.87).

**Comment by alvarotrigo** [comment]
I've fixed it now in the dev version. I was taking a deeper look at it and it seems to be [an issue I solved a few weeks ago](https://github.com/alvarotrigo/fullPage.js/issues/2507).
Can you please try again using [this file instead](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)?

**Comment by polyamide** [comment]
The issues no longer exist in the latest dev version, thanks a lot!

**Comment by avinashdvv** [comment]
Hi 
 I am getting same error on laptop , when i am using scroll

**Comment by alvarotrigo** [comment]
Make sure to use the latest fullPage.js version 2.9.4
