### ISSUE TITLE
More than one Menu

### ISSUE THREAD

**Issue by jacob-JM** [alvarotrigo/fullPage.js#2569]
### Description
Hello, 
I have created a second menu to the fullpage using the same link to the anchors as fp-nav and they refuse to work. Any help would be appreciated. 

### Link to isolated reproduction with no external CSS / JS
```
      anchors: ['home', 'whois', 'contact'],
      menu: '#menu',
```
(just a small part of the full page function).

```html
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li data-menuanchor="home"><a href="#home">Home</a></li>
            <li data-menuanchor="whoisthecds"><a href="#whois">Who is?</a></li>
            <li data-menuanchor="contact"><a href="#contact">Contact Us</a></li>
            
        </ul>
    </div>
```

The standard fp-nav does work with the same hrefs, i'm just wondering where I have gone wrong with these. Thanks for any help.

**Comment by alvarotrigo** [comment]
I don't see any element in your HTML with the id `menu`, which is the one you have used in your `menu` option.

**Comment by jacob-JM** [comment]
Even with an Id of menu on the menu the links still don't work. Yet the fp-nav with the same href and without an id="menu" works.

**Comment by alvarotrigo** [comment]
Provide a reproduction. I can't help otherwise.
