### ISSUE TITLE
Fullpage only works in the first two sections

### ISSUE THREAD

**Issue by dtavares** [alvarotrigo/fullPage.js#2570]
Hello,

I'm using fullpage.js to work in a wordpress website.

I'm having one issue that i don't understand why...in my site the fullpage. js only works in the first two sections of the page, returning this in the url when i do scroll "#null".

http://www.terradesign.pt/wp/clapat_sqr_portfolio/beijinho-de-portugal-2/

I have all the id's and div class correct.

Can you help me, please?

Thanks.

Best regards,
Daniela Tavares

**Comment by alvarotrigo** [comment]
You'd better ask the author of the wordpress theme.
I only provide support for fullPage.js issues. 

If you believe it is a bug in fullpgae.js please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by dtavares** [comment]
Really??
ok...

**Comment by alvarotrigo** [comment]
If you are able to reproduce the issue in jsfiddle or codepen I'll happily help you with it. 
But unfortunately I do not deal with websites and less yet if they are using wordpress :)

**Comment by dtavares** [comment]
Thank you. :)

I found other solution. :)
