### ISSUE TITLE
Offset sections change percentage based on viewport

### ISSUE THREAD

**Issue by getupkid203** [alvarotrigo/fullPage.js#2571]
Hello,
Is there a way to alter the height percentage in the offset sections extension based on the viewport?
E.g. in desktop set data-percentage="60" and in mobile data-percentage="40" ?

I've tried to destroy the instance of fullpage on window.resize, then update the data-percentage and then try to re-initialise again, but that's not working.

Any help appreciated.

Cheers

**Comment by alvarotrigo** [comment]
> I've tried to destroy the instance of fullpage on window.resize, then update the data-percentage and then try to re-initialise again, but that's not working.

That should do it. 
Make sure to use `destroy('all')` and not only `destroy`.
