### ISSUE TITLE
 license error when connecting webvizor 

### ISSUE THREAD

**Issue by IllyaHorbatenko** [alvarotrigo/fullPage.js#2573]
Hello, we use bronchiectasis scrollOwerflowReset [remove link] on site. When you connect an error Yandex webvizor license for faull page extention. How can I remove this error message?

**Comment by alvarotrigo** [comment]
As detailed int he mail that was sent to you just after the purchase, as well as [in the documentation online](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension);

> Access the URL that was sent to your email address when purchasing the extension.
> You will be asked to introduce the license key that was given to you when purchasing the item.
> Additionally a domain name might be required in order to obtain the activation key for your product.
> Then add the activation key for the specific extension by adding an option in the fullpage.js initialization with the form nameOfExtension: key:
