### ISSUE TITLE
control arrows with loopHorizontal:false and interlockedSlides:true

### ISSUE THREAD

**Issue by tschortsch22** [alvarotrigo/fullPage.js#2574]
### Description
With loopHorizontal:false and interlockedSlides:true control arrows are not updating according to interlocked slides in further sections, they keep their original state.

### Steps to reproduce it
1. Create 3 sections each containing 3 slides with basic configuration
2. In section 1 move to slide 2
3. Move section down
4. There should be 2 arrows (left/right) but only the right-hand side arrow is shown.

### Versions 
fullPage 2.9.2 - Extensions 0.0.6 master
fullPage 2.9.2 - Extensions 0.0.7 dev-branch
jQuery 3.1.1

I appreciate any help!

**Comment by alvarotrigo** [comment]
Please use the [dev version 2.9.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js)

Then, if you tell me the email you used for the purchase, I'll send you the new version of the extension that fixes the issue.

**Comment by tschortsch22** [comment]
Thanks a lot! I sent you an email with my contact information.

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.3
