### ISSUE TITLE
FP Auto Height

### ISSUE THREAD

**Issue by bdadev** [alvarotrigo/fullPage.js#2577]
Before I would say that fullPage.js is undoubtedly the best discovery I had last year, you did an incredible job.

Just want to say that I found that the fp-auto-height option does not work in a specific section when all sections are with background fixed / cover. Anyway, with me it did not work.

I have some examples of website that really outdid me lol

Http://crwfitness.com.br/
Http://gordoemagro.com.br/

This is just a comment, maybe it could be wrong.

Big hug! Thanks!

**Comment by alvarotrigo** [comment]
Thanks! Glad you find it useful!

> Http://crwfitness.com.br/
Http://gordoemagro.com.br/

I don't see any section with the class `fp-auto-height` in any of those sites.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by bdadev** [comment]
Yes my friend, I could not make this option work, so I changed the strategy until I found another solution.

But I'll put a codepen here soon, okay?

Thank you!

**Comment by alvarotrigo** [comment]
I would recommend you to check the [autoHeight.html example in the examples folder](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/autoHeight.html) and check if you find your issue by comparisson. 

Also available [online](http://alvarotrigo.com/fullPage/examples/autoHeight.html).

**Comment by jtlscout** [comment]
I figured out that the reason it doesn't work is because the CDN on the GitHub repository doesn't support fp-auto-height. Here's what does:
<link href="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.css" rel="stylesheet"> <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script> <script src="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.js"></script>

**Comment by trainoasis** [comment]
@jtlscout it seems it really doesn't. I installed via NPM and it fp-auto-height doesnt work as well. 
So you are saying I now must hard-code the script instead of using a package manager? Ouch.
