### ISSUE TITLE
Unable to click links and input fields on mobile

### ISSUE THREAD

**Issue by legiondesigns** [alvarotrigo/fullPage.js#2578]
When I view my site on mobile the anchor links are not clickable and input fields are not accessible.

Also when I set "responsiveWidth: 640" to disable fullpage on mobile I am no longer able to scroll down or move past the first section on my phone and still can't click any links.

Does anyone know what I am doing wrong?

**Comment by alvarotrigo** [comment]
Please make sure to use the latest fullPage.js version 2.9.2.

If you are, then please provide an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

I'll close the issue meanwhile.
