### ISSUE TITLE
Responsive not working correctly 

### ISSUE THREAD

**Issue by nickress** [alvarotrigo/fullPage.js#2580]
I am having a couple issues getting this to work correctly on mobile. I have set the responsiveWidth to 900 and when I shrink my browser under 900 the site scrolls normal, however, when viewing it on my phone or through Chromes mobile inspector it is still scrolling to each section as opposed to a normal scroll. The second issue is that the font seems to be shrinking on mobile. 

Im sure Im missing something but I cannot figure this out. 

Any help would be appreciated. 

Here is the the link to the example. 
http://s.codepen.io/nickress/debug/zZxrJX/gakeYJOjPGnk
http://codepen.io/nickress/pen/zZxrJX

### Steps to reproduce it
1. Right click and select "inspect"
2. Click on the Toggle device icon and select iPhone 6.

Thanks
Nick

**Comment by alvarotrigo** [comment]
> however, when viewing it on my phone or through Chromes mobile inspector it is still scrolling to each section as opposed to a normal scroll.

Use the full page view. 

> The second issue is that the font seems to be shrinking on mobile.

fullPage.js doesn't do anything with fonts at all. Not a fullPage.js issue.
