### ISSUE TITLE
How to disable "mobile" version?

### ISSUE THREAD

**Issue by riccardomessineo** [alvarotrigo/fullPage.js#2581]
I'm trying to handle responsive design by using media queries. Until I use the desktop version everything works fine, but as soon as I use "Mobile" (even in chrome dev tools) page height becomes doubled and every element gets smaller...

Is there a way to disable this behavior?

**Comment by alvarotrigo** [comment]
There's no such thing as "mobile" version nowadays. 
There are touch desktop computers, tablets with bigger screens than some laptops and mobile phones with bigger resolutions than some desktops. 

Responsiveness is based in resolution, not on the type of device. 

Use the `responsiveWidth` and `responsiveHeight` options of fullPage.js as well as `fp-auto-height-responsive` if necessary.

Take a look at the examples in the examples folder on the ones available online.

**Comment by riccardomessineo** [comment]
Just for reference, my problem was fixed by adding this meta tag:
	<meta name="viewport" content="width=device-width, initial-scale=1">

Thanks for the support.

**Comment by haris-aqeel** [comment]
@riccardomessineo  Glad you were able to resolve the issue
