### ISSUE TITLE
Stuck/not working mouse wheel

### ISSUE THREAD

**Issue by isloboda** [alvarotrigo/fullPage.js#2585]
Sections getting unscrollable by mouse wheel after page refresh. In firefox it doesn't work at all. Dev console is empty. Scrolling with arrows seems to work well. 

Website  - http://new.it-kitchen.com.ua

### Versions 
Windows 10, Chrome 56.0.2924.87 (64-bit); Firefox 45.7.0

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/) works as expected.

Please provide an isolated reproduction with no external CSS or JS in jsfiddle or codepen as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
I'll close the issue until then.
