### ISSUE TITLE
issues with scrolling with links and id anchors, 

### ISSUE THREAD

**Issue by Oblik-Design** [alvarotrigo/fullPage.js#2586]
I've got a nine page website i'm working on, 

links are set not for all of them in the menu, once you use one, lets say link number 7, it becomes the top of the website, and there is no way to scroll back. even if it is at 700vh from the top .

if you click on the second link, B is now the top... wich is not what I would like obviously, also, the events do not fire, is I go to a section, not by scrolling , but with a link
https://jsfiddle.net/tft14udf/1/

**Comment by alvarotrigo** [comment]
See the examples provided in the example folder.
You should not be using `#stop1` as a link, but '#bb' instead. 

See: https://jsfiddle.net/tft14udf/2/
