### ISSUE TITLE
Sections height to high, but normal on window resize 

### ISSUE THREAD

**Issue by lucaey** [alvarotrigo/fullPage.js#2587]
I use Brackets and Chrome.
When I load the page the sections are much too high, but when I resize the window for just a little bit, everything is perfect.

**Comment by alvarotrigo** [comment]
It might be that you forgot to add the compulsory DOCTYPE declaration.
```html
<!DOCTYPE html>
```
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
