### ISSUE TITLE
Resize : TypeError: e.find(...).get(...) is undefined

### ISSUE THREAD

**Issue by agrigo2s** [alvarotrigo/fullPage.js#2592]
Hi,
first, thank you for fullpage. It realy cool!

### Description
Everytime i Resize the browser i get a Script error: 

`Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at Pn (jquery.fullpage.extensions.min.js:727)
    at HTMLDivElement.<anonymous> (jquery.fullpage.extensions.min.js:107)
    at Function.each (jquery.js:383)
    at jQuery.fn.init.each (jquery.js:136)
    at pe (jquery.fullpage.extensions.min.js:103)
    at jquery.fullpage.extensions.min.js:677`

I startet to search in the code and the problem is the `n = e.find(I).get(0).scrollHeight` in `                r.length ? n = t.scrollHeight(e) : (n = e.get(0).scrollHeight, l.verticalCentered && (n = e.find(I).get(0).scrollHeight));
`

Has anybody an idea how to solve this problem?

regards,
Artur

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. resize the browser

### Versions 
Chrome and Firefox, Ubuntu, Desktop-C

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
