### ISSUE TITLE
Autoscrolling doesn't work [pureJS version]

### ISSUE THREAD

**Issue by Nubzor** [alvarotrigo/fullPage.js#2593]
Autoscrolling to #value doesn't work on pureJS version. Anyhow you have the #value or not it doesn't scroll to the #value section. Lets assume that #value is a section of index > 1

You can try to reproduce it this way:

Init the fullpage script like 

```javascript
 fullpage.initialize('#content', {
        anchors: ['first', 'second', 'third', 'fourth'],
        navigation: true,
        autoScrolling: true,
        loopBottom: true,
});
```

The problem occure on line 309 (master version). The value of section.length is undefined. I would recommend check the type of section's value (object/null) instead of the length property.

I've catch the issue on Chrome 57 on 10.12.3 OSX (MacBook Pro)

**Comment by alvarotrigo** [comment]
The [demo page](http://alvarotrigo.com/fullPage/pure-javascript/#3rdPage) works as expected and has the same `autoScrolling` value than yours.

I'll close the issue until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Nubzor** [comment]
Sorry for the delay but it's not. Try to entry the page with the anchor that doesn't exists. Use the page you've provided above with an anchor like: #test. You'll see an error which I've described above.

**Comment by alvarotrigo** [comment]
> You'll see an error which I've described in first comment.

You are right. There's an error in the console. But the auto scrolling feature works as expected.
Please feel free to provide a pull request with your suggestion to fix the issue.
