### ISSUE TITLE
Can I add the dot for the slider?

### ISSUE THREAD

**Issue by waisie** [alvarotrigo/fullPage.js#2594]
How do I add slide dot for the slider? So If I have 4 images, it will show 4 dots. If I click the dot if slide to next image.
[Dot Example](https://owlcarousel2.github.io/OwlCarousel2/demos/basic.html)

If it's possible to add the slide dot, how do I remove the prev and next arrows?

**Comment by alvarotrigo** [comment]
> If it's possible to add the slide dot

Yeah. Use the fullPage.js option `slidesNavigation:true` for the slides. 
For sections, just use `navigation:true`.



> how do I remove the prev and next arrows?

Just use the option `controlArrows:false`.
Basically:

```javascript
$('#fullpage').fullpage({
     slidesNavigation:true,
     controlArrows:false
})
```
