### ISSUE TITLE
How do I make the slide control arrow auto slide?

### ISSUE THREAD

**Issue by waisie** [alvarotrigo/fullPage.js#2595]
```javascript
function fullPage() {
    $('#fullpage').fullpage( {
        slidesNavigation: true,
        controlArrows: false
        }
    );
}
```

**Comment by alvarotrigo** [comment]
See the fullPage.js frequently answered questions ["Is it possible to scroll automatically through sections / slides?"](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#is-it-possible-to-scroll-automatically-through-sections--slides)
