### ISSUE TITLE
How do I show my footer when i use fullPage plugin?

### ISSUE THREAD

**Issue by waisie** [alvarotrigo/fullPage.js#2596]
When I add the fullPage plugin, my footer disappear. How do I make the footer show up? For my homepage, i want it without footer but for my other pages, i want my footer. Because I will use the slider in my shop page.

**Comment by alvarotrigo** [comment]
Use the footer within a section with `fp-auto-height`  or as a fixed element.

**Comment by waisie** [comment]
Thank you. But how about other pages i use Fullpage plugin i want the footer to show and some pages i don't want to show. For my homepage i don't want to show the footer, but for my shop page i want to show the footer. Because for my shop page i will use the slider and then i will have products and then footer.

**Comment by alvarotrigo** [comment]
> But how about other pages i use Fullpage plugin i want the footer to show and some pages i don't want to show.

That's not fullPage.js business, you'll have to work on it by yourself.

**Comment by alvarotrigo** [comment]
Create the footer when you need and don't create it when you don't need to.

**Comment by waisie** [comment]
But I'm using Wordpress footer.php so I share my footer for all pages. U mean I should have 2 footers??? Can I use js so i don't have to create 2 footers? OR is there another way ?

**Comment by alvarotrigo** [comment]
That's a wordpress issue not a fullPage.js one I'm afraid. You'll have to ask somewhere else.

**Comment by waisie** [comment]
By the way, when i the class for my footer "fp-auto-height", nothing show up.

**Comment by alvarotrigo** [comment]
@waisie I can only provide you help if you are able to reproduce the issue in jsfiddle or codepen I'm afraid. 
It seems to me your problems are not with fullpage.js but with wordpress.

There are plenty of demos available [at the documentation](https://github.com/alvarotrigo/fullPage.js) . Even one for the `fp-auto-height `feature you are trying to use.  [Check it out](http://codepen.io/alvarotrigo/pen/BKjRYm).
