### ISSUE TITLE
Parallax extension: jQuery is not defined

### ISSUE THREAD

**Issue by dghete** [alvarotrigo/fullPage.js#2597]
I'm using the parallax extension in a transpiled ES6 Angular app with dependencies pulled from node modules via npm.

When using just the fullpage main script everthing works perfectly.
```javascript
import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;

import 'fullpage.js/dist/jquery.fullpage.extensions.min.js';
```

If I try to use the parallax extension like this:
```javascript
import jQuery from 'jquery';
window.$ = window.jQuery = jQuery;

import '../app/components/vendor/fullpage.parallax.min';
import 'fullpage.js/dist/jquery.fullpage.extensions.min.js';
```

I'm getting the following error:

> Uncaught ReferenceError: jQuery is not defined
    at Object.<anonymous> (fullpage.parallax.min.js:8)
    at __webpack_require__ (bootstrap d73d17d…:19)
    at Object.<anonymous> (index.module.js:14)
    at __webpack_require__ (bootstrap d73d17d…:19)
    at bootstrap d73d17d…:39
    at bootstrap d73d17d…:39
(anonymous) @ fullpage.parallax.min.js:8
__webpack_require__ @ bootstrap d73d17d…:19
(anonymous) @ index.module.js:14
__webpack_require__ @ bootstrap d73d17d…:19
(anonymous) @ bootstrap d73d17d…:39
(anonymous) @ bootstrap d73d17d…:39

**Comment by alvarotrigo** [comment]
I'm not a webpack expert, but it seems jQuery is loading after fullPage.js? 
You have to make sure jQuery loads before fullPage.js and that the extension file is imported before loading fullPage.js as well .

**Comment by dghete** [comment]
Ok, indeed import statement transpiling was breaking the order. 
I've fixed it by using webpack require methods:

```javascript
window.$ = window.jQuery = require('jquery');
require('../app/components/vendor/fullpage.parallax.min');
require('fullpage.js/dist/jquery.fullpage.extensions.min.js');
```

Everything loads in the correct order and without any erorrs, but still $.fn.fullpage is missing the parallax object.

```javascript
$.fn.fullpage.parallax.init()
```

Triggers the error: "Cannot read property 'init' of undefined"

**Comment by dghete** [comment]
I've had an old version of fullpage.js.
Updated to latest and everything works.
Thanks.
