### ISSUE TITLE
Is Fullpage js compatible with Semantic-Ui?

### ISSUE THREAD

**Issue by jackrsantana** [alvarotrigo/fullPage.js#2599]
When I use the grid system of Semantic UI i lose the height of my grids and when I resize my page one section is overlaping the previous section.

http://codepen.io/jack_rsantana/pen/ryMooO

1. Go to http://codepen.io/jack_rsantana/pen/ryMooO.
2. Resize the page.

![captura de tela 1](https://cloud.githubusercontent.com/assets/16987558/23638782/73606fe6-02c2-11e7-80ee-a2cf3ff0b280.png)
![captura de tela 2](https://cloud.githubusercontent.com/assets/16987558/23638783/73679afa-02c2-11e7-8feb-5c92a04ec03f.png)

Chrome 56.0.2924.87, Windows 10 Home Version 1607 Build 14393.0

**Comment by alvarotrigo** [comment]
You are not importing the required fullpage.js CSS file.

**Comment by jackrsantana** [comment]
Sorry for the silly mistake. I'm starting with web and I do not speak English.
Anyway, although I was not importing the css. The main error remains. As can be seen in the image below, when the semantic-ui stacking mode is activated, section 2 overlaps section 1 by hiding part of the yellow div.
![screencapture-127-0-0-1-8000-teste-1488890429362](https://cloud.githubusercontent.com/assets/16987558/23657075/2d9be612-031b-11e7-929b-607a17e527df.png)

**Comment by alvarotrigo** [comment]
That's totally normal. That's how fullPage.js works. Using full screen sections. 
If you content is bigger than your sectinon you'll have to use `fp-auto-height`  or `scrollOverflow:true`.

**Comment by tmsilva** [comment]
@alvarotrigo Even in responsive mode?
I agree that this behavior is normal in full screen mode.
But when this mode is disabled to give way to the responsive mode. Ideally, the elements should respect their sizes and flows as a normal page. I guess ...

**Comment by alvarotrigo** [comment]
> Even in responsive mode?

Yeah, the reponsive mode only turns off auto scrolling. 
You should be using `fp-auto-heigh-responsive`. Check the docs for more info and examples.
