### ISSUE TITLE
CSS reset using "all:unset" breaks layout

### ISSUE THREAD

**Issue by abimelex** [alvarotrigo/fullPage.js#2601]
I'm using the alpha-no-jQuery version and I have this in my CSS-Reset which seems to break the layout totaly:
```
* {
    all: unset;
}
```

**Comment by alvarotrigo** [comment]
Use that line before importing the CSS stylesheet.

**Comment by abimelex** [comment]
Did you tested it? The CSS reset was indeed the first file I imported in my project.

**Comment by alvarotrigo** [comment]
Please provide a reproduction in jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
Ok, here's the link:
http://jsfiddle.net/97tbk/1775/

Not quite sure what the CSS property does... but it is something pretty weird. It is printing the content of the CSS in jsfiddle :S

**Comment by alvarotrigo** [comment]
But even when fullPage.js is not applied: http://jsfiddle.net/97tbk/1776/

**Comment by abimelex** [comment]
That's weird. Ok, I guess this whole property is kind of nasty, so I will get rid of it in my CSS reset. Thanks for testing.
