### ISSUE TITLE
play video from the beginning after every load 

### ISSUE THREAD

**Issue by kaochihhui** [alvarotrigo/fullPage.js#2602]
Hi, 

Thanks for the brilliant work! It's awesome!

By default, the video will pause when leaving the section, and continue playing after back to the section.

Is it possible to make the video play from the beginning after every time back to the section?

Thank you.

**Comment by alvarotrigo** [comment]
> Is it possible to make the video play from the beginning after every time back to the section?

fullPage.js doesnt provide such option, but I'm sure it is possible by using Javacript in combination with some callback. 

I'd recommend you to ask in stackoverflow about the functionality regarding the restart of the video.
