### ISSUE TITLE
The Webpage is reloaded - Ipad Safari - IOS Issue

### ISSUE THREAD

**Issue by shantanusuryawanshi** [alvarotrigo/fullPage.js#2603]
### Description
I am using fullpage JS, In my webpages I used 40 to 50 sections/slides. When I loaded my website in Ipad IOS safari browser, Its continuously showing warning, The Webpage is reloaded. Site working in Iphone, Desktop and other browsers.  Can you please let me know the solution on the same.

I already check with device settings, network setting, java versions issue and other hardware settings. Also removed all cache and cookies. Still getting same error.

**Comment by alvarotrigo** [comment]
> Its continuously showing warning,

You'll have to be more specific and provide a description of the warning. And ideally, a reproduction in jsfiddle or codepen.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
