### ISSUE TITLE
If section is active add class to child

### ISSUE THREAD

**Issue by agentlucky** [alvarotrigo/fullPage.js#2604]
Hi,
i need to add an extra class to the child of the active section. I tried quite a few things but it just adds the class to all of the section childs but not just to the active one.
Or is there another way to somehow detect the child of the active section?
thanks in advance

David

**Comment by alvarotrigo** [comment]
> Or is there another way to somehow detect the child of the active section?

Use callbacks such as `afterLoad` or `onLeave`. Read more about callbacks [in the docs](https://github.com/alvarotrigo/fullPage.js#callbacks).
Or just use something like `$('.section.active)`

**Comment by agentlucky** [comment]
That's what i ment. It applies to all sections. Not only to the active one. Here is the code i'm using:

afterLoad: function(anchor, index){
            if ( $('.fp-section').hasClass('active') ) {
				$('.desc').addClass('color');
			}
      	}

**Comment by alvarotrigo** [comment]
No. You should be using the logic based on the parameters the callback provides.

Like can be seen in the examples at the docs.
Use comething like `if(index === 1)` or `if(anchor === 'mySectionAnchor')`

**Comment by agentlucky** [comment]
Ok. But i can't set a value like '1' or 'myAnchor'. It has to be dynamically cause every section could be the active one, right? Only the child of the active section has to get an additional class.

**Comment by alvarotrigo** [comment]
```javsacript
afterLoad: function(anchor, index){
   $('.fp-section.active').addClass('whatever')
}```

**Comment by agentlucky** [comment]
Doesn't help...That's what i ment.

**Comment by agentlucky** [comment]
Wait. That adds the extra class to the actual element but not to the child.

**Comment by agentlucky** [comment]
Got the solution
```
afterLoad: function(anchor, index){
   if($('.fp-section.active')) {
      $(this).children('.child').addClass('extra_class');
   }
},
onLeave: function(anchor, index){
   if($('.fp-section.active')) {
      $(this).children('.child').removeClass('extra_class');
   }
}
```
