### ISSUE TITLE
Input on fixed header makes page jump to first section with IOS

### ISSUE THREAD

**Issue by victorcl** [alvarotrigo/fullPage.js#2605]
Hi , I am having this issue where I have an input inside a fixed header and in IOS (chrome or safari) if I click the input it will take me to the first section , this doestn happen on android or desktop browsers , only in IOS , here I have made up a test page that reproduce this error [Error page test](http://dev.victorcl.com/fullpage) scroll down to any section and click on the input in the orange header and you will see the problem.

Thanks.

**Comment by alvarotrigo** [comment]
You can reproduce it without fullPage.js too:
http://alvarotrigo.com/fullPage/test1.html

Not a fullPage.js issue but a browser one.
