### ISSUE TITLE
Fixed elementes move on scrolling up and down

### ISSUE THREAD

**Issue by rafaelsousa99** [alvarotrigo/fullPage.js#2610]
I have a div on a div class="section" thats inside fullpage wrapper, I want to fix it and prevent it from move but when I scroll down and I scroll up to go back to the section I was the "fixed"div moves up, I want to the div always stay on middle of section but it doesnt happen

**Comment by rafaelsousa99** [comment]
http://2vgsi.com/ here you got an live example (the divs that hold content arent fixed, they move when you scroll down and if u scroll up back they arent on the same position that they were

**Comment by alvarotrigo** [comment]
That's a browsers' bug:
http://stackoverflow.com/a/15256339/1081396

Just place them outside fullPage.js wrapper.
