### ISSUE TITLE
How to: Scroll down to specific slide in a section?

### ISSUE THREAD

**Issue by KainLaVey** [alvarotrigo/fullPage.js#2615]
Hi There,

I have two Sections. The second Section includes Slides.
If iam scrolling down from "Section One" to "Section Two" it will allways show "Slide1" first.

But what i need is to change the behavior in this Way:
If the User scrolls down from "Section One" to "Section Two" it should show "Slide3" as default.

I know i can link to a specific Slide like "http://website.com/#SectionTwo/Slide3". But how can i tell fullPage.js to use "Slide3" as the "Default Slide" to start with?

Best regards.

**Comment by alvarotrigo** [comment]
Read the [Required HTML structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure)

> If you want to define a different starting point rather than the first section or the first slide of a section, just add the class active to the section and slide you want to load first.

**Comment by KainLaVey** [comment]
THX <3
