### ISSUE TITLE
Scrolling a modal wich has a bigger height then the document is not possible (Iphone 6)

### ISSUE THREAD

**Issue by JanAckermann1337** [alvarotrigo/fullPage.js#2616]
### Description
Opening a Modal wich has its own scrollbar can not be Scrolled on Iphone 6 and lower in Safari and Chrome.

### Link to isolated reproduction
http://fiddle.jshell.net/o46332j6/21/show/light/

### Steps to reproduce it
1. Get an Iphone6 or Lower (Browserstack)
2. Try to "Touchscroll" the left Modal

### Versions 
Safari and Chrome on Iphone 6 and lower

**Comment by alvarotrigo** [comment]
Use `$.fnf.fullpage.setAllowScrolling(false)` when opening the modal.
Or try using `normalScrollElements.` 

Google some answer, it has been treated multiple times:
http://stackoverflow.com/questions/38264469/block-scroll-on-modal-open

**Comment by JanAckermann1337** [comment]
I dont think this helps for my problem. I dont have the problem that it keeps scrolling when the modal is open. I just cant scroll the Modal content itself. It dose work fine on an Iphone 7 but not lower or.

**Comment by alvarotrigo** [comment]
Yeah right. This is a duplicate of #1912
Was also treating the same issue minutes ago here https://github.com/alvarotrigo/fullPage.js/issues/2614

Easy solution? 
Use `css3:false` and use a fixed element inside the fullPage.js wrapper. 
Then use `normalScrollElements`.

Other than that, you'll have to modify the library as suggested in a comment in #1912

**Comment by JanAckermann1337** [comment]
Thank you for your quick answer. I will look into the threads you sent me.
