### ISSUE TITLE
iOS 10.2 Safari Page Touch Slide Up, and Hamburger Menu sliding problem

### ISSUE THREAD

**Issue by DamirPecnik** [alvarotrigo/fullPage.js#2618]
### Description
I am having a problem with iOS 10 iPhone and iPad Safari and Chrome Browser, the Slides can be slided from bottom to top but it does not work from top to bottom. Also in the hamburger menu if the menu is shown on iPhone SE iOS 10.2 you can't touch scroll it its just not moving. I tested the menu and page slide on the Samsung S7 Chrome and it works perfect also on Chrome and Safari on MacOS and on Windows 10 Chrome.

### Link to isolated reproduction with no external CSS / JS
Isolated case here: http://alliancesfordiscovery.org

### Steps to reproduce it
Try to touch slide from bottom to top and then slide from top to bottom of the screen it will not work. Also for hamburger menu if on the smaller device iphone 6 or iphone SE  you cant scroll the menu up and down.

### Versions 
iOS 10.2 Safari and Chrome iPhone 6S and iPhone SE, latest version of fullPage 2.9.3

**Comment by alvarotrigo** [comment]
As detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues)

> An isolated reproduction of the issue will be required. Make use of jsfiddle or codepen for it if possible.

And as detailed in the issue skeleton:

> links to personal websites won't be reviewed unless isolated

Closed until an isolated reproduction with no external CSS or JS is provided.

**Comment by alvarotrigo** [comment]
Look like a problem with your `g-navigation` element. 

This is a duplicate of #1912
Was also treating the same issue minutes ago here #2614

Easy solution?
Use css3:false and use a fixed element inside the fullPage.js wrapper.
Then use normalScrollElements.

Other than that, you'll have to modify the library as suggested in a comment in #1912

**Comment by DamirPecnik** [comment]
I got the page content moving it was padding, but i have still problem with the hamburger menu, i tried this:
css3:false,
normalScrollElements: '#g-offcanvas',
normalScrollElementTouchThreshold: 1

i also changed the functions

> You could solve the problem by changing in both functions $(WRAPPER_SEL) for $(document).

After i did this the content start moving and not the menu. I need the menu to slide up and down if the window is smaller then menu.

**Comment by alvarotrigo** [comment]
Use a higher `normalScrollElementTouchThreshold` value.  Try 10.

**Comment by alvarotrigo** [comment]
Also, place inside the `#g-offcanvas` element inside `#g-fullpage` .

**Comment by DamirPecnik** [comment]
This worked ;) Thanks
> Use a higher normalScrollElementTouchThreshold value. Try 10.
