### ISSUE TITLE
How to refresh IScroll on window resizing?

### ISSUE THREAD

**Issue by iTayGNR** [alvarotrigo/fullPage.js#2619]
Hi,
I'm using `scrollOverflow: true`, and when I resize my window from something like ~300px high to the normal height, the scrollbar stays and prevents from the content to fit to the section.

How can I refresh the IScroll when the window gets resized?

thanks :)

**Comment by alvarotrigo** [comment]
It should refresh automatically. 
Please provide an isolated reproduction in jsfiddle or codepen without external CSS or JS. 

I'll close the issue until then.

**Comment by iTayGNR** [comment]
you may check in my website: http://shabbat.party
just open the developer console, make it cover almost all the screen and close the console. see how the content does not return to its original height..

**Comment by alvarotrigo** [comment]
> you may check in my website: http://shabbat.party

As detailed in the issue skeleton:

> ### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
