### ISSUE TITLE
Mobile horizontal slides, but desktop just a list 

### ISSUE THREAD

**Issue by BenRacicot** [alvarotrigo/fullPage.js#2622]
### FullPage Conflicting with Flexslider's `slide` class
I'm rebuilding a website and came across an issue where the slide class conflicts with Flexslider. But I'm hoping the solution might be built in to FullPage.js... On mobile I'm currently using Flexslider to scroll horizontally through a list of images. Then on desktop I simply display them in a row.

Now I've adopted FullPage.js but Flexslider's `slide` class conflicts with FullPage.js' `slide` class. Is there a built in way to have horizontal scrolling limited to mobile only? Then on larger screens I can simply layout each image (slide class) without the horizontal scrolling effect?

### Link 
The second page on [this codepen](http://codepen.io/joe-watkins/pen/rFzcf) shows the horizontal effect I'd like to use on mobile only. But I am not seeing a way to stop it from functioning that way on desktop (or > 1024px)

Perhaps there's an option to change the classname `slide` from being used and I could continue to use Flexslider on mobile?

Any advice would be great, because I'd love to forget Flexslider and use FullPage exclusively.

**Comment by alvarotrigo** [comment]
Use the option `slideSelector` as detailed in the docs.
