### ISSUE TITLE
inputs and scrolloverflow

### ISSUE THREAD

**Issue by eeeman1** [alvarotrigo/fullPage.js#2623]
On mobile devices or in webkit browsers, the inputs do not lose focus when pressed outside them. This problem occurs when connecting to the scrolloverflow extension

http://codepen.io/anon/pen/zZRPYp

### Steps to reproduce it
1. Open this link for example in chrome
2. Find the input field and click on it to get the focus
3. Now try to remove the focus by clicking on any place outside the input field

**Comment by alvarotrigo** [comment]
I've [reported it now in iScroll.js issues forum](https://github.com/cubiq/iscroll/issues/1139).

It is definitely a iScroll.js issue and not a fullpage.js one as can be seen in [this demo](https://jsfiddle.net/vhc3bmmk/1/) without fullPage.js

**Comment by eeeman1** [comment]
Yes, for sure, I also noticed that you can not select text, as well as select the checkbox or radio


>Понедельник, 20 марта 2017, 20:14 +03:00 от Álvaro <notifications@github.com>:
>
>I've  reported it now in iScroll.js issues forum .
>It is definitely a iScroll.js issue and not a fullpage.js one as can be seen in  this demo without fullPage.js
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .



