### ISSUE TITLE
height issue on mobile form

### ISSUE THREAD

**Issue by shahjehanali1** [alvarotrigo/fullPage.js#2624]
If I will try to fill the form, height of the section is decrease

http://test.psd2htmldesign.com/runforballs/

Please try to fill this form

**Comment by shahjehanali1** [comment]
need quick reply

**Comment by shahjehanali1** [comment]
@alvarotrigo Please help

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
