### ISSUE TITLE
OnLeave Callback + Animation?

### ISSUE THREAD

**Issue by Uranbold** [alvarotrigo/fullPage.js#2625]
I wanna add transition into fullPage and i have used this.

```
onLeave: function (index, nextIndex, direction) {
                    var animIt = jQuery('.tw-fullpage-main > .pt-page.active');
                    //scrolling down
                    if (direction == 'down') {
                        if ($fpAnimType == 'normal') {
                            animIt.addClass('pt-page-scaleDown');
                            setTimeout(function () {
                                animIt.removeClass('pt-page-scaleDown');
                            }, 700);
                        }
                    }
                    if (direction == 'up') {
                        if ($fpAnimType == 'normal') {
                            animIt.addClass('pt-page-scaleDown');
                            setTimeout(function () {
                                animIt.removeClass('pt-page-scaleDown');
                            }, 700);

                        }
                    }
                },
```
It works on Slider Leave but i wanna add entering Animation on Next Slideshows and i have tried following and it's not working...

```
if (nextIndex){
            animIt.addClass('pt-page-scaleDown');
                        setTimeout(function () {
                                    animIt.removeClass('pt-page-scaleDown');
                        }, 700);
}
```

But i have failed it. Could you suggest some idea?

**Comment by alvarotrigo** [comment]
> It works on Slider Leave but i wanna Add Entering Next Slideshows to another transition

I don't understand what you mean by that. Please explain with other words.

**Comment by Uranbold** [comment]
> > It works on Slider Leave but i wanna Add Entering Next Slideshows to another transition
> I don't understand what you mean by that. Please explain with other words.

I mean i want to add Transition Next Slideshow (Before that slideshow enter i want to add Transition)

Please take a look at this example. https://tympanus.net/Development/PageTransitions/

**Comment by alvarotrigo** [comment]
You can only make use of the `onLeave` and `afterLoad` callbacks. There's no more. 
I hope that answers your question.
