### ISSUE TITLE
fullPage.js in Wordpress

### ISSUE THREAD

**Issue by MichaelNoto** [alvarotrigo/fullPage.js#2626]
Hi, in my school project i am doing a child theme for Wordpress, and i would use fullPage.js. I'm following a guide that says it is a JQuery plugin, so why i can't import it in Wordpress like any other plugin?  It says "The package can not be installed. No results were found valid plugin." I downloaded the last version and WordPress is also at the last version, so i can't understeand.

### Wordpress Version 
WordPress 4.7.3

### fullPage Version
fullPage.js-master

**Comment by alvarotrigo** [comment]
fullPage.js is a jQuery plugin and a Javascript library, not a Wordpress one.
Nevertheless, you can easily find other wordpress themes out there using it such [this one](http://alvarotrigo.com/fullPage/utils/wordpress.html).

Find more components [at the resources section of the docs](https://github.com/alvarotrigo/fullPage.js#resources).
