### ISSUE TITLE
Use fullPage.js in WordPress

### ISSUE THREAD

**Issue by MichaelNoto** [alvarotrigo/fullPage.js#2627]
For my school project i need to use fullPage.js in WordPress, but i can't understeand how to import it because the guide i am following says it is a JQuery Plugin, but i can't install it like any other plugin, i get an error like "Installing... No plugin were found, the package can not be installed". How it work? Thanks.
I use WordPress and fullPage.js both at their last version.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2626
