### ISSUE TITLE
Active class not working in fixed top navbar

### ISSUE THREAD

**Issue by Abdullah-al-Papon** [alvarotrigo/fullPage.js#2630]
Hi,
Fullpage.js is a nice plugin. I've used it in lots of pages. 
But I faced problem in the below page.

When I use a fixed top nav. The active class not working. 
I assigned the menu properly.
But still no luck. I can't figure it out.

http://aapapon.com/project/for/

Thanks in advanced.

**Comment by Abdullah-al-Papon** [comment]
I solved the active issue manually. It's kind of boring but works fine.

        if(index == 2){
              $('#n-collapse li:nth-child(1)').addClass('active');
              }
               else{
              $('#n-collapse li:nth-child(1)').removeClass('active');  
          }

**Comment by alvarotrigo** [comment]
Why don't you just make use of the `menu` option.

**Comment by Abdullah-al-Papon** [comment]
I've tried with the menu option. But I can't figure it out why it is not working.
Maybe because of, I used bootstrap classes in the navbar.

**Comment by alvarotrigo** [comment]
Check the examples available in the examples folder.
