### ISSUE TITLE
Using afterRender & wow.js Issues

### ISSUE THREAD

**Issue by huwrowlands** [alvarotrigo/fullPage.js#2631]
I have added wow.js animations to my test site but some sections aren't animating on scroll and some are. So I may have several 'sections' of content on the page, all full screen and each section has an animation of the text fading/zooming in for example. There may be multiples of the same section code too.
.section-type-1, .section-type-2 and so forth (each section type is a different layout).

But for some reason, some animate and some don't?! Or.. It's possible they are animating but before I've even scrolled down the page.

Any help would be appreciated.

Here is (some of) my html:

```
<div class="section-type-1 page-content-section-inner row align-middle wow fadeIn" data-wow-duration="2s" data-wow-delay=".5s"> Content In Here </div>
 
<div class="section-type-2 page-content-section-inner row align-middle wow fadeIn" data-wow-duration="2s" data-wow-delay=".5s"> Content In Here </div>
```

And my JS call in the footer:

```
  jQuery('#fullpage').fullpage({
	 scrollingSpeed  : 1000,
	 loopHorizontal  : true,
	 //paddingBottom   : '105px',
	 responsiveWidth : 768,
	 animateAnchor   : true,
	 recordHistory   : false,
	 verticalCentered: false,
	 scrollBar       : true,
	 autoScrolling   : true,
	 afterRender     : function(){
	 	new WOW().init();
	 }
  });
```

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by huwrowlands** [comment]
Added to Codepen which worked fine for some reason?! https://codepen.io/anon/pen/bqxyqg
I then added offset : 10 to the wow function call and it works.

Thanks
