### ISSUE TITLE
i bought scrollHorizontallyExtensions, how to activate that

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2632]
i bought scrollHorizontally Extensions i don't know to use it please help me to activate that

**Comment by alvarotrigo** [comment]
As detailed [in the docs](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension):

> Access the URL that was sent to your email address when purchasing the extension.
