### ISSUE TITLE
fp-normal-scroll seems to be ignored on mobile?

### ISSUE THREAD

**Issue by IntrepidCreative** [alvarotrigo/fullPage.js#2633]
its great to have the slider working on mobile as it looks very smooth/cool BUT it won't let me escape the last slide and go into the rest of the page. I have the fp-normal-scroll class applied to the last slide of my slider, and the other options set to:

hybrid:true,
css3: true,
fitToSection: false,
//responsiveWidth: 1000, (commented out for now to show as an example)

Markup layout:
Wrapper
 - slide
 - slide
 - slide (with video + fp-normal-scroll)
end wrapper & into the rest of the page content

V: fullPage 2.9.4

**Comment by alvarotrigo** [comment]
`fp-normal-scroll` is not documented and there's no support for it.
