### ISSUE TITLE
Radio and Checkbox Inputs Not Working With scrollOverflow=true (On Mobile Only)

### ISSUE THREAD

**Issue by luispoll88** [alvarotrigo/fullPage.js#2634]
### WHAT I AM USING?
I am using FullPage.js with scrollOverflow.

### MY SETTINGS
These are my settings

```
<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		//Navigation
		sectionsColor: ['#06C', '#C06', '#930', '#06C'],
		anchors: ['aa', 'bb', 'cc', 'dd'],
		menu: '.menu',
		navigation: true,
		scrollOverflow: false, /* True or False Depending */
		scrollBar: true,
		fixedElements: '.header',
		paddingTop: '3em',
		slidesNavigation: true,
		paddingBottom: '1em'
			});
});
</script>
```
### PROBLEM EXPLANATION
I have a contact form that has radio and checkboxes inputs but those inputs don't work in mobile devices with scrollOverflow equals to true. They work on desktops though.

If I chancge scrollOverflow to false the inputs work on mobile but scrollOverflow does not works which is needed because the contact form is long for mobile.

### LIVE EXAMPLES
You can see scrollOverflow=true (enable) on this live example 1 but radio and checkbox inputs don't work on mobile.

1. https://gramerlab.com/a1.html

On these example 2 I disabled scrollOverflow and the radio and checkbox inputs work on mobile but the scrollOverflow don't works which is bad if the contact form is long and I need to scroll.

2. https://gramerlab.com/a2.html

Does anyone knows how to fix this?

**Comment by alvarotrigo** [comment]
That's a iScroll.js issue not a fullPage.js one. 
See some related topic such as:

 -[Submit button in form doesn't work with Iscroll](http://stackoverflow.com/a/24698151/1081396)
- [Form elements inside a iScroll layer are not usable](https://github.com/cubiq/iscroll/issues/576)

Any other issues please report to [iScroll.js repository](https://github.com/cubiq/iscroll). 

Personally I would encourage you to get rid of scrollOverflow and use `fp-auto-height-responsive` together with the responsive options to turn off auto scrolling on small screen devices.

**Comment by alvarotrigo** [comment]
In any case, I've applied the proposed solution from the last comment in https://github.com/cubiq/iscroll/issues/576 in the dev branch.

Please try again using [the latest version in the dev branch of the scrollOveflow file (v 0.0.1)](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.min.js)  and let me know if it fixes it.

**Comment by luispoll88** [comment]
I just upload the latest version from scrollOverflow file (v 0.0.1) to this place --> https://gramerlab.com/overflow.js

And used inside this file https://gramerlab.com/a3.html

But still not working, I will check again what is going in on.

**Should I also include this?**

```
click: false
preventDefaultException: { tagName:/.*/ }
```

**Comment by luispoll88** [comment]
Just to confirm, I added **click:false, preventDefaultException: { tagName:/.*/ }**

And also added the **scrollOverflow file (v 0.0.1)** in here --> <script src="https://gramerlab.com/overflow.js"></script>

But still the problem remains.

```
<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		//Navigation
		sectionsColor: ['#06C', '#C06', '#930', '#06C'],
		anchors: ['aa', 'bb', 'cc', 'dd'],
		menu: '.menu',
		navigation: true,
		scrollOverflow: true,
		scrollBar: true,
		fixedElements: '.header',
		paddingTop: '3em',
		slidesNavigation: true,
		paddingBottom: '1em',
		click:false, 
		preventDefaultException:{tagName:/.*/}
			});
});
</script>
```

**Comment by alvarotrigo** [comment]
@luispoll88 I wouldn't recommend you to play with the `click` option. You will suffer from [unwanted issues](https://github.com/cubiq/iscroll/issues/1055) due to bugs in iScroll.js. fullPage.js deals with that option by itself in the best possible way I found. 

In any case, you should be using the iScroll options withing the `scrolloverflowOptions` option:

```javascript
$('#fullpage').fullpage({
    //other options here
    scrollOverflowOptions: {
        preventDefaultException: {
            tagName: /.*/
        }
    }
});
```

**Comment by luispoll88** [comment]
Confirming, it works only if I also include click:false but not without it.

Also, I am using the original scrollOverflow file, not need to use the modified file scrollOveflow file (v 0.0.1) 

`<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.2/vendors/scrolloverflow.min.js"></script>`

Here are my final settings:

```
<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		//Navigation
		sectionsColor: ['#06C', '#C06', '#930', '#06C'],
		anchors: ['aa', 'bb', 'cc', 'dd'],
		menu: '.menu',
		navigation: true,
		scrollOverflow: true,
		scrollBar: true,
		fixedElements: '.header',
		paddingTop: '3em',
		slidesNavigation: true,
		paddingBottom: '1em',
		scrollOverflowOptions: {
			click:false,	
        	        preventDefaultException: {tagName: /.*/}
        } 
	});
});
</script>
```
So far I have not problems with other links inside my testings.

Tested on iPhone, Android and Kindle Devices, all of them work.

**Comment by alvarotrigo** [comment]
You should be using the latest fullPage.js version in any case. 2.9.4. Yours is quite old :D

And... just be careful when using any link in the scrollOverflow section. Those might not work on desktop or on mobile when you force a the `click` property to `true`.

**Comment by luispoll88** [comment]
How do I get the latest versions of fullpage.js?

Is there a page that I can follow for updates?

**Comment by alvarotrigo** [comment]
> How do I get the latest versions of fullpage.js?

Github? Npm ? Bower? You choose :D

**Comment by luispoll88** [comment]
Yes but is my first time around Github, so I am wondering what is the right page/link I need to visit.

Is this --> https://github.com/alvarotrigo/fullPage.js/tree/master/dist

**Comment by alvarotrigo** [comment]
Yeah, but you can see the releases here:
https://github.com/alvarotrigo/fullPage.js/releases

You can also follow me [on twitter](https://twitter.com/IMAC2).

**Comment by luispoll88** [comment]
Thanks, and the page for the scrolloverflow?

If it not too much to ask.

**Comment by alvarotrigo** [comment]
> Thanks, and the page for the scrolloverflow?

In the vendors folder:
https://github.com/alvarotrigo/fullPage.js/tree/master/vendors

**Comment by luispoll88** [comment]
Gracias

**Comment by MladenJanjetovic** [comment]
This made my radio inputs work again. Thanks!

```
$('#fullpage').fullpage({
	scrollOverflow: true,
	scrollOverflowOptions: {
		click:false
         } 
});
```

**Comment by CressZZ** [comment]
> This made my radio inputs work again. Thanks!
> 
> ```
> $('#fullpage').fullpage({
> 	scrollOverflow: true,
> 	scrollOverflowOptions: {
> 		click:false
>          } 
> });
> ```

I think you should add `preventDefaultException: {tagName: /.*/}` option.
without this option, it would be not work at IOS safari.
