### ISSUE TITLE
The height of the slides is not equal to the height of the sections

### ISSUE THREAD

**Issue by TurboDizel** [alvarotrigo/fullPage.js#2635]
Hi all.
My english is bad. Sorry.

I need to use pictures size 1920px 1080px (in sections and slides). I connected the images (background-image: url (image / NNNN);) but I saw the following on the screen:
Http://i7.5cm.ru/i/JKR7.png
The slide image became smaller in size.
Decision:
Comment out the line for slide and section(!):
padding: 6% 0 0 0;
The problem reminded me of https://github.com/alvarotrigo/fullPage.js/issues/225, but why did not I see the resolution.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
