### ISSUE TITLE
fp-auto-height doesn't work

### ISSUE THREAD

**Issue by allainna** [alvarotrigo/fullPage.js#2636]
### Description
Hi,

Thanks for the great plugin.
For some reason Auto Height property doesn't work. I added the class but nothing. Could you please help?

http://blue-ox-backend.squarespace.com/home

**Comment by shahjehanali1** [comment]
Your Fullpage.css not connected correctly

**Comment by alvarotrigo** [comment]
@shahjehanali1 good spotted !

**Comment by allainna** [comment]
Sorry for this. I've connected it correctly, but it still scrolls this section.

**Comment by alvarotrigo** [comment]
> Sorry for this. I've connected it correctly, but it still scrolls this section.

Of course it does. Why wouldn't it? 
Read the docs, it doesn't say anything about scrolling.

> To create smaller sections just use the class fp-auto-height in the section you want to apply it. It will then take the height defined by your section/slide content.

And see the [example online](http://alvarotrigo.com/fullPage/examples/autoHeight.html#3rdPage).

It seem you just want to use `scrollOverflow:true` instead. Check [the example online](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by allainna** [comment]
Thanks for your answer! I need one section to be as long as its content and not scrolling like a slide till the end of the section. Are you available for some work to help me?

**Comment by alvarotrigo** [comment]
> Thanks for your answer! I need one section to be as long as its content and not scrolling like a slide till the end of the section. Are you available for some work to help me?

That's not something fullPage.js provides I'm afraid. And I'm afraid I do not have time for those kind of works at the moment.

**Comment by allainna** [comment]
Could you please help to figure out what's wrong with the menu and anchors? Or should I create one more question? It's not working.

**Comment by alvarotrigo** [comment]
@allainna no need. Just check the docs regarding how to use the `menu` option and check any of the provided examples with menu, which are almost all. 
Then compare with your code. The issue is most likely in your side.

If you still want to create an issue, provide an isolated reproduction in jsfiddle or codepen. I won't review personal sites. Only if totally isolated with no external js, css and minimum HTML.

**Comment by jtlscout** [comment]
I figured out that the reason it doesn't work is because the CDN on the GitHub repository doesn't support fp-auto-height. Here's what does:
`    <link href="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.css" rel="stylesheet">
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
     <script src="https://rawgit.com/alvarotrigo/fullPage.js/master/jquery.fullPage.js"></script>
`
