### ISSUE TITLE
Horizontal slider dots delayed

### ISSUE THREAD

**Issue by matiasv93** [alvarotrigo/fullPage.js#2638]
Hi, my problem is on the pagination inside the horizontal slider. The points are delayed with respect to the transition of the slide.
You can see it in the first section of my website:
http://aenimalab.com.ar/dupont/ligate-2017/landing/
I hope I have been explicit.
Greetings.

**Comment by alvarotrigo** [comment]
The bullets get the activation class when the fading effect finishes, which depends on the `scrollingSpeed` option.
This can be seen acting in the same way in the [Fading Effect demo page](http://alvarotrigo.com/fullPage/extensions/fading-effect.html#firstPage/1)

That's just how it works.

**Comment by alvarotrigo** [comment]
If you want to add it before, you might be able to do it using the [`onLeave` callback](https://github.com/alvarotrigo/fullPage.js#onleave-index-nextindex-direction) or the [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs).
