### ISSUE TITLE
Slide in Section

### ISSUE THREAD

**Issue by BekzatJJ** [alvarotrigo/fullPage.js#2640]
### Description
I am trying to make a 3 slides in second section. Following your steps in documentation works perfectly,  
Checking localy (localhost) it works great. But once I deployed it in to my server, slides doesnt work, but the rest of FullPage.js works. It shows all my slides in text view.

p.s. All required js files including css were deployed into my server

### Versions 
Chrome,IE , Safari

**Comment by alvarotrigo** [comment]
Looks like an issue in your side and not in fullPage.js.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by BekzatJJ** [comment]
Any suggestion what it might be ?

**Comment by alvarotrigo** [comment]
No without an isolated reproduction.

**Comment by BekzatJJ** [comment]
Once I run my website from a host, it gives me these errors from console log. Still cant get slider from host, but locally it works.

BTW. These errors are not existed in localhost

Thanks




showError @ jquery.fullPage.js:2921
jquery.fullPage.js:3019 Uncaught TypeError: iScrollInstance.wheelOff is not a function
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:3019)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at Object.create (jquery.fullPage.js:3006)
    at createScrollBar (jquery.fullPage.js:2255)
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:864)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at createScrollBarHandler (jquery.fullPage.js:856)
    at dispatch (jquery.min.js:3)

jquery.fullPage.js:3085 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at Object.remove (jquery.fullPage.js:3085)
    at createScrollBar (jquery.fullPage.js:2260)
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:473)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at reBuild (jquery.fullPage.js:455)
    at jquery.fullPage.js:2100
remove @ jquery.fullPage.js:3085
createScrollBar @ jquery.fullPage.js:2260
(anonymous) @ jquery.fullPage.js:473
each @ jquery.min.js:2
each @ jquery.min.js:2
reBuild @ jquery.fullPage.js:455
(anonymous) @ jquery.fullPage.js:2100

jquery.fullPage.js:3085 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at Object.remove (jquery.fullPage.js:3085)
    at createScrollBar (jquery.fullPage.js:2260)
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:473)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at reBuild (jquery.fullPage.js:455)
    at jquery.fullPage.js:2100

jquery.fullPage.js:3085 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at Object.remove (jquery.fullPage.js:3085)
    at createScrollBar (jquery.fullPage.js:2260)
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:473)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at reBuild (jquery.fullPage.js:455)
    at jquery.fullPage.js:2100
remove @ jquery.fullPage.js:3085
createScrollBar @ jquery.fullPage.js:2260
(anonymous) @ jquery.fullPage.js:473
each @ jquery.min.js:2
each @ jquery.min.js:2
reBuild @ jquery.fullPage.js:455
(anonymous) @ jquery.fullPage.js:2100

jquery.fullPage.js:3085 Uncaught TypeError: Cannot read property 'destroy' of undefined
    at Object.remove (jquery.fullPage.js:3085)
    at createScrollBar (jquery.fullPage.js:2260)
    at HTMLDivElement.<anonymous> (jquery.fullPage.js:473)
    at Function.each (jquery.min.js:2)
    at init.each (jquery.min.js:2)
    at reBuild (jquery.fullPage.js:455)
    at jquery.fullPage.js:2100

**Comment by alvarotrigo** [comment]
Isolated reproduction required.

**Comment by BekzatJJ** [comment]
can I give a link to my web-site?

**Comment by BekzatJJ** [comment]
codeandrun.in

**Comment by alvarotrigo** [comment]
You are including things multiple times... and that's wrong:

```html
	
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
		<script  src="js/jquery.fullPage.min.js"></script>
	<script  src="js/jquery.fullPage.js"></script>
	<script  src="js/scrolloverflow.min.js"></script>
	<script  src="js/scrolloverflow.js"></script>

```

And as detailed in the js console...

> fullPage: fullpage.js extensions require jquery.fullpage.extensions.min.js file instead of the usual jquery.fullpage.js. Requested: resetSliders

Read [how to use fullPage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions)

**Comment by BekzatJJ** [comment]
I have changed everything u told me 
Still slider didnt work on host 
I did everything, I posted all required files to my server. 
But still not working 

This is on localhost ( works fine ) 
![](http://i.imgur.com/7F0A4cT.jpg)

But this is how it shows on web site after deploying
![](http://i.imgur.com/oAjaKYt.jpg)

So tired 😐😐😐

**Comment by BekzatJJ** [comment]
All other features like scrollOverflow etc. are working fine!!!

**Comment by alvarotrigo** [comment]
You should read the docs more carefully...

> scrollOverflow: (default false) (not compatible with IE 8) defines whether or not to create a scroll for the section/slide in case its content is bigger than the height of it. When set to true, your content will be wrapped by the plugin. Consider using delegation or load your other scripts in the afterRender callback. In case of setting it to true, it requires the vendor library scrolloverflow.min.js and **it should be loaded before the fullPage.js plugin. For example:**
```html
<script type="text/javascript" src="vendors/scrolloverflow.min.js"></script>
<script type="text/javascript" src="jquery.fullPage.js"></script>
```

**Comment by BekzatJJ** [comment]
Also tried 
Didnt work

**Comment by alvarotrigo** [comment]
What is not working? No errors in console now.

**Comment by BekzatJJ** [comment]
The slider in section two doesnt work
It works only in localhost

**Comment by BekzatJJ** [comment]
![687474703a2f2f692e696d6775722e636f6d2f6f416a614b59742e6a7067](https://cloud.githubusercontent.com/assets/25384029/24681545/4d60857a-19c8-11e7-890a-b5d255a48842.jpg)

This all texts should be separated as slides, but it gave me everything in one page

supposed to be like this:
![687474703a2f2f692e696d6775722e636f6d2f374630413463542e6a7067](https://cloud.githubusercontent.com/assets/25384029/24681590/7bba1184-19c8-11e7-89c1-bde7978fb832.jpg)

**Comment by alvarotrigo** [comment]
Your server is not serving the CSS file:
http://codeandrun.in/jquery.fullPage.css

**Comment by BekzatJJ** [comment]
Wow, 
Thanks it worked 

I changed the link to CDN, everything is working!!! 

By the way great plugin, thank you!

**Comment by deucemac** [comment]
Hey @alvarotrigo, I tried deploying deploying my website using surge, but fullpage wasn't deployed along with the rest of my html, css, and js.  Is this b/c I need a license? If so, I have no problem buying one.  Thank you.

**Comment by alvarotrigo** [comment]
> I tried deploying deploying my website using surge

I have no idea what surge is, but no, the reason is not the license key, that's for sure :)

**Comment by deucemac** [comment]
Surge is just a way to deploy static front-end websites. It works on my
local machine, but the all the style and js modules disappear in
deployment.  It works perfectly on my local machine, but the console tells
me that I need a licenseKey.

**Comment by alvarotrigo** [comment]
I'm afraid the problem is on the deployment process, not in fullpage.js.
