### ISSUE TITLE
Webpack2 Support

### ISSUE THREAD

**Issue by Spittal** [alvarotrigo/fullPage.js#2641]
I've taken some time to look around and experiment with Fullpage and webpack 2.

The way in webpack1 to get the library to work was to follow this pattern

```javascript
import $ from 'jquery';
import 'fullpage.js/dist/jquery.fullPage.js';

document.addEventListener('DOMContentLoaded', () => {
  $('.slides').fullPage();
});
```

This however doesn't work now and results in this error

```javascript
(0 , _jquery2.default)(...).fullPage is not a function
```

I'm wondering if there will be support for importing this with Webpack. Thanks!

**Comment by Spittal** [comment]
I'm not proud to admit this. But it's because I camel-cased `fullpage` to be `fullPage`

**Comment by alvarotrigo** [comment]
> I'm not proud to admit this.

:)
