### ISSUE TITLE
Section with scrolloverflow and fixed div

### ISSUE THREAD

**Issue by SlavisPL** [alvarotrigo/fullPage.js#2642]
Hi,
I am trying to create page with this plugin. I have section with scrolloverflow and I like to set position fixed of one div. If I set it with css and position fixed it does not work. How to make it? Plugin works well apart from this aspect.

Thanks for help.

**Comment by alvarotrigo** [comment]
Place it outside the fullpage.js wrapper. Fixed positions won't work well with translate3d transformations, which are used by fullPage.js to scroll.
