### ISSUE TITLE
Add the next section data-color to the <body> class like data-anchor

### ISSUE THREAD

**Issue by chillside** [alvarotrigo/fullPage.js#2643]
### Description

```
<div id="fullpage">
  <div class="section" data-anchor="header" data-color="white">1 section</div>
  <div class="section" data-anchor="aboutus" data-color="dark">2 section</div>
  <div class="section" data-anchor="footer" >3 section</div>
</div>
```
If i scroll to 2 section, i want add class "dark" to body tag & remove class "white". 

Tnx!

**Comment by alvarotrigo** [comment]
> If i scroll to 2 section, i want add class "dark" to body tag & remove class "white".

Use jQuery or Javascript within fullPage.js callbacks. See the examples provided in the docs to see how callbacks work.
