### ISSUE TITLE
Mobile link and input event issue

### ISSUE THREAD

**Issue by dikyarifb** [alvarotrigo/fullPage.js#2645]
### Description
heey, so I just use this plugin for my web and when I use autoScrolling:false on mobile , the element inside wrapper doesnt work. can someone help this issue?

I had search every issue that related to this, but no luck for me
here is the js opening for my mobile

$('.main').fullpage({
	              autoScrolling:false,
	              anchors: ['about', 'process', 'location', 'contact'],
	              menu: '#menu',
	              });

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
