### ISSUE TITLE
Parallax Extension and overflow content

### ISSUE THREAD

**Issue by fedeweb** [alvarotrigo/fullPage.js#2646]
Hi,

I've just bought the parallax extension and it works well except on section where there is scrollable content.

I have this code:

```
<div class="section">
  <div class="fp-bg"></div>
  <div class="gallery">....</div>
</div>
```

The gallery exceed the height of the viewport and as you can see in the screenshot the background image doesn't cover all the section.

I'd like to achieve the same effect you can see [here](http://residente.com/). So when you reach the end of the gallery, you mantain the parallax effect when you go to the next section.

I hope everything is clear.

Best regards,

Federico

![screenshot](https://cloud.githubusercontent.com/assets/3769215/24875591/e1f4840c-1e28-11e7-89e7-ef8cdb6d138b.jpg)

**Comment by alvarotrigo** [comment]
Please [contact me](http://alvarotrigo.com/#contact) with a link to the reproduction of the issue.

**Comment by fedeweb** [comment]
HI Alvaro, just sent an email. 

Thanks so much, 

Federico
