### ISSUE TITLE
scroll Horizontal and fading effect

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2648]
Hi @alvarotrigo  We are using scrollhorizontal extension js, we want to use fading effect for horizontascrolll to, we can use both extension?

**Comment by alvarotrigo** [comment]
Sure. They are compatible.

**Comment by cvaraj** [comment]
both scrollhorizontal and vertical scroll will work?

**Comment by alvarotrigo** [comment]
Yeah.

**Comment by cvaraj** [comment]
ok thank you @alvarotrigo
