### ISSUE TITLE
iscroll hide absolute divs

### ISSUE THREAD

**Issue by pepi3** [alvarotrigo/fullPage.js#2649]
Hi,
please, can you help me with little problem?
When I scroll to second section, arrows on the right bottom show after animation. 
![image](https://cloud.githubusercontent.com/assets/27361425/24971192/542707e0-1fb7-11e7-9cb7-78b28422fd89.png)
Below in this section are second arrows, which not displayed at all, but when you use inspect tool, they are there
![image](https://cloud.githubusercontent.com/assets/27361425/24971232/881552c8-1fb7-11e7-8a80-cde3c77fc5ea.png)
And i need to display this arrows constantly
[Here is page](http://test.spoj.se/)

Thank for your help and sorry for my english :)

**Comment by alvarotrigo** [comment]
I'm afraid that's not a fullPage.js issue. Probably related with iScroll.js (used when using scrollOverflow:true) and with its use of translate3d.
