### ISSUE TITLE
Two Critical Issues About Scrolling

### ISSUE THREAD

**Issue by mofizul21** [alvarotrigo/fullPage.js#2650]
Two Critical Issues in FullPage JS

**Issue 1:** Please open the site at first- http://themepack.net/aaa/noar 

If you click here- http://prntscr.com/evzh2k you'll go to the second section. Now if you open 'Inspect Element' you'll see that some class added to the first section- http://prntscr.com/evzi3g And you'll not able to scroll the first section before reloading the page.

**Issue 2:** Now go to the second section, please. Here have a slider on the right side with bullet point controller- http://prntscr.com/ew0s7v Now if you go to the third section there have also a slider. But the third section slider isn't working. Also, if you change the image height 'vh' to '%'- http://prntscr.com/ew0y5e , it overlapping the next section.

Has there any way to fix it?

**Comment by alvarotrigo** [comment]
Issue 1: please provide an isolated reproduction in jsfiddle or codepen as detailed in the reporting issues guidelines.

Issue 2: `carousel-indicators` element is not created by fullpage.js and not its responsability. 

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by mofizul21** [comment]
I've added re-production code here- https://jsfiddle.net/ThemePackNet/fLL8rz1s/

You can check it.

**Comment by alvarotrigo** [comment]
You should not be using ` <a href="#section1">Go to </a>` unless you use the `anchors` option.

See the solution here:
http://jsfiddle.net/fLL8rz1s/2/

And do not use the same value for the anchors than for any ID or NAME attribute in the site as detailed in the docs and the JS console.

**Comment by mofizul21** [comment]
Dear Alvarotrigo,

Thanks a lot for giving us the awesome solution. 

Although the carousel isn't part of FullPage, we'll be happy if you can give us a solution. If I use another plugin, the slider is working.

Thanks again.

**Comment by mofizul21** [comment]
Yeah, now the BS slider is working. In the template have 5 sliders. I've used the same id for all. So it was conflicting with each other, I've changed id's for each slider and now it's perfect :)
