### ISSUE TITLE
scrollbar:true breaks position:absolute

### ISSUE THREAD

**Issue by graciolli-f** [alvarotrigo/fullPage.js#2651]
Hi Alvaro, 

Great plugin! 

When I set scrollbar:true, all of my text which are position:absolute inside each section get forced up to the first section. Help?  

I've got autoScrolling set to false.

![image](https://cloud.githubusercontent.com/assets/26588811/25073781/b26b7a78-22a2-11e7-953e-6e469a796972.png)

**Comment by alvarotrigo** [comment]
That's a CSS knowledge question. You should be asking somewhere else. But well, here you go, use this:

```css
.section{
    position:relative;
}
```

**Comment by graciolli-f** [comment]
Thank you. And sorry about the dumb question... still a noob learning what's what.
