### ISSUE TITLE
fullPage inside "frame"

### ISSUE THREAD

**Issue by dioogbento** [alvarotrigo/fullPage.js#2654]
Is it possible to build a fullPage instance not being full window height, as if inside a frame?

Something like:
- Top of browser window
-- White Space
--- Begin fullPage
--- End fullPage
-- White Space
- Bottom of browser window

Thanks.

**Comment by alvarotrigo** [comment]
Not possible. fullpage.js is a full screen library.

**Comment by alvarotrigo** [comment]
The most you can do is making use of `fp-auto-height` for headers and footers as [in this example](http://alvarotrigo.com/fullPage/examples/autoHeight.html).
