### ISSUE TITLE
Click events originating from within scrolling section not triggered on touch devices

### ISSUE THREAD

**Issue by johnfrancismccann** [alvarotrigo/fullPage.js#2655]
@manorepo mentioned this at the bottom of #2333 after it was closed. He reproduced it here in 
jsfiddle: https://jsfiddle.net/manoharkotapati/dq81a2c0/4/

The button inside Section 1 doesn't trigger an alert message. Tested on Chrome and Safari on iPhone 6.

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/2634
Not a fullpgae.js issue but a iScroll.js one.

**Comment by alvarotrigo** [comment]
By the way, changing `<button>` for `<input type="button" />` might solve the issue.
