### ISSUE TITLE
Critical Display:Table and Bottom:0 Issues

### ISSUE THREAD

**Issue by mofizul21** [alvarotrigo/fullPage.js#2656]
Thanks fro your time to make the plugin. I've found two issues in `.fp-section.fp-table, .fp-slide.fp-table` class.

Please see the site at first- http://themepack.net/aaa/noar/

**Issue 1:**
1. If you go to the 2nd second you'll see here have space- http://prntscr.com/exp9fk 
2. Now scroll down to next(3rd) section, please 
3. And again scroll top to 2nd section, you'll see that there have no space- http://prntscr.com/exp9yr
4. Now open 'Inspect Element' and uncheck the display: table- http://prntscr.com/expai0
5. Again go to 1st section → scroll down to 3rd section → scroll top to 2nd section and **you'll see the space.** - http://prntscr.com/expb6v

I need to show space there. I can make `.fp-section.fp-table, .fp-slide.fp-table{display: inherit;}` but I think it's not efficient way. Has there any way to fix it?

**Issue 2:** 

The bottom arrow icon-http://prntscr.com/expemm working in the external HTML file. But when I integrate FullPage JS it's not working.

I've make reproduction code here- https://jsfiddle.net/ThemePackNet/f5mbukac/ Not sure it'll work for you or not.

Hope that you'll help me to find out the problem.

Regards,
Mofizul

**Comment by alvarotrigo** [comment]
As detailed in the issue skeleton:

>  links to personal websites won't be reviewed unless isolated

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

An isolated reproduction implies using the less minium code. Your jsfiddle contains bootstrap and plenty of HTML and CSS.
