### ISSUE TITLE
Parallax and interlockedSlides extensions

### ISSUE THREAD

**Issue by tschortsch22** [alvarotrigo/fullPage.js#2657]
### Description 
Parallax backgrounds are only shown halfway through on slides (see screenshots attached below) when using interlocked slides together with Parallax extension. According to whether scrolling slides (horizontally) or sections (vertically) the backgrounds are cropped horizontally/vertically.

### Steps to reproduce it
1. create fullPage site with 4 sections and 3 slides in section 2, 3 and 4
2. fp-bg class in section 1 and in the second slide of the other sections
3. appropriate css with path to images
4. interlockedSlides: true, parallax: true
5. images on slides are not shown properly when scrolling through the site

### Versions 
OS X Yosemite 10.11.6
Safari, Chrome, Firefox, Opera latest releases
fullPage.js 2.9.4 + latest extensions releases 

![screenshot-h](https://cloud.githubusercontent.com/assets/10323123/25119723/9ab0e9b6-241b-11e7-835e-96513d7158a9.png)
![screenshot-v](https://cloud.githubusercontent.com/assets/10323123/25119724/9ab1d6e6-241b-11e7-942d-2d42128d219b.png)

**Comment by alvarotrigo** [comment]
Confirmed. That's a bug!
Thanks for reporting it and sorry for the inconvenience!

I'll take a look at it as soon as possible.

**Comment by alvarotrigo** [comment]
Fixed. 
A mail was sent to everybody who bough Interlocked Slides or the Parallax extension notifying them about the new versions that solve this issue.

Parallax 0.0.6
Interlocked Slides 0.0.3

**Comment by tschortsch22** [comment]
Hi Alvaro,
my project consists of 4 sections in total, section 1 without slides, sections 2, 3 and 4 with 3 slides each. I defined the starting point of section 2 to slide 2 rather than the first slide by adding class ".active"! Section 1 and all 2nd slides have a parallax background image. InterlockedSlides and Parallax extensions are set to true. Everything is fine when scrolling down from section 1 to section 2 but on section 3 and 4 I still have the same issue as reported above.

Is this still the same bug or am I doing something wrong with defining the starting point?!

Many thanks in advance!

**Comment by alvarotrigo** [comment]
Are you using `animateAnchor: false` ? Or just the default `true` one?

**Comment by tschortsch22** [comment]
I'm using the default one.

**Comment by alvarotrigo** [comment]
Which is your starting section? 1st ? Or also 2.

**Comment by tschortsch22** [comment]
First section.

**Comment by alvarotrigo** [comment]
@tschortsch22 is the section with the 2nd active slide interlocked with the rest of sections? 
If so, I would expect to see sections 2, 3 and 4 with the 2nd slide active as well?

**Comment by tschortsch22** [comment]
Yes, it is interlocked with the rest of the sections (interlockedSlides: true)! I added active class to the 2nd slide of sections 3 and 4, now it is working! :)
