### ISSUE TITLE
Parallax & Continuous Horizontal Slider Issue

### ISSUE THREAD

**Issue by huwrowlands** [alvarotrigo/fullPage.js#2658]
### Description
I've download and setup the Continuous Horizontal extension and the Parallax extension and installed in a dev site, within a slider area. I am not using the Parallax extension on any other section/s.
Without Parallax, the slider works fine. With 'loopHorizontal' set to false, the slider works fine.

When 'loopHorizontal' is set to true though, I'm getting an issue with the slider background images. I believe it has something to do with the transform css on [.fp-bg](url).
It states that on the first slide, second time around, `transform : translate3d(1005px, 0px, 0px)`; which I believe should go back to `transform : translate3d(0px, 0px, 0px)` ?

### Link to isolated reproduction with no external CSS / JS
Am I ok to send you a link to the dev version of the website? If not, how would I go about using my licence keys within codepen.io?
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. Setup 4 sections, final section is a slider
2. add Continuous Horizontal and Parallax extensions
3. Slide through the slides, from the second time around, the issue of the website background is appearing because the slide background image isn't moving into the viewport enough. (possible transform css issue?)

### Versions 
Chrome Version 57.0.2987.133 (64-bit)
macOs Sierra 10.12.4
iMac

**Comment by alvarotrigo** [comment]
> Am I ok to send you a link to the dev version of the website? If not, how would I go about using my licence keys within codepen.io?

Pleas [contact me](http://alvarotrigo.com/#contact) and send me a link to your site. I'll investigate it. 
Make sure you are using the latest fullPage.js version as well as the latest extensions versions.

**Comment by huwrowlands** [comment]
Sent. Many thanks

**Comment by alvarotrigo** [comment]
The issue was solved by updating to the latest Continuous Horizontal extension version. 0.0.4
