### ISSUE TITLE
mouse click and drag works in chrome and not in firefox

### ISSUE THREAD

**Issue by jyothishpg** [alvarotrigo/fullPage.js#2659]
In chrome drag and scroll option working, but in fire fox its not working, i want to block drag and scroll option in chrome, im using  scrollOverflow: true, need a quick reply, im stuck
in firefox its working fine, is there any solution to fix it,

**Comment by alvarotrigo** [comment]
You can read in [the demo page](http://alvarotrigo.com/fullPage/extensions/drag-and-move.html#secondPage):

> Sections/slides with scrollOverflow:true or any scrollable element won't be scrolled by dragging, only by mouse wheel.

**Comment by alvarotrigo** [comment]
There's also a Javascript warning in the JS console saying:

> fullPage: The option `scrollOverflow` is not fully compatible with `dragAndDrop`; Scrolling sections/slides will not work when dragging
