### ISSUE TITLE
suue in chrome and firefox

### ISSUE THREAD

**Issue by jyothishpg** [alvarotrigo/fullPage.js#2660]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
No data or description was provided.
