### ISSUE TITLE
continuous scroll direction at loop shows returns wrong direction

### ISSUE THREAD

**Issue by tokuz** [alvarotrigo/fullPage.js#2662]
Hi,

I use the continuous scroll plugin, and have to call some functions depending on the direction of  onSlideLeave. If the slides reach the loop it returns the wrong direction. Both directions return the same direction. On the first slide right/right and on the last frame left/left.

Is this a bug, or am i doing something wrong?

**Comment by alvarotrigo** [comment]
Yeap, that's a known "bug". 
You can meanwhile guess the real direction by using the last parameter in the `onLeave` callback, the `nextSlideIndex` one.

```javascript
onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex) {
    var realDirection = direction;
    if (slideIndex === $(this).siblings().length && !nextSlideIndex) {
        realDirection = 'right';
    }
    if (!slideIndex && nextSlideIndex === $(this).siblings().length) {
        realDirection = 'left';
    }
    console.warn(realDirection);
}
```

**Comment by alvarotrigo** [comment]
Fixed on the dev branch. Will get merged in fullpage.js 2.9.5.
