### ISSUE TITLE
"normalScrollElements" option does not affect touch events in iframes

### ISSUE THREAD

**Issue by toulatip8** [alvarotrigo/fullPage.js#2664]
Good day / evening,

while employing the library in an internal company project I noticed that the "normalScrollElements" option does not comprehend touch events, and only disables mouse scroll.

I locally edited the library to add the support.

- Library version: 2.9.4.
- Edited files: jquery.fullPage.js [lines 604 to 620]

```
/**
* Applying normalScroll elements.
* Ignoring the scrolls over the specified selectors.
*/
if(options.normalScrollElements){
    $document.on('mouseenter touchstart', options.normalScrollElements, function () {
        //setMouseWheelScrolling(false);
        setAllowScrolling(false);
    });

    $document.on('mouseleave touchend', options.normalScrollElements, function(){
        //setMouseWheelScrolling(true);
        setAllowScrolling(true);
    });
}
```

In case I missed a more general option that cared also for touch events, I deeply apologize.

Best Regards,

Leo

**Comment by alvarotrigo** [comment]
Thanks for that! But it [does work for touch events too](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1103). Just make sure you use a height `normalScrollElementTouchThreshold` if you need to. 

I'll close the issue until an isolated reproduction proving your point is provided.

**Comment by toulatip8** [comment]
Thank you for the feedback!

I noticed that it heavily depends on the `normalScrollElementTouchThreshold` option.

I reproduced the issue in a fork of a fiddle I found in one of your other replies, it should work with `normalScrollElementTouchThreshold` set to 3 or 5 (which may be too small, afterall). 

http://jsfiddle.net/gou4q9r8/18/

I tested the fiddle using  the responsive mobile view in Google Chrome, which for my issue gave me the same results as on mobile. You should be able to see that, while panning upwards on the Map, the view scrolls to the next session.

**Comment by alvarotrigo** [comment]
Yeap, definetely fails with iframes as they do not propagate touch events within them. But if you attach the `touchstart` and `touchend` events to the iframe itself, then that will do it! 

Thanks for the suggestion! Feel free to provide a pull request in the `dev` branch and I'll merge it!

**Comment by toulatip8** [comment]
Oh that's why! You're definitely right!
You're welcome, I've submitted a PR, but I'm new to PR submissions, I may have fumbled somewhere (apologies beforehand).

Best,

Leo
