### ISSUE TITLE
scrollHorizontall Unlicensed fullPage.js Extension issue

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2666]
**Unlicensed fullPage.js Extension** its showing me @alvarotrigo, we bought this plugin but we are getting this issue

**Comment by alvarotrigo** [comment]
Read [how to use the extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).
And [how to get the activation key](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension)

Notice the following:

> Access the URL **that was sent to your email address when purchasing the extension.**

**Comment by craigb88** [comment]
I'm facing the same issue. 
I have followed the docs and made sure my activation key is correctly used. I've registered the domain name but still getting the **Unlicensed fullPage.js Extension** alert. 
I have no errors in my console.

**Comment by alvarotrigo** [comment]
@craigb88 you are very probably missing something or doing something wrong. 
Please [contact me](https://alvarotrigo.com/#contact) with a link to your site.
