### ISSUE TITLE
Faceing problem in internet explorer on last section

### ISSUE THREAD

**Issue by swaranan** [alvarotrigo/fullPage.js#2668]
### Description
Having problem o on scrolling last section only on Internet Explorer, on Chrome and Firefox all is good..I am using Internet Explorer 11. 
its on a wordpress website.
### Link to isolated reproduction with no external CSS / JS
As its a word press website so i can't add codepen or js fiddle ..
Here is the link: 
http://demo.mejorainfotech.com/dev/options-wp
http://optionsenegal.com

![options3](https://cloud.githubusercontent.com/assets/5773809/25237829/5962900a-2609-11e7-9f60-228100db863e.png)

### Steps to reproduce it
1. Just scroll
2. on the last section Footer

### Versions 
IE11, Windows 7, fullpage.js: "^2.9.4",

### Script used
```
$('#fullpage').fullpage({
            anchors: ["slide1", "slide2", "slide3", "slide4", "slide5", "slide6", "slide7", "slide8"],
            sectionsColor: ['#fff', '#fff', '#fff', '#e96421', '#fff', '#fff', '#fff', '#fff'],
            menu: '#menu',
            lockAnchors: false,
            scrollOverflow: false,
            responsiveWidth: 990,
            afterLoad: function (anchorLink, index) {
                var loadedSection = $(this);

                if (index == 1) {
                    $('.go-top').hide();
                    $('header').removeClass('stuck');
                }
                if (index !== 1) {
                }
            },
            onLeave: function (index, nextIndex, direction) {
                var leavingSection = $(this);

                //after leaving section 2
                if (index == 1 && direction == 'down') {
                    $('header').addClass('stuck');
                    $('.go-top').show(400);
                } else if (index == 2 && direction == 'up') {
                    $('header').removeClass('stuck');

                }
            }
        });
```

**Comment by alvarotrigo** [comment]
Sorry but I can not inspect the fullPage.js CSS or JS files.
It seems you are using some .scss file for the fullpage.js that doesn't belong to fullpage.js ? 

Please place all fullPage.js files separated from any others so I can investigate the issue. And ideally, get rid of any external CSS or JS files to fullPage.js.

**Comment by swaranan** [comment]
Yes i am using .scss version..ok will place all fullPage.js files separated

**Comment by alvarotrigo** [comment]
> Yes i am using .scss version..ok will place all fullPage.js files separated

I don't know where you got it from, but fullPage.js doesn't provide any `scss` version.

**Comment by swaranan** [comment]
yes. full page js doesn't provide .scss version.. But as my work was on .scss , I converted your css to .scss from here : http://css2sass.herokuapp.com/..
will change it to css also will add fullpage.js js seperatly , tomorrow, so you can inspect from there..

**Comment by swaranan** [comment]
Hi, i have uploaded fullpage.css and jquery.fullpage.min.js seperatly.. Now you can inspect on : http://demo.mejorainfotech.com/dev/options-wp

Please let me know...

**Comment by swaranan** [comment]
HI.. I got it.. The problem is for the recaptcha.. It adding a div under the footer section thats why it's scrolling weird on the footer section.. Thank you for your time and the beautiful FullpageJS...
