### ISSUE TITLE
Parallax Extension Bug with settings verticalCentered:false, autoScrolling: false,

### ISSUE THREAD

**Issue by simpas810** [alvarotrigo/fullPage.js#2669]
### Fullpage Parallax Extension is not working with settings verticalCentered:false, autoScrolling: false,

Considering the HTML code suggested in the documentation with settings: **verticalCentered:false,** **autoScrolling: false** the scenario is broken.

### Steps to reproduce it

JS installed:

fullpage.parallax.min.js
fullpage.scrollHorizontally.min.js
jquery.fullpage.extensions.min.js

JS code:

jQuery('#slider').fullpage({
	parallax: true,
	parallaxKey: '..............',
	parallaxOptions: {
			type: 'reveal',
			percentage: 62,
			property: 'translate'
        },
	verticalCentered:false,
	autoScrolling: false
});

### Versions 
[Parallax Extesion 0.0.4]

**Comment by alvarotrigo** [comment]
Please update to parallax 0.0.5 or 0.0.6.
You got a mail about it in the email address used for the purchase.
