### ISSUE TITLE
Automatically pause vimeo playback on pagescroll?

### ISSUE THREAD

**Issue by ghovatter** [alvarotrigo/fullPage.js#2671]
Hello, 
After reading through the documentation I read that videos should be auto-pausing when the user scrolls to the next page although it is not working for me. Am I missing something?

I am using the iframe embed options on vimeo to play the videos.

**Comment by alvarotrigo** [comment]
From the docs:

> Embedded HTML5 <video> / <audio> and Youtube iframes are automatically paused when you navigate away from a section or slide. 

Notice no vimeo videos are mentioned. 
This is because vimeo requires the inclusion of a JS file in order to use its API.
