### ISSUE TITLE
Not scrolling on touch device with jQuery Slim 3.1.1

### ISSUE THREAD

**Issue by jessekinsman** [alvarotrigo/fullPage.js#2672]
Scroll does not function at all (sometimes it works but always scrolls up) on touch device in Chrome or Firefox.

Not able to move to next or previous slide with any type of swipe.

Here is a reproduction of the issue on jsFiddle
https://jsfiddle.net/jessekinsman/ju5pn1tL/

This only appears to be a problem on touch devices

### Steps to reproduce it
Load the following fiddle
https://jsfiddle.net/jessekinsman/ju5pn1tL/

Try to swipe up or down with any of the jQuery slim versions. Screen does not change.
This may not be a bug but perhaps an incompatibility with the slim versions of jQuery

### Versions 
Fullpage.js 2.9.4
jQuery Slim 3.0.0, 3.1.0, 3.1.1 (note 3.1.1 is required dependance for Bootstrap 4)
IOS 10.3.1
Chrome 
Safari
Didn't test Firefox

**Comment by alvarotrigo** [comment]
Do you experience the same problem on the [demo page](http://alvarotrigo.com/fullPage/)?

**Comment by alvarotrigo** [comment]
I'm afraid fullPage.js does not work with the slim version of jQuery, as effects such as `.stop()` are required by fullPage.js.

**Comment by alvarotrigo** [comment]
I would go for the full jQuery version. It is only 6Kb more :) 
Otherwise, you can try the alpha version of [pure Javascript fullPage.js](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)).

**Comment by jessekinsman** [comment]
Yes that is why I ended up doing.

Just thought I would report it in case you weren't aware, but it sounds
like you are.

 I didn't see it anywhere in the documentation. I believe it says any
jQuery beyond 1.6.
