### ISSUE TITLE
How to click one arrow to next section?

### ISSUE THREAD

**Issue by xuxn** [alvarotrigo/fullPage.js#2673]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Easy:

- Create the arrow
- Assign to it the `moveSectionDown` function.

Check the [`moveSectionDown` docs](https://github.com/alvarotrigo/fullPage.js#movesectiondown) and the [demo](http://codepen.io/alvarotrigo/pen/jPvVZx).
