### ISSUE TITLE
PaddingTop issue when sliding up

### ISSUE THREAD

**Issue by ClemLivy** [alvarotrigo/fullPage.js#2674]
Something doesn't work with paddingTop.

when I load my page everything is fine (see screenshot)
<img width="362" alt="screen shot 2017-04-21 at 6 33 14 pm" src="https://cloud.githubusercontent.com/assets/24570966/25287273/0cacb76e-26c1-11e7-8a20-27fa6e480183.png">

if I scroll down everything is perfect, but when I scroll up the paddingTop doesn't work anymore...
<img width="315" alt="screen shot 2017-04-21 at 6 34 53 pm" src="https://cloud.githubusercontent.com/assets/24570966/25287334/43da8d7e-26c1-11e7-8072-3fd4dd3f9fae.png">

When I look at the HTML, I have in `<div class='fullpage fullpage-wrapper' style= 'transform : translate3d(0px, -177px, 0px);`>
-177 correspond to my (screen height - section height). If I put to 0 in translate3d everything is ok.

Same issue when I go from the footer with fp-auto-height to the upper section. Other sections work well.

Please help...

PS : great plugin!

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by DDYMZL** [comment]
so,what's the solution 😂

**Comment by alvarotrigo** [comment]
@DDYMZL If you provide an isolated reproduction on codepen or jsfiddle we will be able to help you.
