### ISSUE TITLE
autoScrolling: false

### ISSUE THREAD

**Issue by BekzatJJ** [alvarotrigo/fullPage.js#2675]
### Description
The problem is that whenever I set autoscrolling:false, the section are not scrollable, it shows only first section doesnt move at all. But when autoscrolling:true, everything works great.

### Link to isolated reproduction with no external CSS / JS
This link to my website
www.codeandrun.in 

please can you check??? 

### Versions 
all devices

**Comment by alvarotrigo** [comment]
As detailed in the issue skeleton:

> ### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, **links to personal websites won't be reviewed unless isolated**. Reported issues without a reproduction might get closed.]
