### ISSUE TITLE
Menu animation not working

### ISSUE THREAD

**Issue by karoomii** [alvarotrigo/fullPage.js#2676]
I'm creating a horizontal scrolling website. I've hidden the arrows and allow page sliding through only the menu and keyboard. When clicking on an anchor from the menu to take me to another page, there's no animation transition. It just takes me straight to that page. However, when using the keyboard, there's an animation transition. I've tried all I could to fix this but it's not working.

Here's my code:
HTML
```html
<div id="fullpage">	
<ol id="myMenu">
		<li data-menuanchor="home-container"><a href="#home">home</a></li>
		<li data-menuanchor="work-container"><a href="#work">work</a></li>
		<li data-menuanchor="about-container"><a href="#about">about</a></li>
	</ol>
	<div class="section">
		<div data-anchor="home-container" class="slide active" id="home"></div>
		<div data-anchor="work-container" class="slide" id="work"></div>
		<div data-anchor="about-container" class="slide" id="about"></div>
	</div>
	
</div>
```
JS
```javascript
$(document).ready(function(){
		$('#fullpage').fullpage({
			anchors: ['home-container','work-container','about-container'],
			menu: '#myMenu',
			easing: 'easeInOutExpo',
			scrollingSpeed: 1000,
			css3: false,
			controlArrows: false,
			loopHorizontal: false,
			fixedElements: '#menu'
		});
	});
```
I should note that I've added the scripts for jquery, fullpage, scrolloverflow, and jquery.easing, along with the the fullpage.css.

EDIT: how do I show the raw html code? I feel like it's inconvenient for everyone to view it like this.

**Comment by alvarotrigo** [comment]
As detailed in the docs and as reported in your JS console: 

> Be careful! anchors can not have the same value as any ID element on the site (or NAME element for IE).
