### ISSUE TITLE
section bg

### ISSUE THREAD

**Issue by iluhin51** [alvarotrigo/fullPage.js#2677]
HI! how fix this: http://viktorsimakov.ru/#section2
Visit site with width up 1400

**Comment by alvarotrigo** [comment]
Please be more specific with your issue and provide an isolated reproduction of it as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
