### ISSUE TITLE
Named slider navigation

### ISSUE THREAD

**Issue by rolfn** [alvarotrigo/fullPage.js#2679]
It's only a small question. Is it possible to create navigation thru the sliders with named buttons instead of dots or arrows –  similar to the section navigation?

**Comment by alvarotrigo** [comment]
Sure.
Just use the [state classes added by fullPage.js](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [the callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) to create your own nav.

Check [my answer here](http://stackoverflow.com/a/36742906/1081396) as well.

**Comment by rolfn** [comment]
Thank you.
