### ISSUE TITLE
Several different hash urls for one slide?

### ISSUE THREAD

**Issue by psr1919plus21** [alvarotrigo/fullPage.js#2680]
Hi, it's possible to define several different hash urls for one slide?

Example:
markup
```
<div class="container">
    <div class="section section_first"></div>
    <div class="section section_second"></div>
</div>
```

init
```
$('.container').fullpage({
    anchors: ['slide1-1', 'slide1-2', 'slide2-1', 'slide2-2']
});
```

It's possible to make first and second anchors lead to section with class `section_first`
`/#slide1-1`
`/#slide1-2`

and next two anchors to section with class `section_second`?
`/#slide2-1`
`/#slide2-2`

**Comment by alvarotrigo** [comment]
Nop.
A slide can only have one anchor. 
A section can only have one anchor.
