### ISSUE TITLE
Disable scrolling on slides when in a modal

### ISSUE THREAD

**Issue by pim013** [alvarotrigo/fullPage.js#2681]
### Description

Our website consists out of 1 section with 5 slides. So, the website is fully horizontal scroll. 

We have various contact forms in modals. When these modals are open, I want to disable scrolling on the slides because users get confused by it. So far, I've not been able to disable this. Have you encountered this before or maybe know a solution?

Thanks!

**Comment by alvarotrigo** [comment]
Check [setAllowScrolling](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions)

**Comment by pim013** [comment]
Wow, such a quick answer. Solved my problem perfectly. Thanks so much!
