### ISSUE TITLE
Issue with slick slider

### ISSUE THREAD

**Issue by shivaninc** [alvarotrigo/fullPage.js#2685]
I'm using fullpage.js on my website www.absorbia.in. I've used the slick slider on the last slide to display testimonials on half the page. But it is not positioning correctly i.e. I would like it to show one testimonial at a time, but it shows half of one and half of the other. How do I correct this?

HTML: 
<div class="section">

            <div class="home-slide-half">
                <div class="half-home-detail">
                    <div class="home-slide" style="background: url(../imgs/testimonial-left-bg.jpg) no-repeat; background-size: cover; height: 100vh;">
                        <h2>HEAR IT DIRECTLY FROM THE SOURCE!</h2>
                        <div class="testimonial-slider">
                            <p>I have been using it all the time. Depends on humidity it can last 30 days or 60 days. I use the pouches for kitchen drawers. In the house, I have it in all cupboards. Depends on size, I have sometimes 1 to 3 pieces. It is a great product to use through out the year.<br>-Glenda Bouzek, Mumbai</p>
                            <p>I am a bags and shoes addict. I travel the world and love to buys bags and shoes, but it was painful to see them rot in Mumbai because of humidity. Absorbia has been a blessing! <br>- Devika Vaid, Mumbai</p>
                            <p>The must smell has gone from my clothes ever since I started using absorbia.<br>- Kabir Grover, Mumbai</p>
                            <p>I have been using Absorbia for 3 months now and I am extremely happy as I don't have to wash my clean clothes again and again.<br>- Meeta, Kolkata</p>
                        </div>
                        <div class="shop-button">
                            <a class="white-button" href="shop.html">SHOP NOW</a>
                        </div>
                    </div>
                </div>
                <div class="half-home-detail half-left" style="    background: url(../imgs/testimonial-right-bg.jpg); background-size: cover; background-position: bottom right;">
                </div>
            </div>
        </div>

CSS:

.half-home-detail img {
    display: block;
}

.half-home-detail {
    width: 50%;
    float: left;
    color: #fff;
}

.half-home-detail p {
    width: 80%;
    margin: 0 auto;
}

.testimonial-slider {
    margin-top: 1.5em;
    padding: 0 3em;
}

.testimonial-slider p {
    margin-bottom: 2em;
    font-size: 1em;
    line-height: 30px;
}

.shop-button {
    margin: 3em 0;
}

.half-left {
    width: 50vw;
    height: 100vh;
}

**Comment by alvarotrigo** [comment]
Not a fullpage.js issue I'm afraid. 
You'd better ask in other place such as stackoverflow.com where they'll be able to help much better.
