### ISSUE TITLE
fullpage javascript

### ISSUE THREAD

**Issue by ramitvakil** [alvarotrigo/fullPage.js#2686]
### Description
Hi,
Wanted to know how to call the destroy method in the javascript version.

**Comment by alvarotrigo** [comment]
I'm afraid there's no such method in the Javascript version.

**Comment by ramitvakil** [comment]
Actually when i am trying to use the plugin with polymerjs on navigation the scope of fullpagejs is not getting destroyed and because of the keyboard key actions still active the code is not working as expected. Any workaround for that?

**Comment by alvarotrigo** [comment]
> Any workaround for that?

Yeah, use the jQuery version :)

**Comment by ramitvakil** [comment]
Thanks :)
