### ISSUE TITLE
Is it possible to move to next section when reaching bottom of scrollable div inside of a section?

### ISSUE THREAD

**Issue by tenold** [alvarotrigo/fullPage.js#2690]
Not really a bug but just asking if this is possible.

I have a scrollable area within a full page section using `normalScrollElements: '.scrollable'`.

When I'm in a section that has a `.scrollable` div, and I get to the bottom of that scrollable div, I would expect it to move onto the next section once the bottom is hit, but it doesn't. Is there a way to force it to move to the next section once this happens?

**Comment by alvarotrigo** [comment]
Many things are possible with the right knowledge. 
You will have to make use of the fullpage.js function `moveSectionDown` or `moveSectionUp`. How you do it and how you detect the scroll top or bottom of your element is up to you.

**Comment by tenold** [comment]
Cool, I know how to do it through writing my own Javascript, but was just making sure I didn't miss some built in function for this.

Thanks!

**Comment by alvarotrigo** [comment]
The most similar thing you have is the `scrollOverflow` option that you can see [in this example](http://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by tenold** [comment]
In case anyone else has this question, here's what I did:

```javascript
$('.scrollable').on('scroll', function() {
    if($(this).scrollTop() + $(this).innerHeight() >= $(this)[0].scrollHeight) {
      // Reached Bottom
      $.fn.fullpage.moveSectionDown();
      $.fn.fullpage.setAllowScrolling(true);    
    } else if ($(this).scrollTop() == 0) {
      // Reached Top
      $.fn.fullpage.moveSectionUp();	    
      $.fn.fullpage.setAllowScrolling(true); 
    }
  });
```

I had to add `$.fn.fullpage.setAllowScrolling(true)` because for some reason when I triggered `$.fn.fullpage.moveSectionDown()` or `$.fn.fullpage.moveSectionUp()` and didn't move move my mouse, scrolling was broken for subsequent sections until I moved my mouse and scrolled again. Not sure if this is a bug or what, but adding `$.fn.fullpage.setAllowScrolling(true)` seemed to fix it for me.
