### ISSUE TITLE
Modal does not scroll on touch devices

### ISSUE THREAD

**Issue by pim013** [alvarotrigo/fullPage.js#2694]
### Description

In Safari & Chrome Webdev Tools both modals are scrollable. On touch devices however, neither modals are scrollable. 
Link: http://djbus.nl/ 
For modal click on button 'Boek nu'.

**Comment by alvarotrigo** [comment]
I don't know how you are making them scrollable, but you should be using the fullpage.js option `normalScrollElements.`
Read more about it in [the docs](https://github.com/alvarotrigo/fullPage.js).

**Comment by pim013** [comment]
I don't want to avoid scrolling so I'm afraid that option doesn't solve the problem for me.
We've made the modals (.booking-request and .contact-form) scrollable by adding `overflow: scroll` to the divs. This works on desktop width, mobile width on desktop but not on actual touch devices. Do you have any idea why this is?

**Comment by alvarotrigo** [comment]
As I said, you need to make use of `normalScrollElements` if you want those elements to be scrolled normally without interfering with fullPage.js scroll. 

Alternatively you can make use of the function `$.fn.setAllowScrolling(false)` to diable fullPage.js scroll and therefore enable only the inner scrolling in those elements.

**Comment by pim013** [comment]
http://djbus.nl/wp-content/themes/djbus/js/main.js?ver=4.7.4

Can you please take a look at our JS? We've defined the `normalscrollelements`at line 46.
We also have used your alternative method, for example at lines 105-109 and 111-115. 

Unfortunately it doesn't work..

**Comment by alvarotrigo** [comment]
Use a higher `normalScrollElementTouchThreshold`, or use the [dev version of fullPage.js](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js) which fixes a related issue as per https://github.com/alvarotrigo/fullPage.js/pull/2691

**Comment by pim013** [comment]
Thanks for the help, got it working now.

**Comment by thewebua** [comment]
I have the 2nd one to combine this scroll, and bootstrap 3, burn in hell developer!

**Comment by thewebua** [comment]
Kick your self! WTF, who writes this shit?
