### ISSUE TITLE
IE page scrolls two pages instead of one

### ISSUE THREAD

**Issue by lucasjohnson** [alvarotrigo/fullPage.js#2695]
### Description
I'm noticing that when I scroll the window advances two pages down, rather than just one. I can replicate this bug on the homepage.

### Link to isolated reproduction with no external CSS / JS
http://realbadrabbits.com/projects/fullpage/index.html

### Versions 
macOS running Virtual Box running Windows 7 IE 10/11/Edge
Also on native Windows 7 machine

**Comment by alvarotrigo** [comment]
I suspect it is a problem of using an emulator such as Virtual Box instead of a real device. 
The mouse wheel events might be received with delay causing the issue. 

I would say this is not something you have to worry about in native windows devices. Also, consider native windows devices won't probably use kinetic scrolling ( the one provided in Mac trackpads)

**Comment by lucasjohnson** [comment]
Thank you for the reply. This is what I was thinking also. I'll be testing more extensively on a windows machine in the coming week so I'll let you if this bug persists. Thank for the great plugin!

**Comment by formdigital** [comment]
Hi,

Hope you can help, im having the same issue with my clients site [ https://warriorsstudio.com/work/mungos-hi-fi ].

Any ideas on the issue on our end at all, any help would be much appreciated.

The issue only appears to be causing the issue on Chrome and Safari [ other browsers are fine ]

Many thanks

**Comment by alvarotrigo** [comment]
> Hope you can help, im having the same issue with my clients site [ https://warriorsstudio.com/work/mungos-hi-fi ].

Unfortunately we do not cover specific sites support here.
For that, you'll need to acquire a Business license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>.

If you believe this is a bug in fullpgae.js, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
