### ISSUE TITLE
How to disable the autoscroll when reaching a certain anchor

### ISSUE THREAD

**Issue by pacman1713** [alvarotrigo/fullPage.js#2696]
Hi,
thanks for the great plugin!

I have a website that has 4 vertical sections that scroll with the plugin, and everything works perfectly.
After those section, there are other sections, but i want to stop the autoscroll in order to make them scroll normally.

How can I do it? I thought it could be possible by using the $.fn.fullpage.setAutoScrolling(false); but how?

Thanks,
Andrea

**Comment by alvarotrigo** [comment]
> How can I do it? I thought it could be possible by using the $.fn.fullpage.setAutoScrolling(false); but how?

Make use of the [fullpage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) such as `onLeave` or `afterLoad`. See the demos available in the docs.
