### ISSUE TITLE
Smooth scroll with mouse wheel

### ISSUE THREAD

**Issue by JoeriE** [alvarotrigo/fullPage.js#2699]
Hello,

Is het possible to combine this plugin with a smooth scroll / ease on scroll while using the mouse wheel? Or is this a feature of this plugin?

**Comment by alvarotrigo** [comment]
> Is het possible to combine this plugin with a smooth scroll / ease on scroll while using the mouse wheel?

No idea. Feel free to try yourself.


> Or is this a feature of this plugin?

It is not I'm afraid.
