### ISSUE TITLE
vertical fade as you scroll?

### ISSUE THREAD

**Issue by umarrg97** [alvarotrigo/fullPage.js#2700]
im sure this is possible using this plugin. could i get some advice on this. my current projects slides vertically as you scroll. how do i make it fade? new to this aha

**Comment by alvarotrigo** [comment]
Sure! 
Check out the [Fading Effect extension.](http://alvarotrigo.com/fullPage/extensions/fading-effect.html).

As detailed in the docs:

> fadingEffect: (default false). Extension of fullpage.js. Defines whether to use a fading effect or not instead of the default scrolling one. Possible values are true, false, sections, slides. It can therefore be applied just vertically or horizontally, or to both at the time. Requires fullpage.js >= 2.8.6.

**Comment by umarrg97** [comment]
ive added fadingEffect: 'sections' and its not doing anything?

**Comment by alvarotrigo** [comment]
Have you purchased the extension?

**Comment by stevieburns** [comment]
I'm seeing the same issue  fadingEffect: true, works beautifully 
but I only want my slides to fade
using fadingEffect: 'sections' or fadingEffect: 'slides' has no effect.
I have purchases the extension ... I can send the link privately

**Comment by alvarotrigo** [comment]
@stevieburns please [contact me](https://alvarotrigo.com/#contact) with the URLs.

**Comment by RajBaptla** [comment]
Need - fullPage/extensions/scroll-vertical

**Comment by alvarotrigo** [comment]
@RajBaptla  fullpage.js scrolls vertically by default :)
