### ISSUE TITLE
Table with angularjs doesn't scroll

### ISSUE THREAD

**Issue by abhitechgithub** [alvarotrigo/fullPage.js#2701]
### Fullpagejs plugin doesn't work as expected with ng-repeat

I am using angular to populate data dynamically on last section of fullpagejs. But the scrolling doesn't work even though I set scrollOverFlow as true.

I also tried using jquery.slimscroll it didn't work as well. I also thought of using hybrid: true but it destroyed layout and didn't work properly.

Any help is appreciated

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
I have no idea what `ng-repeat` is I'm afraid :) 
You'd better ask in other angular forum.



> I also tried using jquery.slimscroll it didn't work as well.

fullPage.js uses `scrolloverflow.min.js` now. Slimscroll was removed time ago. Check the docs for more info.

**Comment by alvarotrigo** [comment]
> I also thought of using hybrid: true

`hybrid` is not a released feature and there's no support for it. You won't find it in the docs either.

**Comment by abhitechgithub** [comment]
I have a table on the last section which gets data from an api in my javascript on page load. Since the table is big in size I was wondering if I could get a scroll on the table, but what actually is happening that I see half of the data in table, the other half is hidden.

If I can build a scroll then user could scroll through the data

**Comment by alvarotrigo** [comment]
> I was wondering if I could get a scroll on the table, but what actually is happening that I see half of the data in table, the other half is hidden.

Check the scrolloverflow feature. [Example online.](http://alvarotrigo.com/fullPage/examples/scrolling.html)
You might have to call the fullPage.js method [`reBuild`](https://github.com/alvarotrigo/fullPage.js#rebuild) after the table gets all the data.

**Comment by abhitechgithub** [comment]
I didn't see the reBuild option. Thank you alavrotrigo.
You are really quick.
