### ISSUE TITLE
mobile question

### ISSUE THREAD

**Issue by umarrg97** [alvarotrigo/fullPage.js#2702]
my project is almost complete however on mobile, as i scroll from section to section. some content pops in suddenly. is their any mobile options to turn on in the plugin?

**Comment by alvarotrigo** [comment]
> some content pops in suddenly

What do you mean by that?

> is their any mobile options to turn on in the plugin?

What do you mean by that?

**Comment by umarrg97** [comment]
is there anyway to make it go back to normal scrolling on mobile?

**Comment by alvarotrigo** [comment]
Check the responsive options in the docs. `responsiveWidth` and `responsiveHeight` also the class `fp-auto-height-responsive`. Also check [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples):
-  `responsiveHeight.html` 
- `responsiveWidth.html`
- `responsiveSlides.html`
- `responsiveAutoHeight`.
