### ISSUE TITLE
set allow drag and move

### ISSUE THREAD

**Issue by elliason** [alvarotrigo/fullPage.js#2705]
hello, it is possible to programatically allow or disallow changing slides/sections with drag and move ? Something similar like setAllowScrolling is for mousewheel ?

**Comment by alvarotrigo** [comment]
**Hi elliason.**

Please [contact me](http://alvarotrigo.com/#contact) and let me know the email you used for the purchase.
I'll send you the latest version of the Drag And Move extension that is not yet released but that provides support for `setAllowScrolling`.
