### ISSUE TITLE
fullPage select2 not compatible when using scrollOverflow

### ISSUE THREAD

**Issue by ClemLivy** [alvarotrigo/fullPage.js#2708]
Hi,

fullPage.js is incompatible with select2.js plugin on touch device when scrollOverflow is set to true. The result is that select2 item doesn't respond to touch action. It works well on desktop or when scrollOverflow is set to false.

Any suggestion to fix that?

Many thanks!

Clem

**Comment by ClemLivy** [comment]
It seems to be related to #2035. the select2.js use event with .on('click') or .on('mousedown'). I've tried several conf with scrollOverflowOptions but I always the same results.....

It works with the following procedure:
1. quit iOS safari
2. open it again
3. load my webpage
4. click on my element and it works just one time. If I want to make it work again I have to restart this procedure...

**Comment by alvarotrigo** [comment]
Feel free to report it to iScroll.js issues.
Probably related with https://github.com/cubiq/iscroll/issues/1055

I personally would encourage you to get rid of scrollOverflow and use instead the responsive options combined with the class `fp-auto-height-responsive`. Read the docs for more infor about it or see [this example](http://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html).

**Comment by smplyjr** [comment]
Hi @ClemLivy, can I know how did you solve this issue? I facing the same error right now and it seems like there is no issue in select2 compatibility in iscroll over the internet. Hoping for your response. Thanks
