### ISSUE TITLE
FullPage.js and SmoothState.js Clashes

### ISSUE THREAD

**Issue by BoraALAP** [alvarotrigo/fullPage.js#2709]
The Issue is happening, when I activate the 'autoScrolling: false,'. First page load works fine, however, when I load the second page with SmoothState.js. Fullpage.js stops working and starts throwing this error: 

`jquery.fullPage.js:1053 Uncaught TypeError: Cannot read property 'top' of undefined at isCompletelyInViewPort (jquery.fullPage.js:1053) at scrollHandler (jquery.fullPage.js:967) at dispatch (jquery-2.2.1.min.js:3) at r.handle (jquery-2.2.1.min.js:3)`

my Js file is 
`
$(function(){

  $('#main').fullpage({
    autoScrolling: false,
    fitToSection: true,
    navigation: true,
    navigationPosition: 'left',
    showActiveTooltip: false,
    scrollOverflow: false,
    scrollOverflowReset: false,
    scrollOverflowOptions: null
  }); 
  'use strict';
  var $page = $('#main'),
      options = {
        debug: true,
        prefetch: true,
        cacheLength: 2,
        onStart: {
          duration: 250, // Duration of our animation
          render: function ($container) {
            // Add your CSS animation reversing class
            $container.addClass('is-exiting');
            // Restart your animation
            smoothState.restartCSSAnimations();

          }
        },
        onReady: {
          duration: 0,
          render: function ($container, $newContent) {
            // Remove your CSS animation reversing class
            $container.removeClass('is-exiting');
            // Inject the new content
            $container.html($newContent);
          }
        },
        onAfter:function($container, $newContent) {
                                   
                  console.log("load on after");
              }
      },
      smoothState = $page.smoothState(options).data('smoothState');
});
`
I hope you can find a solution because I really like the both Plugins and I would like to use them together.

Thanks,

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
It doesn't seem to be a fullPage.js issue but an issue related with the wrong use of it.
