### ISSUE TITLE
Slider Onleave callbacks

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2710]
Hi @alvarotrigo 
   can we use slider onleave callbacks, when slider leave to next slider i have to add class how to do this 

Thanks

**Comment by alvarotrigo** [comment]
Read the documentation regarding [fullpage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks).
There you'll find examples in codepen and snipets that will help you understand it.
