### ISSUE TITLE
Scrolling shows delay on Iphone

### ISSUE THREAD

**Issue by yogesh72564** [alvarotrigo/fullPage.js#2711]
Hello Guys,

Thanks for this beautiful plugin. This has really solved a lot of problems for me, However i am stuck on 1 issue. I have seacrhed solution for this for days but couldn't do anything. The issue occurs only in IOS, I have 16 sections in my webpage. But when i am on any of the section and swipe to next section it takes 2 seconds delay before moving to that section. No matter on which section i am, It always takes nearly 2 seconds before it takes any action. Please help me with this. Any kind of help would be appreciable. Btw here is the link to my webpage:-

http://celebrate005s.wpengine.com/summer/canada-150.php

Thanks

**Comment by alvarotrigo** [comment]
I'm not able to reproduce the problem in [the demo page](http://alvarotrigo.com/fullPage/).
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by byura** [comment]
I have same problem with iMac and bluetooth mouse:
https://youtu.be/n_PQSnTrvQc

when i do long scroll on mouse it takes 2 screens, when short - 1 screen

When using other simple wheel mouse  - no problem detected.

/* PageFull.js */
		initPageFull : function(){
			var pageLayout = $( '.layout' );

			pageLayout.fullpage({
				sectionSelector: '.anchor-section',
				navigation: true,
				navigationPosition: 'left',
				scrollingSpeed: 500,

				scrollOverflow: true,
				responsiveWidth: 900,

			});

		}

**Comment by byura** [comment]
Same problem on Macbook with touchpad scrolling

**Comment by byura** [comment]
temporary solution (pause 1 second)

                        var pageLayout = $( '.layout' );
			var lastLeave = new Date();

			pageLayout.fullpage({
				sectionSelector: '.anchor-section',
				navigation: true,
				navigationPosition: 'left',
				scrollingSpeed: 500,

				/* отключает пагинацию при ширине меньше 900 */
				scrollOverflow: true,
				responsiveWidth: 900,

				onLeave: function( index, nextIndex, direction ){
					var now = new Date();
					if( now - lastLeave < 1000 ){
						return false;
					} else {
						lastLeave = now;
					}
				},
			});

**Comment by alvarotrigo** [comment]
It is not recommended to go lower than the default scrolling speed, which is 700.
You are using `scrollingSpeed: 500` and thus the issue. 

Leave it in 700 if you want to avoid problems. There's no proper solution for this due to the lack of proper browser support for kinetic scroll detection.
