### ISSUE TITLE
Slide Tooltip Labels

### ISSUE THREAD

**Issue by MaryWilliameTaraneeChristineCourtney** [alvarotrigo/fullPage.js#2712]
Is it possible to have labels on the Slide Tooltips?

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/176

Short answer: fullPage.js doesn't provide any option for it.
But, you always create your own navigation and through the fullpage.js callbacks of state classes.

Check [this answer](http://stackoverflow.com/a/36742906/1081396)
