### ISSUE TITLE
Smooth scrolling inside section

### ISSUE THREAD

**Issue by pepi3** [alvarotrigo/fullPage.js#2714]
Hi,

please,
when I scroll with mouse scroller, there is "chopped" scroll, but when I drag&drop with mouse there is smooth motion.
https://alvarotrigo.com/fullPage/examples/scrolling.html
Is there a possibility to smooth scroll with mouse scroller? 
For example, like here http://kupnisila.cz/platove-tridy-tabulky/

TY for your reply
Pepi

**Comment by alvarotrigo** [comment]
You would have to check the [iScroll.js docs for it](http://iscrolljs.com/) as the `scrollOverflow` feature makes use of iScroll.js.

I haven't seen any obvious one. In fact [there's people reporting the same in its issues forum](https://github.com/cubiq/iscroll/issues/568).

**Comment by IgorLav** [comment]
Hi, @pepi3! Did you achieve smooth scrolling inside slide section?

**Comment by alvarotrigo** [comment]
> Please tell me if there's any disadvantage using this.

Never tried myself! If it works well for you, then I guess it is fine :)

**Comment by aslam4276** [comment]
> You would have to check the [iScroll.js docs for it](http://iscrolljs.com/) as the `scrollOverflow` feature makes use of iScroll.js.
> 
> I haven't seen any obvious option for it. In fact [there's people reporting the same in its issues forum](https://github.com/cubiq/iscroll/issues/568).
> 
> [Here's another topic](https://github.com/cubiq/iscroll/issues/458).

Hi @alvarotrigo Is there is any way in fullpage js to make scrollable section without using scrollOverflow: true??

**Comment by alvarotrigo** [comment]
> Hi @alvarotrigo Is there is any way in fullpage js to make scrollable section without using scrollOverflow: true??

You've been answered here: https://github.com/alvarotrigo/fullPage.js/issues/4258
