### ISSUE TITLE
Not available prior sections.

### ISSUE THREAD

**Issue by victornewman** [alvarotrigo/fullPage.js#2715]
I use fullpage.js with 6 section start with section0 to section5. When user click one of anchor on menu prior section is not shown. Let's say you click section3 you can see section3-4-5 but if you want to see first 2 section (2 and 0) they are not available. You need to reload page.

Do you have an idea what it can be problem?
thanks

**Comment by alvarotrigo** [comment]
Sounds like you are not following this ? 

> Be careful! anchors can not have the same value as any ID element on the site (or NAME element for IE).

Can't help more without a reproduction. I can not reproduce it in the [demo page](http://alvarotrigo.com/fullPage/).
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
