### ISSUE TITLE
Smooth transition of page height on rebuild

### ISSUE THREAD

**Issue by clintondix** [alvarotrigo/fullPage.js#2718]
I have a quick question about the rebuild method: is there some way for the rebuild method to resize the page in a smooth manner? 

Specifically: I have a bootstrap accordian collapse group, and with scrollOverflow set to true, I can call the rebuild method when one of the collapse groups open and content extends beneath the page. However, when I close that same section, I'm left with two choices. Either I leave the height of the page the same, and accept the extra space beneath, or I call rebuild again. When I do that however, the resize is effectively instantaneous, and the page appears to jump up. Is it possible for that jump to happen slower, so it appears as a smooth transition?

Thank you for your help, and I'm sorry if this isn't the right place for a question like this.

**Comment by alvarotrigo** [comment]
> Is it possible for that jump to happen slower, so it appears as a smooth transition?

If you are talking about removing scrolloverflow in a smooth was, the answer is no.
