### ISSUE TITLE
less than a second shows failed page

### ISSUE THREAD

**Issue by victornewman** [alvarotrigo/fullPage.js#2719]
Hi,
As soon as click index page, browser is opening and for less than a second you see the page without fullpage.js, I mean when browser can not reach fullpage.js file, it shows broken page such as 

"Story 1
 Story 2
 Story 3"

which are normally must be in a page center with slide. As you refresh the page there is no problem so it is look like first time as browser load the page it can not be fast as much as it needs but second time it uses catch and it's okay. On safari it's okay, on android chrome is okay, on IE it's okay. Only desktop version of Chrome I have this isue.

I upload files on internet I had same isue, I use internal js files (for jquery.js) it is still same. There is no error on DOM (Chrome)

Do you have any idea where it can be problem?
Thans in advance

**Comment by alvarotrigo** [comment]
> which are normally must be in a page center with slide. As you refresh the page there is no problem so it is look like first time as browser load the page it can not be fast as much as it needs but second time it uses catch and it's okay.

That's totally normal. Fullpage.js can't modify your HTML markup or apply any classes to it unless you initialise the library. 
So, if you are doing it on page load it will be slower than if you do it on document ready as it is recommended in the documentation and as it can be seen in the examples.

Additionally, you can force the sections to be 100% height by adding this on your own stylesheet:

```css
#fullpage,
.section,
body,
html {
    height: 100%
}
```

That's what I did in the [demo page](http://alvarotrigo.com/fullPage/) so you won't see the flickering  caused when the  library creates 100% sections.
