### ISSUE TITLE
Multiple Fullpage in one Page

### ISSUE THREAD

**Issue by arixv** [alvarotrigo/fullPage.js#2720]
### Description

Hi Alvaro, we are trying to make a webapp using fullpage.js and we want all 'pages' happens in a single html using ajax to display the content, for example, loading a modal with a list of videos, display a right-side panel with an article content. etc, and each one of the pages need to have the fullpage functionality. Is it possible to do this? I saw the massage in the console 'Fullpage.js can only be initialized once and you are doing it multiple times!' but maybe there is a way to accomplish this.

Thank you in advance.

**Comment by alvarotrigo** [comment]
> I saw the massage in the console 'Fullpage.js can only be initialized once and you are doing it multiple times!

You'll have to destroy it with `$.fn.fullpage.destroy('all')` and then initialise it again.

**Comment by arixv** [comment]
That Works perfectly. Thanks

**Comment by guguji5** [comment]
I use this.plugin in my angular webpage . and it logs the "Fullpage.js can only be initialized once and you are doing it multiple times!".

I add the `$.fn.fullpage.destroy()` and it is useless. but the `$.fn.fullpage.destroy('all')` works.

**Comment by alvarotrigo** [comment]
> Where do we type this destroy line, in the console? or in a lifecycle method?

In the JS code :)
