### ISSUE TITLE
 Unlicensed fullPage.js Extension width red box shown [bug help needed]

### ISSUE THREAD

**Issue by AppleAndAngel** [alvarotrigo/fullPage.js#2722]
there's nothing happend when i use localhost open my html but when I  use hbuilder or ip location open it .It show a little red box  fill Unlicensed fullPage.js  Extension in my screen .Bad is it seems dose not work well as before.
I searched this issue whith google but got nothing .I wanner to how to resolve the issue.
Hope someone can understand my barren English.Thanks a lot.

**Comment by AppleAndAngel** [comment]
![image](https://cloud.githubusercontent.com/assets/28129850/26337941/00ddcf8e-3faf-11e7-87bf-61e64239bac1.png)

**Comment by alvarotrigo** [comment]
Please read carefully [how to use extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions) and don't forget to check [how to activate a fullPage.js extension](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension).

A mail was sent to the email you provided on purchase with instructions on how to proceed.
