### ISSUE TITLE
anchor link id issue

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#2723]
when i use anchor link to move another section using id to scroll, its moving but after fullpage scroll is not working, any idea about this. sorry i could not make this clearly.

**Comment by alvarotrigo** [comment]
The docs states:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

**Comment by alvarotrigo** [comment]
And the same applies for any other element in the site. 
You should not use `id` anchors to scroll if your site doesn't have a scroll bar (by using `scrollBar:true` or `autoScrolling:false`.
