### ISSUE TITLE
Isn't there an option yet to disable page/scroll jacking?

### ISSUE THREAD

**Issue by NetworkGreenhouse** [alvarotrigo/fullPage.js#2724]
This would be an amazing plugin if I could control the scroll. If I cannot, it is severely limited. Anyone have any experience with this? or have tried makingv this change?

Thanks!

**Comment by alvarotrigo** [comment]
> This would be an amazing plugin if I could control the scroll.

What about using `scrollBar:true` or `autoScrolling:false`? 
That way you have full control over the scroll.

**Comment by NetworkGreenhouse** [comment]
Thank you! Can I do the same thing with the Page Piling plugin also?... where the content underneath is revealed instead of just stacked on top of each other?

Thanks!

**Comment by alvarotrigo** [comment]
> where the content underneath is revealed instead of just stacked on top of each other?

No. pagePiling.js is a much limited library. 
I would encourage you to take a look at the parallax option with offset:100%. Check [the demo](https://alvarotrigo.com/fullPage/extensions/parallax.html) and set the offset to 100% to kinda emulate pagePiling.js.

Then you can set scrollBar:true in that same demo.

**Comment by NetworkGreenhouse** [comment]
Ah! Looks perfect. I'm going to try it. Thank you for your help alvarotrigo!!
