### ISSUE TITLE
Change dots navegation for Arrow down

### ISSUE THREAD

**Issue by rinkaslb** [alvarotrigo/fullPage.js#2726]
I there Alvaro,

Is it posible to change the dots navigation, for only one Arrow down, always present above the section?

Cheers

**Comment by alvarotrigo** [comment]
Of course. 
Just create your own arrow and assign to it the [`moveSectionDown` method](https://github.com/alvarotrigo/fullPage.js#movesectiondown).

**Comment by rinkaslb** [comment]
Thats' perfect, but wen i'm at the last slide how can i hide button?

**Comment by alvarotrigo** [comment]
That's up to you.
Use [fullpage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to do whatever you want with it.
Regarding the state classes check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M).
