### ISSUE TITLE
Fullpage.js can only be initialized once and you are doing it multiple times!请问怎么解决？？

### ISSUE THREAD

**Issue by xueyuman** [alvarotrigo/fullPage.js#2727]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
That means you are initializing fullpage.js multiple times by calling $('#fullpage').fullPage() in multiple cases. 
Make sure to only do it once.

**Comment by akinhwan** [comment]
hello alvaro what if this is a vue webpack project? I am not calling with jquery anywhere in my vue component files nor in my index.html. The funny thing is I had fullpage working fine, and then it broke recently after messing with trying to publish to gh-pages

**Comment by alvarotrigo** [comment]
> I am not calling with jquery anywhere in my vue component files nor in my index.html. T

LOL that's impossible. fullPage.js requires jQuery at the moment :)
Have you checked the [Vue-fullpage.js component](https://github.com/alvarotrigo/vue-fullpage.js) I created?

**Comment by vishalnarwal99** [comment]
$('#fullpage').fullpage({
    
});
This is the only thing i have typed other than my personal js in my main.js file but i am getting the same error.

**Comment by alvarotrigo** [comment]
@vishalnarwal99 it is impossible to help you unless you provide a reproduction of the issue in a URL. 
Your picture code won't help much.

You might be using some JS framework to create one page sites? That can be one of the reasons. 
No matter what the reason is, you are clearly calling that script  twice.  :)

Try using a `console.log` just there.

**Comment by vishalnarwal99** [comment]
thanks for the help i was calling it in the html>head>script for providing navigation to my sections

**Comment by alvarotrigo** [comment]
Glad it helped!

**Comment by Rustamxon** [comment]
> That means you are initializing fullpage.js multiple times by calling $('#fullpage').fullPage() in multiple cases.
> Make sure to only do it once.

Bro I did it once for all pages. I have 4 pages with your plugin thank you for that your stable plugin helped me. But this problem is not  solved. Giving error.
$('.fullpageBlock').fullpage({
    autoScrolling: true,
    scrollHorizontally: true,
    navigation: true,
    navigationPosition: 'left',
    showActiveTooltip: false,
    scrollingSpeed: 1500,
    onLeave: function (origin, destination, direction) {
      var number = parseInt(destination);

      if (!isNaN(number) && number > 0) {
        $('.bind-btns-to-fullpage span').removeClass('activeFeature');
        $('.bind-btns-to-fullpage span:nth-child(' + number + ')').addClass('activeFeature');
      }
    },

  });
.fullpageBlock this class i gave my all page wrappers. in 4 page. but the same error.
in my pages structure is similar. One structure only content and informations are different. And all pages i called plugin with one .fullpageBlock  class

**Comment by alvarotrigo** [comment]
@Rustamxon if you got that error it is for sure that you are initialicing fullPage.js multiple times :)
You'll have to figure it out yourself as there's no much I can do to help you here. I can only suggest you to see the` plenty of different examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) where you can see how it works as expected.

If you need further assistance consider acquiring the Organization license from the [pricing page](https://alvarotrigo.com/fullPage/pricing/) to get premium support from us.

**Comment by kerwingo** [comment]
You should check if there is a classname called "fp-enabled" on the HTML tag, if you have, delete it!

**Comment by alvingalit** [comment]
> You should check if there is a classname called "fp-enabled" on the HTML tag, if you have, delete it!

I did this and it removed the error, but it still duplicates the lotties.
