### ISSUE TITLE
Session inside slider

### ISSUE THREAD

**Issue by bsantana** [alvarotrigo/fullPage.js#2729]
Hello Alvaro, I am building a system where I will need to call a section inside another section, and also need to call a section inside a slider, would it be possible with your plugin?
In case I would have the section and inside it would call the modal with another section.
It would be a presentation.

I'm sorry if you're asking in the wrong place, I'm new in development and using github!

**Comment by alvarotrigo** [comment]
> would it be possible with your plugin?

Many things are possible with the right knowledge :) But I'm afraid fullPage.js doesn't provide any option to do what you want.
