### ISSUE TITLE
Fullpage.js infinit scrolling horizontal

### ISSUE THREAD

**Issue by SaraKaterji** [alvarotrigo/fullPage.js#2730]
I am using FullPage.js to have sliding effects . I did the following : a section containing 2 slides .

i get the following behavior

slide 1 -> press on next button -> slide 2 -> press on next button -> slide 2 then slide 1

I do not want it to pass by slide 2 before going back to slide 1 , i want it to keep moving right like a flow not right and then at the last slide it goes left alll the way back to slide number 1

how can I fix this ? Please help

**Comment by alvarotrigo** [comment]
Just purchase the [Continuous Horizontal extension](https://alvarotrigo.com/fullPage/extensions/continuous-horizontal.html) and use the `continuousHorizontal` option as detailed in the docs.
