### ISSUE TITLE
issue with section height that has overflow content in slide

### ISSUE THREAD

**Issue by npano** [alvarotrigo/fullPage.js#2731]
I'm using fullpage for a mobile one-page-website in which I have a couple of sections, some of them containing slides. I have an issue with section heights.

Here's the issue: 
- First slide in section has an image which dimensions equal viewport. No problem at all.
- Second slide has HTML content which is larger than viewport so I bought **scrollOverflowReset extension** to reset the scrollbar after leaving the slide...
- Third slide has an image which dimensions also equal viewport.

All sections have **fp-auto-height class**. But this section inherits the height of the largest slide. Even when I am positioned at First slide I can see an empty space below the image. I need to get rif off that space.

I need all sections to equal viewport and only scroll when content inside slide is larger. Do I need any other extension or extra configuration?

Here's my code:
```html
`	    <section class="section fp-auto-height" id="section5">
	        <div class="slide">
		        <img src="slides/newgrid/16.jpg" alt=""/>
	        </div>
	        <div class="slide">
		        <div class="intro">
			        <h1>My <br>Shows</h1>
			        <table class="agenda">
					  <tr>
					    <td>Now!</td>
					    <td>Hosts & Friends</td>
					    <td>Sofía en show de Ellen.</td>
					  </tr>
					  <tr>
					    <td>5P</td>
					    <td>Modern Family</td>
					    <td>The cast of the show will be in...</td>
					  </tr>
					  <tr>
					    <td>10P</td>
					    <td>Raze</td>
					    <td>Today the...</td>
					  </tr>
					  <tr>
					    <td>12P</td>
					    <td>In My Shoes</td>
					    <td>Premier LA Theaters</td>
					  </tr>
					  <tr>
					    <td>5P</td>
					    <td>Modern Family</td>
					    <td>The cast of the show will be in...</td>
					  </tr>
					  <tr>
					    <td>10P</td>
					    <td>Raze</td>
					    <td>Today the...</td>
					  </tr>
					  <tr>
					    <td>12P</td>
					    <td>In My Shoes</td>
					    <td>Premier LA Theaters</td>
					  </tr>
					</table>
		        </div>
		    </div>
	        <div class="slide">
		        <img src="slides/newgrid/17.jpg" alt=""/>
	        </div>
```

**Comment by alvarotrigo** [comment]
You shoudl not be using `fp-auto-height`, you should be using `scrolloverflow:true` and `scrolloverflowReset:true`.
