### ISSUE TITLE
Retrain DOM position of custom menu

### ISSUE THREAD

**Issue by richgcook** [alvarotrigo/fullPage.js#2732]
Is it possible to retain the DOM position of the custom menu instead of it being appended to the bottom of the DOM? I just want to create my own custom navigation within a specific container.

**Comment by alvarotrigo** [comment]
The menu has to be placed outside the fullpage.js wrapper or you won't be able to get it fixed.
And if it is outside and fixed, it should be irrelevant where it is positioned in the dom. 

Where exactly you want to position it? Why?

**Comment by richgcook** [comment]
I'm using PJAX (ajax library) and only have the fullPage.js init on the homepage so when you visit another page it ajax loads the new content into the wrapper but obviously as the menu is now appended outside the wrapper it doesn't get emptied with the rest of the page content.

**Comment by alvarotrigo** [comment]
> I don't mind it being outside the fullPage.js wrapper but it seems to be appending it to the last element in the DOM rather than the last element of the fullPage.js wrapper.

Why does it matter if it is fixed?

**Comment by richgcook** [comment]
DOM position matters when it's with AJAX as it's updating the content within a certain element but if the menu is appended outside the AJAX container then it breaks. It should append to the fullPage.js wrapper and not to the body.

**Comment by alvarotrigo** [comment]
> It should append to the fullPage.js wrapper and not to the body.

Nop. As I said, It has to be placed outside fullpage.js wrapper to be able to be fixed when using translate3d tranformations.



> DOM position matters when it's with AJAX as it's updating the content within a certain element but if the menu is appended outside the AJAX container then it breaks

Then you have to create another wrapper containing fullpage.js where you update the element. For example:

```html
<div class="ajax-content">
    <div class="menu"></div>
    <div id="fullpage"> 
           <div class="section">
           <div class="section">
    </div>
</div>
```

**Comment by richgcook** [comment]
No I think you're misunderstanding the issue.

My HTML is as follows:

<main class="content">
    <section class="context">
        THIS IS WHERE MY FULLPAGE.JS CODE IS INCLUDING THE CUSTOM MENU
    </section>
</main>

But once fullPage.js is initialised it appends the custom menu to outside the main.content before the closing body tag.

**Comment by alvarotrigo** [comment]
> But once fullPage.js is initialised it appends the custom menu to outside the main.content before the closing body tag.

Yeah. That's what fullPage.js does by design to avoid issues with translate3d elements and fixed positioned ones.

**Comment by richgcook** [comment]
Why not just append outside fullPage.js container rather than all to end of body?

—
Sent AFK

**Comment by alvarotrigo** [comment]
> Why not just append outside fullPage.js container rather than all to end of body?

Because it shouldn't matter at all in normal occasions.
But you can do that yourself in the afterRender callback. Just move it wherever you want.

**Comment by richgcook** [comment]
I think it's fairly normal... no? Maybe I push a change forward? Why would it matter then it would suit both situations?

**Comment by alvarotrigo** [comment]
Feel free to provide a pull request in the `dev` branch. 
But as I said, you can fix it right now by just moving it yourself in the afterRender.
