### ISSUE TITLE
Fullpage.js我想让他初始化不止一次怎么办？求解决？

### ISSUE THREAD

**Issue by xueyuman2** [alvarotrigo/fullPage.js#2733]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
You can not initialize fullpage.js more than once. 
You'll have to destroy it with `$.fn.fullpage.destryo('all')` and initialize it again.

---

您不能多次初始化fullpage.js。
你必须用`$ .fn.fullpage.destryo（'all'）`摧毁它，并再次初始化它。
