### ISSUE TITLE
Modal input long not scroll on mobile devices

### ISSUE THREAD

**Issue by Paxlol** [alvarotrigo/fullPage.js#2734]
I had and issue using Bootstrap v3.3.7 and fullpages. I have an modal with several inputs that in mobile need to use scrollbars. In computer theres no problem but in mobile i cannot scroll. I check in forums and the solution i found was putting that lines in my css:
body,html{
    -webkit-overflow-scrolling : touch !important;
    overflow: auto !important;
    height: 100% !important;
	overflow-scrolling: touch !important;
	-webkit-perspective: 0;
	perspective:0;
}
But it collapse with FULLPAGE library. How can i resolve that issue. Thanks

**Comment by alvarotrigo** [comment]
See answers like this:
https://stackoverflow.com/questions/38264469/block-scroll-on-modal-open

Just disable the autoScrolling when opening the modal and enable it on close. Or rather use the class `normalScrollElements`.
