### ISSUE TITLE
Horizontal nav with many elements not centered for mobile view

### ISSUE THREAD

**Issue by sabalka** [alvarotrigo/fullPage.js#2736]
### Description
When there are many slides in a section, and if the width of the fullPage nav ul (the dots on the bottom) exceeds the initial window width, the dots will not center correctly. It appears the left: 50% position of the .fp-slidesNav may be affecting the nav.width() call in the .margin-left computation in jquery.fullPage.js . Moving the left: 50% into the jquery so it applies after the nav.width() might fix it?

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/ojd2mf45/

### Steps to reproduce it
1. jsfiddle doesn't show the fullPage navs, so make a local copy.
2. Open in Chrome (though I think this reproduces in any browser).
3. Resize Chrome to minimum width.
4. Reload page. The navs should not be centered.

![image](https://cloud.githubusercontent.com/assets/4965542/26685407/b0ca55f0-46af-11e7-898b-f36c2fadcb36.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

I'll take a look at it. I believe it is as easy as using:

```
.fp-slidesNav{
    left: 0 !important;
    right: 0;
    margin: 0 auto !important;
}
``` 

And then removing the current `left:50%` and the Javascript code regarding the `margin-left`.

Until I solve it you can overwrite those styles yourself. Check [this updated demo](http://jsfiddle.net/ojd2mf45/2/).

If you still prefer having them in two rows, just add `width:50%` 

```css
.fp-slidesNav{
    left: 0 !important;
    right: 0;
    width:50%;
    margin: 0 auto !important;
}
```
[Demo online](http://jsfiddle.net/ojd2mf45/3/)

**Comment by alvarotrigo** [comment]
Fixed on the dev branch.
