### ISSUE TITLE
fadingEffect:'slides' breaks wow.js

### ISSUE THREAD

**Issue by lsterling03** [alvarotrigo/fullPage.js#2737]
I am using wow.js to animate content in each section after you scroll to it. I achieve this by setting `scrollBar:true` and adding wow.js in the `afterRender` callback, like so:

`afterRender: function(){ new WOW().init(); }`

I also have the fadingEffect extension. If I set `fadingEffect:true` or `fadingEffect:'sections'`, wow.js works. However, if I set it to `fadingEffect:'slides'`, wow.js will no longer work. There are no console errors... it just doesn't seem to recognize that it has scrolled to the section, and thus wow.js never applies its styles. If I move `new WOW().init();` to the `afterLoad` callback, wow.js works again. But is it bad for performance to initialize wow after every section scrolls?

Is this a bug, or expected behavior? Is putting it in `afterLoad` the best solution?

Version: fullPage 2.9.3 - Extensions 0.0.7 
Browser: Chrome 58

**Comment by lsterling03** [comment]
I am using wow.js successfully by loading it in the afterRender callback, like so:

`
afterRender: function(){
	new WOW().init();
}
`
I also have the fadingEffect extension. If I set fadingEffect:true or fadingEffect:'sections', wow.js works. However, if I set it to fadingEffect:'slides', wow.js will no longer work. There are no console errors... it just doesn't seem to recognize that it has scrolled to the section, and thus wow.js never applies it's styles. If I move `new WOW().init();` to the `afterLoad` callback, wow.js works again. But is it bad for performance to initialize wow after every section scrolls?  

Is this a bug, or expected behavior? Is putting it in afterLoad the best solution?

**Comment by alvarotrigo** [comment]
> I also have the fadingEffect extension. If I set fadingEffect:true or fadingEffect:'sections', wow.js works. However, if I set it to fadingEffect:'slides', wow.js will no longer work. 

`faddingEffect` and `scrollBar:true` are not compatible. `fadingEffect` will always turn `scrollBar` to `false`. So it is totally irrelevant if you use `scrollBar:true`. No scroll bar will be visible and wow shouldn't be working. 

> If I move new WOW().init(); to the afterLoad callback, wow.js works again. But is it bad for performance to initialize wow after every section scrolls?

You should not be using wow.js if you want to use fadingEffect.
It makes no sense, as wow listens to the scroll event of the site and fullPage.js won't fire it.

You should be using [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to fire your animations. 

See topics like this https://github.com/alvarotrigo/fullPage.js/issues/249

**Comment by lsterling03** [comment]
Thank you. Just to clarify -- I'm not using wow.js on the fading part. I've set fadingEffect:'slides' so that the fade only happens on slides.  The wow.js animations are on content in the normal scrolling sections. I just wondered why wow works on the scrolling sections in afterRender callback when fadingEffect:true or fadingEffect:'sections', but not with fadingEffect:'slides'.
