### ISSUE TITLE
Fullpage does not rebuild when its container is resized

### ISSUE THREAD

**Issue by WhiteTitanX** [alvarotrigo/fullPage.js#2738]
### Description
When you push the fullpage container with margin-left due to a side nav opening/closing, it does not auto-correct itself by rebuilding. Preferably it should adjust its size while keeping the current slide in place.

Also, I included a temporary fix which you can enable to rebuild itself after the transition of the nav finishes.

### Link to isolated reproduction with no external CSS / JS
[Demo in JSFiddle](https://jsfiddle.net/WhiteTitan/ps9ce7wg/)
In the demo, goto the second or third slide and open the side nav.

### Steps to reproduce it
1. Create a slide show with background images
2. Create a collapsible side nav, which opens by pushing the content to the right with a transition
3. Goto the second slide
4. Open the nav
5. There you can see that the third slide moves partially into view without auto-correction

### Versions 
Chrome, Windows 10 Desktop

**Comment by alvarotrigo** [comment]
Your solution seem to be the right one. 
Fullpage.js is a full-page library, it doesn't expect a non full screen use of it. This margin example is one of those cases.
