### ISSUE TITLE
normalScrollElementTouchThreshold

### ISSUE THREAD

**Issue by Paxlol** [alvarotrigo/fullPage.js#2740]
### Description
Alvaro. Thanks for the Library. I found an error in the code using bootstrap and fullpage. When i use modal and use normalScrollElementTouchThreshold to avoid the scroll the max value where the normalScrollElementTouchThreshold function correctly is 9. 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
The way normalScrollElements work has been changed as per https://github.com/alvarotrigo/fullPage.js/commit/4d5ba923f9d9ab40db75cbd91c062ad514c95260

`normalScrollElementTouchThreshold` won't exist anymore in 2.9.5.
