### ISSUE TITLE
Swipe horizontally in Firefox mobile not working when responsive

### ISSUE THREAD

**Issue by 3cees** [alvarotrigo/fullPage.js#2741]
Hi,

swiping in the slider does not work in FF Mobile, when a responsive height and width was added.
Is there any workaround for that?

Cheers,
Lars

**Comment by alvarotrigo** [comment]
> swiping in the slider does not work in FF Mobile

Working as expected in Firefox for iOS [on the demo page](http://alvarotrigo.com/fullPage/examples/responsive.html).

What device and OS are you using? 
Can you confirm it doesn't work as expected on the [responsive demo page](http://alvarotrigo.com/fullPage/examples/responsive.html)?

**Comment by 3cees** [comment]
Hey,

on Android, it does not work on the dmeo page...
I have just tested ti.

**Comment by alvarotrigo** [comment]
True! Tested in Browserstack and it seems sliders won't slide horizontally!

**Comment by alvarotrigo** [comment]
I need some help here from anyone with access to any Android device.
I have no access to any and services like Browserstack.com do not provide devtools for Firefox browsers in Android devices.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch. Will get merged in fullpage.js 2.9.6.
