### ISSUE TITLE
Conflict with the slider

### ISSUE THREAD

**Issue by AlexanderBelkevich** [alvarotrigo/fullPage.js#2742]
Hello. The problem with slick slider and Bootstrap 3 slider
When on the page they are used, the block above them disappears for a while. How can this be remedied?

http://alexbeos.beget.tech/test/
[Disappears for a while when returning back to the slider after scrolling](http://prntscr.com/fg64vl)

Sorry for my English

**Comment by AlexanderBelkevich** [comment]
https://drive.google.com/file/d/0B8N586BNak6EZDI0VXh6Z01oVkU/view?usp=sharing

**Comment by alvarotrigo** [comment]
Please provide the steps to reproduce your issue as well as unminified files.
I'll close the issue  until then.
