### ISSUE TITLE
no css3 & jquery3 & jquery-migrate-3.0.0

### ISSUE THREAD

**Issue by lianee** [alvarotrigo/fullPage.js#2743]
### Description
When using fullPage without css3 (either css3:false or scrollBar:true), scroll is disabled, no error displayed.
DOM is updated, but nothing moves until you resize the window.

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/97tbk/1896/

Comment the line ccs3: false in the above fiddle and it works again (not depends on jquery)
or
Remove the loading of the migrate file and it works.

Issue happens only when jquery-migrate is present, so it is not (yet) a jquery 3 issue... not surprising, since this migrate file has already other issues (with angular at least)

**Comment by alvarotrigo** [comment]
> Issue happens only when jquery-migrate is present, so it is not (yet) a jquery 3 issue... not surprising, since this migrate file has already other issues (with angular at least)

I would consider reporting it in [jquery migrate plugin issues.](https://github.com/jquery/jquery-migrate/issues).
There seem to be a problem calculating the window height. The `top` property of the fullPage.js container gets very low values.

In any case, I'll close the issue as this seems to be a jquery migrate plugin issue and not a fullPage.js one. 
fullPage.js provides full support for jQuery.

**Comment by lianee** [comment]
I just wanted to alert that it was a *potential futur* issue with jQuery, never qualified this as a bug in fullPage

**Comment by alvarotrigo** [comment]
Sure! Thanks a lot for that!
It is probably useful for anyone looking for it on Google and ending up here.

I just like to keep the number of open issues as small as possible and only with fullpaje.js issues I can potentially solve :)
