### ISSUE TITLE
Is it possible to freeze the scrolling instead of killing it or setting AutoScroll to false?

### ISSUE THREAD

**Issue by Acovendesigns** [alvarotrigo/fullPage.js#2744]
I'm trying to freeze FullPage so it doesn't updated the translate3d property on scroll after I click my view-case-study button. This is not a site specific request, trying to see if it's possible to stall the scroll for other uses as well.

Here's the link to my site
https://www.alexcoven.com

I've tried overlaying it with a 99999 z-indexed, fixed div while setting AutoScrolling(false); on FullPage and it works wonderfully in Chrome but not at all in safari. Below is a link to a pen to further explore.
https://codepen.io/alcoven/pen/eRNyvd

### Steps to reproduce it
1. Click the view case studies button on the bottom right
2. and scroll
3. watch as the fp-viewing class is updated.

### Versions 
Chrome, Safari, Moz

**Comment by alvarotrigo** [comment]
Use [`setAllowScrolling`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions)
