### ISSUE TITLE
Finger swiping issue on form inputs with scrollOverflow

### ISSUE THREAD

**Issue by ktrzos** [alvarotrigo/fullPage.js#2747]
I've got contact form here:
http://metrkw-front.test.notimeo.pl/#kontakt

When on mobile devices or responsive view in Google Chrome, I cannot swipe up or down when starting from any form input field. What is wrong with this?

I also learned that setting `overflow:auto` on some other DOM elements is making the same bad effect :/.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ktrzos** [comment]
Really? I have given you the proper link. Just click on it, set your browser size on 615x615px and try to swipe trough the form which appears.

**Comment by alvarotrigo** [comment]
> Really?

Really.
You didn't provide neither unminified nor uncompressed JS files. 
Who knows what other libraries or codes you are using in there.
Notice the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md) says very clearly: 

>  links to personal websites won't be reviewed unless isolated

**Comment by ktrzos** [comment]
### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/p9gbzor2/4/

### Steps to reproduce it
1. Open the link with latest Google Chrome browser (in incognito, if You want)
2. Click F12
3. Click ctrl + shift + M
4. Set "Responsive", 800x800px, 100% and turn ON touch events simulation and reload page (on FF it's other option to set and possibly Chrome have this set from the beginning)
5. Set mouse coursor on the input field
6. Hold left mouse button and try to slide up or down

### Versions 
Google Chrome 58.0.3029.110 (64-bit)
Checked also latest Chrome on the smartphone.

For the record... this works on Firefox :/.

ALSO... have a look at this:
https://jsfiddle.net/p9gbzor2/5/

Changed form field on div with `overflow:auto`. Same thing is happening.

Is this what You needed?

**Comment by alvarotrigo** [comment]
Thanks for that!

Regarding your issue, it is within the vendor library `iScroll.js`. Not in fullPage.js.
I would encourage you to open an issue in [their issues forum](https://github.com/cubiq/iscroll) although I believe the project is kind of death... 
See a similar report [in here](https://stackoverflow.com/questions/12849747/iscroll-4-not-scrolling-on-input-elements).

Personally I would try to stop using scrolloverflow and go for a totally responsive approach by using the responsive options together with the class `fp-auto-height-responsive`.

**Comment by ktrzos** [comment]
Thank you for the response. I'll try the solution with `fp-auto-height-responsive` class.

Also... I think that you should clearly add in documentation something  about iScroll and `scrolloverflow`. Maybe that this functionality is deprecated because the `iScroll` is dead or that the `scrolloverflow` is very unstable.

**Comment by alvarotrigo** [comment]
> Maybe that this functionality is deprecated because the iScroll is dead or that the scrolloverflow is very unstable.

Yeap I agree. I'll do for the next release.
