### ISSUE TITLE
Fullpage.js is not loading the animation of slide2 onward, why and how to fix ?  

### ISSUE THREAD

**Issue by subhendumondal** [alvarotrigo/fullPage.js#2750]
I am using fullpage.js to build my website . But I have facing an issue is that.

I have 2 section.
like <div class="section></div>
      <div class="section"></div>

inside <div class="fullpage"></div>

and i call jquery function $('#fullpage').fullpage({});

But the main issue is. I have animation is every section. only the section 1 animation is loading but not others one. other page look completely static page. Why it is happening and how to fix this issue.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
