### ISSUE TITLE
FullPage.js scolling to the top of a long section

### ISSUE THREAD

**Issue by Larraine** [alvarotrigo/fullPage.js#2751]
I am using fullpage.js and it all works perfectly but I want to be able to scroll back to the top of a section shen you have scrolled to the bottom, I ahve scrolling set to allow scrolling in a section.

**Comment by alvarotrigo** [comment]
> I ahve scrolling set to allow scrolling in a section.

I guess you are then using `scrollOverflow:true`?

If so, Sure!
Just get the [Scrolloverflow Reset extension](http://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html) and then use `scrollOverflowReset: true`.

**Comment by Larraine** [comment]
Yes I am using scrollOverflow:true and have tried your suggestion but it has not worked.

**Comment by alvarotrigo** [comment]
> have tried your suggestion but it has not worked.

Have you purchased the extension ?

**Comment by Larraine** [comment]
I have downloaded it all yes.

**Comment by alvarotrigo** [comment]
> I have downloaded it all yes.

Downloaded?
If you have purchase it, let me know the email you used for your purchase and I'll be able to help you.

**Comment by Larraine** [comment]
I downloaded it from github, an email address was not required.

**Comment by Larraine** [comment]
Ok, thank you.

**Comment by Larraine** [comment]
Hi, I have purcahsed the extension, downloaded it, activated it and it is not working.

**Comment by alvarotrigo** [comment]
Can you please [contact me](http://alvarotrigo.com/#contact) with the URL  you are using?

**Comment by Larraine** [comment]
http://www.choirschool.com/SITE-DEVELOPMENT/TEST/headmasters-welcome.php

**Comment by alvarotrigo** [comment]
Check your Javascript console: 

>Uncaught TypeError: $(...).fullpage is not a function
    at HTMLDocument.<anonymous> (headmasters-welcome.php:62)
    at l (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.A (jquery.min.js:2)

You are not including fullpage.js anywhere?
Read the docs regarding [how to use the extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions). You need to include the extension + the fullpage.js extensions file.
You are missing `fullpage.extensions.min.js`
```html
<script type="text/javascript" src="fullpage/jquery.fullpage.extensions.min.js"></script>
```

**Comment by Larraine** [comment]
the fullpage.js is on there.

**Comment by Larraine** [comment]
I missed the bit about the other file, I wil give that a go, thanks.

**Comment by alvarotrigo** [comment]
Check your JS console:

> jquery.fullPage.js:2921 fullPage: fullpage.js extensions require jquery.fullpage.extensions.min.js file instead of the usual jquery.fullpage.js. Requested: scrollOverflowReset

**Comment by Larraine** [comment]
Ok, I have include the fullpage.extensions.min.js file and it is still not working, I'm afraid I don't understand your other comments:

Uncaught TypeError: $(...).fullpage is not a function
at HTMLDocument. (headmasters-welcome.php:62)
at l (jquery.min.js:2)
at Object.fireWith [as resolveWith] (jquery.min.js:2)
at Function.ready (jquery.min.js:2)
at HTMLDocument.A (jquery.min.js:2)

**Comment by Larraine** [comment]
I think I have got this working but have noticed something else, when you are at the bottom of one section (a long section) I need the link for that section to then take you back to the top of that section, or an arrow at the bottom to take you to the top.

**Comment by Larraine** [comment]
Sorry I have noticed something else too, in Safari the background images shudder when you use the navigation on the right.

**Comment by Larraine** [comment]
Sorry again but when I had hte normal fullpage.js and not the one for the extensions the active slide was highlighted in the tooltip navigation, and not it's not, how can I get that back to work?

**Comment by alvarotrigo** [comment]
> Sorry again but when I had hte normal fullpage.js and not the one for the extensions the active slide was highlighted in the tooltip navigation, and not it's not, how can I get that back to work?

Please open a new issue with a reproduction of it.

**Comment by ankit-root** [comment]
Hi, Anyone please help me. how to tabing content section based overflow scroll reset?
I have already using scrollOverflowReset extension for this site.

https://preprod.weareassura.com/platform-2/#features

Please tell me how to fixed this issue
