### ISSUE TITLE
Disabling Hashes and preventing scrolling?

### ISSUE THREAD

**Issue by chrisbrenn** [alvarotrigo/fullPage.js#2753]
Hey Guys,

first of all: amazing plugin!
I already google it but can't find nothing about this topic / solution.
Have two "fancy" issues.

1. I use "data-anchor" to jump to the next or third "section". I always get an anchor to my url. Is there a way to disable the anchor in url and scrolling to the next section?
2. Is it possible to disabling jumping to selected section after adding the "hash" to the url? (So if I add mysite.com/#slide04 id jump to slide4 but i want that the first slide is always visible)

Thanks,
Chris.

**Comment by alvarotrigo** [comment]
> I use "data-anchor" to jump to the next or third "section". I always get an anchor to my url. Is there a way to disable the anchor in url and scrolling to the next section?

Use the fullpage.js function [`moveTo`](https://github.com/alvarotrigo/fullPage.js#movetosection-slide).



> Is it possible to disabling jumping to selected section after adding the "hash" to the url? (So if I add mysite.com/#slide04 id jump to slide4 but i want that the first slide is always visible)

No. That's what anchors are for.
