### ISSUE TITLE
Fullpage.js highlighting the section/slide

### ISSUE THREAD

**Issue by Larraine** [alvarotrigo/fullPage.js#2756]
I was using the normal fullpage.js and I could get the active slide tooltip to be highlighted but since using the fullpage.js for extensions I have lost that function. This is the working version: http://www.mercerdesign.co.uk/client_development/choirschool/TEST/, this is the version that is not working: http://www.choirschool.com/SITE-DEVELOPMENT/TEST/index.php#firstPage

**Comment by alvarotrigo** [comment]
Did you solve it? 
You closed the issue?

**Comment by Larraine** [comment]
Yes, sorry I should have said
