### ISSUE TITLE
Lazy loading background image

### ISSUE THREAD

**Issue by jayeshm66** [alvarotrigo/fullPage.js#2757]
I am using full screen background image for per section.

Is their any way to lazy load background images.

**Comment by alvarotrigo** [comment]
Sure. Just make use of the fullpage.js callbacks or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs).
Check [this answer](https://github.com/alvarotrigo/fullPage.js/issues/46#issuecomment-26509996).
