### ISSUE TITLE
Auto-Height sections keeps adjusting on mobile

### ISSUE THREAD

**Issue by sogeniusio** [alvarotrigo/fullPage.js#2759]
I'd like to turn off the section readjustment for my site. I turned of autoscroll and since this change, every time the page lands to a spot within a section (footer to be exact), it'd either scroll up or down. I'd like to remove this functionality. One this I noticed is that my footer has fp-auto-height (would this be the issue?)

See example here:

Recording - [http://g.recordit.co/UwuiTZ3rHj.gif](Recordit)

### Link to isolated reproduction with no external CSS / JS

JSFiddle - [https://jsfiddle.net/pxzm99u1/1/](JSFiddle)

### Steps to reproduce it
1. Scroll down to my footer, and it let go
2. Screen read adjusts upward or downward
3. This is unwanted functionality

### Versions 
Current version of Fullpage, Bootstrap 4, Jquery 1.11

**Comment by alvarotrigo** [comment]
Use the fullpage.js option `fitToSection:false`
