### ISSUE TITLE
fadingEffect.turnOff jumps back to top section

### ISSUE THREAD

**Issue by lsterling03** [alvarotrigo/fullPage.js#2760]
### Description
I have the fadingEffect extension, and I am trying to turn fadingEffect off between certain sections. When I use the following code, to make it scroll (not fade) between Sections 2 and 3, it instead jumps back to Section 1 at that transition. Am I doing something wrong, or is there a bug?

```
fadingEffect: 'sections',
fadingEffectKey: 'XXX',
onLeave: function(index, nextIndex, direction){
					
   if(index == 2 && direction =='down'){
	 $.fn.fullpage.fadingEffect.turnOff();
         //alert("turn off fade and scroll to section 3!");
   }
  else if(index == 2 && direction == 'up'){
	 $.fn.fullpage.fadingEffect.turnOn();
   }
					
}
```
			
### Link to isolated reproduction with no external CSS / JS
I made a codepen using the official fadingEffect example, but it's not showing the fade effect because I'm using your example fadingEffectKey. I don't want to publish my own key, so if you can just edit this example to use a working key, you'll see the problem I'm referring to.

https://codepen.io/anon/pen/bRqMOe

### Steps to reproduce it
Scroll between Section 2 and Section 3. 
Instead of turn off the fade feature and scrolling to Section 3, it jumps back to Section 1.

### Versions 
Latest version of fullpage.js.

**Comment by lsterling03** [comment]
Note: I can (sort of) get it to work properly  if I turn the fadingEffect on/off in the afterLoad event, but that only works in one direction. 

For example, I can use this:

```
afterLoad: function(anchorLink, index){
	var loadedSection = $(this);

	 if (index == 2)  {   
                $.fn.fullpage.fadingEffect.turnOff();
          } else {
		$.fn.fullpage.fadingEffect.turnOn();
	}

}
```

But this only works when scrolling from Section 2 to 3. It doesn't turn the fade off again from Section 3 to 2. For that, I need onLeave, but that causes the problem outlined in my original question. It seems like you need a beforeLeave event to handle this.

**Comment by alvarotrigo** [comment]
That won't work properly. Changing the page within the `onLeave` callback might cause unwanted results.

You could try something like this:

```javascript
var hasBeenChanged = false;

$('#myContainer').fullpage({
    sectionsColor: ['#61bd6d', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff', '#ccc'],
    anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage'],
    menu: '#menu',
    slidesNavigation: true,
    fadingEffect: true,
    fadingEffectKey: 'YWx2YXJvdHJpZ28uY29tXzAzN1ptRmthVzVuUldabVpXTjBiNXo=',
    onLeave: function(index, nextIndex, direction) {

        if (index == 2 && direction == 'down' && !hasBeenChanged) {
            $.fn.fullpage.fadingEffect.turnOff();
            hasBeenChanged = true;
            return !hasBeenChanged;
            //alert("turn off fade and scroll to section 3!");
        } else if (index == 2 && direction == 'up' && !hasBeenChanged) {
            hasBeenChanged = true;
            $.fn.fullpage.fadingEffect.turnOn();
            return !hasBeenChanged;
        }
        hasBeenChanged = false;

    }

});
```

This way you'll need to enter again in the onLeave callback to actually leave the section.

**Comment by alvarotrigo** [comment]
In any case, if you are not happy with the result, let me know and I'll refund you.

**Comment by CKMacLeod** [comment]
Never mind. I won't be needing the extension after all to achieve the snap-scroll snap-scroll - cross-fades effect we wanted. However, we are admirers of your work and will likely be purchasing one or two at least of the other extensions sometime soon. 

I still don't know what you were saying with that last sentence, but it doesn't matter. Also, the code you used above made for a simple helpful template for use with the un-extended plugin. 

Keep up the great work and thanks!

**Comment by joe830508** [comment]
> That won't work properly. Changing the page within the `onLeave` callback might cause unwanted results.
> 
> You could try something like this:
> 
> ```js
> var hasBeenChanged = false;
> 
> $('#myContainer').fullpage({
>     sectionsColor: ['#61bd6d', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff', '#ccc'],
>     anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage'],
>     menu: '#menu',
>     slidesNavigation: true,
>     fadingEffect: true,
>     onLeave: function(index, nextIndex, direction) {
> 
>         if (index == 2 && direction == 'down' && !hasBeenChanged) {
>             $.fn.fullpage.fadingEffect.turnOff();
>             hasBeenChanged = true;
>             return !hasBeenChanged;
>         } else if (index == 2 && direction == 'up' && !hasBeenChanged) {
>             hasBeenChanged = true;
>             $.fn.fullpage.fadingEffect.turnOn();
>             return !hasBeenChanged;
>         }
>         hasBeenChanged = false;
> 
>     }
> 
> });
> ```
> 
> This way you'll need to enter again in the onLeave callback to actually leave the section.

In my use case, If I go to section by using anchor link, This way can not trigger onLeave callback.

**Comment by alvarotrigo** [comment]
> In my use case, If I go to section by using anchor link, This way can not trigger onLeave callback.

You'll have to provide an isolated reproduction of the issue  if you think it is a bug in fullpage.js.
Make sure to use the latest fullpage.js version 3.0.5.

Then  check if you still have the issue without using the extension.

**Comment by Alice1212** [comment]
> > Am I doing something wrong, or is there a bug?
> 
> There is not a good solution at the moment for this I'm afraid.

Thank, sorry, I almost came to the effect I needed with the help of your library.
maybe you know a bad solution to this problem, maybe you have a hint of where to think
