### ISSUE TITLE
Slide div blocks are not working in rails

### ISSUE THREAD

**Issue by egollas** [alvarotrigo/fullPage.js#2762]
I'm using fullPage.js in a rails app.
I have several `class="slide"` blocks of code inside one of my sections this should slide horizontal. I get no errors. But horizontal sliding does't work.
I try using a the method

```
  $(document).on('click', '#moveRight', function(){
  $.fn.fullpage.moveSlideRight();
});
```

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
