### ISSUE TITLE
Mobile webpage - like mobile app

### ISSUE THREAD

**Issue by pavlito** [alvarotrigo/fullPage.js#2763]
Hi @alvarotrigo 

Is it possible with this plugin to create webpage for mobile (small devices), to have feel like it is mobile app.
By that i mean: 
Sections on page need to imitate separate pages (like slides example). Just to have on each section header (not fixed or absolute positioned).
So page is only 1 section, and parts (sections) of that page are slides?
Navigation for slides, so when user change slide menu item get some class (".active").?
Swipe/horizontal scroll ability for menu, similar like google web search on mobile have.

**Comment by alvarotrigo** [comment]
Your description is not very clear to me. But I guess you'll know if it is possible or not whenever you try it :)

**Comment by pavlito** [comment]
Hahah, you are right.

Ok i will break down to smaller questions :)
I started the development for page. 

I wrapped all content in 1 div=".section" .
Few parts of page i wrapped in div=".slide" and now i have cool swiping ability on mobile.

Here is video of current web page https://vid.me/iJ4C

Is it possible to set header static (not fixed), but visible on other slides?
There is secondary navigation below header. Is it possible to have effects on menu items similar to examples of fullpage.js when scrolling to different sections? Instead of that effect is related to changing slides instead of sections?

**Comment by alvarotrigo** [comment]
> Is it possible to set header static (not fixed), but visible on other slides?
I don't know, just try it yourself.  Not a fullPage.js specific issue.

> Is it possible to have effects on menu items similar to examples of fullpage.js when scrolling to different sections? Instead of that effect is related to changing slides instead of sections?

Sure. Just use the [fullpage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to change the style of the active one.

**Comment by pavlito** [comment]
Created function with adding class to menu item after slide or click.

But i have now issue.

If i go to slide3 for example, and refresh page, then after page loads it automatically slide to slide3. 
Any advice?

**Comment by alvarotrigo** [comment]
> If i go to slide3 for example, and refresh page, then after page loads it automatically slide to slide3.
Any advice?

That's what anchors in the URL are for. 
If you do not want that behavior then do not use the `anchors` option.

**Comment by pavlito** [comment]
So now i am unable to change slide with nav links.
I see there is methods like moveSlideLeft/Right ? Is there any method to provide slideIndex to move to that slide?

**Comment by alvarotrigo** [comment]
> I see there is methods like moveSlideLeft/Right ?
> Is there any method to provide slideIndex to move to that slide?

Yeah. Check the docs.

**Comment by pavlito** [comment]
Ok thank you much @alvarotrigo !
