### ISSUE TITLE
Horizontal swipe gesture

### ISSUE THREAD

**Issue by madeinside** [alvarotrigo/fullPage.js#2764]
Fantastic plugin !!

Is it possible to deactivate only the horizontal swipe gesture on mobile device ?
I use the autoscroll, and the vertical swipe to switch from sections is great,
but I want to use the horizontal touch gestures for something else.

**Comment by alvarotrigo** [comment]
> Is it possible to deactivate only the horizontal swipe gesture on mobile device ?

It depends on you how you define "mobile". But sure, just use the fullpage.js function [`setAllowScrolling(false, 'right, left');](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions) on page load.

**Comment by madeinside** [comment]
Thanks !
I wanted to say "touch device", not "mobile", sorry.

It's working but not as well as expected.
sometimes the scroll occurs anyway.

**Comment by alvarotrigo** [comment]
> Only `setAllowScrolling(false, 'all'); works good.
> No matter wich direction I pass to the method,
> the four are working if I'm not banning them all.

Make sure to use the latest fullPage.js version 2.9.4.
If you still have issues open an issue with an isolated reproduction in jsifflde or codepen.
