### ISSUE TITLE
Horizontal scrolling messes up on last slide

### ISSUE THREAD

**Issue by rredfearn32** [alvarotrigo/fullPage.js#2765]
### Description
I've got a horizontal scrolling section with six slides. I can scroll between them all the way to the last-but-one slide. After that, the plugin loops back to the first slide, despite loopHorizontal being set to false.

The issue is most likely caused by a problem in my own CSS/JS, since making a from-scratch demo of Fullpage horizontal scrolling works fine. But I can't figure out what's interfering, so I thought I'd ask here for help.

*Note: a lot of JS re-arrangement of the page structure happens before Fullpage is called. However, the HTML is definitely in the right structure when Fullpage is called, so it should work.

### Link to isolated reproduction with no external CSS / JS
http://dev.oxplore.surge.online/

### Steps to reproduce it
1. Scroll horizontally through the slides in the first section
2. After reaching slide 5, press right-arrow again.
3. Instead of advancing to slide 6, we loop back to slide 1 again.

### Versions 
Chrome, Firefox, IE, Mobile, etc

**Comment by alvarotrigo** [comment]
I'm not able to reproduce your issue in any of the fullPage.js examples online.

Please provide an isolated reproduction with no external CSS or JS.
Ideally in jsfiddle or codepen.

**Comment by rredfearn32** [comment]
Ah. That's the thing; FullpageJS on its own works fine, and it's definitely either my JS/CSS or the Drupal environment causing the problem. But I've already spent two days debugging it, and (mostly at my bosses prompting) I thought I'd ask the community to see if it's an issue anyone else had come across.

I appreciate that your time is limited though and it's not your job to debug someone else's code. Don't sweat it! :smile:
