### ISSUE TITLE
Scrolling when content is to high on every horizontal slide

### ISSUE THREAD

**Issue by fourroses666** [alvarotrigo/fullPage.js#2766]
Why can I only scroll on the first slide?

Have a look here:
http://www.lc.graffx.nl/logo

Any idea whats going on?

_Also have a jsfiddle which is even weirder, when the browser is small then it doesn't even work:
http://jsfiddle.net/fourroses666/97tbk/1923/_
```
		$(document).ready(function() {
			$('#fullpage').fullpage({
				anchors: ['logo'],
				sectionsColor: ['#EEEEEE'],
				slidesNavigation: true,
				continuousVertical: false,
				continuousHorizontal: false,
				lockAnchors: true,
				loopHorizontal: false,
				scrollOverflow: true
			});
			
			//adding the action to the button
			$(document).on('click', '.nextpage', function(){
				$.fn.fullpage.moveSectionDown();
			});
			$(document).on('click', '.door', function(){
				$.fn.fullpage.moveSlideRight();
			});
		});
```

**Comment by alvarotrigo** [comment]
Check your Javascript console errors:

> jquery.fullPage.min.js:8 fullPage: data-anchor tags can not have the same value as any `id` element on the site (or `name` element for IE).
> jquery.fullPage.min.js:8 fullPage: "logo" is is being used by another element `id` property

**Comment by fourroses666** [comment]
The issue had to be somewhere in the script:

When using the js and css from some example it started to work again.
```
	<link rel="stylesheet" type="text/css" href="https://alvarotrigo.com/fullPage/jquery.fullPage.css" />
	<link rel="stylesheet" type="text/css" href="https://alvarotrigo.com/fullPage/examples/examples.css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript" src="https://alvarotrigo.com/fullPage/vendors/scrolloverflow.min.js"></script>
	<script type="text/javascript" src="https://alvarotrigo.com/fullPage/jquery.fullPage.min.js"></script>
	<script type="text/javascript" src="https://alvarotrigo.com/fullPage/examples/examples.js"></script>
```

One more question; where is this script used for? Is it needed?
`https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js`

**Comment by alvarotrigo** [comment]
> One more question; where is this script used for? Is it needed?
> https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js

The docs state:

> Optionally, when using css3:false, you can add the jQuery UI library in case you want to use other easing effects apart from the ones included in the jQuery library (linear and swing ) or the one included by default in fullPage.js (easeInOutCubic).
