### ISSUE TITLE
Disable touch gesture (only)

### ISSUE THREAD

**Issue by SlavisPL** [alvarotrigo/fullPage.js#2767]
Hi,
Is any way to disable only touch gesture in section with normal scroll? I need to allow user scrolling only by mouse wheel.

**Comment by alvarotrigo** [comment]
> in section with normal scroll

You mean, with `scrollOverflow:true`? Or with `normalScrollElements`?

**Comment by SlavisPL** [comment]
With scrollOverflow

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any option to do so. But take a look to the [iScroll.js docs](https://github.com/cubiq/iscroll) (vendor library used when using scrollOverflow:true) to see if you find anythign to accomplish that and then pass it to the `scrollOverflowOptions` option in fullPage.js.

**Comment by SlavisPL** [comment]
Thank you for your respond. Just one question - I need to initialize iScroll or only `scrollOverflowOption: "disableTouch: true"`?

**Comment by alvarotrigo** [comment]
As can be seen [on the source code](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L91) the default fullPage.js options for iScroll.js are the following:
```javascript
    // Default options for iScroll.js used when using scrollOverflow
    var iscrollOptions = {
        scrollbars: true,
        mouseWheel: true,
        hideScrollbars: false,
        fadeScrollbars: false,
        disableMouse: true,
        interactiveScrollbars: true
    };
```

They are passed in this way to the `scrollOverflowOptions` option:

```javascript
options: {
        scrollbars: true,
        mouseWheel: true,
        hideScrollbars: false,
        fadeScrollbars: false,
        disableMouse: true,
        interactiveScrollbars: true
    }
```

You would have to add all of those and modify or add the new ones.
