### ISSUE TITLE
Fullscreen on landscape mobile devices

### ISSUE THREAD

**Issue by rodolforamos** [alvarotrigo/fullPage.js#2768]
Hi, I'm trying to make landscape go fullscreen on mobile devices (hiding the navigation bar) but all scripts that I've made this go successful without fullPage.js aren't working with fullPage.js. Is there a way to do so just by fullPage.js configurations? Thanks in advance.

Test on iPhone SE

**Comment by alvarotrigo** [comment]
> but all scripts that I've made this go successful without fullPage.js

You'll have to produce much more information if you expect help.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
