### ISSUE TITLE
Reset Sliders extension does not animate when autoscrolling is turned off

### ISSUE THREAD

**Issue by univers0** [alvarotrigo/fullPage.js#2769]
I'm using the Reset Sliders extension to return the slider to the first slide when advancing into the next section. I have `autoScrolling` set to false. The problem is that the slide resets when halfway through the section, but the reset does not occur with animation. 

Is it possible to reset the slider by smooth scrolling back to the first slide?

Thanks.

**Comment by alvarotrigo** [comment]
> The problem is that the slide resets when halfway through the section, but the reset does not occur with animation.

It is not meant to. 

> Is it possible to reset the slider by smooth scrolling back to the first slide?

Nop. 
If you want to refund it [let me know](http://alvarotrigo.com#contact).
