### ISSUE TITLE
Determine which anchor/section is active?

### ISSUE THREAD

**Issue by qmanning** [alvarotrigo/fullPage.js#2770]
Trying to find a way to determine which anchor/section is currently visible, in order to execute jQuery when that section is scrolled into view?

Tried using "index" but as that changes pretty consistently, it creates inconsistent results. 

Thanks!

**Comment by alvarotrigo** [comment]
> Trying to find a way to determine which anchor/section is currently visible, in order to execute jQuery when that section is scrolled into view?

Check the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks). 

> Tried using "index" but as that changes pretty consistently, it creates inconsistent results.

Please provide an isolated reproduction to show that. 
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by qmanning** [comment]
Access the following CodePen:
https://codepen.io/qmanning/pen/LLeWMG

1. Enable Developer Tools
2. View the Console.log

I am using Console.log to show which Index is currently being assigned. As you can see, the INDEX assignment for a section will change, depending on when it was scrolled to.

This make it difficult to have certain actions happen based on the index - as Index 4 may become Index 3 or Index 5, depending on the user's actions.

FullPage.js allows the developer to assign an AnchorName for each section, which is helpful. 

So instead of doing this:
`if(index == 1) {
// Do This Thing
}`

To be able to instead reference the AnchorNames I've assigned, which seem to be consistent no matter what scrolling or actions a user has done.

**Comment by alvarotrigo** [comment]
> To be able to instead reference the AnchorNames I've assigned, which seem to be consistent no matter what scrolling or actions a user has done, and perform CSS or jQuery based on that.

Is this possible?

You answered yourself?

> FullPage.js allows the developer to assign an AnchorName for each section, which is helpful.

**Comment by alvarotrigo** [comment]
Also I do not understand this:

> This make it difficult to have certain actions happen based on the index - as Index 4 may become Index 3 or Index 5, depending on the user's actions.

The index will always be the same no matter what the user does if the HTML structure is the same.

**Comment by alvarotrigo** [comment]
Also... you are using a super old version of fullPage.js (2.6.6). Update to the latest 2.9.4
I do not support old versions.
