### ISSUE TITLE
Link to non-existent element

### ISSUE THREAD

**Issue by jaredoneal12** [alvarotrigo/fullPage.js#2772]
### Steps to reproduce it
When using data-menuanchors for navigation

### Versions 
all

I'd really like to implement this into my site, but this is causing accessibility issues. Is there a way to work around this?

**Comment by alvarotrigo** [comment]
Could you be more specific about which links are you referring to and which issues does it cause?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
