### ISSUE TITLE
Disable iscroll when isResponsive

### ISSUE THREAD

**Issue by pepi3** [alvarotrigo/fullPage.js#2773]
Hi,

please I need to disable _scrollOverflow_ option when width is smaller then _responsiveWidth_. Is it possible to do it? 

I tried to add _fp-auto-height-responsive_ class, but it doesn't work
Because, there is duplicated scrollbars and it doesn't look nice https://ctrlv.cz/civL
I want only one classic scrollbar like this https://ctrlv.cz/dRSv

For example with this functions change scrollOverflow? 
afterResize: function(){}
afterResponsive: function(isResponsive){}

Thanks for your time. Pepi

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/958
Not solved yet.
