### ISSUE TITLE
"Jumping" content as the initial page/layout renders with fullpage.js

### ISSUE THREAD

**Issue by nickpish** [alvarotrigo/fullPage.js#2774]
First off, thank you for this fantastic plugin- the options are amazing, and it's perfect for a current project. One general question regarding the the initial rendering of the page/layout with fullpage.js: in my opening section, I have a div that is positioned absolutely towards the bottom of the frame, and when the page first loads, I see the content of this div "jump" from the top of the viewport to the bottom, as the script loads and defines the (100%) height of the container (`.section`) div. Is there a way I can minimize this jumping effect or even somehow delay rendering of the content until the fullpage script has loaded? I realize that the section div doesn't have it's full height defined until the actual script loads.

Thanks for any insight here!

**Comment by sulym-roman** [comment]
Try initially hide the div and show it once the layout is rendered (using `afterRender` event).

**Comment by alvarotrigo** [comment]
Use the script when the document is ready as seen [in the docs](https://github.com/alvarotrigo/fullPage.js#initialization).

```javascript
$(document).ready(function() {
	$('#fullpage').fullpage();
});
```

And set the height of the sections before even using fullPage.js:

```css 
#fullpage, .section, body, html{
   height: 100%;
}
```
