### ISSUE TITLE
fb-nav on left

### ISSUE THREAD

**Issue by Hilaliz** [alvarotrigo/fullPage.js#2775]
Hi,

How can I force the nav to be on the left side on my page?
my container is max-width:800px
when I added to the #fp-nav the declaration left:0% it move to left but out from the container

**Comment by thisisfed** [comment]
Can you provide a reproduction of the issue @Hilaliz? Looks like an easy stuff.

**Comment by alvarotrigo** [comment]
Use CSS to overwrite the fullPage.js styles.
