### ISSUE TITLE
CSS width style issue with section height

### ISSUE THREAD

**Issue by Sunpacker** [alvarotrigo/fullPage.js#2776]
**Description**
When i set to video section width:100% this one take some height from next section
http://imgur.com/a/VsjeW

**Link to isolated reproduction with no external CSS / JS**
https://codepen.io/Sunpacker/pen/PjQgBG

**Steps to reproduce it**
1. added html code
2. added css styles

**Versions** 
Google Chrome, Windows 10, Desktop

**Comment by alvarotrigo** [comment]
Not a fullpage.js related issue. 
Look for some CSS solutions to deal with videos dimensions.
