### ISSUE TITLE
Video autoplay doesn't work on iOS 10+

### ISSUE THREAD

**Issue by lsterling03** [alvarotrigo/fullPage.js#2778]
I'm using a background video in one of my sections like so:

```
<video muted data-autoplay autoplay poster="poster.jpg">
          <source src="video.mp4" type="video/mp4">
           <source src="video.webm" type="video/webm">
</video>
```

Safari on iOS 10 is supposed to allow autoplay now as long as the video is muted. However, this isn't working with fullpage.js. I tried adding/removing the native "autoplay" spec but no luck. 

You can see that it's not working here on your demo on iOS 10+: https://alvarotrigo.com/fullPage/examples/videoBackground.html

I'm on ios 10.3 specifically with the native safari browser.

**Comment by alvarotrigo** [comment]
Have you tried without fullPage.js? Do you have a link I can test?

**Comment by lsterling03** [comment]
I can't publish the link publicly. Can i send a private message or email? But you can also see the problem with your official example. 

https://alvarotrigo.com/fullPage/examples/videoBackground.html

**Comment by lsterling03** [comment]
I just tried it without fullpage.js, and it didn't autoplay that way either. So I guess this is an iPhone problem. iOS 10+ is supposed to autoplay  as long as its muted, but no luck. Sorry to waste your time.
