### ISSUE TITLE
Miss a slide when scrolling between sections

### ISSUE THREAD

**Issue by Evgenylad** [alvarotrigo/fullPage.js#2779]
### Description
I've 2 slides in first section on my site and 2 slides in second section. Also I've 4 more sections (6 in total). In 6-th section I created a link to return to the first slide of the first section. If the user click it and scrolling down again form first slide of first section that case he would see first slide of second section but move directly to second slide of second section.

Here is my site: http://sedona.nerd-studio.biz/  

### Steps to reproduce it
1. Open http://sedona.nerd-studio.biz/
2. Scroll to http://sedona.nerd-studio.biz/#sixthView
3. Click the arrow with text "В начало"
4. Scroll down again. The issue will be fired when you move from firstView/slide12 to secondView/slide 21

### Versions 
[Browser FF, Chrome]

**Comment by alvarotrigo** [comment]
Sorry but I do not understand your issue. Can you please explain it again with other words?

**Comment by Evgenylad** [comment]
Thanks for your reply. So…
When you open my site http://sedona.nerd-studio.biz/ in Opera browser and scroll down via mouse wheel(PC) or touch-pad(Mac) there are sections and slides goes in following order:
1. http://sedona.nerd-studio.biz/#firstView/slide12 - this view goes after first scroll
2.  http://sedona.nerd-studio.biz/#secondView - after second scroll
3. http://sedona.nerd-studio.biz/#secondView/slide22 - after third scroll
….
….
The last section will be - http://sedona.nerd-studio.biz/#sixthView 
I need slides and sections goes in this order. 

After I click violet arrow with text in russian «в начало» on the last view - http://sedona.nerd-studio.biz/#sixthView  - site scrolls up to it’s first section. Thats fine also. The issue with unexpected behaviour starts when I scroll down again. Try to scroll down after you've clicked the arrow on the last slide and you will see that you will not see the following slide - http://sedona.nerd-studio.biz/#secondView 

I attach the missing slide just in case. This slide I do not see when I scroll down second time. And I have this issue ONLY if I’ve clicked the arrow on the last slide.

P.S. I didn’t register plugging yet because the side under construction yet and hosted on test domain address. It will be registered after I move site to my client’s domain
![1](https://user-images.githubusercontent.com/16710754/27794973-f993205c-600c-11e7-801f-d270c4418771.png)

**Comment by Evgenylad** [comment]
@alvarotrigo Hi! Should I expect any reply here?

**Comment by alvarotrigo** [comment]
@Evgenylad yeap, you should. But I'm pretty busy these days and don't have time to check the issue. So I'll reply whenever I can.

An isolated reproduction with no external CSS or JS to fullPage.js would help a lot. 
And with the minimum amount of HTML to reproduce the issue. That will help me and probably help you too! :)

**Comment by Evgenylad** [comment]
I've tried to reproduce this bug at jsfiddle but was not successful

**Comment by alvarotrigo** [comment]
> I've tried to reproduce this bug at jsfiddle but was not successful

No need to use jsfifdle. Use your own site but remove all non fullpage.js related CSS or JS code.
If you still can't the issue is probably not in fullPage.js.

**Comment by Evgenylad** [comment]
check this out - http://sedona.nerd-studio.biz/test.html 
same issue: 
if you scroll down first time after the site loaded all find and slides goes in following order - Slide11-Slide12-Slide21-Slide22
If you click btn "To start" and start scrolling down you'll see slides in following order Slide11-Slide12-Slide22. It's wrong as soon as Slide21 missed

**Comment by Evgenylad** [comment]
There's the link to isolated code above

**Comment by alvarotrigo** [comment]
> If you click btn "To start" and start scrolling down you'll see slides in following order Slide11-Slide12-Slide22. It's wrong as soon as Slide21 missed

That's not how Scroll Horizontally works. It won't revert it the slider back. 
Check out the [Reset Sliders extension](https://alvarotrigo.com/fullPage/extensions/reset-sliders.html) that you can use in combination with Scroll Horizontally to achieve that effect.

**Comment by alvarotrigo** [comment]
@Biswajit993 make sure to use the lates version of fullPage.js version 4.
