### ISSUE TITLE
How to fade in a slide description

### ISSUE THREAD

**Issue by herby-m** [alvarotrigo/fullPage.js#2780]
### Description
Is there a way to fade-in the slide description (Display Title etc.) after the slide is fully in the viewport?
I´m using the Wordpressplugin. In the DOM there is a "div.inner-slide" . I like to fade the content of this div a second after the Slide flew in and stopped moving.
Thank you for a hint ;-)

### Versions 
[Wordpress Plugin, FF, Chrome, Safari, Win 10, ios...]

**Comment by alvarotrigo** [comment]
Use a javascript `setTimeout` within a callback or use CSS `transition-delay` property if you are planning to use [fullpage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs).

**Comment by herby-m** [comment]
Thank you for your quick feedback. I thought it was made similarly in this way. But (excuse me, I am a bloody beginner) can you please show me in detail how and where? I tend to use a css transition delay. But I'm not able to find the exact selector for CSS animation (or transition).

Please, please, give me a little push in the right direction ;-))

Thank you and greetings, Kai

**Comment by alvarotrigo** [comment]
See the callbacks1.html and callbacks2.html examples available [in the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).
