### ISSUE TITLE
Reset Slider 

### ISSUE THREAD

**Issue by fjzapata** [alvarotrigo/fullPage.js#2781]
Saludos @alvarotrigo,

Estoy realizando una plataforma con fullpage.js, la estoy haciendo que se mueva automáticamente, pero no logro que el Slider me quede en la primera posición, sino se muestra en la posición donde quedo anteriormente.

`$('#fullpage').fullpage({

	              	sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
	             	anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage'],
					menu: '#menu',
					slidesNavigation: true,
					//resetSliders: true,
					//recordHistory: false,
					//autoScrolling: false,
					//lockAnchors: false,
					
	              	//Desplazamiento
					css3: true,
					scrollingSpeed: 1000,
					
					onLeave: function(index, nextIndex, direction){

						//getting the section by the index
						var section = $('.section').eq((index - 1));   

						if (nextIndex == 3) {
				    		move_page(nextIndex);
				    	}					    
					},
					afterLoad: function(anchorLink, index){						
						move_page(index);						
					},
					afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){

						if (slideIndex == 2) {
							move_page('next');
						}else{
				    		move_page(index);
				    	}
					}
	            }); 
	            
	        	// Activar para desplegar lista automaticamente del menu.
		      	$('.activated').dropdownHover().dropdown();

		    });

		    reset_slider = function(section){
		    	
		    }    

		    var tiempo = 5000;

		    move_page = function(page){

		    	if (page == 1 ) {
		    		setTimeout(move_section, tiempo);
		    		console.log(page);
		    	}

		    	if (page == 2) {
		    		setTimeout(move_slider, tiempo);		    		
		    		console.log(page);
		    	}

		    	if (page == 3) {
		    		setTimeout(move_index, tiempo);
		    		console.log(page);
		    	}

		    	if (page == 'next') {
		    		setTimeout(move_section, tiempo);
		    		console.log(page);
		    	}
		    }

		    move = function() {
		    	$.fn.fullpage.moveTo('secondPage',0);
		    }

		    move_slider = function(){
		    	$.fn.fullpage.moveSlideRight();
		    }

		    move_section = function(){
		    	$.fn.fullpage.moveSectionDown();
		    }

		    move_index = function(){			    	
		    	$.fn.fullpage.moveTo(1);
		    }`

**Comment by alvarotrigo** [comment]
Si crees que es un error en el plugin por favor provee una reproducción aislada del problema en jsfiddle o codepen sin CSS or JS externo tal y como se detalla en las [directrices de reporte de problemas](https://github.com/alvarotrigo/fullPage.js#reporting-issues).

Si lo que buscas es soporte para un problema en tu página ofrezco un pack por 50 British Pounds.

PD: usa inglés a ser posible.
