### ISSUE TITLE
Won't scroll to bottom of the page

### ISSUE THREAD

**Issue by jean-occena-meork** [alvarotrigo/fullPage.js#2782]
Hi! Im using fullpage.js with angular. So the footer is outside the id fullpage which prevents it from scrolling to the  footer. Is there anyway I can't use autoscrolling:false . How will I customize the javascript? :) 

Here's what I'm using:

https://github.com/hellsan631/angular-fullpage.js/tree/master

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
