### ISSUE TITLE
Moving slides by hitting tab doesn't trigger onSlideLeave

### ISSUE THREAD

**Issue by carlganz** [alvarotrigo/fullPage.js#2783]
### Description

I find that if you have inputs on multiple slides, and you hit tab to go from one to the next, when you tab to an input on the next slide, it moves to the next slide, but doesn't trigger `onSlideLeave`. Furthermore, pressing the left or right button doesn't work correctly after moving slides with tab (fullpage still thinks it is in the first slide so when you hit right it moves to second slide where you already are)

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/he0ofw92/

### Steps to reproduce it
1. Select the first text input
2. Press tab twice
3. You will be on second slide now, but `onSlideLeave` isn't triggered
4. Press either arrow button and the slides won't slide

### Versions 
Chrome, Windows, jsfiddle

Also had issue on Ubuntu

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1237
