### ISSUE TITLE
Go section up or down depending on direction

### ISSUE THREAD

**Issue by peterboruplund** [alvarotrigo/fullPage.js#2786]
Hi, I have a question that I can't find the answer to in the documentation.
I have activated the Loop/Rewind option. I have used this code to jump to next section when you reach the last slide 

```
if(nextSlideIndex == '0'){
               $.fn.fullpage.moveSectionDown();
            }
```
But how can I go to the previous section if I go back from the first slide?
Hope you understand.

**Comment by alvarotrigo** [comment]
Fullpage.js provides that feature in [the scroll horizontally extension](http://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).

**Comment by peterboruplund** [comment]
Great, will this extension also work by clicking on the prev and next arrow? and not only the mousewheel

**Comment by alvarotrigo** [comment]
> will this extension also work by clicking on the prev and next arrow?

Sure, the arrows will keep their default and expected behaviour :)
