### ISSUE TITLE
How to stop the animation when landing on a slide

### ISSUE THREAD

**Issue by mart1989** [alvarotrigo/fullPage.js#2788]
Hi, my issue is that I am treating each horizontal slide as its own page on my website, sothat I can send out links to a specific slide and have someone view it.

This works already, but at the moment it looks messy because it scrolls through all the previous slides and sections before landing on the slide I want to show. Is there a remedy to this?

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/236
