### ISSUE TITLE
Conflict with flickity.metafizzy.co

### ISSUE THREAD

**Issue by jd2912** [alvarotrigo/fullPage.js#2789]
Hi
I'm working a website that has two sections and in the 2nd section would like to use flickity slides.
I'm able to setup the sliders, however the slider actions are disabled. Is there any setting to over ride them?

Thanks

**Comment by alvarotrigo** [comment]
Please read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

You might have to initialise flicity in the `afterRender` callback.

**Comment by jd2912** [comment]
Thank you. The issue is resolved.
