### ISSUE TITLE
Auto-slide a selected slide section of a multiple slide sections.

### ISSUE THREAD

**Issue by Dzeg** [alvarotrigo/fullPage.js#2791]
### Description
I would like to know if is possible auto slide selected slide section(s) of a multiple slide sections? using `$.fn.fullpage.moveSlideRight();`
``` html
<div id="fullpage">
    <div id="section-1" class="section"> <---- only first auto slide
	<div class="slide"> Slide 1 </div>
    </div>
    <div id="section-2" class="section section">
	<div class="slide"> Slide 1 </div>
    </div>
    <div id="section-3" class="section section">
	<div class="slide"> Slide 1 </div>
    </div>
</div>
```

**Comment by alvarotrigo** [comment]
Sure. Check this topic https://github.com/alvarotrigo/fullPage.js/issues/532

**Comment by Dzeg** [comment]
@alvarotrigo Maybe because my english I didnt make my self understand. I've already have implemented auto slide  in the afterRender callback and I stop it when is moved to other section. My question is that I have a site with 4 sections 3 of them have slides with different purposes and content but, Im wondering how can I affect only the first section to make it auto slide... because my implementation affects all the 3 slides.

**Comment by Dzeg** [comment]
@alvarotrigo Maybe because my english I didnt make my self understand. I've already have implemented auto slide  in the `afterRender` callback and I stop it when is moved to another section in the `onLeave` callback. My question is that I have a site with 4 sections 3 of them are horizontal slider with different purposes and content but, I'm wondering how can I affect only the first section to make it auto slide... because my implementation affects all the 3 slides. 

``` javascript
afterRender: function () {
    slideTimeout = setInterval(function () {
    $.fn.fullpage.moveSlideRight(); <<<<<------- this affect to all my horizontals sliders I just need to one of them not all.
}, 5000);
```

**Comment by Dzeg** [comment]
Or maybe you are refering me to: [#532/comment](https://github.com/alvarotrigo/fullPage.js/issues/532#issuecomment-264719847) ?

**Comment by alvarotrigo** [comment]
>     $.fn.fullpage.moveSlideRight(); <<<<<------- this affect to all my horizontals sliders I just need to one of them not all.

Where for the `active` class in the section you want. Make use of the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs).

`if($('#section2').hasClass('active')`

**Comment by jloguercio** [comment]
> > ```
> > $.fn.fullpage.moveSlideRight(); <<<<<------- this affect to all my horizontals sliders I just need to one of them not all.
> > ```
> 
> Where for the `active` class in the section you want. Make use of the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs).
> $.fn.fullpage.moveSlideRight(); <<<<<------- this affect to all my horizontals sliders
> `if($('#section2').hasClass('active'))`

i got the same issue, how can i archieve this?

**Comment by alvarotrigo** [comment]
@jloguercio you can't move slides of other sections.
If you need to restart them to the first slide, you can make use of the [Reset Sliders extension.](https://alvarotrigo.com/fullPage/extensions/reset-sliders.html)
