### ISSUE TITLE
page stop scrolling >>

### ISSUE THREAD

**Issue by nuruddinbadawi** [alvarotrigo/fullPage.js#2794]
### Description
I have simple page has as sections, one of those sections i need to jump on it from other sections.

      <section>
            <a class="goToRelated">Jump to related post</a>
       </section>
       <section>
           <a class="goToRelated">Jump to related post</a>
       </section>
       <section>
           <a class="goToRelated">Jump to related post</a>
       </section>
       <section id="related_part">
             // I want to jump to her. 
            <div class="section">
                  ///// Related Post Content ///// 
            </div>
       </section>

**The code i using :** 

      <script>
          $(document).ready(function () {

              $('#related_part').fullpage();

              $('.goToRelated').on('click', () => {
                  $.fn.related_part.moveTo();
               })
           });
      </script>

**The problem is :**

1 - Stop Page scrolling, No scroll in page.
2- The scroll working after add autoScrolling: false.

**User Story:** 

I want to add link in section to jump to Related Post section.

And thanks for helping.

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any shortcut for that. You'll have to read the docs and see what features you can use from it to accomplish it.
