### ISSUE TITLE
Hi, i have a trouble. I added a div in a section. A fixed height, width and i added the style 'overflow-y:scroll;'. Overflow scroll is showed there, but the page scroll time the page jump to next section. In that particular div how avoid scroll jump function.???

### ISSUE THREAD

**Issue by akhilsukumaran** [alvarotrigo/fullPage.js#2796]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
