### ISSUE TITLE
Section # not being appended to URL

### ISSUE THREAD

**Issue by ndwl** [alvarotrigo/fullPage.js#2798]
I've implemented previous next links however when they are clicked the new section isn't being appended to the URL where as when you scroll the new section is being appended.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
