### ISSUE TITLE
Drag and Move extension and autoScrolling:false on mobile

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2799]
I've added Drag and Move extension to my fullpage with expectations to have a better UI then scrolling horizontal slides. But in fact drag and move extension is blocking even the vertical scroll and whole website is not accessible with mobile. (we tested on 3 devices all are same). Chome on Samsung and Xiaomi is shaking whole webpage and Safari on IPhone5 S is doing better but hides content of the last page. 

If I use responsiveSlides: true, - all got ruined ! 
with responsiveSlides: false and autoScrolling: true, and scrollBar: false it's more or less ok, but still it's not worth to deploy to production as it is not perfect.

**Comment by alvarotrigo** [comment]
I've replied you by email. 
There's a new option added in the dev version of the Drag And Move extension. 

I'll release it soon. But you got it in your inbox.

**Comment by pgrohosky** [comment]
I am also seeing extremely poor performance across mobile browsers with the dragAndMove extension. Using autoScrolling: true, and scrollBar: false despite multiple fixes, with ranged improvements of performance but nothing worth launching. Has this been fixed?

**Comment by alvarotrigo** [comment]
@pgrohosky I'll have to investigate it when I have some time! It definitely doesn't look as smooth at it should! 
On the meanwhile, please [contact me](https://alvarotrigo.com/#contact) if you want a refund.
