### ISSUE TITLE
Add the current section class to the <body>

### ISSUE THREAD

**Issue by eduarddotgg** [alvarotrigo/fullPage.js#28]
how to add active section data-anchor to body class? or add menu anchors to body class.

**Comment by Mikdadali** [comment]
i want to just add simple 1 class to boy because i want to change the header background when scroll is it possible?

**Comment by alvarotrigo** [comment]
@Mikdadali see my video tutorial here regarding how to use [fulpage.js's css state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to trigger css changes:
https://www.youtube.com/watch?v=qiCVPpI9l3M

**Comment by Mikdadali** [comment]
thank you i have already done that using that classes thanks again
