### ISSUE TITLE
examples not work on mobile

### ISSUE THREAD

**Issue by pkinga** [alvarotrigo/fullPage.js#2802]
### Description
I am new here.I am reading the demos.When i opened the web [https://alvarotrigo.com/fullPage] on mobile,it just showed the first section,i could not scroll it down.I don't not why.How could i make it work on mobile?

**Comment by alvarotrigo** [comment]
Please specify mobile phone and OS.

**Comment by pkinga** [comment]
@alvarotrigo Thanks for your response.I know why now,it's not the plugin's business but the internet.
