### ISSUE TITLE
Menu links don't work on anchors that begin with a slash

### ISSUE THREAD

**Issue by justinjereza** [alvarotrigo/fullPage.js#2803]
### Description

Anchors don't work if the id starts with a slash such that a target URL link becomes "http://example.net/#/foo" as an example. On the other hand, "http://example.net/#foo" works as expected.

### Link to isolated reproduction with no external CSS / JS

The problem is reproduced at https://jsfiddle.net/zug82bb1/4/

### Steps to reproduce it

Only the "Baz" menu link scrolls to the Baz section. The other menu links with anchors that begin with a slash don't work.

### Versions 

Windows 10 64-bit, Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by alvarotrigo** [comment]
Why would anyone want to use those anchors? Honest question :)

**Comment by justinjereza** [comment]
Haha. Fair point.

Honestly, it's just because I think they look better that way in the address bar. It's easier to see where the beginning of a path specified in the hash fragment is (http://example.net/#foo/bar vs http://example.net/#/foo/bar). Angular does the same thing with https://angular2.realworld.io/#/article/how-to-train-your-dragon-30ps16 as an example.

**Comment by alvarotrigo** [comment]
Feel free to provide a pull request for it. I'll mark it as an enhancement.

**Comment by justinjereza** [comment]
Ok, thanks.

**Comment by alvarotrigo** [comment]
Now possible in the dev branch, to be merged in  2.9.5.
