### ISSUE TITLE
Media Query CSS not recognized on mobile

### ISSUE THREAD

**Issue by amurray04** [alvarotrigo/fullPage.js#2805]
I have some CSS trying to hide a div when the screen width gets below a certain size. This doesn't look like it is getting picked up within the media query on a mobile device (iphone) but is being recognized in a browser on a desktop. Any way reason why this is happening or a way to solve it?

Example of media query:

```
@media screen and (max-width : 768px) {
    .about-text {
        display: none !important;
    }
}
```

**Comment by alvarotrigo** [comment]
Not fullpage.js related. 
Probably due to your viewport media tag.

**Comment by apricotrs** [comment]
I ran into the same issue.
It happens only when I turn on the device emulation of developer tool, and seems that the viewport width is set to 980px with the feature and thus the query would not be triggered.
I didn't check it on mobile devices though.
