### ISSUE TITLE
Pure Javascript version

### ISSUE THREAD

**Issue by kkashou** [alvarotrigo/fullPage.js#2806]
I understand the javascript version is still in alpha phase but just was wondering would you still use it for production live site? Also, when do you think it will be out of the alpha phase?

Thanks

**Comment by alvarotrigo** [comment]
It might contains some bugs, but those bugs might not be applicable to your site. It all depends on your site and your initialisation. 

> Also, when do you think it will be out of the alpha phase?

Not a date in mind, but hopefully before the end of this year.
