### ISSUE TITLE
parallax and fadingEffect on slides

### ISSUE THREAD

**Issue by denyo256** [alvarotrigo/fullPage.js#2807]
I want to mix parallax on scrolling and fadingEffect on slides. Unfortunately, if I active both plugins at the same time, the slides after the first are positioned outside the viewport.

Is it possible to active parallax only for sections?

**Comment by alvarotrigo** [comment]
> Is it possible to active parallax only for sections?

Have you tried activating fading effect only for slides? 

`fadingEffect: 'slides'`

**Comment by denyo256** [comment]
> Have you tried activating fading effect only for slides?
Yes I did.

**Comment by alvarotrigo** [comment]
I haven't tried using both, I'll reply you whenever I find some time. A bit busy [travelling](https://twitter.com/IMAC2/status/882578027162587136) at the moment!

**Comment by jk171505** [comment]
I have the same problem, slides only: `fadingEffect: 'slides'`.
Parallax breaks fading effect. 
With `fadingEffect: true` and parallax activated only sections are fading in and out, slides like above are broken.

**Comment by alvarotrigo** [comment]
This can now be done using `parallax: `sections`` and `faddingEffett: 'slides'`.
