### ISSUE TITLE
Too many sections breaks nav (part of it falls off screen)

### ISSUE THREAD

**Issue by TheOddler** [alvarotrigo/fullPage.js#2809]
### Description

I'm making a page that has a lot of sections, over 50. On the side I want to show the nav dots. However because there are so many sections some of the dots fall off the screen. Any way to solve this?

I tried fiddling with css to make the list wrap, but couldn't figure it out.

### Versions 
fullpage version 2.9.4
Firefox 54.0.1
Windows 10 and OSX Sierra

**Comment by alvarotrigo** [comment]
> I tried fiddling with css to make the list wrap, but couldn't figure it out.

Modify the CSS file that defines their styles. 
But... i wouldn't recommend having 50 navigation dots! :D

**Comment by Fuji100** [comment]
Check out my css regarding the NAV. I solved it, Many bullets break nicely, and the line of bulltest is always fixed at the bottom (with some px distance). I.e. you do not have to position the line 60px above bottom to have space in case the line breaks on smaller screen. 
https://camclose-test.lima-city.de/fullpage/index.html#portraits/01
