### ISSUE TITLE
Multiple SlideLoad event after resizing winfow

### ISSUE THREAD

**Issue by mayetf** [alvarotrigo/fullPage.js#2810]
Hi,
I used the Fullpage.js framework for my team and it's a really good framework : thanks for that.

We are currently facing an issue when we resize the page. Indeed after a page resize, the entire site is refreshed and display the first(home) page before displaying back the page the user was on.
The issue on our side is that we have an event triggered based on the PageLoad event which in this particular case is fired 2 times, but as the user is not seeing something new, we don't want to have our event fired in case of windows resize.
Is that another event/trigger to use for such logic?

On another topic, I'd like to know if there is a way to know what triggered a slide change(keydown,mouse scroll or other)?
Thanks for the support
REgards
Franck

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction with no external CSS or JS to fullpage.js and the less possible HTML code. You can use jsfiddle, codepen or your own server.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
