### ISSUE TITLE
Different nav tooltip color on different sections

### ISSUE THREAD

**Issue by vytenisstaugaitis** [alvarotrigo/fullPage.js#2815]
Im expieriencing a problem which could be common but havent found a solution yet. The website which im working on has different color slides, black and white so if tooltip is white it wont be visible on white background. Is there a way to assign different tooltip styles for different slides since tooltip div is out of main fullpage div. (its easy with scrollbar activated but its not a solution in this case)

**Comment by alvarotrigo** [comment]
Use CSS for that. Overwrite the css if necessary with !important.
