### ISSUE TITLE
Lazy loading issue with scrollOverflow

### ISSUE THREAD

**Issue by sarcand** [alvarotrigo/fullPage.js#2816]
When using scrollOverflow with lazy loading feature. The innerHeight of the content is not re-calculated after image loaded. So even if the content is larger than the view port the scrollbar is not activated. When forcing a rebuild on first load of the section. The innerHeigh is applied correctly and the scrollbar is added as expected.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by stevesweets** [comment]
Has there been a fix applied to this?  Have this problem as we speak.

**Comment by alvarotrigo** [comment]
> Has there been a fix applied to this? Have this problem as we speak.

It hans't. But it is as easy as calling `$.fn.fullpage.reBuild()` after the image gets loaded. 
Probably on the `afterLoad` callback is enough. Perhaps something like this


```javascript
$("#myImage")
    .on('load', function() { 
          console.log("image loaded correctly"); 
          $.fn.fullpage.reBuild()
      })
```

**Comment by stevesweets** [comment]
Thanks for the quick response btw :) 👍

**Comment by alvarotrigo** [comment]
This no longer takes place on fullPage.js version 4. 🥳
