### ISSUE TITLE
Can someone provide a general explanation of how fullpage js works?

### ISSUE THREAD

**Issue by 00dav00** [alvarotrigo/fullPage.js#2817]
It would be nice it someone can provide "the big picture" of how fullpage js works internally.
I see it creates a lot of elements via JS but I'm not completely sure how they work or why are they created for. 

Thanks!!

**Comment by alvarotrigo** [comment]
Detects the wheel event.
Uses the css3 translate3d properties or the `top` one to move a container with sections. This is what creates the animation when combined with a css3 `transition` property or a jQuery `animate` function.
