### ISSUE TITLE
Page skipping

### ISSUE THREAD

**Issue by antonettis** [alvarotrigo/fullPage.js#2818]
Hi, I'm having a very similar problem to [issue #72](https://github.com/alvarotrigo/fullPage.js/issues/72) however it's been closed so I wasn't sure where to post this. Your answer suggested that it might have something to do with sections ID however none of my sections have IDs. I also tried changing the css value to false as someone suggested but it didn't work either, I also tried to add the different lines of code proposed in the answers.

Here is the [preview of my website](https://github.com/antonettis/portfolio) so you can see what the problem is. Basically when you get to the 3rd or 4rth section, the page skips to the next section on its own.
[Here is my code](https://github.com/antonettis/portfolio/tree/gh-pages).

I'm using Safari on Sierra. I tried using other browsers but the problem seems to be consistent. Let me know if you need more information. If someone could take a look at my code I would be very grateful, this is seriously starting to drive me crazy!

Apart from that, I had no problems with fullPage and I'm very happy with it, thank you so much for your hard work! I'm excited for my website to go live and this wouldn't have been possible without fullPage :)

**Comment by alvarotrigo** [comment]
Have you checked the `name` parameter too? 
As detailed in the docs:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).

I'll close the issue until you provide an isolated reproduction with the minimum HTML as possible to reproduce it and no external CSS or JS to fullPage.js.

**Comment by antonettis** [comment]
Hi, thank you for your answer.

I have taken a closer look at my code and I figured out that my problem was because of the background image on one of my slides. This is my code for it:
`	#slide1{
    background-image: url(img/chess.jpg);
	background-repeat: no-repeat;
	background-size: auto 100%;
	}
	`
To fix it I tried to add the background image the same way you did in your demo, so I wrote this:
`	#slide1{
    background-image: url(img/chess.jpg);
		background-size: cover;
		background-attachment: fixed;
	}
	`

But when I do this the image does not display at all! Do you have any idea about what could be causing this?

Tried Safari, Chrome and Firefox.

I removed all other content from my html page, I am not sure if this is what you were asking for, here is [the link to my new html](https://github.com/antonettis/fullpage/blob/gh-pages/index.html). If you need to see a preview of the problem the link is [here](https://antonettis.github.io/fullpage/). Thanks again.

**Comment by alvarotrigo** [comment]
You'd better ask in other place such as stackoverflow.com.
That seems more a CSS issue than a fullPage.js one.

**Comment by antonettis** [comment]
OK, thank you for your time! 👍

**Comment by taiyrbegeyev** [comment]
@antonettis Did you find out the solution for your problem? I have got the same issue

**Comment by alvarotrigo** [comment]
@taiyrbegeyev see my first answer. See your JS console too fo find out if you have errors.
