### ISSUE TITLE
Please help me with setAllowScrolling.

### ISSUE THREAD

**Issue by tarasbilozir** [alvarotrigo/fullPage.js#2820]
Hello, alvarotrigo
Thank you for fullpage.js that's really nice package.

Could you tell me when (in afterLoad or any other method?) should I use $.fn.fullpage.setAllowScrolling() to disable scrolling between sections but allow scrolling in specific section?
I mean: when I'm moving from section 'n' to section 'm', please disable scrolling between sections but let me have an ability to scroll the content of section 'm'.

P.S. setAllowScrolling disables scroll properly when there is no scroll in that section. But if there is a scroll for the section's content, then the section changed and scroll blocked. (seems to be a bug)

Thanks in advance!

**Comment by tarasbilozir** [comment]
To reproduce the problem just try to disable scrolling for section, but allow for current section's content.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by tarasbilozir** [comment]
Alvaro, thank you, but I have already fixed this issue.
Have a nice day.

**Comment by taraskhvyl** [comment]
@tarasbilozir , how did you fixed it?

**Comment by tarasbilozir** [comment]
@taraskhvyl 
`new fullpage('#fullpage', {`
	`onLeave: function(origin, destination, direction){`
		`if(preventScroll){`
			`return false;`
		`}`

                `if(allowScroll){`
			`return true;`
		`}`
	`}`
`});`
