### ISSUE TITLE
section names

### ISSUE THREAD

**Issue by Simon1012** [alvarotrigo/fullPage.js#2821]
hi,

i am using fullpage js and its works perfectly for everything except for one thing. i dont know how to change the section names so that you dont have a url like: servicekiosk.nl/#firstsection.
can someone tell me how to hide these section names in url or change them?

grtz,
Simon

**Comment by alvarotrigo** [comment]
Use the anchors option or the attribute data-anchor.
Read the docs for more info and see the available examples.

**Comment by alvarotrigo** [comment]
> can someone tell me how to hide these section names in url or change them?

If you want to get rid of them do not use the anchors option and do not use data-anchor attribute sin the sections. Again, all in the docs and examples.
