### ISSUE TITLE
Adding Drop Down Menu on NavigationTooltips Menu

### ISSUE THREAD

**Issue by khaliljan** [alvarotrigo/fullPage.js#2822]
### It is Simple, as shown in this image, I want a Drop-Down (click/hover) menu with in a navigationTooltips menu the in fullPage.js (Vertical Navigation Dots)
![click hover drop down](https://user-images.githubusercontent.com/22653042/28821613-57436f2a-76cb-11e7-9395-7774246c8eef.jpg)

### I tried this, but didn't succeeded. 
` navigationTooltips:
['Section One','Section Two','<ul><li>Section Three  <ul><li>Sub Section one</li><li>Sub Section Two</li> </ul>  </li></ul>','Section Four','Section Five'],`

### Any solution is appreciated in any way to add sub sections for one/two of my sections.

**Comment by alvarotrigo** [comment]
You'd better ask this kind of questions in other place such as stackoverflow.com.
This forum is to provide support for fullPage.js issues and bugs, not for specific questions regarding how to do something for your site.
