### ISSUE TITLE
Defining a section footer

### ISSUE THREAD

**Issue by osvaldoM** [alvarotrigo/fullPage.js#2823]
### How to define a  different footer for each section?

I would like to know if is there is curently a way to have a different footer placed in the bottom  for each section in my full page. 

I already have different footers as can be seen in this  [example](https://uxmz.github.io/mopa-redesign) ,however , I don't know how to style them to stick to the bottom by using fixed positioning for instance.

**Comment by thisisfed** [comment]
You'd better ask here for this kind of help @osvaldoM: https://stackoverflow.com

**Comment by alvarotrigo** [comment]
@thisisfed well said! :) 

That's a CSS knowledge question. It doesn't belong to this forum which treats fullpage.js bugs or issues.
