### ISSUE TITLE
Question: Have A Slide no longer load after scroll (except if page refreshed)

### ISSUE THREAD

**Issue by GeorgeWL** [alvarotrigo/fullPage.js#2824]
### Description
We've got a use case of wanting there to be an "Welcome" slide that's the start slide on initial load, but then isn't visible after you scroll past it.

Just wondered if there's a way pre-built or if we'd need to custom code it?
How would you recommend if the latter?

### Versions 
Latest Stable Fullpage
Chrome 5.9.0
Windows 10 
Windows Desktop

**Comment by thisisfed** [comment]
A simple use of CSS and JS will do the trick. Just create a 100%width / 100%height div external from Fullpage. Then you can slide it up after x time with Fullpage to follow from the bottom of the page.

**Comment by alvarotrigo** [comment]
Or just use the method setAllowScrolling within a callback to deny scrolling up when you are in that section.
Read the docs for more info.
