### ISSUE TITLE
Request: LESS/SASS versions of the CSS

### ISSUE THREAD

**Issue by GeorgeWL** [alvarotrigo/fullPage.js#2825]
### Description
Would like this for the included CSS, as the use of variables and mixins can make the whole thing far quicker to modify and through compiling all css into one large file can reduce load of all pages.

### Versions 
fullPage 2.9.4
Chrome 5.9.0
Windows 10
Windows Desktop

**Comment by kukac7** [comment]
https://github.com/alvarotrigo/fullPage.js/issues/1802#issuecomment-261225535

**Comment by GeorgeWL** [comment]
aha okay. Well, I know the default has been changed from `.sass` to `.scss`

**Comment by alvarotrigo** [comment]
Thanks for answering @kukac7 !
Nothing to add. 

fullPage.js uses a very small CSS file and I as a developer don't see the need of LESS or SASS to maintain it. 
Additionally you can also find in here the minified version of it.
And you can make use on your own of built tools such as WebPack, Grunt, Gulpt etc to combine whatever CSS files you need.

**Comment by alvarotrigo** [comment]
Unless you can provide with a real advantage of using them, I don't see why changing to them now.

**Comment by GeorgeWL** [comment]
set the variables for recurring things at the top, let's the developer not have to find-replace the css, just set once at the top, and not have to touch any other code.

**Comment by alvarotrigo** [comment]
Yeah I see what you mean. That's in case you want to modify the CSS file right?
Well, I'm afraid I'm not familiar with the syntax so right now I won't provide such file. Maybe I'll consider it for a future.
Thanks anyways for the suggestion!

**Comment by GeorgeWL** [comment]
cool :)

It's remarkably similar to standard CSS btw, just with some JavaScript-style variables, AND NOT OR operators and with even more levels of CSS nesting

**Comment by GeorgeWL** [comment]
A good example of SASS being used is this one:
https://github.com/vmitsaras/js-offcanvas/tree/master/src

They've separated out any CSS which might be modified sometimes into two files of mixins and settings, to make it easier for the end users.
