### ISSUE TITLE
New Extension suggestion

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2826]
Hi Alvaro, just as a suggestion I would love the implementation of a minimal lightbox that permit to zoom the content of a slide and let you scroll every section's slide zoomed. I would love it :)

REF.:https://github.com/noelboss/featherlight

**Comment by alvarotrigo** [comment]
Thanks for the suggestion! But I'm under the opinion that a real responsive site doesn't need zoom :)
Therefore I don't think I'll go for this idea.
Thanks anyways!
