### ISSUE TITLE
parallax on all visible slides / directions not just 

### ISSUE THREAD

**Issue by eliteproxy7** [alvarotrigo/fullPage.js#2828]
seems like the parallax does not show on the slide that is moving UP and away and the first slide never has any one it.. can we have it where it has parallax on all slides at all times?

**Comment by alvarotrigo** [comment]
Try changing the `type` property of the parallax configuration. There are two values "cover" or "reveal".
You can test it yourself on the [demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html) and learn more about them in the [parallax extension docs](https://github.com/alvarotrigo/fullPage.js/wiki/Extension---Parallax).
