### ISSUE TITLE
Hide section in desktop media query

### ISSUE THREAD

**Issue by jk171505** [alvarotrigo/fullPage.js#2829]
It's a duplicate of #80 but it's not answered...

I want to hide some section in specific media query. How can I deal with the scrolling problem or how can I tell the plugin to skip this section in specific media query?

**Comment by alvarotrigo** [comment]
I'm afraid it is not possible at the moment. 
The best you can do is remove those sections with javascript under certain dimension. 

I'll mark it as a possible enhancement for the future.

**Comment by thisisfed** [comment]
I was able to remove them, I don't know how to readd them though.
Removed usign remove() or detach()

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2941

**Comment by MattAppleton** [comment]
just bumping this request... would be great to hide sections (and have hidden sections) without affecting scrolling.

**Comment by henryManektech** [comment]
it's 2021, Hide section without affecting scrolling is possible now?

**Comment by alvarotrigo** [comment]
It's 2021?? 😱 😱 😱 😱 
Didn't notice! :)

It's not possible yet.
But it's your lucky day! Notice the code is fully open source so you (or anyone else) can feel free to modify it to support such feature and provide a pull request so we can merge it in a future version.
