### ISSUE TITLE
Bootstrap & .table-responsive

### ISSUE THREAD

**Issue by ediblemanager** [alvarotrigo/fullPage.js#2830]
### Description

Scrolling horizontally when using bootstrap's table-responsive class on a table doesn't work.

I can't use scrollOverflow as I need to be able to vertically scroll in other sections. Using responsive options hasn't helped either.

I've read as many posts as possible on SO, have read all the issues already listed about Bootstrap and tables and have had a look through the source of fullPage. Before I go my merry hacking way, I wanted to see if I've missed anything fundamentally obvious that would help me.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

https://jsfiddle.net/ediblemanager/e757syhe/

### Steps to reproduce it
Load jsfiddle on a mobile device (viewing in mobile mode on devtools in Chrome doesn't show the bug).
Try to scroll the table.

### Versions 
Android 7, chrome.
Chrome OSX, mobile view (using devtools).

I've thought of the following fixes, provided in order of work:

- Destroy plugin when viewing section with scrollable table, then re-init plugin on leaving section
    - Use touch event to work out when user is trying to leave?
- Re-format data into non tabular format
    - Probably still going to need to scroll, so not ideal.

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements`.
Try this: https://jsfiddle.net/e757syhe/3/
