### ISSUE TITLE
If you $.fn.fullpage.silentMoveTo to a section the afterLoad is ignored?

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2831]
### Description
If you MoveTo a section the AfterLoad is correctly running but if you SilentMoveTo a section the AfterLoad is ignored or I am doing something wrong?

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/97tbk/2002/ — MOVE if you click on the menu you'll see that the class is added immediately after clicking

http://jsfiddle.net/97tbk/2001/ — SILENT MOVE if you click on the menu you'll see that the class is added just after clicking and going to another slide

PS: the JS is not working super fine I just made a quick one.

**Comment by alvarotrigo** [comment]
Working fine for me? 
http://jsfiddle.net/97tbk/2004/
