### ISSUE TITLE
First section translating to -7px on Y axis

### ISSUE THREAD

**Issue by joshwaiam** [alvarotrigo/fullPage.js#2832]
Good evening!

Before I report an issue, I just want to tell you that I attempted to create my own plugin for this very purpose before discovering yours.  It is absolutely fantastic! 

The one issue that I'm having in implementing it in a site I'm working on is that when scrolling back up to the first section, it is leaving a 7px gap at the bottom.  This doesn't happen when the page loads, but rather only when you scroll down to the next section and then back up.  It appears that the transform: translate3d() that is applied to the element calling fullpage() is calculating to -7px when scrolling back up, leaving a small gap.  I have been racking my brain to figure out why, but since it works fine when first loaded, I'm at a loss!  I have a workaround where I manually change the translate using the afterLoad method with the first slide, but am hoping that there may be a more smooth fix.

### Link to isolated reproduction with no external CSS / JS
I don't have an isolated link for this, but I do have it up online that I can send you if that will help.

### Steps to reproduce it
1. Load page.
2. Wheel down for next section.
3. Wheel back up to first section.

### Versions 
2.9.4

**Comment by alvarotrigo** [comment]
> Before I report an issue, I just want to tell you that I attempted to create my own plugin for this very purpose before discovering yours. It is absolutely fantastic!

Glad you like it!

> I don't have an isolated link for this, but I do have it up online that I can send you if that will help.

I'm not able to reproduce the issue in any of the online demos, therefore, please provide a link I can debug, ideally with the less minimum HTML and no external CSS or JS files to fullPage.js (isolated)

**Comment by joshwaiam** [comment]
I'm very sorry to have used your time on this.  I have been working hard on a site and didn't see GitHub notifications.  I have since moved past this issue and cannot recall where the code was in order to give you a code sample.  Thank you again for your fantastic plugin!

**Comment by Spacefuel** [comment]
Hi,
I have same issue. The content structure:
	<div id="fullpage">
		<div class="section" id="intro">
			<canvas id="canvas1"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas2"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas3"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas4"></canvas>
		</div>
	</div>

	$('#fullpage').fullpage({
				v2compatible: true, (new version callback does NOT work)
				autoScrolling:true,
                               afterLoad: function(anchorLink, index){
		              ///..........changing canvas sizes and drawing functions ....
        }


Initially, the container has a style:: height: 100%; position: relative; touch-action: none; transform: translate3d(0px, 0px, 0px);

When you return to the first slide, the container has a style:
height: 100%; position: relative; touch-action: none; transform: translate3d(0px, -7px, 0px); transition: all 700ms ease;
