### ISSUE TITLE
need to get on scroll event

### ISSUE THREAD

**Issue by jainheenaer** [alvarotrigo/fullPage.js#2833]
#Hi..
i need to fire an event on scroll event. 

```javascript
$(window).scroll(function(){
		if($(window).scrollTop()>50){
           alert('Hello');
		}else{
			
		}
	});
```
but above code is not working.

**Comment by joshwaiam** [comment]
I'm not the plugin author, but I debug a lot of code myself.  Why not take out the conditional statement and simply do:

$(window).scroll(function(){
    console.log('Scroll detected!  Window scroll top: ' + $(this).scrollTop());
});

That way you can see what the issue is - either scrollTop is not returning a value greater than 50 or something else is going on.

**Comment by alvarotrigo** [comment]
Read the [FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) you'll find your answer there.
