### ISSUE TITLE
Prallax + dragAndMove "fp-bg" issue

### ISSUE THREAD

**Issue by eliteproxy7** [alvarotrigo/fullPage.js#2835]
when I use dragAndMove on the slide with parallax (transition) it has the .fp-bg half way out of the area and you see white space 

here is a screen shot

![screen shot 2017-08-09 at 2 48 26 pm](https://user-images.githubusercontent.com/5486268/29138542-07d08d68-7d12-11e7-85a2-f2bc6fbcb0ab.png)

**Comment by alvarotrigo** [comment]
Please read the "Compatibility" information on the parallax [demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html).

> NOT compatible with the following fullPage.js features:
- The `fp-auto-height` feature
- Offset Sections extension
- Drag And Move extension
