### ISSUE TITLE
Larger section with no autoScrolling

### ISSUE THREAD

**Issue by jzhang172** [alvarotrigo/fullPage.js#2836]
### I tried Stackoverflow with no luck, so I've included it here:
https://stackoverflow.com/questions/45581630/fullpage-js-having-larger-sections-and-disable-scrolling-on-some-sections/45581688?noredirect=1#comment78122821_45581688

**Comment by alvarotrigo** [comment]
The only solution is to use the scrollOverflow option as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).
