### ISSUE TITLE
Does this plugin provide absolute footer?

### ISSUE THREAD

**Issue by listatt** [alvarotrigo/fullPage.js#2839]
Thanks for this great plugin. Does it provide absolute footer on last slide scroll? I don't want to displace it, just want to overlay last slide on scroll down.

**Comment by alvarotrigo** [comment]
Absolute to what?
Absolute to a section? Sure, just use `position:relateve` for the section.

Absolute to the site? Sure, just use `position:fixed` and place it outside fullPage.js wrapper. See [this demo](https://alvarotrigo.com/fullPage/examples/fixedHeaders.html).
