### ISSUE TITLE
ios devices like iphone etc hides background section on keyboard appear event

### ISSUE THREAD

**Issue by ondigit** [alvarotrigo/fullPage.js#2842]
### Description
ios devices like iphone etc. hides background section on keyboard appear event.

http://beta.hippeas.com/

Thanks in advance.

**Comment by brokoly250** [comment]
Hey ondigit,

I have a similar issue with the keyboard on Android.

When the keyboard appears there is a blank space after the section, i can´t find the solution for this.

Have you resolved this issue by yourself?

Thanks!

**Comment by ondigit** [comment]
<?php 
//Detect special conditions devices
$iPod    = stripos($_SERVER['HTTP_USER_AGENT'],"iPod");
$iPhone  = stripos($_SERVER['HTTP_USER_AGENT'],"iPhone");
$iPad    = stripos($_SERVER['HTTP_USER_AGENT'],"iPad");
$Android = stripos($_SERVER['HTTP_USER_AGENT'],"Android");
$webOS   = stripos($_SERVER['HTTP_USER_AGENT'],"webOS");

//do something with this information
if( $iPod || $iPhone || $iPad || $webOS ){
?>
<style>
.fp-section,
.fp-slide,
.fp-tableCell{
    height: auto !important;
}
</style>
<?php
}
?>



—
Thanks
Jinendra Mudhale
http://ondigit.com

**Comment by brokoly250** [comment]
Thank you very much for your fast reply. 

I will try your code later and i hope it works,  i have been all the morning fighting against this shit hahaha

Thank you very much one more time!

**Comment by brokoly250** [comment]
I tried but there isn´t way to make it work....

Thank you anyways!

**Comment by alvarotrigo** [comment]
@ondigit what exactly do you mean by "hides background section on keyboard appear event" ?
The result of `fitToSection: true`? Have you tried using `fitToSection:false`?

What's the behaviour you would expect?
