### ISSUE TITLE
possible Parallax / scrollOverflow interference: background-images lost on device orientation-change

### ISSUE THREAD

**Issue by mindshaped** [alvarotrigo/fullPage.js#2845]
When activating the parallax extension and the scrollOverflow option at the same time (parallax and scrollOverflowReset extensions are both active) and viewing the fullpage-slider on mobile and rotating the device, the background-images are lost and the empty (but still scrollable) sections are shown.

Link to the dev-site and actual URL where this happens: https://mihhaller.com/dev/faces-of-the-ocean/

### Steps to reproduce it
1. scroll down to second section (first picture that appears after the intro-text)
2. rotate the device to/from landscape/portrait

While trying to reproduce this, I disabled all fullpage-options one by one, as soon as the scrollOverflow option is being removed, the parallax backgroundimages are displayed fine also on orientation change.

The following fullpage.js options are active. the actual keys are present in the live version and the problem persists. 
`parallax: true,
scrollOverflow: true,
scrollOverflowOptions: {
        probeType: 3
},
scrollOverflowReset: true,
scrollOverflowResetKey: 'key here',
parallaxKey: 'key here',
parallaxOptions: { type: 'cover', percentage: 40, property: 'translate'}`

### Versions 
iOS 10, safari, tested on iPhone6/7
Android Jellybean on Marshall London phone, latest chrome version

when dragging & resizing the screen to the same dimensions on a desktop-device it seems to be working, as the orientation-change event is not being executed. 

in chrome developer tools with device mode active, the problem persists on orientation change.

thanks!
-Nico

**Comment by mindshaped** [comment]
while further debugging the problem, it looks like the generated translate styles on the fp-scroller element are causing the background image to disappear.

more specific the following code:
`transform: translate(0px, 0px) translateZ(0px); `

<img width="1278" alt="hidden" src="https://user-images.githubusercontent.com/815939/29408666-5362201a-8349-11e7-9cd8-0384034ee283.png">

<img width="1280" alt="visible" src="https://user-images.githubusercontent.com/815939/29408667-53682eec-8349-11e7-8815-83015cc8f031.png">

**Comment by alvarotrigo** [comment]
That's solved in the latest version. But it is not yet published. 
Please [contact me](alvarotrigo.com/#contact) with the email you used for the purchase and I'll send you the latest version of the parallax extension that fixes this issue.

**Comment by mindshaped** [comment]
Hey Alvaro,

Thanks for your response and awesome to hear that issues is fixed!

I purchased the extension via nico@mindshaped.com

looking forward to hearing back & updating the site with the latest version

best
-Nico

mndshpd

mindshaped.com
nico brühlmann
+41786197183
