### ISSUE TITLE
Linking to anchor tags without using the "anchors" option

### ISSUE THREAD

**Issue by josephbydeign** [alvarotrigo/fullPage.js#2847]
We use a custom CMS with user generated content so we can't use data-anchor to give our sections id's as these could be anything the user defines. 

Is there any way to link to, and smooth scroll (or jump), to #anchors? 

If not this may be something worth considering adding in the future 

Apologies if I missed something obvious

**Comment by alvarotrigo** [comment]
I don't know your internal problems, but you should be able to find a way to do so.
You can use the `data-anchor` attribute or the `anchors` options. 

Then you can use the fullpage.js methods such as `moveTo` to move to any section by index or anchor name.
