### ISSUE TITLE
afterSlideLoad show image when loaded

### ISSUE THREAD

**Issue by kermix** [alvarotrigo/fullPage.js#2848]
Hi,
I have something like this
```
<div class="section">
    <div class="slide">
         <img id="photo" data-src="/uploads/photos/@item.PhotoPath" style="display: none"/>
    </div>
</div>
```
I'm using build-in lazyLoading and now I want to fadeIn this img with afterSlideLoad when img is fully loaded, but I have no idea how to do this and Google do not help me.
Can any one explain me how to do this?

I'm trying to add this:
```
afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {
                    var loadedSlide = $(this);

                    loadedSlide.find("#photo").on("load", function () {
                        $(this).show();
                    });

                }
```

to my fullpage config, but nothing happens.

**Comment by alvarotrigo** [comment]
You'd better ask for those kind of questions in another place such as  stackoverflow.com.
This forum is to answer questions and issues directly related with fullPage.js.
