### ISSUE TITLE
Destroying and reiniting full page breaks all other js click events

### ISSUE THREAD

**Issue by jmona789** [alvarotrigo/fullPage.js#2849]
When I destroy fullpage using `destroy('all')` and reinit fullpage all the other custom js I've written does't seem to do anything, I have quite a few click functions which are no longer running.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
