### ISSUE TITLE
Dynamic height with fullpage.scrollOverflowReset.min.js

### ISSUE THREAD

**Issue by weiluri** [alvarotrigo/fullPage.js#2850]
Hello,

I just bought the plugin and encounter  a problem.  I have a div that grows dynamically on user action.
The problem is  that at load time is small and doesn't exceed the screen height so there is no scroller and it seems that there is no trigger for the plugin functionality in that case. after user interact on page a div become higher but it's content is hidden because there is no scroller for that section.
Can I solve it with your plugin to get it works for dynamically height dom elements?

Thank you,
  Uri

**Comment by alvarotrigo** [comment]
Take a look at the scrollOverflow option and the method `reBuild` that you should call after the user interaction to tell fullPage.js that it needs to check again the section's height.

**Comment by weiluri** [comment]
Thank you!
The reBuild function is what i nedded.
