### ISSUE TITLE
Issue : demo page need an update

### ISSUE THREAD

**Issue by khaled-nuur** [alvarotrigo/fullPage.js#2851]
# 3 errors in console at the [demo-page](https://alvarotrigo.com/fullPage/).
need simple update
-------------
![image](https://user-images.githubusercontent.com/28248852/29497195-4aefc996-85ec-11e7-90fc-d8519efbc9b5.png)
--------------
waiting for...:dizzy::dizzy:

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll solve them whenever I get back [from China](https://twitter.com/IMAC2/status/882578027162587136)! :)

**Comment by khaled-nuur** [comment]
closed and waiting for the solution
               ✨✨✨✨
