### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by jackiedao** [alvarotrigo/fullPage.js#2852]
I want to return the purchased product.
Very sorry, but I found that I do not need to use this js after purchase.
Please help me implement it
Thanks!

**Comment by alvarotrigo** [comment]
[Contact me](http://alvarotrigo.com/#contact) and let me know the email used for the purchase and the product you bought.

**Comment by jackiedao** [comment]
Email: daoxuannhut@gmail.com
Product : fullPage.js - Parallax.
Thank you for your support

**Comment by alvarotrigo** [comment]
Done

**Comment by jackiedao** [comment]
Thanks you!
Your product is very good, if possible I will buy it again
