### ISSUE TITLE
In Chrome, first slider image does not show if background= fixed & scrollOverflow = true

### ISSUE THREAD

**Issue by Fuji100** [alvarotrigo/fullPage.js#2853]
Hi Álvaro,
great template, but I have a major problem...

### Description
In Chrome: 
On a section with slides (several horizontal slides in the vertical section) the first image does not show at first if "background images = fixed" and "scrollOverflow = true."
After sliding to the second picture/slide and then sliding back to the first one it does show.
This happens only in Chome Desktop for PC (on Mac I could not check). Chrome mobile is working fine.

I have the latest version of everything (fp.js,  YOUR modified scollOverflow.js, Chrome etc... I have NO options on the scrollOverflow.js)

How to reproduce:
Step 1. Use Chrome Browser
Step 2. Call the page https://camclose-test.lima-city.de/fullpage/index.html which will show you section0.
Step 3. Scroll down to section1.
Step 4. Scroll further down to section2.
Result A: 
In section1 and section2 you will NOT see a background image.
(In section3 there is no bg img, so here it is ok that you do not see one...)

Step 5: Scroll back to section1 and click on the "next arrow".
Step 6: Click the "prev arrow" to go back to the first slide in section1. 
Result B:
You will see the background image.

Step 7: Scroll down to section2
Result C: 
You will notice that the bg-img in section1 is NOT fixed.

Step 8: Leave section1, scroll to section2,3,4 etc and scroll back to section1.
Result D: 
The bg img of secion1 displays, as it should have right away, but still is not fixed.

++++
So we have two issues here:

No 1:
It seem that fixed backgrounds and scrollOverflow TOGETHER are not working with Chrome, as the images are NOT fixed. 

No 2:
The images do not show righ away when the page is called.
(When setting scrollOverflow=false the images are fixed and do show right away, but then I do not have scollOverflow, which is super important. This means, Chrome DOES NOT have a bug with fixed images, but the fp.js integration of scrollOverflow does have a bug when used in Chrome... as scrollOverflow works well also in Chome even if the bg-images are fixed.)

+++
By the way - little design improvement for the template:
I changed the css related to the NAV buttons. Now they do really center also on small screens, even if there are many bullets (see section1 of my page).
Everything breaks nicely and stays centered on small screens.
The current fp.js/.ccs centers only if there are not more bullets than fit in ONE row on the small screen.
If there are more, the negative margin calculated by js moves everything off center.
The js-calculation of the negative margin on NAV is actually not needed, I overruled it with "0!important. Feel free to copy the changed values and attributes ;-)

So, thanks for the great template!
$$$
If this issue here is solved I will go buy some extensions and really use the template (the pics currently are NOT mine....)
(scrollOverflowReset &  resetSliders)

Cheers
Christian

**Comment by WMEGITHUB** [comment]
none yet

**Comment by alvarotrigo** [comment]
The provided URL for the reproduction no longer works.
In any case, that seems to be an issue with fixed positioned elements and translate3d transformations. That's a well known Chrome bug. Check [this answer](https://stackoverflow.com/questions/16901888/webkit-translate-fixed-background-attachment-bug) or [this another one](https://stackoverflow.com/a/31614745/1081396). 

> I changed the css related to the NAV buttons. Now they do really center also on small screens, even if there are many bullets (see section1 of my page).
Everything breaks nicely and stays centered on small screens.

Thanks, I'll review it!
