### ISSUE TITLE
Inconsistent behaviour of mouse & arrow-key navigation

### ISSUE THREAD

**Issue by Fuji100** [alvarotrigo/fullPage.js#2854]
Bug or feature? Or did I miss an option... 
When you are in a scrolling section (with overflow Scoll=true and overscroll content), the mouse will scroll the content until the end, then jump to the next slide below.
When you use the arrow keys to do navigate, the page with overflow-content jumps directly to the next slide below, instead of leading you through the scrollable content line by line or maybe 5 lines in one keystroke. 
I'd prefer the content to scroll through to the end with arrow-keys, for assesibility-reasons and for consistency.

(It did find the "function onkeydown(e)" in the js and turned it off... this results in the desired arrow-key scrolling, but at the end of the section it stops - it does not continue to the next slide below, as fp.js does not listen to the keys anymore...)

See here:
https://camclose-test.lima-city.de/fullpage/index.html#nudes/story

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1065
The issue stills open.

**Comment by Fuji100** [comment]
Sorry, I did not see that before.
However... slimscroll is also actve on mobile. On mobile the swipe does exactly what I and the others desire. So - to whatever the swipe logic is listening to the keyboard logic should listen to as well. I'm new to css and have no skill in writing js.... but the logic is there already for swipe, so it would just need to be transferred to keys?
