### ISSUE TITLE
Drag and Move extension issue, fitToSection issue, last section size issue

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2855]
Alvaro,

Can you access this jsfiddle ? 

[Removed link]

There are several issues, 
1 - Javascript error only if I use Drag and Move extension, 
2 - fitToSection: false , but it ignores it and jumps to section,  
3 - Have a look at the last slide, why it is so small ?

**Comment by alvarotrigo** [comment]
As I suggested you in a previous answer in other topic, please contact me [by email](http://alvarotrigo.com/#contact) if you believe it is a Drag And Move extension issue.
Otherwise, remove the dragAndMove file from the fiddle and post the new URL for the reproduction again.

**Comment by flyingbaba** [comment]
Alvaro, why link to my JSFIDDLE is removed ?

**Comment by flyingbaba** [comment]
> remove the dragAndMove file from the fiddle and post the new URL for the reproduction again.

Where can I get cdn dragandmove.js ? this is what I purchased from you ! How can I create fiddle with your extensions in this case ?

**Comment by flyingbaba** [comment]
Alvaro, answer me please !

**Comment by flyingbaba** [comment]
Alvaro, it's been a month I'm trying to contact you regarding to this issue and you are fooling around every time I write to you. Everytime these is a problem, either you don't want to open .zip archive or you don't like the JSFIDDLE provided or you can't open FTP for some reason. Shame on you dude...

**Comment by alvarotrigo** [comment]
@flyingbaba I've replied you by mail.

**Comment by flyingbaba** [comment]
> As per your comments on the github issues forum it seems you are really in a rush for the fix.
Unfortunately I can not provide you such service at the moment due to my current situation and therefore I'll happily provide you with a full refund if you are not happy with the service.

> Please let me know if you prefer me to refund you instead of solving the issue whenever I have the time for it.

Alvaro, 

I don't need refund, I need you to work on the issue.  

You gave me tons of troubles with your Drag and Move extension and before I was writing only e-mails informing you about the issues, now I will post everything here on github, so everyone will see how you give a support. 

Max

**Comment by alvarotrigo** [comment]
Read [the license terms](https://alvarotrigo.com/fullPage/extensions/license.html#for-unlimited-websites) regarding "Maintenance and support"

> Under no circumstances is Alvaro Trigo compelled to fix Software's bugs, to perform custom development or to write code for the Licensee.

At the moment I'm not able to provide you with the fast support you demand, threfore I provide you the option to get a full refund.
If you want me to fix the issue then you'll have to wait for me to fix it whenever I have the time for it.

You choose.
