### ISSUE TITLE
Drag and Move extension triggers other errors

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2856]
After purchasing Drag and Move extension and binding it to the project the whole page was broken. Alvaro recomended me to use dragAndMove: 'horizontal', which cuts half functionality of it but I agreed on that. 

But this extension triggers fitToSection issue, it is set to FALSE but page begins to jump on top of sections. Removing dragAndMove solves this issue. but hold on, we've payed for that, so kinda expect the functionality. 

Maybe in a combination with other options autoScrolling: false, scrollBar: true, it will not throw this errors, but in our case this is like this. 

[JSFIDDLE](http://jsfiddle.net/flyingbaba/ykkudycm/2/)

Then you charge people for plugins you develop, be kind to provide support! 
I feel very bad I started to work with fullPage.js instead of writing my own solution.

**Comment by alvarotrigo** [comment]
> Then you charge people for plugins you develop, be kind to provide support!

Apologies for the delay!
I do provide support, but it is not immediate and right now I'm travelling around China where I do not always have it easy to get internet access or time to answer every issue in 24 hours. 

I've replied you by email.
