### ISSUE TITLE
Getting the previous or initial state

### ISSUE THREAD

**Issue by bonucci** [alvarotrigo/fullPage.js#2858]
I there guys, im trying to get a animation done but i cant find any method for what im trying to do, in my case i wish in my menu when the mouse hoovers the link, t scrolls to the desired page, but it doesnt stays there, unless the user clicks on it, i ony need to go and after leaving with the mouse stays in the previous page, i made this small example:

```
//Initialize scroll page
            $('#fullpage').fullpage({
                anchors: ['home', 'services', 'sports', 'contact'],
                menu: '#menu'
            });


            $(".nav li a").hover(
                function() {
                    var url = $(this).attr('href');
                    $.fn.fullpage.moveTo(url.replace("#", ""));

                },
                function() {
var a= getleftPage;
                    $.fn.fullpage.moveTo(a);
                }
            );
```

I notice that there is onLeave method but that is on the initialization, is there other way?

**Comment by alvarotrigo** [comment]
You'd better ask these kind of questions in another place such as stackoverflow as your issue is more a Javascript one than a fullPage.js one.
