### ISSUE TITLE
Popup scrolling not working

### ISSUE THREAD

**Issue by jayeshm66** [alvarotrigo/fullPage.js#2859]
I have created costume popup modal. but when i open popup, i am unable to scroll popup instead of that page is scrolling, can be scrollable using browser scrollbar but not with mouse scrollbar,

I have given height and overflow:scroll to popup

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements` or the fullpage.js method `$.fn.fullpage.setAllowScrolling(false)` when opening the modal.

Check [this answer](https://stackoverflow.com/questions/38264469/block-scroll-on-modal-open) too.
