### ISSUE TITLE
scrollOverflow: true

### ISSUE THREAD

**Issue by Larraine** [alvarotrigo/fullPage.js#2860]
**scrollOverflow: true on mobile device**

I have searched and searched for an answer to this but cannot find the answer or understand any answers I find, how can I change scrollOverflow: true to scrollOverflow: false when viewed on a mobile device? I am already using responsiveWidth and fp-auto-height-responsive.

**Comment by alvarotrigo** [comment]
Duplicated of the open issue https://github.com/alvarotrigo/fullPage.js/issues/958
No proper solution for it yet.

**Comment by jonathan-bird** [comment]
Something like this?
```
$(window).resize(function () {
				if($(window).width() < 768){
				  $.fn.fullpage.setAutoScrolling(false);
				  $.fn.fullpage.setFitToSection(false);
				} else {
					$.fn.fullpage.setAutoScrolling(true);
				  $.fn.fullpage.setFitToSection(true);
				}
			});
```
