### ISSUE TITLE
Icon not included in overall height

### ISSUE THREAD

**Issue by ediblemanager** [alvarotrigo/fullPage.js#2863]
### Description
Icon at foot of section isn't included in overall height for scrollbars (using scrolloverFlow).

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/ediblemanager/u0sh660h/5/

### Steps to reproduce it
1. Scroll down to bottom section
2. Take a look!

### Versions 
Chrome shows this when emulating a mobile screen, and also on my Oneplus One.

I've been staring at this for days, and still at a loss.

Please, show me my idiocy!

**Comment by alvarotrigo** [comment]
That's not a fullpage.js issue but a CSS one.
Probably related with your style `.margin-bottom-20px`. You'd better ask somewhere else such as stackoverflow.com
