### ISSUE TITLE
[question] How do I hook into iScroll events?

### ISSUE THREAD

**Issue by nathanaelphilip** [alvarotrigo/fullPage.js#2864]
### Description
I’d like to know when a section is done scrolling, but I can’t figure out how to bind the scroll or scrollEnd event

### Versions 
Fullpage: 2.9.4

**Comment by alvarotrigo** [comment]
Look into the [vendor library docs](http://iscrolljs.com/) and check also [my answer here](https://stackoverflow.com/a/39369282/1081396).
