### ISSUE TITLE
Parallax Extension

### ISSUE THREAD

**Issue by bonucci** [alvarotrigo/fullPage.js#2867]
Hello, i have a question regarding the parallax extension, is it possible for example when the user uses the mousewell the app takes the parallax effect, but if the user uses the navigation  links to be used the normal fullPage.js transition?

**Comment by alvarotrigo** [comment]
The library or extension does not provide such feature, but you might be able to achieve it with the functions they provide such as `$.fn.fullpage.parallax.setOption('percentage', '0')`.
