### ISSUE TITLE
Not sibling elements

### ISSUE THREAD

**Issue by pixedelic** [alvarotrigo/fullPage.js#2869]
Is it possible to select not sibling elements? We need to display header and footer that are not siblings, but out of the container. Here is a very basic example: https://jsfiddle.net/pixedelic/7b44bzeo/1/ As you can see the element #footer is not included by your plugin. Am I missing something maybe?

**Comment by alvarotrigo** [comment]
No.
[The required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure) does not allow you to use any non sibling elements. 
Not even have any container within the plugin wrapper as you do with `id="content"`

**Comment by adamrobinson** [comment]
It's a shame this is the case as im running into this issue.  The required structure means i can't mark up my html in the most valid way

`<main>
   <section>
   <section>
   <section>
</main>
<footer></footer>`

I'd like to be able to see the footer without moving it into the <main> element.

**Comment by alvarotrigo** [comment]
As I said, that's not possible.
