### ISSUE TITLE
Parallax extension not working

### ISSUE THREAD

**Issue by bonucci** [alvarotrigo/fullPage.js#2870]
Hello, im trying to run  the extension parallax but is not working.

My code:
  ```
<script type="text/javascript" src="js/fullpage.parallax.min.js"></script>
      <script type="text/javascript" src="js/jquery.fullpage.extensions.min.js"></script>
```

```
 $(document).ready(function() {
//Initialize scroll page
            $('#fullpage').fullpage({
                anchors: ['inicio', 'servicos', 'desportos', 'paisagem', 'qualidade', 'contacto'],
                menu: '#menu',
                parallax: true,
                parallaxKey: 'mykey',
            });

 });
```

Error:
```
 Uncaught SyntaxError: Unexpected token < jquery.fullpage.extensions.min.js:7
index.html:525 Uncaught TypeError: $(...).fullpage is not a function
    at HTMLDocument.<anonymous> (index.html:525)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.K (jquery.min.js:2)
```

**Comment by alvarotrigo** [comment]
Please [contact me](http://alvarotrigo.com/#contact) and let me know the email you used for the purchase as well as the URL where you are having the issue.

**Comment by bonucci** [comment]
Sent the email, waiting for response, thanks

**Comment by sssnakes** [comment]
Hi, I'm also having plenty of trouble with this. There's no clean example page provided, which is making it difficult.

**Comment by bonucci** [comment]
Cleaner version
http://relvadossinteticos.com/beta/teste.html

Cumprimentos,
Mauro Bonucci


website: http://maurobonucci.com
email: mail@maurobonucci.com
tel: +351 961 697 951

*Nota de Confidencialidade:* Esta mensagem (e eventuais ficheiros anexos) é
confidencial (art.º 108.º EOA), protegida por sigilo profissional e
destina-se exclusivamente ao seu destinatário. Se for recebida por quem não
seja o seu destinatário, solicita-se a sua devolução e destruição imediata.
A divulgação do conteúdo, quando não autorizado, é passível de
responsabilização civil e criminal.

2017-08-29 15:51 GMT+01:00 sssnakes <notifications@github.com>:

**Comment by bonucci** [comment]
hello, i sent you a email with a cleaner version, please check
