### ISSUE TITLE
Crash in Chrome with Window Resizer Plugin

### ISSUE THREAD

**Issue by grafyte** [alvarotrigo/fullPage.js#2871]
### Description

When viewing the demo of the Horizontal Scroll extension with Chrome (Version 60.0.3112.113 (Official Build) (64-bit)) - the scroll behaviour doesn't work, and I get an error in the console.

I managed to isolate the problem to a clash with a plugin called "Window Resizer" (v 1.9.1.6) which presumably breaks the functionality in some way.

https://chrome.google.com/webstore/detail/window-resizer/kkelicaakdanhinjdeammmilcgefonfh

I wanted to report this, although don't have a jsfiddle or codepen link since this is on your own demo page.

### Steps to reproduce it
1. Install Chrome plugin "Window Resizer"
2. Visit Horizontal Scroll extension demo page
3. Try to scroll (to no avail)

### Versions 
Mac OS Sierra 10.12.5
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Window Resizer Extension v 1.9.1.6

**Comment by alvarotrigo** [comment]
What does the Chrome plugin does? 
Why not using Chrome inspector for the resolutions? 

> and I get an error in the console.

Can you tell us which error you get?

**Comment by grafyte** [comment]
The extension allows me to save a few window sizes (both viewport and window) - I don't use it much, just sometimes, so it's not a major issue - but others might and maybe it has highlighted an issue with other things. I don't know.

The error I get is:

'Uncaught TypeError: o is not a function
    at Pe (jquery.fullpage.extensions.min.js:8)
    at HTMLDocument.Ne (jquery.fullpage.extensions.min.js:8)'

**Comment by alvarotrigo** [comment]
Can you try it with the normal version (not the extensions one) and with the unminified code?
Then please let me know what error you get and in which line.

**Comment by grafyte** [comment]
It works fine with the normal version - it's only the extension (only when needing to scroll horizontally) and if I prettify (AKA, non-minify) the code, it's on line 458 and line 520.

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it.
