### ISSUE TITLE
Does not work overflow scroll if fullpage.js is running

### ISSUE THREAD

**Issue by drtvader** [alvarotrigo/fullPage.js#2873]
Hello!
I have a problem.
When fullpage works on the whole page, overflow auto / scroll does not work in IPad.
When you turn off the script, everything works fine.

JS:
```javascript
$('#fullpage').fullpage({
            //Navigation
            menu: '#fullpage-nav',
            // continuousVertical: true,
            anchors:['slide1', 'slide2', 'slide3', 'slide4', 'slide5'],
            controlArrows: false,
            slidesNavigation: true,
                css3: true,
                scrollingSpeed: 1000,
                autoScrolling: true,
                touchSensitivity: 20,
                continuousVertical: true,
            afterRender: function(){
                setInterval(function(){
                    $.fn.fullpage.moveSectionDown();
                }, 12000);
            }
        });
```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

Also, if you want to have scroll bar in a section you should be using the scrolloverflow option as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by drtvader** [comment]
http://manulife.odditystudio.com/home-page_v2.html
When we open the page. On the first slide link: your goals.
Opens the block, which on the iPad should be scrolled. But because of the script it is not. The block is outside the #fullpage

**Comment by alvarotrigo** [comment]
Place it inside the wrapper and use the fullpage.js option `normalScrollElements` for it.
