### ISSUE TITLE
offsetSections: true not working when using paddingTop

### ISSUE THREAD

**Issue by omikron** [alvarotrigo/fullPage.js#2876]
### Description
Basic setup of fullpage.js with offsetSections set to true not working in a specific setup.

### Link to isolated reproduction with no external CSS / JS
[Removed Link]

### Steps to reproduce it
1. First 3 sections have various "data-percentage" set but do not show to be decreasing in size.
2. Scroll down to see each top 3 slides not have any decreased height.

### Versions 
Chrome 60 on OSX

**Comment by alvarotrigo** [comment]
You are not using the extension, you are using the limited extensio (fullpage.offsetSections.limited.min.js), which is limited to only work on the demo page.

Use the one you got when purchasing the extension and you'll be fine.

**Comment by omikron** [comment]
Apologies, I was up late last night looking for a publicly hosted version of the JS(fullpage.offsetSections.min.js) to use for the demo, I missed that the demo one was limited.

Originally I was using the one hosted from a dev site which I have now put in place of the limited version in the Codepen. It doesn't change the problem, however, offsetSections still does not work.

https://codepen.io/50foot/pen/Vzqeby

**Comment by omikron** [comment]
After a little more testing I have realized that it seems like offsetSections:true is incompatible with paddingTop.

I didn't see that anywhere in the docs. We use paddingTop on this site to offset for a top fixed menubar. Is this a bug?

**Comment by alvarotrigo** [comment]
> I didn't see that anywhere in the docs. We use paddingTop on this site to offset for a top fixed menubar. Is this a bug?

Seems to be a bug. I'll re-open it again.

**Comment by omikron** [comment]
Is there an alternative method/workaround I could use to get spacing at the top beside using the paddingTop method?

**Comment by alvarotrigo** [comment]
Sure. Just use your own wrapper inside the section and add the padding top to it.

```html
<div class="section">
    <div class="section-wrapper">
          Content
    </div>
</div>
```

**Comment by omikron** [comment]
I tried that, but the content does not stay centered properly.

https://codepen.io/50foot/pen/NvoWww

**Comment by omikron** [comment]
Any update on this?

**Comment by alvarotrigo** [comment]
> Any update on this?

Clearly not as the issue stills open.
