### ISSUE TITLE
Content of a section disapers

### ISSUE THREAD

**Issue by bonucci** [alvarotrigo/fullPage.js#2877]
In one of my sections i have some long content, but fullPage.js hides the content above, is almost impossible having some long text our having images above each other.

**Comment by thisisfed** [comment]
Con un nickname del genere non meriteresti neanche un aiuto : )
https://alvarotrigo.com/fullPage/examples/scrolling.html

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
