### ISSUE TITLE
Bug with offsetSections when used with scrollOverflow

### ISSUE THREAD

**Issue by omikron** [alvarotrigo/fullPage.js#2878]
### Description
With both offsetSections and scrollOverflow enabled, sections without scrollable content sometimes get the content wrapped in container ".fp-scrollable" and with height set - this is causing it to no longer be centered.

### Link to isolated reproduction with no external CSS / JS
[Removed link]

### Steps to reproduce it
1. Load link - usually content is loaded with the top sections already wrapped with .fp-scrollable causing them to not be centered vertically.
2. Resize width of browser and when you stop resizing the content will go back and forth from center to top aligned.

### Versions 
Chrome 60 and Safari 10.1.2 on OSX

**Comment by alvarotrigo** [comment]
> this is causing it to no longer be centered.

What do you mean by that? The section is taking the whole viewport as it should. Then creating the internal scroll bar. What's wrong there?

> Load link - usually content is loaded with the top sections already wrapped with .fp-scrollable causing them to not be centered vertically.

The top sections have so little content that no scrollable bar is created, even when i reduce the width of the viewport considerably. Can you please post a picture of it?

> Resize width of browser and when you stop resizing the content will go back and forth from center to top aligned.

I'm in section 2 (Section set with 'data-percentage="80"') and I'm not able to reproduce that either. 
Please [contact me](https://alvarotrigo.com/#contact) with more codepen links if you need to.

**Comment by omikron** [comment]
You can see the problem here;

https://www.youtube.com/watch?v=eMdUs7BvO3c

**Comment by alvarotrigo** [comment]
Thanks for that, I was able to see what you mean now and to reproduce it on your fiddle.
I'll investigate it!
