### ISSUE TITLE
scrolloverflow not working

### ISSUE THREAD

**Issue by cheon7886** [alvarotrigo/fullPage.js#2881]
Hello. I'm trying to using your script, but scrolloverflow not work only except for first page, and other pages aren't scrolled properly.
the demo is here: https://codepen.io/cheon7886/pen/oemejL
and if i upload it at github, it does not work at all.. http://cheon7886.github.io/SPROUT/

**Comment by alvarotrigo** [comment]
> and if i upload it at github, it does not work at all.. http://cheon7886.github.io/SPROUT/

You should be including the scrolloverflow file before fullpage.js. Please try again.

**Comment by cheon7886** [comment]
Thanks for your help. Then how can i fix the problem that other pages are not scrolled properly?

**Comment by apeguero24** [comment]
I am having the same issue with scrolloverflow.

**Comment by cheon7886** [comment]
I solved this problem. this occurs if element id is directly inserted in anchors.

**Comment by alvarotrigo** [comment]
> I solved this problem. this occurs if element id is directly inserted in anchors.

I'll close the issue then.
