### ISSUE TITLE
Keeping background image height 100% across devices

### ISSUE THREAD

**Issue by icakostika** [alvarotrigo/fullPage.js#2882]
I'm using the example from fullscreen backgrounds, I've done nothing special, but it is clipping my image very small by the time it gets to mobile. I have the image background set to no-repeat center center is one of the only things I have changed in CSS. I would like the image height to stay at 100% and only overflow/clip the width, not sure if this is possible.
The effect I am going for is the same as this background image responsive across sizes: https://northamerica.triangl.com/

**Comment by alvarotrigo** [comment]
That's a CSS issue and not a fullPage.js one. You should be asking those kind of questions in other places such as stackoverflow.com where they'll be able to help you much better than here.
