### ISSUE TITLE
Different effect for fullpage.js slide image (fixed position)

### ISSUE THREAD

**Issue by Wymowny** [alvarotrigo/fullPage.js#2885]
### Description
What I'm trying is to achieve effect shown on this video: 

https://www.youtube.com/watch?v=Wq-jyRTzpDw 

My current solution with fullpage.js & parallax looks like this: 

http://warsawwatches.pl/

The problem is that 'current' watch goes to the top after scrolling (autoscroll is on) instead of 'changing height to zero from bottom'. I'm not sure if this effect is even possible with those plugins but can I buy some other effect instead of parallax or additional library? This watch should have fixed position and be covered by next one without moving. 

I found expected result on this website (cars images): http://porschevolution.com/

If you would have any other possible solution I'll be thankful for your input.

**Comment by alvarotrigo** [comment]
You can try using a fixed positioned watch image and `css3:false`. (as fixed positioned elements are not supported very well with translate3d transitions at the moment)

But in any case, you'd better ask this kind of questions in a other place such as stackoverflow.com

This forum treats fullpage.js issues, bugs and questions regarding its usage. Yours is a very specific scenario and fullpage.js doesn't provide any built in solution for it I'm afraid.
