### ISSUE TITLE
take activation code

### ISSUE THREAD

**Issue by sgulcin** [alvarotrigo/fullPage.js#2887]
I bougth offsetsection extention but never had a mail for activation code. I send a mail ask for it. Noone has replied yet.

I need that code until tomorrow. Can you help about it?

**Comment by alvarotrigo** [comment]
That's weird. I have replied all support emails.
What's your email address? 
Are you sure you introduced it correctly when purchasing the extension? 
If so, have you checked the spam folder just on case?

Feel fee to reply this on private by the contact form in my site.
