### ISSUE TITLE
[pure javascript] Auto-height issue

### ISSUE THREAD

**Issue by yogie89** [alvarotrigo/fullPage.js#2888]
I love pure javascript method. to make our site performance better that before. but when i want to using the library for auto-height.
im using class "fp-auto-height" it doesnt work at all for the height.

is that true, if this pure javsacript cant provide auto-height ?

thank you

**Comment by alvarotrigo** [comment]
Not provided in the javascript version. It hasn't been updated in a long time and not planning to work on it at the moment due to lack of interests in it.
