### ISSUE TITLE
Fullpage only working locally

### ISSUE THREAD

**Issue by ZeAntwan** [alvarotrigo/fullPage.js#2889]
For a small website, I am using both Fullpage and Parallax.js plugin (https://github.com/wagerfield/parallax).
Everything works fine locally, but when put on my server, Fullpage doesn't load, leaving only a Loading error in the Console

`"Échec du chargement pour l’élément <script> dont la source est « http://labs.studiotwan.com/vrtex/js/jquery.fullPage.min.js »."`

Here is the website (couldn't figure out how to make it on codepen.io) : http://labs.studiotwan.com/vrtex/ 

Thanks

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
