### ISSUE TITLE
Trigger event when user scrolls past last section

### ISSUE THREAD

**Issue by richgcook** [alvarotrigo/fullPage.js#2890]
Is it possible to trigger an event once the user tries to scroll past the last section? I'd like to trigger a notification at this point but wasn't sure if `onSlideLeave` would work as it's not actually leaving the slide. Any thoughts?

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/2494

**Comment by alvarotrigo** [comment]
I'll close this one.

**Comment by richgcook** [comment]
@alvarotrigo Are you sure it's the same/related? I'm wanting to trigger an event once the user tries to slide past the last section (when not set to loop).

**Comment by alvarotrigo** [comment]
@richgcook yeap it is related if you want to trigger it when they use the mousewheel or trackpad.
Right now there's no mouse callback and therefore nothing will get triggered when the user tries to scroll the last section.

**Comment by richgcook** [comment]
@alvarotrigo Thanks for the reply. I'm guessing I could, on mousewheel/trackpad scroll... if the slide in the last slide do something, right?

**Comment by alvarotrigo** [comment]
Yeah but as I said fullpage.js doesn't provide such callback at the moment. You would have to code it yourself, and it can be a bit more tricky when dealing with kinetic scrolling from Apple trackpads and mouses and some other laptops.

**Comment by richgcook** [comment]
Hmm damn. I can check current index with total index length though, right?

**Comment by richgcook** [comment]
@alvarotrigo 

I actually thought this could work:

```
onLeave: function(index, nextIndex, direction) {
    if (nextIndex == 1 && direction == 'down') {
        console.log('works');
        return false;
    }
}
```

If I add `continuousVertical: true,` then I would expect it, on the last section, if the user tries to scroll it would return false. However, even though I get the console.log it still goes back to the top. Any thoughts?

**Comment by richgcook** [comment]
I thought `loopBottom: true,` might've been better suited but my `onLeave` function doesn't want to call when using the && operative with direction == down. I dropped the direction, and instead of `return false` I started using `$.fn.fullpage.setAllowScrolling(false, 'down');` but that only set scrolling to false after it had looped. I returned to `return: false` and seems to work okay 🙏🏻

**Comment by alvarotrigo** [comment]
@richgcook if you think the callback is failing for any reason or not behaving as it should, then please create a new issue with an isolated reproduction for it and I'll take a look at it whenever I can.
