### ISSUE TITLE
DragAndMove and scrollBar:true - Javascript error on mobiles

### ISSUE THREAD

**Issue by flyingbaba** [alvarotrigo/fullPage.js#2892]
Extension DragAndMove causes the Javascript error on jquery.fullpage.extensions.min.js
This error exist only if DragAndMove is used.

https://www.youtube.com/watch?v=xc9CUc57YSQ

**Comment by alvarotrigo** [comment]
Probably only on the emulator and not in real devices. But I'll check it.

**Comment by alvarotrigo** [comment]
Javascript error has been removed in the dev branch. 
Still need to deal with the warning regarding passive events.

**Comment by alvarotrigo** [comment]
The Javascript error has been solved in the dev branch.
The Javascript warning regarding passive events still need to be fixed.
