### ISSUE TITLE
Fullpage scrollOverflow function

### ISSUE THREAD

**Issue by daerlenl** [alvarotrigo/fullPage.js#2893]
Hello,

I'm using fullPage for a long time, but I found an issue. I think its the iScroll that makes the problem.
Unfortunately I can't use jsfiddle.net or codepen.io to explain my problem.

**What is the problem?**
If you're going to this link: www.twitter.com/daerlenl/status/906426626111655936 you see fullPage 2.7.8 working great. But the latest version fullPage 2.9.4 doesn't scroll to the end, it stays hanging.

www.daerle.nl _running on fullPage 2.7.8_
www.daerle.nl/github _running on fullPage 2.9.4_

Does someone have the same issue?

With kind regards,
Dylan van Aerle

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction without any external CSS or JS file to fullPage.js and the less minimum HTML code.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
