### ISSUE TITLE
Remove section after leaving it

### ISSUE THREAD

**Issue by JakeSchroeder** [alvarotrigo/fullPage.js#2894]
I am using the afterLoad callback function and checking to see if I have loaded the second section and then I remove the first section. But the issue is, when I remove the first section it scrolls past the second section to the third. I tried different callback functions and the same effect occurred. 

Here is my code 
```javascript
$(document).ready(function () {
    $('#fullpage').fullpage({
        afterLoad: function(anchorLink, index) {
            if (index === 2) {
                setTimeout(function () {
                    
                        $(".intro").remove();

                }, 700);
            }
        }
    });

});

```

### Steps to reproduce it
1. [Call afterLoad callback function]
2. [check to see if the section you are on currently is the right index in this case (index:2)]
3. [remove the first section in this case (index:1 or .intro)]

### Lastest Version
[Chrome, Mac OSX]

**Comment by alvarotrigo** [comment]
Removing sections is not supported.
