### ISSUE TITLE
Links to sections and scroll up

### ISSUE THREAD

**Issue by Meteoromancie** [alvarotrigo/fullPage.js#2896]
Hello,

I made a HTML page with two links to another HTML page to go « section1 » or « section2 ».
My sections use « scrollOverflow », they contain several pictures.

When I click on « section1 » all is fine, I can scroll down to « section2 »
When I click on « section2 » and scroll up, I go directly on top of the « section1 », but I would like to go on the bottom of « section1 ».

I tried bigSectionsDestination: ‘bottom’, but it doesn’t work.

Is that possible to do that ?
Here an example of the problem now : http://erosionpower.com/Fullpage.html

Thanks,
![pbfullpage](https://user-images.githubusercontent.com/31831245/30253433-49893822-9685-11e7-82cb-ee75a4199987.jpg)

**Comment by alvarotrigo** [comment]
Use the extension Scrolloverflow Reset. See a [demo here](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html).

**Comment by Meteoromancie** [comment]
Hi,

Thanks for the quick answer.

When I read the description of the plugin it says « when leaving it so it will always be at the start »
But I would like to be at the bottom of section1 when I leaving section2, not at the top. 

Is that possible to choose top or bottom reset with the plugin ?

**Comment by alvarotrigo** [comment]
> Is that possible to choose top or bottom reset with the plugin ?

It is at the bottom by default if you use the scrollOverflow option.

**Comment by alvarotrigo** [comment]
Sorry I missunderstood you. You seem to be talking about sections with fp-auto-height ? 
Can you please provide a jsfiddle or codepen illustrating the issue? I don't see anything clear on the url you provided.
