### ISSUE TITLE
Grids hidden by the script

### ISSUE THREAD

**Issue by DGtalDesign** [alvarotrigo/fullPage.js#2898]
Awesome script but I have a problem with it when it comes to CSS grids. It automatically adds styles to hide the grids and disables the CSS animations assigned to the grids. Know how to fix this?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen with no external CSS or JS files and the less minimum HTML code for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
