### ISSUE TITLE
Cover video backgrounds on IE

### ISSUE THREAD

**Issue by sssnakes** [alvarotrigo/fullPage.js#2899]
Hey, loving fullPage.js so far, everything has been running smoothly for my current project on Chrome, but having great difficulty now towards the end whilst we try to cover the background video in IE 11? Currently auto-corrects itself to 'contain', with large borders, no matter what I try, is this just an IE WebM/ MP4 issue?

Would love to know if this is an unavoidable issue or if there is still some CSS that can be wrangled into making it work but I'm currently at a loss.

<img width="1119" alt="screen shot 2017-09-12 at 08 46 17" src="https://user-images.githubusercontent.com/13465861/30311868-87b1a73e-9797-11e7-9ad2-4f07b4e242e8.png">

Thanks

**Comment by sssnakes** [comment]
Apologies, a friend of mine quickly recommended this workaround, which seems to work thusfar:

`<video width="" height="100%" loop muted data-autoplay>`

**Comment by alvarotrigo** [comment]
Glad you found a solution. In any case, this is not a fullpage.js issue but a CSS one.
