### ISSUE TITLE
Query Parameters attached after the anchors do not persist through section change events.

### ISSUE THREAD

**Issue by TheCrinventor** [alvarotrigo/fullPage.js#2900]
### Description
Whenever I append query parameters in the url of a page after the section-anchor, these query parameters are removed on section change event. These query parameters should be retained even after a section changes. 

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/#3rdPage?sampleQuery=Parameter

### Steps to reproduce it
1. Open the above sample link.
2. Scroll to next section
3. Observe that the query parameters have been removed from the page url.

### Versions 
All browsers.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll mark it as an enhancement!

**Comment by alvarotrigo** [comment]
URL parameters have to be placed before the `#` symbol.
That seems to be [the proper way of using them](https://stackoverflow.com/questions/12682952/proper-url-forming-with-query-string-and-anchor-hashtag).

I'll therefore close this issue.
