### ISSUE TITLE
ui slider doesn't work with fullPage.js

### ISSUE THREAD

**Issue by SergeyJyravlev** [alvarotrigo/fullPage.js#2901]
Hello.

I'm using ui slider and fullPage.js. But ui slider not draggable if option `scrollOverflow: true`. If this option will be set to false that ui slider will be work is correct. Please help me with this issue. 

```
$(".wrapper").fullpage({
        verticalCentered: false,
        css3: true,
        scrollOverflow: true,
        normalScrollElements: '#order-budget-slider',
        scrollOverflowOptions: {
        },
        afterRender: function () {
             $("#order-budget-slider").slider({});
       },
   });
```

**Comment by alvarotrigo** [comment]
You might want to check the [iScroll docs](http://cubiq.org/iscroll-5) to see if you find anything you can configure there and pass it to fullpage.js through the `scrollOverflowOptions` option.

You can even try to ask in [its github issues forum](https://github.com/cubiq/iscroll/issues).

**Comment by pyramidion** [comment]
For future reference, I was able to get this working using:

`scrollOverflowOptions: {preventDefault: false}`
