### ISSUE TITLE
scrollHorizontally not working 

### ISSUE THREAD

**Issue by sbotezatu** [alvarotrigo/fullPage.js#2902]
I am trying to create a page to scroll horizontally when using the mouse wheel.
and I am getting the following error when I move the mouse wheel:

> Uncaught TypeError: o is not a function at Pe (jquery.fullpage.extensions.min.js:8)
 
I am loading these files:
```html
<script type="text/javascript" src="scripts3/fullpage.scrollHorizontally.limited.min.js"></script>
<script type="text/javascript" src="scripts3/jquery.fullpage.extensions.min.js"></script>
````
and initialize the plugin like this:
```javascript
        $(document).ready(function() {
            $('#fullpage').fullpage({
              sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
              anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],
              menu: '#menu',
              slidesNavigation: true,
              scrollHorizontally: true,
              scrollHorizontallyKey: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            });
        });
```

Note: I purchased the extension and got the key 

What am I missing here? Thank you very much

**Comment by alvarotrigo** [comment]
You are using the file from the demo (fullpage.scrollHorizontally.limited.min.js) and that won't work for you.
You first need to purchase the extension and use the file you get when you purchase it.

**Comment by sbotezatu** [comment]
Hi Alvaro,

It worked fine.

Thank you

**Comment by satuweb** [comment]
Hi Alvaro, 
I would like test the scrollHorizontally in my local web site, but it doesn't work fine (it ignored the mousewheel). How can I do this?
Thanks

**Comment by alvarotrigo** [comment]
@satuweb firs you have to purchase it. Then you can try it. 
Make sure to read the docs regarding [how to use extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).

**Comment by satuweb** [comment]
@alvarotrigo Thank you for the answer. I know the purchase process, but I want know if possible to test in localhost the extension before to purchase it.

**Comment by alvarotrigo** [comment]
@satuweb no. You need to purchase them in order to try them. But remember you have a 30 days money back guarantee as long as you do not generate any activation key. Pleas read the [fullPage.js Refund Terms](https://alvarotrigo.com/fullPage/extensions/license.html#refund) of the license.

**Comment by germanpaglia** [comment]
Hello Alvaro, how are you? Buy both licenses now. But I'm trying to test it on localhost and horizontal scrolling is not working for me.

**Comment by alvarotrigo** [comment]
It comes with a demo file, open it and inspect the code and make sure to also read the file "How to use it.html"
