### ISSUE TITLE
Scroll fast through sections without waiting for the current section to slide in completely

### ISSUE THREAD

**Issue by kollew** [alvarotrigo/fullPage.js#2904]
Hi, thank you so much for this awesome plugin. 

I will use a quite long transition and during the transition it is unfortunately not possible to "skip" a section by using the mousewheel. Is there an option to scroll fast through sections without waiting for the current section to slide in completely?

Thanks!

**Comment by alvarotrigo** [comment]
> Is there an option to scroll fast through sections without waiting for the current section to slide in completely?

Nop. And not easy to do it due to the kinetic scrolling behaviour in some devices such as Apple trackpads and mouses.

Related with: https://github.com/alvarotrigo/fullPage.js/issues/1654 as it's about the same problem, kinetic scrolling detection.
