### ISSUE TITLE
featherlight.js and normalScrollElements

### ISSUE THREAD

**Issue by weiluri** [alvarotrigo/fullPage.js#2905]
### I have this js lib featherlight.js to handle lightbox on my  page. 
on some cases the lightbox content is bigger/longer then the screen so I've added the overflowing div class to the normalScrollElements property on the fullpage definitions. 
it is working fine regarding the scroll functionality but on some cases clicking on the "X" of the lightbox (which closes it and remove it's html from the dom), is not "releasing" the page and the user can't scroll the page after closing the lightbox. 
This bug is not stable and not happening on every click on the "X" of the lightbox.
also clicking on the lightbox overlay while it is open, which also does the same thing (closing the lightbox and removing it's html from dom), is not causing the bug and every thing is functioning just fine regarding the fullpage scroll.
i've tried to cancel the event on click on the "X" and just triggering  the click on the overlay but it is still causing the bug. 
if i remove the class from the normalScrollElements on my fullpage code then everything is ok but i have no scroll when needed on that element.
i've tried invoking $.fn.fullpage.reBuild();  after clicking on the  "X" but it didn't help.
also tried to remove the related class before clicking on the "X" but fullpage still not refreshing it's behavior and page scroll remains locked.
can i make some refresh to the fullpage or to the normalScrollElements or something like this to make fullpage normalScrollElements updated so it won't consider this class a part of the normalScrollElements  anymore?
You can see the reproduction of it here:
https://www.robotemi.com

### Steps to reproduce it
1. [click on the green plus sign on the upper right corner of page]
2. [click on the "X" in the lightbox that will be opened]
3. [try to scroll the the page after the lightbox closes.  if it is scrolling try to repeat these stages a few times and it will surely happen after a few tries]

Thank you,
  Uri

**Comment by thisisfed** [comment]
I use the same lib and I do not have this problem.
You can try something like this:

$(document).on("click",".featherlight-close-icon",function(){$.fn.fullpage.setAllowScrolling(true)})
$(document).on("click",".featherlight-close-icon",function(){$.fn.fullpage.setKeyboardScrolling(true)})

**Comment by weiluri** [comment]
Thank you very much! 
It solves the issue.
just one add - should be called with setTimeout to run after popup closed
