### ISSUE TITLE
Parallax animation breaks if onLeave returns false

### ISSUE THREAD

**Issue by dazjohnson** [alvarotrigo/fullPage.js#2906]
Try the following with the parallax extension enabled:

```
var temp = false;

$('#whatever').fullpage({
    onLeave: function (index, nextIndex, direction) {  
                 if(temp == false){
                    temp = true;
                    return false;
                }else{
                    return true;
                }
    }
});
```

You'll notice that the background image no longer parallaxes.

Let me know if you're happy for me to do a codepen, but it will involve uploading the parallax lib.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Using `return false` within the `onLeave` callback will prevent the section to slide up or down, therefore there's no animation to be performed.

What I noticed is that scrolling down seems to work fine, just not doing anything, but when scrolling up again, keeping on the same section as it should, it applies the transformation to the background when it shouldn't, as the section stills the same and did not move at all. 
Is this last problem the one you are referring to ?

**Comment by alvarotrigo** [comment]
Fixed on the dev branch.
