### ISSUE TITLE
How to hide navigation dot for footer?

### ISSUE THREAD

**Issue by kosarlukascz** [alvarotrigo/fullPage.js#2908]
Hello, i use this config

```
<script type="text/javascript">
    $(document).ready(function() {
        $('#fullpage').fullpage({
            anchors: ['firstPage', 'secondPage', '3rdPage', 'footer'],
            navigation: true,
            navigationPosition: 'right',
            responsiveWidth: 900,
            afterResponsive: function(isResponsive){

            }

        });
    });

</script>

```

I need hide dot from navigation for footer
`<div class="section fp-auto-height" id="#footer">`

How?

**Comment by alvarotrigo** [comment]
Use [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to hide it. 

For example adding the following CSS that makes use of the state class will do it:

```css
.fp-viewing-section4 #fp-nav{
     display:none
}
```

**Comment by kosarlukascz** [comment]
I know that. But, i want remove dot for footer section with auto height. I won't remove hide in footer section scrolling nav.

**Comment by alvarotrigo** [comment]
Sorry I don't understand what you mean. Can you try to explain it with another words or use an example in jsfiddle or codepen to illustrate your issue?

**Comment by kosarlukascz** [comment]
Sorry for my really bad english. [Check this picture](https://i.imgur.com/vt8whXx.png), i need remove footer dot in all section.

**Comment by alvarotrigo** [comment]
Use css selector for the last child. That's a question you should be asking in other place such as stackoverflow.com as it is not a fullpage.js related one but a css knowledge one.

**Comment by kosarlukascz** [comment]
Thank you, sorry for that. It's working correct now.

**Comment by localnetwork** [comment]
If you have a dynamic sections like you don't know how many sections you have per page in a fullpage container, you can also do this in afterLoad function. This time i use hasClass function in jquery.

`afterLoad: function(section, origin, destination, direction){

	// this is the current/active section.
 	if($(this).hasClass('site-footer')) {  
	    console.log('footer!'); 
	    
	    $('#fp-nav').addClass('hide-nav');
	}else {
	    $('#fp-nav').removeClass('hide-nav');
	}
},`

**Comment by alvarotrigo** [comment]
@localnetwork thanks for pointing that out!
