### ISSUE TITLE
解决了一个bug

### ISSUE THREAD

**Issue by fkdswfwqfet** [alvarotrigo/fullPage.js#2909]
### Description
在1个锚点下有2屏需要滚动的时候，点击菜单时，滑动鼠标和键盘按下会没效果。

解决办法是修改1612行，如下，加了个判断
if(v.element.length>1)
        $(v.element[0]).addClass(ACTIVE).addClass(COMPLETELY).siblings().removeClass(COMPLETELY);            
else
        v.element.addClass(COMPLETELY).siblings().removeClass(COMPLETELY);
//最好加上下面这段代码，
$(SECTION_NAV_SEL).find(ACTIVE_SEL).removeClass(ACTIVE);                
$(SECTION_NAV_SEL).find('li').eq(v.sectionIndex).find('a').addClass(ACTIVE);  
//或者
$(SECTION_NAV_SEL).find('li > a').removeClass("wj-active");                
$(SECTION_NAV_SEL).find('li').eq(v.sectionIndex).find('a').addClass("wj-active");  

### Versions 
2.9.4

**Comment by alvarotrigo** [comment]
Can you please use english to describe the issue?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
