### ISSUE TITLE
Scroll to the bottom

### ISSUE THREAD

**Issue by gaz12** [alvarotrigo/fullPage.js#2911]
Hi!
I have some site http://adobeg.bget.ru/bank/
I need to scroll to the second slide. The second slide has a height bigger than the screen height and has a scroll. I need to move from the first to the second slide was at the bottom of the second slide.
Slide now https://snag.gy/nUh0MR.jpg
What I need https://snag.gy/fknSFT.jpg

**Comment by alvarotrigo** [comment]
Not something fullPage.js provides. But you can probably achieve that with javascript or looking into the [iScroll docs](http://iscrolljs.com/).

**Comment by gaz12** [comment]
Already looked.
var myScroll = new IScroll('.wrapper');
option myScroll.scrollTo(0, -100) must solve the problem, but I don`t know what var set instead of myScroll becase isrcoll plugin initialized inside the fullpagejs.

**Comment by alvarotrigo** [comment]
Look into [my answer here](https://stackoverflow.com/a/39369282/1081396) where you'll be able to learn how to extract the iScroll instance from each section.

**Comment by gaz12** [comment]
Thank you very much!
