### ISSUE TITLE
Scrollable on scrollEnd

### ISSUE THREAD

**Issue by TylerOlthuizen** [alvarotrigo/fullPage.js#2914]
Hello , I have a quick question/issue. I want to change the z-index on my footer when my scrollable is finished scrolling or the footer is revealed. I noticed iScroll has an scrollEnd function but I couldn't seem to get it working. Any suggestions?

http://96.30.9.8/~wildpine/

**Comment by alvarotrigo** [comment]
Take a look at [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/2912) and feel free to try to use it.

Right now fullPage.js doesn't provide a way to deal with it. 
But you can get that information but accessing the iscroll object for the section. Check [my answer here](https://stackoverflow.com/a/39369282/1081396) for more details on how this can be achieved.

**Comment by TylerOlthuizen** [comment]
Got it working , thanks! XD
