### ISSUE TITLE
Is it possible navigation as canvas?

### ISSUE THREAD

**Issue by bissolli** [alvarotrigo/fullPage.js#2915]
Sorry about the title, I couldn't find a way to explain what I need in a few words.

Basically I would like to know if is it possible invoke cascade fullPage.js, as on the following example.

 https://transfer.sh/17MHy/cascade.png

Imagine as each bock is a section where I have vertical and horizontal scrolling... I know for the first level (vertical and horizontal) I can do it, what about the second level?

**Comment by alvarotrigo** [comment]
> Imagine as each bock is a section where I have vertical and horizontal scrolling

Not possible I'm afraid.
