### ISSUE TITLE
dots nav on large monitor

### ISSUE THREAD

**Issue by p3k074** [alvarotrigo/fullPage.js#2916]
Hi, I have page container set to max-width  1200px. On bigger monitor like 1920px navigatioon dots stretching to right side outside container with page content. 
Its possible put nav  to specific DIV ? or maybe its other way to solved it ?

Thnx

**Comment by alvarotrigo** [comment]
> On bigger monitor like 1920px navigatioon dots stretching to right side outside container with page content.

Not sure to understand what you mean by that. Can you provide a link or an image to illustrate the issue?

**Comment by p3k074** [comment]
Sure , here is pic :

![2017-09-25 02_20_07-horizontal navigation dots - fullpage](https://user-images.githubusercontent.com/32250234/30788181-6a013da2-a198-11e7-8476-eb19fb8d86da.jpg)


I need move dots fro mwhite to orange :)

**Comment by alvarotrigo** [comment]
Two options:

- Use CSS to style the existent element (#fp-nav)
- Use your own navigation system (check [my answer here](https://stackoverflow.com/a/36742906/1081396))
