### ISSUE TITLE
Continuous Vertical not selecting proper navigation bullet with jquery.fullpage.extensions.min.js

### ISSUE THREAD

**Issue by aunruh** [alvarotrigo/fullPage.js#2917]
Hello!

Here is a codepen for the issue:
https://codepen.io/arminunruh/pen/MEJKYw

When you scroll down when the nav's last bullet is active, you arrive again at the first section, but the second bullet is active.
Also when you are on the first section and scrolling up, the bullet before the last one is selected.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!

**Comment by aunruh** [comment]
Hope you can find the time to work on it soon *hug* :)

**Comment by alvarotrigo** [comment]
I also noticed the bug disappears when using the `anchors` option.

**Comment by alvarotrigo** [comment]
Fixed [on dev](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/jquery.fullpage.extensions.min.js).
