### ISSUE TITLE
Swapping of Logo upon going #anchor2

### ISSUE THREAD

**Issue by vectorbros** [alvarotrigo/fullPage.js#2918]
Is there a method to swap the logo to a different image upon scrolling?

**Comment by alvarotrigo** [comment]
Sure, make use of [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to achieve that.
How you do it is not a matter of this forum. That's about CSS or JS knowledge so I would encourage you to ask in other place such as stackoverflow where they'll be able to help you much better.
