### ISSUE TITLE
Touch events on different element

### ISSUE THREAD

**Issue by richgcook** [alvarotrigo/fullPage.js#2919]
If I have a panel over the fullPage element then on desktop it still works (as it’s controlled by mouse/keyboard and not touch on the actual element) but in touch devices obviously this doesn’t work. Is there any way to allow touch events when the element to be scrolled is behind a panel?

**Comment by alvarotrigo** [comment]
The description is not clear enough to me. Please be more specific and provide a reproduction or at least a video or image illustrating your issue.

**Comment by richgcook** [comment]
Sorry, yes.

http://dev.braw.io/junk-shop-creative/projects/m-s-for-vogue/

If you scroll down and get to the last slide, a separate 'layer' will scroll up and over and the mouswheel/keyboard still works to get rid of it but on a touch device you obviously cannot 'touch' the `fullPage` element as the layer is over it. Is there any way to ignore this 'layer' for touch (almost like `touch-events: none` so the `fullPage` element behind still fires the touch events?

**Comment by alvarotrigo** [comment]
Try placing the layer within the fullPage.js container, inside a section.

**Comment by alvarotrigo** [comment]
Did you try what I suggested?

**Comment by richgcook** [comment]
@alvarotrigo It might've worked but went with the following (using hammer)

```
$('section.projects__meta').hammer().data('hammer').get('swipe').set({
	direction: Hammer.DIRECTION_ALL
});
$('section.projects__meta').hammer().on('swipedown', function() {
	$('body').removeClass('is--near-bottom');
});
```
