### ISSUE TITLE
Using down arrow to scroll with normal behavior

### ISSUE THREAD

**Issue by jibax** [alvarotrigo/fullPage.js#2920]
### Description

One of a section of my page is bigger than the viewheight and the scroll is working well with the mouse scrolling. But if I scroll with the down arrow keyboard, it goes to the next section (and not scroll down into the section)  

Is it possible to scroll normally with keyboard (up & down arrow) without setting autoScrolling to false ?

**Comment by alvarotrigo** [comment]
Duplicate of https://github.com/alvarotrigo/fullPage.js/issues/1065

The issue stills open.
