### ISSUE TITLE
Slides do not respect parent container height value. (w/ Header/Footer)

### ISSUE THREAD

**Issue by BlackWyvern** [alvarotrigo/fullPage.js#2923]
### Description
I'm using a modified version of the header/footer example code. I have a header and footer defined in fixed positions that are dynamically sized. My main navigation menu exists within the header and is defined in a #menu div. If there is not enough width in the page to display the full menu, it will drop down to a second line and automatically rescale the header and content area.

```
<div id="header">
 <div id="menu">
  <nav>
   MENU THING
  </nav>
 </div>
</div>

<div id="fullpage" class="container">
 <div class="content">
  <div class="section " id="section0">
   CONTENT IS HERE
  </div>
 </div>
</div>

<div id="footer">
 FOOTER THING
</div>
```

```
#header{
	position: fixed;
	top: 0px;
	display: block;
	width: 100%;
	background: #000;
	z-index: 9;
	color: #000;}

#footer{
	bottom: 0px;
	padding-top: 0px;}
```

This means that at any given time, the viewable content area is variable and needs to be adjusted if the screen is resized.

I have set up the fullpage div as a container for the viewable area whos height value is set by the following code triggered on display ready and window resize.

```
function resizeViewArea() {
	var hh = $('#menu').height();
	var fh = $('#footer').outerHeight();
	document.getElementById('header').style.height = hh+"px";
	document.getElementById("fullpage").style.marginTop = hh+"px";
	document.getElementById("fullpage").style.marginBottom = fh+"px";
	document.getElementById("fullpage").style.height = ($(window).height() - (fh+hh))+"px";
}
```

This correctly rescales the header and content area if there is not enough width to display all navigation items in the header in one line.

However, the slides themselves use $window.height to determine their size and sub-element placement. This results in text and the navigation buttons for horizontal slides appearing beneath the header and footer, becoming inaccessible.

In a very non-elegant solution I replaced all instances of $window.height in fullPage.js with a function call to bwx_height_adjust() which looks like this:

```
function bwx_height_adjust() {
	var hh = $('#header').outerHeight();
	var fh = $('#footer').outerHeight();
	return $(window).height() - (fh+hh);
}
```

This correctly scales the slide viewable height as the page is rescaled. At least in my case.

### Steps to reproduce it
1. Set header and footer to known fixed values.
2. Set the margins of fullPage to match the header and footer.
3. Set the height of fullPage to match the viewable area by subtracting the header and footer from the window size.
4. Inspect code, note that even though fullPage will have the correct height value, fp-tableCell and fp-Section will still be using $window.height.

### Suggested improvement
Instead of doing something like I did and making a function call doing math all the time, it'd be better if there were some way to simply grab the height value of the container the slides are in. I don't know enough code to do this off hand though. So, this is what I've got.

### Versions 
Chrome 60.0.3112.113

**Comment by alvarotrigo** [comment]
That structure goes against [fullPage.js required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure).

**Comment by wiadev** [comment]
@alvarotrigo Sorry, I have a same issue.
Right now, each section is readying the full height of the mobile device but I have a nav bar at the top(height: 44px)
I need a each section's height to be height: calc(100% -44px) but it's setting full device height as a inline style.

Is there any way to read the parent's height?

```
<div id="fullpage">
  <div class="section" *ngFor="let stack of stacks; let index = index;">
    <div class="slide">
      <home-profile [stack]="stack"></home-profile>
    </div>
  </div>
</div>
```

**Comment by alvarotrigo** [comment]
> I need a each section's height to be height: calc(100% -44px) but it's setting full device height as a inline style.

Sure! Just set the height by yourself using CSS and overwriting the value added by fullPage.js.
Make sure to use the `!important` tag. For example:

```css
#section1{
   height:  calc(100% -44px) !important;
}
``` 

Then use the class `fp-auto-height` on the section as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections):

```html
<div class="section fp-auto-height">
</div>
```

That should do the trick.
