### ISSUE TITLE
Chrome 61.0.3163.100 bug on autoScrolling

### ISSUE THREAD

**Issue by rodrigoprobst** [alvarotrigo/fullPage.js#2924]
Hello, i'm working on a project with use your plugin.

Until the release of this website, all seems to work just fine, but today the client go take a look on the site, and have a bug.

For some reason, the autoscrolling feature was not locking the scroll, no error given, but in edge and mozilla, it was working.

have a look: http://www.digittalart.com.br/portfolio/marcas-7/click-solucoes-inteligentes-56.html

**Comment by alvarotrigo** [comment]
It seems to be working fine on the [demo page](https://alvarotrigo.com/fullPage/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
