### ISSUE TITLE
multiscroll.responsiveExpand not working

### ISSUE THREAD

**Issue by ashleighmm** [alvarotrigo/fullPage.js#2926]
Thanks for the extension Responsive Expand extension isn't not working.

I did the following:
1. Called the multiscroll.responsiveExpand.min.js file before multiscroll.js
2. Activated it with the key in the jquery:
            responsiveExpandKey: 'mykey',
            responsiveWidth: 900,
            responsiveExpand: true

Am I missing something? It isn't working and it's urgent.

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) and let me know the email used for the purchase or the domain you activated it for.
