### ISSUE TITLE
Activate Menu Item for Slides

### ISSUE THREAD

**Issue by ibrokemypie** [alvarotrigo/fullPage.js#2927]
### Description
It is impossible to make a menu item activate based upon the slide of the section, only of the section itself.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/ibrokemypie/dsz8pjdj/4/

### Steps to reproduce it
Create a menu
Activate a slide

### Versions 
All

**Comment by alvarotrigo** [comment]
Use fullpage.js [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to create Javascript or CSS conditions that can serve you to activate any element you want. 

For example:

```css
.fp-viewing-1-2 #myMenu li.testimonies{
     background:red;
} 
```
