### ISSUE TITLE
Slide animation when you click to last slide, then click to 3rd slide (e.g.)

### ISSUE THREAD

**Issue by nachonathan** [alvarotrigo/fullPage.js#2929]
I am using the basic setup for slide animations 

```javascript
else if( ( index == 1 || index == 2) && nextIndex == 3 ) {
        $isAnimatedThreeUp.addClass('animated fadeInUp');
        $isAnimatedThreeUp.eq(0).css('animation-delay', '0s');
        $isAnimatedThreeUp.eq(1).css('animation-delay', '.5s');
```
etc...`

However, if - let's say - I jump to the last slide from the first slide with the dot navigation, and click scroll up or click to a slide in the middle, the animations will not fire. 

For instance, I have a script that counts up to a specified number. If I click past the slide with that script, and then scroll up to it, the number will not count. 

Is there a way to achieve this?

**Comment by alvarotrigo** [comment]
If you believe the callback is not working as expected, please provide an isolated reproduction of the issue in jsfiddle or codepen.
Please keep it as simple as possible to show the callback functionality that you think it is not correct.

**Comment by nachonathan** [comment]
https://jsfiddle.net/fcx49c8L/

**Comment by alvarotrigo** [comment]
Please simplify the example to illustrate your callbacks issue. Remove any external CSS or JS file and keep a simple structure with the less minimum HTML and JS code to illustrate your issue.

For example. Use 3 sections and one of them with 3 slides.
Then use the onLeave callback and use `console.log`.

Then explain what you expect and what you get.

**Comment by nachonathan** [comment]
looks like I fixed it. I needed to add (index!=X && direction =='up')



Nathan Skinner
Senior Interactive Designer
office: 404.233.0332 (x109) <404.233.0332>
3390 Peachtree Rd NE Ste 1000
Atlanta, GA 30326
www.bkv.com | Blog <http://www.bkv.com/blog>
A part of unified.agency

<https://twitter.com/bkvadvertising>
<https://www.linkedin.com/company/18792>
<https://www.facebook.com/bkvadvertising>
<https://www.pinterest.com/bkvadvertising/>
<https://www.instagram.com/bkvadvertising/>



BKV - CONFIDENTIALITY NOTICE: This electronic message is intended to be
viewed only by the individual or entity to whom it is addressed. It may
contain information that is privileged, confidential and exempt from
disclosure under applicable law. Any dissemination, distribution or copying
of this communication is strictly prohibited without our prior permission.
If the reader of this message is not the intended recipient or the employee
or agent responsible for delivering the message to the intended recipient,
or if you have received this communication in error, please notify us
immediately by return e-mail and delete the original message and any copies
of it from your computer system.
