### ISSUE TITLE
Using more than one slider in one section

### ISSUE THREAD

**Issue by juanr-yes** [alvarotrigo/fullPage.js#2930]
Hi, 

I'm trying to use more than one slider on the same section (here's the pen: https://codepen.io/juanr-yes/pen/vedgZW) using bootstrap and fullPage

I understand that, since i'm using the same class, fullPage is putting together all the "slide" items on the same "section", even though they are on different columns according to bootstrap. 

Is this possible to achieve? Perhaps giving more than one selector to "slideSelector" (i have tried using: `slideSelector: ['.slide', '.slide2']` and it just not worked)?

**Comment by alvarotrigo** [comment]
Not something fullPage.js supports. Slides will always take the whole width of the viewport. So you'll only be able to see a single slide at a time.
