### ISSUE TITLE
'Pause' fullPage on full screen menu.

### ISSUE THREAD

**Issue by ChristopherJohnson25** [alvarotrigo/fullPage.js#2931]
I have a transparent full screen menu on a site, I'd like to 'pause' any fullPage functionality while the menu is opened. The destroy method doesn't seem to work, as it completely destroys everything (duh!). Any thoughts or workarounds to pause the scroll jack?

**Comment by alvarotrigo** [comment]
> Any thoughts or workarounds to pause the scroll jack?

Check `setAllowScrolling(false)`

**Comment by ChristopherJohnson25** [comment]
Just saw this! Thanks Alvaro, I skimmed past that method earlier, sorry I missed it!

**Comment by alvarotrigo** [comment]
No problem! :)
