### ISSUE TITLE
Fullscreen mode on html5 or youtube iframe videos is not working correctly. 

### ISSUE THREAD

**Issue by meskimeski** [alvarotrigo/fullPage.js#2932]
### Description
When im add the iframe video player or html5 video player to any of the slides and try to open it on fullscreen mode - the fullpage is not working correctly and start to scrolling - also i can watch the video i see the slides.

http://kitchirigami.com/#projects 
Click more info and try to open the video in fullscreen

**Comment by alvarotrigo** [comment]
Duplicated of #2804
