### ISSUE TITLE
Can't use "active" to style links. 

### ISSUE THREAD

**Issue by AaronD1** [alvarotrigo/fullPage.js#2933]
I'm sorry if this is the wrong place to post this, but I'm new to github and web development in general... 

I'm having issues using the CSS link property "active" in order to style my links in my navigation bar, which is built with bootstrap. 

As a test, I attempted to have the links change to the color red when that link was "active". The result is that when the user clicks on the link, it turns red very briefly, but changes back to black. 

One user on reddit suggested that I use "focus" instead of active, and that helps when the user clicks on the navigation items directly but not when they scroll down to the next section. 

You can see this in action here: https://codepen.io/AaronD01/pen/BwVyRO 

What I want to do is have each link surrounded by a rounded background color and have the text change color, or become transparent (so that it matches the background) when the user clicks a link or scrolls through the sections/slides.

**Comment by alvarotrigo** [comment]
You'd better ask those kind of CSS related questions in other place such as https://stackoverflow.com/ where they'll be able to help you much better.

This forum is to treat fullpage.js issues or related questions of usage. Not specific use cases related with other technologies such as CSS or JS.
