### ISSUE TITLE
Horizontal slider wrapped with some blocks

### ISSUE THREAD

**Issue by KoalaMontana** [alvarotrigo/fullPage.js#2934]
### Description
For the project it is necessary to make a slider, which should be wrapped in several other blocks and have a fixed title for all slides.
As I understand it, the script works only in case of placing slides behind the block with the class 'section'.
Is it possible to do so?

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/nvcpq9mm/

### Steps to reproduce it
See jsfiddle

### Versions 
Any devices

**Comment by alvarotrigo** [comment]
You'll have to follow the [fullPage.js required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure).

**Comment by KoalaMontana** [comment]
@alvarotrigo I got acquainted with the structure first of all, of course.
I'm interested in how to add fixed elements of the main page that would not be included in the slider?
