### ISSUE TITLE
Change menu icon color on scrolling

### ISSUE THREAD

**Issue by zetareticoli** [alvarotrigo/fullPage.js#2935]
### Description
I need to change menu icon color (black/white) depending on which section I'm viewing. 
Example: section with .inverse class should make change menu color to white. 

Link to pen: https://codepen.io/zetareticoli/pen/ZXjvog

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by zetareticoli** [comment]
But what if I don't know which section has this class? Section's order could change dinamically each refresh

**Comment by alvarotrigo** [comment]
Use anchors then.

**Comment by zetareticoli** [comment]
Tried adding `data-anchor="inverse"` to each section where I need it. Shouldn't anchors be unique?

**Comment by alvarotrigo** [comment]
> Shouldn't anchors be unique?

They should.
