### ISSUE TITLE
scrollOverflowOption and mouseWheel

### ISSUE THREAD

**Issue by Andrewdev11** [alvarotrigo/fullPage.js#2936]
Hello. I have problem with "scrollOverflowOption:". I cant change "mouseWheel" no way. Help me, please?
Some others options doesnt work too. For example "bounceEasing". It works only if i change scrollOverflow.js, but mouseWheel doesnt work nowhere.

**Comment by alvarotrigo** [comment]
Pass them through `scrollOverflowOptions`:

```javascript
scrollOverflowOptions:{
    //any iScroll options here.
}
```
