### ISSUE TITLE
Reset Slider not resetting the slides. 

### ISSUE THREAD

**Issue by nvassos** [alvarotrigo/fullPage.js#2937]
Hey there, I have purchased ResetSlider and Horizontal Scrolling plugins. I had setup HorizontalScrolling and everything was working as intended and everyone was happy except the client asked us to not scroll to the right or left on scroll on the horizontal sections and instead scroll to previous or next section. I disabled The horizontal scrolling so that works. Now to add to that, what he wants is when you actually see any of the slides of the horizontal sections and you scroll down or up, and go to other section and COME BACK, to reset the position of the slider. So we purchased ResetSlider plugin. But for some reason it doesn't reset the position. Is there anything that could be preventing it. I cannot attach a codepen unless i copy the entire code. it's a fully designed site. I am attaching the URL in the hopes that it will actually be reviewed as an isolated but generic issue. I am linking the exact section with the issue

[removed link]

At this point I have disabled HorizontalScroll so it doesn't actually scroll unless there is a way to do it programatically. But if you navigate using the 3 links to different slides and scroll down it does not reset it. My only assumption would be that i have alot of callbacks and maybe that's overriding the ResetSlider plugin.

Edit. I disabled all callbacks and still doesn't work.

**Comment by alvarotrigo** [comment]
I can not see any inclusion of `fullpage.resetSliders.min.js` in your page.

**Comment by nvassos** [comment]
Then maybe the documentation should be updated? 

https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension

**Comment by alvarotrigo** [comment]
Read [how to use extensions.](https://github.com/alvarotrigo/fullPage.js#use-extensions)

> Once you adquire the extension file, you will need to add it before fullPage. For example, if I want to use the Continuos Horizontal extension, I would have include the extension file and then the extensions version of the fullPage file.

> Where do I download the JS file you referred to?

You have to purchase it. You get a link to the download after the purchase and in your inbox.

**Comment by alvarotrigo** [comment]
> Where do I download the JS file you referred to?

As you as you did with continousHorizontal extension.

**Comment by nvassos** [comment]
Yup. I got it. Completely missed the download button. I apologize.

**Comment by nvassos** [comment]
It still doesn't work though.

**Comment by alvarotrigo** [comment]
Working perfectly for me.

**Comment by nvassos** [comment]
Yes I see it, but what do I have to do so it honors the js i have and logic for each section?

**Comment by alvarotrigo** [comment]
> what do I have to do so it honors the js i have and logic for each section?

I don't understand the question.

**Comment by nvassos** [comment]
Ok let me explain, the pushstate is working however it is not honoring my js. 

For Example if you go to http://staging.theagencycreates.com/mandarinaa_dev/#flatlands/private_beach

and you remove the private_beach part you see what's happening, there is animation happening, which is not honored by the Reset.

**Comment by alvarotrigo** [comment]
Right, you mean, the callback doesn't get fired for that slide that just got reseted?

**Comment by nvassos** [comment]
Yup! Do I have to add something to cover the reset?

**Comment by alvarotrigo** [comment]
@nvassos please [contact me](https://alvarotrigo.com/#contact) and I'll provide you a solution.

**Comment by nvassos** [comment]
@alvarotrigo Done, NIkolaos Vassos.
