### ISSUE TITLE
We are having issue after inner scrolling content.

### ISSUE THREAD

**Issue by nive745** [alvarotrigo/fullPage.js#2939]
We use plugin scrolloverflow.min.js  for overflowing content. It's working fine  when page load. But when we navigate through menu it showing only bottom content.  Could not showing content from top of the section.
Link : http://architekt-grell.de/demo/
Issue image :  http://architekt-grell.de/demo/wp-content/uploads/2017/10/wrong.png
We need to show like this image :  http://architekt-grell.de/demo/wp-content/uploads/2017/10/right.png

Thanks in advance

**Comment by alvarotrigo** [comment]
Working all fine for me.
I guess you are talking about when you access through the menu for the 2nd time? 

You might want to take a look at the [ScrollOverflow Reset extension](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html).

**Comment by nive745** [comment]
Yes, i  asking access menu for the 2nd time? We tried but its not working.

**Comment by alvarotrigo** [comment]
> We tried but its not working.

You are not using the extension I mentioned.

**Comment by nive745** [comment]
We included js  which provided just now but not working :(

$('#fullpage').fullpage({
		 resize: false,
		 scrollOverflow: true,
         anchors: ['1stPage', '2ndPage', '3rdPage', '4thPage', '5thPage', '6thPage'],
         menu: '#menumenu',
		 scrollOverflowReset: true,
		// scrollOverflowResetKey: 'YWx2YXJvdHJpZ28uY29tXzlRaGMyTnliMnhzVDNabGNtWnNiM2RTWlhObGRBPT14Ykk=',
         scrollingSpeed: 1000,
         onLeave: function(index, nextIndex, direction) {
			 if(index == 2){
				// setTimeout(function(){ showslider(); }, 500);
				 
			 }
			 $(".menu").hide()
			//menu class add
			var d =nextIndex-1;
			//alert(d);
			 var currelem = $('.menu-key-'+d)[0];
			 $('.menuindex').removeAttr('style');
			  var elem = $('.menu-key-'+d)[0];
			 //$(elem).css("border-bottom","#000 solid 1px") 
			  $('a.menuindex').removeClass('active')
			 $(elem).addClass('active')
			//end
			
             // after leaving Introduction
             if (index == 0 && direction == 'down') {


                 $(".menu").fadeOut();
						$(".menu").fadeOut("slow");
						 $(".menu").fadeOut(500);
             } else if (index == 2 && direction == 'up') {
                 $(".menu").fadeOut();
						$(".menu").fadeOut("slow");
						 $(".menu").fadeOut(500);
             } else {
                 /*$.fn.fullpage.setMouseWheelScrolling(true);
                 $.fn.fullpage.setAllowScrolling(true);*/               
				 $(".menu").fadeIn();
						$(".menu").fadeIn("slow");
						 $(".menu").fadeIn(500);
             }
         }

     });

**Comment by alvarotrigo** [comment]
2 mistakes here:

```html
<script type='text/javascript' src='https://alvarotrigo.com/fullPage/fullpage.scrollOverflowReset.limited.min.js?ver=4.8.2'></script>
--
  | <script type='text/javascript' src='https://alvarotrigo.com/fullPage/jquery.fullpage.extensions.min.js?ver=4.8.2'></script>
  | <script type='text/javascript' src='http://architekt-grell.de/demo/wp-content/themes/grell/js/jquery.fullPage.js?ver=4.8.2'></script>
````

1 - You are not using the file you purchased, you are using the `limited` version that you got from the source code of the demo page. You need[ to purchase the extension.](http://alvarotrigo.com/fullPage/extensions/)
2- You are using both the `jquery.fullpage.extensions.min.js`and the `jquery.fullPage.js`one. Only one is necessary. Read [how to use fullpage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).

**Comment by nive745** [comment]
Okay, thanks for your quick support

**Comment by nive745** [comment]
Now we purchase plugin can please check.

**Comment by alvarotrigo** [comment]
Working fine for me now. Always in the top when accessing for the 2nd time.

**Comment by nive745** [comment]
Yes it was our mistake. We didn’t generate activation key. 

Thank you so much for great support.
