### ISSUE TITLE
Javascript alpha version

### ISSUE THREAD

**Issue by peteringram0** [alvarotrigo/fullPage.js#2940]
With the javascript alpha version is there a way to destroy the instance for mobile devices?

**Comment by alvarotrigo** [comment]
No.

**Comment by peteringram0** [comment]
Sorry can i ask, are you planning to continue working on the pure javascript version? I see the last commits are about 10 months old. trying to work out if its worth a fork for the features i want or if there is stuff in the pipeline? 

Thanks.

**Comment by alvarotrigo** [comment]
Not planning to work on it yet. There's no enough demand for it I'm afraid and there's a lot of work to be done in it, more yet if I want to include the extensions.
