### ISSUE TITLE
Lazy Load "cannot read property 'Load"' error

### ISSUE THREAD

**Issue by chriscubellis** [alvarotrigo/fullPage.js#2942]
### Description

I'm getting an error when trying to use data-src with data-autoplay. 

`TypeError: undefined is not an object (evaluating 'element.closest('video').get(0).load')`

The videos never start playing when data-src is active along with data-autoplay, but play when removing either. 

### Link to isolated reproduction with no external CSS / JS

I isolated everything else from the site I'm working on, error is still happening here: (there's also an iScroll error that appeared after removing everything else)
[http://albums.world/isolated/b.html](url)

**Comment by alvarotrigo** [comment]
Please include scrolloverflow.js file as detailed in the docs. This should get rid of the iScroll error.
Or if you prefer, use `scrollOverflow:false`.

**Comment by chriscubellis** [comment]
Hi @alvarotrigo, sorry– the iScroll error isn't what's causing the lazyloading data-src error. I set scrollOverflow:false, I've narrowed down a better reproduction. I think it has something to do with lazyloading the audio?

Here's two demos.

[A](http://albums.world/isolated/a.html)
[B](http://albums.world/isolated/b.html)

A has working data-src on the video object and no data-src on the audio object, and is working fine.

`<div class="section" id="one">
			<video data-autoplay loop muted playsinline>
            <source src="media/covers/mogwai.mp4" type="video/mp4">
      </video>
			<audio data-autoplay loop>
					<source src="media/covers/mogwai.mp3" type="audio/mpeg"></source>
			</audio>
		</div>`

B has data-src on both the video object and audio object, and is throwing the Type Error:undefined that I gave above.

`<div class="section" id="one">
			<video data-autoplay loop muted playsinline>
            <source data-src="media/covers/mogwai.mp4" type="video/mp4">
      </video>
			<audio data-autoplay loop>
					<source data-src="media/covers/mogwai.mp3" type="audio/mpeg"></source>
			</audio>
		</div>`

I also tried standalone video only (without a separate audio object), which worked fine. Standalone audio only (without a separate video object) was still broken. It's unfortunately a requirement for what I'm working on that the audio is separate from the video :/

**Comment by alvarotrigo** [comment]
Neither demo A nor demo B are currently up. 404 error.

**Comment by chriscubellis** [comment]
@alvarotrigo I'm so sorry, I accidentally renamed a folder earlier today that broke those two links...they're back up now. Sorry!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.9.5.
Please try again using the [latest fullpage.js file.](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/jquery.fullPage.js)

**Comment by chriscubellis** [comment]
@alvarotrigo it's working for me now, thank you for the quick update!
