### ISSUE TITLE
Performance issues with dragandmove

### ISSUE THREAD

**Issue by sarath704** [alvarotrigo/fullPage.js#2943]
Thanks for your excellent plugin,

I am using fullpage.js with dragandmove plugin, but i have few issues while i am using. 

1. I enabled Css3 , used easingcss3 for custom easing but some how it's not working in mobile devices.
2. I am using slick carousal in few sections but slick swipe is too hard/long with in fullpage.js.
3. Once slick carousal swipe events happen , fullpage.js having performance issues very hard to move up and down, also sometimes saw  jerk while transition .

Above issues mostly using chrome browser in Android devices. I replaced slick plugin with owl carousal still i am facing same issues

Regards,
Sarath

**Comment by alvarotrigo** [comment]
> I enabled Css3 , used easingcss3 for custom easing but some how it's not working in mobile devices.

DragAndMove has nothing to do with CSS3 transitions. Those casings are not applied when using the dragAndMove feature when dragging and moving. Only when scrolling with mousewheel or trackpad in the normal way. 

> I am using slick carousal in few sections but slick swipe is too hard/long with in fullpage.js.

> Once slick carousal swipe events happen , fullpage.js having performance issues very hard to move up and down, also sometimes saw jerk while transition .

Please [contact me by email](https://alvarotrigo.com/#contact) with the link and steps to reprocue the issue.
