### ISSUE TITLE
mouseWheelSpeed event

### ISSUE THREAD

**Issue by Andrewdev11** [alvarotrigo/fullPage.js#2945]
Hello. 
is mouseWheelSpeed event works? I see open issue on iscroll github 3 years ago. And examples doesnt react this option.

<script src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script> 

	<script type="text/javascript" src="../vendors/scrolloverflow.js"></script>

	<script type="text/javascript" src="../jquery.fullPage.js"></script>
	<script type="text/javascript" src="examples.js"></script>

	<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage({
				anchors: ['firstPage', 'secondPage', '3rdPage', '4thPage'],
				sectionsColor: ['#4A6FB1', '#939FAA', '#323539'],
				scrollOverflow: true,
				scrollOverflowOptions:{

				    //any iScroll options here.

				    mouseWheel:true,
				    mouseWheelSpeed: 50, //not works
				    freeScroll:true,
				    fadeScrollbars:true, // works
				    
				}
			});
		});
	</script>
</head>
<body>

**Comment by alvarotrigo** [comment]
Have you checked if it works in [iscroll.js](http://iscrolljs.com/) without making use of fullpage.js?

**Comment by Andrewdev11** [comment]
Yes. I check separately without fullpage. it doesnt works. 
i use newest Google Chrome browser

**Comment by alvarotrigo** [comment]
> Yes. I check separately without fullpage. it doesnt works.

Then it is a iScroll.js issue and not a fullPage.js one.
I'll close the issue.
