### ISSUE TITLE
How to restart autoplay audio / video after leave slider

### ISSUE THREAD

**Issue by onmarketing** [alvarotrigo/fullPage.js#2946]
Hi,

I wonder if you know how to fix this. I would like to have restart autoplay after leave slider, when come back slider start new video / audio again if you know what I mean.

HTML:
```
<div class="slide">
   <video loop muted controls="false" data-autoplay>
     <source src="..." type="video/mp4">
     <source src="..." type="video/ogg">
   </video>
</div>
<div class="slide book-1">
   <audio controls="" data-autoplay>
     <source src="..." type="audio/ogg">
     <source src="..." type="audio/mpeg">
     Your browser does not support the audio element.
   </audio>
</div>
```

Javascript:

```
<script type="text/javascript">
$(document).ready(function() {
  $('#fullpage').fullpage({
  sectionsColor: ['#eee', '#fff'],
  anchors: ['firstPage', 'book-1']
   });
});
</script>
```

I looking forward to hearing from you :)

Thanks,

Shaun.

**Comment by alvarotrigo** [comment]
Restart the video? I'm afraid fullPage.js doesn't provide such option, you'll have to do it yourself by using fullPage.js callbacks. 

If you are talking about autoplay the audio/video after the section/slide loads, then that's the whole  purpose of `data-autoplay`. Read [the docs](https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media) for more info.

**Comment by onmarketing** [comment]
How do I create callback?

Please give me an example?

Thanks,

Shaun.

**Comment by alvarotrigo** [comment]
All you need to know its in the docs.
https://github.com/alvarotrigo/fullPage.js#callbacks

**Comment by onmarketing** [comment]
```
$('#fullpage').fullpage({
	anchors: ['firstPage', 'book-1'],

	afterLoad: function(anchorLink, index){
		var loadedSection = $(this);

		//using anchorLink
		if(anchorLink == 'book-1'){
			alert(" how do I create here");
		}
	}
});
```

**Comment by alvarotrigo** [comment]
> alert(" how do I create here");

That's up to you. If you don't know how to do it you'd better ask in other place such as https://stackoverflow.com/
This forum is only to treat fullPage.js features and you'r is something outside fullPage.js scope.
