### ISSUE TITLE
The picture on second section flash when refresh the page on the first section

### ISSUE THREAD

**Issue by wfk007** [alvarotrigo/fullPage.js#2947]
### Description
The picture on second section flash when refresh(ctrl+F5) the page on the first section.

### Versions 
- Browse：chrome 61.0.3159.5 
- fullpage.js：2.9.4
- system：windows X64 
- device：thinkpad x250

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by nvassos** [comment]
what kind of flashing? 

I am using this when i have issues on certain things with flashing / hidden etc etc. 

.element {
  -webkit-transform: translate3d(0,0,0);
  -ms-transform: translate3d(0,0,0);
  transform: translate3d(0,0,0);
}

**Comment by alvarotrigo** [comment]
> what kind of flashing?

No, I'm asking for a link where I can see the issue myself.

But in any case, it seems you are talking about a rendering problem. That's probably related with translate3d transitions and some browsers. Not a fullPage.js issue.

**Comment by alvarotrigo** [comment]
You'll be able to find related issues online, such as:
https://www.sitepoint.com/fix-chrome-animation-flash-bug/

**Comment by wfk007** [comment]
### Link to isolated reproduction with no external CSS / JS
- I have written a demo about it on the [codepen](https://codepen.io/wfk007/project/full/ANGOYB).
Imges are not allowed to upload without codepen PRO and the outer chain might slow the loading.
- you can also download it into your disk.
### Description
I mean it attempts to load the whole raw message when refreshing. The flash I saw might be the raw message on the picture page.

**Comment by alvarotrigo** [comment]
> I mean it attempts to load the whole raw message when refreshing.

I don't know what "message" you are talking about, but I would say this is not a fullPage.js issue but rather a browser one
