### ISSUE TITLE
Horizontal scroll disabled after scrollable section

### ISSUE THREAD

**Issue by SeeMax** [alvarotrigo/fullPage.js#2948]
First, thanks for the awesome plugin, really fantastic. 
And thanks for taking the time to help so many people (including me).
I’m having an issue I’m hoping to get some help / insight on.

————

I’ve created a simplified working example here on codepen:
[removed link]
————

I’m building a page, using fullpage.js, that will have two major sections:

1. A hero section that scrolls horizontally with a few full-page slides.
2. A main content section that will have a height based on it’s content. And that content will be scrollable (like a normal site).

- I’ve purchased the scrollHorizontally plugin and installed it.
- I have the Hero section set up as a “section” with “slides” inside.
- I have the second, scrollable main content section, set up with the class of fp-normal-scroll. 
- I have “hybrid:true” and “fitToSection: false” called in the fullpage.js initialization.

Everything works perfectly on the initial scroll:
• The hero slides move horizontally 
• When I reach the end of the horizontal slides the main content section slides up 
• The content section is then scrollable.

However, if I scroll back up to the Hero Section (that normally scrolls horizontally):
• The mouse scroll no longer moves the slides left and right / The Horizontal Scroll plugin no longer works.
• If I use the buttons the scrolling takes place, but not with the mouse event / scroll.

————

I’m hoping to find a way to allow the horizontal slides to be scrollable again when you return to the hero section.

Even if I could trigger a reinitialization of fullpage.js horizontal scrolling when a user hits the top of the page that would be great.

————

Also I recognize that I’m using fp-normal-scroll and that this is an experimental feature.
But I was hoping that this issue might be one that is solvable and perhaps not related to the experimental class.

Thanks so much again for any insight / assistance and for the time.

Cheers.

**Comment by alvarotrigo** [comment]
Few things:

- `hybrid:true` is not supported. Not even documented. There's no support for it in fullPage.js.
I don't know where you found about it, but it is not fully functional feature and I do not provide support for it.

- `fp-normal-scroll` is not supported either.

- `slimScroll` is not used anymore. Now fullPage.js uses a forked version of [iScroll.js](http://iscrolljs.com/) as can be seen in the docs.

If you still having issues after removing all those things, then please [contact me](https://alvarotrigo.com/#contact) by mail with a reproduction to the issue and the steps to reproduce it.

**Comment by alvarotrigo** [comment]
I suggest you to make use of `scrollOverflow:true` for the 2nd section. This way you can have scrollable content on it as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html). Emulating this way a scrollable website from the 1st section onwards.

**Comment by SeeMax** [comment]
Thanks so much for the fast response. 
It appears I needed to add scrollOverflow and the relevant fullpage.scrollOverflow.js
I've got it working. (glad I finally asked and that you've been so responsive).
Cheers.

P.S.
I found the hybrid:true and fp-normal-scroll in some older conversations on here. Was willing to try any new way of banging my head against the wall.
