### ISSUE TITLE
On scroll appears а large padding on the bottom of section

### ISSUE THREAD

**Issue by gaz12** [alvarotrigo/fullPage.js#2952]
Hello! Thank you very much for your plugin. Did a lot of sites on it.
There is one bug, I do not know how to fix it.
On scroll appears а large padding on the bottom of section.
Website bodyweight.com.ua 
jsfiddle example https://jsfiddle.net/gaz12/h1sbch8m/14/
Video with the problem https://yadi.sk/i/pkLsVYI_3NzLgX
How to fix it?

**Comment by alvarotrigo** [comment]
> jsfiddle example https://jsfiddle.net/gaz12/h1sbch8m/14/

Can't seem to reproduce the issue there. 
Also please, get rid of all unnecessary HTML, CSS and JS. 
Keep it as simple as possible to reproduce the issue.

**Comment by gaz12** [comment]
Owl carousel plugin created this error.
