### ISSUE TITLE
Different section view on scroll from top/bottom + white line.

### ISSUE THREAD

**Issue by Filpet96** [alvarotrigo/fullPage.js#2953]
When im scrolling from top to bottom i get a different section view from when im scrolling from bottom to top.  Is there anyway to make them the same?
![Top to bottom](https://user-images.githubusercontent.com/24651632/31890738-902c2d34-b804-11e7-99d4-c87c48404d02.png)![Bottom to top](https://user-images.githubusercontent.com/24651632/31890753-a03d6ada-b804-11e7-90b7-0e4b8481f01d.png)

Left pic: Top to bottom.
Right pic: Bottom to top.   

Also does anyone know why there is a white 1px line on the bottom of the view.
Best regards 
Filip

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
