### ISSUE TITLE
My background video doesn't play automatically

### ISSUE THREAD

**Issue by 1027836596** [alvarotrigo/fullPage.js#2955]
### Description
My background video is not automatically played. It has been set up Video Attribute data-autoplay. Please help me to see it. Thank you

### Link to isolated reproduction with no external CSS / JS
demo: http://www.xunliw.com/1.html

JS:

  <script src="/plugin/fullPage2.9.4/vendors/jquery.easings.min.js?12"></script>
  <script src="/plugin/fullPage2.9.4/vendors/scrolloverflow.min.js?12"></script>
  <script src="/plugin/fullPage2.9.4/jquery.fullpage.js?1508846348"></script>
  

### Versions 
[PC,chrome61,fullpage.js 2.9.4,Windows 10]

**Comment by alvarotrigo** [comment]
> demo: http://www.xunliw.com/1.html

Not working...
![screen shot 2017-10-24 at 13 29 59](https://user-images.githubusercontent.com/1706326/31943090-767982b8-b8bf-11e7-9a0e-554214499910.png)

**Comment by alvarotrigo** [comment]
Please add the HTML you are using.

**Comment by 1027836596** [comment]
Sorry, try this Hongkong server web site demo: http://www.sureline-express.net/1.html

**Comment by alvarotrigo** [comment]
> Sorry, try this Hongkong server web site demo: http://www.sureline-express.net/1.html

Not working either.

**Comment by 1027836596** [comment]
Maybe some foreign servers can't access China; in fact, my problem is that the video is not played on the first screen by default, but after scrolling the next screen, then back to the first screen, you can play the video again.

**Comment by alvarotrigo** [comment]
Try reproducing the issue in jsfiddle or codepen as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by 1027836596** [comment]
OK,Thank you

**Comment by 1027836596** [comment]
The reason has been found, remove configuration navigation: true, navigationPosition:'right'  two items,
The video can be played automatically

**Comment by alvarotrigo** [comment]
> The reason has been found, remove configuration navigation: true, navigationPosition:'right' two items,

What do you mean? Can you be more specific?

**Comment by 1027836596** [comment]
If you set navigation: true, navigationPosition:'right'in the fullpage initialization, my video can not play automatically; after removing it can play normally

**Comment by 1027836596** [comment]
`jQuery('#fullpage').fullpage({  controlArrows:false, paddingTop:'60px'});  Background Video works normally

`jQuery('#fullpage').fullpage({  controlArrows:false, paddingTop:'60px',navigation: true,  navigationPosition: 'right',}); `Background Video Not working

**Comment by alvarotrigo** [comment]
`jQuery('#fullpage').fullpage({ controlArrows:false, paddingTop:'60px',navigation: true, navigationPosition: 'right',});`

You need to remove the comma after `'right'`

Working perfectly: https://jsfiddle.net/5g8ttcq3/
