### ISSUE TITLE
Webpack 3.8.1 Vue-Cli bug?

### ISSUE THREAD

**Issue by leiangelli** [alvarotrigo/fullPage.js#2957]
### Description
I was looking for documentations for fullPage.js for vue-cli webpack but there wasn't any, but somehow I made it work but there is a bug. 
I'm currently working on SPA, supposedly each route (page) will have a different contents with fullpage Js, but it only works on 1st load. If I try to go to another route it won't work.

Is there anyway to fix it?
I'm quite new with vue js.

![bug1](https://user-images.githubusercontent.com/7858310/31977990-e16c22f8-b971-11e7-9bd0-c73f422a0f52.gif)

### Versions 
webpack v3.8.1
fullpage js v2.9.4
jquery v3.2.1
vue js v2.5.2

**Comment by alvarotrigo** [comment]
I don't know how vue-cli works.
You might have to destroy and initialize fullPage.js again with every change you do in the HTML document.
