### ISSUE TITLE
moveSlideRight does not work

### ISSUE THREAD

**Issue by Irina23** [alvarotrigo/fullPage.js#2958]
### Description
Hi, I used code

afterRender: function () {
	setInterval(function () {
		$.fn.fullpage.moveSlideRight();
	}, 6000);
}

but if click on the fp-slidesNav slide open next and quickly scroll to next
Can this be fixed?

### Steps to reproduce it
1. example active slide 3
2. click to 1
3. open 1 and then quickly to 2

### Versions 
Chrom 62, fullPage 2.9.4

**Comment by alvarotrigo** [comment]
Not a fullPage.js issue. That is not proving the moveSlideRight doesn't work. It only proves your code doesn't work as you expect. 

You'd better ask in other place such as stackoverflow.com

**Comment by Irina23** [comment]
Another option for autoplay slider have in fullPage?

**Comment by alvarotrigo** [comment]
> Another option for autoplay slider has in fullPage?

Check this answer: https://github.com/alvarotrigo/fullPage.js/issues/532
