### ISSUE TITLE
Need Horizontal scroll instead of vertical scroll and on scroll.

### ISSUE THREAD

**Issue by ahsanshafiqe** [alvarotrigo/fullPage.js#296]
I am using fullpage.js, currently when we scroll it scroll vertically, we need scroll horizontally and on inner slides we need vertical scroll, how can i achieve this?

it is possilbe to send an ajax hit on scroll???

Thank you.

**Comment by vikaskyadav** [comment]
How can we include horizontal scroll without using slides?

**Comment by alvarotrigo** [comment]
Horizontal scroll with mousewheel is now possible using the option scrollHorizontally and [the extension](http://alvarotrigo.com/fullPage/extensions/) for it.

**Comment by siorp** [comment]
Hi Alvaro!
With the extension can I scroll horizontally the sections?
Thank you in advance.

**Comment by alvarotrigo** [comment]
@siorp you can [check the extensions page]((http://alvarotrigo.com/fullPage/extensions/scrollHorizontally.html).) to have a better idea of what they provide.
Not quite sure what you mean by e "scroll horizontally the sections". The extension scroll horizontally will allow you to slide the sliders by using the mouse wheel.
