### ISSUE TITLE
Scolloverflow jQuery handling

### ISSUE THREAD

**Issue by css117** [alvarotrigo/fullPage.js#2962]
Hi, nice plugin !
 
I updated my plugin with the latest version because I had trouble with scrollOverflow
but my upgrade ended up with this js error :

Cannot read property 'fn' of undefined @scrolloverflow.js?ver=5.2.0:2362

My environement is wordpress, so the js must be properly wrapped to use $ sign as jQuery

You can fix this by patching scrolloverflow.js @2362
(function (window, document, Math, $) {

and complete @2734
})(window, document, null, jQuery);

**Comment by alvarotrigo** [comment]
Make sure to also use[ the latest version of the scrolloverflow.js file. (v 0.0.2)](https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.min.js)

**Comment by alvarotrigo** [comment]
Sorry without a reproduction I can not be sure if you are using it, but It seems you might be right! 
Right now I'm only using `(function (window, document, Math) {`

**Comment by css117** [comment]
yes it's the latest version I downloaded few minutes ago

**Comment by alvarotrigo** [comment]
Fixed on dev. New [scrolloverflow version 0.0.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.min.js).

**Comment by css117** [comment]
thanks !

**Comment by squalvj** [comment]
well i had this problem, before i update my scrolloverflow to the new version that alvarotrigo mentioned, the afterRender callbacks didnt call. i upgrade the scrolloverflow version to the new version and the problem solved
