### ISSUE TITLE
Applying a CSS transition to .section children screws up repositioning

### ISSUE THREAD

**Issue by indextwo** [alvarotrigo/fullPage.js#2963]
### Description

If I apply a class from a CSS framework I'm using which applies a basic ease transition to `all` properties (and applies that same transition to any descendants), fullPage starts misbehaving when it comes to page resizing - instead of the sections resizing appropriately, their scroll positions get all screwed up and you need to scroll up or down (which will then scroll up or down and back again to 'fix' the positioning.

I have since 'solved' this by removing a CSS transition from a section and its children, but the issue stands. fullPage seems to act as if it's cumulatively adding the transitions - if my CSS class is set to `0.5s`, fullPage takes 2-3 seconds to attempt to settle into place again (albeit, in the wrong place).

### Link to isolated reproduction

http://jsfiddle.net/6n0mtux5/

### Steps to reproduce it
1. Scroll down beyond the first section (first one always seems to resize fine) to either Two, Three or Four
2. Resize the height of the page (easiest way - hit F12 to open up Inspector, assuming it's docked)
3. Watch the fullPage sections slowly settle into a weird half-position between two sections
4. Scroll up or down and then back to 'fix' the scroll positioning

### Versions 
FF 56, Chrome 61, Win 7

**Comment by alvarotrigo** [comment]
The easiest way to solve it is to apply the ease class to a wrapper inside the section.

```html 
<div class="section">
     <div class="wrapper">
         Your content here
     </div>
</didv>
```

Or to apply the easing to the properties you want to animate instead of to `all`.
Take into account each section has `height` properties that will otherwise get animated with your `ease` class.
