### ISSUE TITLE
Mobile Devices Scrolling not working at all

### ISSUE THREAD

**Issue by captainscorch** [alvarotrigo/fullPage.js#2964]
Hello,

I was building a website with the help of your amazing plugin. I did try every possible idea I had in mind to fix this problem, but I couldn't. The Scrolling just won't work on actual mobile devices. The website is working perfectly fine on all desktop browsers and also in the mobile preview in Chrome or Safari. But if I try to scroll on the actual page on an actual mobile device (tested with iPhone & Android-Phone) the Scrolling effect doesn't work at all. I can only navigate with the Arrows I added on the page. I tried several versions of your files, deactivated all other .css and .js files but nothing seems to help. I'm out of ideas now and maybe you or anyone else has an idea to help me fix this.

Thank you for your time and help, I highly appreciate it.

Best regards

Link to the website: [trinkspielschmie.de/dev](https://trinkspielschmie.de/dev)

Problem occurs on: All mobile devices, mobile preview on desktop browsers is working fine, desktop browsers are working fine.

**Comment by alvarotrigo** [comment]
I can't reproduce it on the [demo page](https://alvarotrigo.com/fullPage/).

Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by captainscorch** [comment]
Hello. 
Below are 2 Codepens. One completely isolated only with the Fullpage CSS & JS from the CDN you linked in the Readme. And one Codepen with all the other CSS like Bootstrap.
Isolated Codepen: https://codepen.io/captainscorch/full/EbxMBQ 
Normal Codepen: https://codepen.io/captainscorch/full/LOYard

I still get the same problem. Scrolling is not working on actual mobile devices, tested with an iPhone 6S.

**Comment by alvarotrigo** [comment]
Could you please get rid of any CSS that is not part of fullPage.js, unless necessary for the reproduction?
This will make things easier to identify if the issue is in your code or in fullpage.js.

**Comment by captainscorch** [comment]
I did get rid of any css besides the very basic main colors and font-settings. I also made a video on my iPhone showcasing the Problem. Hope this helps: https://youtu.be/9hXRRlH6KTY
Codepen: https://codepen.io/captainscorch/full/EbxMBQ

**Comment by alvarotrigo** [comment]
fullPage.js requires the normal version of jQuery. It will not work with the slim version.

**Comment by abhishek-suresh** [comment]
Thanks a lot for the tip @alvarotrigo . love you. No homo. Changing to normal jquery fixed it.

**Comment by david-bettondesign** [comment]
I am experiencing something similar but only when using "responsiveWidth" - https://work.bettondesign.co.uk/pg/
