### ISSUE TITLE
scrollOverflow doesn't work.

### ISSUE THREAD

**Issue by PasikCZE** [alvarotrigo/fullPage.js#2965]
Hello,
i tried to work with scrollOverflow but i cant get it working. Can you please tell me what am i doing wrong? Here is my test web page: 

http://fullpagetest.maweb.eu/

Thank you,

**Comment by alvarotrigo** [comment]
Use a wrapper for your text inside your section.
Wrap it in a '<div>' element

```html
<div>
    <h1>Seciton1</h1>
    <p>text here</p>
</div>
```

**Comment by PasikCZE** [comment]
Thank you for your fast respond, but it still doesnt work.

**Comment by alvarotrigo** [comment]
Please remove the `.wrapper` from your html element. 
Apply it to the div inside the  sections.

**Comment by PasikCZE** [comment]
I changed it but it still doesnt work.

**Comment by alvarotrigo** [comment]
You are not including the fullpage.js css file.

**Comment by PasikCZE** [comment]
Oh, im sorry i forgot. Now i included fullpage css but scrollOverflow still doesnt work.

**Comment by alvarotrigo** [comment]
Your site works as expected to me. All fine.

**Comment by PasikCZE** [comment]
Can you scroll in the first section? I cant. When i try to scroll down it just scrolls right to the second section.

**Comment by alvarotrigo** [comment]
> Can you scroll in the first section?

Yeah. Make sure to refresh all your site and that you are not using cached files.

**Comment by PasikCZE** [comment]
I did. Now it works for me only when i pres F12 for inspect, refresh and close inspect mode :D When i just open that page and refresh it doesnt work. Also, when i try to go in inspect mode and select for example iPhone 6 it doesnt work either.

**Comment by PasikCZE** [comment]
Can you please try it again? I tried it on many devices and browsers but it still doesnt work. I really like fullpage js but i need to get scrollOverflow working.

**Comment by alvarotrigo** [comment]
Working as expected. All good.
