### ISSUE TITLE
Dynamically disable dragAndMove extension?

### ISSUE THREAD

**Issue by lazymood** [alvarotrigo/fullPage.js#2966]
Is there any way to programmatically enable/disable the event handlers bound by the dragAndMove extension?

**Comment by alvarotrigo** [comment]
Good point! 
There's none at the moment. I'll mark it as a possible enhancement for future versions of the extension.

**Comment by lazymood** [comment]
I've found that **$.fn.fullpage.dragAndMove.destroy()** makes the job done but when I try to reinitialize the component via **$.fn.fullpage.dragAndMove.init()** the sliding movement loses fluidity. I can't get an idea of why this happens :\

**Comment by alvarotrigo** [comment]
Because, as I said, there's no feature yet to do what you want :) 
That destroy method won't do all the job.

**Comment by lazymood** [comment]
Ok, but can you suggest some workarounds? I have to put an image carousel in front of the fullpage layout with dragAndMove extension. As you can imagine, the drag gesture on the carousel activates both components movements.
Any help would be strongly appreciated.

**Comment by alvarotrigo** [comment]
You'll have to be more specific with your issue.  What movement activate both components? In which way ? Horizontal? Vertical? Drag with mouse? Drag with finger?

Why don't you just use `dragAndMove: 'vertical'` so horizontal sliding won't take any effect.

**Comment by lazymood** [comment]
my fullpage application is a digital signage solution and will run on a full HD touch monitor (so, only touch navigation will be supported). The dragAndmove extension works horizontally (`dragAndMove: 'horizontal'`) and the fullpage sections are reachable only through a dropdown menu. 
The image carousel is a simple slick slider. It's absolute positioned, for each section, in front of the fullpage layout and contains the slides thumbnails (like an index for each section). So, the movement that activates both components is the horizontal drag with mouse or horizontal swipe on a touch monitor.

![demo](https://user-images.githubusercontent.com/1022179/32181298-5027a89a-bd94-11e7-83de-246cb8d9aa15.gif)

Thank you for your willingness.

**Comment by lazymood** [comment]
Do you have any suggestion?

**Comment by alvarotrigo** [comment]
I'll take a look at it later on today.

**Comment by lazymood** [comment]
I'd need to programatically disable the dragAndMove when I open the slick slider (as you can see on the above animated gif) and active it again when I close it. I'd create a jsfiddle but I'm pretty sure it wouldn't work with dragAndMove extension.

**Comment by alvarotrigo** [comment]
@lazymood feel free to [contact me](https://alvarotrigo.com/#contact) if you really need this feature.

**Comment by lazymood** [comment]
I've sent you an email. Did you receive it?

**Comment by alvarotrigo** [comment]
Yes
