### ISSUE TITLE
IOS toolbar appearing in landscape

### ISSUE THREAD

**Issue by jaddedrus** [alvarotrigo/fullPage.js#2967]
Hi, i like your code and it works great with ios landscape no toolbar mode, it not appear while you scrolling and using your navigation system (horizontal and vertical menu + next and prev arrows)

But when i'm creating link with anchor or using moveTo on custom elements (my menus/images) it makes toolbar appear.. What am i doing wrong? How prevent appearing?

Sorry for wrong text of issue but not found better way to communicate..

**Comment by alvarotrigo** [comment]
We developers don't have control over the browsers' navigation bars. There's not a proper solution for all cases. 
I would recommend you to use a responsive site making use of the responsives options or to just make use of `scrollBar:true`.
