### ISSUE TITLE
scrollOverflow is does not work

### ISSUE THREAD

**Issue by imhitt** [alvarotrigo/fullPage.js#2969]
hi,
scrollOverflow is not work normal on the phones.
it's just going trow the slide and never mind whats in there (meaning text or blocks), but if i would clean cache on mobile everething will work for the momen when i will reload the page.
i thought that my problem with my project, but i create a new project and tried to do it on default settings, so i set only : 
```
`sectionsColor : ['#DE5347', '#1CA261', '#FFCE43'],
scrollOverflow:true,`
```
but it still going trow slide. 
sorry for my bad english =)

**Comment by meceware** [comment]
This is probably about #2962.

**Comment by alvarotrigo** [comment]
Without a reproduction of the issue is impossible to tell what's going on in your case. 
Make sure to use the [scrolloverflow 0.0.3 file](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.min.js), as commented by @meceware the issue might be because you are using 0.0.2.
