### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by sinashamsizadeh** [alvarotrigo/fullPage.js#2970]
Hi,

I have a problem; I like to use this in WordPress and a page which is created by Visual Composer. I did “enqueue” the plugin as it is shown in explanations. I have a jQuery.plugins.js file and put all jQuery of used plugins in it and by using wp_enqueue_script function loaded jquery.plugins.js in front-end.
It seems it is working and has no issue but if you check console there are two js errors which I don’t know their reasons.

Here is link and also screenshots:
1 - https://prnt.sc/h6i1yz
2 - https://prnt.sc/h6i21d
3 - https://prnt.sc/h6i232
http://deeptem.com/test/edge-one-page/

**Comment by alvarotrigo** [comment]
Sorry this is not a place to ask for wordpress issues. I only provide support for fullPage.js library.
You'd better ask somewhere else.
