### ISSUE TITLE
Is it possible to disable multi touch swipes?

### ISSUE THREAD

**Issue by jaddedrus** [alvarotrigo/fullPage.js#2971]
Hello, i really like your product!
I'm looking for opportunity to block two finger swipe scrolls on my site, is it possible?

**Comment by alvarotrigo** [comment]
Thanks glad you like it!

> I'm looking for opportunity to block two finger swipe scrolls on my site, is it possible?

Can you be more specific? What's the default behaviour with 2 fingers swipe? 
You want to swipe with 1 finger then? As fullPage.js does by default too?

**Comment by jaddedrus** [comment]
Yes i want to use 1 finger swipe with default action of fullPage.js
but not perform any actions if two or more fingers touch

**Comment by alvarotrigo** [comment]
So, fullPage.js doesn't provide such option within it, but you can do it using its functions and your own code.
I'll explain myself:

You can code the multi touch detection yourself (if even possible, haven't researched it) and then you can call "$.fn.setAllowScrolling(false)" when detecting 2 fingers. 

Then, whenever you detect the release of the multiple fingers (or one of them) just call "$.fn.setAllowScrolling(true)" to enable scrolling again.
