### ISSUE TITLE
Fullpage Fixed Backgrounds Not Working in FireFox 

### ISSUE THREAD

**Issue by Corradlo** [alvarotrigo/fullPage.js#2972]
Hi all < im bulding a site with fullpage and have just enabled fixed backgrounds, these are working on all browsers except to for firefox.

On firefox it just repeats the backgrounds for every slide , so it is not fixed!

Is the code i am missing to achieve this? Thank you

/* Backgrounds will cover all the section
	* --------------------------------------- */
	.section{
		background-size: cover;
		background-attachment: fixed;
	}
	.slide{
		background-size: cover;
		background-attachment: fixed;
	}

	/* Defining each section background and styles
	* --------------------------------------- */
	#section0{
		background-position: center;
		background-image: url(imgs/bg6.gif);
		background-repeat: no-repeat;

Latest Fullpage plugin used

**Comment by alvarotrigo** [comment]
Try it using the fullpage.js option `css3:false`.
If you prefer to use css3, then read [this answer](https://stackoverflow.com/a/20297373/1081396) that might help you.

Not a fullpage.js issue but a browser's one.
