### ISSUE TITLE
SrollOverflow fails on Codepen with jquery v3.0.0 and higher

### ISSUE THREAD

**Issue by adibk** [alvarotrigo/fullPage.js#2973]
### Description
Using the fullpage example of scrolloverflow, the scroll bar disappear with jquery version 3.0.0 and higher on chromium

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ddazal** [comment]
# Description
When setting `scrollOverflow` option to `true` and using with jQuery 3.x.x, the desired behavior is fulfilled **after** a resize. Here is the [pen](https://codepen.io/ddazal/pen/eeegej).
## Steps to reproduce it
1. Follow the instructions written in the sections of the [pen](https://codepen.io/ddazal/pen/eeegej). You'll notice that overflow won't work until you resize the window.
2. Open JS settings in Codepen and change (manually) the jQuery version from _3.2.1_ to a lower version, for example _2.2.4_. Just in case, here is the url: https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js. This time, the overflow will occur as expected.
## Versions
**Google Chrome** 61.0.3163.100
**Firefox** 56.0

**Comment by alvarotrigo** [comment]
Interesting issue... I'll investigate it a bit more to see what's going on.
Thanks for reporting it!

**Comment by alvarotrigo** [comment]
It is not a jQuery issue, it is a Codepen one. It definitely works fine with jQuery >= .

**Comment by alvarotrigo** [comment]
This issue seems to be directly related with this other one https://github.com/alvarotrigo/fullPage.js/issues/3002

If you now make use of the [dev version of the file scrolloverflow.js](https://rawgit.com/alvarotrigo/fullPage.js/dev/vendors/scrolloverflow.js) the issue disappears.
