### ISSUE TITLE
non-passive event listener force a reflow.

### ISSUE THREAD

**Issue by ronyrun** [alvarotrigo/fullPage.js#2974]
Hello, I encounter that error when using the library jquery.fullpage.js
Do you know any trick to remove those events ?

### Description
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

### Steps to reproduce it
1. On Chrome browser

![image](https://user-images.githubusercontent.com/7273443/32514209-95c4928c-c3fc-11e7-894b-013998c9cbf6.png)

**Comment by alvarotrigo** [comment]
You'll have to be more specific. 
I'm not able to reproduce it on the [demo page](https://alvarotrigo.com/fullPage/) with the latest Chrome on Mac.

**Comment by ronyrun** [comment]
Hello,
Yes I don't understand why I got those errors on my Angularjs App.
I'm using angular material design and bootstrap.

**Comment by alvarotrigo** [comment]
Providing an isolated reproduction would help :) No external CSS or JS files please to fullPage.js unless required for the reproduction or part of a framework.

**Comment by ronyrun** [comment]
yes I agree,

https://alvarotrigo.com/fullPage/ provide the issue : 

![image](https://user-images.githubusercontent.com/7273443/32618637-91488a24-c578-11e7-9d80-1637ba7420e8.png)

**Comment by alvarotrigo** [comment]
@ronyrun I can not reproduce it. Please specify browser and its version and operative system.

**Comment by alvarotrigo** [comment]
It might be a configuration in your version of Chrome.

Check out [this docs](https://docs.google.com/document/d/1II7oSIpd8pK91V5kEM3tDLKcIj398jOJn8Niqy6_loI/edit) and see how you can change the default behaviour of Chrome for passive events by accessing your chrome flags: `chrome://flags` and changing the property `
Passive Event Listener Override` to `Default`.

**Comment by ronyrun** [comment]
OK will do.
Thank you to help me on that subject !

**Comment by ronyrun** [comment]
Hey alvaro,

The properties were ok : 
![image](https://user-images.githubusercontent.com/7273443/32697509-3f27f9c0-c792-11e7-91e5-d3d934473e39.png)

I get those errors when calling the `('#fullpage').fullpage(){}` function. (at home.js:36 in the image).
![image](https://user-images.githubusercontent.com/7273443/32697518-79c93620-c792-11e7-8e45-5b5e808b8cf2.png)

Regards,

**Comment by alvarotrigo** [comment]
Which Chrome plugins were them?

**Comment by ronyrun** [comment]
Hey.

Ghostery and AdBlock.

**Comment by ronyrun** [comment]
mmm that's strange even on a Private Chrome session without any plugins I have the errors.

**Comment by ronyrun** [comment]
Can I send you a private link by email ? You'll see by yourself.

**Comment by alvarotrigo** [comment]
> Can I send you a private link by email ? You'll see by yourself.

Sure.

**Comment by mahapo** [comment]
@alvarotrigo This Violation is still present. Please reopen this issue

Tested in Chrome browser. ([URL](https://alvarotrigo.com/fullPage/examples/scrolling.html))

Also is shows an error in the chrome audits tool.

![image](https://user-images.githubusercontent.com/28730855/53245763-f38fae80-36ae-11e9-8b84-89b5f7e8ee36.png)

### Solution
https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by alvarotrigo** [comment]
@mahapo as far as I know you can't use passive true if you are planning to call preventDefault(); (which fullpage.js does in most cases)

> By marking a touch or wheel listener as passive, the developer is promising the handler won't call preventDefault to disable scrolling. This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.
