### ISSUE TITLE
autoScroll with sections larger than viewport height

### ISSUE THREAD

**Issue by abprecious** [alvarotrigo/fullPage.js#2975]
Hi,

I was wondering how I could setup fullPage so that when it comes to a section that is larger than the viewport height it allows you to scroll normally and once you reach the end of that section it continues using autoscroll to go to the next section. Is this even possible? Below is my current JS. The first section is fine and scrolls down to the second but the second has more content below the viewport that I cant scroll to (currently no third section but it's being built). The second section has the following classes:  class="section fp-auto-height fp-noscroll". 

$('#fullpage').fullpage({
        //Scrolling
        autoScrolling: true,
        fitToSection: true,
        scrollOverflow: true,
        scrollOverflowReset: true,
    })

I downloaded the JS today so it should be the most recent version.

Thanks!

**Comment by alvarotrigo** [comment]
Use the scrolloverflow option. You can see an example [here](https://alvarotrigo.com/fullPage/examples/scrolling.html).

Do not use `fp-noscroll` its not necessary. Scrolloverflow won't be applied when not necessary.
