### ISSUE TITLE
Is there a way to reverse how the horizontal and vertical scrolling works example:

### ISSUE THREAD

**Issue by northkode** [alvarotrigo/fullPage.js#2979]
Question:

Normally slides are horizontal and sections are vertical,
is there a way to get sections to be horizontal and slides vertical scrolling? or some how put a section in a slide? 

id like my navigation to work like:

```
1 -> 2 -> 4 
          ↓
          5
          ↓
          6 -> 7 -> 8
```

Inside slide 4 there would be vertical navigation to show how many sub children slide 4 has which is 2 sections. after i reach the bottom, it goes back to sliding horizontally to the other sections/slides

**Comment by alvarotrigo** [comment]
You can emulate that behaviour by making use of the function `setAllowScrolling`  to deny the scroll down until in 1 and 2 you reach the 3rd slide. 
Same to deny movement up in 7 and 8.
