### ISSUE TITLE
Incorrect transforming causing 15px gap at the bottom of the page

### ISSUE THREAD

**Issue by natezerk** [alvarotrigo/fullPage.js#2980]
There is an issue with the transform logic that causes a frustrating 15px gap at the bottom of the page.

`transform: translate3d(0px, -15px, 0px);` is applied to the parent container div incorrectly.

Also the height of the child section is incorrectly calculated as being 15px shorter, requiring sub optimal overrides.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
