### ISSUE TITLE
fp-enabled class is not added to html tag

### ISSUE THREAD

**Issue by rohitsavaj** [alvarotrigo/fullPage.js#2981]
### Description

Can you please help me 
Thanks in advance
i have included required
jquery
fullpage js
fullpage css

but still fp-enabled class is not added to HTML
inshort the fullpage js is not enabled

i am also adding this script
<script type="text/javascript">
        $(document).ready(function() {
            $.fn.fullpage({
				anchors: ['top-section','39-43-passenger-mini-coaches','5-8-cargo-tow-trailer','56-passenger-motor-coach','27-passenger-mini-coaches','executive-sprinter-vans','14-passenger-transit-vans','cadillac-escalade','sport-utility-vehicles','tesla-model-s','mercedes-s550','executive-sedans','footer'],
				navigation: false,
				navigationPosition: 'right',
				navigationTooltips: ['','39-43-PASSENGER MINI-COACHES','5-8 CARGO TOW TRAILER','56-PASSENGER MOTOR COACH','27-PASSENGER MINI-COACHES','EXECUTIVE SPRINTER VANS','14-PASSENGER TRANSIT VANS','CADILLAC ESCALADE','SPORT UTILITY VEHICLES','TESLA MODEL S','MERCEDES S550','EXECUTIVE SEDANS',''],
				scrollBar: true,
				autoScrolling: false,
				showActiveTooltip: true,
				fitToSection: false,
				css3: true,
				scrollingSpeed: 1000
            });
        });
    </script>

**Comment by alvarotrigo** [comment]
Can't help you without a reproduction. Please provide an isolated reproduction of the issue. 

Also, make sure to check the [provided examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) source code to see how to use fullPage.js.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
