### ISSUE TITLE
parallax Need to rely on those javascript?

### ISSUE THREAD

**Issue by backgroundblue** [alvarotrigo/fullPage.js#2982]
jquery.fullPage.css 
jquery.min.js
jquery.fullPage.min.js
jquery.easings.min.js 

In addition, what kind of javascript is required?

err
#1"Uncaught TypeError: Cannot read property 'setOption' of undefined"

**Comment by alvarotrigo** [comment]
I do not understand your question. 
If you are talking about the [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) you need to purchase the extension and include the files as detailed in [how to use fulllPage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).
