### ISSUE TITLE
used screenfull.js with fullpage.js problem

### ISSUE THREAD

**Issue by tudtude** [alvarotrigo/fullPage.js#2983]
### fullpage.js not re calculate new height when request fullscreen mode but if we rotate mobile everything 100% work.

Is it possible to let it work, by first click on button to request to fullscreen?
I try to used step like this but not work.
1) when page open call fullpage.js
2) when user click fullscreen button call $.fn.fulpage.drestroy();
3) after that call fullpage.js again! 

### Steps to reproduce it
1. add https://cdnjs.cloudflare.com/ajax/libs/screenfull.js/3.3.2/screenfull.js in project
2. create button to call function screenfull.request();
3. It will show some withe box at bottom of mobile if we scroll to new page withe box still maintain.
4. If rotate mobile one time to change view from vertical to horizontal everything will work 100%  

### Versions 
fullPage 2.9.4, android, chrome

**Comment by alvarotrigo** [comment]
> when user click fullscreen button call $.fn.fulpage.drestroy();

Try calling $.fn.fulpage.drestroy('all');

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by tudtude** [comment]
I was solve the problem already by destroy them after fullscreen and re-call it again by add delay time. 

Thank you for support, you are very nice to make this for another people when I got some money from my project will invite you to coffee :)

**Comment by alvarotrigo** [comment]
Nice to know you solved it! ;)
