### ISSUE TITLE
FullPageJs doesn't recognize mouse scrolling for some reason

### ISSUE THREAD

**Issue by GiuseppeScalese** [alvarotrigo/fullPage.js#2985]
### Description
Hello,
I've installed fullPageJs to implement a vertical parallax with navigation dots option too.
It works well if I click on the navigation dots I've implemented but it doesn't pick the mouse wheel scroll event. The page doesn't move in any direction.

I'm providing the fiddle to show the HTML and the JS used.

Any help would be much appreciated!
Thanks!!

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/ryeo1jm8/

### Versions 
desktop in chrome

**Comment by alvarotrigo** [comment]
Please add a working reproduction. Your CSS code is in the HTML panel and you didn't add a single external resource for the JS and CSS files for fullPage.js.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
