### ISSUE TITLE
How to completely disable interaction with 'location.hash'

### ISSUE THREAD

**Issue by dev-smith** [alvarotrigo/fullPage.js#2986]
Hello how to completely disable interaction with 'location.hash'. (links click, "ready", "hashchange"...)
`lockAnchors: true` - not enough.

**Comment by alvarotrigo** [comment]
> lockAnchors: true - not enough.

Can you explain why it is not enough?

**Comment by dev-smith** [comment]
Sorry the problem was not in the "fullPage", many thanks for your work!
