### ISSUE TITLE
can i carry same div in next section like sticky? 

### ISSUE THREAD

**Issue by ArslanAkhtar** [alvarotrigo/fullPage.js#2990]
i want to stick my left side div from second section in third section. and when i go up from 4th section carry the left div again to section section.
is there a way through which i can achieve this functionality?

### Steps to reproduce it
1. go to https://www-staging-cdn.wrld3d.com/3d-maps/
2. slide down all the section and check.

**Comment by alvarotrigo** [comment]
Many things are possible with the right knowledge :)
fullPage.js doesn't provide such feature in its core, but it can for sure be achieved somehow, as the site you link is indeed making use of fullpage.js.

This forum is to treat fullPage.js issues, bugs or questions regarding its features and options. 
As your question is not in this category I suggest you to ask in other place as https://stackoverflow.com/ where they'll be able to help you better.
