### ISSUE TITLE
scrollingSpeed: 0 when clicking menu?

### ISSUE THREAD

**Issue by rubaff** [alvarotrigo/fullPage.js#2991]
Hi alvarotrigo,
thanks (again) for the great tool!
Is it possible to have no animation, when clicking on a menu-link (but keep the animation when scrolling)?

Thanks!

**Comment by alvarotrigo** [comment]
Use the function [silentMoveTo](https://github.com/alvarotrigo/fullPage.js#silentmovetosection-slide) and bind it to the clic even for your custom menu. Do not use the `menu` option.

**Comment by rubaff** [comment]
Perfect! Thanks for the quick response <3
