### ISSUE TITLE
Floating navbar

### ISSUE THREAD

**Issue by Tingkerks** [alvarotrigo/fullPage.js#2992]
Thank you for your great work.

But i need help. How do i make a floating navbar that sticks on top on scroll while using your fullpage?

like on this demo 
http://www.dwuser.com/education/content/creating-a-floating-navigation-menu/demo/complete.html

**Comment by alvarotrigo** [comment]
Take a look at [all the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples). They all have a floating menu. 

But in any case, this is not the place to ask that question. Yours is a CSS knowledge question and not a fullPage.js related one. I would encourage you to ask in other places such as stackoverflow.com where they'll be able to help you much better.
