### ISSUE TITLE
Is it posibble to create fixed header inside scrolloverflow?

### ISSUE THREAD

**Issue by tubagusputra159** [alvarotrigo/fullPage.js#2994]
I wanna create a sticky header inside scrolloverflow whether that possible to make it happen? so when I'm scrolling down in scrolloverflow the header will resize to be smaller. here's the link that you can check my project http://adelva.com/demo/illustro/eye-exam.html thanks.

**Comment by megitra** [comment]
Yes, you can.
just  add this code to your javascript
` onLeave: function(index, nextIndex, direction){
              if(nextIndex ==2 && direction == 'down'){
                $('.nav-resize').addClass('tiny');
              }
              if(nextIndex ==1 && direction == 'up'){
                $('.nav-resize').removeClass('tiny');
              }
    }`
**'.nav-resize'** is your header class and **'.tiny'** is your new class for smaller header

**Comment by alvarotrigo** [comment]
This is not the place to ask for those kind of questions. It is more a CSS / JS related issue. 
Or a [iScroll.js](http://iscrolljs.com/) one, which is the library used by fullpage.js for the scrollOverflow feature.

I'd recommend you to ask somewhere else.
