### ISSUE TITLE
fading effect stutter on Safari when using SVG with overflow: visible

### ISSUE THREAD

**Issue by sneakyvince** [alvarotrigo/fullPage.js#2995]
### Description
I have a number of slides with every slide having SVG Text at the bottom. The fading effect animation works properly between the slides on  both Firefox and Chrome but only on Safari does the animation stutter a bit (no fade out animation). 

If you remove the `overflow:visible!important` line on the SVG element the animation works properly again on Safari. Changing the fadingEffect: 'slides' to fadingEffect: true will also fix the problem. Unfortunately I need the fading effect on the slides only.

Is there a fix/workaround for this animation stutter on Safari?

### Link to isolated reproduction with no external CSS / JS
[removed link]

### Steps to reproduce it
1. View the codepen in fullscreen because if the viewport height is too small the problem won't show. 
2. Use fadingEffect: 'slides'
3. add an SVG with overflow: visible
4. Slide animation now stutters on Safari

### Versions 
fadingEffect version: 0.0.3
fullPage.extensions.min: 2.9.5
jQuery: 3.2.1 (2.1.3 in pen)

**Comment by alvarotrigo** [comment]
Can you reproduce the issue removing the SVG elements? 
I don't see why they should have any effect on the way fullPage.js works.

**Comment by sneakyvince** [comment]
I tried to reproduce it with a regular div instead of an SVG here: https://codepen.io/sneakyvince/full/VrxNqo

Unfortunately the stutter won't show up anymore when the SVG is replaced.

**Comment by alvarotrigo** [comment]
Try adding some background color to the slides / sections and see if you get the fading effect. 
Then add a SVG file in one section or two with the minium CSS required for the reproduction.

Please [contact me](https://alvarotrigo.com/#contact) with a link of the reproduction. 

I'll close the issue as it it is probably a non fullpage.js related issue.

**Comment by sneakyvince** [comment]
Just adding the backgrounds to sections fixed the problem:

Here it is fixed:
https://codepen.io/sneakyvince/full/bYvRQV

Thanks for the help
