### ISSUE TITLE
Access to slice in function onLeave?

### ISSUE THREAD

**Issue by ksicinski** [alvarotrigo/fullPage.js#2996]
### Description
Are we have some simply access to **sliceIndex** in method **onLeave** ?

I need implement some code if (slideIndex % 2 === 0) for index example 4.

In method **onSlideLeave** I have **slideIndex** or **nextSlideIndex**. How to make access for this in **onLeave** method?

**Comment by alvarotrigo** [comment]
> Are we have some simply access to sliceIndex in method onLeave ?

Nop! But thanks for pointing it out!

At the moment you can just make use of the [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) for that.

```javascript
onLeave: function(index, nextIndex, direction){

    //leaving section active slide
    $('.fp-section').eq(index).find('.fp-slide.active)

    //next section active slide
    $('.fp-section').eq(nextIndex).find('.fp-slide.active)
}
```

I'll keep it open as a possible enhancement!

**Comment by ksicinski** [comment]
Thx for solution but I found my own more simple:
`var slideIndex = $('.section-portfolio .slide.active').index();`

This modification will be some times needed :) Good to add this :)

**Comment by alvarotrigo** [comment]
This has now been fixed on fullPage.js version 3. 
The [callbacks signature](https://github.com/alvarotrigo/fullPage.js#callbacks) includes Objects containing the origin and destination sections.
