### ISSUE TITLE
Section position sometimes different on mobile when using menu

### ISSUE THREAD

**Issue by levipadre** [alvarotrigo/fullPage.js#2997]
### Link to isolated reproduction with no external CSS / JS
http://browning-associates.rapacioli.co.uk/ [Sorry, can't give you only test website]

### Steps to reproduce it
1. Click through the menu items from the top: Client Experience, after People then Contact Us => position is correct
2. Now the current section is Contact Us
3. Click the menu items from the bottom: Contact Us, after People then Client Experience  => position is not correct

### Versions 
iPhone Safari and Chrome, Chrome dev toolbar (all mobile version)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

No external CSS or JS to fullPage.js and the minimum HTML code necessary for the reproduction. Get rid of everything else.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
