### ISSUE TITLE
Urgent: Problems with videos and mobile devices

### ISSUE THREAD

**Issue by bapadmin** [alvarotrigo/fullPage.js#2998]
Hello,

i've just implemented FullPage.js to my own wordpress theme: https://www.bap.cc/

It seems like it's working fine - in the first moment.
But if you scroll down and up again the video doesn't continue...

Additionally the video doesn't even display on mobile devices. It's just working on desktops.
![bildschirmfoto 2017-11-24 um 12 15 19](https://user-images.githubusercontent.com/33956217/33208284-3a2c1194-d111-11e7-9dea-5c347a2d5bd2.png)

Could you please help me...
 
PHP-Files in following documents:
[front-page.txt](https://github.com/alvarotrigo/fullPage.js/files/1501489/front-page.txt)
[header.txt](https://github.com/alvarotrigo/fullPage.js/files/1501491/header.txt)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Please reproduce the issue with the minimum HTML code and no external JS and CSS. Get rid of everything else and ideally use empty sections.
This way I'll be sure the problem is not in your code and that it is indeed in fullpage.js. 
It will also help me resolved your issue much faster.
