### ISSUE TITLE
FullPage.js not work on mobile and ipad

### ISSUE THREAD

**Issue by kovtaliuk** [alvarotrigo/fullPage.js#2999]
Hi there!
Please tell - why don't work  FullPage.js on this project - http://159.89.0.145/index.php 
When changing screen height of the screen block does not stretch to full screen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Please reproduce the issue with the minimum HTML code and no external JS and CSS. Get rid of everything else and ideally use empty sections.
This way I'll be sure the problem is not in your code and that it is indeed in fullpage.js.
It will also help me resolved your issue much faster.
