### ISSUE TITLE
offsetSections - Vertical position

### ISSUE THREAD

**Issue by Candielope** [alvarotrigo/fullPage.js#3004]
Hi!
I'm using the offsetSections plugin, and I always want the slide to stick to the top of the screen, so I set data-centered="false", when I scroll down this is perfect, each slide starts from the top of the screen, but when I scroll up they stick to the bottom of the screen. Is there a way to make them only stick to the top ? :)

**Comment by alvarotrigo** [comment]
As seen on the demo page:

> This section is using `data-percentage="80"` and `data-centered="false"`. It won't be vertically centered in the viewport and **will show part of the previous or next section depending on the direction of the previous scroll.**

**Comment by alvarotrigo** [comment]
There's no way to force it always to only stick to the top I'm afraid. 
The reason behind it is because you wouldn't be able to scroll to the top on the last few sections if you are using a small `data-percentage` value for them.
