### ISSUE TITLE
Can i detect offsetTop event scroll when scrolloverflow:true

### ISSUE THREAD

**Issue by squalvj** [alvarotrigo/fullPage.js#3006]
Hello, this is an awesome plugin appreciate it.
is it possible to detect the top offset of the scroller in the section ?

**Comment by alvarotrigo** [comment]
Not something provided by fullPage.js.
But if you really need it you can check [my answer here](https://stackoverflow.com/a/39369282/1081396).

You might also want to check [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/2531).

**Comment by squalvj** [comment]
wow thanks, i love you man
