### ISSUE TITLE
Is fullpage.js compatible with vue.js? 

### ISSUE THREAD

**Issue by kaochihhui** [alvarotrigo/fullPage.js#3011]
Hi, 

Thank you for this awesome creation. 

Right now we are using vue.js in our projects and after importing the fullpage.js plugin, nothing appears on the page.

Just wondering if this plugin compatible with vue.js?

Thank you for your time.

**Comment by alvarotrigo** [comment]
Of course it is. As any other javascript library out there. 
You just need to know how to use it in combination with a framework that dynamically generates content on the DOM.

And I'm afraid this is not the best place to ask for that :)
