### ISSUE TITLE
Auto scroll-up only on first section (hybrid:true issue)

### ISSUE THREAD

**Issue by Sylwia777** [alvarotrigo/fullPage.js#3013]
Hi, firstly I would like to thank you for such a useful tool, I love fullPage.js
I have used hybrid:true in combination with fp-normal-scroll class on my website to achieve autoscroll only in first section and it works great

One question: there is autoscroll on first section - while scrolling down, but when I scroll up it doesnt autoscroll back to section one. How can I achieve this - to auto scroll up? Here is an example:
http://ruya.ae/work/al-erkyah-city/

Many thanks,
Sylwia

**Comment by alvarotrigo** [comment]
@Sylwia777 sun away from the `hybrid` option and `fp-normal-scroll`. It is not supported. Expect bugs in certain cases. 

You should be using the scrollOverflow option instead.

**Comment by Sylwia777** [comment]
@alvarotrigo thanks for quick answer. 
I have already tried scrollOverflow option, but in this case normal scroll is "square", "steps", not smooth.
Is there a way to achieve smooth scroll in scrollOverflow option?

Best,
Sylwia

**Comment by alvarotrigo** [comment]
The [demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html) seems to be working quite smooth to me.

**Comment by Sylwia777** [comment]
Demo page is perfectly smooth on mobile device, but on my desktop (Chrome), scrolling is making "steps":
https://youtu.be/0UhBidZlllY

in compare to normal scroll:
https://youtu.be/GpiYPv9fyE8

Can you recognize a reason of this situation?

Thanks a million,
Sylwia

**Comment by alvarotrigo** [comment]
I do not have a window machine where I can test your issue, but it works fine in Mac :)
If there's any issue with iScroll you should better ask [in their forum](https://github.com/cubiq/iscroll/).

**Comment by Sylwia777** [comment]
@alvarotrigo thanks for this tip!
One last question:
scrolloverflow.min.js is a customized version of iScroll.js. 
Should I replace scrolloverflow.min.js with iScroll.js to have a possibility of changing it basing on iScroll's documenation?

Best greetings,
Sylwia

**Comment by alvarotrigo** [comment]
Nop. No need for that. Just pass the options to iScroll through the fullpage.js option `scrollOverflowOptions.`

**Comment by Sylwia777** [comment]
That sounds interesting! I'll try. Thank you @alvarotrigo for all your help, and I send you best greetings from Poland.

Sylwia

**Comment by alvarotrigo** [comment]
Best of luck! ;)
