### ISSUE TITLE
ScrollOverflow on mobile does not work with Fullpage Extensions File

### ISSUE THREAD

**Issue by audramorgan** [alvarotrigo/fullPage.js#3015]
### Description

Hi there,

Great plugin! I have a few sections on my site that contain a lot of content so I used `scrollOverflow:true` and `normalScrollElements: #scrollbar-section` in my fullpage settings. For the `#scrollbar-section` div, I set a max-height and `overflow-y:scroll`. 

Using the normal fullpage.js file, the scrollable div within the fullpage section works perfect. However, I purchased an extension for another aspect of the site and when I switch the fullpage.js file to the fullpage extensions file, the scroll overflow no longer works on mobile.

### Link to isolated reproduction with no external CSS / JS

Here is the fiddle for the working version with fullpage.js file:
https://jsfiddle.net/drufbpkt/3/

Here is the fiddle for the non-working version with fullpage.extensions.min.js:
https://jsfiddle.net/drufbpkt/2/

### Steps to reproduce it
1. Open each JS Fiddle on a mobile device and try to scroll through the content within the gray box.

### Versions 
Tested on iPhone using Chrome and Safari browsers.

Thanks for your help!

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll investigate it!

**Comment by audramorgan** [comment]
Thank you so much! I would so appreciate your help. I love this plugin.

We are hoping to launch our site tomorrow afternoon and it is 100% my fault that I'm reporting this so late in my own timeline, but I wondered if it is viable to have a resolution before we launch or if there is anything I can do to help. 

I totally understand if that's unreasonable!

**Comment by alvarotrigo** [comment]
> I totally understand if that's unreasonable!

Please [contact me](https://alvarotrigo.com/#contact) about it.
