### ISSUE TITLE
How can I apply autoscroll only on specific sections

### ISSUE THREAD

**Issue by rippleytrigger** [alvarotrigo/fullPage.js#3016]
Hi there,

I am using this plugin in one page of a wordpress project, and this page has seven sections, in which three of them are going to work with autoscroll and the other four are going to work with normal scroll.  

Right now I am having some problems to make this plugin to work only in that sections, so I  need to know is this function is possible.

Great plugin by the way!!

**Comment by alvarotrigo** [comment]
You should go for the scrollOverflow option as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html). 
There's no better way to deal with it at the moment.
