### ISSUE TITLE
"scrollOverflow:true" seems not work in 2.9.5

### ISSUE THREAD

**Issue by CradleLiu** [alvarotrigo/fullPage.js#3017]
I tried 2.9.4 and it's okay

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
