### ISSUE TITLE
Video is not auto-playing. I don't understand why?

### ISSUE THREAD

**Issue by abhishek-suresh** [alvarotrigo/fullPage.js#3018]
First of all, great plugin. Absolutely love the features.

### A video with source on the banner(hero) section isn't auto-playing. I couldn't figure out the reason.

I am pasting below the code

`<div id="fullpage">
   
        <div class="section">
        <div class="hero">
                <video playsinline autoplay muted loop>
                    <source src="assets/video/women%20browsing.mp4" type="video/webm">
                    <source src="assets/video/women%20browsing.mp4" type="video/mp4">
                </video>
                
            <div class="container">
                <div class="row">
                    <div class="hero-caption">
                        <h2 class="display-4">Pick Stitch and Deliver</h2>
                        <p class="lead"><span>Premium</span><span> custom</span><span> tailoring</span><span> services</span><span> for</span><span> men</span><span> and</span><span> women</span><span> at</span><span> your</span><span> doorstep</span></p>
                        <i class="fa fa-phone-square" aria-hidden="true"></i>
                        <br><br>
                        <a href="#" class="btn btn-lg btn-primary ">Talk to us</a>
                    </div>
                </div>
            </div>
        </div>
        </div>`

The section is inside the fullpage tag but Its not coming inside the code structure. please note that.

When I remove the section parent from hero, the video is working (autoplaying) perfectly but that messes up the website. What could be done.

Thank you for your time.

**Comment by alvarotrigo** [comment]
Check https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media

**Comment by abhishek-suresh** [comment]
Thanks a lot man.
