### ISSUE TITLE
Disable "jump to first section" on page load

### ISSUE THREAD

**Issue by cellulosa** [alvarotrigo/fullPage.js#3019]
Hi @alvarotrigo and congrats for the great plugin. Sorry if this question has already been answered elsewhere, I googled and looked at the documentation but I couldn't find it.

Is it possible to disable the "jump to first section" on page load? I have a first portion of the page which is not a fullpage.js section, but this gets skipped when I enable the plugin.

Thanks

**Comment by alvarotrigo** [comment]
I'm not sure to understand your question. 
fullPage.js is a full-page library :) It expects to be always taking the whole viewport.

**Comment by thisisfed** [comment]
@cellulosa I'm sure that if you ask on Stackoverflow you'll get what you need. A simple js workaround can do the trick.

**Comment by cellulosa** [comment]
Thank you everybody for your replies.

Well, basically my first section is a layerslider slider that should auto-resize to fit the screen. However, when I render it as a fullpage.js section, the slide does not stretch properly so that white borders appears at the top and bottom of the screen. I could hack it out of the viewport before calling fullpage.js, or else I was hoping to block the "jump to first section" behaviour without too much tweaking.

**Comment by alvarotrigo** [comment]
Not sure what's your issue, but it seems to be a very specific one in your page rather than a direct fullpage.js issue. I'll close the issue for now.
