### ISSUE TITLE
normalScrollElements issue

### ISSUE THREAD

**Issue by Sylwia777** [alvarotrigo/fullPage.js#3022]
Hello,
Alvaro thanks again for great fullPage.js which I appreciate a lot.

I am still trying to achieve normal scroll  after auto scroll section.
I have used normalScrollElements option for one of the sections*:
https://jsfiddle.net/Sylwia777/ms73xx5o/1/
and it works fine except when scrolling back from normalscroll to autoscroll section - it doesn't go back automaticly and nicely to the next section, but with some delay. And when scrolling down from normal to auto section it almost skips following section and jums to the next one.

Is there some way to fix this scrolling flow? It seems i'm close to the solution, but there lacks a bit.
I will be grateful for any advise.

Best greetings,
Sylwia

*I know that normalScrollElements option is not ment for whole section but smaller divs and I have already tried: [scrollOverflow method](https://alvarotrigo.com/fullPage/examples/scrolling.html) but it doesn't seem to be solution for me, as I want to keep whole content with one "scrollbar flow" throught all scrolable and nonscrolable sections, and to not split it for two scrollbars.

**Comment by alvarotrigo** [comment]
> and it works fine except when scrolling back from normalscroll to autoscroll section - it doesn't go back automaticly and nicely to the next section, but with some delay.

It is not something provided by fullPage.js I'm afraid. As you said, it is not suppose to be used that way so I do not provide support for it.
