### ISSUE TITLE
FullPage scroll and Fading Effect mix

### ISSUE THREAD

**Issue by Sylwia777** [alvarotrigo/fullPage.js#3026]
Hello,
I would like to ask if is there a possibility to mix a standart fullPage auto scroll with Fading Effect extension: for example text is auto scrolling and background fading?

Best regards,
Sylwia

**Comment by alvarotrigo** [comment]
> I would like to ask if is there a possibility to mix a standart fullPage auto scroll with Fading Effect extension: for example text is auto scrolling and background fading?

Not something provided by fullPage.js,but surely something you can accomplish yourself by making use of fullPage.js features such as callbacks or state classes.
