### ISSUE TITLE
Issues with scrolling 

### ISSUE THREAD

**Issue by Redaktion123** [alvarotrigo/fullPage.js#3031]
### Description
Hi there,

First of all, thank you for the great plugin. But i am right now expirience a small problem with scrolling down, using the plugin.
Basically we tried it on a Mac, where it works perfectly and we also tried it on 2 different PCs, where it only works on one of them.
The issue is as follows: When I am trying to scroll from section 1 to section 2, it basically overscrolls it and shows me section 2 and a part of section 3. After this it all breaks down and it doesn't scroll normal anymore. Scrolling with the keyboard works fine. This issue only derives with the mouse.

### Versions 
I am using Google Chrome as the browser.

**Comment by alvarotrigo** [comment]
> The issue is as follows: When I am trying to scroll from section 1 to section 2, it basically overscrolls it and shows me section 2 and a part of section 3. After this it all breaks down and it doesn't scroll normal anymore.

Sounds a bit weird. I'm not able to reproduce it on the [demo page](http://alvarotrigo.com/fullPage/).
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md). With no external CSS or JS to fullPage.js and the minium HTML markup for it. Ideally with empty sections.

**Comment by Kennersky** [comment]
Check chrome extend plugin,try to disable it。
