### ISSUE TITLE
Device mockup overflow issue

### ISSUE THREAD

**Issue by kreatiflog** [alvarotrigo/fullPage.js#3035]
Hi, i'm making an app introduction, i put phone mockup as fixed. App content fits perfect but while scrolling the page content overflow the phone mockup. Is there any thing i can do?

```
	<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage();
		});
	</script>
<div class="container main">
    <div class="row">
        <div style="background-image:url(phone.png); background-repeat:no-repeat; width:285px; height:580px; position:fixed; z-index:1;"></div>
        <div id="fullpage" style="height:200px;">
            <div class="section active" id="section0">
            <img src="1.png" width="285">
            </div>
            <div class="section" id="section1">asdasda</div>
            <div class="section" id="section2"><h1>No wraps, no extra markup</h1></div>
            <div class="section" id="section3"><h1>Just the simplest demo ever</h1></div>
        </div>
    </div>
</div>
```

[As you can see here](https://youtu.be/76Y-Q-QiokA)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by kreatiflog** [comment]
Actullay it is not an issue i think couldn't make it.

**Comment by kreatiflog** [comment]
any ideas?

**Comment by alvarotrigo** [comment]
Nop. You'd better ask in other place such as stackoverflow.com
This forum is only to deal with fullpage.js issues or basic questions regarding its features.
