### ISSUE TITLE
Static Image

### ISSUE THREAD

**Issue by jafrinpeter** [alvarotrigo/fullPage.js#3036]
Hi,

I like to use one static image in 2nd section onwards, It should stay from 2nd to last section. rest of the contents should scroll as usual. How do i achieve that

**Comment by alvarotrigo** [comment]
Use a fixed positioned image with css.
Then use  the fullpage.js option `css3:false`.

**Comment by jafrinpeter** [comment]
i have saw your example, is it possible to  display image from section 2 to 6.

**Comment by alvarotrigo** [comment]
Many things are possible with the right CSS / JS knowledge. But you'd better ask in other place such as stackoverflow.com where they'll be able to help you better in those matters.
