### ISSUE TITLE
How to refresh iScroll? 

### ISSUE THREAD

**Issue by sandyno** [alvarotrigo/fullPage.js#3037]
Hi I have a concern, I have a page that has 3 sections, I set the scrollOverflow: true which is working fine but I want to know how to reset the iScroll. The last section is where the normal scroll and at the bottom of it there is an up button arrow that when is clicked it will move you back up to the first slide but the issue is when you get to the last section again you are already at the bottom of that section. Is there a way that I can reset iScroll when the up arrow button is clicked?

**Comment by alvarotrigo** [comment]
Use the [Scrolloverflow reset extension]( https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html )

**Comment by sandyno** [comment]
Thank you for your quick response @alvarotrigo
