### ISSUE TITLE
Unexpected close featherlight.js in mobile version

### ISSUE THREAD

**Issue by squalvj** [alvarotrigo/fullPage.js#3038]
Hi i'd like to ask, why my featherlight always unexpected close when i work with fullpagejs at mobile version with autoscrolling:true

when i open my featherlight.js it always get closed before the content even load
here i how i use my fetherlight: 

`<img class="image-link tab-img" href="<?= $img; ?>" data-featherlight="<?= $img; ?>" src="<?= $img; ?>">`

**Comment by alvarotrigo** [comment]
I have no idea what featherlight is. 
If you believe this is a bug in fullPage.js please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

I'll close the issue until then.
