### ISSUE TITLE
Set SlideIndex

### ISSUE THREAD

**Issue by gstrobl** [alvarotrigo/fullPage.js#3039]
Hey,
I need a solution to set the slideindex on a other value. Is is possible to do this with your libary? Alternative solution would be to this like your setUrlHash function?

**Comment by alvarotrigo** [comment]
Read about `data-anchors` here:
https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides

**Comment by gstrobl** [comment]
I read about data-anchors, but this doesn't help me. I want to start at the second slide. Like the scrollSlider fn but without scrolling animation.

**Comment by alvarotrigo** [comment]
Then read in the docs about the use of `active` class:
https://github.com/alvarotrigo/fullPage.js#required-html-structure
