### ISSUE TITLE
when i use angularJs v1 angularjs not working

### ISSUE THREAD

**Issue by hadijahangiri** [alvarotrigo/fullPage.js#3040]
when i use angularJs v1 angularjs not working
example:
<div id="fullpage">
    <div class="section slider active" id="section0">
        <img class="main" ng-src="{{mainImage}}" />
       
    </div>
    <div class="section" id="section1">
        <div class="slide"><h1>Section 2</h1></div>
        <div class="slide"><h1>Slide 2.2</h1></div>
        <div class="slide"><h1>Slide 2.1</h1></div>
    </div>
    <div class="section" id="section2"><h1>Section 3</h1></div>
</div>

"mainImage" not show

**Comment by alvarotrigo** [comment]
Check out the [resources section](https://github.com/alvarotrigo/fullPage.js#resources) for angular directives.

Otherwise destroy('all') and initialise fullpage.js again with each new call.
