### ISSUE TITLE
using with the hamburger menu

### ISSUE THREAD

**Issue by kaylieko** [alvarotrigo/fullPage.js#3042]
Hello, 
I try to use the anchor link with the hamburger menu, but it doesn't go to the correct section when I click the <a> link on the menu. I am using below javascript  with your fullpage.js, I am guessing that I need to change the 'set_clip_property()' function, but I have no idea how and where to fix.
Thank you in advance for your advice.

 

jQuery(document).ready(function ($) {

    $('.cd-menu-trigger').on('click', function (event) {
        event.preventDefault();
        $('#home-main').addClass('move-out');
        $('#main-nav').addClass('is-visible');
    });
   
    $('.cd-close-menu').on('click', function (event) {
        event.preventDefault();
        $('#home-main').removeClass('move-out');
        $('#main-nav').removeClass('is-visible');
    });

    //clipped image - blur effect
    set_clip_property();
    $(window).on('resize', function () {
        set_clip_property();
    });
    function set_clip_property() {
         var $header_height = $('.cd-header').height(),
             $window_height = $(window).height(),
             $header_top = $window_height - $header_height,
             $window_width = $(window).width();
             $('.cd-blurred-bg').css('clip', 'rect(' + $header_top + 'px, ' + $window_width + 'px, ' + $window_height + 'px, 0px)');
     }
     $('#main-nav a[href^="#"]').on('click', function (event) {
         event.preventDefault();
         var target = $(this.hash);
         $('#home-main').removeClass('move-out');
         $('#main-nav').removeClass('is-visible');
         $('body,html').animate(
            {'scrollTop': target.offset().top}, 900
         );
         });
});

**Comment by alvarotrigo** [comment]
I would encourage you to ask in other place such as stackoverflow.com
This forum is to provide support for fullPage.js issues and bugs as well as usage questions.

Your's seem to be more a Javascript knowledge question. 

If you want to know more about the use of hashes and fullPage.js please read the docs regarding the `anchors` options and the `menu` one. Also check the examples in the examples folder.
