### ISSUE TITLE
Pagination change color on scrolling

### ISSUE THREAD

**Issue by ni4yja** [alvarotrigo/fullPage.js#3043]
I am looking for a way pagination change color if section's background changes. I used afterLoad event, but it takes some time to change.

```
afterLoad: function(anchorLink, index) {
        var loadedSection = $(this);
        if(index == 1 || index == 3) {
            $('#fp-nav ul li a span').css("background-color", "antiquewhite");
        };
        if(index == 2 || index == 4) {
            $('#fp-nav ul li a span').css("background-color", "#002e34");
        }
    }
```
Are there any other opportunities to change pagination color immediately? Here is my pen https://codepen.io/ni4yja/full/GOYBzm/

**Comment by alvarotrigo** [comment]
Then use the `onLeave` callback instead or the `active` [state class](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) of the sections.

Check [my video here](https://www.youtube.com/watch?v=qiCVPpI9l3M&t=1s).
