### ISSUE TITLE
disable iscroll until section is loaded completely

### ISSUE THREAD

**Issue by sandyno** [alvarotrigo/fullPage.js#3044]
Hi is there any way to disable iScroll until scrolling is finished? or disable scrolling itself until the next section is done scrolling? I'm having an issue when I'm scrolling to the next section , this section is set to scroll normally but the problem is if you scrolled too much -- like continously  (touchpad) that section begin to scroll too even if the scrolling isn't completely finished yet then bounce back up because I'm using scrollOverflowReset extension.

**Comment by alvarotrigo** [comment]
Sorry but I would need you to provide a reproduction of it to be able to help you at all.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by sandyno** [comment]
@alvarotrigo sorry for late response, I fixed it, for some reason I have put resize trigger to the onleave callback and that is the reason behind the bounce up hehe. Thank you for being responsive  :)

Happy New Year!!!
