### ISSUE TITLE
Textarea not accepting white-spaces/spaces

### ISSUE THREAD

**Issue by marcreyesph** [alvarotrigo/fullPage.js#3045]
Textarea does not accept white-spaces whenever a user tries to press the spacebar, a space doesn't show up. Error shows on all major browsers (i.e. Chrome, Firefox, Safari)

It somehow kind of worked when I removed Case 32 (shown below) which is the spacebar on the controls, though when the page is refreshed, it will automatically load to where the textarea is located which should not happen. I'm using the pure JavaScript (alpha) version of fullpage.js.

```JavaScript
var keyControls = [40, 38, 32, 33, 34];
            for(var i=0; i<keyControls.length; i++){
                if(keyControls[i] == charCode){
                    preventDefault(e);
                }
            }
```

```JavaScript
function onkeydown(shiftPressed, charCode){
        switch (charCode) {
            //up
            case 38:
            case 33:
                moveSectionUp();
                break;

            //down
            case 32: //spacebar
                if(shiftPressed){
                    moveSectionUp();
                    break;
                }
```

An example of the said bug can be found here: 
https://marcreyesph.github.io/deploy-sample/failing-whitespace.html

**Comment by alvarotrigo** [comment]
Working fine on this demo:
http://jsfiddle.net/97tbk/2193/

Please provide an isolated reproduction with no external CSS or JS to fullPage.js.
I'll close the issue meanwhile.
