### ISSUE TITLE
QUESTION: current section / total sections

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#3047]
I know I should ask in stackoverflow.com and places like that but it's maybe a super easy stuff:
I just want to get "current section / total sections". 

Any hint would be greatly appreciated.
Thanks,
Fed.

**Comment by alvarotrigo** [comment]
That's a jquery / Javascript knowledge question.

```javascript
//javascript
var numSections = document.querySelector('.fp-section').length

//jquery
var numSections = $('.fp-section').length;
```
