### ISSUE TITLE
"ReferenceError: assignment to undeclared variable g_isAboutToRewindVertical" on scrolldown in parallax library

### ISSUE THREAD

**Issue by dazjohnson** [alvarotrigo/fullPage.js#3048]
I'm getting the following error when trying to scroll down with the parallax library enabled. This prevents scrolling. Turning parallax off and it's fine (but obvs without parallax).

ReferenceError: assignment to undeclared variable g_isAboutToRewindVertical

Using v0.0.6 of the parallax lib and fullPage 2.9.3 - Extensions 0.0.7.

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with a link to the reproduction.

**Comment by alvarotrigo** [comment]
Closed due to lack of data from the author.

**Comment by stuseek** [comment]
@alvarotrigo i was able to reproduce this bug.
The issue here is **babel**. Igonring this file in babel options helped us to fix it.

**Comment by alvarotrigo** [comment]
@stuseek I guess you are college of @dazjohnson?

**Comment by stuseek** [comment]
@alvarotrigo no, another "us" :)

**Comment by alvarotrigo** [comment]
@stuseek I'm confused. So, where did you acquire the parallax extension?

**Comment by stuseek** [comment]
@alvarotrigo purchased an extension, did you try to use it with babel?

**Comment by alvarotrigo** [comment]
@stuseek can you please [contact me](https://alvarotrigo.com/#contact) so I can ask you some more questions to understand it?

**Comment by stuseek** [comment]
@alvarotrigo sent you an email, check it

**Comment by alvarotrigo** [comment]
@stuseek I replied you already :)
