### ISSUE TITLE
setAllowScrolling + normalScrollElements + scrollBar fails

### ISSUE THREAD

**Issue by slonikys** [alvarotrigo/fullPage.js#3050]
Hi there!

First, great plugin, many thanks indeed!
Second, this may sound very noobish, but i cant figere it out ! Wenn i use  normalScrollElements: ".scrollable-element1", and $.fn.fullpage.setAllowScrolling(false, "down, up"); i still can slide to top and botom ! Sorry for my English !

**Comment by alvarotrigo** [comment]
I'm not quite sure to understand your issue.

Could you please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md ?

**Comment by slonikys** [comment]
http://whitebubble.altera.media/

second section and slide !

**Comment by alvarotrigo** [comment]
Your callback is not using the right order for the params and your condition is wrong in the example you provided.

Nevertheless, I've tested it myself and you are right, it appears to be some kind of bug there.
I'll check it out for the next release!

**Comment by slonikys** [comment]
can u tell me wenn next release ?

**Comment by alvarotrigo** [comment]
If you are in a rush [contact me](https://alvarotrigo.com/#contact) for an urgent request.

**Comment by alvarotrigo** [comment]
Otherwise just make sure to use `scrollBar:false` if you want to avoid the issue.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch. Will get merged in fullPage.js 2.9.6
