### ISSUE TITLE
Unable to scroll custom element in Fullpage.JS

### ISSUE THREAD

**Issue by xeriuk** [alvarotrigo/fullPage.js#3051]
### Description
I'm currently busy with a website using your fullpage.js plugin. Everything is working perfectly except for 1 thing. I have made a sidebar where I have included the website's menu. As you can see in the link provided below, the sub items of the menu are able to collapse when clicked on the little arrow. After you have opened some subitems the submenu get's to big to be able to see on your mobile screen. That's why I want to enable the scroll on the menu ul with overflow-y:scroll and a fixed height (this normally works).

When I verify this with my Chrome developer tools its working as intended. But when I try to scroll on my iPhone it doesn't work. I tried everything I could but sadly I can't find anything that helps.

I'm not really sure if this is a bug of fullpage.js, or something I forgot to add the the options or something.

If you can guide me if this isn't a bug, I'll be very happy :)

### Link to isolated reproduction with no external CSS / JS
http://koekbreak.daretodevelop.com/ (private non indexed subdomain of my work)

### Versions 
Scroll not working on mobile

**Comment by alvarotrigo** [comment]
I do not review websites I'm afraid.

Could you please provide an isolated reproduction with no external CSS and JS and the minimum HTML code possible?
Use empty sections unless the content is necessary for the reproduction of the issue.

**Comment by xeriuk** [comment]
Hi,

I tried to make it as clean as possible. It's hard to remove all the unnecessary CSS so I let that all in.

https://codepen.io/anon/pen/dJzxBb

Sadly it doesn't load for me on my iphone so i'm not 100% the issue is also present in the codepen

**Comment by alvarotrigo** [comment]
> Sadly it doesn't load for me on my iphone so i'm not 100% the issue is also present in the codepen

You can upload to your server in a subfolder.

**Comment by alvarotrigo** [comment]
Did you check the use of the option `normalScrollElements`? Check it out.
That might be what you are missing.

**Comment by xeriuk** [comment]
That was the case! It's fixed now, thank you very much!
