### ISSUE TITLE
All the page content stack up before loading the js

### ISSUE THREAD

**Issue by darshkoreGC** [alvarotrigo/fullPage.js#3052]
Hi, I am facing the issue where all the slide content stacks on top before displaying/loading actual fullpage.js.. it happens for a sec by is really unprofessional. 

here is the screenshot. 

<img width="1414" alt="screen shot 2018-01-04 at 4 22 36 pm" src="https://user-images.githubusercontent.com/15650577/34560388-895b3914-f16b-11e7-9faf-910af4896890.png">

**Comment by alvarotrigo** [comment]
That's up to to the developer and how he wants to deal with it. 
I usually recommend people to initialise fullpage.js in the document ready function as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#initialization).

But you can also set the height of all sections to 100% on your own CSS before fullpage.js even gets initialised. 

As you can see that issue won't take place in the [demo page](https://alvarotrigo.com/fullPage/) or any of the other examples.
Take a look at them.

**Comment by alvarotrigo** [comment]
Thanks for the feedback! I'll consider it.

**Comment by geochanto** [comment]
@alvarotrigo I'm running into the same issue on react-fullpage. Since I have no access to domready... any suggestions how to deal with it? Setting CSS for .section to 100% doesn't seem to work, even if I inline it on the page before fullpage JS gets loaded.

**Comment by alvarotrigo** [comment]
See [my reply here](https://github.com/alvarotrigo/fullPage.js/issues/3425).

CSS will for sure do the trick, that's what I'm using in the fullpage site, the vue-fullpage one and the react-fullpage one.

**Comment by geochanto** [comment]
No it still does not work. I'm using nextjs. JS assets are using rel="preload". Perhaps that has something to do with it, but as of now your CSS still having no effect :/

**Comment by alvarotrigo** [comment]
This is not really a fullpage.js issue.
Try without using fullPage.js first. Get your section full height with pure HTML + CSS.

Once you have that, add fullpage.js.

**Comment by geochanto** [comment]
OK after much trial and error I came up with a hack. Seems to be working. Maybe it helps someone else later:

1. create a state for the 'display' CSS property, set it to 'none'
2. add inline CSS to each section and set 'display' to your state variable
3. add afterRender() callback to ReactFullpage that sets the state of the variable to 'table'.

basically all sections are hidden until they're finished loading, and then they display.
