### ISSUE TITLE
destroy() removes styles that weren't added by fullPage.js

### ISSUE THREAD

**Issue by Prinzhorn** [alvarotrigo/fullPage.js#3059]
### Description

The `destroy()` method, more specifically the [`destroyStructure()`](https://github.com/alvarotrigo/fullPage.js/blob/fc34fb061ea7e03dac93a45c0673b2307ee6a76d/jquery.fullPage.js#L2711-L2731) function, removes (unsets) inline-styles such as `background-color`. The issue is that these can be styles that were not originally added by fullPage.js, but were already there when it was initialized. For example `background-color` is only set when using the `sectionsColor`option and should only then be removed.

Quoting https://github.com/alvarotrigo/fullPage.js/issues/1669#issuecomment-158928391

> fullPage.js will only remove the styles it added or any inline style that fullpage.js might add.

Quoting the docs https://github.com/alvarotrigo/fullPage.js#destroytype

> This way the original HTML markup, the one used before any plugin modification is made, will be maintained.

One possible solution is to cache `element.style.cssText` (for example using jQuery's `data()`) so it can be reset to the original state. This will still not catch cases where the inline style has been modified in between, but it will put the page in the exact state it was before fullPage was initialized, thus acting as advertised.

**Comment by alvarotrigo** [comment]
Great suggestion! Thanks for reporting it!
I'll take it into account! 

Also, feel free to create a pull request if you think you found a good solution!

**Comment by alvarotrigo** [comment]
This has been solved in the dev branch 2.9.6. Will get merged in the next release.

**Comment by Prinzhorn** [comment]
Nice!

**Comment by alvarotrigo** [comment]
I added your suggestions.
