### ISSUE TITLE
How to select active section

### ISSUE THREAD

**Issue by jafrinpeter** [alvarotrigo/fullPage.js#3061]
### Description

Hi,

How do i select active section, because i have to display some contents only in last 3 sections, in rest of the sections that content should not display. 

Here is my requirement clearly, i am having totally 6 sections, all sections having contents and its working perfectly on mouse scrolling. I have to add some content outside the sections and it should display only for last 3 sections, and that content should not scroll....

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operative system, device...]

**Comment by alvarotrigo** [comment]
> How do i select active section, because i have to display some contents only in last 3 sections, in rest of the sections that content should not display.

Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
