### ISSUE TITLE
Enable scrolling of content in slide in panel on iPhone

### ISSUE THREAD

**Issue by gregorywilliam** [alvarotrigo/fullPage.js#3062]
### Link to isolated reproduction with no external CSS / JS
http://www.daneliandesigns.co.uk/BKS/

### Steps to reproduce it
The slide in formform does not scroll down on iPhone 

(you have to click the [+] button to activate slide in panel). 

I have FullPage.js enabled and this is working well. The content in the second section is scrollable on mobile but when the slide in panel is activated you cannot scroll the form down on iPhone to reach submit button.

### Versions 
[iPhone]

**Comment by alvarotrigo** [comment]
I'm afraid I do not check specific pages and use cases.
If you believe this is a bug please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

I'll close the issue until then.
