### ISSUE TITLE
With the mobile version of the site, the height does not stretch to the full screen

### ISSUE THREAD

**Issue by YuraAnonim** [alvarotrigo/fullPage.js#3065]
Thank you for your work!
I need your help, because I could not find a similar topic in the discussions (

With the mobile version of the site, the height does not stretch to the full screen (see the emptiness at the bottom of the screen). What could be the problem?
Sorry for my english

$(document).ready(function() {
                $('#fullpage').fullpage({
                    css3: true,
                    verticalCentered: false,
                    scrollOverflow: true,
                    
                    dragAndMove: true,
                    slidesNavigation: true,
                    navigationTooltips:['Главная','Услуги','Стоймость','Заявка','Контакты','О нас'],
                    loopBottom: true,
                    anchors: ['firstPage','secondPage','thirdPage','fourthPage','fifthPage','sixthPage']
                });
            });

![lrcunfuvfyw](https://user-images.githubusercontent.com/35377462/34887673-5c8e2f36-f7d8-11e7-93b4-a78f3018dd85.jpg)
![t7tgmg59esy](https://user-images.githubusercontent.com/35377462/34887674-5cb3a496-f7d8-11e7-9d2a-839481961bd6.jpg)
![whwrr78zy3w](https://user-images.githubusercontent.com/35377462/34887675-5cd765a2-f7d8-11e7-880c-8b75435861b9.jpg)

**Comment by alvarotrigo** [comment]
Sorry I not review specific websites. 
If you believe this is a bug in fullPage.js, please provide an isolated reproduction with no external CSS or JS and the minimum HTML possible  as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
