### ISSUE TITLE
fullpage.js with share-point

### ISSUE THREAD

**Issue by rosell921** [alvarotrigo/fullPage.js#3066]
When integrating my project into SharePoint the background of the parallax scrolling will disappear on large screens, it will work again on small screens but that because I added the following function

afterResponsive: function(isResponsive){
					$.fn.fullpage.parallax.destroy();
				},
witsh means the parallax scrolling JS  is clashing some how the ShaPoint JS

### Versions 
[ei and chrome and firfox]

**Comment by alvarotrigo** [comment]
No idea what SharePoint and what it does. 
If you believe this is a bug in fullPage.js please create an isolated reproduction of the issue and [contact me](https://alvarotrigo.com/#contact) for the extensions support.

**Comment by alvarotrigo** [comment]
I'll close the issue as extensions support is provided by email.
