### ISSUE TITLE
jQuery: if .fp-scroller is scrolled

### ISSUE THREAD

**Issue by rubaff** [alvarotrigo/fullPage.js#3067]
Short question: is there some kind of callback for the fp-scroller?
I'd like to set a class once the scrollOverflown section is scrolled.

Thanks and thanks again for the great work on this project!

**Comment by alvarotrigo** [comment]
Nop, there's no such callback but why not using `onLeave` ?
Once scrolled the page will scroll to the next section/slide if exist. So `onLeave` or `onSlideLeave` will get fired at the same time.

**Comment by rubaff** [comment]
Thanks!
I mean when scrolling inside of an scrollOverflow: true section - not when leaving to the next section via scrolling :)

**Comment by alvarotrigo** [comment]
I know what you mean. 
But what's the difference, is you'll automatically scroll to the next section/slide when finishing scrolling scrolloverflow?

**Comment by rubaff** [comment]
Ah, I see - but I would like to set the class already after let's say 1px of scrolling in the section (even though the overflown section might be 10,000px in height).

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any option to do so. 
Nevertheless, take a look at [my reply here](https://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl), it might help you.

**Comment by rubaff** [comment]
Thank you!

Working now with this code:

`afterLoad: function(anchorLink, index){
            var iscroll = $('.fp-section.active').find('.fp-scrollable').data('iscrollInstance');
            if(iscroll && typeof iscroll !== undefined){
                iscroll.on('scrollStart', function(){
                    $('#header').addClass("SCROLLED");
                });
            };
        },`
