### ISSUE TITLE
Can't find solution for bug with a contact form and fullPage.js

### ISSUE THREAD

**Issue by Jakoli** [alvarotrigo/fullPage.js#3068]
Hello!

So I develop a website, and javascript is not my strength. I created a contact form I'm trying several solutions for a few hours but I couldn't find any! When I click the button submit it pushes the contact form to the top and then all the sections are not right!

Sorry for post it here but I couldn't find any other place to post it.

Thank you very much!!

[githubbug.zip](https://github.com/alvarotrigo/fullPage.js/files/1636476/githubbug.zip)

EDIT: Issue updated with the zip.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Jakoli** [comment]
Sorry!

I didn't manage to put everything in the best way on jsfiddle, so I cleared the code and I left only what matters to you in the zip.

1. Open index.html
2. Scroll down and click Submit from the contact form
3. And if you scroll up you will see that some bug appeared.

[githubbug.zip](https://github.com/alvarotrigo/fullPage.js/files/1636476/githubbug.zip)

**Comment by alvarotrigo** [comment]
Unfortunately I do not review zip files or specific websites.
As detailed in the reporting issues guideline

> An isolated reproduction of the issue will be required.

**Comment by Jakoli** [comment]
Hi,

In the JSFiddle I guess you can see.

http://jsfiddle.net/97tbk/2230/

Thanks!!

**Comment by alvarotrigo** [comment]
Please remove any CSS or JS that doesn't belong to fullPage.js unless strictly required for the reproduction.
Same with the HTML code, use empty sections ideally except the form you need.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
