### ISSUE TITLE
Stop auto moveSectionDown when user clicks or swipes to section

### ISSUE THREAD

**Issue by hprata** [alvarotrigo/fullPage.js#3069]
Is there a way to Stop auto moveSectionDown when user clicks or swipes to section

```javascript
$(document).ready(function() {

// DELAY	
setTimeout(
function() 
{
// DELAY		

// START SCROLL	
$('#fullpage').fullpage({
	navigation: true,
	menu: '#mySidenav',
	loopBottom: true,
	scrollingSpeed: (1000),
        afterRender: function(){
            setInterval(function(){
                $.fn.fullpage.moveSectionDown();
            }, 3500);
        }
    });
 // END SCROLL		

 // END DELAY		 
}, 4000);
 // END SCROLL		

});
```

**Comment by alvarotrigo** [comment]
Not a fullPage.js issue but a Javascript knowledge one. 
In any case, just clear the interval:

```javascript
var g_moveDownId;
$(document).ready(function() {

// DELAY	
setTimeout(
function() 
{
// DELAY		

// START SCROLL	
$('#fullpage').fullpage({
	navigation: true,
	menu: '#mySidenav',
	loopBottom: true,
	scrollingSpeed: (1000),
       onLeave: function(){
            clearInterval(g_moveDownId);
        },
        afterRender: function(){
            g_moveDownId = setInterval(function(){
                $.fn.fullpage.moveSectionDown();
            }, 3500);
        }
    });
 // END SCROLL		

 // END DELAY		 
}, 4000);
 // END SCROLL		

});
```

**Comment by hprata** [comment]
Sorry I don't think I was clear on what I am trying to do. I tried something like this but the moveSectionDown interval stops after the first move. What I am looking for is for the sections to keep moving down until a user clicks or swipes then it clears the interval

**Comment by alvarotrigo** [comment]
Just follow the same logic. Clear the interval under the conditions you want. 

If you don't know how to deal with the conditions you'd better ask in other place such as stackoverflow.com where they'll be able to help you better on that matter.

**Comment by hprata** [comment]
never mind I think I know why my second atempt didn't work.
Thx
