### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by figtreedigital** [alvarotrigo/fullPage.js#3070]
### Description
Hi there, I think I have found a little bug that is happening on a website I developed with the help of fullpage.js. Its a little hard to replicate but I will try my best to explain. Please note you might need to try these steps over 6 times in a row for the bug to show up.

Steps to replicate the issue:
1. Scroll down and click on one of the Interior design projects.
2. Click the next link or prev link to access the next project
3. Click the hamburger icon then click on project
4. Try this up to 5 times in a
I have attached screenshot of the glitch. As you can see it blank. It also sometimes get stuck in between two section. It seams to be something with the Interior design project section.

Any ideas how would I go about fixing this bug?

### Link to isolated reproduction with no external CSS / JS
Sorry it not possible for me to isolate the reproduction externally. 
![issue-madebymad](https://user-images.githubusercontent.com/29763663/35082451-cdc941be-fc69-11e7-8f6e-c47ebf166eaf.png)

### Versions 
Mac Chrome. Does happen on Fire fox as well.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

Try to remove any CSS or JS that doesn't belong to fullPage.js unless strictly required for the reproduction.
Same with the HTML code, use empty sections ideally except the form you need.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by CourtneyJooste** [comment]
I had a similar issue if not the exact same. Hard to explain how it happens other than you navigating a lot in a small time-frame. It seems to break everything even after a refresh? 

Fixes when I use responsive layout and resize the browser down and back to full size...

**Comment by alvarotrigo** [comment]
@CourtneyJooste nothing I can do without a clean isolated reproduction of it.
