### ISSUE TITLE
How does this plugin stop scrolling while performing fitToSection?

### ISSUE THREAD

**Issue by vdomah** [alvarotrigo/fullPage.js#3071]
Doing a bit of custom behavior so got a question:
How does this plugin stop scrolling while performing fitToSection? I need to manualy make .animate call in onLeave event and it works but animate is shaking because mousewheel continues to act. To illustrate here is video: https://www.dropbox.com/s/6b63lhpjixsbvop/ice_video_20180119-004426.webm?dl=0
Question is about first section. When mooving up - you can see the shaking - that's my animate call in onLeave that needs to be stabilized. So I just need to copy the behavior of mooving smoothly using plugin's fitToSection with autoScrolling, particulary mousewheel handling.

**Comment by alvarotrigo** [comment]
> How does this plugin stop scrolling while performing fitToSection?
Just check the [source code](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1259) and you'll find everything you need to know about fullPage.js :)

**Comment by vdomah** [comment]
Sure, I checked the source before posting the question, even modified some things there for my purposes. But didn't find the answer myself. Could you please point me not with explanation but just lines number where that happens?

**Comment by vdomah** [comment]
Problem seems not such big after sleep, sorry for bothering, my answer is in this line:
e.preventDefault ? e.preventDefault() : e.returnValue = false;
Problem was that preventDefault didn't work, returnValue did the trick.

**Comment by vdomah** [comment]
No, still that issue. The case is that I switch off and on the autoScrolling when exiting and entering 1st section accordingly:
    onLeave: function(index, nextIndex, direction){
            //after leaving section 2 up
            if(index == 2 && direction =='up'){
                if (!$.fn.fullpage.getAutoScrolling() && !window.scrollingToFirst) {
                    window.scrollingToFirst = true;
                    setTimeout(function () {
                        window.scrollingToFirst = false;
                        $.fn.fullpage.setAutoScrolling(true);
                    }, 500);

//without this animation viewport just jumps to 1st section like silentMoveTo(1)
                    $('html, body').stop().animate({
                        scrollTop: 0
                    }, 400, function() {
                    });
                }
                return false;
            }
            else
            if (index == 1 && direction == 'down'){
                if ($(window).scrollTop() == 0 && window.scrollingToFirst)
                    return false;

                window.scrollingToFirst = true;
                setTimeout(function () {
                    window.scrollingToFirst = false;
                    $.fn.fullpage.setAutoScrolling(false);
                }, 700);
            }

And when moving up from 2 to 1 I use manual animate call because fullPage autoScrolling doesn't work at that moment and throws viewport directly to the page top. That's the initial problem.

But manual animate gets interrupted by scrolling or swiping wich make it shakey. Wich is second problem. 

So I need to find answer for either 1 or 2.
Thanks!

**Comment by alvarotrigo** [comment]
You'd better ask in other place such as stackoverflow.com where they'll be able to help you much better.

This forum is to solve issues with fullPage.js features and yours is not within this category.
Hope you find your solution!
