### ISSUE TITLE
Moves to next section too early with scrollOverflow.js

### ISSUE THREAD

**Issue by KeironLowe92** [alvarotrigo/fullPage.js#3072]
When scrolling in a section with overflow content, it scrolls to the next section before you've got to the bottom of the scroll for the section you are in. 

### Link to isolated reproduction with no external CSS / JS
https://jsbin.com/desoqeseci/1/edit?html,js,output

### Steps to reproduce it
1: Scroll down

### Versions 
Chrome 63, OSX High Sierra

**Comment by alvarotrigo** [comment]
You are not including the css file correctly. You are missing `rel="stylesheet" type="text/css"` in here:

```html
  <link href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.5/jquery.fullpage.min.css" />
```

It should be
```
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.5/jquery.fullpage.min.css" />

```

**Comment by kovinet** [comment]
I have same problem, but with slides. 
I am using Vue Cli, so css includes look like this:

`
<link href=/css/app.699847bc.css rel=preload as=style>
<link href=/css/app.699847bc.css rel=stylesheet>
`
Could this be the reason for this behavior?

**Comment by alvarotrigo** [comment]
What are those css files? 
Where's fullpage one?

**Comment by kovinet** [comment]
I am using Vue with Webpack build. It compiles all css tu bundle and includes them like this. But as I checked  type="text/css" is not required anymore. I really dubt including css like this could lead to scrolling issues, could it?

**Comment by alvarotrigo** [comment]
Difficult to tell without an isolated reproduction. I would encourage you to see the [examples provided on the vue project](https://github.com/alvarotrigo/vue-fullpage.js/tree/master/demos).
