### ISSUE TITLE
Alternative for jQuery

### ISSUE THREAD

**Issue by ppsirius** [alvarotrigo/fullPage.js#3074]
I try to use fullpage.js without jquery but it has a bug with scrolling on mobile and it probably doesn't maintain. So I use a normal version of jQuery but it has weight a lot. Is it any alternative for jQuery?

**Comment by alvarotrigo** [comment]
I'm afraid not. This is a jQuery plugin :) 
Perhaps moving to plain JS if enough people request it. (which didn't happen yet)
