### ISSUE TITLE
Jumps to the bottom section when scrollbar reaches the top of the window

### ISSUE THREAD

**Issue by jeffreytfarrell** [alvarotrigo/fullPage.js#3075]
I have the following configuration:

```javascript
$(document).ready(function() {
	$('#fullpage').fullpage({
		autoScrolling:false,
		//scrollBar: true,
		navigation: true,
		navigationPosition: 'right',
		loopTop: false,
		anchors:['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'fifthPage', 'sixthPage']
	});

});
```
Scrolling with the scrollbar up and down the page works fine, except when the scrollbar reaches the top of the window. In this case, it jumps to the bottom section, even when loopTop is set to false. I want it to stay on the top section under these circumstances.

**Comment by alvarotrigo** [comment]
Use `fitToSection:false`.

If that doesn't solve the issue please provide an isolated reproduction in jsfiddle or codepen as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by jeffreytfarrell** [comment]
It partially fixes the issue. It no longer jumps to the last section, but the navigation dots on the right have the last dot highlighted as if it were jumping to the last section.

**Comment by alvarotrigo** [comment]
> If that doesn't solve the issue please provide an isolated reproduction in jsfiddle or codepen as detailed in the reporting issues guidelines and the issue skeleton.

**Comment by jeffreytfarrell** [comment]
A friend found a fix. Changing 908 of fullpage.js to the following:

var isAtBottom = $(document).height() - $window.height() === currentScroll;

instead of var isAtBottom = $body.height() - $window.height() === currentScroll;

This fixes the issue, i.e. change $body.height() to $(document).height()

**Comment by phoenix214** [comment]
Can you please push @jeffreytfarrell 's fix on the latest fullpage.js?

**Comment by phoenix214** [comment]
@alvarotrigo

**Comment by alvarotrigo** [comment]
@phoenix214 I am not able to reproduce the issue on the [autoScrolling:false demo page](https://alvarotrigo.com/fullPage/examples/normalScroll.html).

If you are able to provide an isolated reproduction of the issue we will definitely take a look at it and try to put a solution as fast as possible.
