### ISSUE TITLE
Disable window width responsive

### ISSUE THREAD

**Issue by seveguay** [alvarotrigo/fullPage.js#3076]
HI, I'm triying to load a background video but I'm considering the responsive design, I mean, I want to load a video for a width less than 415px and another one for less than 1025px, but I have a problem cause the width of the responsive view it's fixed with 980px. I tried with this the responsiveWidth option, but don't works.

I'm doing something like this:
```javascript
var widhtCon = $('#container_video').width();
if (widhtCon<415) {
	$('#container_video').empty().append('<source src="video/video_414.mp4" type="video/mp4" />');
}else{
   if(widhtCon<1025){
     $('#container_video').empty().append('<source src="video/video_1024.mp4" type="video/mp4" />');
   }
}
```
I hope you can help me :)

**Comment by alvarotrigo** [comment]
Use the `afterResize` callback.

**Comment by alvarotrigo** [comment]
Or the `afterResponsive`. Not sure what you want to do.

**Comment by seveguay** [comment]
@alvarotrigo the problem is that when I try to get the size of the body on a mobile device always the width of the body is 980px

**Comment by alvarotrigo** [comment]
That's a javascript question you'd better ask in other place like stackoverflow where they'll be able to help you better.

This forum is only to treat fullPage.js directly related issues.

**Comment by seveguay** [comment]
I know that here all is about fullpage, but this problem only happens with fullpage.
What I'm triying to explain is that using Fullpage if you  debug the width on a mobile device always is 980px.
But it's ok, I'm going to open a thread on stackover, thanks.

**Comment by alvarotrigo** [comment]
If you believe that's a bug you'll have to provide an isolated reproduction of the issue with no CSS or JS files external to fullPage.js and the less minium HTML code.

But I believe this is not a fullpage.js issue anyways.
Make sure to check the viewport meta tag and so on:

```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```
