### ISSUE TITLE
Divs in-between sections: enhancement in moveSectionDown/Up

### ISSUE THREAD

**Issue by danielsefton** [alvarotrigo/fullPage.js#3081]
Hi - I'm trying to add divs in-between sections, however, this breaks the scroll because of the use of .next() and .prev() in moveSectionDown/Up.

I thought a solution might be to override those functions to skip over the divs in-between, but since fullpage is a function and not an object / does not use prototype for the functions, I can't see a way to achieve this. I'd rather not edit the library itself.

Perhaps in future it can be made so that moveSectionDown/Up finds the next fp-section, rather than any following div.

Any suggestions would be appreciated.

**Comment by alvarotrigo** [comment]
> But since fullpage is a function and not an object / does not use prototype for the functions, I can't see a way to achieve this. I'd rather not edit the library itself.

One of the reasons is properties won't get compressed when using minification, creating a much bigger file. 
Another one is to keep them private :)

> Perhaps in future it can be made so that moveSectionDown/Up finds the next fp-section, rather than any following div.

May I ask, what's the purpose of adding elements in between? Why not using `auto-height` sections?

**Comment by danielsefton** [comment]
Thanks for the reply! For the transition effect I wanted to achieve I had to separate the slider and the content in order to add floating shape animations in-between. And, for the CMS software we're using the content and sections must be one after the other:

```
<div>content</div>
<section>background</section>
<div>content</div>
<section>background</section>
```

I realise it might be a bit of an edge case, but I'm sure there will be others who might like to be able to do this. I don't mind if you'd like me to submit a pull request if I come up with something, unless you plan to implement it in future.

**Comment by danielsefton** [comment]
I just needed to change this in moveSectionDown:

`var next = $(SECTION_ACTIVE_SEL).next(SECTION_SEL);`

to:

`var next = $(SECTION_ACTIVE_SEL).nextAll(SECTION_SEL).first();`

Same for prev. Is that something you'd be happy to see merged into the code? Could always add a new configuration option just encase, but shouldn't cause any issues.

**Comment by alvarotrigo** [comment]
@danielsefton yeah, that's the easy part :) The difficult one is making sure that it won't break any other feature or extension.  (which I'm sure it will do).

Things like:

- `active` state class when using `autoScrolling: false` or `scrollBar:false`
- Callbacks 
- fulPage.js state classes
- Anchors
- Extension such as Drag And Move, Fading Effect etc..

It is much more work than it seems, and will lead to tens of possible bugs. 

I would be inclined not to play with it at the moment. It is not something necessary and you probably can achieve the same by using absolute positioned elements within sections or by just using more sections in between with the auto height class `fp-auto-heigh`.

Thanks for the proposal, but I'll close the issue as I'm not planning to include such a big change at the moment. 
I might consider it in the future tho, probably after creating some proper tests for all features :)

**Comment by alvarotrigo** [comment]
As a possible solution for you, if you are restricted to that HTML markup, just change using Javascript before initialising fullPage.js :)

**Comment by danielsefton** [comment]
Yeah I can imagine changing something like this is challenging for such a widely used library. The modifications seem to work for me and don't appear to have broken anything, so I will stick to that for now. Thanks for the help!
