### ISSUE TITLE
Problem Creating anchors with fullpagejs

### ISSUE THREAD

**Issue by jordiguemo** [alvarotrigo/fullPage.js#3083]
Hi,

I'm trying to implement anchor in my menu to footer section but I have a jquery error

> bb3af47c5f809ee2f643c254180e02a3?ver=1.9.4:1133 Uncaught TypeError: Cannot read property 'top' of undefined
    at HTMLAnchorElement.<anonymous> (bb3af47c5f809ee2f643c254180e02a3?ver=1.9.4:1133)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.q.handle (jquery.min.js:3)
(anonymous) @ bb3af47c5f809ee2f643c254180e02a3?ver=1.9.4:1133
dispatch @ jquery.min.js:3
q.handle @ jquery.min.js:3

If I click to link for see the error appears this: 

```javascript
//It is an anchor
// Starts with #, it's safe to do the jQuery stuff

		if (url.match(/^#.*/) !== null) {
		$('html,body').animate({scrollTop: $(url).offset().top - height },'slow'); //in this line is the error
			return;
		}
````

The web structure is created by wordpress, so, I need to manually add via jquery the attributes that you say are necessary: 
**"href" to `<a>` element, and "data-anchor" to section div**

I'm doing this like this: 

```javascript
jQuery('.menu-menu-new-ps-works-container #menu-item-42133 a').attr("href", "#pageFooter");
jQuery('.upfront-region-container-footer-final').attr("data-anchor", "pageFooter");	
jQuery('.home #fullpage').fullpage();
```
I have misunderstood the way to create anchors? I am doing something wrong?

Regards!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
Do not use any CSS or JS files external to fullpage.js and use the minimum HTML code, use empty sections if possible.

**Comment by jordiguemo** [comment]
I can not reproduce the error, if you can explain the mechanics with your words to make the anchors work I would appreciate it.

Is there something that is failing? or having a "href" and a "data-anchor" is enough

**Comment by alvarotrigo** [comment]
> I can not reproduce the error,

Then I'll close the issue. 

> if you can explain the mechanics with your words to make the anchors work I would appreciate it.

Sure, please check out [the documentation](https://github.com/alvarotrigo/fullPage.js). And if you have any question feel free to ask.
Also, do not forget the check all [the examples available](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) to see how they are using it in the source code.

**Comment by jordiguemo** [comment]
The documentation has not made clear to me what is the structure that I have to mount to create an anchor. I do not know if I have to use "data-menuanchor" in "li", "data-anchor" in the section I want to go, along with the id to which I want to go in the "a" element ... Or even the way to initialize fullpage to be able to use the anchor.

Sorry for the inconvenients
