### ISSUE TITLE
Hidden elements outside the #fullpage div

### ISSUE THREAD

**Issue by moshboaron** [alvarotrigo/fullPage.js#3086]
I have few div elements OUTSIDE the id="fullpage", like bootstrap modal's.
When those div's appears in the code the fullpage.js works with issue (skipping on sections) but when I remove those div's from the code it works perfectly.

I tried to name those div as fixed elements but with no success.

Is there a way to separate those div's from the fullpage.js?
Thanks.

**Comment by alvarotrigo** [comment]
Place them outside the fullpage.js wrapper and use a fixed position for them.
You can clearly see this in all the [provided examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) with the menu element.
