### ISSUE TITLE
Iscrollinstance custom event is not working

### ISSUE THREAD

**Issue by OneX** [alvarotrigo/fullPage.js#3087]
I tried using same code as provided [here](https://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl/48544258#48544258) 
but the custom event is not working.

**Comment by alvarotrigo** [comment]
You would need to use iScroll.js probe version and then make the necessary changes to fix some issues. 

Not something provided by fullPage.js yet. Although you can take a look at [this PR](https://github.com/alvarotrigo/fullPage.js/pull/2875).
