### ISSUE TITLE
Scrolling to top of the current section when first slide is visible

### ISSUE THREAD

**Issue by fullpager** [alvarotrigo/fullPage.js#3088]
### Scrolling to top of the current section when first slide is visible
Within a section the first slide has relativley long content. So the slide is quite large in height on a mobile phone. How to proceed a scroll to the top (=beginning)  of the current section when the first slide is visible on screen? $.fn.fullpage.moveTo(1) seems not work, because the first slide is visible on screen. (?) $.fn.fullpage.moveTo(1) seems to work only if the a slide > 1 is visible.

**Comment by alvarotrigo** [comment]
What fullpage.js settings are you using? 
Responsive mode? autoScrolling: false? scrollBar:True? 

Can you please provide your fullpage.js initialisation ?

**Comment by alvarotrigo** [comment]
Closed as I got no responses from you.
