### ISSUE TITLE
 Scrolls through one slide in Fading Effect extention

### ISSUE THREAD

**Issue by ellestragoo** [alvarotrigo/fullPage.js#3090]
Hi there! 

There is a problem with scrolling on trackpad when fading effect is active.
When user try to scrolling site he can see scrolling through one slide.
How to fix this problem? 

### Steps to reproduce it
1. Go to [Fading Effect Example Page](https://alvarotrigo.com/fullPage/extensions/fading-effect.html#firstPage)
2. Try to scroll on trackpad devices
3. You can see a jump from first slide to third, from second to fourth, etc

### Devices
Laptops

**Comment by alvarotrigo** [comment]
I'm afraid I can not reproduce your issue. Working fine in a Mac trackpad.
You might be having issues because of your trackpad speed. It might be too high.

**Comment by ellestragoo** [comment]
Strangely... I reproduce it on Mac trackpad too and other laptops

**Comment by alvarotrigo** [comment]
@ellestragoo had no complain from anyone else of the hundreds who acquired the extension.
And neither I can reproduce the issue in browserstack.com in neither Chrome, Firefox, Safari or IE.
