### ISSUE TITLE
Will there any docs in Chinese?

### ISSUE THREAD

**Issue by czhiemma** [alvarotrigo/fullPage.js#3091]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
They are there already! :)
https://github.com/alvarotrigo/fullPage.js/tree/master/lang/chinese#fullpagejs
