### ISSUE TITLE
Fullpage disables blur on body element.

### ISSUE THREAD

**Issue by zupazt3** [alvarotrigo/fullPage.js#3092]
### Description
When FullPage is loaded with the fullpage() method, the CSS filter blur(), that is set for body element, is being ignored.

### Steps to reproduce it
1. In CSS: `body { filter : blur(10px); }`. 
2. Check if it is working - it is. Everything is blurred. 
3. In JS initialize FullPage:
```
$('#content').fullpage(
        {
            lockAnchors: false,
            keyboardScrolling: true,
            controlArrows: false,

            afterSlideLoad: onSlideLoad,
            onSlideLeave: onSlideLeave,
        });
```
4. Now, when the website is loaded, you can see it is blurred only for a very short moment, and then, when FullPage is loaded, the blur disappears and the website is not blurred...

### Versions 
Windows, Browser is Chromium (actually QtWebEngine).

**Comment by alvarotrigo** [comment]
I was not able to reproduce the issue.
http://jsfiddle.net/97tbk/2260/

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
