### ISSUE TITLE
background of slide disappeared（Splash screen）by iphone.

### ISSUE THREAD

**Issue by woodThunder** [alvarotrigo/fullPage.js#3094]
background missing addressed by adding scrollBar:true.
but background of slide disappeared（Splash screen）by iphone.
Have you ever met?

**Comment by alvarotrigo** [comment]
Sorry you'll have to provide an isolated reproduction so I can check what you are talking about.
I'll close the issue until then.

**Comment by woodThunder** [comment]
http://net.bangong.cn:8004/R_rc/index_fullall.aspx

**Comment by alvarotrigo** [comment]
Please isolate the reproduction. 
Remove any external CSS or JS files to fullPage.js and use the minimum HTML code. Use empty sections.
