### ISSUE TITLE
Background image disappears when using parallax on Safari

### ISSUE THREAD

**Issue by jean-andre-gauthier** [alvarotrigo/fullPage.js#3096]
### Description

When scrolling on a parallax page, the background image sometimes disappears on Safari (desktop). As far as I can tell, this seems only to be the case when `scrollBar: false` and `autoScrolling: true`.
 
### Link to isolated reproduction with no external CSS / JS

This can be reproduced on https://alvarotrigo.com/fullPage/extensions/parallax.html

![parallax_white_bug](https://user-images.githubusercontent.com/2288716/36004022-d05c3846-0d30-11e8-9ce1-40a870896dea.gif)

### Steps to reproduce it
1. Scroll down from the first section to the second section
2. Scroll back up to the first section
3. The background image disappears until the scrolling animation stops 

### Versions 
Safari Version 11.0.2, fullpage.js 2.9.6, parallax 0.0.9

**Comment by alvarotrigo** [comment]
Uh no! That's not good! 
Thanks for reporting it!! I'll check it out!

**Comment by alvarotrigo** [comment]
Apparently it is not a parallax specific issue, but more an issue related with background elements themselves:

- [Reproduction without parallax](http://jsfiddle.net/97tbk/2398/)

I still need to reproduce it without fullPage.js so I can perhaps open an issue on the Safari's bug issues forum.

**Comment by alvarotrigo** [comment]
Alright, my previous fiddle was using `scrollOverflow: true`, which seems to mess up things.
Without it, it works as expected as can be seen [here.](http://jsfiddle.net/97tbk/2401/).

Reproduction without fullPage.js:
https://jsfiddle.net/chq2qfm8/49/

**Comment by alvarotrigo** [comment]
I've reported the bug to Safari:
https://bugs.webkit.org/show_bug.cgi?id=183003

**Comment by alvarotrigo** [comment]
I've made a small improvement. Now it seems it doesn't happen that often, although it still does sometimes. You can check that on the [parallax demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html).
 
I don't really think there's much I can do about it. It is clearly a Safari bug. 

If you want the latest parallax version please [contact me](https://alvarotrigo.com/#contact) and I'll send it to you.

**Comment by alvarotrigo** [comment]
Ok I believe this issue got fixed. Probably due to some Safari update. 
I can not reproduce the issue anymore in any of the reproductions I provided before. 

Using the latest Safari Version 11.1.2 (11605.3.8.1)
