### ISSUE TITLE
Horizontal scroll for slides not working with trackpad

### ISSUE THREAD

**Issue by dansurfrider** [alvarotrigo/fullPage.js#3097]
I like that you can also scroll horizontally between slides. Unfortunately it only works on my iPhone, not on my Macbook Pro with the Trackpad.

Tested on MB Pro 2010 with macOS High Sierra on Firefox, Chrome and Safari.

**Comment by alvarotrigo** [comment]
Yeap, that's not implemented yet. 
There's [an open topic about the issue](https://github.com/alvarotrigo/fullPage.js/issues/1024) marked as a possible enhancement.

I'll close this one as it is a duplicate request.

If you really need the feature, feel free to [contact me](https://alvarotrigo.com/#contact).
