### ISSUE TITLE
Section Content in mobile hides

### ISSUE THREAD

**Issue by DevSachinGupta** [alvarotrigo/fullPage.js#3098]
i am using the fullpage js and i am stuck as the content in the section tag in mobile devices does not show up all as there is no scrollbar active 

my script part is given below 
```
if (jQuery('#fullpage').length) {
			jQuery('#fullpage').fullpage({
		    	scrollOverflow: true,
		    	resize: false,
		    	sectionSelector: '.section',
				slideSelector: '.slide',
		    	anchors: ['main', 'about', 'portfolio', 'blog', 'contact'],
		    	menu: '#fp-nav',
		    	controlArrows: false,
				verticalCentered: false,
				normalScrollElements: '.single-project-slide',
				keyboardScrolling: true,
				afterLoad: function(anchorLink, index){
					sachinGupta.logoFix();
				}
		    });
		}
```
please help as soon as possible

screenshot in browser is below
![screenshot-2018-2-11 sachin gupta resume 1](https://user-images.githubusercontent.com/12891680/36071808-8585c5e2-0f3a-11e8-938f-7b8b6da9ffd9.png)
Screenshot of the mobile is below
![screenshot-2018-2-11 sachin gupta resume](https://user-images.githubusercontent.com/12891680/36071809-85b18c68-0f3a-11e8-8303-e1f48073d5c9.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by DevSachinGupta** [comment]
https://jsfiddle.net/sachingupta/xy6Lsye2/8/#&togetherjs=zCf9Cahr5w

**Comment by alvarotrigo** [comment]
Your JS console is full of errors and there's nothing displaying on the result panel on the bottom right. Please make it work.

**Comment by DevSachinGupta** [comment]
ya i know that and working to fix it

**Comment by DevSachinGupta** [comment]
Fixed the problem of the content visibility

**Comment by DevSachinGupta** [comment]
wahiyaad
