### ISSUE TITLE
Is there a way to loop the bottom with the scroll horizontal plugin?

### ISSUE THREAD

**Issue by lI707** [alvarotrigo/fullPage.js#3100]
Setting loopBottom to true, disables the scroll horizontal feature and just scrolls vertical. Can any of the other extensions provide a solution?

**Comment by alvarotrigo** [comment]
You'll have to be more specific with your issue. 
The option `scrollHorizontally: true` is totally compatible with `loopBottom: true`. And it works as expected. 
Whenever you reach the last vertical section and you scroll down again, you'll be moved to the 1st vertical section. 
Scroll Horizontally will only influence horizontal slides. So whenever you slide up or down, you'll slide left or right respectively.

**Comment by lI707** [comment]
https://codepen.io/Lyricallin/pen/GQmLBX
I reproduced the issue, when looping, it scrolls back to slide 1C instead of 1A. 
So the loop doesn't loop back to the first horizontal slide.

**Comment by alvarotrigo** [comment]
> I reproduced the issue, when looping, it scrolls back to slide 1C instead of 1A.

Totally expected :)

You might want to check out the [Reset Sliders extension](https://alvarotrigo.com/fullPage/extensions/reset-sliders.html).

**Comment by lI707** [comment]
Thanks it's working =) but is it possible to only reset the slides after loopBottom (leaving the final section)? Instead off resetting after each section?

**Comment by alvarotrigo** [comment]
Nop, the extension gets applied when leaving any section I'm afraid. 
If you really need that you can [contact me](https://alvarotrigo.com/#contact) for further assistance.

**Comment by gopal2k6** [comment]
$('#fullpage').on('mousewheel', function(event) {
	
		var delta = event.originalEvent.deltaY;
       if (delta > 0){$.fn.fullpage.moveSlideRight();}
       else{$.fn.fullpage.moveSlideLeft();}
	  
});
