### ISSUE TITLE
Change fixed logo on specific slide

### ISSUE THREAD

**Issue by reverter90** [alvarotrigo/fullPage.js#3104]
Hi,
can I change my logo when I'm on a specific slide?

```
<ul id="menu">
    <li><img src="img/logo.png" alt="logo demia"></li>
    <li class="right"><i class="fas fa-times cursor menu-bars chiudi" onclick="closeNav()"></i></li>
</ul>
```

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
