### ISSUE TITLE
Lazyload two slides at a time

### ISSUE THREAD

**Issue by Lippiun** [alvarotrigo/fullPage.js#3105]
Hey,

I'm using slides in my fullpage setup and I want two slides to show at the same time. 

Because im using lazyload it's only loading the first image, is it possible to customise how many images are loaded per slider?

**Comment by alvarotrigo** [comment]
> I'm using slides in my fullpage setup and I want two slides to show at the same time.

That's not a feature provided by fullpage.js, so I would recommend you to lazy load them yourself by using callbacks or fullpage.js state classes. 

Otherwise, you can use `scrollBar:true` and use any other lazyload library.
