### ISSUE TITLE
Incorrect height calculated on page load, 15px short

### ISSUE THREAD

**Issue by aosmichenko** [alvarotrigo/fullPage.js#3107]
https://github.com/alvarotrigo/fullPage.js/issues/472 - looks like this is back
Chrome latest Mac OS El captain

I am seeing bottom scroll bar, disappearing on page load.

**Comment by alvarotrigo** [comment]
@aosmichenko i can't reproduce it on the [demo page](https://alvarotrigo.com/fullPage/) or any of the online examples for that matter. 
Make sure use use the compulsory doctype declaration. `<!DOCTYPE html>`

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
