### ISSUE TITLE
Stuttering images/slides on parallax in firefox

### ISSUE THREAD

**Issue by LeeDemain** [alvarotrigo/fullPage.js#3108]
In firefox when scrolling down/up and left/right on the carousel it's really juddery, I wondered if it was just the site I was working on, but tried the demo version of the full page parallax plugin and it's the same on there too?

https://alvarotrigo.com/fullPage/extensions/parallax.html#3rdPage/1

**Comment by alvarotrigo** [comment]
The demo page you link works totally fine for me with the default settings in the the latest Firefox for Mac. (and I'm using a 7 and a half years old Macbook Pro )

Have you tried using another computer? It might be your computer is too slow?

**Comment by LeeDemain** [comment]
I haven't, but it was reported to me by someone else on another machine, I can try and update my version of FF to see if that fixes it. Chrome etc works fine

**Comment by LeeDemain** [comment]
Updated firefox but didn't make a difference, also checked on colleagues machine and getting same problem.

Here is the live URL to the site using the plugin, only a problem in firefox

http://www.hoseasons.co.uk/tailormade

**Comment by alvarotrigo** [comment]
> Here is the live URL to the site using the plugin, only a problem in firefox

Do you have the problem on the [demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html)? 
Can you please record a video an upload it so I can see what you are talking about?

**Comment by LeeDemain** [comment]
Alvaro

See url below of page recording and the image delay when scrolling.

https://www.youtube.com/watch?v=lB4FLCEuzEA&feature=youtu.be

Thanks

**Comment by alvarotrigo** [comment]
@LeeDemain please use the [demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html) to illustrate your issue.

**Comment by LeeDemain** [comment]
Alvaro

I've fixed it, this can be closed.

It was a mistake I'd made with the anchors on the nav.

Thanks

**Comment by alvarotrigo** [comment]
Glad to know you solved it!

**Comment by papa-rugi** [comment]
What was the issue? Im facing this as well Lee.

> Alvaro
> 
> I've fixed it, this can be closed.
> 
> It was a mistake I'd made with the anchors on the nav.
> 
> Thanks
