### ISSUE TITLE
Disable fullPage scrolling on mobile only

### ISSUE THREAD

**Issue by anetk** [alvarotrigo/fullPage.js#3109]
Hi there,

Trying to "turn-off" fullPage on mobile only and have normal scrolling but wondering if there is any option for that?
I was trying to remove source for fullPage when less then 776px with javascript, but then it doesn't seem to be working on desktop.

**Comment by alvarotrigo** [comment]
Check the responsive options [in the docs](https://github.com/alvarotrigo/fullPage.js) (responsiveHeight and responsiveWidth) as well as the `fp-auto-height-responsive` class in case you need it.

**Comment by alvarotrigo** [comment]
[Demo online](https://alvarotrigo.com/fullPage/examples/responsive.html)

[Demo with fp-auto-height-responsive](https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html)

**Comment by anetk** [comment]
Hmmm what if you want to turn off scrolling and have normal scrolling on mobile? @alvarotrigo

**Comment by alvarotrigo** [comment]
@anetk that's what the responsive options are for, as I said.

**Comment by majidzeno** [comment]
@anetk you can remove fullpage in mobile 
 `if($(window).width() < 1024){
	$('#fullpage').removeAttr('id');
}`
NOTE:you have to write this code BEFORE starting fullpage.js

**Comment by katiachumakova** [comment]
@majidzeno didn't exactly work but tweaked it to start fullpage only on screen sizes above desired px width:
```
if($(window).width() > 1023){ 
$('#fullpage').fullpage(...)
}
```

**Comment by marekmaurizio** [comment]
I feel adding a class to multiple elements to *disable* something is a pretty bad design choice.

**Comment by alvarotrigo** [comment]
@marekmaurizio you are lucky then! fullPage.js is an open source project and you can contribute with your code an ideas 😄

**Comment by kirkbross** [comment]
> [Demo with fp-auto-height-responsive](https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html)

Is the "responsive slides' extension the one I need to use fp-auto-height-responsive? (full screen scrolling >= x, normal scrolling, auto height <= x).

**Comment by alvarotrigo** [comment]
@kirkbross nope.
The extension is called "Responsive Slides". And its behaviour is explained in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

> **responsiveSlides:** (default false) Extension of fullpage.js. When set to true slides will be turned into vertical sections when responsive mode is fired. (by using the responsiveWidth or responsiveHeight options detailed above). Requires fullpage.js >= 2.8.5.

**Comment by HawkeyePierce89** [comment]
We need a `disable` option

```javascript
const isPhone = Modernizr.phone; // https://github.com/hgoebl/mobile-detect.js

const options = {
	disable: isPhone ? true : false,
}
```

**Comment by alvarotrigo** [comment]
@HawkeyePierce89 why don't just use the `destroy('all')` function? 

Or if you want to keep sections full height and some of the advantages of using fullPage.js such as lazyload, media autoplay/pause, bullet navigations or horizontal slides, why not using `setResponsive(true)`?

**Comment by alvarotrigo** [comment]
@HawkeyePierce89 or easier yet. If you dont want to use fullPage.js at all in an iphone, why just avoid initialising it when you detect an iPhone?

**Comment by marekmaurizio** [comment]
> @marekmaurizio you are lucky then! fullPage.js is an open source project and you can contribute with your code an ideas 😄

If I contribute will the same code be used in the commercial version?

**Comment by ismail432** [comment]
Try it ...confirm it will work 

<script>
if (screen && screen.width > 768) {
document.write('<script type="text/javascript" src="http://your-file-path/fullpage.js"><\/script>');
}
</script>

**Comment by Ezra-Siton-UIX** [comment]
# responsiveWidth option

```
new fullpage('#fullpage', {
     responsiveWidth: 900
});
```
Disabled under 900px (act like a normal page).

**Example**:
https://alvarotrigo.com/fullPage/examples/responsive.html 59

**Comment by Marius-Schwarz** [comment]
great, thanks for solving this. now I was wondering if it would be possible to still scroll-snap align (proximity) the start of the sections. thanks in advance.

**Comment by alvarotrigo** [comment]
Sure, just use the option `fitToSection:true`.

**Comment by saysonjerald** [comment]
use this on your javascript   
```
new fullpage('#fullpage', {
     responsiveWidth: 768
});
```
then in order to customize the height on your mobile view, you must add this `.fp-auto-height-responsive` on each of your slides that you want to be customizable via your media query.  

then go to CSS and add your media query  
```
@media only screen and (max-width: 768px) {
      height: 500px; // <- 500 for example
 } 
```

**Comment by alvarotrigo** [comment]
@saysonjerald you don't actually need to modify anything :)
Just set the height to the content of the section/slide. For example

```html
<div class="section fp-auto-height-responsive">
    <div class="content-wrappper">
         fasdfa
    </div>
</div>
```

```css
@media only screen and (max-width: 768px) {
   .content-wrapper{
      height: 500px;
   }
}
```

**Comment by saysonjerald** [comment]
Yes, I tried that approach, but it's so weird why that fullPage.js is putting inline CSS on every slide that I have, like this one.  

```
<section class="section section-resultDriven fp-auto-height-responsive fp-section active fp-completely" data-fp-styles="null" style="height: 676px;">
//my codes  here
</section>
```  

again, I didn't put` style="height: 676px;"` inside the section tag. It just automatically generated. I don't know why so I modify the fullPage.css file so I can override this inline CSS with higher specificity.

**Comment by alvarotrigo** [comment]
> but it's so weird why that fullPage.js is putting inline CSS on every slide that I have,

You shouldn't be worried about that inline css as it won't have any effect at all if you use `fp-auto-height` or `fp-auto-height-responsive`.

Modifying the CSS or the JS will only make it more difficult for you to:

- Update to future fullpage.js version
- Make sure you won't break anything with fullPage.js
- Make sure you won't break anything with fullPage.js extensions.

Usually, if you can avoid modifying a library, do it :)

**Comment by Anu-Ujin** [comment]
@alvarotrigo Hi! How to disable scroliing in react mobile version. I tried `<ReactFullpage
        anchors={anchors}
        navigationPosition={"left"}
        navigation
        parallax={true}
        scrollOverflow={true}
        responsiveHeight={600}
        render={() => children}
      />`  responsiveHeight={600}. but it's not working. Help me.

**Comment by alvarotrigo** [comment]
@Anu-Ujin that should turn fulpage.js auto scrolling off when the height of your mobile device is less than 600px width.
Try playing with the width instead, that'd be easier.

And make sure to also add this on the HTML header part.

```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```



&lt;meta name="viewport" content="width=device-width,initial-scale=1"&gt;
&nbsp;

<br class="Apple-interchange-newline">
