### ISSUE TITLE
Scroll in bigger section.

### ISSUE THREAD

**Issue by yogie89** [alvarotrigo/fullPage.js#3110]
Is there a way, if the condition is im on the bigger section and then i scroll with my scroll-mouse,  
then it wont automatically go to the next section. but stop in the last text on the bigger section ?

**Comment by alvarotrigo** [comment]
Check the scrollOVerflow option [in the docs.](https://github.com/alvarotrigo/fullPage.js).

[Example online.](https://alvarotrigo.com/fullPage/examples/scrolling.html)
