### ISSUE TITLE
Fading Extension Conflicting With Drag&Move

### ISSUE THREAD

**Issue by andrewnleon** [alvarotrigo/fullPage.js#3111]
Hello,

I am trying to use your fade extension with drag and move extension. The problem I am having is while touch swiping the transition always leads to the first section. When I turn fadingEffect to false, the drag and move works fine. All I want to do is hand swipe while fading through sections.

1. Enable drag and move with fadeing effect extensions
2. Create normal sections with one section that has slides
3. Try swiping through section and slides, and notice how the navigation is unpredictable and leads to first section.

Latest Firefox
Latest Extensions and Fullpage.js

**Comment by alvarotrigo** [comment]
> All I want to do is hand swipe while fading through sections.

You do not need the drag and move extension for that. Drag and move is to have a 1:1 movement relationship with the page while you swipe.

**Comment by alvarotrigo** [comment]
Oh wait, are you talking about draging on touch devices or on desktop with the mouse?

**Comment by andrewnleon** [comment]
I want to drag on touch devices, but eliminate the scrolling up and down. I just want it to fade. Does that make sense?

**Comment by alvarotrigo** [comment]
> I want to drag on touch devices, but eliminate the scrolling up and down. I just want it to fade. Does that make sense?

Yeah, but for that you won't need the drag and move extension.
Just try it without it and you'll see how it is working as expected.

**Comment by andrewnleon** [comment]
Okay, let me give it a shot

**Comment by andrewnleon** [comment]
Dang-it your right. I just bought the drag and drop for no reason then. I also bought the continuous horizontal and don't understand it's purpose. Can we work something out? and can you explain the horizontal extension?

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) about it and we'll see what we can do.

**Comment by andrewnleon** [comment]
OKay I have contacted you
