### ISSUE TITLE
freeze scrollbar for five keydown events after then re-enable them.

### ISSUE THREAD

**Issue by rahul78275** [alvarotrigo/fullPage.js#3115]
@alvarotrigo  I want to freeze me scrollbar in a particular section of the page, which contains some slides. I want to animate each slide on user keydown event and after all slides displayed. only then move the scrollbar to next below section. 

http://www.allinoneseotool.com/demo3/examples/index1.html

I want to display all the slides in one section with animation rollin (rotate clockwise).

**Comment by alvarotrigo** [comment]
It is not something provided by fullPage.js I'm afraid.

**Comment by ibond2k** [comment]
<a herf="http://allinoneseotools.tk/"> Oh! Nice Very important and useful post, thanks for shearing.I think most best website for seo is  All in one seo tools.you can try it, right or wrong.
go</a>http://allinoneseotools.tk
