### ISSUE TITLE
wrong direction value of onleave callback when using continuousVertical

### ISSUE THREAD

**Issue by ageofsys** [alvarotrigo/fullPage.js#3118]
when i use 2.9.6 release, i find bug that onLeave callback's direction parameter is return wrong value. i added 'true' to 'continuousVertical' option. when i do scroll from last section to first section with mouse wheel down, direction parameter's value was 'up'.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!

**Comment by alvarotrigo** [comment]
Fixed on the dev version 2.9.7

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.7!
