### ISSUE TITLE
After changing section fp-viewing not working properly

### ISSUE THREAD

**Issue by ilmatty** [alvarotrigo/fullPage.js#3119]
I try to change the section order, to better fit in a mobile phone. After destroying all instance of fullpage, I change the class name to the element with Jquery and then re-initialize fullpage. The problem is that fullpage calculate only 2 section instead of 4: fp-viewing-0 and fp-viewing-1 

Is it a bug or I wrong something? 
That's my code:
[https://jsfiddle.net/msiri/262xycq9/1/](https://jsfiddle.net/msiri/262xycq9/1/)

**Comment by alvarotrigo** [comment]
I only see two sections on the dom when the width is less than 765:
![screen shot 2018-02-22 at 18 33 07](https://user-images.githubusercontent.com/1706326/36554206-e377f3ec-17fe-11e8-9145-3b3cd9ba68e8.png)
 
where's the issue?
Steps to reproduce it?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
