### ISSUE TITLE
ScrollOverflow with Images

### ISSUE THREAD

**Issue by KlausAndrade** [alvarotrigo/fullPage.js#3120]
Hi, I'm using the plugin to show many images, like a powerpoint presentation, but I have many images that are very big e.g 1920x5800. and I realise that the scrollOverflow works only if I set a specific height for a div inside <div class="section">.
autoHeight also didn't help. 

Is there a way to do this? 

regards, Klaus

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
