### ISSUE TITLE
Padding around fullpage div

### ISSUE THREAD

**Issue by ken-colvin** [alvarotrigo/fullPage.js#3121]
How to set padding around the fullpage div?
see https://jsfiddle.net/revup/9pq8uypw/

- I have a fixed position frame on my page.
- I want the fullpage div to be inside this frame, basically "padding: 40px 50px"
- I also want this to be responsive.
- see frame-x and frame-y css which is the image based frame for the web page.
- I tried paddingTop and paddingBottom but that did not work.

**Comment by alvarotrigo** [comment]
Just use the padding within the sections or slides instead. 

```css
.section{
    padding: 30px;
}
```

fullPage.js won't support iframes.
