### ISSUE TITLE
Full page js overlflowScroll: true, not working on mobile

### ISSUE THREAD

**Issue by shahjehanali1** [alvarotrigo/fullPage.js#3122]
Full page js overlflowScroll: true, not working on mobile

Check second slide on first section http://www.veelo.es/

**Comment by alvarotrigo** [comment]
Make sure to use the dev version of the scrolloverflow file:
https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js

**Comment by shahjehanali1** [comment]
http://www.veelo.es/wp-content/themes/veelo/js/vendors/scrolloverflow.min.js

**Comment by alvarotrigo** [comment]
Not the minified version.

**Comment by alvarotrigo** [comment]
Just take it from he link I posted.

**Comment by shahjehanali1** [comment]
http://www.veelo.es/wp-content/themes/veelo/js/vendors/scrolloverflow.js
now I'm using same version

`var $isAnimatedFive = $('.five .is-animated'),
    slideIndexer = 0;

    $('#fullpagevision').fullpage({
        slidesNavigation: true,
		 navigation: true,
        autoScrolling: true,
        scrollOverflow: true,
        afterLoad: function(anchorLink, index){
            console.log(index);
            if(index == 1 && slideIndexer<2){
                $.fn.fullpage.setAllowScrolling(false, 'down');
                $.fn.fullpage.setKeyboardScrolling(false, 'down');
                $('#fp-nav').hide();
            }else{
                $.fn.fullpage.setAllowScrolling(true, 'down');
                $.fn.fullpage.setKeyboardScrolling(true, 'down');
                $('#fp-nav').show();
            }
        },
        afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
            slideIndexer = slideIndex;
            if (slideIndex === 0 || slideIndex === 1) {
                //disabling scrolling down
                $.fn.fullpage.setAllowScrolling(false, 'down');
                $.fn.fullpage.setKeyboardScrolling(false, 'down');
                $('#fp-nav').hide();
            }else{
                $.fn.fullpage.setAllowScrolling(true, 'down');
                $.fn.fullpage.setKeyboardScrolling(true, 'down');
                $('#fp-nav').show();
            }
        },
        onSlideLeave: function(anchorLink, index, slideIndex, direction, nextSlideIndex) {
            // first animation
            if (slideIndex === 0 && nextSlideIndex === 1) {
                $isAnimatedFive.eq(0).addClass('animated slideInLeft').css('animation-delay', '.4s');
                $isAnimatedFive.eq(1).addClass('animated fadeInUp').css('animation-delay', '.4s');
                $isAnimatedFive.eq(2).addClass('animated fadeInDown').css('animation-delay', '.4s');
                $isAnimatedFive.eq(3).addClass('animated fadeInUp').css('animation-delay', '.4s');
                $isAnimatedFive.eq(4).addClass('animated fadeInDown').css('animation-delay', '.4s');
            }
            slideIndexer = slideIndex;
            if (slideIndex === 0 || slideIndex === 1) {
                console.log('working');
                //disabling scrolling down
                $.fn.fullpage.setAllowScrolling(false, 'down');
                $.fn.fullpage.setKeyboardScrolling(false, 'down');
                $('#fp-nav').hide();
            }else{
                $.fn.fullpage.setAllowScrolling(true, 'down');
                $.fn.fullpage.setKeyboardScrolling(true, 'down');
                $('#fp-nav').show();
            }
        }
    });`

**Comment by shahjehanali1** [comment]
I'm facing this issue on mobile

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

Use empty sections or with the minimum text  and no CSS or JS files external to fullPgae.js.

**Comment by alvarotrigo** [comment]
You can now use the latest version 0.0.7 of the scrolloverflow file:
https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js

**Comment by shahjehanali1** [comment]
I'm using same but its not working

**Comment by alvarotrigo** [comment]
@shahjehanali1 provide an isolated reproduction if you believe it is a bug.

**Comment by shahjehanali1** [comment]
I've been fixed it my self, Actually this is due to display none on fullpage.js wrapper

**Comment by shahjehanali1** [comment]
Scrolling not working on samsung native browser https://codepen.io/shahjehan/details/GQXbEg
Check this

**Comment by alvarotrigo** [comment]
You are using 0.0.5
See my previous answers. Use 0.0.7
