### ISSUE TITLE
hiding certain pagination dot(s).

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#3123]
Hello again,

Here's my scenario:
It's a vertical slider with, say, 5 sections. Pagination is not displayed on section 1 and section 5 (you've shown active one can be hidden here: http://jsfiddle.net/97tbk/2438). Pagination though, is displayed on section 2, 3 and 4. Furthermore and crucially - the pagination shows only 3 pagination dots - those for section 2, 3 and 4, and is linked with them.

One way i'd imagine to do this is through slides, but only if they could move vertically as sections do. Issue #1167 stated it can't be done, but perhaps things changed since 2015? Anyways, I don't need to hide those paginated slides from mouse scrolling business, so they can go as regular sections (or i could use your Scroll Horizontally extension if slides route is an option).

I know active anchors can each be styled separately on every section, so i can make it disappear where needed, but i'll have more than one page without pagination and only one anchor (and i presume paginator dot too) can be removed at a time this way. I'm out of my depth here, but per chance my scenario can be somehow achieved with callbacks?

Therefore my main bet is on somehow hiding pagination dots of sections 1 and 5 on sections 2,3 and 4, and to hide them all in sections 1 and 5. So i guess the question is, - can i style a specific pagination dot? 

Thanks a lot for your attention!

**Comment by alvarotrigo** [comment]
> can i style a specific pagination dot?

Sure! But that's a CSS question. You'd better ask in another place such as stackoverflow.com
