### ISSUE TITLE
Stop slideshow autoplay

### ISSUE THREAD

**Issue by kamalcha** [alvarotrigo/fullPage.js#3126]
I have slideshow on one section, how do I stop the slideshow the autoplay on the slideshow?

**Comment by alvarotrigo** [comment]
That depends on how you have it implemented. 
You probably will have to look at the `clearInterval` function of Javascript. 

But in any case, this is not a fullPage.js related issue. fullPage.js doesn't provide automatic sliding, so I would encourage you to ask for that in other place such as stackoverflow.com where they'll be able to help you better with your issue.
