### ISSUE TITLE
Slide Background Image not Applying Cover Property

### ISSUE THREAD

**Issue by montelco** [alvarotrigo/fullPage.js#3127]
Normally, to have a background image cover an element, the `background-size: cover` property would be applied via CSS. This, however, is not scaling. If it gives more insight, no `background-$whatever` was working, so most was shorthanded into the generic `background` property (eg: no-repeat, center, etc).

### Steps to reproduce it
1. Add a unique class to the slide (eg: about)
2. Apply the following to the CSS block for `#about`:
        `background: linear-gradient(to bottom, rgba(0,47,108,0.6), rgba(0,47,108,0.6)), url(http://placekitten.com/1600/1060) center no-repeat !important;`
        `background-size: cover;`
3. If you have a screen larger than 1600x1060, you will notice that the image appears like [this.](http://prntscr.com/ikjn1u)

NOTE: This only occurs when apply the background, not background-image property.

### Versions 
Chrome 64, Windows 10

**Comment by alvarotrigo** [comment]
Sorry I do not understand your issue. Can you please explain it in another way?
What would you expect?
What is happening?
Why is it related with fullpage.js at all?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
