### ISSUE TITLE
Reload fullPage.js to detect new DOM structure

### ISSUE THREAD

**Issue by thomey** [alvarotrigo/fullPage.js#313]
I have a responsive site where I would like to break up an existing fullPage.js div with class ".section" into separate new divs with class ".section" when visiting from mobile (or on screen resize), so that I can keep the fullPage.js fullscreen section by section scrolling functionality, but make each of the elements in the original div fullscreen and change the order a bit so it's more fitting for a mobile screen.

Here's a simplified example of what I'm trying to achieve:
On desktop:

```
<div class="section">
    <h1>Section heading here</h1>
    <p>Some text</p>
    <img src="" />
</div>
```

On mobile:

```
<div class="section">
    <img src="" />
</div>
<div class="section">
    <h1>Section heading here</h1>
</div>
<div class="section">
    <p>Some text</p>
</div>
```

As you can see the existing div has been broken up into separate divs and the order of the content has been changed a bit.

I've read through the issues/requests here on GitHub to look for solutions, and tried using both fullPage.js callbacks, hiding/showing divs, toggling class ".section" for the divs etc., but none of the solutions have been working.

The main problems with the different solutions seem to be:
1) If I hide/show the content with CSS, fullPage still considers it part of the DOM and this breaks the scrolling.

2) If I toggle the class ".section", fullPage does not detect the divs on the initial load, thus not counting them as part of the scrolling hierarchy.

3) If I add the content on condition using JS, it's not part of the DOM when fullPage.js is loaded and therefore not detected.

Ideally there would be a way to tell fullPage.js to "reload"/"reindex" the divs, or at least a function to unload fullPage.js completely and then load it again when desired. That way one could change the DOM at certain media queries or with JS etc., and then reload fullPage.js to catch the new structure/layout.

Is there any way to achieve what I'm trying to do using the current fullPage.js?

**Comment by wootencl** [comment]
A little late to the game obviously so I'm not expecting a reply from OP but maybe @alvarotrigo can help shed some light. Also I hope my question falls within the scope of this topic enough in order for me to not start another discussion thread. Currently I'm using jQuery to dynamically add/delete sections to my site as it is resized and have used the above mentioned method: destroying FullPage, emptying the content of my div, adding some new content, and then reinitializing FullPage. This all works brilliantly except my one problem with what @alexcroox mentions above is that whenever the function is called (upon a resize) it brings me back to the first page/section. Any tips/advice on how to avoid this? I can throw everything into a codepen if you'd like. Hoping it's a simple fix though. Thanks in advance for any help on the problem!

**Comment by alvarotrigo** [comment]
@wootencl before initializing it again add the `active` class to the section (and slide if any) that was active before destroying it.

**Comment by wootencl** [comment]
@alvarotrigo You are AWESOME! Thanks for the swift reply and help. Two simple lines of jQuery and the problem is solved. For those interested I just selected the active class (before destroying) and added the active class back after adding my new HTML. Like so:

```
var temp = $(".section.active");
...empty/add HTML...
temp.addClass("active");
...reinitialize FullPage...
```

Keep being amazing!

**Comment by Rufustunnel477** [comment]
https://stylesheets.space/questions/guide-on-altering-the-cursor-icon-during-an-ajax-operation-within-a-jquery-dialog I verified the answer
