### ISSUE TITLE
Arrow scrolling inside scrollOverflow elements problems

### ISSUE THREAD

**Issue by isuke01** [alvarotrigo/fullPage.js#3130]
### Description

Hello, I have an problem, Im trying to achive arrow scrolling content using _fullPage.js_ but but but. 
I must use also scrollOverflow for some of elements. 
That's my setup: https://jsfiddle.net/r1a41frt/

#### And her is deal:
1) I try to make arrow navigation but when  #user is on '**Long section**' It shouldn't scroll to next section, that why I enable `scrollOverflowOptions{ keyBindings: true }` But it goes to next section.
2) But when just push arrow down it start scroll through '**Long section**'  but it scroll every of those on page, so If im manage go to middle of content, then next section is scrolled to middle also. <- I don't want that. 
Funny thing it scrolling down if there is no section below ;)
3) scrolling through this section is ... really slowwwwww like 1 arrow tick - +2px , any solution for that (using keyboard arrows) ?
`scrollOverflowOptions: {
                keyBindings: true,
            }`
Someone might say - Use reset scroll section plugin - I want it if user scroll down and goes next then come back, he should see point where he stopped.

**Comment by alvarotrigo** [comment]
1- Try canceling fullPagejs key features on that section. Use `setKeyboardScrolling(false)`. Read more about it in the docs.

2-I don't understand what you mean. Please explain it with other words. 

3- That's not a feature provided by fullPage.js but by scrolloverflow, which uses iScroll.js. You'll have to ask in [their issues forum](https://github.com/cubiq/iscroll/issues).

**Comment by isuke01** [comment]
2) you can go to my fiddle example and to the last section  and then right to scroll section, then push arrow down, it will scroll down, then go to other section and you will see, the other one has been also scrolled.

3) Ok thanks, I also noticed it is issue on MacOS only

**Comment by alvarotrigo** [comment]
> you can go to my fiddle example and to the last section and then right to scroll section, then push arrow down, it will scroll down, then go to other section and you will see, the other one has been also scrolled.

That's because there are not more sections to scroll to. It is a side effect, not an expected behaviour. 
fullPage.js doesn't provide scrolling with arrows inside scrollOverflow.
