### ISSUE TITLE
Overflow:auto is ignored on elements within a Section when using resetSliders plugin

### ISSUE THREAD

**Issue by ezekielaquino** [alvarotrigo/fullPage.js#3132]
I've purchased the resetSliders plugin. Great work!
There's a bug tho:

I have a div let's call it `scrollDiv` which is within a Section. the scrolldiv has overflow: auto set, and is scrolling on mobile when using the regular `fullpage` script. however, when using `fullpage.extensions.min.js` the touch events are totally ignored.

Thanks in advance!

**Comment by ezekielaquino** [comment]
Okay, please ignore the issue. The fullpage.extensions script provided upon purchase is outdated. I copied the version in the dist folder, and all seems well.

**Comment by alvarotrigo** [comment]
> The fullpage.extensions script provided upon purchase is outdated.

The extensions script is not provided with the purchase of any extension as it is freely available.
