### ISSUE TITLE
Responsive - Half Section to Full Section

### ISSUE THREAD

**Issue by ken-colvin** [alvarotrigo/fullPage.js#3133]
For https://alvarotrigo.com/fullPage/examples/responsive.html#firstPage

```
<div class='section'>
   <img class=left src='...'>
   <img class=right src='...'>
</div>
```

How would I make a class=section have 

- left/right be 1/2 the screen on large screens and 
- left/right be 1 FULL section on small screens?
-

**Comment by alvarotrigo** [comment]
That's a CSS question and not a fullPage.js related one. fullPage.js doesn't provide such feature.
You'd better ask in other place such as stakoverflow.com in which they'll be able to help you much better.
