### ISSUE TITLE
fadingEffect fail

### ISSUE THREAD

**Issue by jcs87** [alvarotrigo/fullPage.js#3134]
I realise this is going to sound like a dumb question, but I can't seem to activate fadingEffect.
I've purchased a Key, and added the below to my external js but nothing seems to trigger the effect.
Within the fullpage function:
```javascript
$(document).ready(function() {
			$('#fullpage').fullpage({
                fadingEffect: true,
		fadingEffect: 'sections',
		fadingEffectKey: 'XXX',
});
````
Below the fullpage function:
```javascript
$(document).ready(function() {
			$.fn.fullpage.fadingEffect.turnOn();					   
})
```
Am I blind??

Many thanks for any help!

**Comment by jcs87** [comment]
I should add: I've also linked to the fullpage.fadingEffect.min.js and .css in the <head>.

**Comment by alvarotrigo** [comment]
Use rather `true`or `sections`you can't use both, they are exclusive. True is for both, sections and slides. 

```javascript
$('#fullpage').fullpage({
		fadingEffect: 'sections',
		fadingEffectKey: 'XXX',
});
```

**Comment by alvarotrigo** [comment]
No need to call `$.fn.fullpage.fadingEffect.turnOn();` unless you previously turned it off. 
Please make sure non of your own CSS styles are overwriting fullPage.js ones (or the fading effect ones)

**Comment by alvarotrigo** [comment]
If you still have issues please please [contact me](https://alvarotrigo.com/#contact) with a link to the reproduction.
