### ISSUE TITLE
Split a single section into two at certain browser width

### ISSUE THREAD

**Issue by MichaelPrecel** [alvarotrigo/fullPage.js#3135]
### Description
Hi Alvaro,

Thanks for your fantastic plugin.

I am building a site with some sections which have two images side by side inline. I want to be able to split those sections into two different sections when the browser becomes a smaller width so that the images do not become tiny, but I do not want the section to be a scrollable one either (ie I would like it to keep the same user behaviour as all other sections and centred).

Is this possible?

Thank you!

**Comment by alvarotrigo** [comment]
Sounds like a CSS knowledge issue, not a fullPage.js one. 
You'd better ask in another place such as stackoverflow.com in which they'll be able to help you much better.

**Comment by MichaelPrecel** [comment]
Hey @alvarotrigo , sorry I mustn't have explained my question well enough.

What I mean is:

If you have a section in the fullpage slider like so:
`<div id="fullpage">
    <div class="section">
      <div class="box-1">Content</div>
      <div class="box-2">Other content</div>
    </div>
  </div>`

And those two boxes sit within the one fullpage slide – is there a way to split them into two sections like so upon reaching a certain browser width:

`<div id="fullpage">
    <div class="section">
      <div class="box-1">Content</div>
    </div>
    <div class="section>
      <div class="box-2">Other content</div>
    </div>
  </div>`

So that now each of those boxes has a fullpage slide to themselves. This would help greatly with responsive styling. It's not a CSS question because it involves breaking the HTML DOM tree created by Fullpage and re-structuring it. Any help much appreciated.

**Comment by alvarotrigo** [comment]
> is there a way to split them into two sections like so upon reaching a certain browser width:

No. fullPage.js only provides that feature with horizontal slides turning into sections. Not with other elements in the DOM.

**Comment by alvarotrigo** [comment]
You would have to change the HTML structure by yourself, then destroy and initialise fullpage.js again.
