### ISSUE TITLE
Resizing browser hangs page for a while

### ISSUE THREAD

**Issue by amityweb** [alvarotrigo/fullPage.js#3136]
Hi

When I resize the window, it hangs the page for a while, becomes unresponsive to anything. Sometimes Chrome will ask me to Kill the page! I think maybe its due to the resizing fullpage does. 

How can we address this issue please? Is it normal in the plugin, or does it mean a problem with the site? I can private message a link if you need it. Where should I send it? 

Thanks

**Comment by alvarotrigo** [comment]
If you have many CSS properties changing values on responsive, such as `font-size` and so on, it might be due to the transition applied to the fullpage.js wrapper. 

First of all, try removing your media queries and test it again.

**Comment by amityweb** [comment]
Thanks for the reply. I have actually disabled fullpage.js and think I may still be having issues, so might be something else sorry! I will keep testing and report back.

**Comment by amityweb** [comment]
I think its Revolution Slider causing the issues so apologies!
