### ISSUE TITLE
ScrollHorizontally:true in combination with autoScrolling:false

### ISSUE THREAD

**Issue by kubmin** [alvarotrigo/fullPage.js#3137]
Hi there,

Just got the Scroll Horizontally extension for fullPage.js. Everything works fine when autoScrolling is set to true. However, I would like to use the horizontal scroll without the autoScrolling feature because I want to trigger the navigation on section1.

I isolated the code in a jsfiddle, I was not able to load the (horizontalScroll) extension though, because of the license key and not being able to find a cdn for it (sorry!). 
https://jsfiddle.net/92826mkn/49/

I'm running Chrome 64.0.3282.186, macOS 10.13.3

Thanks for your help and if you need more information I'll gladly help :)

**Comment by alvarotrigo** [comment]
> Just got the Scroll Horizontally extension for fullPage.js. Everything works fine when autoScrolling is set to true. However, I would like to use the horizontal scroll without the autoScrolling feature because I want to trigger the navigation on section1.

Those options are exclusive. Not compatible between them.

**Comment by kubmin** [comment]
Thanks for your response!

Ah that’s unfortunate. I cant seem to trigger aos.js animations when arriving on section 1 with scrollHorizontally and autoScrolling enabled. Do you have any idea on how to trigger tue navbar with these options enabled? 

Thanks for the help, appreciated!

**Comment by alvarotrigo** [comment]
> Ah that’s unfortunate. I cant seem to trigger aos.js animations when arriving on section 1 with scrollHorizontally and autoScrolling enabled. Do you have any idea on how to trigger tue navbar with these options enabled?

I would encourage you to make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

But if you still want to use Aos for any reason, although it won't perform as good, you can use `scrollBar:true` as suggested in [the fullPage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions).

**Comment by kubmin** [comment]
Cheers, I will look into this.

Thanks for your great, fast support. 👍
