### ISSUE TITLE
Padding in top is cut off when scrolling back up

### ISSUE THREAD

**Issue by amityweb** [alvarotrigo/fullPage.js#3138]
I have a section with a data-anchor, and in that section I have put 120px padding on the top, because I have a fixed header. If I scroll down, then backup, fullpage.js stops at the bottom of the padding, so the padding is off the screen, so the content is pushed too far up the page. Do you know how I can get fullpage to respect the padding I put in? I would send a link but its in development, I cant share it publicly. 
Thanks

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by amityweb** [comment]
Hi. Not sure how I can replicate a Wordpress site on jsfiddle.net or codepen.io. It would be much easier to send you a link so you can see whats going on. What does "links to personal websites won't be reviewed unless isolated"? Mean? I dont want to paste the website here as its in development, but its best you take a look to see the issue. 
Thanks

**Comment by amityweb** [comment]
Oh I have an update that may help....

I just realised it works fine on my large monitor. Its on my smaller Macbook monitor the issue exists. So investigating further I can see when scrolling back up its actually stopping at the bottom the section, not the the top. So the issue is that, not cutting padding off!

**Comment by amityweb** [comment]
This fixes it for me:
bigSectionsDestination:top,

I am surprised scrolling to the bottom is the default, because it will always start in the middle of text. It just looks wrong. If its the top section you cant even scroll up more to see the very top text.

**Comment by amityweb** [comment]
Problem now is scrollOverflow: true doesnt work! Long sections are not scrolled normally, they still jump to the next section so we cant read all text. Going to keep looking but cant find a solution for it, may raise another issue.

**Comment by alvarotrigo** [comment]
@amityweb open a new issue with an isolated reproduction for your issue.
**Do not replicate your site**. Replicate the issue. Use empty sections if possible and no CSS or JS code external to fullpage.js

I'll proceed to close this issue as you managed to solve it.
