### ISSUE TITLE
Set min-height 100% and height: auto when autoScrolling:false or in responsive mode

### ISSUE THREAD

**Issue by infloent** [alvarotrigo/fullPage.js#3139]
It would be nice to have a class like fp-auto-height and  fp-auto-height-responsive  to set min-height: 100% and  height: auto, for example: fp-min-height and fp-min-height-responsive
I have seen others requesting something similar

In my case I have sections with lots of text that i want to have height: auto but there are sections with just a headline so it makes sense for this type of section to have the a min-height: 100%.

Unfortunately min-height: 100% on display table/table-cell element it's not working on all browsers.

fp-min-height and fp-min-height-responsive can only be handled with JavaScript

I have come up with this for responsive mode but this should be added to the plugin:

```JavaScript
var isResponsiveMode = false,
    $fullpageContainer = $('.fullpage'),
    responsiveMinHeightCls = 'fp-min-height-responsive';
    
$fullpageContainer.fullpage({
    responsiveWidth: 769,
    responsiveHeight: 800,
    afterResponsive: function(isResponsive) {
        //set the responsive mode status
        isResponsiveMode = isResponsive;
    },
    afterResize: function() {
        // set section min height on resize
        if (isResponsiveMode) {
            var windowHeight = $(window).height();
            $fullpageContainer.find('.section').each(function() {
                var $section = $(this),
                    $sectionInner = $section.find('.fp-tableCell');
                    $sectionAndSectionInner = $section.add($sectionInner);

                if ($section.hasClass(responsiveMinHeightCls)) {
                    $sectionAndSectionInner.removeAttr('style');
                    sectionHeight = $section.height();

                    if (windowHeight < sectionHeight) {
                        $sectionAndSectionInner.height(sectionHeight);
                    } else {
                        $sectionAndSectionInner.height(windowHeight);
                    }
                }

            });
        }
    },
});
```

**Comment by alvarotrigo** [comment]
Why not using a fixed pixels height? If it is just a title it might look quite lost in mobile devices with big screens, won't it?
Setting a fixed height like 500px or 400px can make it look decent in all kind of devices.

**Comment by infloent** [comment]
Main reason... client request and because they are using background images of interest so the full height size it's not bad for it.

In my case on a page are 40+ slides not a really good idea to manually set heights for each slide that has a relatively small content and maintain them on content updates. 

And the content it's still of different sizes even for the small content ones, e.g. for a bigger phone could fit nice, but for a smaller phone some of this small content slides could overflow. 

But if we take in consideration all variation of screens tablet/mobile it's just impossible to maintain.

**Comment by alvarotrigo** [comment]
This has an easy solution:

Only use fp-auto-height for the sections for which you to be bigger or smaller than the viewport. **Do not** use the class for the ones you want to keep full height.
