### ISSUE TITLE
Scrolling-event twice on mac 

### ISSUE THREAD

**Issue by 3oax** [alvarotrigo/fullPage.js#314]
hey!
I don't know if this issues is reported yet:

If i use my trackpad or the magicmouse on an page with the fullpage.js script, the scrolling event is triggered twice. it scrolls down and skips the third page. help?

it even doesn't work on the demopage
http://alvarotrigo.com/fullPage/

**Comment by Biswajit993** [comment]
In my MacBook Air it's Scroll two time when I scroll only one time. How to fix it?

**Comment by alvarotrigo** [comment]
You are rather doing something wrong initializing fullpage multiple times (see the JS console for errors), or you are swiping way too fast. 

Also make sure to use the latest version of fullPage (version 4).

You can also try increasing the scrolling speed option to 900 or 1000.
