### ISSUE TITLE
Activation key lost

### ISSUE THREAD

**Issue by ACRV** [alvarotrigo/fullPage.js#3140]
Hello,
I can not find my activation key
What is the procedure to recapture it?

Thank you for your comeback.

**Comment by alvarotrigo** [comment]
It was sent to the email used for the purchase. 
Please check the SPAM folder if it is not on the inbox.

**Comment by ACRV** [comment]
Yes I received an email with my license key
But I was stupid to generate the key of use and to leave the tab or was the key ...

**Comment by alvarotrigo** [comment]
After the purchase you got in your email a license key that is required to generate the activation key.
After you generated the activation key you got another email with it. 

So, you have two keys in your email.

What's the issue now?

**Comment by ACRV** [comment]
I just did not get the second email ... I'll wait! Thank you !

**Comment by alvarotrigo** [comment]
@ACRV mmm want to [contact me](https://alvarotrigo.com/#contact) on private so I can ask for your email and investigate it?

**Comment by ACRV** [comment]
Ok it's done ! Thanks for your rapidity !
