### ISSUE TITLE
Scrollbar Point Style

### ISSUE THREAD

**Issue by glucee** [alvarotrigo/fullPage.js#3142]
### Description
Can I change the scrollbar style? I found your offical demo https://alvarotrigo.com/fullPage/ using several points on the right hand side as the scrolling indicator, how can I use that one ?

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
https://alvarotrigo.com/fullPage/ 
Can I use the scrollbar points as the scrolling indicator ?

### Steps to reproduce it
1. Open your demo page https://alvarotrigo.com/fullPage/
2. how can I use your demo's scrollbar style (several points)

### Versions 
Chrome 64
Windows 10

**Comment by alvarotrigo** [comment]
Use `navigation:true`
