### ISSUE TITLE
Win 7 mouse scroll issue in IE with Drag And Move on scroll bar

### ISSUE THREAD

**Issue by kater89** [alvarotrigo/fullPage.js#3143]
The issue we ran across on our site is in Windows 7 - IE 11, if you grab the scrollbar and then let go, the page sometimes scrolls right to the top. Also, after you click the scroll bar, you can move the page with your mouse until you click somewhere off the scrollbar.

I duplicated this on your demo site.

If you go to https://alvarotrigo.com/fullPage/examples/scrollBar.html then it's just fine - everything works.

However, I have the drag and move extension enabled with the scrollbar.

If you go to https://alvarotrigo.com/fullPage/extensions/drag-and-move.html, it has the bug.

I can only see this on Windows 7 machines which unfortunately our client uses. We don't have a problem in Windows 10 IE 11. 

There are also some people saying the issue is also on chrome but I have not verified that myself yet.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll investigate it!

**Comment by alvarotrigo** [comment]
> I can only see this on Windows 7 machines which unfortunately our client uses. We don't have a problem in Windows 10 IE 11.

Which IE are we talking about then? If not 10 or 11 ?
The operative version should be irrelevant here.

**Comment by alvarotrigo** [comment]
Ok, I think I've fixed the issue. 
Could you please [contact me](https://alvarotrigo.com/#contact) with the email used for the purchase so I can send you the newest version 0.0.5 ?

**Comment by kater89** [comment]
> Which IE version are we talking about then? If not 11? I assume 10?
> The operative version should be irrelevant here.

I know you said that you have it fixed - I just wanted to clarify for anyone else reading this that the issue was with IE 11 on a Windows 7 machine. IE 11 on Windows 10 worked fine.  I did not test IE10 and Edge versions were fine.

Thanks for fixing this so quickly!

**Comment by alvarotrigo** [comment]
Solved in the new release 2.9.7 and the new Drag And Move version 0.0.5!
