### ISSUE TITLE
ScrollTop when resize the browser.

### ISSUE THREAD

**Issue by brucelin0325** [alvarotrigo/fullPage.js#3146]
### Description
This fullPage.js is great and I'm using this library for my project.
For now I'm facing this issue.
When I resize the browser, section position not correct.

![image](https://user-images.githubusercontent.com/28854619/37182315-a4fc9b18-236b-11e8-8ff8-dd6099af6305.png)

And it is corrected when I scroll up and down.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by brucelin0325** [comment]
Hi, Alvaro. 
Sorry for delayed reply. I tried to provide the isolated reproduction in jsfiddle, but I can't.
So I uploaded the project to server. 
You can check the status on here: ahimsainvestments.com
First section working perfect, but from next one section position is wrong after resizing the browser.
If you resize the broswer smaller then section position is little up and when you resize it lager then position is little down.
If you're not clear yet then I will provide some main code section of the project.
Thanks in advance.

**Comment by alvarotrigo** [comment]
> You can check the status on here: ahimsainvestments.com

Please upload an isolated reproduction with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
