### ISSUE TITLE
scrolloverflow and fullpage.extensions problem

### ISSUE THREAD

**Issue by raxcido** [alvarotrigo/fullPage.js#3149]
Hello there,

I have a problem with fullpage.extensions. I read the instruction of using extensions, and want to use scroll-horizontally extension on my page, but when loading files with this order:
```
scrolloverflow.min.js
fullpage.scrollHorizontally.min.js
jquery.fullpage.extensions.min.js
```
it shows this error:
`fullPage: The option 'scrollOverflow:true' requires the file 'scrolloverflow.min.js'. Please include it before fullPage.js.`

But if I change `jquery.fullpage.extensions.min.js` to `jquery.fullpage.min.js` everything works great ( and can't use scroll-horizontally extension )

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with a link to the reproduction. Ideally isolated (with no external CSS or JS to fullPage.js)
