### ISSUE TITLE
scrolloverflow:true is disabling access to window scroll events

### ISSUE THREAD

**Issue by gemlarin** [alvarotrigo/fullPage.js#3151]
### Description
Setting scrolloverflow:true and following the documentation to configue and import the necessary libraries in turn disables access to window scroll events, so there is no way to trigger scroll based animations.

### Steps to reproduce it
1. Enable scrolloverflow, import slimscroll, import scrolloverflow.min.js as per the documentation
2. Set up a basic fullPage DOM structure with one of the sections set to overscroll as per the documentation
3. Now try to access and console log any window scroll event or trigger any scroll based animations

### Versions 
All tested browsers, OSX, v2.9.6

**Comment by alvarotrigo** [comment]
That's not a bug, it is like this by design, unfortunately.
scrolloverflows uses iScroll library which creates its own scroll behaviour that has nothing to do with the browser's one. 

See [my answer here](https://stackoverflow.com/a/39369282/1081396) for a possible solution.
