### ISSUE TITLE
Uncaught TypeError: $(...).fullpage is not a function

### ISSUE THREAD

**Issue by anjoohyun** [alvarotrigo/fullPage.js#3152]
### Description

I do not know why.

Error Message
Uncaught TypeError: $(...).fullpage is not a function
    at initialize (full.html:26)
    at HTMLDocument.<anonymous> (full.html:23)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

### Link to isolated reproduction with no external CSS / JS

http://the-massshop.com/full.html

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]
Chrom, explorer11, windows 10

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
I have no idea what's going on in your website, but there's something definetely wrong. 
`$.fn.fullpage` doesn't even exist, which is not right. 

![screen shot 2018-03-12 at 14 22 32](https://user-images.githubusercontent.com/1706326/37285965-e4bc9b44-2600-11e8-8ff0-643e1004b9ee.png)


I would encourage you to start from the scratch again. You can start taking [the demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html) as a base and see at which point it fails to discover where's your issue.

**Comment by anjoohyun** [comment]
Thank you.
Once solved with an iframe.
It's not true, but there's an automatic source insert on the server side
I do not know how to solve that part.

**Comment by alvarotrigo** [comment]
I'm sorry. I have no idea why you were having the issue. But it is clearly not a fullpage.js issue but something you did.

**Comment by ShivNandan-28** [comment]
> ### Description
> I do not know why.
> 
> Error Message
> Uncaught TypeError: $(...).fullpage is not a function
> at initialize (full.html:26)
> at HTMLDocument. (full.html:23)
> at j (jquery.min.js:2)
> at Object.fireWith [as resolveWith] (jquery.min.js:2)
> at Function.ready (jquery.min.js:2)
> at HTMLDocument.J (jquery.min.js:2)
> 
> ### Link to isolated reproduction with no external CSS / JS
> http://the-massshop.com/full.html
> 
> ### Steps to reproduce it
> 1. [First step]
> 2. [Second step]
> 3. [and so on...]
> 
> ### Versions
> [Browser, operating system, device, ...]
> Chrom, explorer11, windows 10

dude, actually you might be using jquery.fullpage.min.js inspite of fullpage.js and fullpage.css
