### ISSUE TITLE
Cant scroll after popup is closed

### ISSUE THREAD

**Issue by Tobias-Gustafsson** [alvarotrigo/fullPage.js#3154]
Hello!

Im making a website and it has a bunch of different popups in it. It works wonderfully on desktop, but when I open one on my iphone and then close the popup I cant scroll the page anymore. I'm using the normalScrollElements option to all my popups. Im not toggling any class on anything other than the popup itself. 

Css for one popup might look like this:

```
.partner {
    width: 100%;
    height: 100%;
    position: fixed;
    background: rgba($blue, 0.7);
    z-index: 0;
    visibility: hidden;
    opacity: 0;
    display: flex;
    overflow: auto;
    flex-direction: column;
    transition: opacity .2s cubic-bezier(0,0,.2,1), visibility .2s ease-in-out;

    &.is-open {
        visibility: visible;
        opacity: 1;
        z-index: 99; 
}
```

Anyone who has had the same issue as me and know how to handle it? 

Thanks!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
