### ISSUE TITLE
Set a custom navbar on an specific section

### ISSUE THREAD

**Issue by raul4740** [alvarotrigo/fullPage.js#3155]
I added a Bootstrap custom navbar inside section 1 for achieving a "our features effect" and when you click on a tab the text inside that section changes. I want to set the navbar on the bottom on section 1, but it keeps adding itself to section 0. Any kind of help would be greatly appreciated!
[https://www.w3schools.com/code/tryit.asp?filename=FPEGOMG98MEP](url)

**Comment by alvarotrigo** [comment]
Sounds like a non-fullpage.js issue and more like a CSS one. 
I would encourage you to ask that in another place such as stackoverflow.com where they'll be able to help you much better. 

If you believe it is a fullPage.js bug, please provide an isolated reproduction of it with no external CSS or JS code to fullpage.js and the minimum amount of HTML possible.
