### ISSUE TITLE
Hidden specific slide !

### ISSUE THREAD

**Issue by ACRV** [alvarotrigo/fullPage.js#3156]
Hello, I would like to know if it is possible to hide a specific slide of a section and to have access to it only through a link?
Thank you for your comeback !

**Comment by alvarotrigo** [comment]
Sure. Use the `setAllowScrolling` and `setKeyboardScrolling` methods to deny access to any section or slide:

For example:
```javascript
$.fn.fullpage.setAllowScrolling(false, 'up');
$.fn.fullpage.setKeyboardScrolling(false, 'up');
```

You can use them within a callback such as `onLeave` or `afterLoad`.

**Comment by ACRV** [comment]
Thank you for this super fast return!
But that's not really what I want!
It will be easier to understand with a drawing ^ _ ^

[Link](http://dev.acrv.fr/IMG_3320.JPG)

**Comment by alvarotrigo** [comment]
As I said, that can be accomplish with those methods.

**Comment by ACRV** [comment]
It looks like the methods setAllowScrolling and setKeyboardScrolling are only launched when navigation up and down, and not left and right. I need to prevent only one section to be accessible by a link, not all of it.

**Comment by ACRV** [comment]
Nevermind, I used afterSlideLoad callback to do that !
Thanks !
