### ISSUE TITLE
Bootstrap 4 navbar collapse

### ISSUE THREAD

**Issue by ileido1** [alvarotrigo/fullPage.js#3157]
Hi.
When I use it with Bootstrap,the navbar in device moved when it does the effect of collapse does not displace the content downwards if it does not overlap. I want you to move as I normally would in bootstrap

<nav class="navbar navbar-dark navbar-expand-md " id="navbar">
            <a class="navbar-brand  " href="#home">Logo</a>
            <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#Opciones" aria-controls="Opciones" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="Opciones">
                   <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    </li>
                    <li class="nav-item">  
                    </li>
                    <li class="nav-item">
                    </li>
                  </ul>
                 <div class="navbar-nav ">
                    <a class="nav-item nav-link" href="#about">About</a>
                    <a class="nav-item nav-link" href="#met">Met</a>
                    <a class="nav-item nav-link" href="#contact">Contact</a>
                  </div>
                </div>
            </button>
        </nav>
         
<div id="wrapper">
 <div class="section" id="nosotros" data-anchor="about">
      <div class="container ">
        <h1 class="titulo">Nosotros</h1>
        <div class="row">
          <div class="col-md-6 col-xs-6 ">
            <div class="sidebar">
              <ul class="nav flex-column Lista">
                  <li class="nav-item" >
                    <a class="nav-link" id="about1" href="#">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="skills" href="#">Servicios</a>
                  </li>
                </ul>
            </div>
          </div>
          <div class=" col-xs-6 col-md-6">
          <div class="slides">
            <div class="a1">
                <h1>About</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>
            <div class="s1 hide">
                 <ul class="skills">
                  <li>Diseño web</li>
                    <li>Basico:Home, About, Gallery, Basic Content page, Contact</li>
                    <li>Blog: Basic pages, Blog funtionalities, post, publish, etc</li>
                   <li>Catalog</li>
                   <li>Portafolio</li>
                   <li>E-commerce</li>
                   <li>Custom proyect(meeting required)</li>
                </ul>
            </div>
            <div class="services">
              

            </div>
          </div>
        </div>
      </div>
    </div>
    </div>

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
