### ISSUE TITLE
Expanding a section beyond viewport

### ISSUE THREAD

**Issue by nebojsa11** [alvarotrigo/fullPage.js#3158]
Hi,
I am working on a school project...
I need help with expanding a section. 

http://prntscr.com/itqbpm
http://prntscr.com/itqjcm

On a screenshot, you can see my #section1 
I have accordion styled elements, and I made a code when an accordion element is opened, it adds 500px to the rendered height of the #section1 and removes when it gets closed. Now I need the scrolloverflow to appear, the problem is it still acts as if all the elements fit the viewport and I can only scroll to my next section or sometimes it bugs, so it won't even scroll. 

When the accordion is expanded the content is bigger than the viewport and I can't scroll down to see the rest, cause there is no scrolloverflow at that moment. I figure out that scrolloverflow works only when first loaded the page, so it sees, what fits and what doesn't fit the viewport.

I tried adding classes fp-responsive, fp-scrollable those didn't help. 

My idea is to maybe reinitiate scrolloverflow when accordion gets opened :/

Let me know if there's an easy way to fix this, or I should just give up on it by forcing height to 2000px so there is scroll when loaded, with a bunch of unused space :(

Thank you very much

**Comment by alvarotrigo** [comment]
> My idea is to maybe reinitiate scrolloverflow when accordion gets opened :/

Use the `reBuild` method of fullpage.js. Read more about it in the docs.
