### ISSUE TITLE
Global Background Video?

### ISSUE THREAD

**Issue by DanielLausch** [alvarotrigo/fullPage.js#3159]
Hello,

is it possible to setup a global video background? means a video that always stays behind of the website and doesnt disappear or have to reload when sliding to another content area?

best wishes

Dan

**Comment by alvarotrigo** [comment]
Not sure, never tried myself. But that's not a fullPage.js issue, but a matter of CSS knowledge.
I would encourage you to ask in another place such as stackoverflow.com where they'll be able to help you much better with that.

**Comment by DanielLausch** [comment]
hello alvarotrigo,

thank you for your fast answer. 

i know how to add a background video globally with css.

i thought maybe you have that feature somehow available inside your awesome library!

anyway

good job done with that project. i will definitely use it in my new website.

best wishes

Dan

**Comment by alvarotrigo** [comment]
> i thought maybe you have that feature somehow available inside your awesome library!

Nop, fullPage.js doesn't provide such option. It should be done using CSS. 

> good job done with that project. i will definitely use it in my new website.

Glad you like it! Hope you make a good use of it!
