### ISSUE TITLE
Horizontial scrolling with mouse wheel

### ISSUE THREAD

**Issue by Batmunkh** [alvarotrigo/fullPage.js#316]
Hello, this is a great plugin by the way. I only have one thing I need to work out and was wondering if it was possible with your plugin. I want to be able to go through the horizontal slides when the I'm scrolling my mouse wheel. So for example if I go from Section 1 to Section 2 (Section 2 has slides) with mouse wheel or keyboard down button and keep scrolling my mouse or clicking keyboard down button I would go through Section 2's slides first and then go to Section 3. It would be greatly appreciated if there is a solution for this kind of behavior with your plugin. Thanks

**Comment by bpyrate** [comment]
Is this still something you consider to add in the future/next updates or not? Seems that a lot of people would like this feature...

**Comment by alvarotrigo** [comment]
@bpyrate as I said:

> @alfonsocarmelo nop. And probably won't be possible in the future. 
If you really need it, I could customize the plugin for you for some price. Just contact me. But if you can take it from @jakubmal fork that would be great.

**Comment by arielgelbard** [comment]
Heres what I did to get the slides working left and right:

[Credit to this Stack Over Flow Question](http://stackoverflow.com/questions/18202892/horizontal-mousewheel-events-for-left-and-right-wheel-spin)

```
$("#fullpage").mousewheel(function(event, delta, deltaX, deltaY) {
  	if (deltaX > 10){
		$.fn.fullpage.moveSlideRight();
	}else if(deltaX < -10){
		$.fn.fullpage.moveSlideLeft();
	}
	if (deltaY != 0){
	    ///Anything that makes vertical wheelscroll keeps normal
    } else {
        event.preventDefault();
    }
});
```

**Comment by psrivongse** [comment]
Thanks @arielgelbard.

You can do it without the plugin as well.

    $('#fullpage').on('wheel', function(event) {
      event = event.originalEvent;
      // Set to 25 so the sections don't slide multiple times.
      if (event.deltaX > 25) {
        $
          .fn
          .fullpage
          .moveSlideRight();
      // Set to 25 so the sections don't slide multiple times.
      } else if (event.deltaX < -25) {
        $
          .fn
          .fullpage
          .moveSlideLeft();
      }
      if (event.deltaY != 0) {
        ///Anything that makes vertical wheelscroll keeps normal
      } else {
        event.preventDefault();
      }
    });

**Comment by alvarotrigo** [comment]
This is possible now with the [Scroll Horizontally extension](http://alvarotrigo.com/fullPage/extensions/scrollHorizontally.html)
