### ISSUE TITLE
normalScrollElements & scrollBar:true & setAllowScrolling method not working together

### ISSUE THREAD

**Issue by MichaelPrecel** [alvarotrigo/fullPage.js#3162]
### Description
Hi Alvaro,

Thanks again for this fantastic plugin, and all your hard work on it.

I'm trying to pause scrolling on the Fullpage plugin when a fixed scrollable div menu is opened over the top. The fixed div needs to have normalScrolling, but I want the plugin to stay still. The normalScrollElements & scrollBar: true seems to conflict with the setAllowScrolling method, or they are at least not playing nicely together.

This seems like an important feature, is this caused by a bug, or otherwise somewhere I've gone wrong?

Please note that scrollBar must be set to 'true' for me as I am using a code to detect whether certain elements are on the page as you can see in the code (left in for reference).

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/mikepre23/pen/qomjWR

### Steps to reproduce it
1. Click on menu button on top left (menu slides out)
2. Scroll within menu div
3. Notice how the fullpage plugin refuses to pause scrolling and when you reach the base of the scrollable div autoscrolling is disabled on fullpage section.

Any help would be much appreciated! Thank you!

**Comment by alvarotrigo** [comment]
Interesting issue. Thanks for reporting it! I'll investigate it!

**Comment by MichaelPrecel** [comment]
Thanks @alvarotrigo – let me know how you go. Would love to see if there is a fix or workaround for this one!

**Comment by MichaelPrecel** [comment]
Perhaps another interesting aspect of this issue is that if I try to pause scrolling on the fullpage plugin, for example by using this sort of solution ( https://stackoverflow.com/questions/4770025/how-to-disable-scrolling-temporarily/21533631#21533631 ), then the "fp-viewing-x" class that is added/changed to <body> seems to override that solution or cause bugginess. Don't suppose there's any way to prevent that class changing on scroll?

**Comment by alvarotrigo** [comment]
> Don't suppose there's any way to prevent that class changing on scroll?

$.fn.fullpage.setRecordHistory(false);

**Comment by MichaelPrecel** [comment]
Even with recordHistory: false and $.fn.fullpage.setRecordHistory(false); called the class on <body> still changes depending on which section is in view? And on click it reverts back to 'fp-viewing-0'?

**Comment by ReneHetzel** [comment]
I have the same problem with large modals. In this case i have to stop scrolling because only the background is scrolling :(

I solved it by ignoring the scrollBar setting and i freeze the fullpage this way: 

```
		fullpage_api.setAutoScrolling(true);
		fullpage_api.setAllowScrolling(false);
		fullpage_api.setKeyboardScrolling(false);
		fullpage_api.setLockAnchors(false);
```
But now... the navbar in the background get the top scroll design because `fullpage_api.setAllowScrolling(false);` works only if `fullpage_api.setAutoScrolling(true);` is set before. 

Stop scrolling with a active scrollbar would be nice :)

**Comment by alvarotrigo** [comment]
This issue has been fixed now in the dev branch of fullPage.js 3.0.6.
It will be merged for the next release.

**Comment by alvarotrigo** [comment]
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️
