### ISSUE TITLE
[question] "Vertical" version of scrollHorizontally: true

### ISSUE THREAD

**Issue by mokalovesoulmate** [alvarotrigo/fullPage.js#3164]
Hello,

I saw this example: https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html and this is perfect example for the website I want to build. But I need the slides on 1.* and 3.* to be vertical scroll instead of horizontal scroll.

Is this possible?

Thanks.

**Comment by alvarotrigo** [comment]
> Is this possible?

Unfortunately not.
