### ISSUE TITLE
Responsive Mode and Browser Device Mode

### ISSUE THREAD

**Issue by johnnydevs** [alvarotrigo/fullPage.js#3165]
I am doing some testing locally with responsive mode. I have set responsiveWidth: 800, however whenever I am using Chrome device mode and I minimise my screen to under 800 it's not responsive.

I do notice that if I come out of device mode, and resize the browser screen manually it does become responsive.

The same thing happens when viewing the demo here https://alvarotrigo.com/fullPage/extensions/responsive-slides.html 

Is this normal behavior or am I missing something?

Thanks for the plugin, it's great.

**Comment by alvarotrigo** [comment]
Use this and you'll get another result:
```html
<meta name="viewport" content="width=device-width,initial-scale=1">
```
It all depends on the viewport meta tag you use.
