### ISSUE TITLE
How to use this plugin without easing

### ISSUE THREAD

**Issue by batata004** [alvarotrigo/fullPage.js#3166]
Hi,

By default browsers provide at least 3 easing without any library: easeIn, easeOut and ease. I LOVE this fullpage.js library however I am trying to minimize my page load and I really dont want to use jquery easing library. However if I remov jquery easing library from being imported in my head this plugin does not work anymore and raises tons of erros on console.

Is is possible to use this library with just the 3 default easing methods and without needing to import the full jquery easing library?

**Comment by alvarotrigo** [comment]
Easings are only required when using `css3:false`. Which I do not recommend unless required for particular things.

Use the `easingcss3` option together with `css3:true`. 
You can configure the css3 easing as you wish, you can use sites like this one you can find on the [resources section](https://github.com/alvarotrigo/fullPage.js#resources) do so:
https://matthewlein.com/tools/ceaser

**Comment by alvarotrigo** [comment]
If you still want to use jQuery easings, you can use the easings file in the vendors folder, which is only 12 Kb.

Or... you could use [this one](https://github.com/alvarotrigo/skrollTop.js/blob/master/easings.js) from one of my other projects and remove the ones you do not want to use.

**Comment by batata004** [comment]
@alvarotrigo  I cant use css3 because I need to track the effect as it happens to make other things happen in real time (I scroll a slideshow together with the effect of this plugin).

Regarding the easing file currenty I use this one -> https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js which is only 1.2 KB and is provided by a CDN.

The problem is that I need to download this file syncronously and it prevents the parse of the page while the browser downloads this file.

Isnt it possible to make this plugin check if the ease is present, otherwise it uses the default linear as a fallback instead of showing a JS error which breaks the rendering of the page?

**Comment by batata004** [comment]
My friend I also tried the code you provided but it didnt work. I copied a part of the code and placed it right before I load the fullpage plugin. But it still does not work:



	window.easings = {
		def: 'easeOutQuad',
		
		easeInOutCirc: function (t, b, c, d) {
			if ((t/=d/2) < 1) return -c/2 * (Math.sqrt(1 - t*t) - 1) + b;
			return c/2 * (Math.sqrt(1 - (t-=2)*t) + 1) + b;
		}
		
	};

console says:


Uncaught TypeError: n.easing[this.easing] is not a function
    at init.run (jquery.min.js:4)
    at i (jquery.min.js:4)
    at Function.n.fx.timer (jquery.min.js:4)
    at qb (jquery.min.js:4)
    at HTMLBodyElement.g (jquery.min.js:4)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at n.fn.init.animate (jquery.min.js:4)
    at getScrollSettings (jquery.fullPage-modified.js:1505)
    at performMovement (jquery.fullPage-modified.js:1466)
run @ jquery.min.js:4
i @ jquery.min.js:4
n.fx.timer @ jquery.min.js:4
qb @ jquery.min.js:4
g @ jquery.min.js:4
each @ jquery.min.js:2
each @ jquery.min.js:2
animate @ jquery.min.js:4
getScrollSettings @ jquery.fullPage-modified.js:1505
performMovement @ jquery.fullPage-modified.js:1466
scrollPage @ jquery.fullPage-modified.js:1431
moveSectionDown @ jquery.fullPage-modified.js:394
scrolling @ jquery.fullPage-modified.js:1079
MouseWheelHandler @ jquery.fullPage-modified.js:1252

**Comment by alvarotrigo** [comment]
If you use the file I told you, then you can do in the fullpage.js initialisation:

```javascript
easing: window.easings.easeOutBounce
```

That's how I use it [in skrollTo](https://github.com/alvarotrigo/skrollTop.js#using-easing-effects).

**Comment by batata004** [comment]
THANKS!!!! IT WORKED!!!
