### ISSUE TITLE
从DOM元素结构上看，两个Page元素之间不能加代码，不然就没法用鼠标或者键盘上下滚动了

### ISSUE THREAD

**Issue by jun4rui** [alvarotrigo/fullPage.js#3167]
### Description
只要两个元素中间如果加了style或者script，就会滚动不了，删掉就可以了，我有个8屏的滚动效果，有几屏可以鼠标或者键盘滚，另一些则不行，研究了半天才发现这个问题……

### Versions 
[任何浏览器、操作系统下都会如此]

**Comment by alvarotrigo** [comment]
你会英语吗？ 这对我来说会更容易，我在网上使用翻译，它不会是完美的:)

是的，这是一个已知的问题。 我不明白你为什么想在部分之间有东西。

部分之间你想要什么样的元素？

这也与这个问题有关 https://github.com/alvarotrigo/fullPage.js/issues/3081

**Comment by PunishPeopleWhoDoNotKnowEnglish** [comment]
Hey man you do not know english, I am here to punish you. Do you know that we dont understand what are you talking about? What is 只要两个元素中间如果加了style或者script，就会滚动不了, 删掉就可以了?
you have a 8屏的滚动效果?有几屏可以鼠标或者键盘滚，另一些则不行? 研究了半天才发现这个问题? Why do you want to cut you script to many broken pieces? 为什么你会想把style或者script切成一份份？ Do you think that you are cutting your birthday cake? 你是不是想吃生日蛋糕到疯了？ （-_-）
Hey buddy, go to learn english, before cutting cakes, besides, your code convention is poor, no one will want to insert script between element, it makes the web sad , make me sad, make your mother sad.
I am not crazy, I am teaching you how to be a human, not a pineapple, combine your script and style pls.. 我也是很无奈呀兄dei...

**Comment by PunishPeopleWhoDoNotKnowEnglish** [comment]
Who delete my comment? I need to punish people who dont know English, Holy Shit!

**Comment by alvarotrigo** [comment]
在 fullPage.js 版本 4 中这不再是问题：
https://codepen.io/alvarotrigo/pen/oNroZqX

--- 

This is no longer a problem on fullPage.js version 4:
https://codepen.io/alvarotrigo/pen/oNroZqX
