### ISSUE TITLE
scrollHorizontally plugin with horizontal scrollBar

### ISSUE THREAD

**Issue by carrly** [alvarotrigo/fullPage.js#3168]
Hi, I bought the scrollHorizontally plugin and I'm wondering if I can show a horizontal scrollbar at the bottom of the page, instead of the dots. Is it possible with your current build? Or only possible for vertical scrolling. I've enabled these options:
```
scrollBar: true,
scrollOverflow: true,
scrollHorizontally: true,
```

**Comment by alvarotrigo** [comment]
> I'm wondering if I can show a horizontal scrollbar at the bottom of the page

Nop. That's not something fullPage.js provides.
