### ISSUE TITLE
Scroll issue inside section div content ?

### ISSUE THREAD

**Issue by manojcena** [alvarotrigo/fullPage.js#3169]
HI @alvarotrigo 

thank you for your great library.

scrolling the content inside the scrollable section . 
I developed web application using  fullPage js in that i have 5 sections and some of them are scrollable sections . up to this functionality is working fine when i add div and the content in div is scrollable. when i scroll the content div with mouse it also scrolling the section content. 
I added while initializing the fullpage js 
normalScrollElements: '.ctf-tweets,#ctf,.tab-content,#home',

and added class " fp-scrollable " when i applied above both first section scrolling is not happening but i click on dots in section it will move to the next section and when i scroll to 1st section it is working fine .

issue only when i load the page first time first section is not scrolling when i scroll to next section by clicking on dots then entire functionality is working fine 

expecting : when i scroll the content div section content should not scroll. 

please help me out to solve this issue.

Thanks in advance.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
