### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by safeimuslim** [alvarotrigo/fullPage.js#3171]
I got error log from my error tracking services. 
The error message is :

```
TypeError: Cannot read property 'length' of undefined
  at tn(/static/plugins/fullpage/jquery.fullpage.min.js:8:13932)
  at dispatch(/static/js/jquery.min.js:3:12444)
  at r.handle(/static/js/jquery.min.js:3:9173)
  at r(/_next/2413db6f1d0cedd24fdddc4e05e95751/app.js:19:207410)
```

Enviroment
```
fullPage 2.9.6
Chrome 65.0.3325
Mac OS X 10.12.6
```

How to fix it?

![screen shot 2018-03-29 at 07 42 34](https://user-images.githubusercontent.com/12455939/38063723-cbfbee44-3324-11e8-9d30-c824462a665f.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by safeimuslim** [comment]
@alvarotrigo oke,

![screen shot 2018-03-30 at 23 04 30 1](https://user-images.githubusercontent.com/12455939/38144496-1fc69c36-346f-11e8-818c-fd27a188362f.png)

**Comment by alvarotrigo** [comment]
I need a link to an isolated reproduction. Please provide it for further investigation.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
