### ISSUE TITLE
Fullpage on huge screens like imac

### ISSUE THREAD

**Issue by Zetalia** [alvarotrigo/fullPage.js#3174]
Viewing Fullpage sites on large screens like the imac with +4.000px resolution 
results in a very small website mostly.

You can emulate this on smaller screens by zooming out of https://alvarotrigo.com/fullPage/ for example. The h1 remains barely readable and the other elements could also be bigger.

I was already trying to combine bootstrap with fullpage, but that seems to be overcomplicated.
Whats your method to make fullpages responsive on all screens from 300px phones to 4.000px imacs?

**Comment by alvarotrigo** [comment]
> Whats your method to make fullpages responsive on all screens from 300px phones to 4.000px imacs?

Applying the same techniques you do for any other website out there, such as using css3 media queries.
There's nothing specific for fullPage.js here.
