### ISSUE TITLE
normalScrollElements is not working.

### ISSUE THREAD

**Issue by themoonest** [alvarotrigo/fullPage.js#3175]
Hi.

I wanna one scroll just first page, so i use to normalScrollElements option.
I have four sections. give a 'overflow: auto; ' property to section's parents. (not working without overflow property.)
And i changed to scrollOverflow: true, normalScrollElements: '#section1,#section2,#section3'.

What should i do?

**Comment by alvarotrigo** [comment]
> I wanna one scroll just first page, so i use to normalScrollElements option.

That's not the purpose of it, and, as it is detailed in the docs:

>  This option should not be applied to any section/slide element itself.

**Comment by alvarotrigo** [comment]
If you want to scroll within sections, use `scrollOverflow:true` only. 
You will get [this result](https://alvarotrigo.com/fullPage/examples/scrolling.html).
