### ISSUE TITLE
Firefox problem

### ISSUE THREAD

**Issue by startum** [alvarotrigo/fullPage.js#3177]
The scrolling works perfect in Chrome and Safari. However when viewing in FireFox, it begins on the 4th or 5th section and won't go up to the 1st section.

Site is http://codesaloon.wpsaworkshop.co.za

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Steps to reproduce it?
Result and expected result?

Also, it would be nice if you could remove all the garbage to isolate the issue even more.

- Use empty sections
- Remove external resources like fontawesome

Remove jquery.fullpage.extensions.min.js or jquery.fullpage.min.js. You only need to use of them them. Never both.

**Comment by startum** [comment]
## Steps to reproduce it? 
Compare site on Chrome to Firefox. 

## Result and expected result?
On Firefox the site starts on the 7th section. It should start at the top like in Chrome & Safari

I removed all the "garbage" on Codepen, and external resources. 

Thanks

**Comment by alvarotrigo** [comment]
> Compare site on Chrome to Firefox.

Please be more specific detailing the step by step guide.

**Comment by startum** [comment]
Open a Chrome window, and go to the URL http://codesaloon.wpsaworkshop.co.za You will see that the landing page is the 1st section, (the purple page), which is how it should look. 

Open a Firefox window and go to the URL http://codesaloon.wpsaworkshop.co.za You will see that it lands on the 7th section of the site. When trying to scroll to the 1st section it won't scroll at all. 

Firefox should land on the 1st section. 

Not sure how much more specific I can be.

**Comment by alvarotrigo** [comment]
I can not reproduce that issue on your previous codepen. Can you?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
