### ISSUE TITLE
The section height is higher than the viewport

### ISSUE THREAD

**Issue by rhberro** [alvarotrigo/fullPage.js#3178]
### Description
I have a section with a title and a list inside, if I add too many items to the list then the section height get higher than the viewport height. I just want to hide the overflowing items, don't need to scroll the list separately.

### Example
http://agenciasuba.com.br/#hub

### Steps to reproduce it
1. Visit the page above with the given section.
3. Scroll down.
4. Scroll up back.

### Versions 
Chrome, Firefox and Safari (Latest).

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on the [fullPage.js demo page](https://alvarotrigo.com/fullPage/).

Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
