### ISSUE TITLE
seems like auto height is not working

### ISSUE THREAD

**Issue by tejas-kr** [alvarotrigo/fullPage.js#3179]
first of all thanks for this wonderful plugin.
i m not sure whether the problem is with auto height or there is something else.
here is the link : skoolroom.in/ui
![with taskbar](https://user-images.githubusercontent.com/12600231/38352551-3100cc9a-38d1-11e8-9d71-5ce5876e9a47.png)
![without task bar](https://user-images.githubusercontent.com/12600231/38352554-333940e6-38d1-11e8-901b-ecb05af5bfc7.png)

as you can see i have to remove the taskbar to see the navigation dots in the slider.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
