### ISSUE TITLE
wheel in fullpage

### ISSUE THREAD

**Issue by Irina23** [alvarotrigo/fullPage.js#3181]
### Description
I use wheel in event afterLoad. In first load section wheel work good, but if we go to another and come back, wheel does work correct.  
Even with the slightest scrolling by the wheel, two or more scrolls are triggered, I can not understand the dependency, help me.

### Steps to reproduce it
1. Open section, scroll, wheel work good, even with the slightest scrolling
2. Go to other section
3. Come back to first section, wheel does not work correct

### Versions 
fullPage 2.9.4

Thanks

**Comment by alvarotrigo** [comment]
I can not reproduce it on the [fullPage.js demo page](https://alvarotrigo.com/fullPage/).

Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by Irina23** [comment]
https://jsfiddle.net/o3rvengx

e.stopPropagation(); it works for me

**Comment by alvarotrigo** [comment]
Steps to reproduce the issue?

**Comment by Irina23** [comment]
1 Open section, scroll, wheel work good, even with the slightest scrolling
2 Go to other section
3 Come back to first section, wheel does not work correct (if scroll 1, result 2 or more)

**Comment by alvarotrigo** [comment]
Oh I see what you are trying to do. 
That's not at all a matter of fullPage.js.

That has to do with the way the wheel event works in relation with kinetic / inertial scrolling that uses some laptops trackpads or devices such as Apple mouse. 

See this project, that might help. 
https://github.com/d4nyll/lethargy

**Comment by Irina23** [comment]
connecting the library did not solve the problem

**Comment by alvarotrigo** [comment]
You should be asking in another place such as stackoverflow.com
It is not a fullPage.js related issue.
