### ISSUE TITLE
I have a question about transitions in slides

### ISSUE THREAD

**Issue by Rebsiont** [alvarotrigo/fullPage.js#3182]
### Steps to reproduce it
1. build a section
2. put in some slides
3. put in some different text in each slide
4. put in some different images in each slide
5. now how do I make the text slide like in the normal behaviour but I want the images to just flip instead of slide to the next one

### Versions 
lastest chrome on mac osx 10.13 high sierra

**Comment by alvarotrigo** [comment]
That's not a feature provided by fullpage.js I'm afraid.
