### ISSUE TITLE
cannot scroll vertically on ipad safari

### ISSUE THREAD

**Issue by snowflake98** [alvarotrigo/fullPage.js#3184]
### cannot scroll vertically on ipad safari

The second function in the scrolloverflow.min.js causes page not scrolling vertically on ipad safari (it works on ipad chrome and all browsers on laptop). If I comment out the function, the vertical scroll works for ipad safari, but the scroll is not smooth.

### Versions 
[Safari, IPad.]

**Comment by alvarotrigo** [comment]
See this topic https://github.com/alvarotrigo/fullPage.js/issues/3095

Please use the **unminified** version the dev branch. If you still having issues come back and I'll re-open the issue as long as you provide an isolated reproduction of the issue, with no external CSS and JS files and the minimum amount of HTML code.

**Comment by snowflake98** [comment]
Thank you, Alvaro. I applied the new script. It does scroll vertically on
ipad safari now, but is not smooth. Could you check
http://annualreport.norc.org/index1.html#home/4? I appreciate it if you
could give me any thought on what might cause the problem. This only
happens on ipad safari. It even works well on ipad chrome. Thank you.

**Comment by alvarotrigo** [comment]
If you believe it is an issue in fullPage.js, then please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.
