### ISSUE TITLE
resetSliders to specific slide.

### ISSUE THREAD

**Issue by bitchurch** [alvarotrigo/fullPage.js#3185]
### Description

I defined second slide in second section as `active`. 

I need to make it active by default each time I slide from top or bottom. 
I purchased **resetSliders** plugin, but it resets slides to first slide, not default.

```html
<div id="fullpage">
	<div class="section">0</div>
	<div class="section active">
  		<div class="slide">1.0</div>
  		<div class="slide active">1.1</div>
  		<div class="slide">1.2</div>
 	 </div>
	<div class="section">2</div>
</div> 
```

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase and we'll see what we can do to fix it!

**Comment by alvarotrigo** [comment]
I've fixed this issue. Please [contact me](https://alvarotrigo.com/#contact) if you want to get the new resetSliders files.
