### ISSUE TITLE
On scroll up content does not align properly

### ISSUE THREAD

**Issue by skooperss** [alvarotrigo/fullPage.js#3186]
When i scroll down its working fine but when i scroll up its not align
![1](https://user-images.githubusercontent.com/18639556/38464542-c56e2e32-3b28-11e8-86dd-ac46d61ec09b.png)
![2](https://user-images.githubusercontent.com/18639556/38464544-c60956be-3b28-11e8-8456-a5155fd5f986.png)

 properly

**Comment by bredowmax** [comment]
I have the same issue
https://vimeo.com/263707907

**Comment by alvarotrigo** [comment]
I can't reproduce it ion the [fullPage.js demo page](https://alvarotrigo.com/fullPage/).

Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by bredowmax** [comment]
I'm sorry, I don't know how this works since I am using the WordPress theme. The page is www.gorather.com and my issue is on mobile devices (different alignment when scrolling up vs. when scrolling down)

**Comment by alvarotrigo** [comment]
Unfortunately I do not check websites here, only isolated reproductions which clearly show the issue is in fullPage.js.

If you want me to check your site feel free to [contact me](https://alvarotrigo.com/#contact) and ask for the support package.

**Comment by hortonelectric** [comment]
+1 also having this issue. I'll check back here if I can find a workaround.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
