### ISSUE TITLE
Extra padding appears after nav active

### ISSUE THREAD

**Issue by AsadSit** [alvarotrigo/fullPage.js#3187]
Hello There,

At first thanks to the developer for this cool plugin!

Currently, I am doing a web project.
After adding Navigation and click a nav Item I have noticed that extra top and bottom padding appears in my fullpage div.

Here is the live version of my ongoing project http://projects.iasad.me/CookFellas
Without Fixed navbar it clearly appears please see http://projects.iasad.me/CookFellasNF/

Note: My Bootstrap Navbar is out of fullpage div. 
How can I solve it?

**Comment by AsadSit** [comment]
Please anyone reply me.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by AsadSit** [comment]
Please check my second link

**Comment by alvarotrigo** [comment]
> Please check my second link

That's not an isolated reproduction :)
Please remove all CSS and JS code that doesn't belong to fullPage.js. Then use empty sections with a single title in them.

**Comment by alvarotrigo** [comment]
@AsadSit perhaps if you read my latest blog post you will understand what I mean:
https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/

**Comment by AsadSit** [comment]
@alvarotrigo Thanks,

I am not familiar with JS fiddle.
I am feeling trouble.
Can you please see the added screenshot? I highlighted the style that affected my webpage.
https://ibb.co/hrOLnH
I just want to remove the default fullpageJS styles from my website.
Is that possible?

**Comment by AsadSit** [comment]
Hi,
 I have solved the problem by adding bottom padding on the affected sections.
Thanks
