### ISSUE TITLE
Parallax Bounce when using offset 100% and autoScrolling:false

### ISSUE THREAD

**Issue by Djiggo** [alvarotrigo/fullPage.js#3189]
### Description
Hi!

In some browsers, when i scroll, slides are bouncing.
Effect also reproduces in demo page, but not so much. 

### Steps to reproduce it
Init plugin with options:

```
parallax: true,
parallaxOptions: {
                type: 'reveal',
                percentage: 100,
                property: 'translate'
},
autoScrolling: false,
scrollBar: true
```

### Versions 
Firefox 52.7.3, Debian
Safari Mac OS 
IE11, Windows

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with a URL where I can see the issue.

**Comment by alvarotrigo** [comment]
I've confirmed it. It is a performance issue. Thanks for reporting it!

**Comment by MaxInMoon** [comment]
any news it?

**Comment by alvarotrigo** [comment]
Nop. Busy getting rid of jQuery :)
I recommend you to use it together with `autoScrolling:true` to avoid the issue.

**Comment by Djiggo** [comment]
Hello!

I noticed, when i turned off background animation of first slide, bounce
effect is very reduced, but does't completely disappear.
Unfortunately, I wasn’t able to make plugin to work well :(
I can't turn off background animation and i had to write slide animation
myself. Now i don't use fullPage.js.
My slider animation doesn't work well without autoscroll, if background
animation of first slide is turned on.
I don't know how to fix it :(

sorry for my english :)



-- 

C уважением,

Лев Алексеев



2018-05-03 17:05 GMT+03:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
This should be now fixed in fullPage.js v3 and the v3 extension.
