### ISSUE TITLE
Issue with footer attribute

### ISSUE THREAD

**Issue by sandeepvaishnav** [alvarotrigo/fullPage.js#3190]
When I scroll down to the footer of the page, it does not stay there, instead it pulls you above the footer.
Here is a reference link.
https://codepen.io/sandeep/pen/vRbagw 

You can see that at the bottom of the page, I have added footer, but when we scroll down to the bottom the page jumps to the last section and footer vanishes. 

I have tried to find solution to this problem but looks like nobody has come across the same issue.

**Comment by alvarotrigo** [comment]
Please remove all js files external to fullPage.js. Right now your page is dowing some pretty weird stuff when going from one section to another, and that's not part of fullPage.js.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
