### ISSUE TITLE
verticalCentered = false & scrollBar = true not working together properly

### ISSUE THREAD

**Issue by tyte** [alvarotrigo/fullPage.js#3191]
### Description
When I use the options (se code below) together, plugin seems to ignore  'verticalCentered': false. I would really like to use my own css as much as possible. Notice that 'verticalCentered': false works as it should without scrollBar: true.

```
  	$('#full').fullpage({
          scrollBar: true,
          'verticalCentered': false
  	});

```

**Comment by alvarotrigo** [comment]
Working as expected:
https://jsfiddle.net/5yLsdwmt/23/

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
