### ISSUE TITLE
broken links prevent the default first page callbacks from firing.

### ISSUE THREAD

**Issue by hortonelectric** [alvarotrigo/fullPage.js#3194]
Do any set up you want, but you can't do this on codepen. So I made a dev site http://159.65.5.48/index3.html#undefined (index THREE)  or any non-existent # URL. `afterLoad`, `onLeave` are both not called. But you are forced to the first slide. So you cannot trigger anything for your first slide to do, and you cannot even tell it has loaded. In my case, I need to trigger some animations to begin in that slide.

Not sure if this is really something you want to fix or is there a workaround that I don't see?
Right now I do not have a workaround, I just noticed this during other testing.

I think the correct method here would be to recognize a broken link and have a 'brokenLink' callback method in which the default behavior is to `moveTo('firstPage')` but force it...

**Comment by alvarotrigo** [comment]
I'm not quite sure to understand your issue. Correct me if I'm wrong:
Are you just saying that accessing a URL with a non-existen anchor doesn't trigger the `afterLoad` or `afterSlideLoad` callbacks? 
Something like this, right?
http://159.65.5.48/index3.html#fadsfas

Where the `afterLoad` effect should get fired but it doesn't?

**Comment by hortonelectric** [comment]
Yea that's it. It should call afterLoad on the first slide, but doesn't. It should call moveTo on the first slide I think.

**Comment by alvarotrigo** [comment]
> It should call moveTo on the first slide I think.

Why?

**Comment by hortonelectric** [comment]
Because it IS on the first slide, it does load the first slide. So, since the first slide IS visible, and it DID load the first slide, it's a matter of fact at that point.

**Comment by alvarotrigo** [comment]
> I say it should "moveTo" because that would actually change the # hash link to 'firstPage' as well which I think might help somehow.

Right I see. But it has nothing to do with the `moveTo` method right? Good to know!

**Comment by hortonelectric** [comment]
Yea, the issue itself has something to do with moveTo method, kinda. I did notice something odd, though with moveTo. If I'm already on the firstPage, and I moveTo firstPage, nothing happens. but if I moveTo secondPage and then moveTo firstPage, it works!

**Comment by alvarotrigo** [comment]
I'm not able to reproduce this issue anymore.
You can check it yourself using the callbacks demo page and adding a random anchor:
https://alvarotrigo.com/fullPage/examples/callbacks.html#fadsfafs

See how the `afterLoad` callbacks gets fired.

**Comment by alvarotrigo** [comment]
I can reproduce it in 2.9.9 but not on version 3. It seems I got solved on the way.
