### ISSUE TITLE
is there a view to change navbar color on specific section?

### ISSUE THREAD

**Issue by skooperss** [alvarotrigo/fullPage.js#3196]
i have light and dark multiple sections  i want to change font color on specific sections.

**Comment by alvarotrigo** [comment]
You can accomplish that making use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
