### ISSUE TITLE
Normal scroll above and under the plugin

### ISSUE THREAD

**Issue by elisent** [alvarotrigo/fullPage.js#3197]
Hello,

I cant get the your plugin to resume normal scroll after the plugin.

i have the plugin applied to main ( 

`$("main").fullpage({ sectionSelector: "> *");
`
after getting to the last section from main i want to be able to scroll the footer sections (normal no full screen ) but i cant get it working.
 
```
<body>
<main>
     <div class="title fp-auto-height"></div>
     <section>1</section>
     <section>2</section>
...
</main>
<footer>
     <section>1</section>
</footer>

```
Thanks.

**Comment by kartheekkumar** [comment]
I am also having the same issue what you have I am trying to figure out the solution from different ways but no results. Will wait for author reply on this.

**Comment by elisent** [comment]
Here is a codepen:
https://codepen.io/g_emanuel/pen/Kojxvg

**Comment by elisent** [comment]
Hi,

There was another code pen with other html structrure, the sections must be childs or a certain container or can be sub-childs also ?

https://codepen.io/g_emanuel/pen/VXJGMq

**Comment by alvarotrigo** [comment]
> There was another code pen with other html structrure, the sections must be childs or a certain container or can be sub-childs also ?

The required structure is detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#required-html-structure).

**Comment by elisent** [comment]
The structure is not fully details in the docs. In the last codepen i posted all the sections are inside the container.page-scroller but not all are on the first level. Can it work with this nested structure or not ?

[page-scroller]
     [main]
         [section]
         [section]
         [section]
   [/main]
     [footer]
         [section]
         [section]
         [section]
   [/footer]
[/div]

**Comment by alvarotrigo** [comment]
> Can it work with this nested structure or not ?

No.
