### ISSUE TITLE
.fp-viewing-SECTION-SlideX not applied when SlideX > Slide1 > SlideX

### ISSUE THREAD

**Issue by Paperweb** [alvarotrigo/fullPage.js#3199]
**### Issue**

So, a bit further into my project, I managed to work around my previous [issue](https://github.com/alvarotrigo/fullPage.js/issues/3173) by making an overlay out of my HOME instead of a section, so the _**.fp-viewing-HOME .animated-elements**_ on it wouldn't 'blink' on landing.

Meanwhile, something else came up unexpectedly. 

Using [the menu] or [previous/next page] (navigation dots and keyboard work fine), when coming from Slide X to Slide 1 of a section and then trying to go back to Slide X, the class .fp-viewing-SECTION-slide-X won't be applied, effectively not translating the view to Slide X.
Also, the _**.active**_ class won't be applied to SlideX : it stays on Slide1.

- The hash do change in the address bar
- The next move will work as intended (i.e. move to Slide Y or anywhere different than Slide 1/Slide X)
- It used to work before, and it works on the jsfiddle.

To resolve, I've :
- tried to change the active slide from second to first slide
- tried to remove the overlay
- tried other move sequences, which all work as intended : 
_____Slide3 > Slide2 > Slide3
_____Slide2 > Slide1 > Slide 3 > Slide 1 > Slide 2 > Slide 1 > ...
- tried anything, really, considering my limited skills in javascript to dive further into fullPage.js

**### Isolated non-reproduction**

I tried to build a reproduction of the issue with the basic structure of my project, but... it actually works well.
In any case, it might help to have an idea of what I'm talking about.

https://jsfiddle.net/Paperjuice/yf4rpzvh/

**### Steps that don't work for me (but do on the fiddle)**
1. Go to Slide 1.2 or Slide1.3 or Slide 2.2 or Slide 2.3
2. Go to the first slide of that section (using any mean)
3. Go back to the previous slide using the menu or previous/next

I understand it might be website-related and not fullPage-related, but it is still linked to a function of the plugin and any idea would be helpful!
Meanwhile, I'll keep trying to remove stuff until it works.

Thanks ! :D

**### Versions**
Max OS X.11.6
Firefox 59.0.2 / Chrome 65.0.3325 / Safari 11.0.3

**Comment by alvarotrigo** [comment]
> I tried to build a reproduction of the issue with the basic structure of my project, but... it actually works well.

I can't help if I'm not able to see a reproduction of the issue on jsfiddle or any other isolated environment. 
It might be related with your site, as you said. And therefore not something I cover here.

**Comment by Paperweb** [comment]
Ha! I knew you'd say that. 
Took a chance anyway, thinking maybe you'd have a lead to point me a way or another. 
I'll keep digging and give an update on this post!

**Comment by alvarotrigo** [comment]
> Ha! I knew you'd say that.

Yeap, no isolated rep on => error doesn't belong to fullpage.js => not my duty :)

If you need my payed support services, feel free to [contact me](https://alvarotrigo.com/#contact).

**Comment by Paperweb** [comment]
Okay, so.

After quite a bit of digging, I found where the issue is coming from, and was able to make it work. 

The problem was apparently coming from the **hashChangeHandler** function of fullPage.js, in conjuction with another parameter explained below.
Also, it's good to note than something is hard to see on jsfiddle : the actual hash changes.

**fullPage 2.9.6** – line ~1740

```
[...]
if ((sectionAnchor && sectionAnchor !== lastScrolledDestiny) && !isFirstSlideMove
      || isFirstScrollMove
      || (!slideMoving && lastScrolledSlide != slideAnchor )){
            scrollPageAndSlide(sectionAnchor, slideAnchor);
 }
[...]
```

Leaving the function as it is, here is what happens :
- Landing on Slide1 from SlideX gives me :
`slideAnchor = slide-1`
`lastScrolledSlide = slide-X`
- Going back to SlideX through the menu doesn't work. But the navigation dots helped to make the move and, when landing back on SlideX, provided me with :
`slideAnchor = slide-X`
`lastScrolledSlide = slide-X`
**HA!**

Hence, I changed :
`|| (!slideMoving && lastScrolledSlide != slideAnchor )){`
to :
`|| (!slideMoving)){`

And it worked like a charm. Would there be side effects? Don't quite know. 
But thinking of it, maybe the `lastScrolledSlide != slideAnchor` part is actually not that useful in this **hashChangeHandler** function, since when clicking on a link that tries to change the hash to an identical one, no actual hash change is detected, and the function not fired. What do you think ?

In any case, I had found the issue but not quite resolved it.
The real problem here seemed to be that when trying to leave Slide1 with the menu, the `lastScrolledSlide` variable didn't take the value `slide-1`, but stayed locked on `slide-X`, preventing any move back to it.

And then I stumbled upon line 2398, with this nice note I put earlier on in the project :
`// modified 2018-03-05`

I realize it is most likely related to [this issue](https://github.com/alvarotrigo/fullPage.js/issues/2000) about the possibility of showing the slide anchor in the URL of the first slide of a section.
I needed that functionality (my first active slide is not the first one, and I need external links to lead to it), so I had done the modification explained in TheChovix's answer :

> At line 2398, in function setState(), replace :
> ```
>else if(typeof slideIndex !== 'undefined'){ 
>   lastScrolledSlide = slideAnchor; setUrlHash(anchorLink); }
>```
> to :
> ```
> else if(typeof slideIndex !== 'undefined'){
>   sectionHash = anchorLink;
>   setUrlHash(sectionHash + '/' + slideAnchor); }
>```

In my eager to trust fellow github members and my noviceness to javascript, I did not see at the time that he deleted a critical part : `lastScrolledSlide = slideAnchor;`.

When changing all this to :

```
else if(typeof slideIndex !== 'undefined'){
   lastScrolledSlide = slideAnchor;
   sectionHash = anchorLink;
   setUrlHash(sectionHash + '/' + slideAnchor); }
```

**Well, everything was wonderland again.**

This issue can be closed, and I'll put a note on the other thread (which would still be a sweet and logical enhancement!)

Cheers Álvaro

**Comment by alvarotrigo** [comment]
> Would there be side effects?

Probably :) 
Things are usually there for a reason. But I won't dig into that now. 
Use it if you think it works fine for you. **Perhaps** you won't get any issue in your scenario.

**Comment by alvarotrigo** [comment]
In any case, glad you solved your issues!
