### ISSUE TITLE
Scroll problem in IE

### ISSUE THREAD

**Issue by SadDeploy** [alvarotrigo/fullPage.js#3200]
### Description
Scroll does't work in IE11/Edge

### Link to isolated reproduction with no external CSS / JS
Open your site https://alvarotrigo.com/fullPage/

### Steps to reproduce it
Tried to scroll and it does't work

**Comment by alvarotrigo** [comment]
Tested on Browserstack on IE 11 over Windows 7 and 8.1
Both IE 11 and IE 11 Metro. Working fine. 

I assume you talk about using the mouse wheel or trackpad? Or are you talking about a touch screen??

**Comment by SadDeploy** [comment]
I used trackpad on laptop

**Comment by alvarotrigo** [comment]
Sorry but I can not reproduce the issue in any system or browser version. 
Probably a problem with your hardware or software? 

I'll close the issue as there's nothing I can do to help without being able to reproduce it.
