### ISSUE TITLE
Fullpage.js & imagesloaded.pkgd.min.js

### ISSUE THREAD

**Issue by leacoisser** [alvarotrigo/fullPage.js#3201]
### Issue

I can't make it work  fullpage.js with imagesloaded.pkgd.min.js : 
https://jsfiddle.net/dbray4fL/15/

I'm trying to associate both, with a witching title effect of Tympanus : 
https://tympanus.net/codrops/2018/02/13/scrolling-letters-animation/

When I delete `<div id="fullpage">` it's work again...

Thanks for your help !

### Versions
Windows10
Chrome 65.0.3325.181

**Comment by leacoisser** [comment]
This : https://tympanus.net/Development/ScrollingLettersAnimation/ should happen. 
But with fullpage.js, nothing happen : https://jsfiddle.net/dbray4fL/19/

**Comment by alvarotrigo** [comment]
> This : https://tympanus.net/Development/ScrollingLettersAnimation/index3.html should happen.

Can you please be more specific?
The color change? The text animation? The images? What is "this"?

**Comment by alvarotrigo** [comment]
The issue still not isolated. Please remove all the unnecessary HTML, CSS and JS code that is not strictly esencial for the reproduction.

**Comment by alvarotrigo** [comment]
The fiddle is full of external sources too. I'll proceed to close the issue until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by leacoisser** [comment]
https://tympanus.net/Development/ScrollingLettersAnimation/index3.html the text animation doesn't work with fullpage.js

All the sources are essential to the functionnement of the jsfield

**Comment by alvarotrigo** [comment]
Unfortunately I only provide support for fullPage.js code. Not any external ones.

**Comment by leacoisser** [comment]
Oh okay, I was thinking maybe you know why fullpage.js and this witching title effect are uncompatible ... Thanks anyway.
