### ISSUE TITLE
Initial slide should be set by adding .fp-initial

### ISSUE THREAD

**Issue by delcon** [alvarotrigo/fullPage.js#3203]
### Initial Slide delclaration
  
I discovered in your resetSlider-extension that you check for `.fp-initial` to reset to. I think it would be a nice feature to be able to set the initial slide by adding `.fp-initial`  to the `slide` for each `section` instead of defaulting to `slide` 0.  

This would enable layouts where you are able to slide of to both directions from the default page.

**Comment by alvarotrigo** [comment]
> I think it would be a nice feature to be able to set the initial slide by adding .fp-initial to the slide for each section instead of defaulting to slide 0.

That's already possible now as pointed out in the docs:

> If you want to define a different starting point rather than the first section or the first slide of a section, just add the class active to the section and slide you want to load first.
<div class="section active">Some section</div>

**Comment by delcon** [comment]
`function getSlideByAnchor(slideAnchor, section)` returns section 0 if parameter `section` is not set.
By changing the returned slide to `.fp-initial` when parameter `section` is not set I get **always** the default slide.
  
your doc's state that `.active` is the **current** active slide.

**Comment by alvarotrigo** [comment]
There's no point in discussing it, just prove it if you think it's not possible.
Here's my proof:
https://jsfiddle.net/1kyuL4em/11/
