### ISSUE TITLE
Scroll normally after last fullPage section?

### ISSUE THREAD

**Issue by PivotMatt** [alvarotrigo/fullPage.js#3205]
Hello -- great plugin ... we use it a lot! We are using fullPage for a vertically-scrolling gallery at the top of a website but would like the rest of the site content (below the gallery) to scroll normally once the last section of the fullPage gallery is viewed. Is this possible?

**Comment by alvarotrigo** [comment]
The only way to achieve that is placing your whole website in the last section of fullPage.js and then using `scrollOverflow:true` to create a scroll bar in that last section as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

That way you would be kind of replicating the effect you want.

**Comment by alvarotrigo** [comment]
Unfortunately not. 
This is at the end of the day a fullscreen slider :)

**Comment by PivotMatt** [comment]
@knoxjr Thanks so much for working out a solution. We ended up with a solution similar to what @alvarotrigo suggested re: placing the rest of the website in the last slide. After all of the trouble the client decided to move in a different direction with the design. Good times.

Thanks again!

**Comment by alvarotrigo** [comment]
@tomByrer what don't you understand from [my reply](https://github.com/alvarotrigo/fullPage.js/issues/3205#issuecomment-382787287)?

**Comment by tomferrall** [comment]
@alvarotrigo was that meant for me? If so, I totally understand the scrollOverflow solution, I was just interested to see how another solution might work.

**Comment by alvarotrigo** [comment]
@tomferrall the other solution won't be 100% bulletproof. There's a reason why the feature doesn't exist in fullPage.js :) 
It won't look smooth with kinetic scrolling devices and the change from autoScrolling to free scrolling won't be ideal.

**Comment by tomferrall** [comment]
@alvarotrigo Yeah that's a really good point. Shame because [https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html](url) is exactly what I want but with a 'normal' site below it.

I just worry using scrollOverflow won't work as the rest of the page will include a lot of scroll activated animations. Also would be handy using your built in carousel video playing as well!

Maybe I'll just change the designs!

**Comment by alvarotrigo** [comment]
@knoxjr uh! That doesn't look bad at all! Thanks for sharing it man!
I guess there's of course less friction implementing it when using `scrollBar:true` as you are doing!

I'll definitely take a second look at this feature!

**Comment by knoxjr** [comment]
no problem @alvarotrigo

**Comment by tomferrall** [comment]
Thanks @knoxjr! really helpful. @alvarotrigo if you could add that feature in the next couple of days that would be great! Haha ;)

**Comment by alvarotrigo** [comment]
@tomByrer indeed it would! Hahah, but I won't be able to, I have many other things in the todo list for this month :)

**Comment by WilliamSf** [comment]
The idea of ​​@knoxjr was very good, I tried to implement it on my site and it did not work because of the fullpage version @knoxjr used is 2.8.7 and I'm using the newest one, could it help?

**Comment by WilliamSf** [comment]
I even did the way you reported on the link: [](https://codepen.io/williamsf/pen/pGEQNP?editors=1010) , but it did not go well

**Comment by WilliamSf** [comment]
I even did the way you reported on the link: https://codepen.io/williamsf/pen/pGEQNP?editors=1010 , but it did not go well

**Comment by honeyamin** [comment]
> I even did the way you reported on the link: https://codepen.io/williamsf/pen/pGEQNP?editors=1010 , but it did not go well

if you use 2.6V it will work. but i think that you should include iscroll yourself (if you use it)

**Comment by jaydeepchauhan7** [comment]
```
var apiFullPage;  
$(document).ready(function() {
 
  apiFullPage = new fullpage( element, {
       scrollBar: true,
       onLeave: function(origin, destination, direction) {
         if( destination.isLast ) {
           apiFullPage.setAutoScrolling(false);
           apiFullPage.setFitToSection(false);
         } else {
           apiFullPage.setAutoScrolling(true);
           apiFullPage.setFitToSection(true);
         }
       }
   });
 
});
```
**It's working well for me**

**Comment by alvarotrigo** [comment]
Here's another example of another page implementing it:
https://www.floid.ch/

**Comment by jarodpeachey** [comment]
@knoxjr Do you have the source code that I could take a look at for your solution?

![Capture](https://user-images.githubusercontent.com/46693952/105856631-71554680-5fb7-11eb-85d6-9e2f243195fd.JPG)

**Comment by sebastianbaumann** [comment]
Here's my solution for having a smoother transition when scrolling back up form the 'normal' page content to the fullPage sections. Other solutions mentioned before were a bit jumpy.

```
new fullpage('#fullpage', {
  scrollBar: true,
  onLeave: function(origin, destination, direction) {
    if( destination.isLast ) {
      fullpage_api.setAutoScrolling(false);
      fullpage_api.setFitToSection(false);
    }
  }
});


const onIntersection = (entries) => {
  for (const entry of entries) {
    if (entry.boundingClientRect.top < 0) {
      if (entry.isIntersecting) {
        fullpage_api.fitToSection();
        fullpage_api.setAutoScrolling(true);
        fullpage_api.setFitToSection(true);
      } 
    }
  }
};

const options = {
  threshold: 0.75
}

const observer = new IntersectionObserver(onIntersection, options);
observer.observe(document.querySelector('.fp-section:last-child'));
```

**Comment by alvarotrigo** [comment]
This is now possible in v4! 👍  🕺 🎈  💃
