### ISSUE TITLE
Issue - Scroll up snaps to the bottom of the section

### ISSUE THREAD

**Issue by johnenosh92** [alvarotrigo/fullPage.js#3207]
###Scroll down perfectly scrolls to the top of the  next section. But, Scroll up snaps to the bottom of the section which is not what I expected.

I want SCROLL UP and SCROLL DOWN to snap to the TOP of sections.

My page behaves similarly as shown in the screenshots of #3186 

If there is a fix the the VIEWPORT HEIGHT that the fp-tableCell takes, which actually overflows my browser window, It would be a great deal too. BTW there is no overflowing elements in each section. The elements are minimal throughout.

PS. I know there might be few duplicate issues existent as this, which im not able to find. Please direct me to it through a link that answers this. If this issue is still under Reproduction, Please provide me a temporary fix so that I could deploy my site for now.

Thanks,
John Enosh

**Comment by alvarotrigo** [comment]
> PS. I know there might be few duplicate issues existent as this, which im not able to find. Please direct me to it through a link that answers this. If this issue is still under Reproduction, Please provide me a temporary fix so that I could deploy my site for now.

Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2149
I'll close this issue.

You might find a temporal solution here:
https://github.com/alvarotrigo/fullPage.js/issues/1854#issuecomment-320578553

**Comment by johnenosh92** [comment]
Thanks for the fix. It was such a help to use fullpage JS. Thanks!
