### ISSUE TITLE
fp-tableCell has a padding that is unremovalble

### ISSUE THREAD

**Issue by johnenosh92** [alvarotrigo/fullPage.js#3209]
### 
![fb-cell](https://user-images.githubusercontent.com/21054669/39050754-25d71122-44c4-11e8-9081-a2a0dcf00821.PNG)

As shown in the screenshot, fp-tableCell has a padding that does not allow divs to stick to the bottom of the section. As you see the bottom black bar is not allowed to stick to the bottom of the page because of the padding(green).

I WANT to eliminate the padding of the BOTTOM & TOP of fb-tableCell.

Thanks,
John Enosh

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by johnenosh92** [comment]
Resolved my self. Thank you for your concern.

**Comment by MattAppleton** [comment]
Curious as to how this was resolved @johnenosh92  - - I have run into the same issue!

**Comment by MattAppleton** [comment]
In my case I had an image loading into a slide that wasn't sticking to the bottom as intended with 

.fp-tableCell {
vertical-align: bottom; 
}

I fixed it (so far I think!) by setting the image within .fp-tableCell  to display: list-item;

**Comment by jdsoftverapc-1** [comment]
@alvarotrigo there is unwanted padding in the fullpage js like if you try to open it in ipad screen via chrome inspect thing in screen of 1366 * 1024, all content of that section hides in bottom screen.

**Comment by alvarotrigo** [comment]
That's not really a padding.
It is the result of having a `display: table-cell` element inside a `display: table` one with `vertical-align: middle`;

<img width="309" alt="image" src="https://user-images.githubusercontent.com/1706326/67221403-acb7ab80-f42b-11e9-8c2b-2d08180a0c41.png">


You can actually go to "Computed"styles and search for "padding". You'll see there's no padding at all :)

**Comment by jdsoftverapc-1** [comment]
didn't notice that, pretty neat.

**Comment by Masoud-94** [comment]
This worked for me. Maybe you find it useful for a specific condition to have it.
My problem was when I disabled full-page on small devices and want to control the position of elements.

`.fp-section.fp-table {
    height: auto !important;
  }
  .fp-tableCell {
    height: auto !important;
  }`

**Comment by alvarotrigo** [comment]
@Masoud-94 you should check the class `fp-auto-height-responsive` . I believe that's what you are looking for. More info about it on the  [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)
