### ISSUE TITLE
normalScrollElements making my body scroll after the overflow div reaches the end.

### ISSUE THREAD

**Issue by PratyushMaheshwari** [alvarotrigo/fullPage.js#3213]
I'm using the normalScrollElements  function but when the div reaches the end the body section  scrolls down, the scroll has a normal scrolling behaviour.

this is the code I'm currently working on.

                          `  <script type="text/javascript">

                             $(document).ready(function() {

                      $('#fullpage').fullpage({

                anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage',    
                '5thpage','6thpage','7thpage','8thpage','9thpage', 'lastPage'],
                

           lockAnchors: true,
                    scrollBar: true,

             sectionsColor: ['black',  'whitesmoke', 'whitesmoke',
                                      'whitesmoke','whitesmoke', 'whitesmoke',                
                                         '#383A3E' ,'whitesmoke' ,'black', 'black'],

            normalScrollElements: '.scrollable-element',
             afterLoad: function(anchorLink, index){
 
				if (anchorLink === "firstPage"   ) {
					AOS.init()

					
				} 
			},
		});

		});
	</script>`

             `    <style>
       
               .scrollable-element{
            height: 400px;
            width: 600px;
            overflow-y:scroll;

          position: relative;
           top: 28%;
           left: 29.16%;
             border:  solid #00ff00;
             border-width: 1px 0px 1px 0px;   }

               .box1{
      
             background: whitesmoke;
            margin: 20px;
            padding: 12px;
           font-family: acumin pro;
            letter-spacing: .8px;
            line-height: 16pt;
            color:#383A3E;}

    </style>`

Im using safari.

**Comment by alvarotrigo** [comment]
Duplicated of the open issue: https://github.com/alvarotrigo/fullPage.js/issues/3162

I'll close this one to keep things in a single place.
