### ISSUE TITLE
Site URL not updating when sections scroll. Only updates upon clicking.

### ISSUE THREAD

**Issue by tizrai** [alvarotrigo/fullPage.js#3215]
site url not updating as I scroll the sections. But works perfect on the fullpage.js website. What am I missing? Please help.

The link is this:
http://oneplacegroup.webflow.io/untitled

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
