### ISSUE TITLE
Please create react-fulpage

### ISSUE THREAD

**Issue by dhwrwm** [alvarotrigo/fullPage.js#3216]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Thanks for the reminder! ;) 
It will come!

**Comment by alvarotrigo** [comment]
The [react component for fullpage.js](http://alvarotrigo.com/react-fullpage) is now alive!!
Please check it out! Here's the link to the repo:
https://github.com/alvarotrigo/react-fullpage
