### ISSUE TITLE
Detect Position from Scrolloverflow

### ISSUE THREAD

**Issue by prisingh** [alvarotrigo/fullPage.js#3219]
### Description

Hi!

I am using the code you specified here: https://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl/39369282#39369282 to detect scroll position on an overflow section. However, it is not working as intended. In your code, it should be logging to the console the y position when I scroll within that section, but for me it is not. Is there a working fiddle for the code you supplied (the one on stackoverflow was a deadlink).

Please assist! Thank you, awesome plugin!!!

My code: 
`			$('#wrapper').fullpage({
				navigation: false,
				dragAndMove: 'fingersonly',
				scrollingSpeed: 1000,
				sectionSelector: '.content-part',
				slideSelector: '.fullpage-slide',
				scrollOverflow:true,
				scrollOverflowOptions: {
					disablePointer: true,
					probeType: 3,
				},
			    afterLoad: function(anchorLink, index){
				   console.log('duyde');
			       var iscroll = $('.fp-section.active').find('.fp-scrollable').data('iscrollInstance');
			       console.log(iscroll);
				   if(iscroll && typeof iscroll !== undefined){
			            iscroll.on('scroll', getScroll);
			       }
			    },
				onLeave: function(index, nextIndex, direction){s
					console.log('leaving section:'+index);
					console.log('next section:'+nextIndex);
				},
			});
			function getScroll(){
				console.log('hiiiiiii');
				console.log(this.y);
				//$('#position').text(this.y);
			}
`

**Comment by alvarotrigo** [comment]
As I said there:

> It is indeed possible. Although the iScroll library has some bugs that were solved for its use in fullpage.js with the scrolloverflow.js fork. I would suggest you to do those changes yourself in the iScroll Probe.

That means you'll have to use iScroll Probe and not the scrolloverflow.js file provided by fullPage.js.
Then you'll need to fix the issues iScroll had, as I did on the scrolloverflow.js fork.

Also, as I said:

> And use the iScroll option probeType:3 as detailed in their docs. To do so extend the default scrolloverflow options with the scrollOverflowOptions param.
