### ISSUE TITLE
Fading effect installation

### ISSUE THREAD

**Issue by nicolusse88** [alvarotrigo/fullPage.js#3220]
Hi,

I just downloaded the JS for the fading effect, but I'm a bit confused because I can't successfully link the file to my website and use it properly.
Is there a complete description on how to set up the fading effect anywhere on the Internet? I can't find anything and the demo isn't enough for me.

Thanks in advance for your help.

**Comment by alvarotrigo** [comment]
Sure, just read the docs:

> fadingEffect: (default false). Extension of fullpage.js. Defines whether to use a fading effect or not instead of the default scrolling one. Possible values are true, false, sections, slides. It can therefore be applied just vertically or horizontally, or to both at the time. Requires fullpage.js >= 2.8.6.

And don't forget to read [how to use fullPage.js extensions too](https://github.com/alvarotrigo/fullPage.js#use-extensions). Notice you'll have to use another fullpage.js file instead of the usual one.

**Comment by alvarotrigo** [comment]
I believe you introduced wrong your email address on the purchase... 
@gmail.co instead of @gmail.com. Let me know if you want me to change it, so you can have your invoice in your email as well as any extension update or important information regarding it.

**Comment by nicolusse88** [comment]
Thanks for the quick reply Alvaro, I'm working on the website right now to see if I can make everything work.

Yes, I realized I made a mistake and updated the adress myself on my account.

**Comment by alvarotrigo** [comment]
> Yes, I realized I made a mistake and updated the adress myself on my account.

Alright, I've changed it in my side too. You probably missed a couple of emails from my side after the purchase.

**Comment by nicolusse88** [comment]
Oh, yes I probably did. This makes sense...

**Comment by nicolusse88** [comment]
Alvaro, 

I can't get my hand on the activation key I was supposed to receive, can you please resend the confirmation email?

**Comment by alvarotrigo** [comment]
> I can't get my hand on the activation key I was supposed to receive, can you please resend the confirmation email?

You should get the license key in the receipt email I've just sent you again.
That's what you need in order to get the activation key by following the instructions detailed here:
https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension

**Comment by nicolusse88** [comment]
I only received the "fadingEffect | Get activation key" email and a confirmation of payment from PayPal.

**Comment by nicolusse88** [comment]
Alvaro, my bad, I went back to Gumroad and found a key in my account

**Comment by nicolusse88** [comment]
Alvaro, adding my key # to the html overwrites the section colors. Any idea why it does that? Here is the code:
	<link rel="stylesheet" type="text/css" href="../jquery.fullPage.css" />
	<link rel="stylesheet" href="webfontkit-20180102-051926/stylesheet.css"/>

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>

	<script type="text/javascript" src="../vendors/scrolloverflow.js"></script>

	<script type="text/javascript" src="../dist/fullpage.fadingEffect.min.js"></script>
	<script type="text/javascript" src="../dist/jquery.fullpage.extensions.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function() {
			$('#fullpage').fullpage({
				sectionsColor: ['#a4a4a4','#a4a4a4','#a4a4a4'],
    			fadingEffectKey: 'mykeynumber',
				fadingEffect: true
		});


Also, I must be missing a line or two because my sections have disappeared and now appear on the same page...
Sorry to bother you, I usually to have that many issues when I create a full page.js website.

**Comment by nicolusse88** [comment]
Is there any way I could download the demo page you use for the fading effect, to re-start from it, or is it now allowed even with a licence?

**Comment by alvarotrigo** [comment]
> Alvaro, adding my key # to the html overwrites the section colors.

[Contact me](https://alvarotrigo.com/#contact) with a URL with the reproduction of the issue, with no external CSS and JS files or code to fullpage.js and the less amount of HTML code possible.

**Comment by alvarotrigo** [comment]
> Is there any way I could download the demo page you use for the fading effect, to re-start from it, or is it now allowed even with a licence?

As easy as right click > view source code.

**Comment by nicolusse88** [comment]
Got it, thanks again!
