### ISSUE TITLE
Can't get Offset ext to work

### ISSUE THREAD

**Issue by BenRacicot** [alvarotrigo/fullPage.js#3221]
### Description
Just purchased the offset ext and added it to my localhost init:
```
var fullpage = $('#fullpage').fullpage({
     offsetSections: true,
     offsetSectionsKey: '58686D5E-11644F22-BD43E0CE-...
```

HTML
```
<div class="section top overlay-blue" data-percentage="80" data-centered="true" data-anchor="top" style="background-image:url(<?php bloginfo('template_directory'); ?>/library/images/leadership-topfold-desktop-bg.png)">
```

and loading [jquery.fullpage.extensions.min.js](https://github.com/alvarotrigo/fullPage.js/blob/master/dist/jquery.fullpage.extensions.min.js)

Am I missing something to create the effect shown in the offset demo?

Base Codepen here: [codepen.io/BRacicot/pen/bMqRVB](https://codepen.io/BRacicot/pen/bMqRVB?editors=1010)

**Comment by alvarotrigo** [comment]
>      offsetSectionsKey: '58686D5E-11644F22-BD43E0CE-...

That's not an activation key but a license key.

Please read the email that was sent to you after the purchase and do not forget to read the docs regarding [how to activate fullpage.js extensions](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension) and [how to use fullpage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions).

**Comment by alvarotrigo** [comment]
Also, you are missing the offsetExtensions file that you get after the purchase.

**Comment by alvarotrigo** [comment]
If you have any further issues with the extension, please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase.

**Comment by BenRacicot** [comment]
That was it! Thank you for your time.
