### ISSUE TITLE
HTML5 Video Controls Being Blocked?

### ISSUE THREAD

**Issue by MAguiarPDS** [alvarotrigo/fullPage.js#3223]
I am working with fullpage.js and am trying to allow controls to show on my background videos with no luck. I wanted to find out if there was something within fullpage that would block them from showing and how to unblock them.

You can view this on your own demo of: https://alvarotrigo.com/fullPage/examples/videoBackground.html
If you right click the video and check Show Controls they do not show.

Thanks so much!

**Comment by alvarotrigo** [comment]
See the HTML element:

```html
<video id="myVideo" loop="" muted="" controls="false" data-autoplay="">
```

Try removing the `controls="false"` attribute.

**Comment by alvarotrigo** [comment]
> Not closed,

Yes closed :D 

Your issue has nothing todo with fullPage.js.
You probably just copied and pasted the example code. Remove this:



```html
	/* Hiding video controls
	* See: https://css-tricks.com/custom-controls-in-html5-video-full-screen/
	* --------------------------------------- */
	video::-webkit-media-controls {
	  display:none !important;
	}
```

If you still have issues, you'd better ask in another place such as stackoverflow.com
Your issue doesn't seem to be fullPage.js related at all.
