### ISSUE TITLE
ScrollOverflow Reset breaks when you remove the mystery hidden input field

### ISSUE THREAD

**Issue by CJ-Davies** [alvarotrigo/fullPage.js#3224]
### Description
I've been struggling to get ScrollOverflow Reset to work on a bootstrap+fullpage.js site & in my investigation I've discovered that removing the mystery/unexplained hidden input field at the end of the ScrollOverflow Reset example page (https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html) produces the same problem.

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html

### Steps to reproduce it
1. Visit https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html
2. Scroll down through section 2 & into section 3
3. Scroll back up from section 3 into section 2
4. Section 2 resets to the top as expected
5. Delete the line   <input type="hidden" id="_4" value="3" />
6. Scroll down through section 2 & into section 3
7. Scroll back up from section 3 into section 2
8. Section 2 does not reset to the top

### Versions 
Windows 10 1709 + Chrome 66.0.3359.139
MacOS 10.13.3 + Safari 11.0.3

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with an isolated reproduction on your site and with the scrolloverflowReset file you purchased. 
Also, use the email you used for the purchase.
