### ISSUE TITLE
Tab key is not working in registration form

### ISSUE THREAD

**Issue by sarojuid** [alvarotrigo/fullPage.js#3225]
Hi 
Recently I have implemented fullpage in one of my angular 4 project and it is working fine. 
But somewhere my Tab key is not working.  I will tell you here where I am getting the issue.

I have one landing page, from there I have two navigation.  One is to registation form and other to about us page (this is where i have implemented fullpage.js). In about us page and in about us.ts file only I have written all the script relate to fullpage.js.

Now when I am in Landing page and navigate to registration page everything works fine, But my problem is when I am navigating to about us page, then go to registration page my Tab key is not working. 
Yes Its a strange problem for me.  If anyone having the same issue or got any solution please let know.

**Comment by alvarotrigo** [comment]
Might be related with this issue https://github.com/alvarotrigo/fullPage.js/issues/3144
But we'll never known as you didn't provide an isolated reproduction of the issue.

I'll proceed to close this issue as the other one is open.
