### ISSUE TITLE
Menu Sidebar 

### ISSUE THREAD

**Issue by Mateo-M9** [alvarotrigo/fullPage.js#3226]
Hello Alvaro,

Is it possible to implement a sidebar menu to navigate through all the sections? Which can be hidden and displayed with a button?

How could I do it?

I was doing the example of W3 but it did not work for me.

https://www.w3schools.com/howto/howto_js_sidenav.asp

**Comment by Mateo-M9** [comment]
I just looked at the examples page and could also serve the menu that is used to change the language.

![sidebar](https://user-images.githubusercontent.com/32077469/39820264-05e79f2a-536b-11e8-9646-15c847144835.PNG)

How can I implement it?

**Comment by alvarotrigo** [comment]
That has nothing to do with fullpage.js features. 
It is a CSS / HTML/ JS knowledge question that doesn't belong in this forum.

I would encourage you to ask about menus in other place such as stackoverflow.com

**Comment by Mateo-M9** [comment]
Yes, in fact I have already asked. But I thought that fullpage had something ready for that. For example, as I told you about the language selector that you have implemented on the examples page. It's exactly that's how I need it.

**Comment by alvarotrigo** [comment]
All you need to know about fullPage.js features is detailed int he [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

There's nothing regarding menus like that :)
