### ISSUE TITLE
Only used on screen

### ISSUE THREAD

**Issue by GKennyKwok** [alvarotrigo/fullPage.js#3227]
### If I want to print the most content on the smallest amount of paper, is it not necessary to use fullpage.js?

 I directly added @media only screen to css, but this cannot be updated from the web.
There is a very contradictory thing. Sometimes I want to print the page perfectly.
But more often than not, the background is secondary.
For example, when I used to make a resume, I wanted to print something else.

**Comment by alvarotrigo** [comment]
I'm not sure to understand your issue?
Why don't you just use the "print" css style sheet to remove the background?

**Comment by GKennyKwok** [comment]
Thank you for your code, I'm using fullpage to create my resume.
I want to print when the content is another kind of layout, if a page is printed on a piece of paper, the interview should be said to be not environmentally friendly. 
Usually I need to make extra A print using the page, but I want to try compatibility under the same page.

**Comment by alvarotrigo** [comment]
Sorry I do not understand your issue. 
Try to explain it with another words on with an isolated reproduction in which I can reproduce the issue you are facing.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
