### ISSUE TITLE
proposal: unit tests and CI

### ISSUE THREAD

**Issue by DanielRuf** [alvarotrigo/fullPage.js#3228]
### Description

We should have unit tests which are executed on each commit and PR.
Travis CI (and Browserstack) might be the best solutions.

Let me know ow we can help here and make the suggested changes.

**Comment by alvarotrigo** [comment]
I've been [working for a couple of weeks](https://twitter.com/IMAC2/status/994187997875752966) making tests with qUnit. 

Don't think I feel like starting again from cero right now :) 

> Let me know ow we can help here and make the suggested changes.

Once I get them published and fullPage.js v3 is released, please feel free to port them to any other technology if you believe it is a better approach.

**Comment by DanielRuf** [comment]
Sorry, I was not aware of this. Also I head headless testin in my mind an Browserstack + Travis CI for automatic testing of every commit and PR.

Will help then with the integrations.

**Comment by alvarotrigo** [comment]
Thanks! That'd be great!

**Comment by alvarotrigo** [comment]
> Will help then with the integrations.

Hey @DanielRuf, you can now take a look at the available tests in qUnit here:
https://github.com/alvarotrigo/fullPage.js/tree/master/tests

In case you want to help with the porting.

**Comment by alvarotrigo** [comment]
@DanielRuf still willing to contribute here?

**Comment by DanielRuf** [comment]
So far I had not yet the time to the enough time to write or contribute tests here but it is at the top of my todo-list.

**Comment by alvarotrigo** [comment]
@DanielRuf no need to write them all. I've done them in jQuery. (although I'm sure they can be improved!)

But if you could help me to move one of the tests, the simplest one, to Travis and using CI, that'd be of great help to me! I'm not really familiar with Travis. A quick setup will make things faster for me :)

Then I'll be able to do the same with the rest by my own.

**Comment by alvarotrigo** [comment]
@DanielRuf are you still willing to help here?
Not with the re-write all of test but just with the configuration for Travis + browserstack.
