### ISSUE TITLE
Autopaly youtube iframe do not work in Chrome

### ISSUE THREAD

**Issue by a2exfr** [alvarotrigo/fullPage.js#3229]
Autopaly youtube iframe do not work in Chrome. In Firefox its perfect.
Any suggestions how to fix it?

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!
Sounds like a change in Chrome of some kind! 

I'll investigate it!

**Comment by KoalaMontana** [comment]
Hi! I also ran into this problem, but with the video tag.

**Comment by KoalaMontana** [comment]
For myself, I decided the problem this way:
1. Add attributes autoplay, muted for video tag;
2. Change src to data-src for source tags.

**Comment by vguerrerobosch** [comment]
https://alvarotrigo.com/fullPage/examples/autoplayVideoAndAudio.html

not working anymore on Chrome 66.

probably affected by

https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by alvarotrigo** [comment]
@vguerrerobosch thanks for the information!
Apparently the only way to make it work is by using a muted video, by adding `mute=1` to the video string, like this:

```html
 <iframe width="560" mute height="315" src="https://www.youtube.com/embed/SQmiT2zz_QM?mute=1" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen data-autoplay></iframe>
``` 

[Reproduction online](https://jsfiddle.net/1kyuL4em/69/)

**Comment by alvarotrigo** [comment]
Wondering now what to do from fullpage.js side.
Should I add `?mute=1` by default to all autoplay videos if the used browser is Chrome?

**Comment by alvarotrigo** [comment]
A bit "tedious" detecting Chrome tho, according to [this answer](https://stackoverflow.com/a/13348618/1081396).

```javascript
var isChromium = window.chrome;
var winNav = window.navigator;
var vendorName = winNav.vendor;
var isOpera = typeof window.opr !== "undefined";
var isIEedge = winNav.userAgent.indexOf("Edge") > -1;
var isIOSChrome = winNav.userAgent.match("CriOS");

if (isIOSChrome) {
   // is Google Chrome on IOS
} else if(
  isChromium !== null &&
  typeof isChromium !== "undefined" &&
  vendorName === "Google Inc." &&
  isOpera === false &&
  isIEedge === false
) {
   // is Google Chrome
} else { 
   // not Google Chrome 
}
```

**Comment by herrajon** [comment]
?mute=1 not working inside fullPage. Used your iframe.

Chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by alvarotrigo** [comment]
@herrajon have you checked [my demo](https://jsfiddle.net/1kyuL4em/69/)? It works like a charm :)

**Comment by herrajon** [comment]
Indeed it does @alvarotrigo .  But this one (https://alvarotrigo.com/fullPage/examples/autoplayVideoAndAudio.html) does not, at least yet. I was using similar method as in the latter. But the demo is everything expected and more. Nice.

 Lastly I want to thank you for fullPage. It is truly amazing. I owe you a refreshing drink.

**Comment by alvarotrigo** [comment]
>  But this one (https://alvarotrigo.com/fullPage/examples/autoplayVideoAndAudio.html) does not

I didn't update it yet :D 

> Lastly I want to thank you for fullPage. It is truly amazing. I owe you a refreshing drink.

Thanks!! Soon releasing version 3!! Without jQuery dependency!

**Comment by alvarotrigo** [comment]
I'll close this as this is more a browser issue/ limitation rather than a fullPage.js bug.
