### ISSUE TITLE
Using section elements as sectionSelector

### ISSUE THREAD

**Issue by PlayLikeLars** [alvarotrigo/fullPage.js#3230]
### Description
I've been using `section` elements throughout my page but I was only able to use a `div` combined with the defined sectionSelector - are there any plans to be able to use other elements than a `div ` as a sectionSelector?

### Link to isolated reproduction with no external CSS / JS
//

### Steps to reproduce it
```
<section class="section">
     <!-- content -->
</section>
```

### Versions 
Chrome v66, Win10, PC

**Comment by alvarotrigo** [comment]
Working as expected: https://jsfiddle.net/1kyuL4em/49/

Use;

```javascript
	sectionSelector: 'section',
```

**Comment by PlayLikeLars** [comment]
Thanks for the response, looks like I've overlooked something!
