### ISSUE TITLE
Please include a sass file

### ISSUE THREAD

**Issue by robslotboom** [alvarotrigo/fullPage.js#3231]
Currently fullPage.js only provides a css file.
It would be nice to add a scss file.

Cheers, Rob

**Comment by alvarotrigo** [comment]
> It would be nice to add a scss file.

Unfortunately I work directly on the CSS file and I do not use SCSS. 
There was a SCSS file in the past, but nobody was maintaining it, so I removed it.

**Comment by alvarotrigo** [comment]
> I can make one if you wish but not within the next two weeks.

Problem is maintaining it in case of any change. 
As I said, I work directly on CSS, and adding SCSS only adds more more step in between that only complicate things more for myself. As nobody else maintains it when necessary. 

So far, as I don't see a need for it, I prefer to keep it simple and use CSS for such a basic stylesheet. 

Perhaps, whenever I decide to learn SCSS, I'll do it, but don't see such a big issue in using plain CSS.

**Comment by robslotboom** [comment]
Ok, i see.

Cheers,

Rob

> Problem is maintaining it in case of any change.
> As I said, I work directly on CSS, and adding SCSS only adds more more step in between that only complicate things more for myself. As nobody else maintains it when necessary.
>
