### ISSUE TITLE
Invert the Interlocked Slide example

### ISSUE THREAD

**Issue by armagedan** [alvarotrigo/fullPage.js#3234]
Hello, 

I am currently building an application which uses keyboard only. I am using Interlocked example as specified on the website. My issue is, on the example when i press left and right arrow keys, the child slides changes horizontally. I have the same setup as the example (for now). I want to be able to change to the next menu item when i press left and right and change the child slides when i press down and up arrow key. As for the animation, left and right arrow key should change the menu items to left or right and the child slides to be changed up and down when i press up and down arrow keys.

I could not find any leads or help as i am fairly new to this.

Hope this makes sense.

https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html

Thanks a bunch

**Comment by alvarotrigo** [comment]
Use `setKeyboardScrolling(false)`. Then bind the keyboard events by yourself to fullpage.js functions such as `$.fn.fullpage.moveSectionUp`, `$.fn.fullpage.moveSectionDown`, `$.fn.fullpage.moveSlideRight` and `$.fn.fullpage.moveSlideLeft`.

**Comment by armagedan** [comment]
What about the animation? The left and right slide? Up and down arrow key as of now navigates through the menu. And the animation is up and down. Do i have to use the same method to reverse it? I want to change menu with left and right plus the animation and the correct slide. The child slide to be up and down animation and up and down keybord arrow keys.

**Comment by alvarotrigo** [comment]
Not sure what you are after, but it sounds like something you would have to code by yourself. Not something provided by fullPage.js.

**Comment by armagedan** [comment]
It’s simple actually 
I just need to explain it a bit more. Sorry for this long and hard thread. 
Basically all i want is to inverse the controls and the animations as well. Like i want left and right child slides to go up and down. And up and down slides to go left and right

**Comment by alvarotrigo** [comment]
> Basically all i want is to inverse the controls and the animations as well. Like i want left and right child slides to go up and down. And up and down slides to go left and right

Not something provided by fullPage.js.

**Comment by armagedan** [comment]
Thanks. I’ll try something else.

**Comment by armagedan** [comment]
Hello, 

I am here with an update which might help you better understand what i want to achieve. I have changed the keybindings "switch" according to how i wanted it inside of fullpage.js. Here is the updated code:

    switch (e.which) {
                //up
                case 37:
                case 33:
                    if(isScrollAllowed.k.up){
                        moveSectionUp();
                    }
                    break;

                //down
                case 32: //spacebar
                    if(shiftPressed && isScrollAllowed.k.up){
                        moveSectionUp();
                        break;
                    }
                /* falls through */
                case 39:
                case 34:
                    if(isScrollAllowed.k.down){
                        moveSectionDown();
                    }
                    break;

                //Home
                case 36:
                    if(isScrollAllowed.k.up){
                        moveTo(1);
                    }
                    break;

                //End
                case 35:
                    if(isScrollAllowed.k.down){
                        moveTo( $(SECTION_SEL).length );
                    }
                    break;

                //left
                case 38:
                    if(isScrollAllowed.k.left){
                        moveSlideLeft();
                    }
                    break;

                //right
                case 40:
                    if(isScrollAllowed.k.right){
                        moveSlideRight();
                    }
                    break;

                default:
                    return; // exit this handler for other keys
            }

Now the problem is the animation. When i press left/right key, it goes up and down animation. and when i press up/down arrow key, it goes left and right animation. Where do i change this? Basically i want the opposite of this.

Many Thanks

**Comment by alvarotrigo** [comment]
change `moveSectionUp`for `moveSectionDown`?
But anyways, I'm afraid I do not provide support for fullapage.js modifications.

I believe it is better for you to do what I suggested on the 1st place. And create your own bindings. This way you'll be able to keep using the latest version of fullpage.js whenever a new one is released. (and soon there'll be a huge update removing jQuery from fullpage.js, in version 3)

**Comment by andyiwest** [comment]
I need something along these lines as well.

Basically, I require the interlocked slides example, but instead of the interlocked slides scrolling horizontally, I need the slides to scroll vertically. Is this possible?

I don't require paging or next/prev arrows, it will autoplay and just scroll through until the user scrolls into the next fullpage section

https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html#3rdPage/2

E.g I need sections 3.2,3.3 and 3.4 to scroll vertically, and then when the user scrolls down again, the normal fullpage script takes effect again.

**Comment by alvarotrigo** [comment]
@andyiwest unfortunately it is not something provided by fullpage.js.

**Comment by armagedan** [comment]
@andyiwest The Only answer you are getting from here is above. I don’t understand why this would be the default behavior. The movement of slides are obviously inverted by default. When I press down, it scrolls and animates horizontally while it should be vertical. Anywho, its better to do it yourself

**Comment by andyiwest** [comment]
Fair enough, I do have a working solution, but it utilises the bootstrap carousel as well as fullpage, I was just hoping to use a single script instead of two.

**Comment by andyiwest** [comment]
@armagedan Perhaps this may be of some use to, this is what I'm using in tandem with fullpage.

https://stackoverflow.com/questions/11589816/twitter-bootstrap-carousel-vertical-sliding

I have a hero slider with autoscroll that scrolls vertically through the images, and then you can resume fullpage by scrolling yourself. You can add paging/next/prev etc.. as well

My only concern is the difference in animation and speed but i'll figure that out.

**Comment by andyiwest** [comment]
@armagedan Keyboard control works as well for that example

**Comment by armagedan** [comment]
@andyiwest same problem for me as well. Animation is the only issue I’m having
