### ISSUE TITLE
Video Background is not showing full width in edge and explorer

### ISSUE THREAD

**Issue by maheshwarib** [alvarotrigo/fullPage.js#3237]
### Description
Hi,
Its been great help with your fullpage.js plugin. It saved my time a lot. I loved it. It works perfectly fine in firefox and chrome browser but when I check it in the Microsoft Edge 42.17134.1.0 and IE 11 there is a gap in left and right side of the video. It's not showing 100% width.

I am following your README instruction. Can you help me to solve it?

### Versions 
 Microsoft Edge 42.17134.1.0
 IE 11

**Comment by alvarotrigo** [comment]
Not a fullpage.js specific issue but a HTML / CSS one. 
You'd better ask in another place such as stackoverflow.com
