### ISSUE TITLE
Horizontal scroll using scrollOverflow

### ISSUE THREAD

**Issue by johanvdr** [alvarotrigo/fullPage.js#3238]
### I was wondering if it would be possible to horizontally overflow a slide like on the vertical demo.

Basically this would be the idea:
![screen shot 2018-05-17 at 12 01 47](https://user-images.githubusercontent.com/33028971/40171017-6d23462a-59ca-11e8-81f8-37c1984efbbd.png)

The yellow line represents the actual width of the slide.
the circles right from the yellow line should move into the slide horizontally. Would this be possible?

**Comment by alvarotrigo** [comment]
Many things are possible with the right knowledge!
But unfortunately this is not a feature provided by fullpage.js.
