### ISSUE TITLE
Header hides under tab-panel on scroll-down in landscape mode

### ISSUE THREAD

**Issue by Odywan55** [alvarotrigo/fullPage.js#3239]
### Description
Header hides under tab-panel on scroll-down in landscape mode
### Link to isolated reproduction with no external CSS / JS
Go to https://alvarotrigo.com/fullPage/ and open it in mobile safari in landscape mode and scroll down 

[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
actually everything is broken on mobile safari((
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Kind of related with this issue https://github.com/alvarotrigo/fullPage.js/issues/2414

Not something we developers have control of. 
Address bars are not accessible for us, we can only try different hacks for different platforms and for different fullpage.js configurations.

**Comment by alvarotrigo** [comment]
> actually everything is broken on mobile safari((

Not the [demo page](https://alvarotrigo.com/fullPage/)
