### ISSUE TITLE
Slider with a fixed element

### ISSUE THREAD

**Issue by arifaj** [alvarotrigo/fullPage.js#324]
Hello Alvaro. 

First, thank you and congratulations for the plugin, it has been of great helpful to me. 

I wonder if it is possible to maintain a fixed component when using a slider. 

I mean, I have a section which has a slide, but this section has a title, which would remain fixed while other elements of the page are in the slide. 

I hope I was able to explain my question, since I'm currently developing locally so I can not put the link here. 

Thank you in advance.

**Comment by itzikbenh** [comment]
I also have this problem. Your CSS solution is quite hacky and doesn't solve the real problem. What if I want the title to be vertically center aligned together with the slide? I think it's a legitimate need, which currently is impossible with the way you structured this.  
Also, making it absolute can make the text overlap the slide on small screens.

**Comment by alvarotrigo** [comment]
@itzikbenh if you have any suggestion I'll be happy to hear it :) 
Just bare in mind, fixed elements won't play well in elements with translate3d properties in some browsers.
