### ISSUE TITLE
Horizontal navigation dots arent as smooth

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#3240]
Hey, I think the horizontal navigation dots arent as smooth as the verticals in Chrome 66.0.3359.181 64 Bit
https://alvarotrigo.com/fullPage/examples/navigationH.html#secondPage

**Comment by alvarotrigo** [comment]
I guess by "smooth" you mean, they get activated on slide load and not on slide leave?

I'll mark it as a possible enhancement.

**Comment by alvarotrigo** [comment]
Fixed in v4! 👍
