### ISSUE TITLE
Don't working mouse wheel or keyboard's keys up and down

### ISSUE THREAD

**Issue by artemgolovan** [alvarotrigo/fullPage.js#3241]
What can broke possibility to use mouse wheel or keyboard's keys up and down?
I tried to realize your plugin here
http://harbor-protect.com/prezentatsiya-harbor/

**Comment by alvarotrigo** [comment]
Sorry I do not check non isolated pages. 

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
