### ISSUE TITLE
OnLeave check if the next section's slide is the last one

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#3245]
Is there any way to check, after leaving (onLeave) a section, if the slide I'm reaching is the section's last slide?

Thanks in advance,
F.

**Comment by alvarotrigo** [comment]
> if the slide I'm reaching is the section's last slide

Use basic jQuery or Javascript:

```javascript
$(this).is(':last-child');
```

**Comment by thisisfed** [comment]
I'm  pretty close, not sure why this isn't working :(

```
onLeave:function(index, nextIndex, direction){
if. ($('.fp-section.active .fp-slide').is(':last-child')) {
     $('.total').addClass('green')}
if  ($('.fp-section.active .fp-slide').is(':not(:last-child)')) {
     $('.total').removeClass('green')},
onSlideLeave:function(anchorLink, index, slideIndex, direction, nextSlideIndex){
if  (t === $('.fp-section.active .fp-slide').length - 1) {
   $('.total').addClass('green')}
else {
   $('.total').removeClass('green')}
```

**Comment by alvarotrigo** [comment]
Remember than `$(this)` will be the leaving section as pointed out [in the docs](https://github.com/alvarotrigo/fullPage.js#onleave-index-nextindex-direction).

Try this:
```javascript
if. ($(this).is(':last-child')) {
```
