### ISSUE TITLE
FP.moveSectionUp to FP.moveSectionLeft

### ISSUE THREAD

**Issue by mohamedshuaau** [alvarotrigo/fullPage.js#3246]
Hello, 

I was wondering if this was possible for you to bring as an enhancement or update. We'd really love to see this happen.

`FP.moveSectionUp` to `FP.moveSectionLeft`
`FP.moveSectionDown` to `FP.moveSectionRight`

`FP.moveSlideLeft` to `FP.moveSlideUp`
`FP.moveSlideRight` to `FP.moveSlideDown`

Currently I have no other option but to use the keyboard key bindings as so:

`$.fn.fullpage.moveSectionDown`

If the above mentioned methods are implemented, we could easily change the directions by calling the public vars.

**Comment by alvarotrigo** [comment]
> FP.moveSectionDown to FP.moveSectionRight

No idea what you mean by that. Can you explain it in another way?

Why don't you just use `$.fn.fullpage.moveTo(3, 2)`; ?

**Comment by armagedan** [comment]
What I mean is, ‘FP.moveSectionUp’ currently animates up and down with navigation being up and down arrow keys. Can you make it possible so the developer will be able to choose if the section animates left or right. Or if the section slide animates up or down. 

So the ‘FP.moveSectionUp’ changes to ‘FP.moveSectionLeft’ with the respective animation being to left side. Same goes for section slides. 

‘FP.moveSlideLeft’ changes to ‘FP.moveSlideUp’ with the respective animation. At the moment we are bound to use the animation of axis for section and section slides provided by fullpage. We can not change section animation axis or slide animation axis.

**Comment by armagedan** [comment]
Sorry but at this point I don’t think i can explain this any better. 

From what i understand, there are sections. And each section has many slides. Correct?

Right now the sections animate top and bottom axis.
Can i change the animation to left and right for section?
And for the slides of each section the animation is left and right. Can i change that to top and bottom animation?

Section are the menu items. Or in other words, they are the vertical sliders. And slides are the ones in each section. Correct?

Lets take the interlocked example from the website for an example. 
Can i change the vertical animation to horizontal? And horizontal animation to vertical?

Sorry this is the best i can explain it

**Comment by alvarotrigo** [comment]
> Can i change the animation to left and right for section?

Nop.
But you can emulate that behaviour by using the [Interlocked Slides extension](https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html), which would move all slides of all sections wheneve you move one. 

See this topic:
https://github.com/alvarotrigo/fullPage.js/issues/200

**Comment by armagedan** [comment]
@alvarotrigo I have reviewed your topic #200. This is exactly what i want but the answers are outdated. The vertical scrolling should be changed to horizontal. And horizontal scrolling to be changed to vertical. I have been looking for this but never noticed. But this post is from 2014 and it is outdated. Could you please briefly explain as i am fairly new to Jquery.

I am guessing the `scrollSlider` is no longer available? Which one should i use instead?
You mentioned on one of the answers to use `setAllowScrolling `. Could you please explain what the use of this is?

Is this right?

```
onSlideLeave: function (anchorLink, index, slideIndex, direction) {
        //For the section 1, slide 0 to the right...
        if (index == 1 && slideIndex == 0 && direction == 'right') {
            var section2 = $('#section1');
            var section3 = $('#section2');
            $.fn.fullpage.setScrollingSpeed(0);
            $.fn.fullpage.setAllowScrolling(section2, 1);
            $.fn.fullpage.setAllowScrolling(section3, 1);
            $.fn.fullpage.setScrollingSpeed(1000);
        }
    }
```
This gives me and error:

```
Uncaught TypeError: directions.replace is not a function
    at Function.setAllowScrolling (jquery.fullPage.js:327)
    at init.onSlideLeave (index.html:42)
    at landscapeScroll (jquery.fullPage.js:1969)
    at moveSlide (jquery.fullPage.js:1302)
    at moveSlideRight (jquery.fullPage.js:424)
    at onkeydown (jquery.fullPage.js:1904)
    at jquery.fullPage.js:1776
```

**Comment by alvarotrigo** [comment]
> But this post is from 2014 and it is outdated. Could you please briefly explain as i am fairly new to Jquery.

fullPage.js never provided a way to do so. You have to figure a way to do it by yourself. 
I unfortunately do not provide support for issues that are not directly related to fullpage.js provided features.

As I said, you can probably emulate that behaviour by using the Interlocked Slides extension, which would move all slides of all sections whenever you move one. Then use setAllowScrolling to disable scrolling right and left on the slides.

If you need my services for that, feel free to [contact me](https://alvarotrigo.com/#contact) and I'll provide you with a quote.
