### ISSUE TITLE
Disable Keyboard scrolling on certain sections

### ISSUE THREAD

**Issue by marwanalqadi** [alvarotrigo/fullPage.js#3247]
Hi, is it be possible to disable the keyboardScrolling (arrows) only on certain sections. and keep it enabled on others?

thank you

**Comment by alvarotrigo** [comment]
Sure!

Jut use the fullpage.js function [`$.fn.fullpage.setKeyboardScrolling(false)`](https://github.com/alvarotrigo/fullPage.js#setkeyboardscrollingboolean-directions) within a callback, such as [`afterLoad`](https://github.com/alvarotrigo/fullPage.js#afterload-anchorlink-index).
