### ISSUE TITLE
Video not autoplaying on mobile

### ISSUE THREAD

**Issue by raul4740** [alvarotrigo/fullPage.js#3248]
### Description:
I have a video background on my first page which works perfect on desktop but on mobile it wont autoplay at load, if I slide to my next page and come back the video works, but I can´t manage to make it work at the first mobile load. I checked on previous issues but they were old and your codepen links were expired already :(

I tried many autoplay variations.

"video data-ignore data-autoplay autoplay loop muted controls="false" id="myVideo" autoplay="autoplay"> 
  <source src="imgs/video.mp4" type="video/mp4">
video>"

### Versions 
Chrome, MotoG5

**Comment by alvarotrigo** [comment]
[It never does on mobile](https://www.aerserv.com/why-does-video-autoplay-on-mobile-devices-not-work/), no matter if you use fullpage.js or not.
