### ISSUE TITLE
Enable vertical scrolling inside non-fullpage container

### ISSUE THREAD

**Issue by esvi** [alvarotrigo/fullPage.js#3249]
I have a fixed "modal" element that is not part of the "#fullpage" container. But I can't manage to get scrolling to work inside this element.

I've tried setting 'normalScrollElements' and 'fixedElements', and 'setAllowScrolling'.

None of those options do the trick. How do I release the scroll event while this other modal is open?

Thanks in advance :)

My config looks like this:

```scrollingSpeed: 1000,
		fitToSection: true,
		fitToSectionDelay: 1000,
		scrollBar: true,
		loopHorizontal: true,
		scrollHorizontally: true,
		resetSliders: true,
		scrollOverflow: true,
		scrollOverflowReset: true,
		scrollOverflowOptions: null,
		touchSensitivity: 33,
		controlArrows: true,
		verticalCentered: false,
		normalScrollElements: '#menu',
		fixedElements: '#header, #footer',
		sectionSelector: '.js-fullpage-section',
		slideSelector: '.js-full-page-slide'

**Comment by alvarotrigo** [comment]
Few options:

- Use normalScrollElements.
- Use `$.fn.fullpage.setAllowScrolling(false)` when the modal gets open. And `$.fn.fullpage.setAllowScrolling(true)` when it gets closed.
