### ISSUE TITLE
Want to create full page only in single section.

### ISSUE THREAD

**Issue by awsomedesigner** [alvarotrigo/fullPage.js#3252]
Hello 

I want to make something similar to given link.

https://www.sapientrazorfish.com/

How to make this using fullpage js ?

**Comment by alvarotrigo** [comment]
Place or your "normal page content" on the last section, and use `scrollOverflow:true` to create the scroll bar in that last section, emulating a normal page.

**Comment by awsomedesigner** [comment]
Thank you @alvarotrigo
