### ISSUE TITLE
ScrollOverflow does not work with a div full of images, remain on next section

### ISSUE THREAD

**Issue by samwise24** [alvarotrigo/fullPage.js#3253]
### Description
My second section is a gallery of images in a vertical column. With scrollOverflow: true, when scrolling down, it scrolls to the next section before it reaches the end of the #gallery section, and the bottom part of the gallery is still visible on the next section.

Additionally, when using scrollOverflowReset, it actually resets on the #stacker section, meaning it covers that section totally

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/samwise24/pen/qKNzGg

### Steps to reproduce it
In codepen, live view must be viewed in a mobile size view.

### Versions 
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
Windows 10

**Comment by alvarotrigo** [comment]
Just use the `reBuild` method:

```javascript
 afterResize: function(){
       if($(window).width() <= 762){
          console.log("updating...");
         $.fn.fullpage.reBuild();
       }
  }
```

Your demo updated:
https://codepen.io/alvarotrigo/pen/a9d8bdee7ed198b6999342bcc1b68b96
