### ISSUE TITLE
Responsive Navigation (Movil)

### ISSUE THREAD

**Issue by Mateo-M9** [alvarotrigo/fullPage.js#3254]
Hello Alvaro,

Could you explain how navigation works on mobile phones? In PC to navigate through the pages, the mouse scroll is used. But how would it be on cell phones?

I already implemented fullPage in my project but when I try the responsive it does not let me navigate by dragging the pages.

[Capture Example](https://image.ibb.co/ho1r3T/captura.png)

**Comment by alvarotrigo** [comment]
You can test it yourself in any of the available demo pages online. Like [this one](https://alvarotrigo.com/fullPage/examples/continuous.html) or the [main page](https://alvarotrigo.com/fullPage/) (which uses the DragAndMove extension)

Responsive (when using the option `responsiveWidth` or `responsiveHeight`) mode turns autoScrolling off, as detailed in the docs:

> responsiveWidth: (default 0) A normal scroll (autoScrolling:false) will be used under the defined width in pixels. A class fp-responsive is added to the body tag in case the user wants to use it for their own responsive CSS. For example, if set to 900, whenever the browser's width is less than 900 the plugin will scroll like a normal site.
