### ISSUE TITLE
Can I LazyLoad DIV Content/Text elements

### ISSUE THREAD

**Issue by armagedan** [alvarotrigo/fullPage.js#3255]
Currently I have a lot of texts in a div which is being taken from Database. I can already lazyLoad images (Loving it). But can I lazy load texts? I am using laravel and here is my code:

```
@foreach($menus->pages as $page)
                <div class="slide" id="slideFinder">
                    <div class="intro">
                        <h1>{{$page->heading}}</h1>

                        <div class="menu_content">
                            {!! $page->content !!}
                        </div>
                 </div>
              </div>
@endforeach
```

And here is the result (as expected with no issues):

```
<div class="menu_content">
<p><span style="color: rgb(51, 63, 72); font-size: 19px;">test</span></p>
<p><span style="color: rgb(51, 63, 72); font-size: 19px;">test</span></p>
<p><span style="color: rgb(51, 63, 72); font-size: 19px;">test</span></p>
<p><span style="color: rgb(51, 63, 72); font-size: 19px;">test</span></p>
</div>
```

As you can see, I am using WYSIWYG Text editor and so the texts are in <p> tag, <span> and so on
Now can i lazyload this like i lazyload images in FullPage? Also, does full page use the same JQuery LazyLoad?

**Comment by alvarotrigo** [comment]
Use any of the available [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) to make an ajax call to your page and retrieve the data you need.
