### ISSUE TITLE
Navigate to empty anchor 

### ISSUE THREAD

**Issue by jscti** [alvarotrigo/fullPage.js#3258]
### Description
Hi there,
A section with an empty anchor totally works in Fullpage (I use it on my first landing slide to have a nice url).
But it seems not possible to navigate to a section with an empty anchor using a standard way (data-menuanchor or href). Surely possible with the JS api.

I understand it's working with a non-empty anchor ;) But would this behavior be possible to fix/enhance ?

Thanks

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/4cmvah9g/

### Steps to reproduce it
1. Click menu item 2 or 3
2. Click menu item 1
3. Fullpage should have scrolled back to first slide

**Comment by alvarotrigo** [comment]
You can:

- Use numeric index for your menu links, such as `#1`, `#2` etc that will still work. 
- Attach a click event to your menu elements and call `$.fn.fullpage.moveTo` function.
