### ISSUE TITLE
If height section more height screen

### ISSUE THREAD

**Issue by watch2raff** [alvarotrigo/fullPage.js#3259]
### Description
Hello, i have height section more height screen.
How to scroll on part section which more screen?
Because switching occurs to next screen.
i got this settings in js 
-    scrolloverflow: false,
-    scrolloverflowReset: false

**Comment by alvarotrigo** [comment]
Use scrolloverflow:true. As in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by watch2raff** [comment]
Thx
