### ISSUE TITLE
Form loses the submit behavior

### ISSUE THREAD

**Issue by cirovargas** [alvarotrigo/fullPage.js#326]
forms dont work on enable the plugin,

**Comment by Oblik-Design** [comment]
How do we go about this, the submit input does not event register a click event, when you talk about place it in the afterRender, is there an exemple somewhere ? 
This kind of important , I mean almost everysite has a form somewhere.

**Comment by Oblik-Design** [comment]
do we really have to .load or fetch a  form in ?

**Comment by alvarotrigo** [comment]
> How do we go about this, the submit input does not even register a click event, when you talk about place it in the afterRender, is there an exemple somewhere ?

Sorry but can't help much without you provising in isolated reproduction in jsfiddle or codepen. 
Need to see the relevant code.
Make sure to use the latest fullpage.js version 2.9.3

**Comment by Oblik-Design** [comment]
IT is not and isolated probleme, everyone with overflow: true has issues, SO if i need a bit of scrolling, at one point in my site, I need overflow: true, because Fullpage cannot be contain to  a section of the site, and return to normal scrolling, we, at least need a way to attrach events !!

**Comment by alvarotrigo** [comment]
What I'm suggesting is you to provide an isolated reproduction so I can check the problem and suggest a solution.

**Comment by Oblik-Design** [comment]
this problem all over the place , there is 10 threads on this issue. Is there an answer ?
https://github.com/alvarotrigo/fullPage.js/issues/2035

**Comment by alvarotrigo** [comment]
Just read the issue you linked:

> Very probably related with the [`click:true` issue in iScroll.js](https://github.com/cubiq/iscroll/issues/1055) which seems never got fixed.

**Comment by alvarotrigo** [comment]
Not a fullPage.js issue but a iScroll.js one.

**Comment by alvarotrigo** [comment]
@Oblik-Design In any case, I always recommend to make use of real responsive sites. Using the class fp-auto-height-responsive` as [in this example](http://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html)

**Comment by Oblik-Design** [comment]
you do realise this make fullpage completly useless !! this is not a minor issue. I was done with trhe website, this was the lasst thing on my list, now after all the quirks in fullpage, i ve got to trash everything.

**Comment by Oblik-Design** [comment]
You should really make this clear, if you need scrolling in your site , do not use fullpage. 

 tried EVERYTHING. different version of iscroll, adding submit to the dom from ajax in afterRender, and it screws up any events .

**Comment by alvarotrigo** [comment]
> you do realise this make fullpage completly useless !!

Wrong. It might make the scrollOverflow feature useless in specific cases. 
A feature I usually recommend not to use... 
A bug which is not in fullPage.js but in an external project. 

Also, as I said on the issue you linked: 

>  if you change your buttons for normal text, it works as expected.

And as always, if you are not happy with it, you are free to find the bug, fix it and provide a pull request. This is open source. People is free contribute and fix things.

**Comment by Oblik-Design** [comment]
normal text ? what is normal text for a form ?  specific cases ? a form is not a specific case, the site I made is completly responsive, I do not understand what you mean again. The bug with fullpage is that you cannot add sections after the ones that uses fullpage. 
I know I can uninstall fullpage, but after 40 hours of fixing every quirks, this is not an options, also my client expects this now...

**Comment by Oblik-Design** [comment]
and the auto-height solution? I do not understand how this is a solution, it deactivates fullpage completly for smaller viewports?

**Comment by alvarotrigo** [comment]
There are issues with iScroll.js. Unless you provide a reproduction of it in jsfiddle or codepen I'm not going to be able to examine it and tell you if there's an alternative solution to your issues I'm afraid. 
Every case is different.

And yeah, my proposed solution is disabling autoScrolling for small resolutions.

**Comment by Oblik-Design** [comment]
well you'll end up always telling it's the iscroll you use,but this  should at a minimum handle pages that do not fit in one viewport, i've seen many pointed you this, and you skip any responsibility, even when there is a proper codepen, AND ALSO my ipad pro, is not a small resolution... so I should skip this also ? it has a bigger viewport then most laptops !

**Comment by alvarotrigo** [comment]
> and you skip any responsibility

You say it as if you were paying for fullPage.js and it was my responsibility to provide you a totally working piece of code for any possible situation. As I said, it is free and open source. Anyone can contribute to fix the problem. I have no responsibility on this matter at all. 

So, use it if you want, and don't use it if it doesn't fit your requirements. I did my best and I keep trying to do it whenever I can, but I happen to have a full time job and a live outside this project and unfortunately I can not cover all cases and spend time that I don't have on fixing things for everyone who asks for it. And less yet, when the error is external to my own code.

**Comment by Oblik-Design** [comment]
I know, but you need to SAY IT CLEARLY ON THE SITE !!! Fidding this out after 40 hours, is incredibly frustrating, and reading you trying to deny this is also frustrating.

**Comment by Oblik-Design** [comment]
Having that working on ipad should come with ***** does not work with overflow .

**Comment by Oblik-Design** [comment]
Cause everything is fine on desktop, it's hard to know that you'll hit a deadly wall in the end and loose all you have done.

**Comment by alvarotrigo** [comment]
> but you need to SAY IT CLEARLY ON THE SITE !!!

I'll do it for the next release.
Something like:

> **Be careful! ** Some click events on elements within the scrollable section might not work due to bugs in the vendor library. 

Take a look at [this reproduction](http://jsfiddle.net/Lehqx9ne/21/) on your ipad. 
Notice how using a `button` element instead of an `input type="button"` allows you to register the click event. This might be a solution to your problem? Where are you registering the click event? 
(in order to see how would it behave in a desktop using fullPage.js, use `click:false` in the iScrollOptions)

**Comment by Oblik-Design** [comment]
thing is , a form can not be replicated without input elements. I know i can fake a form, but this is super insecure.

**Comment by Oblik-Design** [comment]
I have found a solution using webworkers, iframe, and ajax.. to get a simple click.

**Comment by Oblik-Design** [comment]
AND it should read : 
Be careful! Some click events on elements within the scrollable section **will not** work due to bugs in the vendor library. If you need a form, this WILL NOT work using this on mobiles ( ipad included).

**Comment by alvarotrigo** [comment]
@Oblik-Design it all depends on your scenario and you deal with it. For example. Using `click:false` will make buttons and input elements react to click actions as can be seen in [this demo](http://jsfiddle.net/Lehqx9ne/25/) but not on other elements or links. 

If your form has no links, then it is not a problem.
