### ISSUE TITLE
Dynamically inject iframes into sections?

### ISSUE THREAD

**Issue by Sanabria** [alvarotrigo/fullPage.js#3261]
I'm trying to accomplish something that I'm not sure it can be done. I've read the docs but haven't found something to start off of, I'd appreciate if somebody could point me in the right direction.

Problem:
Page has around 15 fullpage sections each one pulling an iframe from Google Data Studio. They take a massive amount of time and resources to load, even when using the link preload directive. This makes it very clumsy and inefficient.

Solution?
Can I create empty sections and somehow (ajax, maybe?) inject the iframe when a section comes into view?

**Comment by alvarotrigo** [comment]
> Can I create empty sections and somehow (ajax, maybe?) inject the iframe when a section comes into view?

Sure! I don't see why not.
Or even use the [lazyLoad feature of fullpage.js](https://github.com/alvarotrigo/fullPage.js#lazy-loading), which also applies to iframes too!

Just use `data-src` instad of `src`.
