### ISSUE TITLE
Move within Div

### ISSUE THREAD

**Issue by Mateo-M9** [alvarotrigo/fullPage.js#3262]
Hello Alvaro,

I have a Div with vertical scroll within a section. How do I achieve that when the mouse pointer is inside that div, it allows me to move vertically inside the div and not change the section?

**Comment by alvarotrigo** [comment]
Use `normalScrollElements` as in [this example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/normalScrollElements.html).
