### ISSUE TITLE
Scroll not working after re-init

### ISSUE THREAD

**Issue by koentjev** [alvarotrigo/fullPage.js#3263]
Thanks for the great work.

I am running into the following issue.
After async loading new content I remove fullpage reference using:
```javascript
$.fn.fullpage.destroy('all');
```

When new content is loaded I re-initate with exactly the same code as the first init:
```javascript
$(".fullPages").fullpage();
```

After this, mouse scrolling doesn't have any effect. However clicking on the menu with anchor links does 'scroll' to the new content. After this, mouse scrolling does also work again. 
Is there a way to make scrolling work directly after re-init?

Hope you can help me!
Thanks in advance

**Comment by alvarotrigo** [comment]
I can't reproduce it on the [methods.html demo page](https://alvarotrigo.com/fullPage/examples/methods.html).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
