### ISSUE TITLE
The scroll does not work if the sections are not in order

### ISSUE THREAD

**Issue by Mariya89** [alvarotrigo/fullPage.js#3264]
Hello! Could you help with this problem, please, when using the fullPage plug-in:
if the sections with the desired class are not in order, that is, for example, with sectionSelector: '.second-user', such ntml:

```html
<div class = "one-p-section first-user">
<div class = "one-p-section first-user">
<div class = "one-p-section first-user">
<div class = "one-p-section second-user">
<div class = "one-p-section first-user">
```
then the 3rd section does not trigger the scroll when you press the buttons on the keyboard, only navigation works.

**Comment by alvarotrigo** [comment]
Yeap, I'm afraid there can not be elements between sections unless they have 0 height.
