### ISSUE TITLE
How to add sections dynamically from javascript file.

### ISSUE THREAD

**Issue by adityatambe** [alvarotrigo/fullPage.js#3267]
I'm trying to add sections through js file but scrolling doesnt work. Please help! 

Screenshot shared below,

![screen shot 2018-06-23 at 1 00 34 am](https://user-images.githubusercontent.com/14750809/41795584-e4a7d6f2-7680-11e8-8e82-bfd35ece649d.png)
![screen shot 2018-06-23 at 1 00 43 am](https://user-images.githubusercontent.com/14750809/41795585-e4d0a604-7680-11e8-9e5b-a2c675b9e9ba.png)

**Comment by alvarotrigo** [comment]
See my answer here:
https://stackoverflow.com/a/36643702/1081396
