### ISSUE TITLE
afterLoad (anchorLink, index) based problem

### ISSUE THREAD

**Issue by vishalnarwal99** [alvarotrigo/fullPage.js#3268]
i don't know how to describe it since i haven't been able to reproduce whats in my mind but i will try to explain it.

the whole process is taking effect while i am scrolling down
what i want is if my section scrolls from section(n) to section(n+1), where n is any integer i don't want afterLoad function to be fired after it completes loading section(n+1), if it scrolls form section(n) to any other section (using navigation) other than section(n+1) it should be fired.

it should be something like this
```
onLeave (index, nextIndex, direction) {
    if(direction == 'down' && nextIndex - index != 1) {
        afterLoad (anchorLink, index) {
            alert("you didn't see previous section");
        }
    }
}
```
but this dosen't works i have tried already

**Comment by alvarotrigo** [comment]
>  i don't want afterLoad function to be fired after it completes loading section(n+1), if it scrolls form section(n) to any other section (using navigation) other than section(n+1) it should be fired.

That's not possible. It will ALWAYS be fired.

Just use a condition inside your callback to prevent that from triggering anything, such as:

```javascript
if(index != 4){
   //won't get executed in index = 4
}
```

**Comment by vishalnarwal99** [comment]
can i use afterLoad event inside onLeave event

**Comment by alvarotrigo** [comment]
> is it possible to use afterLoad event inside onLeave event

No

> or some how transfer variables from onLeave to afterLoad event if both used seperately

Just use global variables for that.
