### ISSUE TITLE
Effect apply to only some part of page

### ISSUE THREAD

**Issue by Kalpesh300** [alvarotrigo/fullPage.js#3270]
Hello,
This is not any bug report. I just want to know if this plugin provides behavior I want to implement in my new project. I like your plugin so much. I used it for many projects. But this time my issue is different. 
I want to apply this single scroll effect to only some part of the page, which could be anywhere in between other sections. 
You can view running effect at [auberginesolutions.com:8000/work](https://auberginesolutions.com:8000/work)

**Comment by alvarotrigo** [comment]
Glad you like fullpage.js!

Unfortunately effects are usually applied to the whole page. It is not easy to deal with scroll hijacking on kinetic scrolling devices.
