### ISSUE TITLE
Typo in your webpage

### ISSUE THREAD

**Issue by norman784** [alvarotrigo/fullPage.js#3271]
[Here](https://alvarotrigo.com/fullPage/#page3) the example says `fullPage` (caps P) when is `fullpage` (all lowercase).

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll fix it this afternoon together with the new release!

**Comment by norman784** [comment]
no problem! thanks for the great lib ;)

**Comment by alvarotrigo** [comment]
Fixed! Version 3 released!
