### ISSUE TITLE
Script error Fullpage

### ISSUE THREAD

**Issue by bomatsara** [alvarotrigo/fullPage.js#3272]
### Link to isolated reproduction with no external CSS / JS
Hello, I'm making a website [ http://ezpill.fstry.com/for-pharmacy/](url) using the Fullpage script and visual composer, I have a bug on the page, for some reason the screens are larger in size than they should be. But when you turn off the browser window everything becomes normal. There are no third-party styles that affect the height of the screen. What could be the problem?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
