### ISSUE TITLE
Resize Problem 

### ISSUE THREAD

**Issue by Nathalieworkid** [alvarotrigo/fullPage.js#3273]
Hello:)
I'm using fullPage.js for a webapp project and I have a problem with my screen orientation. At first I want to block the landscape mode, but it doesent work. So i decided to put an image on fullscreen, when the device is turn into landscape mode (the picture shows that you have to rotate your device in portrait mode). Now when i switsch from landscape mode to portrait the whole page is broken (all divs and images are cut of). 
So what should I do, that the page are still working when you change your screen orientation? 

Versions 
[Chrome, Samsung Galaxy A5 (2017), Version of fullPage.js 2.9.6]

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by Nathalieworkid** [comment]
I just comment the scrolloverflow.min.js out and the site work's fine at the mobile phone after switching the screen orientation, but the problem is now, that the scroll function doesen't work. But the resize problem is caused trough the scrolloverflow.min.js
I hope that this is enough 
http://workidtest.de/tee.oryoki.de/

**Comment by alvarotrigo** [comment]
> I hope that this is enough
> http://workidtest.de/tee.oryoki.de/

Sorry, I do not check personal sites here. 
Please create an isolated reproduction with no external CSS or JS to fullpage.js (unless a minimum is required) and use empty sections if possible.
More about isolated reproductions here:
https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/

**Comment by alvarotrigo** [comment]
Use this version of the scrolloverflow file:
https://github.com/alvarotrigo/fullPage.js/blob/2.9.7/vendors/scrolloverflow.js

Probably that will solve the issue you are facing. 

In any case, fullPage.js is now on version 3. It completely got rid of jQuery and it was completely rewritting. You might want to switch to it :)

**Comment by Nathalieworkid** [comment]
it seems to work now with the new version of scrolloverflow. Thank you :) :)

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! ;)
