### ISSUE TITLE
parallax extension fp_utils is not defined 

### ISSUE THREAD

**Issue by aaronsummers** [alvarotrigo/fullPage.js#3278]
I have recently purchased a copy of the parallax extension and am developing locally but can't get it to work.

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase. It seems you are rather using a parallax extension for fullpage.js v2, or you are using the v3 extension and using fullpage.js v3.
