### ISSUE TITLE
Slight anchor problem on responsive devices

### ISSUE THREAD

**Issue by Le-future** [alvarotrigo/fullPage.js#3279]
Hello mate,

Just found a small issue on Fullpage once the responsive is enabled.

When you're using the menu to scroll to for example, section 5, that works.

But, if you are on section 6 and you click on 5 to go back, the content is scrolled but only of 100vh as I can see.

The problem is, my sections have more content than 100vh height.

You can try with your demo here: https://alvarotrigo.com/fullPage/examples/responsive.html

if you add more content in section 2 for example or increase the height of it (more than 100vh), when you will reach section 3 and click to get back to 2, the page will scroll but not at the top of section 2.

Hope my issue is clear 😄 

Version 2.9.2

**Comment by Le-future** [comment]
Followed the trick here: https://github.com/alvarotrigo/fullPage.js/issues/1854

**Comment by alvarotrigo** [comment]
Yeah, in any case, Version 2.9.2 is no longer supported.
I only provide support for the latest version, which is at the moment 3.0.1. Which has been completely re-written to get rid of jQuery dependency.
