### ISSUE TITLE
version 3.0.1 fails in webpack 4

### ISSUE THREAD

**Issue by bazalab** [alvarotrigo/fullPage.js#3284]
### Description
webpack 4 compiles correctly, both in development and in production, but when running in chrome, the following error appears:
**Uncaught TypeError: Cannot set property 'fullpage' of undefined**
    at Object.eval (fullpage.js:19)
    at eval (fullpage.js:21)
    at Object.eval (fullpage.js:24)
    at eval (fullpage.js:3844)
    at Object../node_modules/fullpage.js/dist/fullpage.js (main.js:132)
    at __webpack_require__ (main.js:20)
    at Object.eval (index.js:9)
    at eval (index.js:36)
    at Object../src/index.js (main.js:430)
    at __webpack_require__ (main.js:20)

### Link to isolated reproduction with no external CSS / JS
the link to the compiled files is:
https://jsfiddle.net/jlazaro/djhxyn96/2/

### Steps to reproduce it
1. webpack.config.js
const HtmlWebPackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
var webpack = require("webpack");
......
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      },
.....
      {
        test: /\.js$/,
        exclude: / node_modules /,
        use: {
          loader: "babel-loader",
          query: {
            presets: ['es2015']
          }
        }
      },
    ]
  },

  plugins: [
    new HtmlWebPackPlugin({
      template: "src/index.html",
      filename: "./index.html"
    }),
    new MiniCssExtractPlugin({
      filename: "[name].css",
      chunkFilename: "[id].css"
    }),
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    })
  ]
};
2.index.js (pre-compiled)
import "fullpage.js/dist/fullpage.css";
import style from "./main.css";

window.$ = window.jQuery = require('jquery')
import 'fullpage.js/dist/fullpage.js';

$(document).ready(function() {
	$('#fullpage').fullpage ({
		sectionsColor: ['#000', '#000', '#b4ae88', '#ebe4b8', '#ebe4b8','#099798'],
		anchors: ['Inicio', 'Manifiesto', 'Caso1', 'Caso2', 'Caso3','Contacto'],
		menu: '#menu',
		scrollingSpeed: 1000,
		css3: true,
		lazyLoading: true,
        navigation: false,
        navigationPosition: 'right',
        slidesNavigation: false,
        slidesNavPosition: 'bottom',
        controlArrows: true,
        navigationTooltips: ['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],
        loopTop: true,
        loopBottom: true,
        fitToSection: true,
 
	});   

});
3. [and so on...]
the css file is a copy of your examples

The jquery, fullpage.js and fullpage.css files are loaded correctly

### Versions 
Ubuntu 16.04 LTS
Chrome Versión 67.0.3396.99 (Build oficial) (64 bits)

**Comment by alvarotrigo** [comment]
Have you tried asking in webpack forums? 
They'll probably understand what's going on much better.

**Comment by kukac7** [comment]
@bazalab [that's it!](https://codesandbox.io/s/q7p47wn224?module=%2Fsrc%2Findex.js)

**Comment by alvarotrigo** [comment]
@kukac7 it should work as expected when using jQuery as well.

**Comment by alvarotrigo** [comment]
I might be missing something on the [fullpage jQuery adapter](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L3846).

**Comment by alvarotrigo** [comment]
Seems to be some kind of webpack configuration thing. 
[It happened the same in version 2](https://github.com/alvarotrigo/fullPage.js/issues/2371) 

I'll close the issue as it seems to belong to webpack forums rather than to fullpage.js.

**Comment by daco** [comment]
For what it's worth, had the same issue with version 3.0.1. Reverted to 2.9.7. Now it does work like this:
```
import $ from 'jquery';
window.$ = window.jQuery = $;
import 'fullpage.js/dist/jquery.fullpage.extensions.min';
```

**Comment by alvarotrigo** [comment]
@daco can you explain what was the issue you were facing with v3 ? 
Perhaps if you show the error or your configuration we might be able to help?

**Comment by daco** [comment]
@alvarotrigo Exactly as reported by @bazalab :
`Uncaught TypeError: Cannot set property 'fullpage' of undefined`

**Comment by appcent** [comment]
that's work for me

```
import $ from 'jquery';
import '../node_modules/fullpage.js/vendors/scrolloverflow'
import fullpage from "fullpage.js";

$(document).ready(function() {

    new fullpage("#fullpage", {
        licenseKey: "OPEN-SOURCE-GPLV3-LICENSE",
        verticalCentered: true,
        scrollOverflow: true
    });

    fullpage_api.setAllowScrolling(true);

});
```
fullpage.js --> 3.0.2
webpack --> 3.0.0
