### ISSUE TITLE
Fullpage is not defined

### ISSUE THREAD

**Issue by julian-ca** [alvarotrigo/fullPage.js#3285]
### Description
fullpage is not defined.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/xpvt214o/341618/

### Steps to reproduce it
1. Include jQuery v1.9.1
2. Include fullpage.js v3.0.1
3. instantiate fullpage constructor (`new fullpage()`)

**Comment by alvarotrigo** [comment]
> Include fullpage.js v3.0.1

You are including the 2.9.7 version.

**Comment by kukac7** [comment]
@julian-ca https://jsfiddle.net/6ovy52bs/5/

**Comment by alvarotrigo** [comment]
@kukac7 thanks for that ;)

**Comment by julian-ca** [comment]
But is there some reason why this is an issue in 2.9.7?

**Comment by kukac7** [comment]
@julian-ca because you are wrong to call fullpage.js.

```
try {
	$('#fullpage').fullpage();
 
} catch(e){
 $('body').html(e.message);
}
```

**Comment by alvarotrigo** [comment]
> But is there some reason why this is an issue in 2.9.7?

Sure.
Because 2.9.7 requires jQuery and uses another API.
You won't see the code `new fullpage` anywhere in [the 2.9.7 documentation](https://github.com/alvarotrigo/fullPage.js/tree/2.9.7)
