### ISSUE TITLE
Autoplay video on chrome mobile

### ISSUE THREAD

**Issue by kristoffernolgren** [alvarotrigo/fullPage.js#3287]
### Description
When I run fullpage.js, it stops any video that is running, I can solve this for desktop with javascript:
```
		afterRender: function(){
			$('#bg-video')[0].play();
		}
```

 but for mobile, no video is shown at all and I get this error: 

Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

Basically google won't let me autoplay video with js and fullpage.js won't let me autoplay with the html-element, any suggestions?

### Versions 
[Browser, operating system, device, ...]
Chrome for Android, M66 Stable+

**Comment by alvarotrigo** [comment]
Use the [lazy load option fullpage.js provides](https://github.com/alvarotrigo/fullPage.js#lazy-loading)

Note Chrome will probably not allow autoplay unless the video is muted according to their new policy:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by kristoffernolgren** [comment]
thanks! This seems to allow the videos to be rendered, but not playing. This is my video-element:

	<video data-autoplay id="zynapp-bg-video" class="zynapp-bg-video" autoplay loop muted playsinline>
		<source data-src="/assets/video/vid-01.webm" type="video/webm">
		<source data-src="/assets/video/vid-01.mp4" type="video/mp4">
	</video>

**Comment by alvarotrigo** [comment]
> here is the code in action: https://zynapp.com/markup/

I only check non isolated sites if you got a license with premium support. 

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by kristoffernolgren** [comment]
Sorry about that, here is a  updated version with the latest fullpage.js,  https://jsfiddle.net/h6zkv4g2/2/show

If you run this in chrome on mobile, you get the following error and no video: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

I also tried using the proposed $('#bg-video')[0].play();, without the same result: https://jsfiddle.net/h6zkv4g2/

FYI, I recently bought licenses for fullpage.js, just didn't put the keys in the demo.
