### ISSUE TITLE
Autoplay video on chrome mobile with simple sample

### ISSUE THREAD

**Issue by kristoffernolgren** [alvarotrigo/fullPage.js#3290]
### Description
I can't get autoplay to work in chrome for mobile.

I get the following error and no video: Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

https://jsfiddle.net/h6zkv4g2/2/

I also tried using the proposed $('#bg-video')[0].play();, with the same result: https://jsfiddle.net/h6zkv4g2/

### Steps to reproduce it
1. Visit site on Desktop, see video playing
2. Use android and chrome to visit site,
3. don't see video playing and observe the error message

### Versions 
Chrome 67.
Operating system Android 8.1.0
Details: https://whatsmybrowser.org/b/AVBE7BF

FYI, I recently bought licenses for fullpage.js, just didn't put the keys in the demo.

**Comment by alvarotrigo** [comment]
I can't see the console error you are talking about in the jsfiddle your provided: https://jsfiddle.net/h6zkv4g2/2/

**Comment by alvarotrigo** [comment]
Your phone might be caching some files and not getting the latest version. 
Try in an incognito window. 

I'll close the issue so far, as there's no reproduction available.
