### ISSUE TITLE
scrollOverflow snap

### ISSUE THREAD

**Issue by yanickvanbarneveld** [alvarotrigo/fullPage.js#3291]
### Description
When I reach the bottom of the second section and I scroll down to quickly it goes to the next section using a mouse. Unfortunately touchSensitivity is not working for this, is there an other fix for this? I want that you have to scroll more down before it snaps to the other section?

Also, at the second section I am not able to copy the text. Instead at drags the content down or up. Is there a fix to fix this?

### Link to isolated reproduction with no external CSS / JS
https://goo.gl/LWjLQh --> Website
https://pastebin.com/gKRPbZvY --> JavaScript

### Versions 
Fullpage version 2.9.7

**Comment by alvarotrigo** [comment]
Duplicated of the open issue https://github.com/alvarotrigo/fullPage.js/issues/941
