### ISSUE TITLE
How can we add a judgement before fullpage changes?

### ISSUE THREAD

**Issue by Kole6** [alvarotrigo/fullPage.js#3292]
How can we add a judgement before fullpage changes?

Because sometimes I don't need fullpage to scroll up.

**Comment by alvarotrigo** [comment]
Read the docs regarding [Cancelling the scroll before it takes place](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place).

Also read about the function `setAllowScrolling(false)`.

**Comment by Kole6** [comment]
Thanks very much！
