### ISSUE TITLE
With CSS3: false section aren't moving anymore

### ISSUE THREAD

**Issue by plusklang** [alvarotrigo/fullPage.js#3293]
Everything was working fine until I needed fixed background images which only works with css3: false. As soon as I set this option the sections weren't moving anymore and I could scroll as much as I like without only effect. 

I inspected the code in the browser and saw that the fullPage container is moving but only by like 0.014px:
`<div class="fullPageContainer contentContainer fullpage-wrapper" id="fullpage" style="height: 100%; position: relative; top: -0.01493233819241978px;">`

So it seems like sth. is being calculated wrong. Also the site header which was marked as a fixed element disappeared.

Here's the relevant code:
http://jsfiddle.net/mnL8u14x/20/

### Versions 
[Browser: Safari, Chrome on macOS]

**Comment by alvarotrigo** [comment]
Your jsfiddle is non functional. Please add the required css and js files and make it functional.

**Comment by plusklang** [comment]
http://jsfiddle.net/mnL8u14x/28/ 
Sry I don't exactly know what to add. Its a wordpress project so I can't just copy all the html which is including the wordpress php code. So I put a simplified version in jsfiddle. If you could tell me what code you need I could add it. Thanks for your help!

**Comment by alvarotrigo** [comment]
> Sry I don't exactly know what to add.

I would then recommend you to find some tutorial on how to use jsfiddle or codepen.

>  Its a wordpress project so I can't just copy all the html which is including the wordpress php code.

I assume you got the [developer license](https://alvarotrigo.com/fullPage/pricing/) right? I only provide premium support for people who purchased the Organization license, in which case, I would be able to check your URL. 
Otherwise, I also provide fullPage.js support packages you can acquire for a 1 hour consulting service. Let me know if you are interested.

**Comment by plusklang** [comment]
Ok I just found another way how to have a fixed background image for all section with the css3 option turned on. I added a container with the background image, set position: fixed, set it as fixed element in the fullPage plugin, set the width and height on 100% of the viewport and z-index on -1.  
Not the cleanest way but does its job.

**Comment by alvarotrigo** [comment]
Glad you solved it.
