### ISSUE TITLE
 Anchor tag issue

### ISSUE THREAD

**Issue by arunims** [alvarotrigo/fullPage.js#3294]
### Anchor tag issue

My Anchor tag links are not working. Here I am mentioning the code.

For example this my navigation.

<div id="fullpage">
        <div class="section">
            <a href="#item-section1" class="item-link">Item1</a>
             <a href="#item-section2" class="item-link">Item2</a>

             <section class="content-sec" >
              <div class="container">
                    <div class="each-tem content-wrap" data-anchor="item-section1">Item1 desc</div>
                     <div class="each-tem content-wrap" data-anchor="item-section2">Item2 desc</div>
              </div>
             </section>

         </div>

</div>

in my js

 $('#fullpage').fullpage({
   anchors: ['item-section1', 'item-section2'],
        scrollOverflow : true,

Please help me

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by arunims** [comment]
Thanks for your reply 
Is it possible to add an anchor tag #item-section1 within a section div? Not using data-anchor

**Comment by alvarotrigo** [comment]
No

**Comment by arunims** [comment]
I have lots of subsections in a section div .  I have to link each section using an anchor tag ( like Normall #div Id) 
![image](https://user-images.githubusercontent.com/39903843/42318925-1ee05abe-806e-11e8-9fd4-77457a1e3169.png)

How can do this?

**Comment by arunims** [comment]
While I am clicking on the link it will be going to the particular div section. but the scroll up is not working

**Comment by arunims** [comment]
Can you please help me

**Comment by alvarotrigo** [comment]
Sorry, I only provide support for isolated issues.
If you need my consulting services you can acquire the Support Package with an hourly rate. [Contact me](https://alvarotrigo.com/#contact) if interested.
