### ISSUE TITLE
Remove anchor dot(s) for specific sections

### ISSUE THREAD

**Issue by elliottmangham** [alvarotrigo/fullPage.js#3295]
Hello,

I have several sections on a page, all working with fullPage. I also have the `fp-auto-height` class on my last section, which is the footer.

The issue is that I cannot find how to stop the last section (the footer) from having an anchor dot from being displayed, despite excluding the last one from my `anchors: ['one', 'two'...]` in my jQuery configuration.

I understand that I can do this with CSS, but ideally, I must remove the last `<li>` in the markup, as it greatly affects my unique styling.

Is there a simple class or other solution that I can apply to the last section, to prevent a dot being associated with it?

**Comment by alvarotrigo** [comment]
Yeah fullpage.js doesn't provide any way to do so. 
You should better fix it using CSS. It is quite straight forward.

**Comment by elliott-impression** [comment]
Hi @alvarotrigo, thanks for your response. I wanted to avoid CSS due to some specifics on the site which will make it difficult - but will look into it further!
>  I understand that I can do this with CSS, but ideally, I must remove the last <li> in the markup, as it greatly affects my unique styling.

Maybe a feature request ^

Thanks,

**Comment by alvarotrigo** [comment]
>  I wanted to avoid CSS due to some specifics on the site which will make it difficult

Perhaps if you elaborate your issues using CSS maybe we can find other solution?

**Comment by alvarotrigo** [comment]
Glad you managed to solve it!
