### ISSUE TITLE
Input tabulation not working

### ISSUE THREAD

**Issue by FlawaCLV** [alvarotrigo/fullPage.js#3296]
## Expected Behavior
When editing a input field I should be able to press Tab to focus on the next input.

## Current Behavior
Currently the Tab is stuck on the first input field. I you select the second one and press Tab it focuses on the first input instead of the following one.

## Steps to Reproduce
Here is a sandbox that shows the bug : https://codesandbox.io/s/mmrrjmyz28

## Environment

| Tech         | Version |
|--------------|---------|
| React        | v16.3.2 |
| Fullpage.js  | v3.0.1  |
| browser      | Chrome v67.0.* |

**Comment by marekmaurizio** [comment]
Same huge problem.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!! 
I'll take a look at it whenever I have some time!

**Comment by alvarotrigo** [comment]
This has been introduced in 3.0.1
Meanwhile, if you want, you can revert to 2.9.7 that requieres jQuery.

**Comment by marekmaurizio** [comment]
I solved by adding this
```if (activeElement.parents('.fullpage-wrapper').length == 0) return;```

in the onTab function. Shoud this be the default or at least an option?

**Comment by alvarotrigo** [comment]
I'll check whenever I have some time.

**Comment by FlawaCLV** [comment]
@alvarotrigo when is the next release scheduled approx ?

**Comment by alvarotrigo** [comment]
@FlawaCLV probably end of this week or beginning of the next.

**Comment by FlawaCLV** [comment]
@alvarotrigo great, thanks!

**Comment by julian-ca** [comment]
Confirmed fixed on dev. I hope this will be released as soon as possible.

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
