### ISSUE TITLE
normalScrollElements not working correct on scroll

### ISSUE THREAD

**Issue by denisdemut-fb** [alvarotrigo/fullPage.js#3297]
### Description
When you have options:
```
normalScrollElements: '.active-scroll',
scrollOverflow: true
```
and when you will scroll screens - you will see page where you have block with .active-scroll and it will redirect you to the next screen.

### Steps to reproduce it
1. Set options:
```css3: true,
autoScrolling: true,
fadingEffect: true,
normalScrollElements: '.active-scroll',
scrollOverflow: true
```
2. Have three screens
```anchors: ['first', 'second', 'third'],```
3. Add on Second screen two blocks (half of screen will have class .active-scroll and will have a lot of content)
4. Scroll on first screen and mouse must be in area where on the second screen you have .active scroll
5. So you will see that it will show second screen just for a moment and redirect to the third screen 

### Versions 
Chrome, MacOS

**Comment by alvarotrigo** [comment]
> Add on Second screen two blocks (half of screen will have class .active-scroll and will have a lot of content)

Scrolloverflow will create single scrollbar for the whole section that is overflowing. 
In your case, it seems both blocks of half screen each will have a lot of content and that you want to use a scroll bar for each of the blocks.

If that's the case, you should NOT be using scrollOverflow. 
Use only normalScroll elements and then use the CSS `overflow: scroll` for your blocks.

**Comment by denisdemut-fb** [comment]
I changed code to that variant, but still have the same issue

**Comment by denisdemut-fb** [comment]
Take a look [here](https://jsfiddle.net/xdm690he/28/). But when I added to the jsfiddle the same versions of the library (3.0.0) have error "fullpage is not a constructor"

**Comment by alvarotrigo** [comment]
Yours is a CSS issue and it is not related with fullpage.js
See your fiddle here:
https://jsfiddle.net/xdm690he/33/

I can't see any scroll bar in the right block. If you manage to create the scroll bar, then scrollElements will work just fine.

I'll close the issue.
