### ISSUE TITLE
data-anchor doesn't work

### ISSUE THREAD

**Issue by rjduran** [alvarotrigo/fullPage.js#3299]
### Description

Something changed between v 2.9.7 and v 3.0.1 such that a data-anchor attribute no longer works for a vertical nav menu (dots on left or right sides). 

The instructions [here](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides) are either out of date or something is broken in the updated library. 

### Link to isolated reproduction with no external CSS / JS
Issue: [jsfiddle](http://jsfiddle.net/y60x7hmL/3/). I used the example "examples/navigation-vertical.html" to demonstrate the issue. 

### Steps to reproduce it
1. Comment out anchor option in the js. 
2. Add a data-anchor attribute to each section in the html.
3. Give each data-anchor a value matching what was in the anchors array. 
4. Try to click on the nav dots. They don't have anchors that match the data-anchor of each section. Upon inspection they are all set to '#'. Scrolling seems to work fine but the anchors are broken. 

### Versions 
MacOS, Chrome,

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
