### ISSUE TITLE
ResponsiveSlides not working

### ISSUE THREAD

**Issue by cmediai** [alvarotrigo/fullPage.js#3300]
Hi, I just purchased ResponsiveSlides but I can't seem to make it work. Either the entire plugin stops working (without any JS errors) or I get this error:

Uncaught ReferenceError: fp_utils is not defined
    at new window.fp_responsiveSlidesExtension (jquery.fullpage.responsiveSlides.min.js:8)
    at an (jquery.fullpage.extensions.min.js:8)
    at a.fn.init.e.fn.fullpage (jquery.fullpage.extensions.min.js:8)
    at HTMLDocument.<anonymous> ((index):508)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

Here's my code:

<script src="/js/jquery.fullpage.responsiveSlides.min.js"></script>
<link href="/js/jquery.fullpage.min.css" type="text/css" rel="stylesheet">
<script src="/js/jquery.fullpage.extensions.min.js"></script>

jQuery(document).ready(function() {
   jQuery('.fullpage').fullpage ({
        v2compatible: true,
	anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'lastPage'],
	licenseKey: "OPEN-SOURCE-GPLV3-LICENSE",
	responsiveSlidesKey: '#',
	responsiveSlides: true,
    });

});

**Comment by cmediai** [comment]
Is there a list of previous extension versions that I could try?

**Comment by alvarotrigo** [comment]
You should use the latest fullpage.js version, version 3.
You are using version 2. 

Verion 3 won't require jQuery, therefore the file name won't contain the prefix `jquery` like `jquery.fullpage.extensions.min.js`.

Use the latest version of it: [fullpage.extensions.min.js](https://github.com/alvarotrigo/fullPage.js/blob/master/dist/fullpage.extensions.min.js)

> Is there a list of previous extension versions that I could try?

Nop. Version 2 is not maintained anymore and extensions are only provided for version 3.
