### ISSUE TITLE
Trying to install under OPEN-SOURCE-GPLV3-LICENSE but keep getting error

### ISSUE THREAD

**Issue by kiaramelissa** [alvarotrigo/fullPage.js#3301]
I am trying to use Fullpage.js under the OPEN-SOURCE-GPLV3-LICENSE and am not sure I am using the key correctly?

I have the added the following code before the close body tag:

```
<script>
$(document).ready(function() {
	$('#fullpage').fullpage({
		autoScrolling:false,
		scrollHorizontally: true,
		licenseKey: OPEN-SOURCE-GPLV3-LICENSE
	});

	//methods
	$.fn.fullpage.setAllowScrolling(false);
});
</script>
```

The error I keep getting is:

Uncaught ReferenceError: OPEN is not defined
    at HTMLDocument.<anonymous> ((index):435)
    at i (jquery.min.js?ver=2.2.4:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=2.2.4:2)
    at Function.ready (jquery.min.js?ver=2.2.4:2)
    at HTMLDocument.J (jquery.min.js?ver=2.2.4:2)

How do i fix this?

Any help would be appreciated!

**Comment by alvarotrigo** [comment]
First of all, are you sure your project is open sourced and compatible with GPLv3?
Do you have a repository or any place where people can view and download the whole source code of your project? Included back-end if there's any?

Is it stated somewhere on your code that it is open sourced and the URL where they can access to it?

**Comment by kiaramelissa** [comment]
Ah i see! No it doesnt yet!
