### ISSUE TITLE
parallax extension not work 

### ISSUE THREAD

**Issue by duongtrunga** [alvarotrigo/fullPage.js#3304]
### 

<script type="text/javascript" src="dist/fullpage.parallax.min.js"></script>
    <script type="text/javascript" src="dist/fullpage.extensions.min.js"></script>

<script type="text/javascript">
      var a = "<?php echo of_get_option('n-ss-1'); ?>";
      var b = "<?php echo of_get_option('n-ss-2'); ?>";
      var c = "<?php echo of_get_option('n-ss-3'); ?>";
      var d = "<?php echo of_get_option('n-ss-4'); ?>";
      var e = "<?php echo of_get_option('n-ss-5'); ?>";

    var myFullpage = new fullpage('#fullpage', {
     
      parallaxKey: 'Y3J5c3RhbGJheXZpZXRuYW0uY29tX1MyV2NHRnlZV3hznPTNuTw==',
      parallaxOptions: {type: 'cover', percentage: 100, property: 'translate'},
      parallax:true,
      scrollBar:false,
        autoScrolling:true,

      anchors:['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],
        navigation: true,
        navigationPosition: 'right',
        navigationTooltips: [a, b, c, d, e],
      showActiveTooltip: true,

    });

</script>

### Steps to reproduce it
it not work. can u help me?

### Versions 
fullpage.js 3.0.1

**Comment by alvarotrigo** [comment]
Sure!
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase.

**Comment by alvarotrigo** [comment]
> I also cannot get the paid extension to work, and have emailed you

@DoubleMarv answered.
