### ISSUE TITLE
paddingTop issue when scrolling back up

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3305]
The problem I am having is mainly with the fixed header and scrolling back up to the website.
The fixed header is as follows:

`header { position: fixed; top: 0; z-index: 99; background: black; width: 100%; }`
I am using some padding top to create the space at the top of the sections:
`.section { padding-top: 100px; }`

Everything seems to work fine as expected, however when I scroll down the site and then scroll back up the "padding-top: 100px" seems to sit behind the fixed header? It only happens on the first section.

Versions
[Firefox 60.0.2, macOS Sieera, MacBook Pro (Retina, 13-inch, Early 2015)]

I have created a repoduction:
https://codepen.io/AmanSahota/pen/XYoYrv

Please let me know if this is ok?

**Comment by alvarotrigo** [comment]
Try applying the padding in a wrapper inside the section, not in the section itself.

**Comment by AmanSahota** [comment]
Hey, this worked.. I am not getting that issue any longer 👍
