### ISSUE TITLE
ToolTip Position not correct

### ISSUE THREAD

**Issue by ReneHetzel** [alvarotrigo/fullPage.js#3306]
### Description
Tooltip position in case of vertical nav, in my case on the right, is not correct. 

### Link to isolated reproduction with no external CSS / JS
You can test it on your own page :) 
https://alvarotrigo.com/fullPage/

### Steps to reproduce it
-

### Versions 
Google Chrome, Firefox (Windows 10)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll take a look at it!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch! Will get merged in the next release.

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
