### ISSUE TITLE
Scroll-horizontally [Extension]

### ISSUE THREAD

**Issue by khookeiwai** [alvarotrigo/fullPage.js#3307]
Hi, I'm using this extension and would like to ask how do I create a navigation with fit with vertical and horizontal scroll?

![123](https://user-images.githubusercontent.com/30516072/42564325-0c474132-8533-11e8-9229-ac6e2322ff78.jpg)

Here is the demo link: https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html

Currently the navigation dot separate by section with slide, is it possible to merge all of them together become one navigation?

**Comment by alvarotrigo** [comment]
> Currently the navigation dot separate by section with slide, is it possible to merge all of them together become one navigation?


This is not a feature provided by fullpage.js, but many things are possible with the right knowledge! 
This is one of them. 

Just create your own navigation. Then by using [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) you can activate or deactivate the bullets you wish. 

Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
