### ISSUE TITLE
Is there any possibilities to set active section?

### ISSUE THREAD

**Issue by forethoughtde** [alvarotrigo/fullPage.js#3308]
#question

I would like to know if there is any method to set active section?

I see in the documentation that there is a method to get active section but I did not see any methods to set active section than moveTo method which in turn moves the screen to given section.

**Comment by alvarotrigo** [comment]
Why would you want to set a section as active if it is not on the viewport?

Anyways, just add the `active` class to it.

**Comment by forethoughtde** [comment]
I actually destroy and recreate fullpage.js wheneven **window resize** event triggered. When the user is in the section 3 and tries to resize the window what happens is fullpage.js destroys and keeps the active section somewhere which basically destorys the layout. 

To over come that, I have use the following code in resize event function

```
$.fn.fullpage.moveTo(1); // Go to first section
$.fn.fullpage.destroy('all'); // destroy
$fullPage.fullpage(this.fullPageOptions); // initialize
```

**Comment by alvarotrigo** [comment]
See my answer [here](https://stackoverflow.com/a/36643702/1081396).
