### ISSUE TITLE
error ocourse by using nav dots

### ISSUE THREAD

**Issue by ReneHetzel** [alvarotrigo/fullPage.js#3309]
### Description
Hi found another problem by using the anchors.
When i use/click the navigation dots very often i got this error in console: 

```
fullpage.js:3656 Uncaught TypeError: Cannot read property 'preventDefault' of undefined
    at we (fullpage.js:3656)
    at HTMLAnchorElement.un (fullpage.js:2117)
    at HTMLDocument.<anonymous> (fullpage.js:638
)
```
### Link to isolated reproduction with no external CSS / JS
i modify the jsfiddle from the issue #3299
http://jsfiddle.net/ReneHetzel/Lb571vh6/1/

### Versions 
Google Chrome, Windows 10

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll take a look at it!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch!
It will get merged in the next release!

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
