### ISSUE TITLE
Pause CSS animation keyframes until section comes in viewport

### ISSUE THREAD

**Issue by Akaaal** [alvarotrigo/fullPage.js#3310]
Hi, thank for your plugin, works great here ;)
As mentionned in the title, I'm trying to delay a little CSS animation I've created inside a section. I'm using Jquery to addclass that contain the animation effect added to a div when the section is in the viewport. The addclass works but not the viewport detection. The animation starts when the site loads. 
I was wondering maybe there is already a super feature packed in your plugin that I could use ? or maybe some advices to help me achieve my goal ? 
https://www5.gatcom.fr/ (slide 3 "CREATION" the 3 white shapes)
Thanks for reading
Akal

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by Akaaal** [comment]
Thank you for fast answer I'll check it out ;)
++
Akal
