### ISSUE TITLE
'scrolling in sections' example broken...

### ISSUE THREAD

**Issue by MattAppleton** [alvarotrigo/fullPage.js#3311]
### Steps to reproduce it
look a this page in the fullpage examples
https://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage

the first page wont scroll up / down, just uses regular fullpage  behaviour between sections. Same with the second slide example https://alvarotrigo.com/fullPage/examples/scrolling.html#secondPage/2

### Versions 
OSX on Safari 11.1.1 + Chrome 67 on two different iMacs

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I've introduced it a couple of hours ago :)
Fixed!
