### ISSUE TITLE
"Cannot read property 'preventDefault' of undefined" when touching navigation dots on mobile

### ISSUE THREAD

**Issue by RatserX** [alvarotrigo/fullPage.js#3312]
### Description
As the title says, the navigation dots are not working properly when used on mobile. Also, this error results in a weird behavior when scrolling afterwards, whereas the touched dot remains selected even when scrolling to other sections. This even happens on the main fullPage.js page.

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/#page1

### Steps to reproduce it
1. Navigate to page using fullPage.js on mobile
2. Click on navigation dot
3. Scroll up or down

### Versions 
_Browser_: Google Chrome, Safari
_OS_: Windows 10, Android, iOS
_Device_: PC, Samsung Galaxy S9+, iPhone X

**Comment by RatserX** [comment]
Closing. Found dupe https://github.com/alvarotrigo/fullPage.js/issues/3309.

**Comment by alvarotrigo** [comment]
I've just solved it on the dev branch. 
You can use [the files from there](https://github.com/alvarotrigo/fullPage.js/tree/dev/dist) until I merge it into a new release.
