### ISSUE TITLE
onLeave firing multiple times with manual setTimeout moveTo

### ISSUE THREAD

**Issue by thetimcook** [alvarotrigo/fullPage.js#3313]
I am manually moving sections like you have demonstrated [here](https://stackoverflow.com/questions/36176677/fullpage-js-adding-a-scroll-delay/36182162#36182162), but for some reason onLeave is being called multiple times. I’ve searched for this issue but couldn’t find anyone with the same problem.

I’ve created a [codepen demonstrating the issue](https://codepen.io/thetimcook/pen/MBaQLd) I’m having and didn’t know if you could look and it and tell me what I’m doing wrong. I have it logging to the console “onLeave” each time onLeave is called, and for some reason it’s being called every single time my mouse scrolls and not once per scroll action. This is resulting in the timeout function starting after the scrolling stops and not when the scrolling initiates. For example, instead of the section moving in 1 second, it moves 1 second after scrolling stops.

I don't know how to use the scroll horizontally plugin on codepen but for some reason this issue in not happening with the onSlideLeave function.

Thanks for the help!

**Comment by thetimcook** [comment]
Okay I feel pretty stupid but I have a simple solution if people are having the same issue. 

Just setting a variable to make sure onLeave is only called once works perfect. 

var runOnce = true;

Then check to see if it's true and in that toggle it to false. Then in the afterLoad funciton set that back to true.

**Comment by alvarotrigo** [comment]
Yeap, glad you solved it!
