### ISSUE TITLE
My website on Chrome Mobile appears overflowed

### ISSUE THREAD

**Issue by leotinoco** [alvarotrigo/fullPage.js#3314]
I have this website that I am finishing. But I have the disadvantage that in the mobile version overflows when I use the Google Chrome browser, in Mozilla Firefox it appears correctly.

This is the test website: http://ideas24-7.com/prueba/

In the tests in my development program looks good, but when I access from the mobile using Chrome appears a little higher.

I have verified that the containers do not overflow and removed the padding and the upper and lower margin, but it still continues.

Can I do something to make that section fit on a single page?

What could I do to correct this error?

I attach the images on the same cell phone, MotoG2 from Chrome v.67 and Firefox v.61

![google_chrome](https://user-images.githubusercontent.com/22717176/42788009-b179380c-8922-11e8-937c-63ea2e0d85b9.png)
![mozilla_firefox](https://user-images.githubusercontent.com/22717176/42788010-b198dd4c-8922-11e8-89e3-2d4a5bc9665f.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
