### ISSUE TITLE
Auto height section

### ISSUE THREAD

**Issue by mahmoud-HB** [alvarotrigo/fullPage.js#3318]
Hello, 

I use your plugin recently and I thank you because it works very well.
my question that I have a section with auto height but when I click on a button I display other information longer than the section, so I can not scroll down to display the rest of content (it is my last section). 

Thank you for giving me a track so that I can solve this problem.

Version: fullPage 2.9.7

in the last section, you have to click in "Les accessoires".

[http://jsfiddle.net/6SQhb/794/](http://jsfiddle.net/6SQhb/794/)

with  fp-auto-section : 

[http://jsfiddle.net/6SQhb/796/](http://jsfiddle.net/6SQhb/796/)

**Comment by alvarotrigo** [comment]
> Version: fullPage 2.9.7

I only provide support to the latest version. At this moment 3.0.1.

In any case, the most you can do is use scrollOverflow:true and call the reBuild method after the content changes.

See your updated fiddle here:
http://jsfiddle.net/6SQhb/800/

**Comment by mahmoud-HB** [comment]
Perfect :) 💯 
Thanks u  👍
