### ISSUE TITLE
Navigation Dot Not Working, Data Anchor Problem, Jumping Indefinitely Problems

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#3320]
Hi Alvaro,

I would like to report 3 bugs:
1. Navigation dots are not working when no anchors are given.
2. You have reported data-anchor is fixed on dev but I think it's still not working on dev.
3. Jumping infinitely when anchors are set empty and last row is auto height. If auto height is not given, it jumps to the top and goes to the end one time.

Codepen:
https://codepen.io/anon/pen/BPLrGw/
I think dev js is used.

How to reproduce:
1. Click on right nav dots, the last one is not working.
2. Comment anchors parameter. data-anchor is set but it's still not shown. Nav dots do not show the link.
3. (Add anchors parameter back)Scroll to the end, it will jump infinitely.

Thank you,

**Comment by alvarotrigo** [comment]
Thanks for reporting them!! 

> Navigation dots are not working when no anchors are given.

I've just fixed on dev! 

> You have reported data-anchor is fixed on dev but I think it's still not working on dev.

Could you elaborate this? Provide an isolated reproduction? 

> Jumping infinitely when anchors are set empty and last row is auto height. If auto height is not given, it jumps to the top and goes to the end one time.

Anchors should never be set empty.

**Comment by alvarotrigo** [comment]
> For the first row, data anchor is set but on the navigation dots, the first one has # link only, instead of #s1.

The anchor tag is not set up correctly. You are using `data-anchor-` instead of `data-anchor=`

**Comment by meceware** [comment]
Aha, you are right mate :)

I would like to ask, is there a reason why anchors cannot be empty?

**Comment by alvarotrigo** [comment]
> I would like to ask, is there a reason why anchors cannot be empty?

The question is: why would you want to make use of empty anchors? 

Anchors are there for a reason.

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
