### ISSUE TITLE
How to autoplay slide on javascript

### ISSUE THREAD

**Issue by jacksondaizen** [alvarotrigo/fullPage.js#3321]
I just used javascript, not jquery. i study "https://www.youtube.com/watch?v=MhZP1AzrVrs", but it's for jquery,
please help me how to work on javascript.

my code:

    var myFullpage = new fullpage('#fullpage', {
        anchors: ['page1', 'page2', 'page3','page4'],
        sectionsColor: ['#C63D0F', '#1BBC9B', '#7E8F7C','#CCCCCC'],
        navigation: true,
        navigationPosition: 'left',
        responsiveWidth: 900,
        afterRender: function(){
        	setTimeout(function() {
        		moveSectionDown();
        	},1500);
        }
    });

**Comment by alvarotrigo** [comment]
If you check the docs you'll see the proper way of calling a method is:

```javascript
fullpage_api.moveSectionDown();
```
