### ISSUE TITLE
How to disable loop on only one horisontal slider?

### ISSUE THREAD

**Issue by zevilz** [alvarotrigo/fullPage.js#3322]
How to disable loop on only one horisontal slider?

**Comment by alvarotrigo** [comment]
This option (`getFullpageData`) is not documented, but you can do this:

```javascript
new fullpage('#fullpage', {
    onLeave: function(origin, destination, direction) {
        fullpage_api.getFullpageData.loopHorizontal = destination.index != 1;
    }
});
```

[See the reproduction online](https://jsfiddle.net/1kyuL4em/102/)

**Comment by zevilz** [comment]
Thanks, it working fine!
