### ISSUE TITLE
The fullPage.js Atom skip the second section without an apparent cause

### ISSUE THREAD

**Issue by Fritz-RT** [alvarotrigo/fullPage.js#3325]
### I have a little problem on a rockettheme with gantry5 website that uses the atom alvarotrigo / fullPage.js (Gantry5 Particle).
I activated this atom on an outline divided into sections, following the published instructions for use. Everything works perfectly, however, starting from the top video (first section) by making a few shots with the scrollbar wheel, the section under the video (section 2) is skipped and the fullPage atom brings me to the third section. Yet the atom finds the second section by scrolling upwards.
I tried to change several variables of the jquery.fullpage.js file without getting any changes. I can't figure out how to force the atom to stop correctly at the second section (of the rooms). Can someone give me some suggestions?

### Steps to reproduce it
1. Open the home page (youtube video - section 1)
2. scroll down the mouse wheel until the js leads to section 3
3. go back (scroll up the mouse wheel) to leads to the upper section (section 2)

### Versions 
Browsers: Chrome Vers. 67.0.3396.99 (Official Build 32 bit), Firefox Quantum 61.0.1 (32 bit).
Client OS: Windows7 Ultimate SP1
Webserver: Apache, PHP 7.0.30, MySQL 5.5.56-MariaDB
CMS: Joomla! 3.8.10 Stable with Gantry5, Rockettheme Template

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Also check [my blog post](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/) regarding how to ask coding questions and isolate your issue.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
