### ISSUE TITLE
Section Selector Addition Issue

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#3326]
Hi Alvaro,

First of all, thank you for the great work!

When there is more than one selector in sectionSelector parameter, it doesn't work. I think it's because you are adding data tags directly to the selector in setOptionsFromDom. There might be other places for it.

Check out the code:
https://codepen.io/anon/pen/XBMmWR

Thank you,

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll take a look at it!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch! To be merged in the next release!

**Comment by alvarotrigo** [comment]
Fixed now in fullpage.js 3.0.2
