### ISSUE TITLE
Auto moveSlideRight is not working for me

### ISSUE THREAD

**Issue by dwsiddall** [alvarotrigo/fullPage.js#3327]
### Description
I have read the many posts about wanting an automatic slider.  I have seen the code.  I have copied and pasted the code.  And yet, the slides just sit there.  They can be advanced manually with the arrows, but I cannot get them to advance automatically.

For clarification, I am not talking about sections, I am talking about slides.  What I want is for section1 to have three or four slides that scroll automatically, just like many 3rd party sliders do.  Then I want section2 and section3 to be regular pages without slides.

I have tried integrating a third party slider into fullpage, but when the slider advances to the next slide, it also triggers fullpage to advance to the next section as well.  There must be some duplicate code that causes this.

BTW, the template I am starting with is 'active-slide.html'

Any help is appreciated.

### Code
```javascript
<script>
    $(document).ready(function () {
    $('#fullpage').fullpage({
    sectionsColor: ['#1bbc9b', '#4BBFC3'],
    loopBottom: true,

    afterRender: function () {
    setInterval(function () {
    $.fn.fullpage.moveSlideRight();
    }, 500);
    }
    });
    });
   </script>
```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/2) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by dwsiddall** [comment]
Thank you for the quick reply.  The code is included in the original message.  I will try jsfiddle, although I really don't know how to use it.

I apologize..   

https://jsfiddle.net/kofq82hu/3/

**Comment by alvarotrigo** [comment]
You have to provide a working reproduction, where fullPage.js is initialised. 
If you don't know how to use jsfiddle or codepen, please look for some tutorial online.

**Comment by alvarotrigo** [comment]
You can also provide the reproduction on your own host, but make sure it is isolated, remove all unnecessary code, including HTML.

**Comment by dwsiddall** [comment]
Until I figure out jsfiddle,  can you just answer why some scripts for fullpage begin with:

var myFullpage

and others start with:

$(document).ready(function () {
    $('#fullpage').fullpage({

The script asection of the template I am working with starts with "var" and yet all of the solutions for the autoplay start with $(document).ready...etc.   

Is the code provided supposed to replace the script that runs fullpage or be in addition to the existing script?

Perhaps the answer to these will be a push in the right direction.

Thank you!

**Comment by alvarotrigo** [comment]
The var assignment is irrelevant.

The start by document.ready depends on whether you use jQuery and place the script on the head, or just after the closing body.
If placed before the closing body you won't need the document ready check.

**Comment by alvarotrigo** [comment]
Version 3 has removed the need of jQuery. That's why also it has a few changes in the API. 
You can read all about it on the docs and check the examples available in the examples folder.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
