### ISSUE TITLE
fullpage_api.destroy() not work

### ISSUE THREAD

**Issue by webkitvn** [alvarotrigo/fullPage.js#3328]
I'm using Method fullpage_api.destroy() when viewing on Mobile but it show me an error 
`fullpage_api is not defined`

**Comment by alvarotrigo** [comment]
You might be using fullPage.js version 2. 
See [the example](https://codepen.io/alvarotrigo/pen/bdxBzv) working as expected.

**Comment by webkitvn** [comment]
No, I'm using version 3.0

**Comment by alvarotrigo** [comment]
Then use `$.fn.fullpage` instead of `fullpage_api`

**Comment by webkitvn** [comment]
Do you mean `$.fn.fullpage.destroy()` ?
Still error `not a function` :(

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by webkitvn** [comment]
Could you take a look at my web [http://demo.amwind.vn/project/](url)
I can't find the issue

**Comment by alvarotrigo** [comment]
Sorry I do not take a look at websites in here. 
Only if you acquired the [Organization License](https://alvarotrigo.com/fullPage/pricing/) you'll be able to get premium support.  

Right now you'll have to provide an isolated reproduction in jsfiddle or codepen.
