### ISSUE TITLE
Hello, I am trying to add clickable icons to the first page via class="icon-block center clickable" but as soon as I add the anchors fullpage stops working. The second and third page are inaccessible. Any ideas?  

### ISSUE THREAD

**Issue by skuttenkuler** [alvarotrigo/fullPage.js#3329]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
