### ISSUE TITLE
Can't reliably detect clicks on fp-next and fp-prev arrows

### ISSUE THREAD

**Issue by bowler865** [alvarotrigo/fullPage.js#3331]
Is there a way to reliably capture clicks on the fp-next and fp-prev arrows with JQuery?

I want to send the event to Google Analytics but sometimes the clicks are recognized and sometimes they are not. I can't quite seem to figure out the pattern of when they are or not.

Thanks in advance.

```
$('.fp-section.active > .fp-next').click( function(event) {
				alert( "Handler for .click() called." );
				console.log('Next Arrow Clicked');
				ga('send', 'event', 'FP Next Arrow', 'Click');
			});
			$('.fp-section.active > .fp-prev').click( function(event) {
				alert( "Handler for .click() called." );
				console.log('Previous Arrow Clicked');
				ga('send', 'event', 'FP Previous Arrow', 'Click');
			});
```

**Comment by alvarotrigo** [comment]
Sounds more like a Javasript / jQuery issue more than a fullpage.js one.
I would encourage you to ask somewhere else. Or rather, use the fullpage.js callbacks such as `onSlideLeave` or `onSlideLoad` to trigger your actions.

**Comment by alvarotrigo** [comment]
Perhaps you should add the click even using delagation, as the arrow won't be there on page load. 
Or use the afterRender callback.

**Comment by bowler865** [comment]
Alvaro, Thanks for your reply. I tried using delegation, as you suggested as well as afterRender callback. In both cases I'm running into a similar problem. I couldn't see the pattern before but now I do on when the clicks are recognized and when they are not. If the arrows are clicked to go to the first slide or to the last slide of a section, the click is not recorded. So when there are only two slides nothing is recorded at all which was throwing me. Sections with more than two slides have the arrow clicks recorded unless the click takes the user to the first or last slide. Any thoughts?
