### ISSUE TITLE
Does 'Offset' extension support horizontal?

### ISSUE THREAD

**Issue by elliott-impression** [alvarotrigo/fullPage.js#3334]
Hello,

I had a look at the [Offset Extension demo](https://alvarotrigo.com/fullPage/extensions/offset-sections.html#4thpage) but do not see an example of this actively working when the [Scroll Horizontal Extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html) is also in play.

I am trying to achieve the below, using fullPage.js but it appears both of these extensions are required, unless you can advise otherwise?

![timeline](https://user-images.githubusercontent.com/39268006/43267933-355ddbd4-90e7-11e8-9178-394e657ce1f2.png)

Thank you in advance.

**Comment by alvarotrigo** [comment]
I don't understand your image. But offset sections only creates the offset for the vertical sections, not for the horizontal slides. 

In any case, both extensions are fully compatible.
