### ISSUE TITLE
White sections created below footer, after closing a bootstrap modal

### ISSUE THREAD

**Issue by SirMarley** [alvarotrigo/fullPage.js#3337]
I have 5 section in my home page and, in section 4 I have 4 buttons which open a modal.

Problem is that when the modal is open, the translate3d (or top if css3 is set to false) goes to 0 and when I close it, it goes back to where it was (i.e -2205px); but, if you do it quickly enough, it finally takes the "0" as the place where it was, making it the new 0 position, then it creates 3 new sections below the footer (no content sections) and scrolls down to the "new" section 4.

is there anyway to fix it, so, even if I do it quickly, the page remains where it is when I close the modal?

Thanks!

![image](https://user-images.githubusercontent.com/24829609/43331235-a95794bc-919b-11e8-8c05-3f4bb9ae76db.png)

![image](https://user-images.githubusercontent.com/24829609/43331345-fe236048-919b-11e8-959f-7409a8c04776.png)

![image](https://user-images.githubusercontent.com/24829609/43331366-110f1b0c-919c-11e8-87c5-4dfe0c3862bc.png)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
