### ISSUE TITLE
Error clicking in A tag- Cannot assign to read only property 'view' of object ' ayudaaa

### ISSUE THREAD

**Issue by Alfrex92** [alvarotrigo/fullPage.js#3338]
### Description
Hi, on mobile when I click the button 'Ver más'  in the slide 4 I have this error.
```
bundle.js:1 Uncaught TypeError: Cannot assign to read only property 'view' of object '#<MouseEvent>'
    at Object.n.click (bundle.js:1)
    at o._end (bundle.js:1)
    at o.handleEvent (bundle.js:1)
```
If I put the button in the slide 1 and 5 I do not have any problem. But, in the slide 2,3,4 it is not working. 

### Link to isolated reproduction with no external CSS / JS
https://yugen.biz/#slide4

### Steps to reproduce it
1. Enter to the website on your mobile phone
2. Click on the button 'Ver más' in the slide 4
3. You will see the error 

Thank you.

Gran plugin, muchas gracias Álvaro. Saludos desde Tokio.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
