### ISSUE TITLE
Scroll bar enable issue

### ISSUE THREAD

**Issue by ArslanAkhtar** [alvarotrigo/fullPage.js#3339]
i am trying to enable scroll on my site i am using this full page js code 

```
    $('#fullpage').fullpage({
	  scrollBar: true,
      anchors:['Indoor-3D-Maps', 'Indoor-3D-Maps-Benefits', 'Create-Indoor-3D-Maps','Indoor-Maps-Service','Pricing', 'Footer', ],
      scrollingSpeed: 1000,
      responsiveWidth: 1025,
      verticalCentered: true,
      onLeave: function(index, nextIndex, c) {
        if (index === 2 && mapLoaded === false) {
          mapLoaded = true;
          switchCustomMapFeature('smart-office');
        }
      }
    });
```

### Steps to reproduce it
1. i have noticed that it just `scrollBar: true` just change the css property on body of the page overflow: hidden to visible.
2. This is my site link please check its not making any difference [site link](https://deploy-preview-177--wrld3d.netlify.com/3d-maps/indoor-mapping#Indoor-3D-Maps)
3. i have also tried autoscroll: false that working fine.

**Comment by alvarotrigo** [comment]
Working as expected on [this jsfiddle](https://jsfiddle.net/1kyuL4em/138/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
