### ISSUE TITLE
LicenseKey option

### ISSUE THREAD

**Issue by timoanzalone** [alvarotrigo/fullPage.js#3342]
I've inserted the license key I've purchased into the licenseKey option and get the following error:

no identifiers allowed directly after numeric literal

**Comment by alvarotrigo** [comment]
How are you adding the license? Please add an example.

**Comment by timoanzalone** [comment]
I'm adding the license in the LicenseKey option:

$('#fullpage').fullpage({
    //options here
    licenseKey: xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx,
    autoScrolling:true,
    scrollHorizontally: false,
    keyboardScrolling: true,
    scrollOverflow:true,
    fadingEffect: true,
    lazyLoading: true,
    controlArrows: true
  });

**Comment by alvarotrigo** [comment]
You need to add it between quotes:

```javascript
$('#fullpage').fullpage({
    //options here
    licenseKey: 'xxxxxxxx-xxxxxxxx-xxxxxxxx-xxxxxxxx',
    autoScrolling: true
});
```
