### ISSUE TITLE
moveSectionDown is called immediately after moveSectionDown or moveSectionUp

### ISSUE THREAD

**Issue by jcidras** [alvarotrigo/fullPage.js#3343]
Hello there!

I am running into an issue that is on an AngularJS front-end where we are using fullpage.js to navigate on our home page. Once the home page is loaded the first time, the navigation buttons work as expected. However, when navigation to a different web page and coming back to the home page, when clicking the down arrow, it skips a section. 

Here are my findings while debugging:
1) When clicking the down arrow calls an AngularJS function in the home controller and calls the moveSectionDown correctly. However, when the method is finished, it calls it again. 
2) When clicking the up arrow, which calls an AngularJS function in the home controller and calls the moveSectionUp correctly. However, when the method is finished, it calls the moveSectionDown.
3) Neither the angularJS functions of nextSlide or prevSlide are called twice

Here are the steps to reproduce:
1) Upon loading the website, the navigation up and down arrows are working as expected
2) Click the down arrow once to look at "Browse Careers"
3) Click on career title to navigate to the career details page
4) Upon load of the career details page, click either the "Careers in the Military" logo up top or the "Home" link in the top menu
5) Click on the down arrow and it will skip to the "Hot Jobs" section
6) Click on the up arrow and it does nothing

Here's the Dev/QA version of the [website](http://asvabcitm.humrro.org/)
Here is the Angular code:
```
	$scope.nextSlide = function(){
		$.fn.fullpage.moveSectionDown();
	}
```
	
```	
       $scope.previousSlide = function(){
		$.fn.fullpage.moveSectionUp();
	}
```

On document ready, we have this code:

```
if ($.fn.fullpage.destroy) { 
    $.fn.fullpage.destroy('all');
}
			
if($scope.windowWidth > 640){
    $('#fullpage').fullpage({
        scrollOverflow: true,
        normalScrollElements: '#hot-jobs, #all',
        normalScrollElementTouchThreshold: 10,
    	onLeave: function(index, nextIndex, direction){
        var leavingSection = $(this);			        
        //using index
        if(nextIndex == 1){
            $('header').addClass('expanded');
        } else {
        	$('header').removeClass('expanded');			        	
        }	
      },
      afterRender: function(){
          $('header').addClass('expanded');
          if ( $('#step5 .fp-scrollable').length > 0 ) {
          	$('#step5 .fp-tableCell').css('padding', 0);
          } else {
          	$('#step5 .fp-tableCell').removeAttr('style');          	
          }
          var padding = $('header').outerHeight() + $('#top').outerHeight();
          $('.home #step1 #boxes').css('padding-top', padding);	
      }
    });
} else {
	$('#fullpage').fullpage({
	      afterRender: function(){
	          var padding = $('header').outerHeight() + $('#top').outerHeight();
	          $('.home #step1 #boxes').css('padding-top', padding);
	      }
        });
}
```
			

Production is using fullpage version 2.8.9, I upgraded to 3.0.2 locally to attempt to resolve the issue, but the issue persisted.

Thank you for your time!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
