### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by mi1353** [alvarotrigo/fullPage.js#3344]
Hi,

I have full page js license key but enable to find where I have to use it

**Comment by alvarotrigo** [comment]
As detailed on [the docs](https://github.com/alvarotrigo/fullPage.js#options):

> **licenseKey:** (default null). This option is compulsory. If you use fullPage in a non open source project, then you should use the license key provided on the purchase of the fullPage Commercial License. Otherwise, you can use the string OPEN-SOURCE-GPLV3-LICENSE. Please read more about licenses here and on the website.
