### ISSUE TITLE
Anchors on sections

### ISSUE THREAD

**Issue by johanvdr** [alvarotrigo/fullPage.js#3347]
Hi! when I set data-anchor on sections and remove anchor option from initialisation it doesn't work. It does work when I use anchors in the JS file like so: 

anchors: ['#'], //Works
anchors: [''], //Works
anchors: [], //Not working
[no anchors]//not working

This might be good to add to your docs.

**Comment by alvarotrigo** [comment]
> Hi! when I set data-anchor on sections and remove anchor option from initialisation it doesn't work.

I can not reproduce the issue. See [this demo](https://alvarotrigo.com/fullPage/examples/data-anchors.html).
In there I'm not using the anchors option, but it would work exactly the same way if you use an empty array, such as `anchors: []`

Please make sure to use the latest version 3.0.2.

**Comment by johanvdr** [comment]
Hi Maybe because I’m using parralex extension?

Met vriendelijke groet,
Johan van de Ruitenbeek






H&R Products
Rendementsweg 20B4
3641 SL Mijdrecht

T:    +31 297 - 76 02 56
M:   +31 6 26 93 27 64
E :   info@hr-products.nl
W:   www.hr-products.nl
L:	https://www.linkedin.com/in/johanvanderuitenbeek/
 
Facebook:
https://www.facebook.com/henrproducts

**Comment by alvarotrigo** [comment]
Shouldn't be a reason. Just make sure you use the latest version. 
Also, try without the extension and check it yourself.

**Comment by johanvdr** [comment]
You're right, I've updated to 3.0.2 now it's working fine without anchors set.
