### ISSUE TITLE
README - Link to demoPage.html under Required HTML structure section is broken 

### ISSUE THREAD

**Issue by colinbut** [alvarotrigo/fullPage.js#3348]
### README - Link to demoPage.html under Required HTML structure section is broken 

Gives back Github 404 not found page.

### Steps to reproduce it
1. Navigate to Required HTML structure section in README
2. Click on demoPage.html link

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll fix it for the next release!

**Comment by alvarotrigo** [comment]
Fixed in the latest version 3.0.3
