### ISSUE TITLE
Love the code but why are you forcing re-layout?

### ISSUE THREAD

**Issue by danyj** [alvarotrigo/fullPage.js#3349]
Props on the plugin as everyone has already mentioned  but it is beyond me why you are forcing existing sites to re-layout the HTML in order to use your plugin. 

Most sites structure is
```
<div class="container">
  <header>header</header>
  <section>1</section>
  <section>2</section>
  <section>3</section>
  <footer>footer</footer>
</div>
```
Why you are forcing this  is what I dont understand.

```
<div class="container">
  <div id="fullpage">
    <header>header</header>    <!-- Might not work-->
    <section>1</section>
    <section>2</section>
    <section>3</section>
    <footer>footer</footer>    <!-- Might not work-->
  </div>
</div>
```

Why is it that we cant use fullpage within our existing content but have to redo the structure for it?

**Comment by alvarotrigo** [comment]
Because not everything works as we would like you, and some structures are required for certain things :)

For example, fixed elements like headers or footers won't be fixed in certain browsers when using css3 transformations over their parent element.
