### ISSUE TITLE
Full Page JS not rendering facebook customer chat plugin

### ISSUE THREAD

**Issue by theflyingmantis** [alvarotrigo/fullPage.js#3350]
### Description
Facebook customer chat plugin - [https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/](https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/)

### Link to isolated reproduction with no external CSS / JS
Visit my website - [http://viablimp.com](http://viablimp.com)
Facebook customer chat plugin is not showing.

### Steps to reproduce it
1. Add fullpage js and facebook customer chat plugin. 

### Versions 
Chrome

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
This is probably not a fullPage.js issue. I'll close it until proven the opposite.
