### ISSUE TITLE
Last section of page is adding large amount of height

### ISSUE THREAD

**Issue by DairyBoy117** [alvarotrigo/fullPage.js#3351]
Hello. So I've added fullpage.js with scrollOverflow onto a wordpress site. It seems that the div with the class .fp-scrollable seems to be inconsistently adding large amounts of extra space sometimes before and after certain sections.

The page in question: https://cornerstonehospitalityconsulting.com/home/

I'm currently unsure how to troubleshoot this and was hoping maybe I've just failed to set something up correctly.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
