### ISSUE TITLE
First section translating to -7px on Y axis

### ISSUE THREAD

**Issue by Spacefuel** [alvarotrigo/fullPage.js#3352]
Hi,
I have same as in #2832 issue. The content structure:
`	<div id="fullpage">
		<div class="section" id="intro">
			<canvas id="canvas1"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas2"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas3"></canvas>
		</div>
		<div class="section">
			<canvas id="canvas4"></canvas>
		</div>
	</div>
`

	$('#fullpage').fullpage({
				v2compatible: true, (new version callback does NOT work)
				autoScrolling:true,
                               afterLoad: function(anchorLink, index){
		              ///..........changing canvas sizes and drawing functions ....
        }

Initially, the container has a style:: height: 100%; position: relative; touch-action: none; transform: translate3d(0px, 0px, 0px);

When you return to the first slide, the container has a style:
height: 100%; position: relative; touch-action: none; transform: translate3d(0px, -7px, 0px); transition: all 700ms ease;

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
@Spacefuel working perfectly when you remove all your JS code except the fullpage.js intialization:
https://jsfiddle.net/w3hzoked/15/

Meaning the problem is probably in your code and not in fullpage.js.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by Spacefuel** [comment]
The problem is definitely in fullpage.js and it only with the animation scroll to the first slide.
I think this bug is in calculating the #fullpage container height. This bug is appearing when in afterRender function I change canvas sizes inside each section to be equal to section.

**Comment by Spacefuel** [comment]
I think I found the bug
https://snag.gy/xgwnaC.jpg

**Comment by alvarotrigo** [comment]
If you believe the problem belongs to fullpage.js please provide a reproduction of it without any external JS.

**Comment by Spacefuel** [comment]
@alvarotrigo Have you seen my screenshot? I solved this bug by override the css:
.fp-tableCell, .fp-section.fp-table, .fp-slide.fp-table {display: block!important;}

bug with display:table-cell --> not proper height of div#fullpage --> problem with scroll to first slide.

**Comment by alvarotrigo** [comment]
Still don't see where's the issue within fullpage.js. As it works perfectly in any other occasion. 
Display table has a reason for it, to allow verticalCentered:true.

**Comment by Spacefuel** [comment]
@alvarotrigo  Probably the bug with display:table-cell appears only if the inner container is canvas...
if you want to get away from tables in responsive layout, you can place helper div with 100% height and display:inline-block and vertical align:middle  and all other elements can be inline-block...
Thank you for the plugin.
