### ISSUE TITLE
Tab doesn´t work in modal

### ISSUE THREAD

**Issue by ReneHetzel** [alvarotrigo/fullPage.js#3356]
### Description
`tab` doesn´t work in active bootstrap modals. Because the modal is inserted outside of the fullpage section. In the new version `tab` is only allowed in active sections. What is usually korrekt :) But not in this case.

This error ocourse if i use tab in any modal:

```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at a (fullpage.js:2072)
    at fullpage.js:2078
    at HTMLDocument.nn (fullpage.js:2006)
```
Is there a way to disable fullpage tab logic?

**Comment by alvarotrigo** [comment]
Duplicated of the open issue https://github.com/alvarotrigo/fullPage.js/issues/3144

**Comment by alvarotrigo** [comment]
> Is there a way to disable fullpage tab logic?

Nop.
