### ISSUE TITLE
Reset sliders bug

### ISSUE THREAD

**Issue by krscode** [alvarotrigo/fullPage.js#3357]
When resetslider plugin is enabled background offsets when revisiting slide

### Steps to reproduce it
1. Go to section 2
2. then go to a slide
3. then scroll up
4. then go to the same section
5. then go to the same slide

the background will now be out of alignment.

### Versions 
updated everything and bought all plugins again to use v3.

Thanks for help

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I'll take a look at it!

**Comment by alvarotrigo** [comment]
Which extensions are you using? I assume Parallax combined with Reset Sliders?

**Comment by krscode** [comment]
Thanks for your reply. Please see below the settings being used:



$(document).ready(function() {
$('#fullPage').fullpage({
  v2compatible: true, 
  anchors: ['home', 'investment-platform', 'golden-visa', 'ahimsa-investments'],
  loopHorizontal: false,
  controlArrows: true,
  menu: '#menu',
  animateAnchor: false,
  slidesNavigation: false,
  navigation: false,
  resetSliders: true,
  resetSlidersKey: ‘xx',
  parallax: 'sections',
  parallaxKey: ‘xx',
  parallaxOptions: {
    type: 'reveal',
    percentage: 62,
    property: 'translate',
  },
  css3:true,
  scrollingSpeed: 900,
  autoScrolling: true,
  scrollBar: false,
  fitToSection: true,
  fitToSectionDelay: 1000,
  lazyLoading: false,
  scrollOverflow: true, 
  verticalCentered: true,
  afterLoad: function(anchorLink, index){
  if(index == 3 && anchorLink == 'golden-visa'){
    $('body.fp-viewing-slidefree').find('.fp-section').index();
      $.fn.fullpage.setAllowScrolling(true, 'all'); 
      $.fn.fullpage.setKeyboardScrolling(true, 'all');
  } 
  if(index == 4 && anchorLink == 'ahimsa-investments'){
    $('body.fp-viewing-ahimsa-investments').find('.fp-section').index();
      $.fn.fullpage.setAllowScrolling(false, 'down'); 
      $.fn.fullpage.setKeyboardScrolling(false, 'down');
  }
  if(index == 5 && anchorLink == 'investment-information'){
    $('body.fp-viewing-investment-information').find('.fp-section').index();
      $.fn.fullpage.setAllowScrolling(false, 'all'); 
      $.fn.fullpage.setKeyboardScrolling(false, 'all');
      }
  },
  afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
    var loadedSlide = $(this);       
      if(index == 1 && slideAnchor == 'homepage'){
            $.fn.fullpage.setAllowScrolling(true, 'all');
      }
      if(index == 1 && slideAnchor == 'about-us'){
            $.fn.fullpage.setAllowScrolling(false, 'all');
      }
      if(index == 1 && slideAnchor == 'our-team'){
            $.fn.fullpage.setAllowScrolling(false, 'all');
      }
      if(index == 1 && slideAnchor == 'contact-us'){
            $.fn.fullpage.setAllowScrolling(false, 'all');
      }
      if(index == 1 && slideAnchor == 'register'){
            $.fn.fullpage.setAllowScrolling(false, 'all');
      }         
    }     
  });
  
          
  //Silentmove links
  //Home Links
  $(document).on('click', '#home-m', function(){
    $.fn.fullpage.silentMoveTo('1', 0);
  }); 
  $(document).on('click', '#aboutus-m', function(){
    $.fn.fullpage.silentMoveTo('1', 1);
  }); 
  $(document).on('click', '#ourteam-m', function(){
    $.fn.fullpage.silentMoveTo('1', 2);
  }); 
  $(document).on('click', '#contactus-m', function(){
    $.fn.fullpage.silentMoveTo('1', 3);
  });   
  $(document).on('click', '#register-m', function(){
    $.fn.fullpage.silentMoveTo('1', 4);
  });       
  /* Main Links
  $(document).on('click', '#investment-platform-l', function(){
    $.fn.fullpage.moveTo('2', 0);
  }); 
  $(document).on('click', '#golden-visa-l', function(){
    $.fn.fullpage.moveTo('3', 0);
  }); 
  $(document).on('click', '#ahimsa-investments-l', function(){
    $.fn.fullpage.moveTo('4', 0);
  }); */
  //Section 3 and 5
  $(document).on('click', '#goldenvisa-overview', function(){
    $.fn.fullpage.silentMoveTo('3', 1);
  }); 
  $(document).on('click', '#citizenship-overview', function(){
    $.fn.fullpage.silentMoveTo('3', 2);
  }); 
  $(document).on('click', '#ahimsa-passport', function(){
    $.fn.fullpage.silentMoveTo('3', 3);
  }); 
  $(document).on('click', '#portugal-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 1);
  }); 
  $(document).on('click', '#portugal-process', function(){
    $.fn.fullpage.silentMoveTo('5', 2);
  });     
  $(document).on('click', '#portugal-products', function(){
    $.fn.fullpage.silentMoveTo('5', 3);
  }); 
  $(document).on('click', '#uk-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 4);
  }); 
  $(document).on('click', '#uk-process', function(){
    $.fn.fullpage.silentMoveTo('5', 5);
  }); 
  $(document).on('click', '#uk-products', function(){
    $.fn.fullpage.silentMoveTo('5', 6);
  });   
  $(document).on('click', '#cyprus-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 7);
  }); 
  $(document).on('click', '#cyprus-process', function(){
    $.fn.fullpage.silentMoveTo('5', 8);
  }); 
  $(document).on('click', '#cyprus-products', function(){
    $.fn.fullpage.silentMoveTo('5', 9);
  });   
  $(document).on('click', '#spain-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 10);
  }); 
  $(document).on('click', '#spain-process', function(){
    $.fn.fullpage.silentMoveTo('5', 11);
  }); 
  $(document).on('click', '#spain-products', function(){
    $.fn.fullpage.silentMoveTo('5', 12);
  });     
  $(document).on('click', '#cyprusa-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 13);
  }); 
  $(document).on('click', '#cyprusa-process', function(){
    $.fn.fullpage.silentMoveTo('5', 14);
  }); 
  $(document).on('click', '#cyprusa-products', function(){
    $.fn.fullpage.silentMoveTo('5', 15);
  }); 
  $(document).on('click', '#stkitts-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 16);
  }); 
  $(document).on('click', '#stkitts-process', function(){
    $.fn.fullpage.silentMoveTo('5', 17);
  }); 
  $(document).on('click', '#stkitts-products', function(){
    $.fn.fullpage.silentMoveTo('5', 18);
  }); 
  $(document).on('click', '#dominica-overview', function(){
    $.fn.fullpage.silentMoveTo('5', 19);
  }); 
  $(document).on('click', '#dominica-process', function(){
    $.fn.fullpage.silentMoveTo('5', 20);
  }); 
  $(document).on('click', '#dominica-products', function(){
    $.fn.fullpage.silentMoveTo('5', 21);
  }); 
  
//BUTTON MENU
  var $labels = $('.tablabel').click(function(){
    $(this).toggleClass('clicked')
  }).mouseenter(function(){
    $(this).addClass('hover')
  }).mouseleave(function(){
    var $this = $(this);
    if(!$this.hasClass('clicked')) $this.removeClass('hover')           
  }).click(function(event){
    var closeOtherMenu = true;
    $(this).next().toggleClass("active")
  //Close other menus except the one clicked
    if(closeOtherMenu){
       $labels.not(this)
      .removeClass('clicked hover').next().removeClass('active')
    }   
  });

  //close if anything  but menu clicked
  var $dpd = $(".dpd")
  $(document.body).click(function (e) {
    if (!$(e.target).is('.tablabel') ){
      $dpd.removeClass('active');
      $labels.removeClass('clicked hover')
    }
  });

//LOGIN
  //login forgot password
    $('.forgot-pass').click(function(event) {
    $(".pr-wrap").toggleClass("show-pass-reset");
    }); 
    $('.pass-reset-submit').click(function(event) {
    $(".pr-wrap").removeClass("show-pass-reset");
    });
//MENU ACTIVE
  $('.menuActive').on('click', function(e) {
  e.preventDefault();
  $('.menu li a').removeClass("menuswap"); // remove highlight from all elements
  $(this).toggleClass("menuswap"); // add highlight to clicked element
  });    
  //fadeout bckgrnd on scroll
  // $(window).scroll(function() {
  //  $(".parallax-mirror img").css({
  //  'opacity': 1 - (($(this).scrollTop()) / 250)
  // }); });
});

**Comment by alvarotrigo** [comment]
Yeap, parallax and reset Sliders. 
I'll check it out.

**Comment by krscode** [comment]
Great thanks so much for taking the time

**Comment by alvarotrigo** [comment]
Can you please [contact me](https://alvarotrigo.com/#contact) so I can send you the latest version of parallax with the fix?

**Comment by krscode** [comment]
Hi

 i sent an email from the link.

David

On 4 September 2018 16:40:38 BST, "Álvaro" <notifications@github.com> wrote:
>Can you please [contact me](https://alvarotrigo.com/#contact) so I can
>send you the latest version of parallax with the fix?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/alvarotrigo/fullPage.js/issues/3357#issuecomment-418415986

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
