### ISSUE TITLE
Can't reinitialize fullpage.js with new settings for multi-page website using transition of barba.js

### ISSUE THREAD

**Issue by BuiKimPhat** [alvarotrigo/fullPage.js#3358]
### Problem: fullpage on page2 still remains the settings of page1 after transition
I'm trying to make a website using fullpage.js scrolling animation and barba.js transition which uses PJAX. It's still fine if I just load the pages normally and initialize fullpage.js on each page, the fullpage.js still works as expected. When I add the transition using barba.js, page1 after loaded is OK with its fullpage.js content but when I click on the link to page2 which has another fullpage.js settings, then the transition happens, then page2 is loaded with the combination of page1 and page2 fullpage.js settings.

P/s: I've already destroy('all') on the beginning of the transition.

### Code

> (Since this is a multi-page website, and I'm so amateur that I don't know how to run it in jsfiddle, I would be very glad if you can spend a little time reading my code here.)

This is what I've included in page1:

          $(document).ready(function() {
            function initFp(){
              $('#fullpage').fullpage({
                anchors: ['h1', 'h2','h3'],
                navigation: true,
                navigationPosition: 'right',
                navigationTooltips: ['The Team', 'The Members', 'The Message'],
                scrollBar:true,
                loopBottom: true,
                licenseKey :'OPEN-SOURCE-GPLV3-LICENSE',
                autoScrolling:true,
                lazyLoading: false
              });
              $.fn.fullpage.setAllowScrolling(true);
            }
            initFp();
            Barba.Dispatcher.on('newPageReady', function() {
              $.fn.fullpage.destroy('all');
            });
            Barba.Dispatcher.on('transitionCompleted', function() {
              initFp();
            });
          });

Page2:

          $(document).ready(function(){
            function initFp2(){
              $('#fullpage').fullpage({
                anchors: ['w1', 'w2','w3','w4'],
                sectionsColor: ['#00a94f'],
                navigation: true,
                navigationPosition: 'right',
                navigationTooltips: ['The Team', 'Meo', 'Neo','Leo'],
                scrollBar:true,
                licenseKey :'OPEN-SOURCE-GPLV3-LICENSE',
                autoScrolling:true,
                lazyLoading: false
              });
              $.fn.fullpage.setAllowScrolling(true);
            }
            initFp2();
            Barba.Dispatcher.on('newPageReady', function() {
              $.fn.fullpage.destroy('all');
            });
            Barba.Dispatcher.on('transitionCompleted', function() {
              initFp2();
            });
          });

### The Issue

After transition, the code on page2 remains the same, but I realize that the data-anchor of the sections has respectively been changed to h1, h2, h3, w4; and a similar thing happens to the body tag, too. Moreover, in page2, there are still 4 navigation dots, but the first 3 dots have the tooltips like in page1 and the last dot doesn't have a tooltip.
This issue is kind of weird, I've googled everywhere to find the answer but still couldn't fix it. So, I hope you can help me figure this out as soon as possible. Thank you.

**Comment by alvarotrigo** [comment]
Unfortunately that sounds like a JS / Barba issue rather than a fullPage.js one. 
Not a fullPage.js related issue. 

I'll proceed to close the topic as this is not the best place to ask for help for that.
