### ISSUE TITLE
SVG Color Change onLeave (Help Needed)

### ISSUE THREAD

**Issue by gokkstudio** [alvarotrigo/fullPage.js#3359]
Hi,
If anyone can help with this please.

I'm changing color of inline SVG on sections 3 and 5 (because they use dark bg) like this:
```
onLeave: function(anchor, index){
        if(index == 3 || index == 5){
          $('#svg-logo-color path').css({"fill":"#000"});
        }
        else{
          $('#svg-logo-color path').css({"fill":"#fff"});
        }
      }  
```

Styling SVG color in CSS like this:

```
#svg-logo-color {
    fill:#fff;
}

#svg-logo-color-dark {
    fill:#000;
}
```

Questions are:
1. How do I trigger "onLeave" to change color with css id (or class) "#svg-logo-color-dark" , instead using ".css({"fill":"#000"});"?
2. Is there a way to use css id (or class) to trigger "onLeave" in HTML, instead using index 1,2,3 (sections)? - I ask this because color change should appear on part of the section, not entire section, 
 I would need something like:
```
<div class="section" id="section0">
   <div id="svg-logo-color-dark"><!-- SVG logo color chaged when this div reached -->
      <p>some content here...</p>
   </div>
   <div id="svg-logo-color"><!-- revert SVG logo color when this div reached -->
      <p>some content here...</p>
   </div>
</div>
```

Hope this makes sense, thank you all.

**Comment by alvarotrigo** [comment]
1- Not related with fullpage.js. You'd better ask in another place like stackoverflow in which they'll be able to help you better.

2- Not something provided by fullpage.js.
