### ISSUE TITLE
Can't reBuild after destroy on a specific point

### ISSUE THREAD

**Issue by sonusasankan** [alvarotrigo/fullPage.js#3361]
### Description
Hello,

In my fullpage website, I would like to keep my footer as normal because I want to see all the contents in mobile when scrolling. So I destroyed fullpage after loaded footer section but the problem is I can't rebuild fullpage after footer scrolled top.
I have given my code below

`afterLoad: function(origin, destination, direction){
            var loadedSection = this;
    
            //using index
            if(destination.index == 17){
                fullpage_api.destroy();
            }
            
            var lastScrollTop = 0;
            $('footer').scroll(function(event){
            var st = $(this).scrollTop();
            if (st > lastScrollTop){
                console.log('down');
            } else {
                if(st == 0){
                    fullpage_api.reBuild();
                }
            }
            lastScrollTop = st;
            });
        },`

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Just create a function where you initialise fullPage. 
Call it once to initialise it for the first time. Then call it again when you need it.

**Comment by alvarotrigo** [comment]
reBuild purpose is another one. Only required when using scrollOverflow to recalculate the scroll bar position and size.
