### ISSUE TITLE
First sections not reachable when switching from autoScrolling: false to :true

### ISSUE THREAD

**Issue by plusklang** [alvarotrigo/fullPage.js#3362]
I got an issue when changing from autoscrolling: false to :true via `$.fn.fullpage.setAutoScrolling(true)`. I'm calling this function when I turn my phone from landscape to portrait using the `$(window).resize()` event. The page then slides to the last section and the link doesn't match. When I then scroll up, the autoscrolling works fine but it stops at the second section, so I can't reach the first section anymore. 

### Versions 
I'm using Chrome on Android 8.1. phone. I could also reproduce the error on Chrome on macOS 10.13 when changing to the responsive view and setting the screen size accordingly.

**Comment by alvarotrigo** [comment]
> I'm calling this function when I turn my phone from landscape to portrait using the $(window).resize()

Why don't you use the `responsiveWidth` or `responsiveHeight` options that already turn autoScrolling off?

In any case, `setAutoScrolling` seems to be working properly as can be seen in [this fiddle](https://jsfiddle.net/1kyuL4em/150/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
