### ISSUE TITLE
When autoscrolling is off anchor links do not work

### ISSUE THREAD

**Issue by plusklang** [alvarotrigo/fullPage.js#3363]
I have sections with anchors set with the data-anchor like e.g. `<section class="section" id="introSection" data-anchor="intro">` and a navigation with anchor links set like `<a href="#intro">Home</a>`. I'm not sure if it's a bug or just not possible but if **autoScrolling** is set **false** the links aren't working. If I click on them nothing happens.

[Chrome, macOS 10.13.]

**Comment by alvarotrigo** [comment]
Working as expected as can be seen in [this jsfiddle](https://jsfiddle.net/1kyuL4em/145/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by plusklang** [comment]
Seems like I was using an old version of fullpage. I updated it and now it works! Thanks!
