### ISSUE TITLE
Disconnect the plugin on mobile

### ISSUE THREAD

**Issue by usulla** [alvarotrigo/fullPage.js#3365]
Tell me, please, how to disconnect the plugin on mobile?
I use the option responsiveWidth, but it does not work..

**Comment by alvarotrigo** [comment]
Working perfectly on the demo page:
https://alvarotrigo.com/fullPage/examples/responsive.html

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by usulla** [comment]
Sorry, this question in react-fullpage..

**Comment by alvarotrigo** [comment]
Open the issue in the react-fullpage github forum. And also provide a reproduction if possible.

**Comment by mahendrushivam** [comment]
U can use css either to manage the height of the section container or u can use display none to hide this component

**Comment by usulla** [comment]
But then I need to load all the content of the site twice and that is the weight of the site will be twice as large

**Comment by mahendrushivam** [comment]
U can set height to 100% overflow : scroll it may help

**Comment by alvarotrigo** [comment]
That's not the official repository. I'm not the author. 

Make sure you are using the official one. Otherwise I can't do anything to help you out.

**Comment by usulla** [comment]
Tell me, please, where is your official plugin for React?

Or I can use this plugin with React?

**Comment by usulla** [comment]
I found!
https://github.com/alvarotrigo/react-fullpage

Thanks!

**Comment by mahendrushivam** [comment]
I have used that repository it has some bugs try to keep overflow hidden in case of body tag it may resolve your issue or use this repository where you are commenting

**Comment by alvarotrigo** [comment]
@mahendrushivam if you think you found some bugs please feel free to open an issue in the forum to report it.
