### ISSUE TITLE
Refresh Blank Slide Issue

### ISSUE THREAD

**Issue by Matthew-Hodgetts** [alvarotrigo/fullPage.js#3367]
Good day,

When scrolling to the bottom section (No. 5) and then refreshing the page, the page reloads (data-anchor in use) and what appears is what looks like a blank, 100% space beneath the fullpage wrapper. 

Inspecting in dev tools and selecting the white space shows the element to be the <body> tag.

If i scroll up the issue goes away and the white space then disappears and the slide above the bottom slide becomes in view. 

My options are:

		```
		//options here
		scrollingSpeed: 900,
		lazyLoading: true,
		licenseKey: "{{not shown here}}",
		navigation: true,
		onLeave: function(origin, destination, direction){
		var leavingSection = this;

                // Changes opacity of the logo past slide 1
		if(origin.index == 0 && direction =='down'){
			$(".site__logo").css("opacity", "0");
		}
		else if(origin.index == 1 && direction == 'up'){
			$(".site__logo").css("opacity", "1");
		}
	}
```

The slides do have a "data-anchor" attribute attached to them which makes the anchor appear in the url as I'm sure you are aware of. If there is an option to remove the anchor from the url I believe the issue will not persist for me. I am not concerned with people returning to the slide they last viewed the page on.

Thank you.

Issue appears across all browsers (up to date) (including mobile).

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or codepen, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by Matthew-Hodgetts** [comment]
Can be seen at:
[https://bit.ly/2Pa1c2s](https://bit.ly/2Pa1c2s)

**Comment by alvarotrigo** [comment]
I do not check private websites here, I only provide premium support for people who acquired [the Organization license](https://alvarotrigo.com/fullPage/pricing/).

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
