### ISSUE TITLE
Acceptable way to have position fixed in a section that has overflow scrolling?

### ISSUE THREAD

**Issue by danielimmke** [alvarotrigo/fullPage.js#3371]
It seems like the way that fullPage.js handles overflow scrolling is by using CSS to transform the position of the whole section. Is there a currently accepted way to have pos: fixed content inside that section? Ex: a section is split into left and right. The overflow content is coming from the right column. I want the content on the left to persist the whole way when scrolling.

**Comment by alvarotrigo** [comment]
Use the fixed positioned element outside the fullpage.js wrapper.
