### ISSUE TITLE
How to: Scroll down to specific slide in a section without seeing the slides before it?

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3373]
Hi There,

I am wondering of this is possible. If I have two sections, the second section has 4 slides. 
Is there anyway I can go directly to a slide without it scrolling through the others before it?

Here is an example of what I mean.
![slides](https://user-images.githubusercontent.com/6698804/44202310-815c7100-a143-11e8-8652-0d35380f9a94.png)

The green line is what I am trying to achieve. at the moment it scrolls through like the black line.

Best regards.

**Comment by alvarotrigo** [comment]
See the [silentMove](https://github.com/alvarotrigo/fullPage.js#silentmovetosection-slide) method.
Or turn scrollingSpeed to 0 using the [setScrollingSped](https://github.com/alvarotrigo/fullPage.js#setscrollingspeedmilliseconds) method.

**Comment by AmanSahota** [comment]
Hi, I have been looking at your example here:
https://codepen.io/alvarotrigo/pen/doqOeY

But I cannot get it to move to a different slide other than the first one?

**Comment by alvarotrigo** [comment]
Replace this:
```
  fullpage_api.silentMoveTo('page2', 1);
``` 

For whatever section and slide  you need to. 
More about it in the docs regarding silentMoveTo.


```
  fullpage_api.silentMoveTo('page2', 2);
```
