### ISSUE TITLE
请问，使用fullPage如何避免ios微信底部的白条？（how to use fullPage to avoid the white bar at the bottom of ios WeChat?）

### ISSUE THREAD

**Issue by steady-join** [alvarotrigo/fullPage.js#3374]
新更新的微信底部白条。（The newly updated WeChat bottom white bar.）

**Comment by alvarotrigo** [comment]
Are you talking about this bar?
![unnamed](https://user-images.githubusercontent.com/1706326/44298220-6a528600-a2df-11e8-9b41-4ea05cdfcd70.jpg)

**Comment by steady-join** [comment]
是的，这个功能是微信新更新的，请问如何解决（或者隐藏）
Yes, this feature is new to WeChat, how to solve it (or hide it)

**Comment by alvarotrigo** [comment]
现在可能没有一个完美的方式。 但我会调查它！
谢谢报道！

Right now there isn't probably a perfect way. But I'll investigate it! 
Thanks for reporting it!

**Comment by hanwen1994** [comment]
设置这个参数就可以了
new fullpage('#fullpage', {
     recordHistory:false
})

**Comment by alvarotrigo** [comment]
I'll close the issue then!
