### ISSUE TITLE
fullpage和ias.js冲突了

### ISSUE THREAD

**Issue by NoZuo-NoDie** [alvarotrigo/fullPage.js#3375]
### Description
在wordpress的首页里(去除了head,sidebar,foot)，每2篇文章分一页，下拉文章时使用ias.js的ajax刷新，同时用fullpage让每篇文章以全屏幕展示。但是fullpage.js却没有正确的效果。可以帮助写出有效的代码吗？非常感谢！
[DEMO:](http://xiaomaotao.com/)

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

【index php】
<div id="fullpage">
		<ul id="postlist">
			<?php while (have_posts()) : the_post(); ?>
				<li class="section post_cms" id = "post<?php the_ID(); ?>" >
					<?php $content = get_the_content();echo wp_trim_words( $content, 300, '....' ); ?>
				</li>
			<?php endwhile; ?>
			<div id="pagenav"  class="section fp-auto-height" >
				<?php next_posts_link(__('NEXT PAGE'));  ?>
			</div>
		</ul>
	</div>
[js]
//初始化fullpage.js和ias.js
$(function(){
    $('#fullpage').fullpage({
		scrollBar:true,
		scrolloverflow:true,
	});
	
	//anything wrong? thanks
	$.fn.fullpage.reBuild();
	
	var ias = jQuery.ias({
		container: "#content",
		item: ".post_cms",
		pagination: "#pagenav",
		next: "#pagenav a",
		loader: '<i class="fa fa-spinner fa-spin fa-3x fa-fw" ></i>',
		});
		ias.extension(new IASTriggerExtension({
		text: 'next page', 
		offset: 2
		
		}));
		ias.extension(new IASSpinnerExtension());
		ias.extension(new IASNoneLeftExtension({
		text: 'the end', 
		}));
	
	//Is this necessary?thanks
	$('#fullpage').fullpage({
		scrollBar:true,	
	});
})

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
你可以在没有外部CSS或JS的情况下在jsfiddle或codepen中提供它的独立复制吗？

Can you please provide an isolated reproduction of it in jsfiddle or codepen with no external CSS or JS ?

**Comment by alvarotrigo** [comment]
codepen无法正常工作。 您应该能够从后端代码（PHP）中隔离前端代码（Javascript和jQuery）。

如果没有问题的复制，我无法看到问题，因此我无法帮助您解决问题。

如果您使用Ajax动态添加节，那么您需要完成销毁并再次初始化整页。
您可以使用fullpage_api.destroy（'all'）然后再次初始化fullPage。

你可以在我的答案中看到它的一个例子：
https://stackoverflow.com/a/36643702/1081396
----

The codepen is not working. You should be able to isolated front-end code (Javascript & jQuery) from back-end code (PHP).

Without an isoalted reproduction of the issue I can not see the problem and therefore I can not help you with it.

If you are adding sections dynamically by using Ajax, then you'll need to completey destroy and initialise the fullpage again. 
You can do that by using fullpage_api.destroy('all') and then initialise fullPage again.

You can see an example of it in my answer here:
https://stackoverflow.com/a/36643702/1081396
