### ISSUE TITLE
Address bar stays hidden after changing from responsive to non responsive mode

### ISSUE THREAD

**Issue by plusklang** [alvarotrigo/fullPage.js#3376]
I'm viewing my page on my Android phone with responsive mode switch on `$.fn.fullpage.setResponsive(true)`. When I scroll down the address bar as usual disappears. Thats all good because when I scroll up it appears again. The problem is when I scroll down and then change from landscape to portrait where I set the responsive mode to false. The address bar then stays hidden. Is there a way to make it appear again?

### Steps to reproduce it
1. Responsive mode on
2. Scrolling down
3. Responsive mode off
4. Scrolling up -> Scroll bar stays hidden

### Versions 
[Chrome 68, Android 8.1.0]

**Comment by alvarotrigo** [comment]
> Is there a way to make it appear again?

Unfortunately we developer have no direct control over the address bar. 
The best you can do to use the default behaviour is using `scrollBar:true`. This way the page will act as any other page regarding the address bar.
