### ISSUE TITLE
Problems in iPad with responsive design

### ISSUE THREAD

**Issue by andersonsteve** [alvarotrigo/fullPage.js#3377]
It is understood that the responsive function is variable, I can edit it to work from 480 but in an iPad Pro it detects it from before and does not arm the block function, if it does not activate the scroll and the blocks no longer work.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by andersonsteve** [comment]
Tell you that I reproduce this page on my ipad -  https://alvarotrigo.com/fullPage/examples/responsive.html

and it does not reproduce blocks, it reproduces scroll, it just happens with this, try to lower the responsive reading to 480, but it still reads it as scroll without blocks

other templates that you have if you read them normal, the problem is only with this one.

**Comment by alvarotrigo** [comment]
Read about the view port meta tag.
Probably related with that.

**Comment by alvarotrigo** [comment]
Also, not sure to understand what you mean by "blocks".
