### ISSUE TITLE
Background overlap IE11 (Parallax) when using scrollOverflow:true

### ISSUE THREAD

**Issue by gego05** [alvarotrigo/fullPage.js#3378]
### Description
Hi,
we have a problem with parallax extension in ie11.
Background images are overlapping in slider.

Screenshot Firefox:
![firefox](https://user-images.githubusercontent.com/16879037/44467131-647fdc00-a622-11e8-88f2-48fb4871d30b.png)

Screenshot IE11:
![ie11](https://user-images.githubusercontent.com/16879037/44467132-647fdc00-a622-11e8-81e4-5ebcc608939e.png)

### Link to isolated reproduction with no external CSS / JS
(Removed, I'll check it)
To show the fiddle in IE11, use this:
(Removed, I'll check it)

### Steps to reproduce it
1. Create a html source code with fullpage extension js and parallax js.
2. Everything working fine in Firefox, Chrome, Edge,...
3. Images are overlapping in IE11, see jsfiddle.
4. If we disable parallax then everything is working fine.

### Versions 
Newest Version of IE11
Windows 10
Fullpage JS 3.0.2
Fullpage Extensions 0.1.7
Fullpage Parallax 0.1.3

**Comment by alvarotrigo** [comment]
Thanks for the links to the reproduction! 
I'll check it as soon as I can!

**Comment by alvarotrigo** [comment]
I'm not able to reproduce the issue on my side.
I tried using the latest fullPage.js version 3.0.2 and the parallax extension for version 3.

I also tried using fullPage.js 2.9.7 and the latest version of parallax for version 2. (That's the [demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html))

Can you please [contact me](https://alvarotrigo.com/#contact) with a link to an **isolated reproduction** of the issue? With the minimum amount of HTML and no external CSS or JS files to fullPage.js?

**Comment by alvarotrigo** [comment]
I was able to reproduce it thanks to your fiddle. 
Apparently is related to the option `scrollOverflow:true`. There's no bug without it. 

I'll check it out! Thanks for reporting it and taking the time to create the fiddle!

**Comment by alvarotrigo** [comment]
I've fixed the issue! 
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase and I'll provide you the latest version for the parallax extension that fixes this issue.

**Comment by gego05** [comment]
Thanks again!
