### ISSUE TITLE
Auto adjust content to Slide/Section (responsive)

### ISSUE THREAD

**Issue by e-anima** [alvarotrigo/fullPage.js#3380]
Hi,
i was doing some test because the script is very nice. My aim is to buy it for a client. But i have a major problem.

What i tried is loading an image and a caption inside a section. basically like that.

```html
<div class="section container">
<div class="wrapper">
  <div class="item">
  <figure>
    <picture>
    <img src="image url">
    </picture>
  </figure>
  <div class="caption">
    <h3>
    Hello mate
    </h3>
  </div>
  </div>
</div>
```

The problem i now have is that if i set the img to be 100% height it is but it will push out the caption and will take the whole area of the current slide. As the script adds a lot of css and changes style to tables too i wonder i what i try is even possible here.  Was trying around for 1,5 now, so i decided to ask.
In general i wanted the whole content inside a section to be responsive. Thank you.

**Comment by alvarotrigo** [comment]
I do not undertand what's your issue to be honest, but if you do not want fullpage.js to add any `fp-table` element or to add any css on it, just use `verticalCentered:false`.

The responsive work comes from your side. Fullpage.js can only provide you features such as `responsiveWidth`, `responsiveHeight` and `fp-auto-heigh-responsive` to make it easier for you.
