### ISSUE TITLE
When scrolling, screens are replaced by jerks in Firefox and Chrome

### ISSUE THREAD

**Issue by kireichev** [alvarotrigo/fullPage.js#3381]
### Description

Hi. There was a problem.

When scrolling the site on iMac 27 (Retina 5K) in Firefox 61.0.2 and Chrome 68.0.3440.106, a hang occurs, the screens are replaced by jerks, the feeling is that the FPS is falling. Everything works fine in Safari.

### Link to isolated reproduction with no external CSS / JS
Site - *test.kireichev.ru/kireichev/*

### Versions 
Browser - Firefox 61.0.2, Chrome 68.0.3440.106
Operating system - macOS High Sierra 10.13.6 (17G65)
Device - iMac (Retina 5K, 27-inch, Late 2015)

**Comment by alvarotrigo** [comment]
I'm not able to reproduce it on my 8 years old Mac :)
Try from another computer. Probably not a fullpage.js issue but a browser/computer issue.
