### ISSUE TITLE
Add and remove class when in viewport

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3382]
Hi I am trying to add and remove classes as you fo towards to the top of the viewport.

Here is an example of what I am trying to do:
https://codepen.io/AmanSahota/pen/YOymjN

I tried to add this to a section, but I cannot get it to function:
https://codepen.io/AmanSahota/pen/XYoYrv

Do I need to achieve this another way?

**Comment by alvarotrigo** [comment]
The scrolloverflow element doesn't fire the scroll event.
See [my answer here](https://stackoverflow.com/a/39369282/1081396) if you want to do it yourself somehow.

**Comment by AmanSahota** [comment]
Thanks for getting back.. I was wondering is there any live examples of where this has been achieved? A codepen or anything?
