### ISSUE TITLE
how to do scrolling only footer reaming section need normal scroll 

### ISSUE THREAD

**Issue by Chandankroy92** [alvarotrigo/fullPage.js#3384]
how to do fullpage js in particular section not full website.
here is website link:
[http://fueblabs.redtest.in/smart-city-solution.html](http://fueblabs.redtest.in/smart-city-solution.html)

I want scroll only in footer not in hole page 
I need to scroll on footer. remaining section i need to normal scroll.
Please help me.

**Comment by alvarotrigo** [comment]
Not possible I'm afraid.
