### ISSUE TITLE
the element of current section doesn‘t display in the next section

### ISSUE THREAD

**Issue by lvanboy** [alvarotrigo/fullPage.js#3388]
### Description
the element set css position:absolute.meantime seting the z-index is the greatest level,but try to take it in the next section,but it is not visiable.

**Comment by ervandra** [comment]
Hi @lvanboy , i am trying to help you again by creating this pen: https://codepen.io/ervandra/pen/dqXWOM

* First, if you need an element to be visible across the sections, you might need to set the `position: fixed;` in the first place. this will ensure the elements stay in the viewport / screen.
* You should define the `fixedElements` options by passing their class / id in the options.

Please take a look at the pen sample, and let us know if you haven't resolve your issue :)

**Comment by alvarotrigo** [comment]
@ervandra thanks again for helping me to answer people ;)

> You should define the fixedElements options by passing their class / id in the options.

Just a note, as I noticed you recommended that twice now :)
`fixedElements` was only meant to solve issues when people used fixed elements **inside** the fullPage.js wrapper, so, all that option does is moving those elements outside, as you can see [here](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L758).

As long as you place all fixed elements outside fullpage.js wrapper, they won't have to use the option  `fixedElements`.
