### ISSUE TITLE
autoScrolling followed by normal scrolling

### ISSUE THREAD

**Issue by srikat** [alvarotrigo/fullPage.js#3389]
Hello,

How/Is it possible to display a few sections with snapping effect (autoScrolling) followed by normal scrolling like how it's working in the following site?

https://www.prophet.com/

Is there a way to set `autoScrolling` to false after the user reaches (by scroll or keyboard) the last section in a container on which fullPage has been initialized?

Thanks in advance.

**Comment by alvarotrigo** [comment]
Yeap. It won't be perfectly smooth (as in the page you link), specially when using kinetic scrolling like when using laptops trackpads (specially Apple ones), but you can just turn autoScrolling off an on by using the method provided by fullpages [`fullpage_api.setAllowScrolling(false)`](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions).

You can make use of it on the `afterLoad` or `onLeave` functions. 
You can even inspect how that site is using it, as it is also using fullpage.js.
