### ISSUE TITLE
Hide the Header on Scroll

### ISSUE THREAD

**Issue by kcfgl** [alvarotrigo/fullPage.js#3390]
### Description
First off love this plugin. Second, I'm trying to use the callbacks to know when I've left the first section or arrived back at the first section.  I have a standard #header (this is a wordpress site using Enfold) and I'd like to hide this header whenever I'm not at the top of the page. 

Pretty sure this is very standard and I'm just missing something.  Any help would be appreciated it.  Thanks!
### Link to isolated reproduction with no external CSS / JS
```
onSlideLeave: function( anchorLink, index, slideIndex, direction, nextSlideIndex){
   console.log('onSlideLeave');
        if(slideIndex == 0){
           console.log('Leaving current slide, do your jquery to hide the header);
        }
    }
```

**Comment by alvarotrigo** [comment]
If you are using fullpage.js version 3 (which you should) you should be using the option `v2compatible:true` to use the old callbacks signature.

However I would encourage you to make use of the new signature you can see on the docs. Using the parameters `origin`, `destination` and `direction`. 

You can see an example of the usage of callbacks for both cases in [the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples)

**Comment by kcfgl** [comment]
@alvarotrigo Ah crap, rookie mistake.  Thank you.
