### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by shahjehanali1** [alvarotrigo/fullPage.js#3391]
I'm using jquery UI drag and drop but It's not working if scrolloverflow: true, 
Here is codepen link https://codepen.io/shahjehan/pen/GQXbEg/

**Comment by alvarotrigo** [comment]
You are not making use of the Drag And Move extension for fullPage:
https://alvarotrigo.com/fullPage/extensions/drag-and-move.html

If you have issues with external libraries it might be because you are not initialising them inside the afterRender callback or using delegation for them. 
Try that

**Comment by alvarotrigo** [comment]
It can also be the fact that they

**Comment by shahjehanali1** [comment]
Can you help me to code this?
