### ISSUE TITLE
Safari/iOS 100vh it is cut

### ISSUE THREAD

**Issue by LuisPaico** [alvarotrigo/fullPage.js#3396]
Hi/Hola

I'm doing sections with a 100vh and in Chrome I'm doing fine, but when I open it in Safari from my iPhone it's cut on the bottom.

How can i fix this?

This is the web that I am developing: http://by.kasfactory.net/

**Comment by alvarotrigo** [comment]
Sorry why is this related with fullPage.js at all?
fullpage.js sets's the size of your sections and slides in px, not in vh.

Also note I do not check private websites here, I only provide premium support for people who acquired [the Organization license](https://alvarotrigo.com/fullPage/pricing/).

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by LuisPaico** [comment]
Yes, I've seen the problem.
If I adjust to the height that fullpage.js gives me with 100%, if it adapts well in sarafi (ios). 
Thank you
