### ISSUE TITLE
HTMLDivElement is not a constructor problem

### ISSUE THREAD

**Issue by Blinks44** [alvarotrigo/fullPage.js#3397]
Hello, guys, could you help me, what am i doing wrong?

Clean install of Wordpress Sage9 theme and fullpage.js, nothing more and i get this:
![2018-09-08_17-55-34](https://user-images.githubusercontent.com/8570193/45255544-9918c500-b390-11e8-94cf-5ce4ac96d93b.png)

It's just a blank page with
`  <body @php body_class() @endphp>`
 `   @php do_action('get_header') @endphp`
  `  <div id="fullpage">`
      `<div class="section">Some section</div>`
   `   <div class="section">Some section</div>`
      `<div class="section">Some section</div>`
      `<div class="section">Some section</div>`
   ` </div>`
    `@php wp_footer() @endphp`
  `</body>`

Thank you!

**Comment by Blinks44** [comment]
Ok, sorry, this helps me - https://github.com/alvarotrigo/fullPage.js/issues/3284#issuecomment-408595420

@alvarotrigo You rock!

**Comment by alvarotrigo** [comment]
Glad you managed to get it working! ;)
