### ISSUE TITLE
How to “destroy” fullPage.js?

### ISSUE THREAD

**Issue by mrcoles** [alvarotrigo/fullPage.js#3398]
Is there any way to disable fullPage.js after it has been applied?  Similarly, skrollr has: [skrollr.init().destroy();](https://github.com/Prinzhorn/skrollr/blob/master/src/skrollr.js#L650)

I ask because, a lot of people use my Chrome screenshot extension—[Full Page Screen Capture](https://chrome.google.com/webstore/detail/full-page-screen-capture/fdpohaocaechififmbbbbbknoalclacl?hl=en)—to screenshot pages they’re building, but the way fullPage.js hijacks the scrollbar prevents it from programmatically scrolling the page. If there was a feature for disabling it (maybe a custom event dispatched on the window elt?) then I’d love to add support for it. They added something like this to [AnimateMe](https://github.com/scriptex/AnimateMe/issues/3).

**Comment by alvarotrigo** [comment]
See the docs regarding `fullpage_api.destroy('all')`. 
But I believe what your really want is `fullpage_api.setAutoScrolling(false)`.

**Comment by mmbapin** [comment]
but how to destroy it in nuxt js.

**Comment by alvarotrigo** [comment]
> but how to destroy it in nuxt js.

You can ask in the vue issues forum:
https://github.com/alvarotrigo/vue-fullpage.js

 But basically the same way :) 

```jsx
@click="$refs.fullpage.api.destroy('all')"
```
