### ISSUE TITLE
extensions of parallax maybe have bug

### ISSUE THREAD

**Issue by rfrkk** [alvarotrigo/fullPage.js#3400]
When it added navigation-vertical for page, then the background div having fp-bg class was not at correct postion.

this means that calculation of transform:tranlateX maybe have error.

![_2018-09-09t01-08-59 492z](https://user-images.githubusercontent.com/137764/45260093-0ddf1400-b410-11e8-80c9-3bc5e76dc35b.png)

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase. 
Then provide me a link to the reproduction of the issue.
