### ISSUE TITLE
Developer License for Angular 6

### ISSUE THREAD

**Issue by villain2** [alvarotrigo/fullPage.js#3402]
Having searched several times I've seen different variations on how to install the license key for AngularJS (4 and above). Most of them cite files that don't exist anymore with updated versions of fullpage.js or AngularJS (ex. angular-cli.json, jquery.fullpage.js etc.)

The main issues are a) where does the fullPage.js Commercial Developer License go and b) even using it on localhost, adding this to the angular.json file:

`
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/fullpage.js/dist/fullpage.min.js",
              "node_modules/fullpage.js/LICENSE",`

Under scripts in the .json results in an error:

`Uncaught SyntaxError: Unexpected identifier`
Which is pointing to the beginning of the license that reads: "GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007"

**Comment by alvarotrigo** [comment]
If we are talking about fullpage.js 3. As detailed in [the docs](https://github.com/alvarotrigo/fullPage.js#options) you should use the `licenseKey` option to place the license:

For example:

```javascript
new fullpage({
     licenseKey: 'YOU_KEY_HERE'
});
``` 

You acquire the license key once you purchase the comercial license from [here](https://alvarotrigo.com/fullPage/pricing/).

The LICENSE file is not required as long as you do not remove the credits comments on the JS and CSS files stating fullPage.js is under GPLv3 and linking to the site and repository.

**Comment by tadkim** [comment]
Is fullpage.js available on Angular 6+?

**Comment by alvarotrigo** [comment]
@tadkim not any official component yet. But it's on the process 😄
