### ISSUE TITLE
Using autoScrolling:false with scrollOverflow: true conflicting scrollbars

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3403]
Is there anyway to use both `scrollOverflow: true` and `autoScrolling: false` together with `fp-auto-height` within a section without the scrollbars conflicting?

I have a pen here: https://codepen.io/AmanSahota/pen/MqpJzx

The middle section has `fp-auto-height` and I have enabled the browser scrollbar.. however both sections don't seem to work very well together. What would be the best way to do this?

The reason I would like the main scrollbar is because I want to add some animation effects on scroll.

**Comment by alvarotrigo** [comment]
> Is there anyway to use both scrollOverflow: true and autoScrolling: false together with fp-auto-height within a section without the scrollbars conflicting?

Nop. Those options are mutually exclusive. 
In fact, is difficult for me to make any sense of the use of all them together. 

The only purpose of using `fp-auto-height` is to not use `scrollOverflow:true`.  

In any case, I'll have to add it on the warnings function so you'll get an error on the JS console when using both. As it now happens when using `scrollBar:true` and `scrollOverflow:true` as can be seen [here in this line](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L3134).

**Comment by alvarotrigo** [comment]
This issue stills open for anyone who want to become a contributor to this project! 👍 
I'm giving this way the chance for anyone to contribute to an open source project and practise their Javascript skills.

I propose the solution here. Now you have the chance to work on a few lines and make your contribution! 

Proposed solution
------
On the `displayWarnings` function add an `or` condition in the currently condition that checks for `scrollBar:true` and `scrollOverflow:true`. 
The options `autoScrolling:false` and `scrollOverflow:true` are also exclusive. 

Then on the message replace the following:

> 'Option `scrollBar` is mutually exclusive with `scrollOverflow`.

For 

> 'Options `scrollBar:true` and `autoScrolling:true` are mutually exclusive with `scrollOverflow:true`.

**Comment by alvarotrigo** [comment]
@dotEthan nop. As long as they do not modify the same lines there won't be conflicts.

**Comment by alvarotrigo** [comment]
@dotEthan you can sync or "pull" from the dev branch as I made a few more changes. So you always work on the latest version.

**Comment by dotEthan** [comment]
Updated with pull request #3406

**Comment by alvarotrigo** [comment]
Fixed in the latest version 3.0.3
