### ISSUE TITLE
TypeError: item is undefined error on jQuery load content

### ISSUE THREAD

**Issue by squishz** [alvarotrigo/fullPage.js#3404]
When i load content onto my page into my fullpagejs container and do a fullpage_api.reBuild(); it gives me a TypeError: item is undefined error.

For testing purposes a made a file with just a bunch of `<div class="section">` and that even returns the same error.

The content loads in fine, i can see all the sections correctly within #fullpage.

I have attached my jQuery bellow.

*edit (removed code, added jsfiddle bellow)

Any help would be appreciated as i have been spending ages on this now and its pretty much keeping us from launching a project.

Thanks

**Comment by squishz** [comment]
Just to add the actual error i am getting:

`TypeError: item is undefined[Learn More] fullpage.js:3437:13`

**Comment by squishz** [comment]
@alvarotrigo There you go: http://jsfiddle.net/xpvt214o/783948/ 

Stripped it down completly, still getting the same error.

Thanks

**Comment by alvarotrigo** [comment]
reBuild method only works for the section/slide level.
Whenever you update the content or a particular section/slide. 

You are instead updating the content of all the fullpage element.
In that case you'll need to destroy fullpage.js and initialise it again.

Use `$.fn.fullpage.destroy('all');` and a function to initialise it again.

**Comment by alvarotrigo** [comment]
On this line:
http://jsfiddle.net/alvarotrigo/xpvt214o/786896/
