### ISSUE TITLE
Pause before sliding

### ISSUE THREAD

**Issue by Maik0** [alvarotrigo/fullPage.js#3407]
Hello. I'm trying to make a page with FullPage and animations.
I have an icon which should appear (when section loaded) and dissapear (when I leaving section). Everything is great on first animation, but when I go to next section I do not have time to see second animation. I want to wait and see it and then slide to next section.
For first animation I use afterLoad function, for second animation I use onLeave function.
https://codepen.io/Melkadze/pen/dqeKOg
How can I realize some pause before sliding?

Thanks for attention.

**Comment by squishz** [comment]
@Maik0 you could do something like this i suppose:

> var fload = true;
> var myFullpage = new fullpage('#fullpage', {
>       v2compatible: true,
>       scrollingSpeed: 700,
>       lazyLoad: true,
>       onLeave: function(index, nextIndex, direction) {
>         if(index == 1 & fload == true){
>             document.getElementById('bg-1').classList.remove("bg-1");
>             document.getElementById('bg-1').classList.add("cg-1");
>          
>             setTimeout(function() {
>                 fload = false;
>                 fullpage_api.moveTo(2);
>             }, 3000);
>             return false;
>         }
>       },
>       afterLoad: function(anchorLink, index) {
>         if (index==1) {
>             document.getElementById('bg-1').classList.add("bg-1");
>         }
>       }
>     });

**Comment by alvarotrigo** [comment]
See my answer here:
https://stackoverflow.com/a/36182162/1081396

And the example here:
https://jsfiddle.net/alvarotrigo/o5ak4mgd/5/

**Comment by alvarotrigo** [comment]
@squishz yeap, solution was indeed in that line!
