### ISSUE TITLE
Cannot assign to read only property 'view' of object '#<MouseEvent>'

### ISSUE THREAD

**Issue by Menshykov** [alvarotrigo/fullPage.js#3409]
I have a problem with clicking on area (div) wrapped in .fp-scroller
extension text in console:

> Uncaught TypeError: Cannot assign to read only property 'view' of object '#<MouseEvent>'
    at Object.o.click (scrolloverflow.js:273)
    at n._end (scrolloverflow.js:629)
    at n.handleEvent (scrolloverflow.js:1618)
o.click @ scrolloverflow.js:273
_end @ scrolloverflow.js:629
handleEvent @ scrolloverflow.js:1618

It's only if i use site in mobile mode. Desktop mode all is ok. 

I can provide link to the official website where this problem is demonstrated but i don't know what is isolated link?

1. Open site on mobile device or developer mode in chrome (for example iphone X)
2. sliding to section which wrapped in class .fp-scroller
3. click on any place or links on the slide and get an error that I wrote above

google chrome in developer mode on mobile device or real device for example Iphone

**Comment by alvarotrigo** [comment]
Sorry but I'll need an isolated reproduction. 

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by brycebenson** [comment]
I am having the same issue, but I don't have time currently to create an isolated reproduction. For those wondering, removing 'strict mode' will allow clicks to work again within the `fp-scroller` area.

**Comment by servetoz** [comment]
I had same issue. I fixed it so,
In https://github.com/alvarotrigo/fullPage.js/blob/650d52f83f3d702a8ff52673fd05a1a28cea497f/vendors/scrolloverflow.js#L271
Change it like so;
`if ( !(/(SELECT|INPUT|TEXTAREA)/i).test(target.tagName) ) {
				// https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/initMouseEvent
				// initMouseEvent is deprecated.
				if (window.MouseEvent) {
					ev = new MouseEvent('click',{
						bubbles: true,
						cancelable: true,
						view: e.view || window,
						detail: 1,
						screenX: target.screenX || 0,
						screenY: target.screenY || 0,
						clientX: target.clientX || 0,
						clientY: target.clientY || 0,
						ctrlKey: !!e.ctrlKey,
						altKey: !!e.altKey,
						shiftKey: !!e.shiftKey,
						metaKey: !!e.metaKey,
						button: 0,
						relatedTarget: null,
						_constructed: true
					});
				} else {
					ev = new Event('click',{
						bubbles: true,
						cancelable: true,
						view: e.view || window,
						detail: 1,
						screenX: target.screenX || 0,
						screenY: target.screenY || 0,
						clientX: target.clientX || 0,
						clientY: target.clientY || 0,
						ctrlKey: !!e.ctrlKey,
						altKey: !!e.altKey,
						shiftKey: !!e.shiftKey,
						metaKey: !!e.metaKey,
						button: 0,
						relatedTarget: null,
						_constructed: true
					});
				}
				// ev = document.createEvent(window.MouseEvent ? 'MouseEvents' : 'Event');
				// ev.initEvent('click', true, true);
				// ev.view = e.view || window;
				// ev.detail = 1;
				// ev.screenX = target.screenX || 0;
				// ev.screenY = target.screenY || 0;
				// ev.clientX = target.clientX || 0;
				// ev.clientY = target.clientY || 0;
				// ev.ctrlKey = !!e.ctrlKey;
				// ev.altKey = !!e.altKey;
				// ev.shiftKey = !!e.shiftKey;
				// ev.metaKey = !!e.metaKey;
				// ev.button = 0;
				// ev.relatedTarget = null;
				// ev._constructed = true;
				target.dispatchEvent(ev);`

**Comment by alvarotrigo** [comment]
I can't reproduce that on the [scrollOverlow demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html).

Any link where we can do it? Device, browser an OS?
