### ISSUE TITLE
fp-scroller scrolling independently / fp-scrollable viewport not constraining

### ISSUE THREAD

**Issue by hholmes98** [alvarotrigo/fullPage.js#3410]
I've just started seeing strange behavior in a 1 section, 3 slide setup. I can't tell if its due to the new Chrome 69 (I first spotted it on an iPhone, Chrome / Safari). I can reproduce it everywhere -- but I'm nearly certain I *never* saw this behavior until now!

I'm not even sure this is a bug, and I'm afraid I might be too green to even try to explain what's happening. Instead, I've made a video of what's going on. 

https://send.firefox.com/download/292aaee448/#9UIMWS41tPSCjOscM4tMrg - good for 24 hrs / 20 DLs
(Feel free to recommend a better place to host files like this)

If its not a bug and really something I did, I'm happy to take this to SO -- but thought I would show it here first.

Properties
==

```
        animateAnchor: false,
        controlArrows: false,
        scrollOverflow: true,
         scrollOverflowOptions: {
           scrollbars: false,
           bounce: false,
           momentum: false,
           fadeScrollbars: false,
           disableTouch: true
         },
        responsiveWidth: 2000,
        autoScrolling: true,
        recordHistory: true,
        verticalCentered: false,
        fitToSection: false,
        keyboardScrolling: false,
        bigSectionsDestination: "top",
        anchors:['list'],

```
API Calls
==

```
      fullpage_api.setAllowScrolling(false, 'left, right'); 
      fullpage_api.setKeyboardScrolling(false, 'left, right');
```

...**and** I do process data in the ```afterRender()``` method (its what loads the list of buttons you see on the 2nd slide in the linked video)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
