### ISSUE TITLE
change of orientation and scrollOverflow: true causing false positioning

### ISSUE THREAD

**Issue by alexpichler** [alvarotrigo/fullPage.js#3411]
When using scrollOverflow:true and you change the orientation from portrait to landscape the wrappers for the scrollOverflow (fp-scrollable, fp-scroller) are added, altough the content is not higher than the viewport. This only happens the first time. 

1. Open the page on phone in portrait mode
2. Change the orientation to landscape. Now the <divs> are added.
3. Change back to portrait -> Everything is fine again.
4. Change back to landscape -> Everything is fine.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
I can not reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
