### ISSUE TITLE
fullpage.js laravel mix via webpack 

### ISSUE THREAD

**Issue by PankovAlxndr** [alvarotrigo/fullPage.js#3412]
I can not connect a fullpage to a project on laravel

i see this error:
>app.js:4301 jQuery.Deferred exception: $(...).fullpage is not a function TypeError: $(...).fullpage is not a function
>app.js:11143 Uncaught TypeError: $(...).fullpage is not a function`

webpack.mix.js:

```javascript
mix.js(['resources/js/app.js'], 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .copyDirectory('resources/img', 'public/img')
    .browserSync('slon.loc');`


resources/js/app.js:

```javascript
require('./bootstrap');
$(document).ready(function () {
    $('.js-fullpage').slick();
    $('.js-fullpage').fullpage();
});
```

resources/js/bootstrap.js:
`try {`
   `window.$ = window.jQuery = require('jquery');`
    `require('fullpage.js'); // error`
    `require('slick-carousel'); //work perfect`
`} catch (e) {}`
`window.axios = require('axios');`
`window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';`
`let token = document.head.querySelector('meta[name="csrf-token"]');`
`if (token) {`
    `      window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;`
`} else {`
    `console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');`
`}`

Laravel 5.7

my package.json
`{`
`    "private": true,`
`    "scripts": {`
`        "dev": "npm run development",`
`        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --`progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",`
`        "watch": "npm run development -- --watch",`
`        "watch-poll": "npm run watch -- --watch-poll",`
`        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-`dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",`
`        "prod": "npm run production",`
`        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"`
`    },`
`    "devDependencies": {`
`        "axios": "^0.18",`
`        "browser-sync": "^2.24.7",`
`        "browser-sync-webpack-plugin": "2.0.1",`
`        "cross-env": "^5.1",`
`        "laravel-mix": "^2.0",`
`        "lodash": "^4.17.5",`
`        "svg-spritemap-webpack-plugin": "^1.2.0"`
`    },`
`   "dependencies": {`
`        "bootstrap-4-grid": "^2.4.1",`
`        "fullpage.js": "^3.0.2",`
`        "jquery": "^3.3.1",`
`        "normalize.css": "^8.0.0",`
`        "slick-carousel": "^1.8.1"`
`    }`
`}`

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
