### ISSUE TITLE
Navigation not working after destroy and reload

### ISSUE THREAD

**Issue by LukeCarlThompson** [alvarotrigo/fullPage.js#3413]
After destroying via fullpage_api.destroy('all'); and then initialising a new fullpage the navigation dots don't work anymore. The pages still work via the mousewheel but not when clicking on the navigation dots. When using the navigation dots the classes are applied to the DOM but the translate3d does not update so the slides don't move.

Here is a codepen with the issue isolated.
https://codepen.io/Luke_Carl_Thompson/pen/GXXmVz

Step 1. Run the codepen.

Step 2. Click on the destroy button in top left. This runs fullpage_api.destroy('all');

Step 3. Click on the new button in top left. This runs a new fullpage function.

Step 4. click on the navigation dots on the left. Page won't scroll.

Tested on Safari V11.1.2 and Chrome V69.0.3497.92

Unless I'm misunderstanding something about how to destroy and recreate fullpage it appears like there is a bug.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll take a look at it!

**Comment by LukeCarlThompson** [comment]
No worries. Thanks for making and maintaining such a great library!

**Comment by alvarotrigo** [comment]
Oh, this issue was already solved on [the dev branch](https://github.com/alvarotrigo/fullPage.js/tree/dev) some time ago. See how it works correctly with fullpage.js 3.0.3:
https://codepen.io/alvarotrigo/pen/QVZLze

I'll mark it as fixed. The solution will get merged on the next release.

**Comment by alvarotrigo** [comment]
Fixed in the latest version 3.0.3
