### ISSUE TITLE
scrollOverflowOptions can't click checkbox inputs (on Mobile only)

### ISSUE THREAD

**Issue by bandaber** [alvarotrigo/fullPage.js#3414]
I have a big problem with the "scrollOverflow=true" function.

To fix the problem with the checkbox (on Mobile only) I need to use:

```
scrollOverflowOptions: {
	click:false
}
```

But if I use this setting > I have another problem.
The normal a-tags doesn't work anymore inside the scroll area...

And if I use:

```
scrollOverflowOptions: {
		preventDefaultException: {
            tagName: /.*/
        	}
        }
```

I can't scroll anymore...

How can I fix this guys?

```
<script>
    var myFullpage = new fullpage('#fullpage', {
        anchors: ['home', 'transactions', 'contact'],
        sectionsColor: ['#c1bca6', '#22283a', '#c1bca6'],
		menu: '#menu',
        navigation: true,
        navigationPosition: 'right',
	slidesNavigation: true,
	scrollOverflow: true,
	scrollOverflowReset: true,
	scrollOverflowOptions: {
		click:false
         },
	scrollOverflowResetKey: 'XXXXXXXXXXX'
	});
</script>
```

**Comment by alvarotrigo** [comment]
Have you considered using both? `click:false' and `preventDefaultException `?

See this answer:
https://github.com/alvarotrigo/fullPage.js/issues/2837

**Comment by bandaber** [comment]
Yes, sadly it doesn't work.
Same problem: I can't scroll anymore inside the "scrollOverflow" section.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction of the issue with no external CSS and JS to fullpage.js and the minimum amount of HTML code possible? Use empty sections with a inputs on them.

**Comment by bandaber** [comment]
Of course I can dot it. But first, I have a new insight:

The combination of using both => fix the problem. BUT
I only can scroll (on Mobile) across the scroll bar > NOT anymore with normal touch function, what you typical use at a smartphone.

Maybe is there a setting option for it? Something like "mouseWheel: true" ?
Otherwise I will send you the code...

**Comment by alvarotrigo** [comment]
I'll wait for the isolated reproduction.

**Comment by bandaber** [comment]
[Here](http://sealdeal.oneyearagotoday.de/index2.php) you can see the problem.
If I use
```
scrollOverflowOptions: {
			click: false,
			preventDefaultException: { tagName:/.*/ }
		}

```

The problem with the checkbox and a-tags is fixed. Thats why I delete the form.
But now you only can scroll (on Mobile) across the scroll bar > NOT anymore with normal touch/swipe method.

**Comment by alvarotrigo** [comment]
Fixed in v4! 👍
