### ISSUE TITLE
Tilting scroll when reaching bottom of page/overflowed slide

### ISSUE THREAD

**Issue by jscti** [alvarotrigo/fullPage.js#3415]
### Description
On Firefox@Mac page is trembling when trying to overscroll when the bottom of the page is reached on a slide that has overflowed content.
Bug not reproducted on iScroll demos.

### Link to isolated reproduction with no external CSS / JS
Reproduction: https://codepen.io/anon/pen/rZQmBP
Video : https://media.giphy.com/media/1BGgYQNHyudh5EW9Nz/giphy.gif

### Steps to reproduce it
1. On firefox, navigate to the second slide, reach its bottom, and try to scroll some more to the bottom (overscroll), there the page is all trembling

### Versions 
Bug on Firefox 62.0 and MacOS 10.13.6
Not reproducted on MAC with Chrome / Safari
Not reproducted on Windows 10 with Firefox

**Comment by alvarotrigo** [comment]
Thanks for reporting it! I was able to reproduce it. 

It only takes place when there are no more sections underneath right?

**Comment by alvarotrigo** [comment]
Fixed! 
It should be merged in the next fullpage.js release version 3.0.5

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
