### ISSUE TITLE
scroll

### ISSUE THREAD

**Issue by meteoros** [alvarotrigo/fullPage.js#3416]
my fullpage is divide by two 50vh each,on mobile when page goes down upper part is bigger when the page goes up the opposite happens in opera,edge and chrome,in firefox works well

![screenshot_20180920-101938](https://user-images.githubusercontent.com/10812572/45811515-36df8e80-bcc5-11e8-8b52-b8ffc50ee25c.jpg)
![screenshot_20180920-102010](https://user-images.githubusercontent.com/10812572/45811517-36df8e80-bcc5-11e8-8399-b05cfad8e543.jpg)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
Sorry. Without isolated reproduction I can not help.

**Comment by meteoros** [comment]
Thanks any way
