### ISSUE TITLE
Fullpage - bug on Edge - Object doesn't support property or method 'ScrollTo'

### ISSUE THREAD

**Issue by pharemedia-alex** [alvarotrigo/fullPage.js#3417]
Go to this official demo of Fullpage on Microsoft Edge (bug happens on other versions too): https://alvarotrigo.com/fullPage/examples/methods.html

### Steps to reproduce it
1. click on Destroy('all')
2. Check the browser console for the bug

### Versions 
Any PC with Microsoft Edge, I have tested 2 versions on BrowserStack, same bug.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Seems to be related with [some IE bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15534521/)

But I'll see what can I do.

**Comment by alvarotrigo** [comment]
I've fixed it on the [dev branch 3.0.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js)

To be merged in the next release!

**Comment by pharemedia-alex** [comment]
Great thanks!

**Comment by alvarotrigo** [comment]
Fixed in the latest version 3.0.3

**Comment by splex7** [comment]
Oh! What a good news. I got the same problem in the version 3.0.2. Thank you
