### ISSUE TITLE
The video is pause when I scroll back to the video section

### ISSUE THREAD

**Issue by lxgiang90** [alvarotrigo/fullPage.js#3418]
Hello alvarotrigo.
In the video section.
How to scroll to another section and scroll back to where the video is always pause.
Even when playing video in the video section and then scroll to another section and scroll back, the video is still pause.
Thank you somuch !

**Comment by alvarotrigo** [comment]
Working totally fine for me:
https://jsfiddle.net/ea17skjr/30/

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by lxgiang90** [comment]
Thanks for answering.
I want to scroll to video section, video is stop.
Then I scroll to another section, and scroll back to the video section, I still want the video to stop and not auto play.
Is there a way to help me do this?
That is, it always stops, only when click on the play button, the new video runs.
Thank so much :) .

**Comment by alvarotrigo** [comment]
Do not add the `data-autoplay` attribute and fullPage.js won't play it when landing on its section/slide.

```javascript
        <video width="400" controls  data-autoplay muted>
``` 
vs
```javascript
        <video width="400" controls  muted>
```
