### ISSUE TITLE
Bought the FadingEffect extension but can't find the file for this extension?

### ISSUE THREAD

**Issue by webstories** [alvarotrigo/fullPage.js#3420]
I Bought the FadingEffect extension but nowhere I can find the extension file for the FadingEffect? Not in mails nor in github? Where can I find this file? I read about fullpage.continuousHorizontal.min.js but the fadingEffect file is nowhere to find?

**Comment by alvarotrigo** [comment]
You'll find a link to download it in the purchase confirmation email from Gumroad that contains the receipt. 

Also, you got a link to it right after the purchase, where you could have downloaded it. 

> I read about fullpage.continuousHorizontal.min.js but the fadingEffect file is nowhere to find?

That's just an example. As if you purchased continuousHorizontal.
