### ISSUE TITLE
too much recursion in firefox when usen callback onLeave 

### ISSUE THREAD

**Issue by webstories** [alvarotrigo/fullPage.js#3421]
I'm getting too much recursion in firefox and call stack exceeded in Safari when scrolling down and trying to call the onleave and change the fadingEffect to $.fn.fullpage.fadingEffect.turnOff();

Only in Chrome it works. 

Here's my code:

`$('#fullpage').fullpage({
          licenseKey: '285E5D71-D9E346C8-8BADA867-30AB58FD',
          responsiveHeight: 330,
          css3: true,
         scrollingSpeed: 1200,
         slidesNavigation: false,
         controlArrows: true,
            navigation: true,
            scrollOverflow:true,
            navigationPosition: 'right',
            fadingEffectKey: 'd2F0ZXJmcm9udHdhcmVnZW0uYmVfMGJ4Wm1Ga2FXNW5SV1ptWldOMGpPNg==',
            fadingEffect:false,
          /*  afterLoad: function(anchorLink, index){
                  var loadedSection = index["index"];

               if (loadedSection != 3)  {

                            setTimeout(function(){$.fn.fullpage.fadingEffect.turnOff();},200);

                  }
                  if (loadedSection != 4)  {

                              setTimeout(function(){$.fn.fullpage.fadingEffect.turnOff();},200);

                   

              },}*/
              onLeave: function(index1, nextIndex, direction) {

              index = index1["index"];

            /*  if (index == 2 && direction == 'down' && !hasBeenChanged) {
                  $("#trans2").addClass("transition");
                    $("#trans1").addClass("transition");
              }*/

              if (index == 1 && direction == 'down' && !hasBeenChanged) {
                  $.fn.fullpage.fadingEffect.turnOn();
                  hasBeenChanged = true;
                  return !hasBeenChanged;
              }

              if (index == 4 && direction == 'up' && !hasBeenChanged) {
                  hasBeenChanged = true;
                  $.fn.fullpage.fadingEffect.turnOn();
                  return !hasBeenChanged;
              }
              hasBeenChanged = false;

          }

        });`

**Comment by webstories** [comment]
Found already a part of the issue. When you use scrolloverflow and you have elements outside the section view and you fire this event: $.fn.fullpage.fadingEffect.turnOn; it gives you max stack exceeded or too much recursion.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by webstories** [comment]
Here you can find de fiddle:   https://jsfiddle.net/97apLf1b/

As you will see, the last section has more data than the full screen height. 
So when scrolling once down, then you click on the body and next the fading effect doesn't appear but gives error in the background.

**Comment by alvarotrigo** [comment]
Ok thanks I'll check it out!

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with the email you used for the purchase. I'll send you the fixed version of the fading effect extension.

**Comment by webstories** [comment]
Hi,

I’ve sent the purchase mail to you as requested.

Met vriendelijke groeten,	
 
Jasper Van Braekel
Zaakvoerder
 
+32 494 77 22 61 <tel:+32494772261>
jasper@kuduconcepts.be <mailto:jasper@kuduconcepts.be>
 
 <http://www.kuduconcepts.be/>
 
Kattestraat 62, 8520 Kuurne
www.kuduconcepts.be <http://www.kuduconcepts.be/>
