### ISSUE TITLE
Issue with parallex and scrolloverflow on ie

### ISSUE THREAD

**Issue by johanvdr** [alvarotrigo/fullPage.js#3423]
These are my settings:

```
$('#homeslider').fullpage({
			anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourth', 'fifth', 'sixth', 'secenth'],
		 	licenseKey: '....',
			parallax: true,
			parallaxKey: '...',
			loopHorizontal: false,
			scrollOverflow: true,
			autoScrollingHorizontally:false,
			scrollHorizontally: true,
			scrollHorizontallyKey: '...',
});
```

Problem I got was when scrollOverflow was true the slides weren't rendered correctly. De second slide overlapped the 1st slide for a big part. this problem only occurs in IE 11. I've fixed this by adding these CSS styles:
```
.section.active .fp-bg{
	z-index: 1!important;
}
.section.active .slide.active{
	z-index: 2!important;
}
```

### Versions 
IE11, Windows 10

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with the isolated reproduction.

**Comment by johanvdr** [comment]
Thnx! This problem has been solved in the latest version.
