### ISSUE TITLE
Issues with Pop-Up and Scrolling behind

### ISSUE THREAD

**Issue by elpaulli** [alvarotrigo/fullPage.js#3424]
I have attempted a few solutions and looked through the issues quite a bit, and I might be missing something. 
I am using a Lightbox plugin, MagnificPopup to display images and if you scroll with the mouse or keyboard the slide behind the image pop up changes. 
I have tried to using the 
normalScrollElements: '.mfp-fade' or the div class of the that the popup displays in. This works to stop the mouse scrolling, however when I close the popup mouse scrolling is now disable through the rest of the site. 

Also I have attempted use setAllowScrollingFalse you have listed here,but there is no click to start the function, and if I use load or something else nothing happens.  https://alvarotrigo.com/fullPage/examples/methods.html - 

document.querySelector('#setAllowScrollingFalse').addEventListener('click', function(e){
  | e.preventDefault();
  | fullpage_api.setAllowScrolling(false);
  | });

However, and this might be my lack of JS knowledge, I can seem to link the scrolling the to pop-up. 

I will work on a simplify the code I am using and creating a codepen example. But I am not a 100% sure if I will be able to replicate the issue. 

I am still learning JS so I think my issue might be that I am just not capable of adding the function setAllowScrolling(false) when opening the popup and setAllowScrolling(true) when closing it.
Any help would be great!

**Comment by elpaulli** [comment]
Solved it. Found an old post from 2013, and used there solution.

**Comment by alexandru-burca** [comment]
> Solved it. Found an old post from 2013, and used there solution.

could you please share the solution here as well? thanks
