### ISSUE TITLE
When scrolling through slides, how to always start from the top of the content?

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3428]
If I have four slides for example, on of them I have scrolled down half way. When I return to that slide it is still half the way down. Is it possible to always start the slides at the top? I do not want the slide to remain when the user had scrolled down to.

**Comment by alvarotrigo** [comment]
I assume you are talking about using the option `scrollOverflow:true`.

You can use the extension [ScrollOverflow Reset](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html) for that matter. Just purchase it and follow the docs regarding [how to use fullPage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions)

**Comment by AmanSahota** [comment]
Yes this is regarding `scrolloverflow: true`.

As you can see in the example I have scrolled down. However, everytime I come back to this slide the scrollbar is at the bottom. I would like it to reset to the top as soon as I leave. Is this possible?

<img width="1588" alt="screen shot 2018-09-28 at 08 39 19" src="https://user-images.githubusercontent.com/6698804/46194769-416bda80-c2fa-11e8-9660-557fb4b19f47.png">

**Comment by alvarotrigo** [comment]
As i said:

You can use the extension [ScrollOverflow Reset](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html) for that matter. Just purchase it and follow the docs regarding [how to use fullPage.js extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions)

**Comment by AmanSahota** [comment]
Hi there we have purchased the plugin. However, I need to know if this is correct?

`$(document).ready(function() {
			$('#fullpage').fullpage({
				anchors: ['firstSection', 'personaSection'],
				sectionsColor: ['black', 'black', 'black'],
				// Activates original scrollbar
				controlArrows: false,
				scrollOverflow: true
			});

			new fullPage('#fullpage', {
			    scrollOverflowReset: true,
			    scrollOverflowResetKey: 'KEY GOES HERE',
			});
		});`

**Comment by alvarotrigo** [comment]
Not correct.

Use only one initialisation. 

```javascript
			new fullPage('#fullpage', {
				anchors: ['firstSection', 'personaSection'],
				sectionsColor: ['black', 'black'],
				controlArrows: false,
				scrollOverflow: true
			        scrollOverflowReset: true,
			        scrollOverflowResetKey: 'XYZ'
			});
```

**Comment by alvarotrigo** [comment]
Make sure you are using  the latest fullpage.js version 3. 
Also, better if you just place the code after including fullpage.js, as it is in in all the examples in this repository:

<script type="text/javascript" src="js/fullpage.scrollOverflowReset.min.js"></script>
<script type="text/javascript" src="js/fullpage.extensions.min.js"></script>
<script>
new fullPage('#fullpage', {
				anchors: ['firstSection', 'personaSection'],
				sectionsColor: ['black', 'black'],
				controlArrows: false,
				scrollOverflow: true,
			       scrollOverflowReset: true,
			       scrollOverflowResetKey: 'MY KEY'
			});
</script>

**Comment by AmanSahota** [comment]
Do I still need to include "jquery.fullPage.js" too?

**Comment by alvarotrigo** [comment]
No. Just look at the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). You'll find there all you need to know about fullPage.js usage. And you won't see there anything at all about jquery.fullPage.js

**Comment by AmanSahota** [comment]
Hi, apologies.

I have just checked everything, and it sits as follows just before the <body> tag:

```
<script type="text/javascript" src="js/fullpage.scrollOverflowReset.min.js"></script>
<script type="text/javascript" src="js/fullpage.extensions.min.js"></script>
<script type="text/javascript" src="js/fullpage.js"></script>
<script type="text/javascript" src="js/scrolloverflow.min.js"></script>

<script>
		$(document).ready(function() {
			new fullPage('#fullpage', {
				anchors: ['firstSection', 'personaSection'],
				sectionsColor: ['black', 'black'],
				controlArrows: false,
				scrollOverflow: true,
			    scrollOverflowReset: true,
			    scrollOverflowResetKey: 'XXX'
			});
		});

		// Go directly to persona via menu
		$(document).on('click', '#matt', function(){
		  fullpage_api.silentMoveTo('personaSection', 0);
		});
		$(document).on('click', '#ricciardo', function(){
		  fullpage_api.silentMoveTo('personaSection', 1);
		});
		$(document).on('click', '#henrik', function(){
		  fullpage_api.silentMoveTo('personaSection', 2);
		});
		$(document).on('click', '#gregory', function(){
		  fullpage_api.silentMoveTo('personaSection', 3);
		});
</script>
```

I am using fullPage 3.0.3. As soon as I add the new `new fullPage('#fullpage'` code it breaks and the section colours disappear.

**Comment by alvarotrigo** [comment]
Please read the instructions regarding how to use extensions in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

This is wrong;:

```html
<script type="text/javascript" src="js/fullpage.scrollOverflowReset.min.js"></script>
<script type="text/javascript" src="js/fullpage.extensions.min.js"></script>
<script type="text/javascript" src="js/fullpage.js"></script>
<script type="text/javascript" src="js/scrolloverflow.min.js"></script>
```

**Comment by AmanSahota** [comment]
I just had a read through. based on this section 

> Extensions requires you to use the minified file fullpage.extensions.min.js that is inside the dist folder instead of the usual fullPage.js file (fullpage.js or fullpage.min.js).

I have removed fullPage.js which leaves me with this:

```
<script type="text/javascript" src="js/fullpage.scrollOverflowReset.min.js"></script>
<script type="text/javascript" src="js/fullpage.extensions.min.js"></script>
<script type="text/javascript" src="js/scrolloverflow.min.js"></script>
```

This is the only thing I can see which I need to change?

**Comment by olsp** [comment]
@AmanSahota could you solve this? I may have the same problem ...

**Comment by AmanSahota** [comment]
Yes. You will need the extension for this to work though:

```
afterSlideLoad: function(section, origin, destination, direction){
    fullpage_api.scrollOverflowReset.setPrevious(section.item);
    fullpage_api.scrollOverflowReset.reset();
}
```

**Comment by olsp** [comment]
Great, that works. Thank you!

**Comment by AmanSahota** [comment]
@alvarotrigo could we maybe have this as a feature request? Have it included as an option.. this maybe useful for some others too.

**Comment by alvarotrigo** [comment]
@AmanSahota more like a extension feature :)
I'll definitely consider adding it in the scrollOverflowReset extension!
