### ISSUE TITLE
Can I fix slide content so it's 'revealed' on scroll?

### ISSUE THREAD

**Issue by robbiew** [alvarotrigo/fullPage.js#3430]
Is it possible that when the user scrolls, it reveals fixed content underneath?
Kind of like the last slide/sequence on this page: https://helloelephant.com/

Perhaps with the parallax extension?

**Comment by alvarotrigo** [comment]
> Perhaps with the parallax extension?

Sure! Just place your content on the `<div class="fp-bg">` element.

See my article here:
https://alvarotrigo.com/blog/how-create-tumblr-website-effect/
