### ISSUE TITLE
We can't scroll up when we use "scrollOverflow: true" , pls fix it

### ISSUE THREAD

**Issue by intest200** [alvarotrigo/fullPage.js#3432]
Pls check link

at "OTRAS HISTORIAS" this section when we reach and we try to scroll up but we can't

https://www.activapyme.com/visual-comunicacion/demo/historias/

**Comment by meceware** [comment]
Hi,

fullPage: Option `scrollBar` is mutually exclusive with `scrollOverflow`.  You can disable scroll overflow since scrollbar is enabled.

**Comment by intest200** [comment]
> Hi,
> 
> fullPage: Option `scrollBar` is mutually exclusive with `scrollOverflow`. You can disable scroll overflow since scrollbar is enabled.

Thank you for reply,
Ya I know that but We have to keep that option.
so pls any solution for that

**Comment by alvarotrigo** [comment]
Unfortunately I can't seem to make any sense out of a fix. 
Having 2 scroll bars seems like **a terrible user experience**. In mac, they even overlap each others as can see in this image:

![screen shot 2018-10-02 at 11 36 53](https://user-images.githubusercontent.com/1706326/46341052-84e68180-c637-11e8-921c-2ddc6152bb90.png)

And probably the same in a mobile device.

If you need a fix for your case, I can customise fullPage.js for you, just [contact me](https://alvarotrigo.com/#contact) and I'll provide you a quote.
