### ISSUE TITLE
I cannot activate the license key 

### ISSUE THREAD

**Issue by esteban1603** [alvarotrigo/fullPage.js#3437]
Someone can help me, How can I activate the license key I couldn't find the line to write the code

**Comment by taraskhvyl** [comment]
https://github.com/alvarotrigo/fullPage.js/blob/master/README.md#options
The first option

**Comment by alvarotrigo** [comment]
Bare in mind that only extensions require activation of your license, as detailed in ["How to activate a fullPage.js extension"](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension)
The license for fullPage.js does not require you to activate it.
