### ISSUE TITLE
Unable to scroll when iFrame inside a section

### ISSUE THREAD

**Issue by PushEngineering** [alvarotrigo/fullPage.js#3439]
### Description

As previously mentioned when using iFrames inside of FullPage sections do not work when it comes to scrolling. The recommended solution was to detect scrolling inside the iFrame and deal with navigation manually that way.

However when using cross-domain iframes it is not possible to detect scrolling. 

Any other suggestions?

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/qb8yL2we/

Above example shows how you cannot scroll anywhere when iFrame is inside section.

### Steps to reproduce it
1. Add cross-domain iFrame into section content
2. Load up HTML page
3. Try and scroll past the section with iFrame content

### Versions 
FullPage v3.0.3

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2229
There's no solution I'm afraid.
