### ISSUE TITLE
Ajax jQuery stops working after resizing the screen two times.

### ISSUE THREAD

**Issue by claverwebdesign** [alvarotrigo/fullPage.js#3440]
### Description
ScrollOverflow script causes to break jQuery Ajax after resizing the browser window height 2 times (or by opening & closing your developer console which does the same). 

After removing the ScrollOverflow & ScrollOverflowReset scripts the form keeps working, even after resizing. This is why I think this must have something to do with the ScrollOverflow scripts.

### Steps to reproduce it
1. Load the page, everything works fine
2. In my case, Gravity Forms executes the following script on click: _jQuery("#gform_target_page_number_2").val("5");  jQuery("#gform_2").trigger("submit",[true]);_ 
2. Resize the screen two times in different heights.
3. The send button stops working.

### Versions 
fullPage.js: 3.0.3
ScrollOverflow: 0.1.0
ScrollOverflowReset: 0.2.0

**Comment by alvarotrigo** [comment]
Might be related with [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/3436).

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by claverwebdesign** [comment]
You are completely right. I've tested the unwrap function from the dev branche. This seems to fix the issue.

When will this be released into the fullpage.extensions.min.js? I need an updated version to make my ScrollOverflowReset work. Currently I'm using the default  fullpage.min.js with dev changes.

Perhaps is there an easy way to incorporate this fix into a fullpage.extensions.js file myself until there is a new release available? Please let me know.

**Comment by alvarotrigo** [comment]
Sure! You can try now with the extensions file in the dev branch.
I've just updated it!

**Comment by claverwebdesign** [comment]
Thanks @alvarotrigo.

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!
