### ISSUE TITLE
Scrolling porgressivly off w/ touch and external mouse, track pad cannot scroll back up

### ISSUE THREAD

**Issue by DragonINXS** [alvarotrigo/fullPage.js#3442]
### Description:
Each section seems to get progressively more off.
IE - first  section seem alright, the second seems to be not scroll down enough by 10%-ish, the third by 20%, and so on. 

Alos ai it possible to have a margin on each full page section?

### Link to isolated reproduction with no external CSS / JS
(https://codepen.io/anon/pen/WajEve#anon-signup)
(https://github.com/DragonINXS/portfolio/tree/master/portfolio-site)

### Steps to reproduce [it])
1. Seems to works best with an external mouse using the scroll wheel or using a touchscreen but still gets progressively off as you scroll down
2. Using a track pad causes more issues, inconsistent and can not scroll back up

### Versions 
[Browser, operating system, device, ...]
Firefox Developer Edition - 63.0b13 (64-bit)
Win 10 Pro - Build 17134.286
Device - SurfaceBook Performance 

First time using fullpage.js so I may be at fault.
Thanks in advance for any help!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by DragonINXS** [comment]
Also followed this for the original setup and guide.

(https://www.youtube.com/watch?v=CtPDQudzjnM)

**Comment by alvarotrigo** [comment]
> There is minimal CSS to demonstrate the issue using your tutorial template.

That's not my tutorial :)

And also, that tutorial is for version 2, not version 3 of fullpage.js.
All you need to know about fullpage.js is detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). Also, check the tens of examples available on the examples folder. You can take one of them as your starting point.
