### ISSUE TITLE
inner scroll in offset section

### ISSUE THREAD

**Issue by digitalmdma** [alvarotrigo/fullPage.js#3445]
Hi.

Sorry but I could not find a forum.

I have one question: Which extentions I need to buy if I need fullpage.js with offetSections like 60% height and there I need an inner scroll for long texts. Don't ask why - customer wish. Also it need to work mobile and by touch.

I would appreciate an answer before I spend even more money into this.

Thanks a lot guys.

Best greetings
Florian

**Comment by alvarotrigo** [comment]
For offset sections: [Offset Sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html)
For sections with bigger content than the viewport. Just use the `scrollOverflow:true` option. 
Touch works by default. However, if you prefer a much smooth touch detection, you can use the [Drag And Move extension](https://alvarotrigo.com/fullPage/extensions/drag-and-move.html).

Hope I answered all your questions! ;)
