### ISSUE TITLE
Scroll up doesn't work, when anchor is used in page url

### ISSUE THREAD

**Issue by profesionalplus** [alvarotrigo/fullPage.js#3446]
Hello,

i have a strange problem. If i open the page where fullpage is used with anchor to specific part, i can't scroll up anymore.

For example, if page is www.test.com, scrolling will work as usual. If i open www.test.com/#part-2, browser loads the page at that part and i can't scroll up.

I also noticed on your home page of fullpage.js that when you visit the page with anchor, the page is loaded and then you have smooth scroll to that part. How can i set this up? I tried adding anchors:['home-1' ,'home-whatwedo', 'home-aboutus'], but the page loads first section and when i scroll it skips home-whatwedo and goes to section home-abouts.

I can't create reproduction on codepen because the fullpage is integrated inside WP website of my client. I can, however, provide link to the page, if needed.

I hope that you can help with this, since i paid for the license and i use it on my client's website.

Thank you

**Comment by meceware** [comment]
Hi,

I think both of the things you mention works on my [home page](https://www.meceware.com/fp/#preview) with WP installed.

**Comment by taraskhvyl** [comment]
write 

`fullpage_api.setAllowScrolling(true);`

after fullpage init. it's could help

**Comment by alvarotrigo** [comment]
> I also noticed on your home page of fullpage.js that when you visit the page with anchor, the page is loaded and then you have smooth scroll to that part. How can i set this up?

That's the default behaviour. Using `animateAnchor:false` is what takes off the animation. 

> I tried adding anchors:['home-1' ,'home-whatwedo', 'home-aboutus'], but the page loads first section and when i scroll it skips home-whatwedo and goes to section home-abouts.

Make sure to not use any `id` or `name` element with the same value as any of your anchors, as detailed in the docs.

> I can't create reproduction on codepen because the fullpage is integrated inside WP website of my client. I can, however, provide link to the page, if needed.

What isolated reproduction mean is basically that. Isolate the issue from wordpress. If you can't, then I can't help. As I'm only responsible for fullpage.js and can't support external code such as Wordpress.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by profesionalplus** [comment]
Hello @alvarotrigo ,

thank you for the fast reply. It turns out that the only problem was the fact that anchor names were the same as my ids. That's why fullpage was going crazy and skipping sections.

Maybe you should add this information  inside the docs, that section anchors should differ from ids of the sections, if you haven't added this already?

Thank you again for the support.


Best regards
