### ISSUE TITLE
Licence key

### ISSUE THREAD

**Issue by KirstenStemmet** [alvarotrigo/fullPage.js#3452]
I've read your documentation and it isn't very clear on how to use your licence, will you please be so kind as to help me? Bc the link you are giving me doesn't say much?

**Comment by KirstenStemmet** [comment]
Or could you give me your email to get hold of you please

**Comment by alvarotrigo** [comment]
Really?
What is not clear about this?

> Options
licenseKey: (default null). This option is compulsory. If you use fullPage in a non open source project, then you should use the license key provided on the purchase of the fullPage Commercial License. Otherwise, you can use the string OPEN-SOURCE-GPLV3-LICENSE. Please read more about licenses here and on the website. For example:

```javascript
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});```

**Comment by KirstenStemmet** [comment]
Bc my team and I don't know where to place it? I genuinely need help please, if that would be possible

**Comment by alvarotrigo** [comment]
I guess I'll have to quote myself again?

```javascript
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
```

**Comment by alvarotrigo** [comment]
It is just another fullPage.js option. 
Please read the docs regarding how to use and pass options to fullPage.js.

**Comment by KirstenStemmet** [comment]
I've read your docs over and over and that's all it says?
I'd just like to know how to insert it, I'm not trying to be funny

**Comment by KirstenStemmet** [comment]
I wouldn't ask for help for you to just keep posting the same thing I'm able to read on the docs

**Comment by KirstenStemmet** [comment]
Where do I put it in my react code? in and componentWillMount()? It's not very clear

**Comment by KirstenStemmet** [comment]
So you just aren't going to respond?

**Comment by alvarotrigo** [comment]
Right I see. So your question is mainly how to pass fullPage.js options to the react component.

See how to pass fullPage.js options in the example provided in the react component:
https://github.com/alvarotrigo/react-fullpage/blob/master/example/src/index.js#L17

**Comment by KirstenStemmet** [comment]
Thank you for your patients, I got it
