### ISSUE TITLE
Lazy Loaded Video on iPhone doesn't play when scrolling to next section BEFORE video fully loaded

### ISSUE THREAD

**Issue by claverwebdesign** [alvarotrigo/fullPage.js#3453]
### Description
Lazy Loaded Video on iPhone doesn't play when scrolling to next section BEFORE video fully loaded

### Steps to reproduce it
1. Go to section with video
2. Lazy load starts downloading the Video
3. User scrolls to next section before video loads
4.  User returns to this section
5. Video will never initialize again

### Versions 
Fullpage.js 3.0.4 (dev)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll take a look at it whenever I can!

**Comment by claverwebdesign** [comment]
I've found out that video's are being triggered again when I used the pagination bullets to navigate to the slide. 

Swiping to the slide doesn't trigger to load them again.

Could there be a difference in Logic that helps the video's restart when navigating with the Pagination Bullets?

**Comment by claverwebdesign** [comment]
Hi @alvarotrigo ,

I've managed to create a working simulation with the same problem: https://codepen.io/claverwebdesign/pen/JmMwOP 

Note that swiping on real iPhone devices cause the video to freeze.

Steps to see the bug:
1. Only use swipe
2. Go to next section
3. Video doesn't play
4. Go to next section by swipe --> next video doesn't play
5. Video's will never play until
l next page refresh.

When navigating with the "navigation dots" or "next button" everything works fine.

**Comment by claverwebdesign** [comment]
Hi @alvarotrigo ,

I've also found out that the developer console outputs this "intervention" once I debug for iPhones: 

**fullpage.extensions.min.js?ver=3.0.4:8 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080**

**Comment by claverwebdesign** [comment]
Hi @alvarotrigo,

Have you seen my Codepen with the isolated problem? 

- Swiping causing the video to break
- Navigating through bullet points restarts the video properly and play

Thanks in advance.

**Comment by alvarotrigo** [comment]
> Have you seen my Codepen with the isolated problem?

I haven't checked it yet.

**Comment by alvarotrigo** [comment]
I've looked into this issue but I don't really know which is the problem you are reporting.

- Videos won't autoplay in mobile devices (or at least in some major browsers)
- The video seems to be lazyLading correctly.
- The video seems to be autoplaying correctly (when using the `muted` attribute as expected)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
