### ISSUE TITLE
Actualize scroll in section after CSS event

### ISSUE THREAD

**Issue by AntoineBourin** [alvarotrigo/fullPage.js#3455]
Hey Guys,

I'm using since few days Fullpage.js and I've encountered a little problem with my app. 
I've got a section with a vertical scroll added automatically by fullpage but, inside of it, I have 1 CSS animation. The problem is that when a user click on a button, a block in my section is closed and the height of my section is reduced immediatly but not the scrollbar.
So, after the close of this element, the scrollbar stay with the previous height and a white space appear in my section. 

Can I, in JS for example, actualize the scroll of Fullpage.js to take the new height of my section and don't keep a white space ? 
It can be also reproduce if you want to hide a block in your sections on loading page and after, display it when the user clicked on a button. The scroll stay with the same height, and a part of my content is hidden... 

Thanks in advance for your help! :)

**Comment by alvarotrigo** [comment]
> The problem is that when a user click on a button, a block in my section is closed and the height of my section is reduced immediatly but not the scrollbar.

Use the `reBuild` method you can find on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
