### ISSUE TITLE
Disable onLeave events if button is clicked

### ISSUE THREAD

**Issue by made-dev** [alvarotrigo/fullPage.js#3457]
I have a 4 section page that I'm using onLeave callbacks on to morph an SVG into different shapes as you swipe up and down.

I need to also link to each section in the menu (similar to demos) and have the SVG morph to the appropriate shape. Since I'm using origin and direction [code below] in the callbacks, the menu links don't know when you're jumping around (going from section 1 to section 4).

```
onLeave: function(origin, destination, direction){
	if(origin.index == 0 && direction =='down'){
		shapeMorph1down.play(0);
	}
	else if(origin.index == 1 && direction == 'up'){
		shapeMorph1down.reverse();
	}
}
```

Is there a function to disable the onLeave callbacks temporarily? If a button is clicked for example?

**Comment by alvarotrigo** [comment]
> Is there a function to disable the onLeave callbacks temporarily? If a button is clicked for example?

Just use a global state variable to do so:


onLeave: function(origin, destination, direction){
    if(onLeaveIsEnabled){
	if(origin.index == 0 && direction =='down'){
		shapeMorph1down.play(0);
	}
	else if(origin.index == 1 && direction == 'up'){
		shapeMorph1down.reverse();
	}
   }
}

**Comment by alvarotrigo** [comment]
And update the variable on any action you need.
