### ISSUE TITLE
Video Resize Issue with Chrome Browser

### ISSUE THREAD

**Issue by slickrick13** [alvarotrigo/fullPage.js#3458]
### Description
Hi, 
i created a little website using normal sections and slides and just one video background section at the end. All is working like a charm but when i start the video in the Chrome browser the video expands itself over the other sections. I have to reload the page to reset everything. The funny thing is that it´s working flawlessly with firefox and safari.
Sorry for my bad english.

### Link to isolated reproduction with no external CSS / JS
I´ll try to isolate the code but i really dont know how. It´s that much JS and CSS and the problem could be everywhere. So i do post the link to the webpage. If you are not willing to help or just dont have the time to go thru, then just delete this post. Nevermind. Cheers. 
http://superflow3000.com/URC2/page/index.html#3rdPage

### Steps to reproduce it
Open in Chrome
1. Go to http://superflow3000.com/URC2/page/index.html#3rdPage
2. Scroll down to the Video
3. press play to start the video
4. scroll up or down and you´ll see the issue
5. increase or decrease the browser window

### Versions 
Chrome - Version 70.0.3538.67 
Firefox - Version 62.0.3 (64-Bit) 
Safari - Version 12.0 (13606.2.11) 

System: MacOS High Sierra 10.13.6 , Macbook Pro Retina 15"

**Comment by alvarotrigo** [comment]
> I´ll try to isolate the code but i really dont know how. It´s that much JS and CSS and the problem could be everywhere.

Sorry I do not check specific use cases or sites. 
I only take care of fullpage.js code, therefore all unnecessary code for the reproduction should vanish so I can check the issue. 

I only provide premium support for people who purchased the Organization license. More info on the [pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by slickrick13** [comment]
ok. thx
