### ISSUE TITLE
normalScrollElements not working on smartphone

### ISSUE THREAD

**Issue by futurewebEubling** [alvarotrigo/fullPage.js#3459]
Within my project there is an element with CSS "overflow-y: auto". I have written this element within the "normalScrollElements" option and i have configured the "normalScrollElementTouchThreshold" option as mentioned in the documentation.
Scrolling works fine on desktop, but it doesn't seem to work on mobile devices.
I'm really sorry, but this issue is not reproducible in jsfiddle.net! So here is the link to my project: http://www.baumeisterhaus.at.ex.ortsinfo.at/

I hope you are so kind to check out my issue, although it has not been reproduced in jsfiddle.net...

Steps to reproduce it:

1. Click the detail button in the lower left corner
2. Try to scroll the overflowing text (right on desktop, overlay on mobile device)

Versions:

- PC, Windows 10, Mozilla Firefox Developer Edition 64.0b1 & Google Chrome 69.0.3497.100
- Samsung Galaxy s8/Huawei P8 Light/LG Nexus 5x, Android 8.0.0/8.1.0/6.0, Mozilla Firefox, Google Chrome, Samsung Internet Browser

**Comment by alvarotrigo** [comment]
> I'm really sorry, but this issue is not reproducible in jsfiddle.net! So here is the link to my project: http://www.baumeisterhaus.at.ex.ortsinfo.at/

You'll have to isolate the problem. Remove any CSS or JS files external to fullPage.js and use the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by futurewebEubling** [comment]
I can't isolate the problem, because it is working fine in jsfiddle.

Luckily, I found a solution after trying for several hours!
In the option "normalScrollElements" I have to specify every possible HTML tag like p, a, strong etc. whitin my scrollable div. It seems like I have to specify every tag, which can directly be touched on mobile devices.

Have you ever heared about a behaviour like this?
Is there any way to simplify the option or to group those elements?

**Comment by alvarotrigo** [comment]
> Have you ever heared about a behaviour like this?
Is there any way to simplify the option or to group those elements?

It shouldn't be necessary. Just the scrollable element should be enough.

**Comment by futurewebEubling** [comment]
It won't work within my programming environment...

Anyways, it works fine with my workaround!

Thank you for your support!
