### ISSUE TITLE
scrolloverflow not working

### ISSUE THREAD

**Issue by kirillsavko** [alvarotrigo/fullPage.js#3460]
Hi! Help me please. Why "scrolloverflow" not working?  http://kir.cast.by/
sorry for this link, it's my test server, i can't use codepen or jsfiddle. use please view-source, thanks
I include first - jquery, second - scrolloverflow.js , third - fullpage.js and initialize fullpage with option scrolloverflow: true.
if i made mistakes - sorry, i speak English not well

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by kirillsavko** [comment]
https://jsfiddle.net/ea17skjr/38/

**Comment by alvarotrigo** [comment]
See your JS console. jsfiddle is not loading the scrolloverflow file.
