### ISSUE TITLE
Parallax only working once when using resetSliders and parallax together

### ISSUE THREAD

**Issue by jdickel** [alvarotrigo/fullPage.js#3461]
### Description
The parallax effect is only working once when scrolling from a multiple slide section to a non-slide section while having resetSliders activated.

### Link to isolated reproduction with no external CSS / JS
Link is send per Mail to @alvarotrigo 

### Steps to reproduce it
1. create a vue-fullpage project
2. activate the resetSliders and parallax extension (set both to true) and leave the parallax setting on default 
3. set up 5 sections, section no. 3 has also a few slides
4. each sections gets a ".fp-bg." div with a background-image
5. scrolling from section 3 to 4 the first time, parallax is applied 
6. scrolling back to top and then again from slide 3 to 4  the parallax effect is not applied! 

### Versions 
Google Chrome Version 70.0.3538.67 (Official Build) (64-Bit)
Windows 10 (64-bit)
fullPage 3.0.2
vue-fullpage.js v0.0.5
fullpage.js Parallax Effect Extension 0.1.4 for fullPage.js v3
fullpage.js Reset Sliders Extension 1.0.4 for fullPage.js v3

**Comment by alvarotrigo** [comment]
Can you please detail the following?

- Version of parallax
- Version of fullpage.js
- Version of vue-fullpage.js

Also:

- Are you able to reproduce the issue without using vue-fullpage.js?

If so, please [contact me](https://alvarotrigo.com/#contact) and send me the link to the isolated reproduction with no external CSS or JS to fullpage.js and the minimum amount of HTML for the reproduction. 
Use empty sections if possible.

**Comment by jdickel** [comment]
Hi @alvarotrigo,
added the version to my previous post.

Am i allowed to host the extension files for myself or do you provide a link?

**Comment by alvarotrigo** [comment]
> Am i allowed to host the extension files for myself or do you provide a link?

Yeah you can host it yourself. Just make sure to make the codesandbox private afterwards or to remove it and save it when we get to fix the issue.

**Comment by jdickel** [comment]
https://codepen.io/jdickel/pen/Jmmbgw

There you go. Forked your vue fullpage sample. I was able to reproduce it.
If you scroll from section 1 to section 2 for the first time after the page loaded everything is fine. But if you scroll like section 1 => 2 => **1 => 2** then at the last transition it does not apply the parallax!

**Comment by alvarotrigo** [comment]
It should be fixed by now.
