### ISSUE TITLE
Error with DefaultLoadingContainer when i use another library of GoogleMaps

### ISSUE THREAD

**Issue by MarcelloVSilva** [alvarotrigo/fullPage.js#3463]
### I called my component Mapa inside ReactFullpage.Wrapper, so app crash.

![deepin screenshot_selecionar area_20181024172338](https://user-images.githubusercontent.com/6786382/47460082-1b7c0d80-d7b4-11e8-817b-ce88c8c92b61.png)
![deepin screenshot_selecionar area_20181024172506](https://user-images.githubusercontent.com/6786382/47460083-1b7c0d80-d7b4-11e8-944c-85442136270b.png)
![deepin screenshot_selecionar area_20181024172711](https://user-images.githubusercontent.com/6786382/47460084-1b7c0d80-d7b4-11e8-949d-bcdef44b497a.png)

## OBS: If i remove de library fullpage and run, works fine. 
![deepin screenshot_selecionar area_20181024174754](https://user-images.githubusercontent.com/6786382/47460561-26836d80-d7b5-11e8-8d30-20a69d2e7d9f.png)

### Versions 
    "@fullpage/react-fullpage": "^0.1.2",
    "@google/maps": "^0.5.5",
    "google-maps-react": "^2.0.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-scripts": "2.0.5"

**Comment by alvarotrigo** [comment]
Any issues with react-fullpage please open them at the react-fullpage repository if directly related with it:
https://github.com/alvarotrigo/react-fullpage
