### ISSUE TITLE
Foreground scroll and background fade simultaneously?

### ISSUE THREAD

**Issue by Jamestig** [alvarotrigo/fullPage.js#3464]
### Description
Is it possible to use the fullPage fade effect extension to make certain elements fade while other elements remain as scrolling? 
I am looking to update this website to use fullPage - https://emaidalat.com

### Steps to reproduce it
Please view the website on a PC display for correct example - https://emaidalat.com 
(Full screen version is different to mobile/tablet)

### Versions 
Windows 10, google chrome

**Comment by alvarotrigo** [comment]
> Is it possible to use the fullPage fade effect extension to make certain elements fade while other elements remain as scrolling?

Nop, that's not how the fading effect extension works I'm afraid. 

But you can perhaps achieve it by making use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
