### ISSUE TITLE
Unable to disable scrolling on iOS devices.

### ISSUE THREAD

**Issue by Aeyzaz** [alvarotrigo/fullPage.js#3465]
Hi, I have disabled every scroll but on iOS devices the scroll still takes me to the last slide. here is my config. I want the the slides to only navigate through anchor link from my menu and not from scroll.

```
var myFullpage = new fullpage('#fullwidth', {
  	licenseKey:'',
      verticalCentered: true,
      autoScrolling:false,
      fitToSection:true,
      scrollBar:false,
      scrollOverflow:true,
      anchors: ['homepage','the-product','the-experience' ,'about', 'contact'],
      menu: '#top-menu',
      scrollingSpeed: 500,
      sectionsColor: []
  });
$.fn.fullpage.setMouseWheelScrolling(false);
    $.fn.fullpage.setAllowScrolling(false);
```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
