### ISSUE TITLE
The height of the first element is not calculated correctly.

### ISSUE THREAD

**Issue by DaniilDem** [alvarotrigo/fullPage.js#3467]
### Description
All sections have display: table and it does not allow to set the height less than a certain value. This then leads to errors in calculating the height of the element and the window in the getDestinationPosition function.

### Steps to reproduce it
1.  Open browser not fullscreen mode
2. Scroll down
3. Scroll up

### Versions 
Chrome 69 and all latest browsers

**Comment by alvarotrigo** [comment]
I can not reproduce your issue on the [fullPage.js demo page](https://alvarotrigo.com/fullPage/). 

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
