### ISSUE TITLE
Adding custom page scroll  animation in fullpage.js

### ISSUE THREAD

**Issue by mendax47** [alvarotrigo/fullPage.js#3468]
Have A Look: http://taotajima.jp/

If i wan a custom page scroll animation like the nest section will com by rotating instead of just slide... is there any way to do this..?

**Comment by alvarotrigo** [comment]
Fullpage.js doesn't provide any option for it, although you might be able to achieve it by using [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
