### ISSUE TITLE
No Touch Navigation after Route Change

### ISSUE THREAD

**Issue by MerryMacMapface** [alvarotrigo/fullPage.js#3469]
### Description
On sites build with vue js you can only use touch device's swipe-navigation on first route. If you change the route (via vue-router), no touch events are working anymore. - Normal section switching per buttons is still working correctly. On non-touch devices everything is working fine (except on IE/Edge, but that's another issue). You can try it on iOS or in your desktop browser with activated/emulated touch.

### Steps to reproduce it
1. create vue js project with vue router and vue jullpage js
2. create router-view and some components to switch between per router-view
3. components have multiple other components/divs, wrapped by fullpage
4. there is only one fullpage working at the same time, due to no keep-alive

It seems, the touch-events/listeners were not correctly destroyed on route-change?

### Versions 
"vue-fullpage.js": "0.0.5",
"vue": "2.5.17",
"vue-router": "3.0.1",
Tested on FF-DevEd 64.0b2, Safari 12.0 (Both MacOS 10.13.6),
iPad 5 (iOS 11.1) & 6 (iOS 12), LG V20, Kindle Fire, Samsung Tab (div. Android)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Can you please open the same issue on the Vue-fullpage.js repository?
https://github.com/alvarotrigo/vue-fullpage.js

That should be the place for it.

**Comment by MerryMacMapface** [comment]
Is done! Thank you for the quick response!

https://github.com/alvarotrigo/vue-fullpage.js/issues/65
