### ISSUE TITLE
Brightcove video and iScroll bug issue

### ISSUE THREAD

**Issue by dsc-ian** [alvarotrigo/fullPage.js#3470]
Controls of the brigthcove embed video not working with iScroll.

issue is when iscroll is activated or when the section has scroll the video controls is not functional anymore.
ex: tapping on video pause and play not functional,
      progressbar not functional.
    
if no scrolling or iscroll the video is functional.

https://jsfiddle.net/hukbc01z/3/

**Comment by alvarotrigo** [comment]
I would recommend you looking through the [iScroll issues forum](https://github.com/cubiq/iscroll/issues)

That's clearly a iScroll bug and not a fullpage.js one. 
Perhaps you can solve it changing some of the iScroll options using the fullPage.js option `scrollOverflowOptions`.

**Comment by dsc-ian** [comment]
Hi @alvarotrigo ,

Thanks for your feedback.

I have fixed the issue using 
scrollOverflow: true,
scrollOverflowOptions: { preventDefault:false },

Thanks again :)
