### ISSUE TITLE
"isLast" is never true in afterSlideLoad and onSlideLeave callbacks when there are multiple sections with slides on the page

### ISSUE THREAD

**Issue by i22tha** [alvarotrigo/fullPage.js#3471]
### Description
When there is more than one section on the page that includes slides, the callback parameter "isLast" never evaluates to true. This is because the slide index is checked against the amount of all slides on the page instead of only the slides inside the current section.

https://github.com/alvarotrigo/fullPage.js/blob/f9cf07374d6af7c157d43b6e63c55f3105d6f519/src/fullpage.js#L3326

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/anon/pen/zmVLPY

### Steps to reproduce it
1. Add at least two sections with two slides each
2. Use the afterSlideLoad or onSlideLeave callback and check for value of destination.isLast
3. Even on the last slide, the result is false

**Comment by alvarotrigo** [comment]
Good catch!

Thanks for reporting it!!
I'll take a look at it!

**Comment by alvarotrigo** [comment]
This issue stills open for anyone who want to become a contributor to this project! 👍 
I'm giving this way the chance for anyone to contribute to an open source project and practise their Javascript skills.

I propose the solution here. Now you have the chance to work on a few lines and make your contribution! 

Proposed solution
------

Currently [line 333 at the fullpage.js file in the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js#L3333) looks like this:
```
 this.isLast = this.index === $(selector).length -1;
```

The `selector` parameter can be `.fp-slide`, and that would work perfectly if there was only a single section with slides in our site.
But, as we can have multiple vertical sections with horizontal slides in them, it can be the case that we are on the last slide of a section but the slide index won't be equal to`$('.fp-slide').length-1`, as `$('.fp-slide').length` will be the number of slides in the whole site, including other sections. 

Therefore we need to just look at the .length of the slides within the parent section.

**Comment by alvarotrigo** [comment]
@i22tha awesome! Thanks for that man!

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!
