### ISSUE TITLE
Best way to change the styling of ".fp-nav" on navigation

### ISSUE THREAD

**Issue by CultureInspired** [alvarotrigo/fullPage.js#3472]
What would be the best way to change the span element colors inside ".fp-nav" when changing between sections? I'd like to add classes to elements inside that class if a specific ".section" has the active class.

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
