### ISSUE TITLE
Video + Auido won't auto-play on Chrome.

### ISSUE THREAD

**Issue by stevenprinsloo** [alvarotrigo/fullPage.js#3473]
On the first load of my website, the background video on the first page as well as the background audio won't play automatically. When I move down a page and then back to the first page, the background video then starts to play. However not the audio. If I click the navigation tooltips to jump to another page, the audio then starts playing. This only seems to happen on Google Chrome as the audio and video autoplay on Firefox.

In my afterLoad function, I have added the following code:

```
afterLoad: function(){

		$('#myVideo01')[0].play();
				
		$('#myAudio')[0].play();

	}
```

All my videos also have the 'data-autoplay' attribute.

Here is a recreation of the page without assets (video & audio).

https://codepen.io/malform96/pen/vQEyPQ

Here is a link to my website:

http://stevenprinsloo.co.za/

**Comment by alvarotrigo** [comment]
Only muted videos will play in Chrome. That's a browser restriction not a fullpage.js issue.
Same with audios, they won't autoplay. 

You can read more about it googling a bit.
