### ISSUE TITLE
Section height doesn't match viewport height when using paddingTop and paddingBottom

### ISSUE THREAD

**Issue by docjones7495** [alvarotrigo/fullPage.js#3474]
Hi,
I'm having a problem regarding the heights of the sections of a WordPress website I'm working on (Link to the website below).

This is what I've done: I've set a paddingTop and paddingBottom in the options as I'm using a fixed header and footer on the website. I've also set the box-sizing to "border-box" as I want the paddings to be included in the heights of the elements.

This is what is causing my problem: Despite using "box-sizing: border-box" the height of the section including the paddings exceeds the height of my viewport, when there is a lot of content in a section (see screenshots). This leads to a faulty scrolling behaviour in these sections. As the height of the section doesn't match the height of the viewport, the "scrollOverlow: true" option isn't triggered correctly and the additional scroll-box isn't used when it is already necessary. Furthermore the positioning of the content in the viewport is different depending on whether I scrolled up or down to section because of this difference between section height and viewport height.

Website: http://staging.selected-talents.de/konzept/
User: selected
Password: Talents

Am I missing something or are there any known problems regarding the usage of Fullpage with WordPress?

Thanks in advance and best regards!

Jonas

![screenshot1](https://user-images.githubusercontent.com/44773885/48000750-c53d9180-e106-11e8-8667-395b84f7c761.jpg)

![screenshot2](https://user-images.githubusercontent.com/44773885/48000756-cbcc0900-e106-11e8-8a59-37b64a561d52.jpg)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by docjones7495** [comment]
I tried to reproduce it here: https://jsfiddle.net/ea17skjr/42/

The problem I described can be seen in the 2nd section. The content in its entirety can't be seen because of the missing change of scrolling behaviour.
