### ISSUE TITLE
Scroll Top Firefox

### ISSUE THREAD

**Issue by SNWarbard** [alvarotrigo/fullPage.js#3475]
Hi,

I got a problem with the fullpage.js. It automatically scroll to top on firefox only (Chrome and Edge works well)
How can I fix it ? 

Thank's
SNWarbard

(https://bilel-lahbib.fr)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by SNWarbard** [comment]
I reproduct it and edit my message sorry.

**Comment by alvarotrigo** [comment]
Thanks.
Can you please remove any JS that doesn't belong to fullPage.js? 
That way we will isolate the issue.

**Comment by alvarotrigo** [comment]
You are using fullPage.js version 2.7.4.
Support is only provided for version 3.X. More specifically, the latest version at the moment which is 3.0.3.

**Comment by SNWarbard** [comment]
Ok I update it but I can't even scroll now ^^

**Comment by SNWarbard** [comment]
My fullpage id was on a `<container>`
I change it to a div and it works now ^^
