### ISSUE TITLE
Other jQuery code does not work with fullpage applied

### ISSUE THREAD

**Issue by jkyochum** [alvarotrigo/fullPage.js#3477]
Hello, I am having an issue running some jQuery code alongside the fullpage.js plugin. The plugin works great but it seems to be the only jQuery I can run when it is applied to my web page. I attempted to run code that would smooth scroll to the same div, but this would require a button click. It does run, but when the page has reached the scroll position then the page starts to glitch out and becomes unusable. Thanks for any help or advise.

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
