### ISSUE TITLE
Easing not possible with fullPage

### ISSUE THREAD

**Issue by batata004** [alvarotrigo/fullPage.js#3478]
Hi,

This plugin is AMAZING, it works perfectly accross many devices. I love it. However I always had a problem trying to use `easing` with this plugin. So today I decided to solve it for once and for all! :)

My code is this:

```
				$("#fullpage").fullpage({

					licenseKey:'OPEN-SOURCE-GPLV3-LICENSE',
					scrollingSpeed:1000,
					easingcss3:"easeInOutCirc",
                    navigation:true,
					anchors:["principal","diferenciais","criacao-site","portfolio","precos","contato"],
					showActiveTooltip:true,
					onLeave: function(origin, destination, direction){
				
						$(".section-image img:first").stop(true,false).animate({"margin-top":-407*destination["index"]},1000,"easeInOutCirc");

					}
```

You see, I want to use `easeInOutCirc` however browsers dont have this ease defined by default (like `linear`).  So I imported this ease on my JS file before calling the code above. I imported it like this:

```
	var pow = Math.pow,sqrt = Math.sqrt;
	
	$.extend( $.easing,
	{
		easeInOutCirc: function (x) {
			return x < 0.5 ?
				( 1 - sqrt( 1 - pow( 2 * x, 2 ) ) ) / 2 :
				( sqrt( 1 - pow( -2 * x + 2, 2 ) ) + 1 ) / 2;
		}
	});
```

Despite importing this ease, when I try to scroll, the fullpage plugin scrolls immediatly without any transition (I am pretty sure this is happening cause it is not seeing the `easeInOutCirc` that I pointed in the initialization).

So how can a user use an ease with this plugin?

**Comment by alvarotrigo** [comment]
Just use the css3 transition for your easeInOutCirc:
https://easings.net/es#easeInOutCirc

Use:

```javascript
easingCss3: 'cubic-bezier(0.785, 0.135, 0.15, 0.86)'
```

**Comment by batata004** [comment]
@alvarotrigo  it worked perfectly! But I wish it would be possible to use a named easing that was already loaded with javascript. Anyway, if you dont have a solution to that question, I thank you for the alternative solution you provided here :)

**Comment by alvarotrigo** [comment]
Just use this site to get the equivalent cubic bezier function for it:
https://easings.net/
