### ISSUE TITLE
Direction on afterLoad Event Undefined

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#3480]
Hi Alvaro,

In afterLoad event, the direction comes as undefined instead of up or down.

Isolated reproduction:
https://codepen.io/anon/pen/XyKadN

Check the console.log. Direction variable is undefined. I tried to find the reason behind it but getYmovement seems to be returning true however afterLoad fires as undefined somehow.

Thank you,

**Comment by alvarotrigo** [comment]
Uh! That's not good!
Thanks for reporting it!

So far, you can solve it by using also the `onLeave` callback. That seems to solve the issue somehow. Using both at the same time.

I'll look into this for the next release!

**Comment by meceware** [comment]
Thank you, for now I can understand by checking the indexes as well, so I'm not in a hurry :)

Cheers,

**Comment by alvarotrigo** [comment]
Fixed on dev! To be merged in the next release!

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!
