### ISSUE TITLE
normalScrollElements requires a 1st touch in touch screens

### ISSUE THREAD

**Issue by glo-www** [alvarotrigo/fullPage.js#3481]
Hello,

On touch screens, cannot scroll inside a div with "overflow: auto;" and the option "normalScrollElements"
It looks like I need to "click" on an element inside that div first.

Please see:
https://codepen.io/glo_www/full/QJExwG/

### Steps to reproduce it
1. Have a div inside a fullpage section, with "overflow:auto" set in CSS, fixed height, and content that overflows.
2. Use "normalScrollElements" option to target that div
3. Test on touchscreen

### Versions 
Fullpage 3.0.3
Firefox, Chrome, Edge / Android

(on the demo, the touch navigation between sections do not work at all on Firefox)

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!
