### ISSUE TITLE
Link to fp-auto-height-responsive demo in documentation is broken 

### ISSUE THREAD

**Issue by radscheit** [alvarotrigo/fullPage.js#3483]
### Description
Link to demo in documentation is broken in section lazy loading responsive auto height: https://github.com/alvarotrigo/fullPage.js#lazy-loading

**Comment by alvarotrigo** [comment]
You mean the responsive auto height demo link right?
https://github.com/alvarotrigo/fullPage.js#responsive-auto-height-sections

The lazy loading seems to be working fine.

Thanks for reporting it!
I'll take a look at it!

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!
