### ISSUE TITLE
 The mobile does not work the displacement

### ISSUE THREAD

**Issue by geometry-matteoquintero** [alvarotrigo/fullPage.js#3485]
These are the configurations that I use for mobile but in android the displacement does not work

```javascript
  
      licenseKey: "xxxxxx-xxxxxx-xxxxxx-xxxxxx",
      paddingTop: '80px',
      paddingBottom: '2vh',
      touchSensitivity: 10, 
      scrollBar:true,
      autoScrolling:true,
      scrollOverflow: true,
      scrollOverflowOptions: {
        scrollbars: true,
        fadeScrollbars: false,
        interactiveScrollbars: true
      },
      afterLoad: function(origin, destination) {
        fullpages.animationsLoad(origin, destination);
      },
      onLeave: function(origin, destination) {
        fullpages.animationsLeave(origin, destination);
      }
```

@alvarotrigo  in this link you can see what happens :(
And tomorrow the site goes to production

https://www.geometry.com.co/3dotsxperience/

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by geometry-matteoquintero** [comment]
But at least you can tell me if these settings are good for mobile?

Is there any option that improves navigation in mobile?

**Comment by alvarotrigo** [comment]
I guess they look fine. Nothing weird on them.

**Comment by alvarotrigo** [comment]
OH well, there's a problem there yeah. You should be able to read it yourself on the JS console: 

>   Options scrollBar:true and autoScrolling:false are mutually exclusive with scrollOverflow:true. Sections with scrollOverflow might not work well in Firefox
