### ISSUE TITLE
Anchors stopped working on refresh

### ISSUE THREAD

**Issue by Shizart** [alvarotrigo/fullPage.js#3487]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by Shizart** [comment]
I am using fullpage.js on several pages. Refreshing the page scrolled to the anchor the user was on early in our development and then it stopped working for some reason. If I go to our home page via https://bowlusroadchief.com/#sec3 they would be dropped on the correct url but in the top section. If I scroll down to https://bowlusroadchief.com/#sec3 then refresh, I end up at https://bowlusroadchief.com/#sec1 but the urls is still https://bowlusroadchief.com/#sec3 so attempting to go to the next/previous results in excessive scrolling etc. any idea why? 

Great script. Thanks!

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Shizart** [comment]
I found the reason. thx

**Comment by kylehotchkiss** [comment]
@Shizart any chance you could expand on what problem caused this issue? I'm experiencing it as well.
