### ISSUE TITLE
Broken link on documentation

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3489]
There is a broken link in this section

> scrollOverflowOptions: when using scrollOverflow:true fullpage.js will make use of a forked and modified version of iScroll.js library. You can customize the scrolling behaviour by providing fullpage.js with the iScroll.js options you want to use. Check its documentation for more info.

http://iscrolljs.com/ - seems to be down. An issue on the iScroll site of course.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Seem slike iscroll has died for ever now :D

It was lacking maintenance for the past years, but now it seems the author definitely took the project down.

**Comment by alvarotrigo** [comment]
Please feel free to provide a pull request against the dev branch to remove the link.
You'll figure as a contributor this way :)

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4.
