### ISSUE TITLE
setAllowScrolling not working as expected upon page load in `afterLoad`

### ISSUE THREAD

**Issue by imjared** [alvarotrigo/fullPage.js#3490]
### Link to isolated reproduction with no external CSS / JS
editor view: https://codepen.io/imjared/pen/NEjPqg
full page view: https://codepen.io/imjared/full/NEjPqg/

### Steps to reproduce it
1. Load full page
2. Scroll down
3. After reaching second slide, you can't scroll down any further

### Expected behavior
Upon page load and fullPage initialization, calling `fullpage_api.setAllowScrolling(false);` should lock the page entirely.

### Actual behavior
Upon page load and fullPage initialization, `fullpage_api.setAllowScrolling(false);` is called but has no effect on the first slide. After scrolling down one slide, you can see that the call to `setAllowScrolling()` works as expected since you can no longer scroll.

Additionally, adding a `setTimeout` makes this works as I'd expect. This signals to me that the plugin's initialization isn't totally complete when `afterLoad` is called.

```javascript
window.setTimeout(function() {
  fullpage_api.setAllowScrolling(false, 'down');
}, 0);
```

### Versions 
fullPage 3.0.3

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
It is indeed a bug!

Temporally you can fix it by using a `setTimeout` around the `setAllowScrolling` function:

```javascript
afterLoad: function(origin, destination, direction) {
     setTimeout(function(){
       console.log("va");
       fullpage_api.setAllowScrolling(false);
     });
}
```

**Comment by alvarotrigo** [comment]
You can also fix it by just calling `setAllowScrolling` right after you initialise fullPage.js:

```javascript
new fullpage('#fullpage', {options});

fullpage_api.setAllowScrolling(false);
```

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4.
