### ISSUE TITLE
Continue auto-scrolling to sections after scrolling on "normalScrollElements", without moving mouse.

### ISSUE THREAD

**Issue by CultureInspired** [alvarotrigo/fullPage.js#3492]
This is a design question rather than an issue, regarding "normalScrollElements" on long form content.

Is it possible to continue auto-scrolling to the next/previous section, once you've reached the top/bottom scroll position of a "normalScrollElement", without moving my mouse position off of the normal scroll div?

**Comment by alvarotrigo** [comment]
Not something provided by fullPage.js, but surely possible. 
Just detect when you scroll to the bottom and then call the `moveSectionDown` function.
