### ISSUE TITLE
back to upper page

### ISSUE THREAD

**Issue by alimp76** [alvarotrigo/fullPage.js#3493]
Hey
I use a navigation link in the header of my website and it's linked to #section2 and when i click on the link it goes to section2 and i can scroll down to section3 but i can't scroll up to section 1 again.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
