### ISSUE TITLE
How to enable normal scrolling after section.

### ISSUE THREAD

**Issue by Andi-Stevenson** [alvarotrigo/fullPage.js#3497]
I apologise if I am being an idiot but I can't figure this out for the life of me.
I am using Fullpage.js for my website homepage and the scrolling system works perfectly for the 8 sections of the website I need it too. I can't figure out though how to turn the fullpage scrolling off for the bottom section of my webpage and go back to standard scrolling so I can preform a parallax effect. Should I be using fixedElements:, normalScrollElements:, scrollOverflow:, or the parallax plug in?
Also is there a way to have a snap transition between sections?

Thanks in advance.

**Comment by WilliamSf** [comment]
I think using the `scrollOverflow` would work fine

**Comment by alvarotrigo** [comment]
> I can't figure out though how to turn the fullpage scrolling off for the bottom section of my webpage and go back to standard scrolling so I can preform a parallax effect.

You can't really do what you want without having a few issues.

Usually I recommend people to make use of scrollOverflow, which you can see in action on [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).
However, you won't be able to perform a custom parallax effect on it, as you won't be able to listen the scroll event.

The only other solution you can try is disabling the autoScrolling by using the method `setAutoScrolling(false)` detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). 
You can use it inside an `afterLoad` callback.

```javascript
afterLoad: function(origin, destination, direction){
    if(destination.index == 3){
         fullpage_api.setAutoScrolling(false);
    }
    else{
        fullpage_api.setAutoScrolling(true);
    }
}
``` 
However, you'll have to turn on the autoScrolling again when scrolling up, and that is where you'll find the trouble.

Not an easy solution :)

**Comment by Eklor** [comment]
Hello, sorry for the noob question here. 
Is there a link where the ScrollOverflow script is hosted and accessible? Can I use the link to the one on github? 
I'm new to development obviously :)

**Comment by alvarotrigo** [comment]
Any cdn as pointed out in the docs:
https://github.com/alvarotrigo/fullPage.js#optional-use-of-cdn

You can also un unpkg:
https://unpkg.com/fullpage.js/
