### ISSUE TITLE
Fixed Header Blocks Scrolling through Sections with "scrollOverflow: true"

### ISSUE THREAD

**Issue by mnoesel** [alvarotrigo/fullPage.js#3498]
Dear Álvaro,
I've a fixed header on my website which blocks scrolling, when hovering, through my fullpage sections only when `scrollOverflow: true`. How can I fix this?

Isolated Reproduction:
https://jsfiddle.net/o5Lcpemw/1/

Steps to reproduce it:
1. Hover Red Header
2. Try to Scroll through Sections

MacOS High Sierra, latest Chrome Release

**Comment by alvarotrigo** [comment]
If you want to be able to scroll when the mouse is over the fixed header, then just include the header in the fullPage.js wrapper. 

Then, you might have to use `css3:false`.
