### ISSUE TITLE
add to license error

### ISSUE THREAD

**Issue by jaeseonasd** [alvarotrigo/fullPage.js#3499]
jQuery(document).ready(function() {
    jQuery('#fullpage').fullpage({
    licenseKey: 'XXXXXX-XXXXXX- XXXXXX-XXXXXX',
        anchors:['about-erd', 'contact-erd', 'press-erd'],
        verticalCentered: false,
        menu: '#menu',
        css3:false,
        scrollOverflow: true,
        continuousHorizontalKey: 'XXXXXXXXX',
        continuousHorizontal:true,
        onLeave: function(anchorLink, index){
                var loadedSection = jQuery(this);
                if(index == 1){
                    jQuery(".section2bg").hide();
                    jQuery(".sidebar").fadeIn();
                    jQuery("#scrollDown").fadeIn();
                }
                if(index == 2){
                    jQuery(".section2bg").show();
                    jQuery(".sidebar").fadeOut();
                    jQuery("#scrollDown").fadeIn();
                }
                if(index == 3){
                    jQuery(".sidebar").fadeOut();
                    jQuery("#scrollDown").fadeOut();
                }
        }
    });
}); 

https://bit.ly/2zklwbq

I've inserted the license key I've purchased into the licenseKey option and get the following error:
my mail is jaeseonasd@gmail.com

ASAP

**Comment by alvarotrigo** [comment]
I don't see any problem in your site.
All seems ok to me.

What's the problem?
