### ISSUE TITLE
Video Background in section

### ISSUE THREAD

**Issue by weareburo** [alvarotrigo/fullPage.js#35]
The plugin does'nt let play background video into section when it call var pepe = $.fn.fullpage({
                slidesColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
                anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],
                menu: '#menu'
            });

The video does'nt start, any clue .
Using any solution like bgvideo or http://www.inserthtml.com/2013/09/quick-tips-background-videos/  don't let the video play

**Comment by jolebowski** [comment]
For reactjs it' s not wworking
