### ISSUE TITLE
Links to slides not working

### ISSUE THREAD

**Issue by circa42** [alvarotrigo/fullPage.js#3503]
### Description
I'm trying to get a simple link to work on my sliders. I'd want to use a link to advance slides. 
The regular nav works when I turn it on, but the URL structure doesn't change on the browser like it does in the demo. 

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/circa42/huyqn3ge/3/

### Steps to reproduce it
1. Created a section titled `#form`
2. Created a link to '#form/form1' (e.g. `#section/slide`) 
3. Button links and the URL structure changes, but the sections/slides do not advance. 

### Versions 
Safari 12; Chrome 70

**Comment by alvarotrigo** [comment]
Use `lockAnchors:false`. You are locking them, so changes in the URL won't affect the slider, as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) regarding the lockAnchor option.
