### ISSUE TITLE
Calling jquery events when slide is visible

### ISSUE THREAD

**Issue by Andi-Stevenson** [alvarotrigo/fullPage.js#3506]
Not an issue but a question which others might find the answer to helpful.

I am using Fullpage.js on my website, I am trying to call some jquery animate functions when a user scrolls to a section of my website. I have tried using mouseenter, mouseover, mouseleave (from the previous section) however when I scroll the the next section it does not pick up that the mouse has entered the section and therefore animations do not play until the mouse is moved. 

What method should I use for the animation to play as soon as the section has been scrolled to and is visible? Is this possible in jquery or what is a better solution?

**Comment by alvarotrigo** [comment]
> What method should I use for the animation to play as soon as the section has been scrolled to and is visible? Is this possible in jquery or what is a better solution?

Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
