### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Guchen1** [alvarotrigo/fullPage.js#3507]
Ask for an opensource license of fullpage
https://github.com/ntzx/wangyue.git
And must I pay for its extensions?
Thank you

**Comment by alvarotrigo** [comment]
I answered you by email.

**Comment by Guchen1** [comment]
but I have not received it

**Comment by alvarotrigo** [comment]
Uh, perhaps it wasn't you the one I contacted :)

Please [contact me](https://alvarotrigo.com/#contact) with details regarding your open source project.
