### ISSUE TITLE
$.fn.fullpage.setAllowScrolling not working as expected in `afterLoad`

### ISSUE THREAD

**Issue by imjared** [alvarotrigo/fullPage.js#3510]
### Link to isolated reproduction with no external CSS / JS
https://codepen.io/imjared/pen/GwbvZJ

### Steps to reproduce it
Steps are almost identical to #3490. When `afterLoad` fires, I end up with `Uncaught TypeError: $.fn.fullpage.setAllowScrolling is not a function`. Wrapping the call to fullpage's API in a `setTimeout` with delay of 0 makes it work as expected

### Versions 
fullPage 3.0.4 - Extensions 0.1.7

**Comment by alvarotrigo** [comment]
Interesting... 
Thanks for reporting it!

So far, it works if you replace `$.fn.fullpage.setAllowScrolling` for `fullpage_api.setAllowScrolling`:
https://codepen.io/alvarotrigo/pen/PxrRpL

You can use that meanwhile :)

**Comment by cvaraj** [comment]
Hi @alvarotrigo , i have facing same issues, but i have used fullpage_api.rebuild but it's not working its showing some errors in console like **TypeError: scrollBarHandler is undefined** line-number 484 and too **much recursion**  line-number 3430

**Comment by alvarotrigo** [comment]
@cvaraj please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Good news!
The issue has been fixed and should be merged in the next release of fullPage.js version 3.0.5

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
