### ISSUE TITLE
getActiveSlide() doesn't work after fullpage initialization

### ISSUE THREAD

**Issue by imjared** [alvarotrigo/fullPage.js#3511]
### Link to isolated reproduction with no external CSS / JS
https://codepen.io/alvarotrigo/pen/VdpzRN/

### Steps to reproduce it
1. Load codepen link
2. Open console and click "get active slide" button

Expected:
1. Slide details are logged

Actual:
1. `null` is logged

Note: Upon switching to the next slide and clicking "get active slide", the "get active slide" button works as expected.

### Versions 
fullpage 3.0.4

**Comment by imjared** [comment]
I'm realizing that I may be misunderstanding how you're using the terms "slide" and "section" so will close this out.

**Comment by alvarotrigo** [comment]
`getActiveSlide` returns the active slide on the screen. 
The the moment of loading your codepen there's no active slide, only an active section.

Only when you move down to the 2nd section the active slide will return the active slide within the section.

Perhaps I should clarify in the docs that it makes reference to active slides within the active section, so, if the section has cero slides, `null` will be returned.
