### ISSUE TITLE
continuousHorizontal + scrollHorizontally

### ISSUE THREAD

**Issue by kubmin** [alvarotrigo/fullPage.js#3512]
### Description
I bought the continuousHorizontal and scrollHorizontally extensions to use next to each other, however it is not working as expected. When I reach the end of the slides by scrolling with the mouse/trackpad, it doesn't continue to the first slide. When I do this with the arrow keys on my keyboard, it works as expected and moves to the first slide again.

### Link to isolated reproduction with no external CSS / JS
I don't know how to reproduce this in a jsfiddle or codepen, as I cannot find the extensions on a CDN and can't use them outside of a local environment without a license key.

### Steps to reproduce it
1. FullPage with one section and three slides using Vue.js
2. continuousHorizontal to true
3. scrollHorizontally to true

### Versions 
Version 70.0.3538.110 (Official Build) (64-bit)
Mac OSX 10.14.1

**Comment by alvarotrigo** [comment]
That's how it is suppose to work :)
Otherwise the visitors would be stack in the same section without any possibility to scroll to another vertical section.

It only makes sense to use the way you want if you have a single section with horizontal slides.

Please [contact me](https://alvarotrigo.com/#contact) and I'll provide you a custom version of the extensions.

**Comment by alvarotrigo** [comment]
I'll mark it as an enhancement so it can work that way if there's only a single vertical section in the site with multiple horizontal slides.

**Comment by kubmin** [comment]
Ah I understand. Thanks for your response.
Since I'm only using one section I would love to have this custom version ;-)
I contacted you!

**Comment by alvarotrigo** [comment]
I've fixed with with an update on the Scroll Horizontally extension. 0.0.3

You should get an email about it.
