### ISSUE TITLE
not work callback "afterSlideLoad"

### ISSUE THREAD

**Issue by rttmax** [alvarotrigo/fullPage.js#3513]
**expected:** Callback fired once the slide of a section have been loaded, after the scrolling has ended.
**actual:** nothing happens

Perhaps I missunderstood something?!

Demo: [https://codepen.io/anon/pen/bObGPb](https://codepen.io/anon/pen/bObGPb)

**Comment by alvarotrigo** [comment]
> Perhaps I missunderstood something?!

Yeap you did :)

Sections -> vertical 
Slides -> Horizontal slides within a section.

So you need to use `afterLoad`.

You can see how the docs say regarding `afterSlideLoad`:

> Callback fired once the **slide of a section** have been loaded, after the scrolling has ended.

**Comment by alvarotrigo** [comment]
You can check this yourself on [the callbacks example online](https://alvarotrigo.com/fullPage/examples/callbacks.html)(also available in the examples folder of this project)
