### ISSUE TITLE
api issues

### ISSUE THREAD

**Issue by Mohsen-Khakbiz** [alvarotrigo/fullPage.js#3515]
sometimes I feel the api isn't how it should be. it's lacking a lot of things.

please check this https://jsfiddle.net/Mohsen_Khakbiz/q9bwxcde/5/

before start, I don't want use any of fullpage extensions :)

what I need here is, I need the animation of sections to be done, and then silentMove to the next section. and I want this on each section. but it seems afterLoad is not even firing. 

it's working with fullpage_api.moveTo() but you'll see the issue. it's like firing onLeave twice. https://jsfiddle.net/Mohsen_Khakbiz/q9bwxcde/7/
regardless of animations, please compare with default demo's navigation https://alvarotrigo.com/fullPage/ here the bullets are activate/deactivating as soon as leaving/entering a section. but in my jsfiddle demo you'll see it's waiting for the scrolling to be done and then bullets are changing. 
on the other hand using setScrollingSpeed will mess the scrolling https://jsfiddle.net/Mohsen_Khakbiz/q9bwxcde/10/
please keep scrolling, and you'll see nothing is happening. as we expect to keep scrolling and going to next or previous section

and btw, it's so weird that fullpage_api.moveTo accepts the section index, but silentMoveTo accepts the anchor of the section. both should work the same way I guess. isn't it?

please let me know if I'm doing something wrong there.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction without any external CSS or JS so I can understand better your problem without having to deal with external code that might be changing the way fullPage.js works?

Also, please create an issue in the forum for each of your issues.
It seems to me you are naming a few here, which makes it more difficult to answer, to categorise and to isolate.

**Comment by Mohsen-Khakbiz** [comment]
1. I need to do some animations before sections start moving, and need if for all sections. It's kind of pause the navigation and then move to next/prev sections. The solution provided here https://github.com/alvarotrigo/fullPage.js/issues/3407 it doesn't fit my needs. Is there a better way to be able to do this?

2. May I ask why **silentMoveTo** accepting the section’s anchor but **moveTo** accepts the section’s id? I guess both should accept the same arguments. Isn't it?

**Comment by alvarotrigo** [comment]
1- See how to cancel the movement before leaving the section [on this part of the docs](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place).

2- MoveTo never accepts a section id. It only accepts anchors or numeric indexes starting by 1.
Both silentMoveTo and moveTo accept exactly the same params as detailed in the docs. By just checking [the code](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L418) you can see how silentMoveTo is a wrapper around moveTo.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
