### ISSUE TITLE
Slides Work when using a static page but not when generated through js

### ISSUE THREAD

**Issue by ibrokemypie** [alvarotrigo/fullPage.js#3519]
### Description
When I create a page using js (document.body.appendChild etc) and add jullpage through node, webpacking it all together, slides simply do not work. However if I recreate the page using html copied from the generated page, slides work fine

### Link to isolated reproduction with no external CSS / JS
working static page: https://gitlab.com/ibrokemypie/portfolio/blob/master/test/index.html
broken js page: https://gitlab.com/ibrokemypie/portfolio/blob/master/src/index.js

### Steps to reproduce it
1. Create page using js
2. add slides
3. import and initiate fullpage
4. webpack
5. test

### Versions 
chrome and firefox on macOS, macbook pro, fullpage 3.0.4

**Comment by alvarotrigo** [comment]
That should work.
You are probably missing something, like the fullpage.js wrapper id `fullpage` or similar.

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ibrokemypie** [comment]
I can't reproduce it even copying code directly to jsfiddle without any changes, that works fine. Perhaps fullpage.js doesnt work with webpack?

**Comment by alvarotrigo** [comment]
> Perhaps fullpage.js doesnt work with webpack?

Any library works with webpack :)
In fact, webpack is being used in the React and Vue wrappers for fullPage.js.

**Comment by ibrokemypie** [comment]
got it!  apparently importing fullpage.js doesnt include the css, doing so fixed it. sorry for the trouble!

**Comment by alvarotrigo** [comment]
Yeap :)
