### ISSUE TITLE
Fullpage.js website menu won't scroll on mobile

### ISSUE THREAD

**Issue by imjared** [alvarotrigo/fullPage.js#3520]
### Description
just a heads up that your nav doesn't work on mobile.

### Steps to reproduce it
Go to https://alvarotrigo.com/fullPage/#examples on iPhone. I'm on iPhone 8, Chrome, and the most recent public release of iOS. Try to scroll the list. Also occurs in Safari.

Expected:
- Can scroll

Actual:
- Can't scroll

screencast: https://cl.ly/1bf54bfa258d

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
