### ISSUE TITLE
Fixed sidebare

### ISSUE THREAD

**Issue by keslo** [alvarotrigo/fullPage.js#3521]
Hello!
fullPage is awesome!
I need to add fixed sidebare left or right. And use the remaining space for fullPage. Example, https://mladenplavsic.github.io/bootstrap-navbar-sidebar/
How can i do this?

**Comment by alvarotrigo** [comment]
That's not something related with fullPage.js
You'd better ask in another place such as stackoverflow.com where they'll be able to help you better with CSS knowledge questions.
