### ISSUE TITLE
Lazy Loading Images suggested in documentation breaks html validation

### ISSUE THREAD

**Issue by hjain0902** [alvarotrigo/fullPage.js#3522]
### Description
The suggested method to lazy load images is to add data-src attribute to img tag and remove the existing src tag. However, that is not compliant with html w3c specs

[Section 4.7.5 of W3C recommendations](https://www.w3.org/TR/html5/semantics-embedded-content.html#the-img-element) mentions that "The src attribute must be present, and must contain a valid non-empty URL potentially surrounded by spacesreferencing a non-interactive, optionally animated, image resource that is neither paged nor scripted."

However recommended approach suggests rendering image without src tag.

**Comment by alvarotrigo** [comment]
> The suggested method to lazy load images is to add data-src attribute to img tag and remove the existing src tag. However, that is not compliant with html w3c specs

Not really :)

fullPage.js give you total freedom regarding what you want to do with the `src` attribute. 
fullPage.js doesn't even touch it. 

It only applies `data-src` into `src` when is time to show the resource. 

So, you can actually use any `src` you want.

**Comment by alvarotrigo** [comment]
> I can think of using a placeholder image that can be used for all images on that page or to use a low resolution version of image in the image tag?

Yeah you can do that.

> If the same data-src image url is used for src, then image would be loaded on load which defeats the purpose of lazy loading and non url based text cannot be used in images.

That only happens when you reach the section/slide. The content of `data-src` gets inserted in `src`.
Before that, you can have any value in `src` and have your real image in `data-src`.
