### ISSUE TITLE
Fullpage Brake

### ISSUE THREAD

**Issue by andresclua** [alvarotrigo/fullPage.js#3524]
Hi, 

Thanks for creating this amazing plugin! 
Im working on a digital story using fullpage and its looking really good, but the thing is that when I open it on my mobile or ipad, I get an error from Safari with the message "a problem occurred with this webpage so it was reloaded". I started debugging and realized that the error doesnt come up if I comment the fullpage function, so I think it has to be realted. 
Do you have any clue on how can I fix this? Im currently working with a Developer license.

This is the link so you can check it out:
http://207.154.194.199/works/undp/master-state/

Honestly I wish I could move this into codepen, but seems impossible. Hope you understand this.

![image from ios](https://user-images.githubusercontent.com/612806/50108861-0ef4be00-0215-11e9-8889-30641e27a60c.png)

Thanks in advance!!
Andres

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
