### ISSUE TITLE
Initialization after destroy gives error if scrollOverflow is set to true

### ISSUE THREAD

**Issue by MetaDevelopment** [alvarotrigo/fullPage.js#3525]
Description:
When initializing fullPage, destroying it and after that initializing fullPage again, an infinite loop is created and the browser gives a "Maximum call stack size exceeded" error. (real case scenario: run fullPage, load dynamic content via ajax, destroy the old instance and run fullPage on the new content)

Simulation:
A pen recreating the issue with the bare minimum of content, based on the demo for the destroy method (I had to include scrolloverflow.min.js in the JS window because I couldn't manage to properly include it via a link):
https://codepen.io/anon/pen/OrRzNP

Steps to reproduce it
1. click on "Init" to initialize Fullpage with the scrollOverflow set to true
2. click on "Destroy" to destroy Fullpage with option "all"
3. click on "Init" to initialize Fullpage again

It seems the problem lies within a function called "deepExtend", which keeps calling itself.

**Comment by alvarotrigo** [comment]
Ups!
Thanks for reporting it!

Apparently I forgot to update the minified version of scrollOverflow.js.
You can meanwhile minify it yourself or use the full version 0.1.1 from here:
https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.js

**Comment by alvarotrigo** [comment]
Or, you can use the ones in the file [in dev branch now](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.min.js).

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
