### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andreiv3103** [alvarotrigo/fullPage.js#3526]
### Description
I am new to web development so maybe I'm doing something wrong. I attached a screenshot of my top level html structure.
Could you please have a look and tell me if I did something wrong?
I added the license key. No custom settings I just called the function. The only parameter is the license key. No errors in Chrome developer tools.
Thanks
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
.
### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]
![capture](https://user-images.githubusercontent.com/2743608/50149538-25a61e00-02c4-11e9-846f-ef5206dbef9d.jpg)

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
