### ISSUE TITLE
Problem with moveTo() after Destroy and init!

### ISSUE THREAD

**Issue by LeninFelix** [alvarotrigo/fullPage.js#3528]
Hello, I have a problem with my project, at the same time using an ajax style, but for the moment I am hardcoding this part to then pass that to production, so the problem happens when I add more sections with jquery preppend (), the objective is that they are "news" where the client can access a news and that news is loaded in an "int", where the selected news load on the screen, but for this, they also loaded two more sections, one on top of the current news and another section below the current news, I can control how the user moves (desk) with some on-screen controllers (arrows) which guide the user to take it up on the current news or below the current news , and for example, if a user clicks up to upload a section, what we do with ajax is add another div (section) but above all, that is, load a new section with another news, the problem lies in this case nothing more, steps after s that the user arrives at the news above:

1.- I add the section.
2.- Destroy Fullpage with $ .fn.fullpage.destroy ("all")
3.-I initialize the "initializeFullpage" function again.
4.-I execute the function $ .fn.fullpage.silentMoveTo () to the section where I had stayed.

Here the problem is that everything responds well, the class "active" is right in the section that I ask, but my view is covered a section below, which is what happens?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
