### ISSUE TITLE
Slide height is not fullscreen when changing orientation on firefox browser in iOS 

### ISSUE THREAD

**Issue by jeffreypisa** [alvarotrigo/fullPage.js#3530]
When changing orientation in the firefox browser on iOS 10 from horizontal to vertical the slides lose their fullscreen height. This is also apparent in the demopage: https://alvarotrigo.com/fullPage/examples/backgrounds.html

**Comment by alvarotrigo** [comment]
I assume you are talking about Chrome.
I'll close it as it is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/3336 which stills open and under investigation.
