### ISSUE TITLE
Change height of sections when header sticky

### ISSUE THREAD

**Issue by ShonLevi** [alvarotrigo/fullPage.js#3531]
Hey,
I'm trying to implants the fullpage.js in my website,
It's working really good, except one little thing I'm trying to do and not succeed.

I have a sticky header in my website
something like this example https://alvarotrigo.com/fullPage/examples/fixedHeaders.html

I just want to know if there is anything I can do to make the height of the sections be 100VH minus the header height, so the header won't cover a part of the sections

(I tried to add the paddingTop property and it's seem to fix it, but when I'm scrolling I see a white space between the sections. so...)

Thanks :)

**Comment by alvarotrigo** [comment]
paddinTop is your answer.

> (I tried to add the paddingTop property and it's seem to fix it, but when I'm scrolling I see a white space between the sections. so...)

Can you please provide an isolated reproduction of that?
Seems to be working pretty good for me. https://jsfiddle.net/1kyuL4em/205/

**Comment by ShonLevi** [comment]
When there is no header - you right.
but there is a header, so it cover the section

if I have background image on the section, the header cover part of it

**Comment by alvarotrigo** [comment]
Create a wrapper for your section content and apply the background to the wrapper. 
This way you won't lose any background area but you'll see white space between backgrounds while scrolling. 

The other option is loading a bit of background behind. 

There's no other way around it.

**Comment by ShonLevi** [comment]
So there is no option to make the scrolling get the 100vh and make it minus X px?

Because the white spaces is look wrong.
And make the content behind the header is looking asymmetrical (if I got 2 arrows inside my section, and both is 100px from top and bottom, the header is 50px height, so it looks like the top arrow is 50px from the page and the bottom is 100px)

**Comment by alvarotrigo** [comment]
> So there is no option to make the scrolling get the 100vh and make it minus X px?

Not at the moment. 
The most you could do is use the [Offset Sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html) but it works using percentages and not pixels or any other measure such as em, rm etc.

I will however consider improving the extension in a future.

**Comment by alvarotrigo** [comment]
> (if I got 2 arrows inside my section, and both is 100px from top and bottom, the header is 50px height, so it looks like the top arrow is 50px from the page and the bottom is 100px)

You can do this to solve that issue:

```javascript
 afterRender: function(){
    	$('.fp-controlArrow').appendTo('.fp-slides');
}
```

See the demo here:
https://jsfiddle.net/1kyuL4em/206/
