### ISSUE TITLE
Cant Scroll inside Modal after enabling setAllowScrolling to False

### ISSUE THREAD

**Issue by artistro08** [alvarotrigo/fullPage.js#3534]
### Description
I'm trying to create a popup modal that is scrollable, while disabling scrolling on the `#fullpage` element. for the life of me, I can't figure it out. I'm not fluent in JS, but I know enough to get by. Might be a bug. 

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/artistro08/pen/EGWPZW

### Steps to reproduce it
1. create `#fullpage` wrapper with sections
2. create a popup modal with jQuery that's scrollable with `overflow-y: scroll`
3. Hide modal
4. Call modal via a click of an element

### Versions 
Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Windows 10 laptop

**Comment by artistro08** [comment]
Nevermind, I figured it out by adding `normalScrollElements` for the elements that I needed to whitelist

**Comment by alvarotrigo** [comment]
Glad you figured it out! :)
