### ISSUE TITLE
how to implement a licenseKey

### ISSUE THREAD

**Issue by sejui** [alvarotrigo/fullPage.js#3536]
Hi, I recently purchased the commercial license to implement react fullpage.js 
I input the licenseKey like this but it still complains 'fullpage.js:3388 fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:' 

I'm new to react, please advise me if I'm doing any wrong here, thanks! 

const licenseKey = "263DXXXX-B839XXXX-AE67XXXX-F398XXXX";

const FullpageWrapper = () => (
  <ReactFullpage
    licenseKey={licenseKey}
    anchors={anchors}
    navigation
    navigationTooltips={anchors}
    sectionsColor={["#282c34", "#ff5f45", "#0798ec"]}
    onLeave={(origin, destination, direction) => {
      console.log("onLeave event", { origin, destination, direction });
    }}
    render={({ state, fullpageApi }) => {
      console.log("render prop change", state, fullpageApi); // eslint-disable-line no-console

      return (
        <div>
          <div>page1</div>
          <div>page2</div>
          <div>page3</div>
        </div>
      );
    }}
  />
);

**Comment by alvarotrigo** [comment]
That's the correct way of doing it. Passing it to the licenseKey option.
If you still having problems please [contact me](https://alvarotrigo.com/#contact) with a link to the reproduction.

**Comment by monkeydri** [comment]
Hi @alvarotrigo, I just purchased a commercial license, does the `licenseKey` need to be kept private ? I mean does it need to be somehow kept secured on client side ?

**Comment by alvarotrigo** [comment]
> I mean does it need to be somehow kept secured on client side ?

Client side is by definition public to anyone who visit the site. Therefore unfortunately there's no secure way to hide the key from others.
