### ISSUE TITLE
Lightbox

### ISSUE THREAD

**Issue by dwsiddall** [alvarotrigo/fullPage.js#3537]
I am having trouble finding a lightbox that works with Fullpage.   I need to pop-up an html file (a restaurant menu).  I am finding that JS lightboxes simply don't functions and Pure CSS lightboxes only display images.

I read about using afterRender to allow plugins to work, but none of the documentation is clear (for a person at my level) and there are no clear instructions (like WHERE to place the code, etc) and demos.

**Comment by dwsiddall** [comment]
I had that piece of code, but as stated in the original question, it is never made clear where this code GOES.  Does it go by itself in the HTML file wrapped in a <script> tag?  Does it get added to the fullpage.js file?  Do I put the initialization script in the afterRender code or just the call for the JS file?

I appreciate that you took the time to answer, but I gained no new information from your answer.

Thank you for your time.

-Daniel

**Comment by alvarotrigo** [comment]
You can check tens of examples of how to use fullPage and where to initialise it in the examples folder provided here in the repository.
