### ISSUE TITLE
How to remove Dynamic 'top' Property from "fullpage-wrapper" class

### ISSUE THREAD

**Issue by ashvin0999** [alvarotrigo/fullPage.js#3538]
my page is working good with latest version of fullpage.js but one dynamic property creating the issue and when i scroll then it skips section to 3rd then 5th...

css dynamic property:

   `height: 100%;
    position: relative;
    touch-action: none;
    transform: translate3d(0px, -1578px, 0px);
    top: -2367px;
    transition: all 1000ms ease 0s;`

So, Please help me how to remove top property that added automatically.

**Comment by alvarotrigo** [comment]
`top` is never added to fullPage.js unless you use `css3:false`. 
But it doesn't seem you are as otherwise `translate3d`won't be applied. 

Seems to be something external to fullpage.js.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by ashvin0999** [comment]
Hello,

i did `css3:false` and then i have checked so i found that it skips one section alternatively.

i have 8-9 sections in one page but i scroll from top that skips 2nd and stop at 3rd then again scroll it skips 4th and stop at 5th , i dont know what is the problem?

and one thing i am getting that page by ajax call so once i refresh that page then it works well.

**Comment by alvarotrigo** [comment]
Unfortunately there's nothing I can do to help you without an isolated reproduction.
