### ISSUE TITLE
FP don't work well on iOS devices in Safari

### ISSUE THREAD

**Issue by keslo** [alvarotrigo/fullPage.js#3539]
Hello!
FP don't work well on iOS devices in Safari. Example, I have a iPhone SE and when I rotate that mobile to change in landscape orientation then is adding a padding that has height as well as navbar in Safari with little delay. That behavior is also in several templates in the demo section https://alvarotrigo.com/fullPage/ru/

**Comment by alvarotrigo** [comment]
I've tested it but I don't know what you mean by that. I don't see anything weird on Safari or Chrome in iOS.

Can you please explain what you mean with some image or video?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
