### ISSUE TITLE
Issue after ACF integration, scrolls only down 1 time, then stuck

### ISSUE THREAD

**Issue by ronalddev23** [alvarotrigo/fullPage.js#3542]
Hi there,

I am currently working on a website which is going to be a Wordpress one. I use ACF. Without ACF, the fullpage.js is working fine, but when I implemented the ACF, it got stuck on the second section. I have 4 sections, all are being loaded, the last two aren't reachable at all. 

Is there something known about the 'collaboration' between ACF and Fullpage.js, which I can read in to?

Thanks in advance !

**Comment by alvarotrigo** [comment]
I have no idea what ACF is :)

In any case, and as always, please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

I'll close the issue until then.

**Comment by ronalddev23** [comment]
Hi Alvaro, 

I solved it already, ACF is Advance Custom Fields btw. Without ACF I used <section> instead of <div class="section"> and that worked. But with ACF and Wordpress it didn't work anymore. So I changed it after some search.

Thanks for your reply
