### ISSUE TITLE
License Key in production

### ISSUE THREAD

**Issue by lifeinchords** [alvarotrigo/fullPage.js#3544]
I'm building and hosting a statically generated site with Webpack (aka, JAMStack). 
I purchased a commercial key. I can use it locally during development, now it's time to deploy to a public site. 

If I use an ENV var on the server/deploy service, that helps me avoid storing the key in source control / Github public repo (great).... 

but how do I package the key, deploy and build my static site  **without** exposing the key to anyone who views the source, and still have fullpage library validate it (which happens at runtime?)

Here's an article discussing the same issue and the author's comment https://dev.to/deammer/comment/4g5j

Am I missing something? How should this be done? Or is the only way via encryption (`node-cypher` ?) or obfuscation?

I'm guessing this is a general problem with static / JAMStack sites, this is the first lib Im running into this issue and am curious if you've run into this, or have any suggestions.

**Comment by alvarotrigo** [comment]
**There's no way you can hide if from someone who wants to find it.**

These are limitations of front-end code and unfortunately there's nothing we can do besides trying to make it harder for others by obfuscating it somehow.

You can perhaps take it from some HTML element and then remove that element:
```html
<input id="myKey" type="hidden" value="key" />
``` 

```javascript
new fullpage('#fullpage', {
    licenseKey: document.querySelector('#myKey').value;
});

//removing the element
var item = document.querySelector('#myKey');
item.parentNode.removeChild(item);
```

Anything you can think of. 
But nothing 100% bulletproof.

**Comment by katebrehm** [comment]
Ok, thanks for the detailed reply and suggestions. I'll give that a try

**Comment by notcarbide** [comment]
To expand on alvaro's answer, it is also possible to use [Google Tag Manager](https://marketingplatform.google.com/about/tag-manager/) . First you must create a **Custom HTML tag** in Tag Manager that contains the following:
```javascript
<script type="text/javascript">
var key = document.querySelector('#myKey');
key.value = "xyz"; //xyz is your actual licenseKey
</script>
```
For the **Triggering** option, create a **Custom Event** named *assign_key* (in Event Name).

And then in code, sImilar to what was posted above:
```html
<input id="myKey" type="hidden" value="null" />
```
```javascript
//Tag Manager event trigger for the key script
dataLayer = window.dataLayer || [];
dataLayer.push({'event': 'find_key'});

new fullpage('#fullpage', {
    licenseKey: document.querySelector('#myKey').value
}

//removing the element
var item = document.querySelector('#myKey');
item.parentNode.removeChild(item);
```

**Comment by alvarotrigo** [comment]
Who was talking about the google tag manager? 🤣
