### ISSUE TITLE
Updating the URL completely

### ISSUE THREAD

**Issue by wiadev** [alvarotrigo/fullPage.js#3545]
Hi Thanks for the awesome plugin

I'm integrating fullstack.js on ionic v3.

I'm integrating your angular-fullpage demo project on localhost:8000/#/card.

The first screen was displayed but when I scroll down, it's updating the scroll completely.
(e.g. localhost:8000/#secondPage)

Any thoughts on this?

Thanks

**Comment by alvarotrigo** [comment]
> localhost:8000/#/card.

Whatever is after `#` is considered a hashtag. 
fullPage.js will change the hastag as long as you use anchors and do not use `lockAnchors:true`.

**Comment by wiadev** [comment]
```
this.config = {
      licenseKey: 'AF6E6FEF-0C764731-8289ADEB-285F2ADA',
      resetSliders: true,
      resetSlidesKey: 'QU5ZX3RBQWNtVnpaWFJUYkdsa1pYSnpNMTQ=',
      continuousHorizontal: true,
      continuousHorizontalKey: 'QU5ZX3Y1N1kyOXVkR2x1ZFc5MWMwaHZjbWw2YjI1MFlXdz0zVzY=',
      anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'lastPage'],
      menu: '#menu',
      recordHistory: false,
      slidesNavigation: true,
      scrollOverflow: true,
      scrollOverflowReset:true,

      // events callback
      afterLoad: (origin, destination, direction) => {
        //change the title of the page here.
      },
      onLeave: (origin, destination, direction) => {
        //changing the color of the body with a transition
        document.body.style.backgroundColor = colors[destination.index];
      },
      afterRender: () => {
        // console.log('afterRender');
      },
      afterResize: (width, height) => {
        // console.log('afterResize' + width + ' ' + height);
      },
      afterSlideLoad: (section, origin, destination, direction) => {
        // console.log(destination);
      }
    };
```

Here is my config and I don't use `lockAnchors: true`.
I believe it's false by default.

**Comment by alvarotrigo** [comment]
Yeap, I said " as long as you do NOT use `loackAnchors`" :)

Nothing weird on the behaviour you are facing. It is exactly how it is supposed to work.

**Comment by wiadev** [comment]
Thanks.
I've included `scrolloverflow.min.js` and got the following error.

```
Uncaught SyntaxError: Unexpected token < (scrolloverflow.min.js:1)
```

any thoughts?

**Comment by alvarotrigo** [comment]
First of all. Do you have that issue when using normal anchors?
Or as a result of the solution I recommended?

If it's not related at all, open a new issue with a link to an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
