### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < with scrolloverflow.min.js

### ISSUE THREAD

**Issue by wiadev** [alvarotrigo/fullPage.js#3546]
Hi
I've integrated the fullpage.js on my project(ionic) and vertical scrolling works fine.

I've set `continuousHorizental: true` and included the scrolloverflow.min.js but got the following error.

```
Uncaught SyntaxError: Unexpected token (scrolloverflow.min.js:1)
```

Do you have any thoughts? 

FYI, while I'm investigating, I found that there was a PR related to the above bug but not sure it was fixed already.

Thanks

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by wiadev** [comment]
Used CDN for now

**Comment by alvarotrigo** [comment]
No idea what you mean by that, but glad you managed to solve your issue :)
