### ISSUE TITLE
onLeave but once

### ISSUE THREAD

**Issue by othy54** [alvarotrigo/fullPage.js#3547]
Hello I have this using inside fullpage 

if (destination.index == 2) {
            const line = new Vivus('my-svg', { duration: 200 });
            line.play(0.0);
          }

I'm using it with onLeave but I want the effect to be played only the first time we go to that section how can I do ? 

Thanks !

**Comment by othy54** [comment]
found solution here https://github.com/alvarotrigo/fullPage.js/issues/93

Thanks ! ^^

**Comment by alvarotrigo** [comment]
Glad you did!
