### ISSUE TITLE
Navbar active

### ISSUE THREAD

**Issue by TWDbag** [alvarotrigo/fullPage.js#3548]
Hi,
I am new to this so I need a little bit of help.
I am trying to make the navabar active for more than 3 tabs but unfortinatly I can't.

Here is the .html code and in the .js I wasn't changing anything.
Do I have to do something else except adding a new page?

https://pastebin.com/E6t2HnnP

I have tried solving this issue as stated [here](https://github.com/alvarotrigo/fullPage.js/issues/3021) and [here](https://github.com/alvarotrigo/fullPage.js/issues/2630).

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
