### ISSUE TITLE
Menu scrolls to nearest instead of top of section when fp-auto-height-responsive

### ISSUE THREAD

**Issue by tb9jen** [alvarotrigo/fullPage.js#3550]
I have the responsive settings in place, and I have .fp-auto-height-responsive so you can scroll through the sections properly, and using the menu (the hamburger) you can scroll to the sections correctly if you are above the section on the page (although it could use an offset). However,  if i'm below the section I click to, it takes me to the BOTTOM of that section not the top. Any way to fix this?

Recreated issue here (
https://codepen.io/anon/pen/mvemNm

1. make sure browser is less than 1400px wide. 
2. use the navigation to scroll to the third section from the top
3.  use the navigation again to scroll to the second section from the third. 
4. You'll see the bottom of the second section rather than the top. 

OSX Mojave, Chrome 71, fullpage 3.0.4 - commercial license purchased.

**Comment by alvarotrigo** [comment]
Use the option: bigSectionsDestination

> **bigSectionsDestination:** (default null) Defines how to scroll to a section which size is bigger than the viewport. By default fullPage.js scrolls to the top if you come from a section above the destination one and to the bottom if you come from a section below the destination one. Possible values are top, bottom, null.
