### ISSUE TITLE
single one section with autoscrolling

### ISSUE THREAD

**Issue by stivoox** [alvarotrigo/fullPage.js#3551]
Hi friends .
I want to know if there's a way to use auto scrolling with one single section , that mean having one section and then after the smooth scrolling we have the rest of the content.
regards ^^

**Comment by alvarotrigo** [comment]
If you do not mind using `scrollBar:true` you can use the approach commented on this post:
https://github.com/alvarotrigo/fullPage.js/issues/3205#issuecomment-458642204
