### ISSUE TITLE
hardyal singh

### ISSUE THREAD

**Issue by hardyalsingh28** [alvarotrigo/fullPage.js#3552]
i want to show two section which is work vertical properly but when i create the slides in second section then it slides does not work horizontally on mouse scroll
code is mentioned below please check and revert its very urgent

/*-------HTML CODE----------*/
<header>
            <div class="header-top clearfix">
                <h1 class="l-left"><a href="#firstSection">Your Logo</a></h1>
                <a class="l-right toggle-menu" href="#">
                    <i></i>
                    <i></i>
                    <i></i>
                </a>
            </div>

            <nav class="hide">
                <ul id="menu">
                    <li data-menuanchor="firstSection">
                        <a href="#firstSection" title="First Section">First Section</a>
                    </li>
                    <li data-menuanchor="fifthSection">
                        <a href="#secondSection" title="First Slide">First Slide</a>
                    </li>
                    <li data-menuanchor="fifthSection/1">
                        <a href="#secondSection/1" title="Second Slide">Second Slide</a>
                    </li>
                </ul>
            </nav>
        </header>

        <div id="fullpage">
            <section class="vertical-scrolling">
                <h2>fullPage.js</h2>
                <h3>This is the first section</h3>
                <div class="scroll-icon">
                    <p>Jump into the last slide</p>
                    <a href="#secondSection/1" class="icon-up-open-big"></a>
                </div>
            </section>
            <section class="vertical-scrolling">
                <div class="horizontal-scrolling">
                    <h2>fullPage.js</h2>
                    <h3>This is the fifth section and it contains the first slide (actually section == first slide)</h3>
                </div>
                <div class="horizontal-scrolling">
                    <h2>fullPage.js</h2>
                    <h3>This is the second slide</h3> 
                    <p class="end">Thank you!</p>
                </div>
            </section>
        </div>

/*---------javascript code------------*/

// variables
var $header_top = $('.header-top');
var $nav = $('nav');

// toggle menu 
$header_top.find('a').on('click', function () {
    $(this).parent().toggleClass('open-menu');
});

// fullpage customization
$('#fullpage').fullpage({
    sectionsColor: ['#B8AE9C', '#348899'],
    sectionSelector: '.vertical-scrolling',
    slideSelector: '.horizontal-scrolling',
    navigation: false,
    slidesNavigation: true,
    controlArrows: false,
    anchors: ['firstSection', 'secondSection'],
    menu: '#menu',
    afterLoad: function (anchorLink, index) {
        $header_top.css('background', 'rgba(0, 47, 77, .3)');
        $nav.css('background', 'rgba(0, 47, 77, .25)');
        if (index == 5) {
            $('#fp-nav').hide();
        }
    },
    onLeave: function (index, nextIndex, direction) {
        if (index == 5) {
            $('#fp-nav').show();
        }
    },
    afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {
        if (anchorLink == 'secondSection' && slideIndex == 1) {
            $.fn.fullpage.setAllowScrolling(false, 'up');
            $header_top.css('background', 'transparent');
            $nav.css('background', 'transparent');
            $(this).css('background', '#374140');
            $(this).find('h2').css('color', 'white');
            $(this).find('h3').css('color', 'white');
            $(this).find('p').css(
                    {
                        'color': '#DC3522',
                        'opacity': 1,
                        'transform': 'translateY(0)'
                    }
            );
        }
    },
    onSlideLeave: function (anchorLink, index, slideIndex, direction) {
        if (anchorLink == 'secondSection' && slideIndex == 1) {
            $.fn.fullpage.setAllowScrolling(true, 'up');
            $header_top.css('background', 'rgba(0, 47, 77, .3)');
            $nav.css('background', 'rgba(0, 47, 77, .25)');
        }
    }
}); 

Please help me to solve it..........

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
