### ISSUE TITLE
Is there one methd to  scroll inside box and the scroll outer box?

### ISSUE THREAD

**Issue by Tinalst** [alvarotrigo/fullPage.js#3553]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
no
### Steps to reproduce it
hi, everyone, I don't know  how to describe my problem, therefore I draw a picture ;
[picture-click-me](https://github.com/Tinalst/readme_pic/blob/master/FQA/WechatIMG108.jpeg)

is there some method can prevent outer scroll and after scrolled section2.1 and section 2.2 then scroll section3?
### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
I'm sorry I have no idea what you mean.
But all you need to know is in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). If you can't find it there, then it is probable not possible :)

**Comment by Tinalst** [comment]
Hi, @alvarotrigo .
Scrolling the first screen and entering the second screen scrolls the container in the second screen before leaving the second screen (there are two screens in the container, ensuring that the contents of the container are scrolled before continuing to scroll)

**Comment by alvarotrigo** [comment]
Might be related with https://github.com/alvarotrigo/fullPage.js/issues/3549
