### ISSUE TITLE
Youtube video as fullpage background

### ISSUE THREAD

**Issue by stivoox** [alvarotrigo/fullPage.js#3555]
Hi .
I just want to know hwa to put youtube video as fullpage background , I have tried this approch as mentioned here : https://alvarotrigo.com/fullPage/examples/videoBackground.html, in a video tags but this doesn't work .
any idea ??

**Comment by alvarotrigo** [comment]
It is working on the demo, so you are definitely not doing it the same way :) 
Make sure the video is muted. Browsers policy won't allow to autoplay videos with sound.

**Comment by stivoox** [comment]
@alvarotrigo But it's not a Youtube video . I said a youtube video .

**Comment by alvarotrigo** [comment]
You'd better ask for that somewhere else. 
It is not a fullpage.js matter how you create a fullscreen youtube video.

All you need to know about autoplay or autopause youtube videos is on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
