### ISSUE TITLE
Testing out fullpage on localhost:port but not working

### ISSUE THREAD

**Issue by frazerf** [alvarotrigo/fullPage.js#3556]
### Description

Hi there,

I'm trying to achieve a multidimensional page and I've stumbled across fullpage which looks like it could work but I want to test it out first. I've set up a local web server - http://127.0.0.1:5010 - but the console is saying I need a license. Am I doing something wrong?

**Comment by alvarotrigo** [comment]
That message won't prevent you from testing it. 
Take any of [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) as a starting point if you are having troubles.
