### ISSUE TITLE
Scrolloverflow does not work on mobile (fullpage.js 2.9.7)

### ISSUE THREAD

**Issue by apple0408** [alvarotrigo/fullPage.js#3561]
### https://www.bottless.hk 
The environment is wordpress...

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
fullpage.js version 2.9.7 
scrolloverflow does not work on iphone X, Galaxy S5, all android phones when the content has larger height.

**Comment by alvarotrigo** [comment]
Unfortunately fullPage.js version 2 is no longer maintained. 
You would have to updated to version 3.
