### ISSUE TITLE
Changing slidesNavigation from text to numbers

### ISSUE THREAD

**Issue by craigb88** [alvarotrigo/fullPage.js#3563]
Is there a way or an option to change the slidesNavigation from slide 1, slide 2 etc to 01, 02, 03

**Comment by alvarotrigo** [comment]
Sure!
See the docs regarding the navigation tooltips:

> **navigationTooltips**: (default []) Defines the tooltips to show for the navigation circles in case they are being used. Example: navigationTooltips: ['firstSlide', 'secondSlide']. You can also define them by using the attribute data-tooltip in each section if you prefer.

Just use the navigationTooltips option:

```
new fullpage('#fullpage', {
    navigationTooltips: ['01', '02', '03']
});
```

**Comment by alvarotrigo** [comment]
You have an example available in the examples folder:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/navigation-tooltips.html

**Comment by craigb88** [comment]
Sorry, I should have been more descriptive! So I have 4 sections which use the bullet point navigation on the left. The second and forth sections have horizontal slides in there which I need to use 01, 02, 03 etc. 

This needs to be some what dynamic though as the first section with horizontal slides has 7 slides and the forth section has 9 slides. 

Is this possible? So I need just bullet points to make the page go up / down and number to make the slides go left / right.
