### ISSUE TITLE
ScrollOverflowReset not working

### ISSUE THREAD

**Issue by acagnoli** [alvarotrigo/fullPage.js#3564]
Hi Alvaro,

I'm finishing a project using fullpage.js and i got an issue with ScrollOverflowReset that don't want to work, i registered everything, and got no error msg. It's just not working.
Everything is fine except that. I precise that i use css grid and flex in my layouts.
Here is a link to the project, to a specific page wich is impacted.

http://rapportmediateur2018.mediation-telecom.org/#exemples/slide2

Any idea ?

Cheers

Alex

**Comment by alvarotrigo** [comment]
Working perfectly on the [demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html) and the example provided in the examples folder of this repository.

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
