### ISSUE TITLE
scrollOverflow: true not working when the fullpage.extensions.min.js is used

### ISSUE THREAD

**Issue by FTA-RBeaney** [alvarotrigo/fullPage.js#3565]
### Description
After replacing the regular Fullpage.js with the extensions version (to use the fade effect) the scrollOverflow: true no longer works, despite including everything in the correct order.

This error shows in the console:
"fullPage: The option `scrollOverflow:true` requires the file `scrolloverflow.min.js`. Please include it before fullPage.js."

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/tvakydpe/

### Steps to reproduce it
1. Replace fullpage.js with fullpage.extensions.min.js
2. Place scrolloverflow.min.js first, then the extension file, then fullpage.extensions.min.js
3. Set scrollOverflow to true
4. Error shows in console

### Versions 
fullPage 3.0.4 - Extensions 0.1.7
scrolloverflow: Customized version of iScroll.js 0.0.8

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with a link to the isolated reproduction. (The one you posted is not actually a reproduction as it is not working at all)
