### ISSUE TITLE
RecordHistory not working when using scrollBar:true

### ISSUE THREAD

**Issue by Kamran-Nasir47** [alvarotrigo/fullPage.js#3566]
Hello @alvarotrigo ,

Hope you are doing great, I have used your plugin many times in different websites and I am very thankful to you for this awesome plugin. Really appreciated.

Now, I am using your plugin in my website. I am facing two issues. 

1. RecordHistory does not work with scrollBar: true, 
2. I am using Popup with detail section of every slide with URL of xyz.com/#slide1/slide1-detail. When i close Popup i am removing URL slide1-detail and that way the #slide1 also removing.

Could you please help mw regarding these issues.

Kind Regards,
Kamran Nasir

**Comment by alvarotrigo** [comment]
> * RecordHistory does not work with scrollBar: true,

Thanks for reporting it! It seems it is not working either on the [example page](https://alvarotrigo.com/fullPage/examples/scrollBar.html#firstPage) using scrollBar:true.



> 2\. I am using Popup with detail section of every slide with URL of xyz.com/#slide1/slide1-detail. When i close Popup i am removing URL slide1-detail and that way the #slide1 also removing.

fullPage.js won't expect you to play with the URL, so you'll have to deal with the consequences of that by yourself. Not something fullPage.js contemplates.

**Comment by Kamran-Nasir47** [comment]
Thanks for you quick reply. Really appreciated.

So any way to achieve both scrollBar: true and RecordHistory: true at the same time?

**Comment by Kamran-Nasir47** [comment]
Actually i am using animate.css for animations on slider content. As you know that animate.css trigger animations with body scroll that's why i have enable scrollBar: true. If RecordHistory: true and scrollBar: true does not work at the same time then please suggest me how to trigger animations of animate.css without scrollBar: true?

**Comment by alvarotrigo** [comment]
> So any way to achieve both scrollBar: true and RecordHistory: true at the same time?

That seems to be a bug at the moment. I've marked the issue as a "bug", so I'll try to solve it for the next release.



> Actually i am using animate.css for animations on slider content. As you know that animate.css trigger animations with body scroll that's why i have enable scrollBar: true. If RecordHistory: true and scrollBar: true does not work at the same time then please suggest me how to trigger animations of animate.css without scrollBar: true?

Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by Kamran-Nasir47** [comment]
Hey! Thank you for your help. I have achieved the things that i wanted to. Cheers. :)

**Comment by alvarotrigo** [comment]
I've fixed the issue! 
The back and forward button won't create animations to the previous or next section/slide due to browser restrictions, but at least they'll now be able to navigate using them as it would be expected.

This will get merged in the next release of fullpage.js version 3.0.5.

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
