### ISSUE TITLE
IScorll 'scrollToElement' not working with fullpage.js & scrolloverflow

### ISSUE THREAD

**Issue by Nathan-F** [alvarotrigo/fullPage.js#3567]
Hi Alvarotrigo,

I'm having trouble with getting IScroll to scroll to an element using the scrollToElement method https://github.com/cubiq/iscroll#scrolltoelementel-time-offsetx-offsety-easing

wondering if I need to call this in a different way when using fullpage.js & scrolloverflow.js

Here is a pen of what I have tried but with no joy :(
https://codepen.io/anon/pen/XOeyyv

For the pen I have set the event to fire on click although in my site it will trigger like the bellow
```
if(window.location.href.indexOf("?origin") > -1) {
  setTimeout(function(){
   fullpage_api.moveTo(2, 0);

   setTimeout(function(){
     IScroll.scrollToElement(document.querySelector("#scrollToOrigin"))
   }, 3000);
			
  }, 3000);
}
```

Using Firefox on windows desktop although don't think this is a browser issue.

Hope you can help as this has stumped me and my client needs this functionality :(

**Comment by alvarotrigo** [comment]
You probably have to get the iscroll instance that you want from the section or slide for which you want to call the method `scrollToElement`.
Something among these lines:

```javascript
//getting the scrollable element for the active section (using jQuery)
var  scrollable = $('.fp-section.active').find('.fp-scrollable')[0];

//getting the iScroll instance for that scrollable element
var iScrollInstance = scrollable.fp_iscrollInstance;

//calling the method you want
iScrollInstance.scrollToElement(document.querySelector("#scrollToOrigin"));
```

**Comment by Nathan-F** [comment]
Thank you, that makes sense will give it a go.

**Comment by alvarotrigo** [comment]
You can see the same approach in the [the scrollOverflow file](https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.js#L2374).

**Comment by Nathan-F** [comment]
Hi Alvaro,

Thank you so much for taking the time to explain this to me.

It is all working as expected now so thanks again.

Amazing plug-in can see how much hard work has gone into it, keep up the
good work 👍

Kind regards

Nathan

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! 😉 
And thanks for appreciating it!
