### ISSUE TITLE
Change sidebar menu

### ISSUE THREAD

**Issue by nemanjasipka** [alvarotrigo/fullPage.js#3568]
### Description
I have client that use your fullpage.js plugin and he want  to create this: Please can you change the side nav so that ALL pages / sections are shown at all times... so instead of having the – icon for each page actually show them saying 'HOME', 'ENTER HERE', 'ABOUT'...etc, etc,. Then we can still animate to the red dot on hover, perhaps also make the text red on hover as well.

Can you tell me where exactly I can do this.

Here is the link of the website: 
http://www.thousandfilms.co.uk/temp_index.html

**Comment by alvarotrigo** [comment]
This forum intends to provide general support for fullPage.js issues or questions, not for specific websites or use cases.

You'd better ask about that in another place such as stackoverflow where they'll be able to help you better.
