### ISSUE TITLE
drag not working on google map

### ISSUE THREAD

**Issue by shahjehanali1** [alvarotrigo/fullPage.js#3569]
not b able to drag google map when `scrollOverflow: true`, also iScroll don't have anwser of this bug
Check this [iScroll #1238](https://github.com/cubiq/iscroll/issues/1238)

**Comment by alvarotrigo** [comment]
That's a iScroll issue. If it is not solved there, there's nothing we can do in fullpage.js about it.
I would encourage you not to use `scrollOverflow:true`.

**Comment by david43** [comment]
You can lock fullpage when dragstart.
```
map.addListener('dragstart', function() {
	vm.fullpage.setAllowScrolling(false);
});
map.addListener('dragend', function() {
	vm.fullpage.setAllowScrolling(true);
});
```

**Comment by alvarotrigo** [comment]
@david43 awesome to know!

**Comment by syakirurahman** [comment]
Just trying to help. Adding scrollOverflowOptions as follows solves the problem.

`scrollOverflowOptions: {
   disablePointer: true,
}`
