### ISSUE TITLE
Background pops in to view after scrolling on iOS

### ISSUE THREAD

**Issue by thetwopct** [alvarotrigo/fullPage.js#3570]
### Description
I'm working on a site build and noticed some issues with fullpage.js on Safari on iOS. When swiping up and down for a while, the background pops over the top of content. This happens when an image or a colour is a background (I spent a while thinking it was to do with iOS fixed background issue, but then realised it happens when only using bg colour too).

Maybe I'm doing something wrong, or its something very obvious for you Alvaro, but after a few hours of searching and experimenting, I thought I would ask! Thanks in advance

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/thetwopct/pen/pGVBpW

### Steps to reproduce it
1. Start scrolling up and down multiple times
Here's a video - https://youtu.be/_ZHzwNNDNw8 - starts happening around 23 seconds.

### Versions 
FP 3.0.4
iOS Safari (latest)

**Comment by thetwopct** [comment]
As usual, a solution seems to present itself but gleamed from trying to fix something else 😂

I added

`css3: false`

and this fixed the issue I believe

**Comment by alvarotrigo** [comment]
I would encourage you to keep using `css3:true` as it will perform much better.

You should try removing the `fixed` property from your body background. 
You won't need it, as the body won't scroll at all. Try that way and see if it works better for you.
