### ISSUE TITLE
normalScrollElements not working with scrollOverflow: auto,

### ISSUE THREAD

**Issue by shahjehanali1** [alvarotrigo/fullPage.js#3572]
I'm trying to use normalScrollElements but it's not working with scrollOverflow: auto,

**Comment by alvarotrigo** [comment]
`scrollOverflow:auto` is not a valid value :)
It has to be true or false.

And yeah, not surprising. It won't support both options together.

**Comment by shahjehanali1** [comment]
https://www.sebrichards.ca/qwest/
I make last section as normalScrollElements but its not working
this is my code
'var myFullpage = new fullpage('#home_page',{
            licenseKey: '9FB52152-D04E47DF-B8D8F3F8-4E7404BA',
            navigation: true,
            navigationPosition: 'right',
            scrollOverflow: true,
            normalScrollElements: '#buy, .options, .map-holder,.google-map',
            afterLoad: function(origin, destination, direction){
                // console.log(origin, destination, direction);
                // console.log(destination.index);
                // console.log(destination.index);
                if(destination.index == 0 ){
                    fullpage_api.setAllowScrolling(false);
                }
                if(destination.index == 1 ){
                    fullpage_api.setAllowScrolling(true);
                    fullpage_api.setAllowScrolling(false, 'up');
                }else if(destination.index > 1){
                    fullpage_api.setAllowScrolling(true);
                }
            }
        });'

**Comment by shahjehanali1** [comment]
https://www.sebrichards.ca/qwest/
I make last section as normalScrollElements but its not working
this is my code
`var myFullpage = new fullpage('#home_page',{
            licenseKey: 'Key',
            navigation: true,
            navigationPosition: 'right',
            scrollOverflow: true,
            normalScrollElements: '#buy, .options, .map-holder,.google-map',
            afterLoad: function(origin, destination, direction){
                // console.log(origin, destination, direction);
                // console.log(destination.index);
                // console.log(destination.index);
                if(destination.index == 0 ){
                    fullpage_api.setAllowScrolling(false);
                }
                if(destination.index == 1 ){
                    fullpage_api.setAllowScrolling(true);
                    fullpage_api.setAllowScrolling(false, 'up');
                }else if(destination.index > 1){
                    fullpage_api.setAllowScrolling(true);
                }
            }
        });`

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
