### ISSUE TITLE
Open Source License Key

### ISSUE THREAD

**Issue by palash96rox** [alvarotrigo/fullPage.js#3573]
Hi, I'm so sorry if this has been answered before, but I can't seem to find the link to request a license key for our open source landing page. I had requested already but on receiving no response, I wanted to send in another request. The project is pushed to [github](https://github.com/BU-hack/BU-hack). The landing page is for a college hackathon, and hence we were not very keen on obtaining a commercial license.

Please do check, our contact email is `bu [dot] hack [at] bennett [dot] edu [dot] in`

**Comment by alvarotrigo** [comment]
Just [contact me](https://alvarotrigo.com/#contact)
