### ISSUE TITLE
scroll back on small footer

### ISSUE THREAD

**Issue by overheaddesign** [alvarotrigo/fullPage.js#3578]
Hello,
what can I do if I have the scrollbar active and the footer is relatively small?
Whenever I am at the footer, it automatically scrolls back to a section.

what can I do?

**Comment by alvarotrigo** [comment]
Use the option `fitToSection: false`.

**Comment by alvarotrigo** [comment]
Or, turn it off using the afterLoad or onLeave callback when arriving to that last section using the method  `setFitToSection(false)`

**Comment by overheaddesign** [comment]
are there any examples with afterload and fittoselection?

**Comment by alvarotrigo** [comment]
On the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) you can find examples for both. 
Just put them together.

**Comment by overheaddesign** [comment]
Thank you. but i have autoscrolling false. the method settosection starts so if I scroll in the index 4 purely. But I would like to change the fittosection if my index 4 is in the right place.

**Comment by alvarotrigo** [comment]
@overheaddesign not an easy one then.
Perhaps turn it off when your reach section 4? 

Then on again when you do an onLeave to section 3?
