### ISSUE TITLE
Parallax Plugin Possible issue with background images not loading

### ISSUE THREAD

**Issue by jcbrown33** [alvarotrigo/fullPage.js#3579]
### I purchased the parallax, added the reg codes as needed and have everything working great on my test site newsite.silverfoxwebdesigns.com which is where I make changes and updates and then upload to the root as to not effect the main site. 

I copied the files exactly as they are on my test site as I always do, double checked to make sure. Uploaded fine and you can load the images if you type in the direct link to the image, they load fine. 

I have in the CSS ../img/imagename.png as well I've used a direct link with the full website url and neither will load the background. I have a feeling it's the plugin as all the code on my end seems fine. 

You can view the main site at silverfoxwebdesigns.com and the test site at newsite.silverfoxwebdesigns.com, both identical yet one loads the images and the other does not. 

### Versions 
Latest Opera and tested on latest Chrome

**Comment by jcbrown33** [comment]
Is there something with the license or something preventing it from working on both domains? 

Speedy help is much appreciated.

**Comment by jcbrown33** [comment]
anyway, i wanted the developer to look at both sites. I can temp take down the test site to see if that changes anything. I'll do that real fast and if that doesn't work then I'll put it back up so the dev can view it. One moment.

**Comment by jcbrown33** [comment]
K, well the test site is taken down, not sure if that helped anything, the main site is still not loading the background images. Pretty sure it's the plugin, need some insight at this point. Thanks.

**Comment by jcbrown33** [comment]
Anyway, test site is back up, root site is back up. I've asked my hosting to make sure it's not a server issue. I'm still pretty sure it's a plugin license issue as I only purchased the 1 site license, but again I don't know how you have that setup. At any rate I will need to be able to develop on the test domain and transfer to my root often so will need to be able to have this work on both, same domain, one site is active the other is for testing only. Anyway, any help is much appreciated at this point as the site looks quite bland without the images.

**Comment by alvarotrigo** [comment]
As you said, it was working on your test side, so the issue has nothing to do with the parallax extension or fullpage.js for that matter.
It is probably a HTML, CSS or even a server issue. 

Check your paths for images and make sure you have no errors in console.

**Comment by jcbrown33** [comment]
http://www.silverfoxwebdesigns.com/img/background001.png will load just fine. I even put this in the CSS on the root site. The code is exactly the same as it was on the test site it didn't work, since then I've tried several combinations on the root site considering exactly what you said. I even reached out to my server provider, you and then say the same thing, yet, img loads fine, they are there, CSS is fine, It's loading, but still nada. Yet on test site images load no issues. 

I'm pretty sure it's the licensing of this plugin. Can you explain how that works and if it prevents the plugin from working, because pretty sure that's the issue here, there is no reason for the background to not load otherwise. I've tried every other combination and you can't deny the direct link which also is not loading.

**Comment by jcbrown33** [comment]
As well all images not related to the plugin in the content area of the site are loading, they load from the same directory as the backgrounds. As I said, the code was identical, works on one, doesn't on the other. 

Anyway, please explain how your licensing system works because I only purchased a single site license and the plugin is acting like it did when I did not have the auth codes.

**Comment by jcbrown33** [comment]
#section01 .fp-bg {background-image: url('../img/background001.png');} Is how the code is on the test site, works. This code should also work on any other site as long as the img folder is there with the images in the folder which has already been confirmed. Doesn't work, 


#section01 .fp-bg {background-image: url('img/background001.png');}
#section01 .fp-bg {background-image: url('/img/background001.png');}
#section01 .fp-bg {background-image: url('http://www.silverfoxwebdesigns.com/img/background001.png');}

Are other combos I tried because you never know, all fail. Yet you copy the domain name url to the image and paste it in the browser, loads the image.

**Comment by jcbrown33** [comment]
I just tried the same CSS on the body and it's loading the background image no issue. 

Pretty sure at this point the only thing that remains is the plugin, everything else seems fine.

**Comment by alvarotrigo** [comment]
If you think there's an issue with the extension, then please [contact me](https://alvarotrigo.com/#contact) with an isolated reproduction of it, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by jcbrown33** [comment]
Just look at the 2 sites, you can view code easily. There is nothing to the websites, very simple. 
silverfoxwebdesigns.com and newsite.silverfoxwebdesigns.com where you can see all the the code and see how it's the same and working on one and not on the other. I've exhausted all options at this point and have already done what you've requested. We're at the point now where it's most likely a license issue. If I had to guess my code registered on your system for the newsite.silverfoxwebdesigns.com and thus won't allow it to run on any other domain. Even though I got the auth code for silverfoxwebdesigns.com.

**Comment by jcbrown33** [comment]
I had another dev take a look, we are get a 0 background setting via your plugin on the root site. If we set the background size up the image shows. So we've determined the issue lies in the plugin, most likely not a bug or anything like that, but most likely a license issue. Is there a way to update the domain the license is attached to ??????

**Comment by jcbrown33** [comment]
Anyway, we've both reached the same conclusion on our end. License issue. How do we fix this with the license?

**Comment by jcbrown33** [comment]
I emailed you.

**Comment by jcbrown33** [comment]
In case anyone was curious. this issue is resolved now. It wasn't a coding issue it was the fact that fullpage.js was being loaded at the time the fullpage.exentsions.min.js was loading and so removal of the call to load fullpage.js and only loading the extension.min.js fixed this issue. Strange it worked with both loading on the test site, but at any rate, it's working.
