### ISSUE TITLE
refresh iscroll

### ISSUE THREAD

**Issue by festwertspeicher** [alvarotrigo/fullPage.js#3583]
i have a problem with an image that's getting loaded dynamically by a script.
the section uses scrollOverflow:true and the image gets cropped
(iScroll calculates the height of this section without the image).

how do i call the refresh method provided by iScroll after the image is loaded?
https://github.com/cubiq/iscroll#mastering-the-refresh-method

**Comment by festwertspeicher** [comment]
at the moment i'm triggering the window resize event on this slide to get the refresh method called.
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events
this is a hacky solution and i would enjoy if there is a cleaner way to do that.

**Comment by meceware** [comment]
Hi,

Have you tried calling [rebuild](https://github.com/alvarotrigo/fullPage.js#rebuild)?
`fullpage_api.reBuild();`

**Comment by festwertspeicher** [comment]
yes, rebuild works, thank you! this can be closed now...

**Comment by alvarotrigo** [comment]
@meceware thanks for the answer! I appreciate it! 😉
