### ISSUE TITLE
Scrolloverflow 0.1.1 causing a section skip

### ISSUE THREAD

**Issue by eddogan** [alvarotrigo/fullPage.js#3585]
I have a live site in production using fullpage.js and scrolloverflow. https://www.flyomni.com/aircraft/learjet-45/

I was getting a maximum call stack exceeded error which was listed as an issue in the react version. I applied the fix and used the v0.1.1 in dev site. 
https://oatransportdev.wpengine.com/aircraft/learjet-60-se/

But with this new fix, it's skipping sections even if I use the keyboard controls. Initialization script contains these options:
```
scrollOverflow: true,
sectionSelector: '.scrollful',
lazyLoading: false,
scrollingSpeed: 1200,
css3: true,
easingcss3: 'cubic-bezier(1,.00,.50,.50)',
fixedElements: '#aircraft, .previous_aircraft, .next_aircraft',
```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
The [scrolloverflow demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html) seems to be working as expected.

**Comment by eddogan** [comment]
I had multiple initialization scripts, for iPad Pros and IE, that was causing the problem. Sorry for bothering you.
