### ISSUE TITLE
getFullpageData is a function when using fullpage.extensions.js

### ISSUE THREAD

**Issue by ollyradford** [alvarotrigo/fullPage.js#3588]
Hi there,

If I create a new instance of fullpage using fullpage.js:

`var myFullPage = new fullpage('#fullpage');`

`myFullPage.getFullpageData` is an object and I can extract tooltips etc from it

https://codepen.io/anon/pen/XGmBga?editors=1111

Switch to fullpage.extensions.js and `myFullPage.getFullpageData` is now a function
https://codepen.io/anon/pen/YgyjBb?editors=1111

I am not sure if this is a bug or if my JS knowledge is too weak to understand this problem. Should both versions of the JS file return the same either the function or the object?

Hope someone can help get me back on track.

Thanks,
Olly

**Comment by alvarotrigo** [comment]
> I am not sure if this is a bug or if my JS knowledge is too weak to understand this problem. Should both versions of the JS file return the same either the function or the object?

That's how it is right now.
I should probably change it to make it exactly the same :) However, `getFullpageData` is not really a function I've documented anywhere, so I though nobody would make use of it.

**Comment by ollyradford** [comment]
Is there another method to get the tooltips from the initialised instance of fullPage?

If not, I would be very happy to see an update to fullpage.extensions.js so `myFullPage.getFullpageData` returns an object.

**Comment by alvarotrigo** [comment]
> Is there another method to get the tooltips from the initialised instance of fullPage?

Nop.

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!
