### ISSUE TITLE
Only one section and iPhone in landscape mode

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#3590]
### Description
If there's only one section and you browse it using Safari on an iPhone, once you rotate the phone horizontally, Safari's address bar and the lower bar will cover a big part of the content.

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html

### Steps to reproduce it
1. Click the link from your iPhone
2. Turn the iPhone in landscape mode

### Versions 
iPhone 6s ios 12.1.4, Safari

**Comment by alvarotrigo** [comment]
Yeap, we developers have no control over the top or bottom bars showed in mobile browsers.
Try not using `anchors` or using `lockAnchors` to see if you get any better result.

If you want to emulate the default behaviour of any site, you should be using `scrollBar:true`.
