### ISSUE TITLE
IE 10 / 11 Scroll issue

### ISSUE THREAD

**Issue by nelly-gretsch** [alvarotrigo/fullPage.js#3592]
### Description

https://www.dimeoschneider.com/services

### Steps to reproduce it
1. https://www.dimeoschneider.com/services
2. Scoll down in IE 10 or 11
3. The nav element scrolls, however the background slides aren't. Console triggers errors in extension JS file (minified and not edited).

### Versions 
IE 10 or IE 11

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
