### ISSUE TITLE
overlay slide

### ISSUE THREAD

**Issue by ricksternyc** [alvarotrigo/fullPage.js#3593]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Closed as there's not a single line of text in the body of the issue.

**Comment by ricksternyc** [comment]
Sorry, mistakenly submitted while searching for answers.
