### ISSUE TITLE
Licence Key error in console

### ISSUE THREAD

**Issue by babsSDM** [alvarotrigo/fullPage.js#3596]
Hi!
I just bought fullPage.js and placed the licence number as described in the documentation (licenseKey: 'xxx-xxx-xxx')., but I have this error in console:
Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here

Is maybe only because I'm working in localhost or I must do something to activate my licence?

Thanks a lot
Barbara

**Comment by alvarotrigo** [comment]
As detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) all you need to do is add the licenseKey option with the value you got:

```javascript
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
```

**Comment by alvarotrigo** [comment]
If you still getting the error, it means you are not doing it properly for some reason.

**Comment by jlgouveia** [comment]
I'm having the same issue

**Comment by alvarotrigo** [comment]
Then apply the same suggested solution:
https://github.com/alvarotrigo/fullPage.js/issues/3596#issuecomment-472030367

**Comment by jlgouveia** [comment]
your answers are fucking awesome!

**Comment by alvarotrigo** [comment]
Well, you didn't provide any information at all. So if you get the error is basically because you didn't add the licenseKey option properly :)

**Comment by hothit43** [comment]
Hello I was having the same issue. I was about to comment before I figured it out.
I am using vue fullpage and fullpage.

Just commenting here in case anyone makes the same mistake. 
It really Helps if you look at the demos.

My issue was I was initializing it more than once as was mentioned above. 
I did vue.use on fullpage and vuefullpage
`[fullpage, VueFullPage].forEach((plugin) => Vue.use(plugin))`

What worked for me was not calling fullpage and just doing VueFullPage
I still installed both ofc.
```
[VueFullPage].forEach((plugin) => Vue.use(plugin))
or Vue.use(VueFullPage).
```
VueFullPage adds the wrapper and also initializes fullpage which wasn't super clear to me at first.

Here is a link to the demo I used.
https://github.com/alvarotrigo/vue-fullpage.js/blob/master/demos/webpack/src/main.js
There are a ton more demos there which is nice :)

**Comment by alvarotrigo** [comment]
Glad you managed to find a solution @hothit43 !

**Comment by krispind** [comment]
Having same issue with licenseKey option written as specified in docs.

**Comment by alvarotrigo** [comment]
@krispind two possible options:

- Your key is incorrect
- You have typed the option `licenseKey` incorrectly or all in lower cases.
