### ISSUE TITLE
n.fn.fullpage.getFullpageData is not a function

### ISSUE THREAD

**Issue by hotlinestudio** [alvarotrigo/fullPage.js#3598]
TypeError: n.fn.fullpage.getFullpageData is not a function

I'm getting this error when using [fullpage.js Fading Effect Extension 0.0.7] & [fullPage 3.0.4 - Extensions 0.1.7] together, using Jquery to initialize:

```
$(document).ready(function() {
	$('#fullpage').fullpage({
	    licenseKey: 'KEY',
            fadingEffectKey: 'KEY',
            fadingEffect: true,
	});
});
```

I think the issue may be with extensions.js / extension.js versions, but after isolating everything I can't seem to find a solution. please advise!

Thank you

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/3588?

**Comment by hotlinestudio** [comment]
Sorry, I should have mentioned – I'm not explicitly looking to make use of .getFullpageData in any way, object or function – It is throwing this error on initialization. Maybe there's something I'm missing?

**Comment by alvarotrigo** [comment]
Are you using the latest fullpage.js version 3 ? 
What version is the extension?
