### ISSUE TITLE
TypeError with fullpage, fading effect extension, and vue

### ISSUE THREAD

**Issue by joewaine** [alvarotrigo/fullPage.js#3599]
in Vue.js with FullPage and the Fade Extension: 

nothing appears to be functioning incorrectly, but i am getting this console error when changing from one view to another in which i turn off the fade effect extension in an afterLoad() method

method and api call:
```javascript
afterLoad: function(origin, destination) {
fullpage_api.fadingEffect.turnOff();
}
```

console error:
> fullpage.fadingEffect.min.js:8 Uncaught TypeError: Cannot read property '0' of null
    at HTMLDivElement.I (fullpage.fadingEffect.min.js:8)
    at mt (vue-fullpage.js:103)
    at Object.ft.destroy (vue-fullpage.js:103)
    at s.destroy (vue-fullpage.js:206)
    at s.beforeDestroy (vue-fullpage.js:227)
    at ne (vue.runtime.esm.js:1854)
    at Dn (vue.runtime.esm.js:4190)
    at s.t.$destroy (vue.runtime.esm.js:3949)
    at destroy (vue.runtime.esm.js:3152)
    at E (vue.runtime.esm.js:6075)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll take a look at it!

**Comment by alvarotrigo** [comment]
Do you still have the same issue without Vue?
If that's the case, please [contact me](https://alvarotrigo.com/#contact) with an isolated reproduction to it. 

Use no external CSS or JS and the minimum amount of HTML code possible.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
