### ISSUE TITLE
normal content after slides

### ISSUE THREAD

**Issue by matchbranding** [alvarotrigo/fullPage.js#360]
Is there a way to have normal content after the slides?  Like a footer after the last slide.

**Comment by Huluti** [comment]
@alvarotrigo 4 years after is it possible to do what @wooama has said?

**Comment by alvarotrigo** [comment]
@Huluti nop. What was difficult to implement 4 years ago still being difficult nowadays :)

**Comment by alvarotrigo** [comment]
@Huluti but if you just want to add a footer, why not using a section with `fp-auto-height` as in [this example](https://alvarotrigo.com/fullPage/examples/autoHeight.html#3rdPage)?

**Comment by Huluti** [comment]
@alvarotrigo thank you very much for your suggestion, it's working great. That's why I wanted ;)
