### ISSUE TITLE
The content doesn't scroll

### ISSUE THREAD

**Issue by francescabassi** [alvarotrigo/fullPage.js#3603]
Hi! 

I have a strange issue that I can't resolve.
I use fullpage-react in dev mode. I'm developing a website and only a part is made with fullpage.
If I load the page with fullpage directly, all works fine. But if I came at this page by a link of the main menu, the page doesn't load properly. If I inspect the page I can see all the code, but the content doesn't scroll all, but only a part (the first and a portion of the second section, the 3rd, 4th and 5th are not reachable with scroll) 

Any ideas on why this happens? 

Thanks

**Comment by alvarotrigo** [comment]
Unfortunately it is impossible to help you without an isolated reproduction of the issue in codepen, codesandbox or stackblitz.

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by WillanTheunissen** [comment]
I was able to resolve the issue, 

I copied the site from my own implmentation of the functionality(That was buggy, hence why my purchase of the plugin) 

For future reference, the issue was generated by me hooking into my click function on menulinks: 
```
$(".menulink").on('click', function () {
        $('.active').removeClass('active');
        $(this).addClass('active');
    })
```
This removed the active tracking on the current section, and therefore anchorlinks didn't work
