### ISSUE TITLE
A video background to all the slides of a section

### ISSUE THREAD

**Issue by untecnologo** [alvarotrigo/fullPage.js#3604]
Hello, I hope all of you are very well.
I need to use a video background for all the slides in an specific section.
But when I try to use the examples code it fails. 

/* Style for our header texts
	* --------------------------------------- */
	h1{
		font-size: 5em;
		font-family: arial,helvetica;
		color: #fff;
		z-index: 4;
	}

	/* Centered texts in each section
	* --------------------------------------- */
	.section{
		text-align:center;
		overflow: hidden;
	}

	#myVideo{
		right: 0;
		bottom: 0;
		top:0;
		right:0;
		width: 100%;
		height: 100%;
		background-size: 100% 100%;
 		background-color: black; /* in case the video doesn't fit the whole page*/
  		background-image: /* our video */;
  		background-position: center center;
  		background-size: contain;
   		object-fit: cover; /*cover video background */
   		z-index:0;
	}

	/* Bottom menu
	* --------------------------------------- */
	#infoMenu li a {
		color: #fff;
	}

	/* Hiding video controls
	* See: https://css-tricks.com/custom-controls-in-html5-video-full-screen/
	* --------------------------------------- */
	video::-webkit-media-controls {
	  display:none !important;
	}

.fp-bottom{
		text-align: center !important;
	}

#fp-nav ul li a span, .fp-slidesNav ul li a span {
	background: white !important;
}

The video never start.

http://sfsp-ikk.com/presentation/hdg-plant-egypt/

This is my project link
Thanks for your support.

**Comment by alvarotrigo** [comment]
You'll probably have to use the `afterRender` callback to change the location of the absolute positioned element within your horizontal slider.
you need to append it as a child of the section and take it outside of the parent that fullPage.js uses for the horizontal slider.

Then with CSS you set its absolute position and so on.

Take a look at this jsfiddle:
https://jsfiddle.net/alvarotrigo/k7moxgqj/

I hope that helps! ;)
