### ISSUE TITLE
Height of images seems empty when lazyLoading: true and scrollOverflow: true

### ISSUE THREAD

**Issue by akikokubo** [alvarotrigo/fullPage.js#3605]
Hello, thanks for developing this plugin.
I found lazy loading doesn't work if the section is  `lazyLoading: true` and `scrollOverflow: true`.  It seems lazy loading doesn't get the height of images. I've been wondering how I solve this.

### Steps to reproduce it 
1. set `lazyLoading: true`
2. set `scrollOverflow: true`
3. change `src` attribute to `data-src` on img tags
then, images in the section don't shown on the page.

### Versions 
fullPage 3.0.4
Mac - latest Chrome/FF/Safari
Windows - latest Chrome/FF/Edge and IE11
iOS 12.1.4 Safari

Advice is much appreciated!

**Comment by alvarotrigo** [comment]
Yeah, lazyload won't be able to just guess the size of your image without loading it :)
There's literally no way to that.

You should be adding the height and width of your image on your css stylehseet or HTML markup. So, you need to know it in advance. Fullpage.js can't do that for you.

Here's an example:
https://codepen.io/alvarotrigo/pen/ZPwjaP

Where I used:

```css
.section:nth-child(2) img{
  height: 322px;
  width: 691px;
}
```

But you could have used HTML for it too.

**Comment by akikokubo** [comment]
Hello, thank you for your reply! and sorry for my wrong post on pagePiling,.js repo.

I understand lazyload won't be able to guess the size fo images. I added the height and width of the images but the `scrollOverflow: true` section isn't shown properly. 

Now I think the scrolling function of fullpage.js might be not compatible with lazyloading.
