### ISSUE TITLE
Struggling with mobile view

### ISSUE THREAD

**Issue by welbinator** [alvarotrigo/fullPage.js#3606]
Building this on desktop so far has been pretty darn easy.

But I'm having some issues with media queries.

I created one for 1024px and that's working great but for the life of me I can't get another media query to work at 680px.

I tried adding the viewport meta tag but that completely breaks my site.

is there an easier way? I'm trying to go through the documentation but I'm not finding the answer.

Any insight would be greatly appreciated.

**Comment by welbinator** [comment]
What's frustrating is fullpage is actually very responsive, but the problem is responsive is mostly meaningless because people aren't dragging their Chrome window down and resizing their browser. They're either viewing on desktop, tablet or mobile and full page looks completely different on a device with a width of say 680px (mobile) vs desktop with the browser shrunk down to 680px (responsive). So I do all this work making it "responsive" on desktop only to look at it on my phone and discover that it looks completely different.

there's clearly a hole in my knowledge about web design somewhere that hopefully I can fill sooner rather than later.

**Comment by alvarotrigo** [comment]
Sorry I do not understand what is your problem.

Media queries work in fullpage.js as they work in any other site.
And so does the viewport meta tag. 
And as far as I know there are no issues with the `responsiveWidth` or `responsiveHeight` options and neither with the `fp-auto-height-responsive` class.

**Comment by welbinator** [comment]
Thanks for your reply!

My current issues:

1. media queries don't work. //not important

2. adding the viewport meta tag breaks my site. //not important

3. new problem: I can't get scrollOverflow: true, working. I've added the overflow.js file, and I've added the scrollOverflow: true, call back. //important

I only need this for one section, and it only applies on mobile. If you look at my Services section, on desktop it's fine, but on mobile I need to be able to scroll within that section because the content gets pushed down and is much longer than the original viewport.

number 3 is my main concern right now. I've solved the mobile issue by using a simple javascript if statement that applies a class to the body tag at certain browser window widths. But I really need to figure out this scrolling within a section problem.

I'm assuming I'm just doing something wrong/not best practice.

Here's the site I'm working on: http://playground.cedarrapidswebdesign.com/fullpage1

here's a downloadable zip of all the files.

http://playground.cedarrapidswebdesign.com/fullpage.zip

I will be buying the license before I go live, assuming I can get everything working.

**Comment by alvarotrigo** [comment]
> * media queries don't work. //not important

Can you prove that? 
Please provide a link to an isolated reproduction of it in jsfiddle or codepen.

> adding the viewport meta tag breaks my site. //not important

Definitely not a fullpage.js issue :) 

> new problem: I can't get scrollOverflow: true, working. I've added the overflow.js file, and I've added the scrollOverflow: true, call back. //important

Working perfectly on the [demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html) and the [scrollOverflow example in the examples folder](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html) of this repository.

If you believe it is an issue please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
