### ISSUE TITLE
Cannot read property 'fadingEffect' of undefined

### ISSUE THREAD

**Issue by ourstudio-erikblomqvist** [alvarotrigo/fullPage.js#3607]
### Description
I've bought the Fading Effect extension, but when I'm trying to toggle the effect, the console just logs:

```
fullpage.fadingEffect.min.js:8 Uncaught TypeError: Cannot read property 'fadingEffect' of undefined
    at window.fp_fadingEffectExtension.C [as turnOn] (fullpage.fadingEffect.min.js:8)
    at Wt.afterSlideLoad (app.js:76)
    at He (fullpage.extensions.min.js:8)
    at lt (fullpage.extensions.min.js:8)
    at Object.rt [as landscapeScroll] (fullpage.extensions.min.js:8)
    at j (fullpage.dragAndMove.min.js:8)
```

### Code
```
afterSlideLoad: (section, origin, destination, direction) => {
  if (destination.item.hasAttribute('data-fade')) {
    fullpage_api.fadingEffect.turnOn();
  }
}
```

### Problem with Drag And Move
I'm also having problem with getting the timing correctly with `afterSlideLoad()` together with the extension Drag And Move. It seems to fire when I'm starting to drag the slide, rather than when the sliding effect has finished, as opposed to when not using the extension.

**Comment by alvarotrigo** [comment]
Please [contact me](https://alvarotrigo.com/#contact) with an isolated reproduction of the issue with no external CSS or JS and the minimum amount of HTML code possible.
I'll review it.
