### ISSUE TITLE
Is there a way to hide browser controls in mobile browsers?

### ISSUE THREAD

**Issue by SilencerWeb** [alvarotrigo/fullPage.js#3608]
### Description
I believe this question has been asked before because I think a lot of people have already faced such problem but unfortunately, I couldn't find the issue about it. So, the problem: mobile browsers have elements that are hiding or getting smaller once you start scrolling the page. For example, in Safari it is these elements:

![image](https://user-images.githubusercontent.com/20713191/54919897-bf184800-4f23-11e9-8ae0-64fff0906a9c.png)

But with fullpage, when you use slides animation, there is no way they will be hidden because elements are shown as slides and there is no scroll. So, is there a workaround for this issue?

P.S. Also, if you want each slides to be with the height 100vh, they are will be larger than the visible part — nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html

### Link to isolated reproduction with no external CSS / JS
Code - https://repl.it/@SilencerWeb/Fullpagejs-Bug-Demo (don't forget to hit "Run" button!)
Demo - https://fullpagejs-bug-demo--silencerweb.repl.co

### Steps to reproduce it
Just open the demo in any mobile browser

### Versions 
fullPage - v3.0.4

**Comment by alvarotrigo** [comment]
We developers don't really have control over those elements.

That being said, you can try different things:

- Use `scrollBar:true` (this will make fullpage.js act as any other site)
- Use no anchors
- Use `lockAnchors:true`
