### ISSUE TITLE
setAllowScrolling(false) disables scrolling inside modal

### ISSUE THREAD

**Issue by adrianlacheta** [alvarotrigo/fullPage.js#3611]
I'm using Bootstrap modals together with fullpage.js.

When a modal opens, I'm disabling mouse and keyboard scrolling on fullpage.js like so:
```
$.fn.fullpage.setAllowScrolling(false);
$.fn.fullpage.setKeyboardScrolling(false);
```
When a modal contains to much content, then it has to be scrolled. This works in Chrome like expected, but in Firefox and Safari the mouse scrolling inside the modal is disabled as well.

Is this a bug, or how can I disable only fullpage.js navigation, when a modal is open?

[Link to Codepen](https://codepen.io/adrianlacheta/pen/bZyOdr)

**Comment by alvarotrigo** [comment]
Just make use of the `normalScrollElements` option of fullPage.js:

```js
        normalScrollElements: '.modal-open .modal',
```
