### ISSUE TITLE
Overflow Issue

### ISSUE THREAD

**Issue by seichang00** [alvarotrigo/fullPage.js#3612]
### Description
I have been using fullpage.js and it works awesome but I realized that I was not able to scroll through a container that had the overflow scroll property enabled (mainly overflow-x). This is for my website, but I reproduced the issue on the link below. It works perfectly on desktop but doesn't work on mobile.

When I tried the mobile view of the website on the desktop browser, I realized that the touch gestures were not working but the mouse scrolling worked. Could this be due to touch gestures somehow reacting differently from the mouse scrolling on fullpage? Thank you so much!

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/seichang00/pen/MRgXVx

### Steps to reproduce it
1. if you view the codepen on desktop, scrolling works fine. 
2. On mobile, however, you can't scroll...

### Versions 
Problem on mobile views on any browser (tested on chrome, samsung internet)

**Comment by alvarotrigo** [comment]
You should use the `normalScollElements` option for that element.
Just bare in mind vertical scroll within that element won't cause the vertical scroll to another section.
