### ISSUE TITLE
Multiple Menus

### ISSUE THREAD

**Issue by englishtom** [alvarotrigo/fullPage.js#3613]
### Description
In the [change from v2.* to v3.*](https://github.com/alvarotrigo/fullPage.js/commit/27f4f8ec22435ce01e73de7ee75395b5d42e9698) there was a regression in the code. In v2.* when providing a selector for the menu options you could provide a class selector and it would target all matched elements, in v3.* it will only target the first matched element.

### Link to isolated reproduction with no external CSS / JS
[Functionality in v2.6.6](https://codepen.io/englishtom/full/OGVoMo)
[Functionality in v3.0.4](https://codepen.io/englishtom/full/pBJZMm)

### Steps to reproduce it
1. Scroll down the page in both provided examples
2. In v2.6.6 both menu's active state are updated
3. In v3.0.4 only the first menu's active state is updated

### Versions 
All browsers
All operating systems
fullpage.js v3.0.4

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll take a look at it!
