### ISSUE TITLE
website using with fullpage.js plugin, which is not smooth scrolling in desktop

### ISSUE THREAD

**Issue by nishadtu** [alvarotrigo/fullPage.js#3614]
I have used fullpage.js plugin for page scrolling, I have issue with scrolling in desktop. In desktop scrolling which has stuck in some places and there hasn't smooth scrolling. But in the case of mobile which works perfectly.

This is my jquery codes for the page

http://wefewlondon.com/wefew/wp-content/themes/egwineco/assets/js/main.js

My issued website is

http://wefewlondon.com/wefew

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by nishadtu** [comment]
> Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.
> 
> Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

Hi, The above link has the full code, and there has only issue with the home page. The each codes are mutually connected. so cant seperate codes from one to another. When you see the website, can you tell a major reason for this type of error?

**Comment by alvarotrigo** [comment]
Unfortunately I do not check non isolated issues or websites in Github issues.

If you need consulting servicies please get the Organization license from the [pricing page](https://alvarotrigo.com/fullPage/pricing/) and you'll be able to get premium assistance with your use case and website.

**Comment by nishadtu** [comment]
> Unfortunately I do not check non isolated issues or websites in Github issues.
> 
> If you need consulting servicies please get the Organization license from the [pricing page](https://alvarotrigo.com/fullPage/pricing/) and you'll be able to get premium assistance with your use case and website.

 $(function() {
        var e = $(".overflow-container, .bg, .hero-line-texture, .home-icon"),
            t = $(".hero-arrow"),
            i = $(".home-hero-main"),
            n = $(".ethos-hero-items"),
            o = $(".header-logo"),
            s = {
                scrollingSpeed: 1e3,
                scrollBar: !0,
                onLeave: function(s, r, a) {
                    var l = $(this);
                    l.removeClass("animate"), l.find(e).removeClass("animate"), $(".hero-arrow-small").addClass("hide"), "down" === a && (l.next().find(e).addClass("animate"), 1 == s && (t.addClass("animate"), i.addClass("animate"), i.find(".overflow-container, #play-button").removeClass("animate"), o.addClass("animate"), $(".hero-video").get(0).pause(), $(".hero-video").get(1).pause()), 5 == s && n.addClass("animate-in"), 6 == s && n.addClass("animate-out")), "up" === a && (l.prev().find(e).addClass("animate"), 2 == s && (t.removeClass("animate"), i.removeClass("animate"), i.find(".overflow-container, #play-button").addClass("animate"), o.removeClass("animate"), $(".hero-video").get(0).play(), $(".hero-video").get(1).play()), 6 == s && n.removeClass("animate-in"), 7 == s && n.removeClass("animate-out"))
                },
                afterLoad: function(t, n) {
                    1 == n ? ($(".hero-video").get(0).play(), $(".hero-video").get(1).play(), setTimeout(function() {
                        i.find(".overflow-container, #play-button").addClass("animate"), $(".hero-arrow-small.main").removeClass("hidden")
                    }, 1e3)) : 6 == n ? ($(this).find(e).addClass("animate"), $(".ethos-hero-items").addClass("animate-in")) : n > 6 ? $(".ethos-hero-items").addClass("animate-in animate-out") : (e.removeClass("animate"), $(this).find(e).addClass("animate")), $(this).find(".hero-arrow-small").removeClass("hide")
                }
            };
        $("#home").length && ($("#home").fullpage(s), navigator.userAgent.indexOf("FBAV") !== -1 || navigator.userAgent.indexOf("Instagram") !== -1 ? ($.fn.fullpage.setResponsive(!0), $(".hero.parallax").addClass("no-parallax"), $(".hero-arrow").addClass("hero-arrow-small main").removeClass("hero-arrow")) : $(".home-hero-main").swipe({
            swipe: function(e, t, i, n, o, s) {
                "up" === t && $.fn.fullpage.moveSectionUp()
            }
        }))
    })

I think the issue with this codes, is there any error?

**Comment by nishadtu** [comment]
` $(function() {
        var e = $(".overflow-container, .bg, .hero-line-texture, .home-icon"),
            t = $(".hero-arrow"),
            i = $(".home-hero-main"),
            n = $(".ethos-hero-items"),
            o = $(".header-logo"),
            s = {
                scrollingSpeed: 1e3,
                scrollBar: !0,
                onLeave: function(s, r, a) {
                    var l = $(this);
                    l.removeClass("animate"), l.find(e).removeClass("animate"), $(".hero-arrow-small").addClass("hide"), "down" === a && (l.next().find(e).addClass("animate"), 1 == s && (t.addClass("animate"), i.addClass("animate"), i.find(".overflow-container, #play-button").removeClass("animate"), o.addClass("animate"), $(".hero-video").get(0).pause(), $(".hero-video").get(1).pause()), 5 == s && n.addClass("animate-in"), 6 == s && n.addClass("animate-out")), "up" === a && (l.prev().find(e).addClass("animate"), 2 == s && (t.removeClass("animate"), i.removeClass("animate"), i.find(".overflow-container, #play-button").addClass("animate"), o.removeClass("animate"), $(".hero-video").get(0).play(), $(".hero-video").get(1).play()), 6 == s && n.removeClass("animate-in"), 7 == s && n.removeClass("animate-out"))
                },
                afterLoad: function(t, n) {
                    1 == n ? ($(".hero-video").get(0).play(), $(".hero-video").get(1).play(), setTimeout(function() {
                        i.find(".overflow-container, #play-button").addClass("animate"), $(".hero-arrow-small.main").removeClass("hidden")
                    }, 1e3)) : 6 == n ? ($(this).find(e).addClass("animate"), $(".ethos-hero-items").addClass("animate-in")) : n > 6 ? $(".ethos-hero-items").addClass("animate-in animate-out") : (e.removeClass("animate"), $(this).find(e).addClass("animate")), $(this).find(".hero-arrow-small").removeClass("hide")
                }
            };
        $("#home").length && ($("#home").fullpage(s), navigator.userAgent.indexOf("FBAV") !== -1 || navigator.userAgent.indexOf("Instagram") !== -1 ? ($.fn.fullpage.setResponsive(!0), $(".hero.parallax").addClass("no-parallax"), $(".hero-arrow").addClass("hero-arrow-small main").removeClass("hero-arrow")) : $(".home-hero-main").swipe({
            swipe: function(e, t, i, n, o, s) {
                "up" === t && $.fn.fullpage.moveSectionUp()
            }
        }))
    })`

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
