### ISSUE TITLE
onLeave from anchor add class

### ISSUE THREAD

**Issue by jtalbot77** [alvarotrigo/fullPage.js#3616]
Hi, I want to create a onLeave event where a class is added to a div when the section is left. To test this I have the below set up, but nothing is happening?

onLeave: function(anchor, index, direction){
	if(anchor=='secondPage' && direction == "down"){
                alert("Going to section 3!");
			}
		},

**Comment by alvarotrigo** [comment]
`onLeave` callback doesn't look like that anymore. See the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

```js
onLeave: function(origin, destination, direction){},
```

You can also check [the callbacks examples](https://codepen.io/alvarotrigo/pen/XbPNQv) from the docs to see how it works as expected.

**Comment by jtalbot77** [comment]
Is there a a way to target a specific section, I am not seeing that in the docs? I don't want it to happen to all the sections just the second one.

**Comment by alvarotrigo** [comment]
Please check the [callbacks example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/callbacks-v3.html) and read the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) code examples like this one:

```js
new fullpage('#fullpage', {
	anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'lastPage'],

	afterLoad: function(origin, destination, direction){
		var loadedSection = this;

		//using index
		if(origin.index == 2){
			alert("Section 3 ended loading");
		}

		//using anchorLink
		if(origin.anchor == 'secondSlide'){
			alert("Section 2 ended loading");
		}
	}
});
```

**Comment by jtalbot77** [comment]
Got it! It's working now. Much appreciated.
