### ISSUE TITLE
Populating Burger Menu

### ISSUE THREAD

**Issue by Theycallmeholla** [alvarotrigo/fullPage.js#3617]
### The burger menu is visible but doesn't populate any items

```html
 <li class="mobile-menu-btn">
                    <button class="toggle-menu" data-toggle="mobile-menu" data-effect="hover" style="top: -35px;padding-left: 10px;">
                      <span class="menu-label label-left">Menu</span>
                      <i class="nc-icon-outline ui-2_menu-35"></i>
                    </button>
```
### Versions 
Iphone X, Firefox 66.0.2 (64-bit) (Developer Mobile Preview)

**Comment by alvarotrigo** [comment]
If you believe this is an issue in fullpage.js please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by Theycallmeholla** [comment]
https://codepen.io/theycallmeholla/pen/vMXKoo

**Comment by alvarotrigo** [comment]
I don't see any fullpage.js code in that codepen. I expect a working reproduction with a fullpage.js initialization.

**Comment by Theycallmeholla** [comment]
Im sorry I just dont think I understand what to add and what not to add?

Is that better?  https://codepen.io/theycallmeholla/pen/vMXKoo

**Comment by alvarotrigo** [comment]
Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

I need you to reproduce your issue in codepen using fullpage.js.

**Comment by Theycallmeholla** [comment]
I read it, I just don't understand what to do.  I guess Ill just figure it out on my own.  Thanks.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
