### ISSUE TITLE
Mobile Landscape issue

### ISSUE THREAD

**Issue by DamianBusz** [alvarotrigo/fullPage.js#3618]
### Description
Standard behaviour is that fullpagepage puts autoscrolling off on mobile and that is what is Expected, however once we turn the phone into landscape autoscroling is going back on.

### Steps to reproduce it
Setup fullpage and put landscape on your phone

### Versions 
Iphone 7, 8, 10

**Comment by alvarotrigo** [comment]
> Standard behaviour is that fullpagepage puts autoscrolling off on mobile and that is what is Expected, however once we turn the phone into landscape autoscroling is going back on.

Not really.
fullPage.js doesn't do that by default. In fact, the responsive options are set to `false` by default. 

You are the one deciding under which width tor height is fullpage.js autoScrolling turned off.
