### ISSUE TITLE
if change the browser horizontal size, the screen disappears. (ONLY IE)

### ISSUE THREAD

**Issue by lucky77th** [alvarotrigo/fullPage.js#3619]
hi i use fullpage.js with vue ( vue-fullpage.js: 0.1.2 )
if change the browser horizontal size, the screen disappears. (ONLY IE)
please solve this problem.
site : http://14.63.160.137:8000/

IE11
nuxtjs 1.3.2, vue-fullpage.js 0.1.2

**Comment by alvarotrigo** [comment]
I can't reproduce this problem in neither the [vue demo page](https://alvarotrigo.com/vue-fullpage/) or the codepen provided on the vue-fullpage.js repository. 

Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

I've moved the issue into the vue-fullpage.js repository.
