### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by peterennisrda** [alvarotrigo/fullPage.js#3620]
Another one:

![Capture113](https://user-images.githubusercontent.com/1280523/55744168-25ec3580-59e9-11e9-995a-02d2ce25599d.png)
![Capture114](https://user-images.githubusercontent.com/1280523/55744175-297fbc80-59e9-11e9-80b0-55a9a037b4f6.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
Things that one forget when not touching my homepage in a while! :)

Fixed!
