### ISSUE TITLE
iPhone X, safari

### ISSUE THREAD

**Issue by DJRay57** [alvarotrigo/fullPage.js#3622]
### Description

Huge amount of padding at the top of each page. Cannot reproduce on any other device including iPhone 7/8 running same OS. Was also not able to reproduce on the fullPage.js demo site. Only on our live production site.

### Link to isolated reproduction with no external CSS / JS
https://hertfordmedia.co.uk

### Steps to reproduce it
1. Visit https://hertfordmedia.co.uk/ on an iPhone X

### Versions 
[Browser, operating system, device, ...]
Safari, iOS 12.2, iPhone X

**Comment by quadeinc** [comment]
@alvarotrigo If you visit his webpage. Inspect it and try to look on iPhoneX view there is some sort padding.

**Comment by alvarotrigo** [comment]
I do not check private websites here, I only provide premium support for people who acquired [the Organization license](https://alvarotrigo.com/fullPage/pricing/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
