### ISSUE TITLE
Sections and Slides have differing index start points in moveTo()

### ISSUE THREAD

**Issue by SulphurDioxide** [alvarotrigo/fullPage.js#3626]
The `moveTo()` method uses an integer range starting at 0 for _slide_ position but an integer range starting at 1 for the _section_ position.

The docs specifically say: 
> The first slide, the visible one by default, will have index 0

When I use `getActiveSection()` it returns an object (type Section) which has an index value starting at 0. If, for example, I call:
`var a = fullpage_api.getActiveSection()` on my _second_ section my variable `a` contains the following:
> anchor: "page2"
index: 1
isFirst: false
...

When I want to navigate to the previous section with `moveTo()`, I assumed I would do the following:
`moveTo(a.index - 1); // Move to section 0 in this specific case`

but actually, that wouldn't work because the first section is 1. I would instead have to do something which feels less intuitive like this: 
`moveTo(a.index); // using the 'current sections' index as the target for the previous section`

## Resolution: 
 - I understand I could use `moveSectionUp()` or `moveSectionDown()` but this isn't a solution if I wanted to use `silentMoveTo()` for no animation.
- Obviously, once you know that this is how it works you can manage but it seems counter intuitive to start slides at `0` and start sections at `1` _especially_ when the index returned for sections in `getActiveSection()` starts at `0` as you'd expect.

I understand that to update this could be disruptive to existing implementations but in the interim, **is it possible to update the documentation to explain** that the index for `moveTo()` is not actually the same index as is returned in the type Section?

---

### Link to isolated reproduction with no external CSS / JS
I tested this on the `moveTo()` [example codepen](https://codepen.io/alvarotrigo/pen/doqOmY).

### Steps to reproduce it
1. Scroll to the second section
2. Call `fullpage_api.getActiveSection();`
3. Using the index returned by the above method
4. Subtract one from it to get the previous index of the section.
5. Call `moveTo()` with the `index - 1` as the section location.

**Comment by alvarotrigo** [comment]
Yeap!
I totally agree! 

We have to fix that index crazyness :)
But as you said, it is a breaking change, so we'll have to wait for version 4 of fullpage.js to fix it.

So far we can add some small clarification on the english docs if you think the current comment for the `moveTo` method not enough:

```js
//Scrolling to the 3rd section in the site
fullpage_api.moveTo(3, 0);
```

Please feel free to provide a pull request in the dev branch.

**Comment by alvarotrigo** [comment]
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️
