### ISSUE TITLE
FullPageJs with static header

### ISSUE THREAD

**Issue by htruong24** [alvarotrigo/fullPage.js#3628]
Hi @alvarotrigo,

If we use paddingTop for static header like your answer here: https://jsfiddle.net/alvarotrigo/6qazLsrt/1/

It means that all content will be padding top to 110px so how could we combined it with **scrollOverflow:true**

I see that the **paddingTop** not work with **scrollOverflow** feature.

Thanks

**Comment by alvarotrigo** [comment]
It does work, just make sure to add the scrolloverflow file as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)

https://jsfiddle.net/alvarotrigo/6qazLsrt/2/
