### ISSUE TITLE
On mobile devices some of content are cropped and can't be reached

### ISSUE THREAD

**Issue by 01Kuzma** [alvarotrigo/fullPage.js#3629]
Hi!
I'm trying to implement deferent configurations to desktop and mobile devices.
Seems to work, but the problem is that on mobile device the slides are cropped and further information can't be reached. The first anchor - **intro** and last **kontaktai** are the examples in my live example.

The link is located [here](www.filmustudija.lt)

The configuration:
```

            $('#splitscreen').fullpage({
                scrollingSpeed: 800,                
                
                anchors: ['intro', 'profilis', 'portfolio', 'kontaktai'],
                navigation: false,                
                css3: true,                
                autoScrolling: true,
                fitToSection: true,
                fitToSectionDelay: 1000,
                
                easing: 'easeInOutCubic',
                easingcss3: 'ease',

                keyboardScrolling: true,
                animateAnchor: true,
                recordHistory: true
            });
```

### Versions 
FullPage 3.02

**Comment by alvarotrigo** [comment]
See the demo provided in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) regarding `fp-auto-height-reponsivie` in combination with `esponsiveWidth` or `responsiveHeight`:
https://codepen.io/alvarotrigo/pen/MzByMa
