### ISSUE TITLE
Not working on touch devices ...

### ISSUE THREAD

**Issue by TajinderSagar** [alvarotrigo/fullPage.js#3631]
### Hi, I have bought the commercial licence, also the DragAndMove plugin, have it all installed just fine, works on desktop for transition from one slide to another purposes, however is not working for touch devices, have tried on 2 browsers on my Samsung Note 4, using Chrome and Opera, also on my slate, 

Also if it helps to find what the problem may be the DragAndMove mouse drag is not working on desktop also,

[Removed URL]

I understand a separate reproduction environment, however I have bought both a commercial licence and a plugin, a quick look into why the plugin may not be working would be greatly appreciated, 

### Steps to reproduce it
Simply go to link and drag with a touch device, no response on touch swipe etc. very bad for mobile usage at the moment ...

### Versions 
2 touch phones, 1 slate and desktop also ...

**Comment by alvarotrigo** [comment]
Hi there!
Let's try to first isolate the issue.

Do you still have the issue when NOT using the Drag And Move extension?

**Comment by TajinderSagar** [comment]
Hi, thanks for the quick reply,
  

  
Yes even without the Drag and Move plugin the touch non responsive problem exists,
  

  
Tajinder
  
  
  

  
  
  
  
  
>

**Comment by alvarotrigo** [comment]
Sounds like you are doing something wrong then. 
I assume you can't reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) nor in  [the codepen](https://codepen.io/alvarotrigo/pen/NxyPPp) provided in the docs.

Try to reproduce your issue in codepen or create an isolated reproduction in your site with no external CSS or JS and the less amount of HTML code possible.

**Comment by TajinderSagar** [comment]
Hi,

 

Ok so I deactivated all plugins, did not work, 

If you can check the plugin is installed properly, 

Link: https://www.agnisage.com/testing-scroll-section/ 

 

The problem may be as am using Flatsome theme,

I did a quick copy and page code and problem is the same,

Link: https://codepen.io/anon/pen/zXjEdM 

 

So probably something to do with theme compatibility …, 

 

?

 

Tajinder

**Comment by alvarotrigo** [comment]
> I did a quick copy and page code and problem is the same,
Link: https://codepen.io/anon/pen/zXjEdM

Please isolate the issue by removing all external CSS and JS files to fullpage.js. 
Use the minimum amount of HTML code too. 
That's the only way we can be sure the issue is in fullpage.js and not in any external code.

Sounds like you are missing something.
Please check the [examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) available as well as the [codepen](https://codepen.io/alvarotrigo/pen/NxyPPp) and the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

Good luck with that!

**Comment by TajinderSagar** [comment]
That is fine, thank you for your support, 

 

Tajinder
