### ISSUE TITLE
Local website not working, only LIVE version

### ISSUE THREAD

**Issue by AmanSahota** [alvarotrigo/fullPage.js#3634]
Hi my DEV version of the website seems to have stopped working.. I am not sure why?

This is the LIVE version (everything is fine):
[removed url]

I have also setup a DEV version which has identical files:
[removed url]

However the DEV, and also on my local the site is not working. It's fine on the LIVE version?

I have noticed that the fullpage classes are missing:

`fp-enabled` `fp-viewing-firstSection`

It looks like this section is being ignored and not running:

`<script type="text/javascript">
	new fullpage('#fullpage', {
		afterSlideLoad: function(section, origin, destination, direction){
			fullpage_api.scrollOverflowReset.setPrevious(section.item);
			fullpage_api.scrollOverflowReset.reset();
		},
        anchors: ['firstSection', 'personaSection'],
		sectionsColor: ['black', 'black'],
		// Activates original scrollbar
		controlArrows: false,
		scrollOverflow: true,
		scrollOverflowReset: true,
		scrollOverflowResetKey: 'I'VE REMOVED MY KEY'
    });
</script>`

Could this be something to do with the license? We did change from HTTP to HTTPS, will this cause an issue? I have also noticed the scrollbar on the LIVE site has disappeared.

**Comment by AmanSahota** [comment]
I have also noticed the scrollbar on the LIVE site has disappeared. Would this be related?

**Comment by alvarotrigo** [comment]
I've sent you an email about it.

**Comment by AmanSahota** [comment]
Thanks, I will create a reproduction. Apologies.
