### ISSUE TITLE
Trigger animation on scroll with fullpage.js

### ISSUE THREAD

**Issue by Damiano31** [alvarotrigo/fullPage.js#3641]
Hi, I would like to add this counter to my site with fullpage.js which starts as soon as it becomes visible. Only when I add it to the site code it doesn't work. 
how can i solve?

https://codepen.io/damiano31/pen/LoNzQo

### Steps to reproduce it
1. Scroll down and the counter should start

**Comment by alvarotrigo** [comment]
In order to trigger anything you want when moving to another section or slide, make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

Also check the [callback example available](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/callbacks-v3.html).

**Comment by Damiano31** [comment]
so i need to add my function inside after load?

`afterLoad: function(anchorLink, index) {
   myfunction();
  },`

**Comment by alvarotrigo** [comment]
Yes.

**Comment by Damiano31** [comment]
this is my js
` function addToLog(callbackName, params){
        var callbackData = '<h4>' + callbackName + '</h4>';
        Object.keys(params).forEach(function(key){
            var content =  params[key];
            if(content !== null && typeof content === 'object'){
                content = JSON.stringify(content);
            }
            callbackData += '<p><b>' + key + '</b>: ' + content + '</p>';
        });
        callbackData += '<br />';
        document.getElementById('callbacksDiv').innerHTML += callbackData;
    }


new fullpage('#fullpage', {
   anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthpage'],
        navigation: true,
        navigationPosition: 'right',
        navigationTooltips: ['Consorzio Scorte Italia', 'Consorziati', 'Vantaggi','Lavora con noi'],
	    navigationColor: '#333',
	
	 afterSlideLoad: function(section, origin, destination, direction){
            var params = {
                section: section,
                origin: origin,
                destination: destination,
                direction: direction
            };
            addToLog('afterSlideLoad', params);
            console.log("--- afterSlideLoad ---");
            console.log(params);
            console.log("----------------");
		    bobi();
            deleteLog = true;
		    
        },
	
	
});

 
   function bobi() {
  $(window).scroll(function(){
  $('#counter').each(function(){
    if(isScrolledIntoView($(this))){
         $('.counter-value').each(function() {
      var $this = $(this),
        countTo = $this.attr('data-count');
      $({
        countNum: $this.text()
      }).animate({
          countNum: countTo
        },

        {

          duration: 2000,
          easing: 'swing',
          step: function() {
            $this.text(Math.floor(this.countNum));
          },
          complete: function() {
            $this.text(this.countNum);
            //alert('finished');
          }

        });
    });
    a = 1;
    }
   
  });
});

function isScrolledIntoView(elem){
    var $elem = $(elem);
    var $window = $(window);

    var docViewTop = $window.scrollTop();
    var docViewBottom = docViewTop + $window.height();

    var elemTop = $elem.offset().top;
    var elemBottom = elemTop + $elem.height();

    return ((elemBottom <= docViewBottom) && (elemTop >= docViewTop));
}

}`

the html 

` <div id="counter">
  <div class="counter-value" data-count="300">0</div>
</div>`

it still does not work

**Comment by alvarotrigo** [comment]
Just check the demos regarding how to use callbacks as I said.
They should work as expected :)
