### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scrollHeight' of undefined - scrollOverflow

### ISSUE THREAD

**Issue by amiramieng** [alvarotrigo/fullPage.js#3642]
I cannot really reproduce the issue since I am writing a wordpress theme with it.
But here is my script order:

```
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/conditionizr-4.3.0.min.js?ver=4.3.0'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/modernizr-2.7.1.min.js?ver=2.7.1'></script>
<script type='text/javascript' src='http://amirrami.test/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
<script type='text/javascript' src='http://amirrami.test/wp-includes/js/jquery/jquery-migrate.min.js?ver=1.4.1'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/bootstrap.min.js?ver=4.0.0'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/jquery.slimscroll.min.js?ver=1.3.8'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.js?ver=3.0.5'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.extensions.min.js?ver=0.1.5'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/scripts.js?ver=5.2'></script>
```

```
<div id="fullpageWrapper">
    <div class="section fp-table" id="section-1">
        <div class="fp-scrollable">
            
        </div>
    </div>

    <div class="section fp-table" id="section-2">

    </div>

    <div class="section fp-table" id="section-3">

    </div>

    <div class="section fp-table" id="section-4">

    </div>
</div>
```

**Comment by alvarotrigo** [comment]
> I cannot really reproduce the issue since I am writing a wordpress theme with it.

Of course you can :)
Try to isolate the issue from all non fullpage.js related code. 
Then create a [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
So far i can see you are importing fullpage.js twice instead of 1:

```html 
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.js?ver=3.0.5'></script>
<script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.extensions.min.js?ver=0.1.5'></script>
``` 

And if you are planning to distribute or sell your theme to others you'll need an OEM/SaaS license as detailed in the[ pricing page.](https://alvarotrigo.com/fullPage/pricing/)

**Comment by amiramieng** [comment]
> So far i can see you are importing fullpage.js twice instead of 1:
> 
> ```
> <script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.js?ver=3.0.5'></script>
> <script type='text/javascript' src='http://amirrami.test/wp-content/themes/amirrami/js/lib/fullpage.extensions.min.js?ver=0.1.5'></script>
> ```
> 
> And if you are planning to distribute or sell your theme to others you'll need an OEM/SaaS license as detailed in the[ pricing page.](https://alvarotrigo.com/fullPage/pricing/)

Was a typo I have only extensions included in my theme, and it's not for commercial purposes.

**Comment by amiramieng** [comment]
[https://codepen.io/amiramisb/pen/XwKpMG](here) is the reproduction, same error here as well.

**Comment by alvarotrigo** [comment]
Remove the internal classes added by fullpagea.js such as `fp-table` and `fp-scrollable`.

**Comment by amiramieng** [comment]
> Remove the internal classes added by fullpagea.js such as `fp-table` and `fp-scrollable`.

Works, thanks. :)
