### ISSUE TITLE
ScrollOverflow causing section change immediately when hitting bottom of section

### ISSUE THREAD

**Issue by chrismou** [alvarotrigo/fullPage.js#3644]
Am seeing an inconsistency across browsers when it comes to hitting the bottom of a section that's longer than a single page, with ScrollOverflow enabled.

On Chrome/Android, if you quickly swipe to the bottom of the section, you get that little bounce animation mobile browsers use to show you've hit the bottom. Then you have to swipe a second time to move to the next section.

On IOS however (specifically tested on an Ipad), you don't get this buffer. If you quickly swipe, as soon as the browser hits the bottom of the section, it triggers the change to the next section. The implication is that I'm getting a lot of reports of people trying to read the final line of text on the section, and it jumped down a section before they can.

The above issue I'm also seeing on Chrome dev tools responsive view. In fact, the only mobile view I've seen the former happen so far is on Chrome/Android.

I'm guessing the former is the intended behaviour, but I'm looking for some sort of confirmation of whether this is a bug, as it's being used on a relatively text heavy site, I'm concerned that the latter behaviour makes the plugin unusable in my case.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! Although, this issue has been reported before in https://github.com/alvarotrigo/fullPage.js/issues/3527. So I'll have to close it to prevent duplicates. 

Perhaps you can take a look at this [pull request](https://github.com/alvarotrigo/fullPage.js/pull/3541). 
I haven't had the time to look into that.

**Comment by chrismou** [comment]
Ah nice, my apologies, I didn't spot this ticket. I'll check it out!
