### ISSUE TITLE
fullPage.js and Webflow

### ISSUE THREAD

**Issue by retoschneller** [alvarotrigo/fullPage.js#3645]
### When fullPage.js is active the page indicator is not working.
The vertical page indicators is navigating the user on my page.

### Steps to reproduce it
1. Link block in Webflow
2. Link block settings: page section: section1
3. in current stage the link should change opacity

### Versions 
Safari 12.1 / macOS Mojave 10.14.4

**Comment by alvarotrigo** [comment]
What is a "page indicator"? Can you please provide a link where you can reproduce your issue so we can check it?
Or a picture?

**Comment by retoschneller** [comment]
https://retoschneller.webflow.io

"page indicator" is the navigation bar on the left, see the screenshot:
<img width="480" alt=" 2019-05-14 at 09 35 01" src="https://user-images.githubusercontent.com/50627312/57711248-99f2ac80-762b-11e9-80b1-c6d627bfa578.png">

**Comment by alvarotrigo** [comment]
I don't know how you made that "indicator", but that's not the navigation bullet provided by fullpage.js when using the option `navigation:true`.

If that depends on the scroll position, then you'll have to add the option `scrollBar:true` to your fullpage.js initialisation. 
Just bear in mind that will add a scroll bar.

**Comment by retoschneller** [comment]
Thanks Alvaro
Navigation bullets provided by fullpage.js works, but I wanted to create my own style of navigation.

And you were right, as I added option scrollBar:true it worked as well with Weblfow. I would like it to work without the slider. Do you have any idea?

The screenshot shows how I defined the active bullet/rectangular:

<img width="240" alt=" 2019-05-15 at 17 31 36" src="https://user-images.githubusercontent.com/50627312/57816116-57b69180-7737-11e9-8072-52ebb7ef1469.png">

**Comment by alvarotrigo** [comment]
> I would like it to work without the slider. Do you have any idea?

It won't be possible without `scrollBar:true`

**Comment by retoschneller** [comment]
Okay. Is there any way to personalize the style of the navigation in fullpage.js?

**Comment by alvarotrigo** [comment]
Sure!
Using CSS and overwriting the default styles.
Or getting the navigation elements from the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page.
