### ISSUE TITLE
Swipe event not detect in mobile

### ISSUE THREAD

**Issue by nlagdhir** [alvarotrigo/fullPage.js#3646]
First of all thank you for great plugin.

I want to detect swipe event in mobile and want to apply some logic there. I have attached small video please check that. I want to do same in mobile and for that I need to detect swipe event. 

I have also use jquery mobile for that but its not working with fullpage js. Its working in other page properly.

https://streamable.com/tm09s

**Comment by alvarotrigo** [comment]
*Hi there,*
I'm afraid I do not provide email premium support unless you acquired
the Organization
License <https://alvarotrigo.com/fullPage/pricing/>.
If you believe this is a bug in fullPage.js please create an isolated
reproduction of it in jsfiddle <https://jsfiddle.net/alvarotrigo/ea17skjr/>
or codepen with no external CSS or JS files and with the less possible code.

Then proceed to create an issue in the github issues forum
<https://github.com/alvarotrigo/fullPage.js/issues> with a link to it.



* Alvaro Trigo  alvarotrigo.com <http://alvarotrigo.com> [image: Follow me
on Twitter!] <https://twitter.com/IMAC2> Check the latest Parallax effect!
<http://alvarotrigo.com/fullPage/extensions/parallax.html>*

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
