### ISSUE TITLE
I can't try fullPage before I buy? License Key Required

### ISSUE THREAD

**Issue by LloydBennett** [alvarotrigo/fullPage.js#3648]
On the FAQs section on the pricing page it says you can try fullpage.js before you buy.

**screenshot**
<img width="739" alt="Screenshot 2019-05-16 at 23 38 37" src="https://user-images.githubusercontent.com/8522713/57891569-c8db6f00-7833-11e9-9240-680647265fc2.png">

I've downloaded the files and included it in my personal project, and I'm now getting this error.

"fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here"

Correct me if I'm wrong but a license key has to be purchased? Which means I can't try before I buy?

@alvarotrigo

**Comment by alvarotrigo** [comment]
You are getting the error as expected.
But that doesn't mean you can not try it like that.

**Comment by johhansantana** [comment]
> You are getting the error as expected.
> But that doesn't mean you can not try it like that.

then how do we test it?

**Comment by alvarotrigo** [comment]
> then how do we test it?

The error in the console won't prevent you from trying and using it.

**Comment by johhansantana** [comment]
At least when I tried it would just go into a blank screen without showing anything just that error. @LloydBennett was this the same behavior for you?

**Comment by alvarotrigo** [comment]
> At least when I tried it would just go into a blank screen without showing anything just that error. @LloydBennett was this the same behavior for you?

Definitely not a fullPage.js license issue :)
It is as easy as going to the [codepen provided in the docs](https://codepen.io/alvarotrigo/pen/NxyPPp) to see that license won't prevent you from using it.

**Comment by congy15** [comment]
@alvarotrigo I prepare buy a fullPage license, "Hobby plan for one developer" - what is for one developer mean? just 1 computer' IP address?

**Comment by alvarotrigo** [comment]
@congy15 as detailed on the pricing page:

> License per member
Commercial Licenses are priced per team member. A team member is someone on your team working on a project that uses Fullpage. This includes implementing, integrating, or changing the code.

**Comment by antyoxydant** [comment]
So I see, this so called license is a protocal for "gentle men", you can obey the license and buy one to use it in your not-open-sourced project, but still you can use is without paying anything.

**Comment by alvarotrigo** [comment]
@antyoxydant i would say it is more about legality.  If you use fullPage.js in a non GPLv3 compatible project, then you or your company can be subject to legal actions.
