### ISSUE TITLE
$(...).fullpage is not a function after destroy

### ISSUE THREAD

**Issue by danajeremy** [alvarotrigo/fullPage.js#3649]
Hello,

### Description
I'm trying to destroy and then re-instantiate fullpage.js on my website but everytime I try to do so, the fullpage method is not recognized.

Any ideas on how I can solve this?

### Sandbox
Here's the JSFiddle to test the bug.
https://jsfiddle.net/djnmqco6/1/

### Steps to reproduce it
1. Scroll to the 3rd section
2. Click on destroy
3. Then click on create
-> Look at the console, you'll see the error that pops up

### Versions 
[Browser, operating system, device, ...]
- Chrome 74.0.3729.131
- Mac OS Mojave
- jQuery 2.2.0

**Comment by alvarotrigo** [comment]
Working perfectly:
https://jsfiddle.net/alvarotrigo/fk5sd4Lz/3/

**Comment by danajeremy** [comment]
I'm sorry but it's not, the demo that you sent doesn't work. I can destroy Fullpage but when I click on "create", I still have the same error!
Tried on Chrome and Firefox, error on both browsers.

**Comment by alvarotrigo** [comment]
True :)
As your fiddle didn't even have fullpage.js in it and didn't even work, I though that was the issue.

I'll keep it open for revision.
So far, you can easily fix it by using the fullpage.js version 3 initialization:

```js
new fullpage('#fullpage', { 
    //options
});
```

**Comment by alvarotrigo** [comment]
Fixed in the dev branch 3.0.6! 
Thanks again for reporting it!

**Comment by alvarotrigo** [comment]
Merged into fullpage.js 3.0.6 which is now available! ⚡️ ⚡️
