### ISSUE TITLE
404 error for non-critical.min.css on main website 

### ISSUE THREAD

**Issue by co16353sidak** [alvarotrigo/fullPage.js#3650]
### Description

The main website for fullPage.js seems to be giving a 404 error for a minified css file.
namely `non-critical.min.css`
It could be possible that there might be a duplicate call to the file or that this file might not be getting loaded onto the website.
would love to work on this as my first issue here. 🥇 

### Screenshot 
<img width="1280" alt="Screenshot 2019-05-19 at 7 38 58 PM" src="https://user-images.githubusercontent.com/35738138/57983339-3a066680-7a6e-11e9-9425-b0253670ae37.png">

### Steps to reproduce it
1. Visit https://alvarotrigo.com/fullPage/
2. Check browser console for 404 error.

### Versions 
Not dependent.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'm not sure why, but I do not get the error in the JS console.

I'll add the map file now!
