### ISSUE TITLE
HELPPP ! fullPage.js works on test code but doesn't work on my website 

### ISSUE THREAD

**Issue by HilalHakla** [alvarotrigo/fullPage.js#3651]
The code 
![image](https://user-images.githubusercontent.com/26529048/58238893-c061c780-7d50-11e9-9669-56c8ec7fc929.png)

Full page is not initializing properly.
I tried using the test div (static divs ) it works fine even on the same page, but using the librairy with the above code fails with no errors.

        $(document).ready(function () {
            $('#fullpage').fullpage({
                licenseKey: 'XXXXXXX',
                sectionSelector: '.fullPageRow'
            });
        });

I wish you could help as i really need this feature ! please :(

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by HilalHakla** [comment]
https://jsfiddle.net/rbqL8p7g/1/

Can you please check this ?

**Comment by alvarotrigo** [comment]
Your fullpage.js id is "fullPage" and your are initializating it with all in lower cases "fullpage".
That's the issue:
https://jsfiddle.net/mecgpnfq/

**Comment by HilalHakla** [comment]
> Your fullpage.js id is "fullPage" and your are initializating it with all in lower cases "fullpage".
> That's the issue:
> https://jsfiddle.net/mecgpnfq/

Oh my God, terribly sorry for this mistake, i should not be coding right now lolz, thank you so much man ! btw i bought a license which i will remove from the fiddle lol
