### ISSUE TITLE
How to enable arrow key scrolling up/down when using scrollOverflow

### ISSUE THREAD

**Issue by akikokubo** [alvarotrigo/fullPage.js#3652]
Hello, I wrote an issue few weeks ago, and I could release a page with fullPage.js. Thank you so much! 

Today I have another issue. First of all, let me write the layout of the page.
The page has `scrollOverflow: true` setting.
It's like this,
Section1 -- full screen page
Section2 -- full screen page
Section3 -- a long section in the bottom of the page. This section scrolls.

Few days ago, my client mentioned an issue that arrow key scrolling up/down doesn't work in Section3. And I'm trying to solve it.

I read iScroll.js library is used. So I set `scrollOverflowOptions` like below.
```
		scrollOverflowOptions:{
			keyBindings: {
			    pageUp: 33,
			    pageDown: 34,
			}
		},
```
It worked. I can scroll Section3 with the down arrow key.
But, once I try to up the page with the up arrow key, the screen moves to Section2 immediately. It looks like Section 3 disappeared. 

I thought it happens because the height of Section3 isn't recognized...? I have no idea how to solve this situation.

Could you please give me some advice?
I've been wondering if it's better to write on the iScroll github page.

Thank you,

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code?. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by akikokubo** [comment]
Thank you so much for your kind reply! 
I'll prepare and show a reproduction this week.

**Comment by akikokubo** [comment]
Hello, I prepared a reproduction. I appreciate if you take a look.

### Description
A scrolling section covers a section above, when I scroll with the down/up arrow keys.
But I'd like to show the contents without covering.

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/akikokubo/pen/NVzWPV

### Steps to reproduce it
1. Go to Section3 with a down arrow key.
2. Scroll to No.4 in Section3 with keeping pressing the down arrow key. 
3. Press the up arrow key to scroll up and find No.1 in Section3. No.1 is above on Section2.

### Versions 
Chrome 74.0.3729.169 Mac
got the same result on Windows Chrome

Thank you,

**Comment by meceware** [comment]
Hi,

I don't see the CSS file at the page.
https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.css

If you add it, I don't see a problem.

**Comment by akikokubo** [comment]
Hello, thank you so much for taking a look of my issue.
I should have added the CSS file at the page. I added it.
https://codepen.io/akikokubo/pen/NVzWPV

Section3 doesn't hang over Section2, but Section3 is hidden under Section2. 
1. Go to Section3 with a down arrow key.
2. Scroll to No.4 in Section3 with keeping pressing the down arrow key.
3. Press the up arrow key to scroll up to Section2.
4. Press the down arrow key to see No.1 in Section3. But Section3 is shown like this. 
![スクリーンショット 2019-06-03 17 25 07](https://user-images.githubusercontent.com/30306516/58787939-d5c6d380-8625-11e9-8e7c-a8239166aa99.png)
No.1 in Section3 doesn't appear as if it is drawn into Section2. (I'm sorry if this expression is weird...)

**Comment by meceware** [comment]
Scroll overflow does not reset itself. That's why it doesn't go to no 1 in the section. But it's still there and there is no error here.

**Comment by akikokubo** [comment]
Thank you so much! I think I understand... that means, if there's a page with the scrolling section, and I'd like to use the scroll up/down key, the behavior is not the same as a mouse operation. Is this understanding is correct?

**Comment by alvarotrigo** [comment]
Thanks for those replies @meceware ! 👍 

> the behavior of the page is not the same as a mouse operation. Is this understanding is correct?

That's it. It is a nice observation!
I think this is something that can be improved, so I've labeled it as a possible enhancement. 

The behaviour could be:

- Add a new option "scrollOverflowKeyboard" (default false?)
- When set to true, user will be able to use the arrow keys to scroll within the scrollOverflow section.
- When reaching the top or the bottom, if there's any section above or below, it would scroll to the previous or next one. 

I usually prefer not to add many more options into fullPage.js, but I guess this is the only way to solve this issue, as I guess some prefer to keep the current behaviour?

**Comment by akikokubo** [comment]
Hello, 
I appreciate your kind support @meceware. 
And I am grateful for your thoughtful consideration @alvarotrigo .
I look forward to the future enhancement. Thanks for your great work.

**Comment by Trollhag** [comment]
Hello!

I solved this by doing this
```js
onLeave(origin, destination, direction) {
  const scroll = origin.item.querySelector('.fp-scrollable');
  if (scroll && scroll.fp_iscrollInstance.y < 0) {
    return false;
  }
}
```
Here's a fork of @akikokubo's codepen
https://codepen.io/Trollhag/pen/gOarBdZ

**Comment by learncopycode** [comment]
but did you notice @Trollhag that the menu does not work properly now. What can be a solution to this?

**Comment by Trollhag** [comment]
Oh, I didnt use a navigation for the application I used this for so I didnt notice. I'll take a look at it.

**Comment by jeydaksh** [comment]
it is working fine when using arrow key scroll
but, we are using multiple overflow sections. so this event call once, it will reflect to both.
need to fix it, please help

I tried more option but

**Comment by jeydaksh** [comment]
@Trollhag please let me know if any possible to split this action for which one active

**Comment by alvarotrigo** [comment]
Fixed on v4! 👍
