### ISSUE TITLE
Autoplay sections/sliders, vertical and horizontal together

### ISSUE THREAD

**Issue by mxkeke** [alvarotrigo/fullPage.js#3654]
Hello,
I've a fullpage installation composed by six sections; in the second I've three "Continuous Horizontal" sliders.
Now I'd like to create an autoplay but if I use this code the animation not run in the horizontal sliders; the autoplay run in the first section, go to the second but instead to continue with the second horizontal slider, jump directly to the third section.

```
<div id="fullpage">
	<div id="section1" class="section"> section 1</div>
	<div id="section2" class="section">
	   <div id="slide2-1" class="slide">slide 2.1</div>
	   <div id="slide2-2" class="slide">slide 2.2</div>
	   <div id="slide2-3" class="slide">slide 2.3</div>
	</div>
	<div id="section3" class="section"> section 3</div>
	<div id="section4" class="section"> section 4</div>
	<div id="section5" class="section"> section 5</div>
	<div id="section6" class="section"> section 6</div>
</div>
```

```
afterRender: function(){ 
    slideTimeout = setInterval(function(){ 
    fullpage_api.moveSectionDown(); 
    }, 15000); 
} 
```

How can I fix it?
Thanks.

**Comment by alvarotrigo** [comment]
Just detect when there's a horizontal slider and call `moveSlideRight()`

**Comment by mxkeke** [comment]
Is it too difficult for you write here the code to detect a "continuous horizontal slider"?
Anyway, which are the api to detect the horizontal slider and which one to "moveDown when is the last slide?
Thanks.

**Comment by alvarotrigo** [comment]
Just check for the class `.fp-slide` inside the current section.
To get the current section see the function `getActiveSection` from the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
