### ISSUE TITLE
Bug when using responsiveHeight setting

### ISSUE THREAD

**Issue by batata004** [alvarotrigo/fullPage.js#3656]
Hi,

First of all I must say this library is awesome, congrats! After years of use, today I had a problem that I cant find anyway to easily fix without too many "hacks".

Suppose you have 3 sections `div`. The first section has 1 line of text (assume the height of the line is, for example 20px). The second section has 10 lines of text (200px of content height) and the third section has 3 lines of text (60px of content height).

On small screens (with less than 200px of viewport height) the plugin gets "buggy". However it has a really nice setting `responsiveHeight` which solves any problem.

So, if I set `responsiveHeight` to 200px, the plugin works like a charm! But here is the bug: this fullpage plugin makes every section match the height of the viewport. Great! So lets assume my viewport height is 199px, this plugin will make all the 3 sections have exactly 199px of height.

This is working fine, no problem so far. The problem is that the first section will have 199px of height and only a single line of content. When the user starts to scroll down the user will see a lot of "blank" space between the first section and the second. Now when the user scrolls to the third section, he will see also a lot of blank space (less than between sections 1 and 2 cause this third section has 3 lines of content).

This "random" blank space area between sections is not beautifull nor user friendly cause it looks something is missing between sections. I think that when the user sets `responsiveHeight` the plugin SHOULD NOT make the sections match the viewport height. No, it should make the sections have the height they need and nothing else. 

Is this kind of usage possible to achieve with the current status of this plugin?

**Comment by meceware** [comment]
> This "random" blank space area between sections is not beautifull nor user friendly cause it looks something is missing between sections. 

I think it's about the design. You can always add some kind of background image or any other design that would make it user friendly.

> I think that when the user sets responsiveHeight the plugin SHOULD NOT make the sections match the viewport height. No, it should make the sections have the height they need and nothing else.

I think it's doing the exact thing that you want. When responsive height is set and the sections are set as responsive, then it doesn't match with viewport height but the height of the content.

I think another way would be using auto height for sections 1 and 3. Have you considered it?

**Comment by alvarotrigo** [comment]
> I think that when the user sets `responsiveHeight` the plugin SHOULD NOT make the sections match the viewport height. No, it should make the sections have the height they need and nothing else.

Please check the `fp-auto-height` and the `fp-auto-height-responsive` classes.
https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections

**Comment by batata004** [comment]
@meceware  and @alvarotrigo Please remove the `question` label and add `bug` to this thread. I can prove to you there is a bug.

Open this very simple jsfiddle similar to the one you gave me -> https://codepen.io/anon/pen/byzwLx

I can proof the bug happening right there. After you open that link reduce your window height/viewport to a size smaller than 300px (for example, 280px). Then scroll down to section where is written THREE. I added the class `fp-auto-height-responsive` to that section. You will see that the section three will have a height. Now decrease even further your viewport to 250px and inspect the section three. You will see its height changed!

The class `fp-auto-height-responsive` should make the section keep the height and the content's height of the section three. So how is the height of the section three changing when you change the viewport height (keeping it smaller than 300px) if the content is not changing?

The bug happens right there!

**Comment by alvarotrigo** [comment]
@batata004 sorry I still don't see any bug?

When the height is less than 300px, then responsiveHeight fires in and section 3 becomes **smaller than the viewport** adjusting itself **to the size of the content**.
See the image below:

![image](https://user-images.githubusercontent.com/1706326/58796152-c8492380-85fc-11e9-8a07-e3b66a40d62e.png)

When the height is 300px or bigger, then the section will be fullscreen.

Where's the bug ?

**Comment by alvarotrigo** [comment]
If you are speaking about the `height` inline CSS style added to the section, that's totally irrelevant. 
It gets overwritten by the `fp-auto-height-responsive` class, see the `!important` there:

 ```css
.fp-responsive .fp-auto-height-responsive.fp-section,
.fp-responsive .fp-auto-height-responsive .fp-slide,
.fp-responsive .fp-auto-height-responsive .fp-tableCell {
    height: auto !important;
}
```
