### ISSUE TITLE
data-srcset doesn't work and a question about lazysizes compatibility

### ISSUE THREAD

**Issue by mxkeke** [alvarotrigo/fullPage.js#3658]
Hello,
I'm searching to use the last version of lazysizes (5.1: https://github.com/aFarkas/lazysizes) to load the images on a fullPage.js project (with cards 3d extension), but not works.
I don't know if is a bug of lazysizes but having urgency to lunch the website I'd like to know how can I use "data-srcset" with the lazy load system integrated with fullPage (lazyLoading: true):
If I use this code it will not work, the image load immediately and not when the section where it's placed is opened.
`<img data-srcset="image.png 1x, image@2x.png 2x" class="lazyload" alt=""/>`

Is "data-srcset" supported?
Thanks.

**Comment by mxkeke** [comment]
FYI if I disable the "cards 3d extension" (cards: false) the lazysizes works good.

**Comment by alvarotrigo** [comment]
lazysizes probalby depends on the scroll event. You would then have to use `scrollBar:true`.
And scrollBar true is NOT compatible with the cards extension.

Regarding how to use fullPage.js lazy load, please read the the docs about it:
https://github.com/alvarotrigo/fullPage.js#lazy-loading

They come with a demo on codepen.

**Comment by mxkeke** [comment]
Ok, thanks but I don't see in the docs/demo the way to load the images "@2x" for the "retina display".
How can I load "image@2x" with your lazy load system?
`<img data-src="image.png" class="lazyload" alt=""/>`

**Comment by alvarotrigo** [comment]
@mxkeke can you please add an example of what you mean by that?
The image code you used is for a normal image, and that would work as expected in fullPage.js.

**Comment by mxkeke** [comment]
Now I'm using "data-srcset" (using lazysizes plugin) with two images, normal and retina display:
`<img data-srcset="image.png 1x, image@2x.png 2x" class="lazyload" alt=""/>`

If I use your lazy load system I can't use "data-srcset" (the above code not works, no image loaded), so (from your documentation) I have to use "data-src" but I don't know where to set the retina image “image@2x.png":
`<img data-src="image.png" class="lazyload" alt=""/>`

**Comment by alvarotrigo** [comment]
@mxkeke I see, so you are speaking about having something like this?

```html
<img src="/images/foo.png" alt="bar" srcset="/images/foo.png 2x" />
```

That's the HTML way of doing so, more info [here](https://brianflove.com/2014/08/07/retina-display-images/).

If that's the case, just use `data-srcset` and `data-src`. Both:

```html
<img data-src="/images/foo.png" alt="bar" data-srcset="/images/foo.png 2x" />
```
