### ISSUE TITLE
scroll only after the page is loaded

### ISSUE THREAD

**Issue by bohdan0702** [alvarotrigo/fullPage.js#3659]
### Description
I need to be able to scroll only after the section has been loaded. I scroll to section 2, the section is loaded, only after that it can scroll to section 3. How to solve, please help. I can not find anywhere

### Versions 
[Browser, operating system, device, ...]
use fullPage 2.9.4

**Comment by alvarotrigo** [comment]
You can disable scrolling by default by using the fullpage method `fullpage_api.setAllowScrolling(false)`. Then, set it to true whenever you detect your page is laoded.
