### ISSUE TITLE
Bug on mobile when opening keyboard

### ISSUE THREAD

**Issue by batata004** [alvarotrigo/fullPage.js#3660]
Hi!

I am using `responsiveHeight` and it works perfectly on mobile :) But let's see this example: the user opens a webpage on his smartphone and the height of the viewport of the smartphone's browser does not trigger `responsiveHeight` code (I mean, the viewport height is bigger than the size defined at `responsiveHeight`). Great, the scrolling is really beautifull and works fine.

BUT if inside the current `section` there is an `input`, if the user clicks on it the keyboard of the browser will appear. This will make the viewport size change and, depending on its change, it may now trigger `responsiveHeight`! So far no problem. When the user finishes typing and closes the keyboard, the page should now adapt to the new viewport size and disable `responsiveHeight`. The problem is that when it disables the `responsiveHeight` it keeps the scrolling on a "random" position. So if the users tries to fill another field in the form he will get lost cause the page scrolled to some random position and the user has to find its way back to the form and when he focus/blur another input field, the same problem wiill happen again and again!

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Would it be possible to have a video of that? Or better yet, an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/), [codepen](https://codepen.io/alvarotrigo/pen/qqabrp) or your own server, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections with a single h1 unless strictly necessary for the reproduction.

This way we will be able to test it ourselves and perhaps find a solution :)

**Comment by batata004** [comment]
Sure! I am leaving to travel right now but I recorded the bug happening! Sorry for my english on the video and the poor quality, I had to hold another smartphone while I recorded the screen of another.

https://photos.app.goo.gl/Zpfj6uPi1tj4QfsH9

I really dont know how this bug could easily be fixed, maybe saving the last section the user was when the keyboard opened and then going back/making sure the user is at the same section as previously. Still no easy fix I think.

**Comment by alvarotrigo** [comment]
@batata004 I'm looking into this issue now and I need some more info from you.

- What browser are you using?
- What fullPage.js initialisation are you using? Which options?
- Are you sure it enters into responsive mode when you open the keyboard? Can you scroll up and down when you do so so test it? I can't see it in the video either.

**Comment by alvarotrigo** [comment]
Any update please?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
