### ISSUE TITLE
Parallax only on horizontal Slides

### ISSUE THREAD

**Issue by rogerburkhard** [alvarotrigo/fullPage.js#3665]
Based on your support mail it should be possible to add the parallax effect only on horizontal slides with parallax: 'slides':

```
new fullpage('#myContainer', {
        anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage'],
        menu: '#menu',
        slidesNavigation: true,
        scrollingSpeed: 1000,
        licenseKey: 'INSERT YOUR FULLPAGE LICENSE KEY HERE',
        parallax: 'slides',
        parallaxKey: 'INSERT YOUR EXTENSION KEY HERE', //see https://goo.gl/xkUmHS
        parallaxOptions: {
            type: 'reveal',
            percentage: 62,
            property: 'translate'
       }
});
```

Here a link to your example file where I changed only the parallax: 'slides' option:
--> 

As you can see, the parallax effects is in effect for sections and slides. So the option doesn't seem to work.

When I change the value to parallax: 'sections' it works as expected.
-->

**Comment by alvarotrigo** [comment]
I've replied you by email. 
The issue has been solved in parallax version 0.1.9.

Before that, you would have had to remove the `fp-bg` element in the sections and use it only in the slides.
