### ISSUE TITLE
Modify the margin of scrolling when changing slides

### ISSUE THREAD

**Issue by dtek516** [alvarotrigo/fullPage.js#3666]
When using Fullpage.js and scrolling within a section, if I scroll to the top or bottom it immediately changes to the next/previous slide. This is causing an issue whereas, you cannot read content that may be at the very bottom/top of a section. It seems as if, there should be a delay of sorts of the mousewheel to give time to see the beginning and end of the sections content. Any advice?

I have attempted setScrollingSpeed, scrollingSpeed, paddingTop and PaddingBottom.

None applicable, as the plugin in working otherwise. This is only an issue of delaying the jump from section to section.

**Comment by alvarotrigo** [comment]
Duplicated of the following open issue: https://github.com/alvarotrigo/fullPage.js/issues/941

I'll close it to keep the conversation in a single place.
Short answer: there's no solution for it at the moment. 

But please feel free to check the following pull request who aim to solve the issue to some extend:
https://github.com/alvarotrigo/fullPage.js/pull/3541
https://github.com/alvarotrigo/fullPage.js/pull/3217
