### ISSUE TITLE
Can not Scrolling Up on version 3.0.5

### ISSUE THREAD

**Issue by 1N05A1** [alvarotrigo/fullPage.js#3667]
### First of all, thanks for your awesome plugin. 

I hope you can support me my issue.
I am using version 3.0.5, and set `keyboardScrolling: true,` for ADA.
Scrolling down is smooth, but scrolling up is blocked. I can not scrolling up with mouse or touchpad, I only can scroll up with `up arrow`.
I feel confuse if this issue because I do not use license?
(I use Chrome on Mac)

**Comment by alvarotrigo** [comment]
Hi there!

I'm not able to reproduce your issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the examples for that matter.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by 1N05A1** [comment]
Thanks for your supporting, I will create isolated reproductions in next time. Now, I can close this question because my fr resolved it. 
The reason is not version of fullpage. My fault. Sorry.
