### ISSUE TITLE
Single Section Scrolling + Horizontal Scrolling on Normal Webpage

### ISSUE THREAD

**Issue by brian-open** [alvarotrigo/fullPage.js#3668]
Hi,

I'm looking for some assistance with your plugin. We're attempting to integrate the horizontal scrolling plugin onto a standard webpage. Our client likes the functionality the horizontal scrolling brings however I'm having difficulty utilising it as I only want to use fullpage.js for one section only.

Below is a link of where we want to integrate the horizontal scrolling:

http://skelligsv2.flywheelsites.com (Our Distillery slider - Currently using Swiper.js)

Login
Username: skelligsix
Password: skelligsix

I've setup a test page here with the plugin in use however I've encountered problems using it:

https://weareopen.ie/demo/horizontal-test/

As you'll notice from the design we only want fullpage.js to function on the 'Our Distillery Slider Section'.  

I attempted to do this in the demo however the autoScrolling feature takes over the entire webpage. I've attempted workarounds adding slides before and after the horizontal sliding section however issues are still evident in content that precedes the fullpage container.

I've attempted callbacks after the horizontal section to set autoScroll to false and that works in part. If the section below this is set with an auto height it's not possible to move past the slide and onto the rest of the page.

I guess my question is whether or not it'll be possible to use fullpage.js horizontal scrolling on one section of a webpage?

Will it be possible to integrate it into the homepage of the website within its current design?

Potential site:
http://skelligsv2.flywheelsites.com

Demo Site:
https://weareopen.ie/demo/horizontal-test/

Any assistance would be greatly appreciated.

* To note we purchased the horizontal scrolling plugin June 12 2019 - rhys@weareopen.ie

Thanks,

**Comment by meceware** [comment]
The potential site asks for password. Just a heads up.

**Comment by alvarotrigo** [comment]
It is not possible to use `scrollHorizontally:true` when using `autoScrolling:false`. As described in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

> **scrollHorizontally**: (default false) Extension of fullpage.js. Defines whether to slide horizontally within sliders by using the mouse wheel or trackpad. **It can only be used when using: `autoScrolling:true`**. Ideal for story telling. Requires fullpage.js >= 3.0.1.
