### ISSUE TITLE
how to use it in pc normal,and mobile no move

### ISSUE THREAD

**Issue by 93344999** [alvarotrigo/fullPage.js#3669]
Hello, handsome guys
 i want use it in pc  but mobile stop the move work,  
just like normal wap touch
try the autoScrolling: false, the result is a  blank web

**Comment by alvarotrigo** [comment]
I can't reproduce your issue in the `autoScrolling:false` [demo page](https://alvarotrigo.com/fullPage/examples/normalScroll.html).

Could you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
