### ISSUE TITLE
Problem with Last Section

### ISSUE THREAD

**Issue by marcohanke** [alvarotrigo/fullPage.js#3670]
Hey there i've got a wired behavor and can't find the Problem. Every last Section of Fullpage breaks in Safari and IE11. Here is a Autohight-Footer alex.36pixel.de but i have the same behavor with a normal section. After scrolling i see just a white screen ???

**Comment by alvarotrigo** [comment]
I can't reproduce your issue in the [demo page](https://alvarotrigo.com/fullPage/) or any of the available examples online and offline [in the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

Could you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
