### ISSUE TITLE
Need to find the drag scroll for react

### ISSUE THREAD

**Issue by zfc9d3f** [alvarotrigo/fullPage.js#3672]
I'm trying to figure out how to add drag scroll so that it would be suitable for mobile screens
is this the extension?
https://github.com/alvarotrigo/fullPage.js/issues
i have no idea what i'm getting after paying for it, so i must ask, is this compatible with your react fullpage package?

**Comment by alvarotrigo** [comment]
Yeah fullpage.js and all its extensions are compatible with [the official React component](https://github.com/alvarotrigo/react-fullpage).

DragAndMove is the extension you need:
https://alvarotrigo.com/fullPage/extensions/drag-and-move.html
