### ISSUE TITLE
License for fadingEffect not working or failing

### ISSUE THREAD

**Issue by tsawitzki** [alvarotrigo/fullPage.js#3673]
Hello,
I have trouble getting the purchased Fade effect up and running.

- Purchased a Developer License for the plugin
- Purchased a Hobby License for the Fade Extension
- Added `licenseKey: '8F177........',` to my init function
- Added `fadingEffect: true,`  to my init function
- Added `fadingEffectKey: 'dnliZWFwcC5jb1........'` to my init function
- Referencing the `fullpage.extensions.min.js` directly through my index.php file
- Running on `localhost:8888`

From my console I am getting the following errors:

```
GET http://localhost:8888/count/3614ce net::ERR_ABORTED 404 (Not Found)
fullpage.extensions.min.js:8 GET http://localhost:8888/vybe/css/fonts/3614CE_0_0.woff2 net::ERR_ABORTED 404 (Not Found)
(anonymous) @ fullpage.extensions.min.js:8
(anonymous) @ fullpage.extensions.min.js:8
(anonymous) @ compile.js:64
localhost/:1 GET http://localhost:8888/vybe/css/fonts/3614CE_0_0.woff net::ERR_ABORTED 404 (Not Found)
```

Please let me know what I am doing wrong here, the licenses were purchased the official way and included as described per documentation.

Thanks in advance!

**Comment by alvarotrigo** [comment]
All steps are good.
It seems you are not using the right path for some of your files?

[contact me](https://alvarotrigo.com/#contact) with a URL I can check.
I'll close this issue as it is most likely an issue in your side and not in the extension or in fullPage.js for that matter.
