### ISSUE TITLE
vidéo don't working

### ISSUE THREAD

**Issue by jolebowski** [alvarotrigo/fullPage.js#3676]
hi, 

I use your plugin but i would like to make this one: https://alvarotrigo.com/fullPage/examples/videoBackground.html
but my video it' s not working.

My code this one : 
           <video src={video} type="video/mp4">
            </video>
thanks

**Comment by alvarotrigo** [comment]
Please take a look at the code of the example using videos:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/background-video.html
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/autoplay-video-and-audio.html

**Comment by jolebowski** [comment]
it s a with react js

**Comment by jolebowski** [comment]
it s working thanks
