### ISSUE TITLE
White Bar at the top of the page in Safari IOS

### ISSUE THREAD

**Issue by taiyrbegeyev** [alvarotrigo/fullPage.js#3677]
### Description

Every time I open the website for the first time, the white bar appears. So I have to reload the page to make it positioned normally.

Opened for the first time in a new tab:
![image](https://user-images.githubusercontent.com/44882080/59979139-06c27480-95e4-11e9-92c0-83bc197978ea.png)

After I refreshed the page:
![image](https://user-images.githubusercontent.com/44882080/59979195-ad0e7a00-95e4-11e9-99db-129585b178cf.png)

I am encountering this issue only on Safari. It works perfectly on Firefox and Chrome on mobile.

### Versions 
[Browser, operating system, device, ...]
Browser - Safari IOS
OS - iOS 12.3.1
Device - iPhone 7

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the available examples for that matter.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
