### ISSUE TITLE
I migrated a development site to a new host and now it says Unlicensed fullPage.js Extension

### ISSUE THREAD

**Issue by mikeymaff** [alvarotrigo/fullPage.js#3678]
I inherited this site from another developer. The plugin is currently successfully being used on pure-ip.com here: https://pure-ip.com/

We had to create a new development environment for the site (the production site url will remain the same). But on the development site, we're getting this error Unlicensed fullPage.js Extension. See here: http://dev-pure-ip.pantheonsite.io

How do I remove this warning? Do I have to register the new dev domain with that license key?

**Comment by alvarotrigo** [comment]
On the section ["Use of extensions"](https://github.com/alvarotrigo/fullPage.js#use-extensions) of the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) you'll find a link to ["How to activate a fullpage extension"](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension).

Just introduce in it the license key of your product and activate another domain. You bought the Professional license so you can now activate up to 2 more domains. (you already activated 3)

If you do not have the license key please [contact me](https://alvarotrigo.com/#contact) and I'll provide you with more details.
