### ISSUE TITLE
Chrome doesn't work, problem with jquery.fullpage.js 

### ISSUE THREAD

**Issue by Giuly92** [alvarotrigo/fullPage.js#3679]
I have a problem...
I finished fixing my new site (is a template that I bought and modified, touching only HTML and CSS, very basic things).

Once loaded, everything works correctly on Safari, unlike Chrome it breaks everything.
(www.tuvesgt.com)

<img width="875" alt="Schermata 2019-06-27 alle 18 01 53" src="https://user-images.githubusercontent.com/52291073/60281714-bdd12f80-9905-11e9-8b63-39b234e3d6ad.png">

**Comment by alvarotrigo** [comment]
Version  jquery.fullpage.js is no longer maintained.
Try updating to the latest fullPage.js version 3.

**Comment by Giuly92** [comment]
I'll try and let you know!!
For now thank you so much

**Comment by Giuly92** [comment]
I'm not sure ho I can update it.
I have to download (in case where download it??) the new file, put it in the folder and then relink it?

In the picture the folders of my .js files
<img width="444" alt="Schermata 2019-06-27 alle 20 16 37" src="https://user-images.githubusercontent.com/52291073/60290357-e6165980-9918-11e9-88db-aa5cc4667550.png">

**Comment by alvarotrigo** [comment]
Search in Google "fullpage.js" then click on download. 

Then click in "documentation". :)
