### ISSUE TITLE
TouchSensivity across devices

### ISSUE THREAD

**Issue by fietstouring** [alvarotrigo/fullPage.js#3680]
This is not a bug report but merely an effort to enhance fullpage.js 
In my experience different devices need different values for TouchSensivity. For example low values (5 to 20) are not ideal for TouchPads like in Apple Laptops. A "normal" swipe with 2 fingers makes the page **move two slides – jumping over one**, whereas low values on Touch Screens like iPads makes it more responsive and working much better than with the higher values, because you have to move the finger for a shorter distance. At the moment I tend to use higher values (like 20 or more), because the jumping over slides on Apple Laptops (or Apple Magic Mouses) is really annoying. The downside to this is, that responsiveness on touch screens is decreased.

Maybe someone here has dealt with that issue like I do and has suggestions or ideas. I myself am thinking about some kind of device and/or screen size/pixel-density detection that creates different values to be used in the initialization of fullpage.js but am in the early stages of that idea.

**Comment by alvarotrigo** [comment]
> At the moment I tend to use higher values (like 20 or more), because the jumping over slides on Apple Laptops (or Apple Magic Mouses) is really annoying.

`touchSensitivity` has cero influence on any kind of mouse / trackpad. For mouses you'll have to adapt the scrollingSpeed which which is somehow linked with the kinetic scrolling behaviour of mouse mouses and tracpads. 
The slower the movement is (the higher the scrollingSpeed value is) the less problems you'll suffer with kinetic scrolling devices.(like Apple Magic Mouses)

For mobile devices, you can use one or another `touchSensitivity` value by detecting the viewport size yourself before initialising fullpage.js. 
That, or you can opt to get a better experience yet by purchasing the [Drag And Move extension](https://alvarotrigo.com/fullPage/extensions/drag-and-move.html) that will solve those issues.

**Comment by fietstouring** [comment]
Hi, I recently purchased Drag and Move extension, because my customer wanted this behavior. Unfortunately there is a problem with a "normalScrollElement" on the page. It is a container which is layed over the page with text in it. After opening and scrolling the container, the Drag and Move behavior is completely broken. I remember that I had problems with the  "normalScrollElement" back when I was creating that page. You made an update then to fix it, that was Version 3.0.6...

**Comment by alvarotrigo** [comment]
Make sure to use the latest Drag And Move version 3.0.8. 
En email was sent to you with the last update. 

Also,  there's another issue that has been fixed on the dev branch regarding your issue.
Make sure to update to the latest fullpage.extensions.min.js version 3.0.9
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.extensions.min.js

**Comment by fietstouring** [comment]
Thanks, it works now! 
Only thing I notice is that scrolling speed is good on iOS/iPhone but very slow on Android/Chrome...?

**Comment by alvarotrigo** [comment]
Scrolling speed is not configurable on Drag And Move. It will depend on the device hardware and  performance when you leave the fingers from the screen.
