### ISSUE TITLE
Normal scrolling + fullscreen scrolling in one app

### ISSUE THREAD

**Issue by mylnikovD** [alvarotrigo/fullPage.js#3683]
So, the name of the topic speaks for itself, is it possible to have normal scroll and fullscreen section scroll on the same page, using this library? 

As far as I searched through the issues and the internet in general about this topic, there were some options like "hybrid: true" but this is not the option today, as it seems.

But maybe I'm wrong and there is actually a way?  
Sorry if this topic has already been discussed and thanks in advance for the answer!

**Comment by alvarotrigo** [comment]
You are right. There's no such option currently. Not easy to do without when hidding the scroll bar and perhaps possible to do when using `scrollBar:true`. So we'll definitely think about implementing it in a near future but so far there's no such option.

The most you can do is make use of the scrollOverflow option as[ in this example.](https://alvarotrigo.com/fullPage/examples/scrolling.html) to emulate the normal scroll in whatever section you want. For example, the last one.

I'll keep the issue closed as it is a duplicate of https://github.com/alvarotrigo/fullPage.js/issues/3205

If you want to try playing a bit by yourself, see this fiflde:
https://jsfiddle.net/enuh8t5o/
