### ISSUE TITLE
Slider question

### ISSUE THREAD

**Issue by mariusds** [alvarotrigo/fullPage.js#3686]
Hello,
I'm wondering whether it is possible to create a full screen slider with fullpage.js that meets the following guidelines: first slider is a video, second and third slider are images. 

If possible, can anyone please guide me in the right direction ? 

Thank you!

**Comment by alvarotrigo** [comment]
Sure!

Easy:

1- Create 3 sections
2- Add a video no the first one ( see [this example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/background-video.html) - [online here](https://alvarotrigo.com/fullPage/examples/videoBackground.html))
3. Add images on the other 2 sections (see [this example](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/backgrounds.html) - [online here](https://alvarotrigo.com/fullPage/examples/backgrounds.html))

**Comment by mariusds** [comment]
Hello Alvaro,
Thank you for replying. I think i wasn't very clear at the beginning. I want all three ( video and images ) to be part of the same section.. First slide would be the video, second slide ( horizontally ) would be the first image and the third slide would be the second image.

**Comment by alvarotrigo** [comment]
Change the word `section` for `slide` then :)

> Sure!
Easy:
1- Create 3 sections
2- Add a video no the first one ( see this example - online here)
3. Add images on the other 2 sections (see this example - online here)

**Comment by mariusds** [comment]
I've tried it. This is the code I have used:

``<div id="fullpage">
<div id="section0" class="section">

<video id="myVideo" loop="loop" muted="" controls="controls" data-autoplay="">
<source src="http://www.ejidvei.ro/jdv/wp-content/uploads/2019/06/4.mp4" type="video/mp4" />

</video>

<div class="layer"></div>

<div id="slide1" class="slide"></div>
<div id="slide2" class="slide"></div>

</div>



</div>``

however, i see the video loading fine, i see the right and left arrows, but when i click on the arrows nothing happens. What am I doing wrong ?

**Comment by mariusds** [comment]
```<div id="fullpage">
<div id="section0" class="section">

<video id="myVideo" loop="loop" muted="" controls="controls" data-autoplay="">
<source src="http://www.ejidvei.ro/jdv/wp-content/uploads/2019/06/4.mp4" type="video/mp4" />

</video>

<div class="layer"></div>

<div id="slide1" class="slide"></div>
<div id="slide2" class="slide"></div>

</div>



</div>```

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by mariusds** [comment]
Hello Alvaro,
If you don't mind. I have uploaded the background-video.html file ( from your examples ), and I have added the two slides, in the same section. Here is the URL: https://www.dmsoftstudio.com/example/background-video.html

**Comment by alvarotrigo** [comment]
Please read the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) regarding how to use slides. You are not doing it correctly.

See any of the examples available.

**Comment by mariusds** [comment]
Now things are moving when I click on the arrows however on the second slide i still see the video no the image defined...

**Comment by mariusds** [comment]
I have done it again, locally, using the files in your example. I simply added a new slide with the video as the slide's contents and still the only thing I can see in the slides is the video..

**Comment by alvarotrigo** [comment]
We'll be able to help you if you create a jsfiddle or codepen where we can actually see what your issue is.

**Comment by mariusds** [comment]
Hello Alvaro, thank you again for replying. In the link I posted above ( https://www.dmsoftstudio.com/example/background-video.html ) i managed to get the slides working ( the first slide is a video, the second and third slides are images ) however I can only see the video on all three slides. 

I have recreated this locally using the files in the fullpage example and i get the same problem. I don't know how to use codepen ( never used it before ) that's why I uploaded everything to the link above. If you can help me, I would greatly appreciate it as I am also going to buy the wordpress plugin of fullpage.

**Comment by alvarotrigo** [comment]
That's a matter of CSS. 
You have to set the width of the video to the same width of the slide in which it is, as it has absolute position.

You probably will get a better answer if you ask the CSS issue in stackoverflow.com where they'll be able to help you better.

**Comment by mariusds** [comment]
Hey Alvaro, I fixed the issue by simply using position:relative; instead of absolute and it works very well ( locally ).

Thank you so much for your help!

**Comment by alvarotrigo** [comment]
Glad you got it working! 👍
