### ISSUE TITLE
Wrong navigation dot activated when using continuousVertical

### ISSUE THREAD

**Issue by SamBenson** [alvarotrigo/fullPage.js#3688]
### Description
Adding continuousVertical and navigation results in the wrong navigation dot being activated when looping.

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/SamBenson/pen/XLxjBO

### Steps to reproduce it
1. Add `continuousVertical:true`
2. Add `navigation: true`
3. Scroll up from first slide or down from last

### Versions 
Latest Chrome & Mac OS Mojave

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll fix it now!

**Comment by alvarotrigo** [comment]
The issue has been fixed on the dev branch!
It will get merged in the next release 3.0.6!

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 3.0.6 which is now available!
