### ISSUE TITLE
add class slide to small screens

### ISSUE THREAD

**Issue by tkoutso** [alvarotrigo/fullPage.js#3689]
I want to add class slide only to mobile screens

I integrated to the html file a script:

<script>
$(window).on('load, resize', function mobileViewUpdate() {
    var viewportWidth = $(window).width();
    if (viewportWidth < 600) {
        $(".boxes").addClass("slide");
    }
});
</script>

It works with other classes, but doesn't work with class "slide"

**Comment by alvarotrigo** [comment]
You probably want to ask that in another place such as stackoverflow.com where they'll be able to help you better.

This issues forum is just to report issues or ask questions directly related with fullpage.js. options or features.
