### ISSUE TITLE
full page scroll disable on mobile wordpress 

### ISSUE THREAD

**Issue by abwolf1920** [alvarotrigo/fullPage.js#3694]
hello guys i want to disable full page scroll when open my website from mobile, i using wp  and elementor plugin

**Comment by alvarotrigo** [comment]
Please check the `responsiveWidth`, `responsiveHeight`, `responsiveSlides` and `fp-auto-height-repsonsive` options in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
