### ISSUE TITLE
how to highlight the active section on the navbar?

### ISSUE THREAD

**Issue by captainalbert** [alvarotrigo/fullPage.js#3695]
Is there an existing function that I can use to highlight the current section that I'm in the navigation panel? 

Like for example, I'm in the third section, I want to have something that will highlight the third section in the nav panel to show that I'm in that section.

Thanks in advance.

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by captainalbert** [comment]
Alright thankyou for your reply, i'm gonna do that and will update for any progress.
