### ISSUE TITLE
fullPage.js breaks down when changing browser scale

### ISSUE THREAD

**Issue by hacklun** [alvarotrigo/fullPage.js#3696]
Hello!
I would like to ask a question. There is a trouble. Initially, everything works correctly. However, after changing the scale when scrolling with the mouse wheel, there is a transition from the first to the last section or vice versa, depending on the direction of scrolling.

Example: https://jsfiddle.net/gaLyo8fn/

**Comment by alvarotrigo** [comment]
Your jsfiddle is not including fullPage.js at all.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by hacklun** [comment]
https://jsfiddle.net/gaLyo8fn/1/

**Comment by alvarotrigo** [comment]
What are the steps to reproduce the issue?

**Comment by hacklun** [comment]
1. Increase or reduce the browser scale
2. Return to normal scale
3. Turn the mouse wheel, jumps from first to last and vice versa

**Comment by alvarotrigo** [comment]
> * Increase or reduce the browser scale

How? On which device? 
There are so many ways to do so, on Mac, on Windows, with keyboard, with mouse, with trackpad...

**Comment by hacklun** [comment]
On desktop, on Windows with Ctrl+mouse wheel

**Comment by hacklun** [comment]
Also a similar situation happens on the Mac when using the touchpad

**Comment by alvarotrigo** [comment]
> Also a similar situation happens on the Mac when using the touchpad

Way to reproduce ?

**Comment by hacklun** [comment]
При использовании тачпада

**Comment by alvarotrigo** [comment]
> When using the touchpad

How exactly.

**Comment by hacklun** [comment]
Swipe up or down with two fingers to scroll

**Comment by imcarthi** [comment]
HI Hacklun, have you fixed  this issues ? am also getting same issues

**Comment by hacklun** [comment]
No, I haven’t fix this issues

  
>Воскресенье, 23 февраля 2020, 19:56 +03:00 от imcarthi <notifications@github.com>:
> 
>HI Hacklun, have you fixed this issues ? am also getting same issues
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Павел Ившин

**Comment by alvarotrigo** [comment]
I can't see any issue with that?
See the GIF below:
![img2](https://user-images.githubusercontent.com/1706326/75242730-ee38d880-57c8-11ea-8346-f8330f6f3498.gif)

**Comment by Sahu93** [comment]
When I do this (Ctrl+Zoom) the page keeps sliding down when I scroll down and up when I scroll up.
Unlike the gif @alvarotrigo attached. Is there a fix to this? Everything else is working perfectly.

**Comment by alvarotrigo** [comment]
@Sahu93 please provide a link where we can reproduce your issue.
Then let us know what browser and operative system are you using and what exactly you mean by "ctrl + zoom".

**Comment by Sahu93** [comment]
Hi sorry, I'm new to coding so couldn't successfully reproduce the issue but I found a fiddle in some thread which is giving me the same problem. 
I'm using Google Chrome Version 81.0.4044.92 which I believe is the latest and I'm on a Windows 10 system

Here's the fiddle:
https://jsfiddle.net/1kyuL4em/96/

By Ctrl + Zoom I mean 'Ctrl + MwheelUp' and 'Ctrl + MwheelDown' 
In the fiddle, **when I take my cursor to the bottom right section** with the implementation (Yellow background with section 1 written all over it) and try to scroll my mousewheel while holding down shift, it doesn't zoom at all it just keeps scrolling down until i reach section 2. When I reach section 2  while holding down 'ctrl' and scrolling down it starts zooming and scrolling at the same time in a very weird manner. The same thing is happening with my html.

Like in the gif above, I believe you are scrolling up or down with ctrl held which is letting you zoom in and out but it's not changing the section it stays on the section you last scrolled on to even though it looks like it's gonna scroll further it snaps back to the initial section.

In my issue and the fiddle provided above, this is not the case. It's scrolling down and zooming in and out at the same time.

**Comment by alvarotrigo** [comment]
@Sahu93 does it happen also when you apply that code outside jsfiddle?
Jsfiddle is not a good example as it uses iframes and its within another site.

Are you able to reproduce your issue on the [demo page](https://alvarotrigo.com/fullPage/) or any other [example](https://alvarotrigo.com/fullPage/#examples) for that matter? I was not able to.

Also, are you able to reproduce it without using the `scrollOverflow` option?

**Comment by Sahu93** [comment]
@alvarotrigo no I am unable to reproduce this issue on the demo page and other examples. The zooming and scrolling work just like they're supposed to (Like in the GIF).
This is only happening on my site. It's happening both with and without the `scrollOverflow` otpion.

**Comment by Sahu93** [comment]
> Attaching my files just in case :)
> [Issue #3696.zip](https://github.com/alvarotrigo/fullPage.js/files/4466236/Issue.3696.zip)

**Comment by Sahu93** [comment]
@alvarotrigo so I tried using the code from jsfiddle on dreamweaver and when I open the html I can successfully reproduce the problem.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated link to a page on your site? Use no external css or js to fullpage and empty sections of possible or using a single title.

**Comment by Sahu93** [comment]
My site's not live I just started making it. How can I provide an isolated link to it?
I provided all the files in my comment above. Will that be helpful?
I also created a pen and have successfully reproduced the issue.
https://codepen.io/sahu93/pen/zYvGvGb
I tested it in Chrome and Edge and the problem is present on both browsers.
Let me know if the link doesn't work.
And thanks a lot for your time! 👍

**Comment by Sahu93** [comment]
I provided all the files in my comment above. Will that be helpful?
I also created a pen and have successfully reproduced the issue. (Not sure if that's the isolated link you're talking about)
https://codepen.io/sahu93/pen/zYvGvGb
I tested it in Chrome and Edge and the problem is present on both browsers.
Let me know if the link doesn't work.
And thanks a lot for your time! 👍

**Comment by alvarotrigo** [comment]
> I tested it in Chrome and Edge and the problem is present on both browsers.

Have you tested that same content outside of codepen? 

I am not able to reproduce the issue on Windows 10 using Chrome 80.0.3987.132 (latest available in browserstack.com)

See the video:
![bb](https://user-images.githubusercontent.com/1706326/79250105-81fc5c00-7e7e-11ea-8140-e2e084bfce15.gif)

**Comment by Sahu93** [comment]
You are right. I just exported the pen (didn't know I could), opened it up and it works perfectly. I don't get why my site is giving me this problem. Anyway, thanks a lot for your help. I will try to figure out what's wrong with my site because the base code is almost the same as the codepen and now I'm pretty sure it's not an issue with fullpage. Btw, the javascript is amazing so thanks for that as well!! Cheers :)

**Comment by alvarotrigo** [comment]
No problem! Hopee you find a solution!

**Comment by hacklun** [comment]
Yes. Problem resolved
