### ISSUE TITLE
fp-table breaks the site layout

### ISSUE THREAD

**Issue by bernardojb** [alvarotrigo/fullPage.js#3698]
Hey Alvaro!
I'm new at html and stuff so I'll do my best to explain what is happening.
My site was made using bootstrap. It consists of 4 flex rows and each one has 2 divs with col-md-6. So each row has 2 major sections, one for an image and the other for a description. As I've added the class "section" my rows turned in to "table" braking my columns layout. 
Inspecting fullpage.js I found "var TABLE ='fp-table';". When comenting/deleting it my layout gets fixed but obviously the scroll stoped working.
I don't know what to do to avoid my layout turning into table on md+ devices but staying table on sm-..

**Comment by alvarotrigo** [comment]
Try using `verticalCentered:false`.
