### ISSUE TITLE
Drag And Move sends you back to the top of the page while dragging a section

### ISSUE THREAD

**Issue by TheTrickmaster** [alvarotrigo/fullPage.js#3699]
Basically, I've got this code with the DragAndMove extension installed:
https://jsfiddle.net/2pmcoxnk/

Everything works like a charm, but when I try to "drag and move" the slider section, the page automatically bounces back to the top (the red section basically).

I've tried disabling all the other .js on the page with no luck at all.
I'm guessing the strange behavior could be due to the nested fullpage main container?

Tried on Firefox, Chrome, Safari, Chrome iOS, Safari iOS

Thanks!

**Comment by alvarotrigo** [comment]
Nothing should be above or below fullPage.js.
It is not meant to be used that way.
