### ISSUE TITLE
Can I Hide full section in the in the mobile?

### ISSUE THREAD

**Issue by HatemHusam** [alvarotrigo/fullPage.js#3700]
Hi, I wonder if there is any possibility to hide full section in mobile device?

Assuming that I've section0, section1, section2 & scetion3. section 2 should not appear in the mobile view, instead, the user should see only the other sections.

MoveTo API is doing the job to skip the unwanted section, but it fails if I set that section to be hidden.

**Comment by alvarotrigo** [comment]
You can do the following:

- Replace the section selector for anything else
- Hide the section using `display:none`

See how it is skipping section 2 in this example:
https://jsfiddle.net/alvarotrigo/ea17skjr/53/

**Comment by HatemHusam** [comment]
Thank you @alvarotrigo , I tried your code, if I will keep #section2 display:none if the screen size is less than 991px for example (mobile view) and change the class to section-hidden it do the job, but if the user is using desktop view then section-hidden will not be manipulated?

Do I've to add the change the classautomaticly to section instead of section hidden is the user is using desktop view, before calling fullpage? is that good solution to?

**Comment by alvarotrigo** [comment]
I don't know how you are detecting that the visitors is a "mobile" device.
Usually this is done based on the resolution.

If you are planning to do the change dynamically, this is, resizing down the window should fire the "mobile" view, then you would need to destroy fullpage.js (with `destroy('all')` and initialise it again with the change in the class from "section" to "section-hidden".
