### ISSUE TITLE
Sections appearing blank with auto scroll - tip/solution

### ISSUE THREAD

**Issue by CultureInspired** [alvarotrigo/fullPage.js#3701]
This is an observation not a support ticket, I was stuck on a problem where some of my full page sections were appearing completely blank with auto scroll enabled. It was very odd because my first four sections worked fine but the 5th, 6th etc. that appeared blank had identical markup and css to previous the working sections.

Turns out I had overflow: hidden on my .wrapper class and this caused the issue. I know there have been other tickets opened for this issue in the past so I figured I'd share my solution to hopefully help the next person.

**Comment by alvarotrigo** [comment]
Thanks for the feedback!
