### ISSUE TITLE
Webflow integration help: Scrolloverflow:True - Scrollable section?

### ISSUE THREAD

**Issue by makeshop203** [alvarotrigo/fullPage.js#3702]
I want to have the first section of my page ‘flick’ with the fullpage.js then I want the second section to be scrollable. I have linked scrolloverflow.min.js which enables scrolloverflow:true but it is just not working.

Unfortunately I cannot export the code to an isolated reproduction as I am not on a webflow plan that includes code export.

Webflow share link: https://preview.webflow.com/preview/helen-jarviss-first-site?utm_medium=preview_link&utm_source=dashboard&utm_content=helen-jarviss-first-site&preview=55ca36ede056cead895a4f822ec5a92b&mode=preview

Live site: https://helen-jarviss-first-site.webflow.io/lasercutting 2

In the live site on the laser cutting page see the FAQ or file set up tab for text that goes beyond the section which cannot be scrolled to currently.

Any help would be appreciated, I'm really not good with coding.

**Comment by alvarotrigo** [comment]
Unfortunately we only provide support for isolated reproductions on the forum. 
This might be more a webflow issue than a fullPage.js one in any case.
