### ISSUE TITLE
Ability to disable scroll up/down on slides

### ISSUE THREAD

**Issue by davidlower8** [alvarotrigo/fullPage.js#3703]
Hi Alvaro,

Is there an ability to **not** scroll up/down when on slides. The default is to scroll up/down for sections and then left/right for slides. But the slides also scroll up/down and I would like to be able to disable that. In the documentation you have onSlideLeave, afterSlideLoad, onLeave. But all 3 only allow the left and right direction arguments. So I was not able to get this to work even though I tried. The only other option is the api setAllowScrolling which does take up/down arguments. However, I was not able to successfully implement this either. I am struggling to get this implemented. Your help and time is much appreciate. Thank you.

**Comment by alvarotrigo** [comment]
> The only other option is the api setAllowScrolling which does take up/down arguments. However, I was not able to successfully implement this either.

Can you share a jsfiddle or [codepen](https://codepen.io/alvarotrigo/pen/NxyPPp) link with your implementation so we can see why it is not working?

**Comment by davidlower8** [comment]
Hi Alvaro,

I appreciate you getting back to me. Rather than making a codepen, which will take some time since I can’t just copy and paste the code as it uses a lot of imports, includes and variables etc.

But if you can confirm which method does indeed stop up and down scrolling for slides. I can then go away and try to implement it again and see what I come up with. If I still fail, I’ll do a Codepen. I mostly gave up after a while because I saw the input arguments were only left and right which naturally is not what I was looking for.

Thanks for the time.

Cheers

David Lower

**Comment by alvarotrigo** [comment]
> But if you can confirm which method does indeed stop up and down scrolling for slides.

As per the [the fullpage.js documentation regarding setAllowScrolling](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions):

```js
//disabling scrolling
fullpage_api.setAllowScrolling(false);

//disabling scrolling down
fullpage_api.setAllowScrolling(false, 'down');

//disabling scrolling down and right
fullpage_api.setAllowScrolling(false, 'down, right');
```

**Comment by alvarotrigo** [comment]
> . Rather than making a codepen, which will take some time since I can’t just copy and paste the code as it uses a lot of imports, includes and variables etc.

That's not an isolated reproduction, that's a reproduction of your whole page.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by davidlower8** [comment]
Hey,

Thanks for the article on your blog about asking better questions, something I’m certain I can improve on. I just get nervous asking for help until I absolutely have to. It’s that stupid ‘not wanting to disturb’ syndrome.

Anyway I’ll try and implement again and I’ll be in touch.  Thanks for the help.

**Comment by davidlower8** [comment]
Ok I finally got around to implementing this to my website. It was successfully. Works perfectly.
Here is the code in case someone else has a similar issue as I did. Thanks @alvarotrigo. This can be marked as solved.

```
afterSlideLoad: function (section, origin, destination, direction) {
         var loadedSlide = this;

         // Disables scrolling up and down for slides
         if (section.anchor == 'logos' && destination.index == 1) {
            fullpage_api.setAllowScrolling(false, 'up, down');
         }
         if (section.anchor == 'websites' && destination.index == 1) {
            fullpage_api.setAllowScrolling(false, 'up, down');
         }
         if (section.anchor == 'branding' && destination.index == 1) {
            fullpage_api.setAllowScrolling(false, 'up, down');
         }
         // Turns scrolling back on from sections
         if (section.anchor == 'logos' && destination.index == 0) {
            fullpage_api.setAllowScrolling(true, 'up, down');
         }
         if (section.anchor == 'websites' && destination.index == 0) {
            fullpage_api.setAllowScrolling(true, 'up, down');
         }
         if (section.anchor == 'branding' && destination.index == 0) {
            fullpage_api.setAllowScrolling(true, 'up, down');
         }
      }
```

**Comment by alvarotrigo** [comment]
@davidlower8 awesome to hear you managed to get it working! ;)

**Comment by AcapSLP** [comment]
> Ok I finally got around to implementing this to my website. It was successful. Works perfectly. Here is the code in case someone else has a similar issue as I did. Thanks @alvarotrigo. This can be marked as solved.
> 
> ```
> afterSlideLoad: function (section, origin, destination, direction) {
>          var loadedSlide = this;
> 
>          // Disables scrolling up and down for slides
>          if (section.anchor == 'logos' && destination.index == 1) {
>             fullpage_api.setAllowScrolling(false, 'up, down');
>          }
>          if (section.anchor == 'websites' && destination.index == 1) {
>             fullpage_api.setAllowScrolling(false, 'up, down');
>          }
>          if (section.anchor == 'branding' && destination.index == 1) {
>             fullpage_api.setAllowScrolling(false, 'up, down');
>          }
>          // Turns scrolling back on for sections
>          if (section.anchor == 'logos' && destination.index == 0) {
>             fullpage_api.setAllowScrolling(true, 'up, down');
>          }
>          if (section.anchor == 'websites' && destination.index == 0) {
>             fullpage_api.setAllowScrolling(true, 'up, down');
>          }
>          if (section.anchor == 'branding' && destination.index == 0) {
>             fullpage_api.setAllowScrolling(true, 'up, down');
>          }
>       }
> ```

thanks this is exactly what im looking for
