### ISSUE TITLE
Using fullPage with elementor

### ISSUE THREAD

**Issue by hasintha** [alvarotrigo/fullPage.js#3705]
### Description
I'm trying to create this scrolling effect for a page built with elementor.  I've created my structure as below. 

```html
<div id="fullpage" class="elementor-section-wrap">
<section class="section">
<section class="section">
</div>
```

My configurations
============
```js
    new fullpage('#fullpage', {
        licenseKey: '**',
        autoScrolling:true
    });

    //methods
    fullpage_api.setAllowScrolling(true);
```

For some reason this fails to render properly. 

Link
====
http://bit.ly/312zfis

### Versions 
[Chrome, Win 10]

**Comment by alvarotrigo** [comment]
> ```
> <div id="fullpage" class="elementor-section-wrap">
> <section class="section">
> <section class="section">
> </div>
> ```

You are forgetting to add content to the section and close each tag?

Other than that it seems to be working fine:
https://jsfiddle.net/alvarotrigo/zxoep3c4/1/

Your problem is likely in how you are implementing it in Elementor rather than in fullPage.js itself.

**Comment by hasintha** [comment]
How am I implementing it wrong.? Your jsfiddle doesn't mean anything because you haven't implemented any elementor styles in it.

**Comment by alvarotrigo** [comment]
> How am I implementing it wrong.?

I have no idea :) I haven't seen your Elementor implementation / backend.

I've never used Elementor. But it seems to be an implementation error and not a fullpage.js one.
