### ISSUE TITLE
Get scroll distance when not using scrollBar:true

### ISSUE THREAD

**Issue by fuzion** [alvarotrigo/fullPage.js#3707]
Hello all.

Congrats to alvarotrigo for a great js module overall, i was happy to purchase the licence. 

I was wondering if there is a trick to get scrolldistance or offset top of an element, (to create some other animations) when i am -not- using scrollBar: true. if i use something like this:

    $(window).scroll(function() {
    var offset  = window.pageYOffset;
    $("#info1").html("scroll distance: " + offset);
    });

with scrollbar: true it works and i can get scroll distance. But the whole transition animations become somewhat slower and glitchy.

Is there any other workaround on this? also tried css3: false.

**Comment by fuzion** [comment]
okay seems like i found out a workaround with onleave destination function! :)

**Comment by alvarotrigo** [comment]
Glad you did! ;)
