### ISSUE TITLE
scrollOverflowOptions are not working (webpack 4)

### ISSUE THREAD

**Issue by curvedb** [alvarotrigo/fullPage.js#3709]
Hello. I am going to buy a licence soon from your site but I have a problem.
I am using latest version of fullpage.js with webpack 4.
I could't make any options work under scrollOverflowOptions except scrollbars and hideScrollbars. I can't disable mouse or touch.I need to disable dragging with mouse which acts like touch. I also tried to set setAllowScrolling() method to false and dragAndMove option to 'fingersonly'. 

```js
import 'fullpage.js/vendors/scrolloverflow';
import fullpage from 'fullpage.js';
import 'fullpage.js/dist/fullpage.css';

var fullpage = new fullpage('#slides', {
    autoScrolling: true,
    scrollHorizontally: true,
    scrollOverflow: true,
    scrollOverflowOptions: {
        scrollbars: true,
        mouseWheel: false,
        hideScrollbars: false,
        fadeScrollbars: false,
        disableMouse: true,
        interactiveScrollbars: false,
        disableTouch: true
    },
    dragAndMove: 'fingersonly',
});
```

**Comment by alvarotrigo** [comment]
This seems to be another bug in iScroll.js, the library used for scrolloverflow.
I can't seem to turn off `interactiveScrollbars` either on this demo:

https://jsfiddle.net/xtarL025/

I would try playing with other options such as:
options.disableMouse
options.disablePointer
options.disableTouch

See [the docs](https://github.com/cubiq/iscroll#optionsdisablemouseoptionsdisablepointeroptionsdisabletouch).

**Comment by curvedb** [comment]
Thank you for your help. So should I instantiate the plugin manually to pass the options then?

**Comment by alvarotrigo** [comment]
> So should I instantiate the plugin manually to pass the options then?

I'm not sure what you mean by that.

I'm suggesting you to use those options instead of `interactiveScrollbars` within the `scrollOverflowOptions` option on the fullPage.js initialization.
