### ISSUE TITLE
How to disable fp-viewing class?

### ISSUE THREAD

**Issue by baeharam** [alvarotrigo/fullPage.js#3713]
I have several sections and when I click specific section, `hide` class is added to other sections except clicked section. `hide` is for `display: none;`. It means only clicked section occupies full page and heights of other sections are gone. And when I click back button, heights of other sections are reassigned again.

I wanna implement feature like above. But, when I enter full page of specific section and scroll, `fp-viewing` is moving. Therefore, when I click back button, it goes to other section.

Is there any option to disable that feature when specific section occupies full page? You can see this kind of feature in [this site](https://www.mariodragicevic.com/). It is horizontal version and my site is vertical version.

**Comment by alvarotrigo** [comment]
> Is there any option to disable that feature when specific section occupies full page? 

You can take a look at:

- The `fp-auto-height` class. [Example here](https://alvarotrigo.com/fullPage/examples/autoHeight.html) ( see last section)
- [Offset Sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html)

> How to disable fp-viewing class? 

You can not. Why would would you need to?
If you are worried about the back button functionality then you should be looking at the option `recordHistory:false`, more info in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

**Comment by baeharam** [comment]
Thanks for your comment, but your suggestions are not proper for my problem.

1. I don't wanna auto-height feature.
2. `offsetsections` options is for partial view of next content which is not related to my problem.
3. `recordHistory` is for new paging function and `lockAnchors` option is not working for my problem too.

What I want to solve is that when I expand specific section into full page, I wanna disable changing of `fp-viewing` value. But, I still wanna scrolling function.

When I click section, forwarding animation is occurred and click back button, reversing animation is occurred. From this point of view, I can solve this problem using `destroy` option, but it occurs problem of reversing animation. Therefore, I definitely need disabling of `fp-viewing`.

**Comment by alvarotrigo** [comment]
I still do not understand why the `fp-viewing` class is relevant to you and why you want to remove it.
Can you elaborate on that abstracting as much as possible your problem? Perhaps even with an example in jsfiddle or codepen?

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by baeharam** [comment]
[Codepen Here](https://codepen.io/BaeHaram/pen/ymrwKL)

Scenario is like this.

1. Click image of one section, then it will animate and occupy full page. I implemented this effect by applying `display:none` property to another sections except clicked section.

2. When section is expanded, scroll and wait a sec!! **It will be scrolled to up automatically.** This part is my problem. When I scroll in expanded section, every section will be scrolled to `fp-viewing-joy` section. You can verify by Chrome developer tool.

How can I handle this?

**Comment by alvarotrigo** [comment]
> 2\. When section is expanded, scroll and wait a sec!! **It will be scrolled to up automatically.** This part is my problem.

Then use the option `fitToSection:false`, or, if you just want to disable it when you expand the picture, use the method `fullpage_api.setFitToSection(false)`.

**Comment by baeharam** [comment]
It prevents from auto-scrolling up, but it cannot prevent change of `fp-viewing`. When I click back button, it moves to other section, not original section.

**Comment by alvarotrigo** [comment]
What "back button" are you talking about? Your own back button or the browser's one?
If you are talking about your own:
![image](https://user-images.githubusercontent.com/1706326/62934087-06fd1600-bdc4-11e9-8734-d20d02d0343d.png)

It seems to be working fine for me. 
I click it and it closes the full screen view and returns to the active section as expected, also the fp-viewing class changes from "joy" to the active section's anchor. See the video below:

![ezgif-3-b7eeefff8bfe](https://user-images.githubusercontent.com/1706326/62935409-542eb700-bdc7-11e9-8520-d15af49a7909.gif)

**Comment by alvarotrigo** [comment]
In any case, I would add that you have to remove the class `hide` before calling `moveTo`.
And right now that's not happening. You are removing it after calling `moveTo`.

**Comment by baeharam** [comment]
Thanks for your advice, I applied your suggestions. However, when I come back to original section, it cannot be scrolled like below. I added codepen for this feature.

![image](https://user-images.githubusercontent.com/35518072/62994581-a5a67700-be97-11e9-8b91-4fcac2034855.png)

**Comment by alvarotrigo** [comment]
> Thanks for your advice, I applied your suggestions. However, when I come back to original section, it cannot be scrolled like below. I added codepen for this feature.

Can you please share the codepen with the updated changes so I can take a look at it?

Also I noticed you are loading `/js/photos.js` in addition the the JS tab code, so the code in the JS tab has no effect at all.

**Comment by alvarotrigo** [comment]
See my approach here, I would go for an `overflow:scroll` on `.fp-tableCell` for that section instead of doing `setAutoScrolling(false)`:
https://codepen.io/alvarotrigo/pen/ZEzQaxQ

It needs a couple of improvements but seems doable.

**Comment by baeharam** [comment]
I saw your approach and tested it. However, it solves only first section and occurs other bugs when I click other sections. Is it your intention? or bug?

**Comment by alvarotrigo** [comment]
> However, it solves only first section and occurs other bugs when I click other sections. Is it your intention? or bug?

Of course I won't be coding the whole site for you :)
I was just suggesting other approach that seems a bit less hacky than yours. 

Otherwise you can try your approach but removing the class `fp-section` in all sections where you apply the `hide` class. I haven't tried but seems like it could solve the issue.

Your problem when hitting the back button and the one regarding fp-viewing is that the mousewheel events still apply even when the sections are hidden. Fullpage.js only cares about the `fp-section` class and as long as they still have it fullPage.js thinks it can still scroll up or down.
So, when you get into fullscreen, fullpage acts with `autoScrolling:false` but still changes the `active` class to the next or previous sections when scrolling up or down. That's also the reason why you can't scroll up or down when closing the modal. The `active` class is not on the visible section anymore.

**Comment by baeharam** [comment]
Thanks for your sincere suggestions till now :)
I tried lots of test, but I failed and decided to change my whole layout to other design.
This discussion was totally good for newbie for JS like me! Thanks again!

**Comment by alvarotrigo** [comment]
No problem!
