### ISSUE TITLE
Issue with motion effects enabled on Elementor

### ISSUE THREAD

**Issue by tchm17** [alvarotrigo/fullPage.js#3716]
### Description

Hi, I have some issues on my website with some elements which disappear when the code is activated on Wordpress (HMTL & JS). I am using Elementor Pro and I added motion effects on some elements (titles and icons). When the code is activated, those elements are not displayed nor is the video on my homepage hero section.  Somehow Elementor isn’t playing nice with my code.  Is my code the problem?

 <img width="969" alt="Screen Shot 2019-08-14 at 2 16 06 PM" src="https://user-images.githubusercontent.com/54117387/63045393-4304a980-be9e-11e9-8edc-cdafe06d3c1d.png">
<img width="367" alt="Screen Shot 2019-08-14 at 2 16 13 PM" src="https://user-images.githubusercontent.com/54117387/63045395-4304a980-be9e-11e9-8469-27abfbc40536.png">

Thanks for you help.

**Comment by meceware** [comment]
Hi,

I don't think this is right. Please take a look at
[Including files](https://github.com/alvarotrigo/fullPage.js#including-files)

You might want to try enabling scrollbars to identify the problem behind animations as well.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by tchm17** [comment]
Thanks for your replies guys.

I am not really comfortable with this whole thing, I just added a html code to load fullpage.js and insert the js in another one. I am using Wordpress with the basic theme (Twenty Seventeen) + Elementor so except the HTML and JS I showed you, I edited nothing.

<p class="codepen" data-height="265" data-theme-id="0" data-default-tab="html,result" data-user="tchm17" data-slug-hash="jONqqVa" style="height: 265px; box-sizing: border-box; display: flex; align-items: center; justify-content: center; border: 2px solid; margin: 1em 0; padding: 1em;" data-pen-title="jONqqVa">
  <span>See the Pen <a href="https://codepen.io/tchm17/pen/jONqqVa/">
  jONqqVa</a> by tchm17 (<a href="https://codepen.io/tchm17">@tchm17</a>)
  on <a href="https://codepen.io">CodePen</a>.</span>
</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by alvarotrigo** [comment]
@tchm17 we will need an isolated reproduction of the issue in order to be able to help you here.
You can try to read online regarding how to use codepen or jsfiddle so you can provide us with the reproduction.

If you need premium support and want me to check your site you can get the Organization license from the [pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
