### ISSUE TITLE
aria-label on the link of my nav

### ISSUE THREAD

**Issue by StevenGuilpin** [alvarotrigo/fullPage.js#3717]
Hi, how to solve "links do not have a discernible name" on google devtools? because I have all 100% except accessibility (98%). I tried with the tooltips and anchor but no effect. I would like to be able to add an aria-label on the links of my nav. thank's

**Comment by alvarotrigo** [comment]
I don't seem to get that error using Wave accessibility tool:
http://wave.webaim.org/report#/http://alvarotrigo.com/fullPage/examples/navigationV.html

@charlesprescottcollins @ShayMe21 any tips on this issue regarding aria-label?

**Comment by StevenGuilpin** [comment]
try to see on my website
https://steven-guilpin.fr/

**Comment by StevenGuilpin** [comment]
I would like to find the solution to have 100% accessibility

**Comment by alvarotrigo** [comment]
I believe this got fixed in version 4 by using the "hidden text" technique, where `fp-sr-only` uses `display: none;`.

Related to this topic: https://github.com/alvarotrigo/fullPage.js/issues/2704

```html
<a href="#" class="">
    <span class="fp-sr-only">Slide%201</span>
    <span></span>
</a>
```
