### ISSUE TITLE
Fullpage.js stopped working when insert License Key into script?

### ISSUE THREAD

**Issue by gjwjr** [alvarotrigo/fullPage.js#3718]
I just purchased and added license key to script on my website and it has stopped fullpage.js working...any ideas?

jQuery(document).ready(function( $ ) {
	$('#fullpage').fullpage({
		//options here
        licenseKey: 'HIDDEN LICENSE KEY'
        scrollingSpeed: 1000,
        navigation: true,
        slidesNavigation: true
       
        
      
		
	});

**Comment by alvarotrigo** [comment]
You are missing a comma after:

```js
licenseKey: 'HIDDEN LICENSE KEY', //<--- here
```
