### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by gjwjr** [alvarotrigo/fullPage.js#3719]
Hey,

I am struggling to figure out why Fullpage wont work on mobile via elementor, below is my HTML/CSS/JS, if you can see any reason that would make it not work on mobile I would be very grateful!

```js
jQuery(document).ready(function( $ ) {
	$('#fullpage').fullpage({
		//options here
        licenseKey: 'EXAMPLE',
        scrollingSpeed: 1000,
        navigation: true,
        slidesNavigation: true
       
        
      
		
	});

	//methods
	$.fn.fullpage.setAllowScrolling(true);
});
````

```css
@media (max-width: 600px){
.full_height{
	height: 100vh;
	display: flex;
}
}
```

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.extensions.min.js"></script>
```

**Comment by alvarotrigo** [comment]
The [demo page](https://alvarotrigo.com/fullPage/) is working as expected on mobile.

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
