### ISSUE TITLE
Overflow scroll not working on mobile phone (Samsung S10)

### ISSUE THREAD

**Issue by shaselboeck** [alvarotrigo/fullPage.js#3720]
Overflow scroll is not working on mobile phone (Samsung Galaxy S10, Chrome).
You can see the bug and test it in your example:
https://alvarotrigo.com/fullPage/examples/scrolling.html

**Comment by alvarotrigo** [comment]
Thanks for the heads up!
The scrolloverflow.js file was not updated to the latest version :)

All working now! Make sure to refresh your browser a couple of times or to reload the following files a few times.
https://alvarotrigo.com/fullPage/vendors/scrolloverflow.js
