### ISSUE TITLE
Unable to scroll inside scrollable div without moving to next section

### ISSUE THREAD

**Issue by IdanGoor** [alvarotrigo/fullPage.js#3723]
In case we have a div element inside a section, and that div is scrollable, it is impossible to scroll inside it without also moving to the next section (since the whole document is listening to the wheel event).

example: https://codepen.io/idangoor/pen/JjPNQVB

**Comment by alvarotrigo** [comment]
You can make use of the `scrollOverflow` option as in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

If you just want to make a specific div scrollable you can make use of the `normalScrollElements` option as in [this example](https://codepen.io/alvarotrigo/pen/RmVazM) provided in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)

However, it is your job to detect when it reaches the bottom and what do you want to do when such thing happen. Fullpage.js wont' do that for you.

**Comment by IdanGoor** [comment]
Awesome, thanks! 'normalScrollElements' is exactly what I was looking for :)
