### ISSUE TITLE
Youtube video stopping when scrolling away but not starting again when you scroll back to it

### ISSUE THREAD

**Issue by Probablybest** [alvarotrigo/fullPage.js#3724]
I have a youtube video that auto plays by using the youtube api. When you scroll down the page the youtube video stops playing which is great. However when you scroll back up to the first section with the youtube video it doesn't start playing again.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/probablybest/o5ures1x/

### Steps to reproduce it
1. Video auto plays on first page load within first section
2. Scroll down to next section
3. Scroll back up to first/previous section with video. Video is still paused and not playing

### Versions 
Chrome, Windows 10, Desktop

**Comment by meceware** [comment]
Hi,

You should check the data-autoplay part of the documentation.

https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media

**Comment by alvarotrigo** [comment]
As @meceware, please check the data-autoplay feature.

**Comment by bztrn** [comment]
> I have a youtube video that auto plays by using the youtube api. When you scroll down the page the youtube video stops playing which is great. However when you scroll back up to the first section with the youtube video it doesn't start playing again.
> 
> ### Link to isolated reproduction with no external CSS / JS
> [Removed]
> 
> ### Steps to reproduce it
> 1. Video auto plays on first page load within first section
> 2. Scroll down to next section
> 3. Scroll back up to first/previous section with video. Video is still paused and not playing
> 
> ### Versions
> Chrome, Windows 10, Desktop

I had the same issue and discovered that it works well if scrollbar is enabled in my situation : )

**Comment by alvarotrigo** [comment]
@bztrn can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
