### ISSUE TITLE
Normal scroll element isn't scrollable when placed inside section with scrollOverflow

### ISSUE THREAD

**Issue by IdanGoor** [alvarotrigo/fullPage.js#3725]
I'm using `scrollOverflow:true` because some of my sections have long content. Moreover, I'm setting a CSS class for the normalScrollElements, such that all the scrollable divs will still be scrollable without switching to the next/prev section.
But when I try to combine the two behaviours together, it seems that we can't scroll inside the scrollable div. Instead it scrolls within the section because of the scrollOverflow.

Example: https://codepen.io/idangoor/pen/pozWEBr

Any idea how to fix this?

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Seems like a bug. To be honest I never even though someone would make use of `scrollOverflow` and `normalScrollElements` together :)

I'll mark it as a bug and see if we can fix it in future releases.

**Comment by IdanGoor** [comment]
Thanks for answering so fast! :)
Why is this happening anyway? Is it because the section listens to wheel events and then stops it from propagating to the scrollable div?
And can you estimate how long is it going to fix this issue? Or maybe there is a workaround meanwhile?

**Comment by alvarotrigo** [comment]
> Is it because the section listens to wheel events and then stops it from propagating to the scrollable div?

No idea as I haven't checked the issue yet :)
But I assume it has something to do with the external library `iscroll.js` used for the `scrollOverflow` option.

**Comment by alvarotrigo** [comment]
> And can you estimate how long is it going to fix this issue?

No less than a month for sure.

**Comment by alvarotrigo** [comment]
The issue has been fixed in the dev version 3.0.8!
It will get merged in the next release!

**Comment by alvarotrigo** [comment]
Fixed on 3.0.8!
