### ISSUE TITLE
Gap/offset at the bottom of the screen when scrolling up

### ISSUE THREAD

**Issue by mrpaule66** [alvarotrigo/fullPage.js#3726]
Hello,
I have created a website and try to install fullPage.js.
The individual "pages" of the onepager layout are assigned the browser height via a script so that they always fill the browser window in height.
The scrolling down works perfectly. Only when scrolling up I get on every "page" below an offset (gap) of 50px. This can be seen in the pictures, which have 100% display height.
I tried paddingTop and paddingBottom in fullpage.js and jquery.fullpage.min.js, but that does not work.
Is there a solution to "move" the anchor point when scrolling up to 50px?
Thank you in advance!

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on the [demo page](https://alvarotrigo.com/fullPage/) or any of the other examples. 

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by mrpaule66** [comment]
Hi alvarotrigo,

I may give you an url: https://www.adensam.de/test/index-2-B.php

If you scroll-down, you will see that the images have "full-height" of the browser height.
But when you scroll-up, there is a white space below the pictures. 
The scrolling up would have to scroll down about 50px, so that the picture at the bottom closes again.
At first I thought, after reading the documentation, that you can use paddingBottom or paddingTop to set such an offset.

**Comment by alvarotrigo** [comment]
Unfortunately we do not check sites here. Just reproductions in jsfiddle or codepen.
If you need premium support consider purchasing the [Organization license](https://alvarotrigo.com/fullPage/pricing/).

**Comment by mrpaule66** [comment]
Hello,
Of course I do not expect that the website will be checked here. I just wanted to know if this "problem" can be fixed and if paddingBottom / paddingTop is provided for it ... and if so maybe a tip, why paddingBottom / paddingTop does not work.
Other question: Could the premium support solve the problem?
Thank you in advance.

**Comment by alvarotrigo** [comment]
> Other question: Could the premium support solve the problem?

When acquiring the premium support we will take a look at your site and investigate the problem.
Otherwise, you'll need to provide an isolated reproduction of the issue in jsfiddle or codepen so we can be sure the issue is in fullPage.js and not in any external code to it.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
