### ISSUE TITLE
Images shaking on fixed backgrounds

### ISSUE THREAD

**Issue by komidesign** [alvarotrigo/fullPage.js#3727]
On the fixed background mode, the images are shaking a bit when scrolling to the next section. I know is not a big issue but is there any fix for this? Thanks.

https://alvarotrigo.com/fullPage/examples/fixedBackgrounds.html

**Comment by alvarotrigo** [comment]
Sounds like a browser's problem. 
What browser are you using? It works well for me in:

- Chrome for Mac
- Firefox for Mac
- Safari for Mac
- Chrome for iOS
- Safari for iOS
- Firefox for iOS

**Comment by komidesign** [comment]
I'm using chrome for windows Version 76.0 (latest for now), so it's probably a chrome windows bug  only. On mozilla windows no issue. Thanks.
