### ISSUE TITLE
Navigate to child slides

### ISSUE THREAD

**Issue by danishadeel** [alvarotrigo/fullPage.js#3728]
### How to create custom navigation for child slides
I know there is a way to create custom navigation for the slides, but is there a was to cutomize the dots of child horizontal slides ?

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/pohtani/pen/OXMwKb

### Versions 
3.0.7

**Comment by alvarotrigo** [comment]
I don't see why not :)
Just overwrite the CSS styles defined in fullpage.css.
