### ISSUE TITLE
Is it possible to use a sticky/affix navbar on pages that allow scrolling?

### ISSUE THREAD

**Issue by vladartym** [alvarotrigo/fullPage.js#3729]

**Comment by alvarotrigo** [comment]
Yes it is possible as long as you use `scrollBar:true`.

**Comment by vladartym** [comment]
Hey Alvaro, but it looks like when I turn on that function all it does is add an additional scrollbar (2 scrollbars). It allows for scrolling within my second section but I can't scroll back to the first section.
