### ISSUE TITLE
Scroll Overflow Reset with normal scrolling don't scroll to section top

### ISSUE THREAD

**Issue by dbruening** [alvarotrigo/fullPage.js#3730]
Hello,

I have a problem with the paid ScrollOverflow Reset Extension and the responsive behavior.

Here is the isolated codepen:
https://codepen.io/reteid/pen/ZEzvxMZ

On my website, I deactivate the full-page scorling on touch devices with an orientation portrait and let the website scroll normally. I set this by 'fullpage_api.setResponsive (true)'. In addition, the over-length sections are responsive by: '.fp-auto-height-responsive'.

If a visitor scrolls normally down and goes up to a section with auto-height by the menu, he doesn't scroll up to the top corne of the section, always.

The behavior can not be reproduced always. It seemed so, that it would make a difference if I scroll down by the menu and then up again. Or if I scoll normally (by mouse, touch) down and then back up via the menu. - Sometimes it works correcty, sometimes not.

### Steps to reproduce it
1. Scoll down to "section 4" (by touch, mouse or with the menu point)
2. Click on menu point "section 3"
-> Are you on the top of the section 3?

### Versions 
Test so far on Windows 10, Firefox and Chrome

I'm happy about help.

**Comment by alvarotrigo** [comment]
On the codepen you are using the "limited" version of the javascript file for scrollOverflowReset.
That won't work :)

As detailed in the f[fullPage.js extensions FAQs](https://alvarotrigo.com/fullPage/extensions/faqs.html) you'll first need to purchase the extension in order to get the proper file and be able to try it.

**Comment by dbruening** [comment]
Thanks you for your response!

We have already bought the extension. I've changed the js include to use the not limited extension file. (The file is uploaded to a test server because the customer website is not available.) Should the codepen work correctly now? Or do I have to change more?

**Comment by alvarotrigo** [comment]
I am not sure why are you making use of `fullpage_api.setResponsive(true);`, but scrollOverflow won't work on responsive mode or when using `autoScrolling:true` or `scrollBar:true`.
If you remove that line, it will work as expected. 

Just read the docs regarding how to use extension and [how to generate an activation key for them](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension).

If you want deal with scrollOverflow on responsive you'd better apply this in this case:

> You can also prevent scrolloverflow from getting applied on responsive mode when using `fp-auto-height-responsive` in the section element.


This way your section will become bigger than the viewport when required in responsive mode.

**Comment by alvarotrigo** [comment]
Also, can you please remove the extension file from your codepen when you are done?
Better not to make the file public :)
