### ISSUE TITLE
Content is cropped and not fully visible on tablets (Ipad, Ipad Pro)

### ISSUE THREAD

**Issue by nikolapa** [alvarotrigo/fullPage.js#3732]
### Description
Hey Awesome Fullpage.js support. I implemented fullpage.js plugin to this website https://digitalleadership.webflow.io/ and I love how it works. The only problem occurs on tablets because the content is often cropped and not fully visible. When I check it from inspect element everything looks fine though. 

I understand that this could happen when there is too much content in some section, but this happens even when it isn't.

Any advise would be helpful! 

Thanks in advance

**Comment by alvarotrigo** [comment]
fullPage.js provides different options to deal with those cases.

- You can use the `scrollOverfow` option. [See example](https://alvarotrigo.com/fullPage/examples/scrolling.html).
- You can use the `fp-auto-height` class  combined with `responsiveWidth` or `responsiveHeight`. [See example](https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html)
