### ISSUE TITLE
Way to show footer outside fullpage section?

### ISSUE THREAD

**Issue by ninmorfeo** [alvarotrigo/fullPage.js#3734]
HI,
Is there a way to make items visible outside the fullpage container?
Specifically I have a site in wordpress that has the footer in position relative to the bottom of the page according to this structure:
```
<div id="fullpage">
            <div id='sec1' class="section" ></div>
            <div id='sec2' class="section" ></div>
</div>
<footer> .... </footer>
```
this is js code:
```
   $('#fullpage').fullpage({
        scrollHorizontally: false,
        continuousVertical: false,
        autoScrolling: true,
        scrollBar: true
});
```
When I reach the last slide the mouse does not shake until the footer ...
I tried to add a third slide with a transparent background but I can't see below.
is there some trick?

**Comment by alvarotrigo** [comment]
Unfortunately that's not an option.
fullpage.js expects all content of the page to be within its wrapper.

However, you can try moving the footer inside fullpage.js wrapper and use it as an auto-height last section. 

See a great example of a footer within fullPage.js here:
https://alvarotrigo.com/fullPage/examples/autoHeight.html

If somehow you can not edit the HTML, you can always move it inside fullPage.js wrapper by using javascript too :)

**Comment by ninmorfeo** [comment]
ok, so I provide javascript with thanks :)

**Comment by Oteo95** [comment]
@alvarotrigo I am using auto-height but for some reason if I change the view and go back to the full page all the components are misaligned in the section.

<img width="1861" alt="image" src="https://github.com/alvarotrigo/fullPage.js/assets/38784598/9830ddc7-3318-4993-84ca-6226e0117653">

vs

<img width="1837" alt="image" src="https://github.com/alvarotrigo/fullPage.js/assets/38784598/de5e665a-09a6-41af-9c9b-6a7038f66d2a">


I can not find the source of this behaviour.

**Comment by alvarotrigo** [comment]
@Oteo95 can you open a new issue with an isolated reproduction on codepen or jsfiddle?
Thanks!
