### ISSUE TITLE
On autoscroll sections, avoid jumping back through previous sections

### ISSUE THREAD

**Issue by komidesign** [alvarotrigo/fullPage.js#3735]
Hi. When using the auto scroll feature ( to auto scroll from one section to another ) when is reaching the last section and loops back to the first one , all other sections are visible for a short period of time, is like a fast scroll through all other sections for reaching the first one.
Any way we can avoid that so it could jump back directly to the first one after the last section?

```
$('#slider-home').fullpage({
  verticalCentered: false,
  navigation: true,
  css3:false,  
  loopBottom: true,
  afterRender: function(){
    setInterval(function(){
            $.fn.fullpage.moveSectionDown();
    }, 2500);
  }
});
```

**Comment by alvarotrigo** [comment]
> Any way we can avoid that so it could jump back directly to the first one after the last section?

Sure!
Just make sure to use the `continuousVertical` option.

**Comment by komidesign** [comment]
It works but only without ( or add false ) the `loopBottom: true` . So in my case that was the issue.
Thanks a lot.

**Comment by alvarotrigo** [comment]
Yeah, you'll get a warning error in the console talking about the incompatibility of those options.
