### ISSUE TITLE
CSS easing not working when scrollBar is true

### ISSUE THREAD

**Issue by kacho** [alvarotrigo/fullPage.js#3736]
### Link to isolated reproduction with no external CSS / JS
[JSFiddle](https://jsfiddle.net/designolog/2a85p4e7/)

### Steps to reproduce it
Check the setup above. Make scrollBar: false to check how the animation is expected to work. But it's not working when scrollBar is true. The documentation does not mention scrollBar: false and easingcss3 as incompatible so I assume this is a bug. 

### Versions 
Latest version and all browsers.

P.S. Am I supposed to publish a fiddle with my license key inside? I purchased it yesterday but don't feel comfortable with the idea of displaying it publicly in the fiddle. I'll update it if it's required for support requests.

**Comment by alvarotrigo** [comment]
The animation taking place when using `scrollBar:true`  is not fired by CSS 3 but by Javascript instead.
There's no way to fire a real page scroll (with scrollbar) using CSS.

Therefore, the use of `css3:true` there won't have any effect. It is exactly the same as using `css3:false` and therefore the easing you have to use will have to be placed under the `easing` option and not the `easingcss3` one.

Demo here:
https://jsfiddle.net/oavL2j65/

Notice I also imported the file `vendors/easings.js`

**Comment by alvarotrigo** [comment]
> P.S. Am I supposed to publish a fiddle with my license key inside? I purchased it yesterday but don't feel comfortable with the idea of displaying it publicly in the fiddle. I'll update it if it's required for support requests.

The key is not required for  the fiddle :)
No worries! 😉

**Comment by kacho** [comment]
Thank you very much for the detailed explanation and the demo. Makes perfect sense now.
