### ISSUE TITLE
Can't add section, fullpage stop to work. (Semplice wordpress theme)

### ISSUE THREAD

**Issue by s3nia** [alvarotrigo/fullPage.js#3737]
### Hi, I'm a graphic designer, i'm dead in the water and I don't know how to get out of it :(.
I set up a fullpage page and all was ok, it has four sections as in the code i find on the web. I'm using wordpress with Semplice theme. When I try to add more sections, fullpage.js seems not to work. I can see progress in the navbar (#1, #2, ...) but browser window is always white.
I don't know if is a compatibility issue with Semplice theme 'cause in the codepen below all seems to be ok. Can anyone please help me? Many thanks.

This is my site https://www.spazio.studio/homepage?preview_id=683&preview=true

**Comment by alvarotrigo** [comment]
Unfortunately we don't provide support for wordpress themes we don't offer.
We can only provide you with support for fullpage.js itself, but it seems it works as expected on the codepen you provide.

The most we can do is recommend you to make use of our [fullPage.js Wordpress plugin for Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/).
