### ISSUE TITLE
Unable to use the free version in valet and/or laravel locally

### ISSUE THREAD

**Issue by MarcianoStikkelorum** [alvarotrigo/fullPage.js#3738]
Hii, as a laravel developer trying new things, I've noticed that I'm unable to use the package in a laravel based project. Whether I'm using `php artisan serve` (turns into 127.0.0.1:port) or a `valet` linked project (ngix for Laravel), they both throw an error to me about the license key. They're still on localhost but unable to parse the actual host I guess.

### Steps to reproduce it
1. create a new laravel project
2. add the plugin through NPM
3. import it into your app.js (resources/js/app.js) as;
```global.$ = global.jQuery = require('jquery');
fullpage = require('fullpage.js');
require('./bootstrap');

$(document).ready(function () {
    var fullPageInstance = new fullpage('#fullpage', {
        navigation: true,
        sectionsColor:['#ff5f45', '#0798ec', '#fc6c7c', 'grey']
    });
});
```

4. link your project using `Valet link <name>`
5. compile your assets (`npm run dev`) (webpack/laravel-mix)
6. edit the welcome.blade.php (resources/views/welcome.blade.php) to the example on the wiki
7. turn on your console and see the magic happen

### Versions 
- laravel 6.0
- webpack (laravel-mix 4.0.7)
- sass 1.15.2
- fullPage 3.0.7 (fresh install)
- jquery 3.4.1
- Laravel Valet 2.1.5

**Comment by alvarotrigo** [comment]
Can you please specify what are the errors you are having?

**Comment by alvarotrigo** [comment]
> they both throw an error to me about the license key.

That means you need to purchase a license from [the website](https://alvarotrigo.com/fullPage/pricing/).

**Comment by MarcianoStikkelorum** [comment]
The error/warning I'm getting is;
```
fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:
fullPage: https://github.com/alvarotrigo/fullPage.js#options.
```

As stated on the website and wiki, you could use/try the package on a localhost based website for development and/or testing it out. If I'm not mistaken, that's what I'm doing.

**Comment by alvarotrigo** [comment]
And you can still try it. 
That message won't prevent you from doing so :)
