### ISSUE TITLE
Hide fp-nav

### ISSUE THREAD

**Issue by alexmillern** [alvarotrigo/fullPage.js#3739]
Hello, how to hide #fp-nav when the hamburger is active and show again when the hamburger is closed? I sketched the link below for an example. Sorry for my English.
https://codepen.io/alexmillern/pen/KKPYpMO

> $('.hamburger').click(function(){
		$('#fp-nav').hide();
		$('.hamburger').click(function(){
			$('#fp-nav').show();
		});
});

I tried to do it, it turned out, but how to loop?

**Comment by alvarotrigo** [comment]
That's more a JS / CSS question than a fullPage.js one.
I would encourage you to ask in other places such as stackoverflow.com where they'll be able to help you better.
