### ISSUE TITLE
Big glitch when revisiting the slider tab

### ISSUE THREAD

**Issue by komidesign** [alvarotrigo/fullPage.js#3741]
I've noticed a big glitch if for example we visit the page containing the slider , move to another browser tab, wait 10-15 seconds and then switch back to the slider's page.
Example: 
https://codepen.io/komidesign/pen/QWLPVbO

**Comment by alvarotrigo** [comment]
That's a JS  question rather than a Javascript one :)

`setInterval` stills runs in the background when you change tabs.
Just make sure to disable it somehow.

But you'd better ask this question in stackoverflow.com where they'll be able to help you much better.
