### ISSUE TITLE
[Question] scrollHorizontally

### ISSUE THREAD

**Issue by wfabian** [alvarotrigo/fullPage.js#3742]
Hi,
i'm thinking about to buy and use the scrollHorizontally-Extension.
But I've some questions about it.

I would use only one section and about 5 slides.

- Would it be possible to have a larger width than normal/100vw? _**--> Edit: Tested it with standard version. Doesnt work. Wont work either. So this question is useless - sorry for that :-)**_

- Is it possible to use scrollOverflow and scroll down inside a slide, while using scrollHorizontally-extension? 

Thanks for your help! :-)

**Comment by wfabian** [comment]
Update:
Bought it. Tested it. Overflow is still working :-)

**Comment by alvarotrigo** [comment]
Glad you managed to solve your issue :)
