### ISSUE TITLE
Working with pre-existing anchors.

### ISSUE THREAD

**Issue by imlearningslow** [alvarotrigo/fullPage.js#3744]
Alvaro i am so sorry for using this method to ask such a noob question. But i did not know how else to contact you, if i am out of line please inform me so i delete this and please feel free to do so if you can and want to.

I have been reading thru all of your documentation and i cant find a way to make it work with pre-existing anchors.

I wanted to try the initialization using the anchor options, and the main div so i wouldn't have to change my Dom structure all that much.

Do i have to mark the anchors with data-anchor regardless of my approach.

i apologize for being stupid in advanced.

**Comment by alvarotrigo** [comment]
I'm not sure what you are asking for.

You can define anchors by using the anchors option or by  using the `data-anchor` attribute.
You can choose :)

**Comment by imlearningslow** [comment]
Dear Alvaro Sorry for being so vague and for not replying on time, i honestly didn't think you would ever reply. You must be really kind and for that i am very grateful.

i found out that this was my problems, again thanks to you.

@Jake, fullpage.js support them, but you were doing it in the wrong way. Of course, you have to specify the section name before it, otherwise there could be conflicts between slides of different sections in case of using the default anchorlink (1, 2...). Anyway, as I said, your problem was in the use of id tags with the same value as your anchorlink. – Alvaro Apr 22 '14 at 8:51

You diserve good things in life, as soon as i have money i would at least buy you a cup of coffee.

Thanks and keep up the good work!.

**Comment by alvarotrigo** [comment]
Glad you managed to solve your issue ;)
