### ISSUE TITLE
how to setup licence key

### ISSUE THREAD

**Issue by sachinsam11** [alvarotrigo/fullPage.js#3753]
###I have licence key

Hi,
I have licence key but it not working I have licence key and I added it in option in Fullpage.js but it's not working can you please help? 

```javascript
  options = deepExtend({

            //navigation

            menu: false,

            licenseKey: 'XXXX-XXXX-XXXX-XXXX',

            anchors:[],

            lockAnchors: true,

            navigation: false,
```

**Comment by alvarotrigo** [comment]
As detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

> **licenseKey:** (default null). This option is compulsory. If you use fullPage in a non open source project, then you should use the license key provided on the purchase of the fullPage Commercial License. If your project is open source, contact me with a link to its repository and I'll provide you a license key. Please read more about licenses here and on the website. For example:

```javascript
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});
``` 

So, DO NOT modify the fullpage.js source code. Just add the option in the initialisation.
