### ISSUE TITLE
normalScrollElements only works in first section

### ISSUE THREAD

**Issue by djhe** [alvarotrigo/fullPage.js#3754]
Hi,
normalScrollElements only works in first section

**Comment by alvarotrigo** [comment]
Perhaps you are trying the fullpage.js in the development branch?

It indeed seems there's an issue there, but not on the stable master one:
https://codepen.io/alvarotrigo/pen/RmVazM

**Comment by djhe** [comment]
Ok, I will check with another version. 
Thanks for your reply.

**Comment by alvarotrigo** [comment]
I'll keep it open as it is an issue on the dev branch.

**Comment by alvarotrigo** [comment]
Fixed on dev!

**Comment by alvarotrigo** [comment]
Fixed on 3.0.8!
