### ISSUE TITLE
Drag and Move not working on Mobile

### ISSUE THREAD

**Issue by IntricatePixels** [alvarotrigo/fullPage.js#3755]
### Description
On a mobile device I cannot scroll up and down the sections unless I use the navigation dots. 

### Link to isolated reproduction with no external CSS / JS
Simply open this link in your mobile device to repro (it will work if you are using a regular browser like Chrome and using the mobile view inspector), so please use mobile device.

### Steps to reproduce it
1. Open Link on a Mobile Phone (or emulator)
2. Tap screen to scroll down

### Versions 
Tested on Android and iPhone. 
Using latest version (plugin and Drag and Move extensions purchased yesterday.

I tried disabling fullPage.js below 900 to no avail. 

`<link rel="stylesheet" type="text/css" href="/fullPage.js-master/dist/fullpage.css" />`
`<script src="/fullPage.js-master/vendors/easings.min.js"></script>`
`<script type="text/javascript" src="/fullPage.js-master/dist/fullpage.dragAndMove.min.js"></script>`
`<script type="text/javascript" src="/fullPage.js-master/dist/fullpage.extensions.min.js"></script>`

`<script>`
`new fullpage('#fullpage', {`
`	licenseKey: 'XXXXXX',`
`  	anchors: ['panel1', 'panel2', 'panel3', 'panel4', 'panel5'],`
`         navigationTooltips: ['Prints', 'Ordering', 'Sizes', 'Honor', 'Footer'],`
 `        css3: true,`
 `        scrollingSpeed: 1000,`
  `       navigation: true,`
   `      dragAndMove: true,`
   `      dragAndMoveKey: 'XXXXXX'`
   `     });`
`</script>`

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by IntricatePixels** [comment]
Anything that stands out on your end from the code with options I've provided?

**Comment by alvarotrigo** [comment]
@IntricatePixels nope. Everything looks pretty normal. (although you don't need to import easings.min.js)

And as far as I can tell, the [main fullPage.js site](https://alvarotrigo.com/fullPage/) (that uses Drag And Move) works perfectly on touch devices.

**Comment by IntricatePixels** [comment]
If I go to the second panel, it starts working so looks like it's something funky with the first panel where it gets stuck.  Thanks for the prompt replies.  I'll see if I can fix, otherwise will add it on a jsfiddle.

**Comment by alvarotrigo** [comment]
> otherwise will add it on a jsfiddle.

Try an isolated reproduction in your server  better.
jsfiddle and codepen use iframes that can conflict with fullPage.js behaviour.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
