### ISSUE TITLE
Horizontal Scrolling does not work on last slide on Chrome

### ISSUE THREAD

**Issue by snowflake2019** [alvarotrigo/fullPage.js#3757]
### Description
The last slide scrolls to the first slide, rather than stay on the last slide.

### Link to isolated reproduction with no external CSS / JS
annualreport.norc.org

### Steps to reproduce it
Scroll horizontally through the slides
After clicking on the last arrow, it look back to the slide 1 again.

### Versions 
Problem only exists in Chrome. Firefox and Edge, IE all work.

**Comment by alvarotrigo** [comment]
Use the fullPage.js option `loopHorizontally:false`
