### ISSUE TITLE
Background Video Auto-Rewind

### ISSUE THREAD

**Issue by asdangus** [alvarotrigo/fullPage.js#3759]
Hi!

I have a short background video, that plays one time and stops (freezes at end).

Now when i scroll out, i want that video to then automatically and invisibly rewind to start, so that when user comes back to that video section, it autoplays it like in your example (https://alvarotrigo.com/fullPage/examples/videoBackground.html), but from the beginning of the video, and then stops again.

Forgive me for no code embed, it's more a general question towards what should i look to, maybe callbacks? Some guidance would be appreciated!

Thanks many for your attention!

**Comment by alvarotrigo** [comment]
> Forgive me for no code embed, it's more a general question towards what should i look to, maybe callbacks? Some guidance would be appreciated!

Yeah you can make use of the `onLeave` or `afterLoad` callbacks to force the rewind of the video when leaving the section containing it.
