### ISSUE TITLE
Behaviour of the scrolling when all sections are fp-auto-height

### ISSUE THREAD

**Issue by Delemo** [alvarotrigo/fullPage.js#3762]
Hello,

I'm working on a onepage site for which all fp sections have class fp-auto-height.

I don't understand how fp is managing scrolling in this mode.
The scrolldown seems to go section by section by using the bottom of each section.
The scrollup seems to go section by section by using the top of each section.
Is it correct?
If so, could this behaviour be changed to have the scroll go to the top of each section regardless of the direction of the scroll?

Thank you
Simon

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/2801.

I'll close this issue so we can keep the conversation in a single place.
Short answer: not possible yet.
