### ISSUE TITLE
Scripts/plugins not working on responsive resize

### ISSUE THREAD

**Issue by thedesigncore** [alvarotrigo/fullPage.js#3769]
I'm using the responsive slides extension to convert my horizontal slides to normal scrolling under a specified viewport width.

I have some scripts and other plugins that work fine until the browser window gets resized and fires the responsive slides extension. Once that happens my custom scripts and other plugins stop working. I have to refresh the page to get them to work again.

Any help is appreciated.

**Comment by alvarotrigo** [comment]
Any question regarding extensions, please [contact us](https://alvarotrigo.com/#contact) with an isolated reproduction of the issue.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by alvarotrigo** [comment]
The issue was solved and was due to the lack of event delegation on `click` events.
