### ISSUE TITLE
Updating failed (403 Error) after Enable FullPage

### ISSUE THREAD

**Issue by cschultzburkson** [alvarotrigo/fullPage.js#3771]
### Description

Error when saving a page or publishing a new page after enabling FullPage in Gutenberg. In console I see a 403 error to https://www.domain.com/wp-json/wp/v2/pages/279/autosaves?_locale=user

Error: "Updating failed"

### Steps to reproduce it
1. Create a new page (or edit existing)
2. Add a section with fullPage.js
3. Enable FullPage
4. Publish page

### Versions 
WordPress 5.2.3
Chrome

**Comment by alvarotrigo** [comment]
As this is not a fullpage issue, can you please report it by using the [contact form](http://alvarotrigo.com/#contact) in the page and selecting the WordPress option? 

Thanks!

**Comment by cschultzburkson** [comment]
For the record, the issue was that I needed to disable ModSecurity with my hosting provider.

**Comment by alvarotrigo** [comment]
Thanks for clarifying it! :)
