### ISSUE TITLE
Text cannot be selected inside section with scrollOverflow

### ISSUE THREAD

**Issue by IdanGoor** [alvarotrigo/fullPage.js#3772]
Unable to select text inside section with scrollOverflow.
This can be easily reproduced in the formal fullPage.js example:
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html#secondPage

Pay attention that text can be selected in Section 1 but not in Section 2.

**Comment by alvarotrigo** [comment]
Duplicated of #2489
