### ISSUE TITLE
possible to make moveSlideRight() and moveSlideLeft() operate silently?

### ISSUE THREAD

**Issue by jeffreynolds** [alvarotrigo/fullPage.js#3774]
Apologies if this is obvious or has been asked before, I couldn't find it.

I've got a fullpage site going where anytime I navigate a slide to the right/left, I want it to occur silently. I'm accomplishing this now by looking to see what fp class is on the body, and conditionally using silentMoveTo() while specifying which slide to move to individually based on that condition. obviously not ideal.

If there's a better way to do this, maybe someone can enlighten me - otherwise, I'd like to put that in as an enhancement request.

**Comment by alvarotrigo** [comment]
Sure! 
Just look at the silentMoveTo method 🙃
