### ISSUE TITLE
normalScroll allong with fixed element makes sections not scrolling on firefox

### ISSUE THREAD

**Issue by 4nt0n** [alvarotrigo/fullPage.js#3775]
I use normalScrollElement:true in a fixed sidebar on top of my scrolling sections. Aftrer you scroll inside the fixed element the section do not scroll anymore for some time. (or If you click in an element inside a section seems to make it work again). 

This happens in FIrefox (latest version)

Example: [https://codepen.io/_4nt0n_/pen/mddeYwG](https://codepen.io/_4nt0n_/pen/mddeYwG)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I was able to test it myself and seems to be some kind of bug.

We'll check it for the next release!

**Comment by 4nt0n** [comment]
Do you have an estimation on when is the next release?

**Comment by alvarotrigo** [comment]
Not really, I would need to take a look at it with time.
Hopefully in the next release in about a month or so.

**Comment by alvarotrigo** [comment]
The issue has been fixed on the dev branch 3.0.8!

**Comment by alvarotrigo** [comment]
Fixed on 3.0.8!
