### ISSUE TITLE
Img fadein after section load

### ISSUE THREAD

**Issue by s3nia** [alvarotrigo/fullPage.js#3776]
Hi!
i'm trying to have img fadein effect after section has been loaded (something like this https://codepen.io/anon/pen/aNGdvr but with section instead of slides ). I set img display:none in the 3rd section of my fullpage, then I tried using afterload but it doesn't work. I'm not so good with coding, can please anyone help me? Many thanks! This is my code:
https://codepen.io/antonio_senia/pen/MWWKXjW

**Comment by alvarotrigo** [comment]
We only provide support for the latest version of fullPage.js here. (3.0.07 now) so please update and see the docs regarding callbacks:
https://github.com/alvarotrigo/fullPage.js#callbacks

You'll be able to find an example of triggering animations here:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/trigger-animations.html

**Comment by s3nia** [comment]
Is there any other site where I can ask for help? Unfortunately I'm not a programmer and I can't figure out how to use the links you shared with me. Thanks!

**Comment by alvarotrigo** [comment]
Sure!
We provide premium support for those who acquire the Organization license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by alvarotrigo** [comment]
Otherwise I would suggest you to ask in other places such as stackoverflow.com where they'll be able to help you better.

**Comment by s3nia** [comment]
Thank you!
