### ISSUE TITLE
Autoplay video in section with slides

### ISSUE THREAD

**Issue by wfabian** [alvarotrigo/fullPage.js#3777]
Hi,
I'm trying somethin very special.

I do have a page with multiple sections and slides.

For every section there is a background-video.
The video should be playing in background of my slides – But:
It should play continuously. It shouldnt start from 0 on each slide.

So i created a structure similiar to this:

```
<div class="section">
  <div class="video-wrapper">
    <video data-src="the/path/to/video.mp4" data-autoplay><video>
  </div>
  <div class="slide">1</div>
  <div class="slide">2</div>
  <div class="slide">3</div>
</div>

```

But the video will not be loaded through the lazy-load-function. 
Autoplay works fine, while I'm not using the data-src attribute.

If i put the background-video inside a slide, everything works fine. 
But then, the video is not in background of all slide – Just in background for the specific slide, which contains the video.

Do you understand, what I'm trying to do?
Is there any way to do that?
Would be great!

**Comment by alvarotrigo** [comment]
fullPage.js won't lazy load it as it would only lazyLoad the elements in the active slide. As your video is no in any slide then it won't be loaded.

You can just load it yourself by using the `onLeave` callback and changing the data-src attribute yourself :)
