### ISSUE TITLE
Scroll horizontally does not work on the last slide

### ISSUE THREAD

**Issue by snowflake2019** [alvarotrigo/fullPage.js#3781]
### Link to isolated reproduction with no external CSS / JS
annualreport.norc.org

### Steps to reproduce it
On Google Chrome, 
Scroll horizontally through the slides
After clicking on the last arrow, it loop back to the slide 1 again (never have chance to view the last slide).
The loop horizontally is set to false.

### Versions 
Issue exists in Chrome only.

**Comment by alvarotrigo** [comment]
Unfortunately we only provide support for the latest fullPage.js version, which right now is 3.0.7.
You are using 2.9.6.
