### ISSUE TITLE
Scroll horizontally does not work on the last slide

### ISSUE THREAD

**Issue by snowflake2019** [alvarotrigo/fullPage.js#3782]
### Description
When scrolling horizontally to the last slide, on chrome, it loops back to the first slide without display the current slide content.
### Link to isolated reproduction with no external CSS / JS
annualreport.norc.org

### Steps to reproduce it
This issue is reproduced on fullPage.js 3.0.7 (the latest version)
On Google Chrome,
Scroll horizontally through the slides
After clicking on the last arrow, it loop back to the slide 1 again (never have chance to view the last slide).
The loop horizontally is set to false.

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
I'm not able to reproduce the issue. 
I can see the last slide (#home/7) with blue background.

**Comment by snowflake2019** [comment]
It only occurs on Google Chrome. Do you use Google Chrome? If yes, which version of chrome?

**Comment by alvarotrigo** [comment]
> Do you use Google Chrome? If yes, which version of chrome?

Yes, the latest :)
Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by snowflake2019** [comment]
On laptop? What is the screen resolution? Thanks.

**Comment by alvarotrigo** [comment]
> On laptop? What is the screen resolution? Thanks.

That should be irrelevant :)

In any case, [you are using fullPgae.js 2.9.7](http://annualreport.norc.org/fullpage/jquery.fullpage.min.js) and we only provide support for the latest version 3.0.7.

Try updating fullpage.min.js, fullpage.min.css and scrolloverflow.min.js.
