### ISSUE TITLE
Trouble integrating fullscreen iframes into Fullpage js. 

### ISSUE THREAD

**Issue by LisaBluniverse** [alvarotrigo/fullPage.js#3783]
https://github.com/alvarotrigo/fullPage.js

How can I add an iframe to Fullpage js without it all freaking out? 

As soon as I add an iframe, the whole thing goes crazy - loading straight to a later page, loading halfway up the screen, or just scrolling fast from beginning to end. 

I'm not even concerned with my iframe scrolling within the page because I have a menu always present (although I'd like to fix that also!).

Thank you! :)

**Comment by alvarotrigo** [comment]
I can't see any problem:
https://jsfiddle.net/g9brfyak/

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
