### ISSUE TITLE
Blocked scroll in modal window

### ISSUE THREAD

**Issue by AShukilovich** [alvarotrigo/fullPage.js#3785]
### Description
Hey. I ran into the problem that when you open a modal window with a lot of content, the background with the page scrolls all the way. I tried to solve this problem by method setAllowScrolling on events of opening/closing a modal window. But then the whole scroll on the mouse wheel is blocked. I tried to solve the problem by method setAutoScrolling, but then the site jerks.

### Link to isolated listening
https://jsfiddle.net/AShukilovich/7a3y8Lg1/25/

### Steps to display it
1. Open the modal bootstrap window
2. Check scroll in modal

### Versions
All browsers

p.s. Sorry, for my bad english

**Comment by alvarotrigo** [comment]
See the `normalScrollElements` option in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

Your updated jsfiddle: https://jsfiddle.net/bh0dsc4r/
