### ISSUE TITLE
fullpage option scrollOverflow 

### ISSUE THREAD

**Issue by robertvanroon** [alvarotrigo/fullPage.js#3787]
iScroll seems to have issues with vh (css) on iOS

https://github.com/robertvanroon/fullpage-scrollOverflow

It doesn't show on codepen. Codepen makes its own container/wrapper.

It is only possible to check this on the devices itself.

When using vh in stead of % for height the scrollOverflow option of fullpagejs auto magically adds overflow.

Tested on iPad & iPhone on iOS 10.3.4 & 12.4.2

**Comment by alvarotrigo** [comment]
Where are you using vh? 
Can you please provide an isolated reproduction in your own server? Or just paste the code in codepen and I'll create the file myself.

**Comment by robertvanroon** [comment]
Hi Álvaro,

I am using vh (& vw, the overflow seems to occur only with vh) for divs inside the sections.

I've made isolated reproduction, you can get it at:
https://github.com/robertvanroon/fullpage-scrollOverflow

Or if you prefer codepen:
https://codepen.io/robertvanroon/pen/zYYojBz

I would like to use vh instead of %, because it offers some options that % doesn't.

**Comment by alvarotrigo** [comment]
VH was never ideal :)
I would say it is not really a bug in fullpage.js or iScroll but on the way browsers treat VH units.

See this topic for more info:
https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html
