### ISSUE TITLE
scroll not working

### ISSUE THREAD

**Issue by jlgouveia** [alvarotrigo/fullPage.js#3788]
https://blug.joseluisgouveia.com

**Comment by jlgouveia** [comment]
arrow up and down work, but not normal scroll not wheel

**Comment by alvarotrigo** [comment]
Unfortunately we do not check private websites here, we only provide premium support for people who acquired [the Organization license](https://alvarotrigo.com/fullPage/pricing/).

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/1kyuL4em/116/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
