### ISSUE TITLE
Page with Fullpage Mobile menu doesnt scroll

### ISSUE THREAD

**Issue by Kristea** [alvarotrigo/fullPage.js#3789]
I'm getting this issue now on a website I am working on (staging site: https://floccstage.wpengine.com) The mobile menu on the Home page just doesn't scroll. 
Disabling the script, or on pages where there is no fullpage.js the menu can scroll fine. So it must be something the script is implementing. 
It seems similar to issue  #3520 
I have the latest js and css versions (3.0.7).

  ```
var fullPageInstance = new fullpage('#fullpage', {
        scrollHorizontally: false,
        scrollingSpeed: 100,
        navigation: true,
        dragAndMove:true,
        onLeave: function (origin, destination, direction) {
            if (homeSlides.tweening) {
                return false;
            }
        },
        afterLoad: function (origin, destination, direction) {

            if (direction === "up") {
                tweenDown(destination.index);
            }
            else if (direction === "down") {
                tweenUp(destination.index);
            }
        },
        licenseKey: '****'
    });

```

Any suggestions welome. Many thanks.

**Comment by alvarotrigo** [comment]
Have you taken a look at the `normalScrollElements` option in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)?

That's probably what you need.

**Comment by Kristea** [comment]
@alvarotrigo Brilliant! Thanks :)
