### ISSUE TITLE
Closing a modal on scrolling up

### ISSUE THREAD

**Issue by Damiano31** [alvarotrigo/fullPage.js#3791]
I want to close modal if it's still open when i scroll up or down. when I scroll downwards they close properly instead if I scroll upwards I return to the same section and the section does not cover the entire viewport in height

### Steps to reproduce it
1. Open Bootstrap modal
2. Scroll up

How can i fix ?

Thanks

**Comment by alvarotrigo** [comment]
Take a look at the normalScrollElements option in the <a href="https://github.com/alvarotrigo/fullPage.js" target="_blank">fullpage.js documentation</a>.

That's what you need.

And if that doesn't do the trick you can always use `fullpage_api.setAllowScrolling(true)` and `fullpage_api.setAllowScrolling(false)`
