### ISSUE TITLE
Only slide with carousel

### ISSUE THREAD

**Issue by wfabian** [alvarotrigo/fullPage.js#3793]
Hey,
what I like to do is:
To have a page with only one section and a few slides.
There will be about 8 slides but it doesnt matter for my question.

I also would like to have a carousel. Tried it with slick:
https://kenwheeler.github.io/slick/

Maybe I'm used to use another plugin like tiny slider. But i think in doenst matter for my question

But if I try to swipe to next slick-carousel-item, i'm always swiping to the next fullpage.js-slide. (mobile)

Is there anyway to do that?
Can anybody understand what i'm lookin for? :D

**Comment by alvarotrigo** [comment]
You probably are talking about  the Scroll Horizontally extension:
https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html

**Comment by alvarotrigo** [comment]
Check the fullpage.js option `normalScrollElements` .

**Comment by wfabian** [comment]
Worked for me - thanks!
