### ISSUE TITLE
loadCSS + Fullpage

### ISSUE THREAD

**Issue by localnetwork** [alvarotrigo/fullPage.js#3795]
When using [loadCSS](https://github.com/filamentgroup/loadCSS) most of the time, the page is whitespace. loadCSS fixes the "Eliminate render-blocking resources" in google pagespeed.

![fullpage-loadcss](https://user-images.githubusercontent.com/15809239/67752713-6a671d80-fa6e-11e9-8c2c-e311f9755c35.gif)

**Comment by alvarotrigo** [comment]
What's exactly the issue?
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
