### ISSUE TITLE
I didn't find the code of this page on the master branch.

### ISSUE THREAD

**Issue by GanZhiXiong** [alvarotrigo/fullPage.js#3803]
this page https://alvarotrigo.com/fullPage/examples/apple.html

**Comment by alvarotrigo** [comment]
That's because it was never there :)

**Comment by GanZhiXiong** [comment]
😀   Hi, @alvarotrigo   Can this code be open source？Thanks！

**Comment by alvarotrigo** [comment]
Just open this url in chrome:
view-source:https://alvarotrigo.com/fullPage/examples/apple.html

**Comment by GanZhiXiong** [comment]
Thank you, or look forward to your open source!😀
