### ISSUE TITLE
How to set section to follow finger movement on the phone

### ISSUE THREAD

**Issue by GanZhiXiong** [alvarotrigo/fullPage.js#3805]
When more than half of the section of mobile scales automatically move to the next or on a section, I see your sample web site (https://alvarotrigo.com/fullPage) is achievable

**Comment by alvarotrigo** [comment]
Using the  Drag And Move extension:
https://alvarotrigo.com/fullPage/extensions/drag-and-move.html

You can find all extensions on the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/) page.
