### ISSUE TITLE
How do I set the section to be displayed when I open a website？

### ISSUE THREAD

**Issue by GanZhiXiong** [alvarotrigo/fullPage.js#3806]
Let's say I have multiple sections, section1, section2, section3, and I want section2 to be displayed by default when I open the website, how do I do that?

**Comment by alvarotrigo** [comment]
Easy! 
Just add the class `active` to that slide as detailed in the docs:

> If you want to define a different starting point rather than the first section or the first slide of a section, just add the class active to the section and slide you want to load first.
```html
<div class="section active">Some section</div>
 ```
