### ISSUE TITLE
Sections scrolled differently onload (scrolloverflow)

### ISSUE THREAD

**Issue by LauraPiccolo** [alvarotrigo/fullPage.js#3807]
Hi Alvaro,
I am writing this because I couldn't find a solution anywhere for my problem, I have spent days looking.
It's very simple : in my page I have 3 sections.
```
<div id="section1">This section uses scrolloverflow</div>
<div id="section2">This section has a height of 100vh</div>
<div id="section3">This section uses scrolloverflow</div>
```

When the user arrives on the page, I use :
`fullpage_api.moveTo('section2', 1);`
— to move to the middle section.

Everything works fine, but when the user scrolls up to section1, section1 is scrolled to top, and I would like it to be scrolled to bottom.
BUT I still want section3 to be scrolled to top at the begining (which is already the case currently).
I have seen the "bigSectionsDestination" option, but :
1 - It doesn't work on my script, I am not sure why
2 - I don't think it would be the solution anyways, as I want the two big sections to be scrolled differently

I have tried to scroll it dynamically, by changing the "transform" property, which works, but as soon as I start scrolling, it goes back to the top of the section.
I hope the explanations are clear, I am not a professional programmer yet.

Do you think there is a solution to my problem ?
Thank you so much!

**Comment by alvarotrigo** [comment]
Unfortunately that's not an option provided by fullPage.js and we won't probably provide it.

You can try running this on `afterLoad` when reaching section 1:

```js
document.querySelector('#section1 .fp-scrollable').fp_iscrollInstance.scrollTo(0, -document.querySelector('#section1 .fp-scroller').offsetHeight + window.innerHeight);
```

**Comment by LauraPiccolo** [comment]
Thank you so much it works !!
