### ISSUE TITLE
HP trackpad scrolls too far ONLY when scrollBar:true

### ISSUE THREAD

**Issue by noob01000101** [alvarotrigo/fullPage.js#3811]
I used scrollBar:true to get my number counter to work, then it started to scroll too far when using my trackpad.  My scroll speed is set to 1000.  I do scroll pretty fast admittedly, with sort of a flick motion I guess.  I read through a bunch of posts but most of them seemed to be focused on mac.  It also seemed that most people use callbacks instead of activating the scrollbar but that is beyond my ability level as this is my first time creating a website.  I kind of like having the scrollbar in case my section happens to be too large, even though it doesn't look as good...again too much of a noob to make sure this never happens.  

I'm using elementor, hello theme, windows 10, and an HP laptop.  I had this issue on chrome, firefox, and explorer.  All are up to date.

Please let me know if you need any other info, thanks!

**Comment by noob01000101** [comment]
Oh and here's my site: http://alexm17.sg-host.com/

Don't mind all of the colors at the end...I'm also having an issue with it snapping to the start of my section.  The green strips are from the background of my home page and the other colors are the backgrounds of my sections/templates.  There shouldn't be any space between my sections (green strip) so I'm asking elementor for help.  If you can beat them to it though that'll be awesome ^_^

**Comment by alvarotrigo** [comment]
You are importing fullPage.js multiple times. Get rid of `fullpage.extensions.min.js` because you are not using any extension.

```html

<!-- end Simple Custom CSS and JS -->
--
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.js"></script>
  | <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.css" />
  | <script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.4/fullpage.extensions.min.js"></script>
``` 


Also make sure to use the latest version 3.0.7. 
You can get it from Github, npm or [any CDN](https://unpkg.com/browse/fullpage.js/).

Regarding your scroll problem, I can only recommend you to scroll slower :)
There's no proper solution for kinetic scrolling devices when they scroll so fast. We have no control over it.
