### ISSUE TITLE
fp-auto-height not snapping to footer

### ISSUE THREAD

**Issue by noob01000101** [alvarotrigo/fullPage.js#3812]
I gave my footer the class fp-auto-height but it still is not snapping.  I'm wondering if it is because this section is nested?  I'm using elementor, so the section is nested within a few other divs.  Does this class need to be on the highest footer div?  I'm not sure how to add a class to it so I can't test this out.

http://alexm17.sg-host.com/

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML codee? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by noob01000101** [comment]
I'm using a theme to design my site so I'm not sure how to create an isolated reproduction.  

I did make some progress though...instead of applying my footer template to my entire site, I just used it's id.  Now the dot icon shows up on the side, and it scrolls farther than it did before, **but it only scrolls half way**.

How can I get it to scroll all the way to the bottom?

**Comment by alvarotrigo** [comment]
Unfortunately we can't really  help you more without an isolated reproduction.
I'll close the issue until a reproduction is provided.

If you need premium support so we can check your site you can consider purchasing the Business license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/).

**Comment by noob01000101** [comment]
I got it to scroll to the bottom of my footer by purchasing your elementor plugin.  However now I'm having issues with my nav menu widget...is there a way to make it fixed, remove it's dot, and scroll over the next section since it's only a few pixels down?  I'm using the Hello theme so I can't really use the theme's header.  Last question then I give up -_-

**Comment by alvarotrigo** [comment]
Consider using the `fixedElements` option or just place it outside the fullPage.js wrapper.
