### ISSUE TITLE
Screen reader support

### ISSUE THREAD

**Issue by SpacegoatHQ** [alvarotrigo/fullPage.js#3816]
This is just a question. Does fullPage.js support screen readers (e.g. the built in VoiceOver on Mac, Windows Narrator, JAWS or NVDA)? If it does, how does the accessibility tool turned on effects the navigation of the site?
Thanks!

**Comment by alvarotrigo** [comment]
Good question!
Unfortunately however I might not be the right person to answer that :)

I'm not well versed on accessibility issues, but you can read a bit about it [on a topic we had in the past](https://github.com/alvarotrigo/fullPage.js/issues/2704).

You can test it yourself by using WAVE Web Accessibility Evaluation Tool here:
http://wave.webaim.org/report#/http://alvarotrigo.com/fullPage/examples/navigationV.html

As far as I read it, it doesn't seem to find any relevant errors?

Perhaps @charlesprescottcollins, @mjoyce91 , @ShayMe21, @chris480  or @karlbalagtey can bring up some insights about it as they seem to know more about the topic.
