### ISSUE TITLE
Cannot find fullpaga.parallax.min.js (I paid for license and extension)

### ISSUE THREAD

**Issue by PubliAlex** [alvarotrigo/fullPage.js#3817]
Hello,

All is in the title, I bought a pro license, bith a parallax extension. Followed all the procedure (have a license Key, a parallax key) but I can't find the fullpage.parallax.min.js file.

Best regards,

Alex

**Comment by alvarotrigo** [comment]
Easy!
Look at your purchase confirmation email. 
There you'll find a green button to download the extension at the bottom.

You also got a link to it on the screen right after the purchase, but I guess you missed it :)

**Comment by PubliAlex** [comment]
Thank you, my teamate bought the extension and forgot to forward me the email ^^'. Resolved.
