### ISSUE TITLE
disable scrolling

### ISSUE THREAD

**Issue by shahab68** [alvarotrigo/fullPage.js#3818]
how to disable scrolling in diffrent device

**Comment by alvarotrigo** [comment]
Easy!
See the different responsive options in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) or the [available examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

**Comment by psobhanlo** [comment]
i want disbale  fullpage  after less sceern 1200px

please help

**Comment by alvarotrigo** [comment]
See the different responsive options in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) or the [available examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

**Comment by shahab68** [comment]
responsiveWidth dosen`t work properly in react fullpage

**Comment by alvarotrigo** [comment]
@shahab68 feel free to open an issue in the[ react-fullpage.js repository ](https://github.com/alvarotrigo/react-fullpage) with a link to an isolated reproduction.
