### ISSUE TITLE
Followed all guides and dragAndMove is still not dragging or moving

### ISSUE THREAD

**Issue by DaveMitten** [alvarotrigo/fullPage.js#3823]
### Followed all guides and dragAndMove is still not dragging or moving

https://jsfiddle.net/davidmitten/n7m2y8du/9/

### Steps to reproduce it
1. Simply open the link above and try to drag and move. It's in local normally or 127.00.....etc.  I use vs-code live server extension normally, but i've also tried running the local file path. I've followed each guide, tried picking apart the demo. Looked at others using it and i cannot see why mine isn't functioning as expected.

The ability to navigate via arrow buttons or via keyboard controls works, it does not work when clicking and dragging and one can presume with a touch event either.

### Versions 
chrome - version 78.0.3904.108 (Official Build) (64-bit)
mac - vr 10.14.6 Mojave
vs-code - Version: 1.40.2

**Comment by alvarotrigo** [comment]
Did you purchase the Drag And Move extension from the [fullpage.js extensions](https://alvarotrigo.com/fullPage/extensions/)page?

**Comment by DaveMitten** [comment]
Yes. I've added that key and the license key.

I have not activated it as in the guides it says i do not need that to proceed with using it. Although I have tried both situations to no avail.

**Comment by alvarotrigo** [comment]
Can you please [contact us](https://alvarotrigo.com/#contact) with a link we can check?

**Comment by DaveMitten** [comment]
Contacted you with the js fiddle link, is that ok? or do you need the github repo access?
