### ISSUE TITLE
scrollBar and empty anchor

### ISSUE THREAD

**Issue by jakubm95** [alvarotrigo/fullPage.js#3827]
Hello
I have a question

Is it possible to enable the "scrollBar" option so that the first section does not have an anchor added?
Below is the problem I've encountered

https://jsfiddle.net/u1nodcg5/1/
When scrolling to a section that does not have an anchor, an error occurs

**Comment by alvarotrigo** [comment]
Rather you have all your sections with an anchor each. Or you do not use anchors at all.
You can not have both sections with anchors and sections without them at the same time.
