### ISSUE TITLE
Fullpage.js with Bootstrap Accordion

### ISSUE THREAD

**Issue by amrfhn** [alvarotrigo/fullPage.js#3829]
Hi Alvaro,

I am using Fullpage.js on my web , and one of my section contains Bootstrap accordion. When the accordion is opened, the section will rebuild and the section's height will increase. Then when the accordion is closed, the section's height doesn't remove back the height it adds when the accordion opened. I am using  fullpage_api.reBuild(); in $('.accordion').on('shown.bs.collapse', function (){}) .

**Comment by alvarotrigo** [comment]
> I am using fullpage_api.reBuild(); in $('.accordion').on('shown.bs.collapse', function (){}) .

You'll also have to use the  reBuild method when you close the accordion. There's probably another callback for that in Bootstrap.

**Comment by amrfhn** [comment]
Thanks, I found the solution. I used .on('hide') instead of .on('hidden'). So when I apply 

$('.accordion').on('hidden'.bs.collpase', function () {
   fullpage_api.reBuild() ; 
});

it's reset my spacing back to default spacing.
