### ISSUE TITLE
afterLoad function returns duplicate sections

### ISSUE THREAD

**Issue by joshua-isaac** [alvarotrigo/fullPage.js#3830]
### Description
I'm trying to use fullpage.js and create an afterLoad function to fire off wow.js to do some animations.

html:
```
<div id="fullpage">
  <div id="home">Home</div>
  <div id="about">About</div>
  <div id="contact">Contact</div>
</div>
```

js:
```
   new fullpage('#fullpage', {
      licenseKey: 'MY_KEY',
      anchors: ['Home', 'About', 'Contact'],
      navigation: true,
      navigationTooltips: ['Home', 'About', 'Contact'],
      showActiveTooltip: true,
      menu: '#menu',
      scrollBar: true,
      afterLoad: function (anchorLink, index) {
      console.log(anchorLink);
      }
   });
```

When scrolling through the sections (Home, About, Contact) the console.log() returns Home, Home, Contact

Any idea why this happens? Thanks in advance!

**Comment by alvarotrigo** [comment]
Can you please reproduce your issue in this fiddle?
https://jsfiddle.net/de8psty3/

It works correctly there at the moment.

**Comment by joshua-isaac** [comment]
> Can you please reproduce your issue in this fiddle?
> https://jsfiddle.net/de8psty3/
> 
> It works correctly there at the moment.

Hey Alvaro, thanks for quick reply! Here's a reproduction of my issue: https://jsfiddle.net/jjuuiiccyyjj/kdbthgc6/5/

**Comment by joshua-isaac** [comment]
> > Can you please reproduce your issue in this fiddle?
> > https://jsfiddle.net/de8psty3/
> > It works correctly there at the moment.
> 
> Hey Alvaro, thanks for quick reply! Here's a reproduction of my issue: https://jsfiddle.net/jjuuiiccyyjj/kdbthgc6/5/

What my goal is the following:

```
		new fullpage('#fullpage', {
			licenseKey: 'YOUR KEY HERE',
			anchors: ['Home', 'About', 'Contact'],
			navigation: true,
			navigationTooltips: ['Home', 'About', 'Contact'],
			showActiveTooltip: true,
			menu: '#menu',
			scrollBar: true,
			afterLoad: function (anchorLink, index) {
				console.log(anchorLink.anchor);
				if(anchorLink.anchor === 'About'){
					// fire off this animation
					$('.about-detail').addClass('wow fadeIn');
				}
			}
		});
```

**Comment by alvarotrigo** [comment]
Your callback signature is not correct.

You use 
```js
afterLoad: function (anchorLink, index) {
```
While the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) talk about:

```js
afterLoad: function(origin, destination, direction){
```
