### ISSUE TITLE
two extension dragAndMove and scrollOverflowReset

### ISSUE THREAD

**Issue by onionlian** [alvarotrigo/fullPage.js#3831]
### Description

When I use two extension at one page, the console show

```
The option `scrollOverflow` is not fully compatible with `dragAndDrop`; Scrolling sections/slides will not work when dragging
```

I want that page dragAndMove then section will always show the start of its content even when scrolling from a section under it

### Link to isolated reproduction with no external CSS / JS
how do I use extension at codepen with Hobby license?

### Steps to reproduce it
1. use mobile, go to https://www.cool-style.com.tw/cool-issue/issue/3
2. scroll to page 3

### Versions 
iphone , safari and chrome

**Comment by alvarotrigo** [comment]
Yeap, the error is correct.
Those extensions are not fully compatible. You won't be able to drag and move on sections using scrollOverflow. 

If you need a refund of one of the extensions please [contact us](https://alvarotrigo.com/#contact)

**Comment by gauini** [comment]
hey @alvarotrigo has this been fixed on the most recent version? thanks!

**Comment by alvarotrigo** [comment]
Nope. That's why the issue is closed, I offered a refund and there's no update from me on the comments :)
