### ISSUE TITLE
Horizontall Scroll Notw working

### ISSUE THREAD

**Issue by LaGtt** [alvarotrigo/fullPage.js#3833]
I've worked with fullpage before at wordpress, and it worked amazing, actually i decided to bought the horizontal scroll license key ! so i replicate those working scripts at mi current installation but i found two problems with my site:
1. The horizontall scroll is not working, and i dont get any console error. The vertical scroll works fine, so i know the site is loading correctly the fullpage.extensions javascript file, and the scroll parametres (speed, etc) except for the HorizontallyScroll:true

2. The site never load completely unless i open (at chrome) DevTools, and magic, it loads the css!!!, some times loads completely but the content stops loading at the middle of the site, unless, again,  i open DevTools. It thought it was the lazy load crushing the content inside the sections, so i tried with lazyload=false, but i still have the same problem (_i had to disable all lazy load options and minify js html & css optimizations plugins to try if they were making trobules but sill have the loading & scroll problem_)

this is how i initiate fullpage script at my page.
As documentation indicated i call the js files, first the fullpage.extensions via cdn and the scrollhorizontally file from my server
this is the script at my page:
<script>
jQuery(document).ready(function( $ ) {
	$('#fullpage').fullpage({
		//options here
        scrollingSpeed: 600,
    lazyload:true,
        navigation: true,
        slidesNavigation: true,
     autoScrolling:true,
    licenseKey:'xxxxxxxxxxxxxxxx',
    scrollHorizontally: true,
    scrollHorizontallyKey: 'XXXXXXXXXXXXXX',
	});
	//methods
	$.fn.fullpage.setAllowScrolling(true);
});
</script>

And my html structure at wordpress consist of  7 "section" class divs inside a "fullpage" id divs.
(please note i've already tried fullpage at wordpress with this "structure" and it worked perfecly")

### Versions 
WordPress: 5.3
fullpage extensions: 3.0.8
Hosting: Siteground

**Comment by alvarotrigo** [comment]
1. You can check a working example named "example-scroll-horizontally.html" on the files that you got  from the "download" button on the purchase confirmation email.
If you believe there's any kind of bug, please provide an isolated reproduction on a page of your site with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction. Then [contact us](https://alvarotrigo.com/#contact) with the link.

I would also advise you to check potential issues by using the fullPage.js inspector page:
https://alvarotrigo.com/fullPage/inspector/

2. Any non extensions issues, please report them on this forum with an isolated reproduction in jsfiddle, codepen or your own site with the minimum amount of code and external files. 

Additionally, you can find a file named "How to use it.html" that guides you step by step on how to use the extension you purchased.

Oh,and if you prefer, we provide a plugin for [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) and [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) builders too!
