### ISSUE TITLE
Form submission not working in Mobile and Tablets

### ISSUE THREAD

**Issue by WLNishantha** [alvarotrigo/fullPage.js#3834]
Hi,
I am using this plugin in WordPress. Also I am using [Contact Form 7](https://wordpress.org/plugins/contact-form-7/) In desktop works well. But in Mobile and Tablet devices, form submission not working.

Please advice.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/), [codepen](https://codepen.io/alvarotrigo/pen/qqabrp) or a subpage of your own site, with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
