### ISSUE TITLE
Centering error on mobile phones

### ISSUE THREAD

**Issue by Coffer-studio** [alvarotrigo/fullPage.js#3835]
Good day. We paid for the license, but did not find the support service, so we leave a request here. On our site, when scrolling the page, each time the blocks are centered incorrectly in height. As a result, some content may not be visible.
http://vidodo.coffer.studio/main/index_ru.html

![1](https://user-images.githubusercontent.com/53970973/70800029-3e082600-1dbc-11ea-94a3-63662b348e89.jpeg)
![2](https://user-images.githubusercontent.com/53970973/70800030-3e082600-1dbc-11ea-9243-d077f4003a8d.jpeg)

**Comment by alvarotrigo** [comment]
If you purchased the Business license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/), then you can [contact us](https://alvarotrigo.com/#contact) directly. 

Let me know if that's the case!

**Comment by Coffer-studio** [comment]
Hello. I've wrote you by that form, but didn't get any answer. What i should do, to get solution?

**Comment by alvarotrigo** [comment]
Wait a bit? :)

**Comment by Coffer-studio** [comment]
ok

**Comment by Coffer-studio** [comment]
??

**Comment by alvarotrigo** [comment]
You got replied by email  2 days ago. You just didn't reply back. We are waiting for your reply.

**Comment by Coffer-studio** [comment]
I will be very grateful if I can solve this before the end of the month, because I have a deadline for the completion of the project. Thanks!

**Comment by alvarotrigo** [comment]
Try creating an isolated reproduction in jsfiddle or codepen and that will speed  up the process of us taking a look at it, as we don't check private sites on Github issues unless isolated.
