### ISSUE TITLE
Autoscroll back to top

### ISSUE THREAD

**Issue by dropthespark** [alvarotrigo/fullPage.js#3836]
Hello!

Is there a way to autoscroll back to the top if you reached the last section at the bottom of a page?
I'm using webflow.

Thank you!

**Comment by alvarotrigo** [comment]
Yeap!
Use the method `fullpage_api.moveTo(1)` on the click event :)

**Comment by krishnaprasadkckp** [comment]
@alvarotrigo , tried the same, Suppose my structure is like this - 
<section>1</section>

<section>2
    <slide>A</slide>
    <slide>B</slide>
    <slide>C</slide>
</section>

<section>3</section>
<section>4</section>

If I used fullpage_api.moveTo(1) - it will reach top. but active horizontal section will be 'C'. 
Is there any option to refresh the plugin/reset to default?
Thanks

**Comment by alvarotrigo** [comment]
I don't know what you mean :) 
See the moveTo function working as expected here:
https://codepen.io/alvarotrigo/pen/doqOmY

If it doesn't work as you expect for some reason, can you please provide an isolated reproduction in jsfiddle or codepen? Thanks!
