### ISSUE TITLE
Change Color Of Scrollbar Dots - Webflow

### ISSUE THREAD

**Issue by dropthespark** [alvarotrigo/fullPage.js#3837]
Hello!

Im using webflow and have difficulties to change the color of the scrollbar dots. It's default color is a dark grey tone, but I want to make it white, just like here: https://alvarotrigo.com/fullPage/#page1 

Can I change the color in webflows Custom Code Section?

Thank you!

**Comment by alvarotrigo** [comment]
Just overwrite the default CSS styles for those elements or directly change the CSS styles of fullPage.js.
Check the `#fp-nav` styles on the styles:
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.css
