### ISSUE TITLE
Anchor link delay

### ISSUE THREAD

**Issue by chrismagiera** [alvarotrigo/fullPage.js#3838]
I have an anchor navigation in an overlay. I’d like the overlay to be closed before the site scrolls to the clicked anchor, so I need a delay of 300ms before the anchor scrolling event is fired. Is there a way to add such a delay?

**Comment by alvarotrigo** [comment]
I would recommend you to use the method `moveTo` instead of the anchor link.
This way you have total control over it by using JS. So you can use a `setTimeout` or just call it when the overlay gets closed.
