### ISSUE TITLE
FullPage.js does not work as in the tutorial

### ISSUE THREAD

**Issue by lalinda74** [alvarotrigo/fullPage.js#3839]
This is a question.

I'm trying to add fullpage.js to my website and I have already requested the license key. I went through this tutorial in below link and followed the same steps. 

[YouTube Tutorial](https://www.youtube.com/watch?v=IeZSN6lWsWM)

But I'm not getting the expected result. Instead, I get below errors in console.

> fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a licenseKey option. Read about it here:

> fullPage: https://github.com/alvarotrigo/fullPage.js#options.

I can see the same errors in the console of instructor who is doing the tutorial in the video. But he is getting the desired output.

What I'm doing wrong here ?

This is the only file in my project.

`<div id="fullPage">
        <div class="section s1">
            <h1>the first section</h1>
        </div>
        <div class="section s2">
            <h1>the second section</h1>
        </div>
        <div class="section s3">
            <h1>the third section</h1>
        </div>
    </div>`

`<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.5/fullpage.min.js"
        integrity="sha256-C19V3BEZT3jDhm7hctby8ZYhoXDJr0DxagpwB4RIpWc=" crossorigin="anonymous"></script>
    <script>
        new fullpage('#fullpage', {
            autoScrolling: true
        })
    </script>`

Secondly, I would like to know how this license key thing is going to work in front-end applications?

**Comment by alvarotrigo** [comment]
No problem!
You can just [download fullpage](https://github.com/alvarotrigo/fullpage.js/archive/master.zip) and take a look at the examples folder.

There you can take any of those as your starting point.

If you still have doubts, you can read all you need to know about fullPage.js in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

**Comment by lalinda74** [comment]
Hi @alvarotrigo,

But when I copy the fullapage.min.css and fullapage.min.js files from examples folder to my project, it doesn't work. Do you know any reason for that ?

**Comment by alvarotrigo** [comment]
Yeah, you are definitely doing something wrong :)
What? I have no clue.

That's why I suggest you to take any of the working examples as your base project.
