### ISSUE TITLE
scrollOverflow not work in Microsoft Edge 

### ISSUE THREAD

**Issue by k1rilenko** [alvarotrigo/fullPage.js#3840]
Hello, on your [demo](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html#secondPage) after the second section there is no way to go to the third slide

### Versions 
[Browser- Microsoft Edge 44.17763.831.0, operating system - Win 10 ver.1809]

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
We are actually aware of the situation and we will try to fix it as soon as possible!

**Comment by alvarotrigo** [comment]
This issue  has been fixed on the [dev branch](https://github.com/alvarotrigo/fullPage.js/tree/dev/vendors) and will get merged in the next fullPage.js release.

**Comment by xapizmat** [comment]
> This issue has been fixed on the [dev branch](https://github.com/alvarotrigo/fullPage.js/tree/dev/vendors) and will get merged in the next fullPage.js release.

Hello. I'm waiting for a new release with a fixed this bug very match. But when it will be?

**Comment by alvarotrigo** [comment]
@xapizmat not sure yet. We usually wait for a few more bugs in order to make a new release.
However, you can get it from the file `vendors/scrolloverflow.js `from the [dev branch](https://github.com/alvarotrigo/fullPage.js/tree/dev/vendors) or get it from npm by installing it  using:

```sh
npm install git://github.com/alvarotrigo/fullPage.git#dev --save
```

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
