### ISSUE TITLE
low frame rate when scrolling

### ISSUE THREAD

**Issue by amantham20** [alvarotrigo/fullPage.js#3842]
### Versions 
[chrome 79, windows 10, microsoft surface, ...]

**Comment by alvarotrigo** [comment]
CSS3 transformations are hardware accelerated so the animation will be more or less smooth depending on your hardware setup.

Also, consider using `css3:false` to disable hardware acceleration or `scrollBar:true`, but `css3` should be the most optimal one in any case.

**Comment by Mostafa266** [comment]
Hello,
my company was buy dragAndMove plugin
and now i'm using it
it's working perfect in small screen with 60 FPS and Above but in large screen from 
1920*1080 and above is laaag 
and low frameRate maximum 40 FPS and 10 - Avg 15 or 20
how fix this issue 
my code is clean and do everything to optimise my code

**Comment by Mostafa266** [comment]
Sorry for my English :) 
I'm speak Arabic :)

**Comment by Mostafa266** [comment]
FYI -
i'm build the whole website with horizontal slides not sections

**Comment by alvarotrigo** [comment]
@Mostafa266 the smoothness of the effect will mostly depend on your hardware.
Right now there's no much we can do about it. What you can do is perhaps disable the effect on bigger screens.

**Comment by Mostafa266** [comment]
Okay, thank you for you support i'll do this
