### ISSUE TITLE
fadeEffect - section elements not accessible, possibly stacking order issue?

### ISSUE THREAD

**Issue by EricJammin** [alvarotrigo/fullPage.js#3844]
### Description
There seems to be an issue with the fadeEffect, where some of the section's elements are not accessible because the next section is actually covering it (even though it's not visible). 

This can be seen in your own demo. The text in section 2 can not be selected. If you try to highlight it and inspect it, you'll see you are actually highlighting the text from section 3. Elements inside section 2 are not selectable / can not be interacted with.

### Link to isolated reproduction with no external CSS / JS
The fading effect demo shows this error when you get to the 2nd section:
https://alvarotrigo.com/fullPage/extensions/fading-effect.html

### Steps to reproduce it
1. When you move to section 2, the text elements within that section can not be selected or interacted with, because section 3 is actually on top of it.
2. As a test you can try highlighting the text in section 2, but you'll see it actually highlights the text in section 3. I added in some additional html elements like a paragraph and link into section 2 as a test, and there is no way to click or interact with them.

### Versions 
Tested in Chrome, Firefox and Safari on a mac OS

**Comment by alvarotrigo** [comment]
Uh wow! Good catch! 👍 Thanks for reporting it!!
I'm surprised no-one else mentioned it before! 

Working on the fix!

**Comment by alvarotrigo** [comment]
Good news! 
We've fixed the issue! 😄 

You'll get an email from us about the new version of the extension.
If you don't get it in like 15 or 30 mins just [contact us](https://alvarotrigo.com/#contact).

**Comment by EricJammin** [comment]
Wow that was super fast! Thanks @alvarotrigo 

I was just about to come back here and post a solution using z-index 👍
