### ISSUE TITLE
When "scrollBar:true" doesn't work "easingcss3"

### ISSUE THREAD

**Issue by alekseykurylev** [alvarotrigo/fullPage.js#3847]
Hi, when I specify "scrollBar:true" I don't have the "easingcss3" parameter working"

**Comment by alvarotrigo** [comment]
That's expected.
Scrollbar animation takes place using JavaScript and not css3 transformations. 

You will have to use the `easing` option instead.

**Comment by alekseykurylev** [comment]
Can I use cubic-bezier in the "easing" function?
