### ISSUE TITLE
Options "easing" other libraries

### ISSUE THREAD

**Issue by alekseykurylev** [alvarotrigo/fullPage.js#3849]
I can't connect the library for cubic-bezier to the "easing" option in any way. Please help me find a solution.

**Comment by alvarotrigo** [comment]
If you want to add a new non css3 easing, then you will have to make it available in the `window.fp_easings` object and then use the name of your function in the `easing` option, for example:


```
window.fp_easings.myNewEasing = function (t, b, c, d) {
        return c*(t/=d)*t*t + b;
};
```

Then:
```
new fullpage('#fullpage', { 
     easing: 'myNewEasing'
});
```
