### ISSUE TITLE
Automating slides (js + html)

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#3850]
Hi there! I'm using FullPage to build a website that is populated by an existing dataset. There is a list and each item is clickable and once it's clicked, it triggers another part of the data set that will define the content and how many slides a section should have. 

I have programmed in the same way as this simplified example: https://codepen.io/gauini/pen/XWJgQoe

When I run the files, I can retrieve and display the data from the dataset but it doesn't behave like horizontal slides.

I currently have installed Mac OS Mojave 10.14.5 / programming on Atom 1.42.0 / visualizing on Firefox 70.0.1 (64-bits)

thanks!

**Comment by alvarotrigo** [comment]
I can't see anything on the codepen, just a single section. 

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by gauini** [comment]
hi Alvaro, thanks for the quick response - i've forgot to add a window.onload to run the script once the webpage is loaded, so i've updated it on codepen but that is all the code. The idea is that i'm generating all slide divs through this part of the javascript:

  for (i = 0; i < 10; i++){
    var div = document.createElement("div");
    div.setAttribute("class","slide");
    div.innerHTML = i;
    container.appendChild(div);
  }

when i run locally, it generates the divs but for some reason they don't behave like a fullPage slide. see attached imgs to see what i'm getting so far
![Screen Shot 2019-12-27 at 5 26 26 PM](https://user-images.githubusercontent.com/4229215/71534650-2f4a6480-28ce-11ea-838b-9e5df88cb65b.png)
<img width="682" alt="Screen Shot 2019-12-27 at 5 26 17 PM" src="https://user-images.githubusercontent.com/4229215/71534651-2fe2fb00-28ce-11ea-8dd6-684ff4f66f34.png">

**Comment by alvarotrigo** [comment]
Make sure to update the codepen so I can see what you mean.

**Comment by gauini** [comment]
codepen is updated, but i am getting an error from fullpage obj on the js part: "fullpage is not a constructor"

**Comment by alvarotrigo** [comment]
> codepen is updated, but i am getting an error from fullpage obj on the js part: "fullpage is not a constructor"

You are not including fullpage.js JS and CSS files.
Make sure to do so.

**Comment by gauini** [comment]
copying and pasting all the content from fullpage.js and fullpage.css? thanks!

**Comment by gauini** [comment]
ok i just forked your example and here's the result:
 https://codepen.io/gauini/pen/RwNZoeW

**Comment by alvarotrigo** [comment]
> https://codepen.io/gauini/pen/RwNZoeW

I can't see your code there. Make sure to save the changes.

**Comment by gauini** [comment]
oops sorry about that - saved

**Comment by alvarotrigo** [comment]
You'll need to re-initialise fullPage.js when you change the structure.
Call `fullpage_api.destroy('all')` and then initialise fullpage.js again after the change in the DOM.

**Comment by gauini** [comment]
got it, thanks!
