### ISSUE TITLE
Exclude section from navigation dots

### ISSUE THREAD

**Issue by standerksen** [alvarotrigo/fullPage.js#3851]
Hi!

First of all, great product. I was wondering if it is possible to exclude a certain section from the navigation dots on the side. For example my page has a footer on the bottom, which is a section with `fp-auto-height`. It looks kinda silly to have this footer listed in the navigation dots as it is not a real main section, just a small addition. Is it possible to exclude a single section from the navigation dots?

Cheers!

**Comment by alvarotrigo** [comment]
Fullpage.js doesn't provide any way to do so out of the box.
Is it possible? Probably :) 

The easiest way would be creating your own bullet navigation and assigning to each of  the dots a different `moveTo` function.

**Comment by SNagel** [comment]
Just in case it's a consideration to add such a feature:
i'm currently trying to do the same – exclude the footer from navigation. 
Will do it by just hiding he last dot of the navigation with CSS for now.

**Comment by alvarotrigo** [comment]
Have you considered using CSS to hide the bullet?

See this example:
https://codepen.io/alvarotrigo/pen/oNoMKVR

I just used this CSS for it:
```css
/* Excluding bullet for the last section */
#fp-nav li:nth-child(4){
  display: none;
}
```
