### ISSUE TITLE
An error occurs in 'fullpage.parallax plug-in' when dragging. 

### ISSUE THREAD

**Issue by GronkOut** [alvarotrigo/fullPage.js#3852]
I have purchased and using a 'fullpage.js' license and an additional plug-in.
When I using 'parallax' and 'dragAndMove' plug-ins at the same time, an error occurs when dragging.

Uncaght TypeError: window.fp_dragAndMoveExtension.getCurrentScroll is not a function

'fullpage.js' version at ^3.0.8.
Am I missing something?
Please check error and reply.

**Comment by alvarotrigo** [comment]
Drag and Move is not compatible with Parallax as detailed on the [Parallax demo page](https://alvarotrigo.com/fullPage/extensions/parallax.html) (bottom  left)  

Feel free to [contact us](https://alvarotrigo.com/#contact) if you want a refund for one of those extensions.
