### ISSUE TITLE
Footer doesn't display entirely.

### ISSUE THREAD

**Issue by chilesun** [alvarotrigo/fullPage.js#3855]
### Description
For some unknown reason my half section footer won't display entirely.

### Link to isolated reproduction with no external CSS / JS (there is external JS, CSS, but should not interfere).
https://dev31245.crystal-lagoons.com/pal/ ---> it just won't
https://dev31245.crystal-lagoons.com/ --> it usually works the second time, but not the first time.

### Steps to reproduce it
1. Slide down to the footer (or last section).

**Comment by alvarotrigo** [comment]
Can you pllease provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by chilesun** [comment]
@alvarotrigo it's ok, managed to realize lazy loading of images affected height. Solved.
