### ISSUE TITLE
Navbar on mobile only - webflow

### ISSUE THREAD

**Issue by dropthespark** [alvarotrigo/fullPage.js#3859]
Hi!

I'm trying to deactivate the navbar on mobile devices only, using webflow. Is there something like a "mouseonly" value for navigation or another workaround? 

Thank you so much for your great support!

**Comment by alvarotrigo** [comment]
What do you mean by "navbar"?

**Comment by dropthespark** [comment]
> What do you mean by "navbar"?

Sorry, let me be more specific: The dots on the right side of the screen, as seen here for example: https://alvarotrigo.com/fullPage/

**Comment by alvarotrigo** [comment]
Just use CSS media queries to hide it whenever you  need.
