### ISSUE TITLE
Not Support jquery 1.9.1 ?

### ISSUE THREAD

**Issue by xianghongai** [alvarotrigo/fullPage.js#386]
[ examples  navigationV.html ]
jquery-1.9.1.min.js
jquery-ui-1.9.2.min.js
fullPage 2.0.4
firefox 28

It doesn't work

**Comment by blazblaz** [comment]
I have what seems to be a similar problem (on Windows 7 on Firefox 46.0.1, Chrome 50, Opera 37, IE11). Here's [a simple layout](http://lepagesta.org/example/fullpage/index.html), where the following error is triggered when version is 1.9.1, but not with 1.8.3:
jquery.fullPage.js:2772 Uncaught TypeError: Cannot read property 'wheelOff' of null

Changing jQuery version from 1.9.1 to 1.8.3 version seems to fix the problem, but then Bootstrap doesn't work. [Link to a zip](http://lepagesta.org/example/fullpage/fullpage-example.zip)

I guess one could use alternatives to Bootstrap's js features in this particular case.

**Comment by alvarotrigo** [comment]
@blazblaz update to fullpage.js 2.8.1.
