### ISSUE TITLE
scrollOverflow blocks section scrolling after inner scroll

### ISSUE THREAD

**Issue by lukasztyminski** [alvarotrigo/fullPage.js#3860]
### Description
When I am on section which content is taller than viewport and scrollOverflow is on, scroll inside the section the down is blocked. This bug occurs on sections with plugin isotope.js https://isotope.metafizzy.co/ when items inside the container have position absolute. 
1. **Go to the website http://77studio.projektowaniestron-warszawa.pl/#wielorodzinne**
2. **Scroll on "projekty" and click on"wielorodzinne" or "domy" or "przemysłowe"**
### Link to isolated reproduction with no external CSS / JS
Isolated reproduction: https://jsfiddle.net/0km5d834/9/

### Steps to reproduce it
1. **Go to https://jsfiddle.net/0km5d834/9/**
2. **Scroll on `section__error` down elements not scrolling just like on the my page above**

### Versions 
Tested on version 3.0.8 with latest Chrome nad Firefox on Windows 10 Pro

**Comment by alvarotrigo** [comment]
> when items inside the container have position absolute.

Yeah, that's expected.
FullPage.js has no way to calculate the height of the section when the content is using absolute position.

I would recommend you to make a `position:relative` wrapper around your absoluted positioned elements and set an height for it. That's probably the only way :)

See the related answers:
https://stackoverflow.com/a/42058100/1081396
https://stackoverflow.com/a/1915972/1081396

**Comment by alvarotrigo** [comment]
Oh well, apparently you are not using position:absolute, just a grid element.
You just forgot to add the scrolloverflow.min.js file that is required for the scrollOverflow option.

See your updated fiddle:
https://jsfiddle.net/0v67bznt/1/

**Comment by lukasztyminski** [comment]
> > when items inside the container have position absolute.
> 
> Yeah, that's expected.
> FullPage.js has no way to calculate the height of the section when the content is using absolute position.
> 
> I would recommend you to make a `position:relative` wrapper around your absoluted positioned elements and manually set an height for it. That's probably the only way :)
> 
> See the related answers:
> https://stackoverflow.com/a/42058100/1081396
> https://stackoverflow.com/a/1915972/1081396

Do I create relative div each element of the set in the grid ?

**Comment by alvarotrigo** [comment]
> Do I create relative div each element of the set in the grid ?

No need, see my last answer.

**Comment by lukasztyminski** [comment]
> > Do I create relative div each element of the set in the grid ?
> 
> No need, see my last answer.

Yes, but on my page I using scrolloverflow.min.js 
`<script src="{{theme.link}}/bower_components/fullpage.js/vendors/easings.min.js"></script>
<script src="{{theme.link}}/bower_components/fullpage.js/vendors/scrolloverflow.min.js"></script>
<script src="{{theme.link}}/bower_components/fullpage.js/dist/fullpage.min.js"></script>
<script src="{{theme.link}}/bower_components/fullpage.js/dist/fullpage.extensions.min.js"></script>`
