### ISSUE TITLE
Babel transpiles 'this' to 'undefined' on IIFE

### ISSUE THREAD

**Issue by diegomrv** [alvarotrigo/fullPage.js#3861]
Hello!
So, I started having the `Cannot set property 'fullpage' of undefined` error right after I installed and imported fullpage.js on a project that uses webpack. I did my researchg and found other closed issues about this and started trying many solutions that didn't work.

To check if something on my project was causing this, I started a new empty project with the same webpack config, BUT, I forgot to bring the `.babelrc` file over, so it worked but I didn't know why. After I found out about the missing babel config, I brought it to the new empty project, and then even if I just add this to the `.babelrc` file:

```
{
    "presets": [
        [
            "env", {}
        ]
    ]
}
```
which I believe triggers some default ES2015+ config for Babel, the resulting transpiled code changes `this` to `undefined`.

Uncompiled code:
```
(function( root, window, document, factory, undefined) {
    if( typeof define === 'function' && define.amd ) {
        // AMD. Register as an anonymous module.
        define( function() {
            root.fullpage = factory(window, document);
            return root.fullpage;
        } );
    } else if( typeof exports === 'object' ) {
        // Node. Does not work with strict CommonJS.
        module.exports = factory(window, document);
    } else {
        // Browser globals.
        window.fullpage = factory(window, document);
    }
}(this, window, document, function(window, document)
```
Compiled code:
```
(function (root, window, document, factory, undefined) {
    if (true) {
        // AMD. Register as an anonymous module.
        !(__WEBPACK_AMD_DEFINE_RESULT__ = (function () {
            root.fullpage = factory(window, document);
            return root.fullpage;
        }).call(exports, __webpack_require__, exports, module),
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
    } else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
        // Node. Does not work with strict CommonJS.
        module.exports = factory(window, document);
    } else {
        // Browser globals.
        window.fullpage = factory(window, document);
    }
})(undefined, window, document, function (window, document)...
```

So `root` ends up being undefined and it fails on `root.fullpage = factory(window, document);`. Then I kept looking for anything I could do about this... best explanation I could find was here [https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined-and-inserting-use-str](https://stackoverflow.com/questions/34973442/how-to-stop-babel-from-transpiling-this-to-undefined-and-inserting-use-str) but still, changing Babel sourceType mode to anything different than 'module' is not a solution because then I get an error when I try to do `import fullpage from 'fullpage.js' `

So! Came in here to share my findings in case I'm still missing something, or in case this means there should be a change on how `this` is passed to the function.

### Steps to reproduce it
1. Install fullpage.js, import it on a js file and compile with webpack
2. Add a Babel preset-env config.
3. Success! (I mean, it succeeds to give an error :( )

### Versions 
webpack 3.0.0
fullpage.js 3.0.8
babel-core 6.24.1

**Comment by alvarotrigo** [comment]
I'm not able to reproduce the issue on the [webpack example](https://github.com/alvarotrigo/fullPage.js/tree/master/examples/module_loaders/webpack-example).

I added the `.babelrc` on the `examples/module_loaders/webpack/` folder with the content you suggested:

```js
{
    "presets": [
        [
            "env", {}
        ]
    ]
}
```

Then did `npm run build`.

It compiled correctly and output the `dist/main.js` file.
Opened the `dist/index.html` file and everything works as expected.

**Comment by diegomrv** [comment]
Hey! thanks for the reply!

So, using the webpack example and doing a fresh install of the babel loader and preset packages did the trick!

Took the webpack example, and ran `npm install -D babel-loader @babel/core @babel/preset-env` to install the babel loader for webpack and the preset, configured webpack to use the babel loader for js files... and then it worked fine! 

Just to be sure, I went to my project's package.json and copied the versions of the Babel packages I  was using, and yeah, that reproduced the issue I was having, so the fix was just to update Babel and learned that I shouldn't use old projects package.json as a starting point 😅 

Thank you for your time!

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! :)
