### ISSUE TITLE
scrollOverflow overlapping into next section

### ISSUE THREAD

**Issue by navabase** [alvarotrigo/fullPage.js#3864]
We are working with fullpage.js and the scrollOverflow plugin. When scrolling through the site everything works as expected but when using the navigation the Overflow content is overlapping into the next section.

 Here a JSFiddle link for reproduction: https://jsfiddle.net/johann_su/eyf0bx1L/4/

Steps to reproduce it
1. Click on the third navigation link (3)

**Comment by alvarotrigo** [comment]
Your header should use the css `position:fixed`

**Comment by navabase** [comment]
That doesn't solve the issue. When going onto the third section without scrolling through the scrollOverflow section (section 2) the text from section 2 is overlapping into section 3.
<img width="613" alt="Bildschirmfoto 2020-01-17 um 13 12 05" src="https://user-images.githubusercontent.com/57961618/72611702-119b7880-392b-11ea-9b34-b73a38c624b1.png">

**Comment by alvarotrigo** [comment]
Can you update the fiddle and provide  the reproduction of it?

**Comment by navabase** [comment]
Here is the link: https://jsfiddle.net/johann_su/eyf0bx1L/

**Comment by alvarotrigo** [comment]
You are missing the CSS styles for fullPage.js. Make sure to include them.

**Comment by navabase** [comment]
That solved the issue. Thanks :)
