### ISSUE TITLE
Navigation Dots Size

### ISSUE THREAD

**Issue by welbinator** [alvarotrigo/fullPage.js#3866]
Is there an easy way to increase the size of the dots? I'm having a hard time figuring out the CSS. Would be nice if there was some fullpage option to have small, medium, large, x-large dots or something.

**Comment by alvarotrigo** [comment]
That should be easy to configure through the CSS files directly.
Adding the styling in the fullpage code doesn't seem right for it.

Look for `#fp-nav` (or `.fp-slidesNav` for the horizontal bullets) on the [fullpage.css file](https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.css) and change what you want from it.
