### ISSUE TITLE
Bootstrap 4 columns with fullpage

### ISSUE THREAD

**Issue by MohammadNehru** [alvarotrigo/fullPage.js#3867]
Can't use responsive Bootstrap 4 columns in fullpage js section on mobile.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by MohammadNehru** [comment]
https://codepen.io/mohammed_nehru/pen/oNgQEGy

In section 3 when mobile screen size applied the image column disappear.

**Comment by alvarotrigo** [comment]
Just set `scrollOverflow:true` in the fullPage.js initialisation. 
Bootstrap is placing it underneath the text and creates a content bigger than the viewport.
