### ISSUE TITLE
avoid active section when section is not displayed

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#3868]
Hi Alvaro, I'm trying to make a website in which you only have a second section visible / displayed when you are on the third slide of the first section. Here's a reproduction of it: 
https://codepen.io/gauini/pen/KKwrGYa

I've noticed that if I acidentally scroll down, the html behaves as if the second section is active dispite the fact that it is not displayed. I was wondering if there is a possibility of not allowing the second section to become the active section if someone accidentally scroll down outside of the third slide, because when it happens it kind of freezes any interaction with the first section (which is the one visualized). 

thank you!

**Comment by alvarotrigo** [comment]
At the moment if you plan to add or remove sections dynamically then you'll have to destroy and initialise fullpage.js again.

You can see an example of it in the vue-fullpage.js component:
https://github.com/alvarotrigo/vue-fullpage.js/blob/master/src/FullPage.vue#L17

Hopefully this will get fixed in future versions :)

**Comment by gauini** [comment]
cool, thanks for sending the reference. Could you explain to me a bit of the difference between the destroy() and the rebuild() api calls, and if i can use them separately? I understand that I need to destroy before i initialise it again so that the fullpage adapts to the updated content, but currently i need it to be rebuild on a specific slide within a section..curious to understand if there is a way i could do that. thanks again!

**Comment by alvarotrigo** [comment]
`reBuild` is usually used only to force the correct draw of the scrollbar  in the section when using `scrollOverflow` as pointed out in the docs.

`destroy('all')` leaves the DOM as if fullPage.js was never applied.
