### ISSUE TITLE
Section Heights

### ISSUE THREAD

**Issue by Sjay1881** [alvarotrigo/fullPage.js#3869]
### Problem with Menue in CMS and Slider height

Unfortunatly im not allowed to share the Linke yet but atm I have 2 Problems.

The Script should run in an CMS. That CMS has a Menue at top and a footer at the bottom. The content area inbetween those two holds the complete Side.

1. To avaoid the Menue to be placed over the Content area on top, the Contentarea was Set down from top about the Menues Height. So the Menues Height is missing at the Bottom of every Setction. The Question is can I anyhow reduce the Size of the Sections by the Value that the CMS Menue is Height?

2. On mobile Landscapes I have deactivated the Snapping and Scaling to the Section. To get the Sizes I need for the Sections I have put the Content into a wrapper and gave that wrapper a mindest Height. That worked on most parts of the Side very well. It is just not working on the Slider. Is ther anyway to set a Custom min. Height to the Slider?

Testing here: www.area51.interstate-advertising.de 

Since im not a developer I must say I really like your script and it makes it possible for ppl like me to create nice Websites. Just wanted to say: very good work  :)

**Comment by alvarotrigo** [comment]
>  can I anyhow reduce the Size of the Sections by the Value that the CMS Menue is Height?

Try  using the `paddingTop` option.
However, this is probably related with [this issue](https://github.com/alvarotrigo/fullPage.js/issues/2785) which stills open and doesn't have a proper solution yet.

>  It is just not working on the Slider. Is ther anyway to set a Custom min.

Try using the `fp-auto-height` class as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections).
See [this demo](https://codepen.io/alvarotrigo/pen/MzByMa) on responsive and [this one](https://codepen.io/alvarotrigo/pen/BKjRYm) without responsive.  


> Since im not a developer I must say I really like your script and it makes it possible for ppl like me to create nice Websites. Just wanted to say: very good work :)

Glad to hear you find it useful!! 👍
