### ISSUE TITLE
Overflow content in section : Height: auto, Margin & padding not supported by Fullpage.js ?

### ISSUE THREAD

**Issue by THLCX** [alvarotrigo/fullPage.js#3872]
Hello

I just paid for a license and I encounter a very big problem.
I have sections like this : 

```
	<div class="section">1...</div>
			
	<div class="section">2...</div>
			
	<div class="section">3...</div>
```

The content of sections can be higher than viewport height, so I've set : 

```
			new fullpage('#fullpage', {
				//options here
				licenseKey: 'xxx';
				autoScrolling:true,
				scrollOverflow: true
			});
			fullpage_api.setAllowScrolling(true);
```

The bug is that if I set custom content into sections with elements using variable heights, the elements will overflow over the next section !! (Same problem if any element got margin / padding).

```
<div class="section">
		<img src="test.img" alt="" style="height: auto;" />
<br/>
<img src="tesT.img" alt="" style="width: 80%;height: auto;" />
</div>
```
Test it by yourself, how can I do now ? I've lost so many time trying to figure out a solution ;(

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by THLCX** [comment]
Can I email you the files directly ? Thanks in advance

**Comment by THLCX** [comment]
Okay, I figured out what the bug was : Corrupted .css file. Can you please delete this thread since it was not a bug and out of purpose ? Sorry for the delay and thanks for your reactiveness

**Comment by alvarotrigo** [comment]
No problem! ;)
