### ISSUE TITLE
No swipe on mobile ?

### ISSUE THREAD

**Issue by THLCX** [alvarotrigo/fullPage.js#3873]
Hello

The swipe does not work on mobile (iphone, galaxy, etc...)

### Steps to reproduce it
1. Go to [https://alvarotrigo.com/fullPage/#examples](https://alvarotrigo.com/fullPage/#examples) and try to swipe (firefox mobile mode will also see the problem)

### Versions 
Any mobile touch device without scroll but swipe ;)

**Comment by alvarotrigo** [comment]
The examples overlay you mean?
Working perfectly for  me on my iPhone 11 (Chome, Safari and Firefox)

Also in https://www.browserstack.com/ iphones (Safari and Chrome in iOS and Firefox in Android)

**Comment by alvarotrigo** [comment]
What device are you using?

**Comment by THLCX** [comment]
Okay, got it : I needed to refresh the page to get the touch working
