### ISSUE TITLE
Drag & Drop scrollbar: true

### ISSUE THREAD

**Issue by polimorfestudio** [alvarotrigo/fullPage.js#3876]
Hi!

I bought the Drag & Move extension and tried to create a horizontal drag & move slider. I got everything working but can't trigger webflow's native scroll into view interactions. Can I allow webflow's interactions with the scrollbar: true option as they do with the slides in this example: https://fullpage-js-interactions.webflow.io/. I added the code but the interaction triggers instantly. I think it's because my slides are inside the same wrapper. Is there a workaround method for this integration? I want to drag and move horizontally and trigger webflow's scroll into view interaction as the slide come into view.

Hope you can help me with this one,

Thanks!

**Comment by alvarotrigo** [comment]
Try using the option `css3:false`.
If you are using `scrollBar:true` that'd be irrelevant for the vertical scroll but will change the way horizontal scroll works, so this way you might be able to detect the horizontal scroll.

**Comment by polimorfestudio** [comment]
Tried that, but didn't work.

Curiously, if I use the drag & move extension with vertical Fullpage.js, Webflow's interactions works. Check this example: https://alemans-stellar-project.webflow.io/

I'm trying to achieve exactly that, but horizontally. I.E drag horizontally but scroll vertically.

Any idea?

**Comment by alvarotrigo** [comment]
> I'm trying to achieve exactly that, but horizontally. I.E drag horizontally but scroll vertically.

Post the link with the page containing horizontal slides.

**Comment by polimorfestudio** [comment]
Here is an example: https://alemans-beautiful-project-1eb1b6.webflow.io/

**Comment by alvarotrigo** [comment]
I don't know how webflow monitors it, but you'll have to base your animations  on the `scrollLeft` property of the `.fp-slides` element.
