### ISSUE TITLE
scrollOverflow: true + menu

### ISSUE THREAD

**Issue by oleh-khalin** [alvarotrigo/fullPage.js#3877]
When I'm using scrollOverflow: true and menu links, the scroll inside scrolled sections are at the start point, how can I avoid it?

I mean how to make the start point of scrolling in the end? I've done it with transform however the scrollbar is always at the top point

**Comment by alvarotrigo** [comment]
You mean.

When accessing through the menu, let's say, to section 3, you want then when you scroll to section 2 (that contains scrollOverflow) to be scrolled at the end?

That's currently no provided by fullPage.js. 
But I'll keep this issue open for future review as a possible enhancement!

**Comment by oleh-khalin** [comment]
@alvarotrigo yeah, thank you

And another question
How can I like rebuild the scroll inside section? I have resized elements like drop down items and them change blocks' heights

**Comment by alvarotrigo** [comment]
Read about the `reBuild` method in the docs.

**Comment by alvarotrigo** [comment]
This will not be implemented by fullPage.js
However, it can easily be done by using callbacks and JS to scroll to the bottom of the scrollable section.
