### ISSUE TITLE
Scroll and Navigation issue

### ISSUE THREAD

**Issue by kp1007** [alvarotrigo/fullPage.js#3878]
https://codepen.io/alvarotrigo/pen/qqabrp

on this example if I set these two values in fullpage

bigSectionsDestination: ".section",
normalScrollElements: '.section',

So, it looks like
new fullpage('#fullpage', { sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'], bigSectionsDestination: ".section", normalScrollElements: '.section', navigation: true, });

because my section size is more then viewport and I also want to scroll on it and also navigation: true, then navigation using mouse wheel  is not working

**Comment by alvarotrigo** [comment]
> because my section size is more then viewport and I also want to scroll on it and also navigation: true, then navigation using mouse wheel is not working

Use `scrollOverflow:true` instead.
You can't apply normalScrollElements to the section as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js):

> **normalScrollElements:** (default null) Demo If you want to avoid the auto scroll when scrolling over some elements, this is the option you need to use. (useful for maps, scrolling divs etc.) It requires a string with the Javascript selectors for those elements. (For example: normalScrollElements: '#element1, .element2'). **This option should not be applied to any section/slide element itself.**
