### ISSUE TITLE
Advice / Mobile with nav but not full height?

### ISSUE THREAD

**Issue by gsc89** [alvarotrigo/fullPage.js#3879]
### Description

I am supporting a website using this script (developer wasn't me) but I have been asked to look at making it so that it behaves differently on mobile and based off the options you have and the ones I have tried this is not going to happen. 

https://gregoryphillips.com/

This site has 2 types of section on desktop half text half image, and full images, this is fine on desktop but on mobile it cuts off to much of the left / right of the single full size images and they would like on mobile for the full images to just take max width instead of max height. 

I have tried some of the responsive options but they only seem to remove the navigation and do not stop the slides being looped over and set to full widow height, and they would like to keep the nav anyway and just resize the images under a certain width. 

Can you confirm doing what they want is possible or if its out with the scope of using this script?

**Comment by alvarotrigo** [comment]
Yeap, totally possible :)

You can use the option `fp-auto-height-responsive` as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#responsive-auto-height-sections).

Demo:
https://codepen.io/alvarotrigo/pen/MzByMa

Demo 2:
https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html

**Comment by gsc89** [comment]
Hi @alvarotrigo 

This doesn't work as I have detailed sorry of I confused somthing here.

However using: 

responsiveHeight
responsiveWidth

Mean that the fullpage nav no longer appears under the sizes set, they still want the navigation to show when under the width / height set. 

When I use either of these it removes the nav.

See: https://codepen.io/gsc89/pen/YzPozyV

**Comment by alvarotrigo** [comment]
You can make the navigation visible again by just using CSS. 
Use:

```css
#fp-nav{
    display: block !important;
}
```
