### ISSUE TITLE
IE 11 fullpage.js anchor issue

### ISSUE THREAD

**Issue by EllisCrowther** [alvarotrigo/fullPage.js#3881]
### Description
There seems to be an issue when resizing the window specifically in Internet Explorer.

The issue is that none of the links, which are set up using the data-anchors as set up in my main.js file, work when the window is resized and I can't figure out why.

They're all lowercase, both in the href value and in the data-anchor of each section, and the site seems to be working absolutely fine on Chrome, Firefox, Edge and Safari so as far as I can see the issue can be isolated to IE.

Would you be able to help with this?

### Link to isolated reproduction with no external CSS / JS
http://andrewdavisllp.devserver3.co.uk/

### Steps to reproduce it
1. Open in IE
2. Resize window

### Versions 
IE 11

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in in a test page with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
