### ISSUE TITLE
using fullPage.js on Elementor at mobile devices

### ISSUE THREAD

**Issue by betzebu** [alvarotrigo/fullPage.js#3884]
Hi all, 

I want to use fullPage.js with Elementor & Wordpress. On Desktop its running fine. I used this tutorial: https://www.youtube.com/watch?v=CDTsVrajj-Y&t=37s

My problem is that I cant use the scroll effect on mobile devices. It worked not at a small browser window size, and also not on my iPhone 7. 
1. Problem is, that I cant set the elementor section to full height. 
2. Problem is, that it seems the js is not activated on this windows size.

I cant isolate the code, because Im using Wordpress & Elementor. 

### Steps to reproduce it
1. Go to http://dev.dein-boom.de/ with mobile device or resize your browser window
2. Scroll

**Comment by alvarotrigo** [comment]
Unfortunately we only provide support for our [fullpage plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) or the fullPage.js Javascript library itself. 

I can only recommend you to contact the author of that tutorial.
