### ISSUE TITLE
QUESTION: change list of normalScrollElements

### ISSUE THREAD

**Issue by Demonstr8** [alvarotrigo/fullPage.js#3885]
How can i change list of normalScrollElements when i need?
Init:

```
var options = {
....
....
normalScrollElements: '#one, #two',
...
}
```
`var fullpagejs = new fullpage("#fullpage", options)`
After some time i need to change `normalScrollElements` in options to `'#one, #three, #four'`

**Comment by alvarotrigo** [comment]
You can access the list with:

```
fullpage_api.getFullpageData().options.normalScrollElements
```
