### ISSUE TITLE
Fullpage.js scrolling inside section with MixItUp plugin

### ISSUE THREAD

**Issue by slobo-sole** [alvarotrigo/fullPage.js#3886]
Hi hi,

I am trying to run MixItUp under Fullpage.js in order to avoid the standard side scrolling for all the images I have under my filters. You can see that is possible to achieve in the link below, however when I do it then MixItUp filtering does not work anymore:

http://raddar.pro/projects_12.html

I have contacted Fullpage.js and they have told me to Try initializing MixItUp in the afterRender callback of fullpage.js, because fullPage.js modifies the DOM it's better to do any initialization that depends on it in the callback. Below is what I wrote

afterRender:  function () {		
		var filterList = {init: function () {
			// MixItUp plugin
			// http://mixitup.io
			$('#portfoliolist').mixItUp({
				selectors: {
					target: '.portfolio',
					filter: '.filter'	
					},
				load: {
					filter: '.architecture, .interiordesign, .urbandesign, .development, .art, .branding, .raddar' // show app tab on first load
					}     
				});								
			}
		};
		// Run the show!
		filterList.init();
	},	

Hope you can help me, many thanks!!!

**Comment by alvarotrigo** [comment]
I believe this issue got solved.
