### ISSUE TITLE
Sections being skipped when using fadingEffect extention

### ISSUE THREAD

**Issue by lukemoody** [alvarotrigo/fullPage.js#3891]
Hi,

We are using Fullpage.js with the fadingEffect extenuation. Once a user has scrolled through all available slides we have set it to 'unlock' so that the rest of the page and be scrolled through as normal. Scrolling down works as expected as does clicking the navigation pips to go directly to a section. The issue we are facing is when a user scrolls back up to the top of the page and into the slider, the transition to the next slide skips a section (e.g. goes from slide 3 to 1, missing out 2). The same issue then occurs when a user scrolls back down.

A class is added to override styles added to html and body tags to allow the user to scroll back into the last slide fully before using the 'onLeave' function to remove the class to use default styles again. Using both fullpage_api.setAutoScrolling(false); and fullpage_api.setAllowScrolling(true); together is the only way to re-allow scrolling from the first slide again as without you cannot scroll. I'm not sure if I am using this correctly based on examples seen online.

If I deactivate the fadeEffect option to initiate normal scrolling, then the effect functions as expected. 

I am unable to provide a link as the site is local at the moment, but here is the code were using currently: https://jsfiddle.net/t28bwjzf/1/

Are you able to point me in the direction of why sections are being skipped? and also if the way we are trying to achieve the effect is correct?

We are using the latest versions for both fullpage.js and extension.

Thanks

**Comment by alvarotrigo** [comment]
Your jsfiddle is not working at all.
![image](https://user-images.githubusercontent.com/1706326/74164930-b35d6f00-4c24-11ea-8286-adef39c843c6.png)

**Comment by lukemoody** [comment]
> Your jsfiddle is not working at all.
> ![image](https://user-images.githubusercontent.com/1706326/74164930-b35d6f00-4c24-11ea-8286-adef39c843c6.png)

Sorry I forgot to add a link to fullpage.extensions.min.js. I can't add the file for the extension itself.

Thanks,

**Comment by alvarotrigo** [comment]
The issue seems to be in the code you are using in the callbacks and not in fullPage.js or the extension itself. Try removing it to test it out.

**Comment by lukemoody** [comment]
> The issue seems to be in the code you are using in the callbacks and not in fullPage.js or the extension itself. Try removing it to test it out.

As mentioned previously, from testing already undertaken the issue only occurs when `fadeEffect: true` is set:

**The required effect works with the following configuration:**

1) fullpage.extensions.min.js
2)  `fadeEffect: false`
3) my code as written in fiddle

When scrolling through slider, each section changes (but without the fade effect from the paid extension). Once the user reaches last slide, it unlocks to allow the user to scroll the rest of the page. When scrolling back up through the slider, the slider locks back in place when user transitions from last to next slide. Then the user can use the slider as expected.

**The required effect doesn't work with the following configuration:**

1) fullpage.extensions.min.js
2)  `fadeEffect: true`
3) my code as written in fiddle

When scrolling through slider, each section changes (with fade effect). Once the user reaches last slide, it unlocks to allow the user to scroll the rest of the page. When scrolling back up through the slider however, the slider locks back in place when user transitions from last to next slide it jumps the next slide and goes directly to the first section. The same issue occurs when scrolling back down through the slider, it skips the next section and goes directly to the last.

As there are no errors to use to troubleshoot, i'm looking for assistance as the issue occurs when the paid extension is activated.

Thank you for your assistance.

**Comment by alvarotrigo** [comment]
I would recommend you to make use of the `fullpage_api.fadingEffect.turnOn();` and `fullpage_api.fadingEffect.turnOff` methods before calling `setAutoScrolling`.

Fading effect extension is not supposed to be used with `autoScrolling:false` as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

Disable the fading effect extension first and see if that do the trick.
However, you are kind of playing with the system here, so I can't assure you there's a good solution for it.

There's a reason why this isn't a feature yet ;)

**Comment by lukemoody** [comment]
> I would recommend you to make use of the `fullpage_api.fadingEffect.turnOn();` and `fullpage_api.fadingEffect.turnOff` methods before calling `setAutoScrolling`.
> 
> Fading effect extension is not supposed to be used with `autoScrolling:false` as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
> 
> Disable the fading effect extension first and see if that do the trick.
> However, you are kind of playing with the system here, so I can't assure you there's a good solution for it.
> 
> There's a reason why this isn't a feature yet ;)

Managed to achieve the effect we needed using a combination of `fullpage_api.fadingEffect.turnOn();` and `fullpage_api.fadingEffect.turnOff();` in separate timeOut function upon scrolling back up to the first slide. Bit of a dirty fix, but works : )

The only slight issue remaining is that when scrolling back into the slider, it jumps directly from the last slide to the first (skipping middle completely).
