### ISSUE TITLE
scrollOverflowReset not working on mobile

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#3892]
hi Alvaro,

I'm on the final steps of implementing a website for a project, and i've setup to have a responsiveWidth and to have scrollOverflowReset (which I purchased and activated). For some reason, when I click through the menu to go to a section it's not doing the reset - so I'm wondering if scrollOverflowReset works on responsive more.
Here's the website: http://www.rotawear.com/
thanks!

**Comment by alvarotrigo** [comment]
> and i've setup to have a responsiveWidth and to have scrollOverflowReset

That's not how it works. 
You just need to use `scrollOverflow:true` to use `scrollOverflowReset:true`. You don't need the responsive options at all. 

Just remove the responsive options and you'll have it working.

The responsive options is just to disable autoScrolling and even the restriction of having a section that have to be the same height as the viewport.
You have more info about this on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
