### ISSUE TITLE
Background video play only the first time. 

### ISSUE THREAD

**Issue by nicolabortignon** [alvarotrigo/fullPage.js#3893]
What would be the best way to make sure that a background video on a slide plays only one time.
This includes when you are going back to the slide hosting the video.

I was thinking to remove any autoplay,
listen to the event when the slide is first render (not sure which one it is), play the video only if a global variable is set to true, change the global variable to false.

Any other options?

**Comment by alvarotrigo** [comment]
Add and remove the data-autoplay featured based on your global variable 😉

**Comment by nicolabortignon** [comment]
For future reference:
```
onLeave: function(item){
            var introVideo = document.getElementById('introVideo');
            if(item.index == 0){ //the index of the slide where I want the video to stop
                if(introVideo.hasAttribute('data-autoplay') && introVideo.ended){ // I don't want to stop it if is not finished, or if I already removed the data-autoplay. 
                    introVideo.removeAttribute('data-autoplay');
                 }
            }
        }


There is one thing that still doesn't seem to be very smooth. When re-entering the slide with the video, while the video has not finished yet, there is a 1 second delay where you cannot see the video progressive (still frame) and after that second it jumps to the correct frame and continue playing 



![Untitled 2](https://user-images.githubusercontent.com/883459/74591594-06626800-5011-11ea-8d5c-e9ba6414fa97.gif)

**Comment by alvarotrigo** [comment]
Any reproduction in jsfiddle or codepen we can see?

**Comment by nicolabortignon** [comment]
Do you have a boilerplate on either of the two platform that I can start with.
I'd be very happy to create a reproducible example

**Comment by alvarotrigo** [comment]
[jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp)

**Comment by nicolabortignon** [comment]
Thank you @alvarotrigo 

Here the example: https://jsfiddle.net/qmnc3srf/2/
If you scroll up and down between the first and the second slide, you'll see that there is a bit of lag and a skip of frames. 
(I'm testing with Chrome on OSX)

**Comment by alvarotrigo** [comment]
Weird :)
Don't think there's much we can do there.

The video starts playing after the section loads. Then it depends on the browser how fast it wants to play the video after giving him the order I guess.

**Comment by nicolabortignon** [comment]
The bug here is that the rendering of the video skips some frames.
In Safari and Mozilla (same machine, OSX), the problem doesn't manifest. I'll try to see what the chromium community thinks

Thanks
