### ISSUE TITLE
[bug] Anchornames of Navigation appearing in vertical screenreader-span elements

### ISSUE THREAD

**Issue by dstN** [alvarotrigo/fullPage.js#3898]
Talking about this issue: [https://github.com/alvarotrigo/vue-fullpage.js/issues/158](https://github.com/alvarotrigo/vue-fullpage.js/issues/158)

You can also see this behaviour on the mainsite: https://alvarotrigo.com/fullPage/#page2

Check the dev-tools on the bullet-points for the vertical navigation and see this:

![image](https://user-images.githubusercontent.com/960879/75139482-0804ed80-56ed-11ea-8e0d-0887c08425ec.png)

You can see the `<span class="fp-sr-only">`-Tags having content from the navigationTooltip-Setting

In my environment the sr-only Tags get the content from the anchors-Setting:

![image](https://user-images.githubusercontent.com/960879/75139667-7cd82780-56ed-11ea-99de-7204c0373d07.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
We will definitely fix it for the next release!

**Comment by alvarotrigo** [comment]
Fixed on dev!

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
