### ISSUE TITLE
different slide count for mobile and desktop; anchor scrolling issue 

### ISSUE THREAD

**Issue by rudeone** [alvarotrigo/fullPage.js#3899]
### Description
on this page:
https://mavorswenera.com/stories

i have 3 slides for mobile layout but only need 2 for desktop layout. ive hidden the second unwanted slide on desktopvia "display none" which works fine.

unfortunatly when scrolling through the slides via mouse it still recognizes the hidden slide, so i have to scroll twice on the very first slide. (which might be a minor thing but could confuse the user)

any suggestion how i can do this?

i havent done an isolated codepen because its not a conflict issue or any of that sort.
its more like a general question or feature request
i can do if needed though.

**Comment by alvarotrigo** [comment]
Not a proper solutions so far.
The issue was treated before, see this [open topic](https://github.com/alvarotrigo/fullPage.js/issues/2098).

Closed as duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2098
