### ISSUE TITLE
Autoplay Slider Fullpage.js

### ISSUE THREAD

**Issue by canadaunique** [alvarotrigo/fullPage.js#3900]
Hey guys,

can someone give me a documentation how to enable autoslide on fullpage sliders on wordpress. Autoslide should start, when the sectionslider is active.

This does not help me enough:

https://github.com/alvarotrigo/fullPage.js/issues/532

Thanks for your help!

regards

**Comment by alvarotrigo** [comment]
What Wordpress plugin are you using? [Gutengerg plugin](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/)? [Elementor plugin](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/)?

**Comment by canadaunique** [comment]
I work with Gutenberg.

**Comment by alvarotrigo** [comment]
Easy then:

Click on "fullpage.js for Gutenberg"

![image](https://user-images.githubusercontent.com/1706326/75158339-2f23e500-5716-11ea-81c1-9c79e07995c9.png)

Open Events on the right menu:
![image](https://user-images.githubusercontent.com/1706326/75158376-3d720100-5716-11ea-827e-eed762d2de88.png)

Click on "afterRender Event Javascript":
Paste this:


```js
setInterval(function () {
    fullpage:api.moveSectionDown();
}, 1500);
```

1500 is the value in milliseconds for the interval. Which is 1.5 seconds.
You an adapt this as you want.

**Comment by canadaunique** [comment]
moveSlideRight() it was actually =) But Thanks a lot!!!!
