### ISSUE TITLE
Invalid Licence Key

### ISSUE THREAD

**Issue by raminrabie** [alvarotrigo/fullPage.js#3908]
Hi
I have purchased a license for fullpage.js but when i go to activate extensions on link below, it show that my license is not valid.
https://alvarotrigo.com/fullPage/extensions/activationKey.html

**Comment by alvarotrigo** [comment]
You don't need to generate any activation key for fullpage.js itself, only for the extensions.

**Comment by raminrabie** [comment]
You mean I should still buy extra license for extensions in addition to the license I bought for fullage.js?

**Comment by alvarotrigo** [comment]
Exactly, as detailed in the pricing page faqs extensions are sold separately: 
https://alvarotrigo.com/fullPage/pricing/#faq

**Comment by raminrabie** [comment]
ok, thanks

**Comment by preston-method** [comment]
Hi I am having the same issue. The paid license for a plugin is not working. Sent email.
