### ISSUE TITLE
Problem with ScrollOverflow and AutoScrolling on mobile

### ISSUE THREAD

**Issue by Riggd** [alvarotrigo/fullPage.js#391]
I was unable to find the issue again, though I swore it was stated somewhere,

However I am trying to disable the autoscroll process for mobile and the website just just have normalScroll. I have tried a different combination of many things, and I either get 2 scroll bars (the normal kind), Or a scrollOverflow scroll bar per section and then the scroll bar for the whole height of the website. 

I am setting my mobile / desktop fullpage as such:

```
var isPhoneDevice = "ontouchstart" in document.documentElement; 
$(document).ready(function() {
    var isMobile = window.matchMedia("only screen and (max-width: 760px)");
    if (isMobile.matches) {
        $('#fullpage').fullpage ({
            autoScrolling:false,
            resize:false
        });     
    }
    else {
        $('#fullpage').fullpage({
            navigation: true,
            navigationPosition: 'right',
            navigationTooltips: ['Heim', 'Konzept', 'Service', 'Software', 'Firma'],
            scrollOverflow: true,
            scrollingSpeed: 1250,
            resize: false,
            touchSensitivity: 10,
            css3: true 
        });
    }
});
```

**Comment by rijosh** [comment]
i want disable all features in mobile devices. is there any way?
the problem is section scroll in mobile devices. that is not equal of normal scroll. the problem is only in mobile... help me pls

**Comment by alvarotrigo** [comment]
> i want disable all features in mobile devices. is there any way?

See the destroy functions in the docs.
Also check the responsive options.

**Comment by ideaenvy** [comment]
Am followed the same scenario in mobile devices its coming as much as finely but the new problem raised in my site.
While using the var isMobile = window.matchMedia("only screen and (max-width: 760px)"); that page's normal anchor tags are not working.
