### ISSUE TITLE
Skip section if auto height = 0

### ISSUE THREAD

**Issue by BELVOIRSTUDIOROSS** [alvarotrigo/fullPage.js#3910]
Hello,

I was wondering if I might be able to trouble you with a query I had in regards to how to skip a section if the height = 0? I'm using webflow to build my site and for some projects there will, in some cases, be a variable number of images depending on the project. I have allowed for a maximum number of images to be 10. For the projects that have fewer than 10 images I have set the redundant gallery sections to auto height so that you don't get a blank section. However, the sections that are blank still require a scroll action in order to navigate further down the page. For example, with a project that has 5 gallery sections, it will still require an additional 5 scrolling actions to reach the site footer. I hope that makes sense? Is there a way to disable the scroll if a section has no auto height? 

The code I have in the page body is as follows,

<script type="text/javascript" src="https://unpkg.com/fullpage.js/dist/fullpage.min.js"></script>

<script>
   // fullpage.js initialization
   new fullpage('#fullpage', {
   	  scrollingSpeed: 1000,
         	  verticalCentered: false,
            paddingTop: '10vh',
   });
</script> 

The link to the site is https://arabella-lennox-boyd.webflow.io/projects-public-gardens/natus
As you can see on the last full screen image at the bottom, you still have to perform a scroll action that doesn't trigger the scroll so you have to perform the same action twice.  

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
