### ISSUE TITLE
options padding-left and padding-right for class slideContainer

### ISSUE THREAD

**Issue by benjaminpreiss** [alvarotrigo/fullPage.js#3911]
### I would like to add padding-left and padding-right options

I just had a project where I wanted to use fullpage.js and I thought it would be quite useful to have the options `paddingLeft` and `paddingRight` for fullpage!
I do not want to add a padding to each slide. Instead I would like the first slide to have padding-left and the last slide to have padding-right

I think I found a smooth way to do it... Can I make a PR?

**Comment by alvarotrigo** [comment]
Sounds like a CSS solution? 
Why should this be integrated in fullPage.js?

**Comment by benjaminpreiss** [comment]
Yes, you are absolutely right.
Isn't the same true for paddingTop and paddingBottom?
