### ISSUE TITLE
custom-width slides via --c-width and custom viewport alignment via --c-align

### ISSUE THREAD

**Issue by benjaminpreiss** [alvarotrigo/fullPage.js#3912]
### I would like to add custom slide width and custom viewport alignment for slides

I think it would be cool if one could define a custom width for each slide and define how it should be aligned with the viewport, when scrolling horizontally.

when responsive mode is triggered and the screen is smaller than the threshold the slides would get back 100% width.

I found a solution to do this with --c-width and --c-align custom css declarations.

May I make a PR?

**Comment by alvarotrigo** [comment]
Someone suggested it time ago as well. see [this open issue](https://github.com/alvarotrigo/fullPage.js/issues/2510).

However it is not yet possible. 

> I found a solution to do this with --c-width and --c-align custom css declarations.
> May I make a PR?

Feel free to demo it so we can take a look at it.

**Comment by alvarotrigo** [comment]
I'll close this issue as a duplicate. Please feel free to follow up the conversation in https://github.com/alvarotrigo/fullPage.js/issues/2510
