### ISSUE TITLE
Change Log improvement

### ISSUE THREAD

**Issue by PythonLinks** [alvarotrigo/fullPage.js#3914]
### Description
First of all thank you for this awesome library. 

I had smart develoeprs tell me they did not know you could do this on the web. 

I just had a bug.  So I figured upgrade to the current commercial version.  That fixed the problem.  Thank you.  But it was way way harder than it should have been. 
You changed the api for onLeave and onSlideLeave. 
Took quite a while to chase it down.  I even read the change log, but did not see a mention that the api had changed. 

You may want to flag api changes in the change log, in large letters.  That would have been most helpful. 

Have a great day. 

### Versions 
2.7.8 to current version.

**Comment by alvarotrigo** [comment]
Major versions means major breaking changes. 
From 2.8.8 to 3.0.8 there's a major change of version, so you should always expect breaking changes. 

Bean in mind 2.8.8 was released 2 years and a half ago :) 

It is usually as easy as taking a look at the docs to realise why callbacks fail:
https://github.com/alvarotrigo/fullPage.js#callbacks

I appreciate the suggestion but after 2 years I don't think it is the right moment to add warning anywhere :)
