### ISSUE TITLE
fp-auto-height and vertical center when scrolling (up or down)

### ISSUE THREAD

**Issue by enzorevo** [alvarotrigo/fullPage.js#3916]
Hi, I'm trying to use your script in order to realize this attached image effect.
![Schermata 2020-03-06 alle 16](https://user-images.githubusercontent.com/49289823/76100122-72127200-5fcc-11ea-8cff-30a49d4e40a7.png)

Basically, I'm using the fp-auto-height option in order to realize the effect. The problem is I would like to give a preview of both the upper and the lower sections. The text that is on the top and on the bottom of the section would then appear after the new section is scrolled, and therefore the previews should regards the image and not the relative text. I hope everything is clear, otherwise tell me.

Is there any way to realize it using your script? I'm struggling since a week and I still cannot find a good solution.

Thank you very much in advance,

L

**Comment by alvarotrigo** [comment]
Sorry I don't know what you mean. 
If you can add a video or a link with a page with the same effect, that'd be great.

**Comment by enzorevo** [comment]
Hi Alvaro, there is a gif that should explain it properly.
![gif page](https://user-images.githubusercontent.com/49289823/76147937-ae63d200-60a1-11ea-9614-b78ada9ecab3.gif)
Let me know if you need anything other.

Thank you

Lorenzo

**Comment by alvarotrigo** [comment]
That's a matter of CSS. I would encourage you to ask in other places such as stackoverflow.com
