### ISSUE TITLE
Making navigation inside first slide with css3: true

### ISSUE THREAD

**Issue by mxnvkv** [alvarotrigo/fullPage.js#3919]
### Making navigation inside first slide with css3: true

Is it possible to make menu with anchors inside the first slide with `css3: true`? The thing is, that when `css3: false`, website starts working extremely slow. But what should I do, if I need menu **only** inside the first anchor / slide ?

**Comment by alvarotrigo** [comment]
Why not placing the menu outside the fullpage.js wrapper?
Will it be fixed?

**Comment by mxnvkv** [comment]
Unfortunately, it has to be only inside the first slide
I can place menu outside the fullpage.js wrapper, but do you know how to make it only inside first slide?
Or, maybe, can I create four separate links and make them look like its menu?

**Comment by alvarotrigo** [comment]
> Or, maybe, can I create four separate links and make them look like its menu?

You can probably do that. Then just use the `fullpage_api.moveTo` method to link them with sections or slides. 

> I can place menu outside the fullpage.js wrapper, but do you know how to make it only inside first slide?

You could do that  as well, you can hide it using fullpage callbacks or state classes. You can read more about them in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

**Comment by mxnvkv** [comment]
Thanks a lot!
