### ISSUE TITLE
fullpane has a very uncomfortable UI

### ISSUE THREAD

**Issue by Vnthf** [alvarotrigo/fullPage.js#3920]
Hello.
I purchased fullpane which is a wordpress theme a few days ago.
There are some inconveniences, and there is no place to say because no mail address is written anywhere on the site.

The fullpane is a very inconvenient structure to customize.
I cannot add a column inside a column. I have only one row and one column in one page. There is no way to add sub-column and sub-row.

I cannot move the position of the text or box. I want to put the text on top, but it's in always the middle.

I cannot remove the margin between blocks. I do not understand this way.
between orange line
![image](https://user-images.githubusercontent.com/6292309/76428026-7980b380-63f0-11ea-97fa-476d21502401.png)

If I don't know how to do that, I would like to have a guide.
I will remove this issue when contacted.

**Comment by alvarotrigo** [comment]
fullpane has nothing to do with this repository, itt is a third party theme that we link from the page, but that is build but someone else. 

I would recommend you to take a look at the plugins we provide [for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) editors for Wordpress.
