### ISSUE TITLE
scrollOverflow doesn't seem to work

### ISSUE THREAD

**Issue by oguilleux** [alvarotrigo/fullPage.js#3921]
I've tried to get scrollOverflow to work but it doesn't seem to. 

I have two problems : 
- I can't scroll back to top
- the second section is not scrollable and it should be

Here is an isolated page of my problem :  https://codepen.io/olig/pen/GRJQQLp

Thanks a lot for your help !

fullpage.js v3.0.8
Mac os x 10.15.3
chrome 80 - Firefox 74 - Safari 13

**Comment by alvarotrigo** [comment]
ScrollOverflow is not actually compatible with the option `scrollBar:true`.
There's a warning in your JS console about it, although it should be improved with the `scrollBar` option too :)

> fullPage: Options scrollBar:true and autoScrolling:false are mutually exclusive with scrollOverflow:true. Sections with scrollOverflow might not work well in Firefox

**Comment by oguilleux** [comment]
Ok sure. So I deleted the `scrollBar:true` parameter. It still doesn't work unfortunately : https://codepen.io/olig/pen/GRJQQLp

**Comment by alvarotrigo** [comment]
Too much CSS to inspect. 
Can you please reduce the issue to the bear minimum?

Can be your text is absoluted position, maybe the fact that is `flex`? can't really tell yet.
Start removing CSS until the problem goes out, this way we can localise it better.

**Comment by oguilleux** [comment]
You're right it seems to come from CSS. Thanks for having taken the time to help debug this.
