### ISSUE TITLE
Getting scrollOverflow scroll events in sections

### ISSUE THREAD

**Issue by oguilleux** [alvarotrigo/fullPage.js#3922]
Hello,

I read your solution provided on [stackoverflow](https://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl/39369282#39369282) using iscroll-probe and tried to implent it but it doesn't work.

Is it still in version 3 or has it been removed ?

Check out my codepen here : https://codepen.io/olig/pen/eYNVozY

Again, thanks for your help.

**Comment by alvarotrigo** [comment]
That's an old answer for fullpage.js version 2. You would have to update the code for version 3 on the `afterLoad`  besides having to modify iScroll probe. 

Not something we provide support with unfortunately.
