### ISSUE TITLE
Issues with scaling on desktop

### ISSUE THREAD

**Issue by LewisScott94** [alvarotrigo/fullPage.js#3923]
### Description
Using the Elementor WP plugin, I've run into problems getting the content to scale (and therefore stay on screen) when the Windows Scaling setting is set to 125% or 150%.

Also, fullpage turns off on Chrome at 150% scaling but stays activated on Edge, is there a way of forcing it to be activated on chrome?

Not an issue with mobile, that's what people usually go on about when referencing scaling, we just have it set to turn off at <600px . 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

https://aeonomega.com/products/complete-solution/    --- unable to get a reproduction working, but scroll down 3 times and it's that page that's affected

### Steps to reproduce it
1. [First step]

Display settings

2. [Second step]

Scaling (text, apps, etc) = 150%

3. [and so on...]

Check 4th page on https://aeonomega.com/products/complete-solution/

### Versions 
[Browser, operating system, device, ...]

Edge

Chrome

**Comment by alvarotrigo** [comment]
> https://aeonomega.com/products/complete-solution/ --- unable to get a reproduction working, but scroll down 3 times and it's that page that's affected

Your link doesn't contain any reproduction now.

Can you please provide an isolated reproduction with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
