### ISSUE TITLE
Mixed Javascript & CSS Vertical Centering of #fp-nav

### ISSUE THREAD

**Issue by alanalvarado** [alvarotrigo/fullPage.js#3925]
I have been checking the fullpage.js code and I noticed it centers #fp-nav vertically by using javascript combined with css

on the CSS we have

```
#fp-nav {
margin-top: -32px;
top: 50%
}
```
and then in the javascript
```
//centering it vertically
css($(SECTION_NAV_SEL), {'margin-top': '-' + ($(SECTION_NAV_SEL)[0].offsetHeight/2) + 'px'});
```

wouldn't it be better to just use a 2D transform?

```
#fp-nav {
top: 50%
transform: translateY(-50%)
}
```

In this way one would not have to override too much css to move the navigation with callbacks

According to www.caniuse.com 2D transforms are available from ie9

**Comment by alvarotrigo** [comment]
Totally agree :)
Please feel free to open a pull request on the dev branch with the changes and I'll merge it!  👍

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
