### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by line49** [alvarotrigo/fullPage.js#3926]
### Description

This is not a technical bug, other than we can't get our paid licenses to work. Trying to get support.

### Steps to reproduce it

See emails to alvaro@alvarotrigo.com from dave@line49.ca

**Comment by alvarotrigo** [comment]
Answered by email.

**Comment by preston-method** [comment]
Hi I am having the same issue. The paid license for a plugin is not working. Sent email.
