### ISSUE TITLE
Number of current slide/total number of slides

### ISSUE THREAD

**Issue by kreativstau** [alvarotrigo/fullPage.js#3928]
Hello,

is there a way to show the "number of current slide" and the "total number of slides", e.g. **Slide 1/of 12**?

Thanks!

**Comment by alvarotrigo** [comment]
Sure!
Google exactly your same question and you'll find many answers there :)

(Probably has been answered in this forum too)

https://www.google.com/search?q=Number+of+current+slide%2Ftotal+number+of+slides+fullpage&oq=Number+of+current+slide%2Ftotal+number+of+slides+fullpage&aqs=chrome..69i57j69i60l2j69i61.910j0j7&sourceid=chrome&ie=UTF-8

**Comment by alvarotrigo** [comment]
For the number of slides or sections you can just use jquery:

```js
var numSections = document.querySelectorAll('.fp-sections').length;
```
