### ISSUE TITLE
Will this library have issue with one page website?

### ISSUE THREAD

**Issue by wv1317bq** [alvarotrigo/fullPage.js#3929]
### Description
I have implemented this library in one page website. vertical anchor menus are working fine. Will i have further issue with since page is not full page website?

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
I don't see why it would :)
