### ISSUE TITLE
import extension as module 

### ISSUE THREAD

**Issue by ametthey** [alvarotrigo/fullPage.js#3932]
### Trying to import fullpage.extension.min.js from node_modules

Hello, I'm setting up a new environnement with gulp from creating a Wordpress Theme.

I'm trying to add fullpage.extension.min.js because I want to use the extension offsetSections that I bought.

before that, I implement the plugin fullpage.js easily with 

**import fullpage from 'fullpage.js'** from my node_modules folder after the command:
npm install --save fullpage.js

The folder fullpage.js has been created with this structure
fullpage.js > dist (all the files belonging to the folder)
                  > vendors (all the files belonging to the folder)
                  > LICENSE
                  > package.json
                  README.md

Following the logic behind import fullpage from 'fullpage.js' I want to import the extension file within the dist folder

import extension from 'fullpage.js' // doesn't workt
import * as extension from 'fullpage.js' // doesn't work also

I'm stuck here and I would really like to import it properly and not to enqueue it or to create a script tag that would be against performance, 

Could someone guide me ?

Thanks a lot =)

Albin

**Comment by alvarotrigo** [comment]
Did you check the docs?
https://github.com/alvarotrigo/fullPage.js/wiki/Use-module-loaders-for-fullPage.js

**Comment by ametthey** [comment]
Oh damn ! didn't know this exist !!! Thanks so much for this amazing documentation !
