### ISSUE TITLE
Issue when enabling fade effect by fullpage_api.fadingEffect.turnOn();

### ISSUE THREAD

**Issue by imi47** [alvarotrigo/fullPage.js#3934]
Hi Alvaro,
I'm facing an issue with the fade extension. When I use fullpage_api.fadingEffect.turnOn() I get the following error: Uncaught TypeError: Cannot read property 'fadingEffect' of undefined
    at window.fp_fadingEffectExtension.N [as turnOn]

Link to isolated reproduction: https://codepen.io/imi47/pen/LYVBwZa

Versions:
fullPage 3.0.8 - Extensions 0.1.9
fullpage.js Fading Effect Extension 0.1.2 for fullPage.js v3

OS:
Windows 10

Browser:
Chrome

**Comment by SamuelMTDavies** [comment]
Had similar issues when wanting to use the fade extension only on certain sections.

Any thoughts @alvarotrigo ?

**Comment by alvarotrigo** [comment]
Please use the [contact form](https://alvarotrigo.com/#contact) to provide us with an isolated reproduction of the issue.
Make sure to remove any CSS and JS  that is external to fullpage.js and to provide the minimum HTML code for the reproduction. 

The better isolated the reproduction is the faster response you'll have. 
Bear in mind that without an isolated reproduction we might not be able to investigate the issue.

**Comment by SamuelMTDavies** [comment]
@alvarotrigo How come you can't answer it here? I believe he has provided a minimal example already. I hope you're not just trying to keep your issues numbers looking nice by providing support elsewhere?

**Comment by alvarotrigo** [comment]
> I hope you're not just trying to keep your issues numbers looking nice by providing support elsewhere?

Believe me, we don't have the time o care about numbers of issues 😄 

If you read the [license terms of any extension](https://alvarotrigo.com/fullPage/extensions/license.html#for-up-to-1-website) you'll see how support is only provided by email:
![image](https://user-images.githubusercontent.com/1706326/77330538-cb460980-6d1f-11ea-9e57-475c4a57660d.png)

Reasons for it are:

- Extensions are not open sourced and therefore don't belong to this repository.
- Github issues can't be linked with commits (we do that in our own private repo)
- We prefer people don't create links in codepen or jsfiddle with extensions files
- We prefer people don't share their license key + activation key online
- We check users email or license key to verify if they still within their support period.

And probably many others that don't come to my mind now and that I won't lose time thinking of. 
Hope that answers your question.

**Comment by SamuelMTDavies** [comment]
It does thanks for taking the time to answer. I may be a bit too cynical but your response is very useful and enlightening.

**Comment by codeninja-top** [comment]
could you share with me fading extension js file?
