### ISSUE TITLE
chinese readme.md

### ISSUE THREAD

**Issue by yingjieweb** [alvarotrigo/fullPage.js#3935]
### Steps to reproduce it
1. To view the readme file under https://github.com/alvarotrigo/fullPage.js, click on the "Chinese" jump to the Chinese version of the readme.
2. Under the words "for Vue, React and Angular" in the Chinese version of the readme file is the word "---" .
3. There is no component secant for this markdown rendering.
![1584791164(1)](https://user-images.githubusercontent.com/47938439/77225724-b6953480-6bac-11ea-9457-ed6dda5bab45.png)

**Comment by alvarotrigo** [comment]
Thanks for reporting it!! 👍 
Please feel free to create a pull request with the fix :)

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
