### ISSUE TITLE
Deactivate on one section

### ISSUE THREAD

**Issue by gjwjr** [alvarotrigo/fullPage.js#3936]
Hi,

Is there a way to deactivate a section on elementor? 

I want to scroll along horizontally and then Fullpage not apply on that second inner section so thati can have more content than a mobile screen can fit

**Comment by alvarotrigo** [comment]
Sure!
You can ttry using `fullpage_api.setAllowScrolling(false);` on a callback such as `afterLoad` and then activating it again when you leave that section.

**Comment by gjwjr** [comment]
Thanks Im not sure how to implement this with the Events settings on the
plugin though.

Thanks

*Gary West Jr*
*Web Design & Development*
www.garywestjr.com <https://garywestjr.com/>

**Comment by gjwjr** [comment]
Ive got it working on this section with the following code -
https://daisy.garywestjr.com/portfolio/dj-snake/#section-203faf2/media

if(origin.anchor == 'media')
{
fullpage_api.setAllowScrolling(false);
}

BUT I still want to make that inner section scrollable so that users can
see the content beyond the screen.

Thanks

*Gary West Jr*
*Web Design & Development*
www.garywestjr.com <https://garywestjr.com/>

**Comment by gjwjr** [comment]
Its not working actually....its easier if i show you what I am trying to
achieve.

See the video below, this is how it works currently, the problem is when
the user tries to scroll down in an inner section to view the content below
the screen, once it reaches the bottom or top it scrolls to the next
section. I need it not to do this.


Thanks

*Gary West Jr*
*Web Design & Development*
www.garywestjr.com <https://garywestjr.com/>
