### ISSUE TITLE
Cannot activate license key in elementor

### ISSUE THREAD

**Issue by ayertay** [alvarotrigo/fullPage.js#3937]
Hello,

I'm trying to activate the plugin but I get an error:

An error occured while activating the license. Please check your license key!
Error: You have reached the limit of domains for your license.

I haven't used it yet.

**Comment by alvarotrigo** [comment]
Please contact us though the [https://alvarotrigo.com/#contact](contact form).

**Comment by preston-method** [comment]
Hi I am having the same issue. The paid license for a plugin is not working. Sent email.
