### ISSUE TITLE
slide render outside of section (WP theme dev)

### ISSUE THREAD

**Issue by ametthey** [alvarotrigo/fullPage.js#3938]
Hi all, 

I'm currently working on a WP theme with fullpage js as a main functionnality for displaying portfolio project

I'm using the functionnality section > slide to display my project horizontally but a weird event occur ... 

I'm using the function get_template_parts.

sometimes the slide is displaying outside of the section even though I'm including it inside of the section div ! 

Did someone have the same issue ?

![Capture d’écran 2020-03-25 à 13 00 32](https://user-images.githubusercontent.com/7902934/77534409-df614680-6e98-11ea-9394-35b2b81bebe8.jpg)

![Capture d’écran 2020-03-25 à 13 01 26](https://user-images.githubusercontent.com/7902934/77534416-e38d6400-6e98-11ea-9751-995e46acf919.jpg)

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by ametthey** [comment]
I can put the code on a server that's ok for you ?

**Comment by alvarotrigo** [comment]
As long as there are no external CSS or JS files to fullpage.js that's fine. 
Also, use the minimum amount of HTML code possible. Use empty section or with a single title in them.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
