### ISSUE TITLE
Down navigation only when reaching last slide

### ISSUE THREAD

**Issue by Zubrik** [alvarotrigo/fullPage.js#3939]
Hi,

I'm thinking of using fullPage.js for a project, but first I have to know if this is possible (I haven't found it on the docs):

My site would start with a fullpage horizontal navigation (slides), and at the last slide, the user would scroll down to find another horizontal slide. It shouldn't be possible to scroll down from any of the other slides but the last.

This structure would be repeated throughout the site.

I hope I've succeeded in explaining what I'm looking for.

Thanks.

**Comment by alvarotrigo** [comment]
It is possible.
You can use the method `setAllowScrolling` on the `afterLoad` callback to allow or deny scroll to certain directions.

Then you can use the paid extension `scrollHorizontally` that will allow you to slide right or left by using the mouse wheel /trackpad as well as allowing you to move down when reaching the last slide within a section. 

I would encourage you to try it before without the extension and then if you manage to make directitons work then you can purchase both the fullPage.js license and the extension.
