### ISSUE TITLE
License Key 2020

### ISSUE THREAD

**Issue by rothschild696** [alvarotrigo/fullPage.js#3941]
Hello Alvaro,
i´ve purchased a License Key for the fullpage.js.
i tried to add it in to the complex configuration .js file, but i still get an error warning on the developer tool of google Chrome.
can you help me solving it?

Thank you in Advance

David

let myFullpage = new fullpage('#fullpage', {
    //Navigation
    **licensekey:'xxxx-xxxx-xxxx-xxxx',**
    menu: '#menu',
    lockAnchors: true,

**Comment by alvarotrigo** [comment]
You are very probably introducing it wrong. 
However, give it a check on the fullpage inspector: https://alvarotrigo.com/fullPage/inspector/
