### ISSUE TITLE
 I don't see the 11 slide

### ISSUE THREAD

**Issue by Alice11988** [alvarotrigo/fullPage.js#3942]
Hello, 
last year I purchased a Hobby Commercial License for 1 developer for a little personal project. 
I can only view 10 slides. When I add 11 I don't see it. Is there a slide limit or do I have to integrate some functions? I apologize in advance if there are answers online to my problem, I have tried to search but have not found them ... I am inexperienced and my English is only basic. Thank you very much.

**Comment by alvarotrigo** [comment]
There's no limit. It must be some other error in your side.

**Comment by Alice11988** [comment]
Ok thank you.
