### ISSUE TITLE
ImageLoaded event for lazyLoaded images

### ISSUE THREAD

**Issue by amjo** [alvarotrigo/fullPage.js#3943]
I am using the latest version of FPJS, and i am lazy loading the images through data-src, along with autoplaying the slides/sections every 5 seconds.

The plugin is working just fine and flawlessly, same for the autoplay, but what i am trying to achieve is a bit tricky for me. Is there an event listener for when the images are loaded completely? 

right now, for high resolution images, it can take more than 5 seconds for an image to load. and since autoplay is set to 5 seconds, the slide changes before the image is loaded. 

how do you suggest going about this? (my current solution in my head, at least, is to NOT use data-src and use my own data attribute to lazy load images so  i can track the on("load") event of the images.

thanks,
/avz

**Comment by alvarotrigo** [comment]
> Is there an event listener for when the images are loaded completely?

That's a JS question rather a JavaScript one. I would recommend you asking in another place such as stackoverflow.com.

**Comment by amjo** [comment]
@alvarotrigo i know it is a javascript question, and also know how to implement onLoad on any general image with a basic code like below:

`$("<img/>").on('load', function() { console.log("image loaded correctly"); })`

but my question is a direct question about JSFP asking if there's an event listener for onload of images when using data-src lazy load. Otherwise, we'll need to modify the core fullpage.js for this.

**Comment by alvarotrigo** [comment]
The load event would get fired when the src changes, see this:
https://jsfiddle.net/pvtL9w0c/
