### ISSUE TITLE
Lazy loading ignores fp-auto-height-reponsive and enables scrollbar

### ISSUE THREAD

**Issue by superspace** [alvarotrigo/fullPage.js#3944]
### Description
The callback of lazy-loading images "onMediaLoad()" ignores the .fp-auto-height-responsive class and re-enables the scrollbar also in responsive-mode.

Options:
```
scrollOverflow: true
responsiveWidth: 640
```

HTML:
```
<div class="section fp-auto-height-responsive">
   <img data-src="…" />
</div>

```
### Link to isolated reproduction with no external CSS / JS

[codepen.io](https://codepen.io/superspace/pen/XWbGbXg)

### Steps to reproduce it
1. Load the page in a window width < 640px
2. Scroll down
3. Section 3 scrolls overflow, even if auto-height is set

### Versions 
Any Browser, any version

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!
We'll take a look at it!

**Comment by alvarotrigo** [comment]
Fixed on the dev branch! 
Will get merged in the next release. If you want to use it know use [this file](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.min.js).

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
