### ISSUE TITLE
Unable to select/highlight text

### ISSUE THREAD

**Issue by romain-granai** [alvarotrigo/fullPage.js#3945]
Hi,

I'd like to know what prevent the ability to select/highlight anything inside the the fullpage wrapper?
I'm currently removing all css related to the fullpage plugin in order to isolate the problem without success. Is it possible to achieve? 

I thought I've added something but I tried on the demo page (https://alvarotrigo.com/fullPage) and it's actually impossible to select the text. I've checked the other issues :

https://github.com/alvarotrigo/fullPage.js/issues/3772
https://github.com/alvarotrigo/fullPage.js/issues/2489 

 and found out it could be a problem with scrollOverflow, but first I'm not using it and even tho I'm not using it I tried the fixes and it still not working.

Thank you

**Comment by alvarotrigo** [comment]
The demo page uses the extension Drag And Move, which prevents text selection as it forces dragging. 
Regarding scrollOverflow, the issue still open but you can read the solutions that worked for others in that same issue.

**Comment by romain-granai** [comment]
Hi,

I already tried to fix the issue following the other posts, but I'm not using scrollOverflow  and even tho I'm not using it I tried the fixes and it is still not working.

What could be the issue?

here is the website : http://romaingranai.be/pb/index-v2.html

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
