### ISSUE TITLE
Elementor plugin - Fadding Effect : Target Slide - Makes all the section invisible

### ISSUE THREAD

**Issue by raphael-theriault** [alvarotrigo/fullPage.js#3947]
Issue is pretty straight forward to reproduce. 
As soon as I turn on the fading effect, all the sections are invisible. ( From Javascript or from the designer)

All my sections are "Has Horizontal Slides" to "Yes".

The css section added in the header of the html cause the problem (fullpage.fadingEffect.js:77 - function L(e) )

**Comment by alvarotrigo** [comment]
Please report that though the [contact form](https://alvarotrigo.com/#contact). We don't deal with Elementor or extensions issues in this forum.
