### ISSUE TITLE
Anchors button box

### ISSUE THREAD

**Issue by Pedroluarez** [alvarotrigo/fullPage.js#3949]
Hi Sir,
I'm having a difficulty on removing this white box and hover on my Anchors.
<img width="358" alt="Anchors" src="https://user-images.githubusercontent.com/63353880/78792077-41ff2a00-79e3-11ea-8ea9-d82dcdab7fe1.PNG">

I use your default way of anchors. I tried to find a way how to remove those white boxes. I remove may bootstrap tag and check my custom CSS but still I cant remove it. Please help me thanks.

My HTML Code: 
<img width="418" alt="code" src="https://user-images.githubusercontent.com/63353880/78793216-ab336d00-79e4-11ea-92d4-f1d976bf341a.PNG">

**Comment by alvarotrigo** [comment]
Just don't include the examples.css of fullpage demos.

**Comment by Pedroluarez** [comment]
alvarotrigo Thank you sir. closed.
