### ISSUE TITLE
Shows error message despite license key

### ISSUE THREAD

**Issue by NielsKl** [alvarotrigo/fullPage.js#3951]
### I just bought a license key and the console still logs an error message to Chromes console. I also ran Alvaro's fullPage inspector but it showed nothing suspicious.

FullPage is initialized the following way:
`new fullpage('.fullpage', {
	licenseKey: 'XXXXXXX-XXXXXXX-XXXXXXX-XXXXXXX',
	autoScrolling:true,
	scrollHorizontally: false,
});`

Using chromes newest version.
Help is much appreciated.

**Comment by alvarotrigo** [comment]
I would recommend you to use the fullPage.js inspector to see what's wrong with your site:
https://alvarotrigo.com/fullPage/inspector/
