### ISSUE TITLE
error Uncaught TypeError: options.scrollOverflowHandler.setIscroll is not a function     at HTMLDocument.onMouseEnterOrLeave

### ISSUE THREAD

**Issue by vaigtech** [alvarotrigo/fullPage.js#3952]
Uncaught TypeError: options.scrollOverflowHandler.setIscroll is not a function
    at HTMLDocument.onMouseEnterOrLeave
![image](https://user-images.githubusercontent.com/5129134/79309253-0b597000-7f0b-11ea-9282-197a0d07a039.png)
![image](https://user-images.githubusercontent.com/5129134/79309357-393eb480-7f0b-11ea-91e9-5a142859aa5b.png)

**Comment by alvarotrigo** [comment]
You might be using an old version of fullPage.js or the  scrolloverflow file?
Are you using the latest? 

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by vaigtech** [comment]
I am using  3.0.8 version. It is very difficult to provide  isolated
reproduction in jsfiddle <https://jsfiddle.net/alvarotrigo/ea17skjr/> .Thanks
in advance

**Comment by alvarotrigo** [comment]
Let us know when you manage to create one in jsfiddle, codepen or even your own web server, but make sure that it is isolated :)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
