### ISSUE TITLE
I created a fullpage site with fullpage.js....then i added a navigation menu using Bootstap nav. The problem is that there was a margin-top created that pushed all fullpage content downwards. How do i get the site content to fit without any margin on top? 

### ISSUE THREAD

**Issue by Marvtc23** [alvarotrigo/fullPage.js#3954]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Sounds like a css issue rather than a fullpage.js one.
I would recommend you to ask in another place such as stackoverflow.com where they'll be able to help you much better.
