### ISSUE TITLE
can each slide has a specific height?

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#3955]
hi Alvaro,
still tweaking a project that i'm using FullPage and i was wondering if it would be possible to have a specific height per slide, in the same sense that sections can have heights smaller or bigger than the viewport. thanks!

**Comment by alvarotrigo** [comment]
Sure!
Read about the class `fp-auto-height` in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections).
