### ISSUE TITLE
I can't make elementor animations work with FullPage plugin.

### ISSUE THREAD

**Issue by InfinetyEs** [alvarotrigo/fullPage.js#3956]
### Description

Hello. 

Is like all the animations are being triggered when the section loads and you don´t see the animations when you scroll to that section. 

Is there any option to make it work?

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

It's a wordpress I can send you the credentials on private. How do you want me to send it to you?

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Please use the contact form in the site to report issues for the WordPress plugin.
