### ISSUE TITLE
Fullpage scroll only works when logged in as admin.

### ISSUE THREAD

**Issue by hjalmar86** [alvarotrigo/fullPage.js#3958]
Hi

I have an issue for which I cannot find a solution.

While I am logged into wordpress as admin, the scroll function works perfect. But if I log out or visit from Another browser or computer, the function is gone.

Has this issue come up before?

**Comment by nuriaheep** [comment]
Hi,
Do you have WP Rocket plugin installed or some plugin that work with cache?
I this is the case, try to clean the cache from inside the plugin dashboard

**Comment by alvarotrigo** [comment]
We do not treat wordpress issues in this forum.
If you are using our Elementor or Gutenberg plugin please use the [contact form](https://alvarotrigo.com/#contact) to reach for specific product support.
