### ISSUE TITLE
Make fullpage.js not fill full screen

### ISSUE THREAD

**Issue by hormigaz** [alvarotrigo/fullPage.js#3959]
Hi Álvaro! Óscar from Spain. Your plugin is Buenísimo!

I'm trying to make fullpage.js not fill the entire screen. I know it is a plugin designed for fullscreen, but I am trying to make it not. It's possible?

My layout has a menu fixed to the bottom and I am trying to make fullpage.js fill the entire screen minus the height of the menu. When fullpage.js slides up, works. But when it slides down, it doesn't work, it leaves a gap (same height of fixed bottom layer) at the top...

![ezgif-6-083ff53a2a15](https://user-images.githubusercontent.com/20417848/80090573-9fed4f00-8557-11ea-9e9f-db5363dd7833.gif)

CodePen --> https://codepen.io/hormigaz22/pen/eYpgOGb

What I'm trying to achieve is something similar to this example (https://alvarotrigo.com/fullPage/examples/fixedHeaders.html#firstPage), but in this particular example, fullpage.js is moving behind the fixed header and footer. I do not want fullpage.js move behind fixed layers. Summarinzing, the size of fullpage.js would be 100% height of window minus fixed header height minus fixed footer height (in your example).

Thanks!

**Comment by alvarotrigo** [comment]
Me alegro que te resulte útil!! 👍 

Regarding your issue, the most you can do at the moment is use the `fp-auto-height` feature detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) or use the [offset sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html), which allows you to use percentages for them.

There's [an open topic](https://github.com/alvarotrigo/fullPage.js/issues/2785) about implementing an offset top for your purpose, but nothing has been done on the topic there.

I'll close this issue as the topic is being treated in that issue I just mentioned.
