### ISSUE TITLE
fullpage js extension Drag And Move on mobile devices with normalScrollElements

### ISSUE THREAD

**Issue by VladislavAlek** [alvarotrigo/fullPage.js#3962]
Hello!
I write using a translator) I use the fullpage.js plugin with the extension drag and move on my site. The described situation applies to mobile devices.

I also use the following settings: css3: true, scrollBar: false, autoScrolling: true, fitToSection: false, dragAndMove: true, normalScrollElements: ".producttext, .folded, .unfolded, #mapmarkets, .right_map, .sidebarForm"

Everything works well and smoothly. Elements marked in normalscrollelements also work well when used. However, when you stop using them and return to elements that are not marked as normalscroll, the section transition system collapses, sections jump over one or two or even more at a time, this does not happen with slides.

If autoscrolling: false with all the rest of the same settings as I listed earlier, then section transitions work fine and do not jump over several at once, but then they jerk, while transitions between slides remain smooth always with any autoscrolling settings and dragandmove: true.

Is there a solution for this now? Autoscrolling: true, dragandmove: true and normalscrollelements need to work well together.

**Comment by alvarotrigo** [comment]
Make sure to use the latest version for both fullpage.js 3.0.8 and the extension ( 0.0.9 ).
If that still doesn't work for you, try with the [development version of fullpage.js](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js).

**Comment by VladislavAlek** [comment]
I checked, I am using the given version. When using the .js file you proposed, the DragAndMove extension stops working and fullPage.js works in its normal mode.

**Comment by alvarotrigo** [comment]
> When using the .js file you proposed, the DragAndMove extension stops working and fullPage.js works in its normal mode.

Oh :) I Should have pointed to the extensions one:
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.extensions.min.js

Let me know if you still have the issue with it.

**Comment by VladislavAlek** [comment]
Fine! Now it works as I expected. Thank you!

There is still a small, not very critical observation.
This can be seen even on the demo page of the DragAndMove extension. In the first section, when moving to the second slide and returning to the first slide, the transition sticks, it goes through and works well after turning to the second section and returning to the first. Is there any way to get rid of this right away?

By the way, if you use the data-anchors attribute on slides, then this sticking on the first slide of each section remains in any case.

**Comment by alvarotrigo** [comment]
> In the first section, when moving to the second slide and returning to the first slide, the transition sticks, it goes through and works well after turning to the second section and returning to the first. Is there any way to get rid of this right away?

Yeah, that's an old issue that I though it was fixed, but apparently stills there... 
We will have to look at it with more time. 

> By the way, if you use the data-anchors attribute on slides, then this sticking on the first slide of each section remains in any case.

I guess you are talking about the positioning of the horizontal slides while moving up or down to another section? 
That's intentional, but shouldn't be a problem if  you don't scroll too fast :)

**Comment by VladislavAlek** [comment]
No, not about that, it's the difficulties of machine translation)

I mean that if the slides have the data-anchors attribute, then there is a lag in the transition to the first slide in the section, as in the first section on the demo page and this lag does not pass after scrolling to another section.
If this attribute is not on the slides, then the lag passes after scrolling to the next section.

**Comment by alvarotrigo** [comment]
Yeah, the transition back to the first horizontal slide within a section right? Yeah that's the problem we will have to look at with more calm. But nice to know it depends on data-anchors! :)

**Comment by alvarotrigo** [comment]
> Yeah, the transition back to the first horizontal slide within a section right? Yeah that's the problem we will have to look at with more calm. But nice to know it depends on data-anchors! :) Thansk for the info! 👍

Fixed on dev!

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
