### ISSUE TITLE
Demo at https://alvarotrigo.com/vue-fullpage/ broken

### ISSUE THREAD

**Issue by hartwork** [alvarotrigo/fullPage.js#3963]
Hi!

Cool component! I found that a Git clone does not have the issues I face on https://alvarotrigo.com/vue-fullpage/ , i.e. with both Chromium and Firefox:
- There are three slides in section 2 that all say "Slide 2.2" (rather than "Slide 2.1", "Slide 2.2", "Slide 2.3")
- The navigation to the right shows out-of-place text "page1", "page2" and "page3" (see screenshot below).

Are there plans to get the live demo back in sync with the repository?

Best, Sebastian

![navigation](https://user-images.githubusercontent.com/1577132/80397525-8c731880-88b6-11ea-89b8-c980ccf3c4f0.png)

**Comment by hartwork** [comment]
Should have gone to https://github.com/alvarotrigo/vue-fullpage.js, my bad.

**Comment by alvarotrigo** [comment]
;)
