### ISSUE TITLE
MacOS // Magic Scroll // Touchpad scrolls 2 times

### ISSUE THREAD

**Issue by soerenmuenster** [alvarotrigo/fullPage.js#3964]
### Description
On older MacBooks the page scrolls 2 times. I already disabled magicscroll via js. On older MacBooks there are still those issues. Does anyone know how to fix this? 

### Code for disabling MagicScroll
`    document.addEventListener('DOMMouseScroll', function(e) {
        if (e.axis == e.HORIZONTAL_AXIS) {
            e.stopPropagation();
            e.preventDefault();
            e.cancelBubble = false;
        }
        return false;
    }, false);
`

### Versions 
Issue on MacBook(Catalina) from 2013 with Chrome, Safari, Firefox and Opera

**Comment by alvarotrigo** [comment]
Duplicated of this issue https://github.com/alvarotrigo/fullPage.js/issues/1654
I'll close it as the other one stills open.
