### ISSUE TITLE
Show/hide content in slide.

### ISSUE THREAD

**Issue by pbialasz** [alvarotrigo/fullPage.js#3966]
### Description
I'm trying to do FAQ section with hide/show answer. When the answer open, height of slide is changing and scrolling is not working correct. Is there any solution for this kind of dynamic content?

### Link to isolated reproduction with no external CSS / JS
Here is this page: [https://budman.house/#faq](url)

### Steps to reproduce it
1. scrollOverflow is true.
2. reBuild is not working.

### Versions 
[Chrome]

**Comment by alvarotrigo** [comment]
Sure!
You'll just have to call the `fullpage_api.reBuild()` function just after you open your element.

More info here on the docs:
https://github.com/alvarotrigo/fullPage.js#rebuild
