### ISSUE TITLE
AutoScrolling and ResponsiveSlides etc.

### ISSUE THREAD

**Issue by lukeymason** [alvarotrigo/fullPage.js#3967]
Hey there!

I've been working on this site for my business - http://tripbooth.family/ - I have limited HTML/JS knowledge and indeed coding overall but can work things out and have got this far.

I have brought the main hobby license and also the ResponsiveSlides extension but I'm just struggling to achieve what I'm trying to achieve.

I essentially would like the website as it looks on the browser to look on mobile. i.e. with AutoScrolling, larger images, text that wraps to the smaller mobile screen. At the moment it all looks a bit small on a mobile screen. It doesn't 'shrink up' well and the main images (of trips etc.) don't then go full size.

I've tried searching everywhere on here and Google and trying all the options but either it breaks or doesn't quite work right. I get responsive width etc to work but I want AutoScrolling to continue... and things still look small.

So I wonder if anyone has any advice or guidance for this? :) Basically would like the site as it appears on Desktop to appear as it is on Mobile - i.e. with the same functionality and the images/text to be larger.

Thank you :)

Luke

**Comment by alvarotrigo** [comment]
> So I wonder if anyone has any advice or guidance for this? :) Basically would like the site as it appears on Desktop to appear as it is on Mobile - i.e. with the same functionality and the images/text to be larger.

fullPage.js won't deal with styles for you :)
You'll need to achieve that by using CSS media queries or any other technique.

If you have question about fullPage.js behaviour regarding any options please feel free to ask o reach the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).
