### ISSUE TITLE
Slide audio player and reset current time

### ISSUE THREAD

**Issue by rebosha** [alvarotrigo/fullPage.js#3968]
I would like to slide mp3 files with fullpage but i need to play audio always from the beginning when is slided. I create a button to work it with click function. 
$this.find('span[data-skip]').on('click', function() {
				audioFile.currentTime = 0
				audioFile.play();

Is it possible to focus this function to fullpage ? When user slide - currentTime=0; 
This is a link to slider. https://onlinegallery.online/online/beat/

**Comment by alvarotrigo** [comment]
Sure! 
Make use of callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that.
