### ISSUE TITLE
Showing only a part of the background behind a section

### ISSUE THREAD

**Issue by JulianBroudy** [alvarotrigo/fullPage.js#3969]
### Inserting a mask between a section and its contents.

Hi there!
I am enjoying greatly your library!

I got a little fancy and am trying to create the following effect: [codepen](https://codepen.io/JulianBroudy/pen/WNQdMRK) 🤩.

Here is what I have so far: [codepen](https://codepen.io/JulianBroudy/pen/XWmVZxm) 🤔.

### Steps to reproduce it 😊
1. Click the 1st CodePen.
2. Click the 2nd CodePen.
3. Know your time and support are greatly appreciated.

Initially, I tried to replicate the "Long gradient background" that is larger than the viewport's height. 
You might notice this comes rather easily in the 2nd CodePen. But it took me some time. 
I was able to achieve this by changing the body's `HTML`s height to `height: auto !important;
` and applying the background to the `<div id="fullpage">` element which I was very reluctant doing but I didn't find any other solution so far.
So it seems like the `performMovement` is what gives the effect of a gradient background that is larger than the viewport height.
<br>
**The main problem is that although I have almost accomplished what I need, the section's contents are behind the mask that I applied although I did change the `z-index` properties.**

- **Is it possible to achieve what I am trying to?**
- Do you think this is the right way to do it? Is there a better solution?

Thank you very much.

P.S., The end goal is a bit more complex but I thought I should start with the main problem. Eventually, I would like to have an HTML Canvas in the background something similar to what I have now if you'd like to take a looksie I would really appreciate it and any feedback/criticism that might come with it: [broude.co.il](http://broude.co.il/).

**Comment by alvarotrigo** [comment]
> I am enjoying greatly your library!

Glad you like it! 😉 

Your problem however seems to be a bit outside of the scope of this forum. It seems more like a CSS + HTML issue that is very specific for your use case.

I can however tell you that I would recommend against overwriting the styles used by fullpage.js. So, I would advise you not to use `height: auto !important;` and instead use `autoScrolling: false` on the fullPage.js initialisation. 

For other matters  I would encourage you to ask in other places such as stackoverflow.com where they'll be able to help you much better.

**Comment by JulianBroudy** [comment]
Greatly appreciated.

**Comment by JulianBroudy** [comment]
Found a [solution](https://stackoverflow.com/a/62860907/8062035). 
Thought it wouldn't hurt to mention it here in case anyone ever has the same inquiry.

**Comment by alvarotrigo** [comment]
Good to hear! And thanks for posting it! Hopefully it will be useful for others with your same problem :)
