### ISSUE TITLE
Background-attachment: fixed

### ISSUE THREAD

**Issue by bradwrage** [alvarotrigo/fullPage.js#397]
Hi folks, trying to get background fixed to work, so the the slide takes place like cards folding up.  Having trouble here.

**Comment by BC17** [comment]
On your links, it seems not fixed

**Comment by alvarotrigo** [comment]
In order to use fixed backgruonds you'll probably have to use `css3:false` due to browser's bugs regading fixed positioned backgruonds and translate3d transformations.

**Comment by BC17** [comment]
Good point it works GG
