### ISSUE TITLE
Please contact us for the current phenomenon in IE11.

### ISSUE THREAD

**Issue by jnssanaee** [alvarotrigo/fullPage.js#3970]
[http://www.deepfine.ai/aron_kor.do](http://www.deepfine.ai/aron_kor.do)

Good morning. First of all, thank you for providing a good library.
We built our site using fullpage.js.
In IE11, if you go to slide 2 and go back to 1, there is a phenomenon that the scroll does not rise up to the end.
In addition, when scrolling quickly to reach the end of slide 1, there is a phenomenon in which the scroll is forced to the bottom of the page.
If you declare fp-auto-height on the second slide, does this happen in IE?

### Versions 
IE11

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

If you need us to take a look at your site, consider getting a [Business license](https://alvarotrigo.com/fullPage/pricing/) for premium support.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
