### ISSUE TITLE
[bug] navigation have link to '#undefined' if in one section not exists data-anchor

### ISSUE THREAD

**Issue by urffin** [alvarotrigo/fullPage.js#3971]
### Description
1. run fiddle
2. navigation have four anchors, but in DOM exists just three sections with data-anchor attribute. 
3. seems like a bug and should not added link `<a href="#undefined"` for section without data-anchor attribute

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/vpobq85e/

### Versions 
at least 3.0.4+

----

After some research founded here simple loop by sections https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L1077

    for (var i = 0; i < $(SECTION_SEL).length; i++) {
        var link = '';
        if (options.anchors.length) {  
            link = options.anchors[i]; // here always set link from options.anchors[i] even if this undefined
        }

        // possibly here need checkin for link, like checking for tooltip below
        li += '<li><a href="#' + link + '"><span class="fp-sr-only">' + getBulletLinkName(i, 'Section') + '</span><span></span></a>';

        // Only add tooltip if needed (defined by user)
        var tooltip = options.navigationTooltips[i];

        if (typeof tooltip !== 'undefined' && tooltip !== '') {
            li += '<div class="' + SECTION_NAV_TOOLTIP + ' fp-' + options.navigationPosition + '">' + tooltip + '</div>';
        }

        li += '</li>';
    }

**Comment by alvarotrigo** [comment]
You can not leave a section without anchor. That's reserved for the one on page load.

**Comment by urffin** [comment]
But in this case in anchor `href="#undefined"`.  Can you add somewhere in docs this point?
