### ISSUE TITLE
Script for shrinking navbar on scrolling is not working with FullPage.js

### ISSUE THREAD

**Issue by nilsbh12** [alvarotrigo/fullPage.js#3974]
So I'm using FullPage.js in my website. I want my navbar height to shrink to 100px from 200px after scrolling to second section. But the script is not working with FullPage.js library. When I'm trying it without FullPage.js library, it is working perfectly fine.

Here is script for shrinking navbar.

<script>
    window.onscroll = function()
    {
        scrollFunction()
    };
    function scrollFunction() 
        {
        if (document.body.scrollTop > 10 || document.documentElement.scrollTop > 10)
            {
            document.getElementById("navbar").style.height = "215px";
            }
        else {
            document.getElementById("navbar").style.height = "115px";
                }
            }
</script>

**Comment by alvarotrigo** [comment]
You can:

- Use the fullpage option `scrollBar:true`.This way fullpage will use a scrollbar for the site and your script will work.

- Use [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) or [state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to trigger the change on the navbar. As your script using `onscroll` won't work without a scrollbar. 

You can see a video of how to trigger css changes with state classes here:
https://www.youtube.com/watch?v=qiCVPpI9l3M

**Comment by nilsbh12** [comment]
`scrollBar: true ` worked. But it isn't giving the smooth scroll like before. It's like fps dropped down (pun intended). Any solution for this?

**Comment by alvarotrigo** [comment]
> Any solution for this?

The suggested 2nd solution.

**Comment by nilsbh12** [comment]
Thankyou so much for the help.

**Comment by alvarotrigo** [comment]
You're welcome! :)
