### ISSUE TITLE
Hide a slide on mobile devices or make it responsive

### ISSUE THREAD

**Issue by mariusds** [alvarotrigo/fullPage.js#3975]
Hello,
I have a slide that contains a video ( the first slide ). The video also contains some text and it appears great on desktop however on mobile devices the video does not get resized and I was thinking about hiding it. It is possible to show the video slide only on desktop but hide it on mobile ? Or, if this is not possible, any ideas how to resize the video on mobile to make the responsive ? The video is not from youtube, its a local video i added using the <video> tags.

Thank you!

**Comment by alvarotrigo** [comment]
> It is possible to show the video slide only on desktop but hide it on mobile ?

Of course, but this is amore a CSS question than a fullPage.js one. 
I would encourage you to ask in other places such as stackoverflow.com with the CSS tag. They'll be able to help you much better there.

**Comment by mariusds** [comment]
Hello,
I have managed to hide the content of the side using css but now there is an empty place instead of the slide that does not appear on mobile....

**Comment by alvarotrigo** [comment]
FullPage.js doesn't provide any out of the box way to do so I'm afraid.
