### ISSUE TITLE
Bug with internal links inside a div with scrollOverflow:true

### ISSUE THREAD

**Issue by vitybadelrio** [alvarotrigo/fullPage.js#3976]
Hola! 

Cuando inserto links que apuntan a zonas dentro de un div con scrollOverflow:true, la web no me situa en el punto, empieza a generar espacios y a partir de ahi no me deja volver a navegar correctamente. 

Me puedes echar una mano?

Gracias!

**Comment by alvarotrigo** [comment]
You can not point to any anchor inside any section with scrollOverflow:true. That's a limitation of the vendor library used for such feature (iScroll.js).
