### ISSUE TITLE
Google Maps Infowindow with fullpage js

### ISSUE THREAD

**Issue by JanWerth** [alvarotrigo/fullPage.js#3977]
Hi,
first of all, fullpage js is a really well done library and I didn't run into problems till now.

I wanted to add a map to a section on my page, which wasn't a problem. I also was able to add a Marker and a Infowindow. However, when I open the infowindow the content doesn't show (https://imgur.com/a/5AB18t5).

The following is the JS for the Map:
```
function initMap() {
    var uluru = { lat: -25.363, lng: 131.044 };
    var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 4,
        center: uluru,
        gestureHandling: 'cooperative'
    });

    var infowindow = new google.maps.InfoWindow({
        content: 'Hi this is a test string hoping that it works'
    });

    var marker = new google.maps.Marker({
        position: uluru,
        map: map,
        title: 'Uluru (Ayers Rock)'
    });
    marker.addListener('click', function () {
        infowindow.open(map, marker);
    });
}
```

And the html of the section looks like this: 
```
<div class="section" id="section2">
            <div id="map"></div>
</div>
```

I'm using the W10 with Google Chrome Version 83.0.4103.61

**Comment by alvarotrigo** [comment]
It is difficult to know what's going on without a reproduction of the issue.
Is it working without fullPage.js? Is there any event that triggers that code?

Cam you provide an isolated reproduction in [Codesandbox](https://codesandbox.io/s/m34yq5q0qx) with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by JanWerth** [comment]
Sorry for the late answer, I was lost in finding/fixing the error. 
Yes it is working without fullPage.js and I also found fixed it by adding 
```
p{
	color: black;
}
```
I don't know why or where, but the color of p was white. And I'm pretty sure it's an error on my site so sorry for wasting your time, you can close this thread.

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! ;)
