### ISSUE TITLE
collision script with fullPagejs

### ISSUE THREAD

**Issue by c0ncentus** [alvarotrigo/fullPage.js#3979]
### Link to isolated reproduction with no external CSS / JS
https://codepen.io/c0ncentus/pen/Yzygddb

### Steps to reproduce it
1. hover navigation ("Options" for exemple)
2. want select the menu like "experience vintage"
3. the menu hide itself -> bug
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25374826/82753867-85fa9280-9dc9-11ea-870a-8f6f5725cbd6.gif)

### Suggestion what to be done
maybe is collision with \<li \> tag, please do not select all li tag on your script .
please do ===> [ ... document.querySelectorAll('liAnchorClass')]
 document.querySelectorAll('liAnchorClass') ==> you will get object ...
[ ... document.querySelectorAll('liAnchorClass')] ==> you will get all html element on the tab OKLM.

or making special class to ignore custom nav element please.

### Versions 
Mozilla 76, Windows 10

thanks

**Comment by alvarotrigo** [comment]
I'm sorry but I don't understand what's the issue.

What's the problem with `li` again? We only add the active class to the elements in the menu matching the anchor as you can see here:
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L2744

**Comment by c0ncentus** [comment]
the problem is when i hover the menu i cant keep active menu.... 

if you want test yourself you have already this link https://codepen.io/c0ncentus/pen/Yzygddb. impossible to click on "charte infomatique" for exemple ....

**Comment by alvarotrigo** [comment]
Sorry but I still don't understand very well where's the problem. Can you be a bit more specific?
Detail "expected behaviour", "current behaviour" and if you know where the problem is in the code, line of code too :)

**Comment by c0ncentus** [comment]
Usually when you navigate on a website you have [nav bar](https://www.w3schools.com/css/css_navbar_horizontal.asp). Fullpage JS is use fore singlePage website However I want users can access on other content.
 As you can see I show you first what Im expected and then show you with FullPage js the navbar dont work at all ...

you can click on submenus .... "Rejoignez-nous">click on "Charte Informatique"
[codepen expected behavior](https://codepen.io/c0ncentus/pen/XWmwxXz)

you cant click on subenus .... "Rejoignez-nous">cant click on "Charte Informatique"
[codepen current failed behavior](https://codepen.io/c0ncentus/pen/Yzygddb)

**Comment by c0ncentus** [comment]
its just bug's css navbar  with zindex and collapse element ...
