### ISSUE TITLE
Didnt receive license

### ISSUE THREAD

**Issue by Juka99** [alvarotrigo/fullPage.js#3981]
Greetings,

I just bought fullpage.js license for 1 developer (10.89$), and when I clicked on Pay, it didnt let me go through because I ,,didnt type data from my credit card correctly,,. But my money still got taken from the credit card ? And now I spent 10$ and received nothing ? Help ?

This is what I got after : 

26.05.2020,21:13:21 MC DEBIT PLATINUM PRIM: ********** Iznos:11.09 USD 
Lokacija: GUMROAD.CO* ALVAROTRIG+16502043486 GBRGB

**Comment by alvarotrigo** [comment]
Please [contact us](https://alvarotrigo.com/#contact) for more info.
However, I can tell you in advance that if the payment didn't go through you'll very probably receive a full refund from Gumroad in a couple of days. This is the normal procedure.

**Comment by Juka99** [comment]
I got a refund, tried it again and everything went smooth this time.

Thank you for the reply sir. :)

**Comment by alvarotrigo** [comment]
Glad it all worked out :)
