### ISSUE TITLE
Disallow scrolling in ReactJs

### ISSUE THREAD

**Issue by lardi** [alvarotrigo/fullPage.js#3982]
How can I disallow scrolling in reactJs, any method to do this?

**Comment by alvarotrigo** [comment]
For react we have created a component you can check here
https://github.com/alvarotrigo/react-fullpage

Methods are exactly the same as the ones provided by fullpage.js so you can read about them all in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

Perhaps the one you want is `setAllowScrolling(false)`?
