### ISSUE TITLE
Tooltip with Data Attribute

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#3983]
Hi,

Sorry if this has been asked before but I didn't see a question about it.

When `data-tooltip` is set on a section other than the first one, the tooltip is set to the first section.

https://codepen.io/meceware/pen/oNjrBQx

Please notice `data-tooltip` is set on the third section but it's shown on the first section. Is this normal behaviour?

Thank you,

**Comment by alvarotrigo** [comment]
Thanks for reporting it Mehmet! ;)

Yeah, we definetely have to take a look at tooltips, there are other [related issues](https://github.com/alvarotrigo/fullPage.js/issues/3898) that need to be fixed too. 

I'll mark it as a bug.

**Comment by alvarotrigo** [comment]
Fixed on dev!
Anchors won't be applied when not used for all sections. Rather they use anchors or they don't, but they can't just apply them for some sections and not for others.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
