### ISSUE TITLE
[Question] Extension ScrollOverview

### ISSUE THREAD

**Issue by c0ncentus** [alvarotrigo/fullPage.js#3984]
### Description
Question about Extension ScrollOverview

### Questions
I have some special element use "position: absolute" css properties so my questions are : 

1_ Can i resize one or many scrolls*bar* (with particular fixed height value when you make new fullpageJs('', {...}) on specific particular slide ? (that would be very helpfull) 
2_ How you calculate the scrollbar view ?

thanks

**Comment by alvarotrigo** [comment]
> Can i resize one or many scrolls

What is a "scroll"?

> 2_ How you calculate the scrollbar view ?

You can check the code :)
https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.js#L2255
