### ISSUE TITLE
How to disable & re-enable fullPage.js?

### ISSUE THREAD

**Issue by NPanayotov** [alvarotrigo/fullPage.js#3985]
So I need to destroy or pause the functionality and then enable it at a later stage when I need to (ex when some actions have been done by the user).

I tried using: `fullpage_api.destroy();`  which works halfway.

Once the user interactions are done I want to enable the plugin and continue scrolling.

Tried to re-init but I get an error:

> FullPage: Fullpage.js can only be initialized once and you are doing it multiple times!

I don't really need to destroy it, I just need to prevent the scrolling and then enable it at will.

Is there a way to do that?

**Comment by alvarotrigo** [comment]
Consider using instead `setAllowScrolling(false)` if all you want is to disable scroll.

**Comment by NPanayotov** [comment]
Hi,

Thank you for your swift reply.

I think this is exactly what I need.

Cheers

**Comment by alvarotrigo** [comment]
Glad it helped! 👍
