### ISSUE TITLE
Make slide clickable

### ISSUE THREAD

**Issue by mariusds** [alvarotrigo/fullPage.js#3986]
Hello,
Is there a way we could make a slide clickable ? For example, I display an image in slide1 however when the user clicks that image i want to load a page from the site. Is this possible ?

**Comment by alvarotrigo** [comment]
I don't see why not. Just add a link to the image :)

**Comment by mariusds** [comment]
Hello, Alvaro,
The images I am using are backgrounds. To display the slide I use: 

`<div id="slide1" class="slide"></div>`

I have tried to add the a tag to the divs, like this:
`<a href="#"><div id="slide1" class="slide"></div></a>`

however this doesn't make the slide clickable.
What am I doing wrong ?:)

**Comment by alvarotrigo** [comment]
You'll then need to use JS for that. 
But you'd better ask in another place such as stackoverflow.com about that. They'll be able to help you much better there as this is not a fullpage.js specific issue.
