### ISSUE TITLE
bug when using autoScrolling={false}

### ISSUE THREAD

**Issue by lardi** [alvarotrigo/fullPage.js#3989]
When using `autoScrolling={false}`,
on top of window navigation jump to last section.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
