### ISSUE TITLE
Footer Snap Scroll - shows white space on first page load

### ISSUE THREAD

**Issue by ltater21** [alvarotrigo/fullPage.js#3991]
Hello! Thank you for your help!

### Footer Snap Scroll
Footer adjust with white space first time when scrolling down to the footer. When scrolling up again, then down again, it works better. The fullpage.js documentation seems it should work without the delayed readjustment. Perhaps the JS might "guess" the wrong footer size?

### Steps to reproduce it
1.  Load https://www.ramseyasphalt.com/commercial/
2. Scroll down to footer to see all the extra white space
3. Scroll up and back down and then it reveals the footer correctly

### Version 3.08

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by fabiangigler** [comment]
I just came across the same issue, I believe.
It's related to an external lazyloading script.

Here is a somewhat isolated example, with only fullpage.js and lazysizes loaded:
https://codepen.io/fabiangigler/pen/bGEBeNE?editors=1111

In my case, I cannot (easily) use the lazy loading feature within fullpage.js as the markup and script is outputted by the same WP plugin.

Is there a way to manually update fullpage.js when the images in the footer have loaded in?
Or is the reBuild() method the only option here?

**Comment by alvarotrigo** [comment]
@fabiangigler I would recommend you to set up the `height` and `width` dimensions of the image to load before it even loads. This is usually the recommended approach to prevent jumps in the page when things start loading. 

Example here:
https://codepen.io/alvarotrigo/pen/VwemmRE

If you really want to rebuild it, which I don't think it looks good enough in any ways, just add a line for your image:

```js
document.querySelector('#myImage').addEventListener('load', fullpage_api.reBuild);
```

Example here:
https://codepen.io/alvarotrigo/pen/WNrooPQ
