### ISSUE TITLE
fp-scrollable class automatically coming in ipad devices causing a horizontal scroll in section

### ISSUE THREAD

**Issue by mohit394** [alvarotrigo/fullPage.js#3993]
the fp-scrollable and fp-scroller div are automatically getting applied in real iPad devices over the section that I'm trying to develop but not in emulators. This is causing the section to have a vertical scroll within the section due to ehih the UI is breaking.
is there a way to remove this class getting auto-applied specifically for iPad devices.

the issue is on Safari and Chrome for Ipads.

the dummy structure----
`<div class="fp-scrollable"><div class="fp-scroller"><div class="my-component">.........</div></div></div>`

**Comment by alvarotrigo** [comment]
Can you pease provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by mohit394** [comment]
Hey, thanks for getting back, I found that on iPad devices the sections were not taking the 100vh height had to control the height via js client height method and that fixed the issue. I think majorly it was because of the resolution and viewport height and width of the iPad.

Thank you

**Comment by alvarotrigo** [comment]
Can you reproduce the issue on [the demo page](https://alvarotrigo.com/fullPage/) or any of its examples?

Can you please detail:

- Device
- Browser
- OS

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
