### ISSUE TITLE
Fullpage.js not working when chrome downloaded item bottom bar

### ISSUE THREAD

**Issue by PureProd** [alvarotrigo/fullPage.js#3994]
Hello,

It seems that the fullpage navigation won't work when the user has an file downloaded in the bottom toolbar
![image](https://user-images.githubusercontent.com/67105633/85020056-0e254b00-b170-11ea-9547-13cedff55e57.png)

is it a known issue ?

thanks

**Comment by alvarotrigo** [comment]
Working fine for me.
It might be related with other issue. Perhaps you are pressing CTRL + CMD at some point?

**Comment by PureProd** [comment]
Hi, thanks for your answer,

No I'm not pressing any keyboard button, I'm using Chrome, and fullpage.js with Wordpress and Oxygenbuilder, I tried on several computer I still have this problem, maybe it's related with how the browser "vh"  react with the add of the bottom bar ?

**Comment by alvarotrigo** [comment]
Unless you can provide an isolated reproduction of the issue I don't think there's much we can do here.

The [demo page](https://alvarotrigo.com/fullPage/) and all its examples seem to be working as expected even when downloading a file.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
