### ISSUE TITLE
silentScroll every slide on mouse wheen scroll like SilentMoveTo functoin?

### ISSUE THREAD

**Issue by atulr376** [alvarotrigo/fullPage.js#3995]
Is it possible to scroll every slide in Full page js to scroll silently on the mouse wheel scroll, just like we do with silentMoveTo function?

**Comment by alvarotrigo** [comment]
Not yet. Once we merge this pull request in the next release it will be possible:
https://github.com/alvarotrigo/fullPage.js/pull/3826

You can subscribe to it so you get a notification when merged ;)
