### ISSUE TITLE
Question about the slides in Fullpage.js

### ISSUE THREAD

**Issue by Melvindl96** [alvarotrigo/fullPage.js#3996]
Hi, everybody. I'm using fullpage.js for elemontor. I have a question about the navigation of the slider.  It is not shown properly in a section. see url: https://oomenopslag.nl/scroll/#section-4fd7317

Can you please let me know how I can fix this?

**Comment by alvarotrigo** [comment]
Hi there!
We use this forum to treat issues about fullPage.js itself.

if you have questions regarding the Elementor plugin, please use [the contact form in the site](https://alvarotrigo.com/#contact) and select "Elementor" as the topic :)

We will attend you there!
