### ISSUE TITLE
Horizontal Scroll on Elementor

### ISSUE THREAD

**Issue by sbikosfp** [alvarotrigo/fullPage.js#3998]
Hello,
I am using your Elementor plugin and I've setup a page for horizontal scroll but I have two questions. Because I want to have a page only with horizontal scroll, I have a main section with inner sections as slides. I also use Scroll Horizontally extension.

First of all, I would like to ask, if is it possible to have horizontal scroll on sections instead of inner sections?
And secondly, does lazy load work on slides if I only have one section (because of the horizontal scroll)?

**Comment by alvarotrigo** [comment]
> First of all, I would like to ask, if is it possible to have horizontal scroll on sections instead of inner sections?

Scroll Horizontally only works in a section with horizontal slides.

> And secondly, does lazy load work on slides if I only have one section (because of the horizontal scroll)?

Yeap :)
