### ISSUE TITLE
Cards Extension Activation Option missing from elementor

### ISSUE THREAD

**Issue by tydeio** [alvarotrigo/fullPage.js#3999]
I cannot seem to activate my cards plugin with elementor:

Path:
![image](https://user-images.githubusercontent.com/33286586/86474516-db1bb380-bd3a-11ea-975a-63c24a596d0b.png)

Files:
![image](https://user-images.githubusercontent.com/33286586/86474525-e4a51b80-bd3a-11ea-874f-e80616c1fabf.png)

Elementor:
![image](https://user-images.githubusercontent.com/33286586/86474683-406fa480-bd3b-11ea-9d85-e404f3998aef.png)

Any ideas?

**Comment by alvarotrigo** [comment]
Yeah unfortunately that's the only extension that is not available for the elementor plugin.

Feel free to contact us for a refund:
https://alvarotrigo.com/#contact
