### ISSUE TITLE
[ANDROID 10][CHROME] Refresh page not working

### ISSUE THREAD

**Issue by DiegoMow** [alvarotrigo/fullPage.js#4000]
### Description
At Android devices (in my case, Android 10) when we try to swipe down to refresh page it doesn't work.

### Link to isolated reproduction with no external CSS / JS
http://alvarotrigo.com/fullPage/extensions/parallax.html

### Steps to reproduce it
1. Open page
2. Swipe down

### Versions 
* SO: Android 10; Build/QPKS30.54-22-9
* Device: Motorola One
* Chrome Version: 83.0.4103.106

**Comment by alvarotrigo** [comment]
Hi there!
I'm not able to reproduce your issue. I've tested it in real devices using Android + Chrome in browserstack.com and it seems to be working as expected.

Have you tried restarting your phone?
Perhaps your Chrome crashed in some way and is not able to perform 3d transformations.

**Comment by alvarotrigo** [comment]
Ahhh, you mean the swipe down to refresh... :) Sorry I misread your question.
Yeah that won't be possible I'm afraid. FullPage.js overwrites de default behaviour and unless you turn off autoscrolling by using `autoScrolling:false` or you use `scrollBar:true`, then I don't think there's nothing we can do about it.

Perhaps using `scrollBar:true` can be a solution for you if you really need the refreshing feature.
