### ISSUE TITLE
Preloading section background

### ISSUE THREAD

**Issue by kacperbeski** [alvarotrigo/fullPage.js#4001]
Hello,

Thanks for an awesome plugin - I bought it this morning and have so far  managed to achieve a close-to-perfect result I have been looking for with my simple resumé website. Very intuitive!

I have however two problems:
1. Section backgrounds (simple solid colors) are not preloaded and instead load on scroll (moving between sections). Is there a simple way to change that?
2. For some reason, the address bar changes on each section with '#section-XXXXXX' - is there a way to get rid of that / change the url to something else? I know this is not necessarily the question to fullPage.js creators, but maybe you have a simple answer!

Thanks a lot,

Kacper

PS In case its needed, I am providing the website url [here](http://kacperbeski.com.dream.website/home)

**Comment by alvarotrigo** [comment]
> 1. Section backgrounds (simple solid colors) are not preloaded and instead load on scroll (moving between sections). Is there a simple way to change that?

Backgrounds are loaded on page load by default like in any other page :)
I don't quite understand your issue here.

> For some reason, the address bar changes on each section with '#section-XXXXXX' - is there a way to get rid of that / change the url to something else? I know this is not necessarily the question to fullPage.js creators, but maybe you have a simple answer!

You can decide if you want to use anchors or not. 
See an example without anchors here:
https://alvarotrigo.com/fullPage/examples/noAnchor.html

**Comment by kacperbeski** [comment]
Hey,

Thanks for your comment. I fixed the anchors issue!

However, when it comes to the 1st issue, your example (/noanchor.html) is exactly what I am trying to achieve - the colors of consecutive sections are loaded before fixing to a specific section. In my case, the background colors appear only when you are already fixed to the section. Is there a workaround to achieve such a result as in your example case? 

Thanks!

**Comment by alvarotrigo** [comment]
> In my case, the background colors appear only when you are already fixed to the section. Is there a workaround to achieve such a result as in your example case?

That sounds weird. 
Can you provide an isolated reproduction of the issue on jsfiddle or codepen with no external JS or CSS files and the less amount of HTML code possible?

**Comment by kacperbeski** [comment]
I would happily do it, but do not know how! :-(

**Comment by alvarotrigo** [comment]
Then take any of [the examples provided in the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) or any of the demos from the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js). None of them will have the issue you mention :)

**Comment by kacperbeski** [comment]
This is unfortunately not clear to me. 

Would it be possible for me to provide you with WP login/password so that you could have a look at it from inside? I am having hard time following what I should do next and I am certainly no developer.

I will very much appreciate it - this is the only missing part for my website to go live!

**Comment by alvarotrigo** [comment]
> Would it be possible for me to provide you with WP login/password so that you could have a look at it from inside? I am having hard time following what I should do next and I am certainly no developer.

Sure! If you are using our [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) or [Elementor plugin](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) feel free to use the [contact form](https://alvarotrigo.com/#contact) to report issues.

**Comment by kacperbeski** [comment]
Done! Just sent a message with all the details through the contact form. Thank you very very much!

**Comment by kacperbeski** [comment]
Hey, did you have a chance to look at the website? Any luck? :)

**Comment by alvarotrigo** [comment]
Nope. Please share the link here to keep track of the issue here.
Contact form is only for premium support.

**Comment by alvarotrigo** [comment]
You'll know once you get an answer ;)

**Comment by kacperbeski** [comment]
Sure.. Right now the plugin actually stopped working saying that I have reach the limit of my domains for the license??

Please advise..

**Comment by alvarotrigo** [comment]
Please use the [contact form](https://alvarotrigo.com/#contact) to get support for the wordpress plugins.

**Comment by kacperbeski** [comment]
I did that already with another matter and am still waiting for it to be resolved. How long will it take? My website was up and ready and is now broken :-(

**Comment by kacperbeski** [comment]
Done.
