### ISSUE TITLE
"bigSectionsDestination: null" not working

### ISSUE THREAD

**Issue by DiegoMow** [alvarotrigo/fullPage.js#4002]
### Description
If you set parameter for bigSectionsDestination to null (which is the default behavior) it doesn't happens according to documentation.
As I could see, it will always scrolls to top even if parameter is bottom.

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html

### Steps to reproduce it
1. Start your website with "bigSectionsDestination" as "null" and/or "bottom"
1. Scroll to a section below our big one (according to example, section 3)
1. Scroll up 1 section

### Versions 
* Linux Ubuntu 18.04
* Chrome Version 83.0.4103.116 (Official Build) (64-bit)

Other systems/browsers were tested, but only this one with official example

**Comment by alvarotrigo** [comment]
bigSectionsDestination is not for scrollOverflow. In that case the section is the viewport height but adds a scrollbar.

bigSectionsDestination is mean to be used with `fp-auto-height` or `fp-auto-height-responsive` classes. 
See the part regarding how to create bigger or smaller sections than the viewport:
https://github.com/alvarotrigo/fullPage.js#creating-smaller-or-bigger-sections

I'll clarify it now and add an demo in codepen.

**Comment by alvarotrigo** [comment]
If you want to scroll to the top using `scrollOverflow:true` you can use the [ScrollOverflow Reset extension](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html).

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍
