### ISSUE TITLE
anchors

### ISSUE THREAD

**Issue by JohanGarnica** [alvarotrigo/fullPage.js#4012]
Hi Alvaro, we recently bought a product called fullPage.js https://github.com/alvarotrigo/fullPage.js/tree/master/lang/spanish#fullpagejs
Now, we are wondering the technical approach in order to access a page section from a different view as if it were an absolute url that achors an specific section of a page?
I´m attaching an example of the code
 <div class=“section”>
      <div class=“slide”>
            <div id=“item_a we want to Access1”>
                contenido
            </div>
            <div id=“item_a we want to Access2">
                contenido
           </div>
      </div>
 </div>

**Comment by alvarotrigo** [comment]
> Now, we are wondering the technical approach in order to access a page section from a different view as if it were an absolute url that achors an specific section of a page?

Sure no problem!
Read [the docs regarding how to create links to specific sections and slides](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides)

Basically you just have to add the anchor of the section or slide you want to go to, for exmple, if you access this page you'll go  to section 2:
https://alvarotrigo.com/fullPage/#page2

And you'll go to section 2 and slide 2 if you access this one:
https://alvarotrigo.com/fullPage/#page2/1

If you want to prevent the animation you can use the fullpage.js option `animateAnchor:false`.
