### ISSUE TITLE
Scripted animations not loading after scroll?

### ISSUE THREAD

**Issue by Manisch** [alvarotrigo/fullPage.js#4013]
### Description
Hi there,

I was working on a rough demo to test fullPage.js (Wordpress. Embedded via header, not via Plugin)

On this page, certain elements are scripted like "Fade-in-up when entering the viewport".

This works quite well for the first slide (above the fold), but not for the following slides. It seems like the animation then doesn't get triggered to start, so the slide remains empty. 

### Link 
https://volt.herrmittmann.de/?page_id=131 (Sorry, not isolated)

On this page there should be a headline fading up after the first scroll and the number in the middle should count up to 25.000 but remains at 0 instead.

(Again, it's just a rough demo to test 2, 3 things)

### Versions 
WordPress 5.4.2
Elementor Page builder

**Comment by alvarotrigo** [comment]
You have 3 options here:

- Use the fullpage.js option `scrollBar:true`.

- Try to play them by using [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks).

- Use the official [Elementor plugin for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) that integrates basic Elementor animations.
