### ISSUE TITLE
Extension Cards Animation Issue

### ISSUE THREAD

**Issue by gabedeko** [alvarotrigo/fullPage.js#4014]
### Description
I have installed fullpage js, extensions, and cards without issue but for some reason the animation that occurs when the pages change seems to be very off.

Here is a gif of what it currently looks like: ![Alt Text](http://blog.gabedeko.com/wp-content/uploads/2020/07/fullpage_animation.gif)
 
It seems to be only shrinking in from the left side of the screen which looks very different from the [demos](https://alvarotrigo.com/fullPage/extensions/cards.html). I haven't changed any of the code which may control the animation and I don't think any of the Cards Effect Options can be used to cause this alteration. What could possibly be causing this?

Any help would be greatly appreciated.

**Comment by alvarotrigo** [comment]
We provide support for extensions by email.

Please use the [contact form](https://alvarotrigo.com/#contact) and send us a link to an isolated reproduction with no CSS external to fullPage.js. Also send us the license key or use the email you used for the purchase to contact us.
