### ISSUE TITLE
Scroll issue on Laptop with Touch

### ISSUE THREAD

**Issue by tomasmrazek92** [alvarotrigo/fullPage.js#4016]
### Hello, 

I have a website with fullpage plugin and everything works fine except notebooks which support touch. 

See this video-> 

https://vimeo.com/438350450

For some reason, it seems like plugin cant decide if it should move to another section or not.. So it stuck in middle for while and then goes to sections or decided to go back. Does anyone know why this is happening? 

I am using only these parameters: 
`                 anchors: ['intro', 'nase-podnikani', 'vyhody', 'o-nas-0', 'o-nas-1', 'o-nas-2', 'o-nas-3', 'zakladatele', 'nase-kancelare', 'kontakt','footer',],
                 menu: '#myMenu',
                 scrollBar: true,
                 responsiveWidth: 1279,
                 bigSectionsDestination: top,
                 fitToSection: true,
          });`

Website -> https://life-5.webflow.io/

Thanks for any help!

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

**Comment by tomasmrazek92** [comment]
Hey, I have digged deeper and the issue existed only on newest edge with Scrollbar:true -> Onfortunately I am building the website with Webflow and have bunch of animations related to scroll so turning scrollbar to "false". Kills all of these animations.

I have tested in on touch laptops and same behaviour is on your example website :/, any possible workaround? 
Thanks

**Comment by kbrookes** [comment]
I'm also having this issue, I cannot use my trackpad to scroll - but I'm not experiencing it on the demo page for fullPage.

I have setup a demo with just the required full page scripts (and jQuery, since I'm using the jQuery method):

http://www.eventcast.com.au/fullpage

I can however use my trackpad to scroll on the demo page:

https://alvarotrigo.com/fullPage/

**Comment by alvarotrigo** [comment]
Thanks for the isolated reproduction @kbrookes 

> I can however use my trackpad to scroll on the demo page:
> 
> https://alvarotrigo.com/fullPage/

Instead of the demo page (which uses the Drag And Move extension), can you test on this example page and see if it works for you as well?
https://alvarotrigo.com/fullPage/examples/continuous.html

**Comment by alvarotrigo** [comment]
> I have setup a demo with just the required full page scripts (and jQuery, since I'm using the jQuery method):
http://www.eventcast.com.au/fullpage

Why are you using `$.fn.fullpage.setAllowScrolling(false);`?

**Comment by kbrookes** [comment]
Ah, my bad - I just copied the code in the 'initialization' part of the wiki and was only looking at the options atttributes to solve the issue. I was totally blind to the method sitting down there.

That's all working beautifully now, thank you.
