### ISSUE TITLE
Android Keyboard issue with React-fullpage

### ISSUE THREAD

**Issue by Amitkumar85533** [alvarotrigo/fullPage.js#4017]
### When you click on the input field (Android device). After you finish typing and you close the keyboard. We get the incorrect content size. 

Let us assume we have 4sections of height **100vh** and keyboard height **30vh**.  I am in section 3 and I clicked on an input field. At this particular time, the keyboard opens. And 30vh of section 3 moves up. Then I closed the keyboard.  

Now,
1. Section 3 = 70vh (From bottom) + 30vh of 4th section (top)
2. Section 2 = 70vh (from bottom) + 30vh of 3rd section (top)
3. Section 1 = 70vh (from bottom) + 30vh of 2nd section (top)
4. Section 4 = 70vh (from bottom) + 30vh **(Black screen)**

### Steps to reproduce it
1. Go to the section which has an input field
2. Click on the input field and observe the page content length

### Note
1. My section 2 has an internal scroll. Also the props  'scrollOverflow', 'scrollOverflowReset' are true.
2. I have the licensed version but When I use the localhost in mobile on top it displays 'Unlicensed fullpage.js extension' . **In this, everything works fine with opening or closing the keyboard**
3. In IOS --> safari and chrome, everything works fine.

### Versions 
React-fullpage : 0.1.17
Android problem (Not facing in IOS)
Browser Tested: Chrome

Kindly help me with this. Thanks in advance !! :)

**Comment by alvarotrigo** [comment]
I assume this happens with fullpage.js itself and not just with React wrapper?
I'll move this issue to the fullPage.js repository for further investigation.

**Comment by Amitkumar85533** [comment]
Hi @alvarotrigo , Thanks for your reply.

I was searching for a solution to this problem. After reading [here](https://github.com/cubiq/iscroll/issues/964) . I went to the documentation and found 'verticalCentered' by default was 'true'.

So I made it 'false' and it solved my problem.

**Comment by Amitkumar85533** [comment]
But how it solved the problem, the reason is still unknown.
For this I made : scrollBar={true} and verticalCentered={true}

In IOS, I was able to observe the changes.

When I was clicking on an input field, instead of zooming to that field the section are scrolling to center.
So then I came up with a solution of making **verticalCentered={false}** and it worked !!

**Comment by alvarotrigo** [comment]
Glad you managed to solve the issue!
Are you using the fullPage.js option "scrollOverflow" as well in order to have content bigger than the viewport ? Issue #964 seems to be using it, is this your case as well? 

What version of fullpage.js are you using? 3.0.9 ?

I will keep this issue open for further investigation if you don't mind :)

**Comment by Amitkumar85533** [comment]
Yes, thanks @alvarotrigo ,

Yes, I am using scrollOverflow={'true'}. 
And version :  "@fullpage/react-fullpage": "^0.1.17".

**Comment by thezjy** [comment]
@alvarotrigo I'm having the same issue. Two simple sections. The first one is larger than then viewport with `scrollOverflow: true` and it has an `<input />` in it. After toggle on and off the keyboard, the height of the sections are wrong.

Works fine on iOS safari.

**Comment by alvarotrigo** [comment]
@thezjy thanks, I'll keep it open for further investigation.

**Comment by Amitkumar85533** [comment]
Hi @thezjy , You can solve this by adding below code in index.html

1)   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" /> 
      Check in iPhone and android this will solve the problem

**Comment by thezjy** [comment]
@Amitkumar85533 Still doesn't work. Codesandbox [here](https://codesandbox.io/s/card-form-fullpage-js-6nlnp)

**Comment by ckingsbury20** [comment]
Having a short delay between the focus/blur events and the rebuild seems to work well for me.

`window.setTimeout(() => { fpApi.reBuild(); }, 500);`
