### ISSUE TITLE
fullpage.js in wordpress theme?

### ISSUE THREAD

**Issue by mindfulLiving** [alvarotrigo/fullPage.js#402]
Has anybody successfully integrated fullpage.js in a wordpress theme?
Anything that can be shared?

Great script anyhow!
/Folha

**Comment by alvarotrigo** [comment]
[Fullpane wordpress theme](https://goo.gl/HuFudq) is using fullpage.js as well.

**Comment by yacjs** [comment]
hi everyone, can anyone tell me how to use fullpage.js in wordpress and match in with the page builder? my page builder isnt visual composer or wpbakery.

**Comment by rosemariepopescu** [comment]
Hi guyz, does anyone know if the [Fullpane wordpress theme](https://goo.gl/HuFudq) includes also fullpage extensions or has any option to extra purchase them? I can't figure it out from the demo

**Comment by alvarotrigo** [comment]
@rosemariepopescu that's strange. Try asking them at `info@themify.me`.
Otherwise you can consider using one of our plugins for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) or [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) instead.

**Comment by rosemariepopescu** [comment]
Good, thanks, i'll email them.
Yes, i'm consideting the Gutenberg plugin instead.
