### ISSUE TITLE
change slide class name

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#4021]
hi Alvaro, thanks as usual for maintaining FullPage. 

I'm currently having an issue in which both bootstrap and fullpage have two distinguish classes with the same name, **slide** . I've seen on older issues that you've replied that we can change the name of the class and it should be fine, but I tried changing it on the following variable inside fullpage.js

**    var SLIDE_DEFAULT_SEL =     '.slide';**

and it didn't work. How should I proceed to change the name of the slide class? do you have a proper documentation on this?

Thank you!

**Comment by alvarotrigo** [comment]
> I tried changing it on the following variable inside fullpage.js

You do not have to modify fullPage.js code.
Just pass the options to change it.

From the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)

```js
//Custom selectors
sectionSelector: '.section',
slideSelector: '.slide',
``` 

So for example you can do:


```js
new fullpage('#fullpage', {
     slideSelector: '.mySlide'
});
``` 

Then have:


```html
<div id="fullpage">
  <div class="section">
    <div class="mySlide">Slide 1</div>
    <div class="mySlide">Slide 2</div>
    <div class="mySlide">Slide 3</div>
  </div>
</div>
```

**Comment by gauini** [comment]
oh I when I tried doing the slideSelector I wrote the class name wrongly. It works, thank you!
