### ISSUE TITLE
Elementor animations doesn't work when scrolling to a new section

### ISSUE THREAD

**Issue by Gapito2** [alvarotrigo/fullPage.js#4023]
### Hello. I'm using fullpage Elementor plugin, but it seems the animations doesn't work when scrolling to a new section. It works fine on the first section (there are some animations), but when I scroll down, widgets with animations (custom animations or, for example, a Counter Widget, doesn't do anything.

BUT: it does work when "Scroll Bar" option is enabled. This is the only way I have found to make it work, but I don't want to enable "Scroll Bar".

Is there any way to fix this?

### Steps to reproduce it
1. Create a section with some custom animated images.
2. Create a second section with some custom animated images.
3. Previsualize it: animations on second section doesn't work.

### Versions 
Chrome, MacOS 10.13.

Thank you.

**Comment by alvarotrigo** [comment]
This repository is dedicated only to the JavaScript component. 
For questions regarding the [official plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/#contact).
