### ISSUE TITLE
Parallax on sections - not just background images

### ISSUE THREAD

**Issue by maverickdude** [alvarotrigo/fullPage.js#4024]
### Description
Is it possible to have the parallax effect on the whole section? And not just the images?
The demo page has the parallax effect only on the background images.

This is the reference website: https://aufi.com
The whole section (with copy) has a fixed position there. I would like to do the same with fullPage.js

Apologies for creating an issue for this but couldn't find any examples of it.

**Comment by alvarotrigo** [comment]
> Is it possible to have the parallax effect on the whole section? And not just the images?

It is not designed for that purpose, but you can try adding your content inside the `fp-bg` element and it should move at the same speed as the background. 

Also, check my other library pagePiling.js in case that fits your needs better:
https://alvarotrigo.com/pagePiling/
