### ISSUE TITLE
Full Page as isolated sub-section of larger page.

### ISSUE THREAD

**Issue by benjaminjamieson** [alvarotrigo/fullPage.js#4028]
### Description
Is it possible to have a series of fullPage sections isolated on a larger page with standard content before and after it?  I am trying to build a page with a standard hero banner, followed by 3 fullPage sections that auto scroll, and then a continued page with more standard, non-fullPage content.

### Link to isolated reproduction with no external CSS / JS
Please see the page below which is set up as described above.  The fullPage sections are marked One, Two, and Three.  And appologies - I realize it isn't isolated, but it seems appropriate since the question is specifically about using this in context of a larger page:

http://nautilusstage.wpengine.com/solution/

Thanks for any help.

**Comment by alvarotrigo** [comment]
> Is it possible to have a series of fullPage sections isolated on a larger page with standard content before and after it?

Nope.
The most you can do at the moment is having a first fullPage.js section with horizontal slides and then a normal page:
https://alvarotrigo.com/fullPage/examples/oneSection.html

I'll mark it as a possible enhancement.
