### ISSUE TITLE
Add a VISITED class to section 

### ISSUE THREAD

**Issue by SimonBak** [alvarotrigo/fullPage.js#4030]
Hello,
I want to know if you have a function to add a class VISITED to each section once is visited. 
This way we can have a class added to the section that won’t leave when the user leaves.

I have this function working with an older version of FULLPAGE but doesn't work with the last version.
https://codepen.io/michaelschmidt_/pen/KmybXa

```js
$('#fullpage').fullpage({
    afterLoad: function(anchorLink, index){
        var currentSectionIndex = index - 1;
        var sections = $('#fullpage').children();
        var currentSection = sections.eq(currentSectionIndex);
        currentSection.addClass('visited');
    },  
});`


Thanks a lot for your help.
Simon.

**Comment by alvarotrigo** [comment]
> I have this function working with an older version of FULLPAGE but doesn't work with the last version.

That's because you are not using the new callbacks and its new parameters. 
See the docs for that:
https://github.com/alvarotrigo/fullPage.js#callbacks

	afterLoad: function(origin, destination, direction){},

**Comment by alvarotrigo** [comment]
I'll keep it open as a possible enhancement tho :)

**Comment by alvarotrigo** [comment]
I've decided not to include this feature.
It can easily be done using callbacks so :)
