### ISSUE TITLE
Fullpage js stops scrolling inside iframe

### ISSUE THREAD

**Issue by cotoje** [alvarotrigo/fullPage.js#4032]
Hello

I'm using fullpage.js with scrollOverflow on my website and inside one of the sections I have included an iframe. I can't scroll further down unless I scroll outside the iframe. :/

Thanks for reply.

**Comment by alvarotrigo** [comment]
It is not going to work on an iframe I'm afraid.
Browser restrictions.

Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/2444
