### ISSUE TITLE
Free license form

### ISSUE THREAD

**Issue by shelcia** [alvarotrigo/fullPage.js#4034]
in free license from , whenever form is submitted the page is refreshed and User doesn't know get any notification if it is submitted or not.

**Comment by alvarotrigo** [comment]
You should get this message on submit:

![image](https://user-images.githubusercontent.com/1706326/90755031-fa66a400-e2da-11ea-9e68-1cbfb9638214.png)

Unless the form has errors, like in this case:
![image](https://user-images.githubusercontent.com/1706326/90755095-123e2800-e2db-11ea-8221-4414a2215ce7.png)
