### ISSUE TITLE
 keyboard arrow scrolling

### ISSUE THREAD

**Issue by santiagorr207** [alvarotrigo/fullPage.js#4035]
Hello, the problem I have is that I change sections with the keyboard arrows I want the keys to move in the same section and not go to another

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
> Hello, the problem I have is that I change sections with the keyboard arrows I want the keys to move in the same section and not go to another

Sorry but I don't understand what you mean :) 

Scrolling down will slide down to the next section. 
Hitting the down key on your keyboard will slide down to the next section.

Where's the problem?

**Comment by santiagorr207** [comment]
what I want to do is that when I use the keyboard arrows, it moves in that same section and does not jump to the other

**Comment by alvarotrigo** [comment]
You can use `keyboardScrolling: false` and then create the keyboard binding using javascript and fullPage.js functions such as `moveTo` or `moveSlideRight`.

Unfortunately fullpage.js doesn't provide an out of the box way to achieve it.
