### ISSUE TITLE
#fullpage in the middle of a page

### ISSUE THREAD

**Issue by ourystefan** [alvarotrigo/fullPage.js#4038]
Hey guys,

I am having troubles implementing a #fullpage section in the middle of my page in webflow. 
This probably has been asked multiple times but only can find info about 'normal' section if they are below the #fullpage section. 

I included a quick mockup on what we want to achieve. 

![image](https://user-images.githubusercontent.com/19817691/91443532-bee84e80-e873-11ea-80ee-d2a1b8a4a4e6.png)

Thanks for your time and reply!

**Comment by alvarotrigo** [comment]
> if they are below the #fullpage section.

Nothing can be below or above fullpage wrapper unless they are fixed elements. 
If you need auto height section, those will have to be inside the fullpage wrapper. See this example:
https://codepen.io/alvarotrigo/pen/BKjRYm
