### ISSUE TITLE
NPM UPDATE REQUEST

### ISSUE THREAD

**Issue by ahsynv** [alvarotrigo/fullPage.js#4039]
Hi, is it possible to update the package on npm for the version 3.0.9 please ? ( https://www.npmjs.com/package/vue-fullpage.js ), actually the version of fullpage.js is 3.0.8

Thanks

**Comment by alvarotrigo** [comment]
I'll definitely do! Thanks for the heads up!

**Comment by alvarotrigo** [comment]
Done! 👍
