### ISSUE TITLE
webflow integration positioning bug

### ISSUE THREAD

**Issue by jmej** [alvarotrigo/fullPage.js#4040]
### Description

Objects are being pushed to the vertical center point within a section when fullpage.js is applied.

Additionally - their location is shifting on the y axis while scrolling up and down through the sections on mobile devices depending on the direction the section is approached by.

### Steps to reproduce it

live demo of this bug is [here](https://parallel-sandbox-1b66ae0f0c27487582b6b9.webflow.io/).

webflow designer link is [here](https://preview.webflow.com/preview/parallel-sandbox-1b66ae0f0c27487582b6b9?utm_medium=preview_link&utm_source=designer&utm_content=parallel-sandbox-1b66ae0f0c27487582b6b9&preview=683135a3638e4fb9a0fbd96ffe21b463&mode=preview). 

The text-1 class has  position: relative; and top: 0px; and without fullpage.js applied it appears at the top of the viewport.

Upon refresh you can see it quickly move from the top position of the window to the middle.

Removing the fullpage css and js returns the element to it's intended position.

If you view this on a mobile browser and while scrolling up and down you can see the position of the text shifting. This may be a separate issue, but my assumption is that they could be related.

### Versions 
Windows 10/chrome, iphone 11/safari

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by jmej** [comment]
@alvarotrigo thank you, and I understand that this is really a webflow specific issue.

I've been unable to integrate fullpage.js with webflow in a way that works on mobile. Your demo that you linked above, as well as the [others ](http://fullpagejs-template.webflow.io/) I've found online also do not work correctly on mobile.

I'm not sure if it makes sense to make a codepen example because the problem seems to be a CSS or JS conflict between your codebase and webflow's includes. I could export my code, but I think your demo is an even better place to look for a fix.

I understand if webflow interoperability clash doesn't necessarily constitute a bug, but it would really be tremendous if your library were to work with webflow since it's such a popular platform right now.

I would love to see a working example of fullpage.js on webflow that functions correctly on mobile browsers.

**Comment by alvarotrigo** [comment]
> Your demo that you linked above, as well as the [others ](http://fullpagejs-template.webflow.io/) I've found online also do not work correctly on mobile.

What do you mean? What's the problem on mobile? Notice it is using the option `responsiveWidth` to disable fullpage.js snap feature on on viewports under 1000px width. Maybe that's what you mean?

**Comment by jmej** [comment]
@alvarotrigo on your example, yes you have it disabled. When I've tried to enable fullpage.js for mobile browers via webflow in my own tests I consistently see the bugs I outlined above. I don't believe you've provided a webflow designer link for your example so I can't test with it specifically. 

If you could enable fullpage.js for mobile browsers on your demo and it works without the above problems that would be extremely helpful to see.

**Comment by alvarotrigo** [comment]
> I don't believe you've provided a webflow designer link for your example so I can't test with it specifically.

What do you mean?
Can't you just clone mine, edit it and (https://webflow.com/website/Fullpagejs-basic-example) and provide me with a reproduction of your issue?
I think this would be the easiest way :)

I've updated this another example removing the `responsiveWidth` option.
It seems to be working fine for me on mobile?
https://webflow.com/website/fullPagejs-Horizontal-Slides

Let me know if you can reproduce the issue there.

**Comment by jmej** [comment]
Thank you - this does indeed resolve the issues I was experiencing!  I believe what actually fixed it in my demo was the following apparently important property:

`verticalCentered: false`

I think the vertical centering was what was causing inconsistencies, and both issues I described in the original post.

Thank you for the your help with this!

**Comment by alvarotrigo** [comment]
Glad to hear!
Yeah, perhaps I should name this somewhere in the demos until I release a new fullPage.js version that doesn't depend on `display: table`, which seems to be interfering with flex containers.
