### ISSUE TITLE
Expose current scroll position (x & y)

### ISSUE THREAD

**Issue by bryanberger** [alvarotrigo/fullPage.js#4043]
### Description

It's helpful to expose the current position of the scroll container (since we are scroll-jacking, this is useful for combining with other libraries such as GSAP ScrollTrigger)

Something like:
```
fullpage.scrollPosition
// returns {x: 0, y: 0}
```

I ended up doing something like this:
```
function getScrollPosition() {
  const transform = wrapper.style.transform
  // contains [x, y, z]
  const position = transform.replace(/[^0-9\-.,]/g, '').split(',')
  // only really care about x and y
  return {
    x: position[0],
    y: position[1]
  }
```

 would love some thoughts/guidance, ty!

See: https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy() for examples from other libraries

**Comment by alvarotrigo** [comment]
The thing is fullpage.js usually operates without scroll bar unless you use the option `scrollBar:true` or `autoScrolling:false`.
Therefore the scroll event won't get triggered :)

That's why it provides [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that.

**Comment by alvarotrigo** [comment]
Oh, sorry, read very fast and didn't see your code.

Why would you prefer to get the offset value of the transform rather than using the callback?
Just trying to understand your use case :)

**Comment by bryanberger** [comment]
@alvarotrigo I essentially need the scroll offset position to supply to GSAP's [ScrollTrigger.scrollProxy()](https://greensock.com/docs/v3/Plugins/ScrollTrigger/static.scrollerProxy()).

This allows you to build ScrollTriggers as you normally would (scrolltriggers, trigger gsap animations based on when trigger elements enter/leave the viewport). `ScrollTrigger.scrollProxy()` allows you to reference the value from another library that is hijacking scroll (scrolltrigger, by default watches the window's native scroll).

_Sidenote: I rather use GSAP for scrolltrigger than fullpage because its much more robust (and I quite like the api). Fullpage is used here to scroll lock/snap to each section in my page design._

So in my case I do this and it works as intended:
```

function getScrollPosition() {
  const transform = wrapper.style.transform
  const position = transform.replace(/[^0-9\-.,]/g, '').split(',')

  // return only `y` position
  return position[1]
}

ScrollTrigger.scrollerProxy('main', {
  scrollTop(value) {
    return arguments.length ? window.scrollTo(value) : getScrollPosition()
  },
  getBoundingClientRect() {
    return {
      top: 0,
      left: 0,
      width: window.innerWidth,
      height: window.innerHeight,
    }
  },
})
```
I realize this ask requires knowledge of Gsap/ScrollTrigger, but exposing the X/Y scroll offsets are probably universally helpful.

**Comment by alvarotrigo** [comment]
It would be easy to provide a function that exposes the current position of the "scrolled position" when requested, as you did.

However, providing an event that gets fired during the scroll animation and that exposes those variables in real time might suppose a performance issue.

It would have to read from the DOM on every frame and extract the Y or X value of the transformation. 

I still do not understand very well what's the purpose of scrollProxy() and why you need the transform value.

**Comment by bryanberger** [comment]
Yeah, wouldn't need an event, just a method/getter to call to receive the latest/current scroll position

**Comment by alvarotrigo** [comment]
> Yeah, wouldn't need an event, just a method/getter to call to receive the latest/current scroll position

Just note this way we won't be exposing or being able to retrieve the real X or Y values at all times. Only when the scroll animation is done. 
This is because the translate property only changes once every time we go from one section to another one and the transition takes place due to a CSS transition property. The Translate3d value won't be changing on every frame.

**Comment by alvarotrigo** [comment]
So I guess if your sections all all full-height then you wouldn't even need your function but simply this:

```js
function getScrollPosition(){
    return document.querySelector('.fp-section.active').offsetTop;
}

```

**Comment by bryanberger** [comment]
Yes, for full-height sections. But ,Fullpage also supports `auto-height` which I'm actually using for 1 section in the group. I might try a few things similar to your suggestion. (ps: currently my "hack" is working well enough for my usecase)

**Comment by alvarotrigo** [comment]
Yeah if you have non fullscreen sections your is probably the easier way.

**Comment by oguilleux** [comment]
@bryanberger Thanks for your solution. How did you manage to update scrollproxy y position when you first load the page and you're straight on an anchor ? (ie: myfullpage.com/#2/1)

**Comment by alvarotrigo** [comment]
Fixed on v4! 👍

There's are 2 methods for this now: `getScrollY` and `getScrollX` (for horizontal slides)
