### ISSUE TITLE
How to get the current slide of Auto Scrolling Horizontal Slide?

### ISSUE THREAD

**Issue by saadtanvir1994** [alvarotrigo/fullPage.js#4045]
### Description
I want to add the GSAP animation if I get the inner slides of auto scrolling of horizontal slides using afterLoad function as it is also used in CSS3 animation. 

### Code
```
afterLoad: function(origin, destination, direction){
		var loadedSection = this;

		//using index
		if(origin.index == 1){
			alert("Section 1 ended loading");
		}

		//using anchorLink
		if(origin.anchor == 'firstsec/3'){  
			alert("firstsec/3 ended loading");
		}
	}
```

**Comment by alvarotrigo** [comment]
Sorry I don't understand what you are asking for.
What do you need, the slide index on the calllbacks?
