### ISSUE TITLE
how can use two hash and redirect to one slide ? 

### ISSUE THREAD

**Issue by Moji0098** [alvarotrigo/fullPage.js#4046]
for example i have a tab list with two option , _tab1_ and _tab2_ in order component and i have two button on home that guides me to order component .
i want when i click on **tab1** or _button one_ in home go to order component and my url changed to **example.com/#tab1**  and when i click on **tab2** or _button two_ in home go to order component and my url changed to **example.com/#tab2**

**Comment by alvarotrigo** [comment]
You can use links to move to other section/slides. 
See the docs here:
https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides

If there's anything that is not clear enough there let me know ;)

**Comment by Moji0098** [comment]
you don't know me ! 
i want to change #hash url in a component ( slide ) and i don't want to change slide , understand my question ?

**Comment by alvarotrigo** [comment]
> i want to change #hash url in a component ( slide ) and i don't want to change slide , understand my question ?

You can not change the hash without changing the slide unless you use the option `lockAnchors: true` or the method `fullpage_api.setLockAnchors(true)`.

More info on that here:
https://github.com/alvarotrigo/fullPage.js#setlockanchorsboolean

I hope that helps you! 😉

**Comment by Moji0098** [comment]
in this way haw can go to other slide ? 
i click on a tag with e.g. href="#Order" but slide not change ?! :(

**Comment by alvarotrigo** [comment]
Sorry but I'm not sure what you are asking for.

You said before you don't want to change to another slide:

> i want to change #hash url in a component ( slide ) and i don't want to change slide , understand my question ?

But now you are saying you want?

> in this way how can go to other slide ?
