### ISSUE TITLE
Disable touchmove event for specific elements

### ISSUE THREAD

**Issue by ahsynv** [alvarotrigo/fullPage.js#4047]
Hi, we have a cookie policy plugin on our site and its a custom modal which appears automatically, the problem is fullpage.js touchmove event listener, we can not scroll down on this custom div on mobile and this issue comes from touchmove listener, how can i disable it for custum divs ? ( i have the last version of fullpagejs )

![image](https://user-images.githubusercontent.com/66742883/93304225-f310b880-f7fc-11ea-9b29-2209f8eeb790.png)

Thanks

**Comment by alvarotrigo** [comment]
You can read about the normalScrollElements in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) or about [the method `setAllowScrolling](https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions)` in case the previous option is not enough to solve your issues.
