### ISSUE TITLE
Reload issue on Chrome

### ISSUE THREAD

**Issue by AdrianRoszak** [alvarotrigo/fullPage.js#4048]
Hi,
I've got problem with reloading my page using fullPage.js.

When I scroll down to sections below and reload there, for example on third one, then this section goes up as a first one and other sections goes still in the correct order but higher. I mean if third becomes first, then fourth becomes second etc. but still I can scroll down the page. To empty sections.

It looks like content of the section I have reloaded go up on the sections that was higher. 

The same problem is when I come back from some subpage. 

This bug is only on Chrome, when I view page in other browsers then everything works perfectly.

Have you ever met this kind of problem?

**Comment by alvarotrigo** [comment]
I can't reproduce this on [the demo page](https://alvarotrigo.com/fullPage/) or any of the other examples in both github and online.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by AdrianRoszak** [comment]
https://cdpn.io/adrian-roszak/debug/OJNogBV/vWARwROZmmKk#5

I made it but it doesn't reproduce the issue. Here work as it should.

**Comment by alvarotrigo** [comment]
That means the issue is not on fullPage.js code itself and something in your code (or any external one) might be interfering. 
Unfortunately we do not check those problems here, but if you get the Business license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/) you can get 1 hour support for it.

**Comment by AdrianRoszak** [comment]
> That means the issue is not on fullPage.js code itself and something in your code (or any external one) might be interfering.

I think you are right ;) Thanks anyway

**Comment by alvarotrigo** [comment]
You're welcome!
