### ISSUE TITLE
Getting wrong origin/destination Index

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4050]
Reference: https://codepen.io/kp/pen/abNaxxe?editors=1111
Im getting wrong index number after load. please refer the console. 

Reference: https://codepen.io/kp/pen/abNaxxe?editors=1111

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
Apparently the docs are wrong :) 

`this` won't return the loaded section but instead the origin one. In fact, it will always contain the same value as the first of the parameters. 

I would however recommend you to use one of the parameters for now, so in your case, you can use `destination.index` and that would also avoid possible confusions.

Thanks for the heads up tho! I'll mark it as a documentation enhancement!

**Comment by alvarotrigo** [comment]
Fixed in v4! 👍
