### ISSUE TITLE
Slide anchoring not working 

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4051]
Hi @alvarotrigo ,
Im trying to setup section and horizontal slides using extension. For vertical sections, menu anchoring working perfectly. But I can't add the anchoring for individual slides. As per documentation, I have added data-anchor values for horizontal slide div. 
For navigation link added data-menuanchor value. buts it's not working. Any codepen reference other than documentation?
I've set lockAnchors: true, hope this also fine. 
Thanks

**Comment by alvarotrigo** [comment]
> Any codepen reference other than documentation?

Sure! Check out the examples folder:
https://github.com/alvarotrigo/fullPage.js/tree/master/examples

More specifically this example:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/navigation-horizontal.html

**Comment by krishnaprasadkckp** [comment]
Thanks for the sharing the links, but my question is slide menu link - 
`<a data-menuanchor="section_a" class="">
                text
</a>

<a data-menuanchor="#section_a/slide_3" class="">
                text
</a>
`
May I know this is connect for slides?

**Comment by alvarotrigo** [comment]
Ah, sure!
There's no out of the box way to "connect it" in a way that your menu gets the `active` class when accessing the horizontal slides. 
You can link the menu item so when clicking on it you can slide to the section/slide you want by just using a norma link with the anchor tag. For example `demo.html#section2/slide2` 
More on links here:
https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides

And if you want to add the `active` class or any other to the element in the menu that makes reference to the horizontal slide, you can use [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by krishnaprasadkckp** [comment]
@alvarotrigo Thanks for your reply. 
Actually I should more clear about my question. 
Section anchoring working fine for me by using below method - 
**`<a data-menuanchor="section_a" class=""> text</a>`**
but slide anchoring not working, want to know the below code is correct - 
**`<a data-menuanchor="#section_a/slide_3" class="">text</a>`**

**Comment by alvarotrigo** [comment]
> **`<a data-menuanchor="#section_a/slide_3" class="">text</a>`**

Yeah that's unfortunately not possible at the moment.
You would have to manually do it by using callbacks, state classes or fullpage.js methods.

I'll however mark it as a possible enhancement for future versions. Thanks for reporting it! ;)

**Comment by itzjoordi** [comment]
Is this feature implemented now?

**Comment by alvarotrigo** [comment]
> Is this feature implemented now?

Nope. But it can easily be done using the [CSS state classes](https://alvarotrigo.com/fullPage/docs/#state-classes-added-by-fullpagejs) applied on the `body` element (`fp-viewing-XXX`) or the callbacks.

Here's an example:
https://codepen.io/alvarotrigo/pen/mdoWMzQ

Notice the styles using the [CSS state classes](https://alvarotrigo.com/fullPage/docs/#state-classes-added-by-fullpagejs) applied by fullPage.js:

.fp-viewing-section1 .menu .item1{
    background: orange;
}

.fp-viewing-section1-slide1 .menu .item1{
    background: orange;
}
.fp-viewing-section1-slide2 .menu .item2{
    background: orange;
}
.fp-viewing-section1-slide3 .menu .item3{
    background: orange;
}
