### ISSUE TITLE
Responsive Slides not scrolling vertically on mobile view and afterSlideLoad not working for Responsive Slide extension

### ISSUE THREAD

**Issue by saadtanvir1994** [alvarotrigo/fullPage.js#4052]
### Description

Have the paid Responsive Slides extension. 

I want to convert the horizontal slider slides into sections on mobile view and I have read the documentation + How to use and applied on my code  but it becomes normal scroll and I have mentioned Greensock animation in if condition of afterSlideLoad. 

Facing two issues , sections are not vertical (but having normal scrolling) and each section not taking up full screen viewport width and height. Second, the afterSlideLoad function is not being used on mobile view, what is the alternate of that?

**Comment by saadtanvir1994** [comment]
I have seen the demos but that is just vertical section that keeps on vertical scrolling when responsiveWidth comes.

**Comment by alvarotrigo** [comment]
The Responsive Slides extension gets activated on responsive mode. And responsive mode is basically turning off the autoScrolling and converting it into a normal scrolling website. 

If you want to prevent this behaviour then you will have to stop using any responsive options and then just call the extension methods when you need to change the structure:

```js
fullpage_api.responsiveSlides.toSections();
fullpage_api.responsiveSlides.toSlides();
```
