### ISSUE TITLE
Inner scroll is not working

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4054]
Hi @alvarotrigo ,
I've set sections and slides as per documentation. On mobile I don't need the auto scroll, it was also done. 
For some slides, i need a tabs, that means it will hide the content on initial load. on user click tab link content will shown. 
since our JS is already set the height dynamic content height not reflecting. 
Is there any solution for this?
To avoid this issue, I've set a fixed height and overflow auto for my tab content div. but when I swipe for overflowed content, its not scrolling (inner scroll not working)
structure will like this - 
` section
     slide
           tab content with 300px height and overflow auto
`
Thanks

**Comment by alvarotrigo** [comment]
Sorry I don't understand what the question is.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by krishnaprasadkckp** [comment]
Question is - can I place a div with 200px height, overflow-y: auto with more than 200px long content. Usually scroll will work, right? when I place this within in the slide, scrollbar comes for a second and disappears. Is there any JS from script removing the entire scroll (including inner scroll of the div)

**Comment by alvarotrigo** [comment]
You can use scrollable elements inside your sections if you use the option `normalScrollElements`. See the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) for more info on it as well as an example on codepen.

> Is there any JS from script removing the entire scroll (including inner scroll of the div)

I'm not sure what you are asking here, but on this forum we only provide support for fullpage.js script.

**Comment by krishnaprasadkckp** [comment]
Thank you @alvarotrigo . normalScrollElements this is what i'm looking for. really appreciate the support.
