### ISSUE TITLE
Scroll horizontal section no slide

### ISSUE THREAD

**Issue by silency** [alvarotrigo/fullPage.js#4055]
Hello, when youre use horizontal scroll, it changes color of each "section", which contains all the "slide".

But how can we change color of section and make them scroll horizontal ?

If im trying this : its scrolling vertically

`<div id="myContainer">

	<div class="section"><h1>Section 1</h1></div>
	<div class="section"><h1>Section 2</h1></div>
	<div class="section"><h1>Section 3</h1></div>
	<div class="section"><h1>Section 4</h1></div>

</div>`

If im trying this : its scrolling horizontally but the color is only changed on parent#section not the slide.

`<div id="myContainer">

	<div class="section">
		<div class="slide"><h1>Section 3</h1></div>
		<div class="slide"><h1>Slide 3.2</h1></div>
		<div class="slide"><h1>Slide 3.3</h1></div>
		<div class="slide"><h1>Slide 3.4</h1></div>
	</div>

</div>`

(i dont need vertical scroll)

Thanks

**Comment by alvarotrigo** [comment]
Sorry but I don't understand what you are asking for, but it probably requires using  [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 

Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by silency** [comment]
I just want horizontal navigation, 0 vertical, and switch color and all other fonctions for section but on slide

**Comment by alvarotrigo** [comment]
For horizontal navigation using mouse wheel or trackpad you'll need to use the Scroll Horizontally paid extension:
https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html
