### ISSUE TITLE
scrollOverflow Hidding element unless using paddingBottom

### ISSUE THREAD

**Issue by saadtanvir1994** [alvarotrigo/fullPage.js#4056]
### Description

I am using `scrollOverflow: true` with ` verticalCentered:false`. The content of the sections hidden until I am giving `paddingBottom`, So, I am here to confirm is it necessary to use `paddingBottom` with `scrollOverflow`? Is there any disadvantage to use `paddingBottom` ?

**Comment by alvarotrigo** [comment]
As far as I know there's no bug with scrollOverflow regarding paddings. 
However, if you think there is, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
