### ISSUE TITLE
Trackpad scroll issue

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4057]
Hi @alvarotrigo,
I've noticed a weird scroll behavior when we use laptop trackpad instance of mouse. 

- It was reproducible in demo - https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html#firstPage
- use trackpad for next section scroll
- You will automatically jump to next slide without any interaction

Is there any control option is available to control trackpad?

**Comment by alvarotrigo** [comment]
Unfortunately I can't reproduce it. 
I believe this might be an issue with your browser. Try restarting the browser or the computer and try again.

**Comment by Mfigueira** [comment]
Hi there!
I'm having the same issue, when scrolling sections with trackpad. The gesture has to be large, if you do a slight movement it may not happen.
When scrolling with mouse wheel, this never happens.

Any finding so far about this issue?

Thanks!

**Comment by alvarotrigo** [comment]
Sounds like your trackpad is broken? :)
Try here:
https://alvarotrigo.com/fullPage/

**Comment by Daasty** [comment]
Sadly I'm having the same issue, reducing scrollingSpeed or transitionLapse to 2000 does not solve it :(
It does not happen on fullPage home but it does on Parallax example

**Comment by alvarotrigo** [comment]
> Sadly I'm having the same issue, reducing scrollingSpeed or transitionLapse to 2000 does not solve it :(

`transitionLapse ` is not a fullPage.js option.

> It does not happen on fullPage home but it does on Parallax example

That is definitely weird.
Both are using exactly the same fullPage.js, so there's no reason for it.

Also, I'm not able to reproduce the issue on my side. I'm using an Apple trackpad on my laptop and using speed 2000 solves the issue.

Perhaps your trackpad is malfunctioning.
The only way you can get a second scroll is if your wheel event propagates for more than 2 seconds, which is  A LOT.
A normal scroll shouldn't take more than 700ms and a long/fast one perhaps 1200 or 1500 max.

**Comment by alvarotrigo** [comment]
I'll close the issue as it seems to be inactive now.
Let me know if you want it re-opened.
