### ISSUE TITLE
Change navigation dots colour on one section only

### ISSUE THREAD

**Issue by didiblocsberg** [alvarotrigo/fullPage.js#4058]
Hello!

I have four sections; the third one has a black background and the rest white & the dots colour is black by default. I need to have the dots change colour to white when reaching the black section. Pure css doesn't work and I've also tried the afterLoad function, but it's very buggy. Im most probably doing something wrong, but I'm very much stuck.

https://jsfiddle.net/w2vfjqz7/12/

What's the best way to solve this issue? and if I need to use one of the fullpagejs functions, could you help me out with some code?

Thank you

**Comment by alvarotrigo** [comment]
You can use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

And yes, you replace the color of the navigation by using css 😄

**Comment by didiblocsberg** [comment]
Oh jeez that was so easy. Cheers!

**Comment by alvarotrigo** [comment]
No problem! 👍
