### ISSUE TITLE
Disable mouse touch swipe in scrollOverFlow

### ISSUE THREAD

**Issue by bilalmalkoc** [alvarotrigo/fullPage.js#4059]
### Description
I can't disable mouse touch swiping in scrolOverFlowed page. It is blocking button clicks and text selections. I want scroll only mobile touch and mousewheel.

```
const fullPage = new fullpage('#sections', {
    menu: '#menu',
    lockAnchors: false,
    anchors: ['sec1', 'sec2', 'sec3', 'km'],
    navigation: false,
    licenseKey: '***',
    autoScrolling: true,
    scrollHorizontally: true,
    scrollOverflow: true,
    scrollOverflowOptions: {
        disableMouse: true,
        disableTouch: true,
    },
});
```

### Versions 
Chrome: 85
FullPage.js: 3.0.9
Scrolloverflow 2.0.5

**Comment by alvarotrigo** [comment]
Take a look at the possible options for scrollOverflow at the iScroll.js documentation:
https://github.com/cubiq/iscroll

Perhaps you can try `options.disableMouse`

**Comment by bilalmalkoc** [comment]
`disablePointer: true` worked for me. Thank you.

**Comment by alvarotrigo** [comment]
Glad to hear! 👍
