### ISSUE TITLE
Callback scroll horizontal

### ISSUE THREAD

**Issue by silency** [alvarotrigo/fullPage.js#4060]
What's the best way to call something on scrolling horizontally in slides ? (i want to call a function for each slide, not section)

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.
