### ISSUE TITLE
Track scrollOverFlow scroll Y position

### ISSUE THREAD

**Issue by bilalmalkoc** [alvarotrigo/fullPage.js#4061]
### Description
Is any way track scroll event in scrollOverFlowed section?

[This](https://stackoverflow.com/questions/39359639/with-fullpage-js-can-y-position-inside-sections-be-reported-during-scrolloverfl/39369282#39369282) answer doesn't work anymore.

### Versions 
Chrome: 85
FullPage.js: 3.0.9
Scrolloverflow 2.0.5

**Comment by alvarotrigo** [comment]
There's unfortunately no out of the box way.
However you can check the code here and perhaps create a callback / event for it.

See how we access the `scroller.y` value here:
https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.js#L2488

I'll keep the open issue as a possible enhancement for future version.

**Comment by bilalmalkoc** [comment]
Thank you it helped me. But i acces with **scrollStart** event. Why it doesn't work with **scroll** event? I tried all probType 1, 2, and 3.

```
const fullPage = new fullpage('#sections', {
    menu: '#menu',
    lockAnchors: false,
    anchors: ['sec1', 'sec2', 'sec3'],
    navigation: false,
    autoScrolling: true,
    scrollHorizontally: true,
    scrollOverflow: true,
    scrollOverflowOptions: {
        disablePointer: true,
        probeType: 3,
    },
    afterLoad: function (anchorLink, index) {
        const scrollable = $('.fp-section.active').find('.fp-scrollable')[0];
        if (scrollable && typeof scrollable !== undefined) {
            console.log('Scroll instance active.');
            const scrollInstance = scrollable.fp_iscrollInstance;
            scrollInstance.on('scrollStart', function () {
                console.log(scrollInstance.y);
            });
        }
    },
});
```

**Comment by alvarotrigo** [comment]
The `probeType` options will not work on the fullPage.js fork of iScroll (scrolloverflow.min.js)
That's why I'm recommending you an alternative way instead of trying to modify `iScroll Probe` and adapt it to fullpage.js.

**Comment by bilalmalkoc** [comment]
Hello again. Sory for noob question but this scroll event `scrollStart` is not usefull. Because it is firing only when scroll is end. I need callback like real `$(window).scroll(function() {` for access page position. Can you advice me a better way?

**Comment by alvarotrigo** [comment]
Unfortunately that doesn't exits anymore. 
I can only tell you to try to make a callback by modifying scrolloverflow.js code by using what I suggested [on my previous comment](https://github.com/alvarotrigo/fullPage.js/issues/4061#issuecomment-698883237)

**Comment by alvarotrigo** [comment]
Fixed on v4! 👍

There's a new callback for this called `onScrollOverflow` reporting the Y position.
