### ISSUE TITLE
Changing initialized options in callbacks

### ISSUE THREAD

**Issue by JulianBroudy** [alvarotrigo/fullPage.js#4062]
# Dynamically changing fullPage options

**Would it be possible to change an option inside a callback method?**

For instance:

```JavaScript
onLeave: function(origin, destination, direction) {
  if (destination.index == 0){
    this.paddingTop = 20 + 'px'
  } else {
    this.paddingTop = 0 + 'px'
  }
}
```

**Expected result:** bind the top padding to a variable that would change based on some other logic.

Thanks in advance.

**Comment by saadtanvir1994** [comment]
@JulianBroudy  A solution that comes to my mind is use of css. As you scroll between different section the class like ` .fp-viewing-youranchorname` is added to body.

**Comment by alvarotrigo** [comment]
The padding options can't be dynamically changed now.
The only option would be to destroy and initialise fullpage.js again, but you might see some flickering.

**Comment by alvarotrigo** [comment]
You can try changing it directly with CSS and then doing something like this:

```
fullpage_api.getFullpageData().options.paddingTop = '40px';
``` 

That might do the trick.
