### ISSUE TITLE
Activation Key | Question

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4065]
Hi @alvarotrigo ,
My website hosted in abc.com I've generated activation key based on this domain and working fine. 
When user take xyz.com, It will redirect to abc.com. In this case Do I need to generate new activation key for xyz.com?

Thanks in advance

**Comment by alvarotrigo** [comment]
> When user take xyz.com, It will redirect to abc.com. In this case Do I need to generate new activation key for xyz.com?

Nope. You always have to generate the activation for the final domain that users will see when navigating your page.
So in this case, `xyz.com` would be the final one.
