### ISSUE TITLE
[Question] How can I listen to scroll Y value + single background for all sections

### ISSUE THREAD

**Issue by ortonomy** [alvarotrigo/fullPage.js#4067]
### Description

I'm not doing parallax, I'm not doing multiple backgrounds. What I am doing is interpolating gradient backgrounds between slides (subtle fade one colour to another.) Therefore, I want one fixed/absolutely positioned BG div that listens to scroll value and animates linear background gradient as we scroll. But I can't find a way to a) get total height of slides b) listen to current `scrollY` without adding `scrollbars: true`.  c) the recommended way to have a single background

Is it possible to hide scroll bars and still get this information as an event that updates on scroll?

**Comment by alvarotrigo** [comment]
> Is it possible to hide scroll bars and still get this information as an event that updates on scroll?

You can't get the current scrollY position without scroll bars.
However you have 3 options:

- Use `scrollBar:true` and this way you'll be able to capture the normal scroll event. (I guess you don't want it)
- Use [fullPage.js callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) to trigger changes in your html/css.
- Use [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) to trigger changes in your CSS. (Video on how to trigger animations with it [here](https://www.youtube.com/watch?v=qiCVPpI9l3M))

As long as you apply a transition to your background you won't need to use the current scrollY position but just the final destination. 
Apply to it the same transition speed that you apply on fullpage `scrollingSpeed` option and you should be fine :)
