### ISSUE TITLE
 Flashing rectangles on the safari browser

### ISSUE THREAD

**Issue by Antoshkiv** [alvarotrigo/fullPage.js#4068]
### Steps to reproduce it
When you scroll in safari will see strange rectangles flash like component rerender, on chrome or firefox everything is okay

### Versions 
safari version 14.0 (15610.1.28.1.9, 15610)
 
same issue on iPhone X plus 

Video
https://drive.google.com/file/d/1VVl9bPsNnk152Fw8Gcwwo1eZdMd8v7Db/view?usp=sharing

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
It seems like a rendering bug in Safari, but I'll mark it as a bug just to investigate it a bit further.

**Comment by alvarotrigo** [comment]
I've opened an issue on WebKit issues forum about it:
https://bugs.webkit.org/show_bug.cgi?id=221085

**Comment by alvarotrigo** [comment]
This should fix or improve the issue:

```js
.fullpage-wrapper{
  -webkit-backface-visibility: hidden;
  -webkit-transform: translate3d(0,0,0);
}
body{
 -webkit-transform-style: preserve-3d;
}
```

Where `body` is the parent of the full-page container:

```html
<body>
    <div id="fullpage">
           <div class="section"></section>
           <div class="section"></section>
           <div class="section"></section>
    </div>
</body>

**Comment by alvarotrigo** [comment]
I am not sure if this is happening anymore on the latest Safari version. 
I'm not able to reproduce it on Safari Version 17.5.

Also, the initial link for the reproduction doesn't exist anymore, so I'm just trying to reproduce it on the [demo page](https://alvarotrigo.com/fullPage/) and other [online demos](https://alvarotrigo.com/fullPage/examples/).
