### ISSUE TITLE
i have a div positioned absolute in one slide, but this div dont stay in this slide,instead go´s to the last slide

### ISSUE THREAD

**Issue by Gus2708** [alvarotrigo/fullPage.js#4070]
what i do to make this div stay in your slide, jsfiddle.net/tomzxg1j/

**Comment by alvarotrigo** [comment]
This is a HTML / CSS question rather than a fullPage.js one.
I would recommend you to ask in another place such as stackoverflow.com where they'll be able to help you much better.
