### ISSUE TITLE
Scroll offset without padding?

### ISSUE THREAD

**Issue by Berkays** [alvarotrigo/fullPage.js#4071]
### Description

Is it possible to add an extra scroll offset? I am using a fixed navbar but i don't want to use padding options in the library as it creates a lot of blank space in my sections. If i dont use padding, part of section stays outside the viewport.

**Comment by alvarotrigo** [comment]
You can:

- Use use `fp-auto-height` class. More on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)
- Use the [Offset Sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html), but that works only using percentages.
- Use the `paddingTop` and `paddingBottom` options of fullPage.js.

That's all fullPage.js provides :)

**Comment by Berkays** [comment]
@alvarotrigo I already use fp-auto-height and offset sections doesn't seem to help. I believe padding is more or less a duct tape solution for this. I guess i have to compile my own version.

**Comment by alvarotrigo** [comment]
Yeah unfortunately fullPage.js doesn't provide any other option. There's [an open issue about it](https://github.com/alvarotrigo/fullPage.js/issues/2785) and hasn't been closed yet.
