### ISSUE TITLE
Wrong height of section on IOS 13 and below ( Safari Browser )

### ISSUE THREAD

**Issue by Antoshkiv** [alvarotrigo/fullPage.js#4072]
### Description
If you open a new tab and close after  u will see the first section and on the bottom, u can see the start of the second section

Or in the third section, u can open a link youtube it will open in a new tab and then close it u will see again the start of the next section at the bottom

Video: https://drive.google.com/file/d/17UN5gZLsxbqpPTSlx4-CSnSXW8808FfD/view?usp=sharing

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/react-fullpagejs-example-forked-b296c?file=/src/index.js

https://b296c.csb.app/

### Steps to reproduce it
Open a new tab or scroll to the third section and open a new tab then close the new tab and u will see the wrong height of the section

### Versions 
Safari ios 13 and below

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
I'll take a look at it for the next release! Although dealing with browsers bars is always tricky when it comes to mobile browsers! :)

**Comment by Antoshkiv** [comment]
https://github.com/alvarotrigo/fullPage.js/issues/4073
https://github.com/alvarotrigo/fullPage.js/issues/4068
@alvarotrigo Can you tell me please when approximately you will fix all three bugs I reported?

**Comment by alvarotrigo** [comment]
Whenever I find the time to work on them :)
Quite busy these days, so perhaps in a month or two I'll try to get a new release out.

Just be aware that or some I might not even find a solution! Dealing with mobile bars is not an easy thing.

#4068  has probably no easy solution either. Sound more like a Safari bug dealing with 3d transformations.

**Comment by alvarotrigo** [comment]
This should be now fixed in v4! 👍
