### ISSUE TITLE
Strange bottom rectangle on chrome android

### ISSUE THREAD

**Issue by Antoshkiv** [alvarotrigo/fullPage.js#4073]
### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/react-fullpagejs-example-forked-b296c?file=/src/index.js

clear URL https://b296c.csb.app/

Video:  https://drive.google.com/file/d/1rvUu0-bwMbmK0-9PZOx477MLi6VQe5EK/view?usp=sharing

### Steps to reproduce it
Open link in URL codeSandbox on android devices in chrome browser
flip the phone horizontally, scroll a bit to the bottom when u see the URL is hidden flip the phone vertical and u will see at the bottom white rectangle

### Versions 
Browser Chrome v 85.0.4183.127

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I'll mark it as a bug for further investigation.

Dealing with browser bars is not an easy task so if you want to avoid possible issues I would recommend you to use the option `scrollBar:true`. This should avoid most issues. Or rather, use the responsive options to turn off autoScrolling on small screen devices such as phones and tablets.

**Comment by alvarotrigo** [comment]
This should be fixed now in v4! 👍
