### ISSUE TITLE
Disable script on mobile

### ISSUE THREAD

**Issue by silency** [alvarotrigo/fullPage.js#4074]
Is there any way to disable fullpage on mobile or if width resolution < to 1000px ?

**Comment by silency** [comment]
`	$(window).on('resize', function() {
		if($(this).width() < '980') {			
			fullpage_api.setAutoScrolling(false);
		}
	});`

I've done this, it's okay, but when i scroll on mobile, it's scroll to Top few seconds after mouseout/touchend

**Comment by alvarotrigo** [comment]
Sure!
Check out the `responsiveWidth`, `responsiveHeight`  and `responsiveSlides` options as well as the `fp-auto-height-responsive` class. All detailed on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js)
