### ISSUE TITLE
ScrollOverflow with fit to section issue on wordpress

### ISSUE THREAD

**Issue by arunprasad809** [alvarotrigo/fullPage.js#4075]
**Where and what I am using:**

I have a wordpress website in which I am using fullpage.js with auto scroll to next section and with some scrollOverflow sections. I also have a fixed header.

**What is the problem:**

I have several sections on the page, some overflows (bigger sections - in height). When I scroll down to the section that overflows, I am unable to scroll back up to the previous section and also, the section doesn't fully scroll to its end before jumping to next section.

**What are the options I am using:**

```
var myFullpage = new fullpage('.page', {
css3: true,  // -- Using this for Fixed Header
scrollBar: true,  // -- Using this for Fixed Header and auto scroll to work
paddingTop: '68px',
scrollOverflow: true,
scrollingSpeed: 1000,
autoScrolling: true,
fitToSection: false,
verticalCentered: true,
navigation: true,
responsiveWidth: 992,
navigationPosition: 'right',
navigationTooltips: ['Sec1', 'Sec2', 'Sec3', 'Sec4', 'Sec5'],
```

**Note:**

If I remove "css3: true & scrollBar: true" from the code above, the scrolling works fine. But, "fixed header" and "fixed navigation" on the right doesn't work.

**What I need:**

Fullpage.js works very great and I love it. The only two things I need are,

"I need to be able to scroll back and forth even in scrollable section"
"Need to be able to scroll to the bottom of the scrollable section"

**Versions I am using (latest):**
fullPage 3.0.9
Scrolloverflow 2.0.6

**Here is the stackoverflow link for the same:**
https://stackoverflow.com/questions/64262550/scrolloverflow-in-fullpage-js-is-not-working-in-wordpress

Please help!! Thanks in advance.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Also, note there are official plugins for WordPress [for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) builders and soon [for Divi](https://alvarotrigo.com/fullPage/wordpress-plugin-divi/)! :)

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
