### ISSUE TITLE
getFullpageData().options.paddingBottom not working

### ISSUE THREAD

**Issue by marcoburlando** [alvarotrigo/fullPage.js#4078]
### Description

I'd like to change paddingBottom on window resize. I have a footer fixed and it's change height on resize.
footerH = parseInt($("footer").innerHeight());
fullpage_api.getFullpageData().options.paddingBottom = footerH+'px';
or 
$.fn.fullpage.getFullpageData().options.paddingBottom = footerH+'px';
Dosen't change the css attribute on .section

Can any one help me?
Thanks

### Versions 
3.0.9

**Comment by alvarotrigo** [comment]
See [this answer](https://github.com/alvarotrigo/fullPage.js/issues/1894#issuecomment-194524243).
And check out [this example](https://codepen.io/alvarotrigo/pen/WNxQpaN)
