### ISSUE TITLE
[Question] How to use on production without license key being exposed

### ISSUE THREAD

**Issue by ortonomy** [alvarotrigo/fullPage.js#4079]
### Description
I bought my license key so that I could use this on a commercial project. For some reason my nuxt build is not properly embedding the the license key (my problem) but it's raised a question:

**How can I put fullPage into deployment on production without exposing my license key in compiled JS? It would be trivial for someone to look at the JS code (if not obfuscated) and steal it.**

After this there would be no way for me to know someone has used my key somewhere on the internet.

### Link to isolated reproduction with no external CSS / JS
https://entertwine.online/

### Steps to reproduce it
1. Look in console:

```
fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here: https://github.com/alvarotrigo/fullPage.js#options.
```

**Comment by alvarotrigo** [comment]
Short answer: you can't.
Front-code will always be exposed. 

Do not worry about it, if someone steals it from you it won't be on you but on them. They would be the responsible ones having to deal with the possible legal consequences of it.
