### ISSUE TITLE
Disable fullscreen.js on mobile

### ISSUE THREAD

**Issue by titouanlh** [alvarotrigo/fullPage.js#408]
Hi everyone !
I just want to know how to disable fullscreen.js when the visitor use a mobile device like on onepage-scroll.js with the fonction  responsiveFallback: ???px
Thanks :-)

**Comment by visiblefrank** [comment]
Hi Alvaro. I'm trying to use the responsive option on ios8 but it disables any scrolling at all. The page loads but i cannot scroll down it. Something I'm missing? Thanks.

<script type="text/javascript">
     $(document).ready(function() {
 	    $('#fullpage').fullpage({
 		    anchors: ['firstPage', 'secondPage', 'thirdPage', 'fourthPage', 'fifthPage', 'sixthPage', 'lastPage'],
 				menu: '#topMenu',
 				css3: true,
 				scrollOverflow: true,
 				scrollingSpeed: 1000,
 				responsive: #500
 });

**Comment by alvarotrigo** [comment]
@visiblefrank make sure you are using the latest version of fullPage.js 2.6.5. Then let me know if you still  having the problem.

**Comment by alvarotrigo** [comment]
@visiblefrank oh, and also make sure you use the latest version of the vendor slimScroll provided by fullPage.js. It was updated a few days ago. (although the version number stills the same as a reference for the original slimScroll version. )

**Comment by visiblefrank** [comment]
Just about to get back to you. Got it working thanks. Works really well, think it was just the syntax in declaration. I had put a # before width.

Thanks for quick reply and excellent plugin! by the way here’s the site i’m using it for. www.corporatestage.ie <http://www.corporatestage.ie/>.

Frank

**Comment by mattyfew** [comment]
Hi Alvaro,

I'm having a problem similar to that described in this thread. I'm using wow.js and fullpage.js and everything was working fine, but when I set the screen resolution to mobile-size, I cannot scroll at all, yet all the animations move (that I can see). I'm not sure what to do, please help. Thanks.

**Comment by alvarotrigo** [comment]
@mattyfew sounds like you are doing something wrong. Use one of the provided examples as the base for your project. The responsiveWidth or height should do it for you.

**Comment by omarel1** [comment]
OMG I figured it out. @mattyfew I hope this helps you!! 

You use Responsive:624, but you HAVE to remove the <div class="slide"></div> that's in the examples!!! Once I did that, mobile scrolled fine without a limiting height. 

It was driving me crazy and I had a deadline to meet. So relieved.

When @alvarotrigo  said it should work and that something else was wrong with your code I was like OK so I started looking at the code that displays my slide and played with it.

Thanks @alvarotrigo for this amazing project.

**Comment by NicholasCK** [comment]
Hi Alvaro,

My site is completed, but when on mobile my anchors which are inside images do not work, neither does scroll on mobile. I am using bootstrap with fullpage js. My code for the fullpage js looks like this:

$(document).ready(function() {
			$('#fullpage').fullpage({
				// anchors: ['landingSec', 'bioSec', 'portfolioSec', 'contactSec'],
				// // sectionsColor: ['#DAC500', '#1BBC9B', '#7E8F7C'],
				// menu: '#menu',
				// navigation: false,
				// navigationPosition: 'right',
				// navigationTooltips: ['Home', 'About', 'Portfolio' , 'Contact'],
				responsiveWidth: 1100
				});
		});




and the code for my anchors look like this:

		<div id="bioIcons">
			<div class="col-xs-2 col-sm-2 col-md-3"><a href="https://www.facebook.com/iknickerbocker"><img src="icons/facebook.png"></a></div>

			<div class="col-xs-2 col-sm-2 col-md-3"><a href="https://instagram.com/iknickerbocker"><img src="icons/instagram.png"></a></div>

			<div class="col-xs-2 col-sm-2 col-md-3"><a href="https://www.linkedin.com/in/nckoretski"><img src="icons/linkedin.png"></a></div>

			<div class="col-xs-2 col-sm-2 col-md-3"><a href="https://plus.google.com/106744546536071712061"><img src="icons/google.png"></a></div>
		</div>

	</div>



May I have some input on what you think the problem could be. The anchors work on everything but mobile. 

Thank you for all your help.

-Nick

**Comment by Jashwanth1602** [comment]
@NicholasCK Hey, I am facing the same problem on mobile. Any help?

**Comment by vjrj** [comment]
@alvarotrigo https://alvarotrigo.com/fullPage/vendors/scrolloverflow.js gives me 404

**Comment by alvarotrigo** [comment]
@vjrj and? 
You have the file here in Github.

**Comment by vjrj** [comment]
Just to say that https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html (the previous sample) gives 404 in https://alvarotrigo.com/fullPage/vendors/scrolloverflow.js ... nothing more

**Comment by alvarotrigo** [comment]
@vjrj right. Thanks for that! Not that the example make use of it, but thanks anyways! I'll fix it now.
