### ISSUE TITLE
Elementor pro scrolling efects don't work with Scroll Bar false and i need Scroll Bar Overflow options for section with overflow

### ISSUE THREAD

**Issue by frehd-developer** [alvarotrigo/fullPage.js#4080]
### Description
I need to create a web like this http://le-mugs.com/en/

Option 1:
Fullpage for elementor setting:
scrollBar: true
Elementor pro scrolling effects **work**, but section with overflow move to next section **without allowing scrolling** through content.

I have a example in: http://3.137.145.174/

Option 2:
scrollBar: false,
scrollOverflow:true,
scrollOverflowOptions:{
    scrollbars:true,
    fadeScrollbars:false,
    interactiveScrollbars:true
}

Elementor pro scrolling effects **don't work**, but section with overflow move to next section **allowing scrolling** through content.

I have a example in: http://3.137.145.174/option2

Note how the animation of the sheet does not work in the option 2.

I need to work with both options, because they are exclusive. What is the appropriate configuration for me to obtain the desired result. Thank you.

### Versions 
Firefox 81

**Comment by alvarotrigo** [comment]
This forum treats issues with fullPage.js JavaScript library.

If you purchased the [official Elementor plugin for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/#contact) and choose the topic for Elementor.
