### ISSUE TITLE
Using Fading Effect with $.fn.fullpage.destroy('all') = not working?

### ISSUE THREAD

**Issue by alexkerber** [alvarotrigo/fullPage.js#4081]
Because of https://alvarotrigo.com/fullPage/extensions/fading-effect.html fullpage.extensions.min.js needs to be imported instead of fullpage.js. Looks like the function fullpage.destroy is not included there? So I can't use them together?

**Comment by alvarotrigo** [comment]
Glad you fixed your issue! :)

**Comment by alexkerber** [comment]
Haha yeah pretty obvious my fault. Really nice plugin btw!

**Comment by alvarotrigo** [comment]
Thanks! 👍
