### ISSUE TITLE
Elementor Entrance Animations already loaded for each section

### ISSUE THREAD

**Issue by raphael-h21** [alvarotrigo/fullPage.js#4083]
### Description
The Elementor entrance animations are already loaded from each section.
But if scroll to a section again it loads the animations correctly so the "Reset Elementor Animations" (Reset elementor animations on section/slide change.)  Setting works fine. But if load the Page for the first time all animations are already done. 

How can i fix that?

### Versions 
Chrome, Windows 10, Laptop

**Comment by alvarotrigo** [comment]
This forum treats issues for the fullPage.js library.

If you purchased [the official plugin for Elementor for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) then you can send us your question through the [contact form](https://alvarotrigo.com/#contact) choosing the Elementor topic.
