### ISSUE TITLE
fullPage.js for Elementor: No scrolling in mobile menue possible

### ISSUE THREAD

**Issue by cms-geek** [alvarotrigo/fullPage.js#4084]
Hello,
first of all thank you very much for this great plugin. I use fullPage.js for Elementor.

For the mobile version I use the plugin Responsive Menu (https://wordpress.org/plugins/responsive-menu/). My menu contains quite a lot of items so that they are not all visible on the smartphone at a glance, but must be scrolled down. Because of fullPage.js this function does not work anymore. 

In the documentation I find the hint that you should activate the scroll bar. I have done this but unfortunately it is not possible to scroll within the mobile menu. Is there another solution here?

Best regards
Chris

**Comment by alvarotrigo** [comment]
Thanks! Glad you like it! ☺️ 

However this forum treats issues for the fullPage.js JavaScript library only.

If you purchased [the official plugin for Elementor for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) then you can send us your question through the [contact form](https://alvarotrigo.com/#contact) choosing the Elementor topic.
