### ISSUE TITLE
How to make scrolling inside section work with FullPageJs?

### ISSUE THREAD

**Issue by funlee** [alvarotrigo/fullPage.js#4086]
see this demo: http://bd-data-visualization-web-product.k8s.101.com/publishPage?type=largeScreen&screen_id=1608&screen_key=1a6aab83-fbac-43d8-bee2-186127de5f4a

![image](https://s1.ax1x.com/2020/10/21/BPuqv4.png)

I use the library react-fullpage

Here is the options i am using

``` javascript
{
  controlArrows: true,
  dragAndMove: "fingersonly",
  easing: "easeInOutCubic",
  fitToSection: true,
  keyboardScrolling: false,
  loopBottom: true,
  navigation: false,
  scrollOverflow: true,
  scrollOverflowOptions: {
    preventDefault: false
  }
}
```

**Comment by alvarotrigo** [comment]
Just use the option `normalScrollElements`. 
See the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) where you'll be able to find an example on the option description.

**Comment by funlee** [comment]
> Just use the option `normalScrollElements`.
> See the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) where you'll be able to find an example on the option description.

thanks

**Comment by funlee** [comment]
> Just use the option `normalScrollElements`.
> See the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) where you'll be able to find an example on the option description.

after I use the option `normalScrollElements`, I see this error in chrome console
![image](https://user-images.githubusercontent.com/20290821/96722388-e4ab5300-13df-11eb-82c5-c1c7bbdf9963.png)

**Comment by alvarotrigo** [comment]
Make sure to use the latest fullpage.js version 3.0.9.

**Comment by funlee** [comment]
> Make sure to use the latest fullpage.js version 3.0.9.

I use the library [react-fullpage](https://github.com/alvarotrigo/react-fullpage), and update it just now

![image](https://s1.ax1x.com/2020/10/21/BPabut.png)

**Comment by alvarotrigo** [comment]
Latest is 0.1.18 :) 
https://www.npmjs.com/package/@fullpage/react-fullpage

**Comment by funlee** [comment]
> 0.1.18

Thank you very much, I solved the problem.
