### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CMMchado2017** [alvarotrigo/fullPage.js#4087]
Hi Alvaro,

I´m working with fullpage.js, it´s working, but our site structure is by tab.. 

I prepared 2 tabs 'Direto ao Ponto' and 'Como funciona', 

At 'Direto ao Ponto', plugin works, change to 'Como Funciona' ( i have a div with same way of first page) not working, 

I have the error:

Uncaught TypeError: Cannot read property 'previousElementSibling' of undefined
at until (fullpage.js:3740)
at prevUntil (fullpage.js:3752)
at moveSectionUp (fullpage.js:425)
at scrolling (fullpage.js:1400)
at HTMLDocument.MouseWheelHandler (fullpage.js:1579)

And returning 'Direto ao Ponto' from 'Como funciona', plugin stop, same error

Uncaught TypeError: Cannot read property 'previousElementSibling' of undefined
at until (fullpage.js:3740)
at prevUntil (fullpage.js:3752)
at moveSectionUp (fullpage.js:425)
at scrolling (fullpage.js:1400)
at HTMLDocument.MouseWheelHandler (fullpage.js:1579)

My partner and bussiness associate will follow this email too!

My conclusion

plugin is not loading! I need a help! I don´t know why!

Url to see the site: http://homologa-creddef1.hospedagemdesites.ws/

It´s necessary to use the real url because it´s a complex situation.  And we have a video!

[WhatsApp Video 2020-10-21 at 20.01.42.zip](https://github.com/alvarotrigo/fullPage.js/files/5422564/WhatsApp.Video.2020-10-21.at.20.01.42.zip)

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by CMMchado2017** [comment]
But my case is more complex Alvaro!
Use my website url

**Comment by CMMchado2017** [comment]
I´m waiting for your help.. I have to fix it... but it´s not necessary jsfiddle.

**Comment by alvarotrigo** [comment]
Sure no problem!
Please make sure to [acquire a Business license](https://alvarotrigo.com/fullPage/pricing/) and you'll get access to premium support that includes checking websites instead of isolated reproductions for a maximum period of 1 hour.

**Comment by CMMchado2017** [comment]
@alvarotrigo I don´t agree, I re-inforce with jsfiddle I can´t reproduce.. Please help me this time

**Comment by alvarotrigo** [comment]
Every bug can and should be isolated for further investigation. Unfortunately I can't help you here unless you get the Business license.
