### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CMMchado2017** [alvarotrigo/fullPage.js#4088]
Sorry @alvarotrigo I need your help! Help-me it´s a simple question!
I don´t need to buy Bussiness License.

**Comment by CMMchado2017** [comment]
I need to insist with you. I bought the license.

**Comment by CMMchado2017** [comment]
@alvarotrigo Help me..

**Comment by CMMchado2017** [comment]
@alvarotrigo Help me..

**Comment by CMMchado2017** [comment]
@alvarotrigo Help me..

**Comment by alvarotrigo** [comment]
Sorry I don't have anything else to add.
