### ISSUE TITLE
How to temporarily lock scrolling?

### ISSUE THREAD

**Issue by kirill-zhirnov** [alvarotrigo/fullPage.js#4091]
### Link to isolated reproduction with no external CSS / JS
https://codepen.io/kirill-zhirnov/pen/NWrpdXJ

### Steps to reproduce it
1. Click on the button "Toggle menu".
2. Button opens aside menu - it has own scroll inside. I want scrolling to be active only in aside menu, page scrolling should be locked when menu is opened.

How can I do it programmatically, via the API?

Thank you!

**Comment by alvarotrigo** [comment]
Use the option `normalScrollElements` for that.
More about it on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

**Comment by kirill-zhirnov** [comment]
Thanks for the answer.

It isnt what I'm looking for - even if I add the option `normalScrollElements` - the fullpage.js scrolling is still exist if mouse pointer is under the e.g toggle button.

The flow is:
1) open menu
2) lock scroll with the https://www.npmjs.com/package/body-scroll-lock

Second step won't work. That is why I'm asking - how to temporarily disable the fullPage.js listeners.

**Comment by alvarotrigo** [comment]
Right.
Then see the `setAllowScrolling` method :)

Everything is in the docs:
https://github.com/alvarotrigo/fullPage.js#setallowscrollingboolean-directions
