### ISSUE TITLE
create a scroll threshold but keep fullpage behaviour

### ISSUE THREAD

**Issue by antonello-alfatauristudio** [alvarotrigo/fullPage.js#4093]
### Description

Isn the dragandmove extension the user can drag and the page scrolls until it release the key. Is there a way to to the same way with scroll? In the way that the user scroll with pad/mouse and the page follows it but then when it stops scrolling it moves to the nearest page.

I can't find a way to do it.

**Comment by alvarotrigo** [comment]
Sure! 
See this demo regarding the option `fitToSection` that get used in combination with `autoScrolling:false`

https://codepen.io/alvarotrigo/pen/GJXNYm
