### ISSUE TITLE
cant install fullpage.js plug in

### ISSUE THREAD

**Issue by CSnickspencer** [alvarotrigo/fullPage.js#4094]
I have been trying to install the full page.js plug in on my site but its saying "The package could not be installed. No valid plugins were found." Anyone got any idea why this is?

**Comment by alvarotrigo** [comment]
fullPage.js is not an installable plugin.
It is a JavaScript library.

If you are using wordpress you can find installable plugins for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) builders and soon for Divi.
