### ISSUE TITLE
Method to get scroll

### ISSUE THREAD

**Issue by MattTrovao** [alvarotrigo/fullPage.js#4096]
Hey everyone, not really a issue, but there is a method, or a way to get the scroll with the plugin? I need create a custom scroll bar, I was trying to make by myself but need this method.

**Comment by alvarotrigo** [comment]
Why not using the normal scroll bar?
Or customise the normal one?

You can use the option `scrollBar:true` as in this example:
https://alvarotrigo.com/fullPage/examples/scrollBar.html

**Comment by MattTrovao** [comment]
The designer create a diferent scroll bar, but i think i found one way to do.
