### ISSUE TITLE
A way to temporarily disable scrolling

### ISSUE THREAD

**Issue by BlazPerus** [alvarotrigo/fullPage.js#4097]
Hey,

is there a way to temporarily disable the scrolling? 

I have a scenario where I'm opening a fullscreen menu on top of the page and when it's open I'd like to disable scrolling and resume the moment I'm exiting the fullscreen menu. 

It becomes a problem because there are some events linked to scrolling and it changes menu appearance and I'd like to fix that.

Couldn't find any nice solutions.

Thanks

**Comment by alvarotrigo** [comment]
No problem! Glad you managed to find a solution! :)
