### ISSUE TITLE
Slider Navigation Code is generating before the </body>

### ISSUE THREAD

**Issue by saysonjerald** [alvarotrigo/fullPage.js#4098]
### Description
I want to make an animation on the slider bullets using Javascript but the thing is that can't access the DOM of `id="fp-nav"` because the navigation is has been generated before the `</body>` and after my `<script src="myCustomScript.js">` which is my main JSscript.

this is how it looks like on the DevTools
```
...
...
<script scr="fullscreen.js"></script>
<script scr="myCustomScript.js"></script>
<div id="fp-nav" class="fp-left">
....
</div>
</body>
</html>
```

### Steps to reproduce it
1. Is there a way to put it on the top? like after the `<body>` tag?

**Comment by alvarotrigo** [comment]
Mmm have you tried running your JS  inside the `load` event?

```js
window.addEventListener('load', onLoad);

function onLoad(){
    //your code here
}
```

**Comment by alvarotrigo** [comment]
> Is there a way to put it on the top? like after the <body> tag?

There's no out of the box way to do it now, but that's a good point!

So far, you could make use of the `afterRender` function to access to it or even to move it wherever you want.


```js
new fullpage({
        //your options here...
       afterRender: function(){
               // now you have access to the #fp-nav 
        }
});
```

**Comment by saysonjerald** [comment]
Yes it's working, thanks man.

**Comment by alvarotrigo** [comment]
Awesome! 👍
