### ISSUE TITLE
scrollOverflowReset not working

### ISSUE THREAD

**Issue by soxy95** [alvarotrigo/fullPage.js#4099]
### Description
The extension scrollOverflowReset not working well

### You can see the problem here section 3
https://dev.lafischduweb.com/

I enqueue the different files in this order : 

`<link rel='stylesheet' id='fullpage_style-css'  href='https://dev.lafischduweb.com/wp-content/themes/alufey/css/fullpage.css?ver=5.5.3' type='text/css' media='all' />`

`<script type='text/javascript' src='https://dev.lafischduweb.com/wp-content/themes/alufey/js/fullpage.scrollOverflowReset.min.js' id='overflowscrollreset-js'></script>`

`<script type='text/javascript' src='https://dev.lafischduweb.com/wp-content/themes/alufey/js/fullpage/dist/fullpage.extensions.min.js' id='exensions_fullpage-js'></script>`

```
    new fullpage('#home_alufey', {
      licenseKey: 'EF8386E7-56744451-AFDBA5DC-B1608A01',
      sectionsColor: ['yellow', '#d7e2ee', 'yellow', 'yellow'],
      // sectionsColor: ['#303030', '#303030', '#303030', '#303030'],
      navigation:true,
      menu:'#menu-top_menu',
      css3:true,
      scrollOverflowReset: true,
      afterLoad: function (anchorLink, index) {
          var currentIndex = index.index ;
          var prevIndex = currentIndex - 1;
            $('#fp-nav ul li').eq(prevIndex).find('a').removeClass('active');
            $('#fp-nav ul li').eq(currentIndex).find('a').addClass('active');            
            $('#menu-top_menu li').eq(prevIndex).find('a').removeClass('active');
            $('#menu-top_menu li').eq(currentIndex).find('a').addClass('active');
            var sizeSlider = $(window).height();
            $('.slider_home').height(sizeSlider);
            $('.slider_home').not('.slick-initialized').slick({
              prevArrow:"<span class='prev_arrow'>&#9001;</span>",
              nextArrow:"<span class='next_arrow'>&#9002;</span>"
            })
      },
    });
```

There isn't any message in the console.

I know there is wordpress plugin for fullpage.js but i can't to use it for differents reasons.

**Comment by alvarotrigo** [comment]
ScrollOverflowReset requires the option `scrollOverflow:true` as can be seen on the example file that comes with the extension as well as on the demo page:
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html#3rdPage

And to use `scrollOverflow:true` you'll also need to import on the page the file `vendors/scrolloverflow.min.js` as detailed on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) and as it is also visible on the example file.

I hope that answers your question ;)
