### ISSUE TITLE
browser resizing block autoscrolling feature

### ISSUE THREAD

**Issue by krishnaprasadkckp** [alvarotrigo/fullPage.js#4100]
Hi @alvarotrigo ,
I'm using horizontal slides and vertical sections. If resized the browser, autoscrolling will be blocked. 
To troubleshoot, I've added reBuild() function within window resize, but no hope. - 

```js 
$(window).resize(function () {
    // fullpage_api.reBuild();
});
```

similarly if I set **scrollOverflow to false** this autoscrolling will work without any issues but I can't make false because some slides and sections have long content. 

```js 
`scrollHorizontally: true,
loopHorizontal: false,


lockAnchors: true,


fixedElements: '[data-menu-wrap]',
anchors: ['1', '', '2', '3', '4', '5', '6', '7'],
menu: ['[home-quick-menu]', '[menu]'],
css3: true,
scrollingSpeed: 700,
autoScrolling: true,
scrollOverflow: true,

onLeave: function (origin, destination, direction) {

},

afterLoad: function (origin, destination, direction) {
	
},

afterSlideLoad: function (section, origin, destination, direction) {
	
},

onSlideLeave: function (section, origin, destination, direction) {
	
},

afterResize: function (width, height) {
},`
```

**Comment by alvarotrigo** [comment]
> To troubleshoot, I've added reBuild() function within window resize, but no hope. -

That's definitely not the way to go.
With that you'll only generate performance issues as that would be called hundreds of times on every resize. 

What's wrong with the default behaviour? What do you mean by "it blocks auto scrolling" ?

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
