### ISSUE TITLE
content-responsive height with DragAndMove ?

### ISSUE THREAD

**Issue by gauini** [alvarotrigo/fullPage.js#4101]
Hi Alvaro, 

I'm using fullpage on a local website that has three sections (variable heights depending on user's selection / data pulled) within a slide. this website will be running on an touchscreen so i need to use the dragandmove extension and i understand it doesn't wor kas of now with scrolloverflow so i'd like to know what would you recommend me doing in order to make this ~ work. 

i thought of rebuilding fp everytime i load my content / move between sections, but i haven't been able to resize the slide when rebuilding so maybe you have other suggestions or specific ways of doing so? maybe there is a way that i can put them in separate slides and change the direction that the slides transition (instead of vertical, to transition horizontally like the sections)?

let me know what you recommend and thanks again for maintaining the library!

**Comment by alvarotrigo** [comment]
> this website will be running on an touchscreen so i need to use the dragandmove extension

Not necessarily.
fullpage.js will still work on touch devices without the extension. The extension is just an enhancement in the way the touch behaviour works. 

Probably that's your best option.
Otherwise you can perhaps turn off autoScrolling on touch screen devices?

**Comment by gauini** [comment]
yeah, autoScrolling is already set as false and it still doesn't work...i'll try to investigate a few options. thanks in any case!

**Comment by alvarotrigo** [comment]
I assume you are using the `responsiveWidth` or `responsiveHeight` options to turn it to false?
Otherwise use `fullpage_api.setResponsive(true);`

This will make sure you can use `fp-auto-height-responsive` to allow sections bigger than the viewport height when on responsive mode. 

This will allow you to see all content without even using scrollOverflow. 
Like the example:
https://alvarotrigo.com/fullPage/examples/autoHeightResponsive.html

**Comment by gauini** [comment]
hm I was disabling autoScroll through autoScrolling: false

but then I removed it and defined a responsiveHeight, kept the scrollOverflow +rest, removed the dragAndMove and it's all good now! thanks Alvaro.

**Comment by alvarotrigo** [comment]
No problem! Glad you got it working! ;)
