### ISSUE TITLE
On Android, the onLeave method stops working if the browser top bar is disappears

### ISSUE THREAD

**Issue by Xugo-23** [alvarotrigo/fullPage.js#4102]
### Description
On Android, the `onLeave` method stops working if the browser top bar is disappears
On a real project scrips stops working (sticky header / animation etc)
**Reproduced only on a real device**

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/Xugo/full/LYZJjPZ

### Steps to reproduce it

1. Open [link](https://codepen.io/Xugo/full/LYZJjPZ) on Android
2. Scroll the page (When you scroll, you can see in the console the `onLeave` method-specific changes)
3. Click on the **Menu button**
4. Scroll the menu to the bottom until the browser top bar on your phone disappears

<details>
 <summary>Screenshot</summary>
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/71509500/98414948-f6018a00-2084-11eb-85cd-0d916dc7f231.jpg"><img src="https://user-images.githubusercontent.com/71509500/98414948-f6018a00-2084-11eb-85cd-0d916dc7f231.jpg" alt="image" style="max-width:100%;"></a>
</details>

5. Close the menu
6. After that, you will not see the changes in the console, which means that the `onLeave` method has stopped working (**Reproduced on a real project**)
### Versions 
Device: Moto G8+
OS: Android 10
Browser: Chrome 86.0.4240.185 / Opera 60.3.3004.55692

Thank You!

**Comment by alvarotrigo** [comment]
I'm unable to reproduce the issue in Browserstack.com on a Moto G7 using real a device under:
- Chrome
- Firefox

The top bar never disappears when scrolling. 
Unfortunately I can't test it on my own device as I don't have android with me, it doesn't happen on iOS either. 

Try using `scrollBar:true` and see if the issue gets fixed.

**Comment by Xugo-23** [comment]
Unfortunately no http://prntscr.com/vewjvf

**Comment by Xugo-23** [comment]
Just in case, I will clarify that I meant this bar (It looks like it only disappears on android)

<details>
 <summary>See Screenshot</summary>
<a href="https://user-images.githubusercontent.com/71509500/98421798-e2f5b680-2092-11eb-850a-9142ad2c1143.jpg" rel="nofollow"><img src="https://user-images.githubusercontent.com/71509500/98421798-e2f5b680-2092-11eb-850a-9142ad2c1143.jpg" alt="image" style="max-width:100%;"></a>
</details>

**Comment by alvarotrigo** [comment]
Have you tried using `scrollBar:false` too? This way the top bar shouldn't get hidden.

**Comment by Xugo-23** [comment]
> Have you tried using `scrollBar:false` too? This way the top bar shouldn't get hidden.

I tried. The top bar is hidden anyway. I am trying to prevent the bar from being hidden. But I haven't found solutions yet

**Comment by alvarotrigo** [comment]
Do you get the same behaviour on pages like this one?
https://alvarotrigo.com/fullPage/examples/continuous.html

**Comment by Xugo-23** [comment]
So. When I just scroll the page using the fullPage.js plugin, the top bar never hides. And when I open the menu (position: fixed) and scroll the content to the very bottom, the top bar appears (And the `onLeave` method stops working for some reason)

I think I need to achieve similar behavior for the fixed menu (CSS or JS).
Also I'm not sure if this is a bug. And at your discretion, you can close this issue.

Thank You!

**Comment by Xugo-23** [comment]
I suspect that you need to calculate the real size of the viewport and pass this height to the menu. Menu height is now `100vh`

**Comment by Xugo-23** [comment]
Yes. Helped set viewport size for menu and `{html, body: height: 100%;}` http://anime.byethost14.com/anime/index.html

**Comment by alvarotrigo** [comment]
Awesome to hear you managed to fix the issue! 😉
