### ISSUE TITLE
Not working when implemented with a collection list

### ISSUE THREAD

**Issue by Fathomed** [alvarotrigo/fullPage.js#4103]
Hi There,
When used with a collection list in Webflow - where each item in the list is a full-page section, it does seem to work. The loaded page is locked to the first section with no scrolling available. 

Here's the test link: [https://dickey-boats-dev-site-777-cd408bec089b0.webflow.io/boat-grid-test](https://dickey-boats-dev-site-777-cd408bec089b0.webflow.io/boat-grid-test)

**Comment by alvarotrigo** [comment]
I have no idea what a collection list in webflow is 😆 

But as long as you follow the [required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure), it should work. 
So very probably your problem is there.

**Comment by Fathomed** [comment]
> I have no idea what a collection list in webflow is 😆
> 
> But as long as you follow the [required structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure), it should work.
> So very probably your problem is there.

@alvarotrigo - After extensive testing, there does appear to be a collection list (CMS list) problem in Webflow - it works perfectly outside the CMS list but not inside it. Perhaps you would like to take another look. In the meantime I've implemented an alternate solution. Thanks. FYI - I've purchased a licence and cannot use it.

**Comment by alvarotrigo** [comment]
Sure, if you please reproduce your issue in codepen or jsfiddle I'll happily take a look at it.

If you want me to check your webflow page you'll need to acquire the Business license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/), as it's the only one providing premium support.

**Comment by Fathomed** [comment]
Obviously I cant reproduce a dynamic Webflow CMS in codepen or jsfiddle. Also not going to buy a premium licence for something that isn't proven to work in a dynamic CMS. Perhaps you could send a link to Fullpage JS working inside a dynamic list, that way I can solve the issue myself, if it solve-able and not a problem with the JS solution.

**Comment by alvarotrigo** [comment]
Webflow is just an editor to edit HTML and CSS code, and perhaps a bit of JS.
So, anything that can be done in webflow can be reproduced in codepen or jsfiddle :) 

I have no idea what a "dynamic list" in webflow means in terms of HTML/CSS/JS so unfortunately I can't help you there. Perhaps you can try asking on webflow forums where they'll know much more about webflow terms and what they actually mean in terms of code.

Hope you find a solution!

**Comment by alvarotrigo** [comment]
If by dynamic list you mean the slides / sections are added dynamically after page load and after fullPage.js gets initialised, then you'll have to destroy and initialise fullpage.js with any DOM change. 

Or if it is easier, wait until all the content loads and then  initialise fullPage.js.

**Comment by Fathomed** [comment]
The dynamic list is populated from a list of posts in the content management system. In this case, each 'list item' on the page is the hero image from each post, wrapped in a div with the class of 'section' set to 100 vh. 
In the best Webflow example I've seen of Fullpage.js, each 'section' is given a custom attribute - data-anchor="firstSlide", data-anchor="secondSlide" etc. For your reference, here is the link: https://webflow.com/website/fullpage-js-interactions
Unfortunately, it's not possible to assign custom attributes to the 'sections' which a children of a dynamic list. Perhaps this is the source of the issue?

**Comment by alvarotrigo** [comment]
No idea.
