### ISSUE TITLE
When scrolloverflow is set to true, Cannot make the vimeo video fullscreen

### ISSUE THREAD

**Issue by mohomedanees** [alvarotrigo/fullPage.js#4104]
Hi I've set to scrolloverflow: true that will automatically enable scroll wherever it's needed. But how can I get rid of this when open an iframe video which is vimeo or youtube in fullscreen the video is getting closed in fullpage.

How can I resolve this issue?

new fullpage('#fullpage', {
        anchors: anchors,
        navigation: true,
        css3: true,
        navigationPosition: 'right',
        bigSectionsDestination: 'top',
        scrollOverflow: true,
        scrollOverflowReset: true,
        scrollingSpeed: 800,
        easingcss3: 'cubic-bezier(.455, .03, .515, .955)',
});

And I'm trying to use this function when on fullscreen and exit from fullscreen.
$(window).resize(checkResize);

          function checkResize() {
            if (
              document.fullscreenElement ||
              document.webkitFullscreenElement ||
              document.mozFullScreenElement ||
              document.msFullscreenElement
            ) {
              console.log('full');
              fullpage_api.reBuild();
            } else {
              console.log('fullexit');
              fullpage_api.reBuild();
            }
          }

This didn't work either. How can I fix this. I think this should be a fix in fullpage.js with scrollOverflow: true. 

Please help me to resolve this issue.

**Comment by alvarotrigo** [comment]
It's a problem on the external library used by fullpage.js for scrolloverflow. 
I [reported it long time ago on iScroll.js](https://github.com/cubiq/iscroll/issues/1078) but the library hasn't been maintained since.

Try passing this options on the fullpage.js option `scrollOverflowOptions`:

```js
scrollOverflowOptions: {
	click: false,
	preventDefaultException: { tagName:/.*/ }
},
```


Or this:

```js
scrollOverflowOptions: {
	click: true,
	preventDefaultException: { tagName:/.*/ }
},
```

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/2837

**Comment by mohomedanees** [comment]
Hi Alvaro,

The solution above also didn't work either.

**Comment by alvarotrigo** [comment]
Also related with https://github.com/alvarotrigo/fullPage.js/issues/2139.
I would recommend you researching a bit on the [iScroll issues forum](https://github.com/cubiq/iscroll/issues).

**Comment by mohomedanees** [comment]
Thank you Alvaro.

**Comment by mohomedanees** [comment]
Alvaro I would say it's better for you to change the plugin that you use for fullpage.js if the scroll plugin in not maintained anymore.

**Comment by alvarotrigo** [comment]
Easy to say, not as easy to do :)
But yeah perhaps in a future.

**Comment by mohomedanees** [comment]
I know it's a hard thing. If you change it no more issues with iScroll then 😄
