### ISSUE TITLE
Element inside fullPage.js which uses scroll event for something different

### ISSUE THREAD

**Issue by cueqzapper** [alvarotrigo/fullPage.js#4105]
### Description
I have an element on which I want to detect scrolling and using it for zooming and prevent the default behavior of fullPage.js.

I set scrollBar: true.

I added 4 different tests, with different methods from Stackoverflow, nothing works.

Use case:
On my website I need the scroll action for zooming on a map. The scroll should work outside of the map but over the map it should zoom and not scroll.

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/fs1a2o3n/

### Steps to reproduce it
1. Open the console
2. Hover with the mouse over the red square and scroll
3. There is no logging in the console. 

### Versions 
I am seeing this behavior with Chrome Version 86.0.4240.198

**Comment by cueqzapper** [comment]
Issue solved by using this option: 

normalScrollElements: '#elementId',

**Comment by alvarotrigo** [comment]
Awesome to hear you managed to solve it :)
