### ISSUE TITLE
Multiple Sections Loading at Once

### ISSUE THREAD

**Issue by nnabros** [alvarotrigo/fullPage.js#4106]
### Description

I have an implementation where I have 4 sections, the 1st one is video and the other 3 have background images. The problem is that on load, the 2nd section (on desktop) and 4th section (on mobile) briefly show before the 1st section (the video one) then displays. This makes the page appear distorted for a couple of seconds. I have gone through similar related issues but the recommended CSS fixes don't work. Actually using 1 of the CSS actually removes the 1st section that has the video.

**Comment by alvarotrigo** [comment]
See my answer here:
https://github.com/alvarotrigo/fullPage.js/issues/3425#issuecomment-425107252

**Comment by nnabros** [comment]
I went through that in detail and implemented the CSS. Like mentioned, the CSS actually removes the 1st slide that has a video.
