### ISSUE TITLE
Full website background-image

### ISSUE THREAD

**Issue by RiccardoCarella** [alvarotrigo/fullPage.js#4107]
### Description
Is there a way to set a background image for the entire website? If I apply a bg-image to the `<div id="fullpage">` it will only be applied to the first section.
### Link to isolated reproduction with no external CSS / JS
My code structure is this one:

**HTML**
```
<div id="fullpage">
            <div class="section"></div>
            <div class="section"></div>
            <div class="section"></div>
</div>
```

**CSS**
```
#fullpage {
	background-image: url(/Assets/BG.png);
	background-position: top;
	background-size: cover;
	background-repeat: repeat-y;
}
```

![Desktop Screenshot 2020 11 18 - 02 41 25 48 (3)_LI](https://user-images.githubusercontent.com/72451708/99472016-0d275e00-2948-11eb-892b-d975cdb1910f.jpg)

It gets perfectly cut on the line that divides the first and the second section.
### Versions 
Fullpage version: 3.09

**Comment by alvarotrigo** [comment]
Apply it to the `body` element instead:
https://jsfiddle.net/t1amd7ns/
```css
body{
    background: red;
}
```
