### ISSUE TITLE
 Header height is subtracted from the section height

### ISSUE THREAD

**Issue by tebaaatusasula** [alvarotrigo/fullPage.js#4108]
When the page loads, the following css is added to the div that contains id = "fullpage". 

transform: translate3d (0px, -120px, 0px);

120px is the height of the navigation div. This value is shifted upward.

The nav div is inside div id = "fullpage" and has position: absolute to overlay on top of the background image.

Is there any solution or am I doing something wrong?

PS The license was purchased today from the MASTERCARD * 8676

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by tebaaatusasula** [comment]
Thanks! The problem has been resolved.

When reproducing with minimal use of third-party code, everything works correctly.

In my case, the problem was in the order in which the styles were loaded.

**Comment by alvarotrigo** [comment]
Glad you managed to solve it!
