### ISSUE TITLE
Anchor links not working WordPress Elementor all steps and screenshots.

### ISSUE THREAD

**Issue by miomate** [alvarotrigo/fullPage.js#4109]
Hello,
our company want to use fullpage.js, I am building a demo site for a presentation.
Could you go through creating links with me? I am using the [docs](https://github.com/alvarotrigo/fullPage.js/#fullpagejs) but the descriptions are a little to complicated for me.
Our site runs on WordPress and as page builder we use Elementor.
Everything works smoothly, we have 3(sections?) vertical and 3 horizontal slides.
We have a single page site, subpages (imprint etc.) will not use fullPage.js

### Description
I am using a plugin to run additional HTML/JS files. 
For JS I have the following code:
```js
jQuery(document).ready(function($) {
    $('#fullpage').fullpage({
        //options here
        scrollingSpeed: 1000,
        navigation: true,
        slidesNavigation: true,
		responsive: 800,
    });
    //methods
    $.fn.fullpage.setAllowScrolling(true);
});
``` 
**Edit:**To start creating anchors I would add to the JS file above the following:
I think I only need firstPage, because we have only one page.
```js
new fullpage('#fullpage', {
	anchors:['firstPage']
});
```
I nested this function inside `jQuery(document).ready(function($) {` for testing, without any change, links still not working.

This is my skeleton Elementor file, all sections/slides are created as templates and linked with short codes in this file:
```html
<div id="fullpage">
    <div class="section">[elementor-template id="1882"]</div>
      ...
    <div class="section">
        <div class="slide">[elementor-template id="1863"]</div>
        ...</div></div>
```
Now I would add `data-anchor=''` an attribute to each section.
```html
<div id="fullpage">
    <div class="section" data-anchor='slide1' >[elementor-template id="1882"]</div>
      ...
    <div class="section">
        <div class="slide" data-anchor='slide1>[elementor-template id="1863"]</div>
        ...</div></div>
```
Question: Can I call sections `data-anchor='section1'` and slides (horizontal) `data-anchor='slide1'`?
I guess not, because all anchors #secondPage/0 #secondPage/1 #secondPage/2
***EDIT:**: When I open the page the url is: namedomain.com/ when I scroll the url changes
namedomain.com/#slide2 /#slide3 /#slide4 that means the data-anchor attribute works.

Now the links, which will be plain links on our site, no buttons:

```html
<a href="#firstPage/0">Section 1</a>
<a href="#firstPage/1">Section 2</a>
<a href="#firstPage/x">Slide 1</a> //first horizontal slide, have to count
<a href="#firstPage/x+1">Slide 1</a>
```
I tried #firstPage/0 #slide1 etc.
Here the steps I tried:
https://i.imgur.com/X1vGxG6.png

### Link to isolated reproduction with no external CSS / JS
-

### Steps to reproduce it
-

### Versions 
Newest chrome and FF
WP: 5.5.3
Elementor:  3.0.8.1

**Comment by alvarotrigo** [comment]
If you are using the official plugin for Elementor for fullPage.js, then you can contact us using the [contact form](https://alvarotrigo.com/#contact).

Otherwise unfortunately we do not cover wordpress issues here. Only JS related questions. 
If you think you can isolate your problem in codepen or jsfiddle then that'd be great!
