### ISSUE TITLE
license key cannot be read

### ISSUE THREAD

**Issue by rrosegregoryy** [alvarotrigo/fullPage.js#4111]
Hi!

I just purchased a licence for fullpage but I'm getting an error when I inspect that it's not readable or undefined. (And there's another issue but I thought I'll tackle this one first as it might be related).

I'm inspecting in Chrome from a Macbook Pro 13inch.

I'm working in Webflow and here is what I put in my <head> tag:

`<style>
/*!
* fullPage 2.9.7
* https://github.com/alvarotrigo/fullPage.js
* MIT licensed
*
* Copyright (C) 2013 alvarotrigo.com - A project by Alvaro Trigo

*/
html.fp-enabled,
.fp-enabled body {
   margin: 0;
   padding: 0;
   overflow:hidden;

   /*Avoid flicker on slides transitions for mobile phones #336 */
   -webkit-tap-highlight-color: rgba(0,0,0,0);
}

.fp-section {
   position: relative;
   -webkit-box-sizing: border-box; /* Safari<=5 Android<=3 */
   -moz-box-sizing: border-box; /* <=28 */
   box-sizing: border-box;
}

.fp-slide {
   float: left;
}

.fp-slide, .fp-slidesContainer {
   height: 100%;
   display: block;
}

.fp-slides {
   z-index:1;
   height: 100%;
   overflow: hidden;
   position: relative;
   -webkit-transition: all 0.3s ease-out; /* Safari<=6 Android<=4.3 */
   transition: all 0.3s ease-out;
}

.fp-section.fp-table, .fp-slide.fp-table {
   display: table;
   table-layout:fixed;
   width: 100%;
}

.fp-tableCell {
   display: table-cell;
   vertical-align: middle;
   width: 100%;
   height: 100%;
}

.fp-slidesContainer {
   float: left;
   position: relative;
}

.fp-controlArrow {
   -webkit-user-select: none; /* webkit (safari, chrome) browsers */
   -moz-user-select: none; /* mozilla browsers */
   -khtml-user-select: none; /* webkit (konqueror) browsers */
   -ms-user-select: none; /* IE10+ */
   position: absolute;
   z-index: 4;
   top: 50%;
   cursor: pointer;
   width: 0;
   height: 0;
   border-style: solid;
   margin-top: -38px;
   -webkit-transform: translate3d(0,0,0);
   -ms-transform: translate3d(0,0,0);
   transform: translate3d(0,0,0);
}

.fp-controlArrow.fp-prev {
   left: 15px;
   width: 0;
   border-width: 38.5px 34px 38.5px 0;
   border-color: transparent #fff transparent transparent;
}

.fp-controlArrow.fp-next {
   right: 15px;
   border-width: 38.5px 0 38.5px 34px;
   border-color: transparent transparent transparent #fff;
}

.fp-scrollable {
   overflow: hidden;
   position: relative;
}

.fp-scroller{
   overflow: hidden;
}

.iScrollIndicator{
   border: 0 !important;
}

.fp-notransition {
   -webkit-transition: none !important;
   transition: none !important;
}

#fp-nav {
   position: fixed;
   z-index: 100;
   margin-top: -32px;
   top: 50%;
   opacity: 1;
   -webkit-transform: translate3d(0,0,0);
}

#fp-nav.right {
   right: 17px;
}

#fp-nav.left {
   left: 17px;
}

.fp-slidesNav{
   position: absolute;
   z-index: 4;
   opacity: 1;
   -webkit-transform: translate3d(0,0,0);
   -ms-transform: translate3d(0,0,0);
   transform: translate3d(0,0,0);
   left: 0 !important;
   right: 0;
   margin: 0 auto !important;
}

.fp-slidesNav.bottom {
   bottom: 17px;
}

.fp-slidesNav.top {
   top: 17px;
}

#fp-nav ul,
.fp-slidesNav ul {
 margin: 0;
 padding: 0;
}

#fp-nav ul li,
.fp-slidesNav ul li {
   display: block;
   width: 14px;
   height: 13px;
   margin: 7px;
   position:relative;
}

.fp-slidesNav ul li {
   display: inline-block;
}

#fp-nav ul li a,
.fp-slidesNav ul li a {
   display: block;
   position: relative;
   z-index: 1;
   width: 100%;
   height: 100%;
   cursor: pointer;
   text-decoration: none;
}

#fp-nav ul li a.active span,
.fp-slidesNav ul li a.active span,
#fp-nav ul li:hover a.active span,
.fp-slidesNav ul li:hover a.active span{
   height: 12px;
   width: 12px;
   margin: -6px 0 0 -6px;
   border-radius: 100%;
}

#fp-nav ul li a span,
.fp-slidesNav ul li a span {
   border-radius: 50%;
   position: absolute;
   z-index: 1;
   height: 4px;
   width: 4px;
   border: 0;
   background: #333;
   left: 50%;
   top: 50%;
   margin: -2px 0 0 -2px;
   -webkit-transition: all 0.1s ease-in-out;
   -moz-transition: all 0.1s ease-in-out;
   -o-transition: all 0.1s ease-in-out;
   transition: all 0.1s ease-in-out;
}

#fp-nav ul li:hover a span,
.fp-slidesNav ul li:hover a span{
   width: 10px;
   height: 10px;
   margin: -5px 0px 0px -5px;
}

#fp-nav ul li .fp-tooltip {
   position: absolute;
   top: -2px;
   color: #fff;
   font-size: 14px;
   font-family: arial, helvetica, sans-serif;
   white-space: nowrap;
   max-width: 220px;
   overflow: hidden;
   display: block;
   opacity: 0;
   width: 0;
   cursor: pointer;
}

#fp-nav ul li:hover .fp-tooltip,
#fp-nav.fp-show-active a.active + .fp-tooltip {
   -webkit-transition: opacity 0.2s ease-in;
   transition: opacity 0.2s ease-in;
   width: auto;
   opacity: 1;
}

#fp-nav ul li .fp-tooltip.right {
   right: 20px;
}

#fp-nav ul li .fp-tooltip.left {
   left: 20px;
}

.fp-auto-height.fp-section,
.fp-auto-height .fp-slide,
.fp-auto-height .fp-tableCell{
   height: auto !important;
}

.fp-responsive .fp-auto-height-responsive.fp-section,
.fp-responsive .fp-auto-height-responsive .fp-slide,
.fp-responsive .fp-auto-height-responsive .fp-tableCell {
   height: auto !important;
}

</style>`

And here is what I put before the end of my <body> tag:

`<script type="text/javascript" src="https://unpkg.com/fullpage.js/dist/fullpage.min.js"></script>

<script>
   // fullpage.js initialization
   new fullpage('#fullpage', {
   	  scrollingSpeed: 1000,
   	  verticalCentered: false
   });
   
   new fullpage({
    licenseKey: 'A43D2B94-424349C4-8D76B190-5B21CD14'
});
</script>

<script>
$(document).ready(function() {
$('#fullpage').fullpage({
    anchors: ['landing', 'work', 'services', 'info']
});
});
</script>`

I've tried multiple variations of the above from hours of looking in forums and at tutorials but the above is the only way that I can get it to work (despite these errors being there). 

Here is a reproduction of my site inside webflow:
[https://studio-y-staging.webflow.io/full-page-scroll-test](https://studio-y-staging.webflow.io/full-page-scroll-test)

Here's my webflow read only link:
https://preview.webflow.com/preview/studio-y-staging?utm_medium=preview_link&utm_source=designer&utm_content=studio-y-staging&preview=a654594c52df24d8b6bb3e0ba15280fd&pageId=5fbe2ccbb0b0b42d3a91310c&mode=preview

Appreciate any help you can offer! Thank you :)

**Comment by alvarotrigo** [comment]
Please update to fullpage.js version 3. 
Version 2 is no longer supported nor maintained.

**Comment by rrosegregoryy** [comment]
Thanks for the quick reply! Could you please point me in the right direction for how to do that?

**Comment by rrosegregoryy** [comment]
Okay I think I've found it here: https://webflow.com/website/Fullpagejs-basic-example

Thank you!

**Comment by alvarotrigo** [comment]
Yeap!
