### ISSUE TITLE
Show a fullpage photo gallery with filter and horizontal swipe?

### ISSUE THREAD

**Issue by MojoDK** [alvarotrigo/fullPage.js#4112]
I need to show a photo gallery with filter like this one:
https://getuikit.com/docs/filter

Any idea if there is a gallery (with filter) that supports the fullpagejs, so I can scroll horizontal to view more photos?

Thanks

**Comment by alvarotrigo** [comment]
Good news! All of them support fullPage.js :)

You just need to integrate them as any other code.
