### ISSUE TITLE
How to change a single section height "on the fly"?

### ISSUE THREAD

**Issue by MojoDK** [alvarotrigo/fullPage.js#4115]
I use a Masonry Gallery in one of my sections - this plugin...
http://preview.codecanyon.net/item/media-boxes-portfolio-responsive-grid/full_screen_preview/5683020

In this gallery you can filter images on the fly to show more or less images.

After the Masonry Gallery plugin layout is done, I get an event with the new height of the gallery.

How can I tell a single section of fullpagejs to match the gallery height? And also if the gallery height is less than a fullpage section, then the section height must be fullpage. In other words, I only want the section to "grow" and not to shrink below a normal section height?

I do not want to use "ScrollOverflow: true".

**Comment by alvarotrigo** [comment]
Try using the [reBuild](https://github.com/alvarotrigo/fullPage.js#rebuild) method.

```js
fullpage_api.reBuild();
```

**Comment by MojoDK** [comment]
Hmmm ... using "fullpage_api.reBuild();" on a section that is now larger than the viewport, makes the fullpagejs automatically scroll to the end of the section. 😮 If I then scroll up, instead of scrolling up the same section (to the start of the section), fullpagejs instantly jumps to previous section. How can I prevent this?

**Comment by MojoDK** [comment]
This illustrates my problem...
https://codepen.io/MojoDK/pen/QWKwVKq?editors=0010

**Comment by alvarotrigo** [comment]
Use the `scrollOverflow` option as in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by MojoDK** [comment]
I've already tried and well it doesn't really work (aldo the link you sent me) ... if I scroll with the mouse whell (that typically scrolls like 3 lines), then I never get to see the last line before it scrolls to the next section. And same problem is, if I am on the next section and scroll up, I never get to the top before it scrolls to the previous section. To use scrollOverflow there needs to be some kinda extra sticking on top and bottom of the section.

**Comment by alvarotrigo** [comment]
Unfortunately there isn't a better solution for now.

**Comment by alvarotrigo** [comment]
You can try the `bigSectionsDestination` option to define whether you want to see the top or the button of it while scrolling to it, but that won't allow you to scroll up or down inside a section with a bigger height that he viewport.  

Demo:
https://codepen.io/alvarotrigo/pen/vYLdMrx

**Comment by MojoDK** [comment]
I was afraid so ... which mean that I can't (for now) use fullpagejs in my project until it has better support for sections lager than viewport. I can't have frustrated users not being able to reach the top or bottom of my section, Thank you anyway.

**Comment by alvarotrigo** [comment]
Sure, it won't fit all use cases.
