### ISSUE TITLE
reduce the mouseWheelSpeed

### ISSUE THREAD

**Issue by nightwolf-041** [alvarotrigo/fullPage.js#4116]
I'm trying to reduce the mouseWheelSpeedl in every mousewheel to have a more positive mood.
But it has no effect on the scroll and its velocity and its value.
Any idea?

```
$("#fullpage").fullpage({
        autoScrolling: true,
        scrollOverflow: true,
        scrollOverflowOptions: { mouseWheelSpeed: 3000 },
        menu: "#navigation",
        loopHorizontal: false,
        loopVertical: false,
        loopBottom: true,
        loopTop: true,
})
```

**Comment by alvarotrigo** [comment]
No idea. Never tried.
You can check it [iScroll.js documentation](https://github.com/cubiq/iscroll) for that. As that's the library used by fullPage.js when using scrollOverflow.

**Comment by nightwolf-041** [comment]
> No idea. Never tried.
> You can check it [iScroll.js documentation](https://github.com/cubiq/iscroll) for that. As that's the library used by fullPage.js when using scrollOverflow.

**yes i use that options
Some of the options work and some don't work.
It's very strange :/
for example disableMouse and disablePointer works well but mouseWheelSpeed dose'nt**
