### ISSUE TITLE
Native horizontal swiping on iOs is disabled from fullpage plugin

### ISSUE THREAD

**Issue by AFriendLikeYou** [alvarotrigo/fullPage.js#4117]
I have tried to integrate the fullpage-plugin in a webview within a native iOs-App and Android-App. The plugin works in the specific webview without problems, the content can be swiped vertically. But the horizontal native swiping from webview to webview within the iOs-App is no longer recognized (on Android everything works fine). The fullpage-plugin seems to block / overwrite the horizontal touches on iOs.

I tried to disable swipe-events on "left" and "right" via
`fullpage_api.setAllowScrolling(false, 'left, right')`
but this has no effect on the native swiping behavior.

Strangely enough on iOs touching the navigation-bullets "activates" the native horizontal swiping again. Did i miss something that could possibly cause the problem with the native swiping?

Here is an [Codepen](https://codepen.io/Afly/pen/QWKEByQ) of how fullpage is integrated into the html page that is displayed in the webview.

**Comment by alvarotrigo** [comment]
Mmm any way I can test in my own device?

**Comment by AFriendLikeYou** [comment]
Unfortunately this is not possible, we are currently still in the development phase.

We tried your similar pagepiling plugin for a short time, but on iOS there was exactly the same problem: the native horizontal swiping did not work anymore once you were in view with the plugin. This could be solved by commenting out [this line of code](https://github.com/alvarotrigo/pagePiling.js/blob/master/jquery.pagepiling.js#L800).

Then the native swiping between views worked again. Probably there is a similar workaround for the fullpage-plugin?

**Comment by alvarotrigo** [comment]
Yeap, you can also comment that line, although that might lead to unwanted behavior in vertical scrolling.
If you won't be using horizontal slides, then i would recommend you to comment [this line](https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.js#L1432) and then replace this:

```js
//vertical scrolling (only when autoScrolling is enabled)
                else if(options.autoScrolling && canScroll){

                    //is the movement greater than the minimum resistance to scroll?
                    if (Math.abs(touchStartY - touchEndY) > (window.innerHeight / 100 * options.touchSensitivity)) {
                        if (touchStartY > touchEndY) {
                            scrolling('down');
                        } else if (touchEndY > touchStartY) {
                            scrolling('up');
                        }
                    }
                }
``` 

For this:


```js
//vertical scrolling (only when autoScrolling is enabled)
                else if(options.autoScrolling && canScroll){

                    //is the movement greater than the minimum resistance to scroll?
                    if (Math.abs(touchStartY - touchEndY) > (window.innerHeight / 100 * options.touchSensitivity)) {
                        
                     preventDefault(e);    // <------------- here

                        if (touchStartY > touchEndY) {
                            scrolling('down');
                        } else if (touchEndY > touchStartY) {
                            scrolling('up');
                        }
                    }
                }
```

**Comment by alvarotrigo** [comment]
It doesn't seem to be an easy work around, as iOS require that line to prevent the elastic overflowing:
https://stackoverflow.com/a/62308410/1081396

**Comment by AFriendLikeYou** [comment]
Thanks for the answer! Unfortunately it did not help in this case. As you wrote, it seems to be a bit more complicated. I will have a closer look at this problem tomorrow.
