### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#4118]
I've bought a Commercial "Hobby" License yesterday (07. December).

On the [Pricing-plans](https://alvarotrigo.com/fullPage/pricing/)-page, the "Hobby"-license-agreement is linked to the ["Developer-license](https://alvarotrigo.com/fullPage/pricing/license.html#developer).
However, in the email I received after buying the license, I received a "Hobby"-license-agreement that is not identical with the Developer-license linked above. 

The problem is: Not only is the title not identical, but also the content isn't identical (see section "Commercial license grant").

Which license-agreement actually is valid for me?

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
The latest version is the one on the website. 

I'll have to update the PDFs.

**Comment by lucianozurlo** [comment]
Hi. I´ve bought two license (fullpage + parallax), but I´m still seeing "[Unlicensed fullPage.js Extension]". My website now is in: https://zeta-id.com/temp/ and the licenses in: https://zeta-id.com/temp/js/fp.js
Thanks!!

**Comment by alvarotrigo** [comment]
@lucianozurlo please use the [contact form](https://alvarotrigo.com/contact/) for any questions regarding extensions purchases.

**Comment by alvarotrigo** [comment]
Fixed
