### ISSUE TITLE
Dynamic anchors in v3 and above

### ISSUE THREAD

**Issue by dimmuboy** [alvarotrigo/fullPage.js#4119]
### Description

I do upgrade from v2.9.7 but dynamic anchors from **data-anchor** attribute instead **anchors** array stopped working. Hash in url is not shows too.
When I add anchors array everything works so data-anchor is not working yet?

**Comment by alvarotrigo** [comment]
Probably related with https://github.com/alvarotrigo/fullPage.js/issues/4010

Make sure every section has an anchor.
And update to the dev version 3.1.0

https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js
