### ISSUE TITLE
Make fitToSectionDelay work with autoScrolling 

### ISSUE THREAD

**Issue by watahell** [alvarotrigo/fullPage.js#4120]
### Description
Sorry if this has been mentioned before, but I can't find an answer for this.
Please, is there a way to make fitToSectionDelay work with autoScrolling , just like on Tesla's homepage (look at how it has a delay before it scrolls to the next/previous section)?
https://www.tesla.com

Video of Tesla's homepage:
https://drive.google.com/file/d/1--iLVjED9v9M5R5VQd9IgtrgjZ2nx7Xq/view

The settings I tried:
autoScrolling: true,
fitToSection: true,
fitToSectionDelay: 1000

Which can be seen here:
https://jsfiddle.net/myLb9ptj/

Thanks

**Comment by alvarotrigo** [comment]
It doesn't make sense to use fitToSection with autoScrolling, as the only reason fitToSection exist is to fit to the correct section when stopping the scrollin between two sections, which is only possible when using `autoScrolling:false` or when using `scrollBar:true` and dragging the scroll bar with the mouse. 

So, are you sure you want to use autoScrolling? It seems to me that you want to use `autoScrolling:false` like Tesla's website.
Here's your edited example:
https://jsfiddle.net/cywt0m58/1/

**Comment by watahell** [comment]
Thanks for the quick response. I might have formulated my question in a bad way, I just meant I want to have something similar to autoScrolling, which moves the user to the next/previous section depending on whether the user scrolls down or up, but with a little delay. I presume custom code will be needed then, so I will just write something myself. Thanks!

**Comment by alvarotrigo** [comment]
I don't see any delay on Tesla website. 
The only difference I see is that they use scrollbar and allow user to freely scroll the page, and only snap to a section when the movement finishes, which is also the purpose of combining `autoScrolling:false` with `fitToSection:true`.
