### ISSUE TITLE
not working on iPad portrait or mobile both orientations

### ISSUE THREAD

**Issue by rrosegregoryy** [alvarotrigo/fullPage.js#4122]
Hello!

Fullpage.js is working perfectly on desktop and iPad landscape, but not for the rest:
- iPad portrait
- mobile portrait
- mobile landscape

I've created an isolated reproduction inside Webflow (where I'm building the actual site). Here is the published link:
[https://studio-y-staging.webflow.io/fullpage-js-ipad-test](https://studio-y-staging.webflow.io/fullpage-js-ipad-test)

And here is the Webflow project link: [https://preview.webflow.com/preview/studio-y-staging?utm_medium=preview_link&utm_source=designer&utm_content=studio-y-staging&preview=a654594c52df24d8b6bb3e0ba15280fd&pageId=5fd9c6a58dced454968c5343&mode=preview](https://preview.webflow.com/preview/studio-y-staging?utm_medium=preview_link&utm_source=designer&utm_content=studio-y-staging&preview=a654594c52df24d8b6bb3e0ba15280fd&pageId=5fd9c6a58dced454968c5343&mode=preview)

I've tested across Chrome and Safari on iOS. 

Thanks!

**Comment by alvarotrigo** [comment]
You are using `responsiveWidth: 1000` which means fullpage.js autoScrolling feature will be turned off under 1000px width.
So play with that or use the viewport meta tag in a different way, for example. 

```html 
<meta name="viewport" content="width=device-width,initial-scale=1">
 ```

**Comment by rrosegregoryy** [comment]
Great, thank you so much :) and thanks for a great plugin! 

Removing `responsiveWidth: 1000` fixed it.
