### ISSUE TITLE
Can't get links to slide to work on iPad portrait

### ISSUE THREAD

**Issue by rrosegregoryy** [alvarotrigo/fullPage.js#4123]
Hello! I'm building a site that the user navigates vertically through sections when on desktop and horizontally through the same content but on slides when on portrait iPad and mobile. 

As well as scrolling, I would also like there to be links that take the user to the next section. 

My anchor links for desktop are working, moving the user between the sections. 

My issue is setting up the links on iPad portrait. I'm struggling to get it to work.

I've tried using the moveTo function as shown [here](https://codepen.io/alvarotrigo/pen/doqOmY) and also by using anchors as described [here](https://github.com/alvarotrigo/fullPage.js#creating-links-to-sections-or-slides).

I've reproduced both my attempts in Webflow (where I'm building the actual site). 

**Using moveTo**
[staged site](https://studio-y-staging.webflow.io/fullpage-js-ipad-test)
[webflow project](https://preview.webflow.com/preview/studio-y-staging?utm_medium=preview_link&utm_source=designer&utm_content=studio-y-staging&preview=a654594c52df24d8b6bb3e0ba15280fd&pageId=5fd9c6a58dced454968c5343&mode=preview)

**Using anchors**
[staged site](https://studio-y-staging.webflow.io/fullpage-js-ipad-test-2)
[webflow project](https://preview.webflow.com/preview/studio-y-staging?utm_medium=preview_link&utm_source=designer&utm_content=studio-y-staging&preview=a654594c52df24d8b6bb3e0ba15280fd&pageId=5fda0aeddd5bccfd92592010&mode=preview)

You will need to view the reproductions on a screen less than 991px wide (as the desktop version is working fine as I want it). 

I appreciate any help you might be able to offer, thank you!

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by rrosegregoryy** [comment]
I can get it working in jsfiddle when I adjust your one [here](https://codepen.io/alvarotrigo/pen/doqOmY) to replicate what I want to do: hiding the sections that don't have sliders. 

The issue is replicating it in Webflow. But I've copied everything exactly like you have it in the jsfiddle and I can't for the life of me figure out what's not working. I've been at it for literally hours. If you have the time, I'd really appreciate it if you could have a look! Sorry I know it's probably annoying :/

**Comment by rrosegregoryy** [comment]
The Webflow reproductions I did have the absolute bare minimum CSS and HTML.

**Comment by alvarotrigo** [comment]
The webflow link contains many other things such as p5.js and other scripts.
Try to remove all those and keep the basic ones. 

Then I'll do a copy paste in a HTML and try to reproduce it.

**Comment by rrosegregoryy** [comment]
Okay I'll do a new project without the other scripts. Thank you! Really appreciate it.

**Comment by rrosegregoryy** [comment]
[Here is the webflow project link](https://preview.webflow.com/preview/fullpage-js-test-8a7fd5?utm_medium=preview_link&utm_source=designer&utm_content=fullpage-js-test-8a7fd5&preview=10a19b262228a1344f65581d6910b020&pageId=5fda23dbe5b2e857e5de49ac&mode=preview)

And the staging sites:
[using moveTo](https://fullpage-js-test-8a7fd5.webflow.io/moveto-test)
[using anchors](https://fullpage-js-test-8a7fd5.webflow.io/anchors-test)

Remember to look at it when the screen is less than 991px wide. You'll see on desktop the anchor links between sections are working fine. It's just on iPad portrait / browser less than 991px where I can't get the links to work.

Thanks so much, I really appreciate it.

**Comment by alvarotrigo** [comment]
There are still js files from webflow in there.
Also the code is minified.

If you can provide only the unminified HTML and the JS used for fullPage.js that'd be ideal.

**Comment by rrosegregoryy** [comment]
Here you go.

**Testing the moveTo function:**
HTML:
`<div class="fixed-test">
    <a href="#" class="button w-button">NEXT SLIDE</a>
  </div>
  <div id="fullpage" class="div-block">
    <div data-anchor="landing" class="section test _1">
      <a href="#work">NEXT SECTION</a>
    </div>
    <div data-anchor="work" class="section test _2">
      <a href="#landing">PREVIOUS SECTION</a>
      <a href="#services">NEXT SECTION</a>
    </div>
    <div data-anchor="services" class="section test _3"></div>
    <div data-anchor="info" class="section test _4"></div>
    <div data-anchor="portrait" class="section test portrait">
      <div data-anchor="slide1" class="slide"></div>
      <div data-anchor="slide2" class="slide _2"></div>
      <div data-anchor="slide3" class="slide _3"></div>
      <div data-anchor="slide4" class="slide _4"></div>
    </div>`

And the JS:
` <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fda22f80525dd764c5c07e5" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  
  <script type="text/javascript" src="https://unpkg.com/fullpage.js/dist/fullpage.min.js"></script>
  <script>
	//fullpage.js initialization
  new fullpage('#fullpage', {
    licenseKey: 'A43D2B94-424349C4-8D76B190-5B21CD14', 
  	scrollingSpeed: 1000,
    verticalCentered: false,
    controlArrows: false,
    //responsiveWidth: 1000,
    anchors: ['landing', 'work', 'services', 'info', 'portrait'],
    scrollBar:true
  });
	$(document).on('click', '#moveWork', function(){
		fullpage_api.moveTo('portrait', 1);
	});
</script>`

**For testing anchors**

HTML:
`<div class="fixed-test">
    <a href="#portrait/slide2" class="button w-button">NEXT SLIDE</a>
  </div>
  <div id="fullpage" class="div-block">
    <div data-anchor="landing" class="section test _1">
      <a href="#work">NEXT SECTION</a>
    </div>
    <div data-anchor="work" class="section test _2">
      <a href="#landing">PEVIOUS SECTION</a>
      <a href="#services">NEXT SECTION</a>
    </div>
    <div data-anchor="services" class="section test _3"></div>
    <div data-anchor="info" class="section test _4"></div>
    <div data-anchor="portrait" class="section test portrait">
      <div data-anchor="slide1" class="slide"></div>
      <div data-anchor="slide2" class="slide _2"></div>
      <div data-anchor="slide3" class="slide _3"></div>
      <div data-anchor="slide4" class="slide _4"></div>
    </div>
  </div>`

JS:
`  <script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=5fda22f80525dd764c5c07e5" type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="js/webflow.js" type="text/javascript"></script>
  
  <script type="text/javascript" src="https://unpkg.com/fullpage.js/dist/fullpage.min.js"></script>
  <script>
	//fullpage.js initialization
  new fullpage('#fullpage', {
    licenseKey: 'A43D2B94-424349C4-8D76B190-5B21CD14', 
  	scrollingSpeed: 1000,
    verticalCentered: false,
    controlArrows: false,
    //responsiveWidth: 1000,
    anchors: ['landing', 'work', 'services', 'info', 'portrait', 'slide1', 'slide2', 'slide3', 'slide4'],
    scrollBar:true
  });
</script>`

Could the issue maybe be that Webflow uses a minified version of JQuery? 

I could also try using the moveSlideRight and moveSlideLeft functions (as I don't ever need to get to a specific slide).

**Comment by rrosegregoryy** [comment]
I don't know why my code doesn't format correctly in here. I'm using the ` ` but it doesn't seem to work

**Comment by rrosegregoryy** [comment]
Hi Alvaro, do you have everything you need? Let me know if there's anything else.

**Comment by alvarotrigo** [comment]
Have you tried the latest dev version 3.1.0?
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.js

**Comment by rrosegregoryy** [comment]
ah no I'm using version 3.0.9

Is there a way to get 3.1.0 as a source link? I don't think I can upload files into Webflow.

**Comment by alvarotrigo** [comment]
https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.js

**Comment by rrosegregoryy** [comment]
nope still can't get it to work 😞 

If it helps, the URL changes, but the transition to the slide doesn't happen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
