### ISSUE TITLE
Scrolling Issue !

### ISSUE THREAD

**Issue by vishalkakkar007** [alvarotrigo/fullPage.js#4124]
If we have data which is more than the height of section and is collapsible also then scrolling issue rises.
For Eg Having A Button And Clicking it Shows The Hidden Data And If The Hidden Data Is More than The Height Of The Section
Then It Behaves Abnormally.
Any Suggestions Or Guide To Solve It?

**Comment by alvarotrigo** [comment]
Check the fullPage.js `reBuild` method used when adding bigger content  on a section/slide dynamically.
Note you'll have to use `scrollOverflow:true` to create the inner scrolling like in this example:
https://alvarotrigo.com/fullPage/examples/scrolling.html
