### ISSUE TITLE
Scrolloverflow: true and scroll always to top

### ISSUE THREAD

**Issue by tdittmann** [alvarotrigo/fullPage.js#4125]
Hi, i want to use the scrolloverflow: true and when scrolling up it should always start on the top of the section... Unfortunately the option ```bigSectionsDestination``` doesn't work :/
How can i archive it anyway?

**Comment by alvarotrigo** [comment]
There's another option for it (`scrollOverflowReset: true`)`that requires a paid extension:
[ScrollOverflow Reset](https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html)

**Comment by cvaraj** [comment]
if I want always from the bottom,  this extension will work?

**Comment by alvarotrigo** [comment]
@cvaraj you can see an example here: 
https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html

See if that does what you want.

**Comment by cvaraj** [comment]
@alvarotrigo yes I saw this link. when I scroll from the top inner scroll bar shows the top, when I scroll from the bottom it shows top content that's the current scenario but now I want reverse order, wherever I scroll from the top or from up I want to show from that bottom content.

**Comment by alvarotrigo** [comment]
Unfortunately that's not possible.

**Comment by cvaraj** [comment]
no option to customize?

**Comment by alvarotrigo** [comment]
Yeap, for an extra amount we are open to customisation, please use the [contact form](https://alvarotrigo.com/#contact) to ask us about more details on that.
