### ISSUE TITLE
One touch causes scrolling of 2 sections in Yandex browser and sometimes in safari on a Laptop in the example of Drug and Move.

### ISSUE THREAD

**Issue by UnveiledNevid** [alvarotrigo/fullPage.js#4127]
Sometimes, i have seen some twice scroll after one touch on Macbook safari after integration all fullpage functionality on my website. After that i have found that in Yandexbrowser you can see it easily here: https://alvarotrigo.com/fullPage/extensions/drag-and-move.html. It would help me a lot on my website if you could fix or explain the reason for this bug on your website in Yandexbrowser.

### Steps to reproduce it
1. Download and install https://browser.yandex.ru/ on your laptop
2. Open Link https://alvarotrigo.com/fullPage/extensions/drag-and-move.html in YandexBrowser
3. Touch down once - two blocks will be scrolled. 

### Versions 
Yandex Browser 20.11.3

**Comment by alvarotrigo** [comment]
It happens in other browsers too sometimes.
See this:
https://github.com/alvarotrigo/fullPage.js/issues/1654
