### ISSUE TITLE
Ajax loading of sections content

### ISSUE THREAD

**Issue by UnveiledNevid** [alvarotrigo/fullPage.js#4128]
On my website i use ajax loading of content inside sections. All sections are loaded along with normal page loading, but most of them are empty and loaded as the user navigates the site. The problem is that when the content of a section with a large amount of information is loaded, no matter where the user is at the moment, if he does a slide down or slide up on the laptop's touchpad, for some reason a bug occurs - scrolling 2 sections at once. Can you please tell me why loading content with ajax inside a section can affect the navigation between sections? Are there any options to deal with this?

**Comment by alvarotrigo** [comment]
Are you using the option `scrollOverflow:true` to get the inner scrollbar within sections?
See an example here:
https://alvarotrigo.com/fullPage/examples/scrolling.html

After you append the dynamic content on any section/slide you'll have to then call `fullpage_api.reBuild()` to force the update of the scroll bar (if required).

**Comment by UnveiledNevid** [comment]
I am not using the scrollOverflow: true option. And i already use fullpage_api.reBuild() after content is loaded. 
I quite accidentally solved the problem today with the option 

bigSectionsDestination: 'top'.

I made all the sections to fit the size of the viewport, but apparently, as I now understand, there are overshoots somewhere with this. Maybe someone else can help.

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! :)
