### ISSUE TITLE
Working on Local but not on server: Fullpage.js can only be initialized once

### ISSUE THREAD

**Issue by BenGamlin** [alvarotrigo/fullPage.js#4129]
Hi!

I have been building a site with FullPage, which works great on my local environment. When I view the site on my staging server however, FullPage refuses to work throwing the error:

**FullPage: Fullpage.js can only be initialized once and you are doing it multiple times**

As I say, this works fine on local but nevertheless I checked the output. FullPage is only being initialised once on the page and is only ever called on the homepage of the site.

Happy to send a link if I could do so securely?

Thanks in advance,
Ben

**Comment by alvarotrigo** [comment]
That means exactly that :)
You are somehow initialising fullPage.js multiple times. 

There's definitely something different between your local and your production page. 

> Happy to send a link if I could do so securely?

Unfortunately I don't check specific websites here. Only isolated reproductions on codepen.
If you need further support you can consider the [Business license](https://alvarotrigo.com/fullPage/pricing/).
