### ISSUE TITLE
Hide address bar on mobile

### ISSUE THREAD

**Issue by cueqzapper** [alvarotrigo/fullPage.js#4130]
### Description
On mobile the address bar doesn't disappear on scroll (default behavior on all other websites), which makes the window quite small.

### Link to isolated reproduction with no external CSS / JS
This happens on all fullpage js examples.

### Steps to reproduce it
1. Open any other website which is scrollable and scroll down, the address bar will hide
2. Do the same thing with fullPage.js and scrollbar won't hide

### Versions 
Chrome Android and Safari iOS

**Comment by alvarotrigo** [comment]
Unfortunately we developers have no control over the address bars. As long as the scroll event is disabled you might find these kind of behaviours.

To fix this you can use the fullPage.js option `scrollBar:true`. 
That will make sure the user will still be able to see the scroll bar and that the scroll event will get fired as normal.
