### ISSUE TITLE
Extensions not working on Webflow

### ISSUE THREAD

**Issue by phristopher** [alvarotrigo/fullPage.js#4132]
Hi all, I am having trouble activating scrollHorizontal and fadingEffect extensions on Webflow. I purchased the license and followed the documentation and neither extension seems to be working. I even tried starting from a clone of Alvaro's Webflow fullpage.js project and it still hasn't worked. **I've gotten fullpage.js to work, but the two extensions I want to use are NOT working**. 

**What I am trying to achieve on the webpage is this:**
Section 1) Scroll overflow
Section 2) Slider w/ scrollHorizontal + fadingEffect
Section 3) Scroll overflow

**What I know I've done following documentation:**
- I loaded the fullpage.extensions.min.js instead of the fullpage.js
- I have both scrollHorizontally.min.js and fadingEffect.min.js loading BEFORE fullpage.extensions.min.js
  (note: I uploaded/host these extension scripts on github gist)
- I bought fullpage.js + extensions and load all the respective licenses and keys in the script.

### Link to isolated reproduction with no external CSS / JS
I know it's suggested to recreate my problem in jsfiddle or codepen.io, but as far as my understanding goes, my problem lies within getting the extensions to activate, WHICH can only be used with an respective license for a specified domain, thus recreating the problem in jsfiddle and codepen would not work.

However, I can provide a webflow share read-only link that will let you see the code I am using.
[Webpage 1](https://www.endeavourii.com/2021/home-extensions)
[Webpage 1: Read-only link with code](https://preview.webflow.com/preview/endeavour-96ac5b?utm_medium=preview_link&utm_source=designer&utm_content=endeavour-96ac5b&preview=d70c94b2f860af88af42c3c49db67647&pageId=5fe2987ae64c879f6e82a8a7&mode=preview)

[Webpage v2 (started from a cloned fullpage.js example by Alvaro](https://www.endeavourii.com/2021/fullpage-js-example-copy)
[Webpage 1: Read-only link with code](https://preview.webflow.com/preview/endeavour-96ac5b?utm_medium=preview_link&utm_source=designer&utm_content=endeavour-96ac5b&preview=d70c94b2f860af88af42c3c49db67647&pageId=5fe649cc65c8172861ffdb7c&mode=preview)

**Some questions that arise for me:**
- Is there a way to verify that the extension scripts are loading?
- Is there a way to verify that the licenses for the extensions are working?
- When generating the license keys for extensions, did I have to include "www." in front of the url when asking me what website it's for?

Please let me know if any of you have any insight to what I am missing. Appreciate any help.

Happy Holidays,
phristopher

### Versions 
[2019 MacBook Pro, OSX Mojave, Chrome Version 87.0.4280.88 (Official Build) (x86_64)]

**Comment by alvarotrigo** [comment]
You are initialising fullPage.js twice. Make sure to do it only once:

```html
<script>
--
  | //fullpage.js initialization
  | new fullpage('#fullpage', {
  | licenseKey: '42FB1E48-732E4B84-BA85E2D3-247583AD',
  | fadingEffectKey: 'ZW5kZWF2b3VyaWkuY29tX1F6bFptRmthVzVuUldabVpXTjBTdnA=',
  | fadingEffect: 'slides',
  | scrollHorizontallyKey: 'ZW5kZWF2b3VyaWkuY29tX3Y1QWMyTnliMnhzU0c5eWFYcHZiblJoYkd4NThVdg==',
  | scrollHorizontally: true,
  | scrollingSpeed: 1000,
  | verticalCentered: false,
  | scrollOverflow: true,
  | autoScrolling: true,
  | scrollBar: false,
  | });
  | </script>
  |  
  |  
  | <!--video loop-->
  | <script> $(document).ready(function() { $('video').each((i,v) => { $(v).attr('data-keepplaying', ''); v.play(); }); $('#fullpage').fullpage(); }); </script>
```

**Comment by alvarotrigo** [comment]
Also you are not loading the JS files correctly for your extensions. 
You can see this in chrome dev tools. See this:
https://stackoverflow.com/questions/14714342/how-to-embed-a-file-gist-in-an-html-file

<img width="1287" alt="Screenshot 2020-12-27 at 12 10 55" src="https://user-images.githubusercontent.com/1706326/103169521-a8133200-483c-11eb-9cb4-c218f5f933aa.png">

**Comment by alvarotrigo** [comment]
For any further questions with extensions please use the contact form.
https://alvarotrigo.com/#contact
