### ISSUE TITLE
How to Install on Typescript

### ISSUE THREAD

**Issue by nvminhhieu** [alvarotrigo/fullPage.js#4133]
### How to Install fullPage.js on Typescript

I am trying to use this library on TypeScript but it keeps giving me errors with the .js installation and even importing from .d.ts . I'm not sure I do these correctly, please help!

## Think I have done: 
1. Get it and its definitelyTypes using Npm
2. Add export = FullPageJs at the end of index.d.ts (because it keeps throw out error that this is not module)
3. Get Node @types using Npm
4. const fullpage = require('fullpage.js');
new fullpage ('#fullpage', {
    //options here
	autoScrolling:true,
	scrollHorizontally: true
});

Above is my attempt code try to import the library. No error was given out but it's not working.

So how can I install this library in Typescript?

**Comment by alvarotrigo** [comment]
I don't know to be honest :)
Never used Typescript. 

I think you will probably get a better answer at https://stackoverflow.com
