### ISSUE TITLE
How to use pagepiling.js and other libraries with fullpage.js?

### ISSUE THREAD

**Issue by adarshmalviyaaa** [alvarotrigo/fullPage.js#4134]
I was trying to integrate both of these libraries together but it was not working. Can anybody suggest a solution?

**Comment by alvarotrigo** [comment]
To be honest I have never  tried :) 
They are not meant to be used together, but if you find a away please let us know here!

I'll close the issue for now as it is not something it is provided out of the box and not a feature I provide support for.
