### ISSUE TITLE
Disable and re-enable Fullpage.js with barbel.js

### ISSUE THREAD

**Issue by nvminhhieu** [alvarotrigo/fullPage.js#4135]
## Disable and re-enable Fullpage.js between switching page using barbel.js 

I want to combine Fullpage.js and Barbal.js page transition library. I use Gsap to animate the transition and also run code while leaving and entering page. The 1st page, I want to use Fullpage.js, but I want to disable it after transition to 2nd page. I tried using fullpage_api.destroy('all'); to remove the fullpage effect when enter the 2nd page. It works! But when I want to go back to the 1st page, the fullpage.js is still disable. 

### So how can I re-enable Fullpage.js on the 1st page after gone from the 2nd page?

Ideally, I want to disable fullpage.js, which includes its scroll effect, class and style on 2nd page and re-enable them when move back to 1st page.

**Comment by alvarotrigo** [comment]
> But when I want to go back to the 1st page, the fullpage.js is still disable.

Then you would have to initialise it again :)

I haven't used barba and I have no idea how it works, but I know for sure the solution to it is basically initializing fullpage.js again :)
For barba specific issues you can probably get better answers at stackoverflow.com or some barba forums.
