### ISSUE TITLE
Possible to combine navigation + slidesNavigation dots?

### ISSUE THREAD

**Issue by phristopher** [alvarotrigo/fullPage.js#4139]
Hi I wondering if it is possible to add the slidesNavigation dots to the regular navigation dots. For instance if a section has three slides, could three dots (instead of 1) be shown in the general navigation for all of the sections?

**Comment by alvarotrigo** [comment]
That's not provided out of the box by fullPage.js.
However, you can do this by yourself by creating your own custom navigation and using the callbacks that fullpage.js provides.

Look at how to [create your own custom navigation for fullPage.js](https://stackoverflow.com/a/36742906/1081396).
