### ISSUE TITLE
Change icon on navigation 

### ISSUE THREAD

**Issue by intissar962** [alvarotrigo/fullPage.js#4141]
i want to change first child of ul with an image it's possible ?

**Comment by alvarotrigo** [comment]
Yeap, just [overwrite the default navigation CSS for fullpage.js](https://stackoverflow.com/a/60468048/1081396).
Or if you prefer, [create your own custom navigation for fullPage.js](https://stackoverflow.com/a/36742906/1081396).

**Comment by intissar962** [comment]
Hello, i'm using fullpage js on my website
Jimmysfitness.ma with WordPress
But i have a baad performance, there is ny solution ?

IBennouna

**Comment by alvarotrigo** [comment]
For wordpress we recommend using our official plugins [for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) or [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) (soon for [Divi](https://alvarotrigo.com/fullPage/wordpress-plugin-divi/) too).

Those are the only ones we provide support for as are the only ones we build :)
