### ISSUE TITLE
If we want to use it to develop our website, do we have to purchase a license even if we don't use the extension?

### ISSUE THREAD

**Issue by pinguo-wangchunyang** [alvarotrigo/fullPage.js#4142]
@alvarotrigo  If we want to use it to develop our website, do we have to purchase a license even if we don't use the extension?

**Comment by alvarotrigo** [comment]
Yes, as long as your code is not licensed under GPLv3 license.
See more about it on the [pricing page](https://alvarotrigo.com/fullPage/pricing/)
