### ISSUE TITLE
scrollOverflow not working

### ISSUE THREAD

**Issue by rbretmounet** [alvarotrigo/fullPage.js#4143]
### Description
I'm trying to use scrollOverFlow and I'm not sure why it's not working. I've set it to true and loaded overflow.min.js before fullpage.js and after jquery. Can't get all the images to load properly in the demo since most files are stored locally. But the second page is where I'm trying to have scrolloverflow for mobile support.
### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/rbretmounet/s1gmxeoL/3/

### Versions 
Browser: Google Chrome 87.0.4280.141
OS: Windows 10.0.19041.488

**Comment by alvarotrigo** [comment]
On the fiddle you are not importing scrolloverflow.min.js

![image](https://user-images.githubusercontent.com/1706326/105020990-4ebbae80-5a48-11eb-9caa-021cd0a9472a.png)

**Comment by rbretmounet** [comment]
Okay added it to the fiddle but it's still not working.

**Comment by alvarotrigo** [comment]
Easiest way for you is to check the available example:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html

And on codepen:
https://codepen.io/alvarotrigo/pen/ZPwjaP

If you believe there's any issue, please create an isolated reproduction with the less amount of HTML possible an empty sections with just titles on it.

**Comment by rbretmounet** [comment]
Update: Figured out the issue. If you are using bootstrap grids and set the container position to the top of the section it will not add the overflow scroll. Do you know if there is a work around for that?

**Comment by alvarotrigo** [comment]
Would need to research it a bit more.
Perhaps using a wrapper `div` around your grid elements?

**Comment by rbretmounet** [comment]
Okay, wrapper div doesn't seem to work. If I do this with my boostrap grid`<div class="container-md" style="position: absolute;top:0;left:0;right:0;" >` then the scroll overflow doesnt work. I have to remove the style for it to work.

**Comment by alvarotrigo** [comment]
Yeah it won't work on absoluted positioned elements as there's no way to get the height of an element containing an absolute positioned element.

**Comment by rbretmounet** [comment]
Ah, I see I'll just have to find another way to align the grids to the top of the page. Is there a way to align the section contents to the top of the page?

**Comment by alvarotrigo** [comment]
No idea, that's more a css matter :)
I would however try to prevent the need of scrollOverflow if possible. Or use the responsive options for small screen devices.

**Comment by rbretmounet** [comment]
Okay, thanks for the help.

**Comment by lairinys** [comment]
Hi, I have the same issue, I am trying to get scrollOverflow works but I can't do it, this is the web site Ima developping https://34.212.55.76/  client session is biggest than screen, but scrooll bar doest appear even I have confifured scrollOverflow:true , scrollOverflowReset doesn't work either, I buy both licences fullpage.js and scrollOverflowReset extension, I really need help in this matter, please.

**Comment by alvarotrigo** [comment]
@lairinys we don't check personal websites on this forum. Create an isolated reproduction on jsfiddle or codepen and we'll take a look at it here. Otherwise, consider getting the Businiess license from the [fullpage.js pricing page](https://alvarotrigo.com/fullPage/pricing/).

Also, make sure to first check the [examples provided](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/) where you can find the [ScrollOverflow option](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html) working as expected.
