### ISSUE TITLE
Forms get stuck zoomed in on iPhone Safari

### ISSUE THREAD

**Issue by wellbeingwebsites** [alvarotrigo/fullPage.js#4144]
### Description

If I have a section containing a form, Safari on mobile likes to zoom the current field to help with data entry. 

This seems to confuse fullpage_js, especially as the form is in a slide where I don't want users to be able to accidentally scroll away from the form until they're done so I've used setAllowScrolling(false) when they're still using the form. On desktop it works great, on iPhone/Safari it's hard to navigate the form. 

### Link to isolated reproduction with no external CSS / JS

https://codepen.io/wellbeingwebsites/pen/poEGGme

### Steps to reproduce it

Visit https://codepen.io/wellbeingwebsites/pen/poEGGme on iPhone/Safari or a good emulator
Scroll to the RIGHT where the form is (I've simulated the full behaviour of my site to be sure it's clear)
Try filling in the form, going back etc. Submitting the form sets allowAutoScrolling(true) again so you can scroll away but zoom is still not right.
 

### Versions 

iPhone 11 Pro Max, iOS 14.3, Safari that comes with iOS 14.3, fullpage_js 3.0.9

### Screenshots

These show a progression of going into the form, entering my name, at this point the name field is zoomed in but I can't feely scroll around – I have to use the ⌄ and ⌃ buttons to navigate the form. Once I submit the form, re-enabling auto scroll, I can navigate away but it remains zoomed in to the size it had for form field entry, and I can't zoom out again. 

![IMG_5271](https://user-images.githubusercontent.com/16512803/104980454-aebb5080-5a5a-11eb-8880-613f15a6030f.PNG)
![IMG_5272](https://user-images.githubusercontent.com/16512803/104980468-b5e25e80-5a5a-11eb-9142-c596ade334f1.PNG)
![IMG_5273](https://user-images.githubusercontent.com/16512803/104980473-b7ac2200-5a5a-11eb-9a08-e33658b8f93f.PNG)
![IMG_5274](https://user-images.githubusercontent.com/16512803/104980477-b844b880-5a5a-11eb-9ecc-18c82ce75ead.PNG)

**Comment by camp54** [comment]
I had a simliar issue the other day which was resolved by following this:

https://www.warrenchandler.com/2019/04/02/stop-iphones-from-zooming-in-on-form-fields/

I always struggle w/ CodePen on the mobile device, but I think it's working when you simply include below in the CSS

`body { font-size: 16px; }
input, select { font-size: 100%; }`

**Comment by heartfelttech** [comment]
Thanks @camp54, it hasn't helped on codepen but I'll give it a try on the direct code when I get a moment.

**Comment by alvarotrigo** [comment]
@heartfelttech check the answers on this topic, perhaps changing font size can help?
https://stackoverflow.com/q/11064237/1081396

I believe the easiest way to deal with this issue is probably preventing the zoom of the form somehow, but this is not a fullPage.js feature, so solution for this should be found outside fullPage.js scope. (meta tag, font size... )

From the fullPage.js point of view I can suggest two things:

- Using the responsive options so it will use autoScrolling: false on small screen devices like mobile phones.
- Or using `scrollBar:true`. This might help as well. But haven't tried it.

I'll close the issue
