### ISSUE TITLE
It is not working with wordpress polylang plugin

### ISSUE THREAD

**Issue by odsconsulting** [alvarotrigo/fullPage.js#4146]
I'm using fullpage.js for wordpress themes, I'm also using polylang plugin for multi language in wordpress. I had not getting any problem while I only use 1 language and my link as website.com/#home (home is an data-anchor) but if I use 2 languages and if my link as become website.com/en/#home, fullpage.js is not working. I hadn't get any error for this situation. Also, I tested scrolling function and it works but page can't slide up or down.

Thank you.

**Comment by alvarotrigo** [comment]
Difficult (or let's say impossible 😄 ) to know what the issue might be without an isolated reproduction.
