### ISSUE TITLE
Problems with re-install extensions inside WP

### ISSUE THREAD

**Issue by mrdexters1** [alvarotrigo/fullPage.js#4147]
### Description

Hello, please, help me.

I bought the FullPage WP plugin and the Fadding Effect extension.
I registered everything and everything was good working until today. Today, I got an "Unlicensed extension" message and decided to reinstall the extension. I deleted extension, and now I can't install it again.

I see error:

"Please wait while installing the extension...
Error while installing the plugin!
Invalid response!
Please check your license key!"

What can be the problem? Thank you.

**Comment by alvarotrigo** [comment]
Contact support for WordPress issues using the [contact form](https://alvarotrigo.com/#contact).
