### ISSUE TITLE
Prevent elastic effect on top of document on mobile.

### ISSUE THREAD

**Issue by tokmo** [alvarotrigo/fullPage.js#4149]
### Description
Hi,

I want prevent the elastic effect when i scroll with finger on mobile on the top of the document.
How can i do that please ?

Thx.

### Steps to reproduce it
1. Go to the top of document
2. Slide with your finger in the bottom direction

### Versions 
IOS/Android and other mobile OS.

**Comment by alvarotrigo** [comment]
That effects only takes place when you use the Drag And Move extension which is not included by default on fullPage.js.

You should not be able to reproduce that on any other page, for example this one:
https://alvarotrigo.com/fullPage/examples/navigationV.html

**Comment by tokmo** [comment]
First thx for you're fast reply.
I don't use Drag and Move extension. I use the react package '@fullpage/react-fullpage' with this option : 

```
licenseKey = {'MYKEY'}
scrollingSpeed = {1000} /* Options here */
scrollBar = {true}
verticalCentered = {false}
scrollOverflow= {true}
```

**Comment by alvarotrigo** [comment]
Can you reproduce your issue on the react demo page?
https://alvarotrigo.com/react-fullpage/

**Comment by tokmo** [comment]
> 
> 
> Can you reproduce your issue on the react demo page?
> https://alvarotrigo.com/react-fullpage/

No, its work fine on your link.

**Comment by alvarotrigo** [comment]
Try turning `scrollBar:false` or `scrollOverflow:false` and see if you can still reproduce it. 

Also try applying your same settings on the example we provide:
https://github.com/alvarotrigo/fullPage.js/tree/master/examples

See if you can reproduce it there.

**Comment by tokmo** [comment]
Ok I just saw what triggers this side effect.

```
<div className="section">
  <div className="sectionWrapper">
    <div
      style={{
      height: '800px',
      background: 'red'
    }}>
  </div>
</div>
</div>
```

.sectionWrapper have only a padding-top for my navbar.
This effect appear when my first .section have a height bigger than the viewport with scrollOverflow on true.

**Comment by tokmo** [comment]
So it doesn't matter to me. I tested the scrolloverflow only if someone wanted to display the site with a very small window height which should be an exception among my visitors.

**Comment by alvarotrigo** [comment]
Glad you managed to fix the issue!
