### ISSUE TITLE
Incorrect definition of the beginning of section at scrolling at transition from other page on an anchor link

### ISSUE THREAD

**Issue by jul-moc** [alvarotrigo/fullPage.js#4151]
### Description
I have a few pages. ON MOBILE: When I go from another page by clicking on the menu item which is the anchor link leading to a certain section on the main page, the scrolling incorrectly determines the beginning of the section.
On mobile devices, the height of the section exceeds the height of the screen.

//My code example
            $('#fullpage').fullpage({
                anchors: ['home', 'about-us', 'services', 'testimonials', 'contact-us'],
                menu: '.main-menu',
                lazyLoad: false,
                autoScrolling: true,
                responsiveHeight: 654,
                responsiveWidth: 992,
                scrollBar: true,
                bigSectionsDestination: 'top',
                animateAnchor: false,
            });
            
I had this bug on all mobile devices, but for androids I fixed it with the 
animateAnchorsetting: false,
and for safari still determines the top of the section when scrolling and stops a little scrolling the section further than necessary. 
           

### Steps to reproduce it
1. I go to another page
2. Click on the anchor link in the menu
3. There is a transition to the main page and loading of the necessary section
4. The section is loaded not from the beginning but a little lower than required

### Versions 
[Browser, operating system, device, ...]
Mobile Safary

**Comment by alvarotrigo** [comment]
I can't reproduce that on the demo page
http://alvarotrigo.com/fullPage/

Or any of the other examples.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by jul-moc** [comment]
I added a little more information to the description

**Comment by alvarotrigo** [comment]
Any link where I can reproduce the issue?

**Comment by jul-moc** [comment]
You can reproduce this on **safari mobile** by going to the menu item Testimonials or Contact us from another page
http://gorepublic.com.user.s414.sureserver.com/client-login/

**Comment by alvarotrigo** [comment]
I'll wait for an isolated reproduction. 
Let me know when you have one I can check. If you prefer me to check your page you can get the [Business license](https://alvarotrigo.com/fullPage/pricing/).

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
