### ISSUE TITLE
Scrolloverflow: true and scroll always to bottom

### ISSUE THREAD

**Issue by cvaraj** [alvarotrigo/fullPage.js#4152]
I need urgent help

https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html, this extension support always from the bottom? when I scroll from the top and scroll up from down, I need always content to load from the bottom of the view

Thank You.

**Comment by alvarotrigo** [comment]
It supports what you see on the demo.
Check the if the demo does what you want.
