### ISSUE TITLE
 everything gets bigger (somehow zooms in) when i refresh the page in chrome

### ISSUE THREAD

**Issue by nightwolf-041** [alvarotrigo/fullPage.js#4153]
https://user-images.githubusercontent.com/51447528/106613099-10151080-657f-11eb-94e3-be7a815735ed.mp4

hi
i'm using fullpage.js for this site
as you can see, when I refresh the page in the bottom sections,
scrolling starts from top to that section and everything gets bigger (somehow zooms in).
**(( I have this problem only in Chrome and it is OK in Firefox ))**

any idea ??? :(

**Comment by alvarotrigo** [comment]
fullPage.js doesn't change the font of your page or anything regarding size :)
So it might be something else. 

If you still think it is a fullpage.js issue then please provide an isolated reproduction of it in jsiffle or codepen and we'll take a look at it.

**Comment by nightwolf-041** [comment]
@alvarotrigo 

But why does this not happen when I refresh the page in the first section? And why is this only in Chrome?
anyway...
this is the pen from just 2 sections (not all of project) :
https://codepen.io/nightwolf-041/pen/mdOJKvZ

But I don't think there is a problem here because the codepen is shown inside the browser itself, not Chrome...
If possible, I will send you the project file to check.

**Comment by alvarotrigo** [comment]
> But why does this not happen when I refresh the page in the first section? And why is this only in Chrome?
anyway...

Good question, but fullPage.js won't be the answer :)

> But I don't think there is a problem here because the codepen is shown inside the browser itself, not Chrome...
If possible, I will send you the project file to check.

If you can please isolate the issue by removing all CSS and JS external to fullpage.js that'd be great. Also use empty sections with a single heading on them to simplify things more.

This way we can see if the issue is on fullPage.js or it has nothing to do with it.

You can create the isolated reproduction on any HTML file, then test you still reproduce it and then paste it on codepen. 
As long as you removed all external code I'll check it out.

**Comment by Noliferqt** [comment]
> 
> 
> > But why does this not happen when I refresh the page in the first section? And why is this only in Chrome?
> > anyway...
> 
> Good question, but fullPage.js won't probably be the answer :)
> 
> > But I don't think there is a problem here because the codepen is shown inside the browser itself, not Chrome...
> > If possible, I will send you the project file to check.
> 
> If you can please isolate the issue by removing all CSS and JS external to fullpage.js that'd be great. Also use empty sections with a single heading on them to simplify things more.
> 
> This way we can see if the issue is on fullPage.js or it has nothing to do with it.
> 
> You can create the isolated reproduction on any HTML file, then test you still reproduce it and then paste it on codepen.
> As long as you removed all external code I'll check it out.

I have same problem, when i try scroll to any section below than first, i have "blur" effect on my section. You can see this problem on main page your plugin: https://alvarotrigo.com/fullPage/  Depending on the color background and font style you can see this effect better or worst . On my opinion it's problem related to scroll mechanic in chrome.

**Comment by julianvolp** [comment]
@Noliferqt @alvarotrigo I am also seeing the "blur" effect on a couple of my sites using fullPage, although it's all content contained inside .fp-section for me (not just text).

Here's an example, you can see the text and bg image blur on scroll.
https://user-images.githubusercontent.com/14869814/108052928-b0216e00-7044-11eb-9838-5058a4602af0.mp4

Do you know what might be causing this?

**Comment by alvarotrigo** [comment]
@julianvolp can you reproduce such effect on any of the examples online?
https://alvarotrigo.com/fullPage/examples/continuous.html#secondPage

**Comment by alvarotrigo** [comment]
@julianvolp I've opened a new topic for it [here](https://github.com/alvarotrigo/fullPage.js/issues/4153) lets follow the conversation there.
