### ISSUE TITLE
Android for  the keyboard-pop cause page slide and splash-screen

### ISSUE THREAD

**Issue by HanTianPeng** [alvarotrigo/fullPage.js#4154]
### Link to isolated reproduction with no external CSS / JS
var clientHeight = document.documentElement.clientHeight || document.body.clientHeight; //最初进来的窗口高度
$(function() {
        //android处理输入框问题
        if (isAndroid) {
          $(window).on('resize', function() {
            var nowClientHeight = document.documentElement.clientHeight || document.body.clientHeight; //变化后窗口的高度
              var diffWidth = clientHeight - nowClientHeight;
            if (clientHeight > nowClientHeight) {
              //键盘弹出事件处理
              $('.fp-section').css('top', '-' + diffWidth + 'px');
            } else {
              //键盘收起事件处理
              $('.fp-section').css('top', '0');
            }
          });
        }
}
### Steps to reproduce it
计算键盘弹出之前的屏幕差，定位元素即可。已经试了多款Android设备，均可以使用！

### Versions 
[Android]

**Comment by alvarotrigo** [comment]
Would it possible for you to write it on english? 
Unfortunately I don't know mandarin! :)
