### ISSUE TITLE
Changing Colour of Navigation Dots in CSS file

### ISSUE THREAD

**Issue by jrolf3** [alvarotrigo/fullPage.js#4155]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Look for `#fp-nav` on the css file:
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.css
