### ISSUE TITLE
Horizontal Navigation (fullPage.js Horizontal Slides)

### ISSUE THREAD

**Issue by wirkoenntenaber** [alvarotrigo/fullPage.js#4157]
I've just purchased a hobby license for fullPage.js in order to create slides in webflow and it works nicely. Now I would like to implement a horizontal navigation. I am however unable to find the appropriate documentation of how to do this. I'd appreciate if someone could point me into the right direction. Thanks in advance.

**Comment by alvarotrigo** [comment]
I've seen you've closed the issue. Did you managed to get it working?
There's a clonable demo here:
https://webflow.com/website/fullPagejs-Horizontal-Slides

**Comment by wirkoenntenaber** [comment]
Yes and no. I managed to get it working by reading the documentation (duh) as neither the clonable demo nor the webflow tutorial explained this. What I was searching for was the option "slidesNavigation: true", I am now trying to figure out how to center the aforementioned navigation bar on the bottom of the screen as seen [here](https://alvarotrigo.com/fullPage/examples/navigationH.html#secondPage).

**Comment by alvarotrigo** [comment]
> as neither the clonable demo nor the webflow tutorial explained this.

I would say the tutorial does explain it  :)
https://www.youtube.com/watch?v=hCz4QkcUHBI&t=3s

> I am now trying to figure out how to center the aforementioned navigation bar on the bottom of the screen as seen here.

Add the following styles on your page:

```css 
.fp-slidesNav{
   text-align: center;
}
```

**Comment by wirkoenntenaber** [comment]
I was referring to how one can activate the horizontal navigation bar by using the additional line of code "slidesNavigation: true" in the "before </body> tag" section of an individual page in webflow, which indeed wasn't explained in the tutorial. Nevertheless you did help me well with suggesting to add the ".fp-slidesNav" style. So thanks a lot for the quick answer. :)

Another issue that I am trying to tackle is how to disable fullpage.js on mobile devices – I found [this documentation ](https://forum.webflow.com/t/how-to-disable-fullpage-js-on-mobile/21462/3), but it appears to break the fullPage.js horizontal slide feature on desktop resolutions on my end.

**Comment by alvarotrigo** [comment]
No problem! 
I'm glad you managed to solve you issues! 👍
