### ISSUE TITLE
window.innerHeight

### ISSUE THREAD

**Issue by EriCreator** [alvarotrigo/fullPage.js#4158]
### I was wondering why FullPageJS uses window.innerHeight 
According to this [source](https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight) , there are major drawbacks to using innerHeight. For example for chrome on android you should be using window.outerHeight instead because for some reason they are using the wrong value. 
To me [document.documentElement.clientHeight](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientHeight) looks like a much better solution.
Can you explain why you are using window.innerHeight in your implementation?

### Problems in my own implementation of FullPageJS
You can visit [this](https://kombucha-moya-noe.webflow.io/)  site and emulate a mobile device.   
When in reality the width and height of the Moto G4 are 360x640, these are the results I get in the console:
window.innerHeight
1072
window.outerHeight
640
document.documentElement.clientHeight
640

There also is a post on the webflow forum about this issue:
[webflow post](https://forum.webflow.com/t/wrong-height-for-fullpagejs-sections/157458?u=ericreator)

**Comment by alvarotrigo** [comment]
Are you experiencing any unwanted result on any mobile device?
If so, which mobile device, browser and OS ? 

I can't seem to reproduce the issue on [the demo page](https://alvarotrigo.com/fullPage/) on Chrome dev tools on the responsive view.

**Comment by alvarotrigo** [comment]
> There also is a post on the webflow forum about this issue:
> [webflow post](https://forum.webflow.com/t/wrong-height-for-fullpagejs-sections/157458?u=ericreator)

The demo page provided on the topic (https://webflow.com/website/fullpage-js-interactions) is using a very old version of fullpage (2.9.7) while we are now on 3.0.9

**Comment by EriCreator** [comment]
Wow that was a quick answer! 
I first noticed the issue on a Huawei P30 Lite phone, in the chrome browser.

And i was only able to reproduce the issue in the edge browser inspector.

**Comment by alvarotrigo** [comment]
> And i was only able to reproduce the issue in the edge browser inspector.

Check you are using the latest fullPage.js version 3.0.9

**Comment by EriCreator** [comment]
I just updated to version 3.0.9 and the issue persists on the Huawei P30 Lite aswell as in the Edge browser when emulating different mobile phones.
[updated website](https://kombucha-moya-noe.webflow.io/)

**Comment by EriCreator** [comment]
I'm starting to think that the issue must be on my end. 
Your [demo page](https://alvarotrigo.com/fullPage/) does not have the same issue.

**Comment by alvarotrigo** [comment]
You can create an isolated reproduction without any external code to fullpage.js and then let me know :)
This way we can check if the problem is on fullPage.js or outside it. And what's more important for you, what's causing it. 

Make sure to use the `<!DOCTYPE html>` tag.

**Comment by EriCreator** [comment]
@alvarotrigo  sorry, I am not very good with programming. 
Does this work as isolated reproduction?
[isolated reproduction](https://fullpagejs-test-d072a3-7eadf3fab8b3143f.webflow.io/)

There the window.innerHeight is correct but on iPhone and Android I can't see the bottom corners. The sections take up too much space. Also I apologize, I am sure that you must have explained how to do this somewhere, I just could not find it

**Comment by alvarotrigo** [comment]
Yeah, not a problem with fullPage.js but with the CSS you are applying.

If you replace `100vh` for `100%` on the property `min-height` it will work as expected.
![image](https://user-images.githubusercontent.com/1706326/107529574-4aa02e00-6bbb-11eb-9656-14750e9f32fa.png)

**Comment by EriCreator** [comment]
thank you so much!
