### ISSUE TITLE
Browser comptability issue

### ISSUE THREAD

**Issue by hemant2494** [alvarotrigo/fullPage.js#4159]
Hi,

i am facing a issue regarding link navigation, links are not working in firefox  browser, in other browsers like chrome, edge ,safari link's are working fine on single click but in case of firefox links active when click two times.

project developed in angular 6, installing fullpage.js using npm 

firefox version 85.0.2

please help me out, i am very thankful to you

Thanks,
Hemant
hemant2494@github.com

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on the [demo page ](https://alvarotrigo.com/fullPage/)or any of [the available examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by hemant2494** [comment]
Thank you so much for the reply, I found the solution ,it's because of I am
using hash routing in angular project , now I am replaced href to
(click)="fullpage_api.moveTo('secondPage',
2)". This click event and everything working fine.

**Comment by hemant2494** [comment]
Thank you so much for the reply, I found the solution ,it's because of I am using hash routing in angular project , now I am replaced href to (click)="fullpage_api.moveTo('secondPage',
2)". This click event and everything working fine.

**Comment by alvarotrigo** [comment]
Awesome to know you managed to solve your issue! 👍
