### ISSUE TITLE
"Blur" effect on scroll

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#4160]
@Noliferqt @alvarotrigo I am also seeing the "blur" effect on a couple of my sites using fullPage, although it's all content contained inside .fp-section for me (not just text).

Here's an example, you can see the text and bg image blur on scroll.
https://user-images.githubusercontent.com/14869814/108052928-b0216e00-7044-11eb-9838-5058a4602af0.mp4

Do you know what might be causing this?

_Originally posted by @julianvolp in https://github.com/alvarotrigo/fullPage.js/issues/4153#issuecomment-779756562_

**Comment by alvarotrigo** [comment]
@julianvolp can you reproduce such effect on any of the examples online?
https://alvarotrigo.com/fullPage/examples/continuous.html#secondPage

**Comment by Noliferqt** [comment]
I found the reason, I guess. I noticed: when I use silder plugin 'slick-slider' i have same problem. Sliders use css 'translate' mechanic like a your plugin. When I set useTransform: false for 'slick', and change this mechanic on other, 'blur effect' is gone.

**Comment by alvarotrigo** [comment]
Awesome you managed to find a solution! 👍

**Comment by Maadtin** [comment]
I  don't understand, how can we fix this? I'm not using slick slider and I'm having this problem :S

**Comment by alvarotrigo** [comment]
@Maadtin I can't see that happening on any of the demo pages. Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by Maadtin** [comment]
@alvarotrigo Sure! here it is: https://codesandbox.io/s/fullpage-qww0n?file=/src/App.js

**Comment by alvarotrigo** [comment]
I can't see any blur:
![dd](https://user-images.githubusercontent.com/1706326/109235454-fbb6e300-77cd-11eb-868b-21730db11a3b.gif)

**Comment by Maadtin** [comment]
Yeah It seems that it must be my monitor or smth because I can see a little bit of blur when scrolling but when I try to capture it on gif It isn't very noticeable.

**Comment by spikerx94** [comment]
I have the same blur problem. Additionally, the video has pauses and some elements load with a delay

https://youtu.be/mT2rZnyPN7E

**Comment by alvarotrigo** [comment]
@spikerx94 can you reproduce the problem on [the demo page](https://alvarotrigo.com/fullPage/) or any of its examples?

**Comment by spikerx94** [comment]
@alvarotrigo thanks for the answer. On the demo page, the blur is also visible.

https://www.youtube.com/watch?v=6KD60xoQKtw

**Comment by alvarotrigo** [comment]
Can you please detail:
- browser
- version
- OS

**Comment by alvarotrigo** [comment]
Also, can  you reproduce the issue here?
https://jsfiddle.net/chq2qfm8/63/

**Comment by spikerx94** [comment]
The problem is due to anti-aliasing, or rather its 3d transform rendering limitations. That's just the way it is with a heavy load of hardware resources. After restarting the computer, everything returned to normal.

My PC.
i7-7700k
gtx 1050 ti
16gb ram cl14 

I am afraid there is no solution to this problem

**Comment by alvarotrigo** [comment]
> I am afraid there is no solution to this problem

Seems like a browser's issue more than a fullPage.js one.
You can always open an issue on the webkit issues forum.
https://bugs.webkit.org/query.cgi?format=specific&product=WebKit
