### ISSUE TITLE
Cannot add a fixed navbar

### ISSUE THREAD

**Issue by shreyas-jadhav** [alvarotrigo/fullPage.js#4161]
I want to add a fixed navbar that resides only on the top of my page, but when I scroll the page the fixed property gets broken and the element becomes invisible. Also the position of my section title is messing when I scroll down and go back up

Link to isolated reproduction with no external CSS / JS
https://codepen.io/shreyasjadhav/pen/abBJgpx

Versions:
[Brave, Ubuntu 20.04, Laptop]

**Comment by alvarotrigo** [comment]
Just use `position:fixed` on the css properties for your nav. 
Right now it's not fixed on your codepen.

For CSS related questions I would encourage you to ask in another place like stackoverflow.com where they'll be able to help you much better.
