### ISSUE TITLE
Is it possible to have a call back function such as "Intention to leave"

### ISSUE THREAD

**Issue by hao-hao-hao** [alvarotrigo/fullPage.js#4166]
### Description

I am trying to implement an infinite scroll by using fullpage.js with gatsby. For example, I have 25 items with 6 items per page, total pages are 5.
I am currently using on leave call back to detect if I should load the next page. For example, if it is the last slide and the direction is down, I will redirect to the next page. This method works nicely except for one scenario - the page 5 which has only 1 element. As page 5 only has 1 element, the onleave call back can't be triggered.  

Is it possible to add a callback function such as intention to leave?

Thanks in advance.

**Comment by alvarotrigo** [comment]
> This method works nicely except for one scenario - the page 5 which has only 1 element. As page 5 only has 1 element, the onleave call back can't be triggered.

Try using `continuousVertical: true` or `loopBottom: true`
