### ISSUE TITLE
Clicking twice on the movetoRight button sends website to white screen

### ISSUE THREAD

**Issue by meetingingorkipark** [alvarotrigo/fullPage.js#4167]
Hi there.

I added movetoRight option to my button in Webflow here is the code:
`https://share.getcloudapp.com/YEuXPZZx
`
It works normally when clicking once, but if you click for the second time it sends website to the right with a high speed and the page becomes blank (white=
Please see what I mean:
https://share.getcloudapp.com/YEuXPZZx

I was using Webflow to build the website and the button specifically. I tried isolating the the code. HTML of the slide section and the CSS for the button. You may notice the -webkit-transform:translate3d(0) snippet. Which I had to use to remove flickering issue in safari. Please note the issue with the button was present even before inserting this snippet.  https://jsfiddle.net/dieinberghain/a94u21g3/

### Steps to reproduce it
1. Go to https://mauible1-48595201398e85f8-70a69fa68b6f0.webflow.io. There are 3 slides. 
2. Scroll to the second slide. Click on the button I am on board. It would move you to the 3 slide. Scroll back to the second slide.
3. Click on the button I ma board again.

### Versions 
[safari, Big Sur, MacBook ...] But the issue is present in any browser
Thank you

**Comment by alvarotrigo** [comment]
Can you try to reproduce your issue on this fiddle please?
https://jsfiddle.net/alvarotrigo/ea17skjr/

Thanks!

**Comment by meetingingorkipark** [comment]
hello, I am not very good with coding. sorry

**HTML:** could you please clarify if in the html sections I should paste the code from all the slides that I have or only from the slide where the button is?

**CSS:** should I pasted the CSS code only from the section as it set in the example on jsfiddle? do you need other classes?

**Comment by alvarotrigo** [comment]
Give it a read to this:
https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/

**Comment by meetingingorkipark** [comment]
I use only the snippets that are relative to the issue however there is nothing that appears in the preview box on jsfiddle 
https://jsfiddle.net/3kpj9mfg/

and thanks for the article. but my website consists of 3 pictures, three text blocks and a button that fails. it's not that I asking for too much.

**Comment by alvarotrigo** [comment]
I guess you've never used jsfiddle or codepen?
You were adding `<script>` tags on the JS tab, which I've now removed.
Also you were only adding a single section, so I've added a new one on top.

Here's the result:
https://jsfiddle.net/jafp6y5n/1/

But 2nd section still looks empty. Let me know when you fix that so I can try to reproduce your issue there.

**Comment by meetingingorkipark** [comment]
hi. its not the I've never used jsfiddle or codpen, it's more that I've never coded.
• Section 
- slide 1
- slide 2
- slide 3

I pasted the code for section and slide 2.  I used all the CSS classes that are present in the 2nd section and all the HTML code between between the first section and the last section. so what else is needed... I am not even sure how jsfiddle is supposed to reproduce such thing as img src="images/Logo.png. if it is a local image for Webflow it knows what it is, how is jsfiddle supposed to know what it refers to...

**Comment by alvarotrigo** [comment]
> I am not even sure how jsfiddle is supposed to reproduce such thing as img src="images/Logo.png. if it is a local image for Webflow it knows what it is, how is jsfiddle supposed to know what it refers to...

That's the whole point of my article :)
Just replace the image for any other, or just replace the image for text. What we need to do is simplify the problem to see if we can find the issue. 

Here I've removed the unnecesasry code and replaces your image for a text.
I also added an horizontal slider on that same section and I can't see any problem at all.
https://jsfiddle.net/pj7n56hg/

**Comment by alvarotrigo** [comment]
I believe yours is more a case in which you'll need the Business license to get premium support, as if you do not know how to code HTML or JS it will be difficult for you to find the issue. Specially as you don't know what webflow is doing under the hood.

In this forum we only provide support fullpage.js itself and we do not inspect external websites. We always require an isolated reproduction.

**Comment by meetingingorkipark** [comment]
I don't think that webflow makes a problem here. because all I have from webflow is 3 images and a button. Webflow's code is supposed to be super clean and I didn't make any changes in it. I was just adding the rest of the code which is the code from unpkg. and so the button works for the fist time meaning that the code is correct, but what happens next I am note sure because it depends on the code that I am using from you.

also in jsfiddle when clicking on the button, it jumps to the slide vertically, it doesn't scroll horizontally and to reproduce the issue you have to scroll back to the slide 2 after it was scrolled to the slide 3 and click on the button again. on jsfiddle after you press the button there is no way to scroll in general, but also there is no way to scroll back to the Slide 2 to try to click on the button again. 

it's the code from unpkg that creates the scrolling effect, right? so I am using all the scrips in jsfiddle. so why wouldn't it scroll the sections but jumps between them? :(

**Comment by alvarotrigo** [comment]
> also in jsfiddle when clicking on the button, it jumps to the slide vertically, it doesn't scroll horizontally and to reproduce the issue you have to scroll back to the slide 2 after it was scrolled to the slide 3 and click on the button again. on jsfiddle after you press the button there is no way to scroll in general, but also there is no way to scroll back to the Slide 2 to try to click on the button again.

Mmm I'm not sure I follow you here.
Let's clarify something before anything else. The terminology I use in fullpage.js (and all its docs) is the following:

sections => vertical panels
slides => horizontal panels within a single section.

Now, what I do on [the jsfiddle](https://jsfiddle.net/pj7n56hg/) is the following:

1 - I scroll down to the 2nd section with my mouse wheel
2- I then click on the only link with red background on the new section
3- It slides horizontally to the next slide on the right.

Where's the issue?

**Comment by meetingingorkipark** [comment]
hi, I deleted   <div class="section">
    aaaaa
    </div>
this from the top and now yes, it is correct it slides horizontally to the net section. 
so then to reproduce the issue you have to scroll back to the to that only link (red button) and you should press on it again. then the issue is happening. as I said it works normally on the website too, when clicking once. but not for the second time.
however it is not the case on jsfiddle because you can't scroll back to the red button link to try to press it again.

**Comment by meetingingorkipark** [comment]
because I believe this is your code from unpkg or queries scrolls the sections?

**Comment by alvarotrigo** [comment]
> however it is not the case on jsfiddle because you can't scroll back to the red button link to try to press it again.

Yes you can, you can use the keyboard :)
Now I added the `slidesNavigation` option so you can also click on the bullets.

Here's the link without the first section.
https://jsfiddle.net/pj7n56hg/2/

What is the issue then?
Expected behaviours vs current one? 

Are you using any extension?

**Comment by alvarotrigo** [comment]
I'll close the issue for now as it seems to be inactive. But let me know if you want to re-open it.
