### ISSUE TITLE
Fullpage 3.1.0.: event callback variables bug

### ISSUE THREAD

**Issue by jmplos** [alvarotrigo/fullPage.js#4168]
### Description
I noticed after updating to fullpage for elementor 1.7.0. (which updates fullpage.js to v3.1.0.), javascript in callback events stopped working: now, they throw errors with their variables. 'destination' is no more there, and 'origin' is just undefined. Error trace for 'destination':

  | afterRender | @ | (index):5324
  | Ne | @ | fullpage.js:1786
  | Ee | @ | fullpage.js:1170
  | (anonymous) | @ | scrolloverflow.js:2231
  | load (async) |   |  
  | p.init | @ | scrolloverflow.js:2229
  | init | @ | scrolloverflow.js:2386
  | (anonymous) | @ | fullpage.js:935
  | (anonymous) | @ | fullpage.js:663
  | (anonymous) | @ | (index):5322

### Link to isolated reproduction with no external CSS / JS
Just copied yours, and set up a console.log to show destination.index:
https://codepen.io/jmpel/pen/NWbvQqj

### Steps to reproduce it
1. Just move to other section. onLeave tries to print destination.index to console, and fails to find destination.

### Versions 
Chrome: 88.0.44324.150
Firefox: 85.0.2 (64-bit)
OS: windows 10 (last retail version)

**Comment by alvarotrigo** [comment]
You are forgetting to add the arguments on your callback:

```js
onLeave: function()
vs
onLeave: function(origin, destination, direction) 
```

**Comment by alvarotrigo** [comment]
If you still think there's a problem on the plugin for Elementor, can you please use [the contact form](https://alvarotrigo.com/#contact) to report it?

We keep this forum only to treat issues regarding fullPage.js.
So it might be the case the problem is on the Elementor side if we are not able to reproduce it on fullPage.js.
