### ISSUE TITLE
License Key invalid when inserted on URL to activate

### ISSUE THREAD

**Issue by IreneMartins** [alvarotrigo/fullPage.js#4170]
Hey, 

I've just bought the Hobby License on your website, to inserted it on Webflow in my personal website (portfolio). 

It's written [here](https://github.com/alvarotrigo/fullPage.js/wiki/How-to-activate-a-fullPage.js-extension) that I've should have received this [link ](https://alvarotrigo.com/fullPage/extensions/activationKey.html) by email, but I did not - only the License Key.

Based on this explanation, I've inserted the License Key on the activation page but it's giving me as "Invalid" in all the products. 

Can you please verify? This functionally is the only element missing on my website!

Thanks!

**Comment by alvarotrigo** [comment]
No problem!
Please contact us through the [contact form](https://alvarotrigo.com/#contact) and we'll help you out.
