### ISSUE TITLE
Do I have to make my website source code open to use fullPage.js with open source license

### ISSUE THREAD

**Issue by khoivan88** [alvarotrigo/fullPage.js#4172]
Hi,

Thank you for creating this very nice project. I looked at the demo page and I thought it would be great for creating a personal website for an academic research group. I am not an expert on licensing so I just want to double check with you on this topic. If I used fullPage.js for a website, would I have to make the source code for that website using open license as well and the repo (e.g. github repo) open to the public?

Thank you very much!

Best wishes

**Comment by alvarotrigo** [comment]
I can't provide you with license advise as I'm not a lawyer myself.
But in general terms if you want to use fullPage.js for free you'll have assign the GPLv3 license (or a compatible one) to your project and make your project's code open source.

If you have doubts, the easiest way is getting a comercial license for less than 11 USD. This way you avoid any legal issues and you'll be contributing to fullPage.js maintenance by supporting me :)

**Comment by khoivan88** [comment]
I'm sorry I did not respond sooner. Thank you so much for your answer. Since I cannot disclose the source code, I switch to using your pagepiling.js and it works really well. Unfortunately I am not in a financial situation to be able to buy the commercial license for fullPage but it is very affordable and I would definitely keep it in mind for future projects.

**Comment by alvarotrigo** [comment]
No problem!
