### ISSUE TITLE
Parallax Extension (Version: 0.2.4) Bug with settings verticalCentered:false, autoScrolling: false

### ISSUE THREAD

**Issue by karthiksekark** [alvarotrigo/fullPage.js#4173]
Description

Fullpage Parallax Extension is not working with settings verticalCentered:false, autoScrolling: false,

Considering the HTML code suggested in the documentation with settings: verticalCentered:false, autoScrolling: false the scenario is broken.

Steps to reproduce it

JS installed:
fullpage.parallax.min.js
fullpage.extensions.min.js

JS code:
```
jQuery('#slider').fullpage({
parallax: true,
parallaxKey: '..............',
parallaxOptions: {
type: 'reveal',
percentage: 62,
property: 'translate'
},
verticalCentered:false,
autoScrolling: false,
fitToSection: false
});
```

Versions
[fullpage 3.1.0 - Extension 0.2.2]
[Parallax Extesion 0.2.4]

**Comment by alvarotrigo** [comment]
Can you please contact us using the [contact form](https://alvarotrigo.com/#contact) and provide us with a link where we can reproduce your issue?
