### ISSUE TITLE
fullpage.js initialization prevents content editing on Webflow 

### ISSUE THREAD

**Issue by thedamruta** [alvarotrigo/fullPage.js#4174]
Hello,

I have a website built with Webflow [www.annakempin.com](url) and my client a week ago noticed that it's not possible to edit content in the editor mode... I am seeing these errors in the console:
<img width="792" alt="Screenshot 2021-03-05 at 18 12 01" src="https://user-images.githubusercontent.com/80633198/111072651-bf78c780-84db-11eb-9a0f-d910ccf704eb.png">

I am experiencing this issue on latest versions of Chrome and Firefox.

As soon as I commented out the var myFullpage = new fullpage('#fullpage', { ... }); script, content editing works and there are no issues or errors. 

I am using the latest version fullpage.js script from CDN in my head tag and Vanilla JS example with all options code snippet right before body tag. 

Well before, fullpage.js and content editing worked without problems, problem seems recent. What could be the issue? 
Why Webflow and fullpage.js are having a code conflict? Maybe I have to add or remove one of the options? Which one could it be? Maybe I forgot something to take into consideration?

Kind regards,

Ruta D.

**Comment by alvarotrigo** [comment]
Look at the source file for those errors. (you cut it on the right side of the picture)
They are not generated by fullPage.js but by webflow. 

Also, I'm not having the problem on the clonable example:
https://webflow.com/website/Fullpagejs-basic-example
