### ISSUE TITLE
super slow mobile version specially on horizontal scroll 

### ISSUE THREAD

**Issue by emsoft1** [alvarotrigo/fullPage.js#4175]
I have a fullpage extension for horizontal scrolling and it runs smoothly in the web version but when I switch to the mobile version it gets super slow and when to sections that have horizontal scrolling it gets super slow that not useable. 

this problem happened after that I change the horizontal js file (from the free version that get from your web page to the version that purges and you send me ).

it is my GitHub page that you can check out for more info. 

for solving this problem I reduce my graphical elements.
I try to reduce the extra js code that I have.
try to reduce the size of the images but steel noting is change and steel it slow.

 https://github.com/emsoft1/tech001/blob/main/examples/scroll-horizontally.html
the problem I just in the mobile version. 
the webpage is also is online you can check it out.

**Comment by alvarotrigo** [comment]
For extensions issues please use the support we provide through the [contact form](https://alvarotrigo.com/#contact).
Use the email you used to purchase your extension.
