### ISSUE TITLE
Click fired on first scroll of floating extra-fullpage content, using scrollOverflow:true and normalScrollElements

### ISSUE THREAD

**Issue by rastafan** [alvarotrigo/fullPage.js#4176]
Hi. i stumbled upon a weird behaviour using scrollOverflow:true and normalScrollElements pointing to an element outside the fullpage container.

NOTE: This behaviour was tested on Android Chrome, iOS Safari, and Mobile mode Chrome on Desktop. So every scroll/drag/swipe is to be intended as a touchscreen event.

The case is: 
- Fullpage container with multiple slides, one with scrolling content (in my case was the last slide)
- Absolutely positioned element floating above the fullpage container, with scrollable content which reacts to tap
- normalScrollElements with selector pointing to the floating element
- scrollOverflow:true and scrollOverflowOptions:{scrollbars: false}

The scrolling content inside the fullpage container works good, and so does the scrolling inside the floating element.

But, when scrolling the floating content, the drag/swipe fires a tap/click event too, causing that content to react to it while scrolling. 

This happens only on the FIRST swipe/scroll/drag of the floating content.

Note that this does NOT happen when first interacting/scrolling with the scrolling slide inside the fullpage container, and then trying to scroll the floating content.

If i turn scrollOverflow:false , the scrolling of the floating element works fine, but the scrolling of the fullpage slide of course does not (which i believe is the correct behaviour).

I hope i made myself clear.

Thank you for your hard work.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction

**Comment by rastafan** [comment]
Sure, here you go:
https://jsfiddle.net/rastafan/mawp162c/31/

NOTE: To reproduce the issue, test it on a tablet.

Steps:

1: tap the red div to open the floating element
2: scroll the floating content

You'll se a "+" sign appear on the element, but it should only appear on the "click" event.
You can notice that it only happens until the first scroll of the floating content, then everything works right.

But, if you follow the following steps:


1: scroll to the last fullpage slide
2: scroll the last slide content
3:  tap the red div to open the floating element
4: scroll the floating content

Everything works fine and the extra "click" event is not fired.

please feel free to ask for more informations if i missed something.

Thank you very much.

**Comment by zhicong** [comment]
I was struggling with this bug as well, but finally found a solution in the iScroll discussions (which has been suggested elsewhere here too). It seems like an extra tap event is fired on the first scroll on some Android devices. Try using the click event like this instead of the tap event:

`scrollOverflowOptions: { click: false, preventDefaultException: { tagName: /.*/ } }`

https://github.com/cubiq/iscroll/issues/674#issuecomment-41500613
