### ISSUE TITLE
Section can't be full-width

### ISSUE THREAD

**Issue by karchung0930** [alvarotrigo/fullPage.js#4177]
Hi Alvaro, I don't know why my section can't be full-width after applying the fullpage.js

I already make the section width as 100% but the problem still exist, there is one rule overwriting the max-width as 1140px, but after I try disable the fullpage.js the section become full-width again
![screenshot](https://user-images.githubusercontent.com/73235650/112278873-3f621700-8cbe-11eb-9c1e-d486304e8479.jpg)

**Comment by alvarotrigo** [comment]
Sounds like a CSS question.
I would recommend you asking that on stackoverflow.com where they'll be able to help you much better.

Otherwise feel free to take any of the examples available on the examples folder as your starting point.
