### ISSUE TITLE
Forms not working in long section with scrollOverflow: true

### ISSUE THREAD

**Issue by AndyRakia** [alvarotrigo/fullPage.js#4178]
When I create a long section with scrollOverflow: true and with the scrollOverflow library my forms stop working.

The same form works in a standard full page section. 

In the below fiddle the submit button works in section 1 (standard section) but not in section 3 (long section)

https://jsfiddle.net/AndyRakia/8pay7135/9/

Latest Google chrome / PC

**Comment by alvarotrigo** [comment]
Check out this topic:
https://github.com/alvarotrigo/fullPage.js/issues/2837
