### ISSUE TITLE
Custom html markup for control arrows?

### ISSUE THREAD

**Issue by stratboy** [alvarotrigo/fullPage.js#4179]
Hi! Is it possible to use custom html markup for control arrows? I know I can edit them via css, but i'd like to change markup instead. How to? Thank you.

**Comment by alvarotrigo** [comment]
Sure, why not :) 

Has been answered many times on the forum.
Check out some of these topics:
https://github.com/alvarotrigo/fullPage.js/issues?q=is%3Aissue+is%3Aclosed+custom+arrow

Also try a search on stackoverflow if you don't find luck here.
https://stackoverflow.com/questions/25785914/css-change-arrows-on-fullpage-js
https://stackoverflow.com/questions/29583338/css-change-the-arrows-in-fullpage-js-to-custom-images
