### ISSUE TITLE
control arrows do not delegate click events

### ISSUE THREAD

**Issue by stratboy** [alvarotrigo/fullPage.js#4180]
Hi, I just tested this:

```
$(document).ready(function () {
  let arrow = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="50"><path d="M1.907 50L0 49.002l13.537-24L0 1.007 1.903 0l14.098 24.997z"/></svg>';
  
  // The changes that were made
  $('.fp-prev').append(arrow);
  $('.fp-next').append(arrow);
});
```

It adds svg arrows inside default ones. Once done, they will no longer work on click. That's probably because source code won't delegate events. Should be fixed. Thank you

**Comment by alvarotrigo** [comment]
They are already delegated, see the code here:
https://github.com/alvarotrigo/fullPage.js/blob/master/src/fullpage.js#L739

**Comment by alvarotrigo** [comment]
Also, you aren't changing the `.fp-prev` or `.fp-next`, so it should work.
Here's a demo:
https://jsfiddle.net/qvp6yuzm/

Of course, the event is on `.fp-prev` and next, not on your svg :) 

I would suggest you to use the methods `moveSlideRight` and left if you want to create your own arrows like I did on the [main page](https://alvarotrigo.com/fullPage/#page2).

**Comment by stratboy** [comment]
Yes, moveSlideRight/Left is the thing! Thank you!
