### ISSUE TITLE
responsive [autoScrolling: false] for slides?

### ISSUE THREAD

**Issue by stratboy** [alvarotrigo/fullPage.js#4182]
Hi, I'm currently using responsiveWidth width option, but surprisingly, when enabled, autoscroll applies only for vertical main sections and not for horizontal slides.

Is there a way to activate it on slides?

**Comment by alvarotrigo** [comment]
> Is there a way to activate it on slides?

Not quite sure what you mean by that. 
Slides won't get a horizontal scrollbar.

The most you can do at the moment is use the [Responsive Slides extension](https://alvarotrigo.com/fullPage/extensions/responsive-slides.html) to turn horizontal slides into vertical sections on responsive.
