### ISSUE TITLE
After calling .reBuild the onLeave function doesn't fire anymore

### ISSUE THREAD

**Issue by lbSOPG** [alvarotrigo/fullPage.js#4183]
https://jsfiddle.net/0fe2da3q/1/
If you comment out the reBuild call you will see the onLeave output in the console.

This seems to happen because in fullpage.js in the reBuild function on line 500, isResizing is set to true, but never set to false again. If I comment out isResizing or set it to false at the end of the function onLeave works again.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
It does look like a bug! 

I'll investigate it further!

**Comment by sanderjn** [comment]
> https://jsfiddle.net/0fe2da3q/1/
> If you comment out the reBuild call you will see the onLeave output in the console.
> 
> This seems to happen because in fullpage.js in the reBuild function on line 500, isResizing is set to true, but never set to false again. If I comment out isResizing or set it to false at the end of the function onLeave works again.

Thank you so much, I've been trying to work this out for hours. isResizing = false at the end of the function worked for me 👍

**Comment by alvarotrigo** [comment]
Fixed on the dev version 3.1.1:
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js

**Comment by alvarotrigo** [comment]
3.1.1 merged!
