### ISSUE TITLE
auto slide the horizontal slides 

### ISSUE THREAD

**Issue by codezion-soft** [alvarotrigo/fullPage.js#4184]
### Link to isolated reproduction with no external CSS / JS
I have Using This Code in JS . The Slide  scroller needs to work on its own .  How to do it?
![image](https://user-images.githubusercontent.com/79931653/112711081-a6184800-8eeb-11eb-8dbc-50bb3892ad6f.png)

$('#fullpage').fullpage({
    		licenseKey:'##########',
    		//options here
    		scrollHorizontallyKey:'########',
    		verticalCentered:true,
    		resize:true,
    		autoScrolling:false,
    		scrollHorizontally: true,
    		fixedElements:'',
    		fitToSection:false,
        scrollingSpeed: 1250,
    		css3:true,
    		easingcss3:'ease-out',
    		controlArrows:false,
    		slidesNavigation:true,

    onLeave: function(index, nextIndex, direction){
            if (index == 2 && direction == 'up') {
                $('#menu').fadeTo("slow",0);
            }
        },
    		afterload: function(anchorlink, index,direction) {
           if (index > 1){
                $('#menu').fadeTo("slow",1);
            }

    			if( index==('#fullpage .section').length ) {
               $fn.fullpage.setAutoScrolling(false);
           }
           $(document).scroll(function(){
           	var last_section =$('#fullpage').find(".section").last();
           	var offset = last_section.offset();
           	var w = $(window);
           	if(offset.top - w.scrolltop()>0){
           		$fn.fullpage.setAutoScrolling(true);
           	}
           });
         }

    	});

**Comment by alvarotrigo** [comment]
See my answer here:
https://stackoverflow.com/a/66655178/1081396
