### ISSUE TITLE
Problemas con el menú

### ISSUE THREAD

**Issue by serna3** [alvarotrigo/fullPage.js#4187]
Hola Álvaro! Estoy utilizando fullpage.js con Elementor y no tengo ni idea de código. 
Mi duda es, que a cada sección le he dado un anchor y he creado un menú con "Custom links" en vez de páginas ya que con fullpage se diseña todo en una única página. Lo que me pasa es que lincando el menú con custom links y no con páginas, el estado activo de la sección en el menú no me funciona. Es decir, a pesar de tener el menú programado con un color específico cuando esté activa y sí redirigirme a esa sección, el menú siempre aparece en estado normal.

Por otro lado, te quería preguntar si hay alguna manera de editar el tamaño o la posición de los "slide navigation", como el tamaño de las flechas, o la altura de los puntos, ya que en el responsive se me cortan.

Muchas gracias!

**Comment by alvarotrigo** [comment]
Para preguntas [del plugin oficial de Elementor para fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) usa el contacto de formulario, gracias!
https://alvarotrigo.com/#contact

**Comment by alvarotrigo** [comment]
Pregunta en inglés a ser posible. La persona de soporte habla inglés.
