### ISSUE TITLE
Anchor links with active side navigation problem

### ISSUE THREAD

**Issue by webarkhu** [alvarotrigo/fullPage.js#4188]
Hi :)

I purchased the fullpage.js few weeks ago, with the scroll horizonatly extension, but I have a little problem. 
I want to use an anchor link, to the last section with data-anchor attributes, but if I enable the navigation dots, on the right side, it will be ruined. When I scroll that section where i set the data-anchor tag, the navigation dot doesn't get the active class.  

### Versions
Browser: Chrome 89.0.4389.90
I use the fullpage.extensions.min.js (3.0.9) with the fullpage.scrollHorizontally.min.js (0.0.4)

**Comment by alvarotrigo** [comment]
`data-anchor` should be in all sections or none.
But you can not have a section with them and others without them.

**Comment by webarkhu** [comment]
Thank you for your fast response. 
I updated my code, and the all section get the unique data-anchor tag, but the all of active dots disappear. 

https://codepen.io/webark/pen/xxgggXP

**Comment by alvarotrigo** [comment]
Make sure to use the latest version 3.1.0.
https://unpkg.com/fullpage.js@3.1.0/dist/fullpage.extensions.min.js

**Comment by webarkhu** [comment]
It was solved. Thank you for your help :)
