### ISSUE TITLE
slide events not called in ios chrome

### ISSUE THREAD

**Issue by johanvs** [alvarotrigo/fullPage.js#4190]
### Description
In chrome ios, the slide events are not called (onSlideLeave, afterSlideLoad)
(it works in safari, and on android chrome, but not in chrome ios)

The page is loaded from a link.
When I reload the page with the refresh in the menu, it doesnt work better.
BUT when I go to the url bar, and reload the page from here, then it works !!

### Steps to reproduce it
```
$('#fullpage').fullpage({
        onSlideLeave: function (section, origin, destination, direction) {
            console.log("test1");
        },
        afterSlideLoad: function (section, origin, destination, direction) {
            console.log("test2");
        },
});
```
When swipping manually, or with `fullpage_api.moveSlideRight();`, any log is seen.

### Versions 
Chrome, ios, iPhone 6

**Comment by alvarotrigo** [comment]
Are you using the latest version 3.1.0?

**Comment by alvarotrigo** [comment]
OH, my bad! You might have to use the dev version 3.1.1:
https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js

Related with https://github.com/alvarotrigo/fullPage.js/issues/4185

**Comment by johanvs** [comment]
Thanks ! (yes, I was using 3.1.0)
