### ISSUE TITLE
The widget in Elementor is not working (after enable fullpage.js)

### ISSUE THREAD

**Issue by johnson-0304** [alvarotrigo/fullPage.js#4192]
### The widget in Elementor is not working

When scroll to this section, it should be start counting the numbers
![CPT2104121041-420x260](https://user-images.githubusercontent.com/75473029/114333792-c1d24e00-9b7b-11eb-85f8-7910fa65b5c6.gif)

But when i scroll to this section(with fullpage enabled), the widget will not start to count
![image](https://user-images.githubusercontent.com/75473029/114333549-2640dd80-9b7b-11eb-95aa-eb8005bb92e8.png)

###Steps to reproduce it
When scroll this widget, the widget will not active.
I guess the reason is the widget cannot detect it when the browser scroll to this scetion
not sure how to fix this

I appreciate your solution!

**Comment by alvarotrigo** [comment]
If you are using [the official fullPage.js plugin for Elementor ](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) then please use the [contact form](https://alvarotrigo.com/#contact) to use the support for it.
