### ISSUE TITLE
Swiping not working on mobile with container position absolute

### ISSUE THREAD

**Issue by ivevil** [alvarotrigo/fullPage.js#4194]
Hello there,

I am using fullpage.js and I am very happy with it, but I experienced the issue with text on mobile which is set to absolute. When swipe over text it doesn't swipe to the next section. There is only one small piece of area (without text) where swiping can be done and next section is shown.
Because of the scrolling effects - Video needs to go through text - I really need text be positioned to absolute.

On desktop everything is working fine since I am using scrolling on my mouse or my keyboard. It doesn't depend on elements - are they absolute positioned or not.

Is there any workaround for this?

Thanks,
Ive

**Comment by alvarotrigo** [comment]
> When swipe over text it doesn't swipe to the next section. There is only one small piece of area (without text) where swiping can be done and next section is shown.

Make sure to add the text inside fullpage.js wrapper.  
Or if you prefer, use the option `touchWrapper: ".your_selector"`, it can be `touchWrapper: "body"` for example.

**Comment by ivevil** [comment]
Thanks, 
but when I try to use touchWrapper I've got an error in console, saying:
"[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>"

Is there any solution for this?

**Comment by alvarotrigo** [comment]
Have you tried placing your element inside the fullpage.js wrapper?
If it is absolute positioned it should be inside the section/slide you want to use it in.

**Comment by ivevil** [comment]
Yes, I tried it but then I am losing the effect that I need to have.
Regarding designs I needed to create two words in container at the top of everything and then the videos are sliding while scrolling mouse. Both words are with position absolute and depends on number of the slide/video I need to set z-index of the word to back or top. 
So i.e. if the two words are LOREM IPSUM on the first slide both words are going to be shown, on the second slide LOREM is going to be on the top of the video and IPSUM at the back, and third slide is LOREM is on the back and IPSUM on the top.
So the effect is text is always staying on the top and videos are sliding between.

When I add text in the slides then I don't have that effect that text is always on the top.

Everything works perfectly fine everywhere except for swiping on mobile, when you swipe over text slides are not sliding, only if you swipe over the area where text is not there.

Thank you very much for your help. I appreciate that.

**Comment by alvarotrigo** [comment]
> When I add text in the slides then I don't have that effect that text is always on the top.

Tried z-index?

**Comment by alvarotrigo** [comment]
Try instead `touchWrapper: document.body,`

**Comment by ivevil** [comment]
Already using it with z-indexes. I tried adding touchWrapper: document.body, but it is not working, still the same error in console and it is not possible to swipe over text, only on the area without text around. 

I also tried to rearrange to use the text inside the fullpage container, but I can't make it to get the effect that text is staying always on the top and not moving while sections are sliding. I tried with z-index, and currently also there are z-indexes on elements.

Btw if it is important to know I am using jQuery. Maybe it is bug within jQuery, I tried to google the solution for it, but didn't have luck.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by ivevil** [comment]
Please find it here: https://codepen.io/ivevil/pen/bGgMwYw

Imagine instead of the "Section 1" text there is a video - but the logic is the same. Text is over it and it needs to stay on top while videos are scrolling in the background.
Everything is working perfect on desktop.
When you open it on mobile there is an issue I mentioned before (area of scrolling is just around the text). When you scroll over text nothing is happening. In console there is an error saying "[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See < URL >"

Thanks again.

**Comment by alvarotrigo** [comment]
@ivan-balanar make sure to use the latest version 3.1.0.
