### ISSUE TITLE
Is is safe if put license key into html file?

### ISSUE THREAD

**Issue by kidqn** [alvarotrigo/fullPage.js#4196]
### Description
Hi Alvarotrigo,
I've bought the license key for fullpage js. But when I read the document and example, I see the key is put directly in html file.
Is it safe or not? Since someone can copy and paste somewhere

// background.html file
new fullpage({
    licenseKey: 'YOUR_KEY_HERE'
});

**Comment by alvarotrigo** [comment]
Yes, see this:
https://alvarotrigo.com/fullPage/help/Can-I-hide-fullPage-js-license-key/

**Comment by kidqn** [comment]
> Yes, see this:
> https://alvarotrigo.com/fullPage/help/Can-I-hide-fullPage-js-license-key/

Thank you. 
One thing, can I use a key with 2 sites not the same time?

I intend to test fullpagejs (+key) on my dev site. 
After testing, I remove it from dev site, then deploy to product for customer.
Is it okay?

**Comment by alvarotrigo** [comment]
> Is it okay?

Yes
