### ISSUE TITLE
Disable fullPage.js plugin for Gutenberg

### ISSUE THREAD

**Issue by tomazin116** [alvarotrigo/fullPage.js#4198]
How can I disable fullpage.js in a WordPress plugin (Gutenberg) on mobile devices? Is there a setting for that?

**Comment by alvarotrigo** [comment]
There's a responsiveWidth option, but you for questions regarding the [official fullpage plugin for Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) please use the [contact form](https://alvarotrigo.com/#contact).
