### ISSUE TITLE
fullpage_api.setAutoScrolling(true) not working

### ISSUE THREAD

**Issue by kidqn** [alvarotrigo/fullPage.js#4199]
### Description

I want to auto play fullpagejs section carousel. 
But when I set fullpage_api.setAutoScrolling(true), nothing working.

It only work with an example using interval:
```
$('#fullpage').fullpage({
			verticalCentered: false,
			afterRender: function () {
				setInterval(function () {
					fullpage_api.moveSectionDown();
				}, 1000);
			}
		});
```

### Versions 
[Chrome, Windows 10]

**Comment by alvarotrigo** [comment]
Check out the tutorial  on how to [create an automatic horizontal slider](https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/) on the [Help Center](https://alvarotrigo.com/fullPage/help/).
