### ISSUE TITLE
repeat section colors

### ISSUE THREAD

**Issue by Mlgprokn** [alvarotrigo/fullPage.js#4201]
Hello,

I would like to use gray and white for my section colors and repeat the two colors over and over again, meaning that if I have 6 sections(this could change, depending on the list I receive from my API) the section colors will be:
Section 1 - gray
Section 2 - white,
Section 3 - gray,
Section 4 - white, 
Section 5 - gray, 
Section 6 - white,

The way that I do this now is by:
```javascript
sectionsColor: ['#D3D3D3', '#fff', '#D3D3D3', '#fff', '#D3D3D3', '#fff']
```
I would rather have something like:
```javascript
sectionsColor: ['#D3D3D3', '#fff']
```
But if I do it this way I only get the colors for the first two sections, is there some way to set the colors to repeat?

**Comment by alvarotrigo** [comment]
> But if I do it this way I only get the colors for the first two sections, is there some way to set the colors to repeat?

Nope. Just fill the whole array :)
Manually or dynamically using JS.

**Comment by alvarotrigo** [comment]
Or easier yet. Just use CSS for your sections background and remove the `sectionsColor` option.
With css you can use ODD and EVEN selectors to do that with just two styles.

Demo online:
https://codepen.io/alvarotrigo/pen/qBRQZxY

```css
.section:nth-child(odd) {
    background: #777;
}
.section:nth-child(even) {
    background: blue;
}
```
