### ISSUE TITLE
Slides jump around on mobile when scrolling through sections

### ISSUE THREAD

**Issue by brandonalexandertong** [alvarotrigo/fullPage.js#4202]
I'm developing a website right now with fullpage, and have modified the fp-prev and fp-next buttons in css so that they take up the full width and height of the section they are in, and are transparent, so when you click on one or the other side of the screen it will take you to the next slide. When switching to responsive however, all of the touch events cause the buttons to fire multiple times, so when scrolling with your finger, or tapping once, the slides will change multiple times and create a really ugly experience.

I went into the developer tools, and found that if I disable the touchstart event that is applied to the document, the page functions as it should, though because I can't access the function in the extensions.min.js file, I'm unable to disable this event listener. (screenshot below)

Things I've already tried:

1. touchSensitivity set to 0 or 1: helps a bit, but issue still remains
2. fullpage_api.setAllowScrolling(false, 'left, right'): this option seems like what I would need, except it completely blocks the slides from being moved to even with a click, so this won't work
3. document.removeEventListener('touchstart', ye) - ye being the function referenced in the developer tools that is supposed to be adding the touchstart event listener, though this throw the error that ye hasn't been defined.

This is an issue on ios devices in mobile.

<img width="578" alt="Screen Shot 2021-04-22 at 11 52 13 AM" src="https://user-images.githubusercontent.com/42078837/115745189-30c05b80-a361-11eb-9788-e198d404b1e1.png">

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by brandonalexandertong** [comment]
Alvaro, 

Thank you for the fast response, here's a link to the reproduction:

https://codepen.io/brandonalexandertong/pen/JjEwGGP

Notice how on mobile when you click on a slide it moves forward two slides, one slide for touchstart and one slide for touchend. Also notice how when scrolling past a section it registers the touchmove as a click and changes the slide.

**Comment by alvarotrigo** [comment]
I can't reproduce the issue. I see no problem at all when scrolling.
Tested on Chrome, Safari and Firefox on iOS

See the video:
![aaa](https://user-images.githubusercontent.com/1706326/115786269-dbb43200-a3c0-11eb-8c85-eb091cfc6ee6.gif)

**Comment by brandonalexandertong** [comment]
Apologies, as I may not have been clear with the issue - the behavior is when clicking on a slide, so when you tap it moves two slides forward. Also, as per scrolling the issue is more apparent when you scroll and hold down your finger within a section. Attached is a video taken on my phone of the behavior - the first half is me tapping (you can see the slides jumping two forward)
-the second half is me scrolling within a section and keeping my finger down (you can see the slide changing rapidly)

https://user-images.githubusercontent.com/42078837/115789396-14d5ad80-a393-11eb-82e8-68187f84bfe6.mov

**Comment by alvarotrigo** [comment]
You are setting the speed to 0, so that's the expected behavior. 
Why are you doing so in any case?

**Comment by brandonalexandertong** [comment]
The reason I’m setting it to 0 is because I don’t want the transition between slides to be gradual, I want it to be instantaneous, but I don’t want the transitions between sections to be instant. So I set it to 0 when moving between slides and set it back to 700 otherwise. 
I’m confused because the behavior works perfectly on desktop, ie. 1 click = 1 slide but for some reason on mobile one touch creates multiple events and multiple slide changes. Like I mentioned in the first comment, disabling the touchstart event from dev tools on the #document seems to fix it, but I can’t figure out how to disable that within the extensions.min.js since its minified

**Comment by alvarotrigo** [comment]
> The reason I’m setting it to 0 is because I don’t want the transition between slides to be gradual, I want it to be instantaneous, but I don’t want the transitions between sections to be instant. So I set it to 0 when moving between slides and set it back to 700 otherwise.

Use instead the method [`fullpage_api.silentMoveTo`](https://github.com/alvarotrigo/fullPage.js#silentmovetosection-slide).
You can easily attach it on click and you'll fix the issue :)

**Comment by brandonalexandertong** [comment]
Apologies, have been away from my computer the past few days! I'm not really sure how I would implement the silentMoveTo in this case. Could you elaborate a bit more?

**Comment by alvarotrigo** [comment]
See the demo:
https://codepen.io/alvarotrigo/pen/doqOeY

Just assign it to any click/touch event you need. 
Not sure what you want to accomplish, perhaps you can elaborate what behaviour you are looking for?

Silent move clicking on an arrow?
Silent move when dragging on touch devices?

**Comment by brandonalexandertong** [comment]
So as an overview:

I want slides to move instantly between themselves, and sections to move at the normal scrollingspeed (700 in this case):

As per this demonstration:
https://codepen.io/brandonalexandertong/pen/JjEwGGP

This is all perfect, the only issue is that on mobile when clicking within a section on a slide if you press down 1 time the slide moves forward two times and if you scroll within a section the slide will change a bunch of times even though you aren't tapping (see above video for a demonstration of what it looks like)

I basically just need to move instantly between _slides_, while maintaining the animation between _sections_, and the only way I was finding that you could do that was by setting the scrolltime to zero between slides and then setting it back between sections. I pulled that idea from [this](https://github.com/alvarotrigo/fullPage.js/issues/2490) previous answer.

SilentMoveTo might be helpful, though it requires the parameters of where to move to, and I need a dynamic solution for each section. In the example you just sent, you're assigning one button to move to the second slide of the second section, but I need a method to move to the next slide, or the previous slide, or back to the beginning if it's the last slide, etc etc in the same way that the plugin already functions. 
I attempted to achieve this by using the onSlideLeave callback and inputting the current section and destination slide as such:

onSlideLeave: function (section, origin, destination, direction) {
  silentMoveTo(section.anchor, destination.index)
  }

However this creates an infinite loop and breaks the site, and I haven't seen anyway for me to use silentMoveTo dynamically. In short I just want to move instantly between slides without it registering one click as two slides on mobile and without it cycling rapidly through slides.

**Comment by brandonalexandertong** [comment]
Commenting the solution I eventually landed on, though it's a bit hacky and I'm still not sure why above problem is happening.

I iterate over all of the previous and next buttons, and run the scrolling speed method, slide left or right, and change scrolling speed back

`const prevButtons = document.querySelectorAll('.prev')
const nextButtons = document.querySelectorAll('.next')

prevButtons.forEach(function (button) {
  button.addEventListener('click', function () {
    fullpage_api.setScrollingSpeed(0)
    fullpage_api.moveSlideLeft()
    fullpage_api.setScrollingSpeed(700)
  })
})

nextButtons.forEach(function (button) {
  button.addEventListener('click', function () {
    fullpage_api.setScrollingSpeed(0)
    fullpage_api.moveSlideRight()
    fullpage_api.setScrollingSpeed(700)
  })
})`
