### ISSUE TITLE
How can I setup scrollOverflow block hight and weight? 

### ISSUE THREAD

**Issue by kaletvintsev** [alvarotrigo/fullPage.js#4203]
How can I setup scrollOverflow block hight and weight? I want to display scrolling block on center of screen and it smaller than window height and width, but when I set custom height of scrollOverflow elements, content didn't adjusts to block heigh.
Tis is an example of my design.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/26550920/115878585-5af14680-a451-11eb-9f67-ab66984796ad.png">

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by kaletvintsev** [comment]
https://codepen.io/kaletvintsev/pen/ExZrerq

After end of scrolling, I expect the "END END END..." text at the end of the block, but the scrolling ends before this text appears.
Also scroll not working outside the scrolling element

**Comment by alvarotrigo** [comment]
You are not using the required structure and are modyfing the default styles. 
There shouldn't be any wrapper or element between the section and the slide element and you have  `cont` and `scrolled`.

![image](https://user-images.githubusercontent.com/1706326/116063200-ffa79a00-a684-11eb-9a4a-3b05f76d6155.png)

Additionally, you are modifying the height/width of the slides element:
![image](https://user-images.githubusercontent.com/1706326/116063333-25cd3a00-a685-11eb-9139-fcec8bfdbf7b.png)


fullPage.js expect the slide to be full-height and it's doing the scrollOverflow calculations based on that premise. 
Unfortunately fullPage.js isn't yet ready to deal with your case.
