### ISSUE TITLE
Can I activate standard keyboard up/down functionality for sections that overflow/have a scrollbar?

### ISSUE THREAD

**Issue by AlexPattison1** [alvarotrigo/fullPage.js#4205]
Hi, great work on fullpage.js! I'm just wondering if this is possible please?

I'm creating a site that has two types of sections:
a) Are sections that fit the browser height.
b) Are sections which overflow and a scrollbar appears. 

For sections that are "b" is it possible to allow normal scrolling behaviour on keyboard up/down arrows. Currently if I press keyboard up/down it scrolls to the next section. I would like the normal up/down arrow behaviour for section type "b". The same behaviour if I where to press the keyboard up/down here on github.

Like the behaviour of the mouse wheel. When on section type "a" it scrolls to the next section. But when on section type "b" it scrolls through the content and only scrolls to the next slide when at the end of the current (or vice versa if scrolling up).

The problem I see is that people will use the up/down arrows and miss out content when on section type "b".

Thank you.

**Comment by alvarotrigo** [comment]
Right now fullPage.js doesn't provide such a feature. 
I'll mark it as a possible enhancement.

**Comment by AlexPattison1** [comment]
alvarotrigo, ok. Thank you for your response.

**Comment by alvarotrigo** [comment]
Fixed on v4! 👍

**Comment by AlexPattison1** [comment]
Thank you alvarotrigo!
