### ISSUE TITLE
Official React example. wrong codepen link.

### ISSUE THREAD

**Issue by wonjinYi** [alvarotrigo/fullPage.js#4206]
### Description
Hi. I'm beginner of fullPage.js. First of all, thanks to the contributors of it.

The problem is simple. 
When I click **[See in Codepen]** button In [THIS PAGE](https://alvarotrigo.com/react-fullpage/#page2), The codepen example link goes to [HERE](https://codepen.io/alvarotrigo/pen/zpQmwq)(the wrong URL.)
It is not the Codepen for React.js, but for Vue.js

I can't find example codepen for react.js..... 😢
How can I solve this problem.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by wonjinYi** [comment]
Sorry. It's my fault. Please delete this issue. I closed this issue.

I found out that there is a separate repository for react. 
It seems that the example code and links on the official site have not been updated.
Now I got the information from <react-fullpage> repo.

**Comment by alvarotrigo** [comment]
> When I click **[See in Codepen]** button In [THIS PAGE](https://alvarotrigo.com/react-fullpage/#page2), The codepen example link goes to [HERE](https://codepen.io/alvarotrigo/pen/zpQmwq)(the wrong URL.)

Uh! Good catch!
Fixed now!
