### ISSUE TITLE
Disable reset sliders on mobile

### ISSUE THREAD

**Issue by brandonalexandertong** [alvarotrigo/fullPage.js#4207]
Hello again!

I'm using the reset sliders extension, though I have autoscrolling to false and auto-height-responsive so that the site scrolls normally when in mobile. When scrolling past a section, the slide resets to the first slide while you can still view the section, creating a pretty ugly user experience, so I'd like to disable reset sliders when in responsive mode. Is there any way to do this?

**Comment by alvarotrigo** [comment]
Sure!
Turn it off/on using the `afterResponsive` callback.

For example:

```js
afterResponsive: function(isResponsive){
    fullpage_api.getFullpageData().options.resetSliders=!isResponsive;
}
```

**Comment by brandonalexandertong** [comment]
Amazing, thank you!
