### ISSUE TITLE
fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!

### ISSUE THREAD

**Issue by ak-o3o** [alvarotrigo/fullPage.js#4208]
### Description
hi 
I want to perform two different processes like the code below.
but, I got an error
`fullPage: Fullpage.js can only be initialized once and you are doing it multiple times!`

please, tell me the solution.

### Link to isolated reproduction with no external CSS / JS
```
window.addEventListener("DOMContentLoaded", function () {
  var fullPageInstance1 = new fullpage("#js-fullpage", {
    navigation: true,
    navigationPosition: "left",
    scrollingSpeed: 900,
    scrollOverflow: false,
    afterLoad: headerChange,
    onLeave: skipSection,
    afterRender: activeChange,
  });
  var fullPageInstance2 = new fullpage("#js-fullpage-2", {
    css3: false,
    slidesNavigation: true,
    slidesNavPosition: "bottom",
    scrollingSpeed: 900,
  });
});
```

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
As the error says, you can not initialize fullpage.js more than once in the same page. 
Remove one of your instances or make them conditional so they will only initialize once per page.

**Comment by ak-o3o** [comment]
thanks!

sorry...
I'm a beginner of js...

If you want to separate the two processes, #js-fullpage and #js-fullpage-2(scroll and slide)
how do you write the code.

**Comment by alvarotrigo** [comment]
> If you want to separate the two processes, #js-fullpage and #js-fullpage-2(scroll and slide)

Can you elaborate on that?
What do you want to achieve?
Are those two fullpage for two pages?

**Comment by ak-o3o** [comment]
>Are those two fullpage for two pages?
yes, two pages.
I want to do different processing on page 1 and page 2.

・page 1
```
<main id="js-fullpage">
  <div class="section"></div>
  <div class="section"></div>
  <div class="section"></div>
</main>
```

・page 2
```
<main id="js-fullpage-shop-2">
  <div class="section">
    <section class="slide active"></section>
    <section class="slide"></section>
    <section class="slide"></section>
  </div>
</main>
```

**Comment by alvarotrigo** [comment]
```js
window.addEventListener("DOMContentLoaded", function() {

        if (document.querySelector('#js-fullpage')) {
            var fullPageInstance1 = new fullpage("#js-fullpage", {
                navigation: true,
                navigationPosition: "left",
                scrollingSpeed: 900,
                scrollOverflow: false,
                afterLoad: headerChange,
                onLeave: skipSection,
                afterRender: activeChange,
            });
        }

        if (document.querySelector('#js-fullpage-2')) {
            var fullPageInstance2 = new fullpage("#js-fullpage-2", {
                css3: false,
                slidesNavigation: true,
                slidesNavPosition: "bottom",
                scrollingSpeed: 900,
            });
        });
}
```

**Comment by ak-o3o** [comment]
thanks.
but, same error will be output for this way...
