### ISSUE TITLE
scroll overflow not working

### ISSUE THREAD

**Issue by ennol01** [alvarotrigo/fullPage.js#4209]
### Description
I have a just made a site using the full page.js elementor plugin. I have most parts as slides that are shown fullscreen - however I also have a growing section which is longer than a normal section and needs to scroll normally. however the site will scroll to the next section instead - causing the visitor to miss what's on the lower part of the section. 

I have looked around but cannot get it to work. Help is appreciated. 

### Steps to reproduce it
open site www.enno.net and scroll down. the fifth section dubbed "portfolio" will scroll as a whole. how do I avoid this?

### Versions 
[Browser, operating system, device, ...] happens on all browsers

**Comment by alvarotrigo** [comment]
If you are using the [Official fullPage.js Plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) then please use the [contact form](https://alvarotrigo.com/#contact) in order to get support for it.

This forum is only for the JavaScript library.
