### ISSUE TITLE
Cannot Center Elements

### ISSUE THREAD

**Issue by karchung0930** [alvarotrigo/fullPage.js#4211]
I just cant center horizontally and vertically everything, I've added the following CSS the the .section class

```css
vertical-align: middle;
align-item: center;
text-align: center;
```
And the Javascript is 

```js
jQuery(document).ready( function() {
  
new fullpage('#fullpage', {
	//options here
  	licenseKey: ‘my-license-key',
  	afterLoad: function(anchorLink, index) {
      jQuery('.fullpage-anchor').removeClass('anchor-active');
      jQuery('a[href="#' + index["anchor"] + '"]').addClass('anchor-active');
    }
});

//methods
fullpage_api.setAllowScrolling(true);
  
});
```

**Comment by alvarotrigo** [comment]
Check any of [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples). They are all centered in both axis.

Use the option `verticalCentered: true`.
Then css `text-align: center`
