### ISSUE TITLE
Can I set a parent for a scroll that is not a tag body? Same tag div.wrapper ?

### ISSUE THREAD

**Issue by manwithawp** [alvarotrigo/fullPage.js#4214]
I need it to custom scroll on IOS becouse Safari kill my custom scroll on body and this very important fo design.
https://yadi.sk/i/ZuUM8_QhUdzVUA

**Comment by alvarotrigo** [comment]
I'm not quite sure what exactly is your question.
fullPage.js doesn't use the `body` element for anything in particular.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by manwithawp** [comment]
thank U for fast answer. I haven't solved my question. Becouse the IOS 14 version don`t can style scroll on css.  Please delete this issue. becouse this is not question to fullPage plugin
