### ISSUE TITLE
Wrong scroll position on safari reload

### ISSUE THREAD

**Issue by manuelsampl** [alvarotrigo/fullPage.js#4215]
Hello.

I just found an issue on my live gatsby site: https://www.obscura.at
The bug only occurs in Safari if you reload and try to scroll down fast it scrolls to the wrong position. Or if you try to scroll in the other direction while the transition is still running.
It doesn't happen all the time, which is even more frustrating. I've tried everything but can't find a solution. 

I'm currently trying with safari 14.03 but the issue also occurs in other versions of safari

Please help.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Can you reproduce it on the [demo page](https://alvarotrigo.com/fullPage/)?

**Comment by manuelsampl** [comment]
Sorry, i was struggling the whole day, but i found it 5 minutes after posting the issue. 🥇 
The problem was a fixed height to 100vh in the first section.

**Comment by alvarotrigo** [comment]
Glad you managed to find the issue! :)
