### ISSUE TITLE
Elementor plugin - Create new section, destroy and initialize again

### ISSUE THREAD

**Issue by arseniov** [alvarotrigo/fullPage.js#4216]
Hi,
I am using the Elementor plugin.
I'd need to add a new section with AJAX, so I'd need to destroy, reBuild and initialize again.

I have this JS: https://codepen.io/ArsenioV/pen/RwppbRJ

but that doesn't seem to work:

1. no new section is created - append returns this code in console: `n.fn.init {context: document, selector: "#fullpage"}`
2. fullpage gets destroyed correctly but I can't manage to initialize it again. Any function I have tried doesn't work - with `new fullpage` it returns this error: `fullpage.js:3650 fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a 'licenseKey' option. Read about it here:` even though it's correctly registered and I also checked with your Inspector.

Any clue?

Thank you
Giacomo

**Comment by alvarotrigo** [comment]
For the official [fullPage.js plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) use the [contact form](https://alvarotrigo.com/#contact) please.
