### ISSUE TITLE
animation before leaving the section (onleave) 

### ISSUE THREAD

**Issue by amo4oma** [alvarotrigo/fullPage.js#4217]
I am trying to make animation to the page that user will leave, so when user scroll the animation starts then the page changes 
1- scroll => animation starts => animation ends => next page appears 
 i have tried to delay the page onleave so that the animation work before changing the page, the problem is that user have to scroll only once and wait for the animation to start and the page to change, and when i keep scrolling (using the mouse wheel or touch pad) the animation loops and never changed, you can see the code pen that i created, do not stop scrolling to understand what is the problem.

what is happening is when you scroll now the animation keep looping until the stop scrolling which is a bad user experience

use the link to view my code 
https://codepen.io/amo4oma/pen/PopmYEx

```

var delay = 500; //milliseconds
var timeoutId;
var animationIsFinished = false;

 
	
	/* Slide variable */
		var slideIndexBis = 1;
		var sliding = false;
	
	new fullpage('#fullpage',{
        
        fadingEffect:true, 
        scrollOverflow:true,
        fadingEffect:'slides',

        onLeave: function(origin, destination, direction){
            const section = origin.index;
            console.log(direction)
            console.log(section)
            tl = new TimelineMax({delay:0.7});
            
            if (section === 1){
                var curTime = new Date().getTime();
               
                //animating my element
              
                    tl.fromTo($('.title-2'),0.5,{scale: 1},{scale: 100, opacity:0, ease: Power1.easeIn})
                    tl.fromTo($('.f-1'),0.5,{x: 0},{x: "600px", ease: Power1.easeIn})
                    tl.fromTo($('.f-2'),0.2,{x: 0},{x: 100, opacity:0, ease: Power1.easeIn})
        
                clearTimeout(timeoutId);
        
                timeoutId = setTimeout(function(){
             
                    animationIsFinished = true;
        
                    fullpage_api.moveTo(destination.index + 1);
                }, delay);
        
                return animationIsFinished;
                
            } 
```

**Comment by alvarotrigo** [comment]
This is more of a JS question rather than a fullPage.js one. 
The issue is not on fullPage.js but on your code.

Try using some flag to know when the animation is still taking place and don't execute it in that case.

If you need further assistance consider getting the Business License from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>
