### ISSUE TITLE
onLeave event fires too quickly after being rejected

### ISSUE THREAD

**Issue by brnteka** [alvarotrigo/fullPage.js#4220]
https://codepen.io/mpbrainwave/pen/YzZjKZx

Hello, I'm trying to make fullpage skip a transition to the next section on a first scroll event and instead add a class to the current section and on a second scroll event finally complete the transition. With the code in the example, everything seems to work as expected but the scroll event fires so quickly right after being rejected that the "second view" of the section I'm trying to hold on to is being scrolled over very easily. Keyboard events don't have this issue.

**Comment by brnteka** [comment]
Not sure how `fullpage_api.setAllowScrolling(false)` can help me here because if i set it anywhere in the onLeave callback it won't ever fire again, mind to show a quick example? we have a license btw :D

**Comment by alvarotrigo** [comment]
You'll very probably have to use a `setTimeout`.
Similar to what I suggested here:
https://stackoverflow.com/a/36182162/1081396

**Comment by brnteka** [comment]
ok got you, thanks

**Comment by alvarotrigo** [comment]
Should be fixed soon in v4.

**Comment by alvarotrigo** [comment]
This is solved now on v4. You can use `beforeLeave` to cancel the movement.
