### ISSUE TITLE
Fullpage.js Section skipping with Oxygen Builder

### ISSUE THREAD

**Issue by RECer** [alvarotrigo/fullPage.js#4221]
### Description
Hi, there @alvarotrigo am a fullpage.js customer and am facing an issue with the implementation of your library into my solution. I have followed many guides and in its most basic form the Elija Mills Oxygen tutorial for the implementation of Fullpage.js. (https://oxygenbuilder.com/tutorial/how-to-use-fullpage-js-with-oxygen/)

The issue I am having is that the sections on my page repeatedly (on the first and last section ) seems to skip 2 sections. This confuses the page sections in the URL and causes the navigation to become chaotic. I have tried this on a couple of pages and installs now to ensure it isn't my error or a clash. I have reached out to the Oxygen builder community. Other members have informed me that they have encountered a bug when using fullpage js.

### Link to isolated reproduction with no external CSS / JS
The core code is exactly as showing in Elijas video above. So I am not sure if you still want me to recreate a codepen

This is my site
https://inseco0staging.wpengine.com/

### Steps to reproduce it
1. Start at first or last 'section' of the Page with fullpage.js (Home page from the link above) - Open in desktop view
2. Scroll using either mouse or keyboard
3. Take note of double scrolls and URL anchor errors.

### Versions 
[Browser, operating system, device, ...]
Chrome 90,  MacOS, Macbook pro 2019 13"

**Comment by alvarotrigo** [comment]
> So I am not sure if you still want me to recreate a codepen

Yeah, please. That'd be great.

**Comment by alvarotrigo** [comment]
Remember to use the minimum HTML possible (empty sections with single heading) and no external CSS or JS to fullpage.js.

**Comment by chihabhajji** [comment]
No need to reproduce, you can inspect this in action with one of FP's sponsored pages [http://promo.prestigio.com/grace1/](Prestigio's website) , its happening to me too and i cant seem to fix it

**Comment by chihabhajji** [comment]
Update : i dont know if oxygen lets you manipulate Fullpage's initialization, but if it does as a work around you can set the "scrollingSpeed" to something higher than 1800 and that should fix it.
