### ISSUE TITLE
Automatic scroll when mobile keyboard is opened

### ISSUE THREAD

**Issue by EriCreator** [alvarotrigo/fullPage.js#4222]
### Description
I wan't to be able to fill in a form within a fullpagejs section.
Always when a text field is focussed or a text input is updated, fullpagejs scrolls out  and brings the form input field behind the keyboard.
Is there a way to disable this automatic scrolling when mobile keyboards are open?
I figured that even setting autoScrolling: false, doesn't resolve this issue. 

### Link to isolated reproduction with no external CSS / JS
The problem occurs on this page, in the last section.
https://kombucha-moya.webflow.io/
It can only be reproduced with a real phone that has a keyboard.

### Steps to reproduce it
1. On a mobile phone, open https://kombucha-moya.webflow.io/
2. Slide down to the last section (Get in Touch)
3. select any field (Name, E-Mail or Message)
and you will notice the annoying automatic scrolling after a 1-2 seconds..

### Versions 
iOS mobile phone, fullpagejs version 3.0.9

**Comment by alvarotrigo** [comment]
> I figured that even setting autoScrolling: false, doesn't resolve this issue.

Can you please provide the reproduction with `autoScrolling:false`?

**Comment by EriCreator** [comment]
@alvarotrigo sure, it's on the same domain:
https://kombucha-moya.webflow.io/

Same issue, when you scroll to the bottom of the page with the phone and try to type into a form field, weird things happen with the scrolling.

**Comment by alvarotrigo** [comment]
Use the option `fitToSection: false` when using `autoScrolling:false` and that should fix the issue :)

**Comment by alvarotrigo** [comment]
You can go further with it and try to disable fullpage.js only when an input is on focus.
Then call `fullpage_api.setAutoScrolling(false)` and `fullpage_api.setFitToSection(false)`

**Comment by EriCreator** [comment]
Impressing, you really know your stuff! 
thanks alot, that resolved my issue.

**Comment by alvarotrigo** [comment]
Glad it did! 👍

**Comment by AcapSLP** [comment]
> Impressing, you really know your stuff! thanks alot, that resolved my issue.

nice one, i ripped off your script and added it to my site.
