### ISSUE TITLE
Can not scroll/view the whole page when using scrolloverflow

### ISSUE THREAD

**Issue by christophergulliksen** [alvarotrigo/fullPage.js#4223]
Thank you for the great work with fullpage.js!
I just bought the scrolloverflow extension and have some problems with it:

I have a webflow site where I have
- 1 section
- 1 section with 4 slides
- 1 section is about 11500px and I want to scroll like ‘normal’
- Then the site finish with 3 sections x 100vh
- 

It seems like it have problems reading the height of the ‘normal scroll’ section when using height ‘auto’ or ‘100%’. 
When I publish the site it doesn’t load/scroll the whole site. It stops before I reach the last 3 x 100vh sections. 

https://livid-femme-jeans.webflow.io/fullpage

https://preview.webflow.com/preview/livid-femme-jeans?utm_medium=preview_link&utm_source=designer&utm_content=livid-femme-jeans&preview=f47f84d3194df8e532ecf893d12326b7&pageId=60c288d7b71dd8494cd8ddc3&workflow=preview

I tried to manually set the height for the section with pixels and then it works (but that is maybe not the best solution when it comes to responsiveness?

https://livid-femme-jeans.webflow.io/one-section

Thank you for the great work. Hope to get some help:)

Christopher

**Comment by alvarotrigo** [comment]
Did you check out the clonable examples here?
- [Basic fullpage.js example in webflow](https://webflow.com/website/Fullpagejs-basic-example)
- [fullpage.js Horizontal Slides example in webflow](https://webflow.com/website/fullPagejs-Horizontal-Slides)

Also read:
- ["How to use fullpage.js in webflow to create a fullscreen slider"](https://alvarotrigo.com/blog/how-to-use-fullpage-in-webflow-create-full-screen-slider/)
- [How to use fullPage.js extensions in webflow](https://alvarotrigo.com/fullPage/help/Use-fullPage-js-extensions-on-Webflow-editor/)

**Comment by christophergulliksen** [comment]
Thanks for the quick reply !

yes, I have seen those. 
seems like everything is working as it should (except the middle section where scrolloverflow is activated)
It works when I set the height for that section manually om 10500px, but not when using auto height. 

Maybe I am doing something wrong there?
Problem with manually px height on that section is responsiveness.

**Comment by alvarotrigo** [comment]
I don't understand what is the issue. 
Can you be more specific?

I see a section with scrollOVerflow that has huge sections with 10800px each. So that makes the scrollable section HUGE.

![image](https://user-images.githubusercontent.com/1706326/121679927-357bd300-cab9-11eb-90e4-baf29b139ffe.png)

**Comment by christophergulliksen** [comment]
I recorded a loom wich shows the issue
https://www.loom.com/share/838cc04f2534409a8da70d11eeb319c7

Page URL
https://livid-femme-jeans.webflow.io/one-section-copy

https://preview.webflow.com/preview/livid-femme-jeans?utm_medium=preview_link&utm_source=designer&utm_content=livid-femme-jeans&preview=f47f84d3194df8e532ecf893d12326b7&pageId=60c36eb47c56a61151c3cbf1&workflow=preview

**Comment by alvarotrigo** [comment]
You'll have to set the height attribute in all your images. Otherwise fullpage.js can't predict what size they'll have until they are fully loaded. 

That, or manually call `fullpage_api.reBuild()` once your images are all loaded.

Or, as an alternative, set the image height for the first few images. Then for the rest, use `data-src` to lazy load them. fullPage.js will detect when they are loaded and call reBuild internally.

**Comment by alvarotrigo** [comment]
Or even create the listener yourself, but that'd be a bit more complicated if you are not very familiar with JS.

```js
var NUM_IMAGES = 40; //(or just query it if you prefer)
var numImagesLoaded = 0;

images.forEach(function(image){
   image.addEventListener('load', function(){
      numImagesLoaded++
      
      //rebuild only when they are all loaded
      if(numImagesLoaded === NUM_IMAGES){
         fullpage_api.reBuild();
      }
   });
});
```

**Comment by christophergulliksen** [comment]
Thanks! 
I don't have the knowledge to do that unfortunately.
I tried to give all the images size, but did not work. 
I still not tried the lazy loading solution, but I will go for the px variant now.

New problem.
I have responsivewidth 900, and when I look at the site on iPad or phone under 900 it is a mess.
https://www.loom.com/share/0a336d87de5f427491b310dfc662f81d

The only thing I did was to change some of the spacing.
Any tips on how to solve this for iPad and iPhone - or is it possible to de-activate fp on smaller devices?

Thanks

**Comment by alvarotrigo** [comment]
> The only thing I did was to change some of the spacing.

Try the data-src option. That might be the best to solve all your problems.

**Comment by alvarotrigo** [comment]
See more about lazy load on the docs:
https://github.com/alvarotrigo/fullPage.js#lazy-loading

**Comment by christophergulliksen** [comment]
Thanks.
So the lazy loading will help with the problem of stacking all the sections when using smaller then 900px screens?

I will try!
BUT.. Maybe you know how I change the src to data-src in webflow? :)

**Comment by alvarotrigo** [comment]
> Maybe you know how I change the src to data-src in webflow?

Not really, not a webflow user :)

**Comment by alvarotrigo** [comment]
> So the lazy loading will help with the problem of stacking all the sections when using smaller then 900px screens?

I should solve all your issues as the size of scrolloverflow wrapper would get calculated after their load.
