### ISSUE TITLE
JS Conflict with FullPage plugin and Glider

### ISSUE THREAD

**Issue by itay1313** [alvarotrigo/fullPage.js#4224]
### Hey I tried to use OoohBoi Steroids for Elementor plugin to create an horizontal slider from custom elements. and I used Glider to create a slider,
it worked great in the elementor editor
but the website doesn’t show it well, it looks broken, can u check?

it’s js conflict with FullPage for Elementor when I cancel it, it works, but I need both plugins,
any tips?

### 
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. Just scroll to the companies section

**Comment by alvarotrigo** [comment]
If you are using [the official fullPage.js plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) then please use the [contact form](https://alvarotrigo.com/#contact) to get support for it.

**Comment by itay1313** [comment]
I am,
done
