### ISSUE TITLE
Scroll issue on IOS when url changes

### ISSUE THREAD

**Issue by bereid** [alvarotrigo/fullPage.js#4226]
Thanks for this amazing package! We have a small, but very confusing issue, and it's totally possible the issue is on our side. We appreciate your help!

### Description
When I'm clicking on a link that navigates to another route, the page scrolls to the right section, but not to the top. It scrolls almost to the bottom of the section instead. It seems like the `verticalCentered issue`, but we set that to false. It appears only on IOS, on Android, it working perfectly fine. When not changing the route, just navigates between hashes, it also works perfectly. 

### Link 
https://stagingincepteamcom.z1.web.core.windows.net/

### Steps to reproduce it
1. Open the page on iPhone IOS Chrome or Safari
2. In the menu, navigate to the Careers page (scrolling works properly)
3. On the careers page click on Open positions to navigate to another route
4. In the menu click any of the links, it navigates to a section on the main page. The screen will stop at almost on the bottom of the section

### Versions 
iPhone, IOS, Safari or Chrome

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for reproduction.

**Comment by bereid** [comment]
Thanks for your quick reply!

I'm not sure that I can reproduce it without the external code (our app uses Next.js and React for routing). How could you do that? Is it impossible to catch this problem without the external code?

**Comment by bereid** [comment]
Okay, thanks for the answers!
