### ISSUE TITLE
Wrong indexing and various navigation issues

### ISSUE THREAD

**Issue by arseniov** [alvarotrigo/fullPage.js#4227]
Hi Alvaro,
I have an issue which I think is the cause for other issues on the same page.

When I reach the last section and I scroll down, the viewport scrolls up on its own to the first section and behaves strangely:
if I scroll down, it goes to the 2nd section and if I scroll down again it goes back to the 1st;
if I scroll up, it doesn't go anywhere;

so I'm stuck at the first section.

I tried to look at this but couldn't find anything that's not working properly.
continuousVertical is disabled.

Unfortunately I couldn't find a way to reproduce this.
This is my basic code: https://jsfiddle.net/viganogiacomo/8wd47ch2/29/

I also have various issues which I think are linked to this one:

1. Index numbers are not correct: 1st section is 0, but 2nd section has 2 instead of 1 so numbering is off
2. Linked to the above: I see a sort of white line between 1st and 2nd section
3. If I try to destroy, reBuild and initialise after having added new sections, even setting the active section doesn't work, as it remains at the top of the page, it doesn't go to the active section. moveTo works, but I would like to avoid the scrolling effect from there.

Things I already checked:

1. structure of the page is correct
2. no blank or empty sections

Sorry for not being able to reproduce it, would you like to make a visit to the public page?

Thanks in advance.
Giacomo

**Comment by alvarotrigo** [comment]
Unfortunately, we will need an isolated reproduction to keep looking into the issue. Without it, we can only assume the issue is outside fullPage.js code.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
