### ISSUE TITLE
Inside sections (slides) are fullpage in mobile version

### ISSUE THREAD

**Issue by hquina** [alvarotrigo/fullPage.js#4230]
I'm having several issues when building my fullpage website in mobile version. The inner sections that work as horizontal slides are displayed as full screen and I can't find a way to change that. This section is already with auto height responsive option turned on. Also, the scrolling is a bit bugged, has it jumps around when scrolling down.

https://staging2.marionete.io/fullpage-frontpage/#whatwedo

Wordpress. Elementor plugin and extensions
![Screenshot 2021-06-23 at 09 55 24](https://user-images.githubusercontent.com/86349059/123068577-ec594680-d409-11eb-89a4-d0f5920a412c.png)
![Screenshot 2021-06-23 at 09 55 16](https://user-images.githubusercontent.com/86349059/123068587-ed8a7380-d409-11eb-84b3-dfa4d3e5c297.png)

**Comment by alvarotrigo** [comment]
If you purchased the [official plugin for Elementor ](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/#contact) to get support for it.

This project in Github only treats issues related to the JavaScript library.
