### ISSUE TITLE
ScrollOverFlowReset not showing start of long section when coming from section below

### ISSUE THREAD

**Issue by kirkbross** [alvarotrigo/fullPage.js#4233]
### Description
`scrollOverflowReset: true` does not show the start of the content on section load when coming from section below.

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/kirkbross/pen/PopMjWX

### Steps to reproduce it
1. Go to above link
2. Click on Section 4 in top nav
3. Click on Section 3 in top nav

It should show the start of section 3, no?

### Versions 
Windows 10, Chrome

**Comment by alvarotrigo** [comment]
If you use `fp-auto-height-responsive` then scrollOverflow won't make any difference.
ScrollOverflow is only used when a full-height section requires scrollable content within itself, like in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html#secondPage).

Removing `fp-auto-height-responsive` should do it.

**Comment by kirkbross** [comment]
> Removing `fp-auto-height-responsive` should do it.

I removed that class from section 3 and it still doesn't work.

https://codepen.io/kirkbross/pen/PopMjWX

**Comment by alvarotrigo** [comment]
The extension file is not being loaded, this doesn't exit:
https://www.coding.ms/fileadmin/test-fullpage-scroll-overflow-rest/fullpage.scrollOverflowReset.min.js

**Comment by kirkbross** [comment]
> The extension file is not being loaded, this doesn't exit:
> https://www.coding.ms/fileadmin/test-fullpage-scroll-overflow-rest/fullpage.scrollOverflowReset.min.js

How do I load this extension in a Pen environment? 
https://storage.googleapis.com/kross_uploads/pen.jpg
