### ISSUE TITLE
Instant response when pressing arrow keys to move to another section/slide

### ISSUE THREAD

**Issue by quickfiredigital** [alvarotrigo/fullPage.js#4234]
On line 2283 of fullpage.js, there is a setTimeout of 150 and was wondering if I were to change this to 0, so there is no delay, would it have any other adverse effects on anything else?

If not... is it possible to add a variable to control this delay.

**Comment by alvarotrigo** [comment]
> On line 2283 of fullpage.js, there is a setTimeout of 150 and was wondering if I were to change this to 0, so there is no delay, would it have any other adverse effects on anything else?

The question is, why would you be interested in removing it?

**Comment by quickfiredigital** [comment]
The reason why I would like to reduce this is because I would like a snappier response time when using the arrow keys to scroll down. As it stands, although relatively minor, there is a noticeable delay and would like it to be instant. However I do not want to remove this if it causes any other issues.

**Comment by alvarotrigo** [comment]
> The reason why I would like to reduce this is because I would like a snappier response time when using the arrow keys to scroll down. As it stands, although relatively minor, there is a noticeable delay and would like it to be instant. However I do not want to remove this if it causes any other issues.

It won't be instant even when you remove the delay.
You won't be allowed to scroll down unless the section has completely finished moving.

**Comment by alvarotrigo** [comment]
I'll mark it as a possible enhancement.
We can perhaps create an option to define if we want an instant response with keyboard or not.

**Comment by alvarotrigo** [comment]
Fixed on v4! 👍
