### ISSUE TITLE
Drag and move

### ISSUE THREAD

**Issue by quickfiredigital** [alvarotrigo/fullPage.js#4235]
I have purchased the fullpage.js drag and move extension and I am getting red banner at the top of my page saying that I have an unlicensed fullpage.js extension even though I have added the license key to my JS and have included the fullpage.extensions.min.js file as well. This is the javascript in which I am using and it does work. I just get the error red banner.

var fullpage_api = new fullpage('#fullpage', {
    licenseKey: '3B0F2C64-939C4E55-A0A99B06-B00D85AB',
    dragAndMoveKey: '4A2ACE89-1EFE4890-833DC892-98833779',
    navigation: false,
    scrollingSpeed: 350,
    normalScrollElements: '.offcanvas',
    dragAndMove: true
});

**Comment by alvarotrigo** [comment]
You are missing the activation part. 
See [why you get the red message on fullPage.js extensions](https://alvarotrigo.com/fullPage/help/How-to-fix-Unlicensed-extension-red-error-message/).
