### ISSUE TITLE
Help making it work with SwupJS on wordpress? 

### ISSUE THREAD

**Issue by Caffeinedesign** [alvarotrigo/fullPage.js#4236]
Hi, i have a license for fullpage.js, and i made a custom plugin in wordpress, it works like a charm with oxygen builder, now i'm trying to make it work with Swup.js, i installed swup head and body plugin to make it work with wordpress/oxygen builder, and it works, the only problem i have, when i go back to the home (where i use fullpage js), home doesn't move nor with fullpage scroll, nor with "vanilla scroll".

in console i have these errors:
fullpage.min.js?ver=1.0.2:11 Uncaught TypeError: Cannot read property 'nextElementSibling' of undefined
fullpage.min.js?ver=1.0.2:11 Uncaught TypeError: Cannot read property 'previousElementSibling' of undefined

Swup is a plugin wich makes loading through pages realtime with a transition, so there should be a reloading problem

can someone help me with this?
thanks a lot

**Comment by alvarotrigo** [comment]
If you want to use fullpage.js in WordPress we provide official plugins for the [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and the [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) builders and soon for [Divi](https://alvarotrigo.com/fullPage/wordpress-plugin-divi/) too!

Apart from those we do not provide support for other kind of integrations. 
But please feel free to ask any code related issues if you think those can be isolated from WordPress stuff that is out of our control.
