### ISSUE TITLE
Section with custom heights. i.e: a section with 2X height in mobile.

### ISSUE THREAD

**Issue by vettorazi** [alvarotrigo/fullPage.js#4237]
### Description
I have a page that is working perfectly on desktop view. But, on mobile, The content needs to stack vertically.
The problem I'm facing is that all divs stacked vertically, won't fit in one screen. I need to find a way to increase the height of the section by 2, at least. How can I do that?

### Versions 
Chrome
ios
fullpage.js v3

**Comment by alvarotrigo** [comment]
You can use the `fp-responsive-auto-height` class. 
Read more about it on the docs where you'll find a demo too:
https://github.com/alvarotrigo/fullPage.js#responsive-auto-height-sections
