### ISSUE TITLE
Flicker when scrolling in transition between section to section

### ISSUE THREAD

**Issue by jamesmjchan** [alvarotrigo/fullPage.js#4238]
### Description
Hi this is what I am trying to do. 
I try to turn off autoScrolling after view 6 section when scrolling down and turn on autoScrolling after view 7 when scrolling up however, the transition flicker a lot and it just not smooth. Is there any other way to do it to make it smooth?

### Link to isolated reproduction with no external CSS / JS

https://jsfiddle.net/7bxLsenp/

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
Chrome

**Comment by alvarotrigo** [comment]
Unfortunately fullpage.js doesn't provide an out-of-the-box way to achieve what you need.
The issue has been treated multiple times and we still working on it.

I'll close this issue as a duplicated of https://github.com/alvarotrigo/fullPage.js/issues/614 and https://github.com/alvarotrigo/fullPage.js/issues/3205 so we can keep the conversation in a single place.
