### ISSUE TITLE
[Question] Fixed div with text above it

### ISSUE THREAD

**Issue by KreNtal** [alvarotrigo/fullPage.js#4239]
Is it possible to have a fixed element between sections but still have some text element from the sections going above it?

I am trying to achieve this:
![2021-07-10 16 44 20 chrome](https://user-images.githubusercontent.com/6420752/125166917-2a8e8e00-e19e-11eb-8324-ce20138433cb.png)

The white triangle should be fixed but the text should change when scrolling sections...

**Comment by alvarotrigo** [comment]
I haven't tried but play with the `z-index` property as well as with absolute positioned elements relative to sections/slides.

As this is a CSS issue and not a fullpage.js I encourage you to ask directly in stackoverflow.com with the `css` tag. You'll get better answers there.
