### ISSUE TITLE
On scroll up content of section is moved upward.

### ISSUE THREAD

**Issue by aryaraj132** [alvarotrigo/fullPage.js#4241]
### This issue is an extension of #3186,
It comes up when scrolled upward (especially in mobile devices.) upon debugging in mobile web browser I found then scrolled down sections are translated upwards from body bottom outline but when scrolled upwards sections are translated downwards from device's top section, hiding topmost part of section and everything is shifted outwards.

#### When Initially loaded its at default position.

![Initial Loading](https://github.com/aryaraj132/aryaraj132.github.io/blob/master/fullpageIssue/1.jpg?raw=true)

#### After scrolling down bottom of the previous section is behind the hidden section above the body

![After Scrolling Down](https://github.com/aryaraj132/aryaraj132.github.io/blob/master/fullpageIssue/2.jpg?raw=true)

#### After scrolling up top of the previous section starts from the hidden section above the body

![After Scrolling Up](https://github.com/aryaraj132/aryaraj132.github.io/blob/master/fullpageIssue/3.jpg?raw=true)

### Link to isolated reproduction with no external CSS / JS
Link to [CodePen](https://codepen.io/aryaraj132/full/bGWWxWO) although the code is same this effect is not seen in codepen as it uses iframe to render code.
So here is a link to isolated page with fullpage.js which demonstrate the problem. [Site Link](https://aryaraj132.github.io/test.html)

**Comment by alvarotrigo** [comment]
On what device and browser does that happen?
I can't reproduce it on iOS on Safari, Firefox or Chrome.

**Comment by alvarotrigo** [comment]
Also, you are forgetting to include the fullpage.min.css file.

**Comment by aryaraj132** [comment]
So, adding fullpage.min.css file did solved the issue for desktop but the issue persisted for mobile devices. I am currently using Chrome (Android to test it). Upon inspecting the problem continue acc/to screenshots I added.

**Comment by alvarotrigo** [comment]
I can't reproduce it.
I'm testing it on Chrome using Android on a Samsung using browserstack.com on a real device.

Video attached:
https://user-images.githubusercontent.com/1706326/126485724-6f02c550-7772-46d1-b52a-5be816ad840a.mp4

**Comment by aryaraj132** [comment]
In case you are not able to reproduce it on ios devices, that might be happening because how they deal with URL bar space . I would recommend trying it on android devices. 

Just in case I have attached the test page in this zip file, same is hosted at [github](https://aryaraj132.github.io/test.html) as well so you can just have a look and inspect with any android mobile.
 
[testFile.zip](https://github.com/alvarotrigo/fullPage.js/files/6855463/testFile.zip)

**Comment by alvarotrigo** [comment]
> would recommend trying it on android devices.

See my post above .

**Comment by aryaraj132** [comment]
> I can't reproduce it.
> I'm testing it on Chrome using Android on a Samsung Galaxy S21 using browserstack.com on a real device.
> 
> Video attached:
> https://user-images.githubusercontent.com/1706326/126485724-6f02c550-7772-46d1-b52a-5be816ad840a.mp4

So in this video you can see initially the title "Home", "About" , etc are few pixel below the nav bar icon and is there when you scroll down. but when you scroll up you can see titles are shifted up and hidden below nav icon

**Comment by aryaraj132** [comment]
Also adding overflow-x:hidden; to parent div mess up everything.


![image](https://user-images.githubusercontent.com/61931454/126486523-1ffd2f4d-4da4-4a89-b265-ed036dc14df6.png)

**Comment by alvarotrigo** [comment]
Yeah I see what you mean.

Can you try with the files on the dev branch?
https://github.com/alvarotrigo/fullPage.js/tree/dev/src

**Comment by aryaraj132** [comment]
Tried with dev files and everything stopped working now.

**Comment by alvarotrigo** [comment]
You are not loading the files correctly. 
Use this urls instead:
https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.css
https://rawgit.com/alvarotrigo/fullPage.js/dev/src/fullpage.js

**Comment by aryaraj132** [comment]
Updated with raw dev files. Problem persisted.

**Comment by alvarotrigo** [comment]
Remove all CSS that doesnt belong to fullpage.js like this one

![image](https://user-images.githubusercontent.com/1706326/126489985-b6e2097b-6919-42d3-9088-ef04cb321898.png)

**Comment by alvarotrigo** [comment]
In fact, you can try again with the old JS and CSS files instead of the dev ones. 
The problem might be in your own css.

**Comment by aryaraj132** [comment]
Ok, so the main issue was section height of 100vh. but shouldn't 100vh cover the display area of the device only same as height dynamically generated by script? Any Idea why it was hiding behind URL bar space?

**Comment by alvarotrigo** [comment]
> shouldn't 100vh cover the display area of the device only same as height dynamically generated by script?

No. Or yes. But if you think it should, you'd better tell all browsers to fix that :) 
There's a reason why fullpage doesn't use those :)

**Comment by aryaraj132** [comment]
Well according to [google](https://developers.google.com/web/updates/2016/12/url-bar-resizing) vh actually doesn't change relative to URL bar but rather assume URL bar to always hidden. Since fullpage doesn't allow URL bar to hide, that might be the issue. The contradiction when painting website browser think URL bar is hidden and fullpage doesn't allow that.

**Comment by aryaraj132** [comment]
Well if it works it's always better to avoid few things. (＾▿＾)

If you can fix that URL bar thing that could avoid so much confusion as well, as people generally test their layout then insert libraries, but I guess doing that will cause resizing issue. "__"

Hope you find a way around.

**Comment by alvarotrigo** [comment]
The URL bar thing is not something we have control over.
