### ISSUE TITLE
Doesn't Initialize with Caching

### ISSUE THREAD

**Issue by dan-caspio21** [alvarotrigo/fullPage.js#4242]
Fullpage element does not initialize onload when cached by nitropack. It will initialize only after a mouse activity e.g by just moving the mouse on screen. After that, the fullpagejs works perfectly fine. I've prepared a short video to demo the current issue. We cannot provide a jsfiddle or codepen as it needs to be cached by the nitropack.
https://drive.google.com/file/d/1YzMEw_MY0T5ipk0tcDL42KuyP3BOZaI_/view

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by dan-caspio21** [comment]
Hi,

Here's our dev page: http://dbgurusweb01.apps123.com/homepage-fullpage-2/

To replicate:
1. Just refresh the page and don't touch mouse or keyboard
2. Wait like more than 10secs before moving the mouse, after then, the fullpagejs will initialize

I hope this helps you to identify the issue.

Thanks!

**Comment by alvarotrigo** [comment]
Thansks, but can you provide an isolated reproduction instead?
We don't check specific websites unless you got the Business license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>. Let us know if that's the case so we can verify it.

For the Hobby and Professional license, we require isolated reproductions, meaning, you should remove all unnecessary elements on the page that are not directly related to the issue.
Any JS or CSS files and any extra HTML should be removed to facilitate fading the possible bug/cause.

Let me know when you have an isolated reproduction ready for it.

**Comment by dan-caspio21** [comment]
Hi,

Again, we cannot provide a codepen or jsfiddle as isolated reproduction because it has to be integrated with nitropack which is the caching platform. That's why we provided you our dev environment page. Would you like us to make the dev page we provided a very simple fullpagejs implementation, because that is the only way in this case. We understood the cyberlaw and really planning to buy once this is solved first. 

May we know if you'll provide a refund once this is left **unresolved in specific time**? If so, we might consider what you suggest to buy first.

Thanks!

**Comment by alvarotrigo** [comment]
> Again, we cannot provide a codepen or jsfiddle as isolated reproduction because it has to be integrated with nitropack

No need to use codepen or jsfiddle.
You can create an isolated reproduction in your server too. Just remove all unnecessary code. Any external CSS and JS to fullPage.js and use sections with a single heading on them.

> May we know if you'll provide a refund once this is left **unresolved in specific time**?

Unfortunately not. Those licenses are non-refundable. 
We can't assure you the issue can get solved, but we will try our best to investigate it.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
