### ISSUE TITLE
ResponsiveSlides doesn't work (Cannot read property 'toSections' of undefined)

### ISSUE THREAD

**Issue by INSANITY99** [alvarotrigo/fullPage.js#4244]
**Description :**

Hello @alvarotrigo,

I recently purchased the FullPage Js license and an extension license for ResponsiveSlides.
I tried to implement the extension, but without success.
It's been two days that I'm looking for a solution on the internet, that I'm reading the documentation of FullPage Js, but I can't find it. 

I tried different ways like this one: 
[Issue](https://github.com/alvarotrigo/fullPage.js/issues/3147)
and others...

Can you help me to understand my mistakes ?

Thank you very much and sorry for my English

[CodePen](https://codepen.io/INSANITY99/pen/OJmoEjq)

**Steps to reproduce it :**

1. Drag the window to 900px.
2. And then the error (Cannot read property 'toSections' of undefined).

![console error](https://user-images.githubusercontent.com/42124407/128281020-c3bda889-7390-4520-ac9f-328c50ddca46.PNG)
![fullpage Init](https://user-images.githubusercontent.com/42124407/128281025-8ded59a5-8776-404e-b3fb-c58d23d9c531.PNG)
![script Order](https://user-images.githubusercontent.com/42124407/128281027-5b1c03ac-7f54-4eb7-be39-625e2fafbe3d.PNG)

**Versions :**

Brave, Version 1.27.109 Chromium: 92.0.4515.115 (Build officiel) (64 bits), Windows 10

**Comment by alvarotrigo** [comment]
For questions regarding extensions, please use the [contact form](https://alvarotrigo.com/#contact).
This forum is just for the JavaScript component, not it's extensions.
