### ISSUE TITLE
Section loses its full-screen size after a resize

### ISSUE THREAD

**Issue by aanders50** [alvarotrigo/fullPage.js#4246]
### Description
Hello! I am demoing the fullPage.js library right now _(with plans to purchase it for future client projects)_, but I am running into a minor issue where when I resize the screen, certain sections lose their full-height. I presume I am simply implementing something correctly but it looks like the fp-scroller class isn't growing to the full viewport height. Just wondering if you can see if I am doing something wrong?

### Link to isolated reproduction with no external CSS / JS
Quick screen recording: [https://aawebapps.com/cartest/fullpagejsgif.gif](https://aawebapps.com/cartest/fullpagejsgif.gif)
Link to issue, section 3 (site is very barebones as I am just testing some ideas out):  [https://aawebapps.com/cartest/#section3](https://aawebapps.com/cartest/#section3)

### Steps to reproduce it
1. Scroll to section 2
2. Shrink screen size a bit
3. Scroll down to section 3 to see large amounts of whitespace under it.

### Versions 
Windows 10 using Chrome

**Comment by alvarotrigo** [comment]
Can you reproduce the issue in any of the [demo pages](https://alvarotrigo.com/fullPage/#examples)?
If so, let me know which.

If not, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
