### ISSUE TITLE
scrollOverflow breaking GSAP animation - new developer

### ISSUE THREAD

**Issue by jand1** [alvarotrigo/fullPage.js#4248]
Hi guys,

I'm a new developer so I'm really struggling to see what I'm doing wrong and testing everything to see if it's my code that is messing up the animation. Maybe it is my fault, but I'm not experienced enough to troubleshoot and don't know how to find a solution at my current level.

Basically, when **scrollOverflow** is set to '**true**', the GSAP animation on my page doesn't work. I've really tried to make it bare HTML, CSS, JS to see if other codes are breaking it, but enough talk and see the demo on CodePen:

[https://codepen.io/jand1/pen/MWmNvLg](https://codepen.io/jand1/pen/MWmNvLg)

the animation only works in these conditions:
1 - if scrollOverflow is set to 'false', or removed entirely,
2 - if the '**function**' that is wrapping the GSAP animation is removed.

The thing is I need the '**function**' to make the animation load only when the page has loaded. This is because I am getting FOUC before the animation happens and so I have followed the GSAP guide on how to minimise/remove FOUC:
[https://greensock.com/forums/topic/11216-fouc-flash-of-items-visible-before-they-animate-on/](https://greensock.com/forums/topic/11216-fouc-flash-of-items-visible-before-they-animate-on/)

Any idea would be great.  Solution, even better!

Thank you!

**Comment by alvarotrigo** [comment]
Try running the init function on the `afterRender` function. 
You'll have to move some variables from your `afterLoad` function or convert them to globals in order to do so.

**Comment by jand1** [comment]
Hi Alvaro,

Thank you for your suggestion, seems that afterRender is doing the trick.
I removed the function as I'm assuming that afterRender works the same - it runs after the page has rendered fully... is that correct?

I'll report if something goes wrong, but all good so far, thank you!

**Comment by alvarotrigo** [comment]
> it runs after the page has rendered fully... is that correct?

Yeap. After fullPage.js has applied all changes in the DOM structure.
