### ISSUE TITLE
[Question/Help]Navigation Menu using Elementor

### ISSUE THREAD

**Issue by ThoxikGFX** [alvarotrigo/fullPage.js#4249]
Hello. I'm new into fullPage.js.
I bought the Elementor plugin and right now I understood how to setup fp.

I am looking to reproduce the navigation menu found on this page at the bottom: https://play2.studiogusto.com/

My question is: How can I link a menu like that to my horizontal slides to act like the nav dots from fp, using elementor?
![Screenshot 2021-08-21 193615](https://user-images.githubusercontent.com/89312974/130328755-51d1a030-a256-47e0-9933-9d6518376a90.png)

Also, if you can suggest me a way to achieve that menu type, would be so nice. Thank you so much!!

**Comment by alvarotrigo** [comment]
> I bought the Elementor plugin and right now I understood how to setup fp.

For any questions about the official plugin please use the [contact form](https://alvarotrigo.com/#contact).
