### ISSUE TITLE
waterEffect Webflow

### ISSUE THREAD

**Issue by albinlenell** [alvarotrigo/fullPage.js#4250]
Ive been following the tutorials and gone through the documentation several times with no success to run the script.

A cloneable would be optimal, but I havent found the script being used within Webflow yet.

https://watereffect-test.webflow.io/

I have purchased the scripts but need to run them before I connect to final domain.

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
For extensions questions use the [contact form](https://alvarotrigo.com/#contact). 

Thanks ;)
