### ISSUE TITLE
Some kind of shake/twitching while scrolling

### ISSUE THREAD

**Issue by AidosMarcos** [alvarotrigo/fullPage.js#4251]
I use FullPage to scroll verticaly. But i get this weird shake while mouse scrolling.
This is an old website, and this bug was reported yesterday, can't seem to figure it out.
Anyone already had this same issue?

This is the website:
http://www.mouras.pt/

Just calls Fullpage like this:

$('#fullpage').fullpage({
       verticalCentered: false,
        scrollBar: true
});

Its most noticible in Edge, but also happens in Firefox and Chrome.

**Comment by Lettro** [comment]
How did you fixed this? I'm having that same issue after I set `scrollBar` to true

**Comment by alvarotrigo** [comment]
> How did you fix this? I'm having that same issue after I set `scrollBar` to true

Can you provide us an isolated reproduction in codepen?

**Comment by Lettro** [comment]
Oh, my bad!

I was using a really outdated version of the script.

Thanks Alvaro!

**Comment by alvarotrigo** [comment]
No problem! :)
