### ISSUE TITLE
Fullpage.js Water Effect

### ISSUE THREAD

**Issue by albinlenell** [alvarotrigo/fullPage.js#4252]
I've been requesting the Water Effect for some time, glad to see its finally here! Great work Alvaro. 
I've succeded to call the script (I believe). But there's still something im missing. The slides comes out black. I tried to inspect the code on the Demo page: https://alvarotrigo.com/fullPage/extensions/water-effect.html
But not sure what look for.

Here's my test page: https://watereffect-test.webflow.io/

**Comment by albinlenell** [comment]
Could it possibly be something with the body? <body class="fp-waterOn">

**Comment by alvarotrigo** [comment]
Not quite sure if you saw my previous answer:
https://github.com/alvarotrigo/fullPage.js/issues/4250

**Comment by alvarotrigo** [comment]
In any case, probably the issue is that you need images to be hosted under the same domain as the JS script.
This is a canvas element restriction.

**Comment by albinlenell** [comment]
@alvarotrigo I did see it, Ive been on the contact form several times, but I get told to resolve to the Github Issues page. And on here I get told to resolve to the contact form. 

[https://imgshare.io/image/mail.peQ0Xf](url)

I would very much appreciate if you could keep this open for now while im trying to sort this out <3

**Comment by albinlenell** [comment]
@alvarotrigo The images are hosted under same domain, and fullpage.js behaves somewhat as it should. I am still unable to get the waterEffect to fire.

Will play around a bit, but would be happy to have you inspect.

**Comment by albinlenell** [comment]
Images are now hosted on same domain, and fullpage.js seems to be working
as intended. The waterEffect is not triggered however.
https://watereffect-test.webflow.io/

I currently host the watereffect script like this:
<script type="text/javascript" src="
https://uploads-ssl.webflow.com/61235da8a85873352c684205/6123aa5235c79705e9e6b8fe_waterEffect.txt
"></script>

could this be the problem?

**Comment by alvarotrigo** [comment]
> @alvarotrigo I did see it, Ive been on the contact form several times, but I get told to resolve to the Github Issues page. And on here I get told to resolve to the contact form.

Sorry about that. A miss understanding.
Let's keep the conversation but email, using the ticket system.
