### ISSUE TITLE
Scrollling content

### ISSUE THREAD

**Issue by aslam4276** [alvarotrigo/fullPage.js#4258]
Is there is any way to make section scrollable without using scrollOverflow: true ??

**Comment by alvarotrigo** [comment]
Nope. That's the whole purpose of `scrollOverflow` :) 

fullPage.js version 4 will come out in about a month or two, and that would make things easier on this regard.

**Comment by aslam4276** [comment]
> Nope. That's the whole purpose of `scrollOverflow` :)
> 
> fullPage.js version 4 will come out in about a month or two, and that would make things easier on this regard.

Okay great, I made a scrollable div inside section without scrollOverflow and scroll is working fine when a drag scroll thumb.  But when a normal scroll the whole section goes down to next section. 

Is there is any way to stop fullpage js scroll functionalty only for this section. When div fully scrolled then enable fullpage js functionality??

**Comment by alvarotrigo** [comment]
> Is there is any way to stop fullpage js scroll functionalty only for this section. When div fully scrolled then enable fullpage js functionality??

Not out of the box.
You'll have to implement it by yourself.

**Comment by aslam4276** [comment]
Hi again @alvarotrigo Are you ready for custom work with charge?
It's very urgent for us.

**Comment by alvarotrigo** [comment]
Depends on what's about.
Can you be more specific? Concact me with more details using the [contact form](https://alvarotrigo.com/#contact).
