### ISSUE TITLE
ScrollOverflow overlapping bigger section bug 

### ISSUE THREAD

**Issue by alexxbout** [alvarotrigo/fullPage.js#4261]
Hi, I wanted to use the scrollOverflow option to navigate thought bigger sections than the viewport but it seems that when scrolling to last section, the previous one is overlapping the next section and make his content not fully visible.

You can see the bug here : https://codepen.io/iCrossing/pen/jOwMQww

Thank you for your time !

**Comment by alvarotrigo** [comment]
I believe you are missing the CSS file `fullpage.min.css`

**Comment by alexxbout** [comment]
Thank you, I'm not good, it works now !
