### ISSUE TITLE
Scroll Horizontally, with other content on Site outside of fullpage

### ISSUE THREAD

**Issue by thebananaland** [alvarotrigo/fullPage.js#4264]
### Description
I'm trying to use the scroll horizontally extension while including content before and after fullpage.js, Since Scroll horizontally needs to use autoscroll, I turn it on when the fullpage element gets to the top of the screen and then turn it off after the last slide in the section. The problem is that the fullpage slider causes the site to scroll to the top of the screen

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/326okrzq/3/

In case you want to see my version: https://tidalriver.wpengine.com/

### Steps to reproduce it
1. Create a content div before the fullpage div
2. Create fullpage div with slides. Include horizontal slide extension
3. Create another content div after the full page
4. By Default turn off autoscroll and fit
5. When fullpage becomes inview enable autoscroll so that horizontal slide extension works
6. Disable autoscroll after last slide so that you can view the rest of the content on the site

### Versions 
Chrome 92.0.4515.159, mac osx,

**Comment by alvarotrigo** [comment]
Unfortunately, fullPage.js is meant o be used "full-page" and not with content above or underneath it.
The library is not supporting that kind of scenario as of today.

The most you can currently do is make use of scrollable sections to simulate the normal scroll of the page.
See an example here:
https://alvarotrigo.com/fullPage/examples/scrolling.html#secondPage
