### ISSUE TITLE
fullpage stuck on the firstPage 

### ISSUE THREAD

**Issue by JamesChao415** [alvarotrigo/fullPage.js#4265]
We use javascript json to gain the m3u8 video.This is normal. We do this to accomplish like tiktok app.
if no use javascript json gain video just write in html , this can work.
But "sometimes" reload the page is fail, the body class write
this is fail status    =>    <body class="fp-viewing-1" style="overflow: hidden; height: 100%;> 
this is right status    =>    <body class="fp-viewing-0" style="overflow: hidden; height: 100%;> 

When fail status, the first page can't slide to the second page and behind pages. 
(This status may fullpage didn't get the other pages)

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
> (This status may fullpage didn't get the other pages)

Make sure you only initialize fullpage.js once the DOM structure is ready.
