### ISSUE TITLE
How to add custom arrows to the Slide component?

### ISSUE THREAD

**Issue by Satyam-code143** [alvarotrigo/fullPage.js#4267]
I have been trying to add my own custom arrows with different icons. However, I was unable to find any property that would display my custom arrows in place of the default ones. In seeking out ways to change arrows, I learned that CSS can alter existing arrows. Could you please help me out with this task or tell me how I can accomplish it.

Thank You!!

**Comment by alvarotrigo** [comment]
This should be much easier in fullPage.js version 4, but so far, for version 3, try these solutions:

- https://stackoverflow.com/a/29583529/1081396
- https://stackoverflow.com/a/30043752/1081396
