### ISSUE TITLE
Oxygen builder - Sections skipping - Disable screen under a media query

### ISSUE THREAD

**Issue by AgenceReally** [alvarotrigo/fullPage.js#4269]
### Description

Hey guys i just bought fullscreen.js and followed Elija Mills Oxygen tutorial for the implementation of Fullpage.js. (https://oxygenbuilder.com/tutorial/how-to-use-fullpage-js-with-oxygen/)

I got a few issues and questions :
I created three simple section, each time the color changes, after the first scroll it goes directly to the 3rd section
Anchors: ['#Couvreur', '#chatalors', '#Relampix'],
It's just skipping chatalors, why ? 

### Steps to reproduce it
1. Go to https://agence-really.fr/test-portfolio/ 
2. Scroll once, you'll see it's skipping a section

I'd like to be able to disable the whole screen under a media query, didn't find anything about that, is it possible ? didn't find anything

### Versions 
Wordpress, oxygen builder
Using : 
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.min.js" integrity="sha512-gSf3NCgs6wWEdztl1e6vUqtRP884ONnCNzCpomdoQ0xXsk06lrxJsR7jX5yM/qAGkPGsps+4bLV5IEjhOZX+gg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.1.2/fullpage.extensions.min.js" integrity="sha512-v0jjVvFpZqb1BcXhgLbaBDRKwZ09IpWFZL5NHTNbW9MlSjhZihkxEz2uNeMGd6HuK1qnSEL6JdyTr24ZHlgKow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

### Things to know about me

You'll have to tell me the exacts steps to follow otherwise i might screw something up or just straight have a blank face !
I'm far from being a dev and still learning a lot, sorry if it longer to answer me !

**Comment by alvarotrigo** [comment]
Unfortunately, we don't cover WordPress implementation issues on this forum.
We would recommend you to use the [official plugins for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/). We created those and we provide top support for them :)

**Comment by AgenceReally** [comment]
I wouldn't mind but those two plugins are not compatible with oxygen from what i heard

Where should i ask a refund then ?

**Comment by alvarotrigo** [comment]
> Where should i ask a refund then ?

Use the [contact form](https://alvarotrigo.com/#contact).
