### ISSUE TITLE
scrolling in Firefox

### ISSUE THREAD

**Issue by andview** [alvarotrigo/fullPage.js#4270]
### Mouse wheel scrolling in Firefox (92.0 64bit) only works between the first two sections.
Although the keyboard arrows and navigation controls work for all sections. This problem is not present in opera, ie, chrom  

### Steps to reproduce it
1a. extract fullPage.js-master.zip and  run any *.html from `examples` folder from Firefox (92.0 64bit (last version))
1b. or https://alvarotrigo.com/fullPage/  from Firefox (92.0 64bit (last version))
2. please scroll the mouse wheel 

### Versions 
 fullPage.js 3.1.2 | Firefox 92.0 64bit, last version | windows10 | descktop

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on either, my computer or browserstack.com.
Have you tried from another computer or using another mouse/trackpad?

**Comment by alvarotrigo** [comment]
Also, make sure you have all firefox extensions deactivated (or try in incognito mode without extensions?). They might be interfering with it in some way.

**Comment by alvarotrigo** [comment]
Awesome! 
Glad you found the issue.
