### ISSUE TITLE
Responsive slides and lazy load not working on mobile

### ISSUE THREAD

**Issue by josh-attwood** [alvarotrigo/fullPage.js#4271]
Currently having a problem with lazy load and responsive slides. Lazy loading is working perfectly on desktop but when reducing screen size to under the responsive slides threshold lazy load is no longer loading the images in. Currently have slidesToSections as true so perhaps lazy load is not accounting for the slides being stacked. It only seems to be a problem when slides become sections.

Can reproduce on the homepage of millco.co.uk

Using wordpress, webpack 5.21.2, postCss 8.3.5

**Comment by josh-attwood** [comment]
Going to do a temporary fix on millco.co.uk so please see https://millco.modernactivity.com/ for reference

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
We'll take a look at it as soon as possible!

**Comment by alvarotrigo** [comment]
I'll close this issue as the issue seems to be fixed now in fullPage.js version 4.
