### ISSUE TITLE
moveSectionDown() overrides setKeyboardScrolling() with spacebar...

### ISSUE THREAD

**Issue by hholland-google** [alvarotrigo/fullPage.js#4275]
### Description
If you setKeyboardScrolling(false) and also implement a button that calls moveSectionDown() a spacebar key input then allows the spacebar to keep scrolling the page - it shouldn't. 

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/hholland/pen/rNwRwRv

### Steps to reproduce it
1. Press the moveDown button
2. Press the spacebar
3. Then press the spacebar again etc..

### Versions 
Chrome Version 94.0.4606.61 (Official Build) (x86_64) MacOS

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
This seems to be a tricky one from the accessibility point of view.

The reason why this is happening is that once you click on a button, the button itself gets focused.
Focused buttons (as well as checkboxes) can be triggered using the space bar:
![image](https://user-images.githubusercontent.com/1706326/135483620-7766876d-325e-4bad-8d8c-ff136f6fb290.png)
Source: https://webaim.org/techniques/keyboard/

I assume this depends on the browser implementation but I haven't checked other browsers.

I'm not quite sure disabling this is the way to go. 

It would be nice to have feedback on this from people more versed on accessibility like @charlesprescottcollins , @mjoyce91 , @ShayMe21 , @chris480 or @karlbalagtey.

**Comment by hholland-google** [comment]
Oh of course! In which case its an easy fix - an _onmousedown_ even instead of an _onclick_ event is the workaround! :-D

**Comment by alvarotrigo** [comment]
Interesting fix! :) 
The other option would be to unfocus it right after the click.

**Comment by chris480** [comment]
Going with webaim is the right call. Users are going to act in a way that conforms most with convention. So if a button is supposed to work a certain way as defined by browser standards, it is not generally accepted to override it.

When the a user is on a button context, it acts in a way you expect a button should be interacted with. 

Unfocus seems like an acceptable solution, or a hidden SR/A11y based navigation.

**Comment by alvarotrigo** [comment]
@chris480 thanks for the explanation! 👍 
I'll proceed to close the issue then as they can still apply alternative solutions to it.
