### ISSUE TITLE
Delay or teaser of the next section on scrolling a little bit

### ISSUE THREAD

**Issue by joerimarquerinck** [alvarotrigo/fullPage.js#4276]
Would it be possible to show a little bit of the next section when you scroll a little bit before going to the next section on a normal/long scroll?

**Comment by alvarotrigo** [comment]
Sure!
Right now you can do that using the [Offset Sections extension](https://alvarotrigo.com/fullPage/extensions/offset-sections.html).

Any other questions feel free to ask ;)
