### ISSUE TITLE
On android chrome, trying to scroll up causes page don't load element

### ISSUE THREAD

**Issue by Juli3n-dotcom** [alvarotrigo/fullPage.js#4277]
### Bonjour,

J'ai essayé de créer mon site avec fullpage.js, le site fonctionne parfaitement sur Desktop et IOS (sur les différents navigateurs), mais par contre il ne fonctionne pas sur android, nottament sur Chrome.

### Link to isolated reproduction with no external CSS / JS
https://julien-quentier.fr/portfolio/beta/

### Steps to reproduce it
1. Try to load my website on Chrone on Android
2. Scroll up

### Versions 
[Chrome, Android, Redmi note 10 , ...]

**Comment by alvarotrigo** [comment]
I took the liberty to translate your text to english using Google Translator:

> I tried to create my site with fullpage.js, the site works perfectly on Desktop and IOS (on the different browsers), but on the other hand it does not work on android, in particular on Chrome.

Answering your question: 
Is this demo page working for you?
https://alvarotrigo.com/fullPage/examples/navigationV.html

**Comment by alvarotrigo** [comment]
I'll close the issue as I was never able to reproduce it.
