### ISSUE TITLE
On iPad, swiping causes page to load error

### ISSUE THREAD

**Issue by shielakn** [alvarotrigo/fullPage.js#4280]
Hi,

Here's the website right now: https://bcanuntoldhistory.knowledge.ca/

If you test it on an iPad, when you swipe up the page reloads then goes to a page loading error like this:
![image](https://user-images.githubusercontent.com/57919044/137025164-16645312-de36-43dc-834b-a63a24f2db2b.png)

**Comment by alvarotrigo** [comment]
We don't check personal sites here.

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
