### ISSUE TITLE
setAutoScrolling not working as intended

### ISSUE THREAD

**Issue by cameronandrews** [alvarotrigo/fullPage.js#4287]
### Description
Trying to disengage the auto scrolling when reaching end of page so that normal scroll is enabled for a footer.  I saw lots of old examples here on Github and it currently works except in doing so it gets rid of the "slide" effect. 

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/cameronandrews/pen/gOxLwyN

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/3205

Short answer: it's not currently possible (as far as I know) and fullPage.js doesn't provide any out-of-the-box solution for it.
You'll have to wait until version 4 comes out.

I'll close the issue to keep the conversation centralized in a single thread.
