### ISSUE TITLE
Question: Ignoring sections with navigation

### ISSUE THREAD

**Issue by jdspeyer** [alvarotrigo/fullPage.js#4288]
### Question: Is it possible to have the integrated navigation dots "ignore" certain sections?

Example: Building a website with 5 sections. Can I make it so section 2 does not receive a navigation dot but sections 1, 3, 4, and 5 do? Or would I have to build my own navigation bar for this sort of functionality?

Thanks in advance!

**Comment by impshum** [comment]
This will hide them.

```
#fp-nav li:nth-of-type(1) {
  display: none;
}
```

**Comment by alvarotrigo** [comment]
> This will hide them.

This will hide the navigation bullets. Not the section itself.
The section will still be present and fullPage.js will scroll to it. (This will soon be fixed in v4)

**Comment by alvarotrigo** [comment]
> #fp-nav li:nth-of-type(1) {
>   display: none;
> }

That's the way to go :)
