### ISSUE TITLE
Multiple FullPage sections in same page

### ISSUE THREAD

**Issue by RajeevRF** [alvarotrigo/fullPage.js#4292]
I am using FullPage.js licensed version.
In my page, we use 2 separate fullpage.js sections.

When I use `new fullpage('')` twice to call them inside `jQuery(document).ready(function($){` , I get error like below.
"Fullpage.js can only be initialized once and you are doing it multiple times!"
I read somewhere to destroy one instance and initiate another again.
In my case, both these sections are on the same page with normal sections(Cannot wrap all these sections in the same wrapper) in between.

How and when to destroy the FullPage instance? Can you share some examples?

**Comment by alvarotrigo** [comment]
> In my case, both these sections are on the same page with normal sections(Cannot wrap all these sections in the same wrapper) in between.

Unfortunately, fullPage.js can only be used once per page. As the error says.

**Comment by alvarotrigo** [comment]
Duplicated of https://github.com/alvarotrigo/fullPage.js/issues/1029
Closed to keep the topic in a single place.
