### ISSUE TITLE
The animations of the divi modules do not load.

### ISSUE THREAD

**Issue by LuisESD** [alvarotrigo/fullPage.js#4293]
I have fullPagejs configured and the animations of the DIVI modules have stopped working.
![image](https://user-images.githubusercontent.com/93682433/140191128-9dc944f6-4716-429a-bf19-e2dc48fec155.png)

You should load the page or section and start scrolling the bars, so that it looks like this:
![image](https://user-images.githubusercontent.com/93682433/140191233-e3b8577d-9da5-434e-a92d-49d7f462c507.png)

Does anyone know how to fix it?

**Comment by alvarotrigo** [comment]
We don't cover third-party integration issues here.
But you might probably have to initialize the plugins used by those components in the `afterRender` callback.
