### ISSUE TITLE
Using fullPage.js in Divi.

### ISSUE THREAD

**Issue by LoganvanWyk** [alvarotrigo/fullPage.js#4294]
Hi,

I’m trying to implement fullPage.js into divi.
How would I go about implementing fullPage.js into divi?

Any guidance would be greatly appreciated. 

Thank you!

**Comment by alvarotrigo** [comment]
Unfortunately, we do not have a Divi plugin yet, only the [fullpage.js plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [fullPage.js for Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/).

However, we good news are we are working on it!! 
You can subscribe to the waiting list on the [fullPage.js plugin for Divi](https://alvarotrigo.com/fullPage/wordpress-plugin-divi/) website.

Besides that, we only treat issues regarding fullPage.js itself on this forum, not third-party integrations. 
So I'll proceed to close this issue.
