### ISSUE TITLE
Movement to bottom after back 

### ISSUE THREAD

**Issue by perroz1988** [alvarotrigo/fullPage.js#4295]
### Description
Hello, 
the page is good, but when we go inside a news, and inside another page, when we return the page scroll automatically to the bottom and return to the right place after some seconds.
How we can fix this?

https://user-images.githubusercontent.com/93984616/140918345-df8a3148-7c12-43ad-8d2a-a453528d6193.mp4

https://bovieassociati.it/

Here you can find a little video

**Comment by alvarotrigo** [comment]
For any questions regarding the [official plugin for Elementor for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/contact/).
