### ISSUE TITLE
'loopTop:false' not working with 'autoScrolling: false'

### ISSUE THREAD

**Issue by Shayan-84** [alvarotrigo/fullPage.js#4298]
Hi, I've been trying to create a page with scroll bar enabled and no loops. But no matter what  I do, still the 'loopTop' is true and loops my entire page back to the bottom.

note: everything is the latest version.

this is my code: 
const myFullpage = new fullpage('#fullpage', {
    autoScrolling: false,
    navigation: true,
    navigationPosition: 'right',
    scrollingSpeed: 800,
    loopTop: false,
    loopBottom: false,
});

**Comment by alvarotrigo** [comment]
I can't reproduce your issue in here:
https://jsfiddle.net/fyp8arnw/1/

Could you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by Shayan-84** [comment]
Hey there, I just tried to run a basic sample of my project in codepen and the problem didn't occur anymore. I figured Fullpage.js has a little bit of conflict with TailwindCSS. So I'll just stick to the auto scrolling feature with a faster speed and hopefully the problem will be solved soon. BTW thanks for the follow-up.

**Comment by alvarotrigo** [comment]
> I figured Fullpage.js has a little bit of conflict with TailwindCSS.

If this is something you can reproduce in an isolated website with no external JS I'd take a look at it.

**Comment by Shayan-84** [comment]
https://codepen.io/shayan-84/pen/eYExEPv

this is what I'm using in my project. But as you see, that problem does not happen in codepen

**Comment by alvarotrigo** [comment]
Maybe you can share an isolated version of your project's URL?
Or use code sandbox or similar to use tailwind on it and try to reproduce the issue.

**Comment by Shayan-84** [comment]
This is a link to the repository I uploaded my project's files on. I described the problems in the readme file. Check it out.

https://github.com/Shayan-84/fullpage.js-test

https://shayan-84.github.io/fullpage.js-test/

**Comment by alvarotrigo** [comment]
[Your fullpage.js stylesheet](https://shayan-84.github.io/fullpage.js-test/fullpage.min.css) is not the original one.

You are modifying it and commenting out specific styles:

```js
*/.fp-enabled body,
html.fp-enabled {
	margin: 0;
	padding: 0;
	overflow: hidden;
	-webkit-tap-highlight-color: rgba(0, 0, 0, 0)
}
```

That is probably a reason.
Another one. You are missing the doctype declaration.`<!DOCTYPE html>` at the beginning of the HTML file, as detailed on the docs.

**Comment by Shayan-84** [comment]
Thank you so much Alvaro. As you said, doctype declaration was the problem and now it's solved.
