### ISSUE TITLE
One element will not scroll on mobile devices (android  & ios)

### ISSUE THREAD

**Issue by eslothouber** [alvarotrigo/fullPage.js#4299]
### Description
I've created an big one scroll page with fullpage and everything works out great. Except one element. On mobile devices it just won't scroll on swipe.

### Link to isolated reproduction with no external CSS / JS
https://blikgoedtest.nl/#over
You cant scroll/swipe to the next "klanten" element.

### Steps to reproduce it
1. goto https://blikgoedtest.nl/
2. Click on "Over" in the navigation
3. Swipe to the following element (klanten). Navigation and arrows work, swipe won't

### Versions 
Android 10, iOS, Fullpage  3.1.2

**Comment by eslothouber** [comment]
Thank you for your reply Alvaro,

I filled in the form, and the website owner bought a license:
licenseKey: '8135C273-21C6444E-93F47484-6B7B6318'
(from @buroblikgoed.nl)

Hope you can help us, thanks in advance.

**Comment by alvarotrigo** [comment]
You bought the Hobby license, not the Business one.
Only the Business one includes premium support as I mentioned on my previous comment. 

Feel free to update and I'll refund you the Hobby one.

**Comment by eslothouber** [comment]
Hi Alvaro,
They upgraded to the Business licence. I hope you can take a look at it now?
005ABF2E-2AF54B5A-815EF0B6-887698BD

Thanks you in advance.

**Comment by alvarotrigo** [comment]
> They upgraded to the Business licence.

You got the Professional license, not the Business one.
You can get the Business one from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>. Let us know when you do so we can refund you the 2 previous one (Hobby + Professional)

**Comment by alvarotrigo** [comment]
I haven't heard from you so I'll be closing the issue for now.
