### ISSUE TITLE
change "navigation: false/true" after load last section

### ISSUE THREAD

**Issue by VNavrockij** [alvarotrigo/fullPage.js#4300]
Hello. How can i "navigation: false" change on "true" when be on last section ?? =)

I need to show the navigation after reaching the last section.

Thank you in advance for your response!

**Comment by alvarotrigo** [comment]
> Hello. How can i "navigation: false" change on "true" when be on last section ?? =)

Unfortunately that's not possible.

However, as an alternative, you can just use CSS to hide whenever you are not in the last section.
See this codepen:
https://codepen.io/alvarotrigo/pen/XWeWWNd

Code:

```js

new fullpage('#fullpage', {
  licenseKey: 'YOUR KEY HERE',
  navigation: true,
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
  onLeave: function(origin, destination, direction){
    var allSections = document.querySelectorAll('.fp-section');
    var navigation =  document.querySelector('#fp-nav');

    // on the last section?
    if( destination.index === allSections.length -1 ){
      navigation.classList.add('show');
    }
    else{
      navigation.classList.remove('show');
    }
  }
});
``` 

```css

#fp-nav{
  display: none;
}
#fp-nav.show{
  display: block;
}
```
