### ISSUE TITLE
Activation for Extensions on Subdomains

### ISSUE THREAD

**Issue by nilswloewen** [alvarotrigo/fullPage.js#4302]
I have purchased the parallax extension and I have it working at my domain. However, I get the 'Unlicensed fullPage.js Extension' error when I use it at subdomain.domain.com. I cannot find any documentation about subdomains. If this is intended functionality and I need to register my subdomain as well as my domain then please document this at the registration page. 

Currently the documentation at the registration page leads me to think any subdomains should work for a registered domain. 

'Introduce the domain name in which you will be using the extension
For example,the domain name of "https://support.apple.com" is "apple.com".'

**Comment by alvarotrigo** [comment]
> Currently the documentation at the registration page leads me to think any subdomains should work for a registered domain.

That's the case.
The activation takes place at the domain level. Sub-domains are all sharing the same domain. 

You'll just need to enter your domain name.

**Comment by nilswloewen** [comment]
Thank you for the quick response!
