### ISSUE TITLE
afterRebuild event not firing (demo included)

### ISSUE THREAD

**Issue by aanders50** [alvarotrigo/fullPage.js#4305]
### Description
I believe I found a found a bug regarding afterRebuild event not firing. I am trying to fix a different issue with reBuild() where it changes the viewport location upon completion, but during this I tried to use the afterRebuild event hook to call a .moveTo() but the reBuild event hook does not seem to not be responding in 3.1.1 or 3.1.2.

### Link to isolated reproduction with no external CSS / JS
This codepen is one of your simple demos and I just added a minor button element with along with a rebuild event.
https://codepen.io/aanders50/pen/BawoGRR?editors=1111 

### Steps to reproduce it
Clicking the button triggers a manual rebuild, which I believe should be triggering the console.log("rebuild event") of the afterRebuild event, but it is not? Any help appreciated!

### Versions 
Fullpage 3.1.2 and/or 3.1.1

**Comment by alvarotrigo** [comment]
Capital B. :) 

```js
afterRebuild 
afterReBuild
```
