### ISSUE TITLE
Image flickering on Section scroll down

### ISSUE THREAD

**Issue by expdeveloper2021** [alvarotrigo/fullPage.js#4306]
Hii Dev community, hope you are all doing good, I will be happy if any one of you can assist me out of this issue.

I have made a component in which I get data from Firebase and show the images to user via ReactFullPagejs, kind of like 10 images in 1 section.

so if I have 30 images it will show me 3 sections and each section will be having 10 images.

issue: whenever I scroll a section from one to other, the images cause a flicker mainly on iPads and iOS devices, is there any way to prevent this flicker.

**Comment by alvarotrigo** [comment]
I can't reproduce your issue in the [demo page](https://alvarotrigo.com/fullPage/) or any of the available examples online and offline [in the examples folder](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

Could you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by expdeveloper2021** [comment]
Hey @alvarotrigo , sorry, but I seen it and now I think it's something issue within my code as I just checked the ReactFullPagejs on a separate page with having background images and it works fine for me, thanks!!
