### ISSUE TITLE
How i can use header main(with section inner) and footer?

### ISSUE THREAD

**Issue by Poylar** [alvarotrigo/fullPage.js#4310]
in of docs: 
```
<div id="full page">
  <div class="section"></div>
  <div class="section"></div>
  <div class="section"></div>
  <div class="section"></div>
</div>
```
i want: 
```
<div id="fp">
  <header class="section"></header>
  <main>
    <div class="section"></div>
    <div class="section"></div>
    <div class="section"></div>
  </main>
  <footer class="section"></footer>
</div>
```
is possible?
I have header full height

**Comment by alvarotrigo** [comment]
> is possible?

Unfortunately that's not possible. fullPage.js requires a [specific structure](https://github.com/alvarotrigo/fullPage.js#required-html-structure).

**Comment by alvarotrigo** [comment]
> I have header full height

Try placing the header on the first section instead. 

```html
<div id="full page">
  <div class="section">YOUR HEADER</div>
  <div class="section"></div>
  <div class="section"></div>
  <div class="section"></div>
</div>
```

**Comment by Poylar** [comment]
> > I have header full height
> 
> Try placing the header on the first section instead.
> 
> ```
> <div id="full page">
>   <div class="section">YOUR HEADER</div>
>   <div class="section"></div>
>   <div class="section"></div>
>   <div class="section"></div>
> </div>
> ```

Thank you, yers I can place header first, but I need he scroll like first section. how I can do that?

**Comment by alvarotrigo** [comment]
Do not change the required structure. That's all.
