### ISSUE TITLE
Scroll not work properly

### ISSUE THREAD

**Issue by NabeelJaan** [alvarotrigo/fullPage.js#4311]
Hi there, is it possible to embed the fullPage.js with other sections of the website, mean to say I have 2 sections above the and 3 sections and  5 sections in the mid, I need the scroll behavior just in the middle 5 sections, not on the whole home.

**Comment by alvarotrigo** [comment]
You can try using an iframe, but you might have issues.
Let me know if that works for you.

**Comment by NabeelJaan** [comment]
> You can try using an iframe, but you might have issues. Let me know if that works for you.

Thanks, for the reply. But It's not working for me.

**Comment by NabeelJaan** [comment]
Could you please guide me? how the issues can be sorted out.

**Comment by alvarotrigo** [comment]
Unfortunately it's not a scenario that fullpage supports.

**Comment by NabeelJaan** [comment]
Do you mean we can't use fullPage.js in middle? It should be a full-page website? but I have purchased the license.

**Comment by alvarotrigo** [comment]
> It should be a full-page website? 

Notice the name of the component is fullpage 🙃

So yeah you can not use it on the mi idle of the page.

**Comment by NabeelJaan** [comment]
Thank you for clarifying.
