### ISSUE TITLE
Problem with scrollTrigger inside fullpage.js

### ISSUE THREAD

**Issue by Desginer123** [alvarotrigo/fullPage.js#4313]
Hello. I have a problem using GSAP ScrollTrigger inside React fullpage.js . I have several sections with the "section" class. Inside them there is content that is not thought of as immediately visible. I need that when loading my site and initializing fullpage.js I had the opportunity to scroll through my section and run GSAP timeline together with ScrollTrigger. I don't understand why scrollTrigger doesn't work inside a section with scrollOverflow = {true}.
In my idea, it looks like this: the site loads, React fullpage initialization, then the section with animation scrolls (as in the codepen I attached). After gsap.timeline ends, fullpage.js  sections are switched .
How to implement this? I ask for help.
Link to codepen: https://codepen.io/desginer123/pen/WNZLpQj
Link to the current website with React fullpage.js: https://projectxmain48161.gtsb.io/
React fullpage settings.js:
<ReactFullpage

    //fullpage options
    licenseKey = {'There is my license key'}
    scrollingSpeed = {1000} 
    fixedElements = {'.grow, .logo, .pagination-wrapper, .cursor2'}
    menu = {'.pagination-wrapper'}
    anchors = {['about', 'mission']}
    scrollOverflow = {true}

    onLeave =  {function(origin, destination, direction){

                 var loadedSection = this;

                 changePagination(destination.index + 1)
                 //using anchorLink

                 if(destination.index == 1){

                   gsap.to('.about-1', {opacity: 0, duration: 1.2})
                   gsap.to('.mission', {opacity: 1, duration: 1.2})
                   gsap.to('.mission-title', {opacity: 1, duration: 1.2})

                 }
                 if(destination.index == 0){

                   gsap.to('.about-1', {opacity: 1, duration: 1.2})
                   gsap.to('.mission', {opacity: 0, duration: 1.2})

                 }
               }}
    render={({ state, fullpageApi }) => {

      return (
        <main className='pageStyles'>
          <Cursor/>
          <Btn/>
          <Pagination/>

          <ReactFullpage.Wrapper>
            <FirstScreen changePagination={changePagination}/>

          </ReactFullpage.Wrapper>
        </main>
      );
    }}
  />
);
JSX: the same as codepen html

**Comment by alvarotrigo** [comment]
> I don't understand why scrollTrigger doesn't work inside a section with scrollOverflow = {true}.

Because sections using scrollOverflow are not using the browser scroll behaviour but a JavaScript simulated one.

fullPage.js version 4 will work differently in this regard and you'll probably have it easier in there to do what you need. It should come out by the end of this month.

**Comment by alvarotrigo** [comment]
Here's what I mean about the scrolling:
If you can somehow extract the translate Y position, you can use that for your GSAP animation. 
https://user-images.githubusercontent.com/1706326/149439443-981b4b25-4314-41e9-b40a-ad3303a2be54.mp4

Unfortunately, fullPage.js doesn't provide any other easy mode to get the Y position for an scrollOverflow section.

**Comment by Desginer123** [comment]
> > I don't understand why scrollTrigger doesn't work inside a section with scrollOverflow = {true}.
> 
> Because sections using scrollOverflow are not using the browser scroll behaviour but a JavaScript simulated one.
> 
> fullPage.js version 4 will work differently in this regard and you'll probably have it easier in there to do what you need. It should come out by the end of this month.

Yes, okay. Can I make the fullpage initialize from the third section, and ignore the first two? When the user has already scrolled to the third, then turn on the fullpage?

**Comment by alvarotrigo** [comment]
> Yes, okay. Can I make the fullpage initialize from the third section, and ignore the first two?

Unfortunately that's not possible.

**Comment by Desginer123** [comment]
> > Yes, okay. Can I make the fullpage initialize from the third section, and ignore the first two?
> 
> Unfortunately that's not possible.

Absolutely no way? Thank you for your answer, I will know in the future that scrollTrigger is not the best idea for fullpage.js. Will be wait fullpage4

**Comment by alvarotrigo** [comment]
> Absolutely no way?

Absolutely not in any way provided by fullPage.js. 
fulPage.js was designed to be used in full-page :)  (Although we'll change this a bit in fullpage.js v4 too!)


> I will know in the future that scrollTrigger is not the best idea for fullpage.js.

`scrollTrigger` can be used in fullPage.js, but not inside `scrollOverflow` sections for now.
You can use it in the rest of the page by using the fullPage option `scrollBar:true`.
