### ISSUE TITLE
fullpage.js onLeave not firing the delayed scroll after the first time

### ISSUE THREAD

**Issue by zaryavtre** [alvarotrigo/fullPage.js#4314]
Like the title says, onLeave timeout animation only fires the first time.

For context, the second section of my page has a script that delays its scroll to the next section until the animation has finished. In order to try to have this animation fire everytime we go from this section downwards I've extended the script to remove the "animate" class. 
But it so happens that the delayed animation only fires the first time we go through this section.

Site where this is happening : https://coincracy-v4.webflow.io/

And the code to supposedly make this work
```
const delay = 1000;

let timeoutId;
let animationIsFinished = false;
const roseTxt = document.querySelectorAll('.smart-rose');
const smartIllus = document.querySelector('.cc-smart-illustration');
const smartTitle = document.querySelector('.cc-smart-title');

new fullpage('#fullpage', {
  //options here
  css3: true,
  scrollHorizontally: true,
  scrollBar: true,
  scrollOverflow: true,
  normalScrollElements: '.scrollable-content',
  fitToSection: true,
  fitToSectionDelay: 1000,
  onLeave: function (origin, destination, direction) {
    var curTime = new Date().getTime();
    if (origin.index == 1 && direction == 'up') {
      for (var i = 0; i < roseTxt.length; i++) {
        roseTxt[i].classList.remove('ccsAnimate');
      }
      smartIllus.classList.remove('ccAnimate');
      smartTitle.classList.remove('ccAnimate');
      return true;
    }
    if (origin.index == 1 && direction == 'down') {
      //animating my element
      for (var i = 0; i < roseTxt.length; i++) {
        roseTxt[i].classList.add('ccsAnimate');
      }
      smartIllus.classList.add('ccAnimate');
      smartTitle.classList.add('ccAnimate');
      //roseTxt.classList.add('ccsAnimate');

      clearTimeout(timeoutId);

      timeoutId = setTimeout(function () {
        animationIsFinished = true;
        fullpage_api.moveTo(destination.index + 1);
      }, delay);

      return animationIsFinished;
    }
    if (origin.index == 2 && destination.index == 1) {
      for (var i = 0; i < roseTxt.length; i++) {
        roseTxt[i].classList.remove('ccsAnimate');
      }
      smartIllus.classList.remove('ccAnimate');
      smartTitle.classList.remove('ccAnimate');
    }
  },
});
```

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by zaryavtre** [comment]
Yes I can, here's a loose reproduction of the issue, the same is happening here on the 2nd section

[Codepen Reproduction](https://codepen.io/zaryavtre/pen/YzrdMZz)

**Comment by alvarotrigo** [comment]
This is what I see in my console when scrolling down from section 1 to 3:
![image](https://user-images.githubusercontent.com/1706326/149526966-63489814-ffd5-4631-a41f-df151e726c5f.png)

https://codepen.io/alvarotrigo/pen/oNGJOKb?editors=1010
What would you expect?

**Comment by alvarotrigo** [comment]
In case it helps, see how I'd recommend to delay the scroll here:
https://stackoverflow.com/questions/36176677/fullpage-js-adding-a-scroll-delay

**Comment by zaryavtre** [comment]
It doesn't really seem to solve the problem of targeting a specific section and then restart the "timeout" we go back to that specific section

**Comment by alvarotrigo** [comment]
See my previous comment and let me know what you would expect in the console.

**Comment by zaryavtre** [comment]
So basically I have 6 sections, which roughly translates to: origin 0 to 5 right?

What I would expect is that whenever we go from origin.index 1 to 2 there's a delayed scroll until the animation is finished.
Now this delayed scroll happens only the first time we go through index 1 to 2.

**Comment by alvarotrigo** [comment]
> Now this delayed scroll happens only the first time we go through index 1 to 2.

Right. But in terms of the `onLeave` callback trigger, is there any problem? 
I'm trying to understand if you are reporting a malfunction on the fullpage.js callbacks, or instead, you just don't manage to accomplish your purpose with it but the callback is working as expected.

To check if there's a problem with the callback, you can use a `console.log` and explain the current result vs the expected one.

**Comment by zaryavtre** [comment]
I mean, I'm not even sure, when console logging the origin, destination things seem to work fine.
Just the timeout isn't firing more than once.

Maybe I'm not really accomplishing the purpose with the callback

**Comment by alvarotrigo** [comment]
Try to reproduce the issue by just using `console.log` to simplify things. 
Getting into CSS classes or animations is probably unnecessary and only complicates things for me to understand.

**Comment by zaryavtre** [comment]
You can close this now if you want. I managed to make a workaround, and it's working so far.

Thanks for the help!
Sorry to have bothered you.

**Comment by alvarotrigo** [comment]
Glad you managed to find a solution! 👍
