### ISSUE TITLE
Continue to next section after scrolling to end of a normalScrollElement

### ISSUE THREAD

**Issue by dinis-rodrigues** [alvarotrigo/fullPage.js#4315]
### Description

Hello, I'm working with `normalScrollElements`. When I reach the end of the container, and continue scrolling down, I would expect to go to the next section (since this is standard behaviour). But I cannot make this happen. I tried `overScrollBehaviour: auto !important` on the element but this doesn't seem to work.

Do you know if this behaviour is possible to achieve ?
 
### Link to isolated reproduction
Reproduction: [CodeSandbox](https://codesandbox.io/s/react-fullpage-js-example-forked-rfm55?file=/src/index.js)
Container in question `.scrollable`.

**Edit:** I'm using React, I mistakenly didn't post In the React repo

**Comment by alvarotrigo** [comment]
I can't see any element in you HTML using the `scrollable` class, you are using `scrollable-team`instead.

But in any case, because you are using `scrollOverflow: true` you won't need to use `normalScrollElements`. 
See [this demo](https://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage). It seems that's what you want?

**Comment by dinis-rodrigues** [comment]
I'm sorry... I updated the example with the right class. 

I understand, In my project I'm using the `scrollOverflow` for some sections as shown in your example. But in this specific section I don't want to use the `scrollOverflow: true`. I have other elements present in the section, that are fixed. And for this specific scrollable container, when I reach the end I would like to follow the behaviour described, this is, to go to the next section.

Did this description helped ?

**Comment by alvarotrigo** [comment]
> I have other elements present in the section, that are fixed. And for this specific scrollable container, when I reach the end I would like to follow the behavior described, this is, to go to the next section.

In that case, fullPage.js won't do it for you.
However, the good news is that you still can do it by yourself! Just detect whether they reach the bottom/top and use fullPage.js methods `moveSectionUp` or `moveSectionDown` respectively. 

fullPage.js doesn't provide this behavior for the `normalScrolElements` option. As many times, people use it in many different ways, such as `canvas` elements, google maps iframes, etc.

**Comment by dinis-rodrigues** [comment]
Thank you for the clarification.

> Just detect whether they reach the bottom/top and use fullPage.js methods moveSectionUp or moveSectionDown respectively.

This was going to be my next step 😁

**Comment by alvarotrigo** [comment]
Awesome, let me know if you have any issues ;)
