### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by xLunarr** [alvarotrigo/fullPage.js#4316]
This is more of a question; how would I add a preloader to my fullPage.JS site?

**Comment by alvarotrigo** [comment]
In the same way you add it to any other site I'd assume?
You might want to use the `afterRender` callback in order to initialise it (if even needed)

**Comment by xLunarr** [comment]
Ok. I use [this](https://www.lunarr.cf/preloader/) preloader, would it work with [this](https://www.lunarr.cf/automatic-octo-tribble/src/html/) site?

**Comment by alvarotrigo** [comment]
I've never tried, but give it a try and let us know :)

**Comment by xLunarr** [comment]
K

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by xLunarr** [comment]
Doesn't work :/

**Comment by xLunarr** [comment]
I used this one and it worked
https://github.com/niklausgerber/PreLoadMe

**Comment by alvarotrigo** [comment]
Awesome!
