### ISSUE TITLE
Fullpage.js is preventing scrolling inside the CMS editor - webflow

### ISSUE THREAD

**Issue by Bradleeey** [alvarotrigo/fullPage.js#4318]
### Steps to reproduce it
1. create a CMS collection
2. Implement fullpage js on the project
3. Go the the CMS editor (cleient view not the view from the designer) and go to the CMS item.
4. try and scroll down

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Have you checked the webflow demos?
1. [Fullpage.js Webflow Example](https://webflow.com/website/Fullpagejs-basic-example)
2. [Fullpage.js Webflow Horizontal Slides](https://webflow.com/website/fullPagejs-Horizontal-Slides)

And the [tutorial on how to use fullPage.js with webflow](https://www.youtube.com/watch?v=1KF1_5A7Mes)?

There's an article on it too:
https://alvarotrigo.com/blog/how-to-use-fullpage-in-webflow-create-full-screen-slider/

**Comment by alvarotrigo** [comment]
I have no experience with webflow CMS editor so I don't really know how this can be done, but you just have to prevent fullPage.js from getting initialised when using the CMS editor.

Only initialise fullPage.s on the final website that will be visible for the user.

That should solve the issue for you.
They can probably guide you on how to accomplish this on the CMS forums.

> It's annoying because I paid for a licence and built the site not foreesing this bug.

Bear in mind fullPage.js is a JavaScript component. Third-party integrations are not part of fullpage.js and we can't possibly predict how it will behave in every use case :)

**Comment by alvarotrigo** [comment]
If you need premium support and you can give me access to the CMS editor I can take a look at it for you.

You can get the Business license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> for a 1 hour support.

I'll be happy to help! 👍

**Comment by Bradleeey** [comment]
Thanks but there isn't any budget for additional support sadly. Looking like I will just have to deactivate the script and work out another UX for the site. I will have a crack at the 'no conflict code again as it semed to work for someone else but if I cant work that out it's game over, unfortunately.

**Comment by alvarotrigo** [comment]
The trick is being able to deactivate it while using the CMS.
But as I said, I'm no expert in Webflow and I'm not familiar with their ways so I can't help you more without taking a deeper look at their CMS.

> I will have a crack at the 'no conflict code again as it semed to work for someone else but if I cant work that out it's game over, unfortunately.

Regarding this line `jQuery.noConflict(true);` I don't think you need that anymore.
fullpage.js version 3 uses JavaScript and doesn't rely on jQuery (not sure if you are using version 2?)

And the initialisation should be:

```js
new fullPage('#fullpage', {
   scrollBar: true,
   anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
   responsiveWidth: 990,
});
````

Instead of:

```js
$('#fullpage').fullpage({
  scrollBar: true,
  anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
  responsiveWidth: 990,
});
```

By the way, I'm not sure where you are applying the code they are suggesting a solution, but on your demo page I can only see this:

```js
<script>
$(document).ready(function() {
  $('#fullpage').fullpage({
    scrollBar: true,
    anchors: ['page1', 'page2', 'page3', 'page4', 'page5'],
    responsiveWidth: 990,
  });
});
</script>
```

So it seems to me you are not using the suggested code yet?
![image](https://user-images.githubusercontent.com/1706326/149948896-1a91a3ff-a576-485f-bdd6-48e37a486110.png)

**Comment by Bradleeey** [comment]
I'm Adding that suggested code into the footer of the site itself rather than the page. I have now implemented the suggested code in the footer tag of the page itself which does indeed cancel out the full-page script but UI for the editor isn't showing at all and the live site now has no fullpage running either. 

think I'm going to give up on this one. thanks for your help though

**Comment by Bradleeey** [comment]
I found a workaround, 
if i use this if (Webflow.env('editor') == undefined) { 
but replace == with != then it works, the only issue is it caches the editor state somehow so the only way to then preview the site at all with FullpageJS working is to go incognito mode. But it means you can edit the CMS and scroll which is a Win I guess.

**Comment by Bradleeey** [comment]
Webflow.push(function () {
  // check is the CMS editor is there
  if (Webflow.env('editor') != undefined) {
    $('#fullpage').fullpage({

    });
  } 
});

this is the solution in case anyone has the same probelm, like i said, has the caching issue but better than not being able to scroll in the editor

**Comment by alvarotrigo** [comment]
Glad you managed to solve it! ;)
