### ISSUE TITLE
jQuery not defined error on Apple Example demo page causing it to break the page

### ISSUE THREAD

**Issue by sethwhitaker** [alvarotrigo/fullPage.js#4319]
### Description
The Apple Example page is throwing JS errors an is causing it to not work.

https://alvarotrigo.com/fullPage/examples/apple.html

### Steps to reproduce it
1. Visit your example page for apple full page demo
2. see the JS error Uncaught ReferenceError: jQuery is not defined

**Comment by alvarotrigo** [comment]
Thanks for the heads up!
I'll need to check that out! 👍
