### ISSUE TITLE
sync anchors with sections

### ISSUE THREAD

**Issue by MarwanElsayed-20** [alvarotrigo/fullPage.js#4320]
### how to sync anchors with their sections 

can you help me with that i need to know how to link the anchor with their sections so when ever  iam in section viewport their anchor have active class?

**Comment by alvarotrigo** [comment]
Sure!
You can read about the `menu` option here:
https://github.com/alvarotrigo/fullPage.js#options

And you can see the examples containing a sync menu here:
https://github.com/alvarotrigo/fullPage.js/tree/master/examples

**Comment by MarwanElsayed-20** [comment]
Thank for help and the fast relpy :)
