### ISSUE TITLE
Unlicensed Js warning - even after purchasing the single domain license

### ISSUE THREAD

**Issue by Deepakajjan** [alvarotrigo/fullPage.js#4322]
### Purchased the Scroll Overflow JS extension and added to the site, however, it shows an error message stating "Unlicensed fullpage JS extension"

https://locationl.q.starberry.com/property-for-sale/7-bedroom-house-mid-terrace-for-sale-in-burma-road-n16-61f3cb40cbb50f60c7aefd26/

### Steps to reproduce it
1. Added the extension key
2. if you go this page you can see the unlicensed error

We are in the staging environment right now and added this extension.  Not sure where we need to add the domain name as it does not provide an option to add the domain name.  Your help would be greatly appreciated

### Versions 
All browsers, devices.

**Comment by alvarotrigo** [comment]
Check out the help center for info on why you get the error:
https://alvarotrigo.com/fullPage/help/How-to-fix-Unlicensed-extension-red-error-message/
