### ISSUE TITLE
Not able to Control Horizontal Slides

### ISSUE THREAD

**Issue by manas-85** [alvarotrigo/fullPage.js#4323]
Is there any option to control Horizontal slides to switch the next section vertically before the last horizontal slide show

**Comment by alvarotrigo** [comment]
I'm not sure to understand what you mean.

Can you please provide more information or a basic example in jsfiddle or codepen so we can get a better idea?

**Comment by manas-85** [comment]
I want to move my section down once 2nd slide is active

**Comment by alvarotrigo** [comment]
Like this?

https://codepen.io/alvarotrigo/pen/QWOMRvq
