### ISSUE TITLE
Responsive mode: does it disable fullpage completely or can it be partial?

### ISSUE THREAD

**Issue by SNagel** [alvarotrigo/fullPage.js#4326]
_Disclaimer: i'm new to this bib, have a "commercial" license for the base and also for the plugins. 
Is this the right spot to get some support?_

I have a yet simple fullpage.js project, nothing special so far. 
In normal (desktop) mode, i'm using full page sections that adjust to the viewport, scroll "section by section" (like a slide show), with a dot menu on the side, and i'm using the afterLoad callback to add some animation css classes to content elements, so when a section is active, some animation happens inside. 

Now i want to have a "normal" scroll behaviour and auto-height sections below 800px viewport width, because the fullpage concept falls apart there.  I'm doing that with the setting responsiveWidth:800 and fp-auto-height-responsive attributes for my sections. 
This works, but in responsive mode, it seems that the afterLoad callback is not active anymore (so no animations when scrolling by), also the menu at the side is not shown anymore, so the responsiveWidth option seems to have disabled everything(?) fullpage.js related? 

Ideally, i would still like to get an event triggered when scrolling by a section, and i would also like that the scrolling still "snaps" to the beginning of a section (even if that section is not full-height anymore). 

Is it possible to configure that behaviour for responsive mode, with the options, attributes or javascript commands? 

Asked differently: can i have two configurations for "normal" and for "responsive" mode, both somewhat fullscreen.js-ish, but with different settings?

**Comment by alvarotrigo** [comment]
> _Is this the right spot to get some support?_

For basic generic questions, yeah it's the right place.
For questions regarding extensions you can use the contact form.

> This works, but in responsive mode, it seems that the afterLoad callback is not active anymore (so no animations when scrolling by), also the menu at the side is not shown anymore, so the responsiveWidth option seems to have disabled everything(?) fullpage.js related?

This shouldn't be happening. Make sure to use the latest fullPage.js version.
See a working example here:
https://codepen.io/alvarotrigo/pen/LYOrXNz

> and i would also like that the scrolling still "snaps" to the beginning of a section (even if that section is not full-height anymore).

Unfortunately that's not an option provided by fullPage.js.
Snap is rather ON or OFF. It can't bee half ON.

You can however consider using the scrollOverflow feature as in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html)

> Is it possible to configure that behaviour for responsive mode, with the options, attributes or javascript commands?

Yes. See the docs regarding the `setResponsive` method.

**Comment by SNagel** [comment]
Thank you for the supprt 

– i think i have figured it out, the event is triggering now, i have re-written the fullpage configuration, there must have been some error in my first attempt. 
– I'll also check out the setResponsive method.

**Comment by alvarotrigo** [comment]
I'm glad you managed to figure it out! ;)
