### ISSUE TITLE
Use normalScrollElements option in combination with waterEffect: true

### ISSUE THREAD

**Issue by benjamin3105** [alvarotrigo/fullPage.js#4330]
I'm using the waterEffect extension. It works great but I also want to have normal scrollable content after lets say 3 sections. This seems impossible with waterEffect turned to true. 

This is my setup, nothing fancy:

<div id="fullpage">
	<div class="section">Some section</div>
	<div class="section">Some section</div>
	<div class="section">Some section</div>
	<div id="reset_scroll" class="section">Some normal  scrollable section</div>
</div>

{
  navigation: true,
  autoScrolling: true,
  continuousVertical: true,
  scrollBar: true,
  normalScrollElements: '#reset_scroll',
  
  waterEffect: true,
  waterEffectOptions: {
      animateContent: true, 
      animateOnMouseMove: true,
      speed: 1000
  }
}

Is it possible to have normal scrollable content in combination with waterEffect?

**Comment by alvarotrigo** [comment]
The most you can do is using the option `scrollOverflow` as in [this example](https://alvarotrigo.com/fullPage/examples/scrolling.html).

That's totally independent of using the water effect or not.

**Comment by benjamin3105** [comment]
@alvarotrigo perfect! Thank you very much!
