### ISSUE TITLE
Enter responsive mode by screen orientation?

### ISSUE THREAD

**Issue by SNagel** [alvarotrigo/fullPage.js#4331]
Dear supporters, 

i'm using fullpage.js (latest version), everything is basically fine. 

But would like to switch it over to responsive mode whenever the screen ratio switches to portrait oriention (no matter of the size of the viewport, first task is just to detect portrait or landscape, and switch to repsponsive if it's portrait).  

I understand we have the options of **responsiveWidth** and **responsiveHeight**, but they don't seem to be connected / in relation to each other. 

Advanced question is, if i can set up something like this, combining a viewport width and a orientation:

Please trigger the responsive mode only IF viewportWidth **<** 960px AND viewportHeight **>** viewportWidth 

Thanks for your support!

**Comment by alvarotrigo** [comment]
> Advanced question is, if i can set up something like this, combining a viewport width and a orientation:

Sure, you can detect the landscape or portrait orientation by using your own custom Javascript and then you can call the full-page function [`fullpage_api.setResponsive`](https://github.com/alvarotrigo/fullPage.js#setresponsiveboolean) with the `true` or `false` values.

However, note fullPage.js won't provide you with the way to detect the orientation of the device as that's something beyond the fullpage.js scope.
You can try to find solutions for that in places like StackOverflow. Check out this answer for example:
https://stackoverflow.com/a/4917796/1081396
