### ISSUE TITLE
Where to enter the LicenceKey?

### ISSUE THREAD

**Issue by SteBoeh** [alvarotrigo/fullPage.js#4332]
Hello,

I try a lot of times now to enter the licence Key, but it does not work. Unfortunately I am quite bad in programming, so I just copied the code as described in the help:

new fullpage('#fullpage', {
    licenseKey: 'xxx',
}); 

I Wrote this in the fullpage.js quite at the beginning. Of course it doesn't work. Help please :-)

Thanks, Ste

**Comment by alvarotrigo** [comment]
That's exactly how you do it.
Can you share the URL so I can take a look at it?

**Comment by alvarotrigo** [comment]
More info here:
https://alvarotrigo.com/fullPage/help/Where-to-use-fullPage-license/

**Comment by SteBoeh** [comment]
Hi Alvaro, thank you.
The url is

**Comment by SteBoeh** [comment]
http://psychotherapie-heilpraktiker.com/

**Comment by SteBoeh** [comment]
Maybe you can give me also an hint what the other error means. the fullPage functionality does not work....

**Comment by alvarotrigo** [comment]
> Maybe you can give me also an hint what the other error means. the fullPage functionality does not work....

You are not using it properly.
See [the docs](https://github.com/alvarotrigo/fullPage.js/) for more info and check [the examples](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).
