### ISSUE TITLE
White flashes in Safari

### ISSUE THREAD

**Issue by renepoell** [alvarotrigo/fullPage.js#4333]
### Description
After a page has changed, there is a short white flash in Safari. The flashing appears not only on my website but also on your demo sites.

### Versions 
[macOS 12.2., Safari 15.3]

**Comment by alvarotrigo** [comment]
Sounds like [a bug in Safari](https://www.viget.com/articles/webkit-transform-kill-the-flash/) dealing with the `translate3d` property.
You can try a few things:
https://stackoverflow.com/a/15759785/1081396

But probably the best way to avoid is by:

1- Using `scrollBar:true`. Eliminating the 3d transform transition.
2- Using `css3: false`. Eliminating the 3d transform transition.

Any of those should fix the issue.

**Comment by renepoell** [comment]
Okay, I will try.
Thanks for the quick response!

R


Am Fr., 11. März 2022 um 19:52 Uhr schrieb Álvaro ***@***.***
