### ISSUE TITLE
Hide control arrows on desktop, but display on mobile

### ISSUE THREAD

**Issue by YungWalkie** [alvarotrigo/fullPage.js#4335]
So, I made a website with this awesome plugin. But, I've created on each section 3 slides, and wanna make appear only first one on desktop, and all of them appear on mobile version. That was very simple, just .fp-controlArrow {display:none}, and put .fp-controlArrow{display: block} in to a @media in css file. But, when I set loopHorizontal: false property in the .js plugin, arrows appear when page restart on the desktop version. How can I hide them? Problem appears only with loophorizontal false

**Comment by alvarotrigo** [comment]
> It works. But when I wanna make them appear in mobile, the can't, because of **!important** property.

Just do the opposite by adding the `important` param again:

```js
// overwriting the display property using "important"
document.querySelector('#my-arow').style.setProperty('display', 'block', 'important');
```
