### ISSUE TITLE
[question] Nav bar override control arrows

### ISSUE THREAD

**Issue by YungWalkie** [alvarotrigo/fullPage.js#4336]
I have navigation bar on left side of the site. <br>
The problem is, the nav bar is a bit large, so it's overrides contorl arrows.
The navigation bar, obviously, is outside the #fullpage id
What can I do, to make control arrows change pos in base how the nav bar large is?

**Comment by YungWalkie** [comment]
`new fullpage("#fullpage", {
});`<br>
`<body>
    <header>
        <nav>
            <ul>
                <li><a href="">Omniasoft on the top</a></li>
            </ul>
            <ul>
                <li><a href="">Academy</a></li>
                <li><a href="">Dev-X</a></li>
                <li><a href="">Cyber Privacy</a></li>
                <li><a href="">Officina Informatica</a></li>
                <li><a href="">Utopya</a></li>
                <li><a href="">B-Smart</a></li>
            </ul>
            <ul class="hiddens">
                <li><a href="">B-Smart</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div id="fullpage">
            <div class="section">
                <div class="container_inslide">
                    <span>Omniasoft Logo</span>
                </div>
            </div>
            <div class="section">
                <div class="slide" data-anchor="slide1">
                    <div class="container_inslide">
                        <span>Omniasoft Logo</span>
                    </div>
                </div>
                <div class="slide" data-anchor="slide2">2</div>
                <div class="slide" data-anchor="slide3">3</div>
            </div>
         </div>
       </main>`

**Comment by alvarotrigo** [comment]
Just modify its CSS styles to adjust it to your needs.

```css
#fp-nav{
   right: 70px;
}
``` 

Or if you prefer, change the arrow positions:

```css
.fp-controlArrow.fp-next {
    right: 59px;
}
```
