### ISSUE TITLE
fp-auto-height is not working

### ISSUE THREAD

**Issue by renepoell** [alvarotrigo/fullPage.js#4338]
Hello Alvaro,

If I replace the normal fullpage.js version (3.1.2) with its alpha version (3.1.2 Alpha), fp-auto-height works.
Can I use the alpha version or do I have to expect other errors then?

Thanks, R

**Comment by alvarotrigo** [comment]
I have no idea what is the alpha version :)

**Comment by alvarotrigo** [comment]
Oh, perhaps you are talking about [this one](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js)?

You can expect errors.
That's not a stable version (that's why it's not on the master branch :) ). 

Version 4 will soon be released and has been completely re-written.

**Comment by alvarotrigo** [comment]
What problem are we talking about?
I can see `fp-auto-height` feature working as expected on this demo:
https://codepen.io/alvarotrigo/pen/BKjRYm

**Comment by renepoell** [comment]
I had not included the CSS file (correctly). Your alpha version seems to
work without CSS, the normal version doesn't.
Case closed.

Please excuse the annoyance!
And many thanks for the prompt feedback! You are awesome!

Best, René


Am Do., 24. März 2022 um 16:34 Uhr schrieb Álvaro ***@***.***

**Comment by alvarotrigo** [comment]
No problem! ;) 
Glad you managed to solve it!
