### ISSUE TITLE
How to add something before dots

### ISSUE THREAD

**Issue by mralperem** [alvarotrigo/fullPage.js#4339]
Hello i would like to add social media icons on top of the dots with same alligment like the one in the image. Could you tell me how can i do that?

![das](https://user-images.githubusercontent.com/29342713/160087521-6104a456-6670-45e2-b233-9ffb049f65a2.png)

**Comment by alvarotrigo** [comment]
Unfortunately, that's not something that fullPage.js provides out of the box.
You can probably attach some HTML dynamically using JS by pretending them to the `#fp-nav` element.

The other option is [creating your own custom navigation bullets](https://stackoverflow.com/a/36742906/1081396) by using fullPage.js methods such as `moveTo`.

If you don't know how to do that with JS I'd recommend you ask in StackOverflow for that specific issue or [get our consulting services package](https://alvarotrigo.gumroad.com/l/fullpageSupport) for 1-hour of premium support.
