### ISSUE TITLE
How to cancel navigational dots animation

### ISSUE THREAD

**Issue by mralperem** [alvarotrigo/fullPage.js#4340]
Hello how can i cancel the animation which accours when i hover one of the navigational dots. Like the picture the one i hover on gets smaller.

![Untitled](https://user-images.githubusercontent.com/29342713/160202967-10a50665-1c13-4600-a211-88fa7e549d21.png)

**Comment by alvarotrigo** [comment]
The navigation bullets provided by fullPage.js version 3 won't look like that.
Make sure to update to the latest version. Version 2 is no longer supported nor maintained.
<img width="57" alt="image" src="https://user-images.githubusercontent.com/1706326/160217839-b0b167a9-14d7-49b1-9a93-d57430c92f1f.png">

See the current navigation dots on the demo page:
https://alvarotrigo.com/fullPage/

Or any oof [the exampleshttps://github.com/alvarotrigo/fullPage.js/tree/master/examples]
