### ISSUE TITLE
Help! Suddenly the full page script stopped working on Webflow websites (both exported and hosted on Webflow itself!)

### ISSUE THREAD

**Issue by kevinbrenkman** [alvarotrigo/fullPage.js#4353]
Help! Suddenly the full page script stopped working on Webflow websites (both exported and hosted on Webflow itself!)
https://discourse.webflow.com/t/fullpage-js-has-stopped-working-on-webflow-sites/202256

Website its not working on for me: https://creative-belgium.webflow.io (doesn't have the key installed) 
Exported website hosted externally: https://www.creativebelgium.be/awards/index.html (key installed)

Problem on Chrome, Safari, IOS Safari, all browsers really. 😟 

My client would need to have this solved by today since the website is a ticket shop and they are missing out ticket sales right now.

**Comment by alvarotrigo** [comment]
I've answered on the Webflow topic:
https://discourse.webflow.com/t/fullpage-js-has-stopped-working-on-webflow-sites/202256

I paste below:

When using a CDN you should never use a link that automatically gets the latest version for it.
You want a CDN link for a specific version of the library. 

There might be breaking changes from version to version and this is one of those cases. 

You are using this CDN link:
https://unpkg.com/fullpage.js/dist/fullpage.min.js

Which gets then transformed into the latest version:
https://unpkg.com/fullpage.js@4.0.3/dist/fullpage.min.js

Instead, use the latest version of the major version 3 you were using when you created the page:
https://unpkg.com/fullpage.js@3.1.2/dist/fullpage.min.js

This way you'll avoid issues when there are breaking changes.
If you want to update to fullPage.js 4 you'll need to first read the migration guidelines in case any of these affect you:
https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4

And get a new license (as the previous one won't be valid for version 4)
https://alvarotrigo.com/fullPage/pricing/

I hope this clarifies it for you! ;)
