### ISSUE TITLE
Last update broke horizontal scroll

### ISSUE THREAD

**Issue by MickaelNeves** [alvarotrigo/fullPage.js#4355]
I'm getting styles from https://unpkg.com/fullpage.js@4.0.2/dist/fullpage.min.css and suddenly these classes
```
.fp-section.fp-table,
 .fp-slide.fp-table {
     display: table;
     table-layout: fixed;
     width: 100%
 }

 .fp-tableCell {
     display: table-cell;
     vertical-align: middle;
     width: 100%;
     height: 100%
 }
```
disappeared, making layouts not center, breaking the horizontal behavior

**Comment by MickaelNeves** [comment]
Ah nevermind, I'm using the fullPage 3.1.2 extensions .js, should be getting the same css version file, and it should work

**Comment by alvarotrigo** [comment]
To upgrade see the migration guide: 
https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4
