### ISSUE TITLE
Problem with registration code

### ISSUE THREAD

**Issue by davidnieto** [alvarotrigo/fullPage.js#4356]
Hello,

I have purchased a fullpage.js license, and a extension, scrollOverflowReset. I have activated the license for the website that I am developing, but when adding and uploading it I get a red alert message that it is not active and I cannot activate it.

You can see it on this page, everything is in the source code. The scrollOverflowResetKey license is commented out so that the error does not appear.

http://www.eventem.es/

Is there something I'm doing wrong?

**Comment by alvarotrigo** [comment]
Are you using fullpage v3 or fullpage v4?

**Comment by davidnieto** [comment]
These are mi js files:

http://www.eventem.es/themes/eventem/assets/assets/js/fullpage.extensions.min.js
http://www.eventem.es/themes/eventem/assets/assets/js/fullpage.scrollOverflowReset.min.js
http://www.eventem.es/themes/eventem/assets/assets/js/scrolloverflow.min.js

**Comment by davidnieto** [comment]
Thanks! I tried to use the last version of fullpage.extensions.min.js and removeI scrolloverflow.min and I received this errors:

Uncaught TypeError: Cannot set properties of undefined (setting 'fullpage')
    at fullpage.extensions.min.js:11:60198
    at fullpage.extensions.min.js:11:60386
    at fullpage.extensions.min.js:11:199
    at fullpage.extensions.min.js:11:203

And this one:

Uncaught TypeError: $(...).fullpage is not a function
    at HTMLDocument.<anonymous> ((index):1115:22)
    at e (jquery-3.6.0.min.js:2:30038)
    at t (jquery-3.6.0.min.js:2:30340)

I tried to call fullpage in another ways, and received the same error

**Comment by alvarotrigo** [comment]
Sorry about that.

What version are you using? 
4.0.3?

**Comment by davidnieto** [comment]
This one: 4.0.0

http://www.eventem.es/themes/eventem/assets/assets/js/fullpage.extensions.min.js

**Comment by davidnieto** [comment]
I copied the code of this page, to reproduce everything in the same way:

https://alvarotrigo.com/fullPage/extensions/scrolloverflow-reset.html

And i get a message of "Unregistered extension". I use this name to register: eventem.es

¿What could be the problem?

**Comment by alvarotrigo** [comment]
> I copied the code of this page, to reproduce everything in the same way:

The demo page is still using version 3. 
So there are a few changes.

Can you contact us through the [contact form](https://alvarotrigo.com/contact/) so we can keep the discussion there? 
That's what we use to provide support for extensions.

Then I'll be able to take a look at your page and help you out.

**Comment by davidnieto** [comment]
OK! I send a message. Thank you!
