### ISSUE TITLE
Can´t activate the Extentions

### ISSUE THREAD

**Issue by hoennscheidt** [alvarotrigo/fullPage.js#4358]
I buy main plugin and extensions today, want to activate it even I need to buy it twice because don´t have a local host and it just say ops, even the count says 1 activation left.

And I don´t know which version I have, buy them 1 hour ago

**Comment by alvarotrigo** [comment]
I believe we are dealing with your case through the Elementor support?
If that's not the case, please feel free to open a ticket by using the [contact form](https://alvarotrigo.com/contact/).

**Comment by alvarotrigo** [comment]
Contact us there and we'll for sure help you out :)
Thanks for the patience! We are having a couple of issues with the transition to this new major version 4.
