### ISSUE TITLE
iPhone SE iOS 13: won't swipe between pages

### ISSUE THREAD

**Issue by rubymused** [alvarotrigo/fullPage.js#4363]
### Description
Fullpage.js is working great on a new site except on iPhone SE 2020 with iOS 13. It moves from page to page using anchors and link, but swipe does not move the page at all.

### Link to isolated reproduction with no external CSS / JS
https://www.cmgsite.com/

### Steps to reproduce it
1. Load the URL on iPhone SE 2020, iOS 15 (I'm using Browserstack)
2. Attempt to swipe

### Versions 
iPhone SE 2020 iOS 15

**Comment by alvarotrigo** [comment]
You [seem to be using verison 3](https://4hj1r48qig3mfn982o8bfrzr-wpengine.netdna-ssl.com/wp-content/themes/cmg/assets/js/fullpage.min.js?ver=3.1.2) of fullPage.js.

Version 3 is no longer maintained. 

You can install the latest version 4.0.5 and see how it goes.
Make sure to first read the [migration guide](https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4) in case the breaking changes affect your site. 

You might have to get a new license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> or new extensions if you were using any before.

**Comment by rubymused** [comment]
Thanks for the spectacularly fast reply.

I purchased the license on Feb 28, but I did not install the code -- apparently the person who did used an old version.

I've updated the code but of course it's complaining about the license key. How can I obtain a new license key? I cannot pay for it again.

**Comment by rubymused** [comment]
So much for the fast reply, eh? I'd settle for support for the product I purchased, for just this one project, though the upgrade is obviously preferable (and fair!). Usually software support is not terminated abruptly the day the new version is released.

**Comment by alvarotrigo** [comment]
Yeah, support is provided for questions of usage for version 3.
But the code won't be maintained/updated anymore.

Regarding the license issue, can you use the [contact form](https://alvarotrigo.com/contact/) to let us know about that?
We'll fix that there.

If you purchased fullPage.js v3 a weeks/month before the new release we can provide you the free update.

> I'm also a little confused as to how I ended up with an old license key for a newly purchased product.

The new version 4 was released on April 12. Any purchase before that was using version 3.

**Comment by alvarotrigo** [comment]
In any case, you can try out version 4  to see if it fixes the issue for you.
Otherwise, the update might not be so helpful for you yet?

**Comment by alvarotrigo** [comment]
Was the issue fixed?
Can I close this?

**Comment by rubymused** [comment]
It's not fixed, unfortunately. I'm going to put together a pared down test case, just slow in making that happen. Please keep it open for another week if you don't mind.

On May 9, 2022, at 8:50 AM, Álvaro ***@***.***> wrote:


Was the issue fixed?
Can I close this?

**Comment by alvarotrigo** [comment]
> Please keep it open for another week if you don't mind.

Any news on this @rubymused ?

**Comment by rubymused** [comment]
Unfortunately the issue persists. 

I thought maybe I'd use your examples page as the minimal test case, but it works there:
https://alvarotrigo.com/fullPage/examples/navigationV.html#firstPage

So I need to figure out what we're doing differently. Our only options are keyboardScrolling: true, and we're using onLeave and afterLoad to trigger various actions like start/stop video play.

**Comment by alvarotrigo** [comment]
Your page (cmgsite .com) still using fullPage.js version 3.
And the examples on fullPage.js site haven't been updated yet to version 4. 

Can you provide a link to an isolated reproduction using fullPage.js version 4?
If not, let me know and I'll close the issue until further notice.

**Comment by rubymused** [comment]
Here is the development site, which is now using fullpage.js V4, and demonstrates the problem: https://cmgsitedev.wpengine.com/

However, I'm struggling to come up with a minimal test case. It works fine in the test I created for a separate issue (http://dev.rubymuse.com/cmg/). For that I removed slick slider, but I also removed a lot of other code so it's not clear that slick slider plays a role.

**Comment by alvarotrigo** [comment]
Let me know whenever you are able to reproduce it in an isolated environment.

**Comment by rubymused** [comment]
It's probably time to close this. I think it's safe to say it's either not a fullpage.js issue, or it's a very specific interplay of elements that I just haven't hit on yet. I'll open a new issue if/when I do. Thanks for your help and patience.

**Comment by alvarotrigo** [comment]
Ok!
