### ISSUE TITLE
Scroll Horizontally Extension does not work

### ISSUE THREAD

**Issue by kzyz** [alvarotrigo/fullPage.js#4364]
### Description
I have enabled the scroll horizontally option.
But it does not work with an error.

### Error Message
fullpage.extensions.min.js:11 Uncaught TypeError: t is not a function
    at uo (fullpage.extensions.min.js:11:36848)
    at HTMLDocument.Zo (fullpage.extensions.min.js:11:42786)

### Versions 
4.0.5

**Comment by alvarotrigo** [comment]
Can you send us an email through the [contact form](https://alvarotrigo.com/contact/) and send the URL where you are having the issue?

Notice you'll have to acquire the extension for v4 as well.

Thanks.

**Comment by kzyz** [comment]
I made it on the sample page.
Please check it.
I think it is a bug.

[Sample Page](https://test.gluum.com/test.html)

**Comment by kzyz** [comment]
Oh sorry!
I use extension for v3!

**Comment by alvarotrigo** [comment]
So, is the problem fixed now?
Are you going to use version 3  or 4? 
Do you have the right extension for your version?

**Comment by kzyz** [comment]
The problem has been resolved.
Version 4 is used.
I got the download page updated so I could download the extension for version 4!
Thanks!

**Comment by alvarotrigo** [comment]
Awesome to hear! 👍
