### ISSUE TITLE
Error with Slider Revolution plugin

### ISSUE THREAD

**Issue by Dante130585** [alvarotrigo/fullPage.js#4365]
Greetings, I purchased the FullPage for Elementor plugin and I have a problem, they do not reproduce the animations of the slider. Could you have any solution?

Thank you!

**Comment by alvarotrigo** [comment]
For questions regarding the official plugin for Elementor, use the [contact form](https://alvarotrigo.com/contact/) please.
Here we only treat issues regarding the JavaScript component.
