### ISSUE TITLE
Trouble with fullpage_api and fullpage.extensions.min.js and fullpage.min.js v4.0.5

### ISSUE THREAD

**Issue by Cosirax** [alvarotrigo/fullPage.js#4366]
Thanks for this awesome project! I've developed a Webpage the last days an now I need the interlockedSlides extension. Therefore I switched from fullpage.min.js (v4.0.5) to fullpage.extensions.min.js (v4.0.5).

What i've discovered:

1. fullpage_api.getActiveSlide() is now working in fullpage.extensions.min.js (v4.0.5) before in fullpage.min.js (v4.0.5) wasn't working.
 
With fullpage.min.js (v4.0.5) running: fullpage_api.getActiveSlide() result:
![image](https://user-images.githubusercontent.com/35615340/163885597-e5eb371e-57ba-409e-abad-26d86aa4125e.png)
running fullpage_api.getActiveSlide() with fullpage.extensions.min.js is working as expected. But i've took advantage during my development on an workaround using fullpage_api.getActiveSection().activeSlide but thats not working anymore because the slides are no longer part of the getActiveSection function.

2. fullpage_api.getActiveSection().slides is no longer working with the extensions file as mentioned above
3. With the extensions file the beforeLeave function is not fired? I need this, please :D

I hope that my explaination was precise enough. If not I can get closer.

Thanks !

**Comment by alvarotrigo** [comment]
Thanks for reporting it! Fixed on the dev branch!

**Comment by alvarotrigo** [comment]
Fixed in 4.0.6.
