### ISSUE TITLE
Move to first slide on origin when change section

### ISSUE THREAD

**Issue by fromcouch** [alvarotrigo/fullPage.js#4370]
### Description
Hi, 

I have a complex development with onLeave and onSlideLeave, etc but basically my client wants that every time goes up or down to previous/next section, the previous/next section resets to slide 0.

### Link to isolated reproduction with no external CSS / JS
[Here](https://alvarotrigo.com/fullPage/examples/callbacks.html)

### Steps to reproduce it
1. Navigate to second section.
2. Move right to slide 2
3. open console
4. write `fullpage_api.moveSectionUp();` 
5. Navigate again with scroll or keyboard to Section 2
6. Shows Slide 2 instead of first slide

### Versions 
All

Thanks for grat plugin Alvaro

**Comment by alvarotrigo** [comment]
This can be done with the `resetSliders` option that requires a paid extension.
Here's [a demo](https://alvarotrigo.com/fullPage/extensions/reset-sliders.html).
