### ISSUE TITLE
"Made with fullpage" is showing on the published site?

### ISSUE THREAD

**Issue by eldvatn** [alvarotrigo/fullPage.js#4371]
### Description

Made with fullpage brand is showing on our site. The license key is installed/pasted in the code per rewuirements

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

Not sure if I should put the code ( and license file ) into fiddle. 

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

using this package.
https://unpkg.com/fullpage.js/dist/fullpage.min.js

![image](https://user-images.githubusercontent.com/104145054/164459715-dc55ddd2-4993-4209-9474-5e538a1cd135.png)

**Comment by alvarotrigo** [comment]
You can use the ‘credits’ option to disable it.

**Comment by eldvatn** [comment]
Ok, thankyou Alvaro. I will try the credits option.  Appreciate the quick feedback
