### ISSUE TITLE
vue fullpage scroll issue

### ISSUE THREAD

**Issue by candijun** [alvarotrigo/fullPage.js#4372]
### Description
It is not scrolling over smoothly, when it turns to next page when I scroll it looks starting from first page.

but I found if I remove anchors setting, then it works fine.

### Versions 
chrome latest version, vue 2.6.11

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction of the issue in codesandbox? 
Thanks!

**Comment by candijun** [comment]
> Can you provide an isolated reproduction of the issue in codesandbox? Thanks!

It was my layout setting problem. It solved ! Thank you for spending your time!

**Comment by alvarotrigo** [comment]
No problem! Glad you managed to make it work!
