### ISSUE TITLE
We are not getting section offset top position when menu click in mobile devices.

### ISSUE THREAD

**Issue by dropways** [alvarotrigo/fullPage.js#4374]
**Here is the demo link**
https://codepen.io/ankithingarajiya/full/yLprOoX

Check the issue step:
First click on the contact menu then click to service menu the service menu section is not display top of the position.

kindly check and do needful to resolve this issue

Thank you in advance.

**Comment by alvarotrigo** [comment]
Check out the option `bigSectionsDestination`.
Use `bigSectionsDestination: 'top'` if you need to scroll to the top when clicking on the menu.
