### ISSUE TITLE
Scroll events not working since update

### ISSUE THREAD

**Issue by dadameck** [alvarotrigo/fullPage.js#4375]
### Description
We have just upgraded to the latest version (4.0.6) of FullPage.js and are having an issue with JQuery scroll events. We have animations set to trigger once the text is in the browser viewport, and this gets checked on scroll events. 

#### The FAQ says to set scrollBar to true, but this did not solve our issue.

The animations work on other events such as resize and click. We also cannot log to the console on scroll events either. The codepen link shows other events working, but scroll will only work once the initialization of fullPage is removed the font size is large enough for a scroll bar to appear. 

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/pscdom/pen/LYevbEr

**Comment by alvarotrigo** [comment]
Can you try using 'fitToSection: false'? 

Or instead of listening to the scroll even in the window object, use the body instead:

document.body.onscroll

**Comment by dadameck** [comment]
Using document.body.onscroll did not solve the issue.

Adding 'fitToSection: false' got window.onscroll to work, but created another issue. 

With 'fitToSection: false', it makes it impossible to control which section you scroll to while using a touch screen. With touch controls, a swipe in any direction will cause a scroll down to the next section, and then will cause it to go back up once you hit the bottom. 

So it is impossible to scroll down to the 2nd section, then back up to the 1st. It will send you down to the 3rd. Even if you swipe sideways (which should do nothing since we do not have slides) it will automatically scroll you down. 

This has been recreated in the original codepen link. (If using a device without a touchscreen, you will need to either already have dev tools open when you click the link, or refresh after you open dev tools for codepen to correctly recognize touch scrolling)

**Comment by alvarotrigo** [comment]
> With 'fitToSection: false', it makes it impossible to control which section you scroll to while using a touch screen. With touch controls, a swipe in any direction will cause a scroll down to the next section, and then will cause it to go back up once you hit the bottom.

Yeap, that seems like a bug!
Opened a new issue for it [here](https://github.com/alvarotrigo/fullPage.js/issues/4376).

> Using document.body.onscroll did not solve the issue.

Not quite sure why the inline `onscroll` attribute doesn't work for the `body`, perhaps due to it being 100% height. 
But applying the event using the event listener seems to do the trick:

```js
document.body.addEventListener('scroll', onScroll);

function onScroll() {
  console.log("Scrolling");
}
```
Reproduction here:
https://codepen.io/alvarotrigo/pen/abExqdE

**Comment by denytbsmartjen** [comment]
just checking on this, https://codepen.io/alvarotrigo/pen/abExqdE

but the console.log not printing "scrolling" and try add effect not working while scrolling to make sure.

is there anything i miss ?

**Comment by alvarotrigo** [comment]
Just for clarification. This issue doesn't take place anymore on the latest fullPage.js versions.
