### ISSUE TITLE
TouchScreen swipe with fitToSection:false & scrollBar:true - always scrolls down

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#4376]
This issue has been mentioned in https://github.com/alvarotrigo/fullPage.js/issues/4375:

> With 'fitToSection: false', it makes it impossible to control which section you scroll to while using a touch screen. With touch controls, a swipe in any direction will cause a scroll down to the next section, and then will cause it to go back up once you hit the bottom.
> So it is impossible to scroll down to the 2nd section, then back up to the 1st. It will send you down to the 3rd. Even if you swipe sideways (which should do nothing since we do not have slides) it will automatically scroll you down.

And can be reproduced here using Chrome Dev Tools on touch mode:
https://codepen.io/alvarotrigo/pen/JjMVpdp

**Comment by dadameck** [comment]
I have found that this will also happen sometimes without the 'fitToSection' option set to false. The direction it will scroll seems to depend on if you start your swipe towards the top or bottom of the screen. But with fitToSection set to false, where you start your swipe makes no difference.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 4.0.7! 👍

**Comment by alvarotrigo** [comment]
Fixed in 4.0.7 🎉
