### ISSUE TITLE
How to prevent switching screens in scroll area?

### ISSUE THREAD

**Issue by zd20041** [alvarotrigo/fullPage.js#4377]
When there is a scrolling area in a page, scrolling will switch screens. Is there any way to stop it from switching screens in that scrolling area?
In the old version I used $.fn.fullpage.setAllowScrolling() to solve it, but it doesn't work in the new version

**Comment by zd20041** [comment]
Using $.fn.fullpage.setAllowScrolling(); in the latest version makes the scrolling area non-scrollable

**Comment by alvarotrigo** [comment]
You can use the option `normalScrollElements`.
You can read more about it on the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js).

`setAllowScrolling(false)` basically disables the fullPage.js sliding behavior when using the mousewheel/trackpad/touch.
