### ISSUE TITLE
Free scroll horizontal on section.

### ISSUE THREAD

**Issue by elsalvador34** [alvarotrigo/fullPage.js#4378]
### Link to isolated reproduction with no external CSS / JS
( https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html )  

When mouse scroll down the div comes section 2. We want on this div when user scroll mouse down the overflow x hidden content comes from free scroll mouse down and the design comes from right to left and when it finished the div goes section 3. İn section 3 we want the same code like section 1. And when it comes section 4 we want free scroll mouse overflow - x hidden design comes right to left.

is it posible.

**Comment by alvarotrigo** [comment]
Unfortunately that's not possible right now, but we will consider it! 👍 
You can keep the conversation on this issue treating the same topic: https://github.com/alvarotrigo/fullPage.js/issues/3360
