### ISSUE TITLE
"Disable scrolling with mouse" not working

### ISSUE THREAD

**Issue by brianruff** [alvarotrigo/fullPage.js#4381]
### Description
I'm unable to completely turn off mouse scrolling in Fullpage:

https://locomojo.com/brian/#
]
I would like to COMPLETELY REMOVE the page up / page down
function via scrolling. People should only be able to see the other
screens by clicking on a button. The example code I got from the docs website
doesn't appear to be working: 

MY CODE:

```
<script type="text/javascript">
  | var myFullpage = new fullpage('#fullpage', {
  | autoScrolling:true,
  | scrollVertically:false,
  |  
  | /*
  | Disable scrolling with mouse:
  | */
  |  
  | normalScrollElements: 'body',
  | afterResponsive: function(isResponsive){
  |  
  | }
  | });
  | </script>
```

### Link to isolated reproduction with no external CSS / JS

https://locomojo.com/brian/

### Steps to reproduce it
1. Open link
2. Scroll mouse wheel down a page, which should be disabled
3. Page scrolling is still happening. 

### Versions 
fullPage 3.0.4 - Extensions 0.1.7

**Comment by alvarotrigo** [comment]
You can not apply `normalScrollElements` to the `body` element.

Here's an example you can find in the docs:
https://codepen.io/alvarotrigo/pen/EjeNdq
