### ISSUE TITLE
Hello, the navigation menu for sections on the same page does not work for me. It detects it in my webflow, but not in the web.

### ISSUE THREAD

**Issue by MARBLEGAMES** [alvarotrigo/fullPage.js#4382]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by MARBLEGAMES** [comment]
I do not have the complete code since my version of webflow does not allow it, the problem is that the navigation menu with scrollBar: false does not work for me,
but if I change it to true it works but the scroll effect stops working.

**Comment by alvarotrigo** [comment]
We'll need an isolated reproduction to check what's going on.
I'm not able to reproduce the issue on my side. 

You can use this file to reproduce the issue:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollBar.html

Then port the code to jsfiddle or codepen.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided.
