### ISSUE TITLE
Extensions causing TypeError

### ISSUE THREAD

**Issue by lindsaymasten** [alvarotrigo/fullPage.js#4383]
### Description
Console error when running Fullpage.js v3.1.2 extensions. Reads: 
`Uncaught TypeError: b.normalScrollElements.split is not a function`
`at HTMLDocument.xe (fullpage.extensions.min.js:8:19532)`
Extensions brought in via cdn. No conflicts/other plugins in use.

<img width="934" alt="Screen Shot 2022-04-27 at 11 29 37 PM" src="https://user-images.githubusercontent.com/6201389/165691003-9cc75a13-66df-4b65-a8f4-52039a048d1e.png">

### Link to isolated reproduction with no external CSS / JS
Installing fullpage.js on Codepen et al is onerous in this case. Please check the line in the file referenced in the console error.

### Steps to reproduce it
1. Have extensions installed

### Versions 
Caught while using Chrome 99 Developer Tools on macOS Big Sur 11.6.5

**Comment by alvarotrigo** [comment]
I can't reproduce the issue on my side.
The normalScrollElements demo works as expected. 
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/normalScrollElements.html

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
In any case, fullPage.js version 3 is no longer receiving updates.
You can try to switch to version 4.

It seems to work fine too:
https://codepen.io/alvarotrigo/pen/RmVazM
