### ISSUE TITLE
Problem with scrollOverflow

### ISSUE THREAD

**Issue by eribertocaria** [alvarotrigo/fullPage.js#4384]
### Description

Hello,
I have a problem with scrollOverflow. 
In the vertical mobile version, the content of some sections is longer than the screen. In this case the scroll is activated, but its use is uncontrollable. When scrolling down, it goes directly to the next section and when scrolling up, it doesn't go to the previous section.
Can you give me a hand?
Thanks.
Best regards 

### Link to isolated reproduction with no external CSS / JS

https://barracuda.pixelarte.com/

**Comment by alvarotrigo** [comment]
You are using fullPage.js version 3:
https://barracuda.pixelarte.com/wp-content/themes/wp-bootstrap-starter-child/assets/fullpage/src/fullpage.js?ver=1

You can try moving to version 4.
Read the migration guidelines here:
https://github.com/alvarotrigo/fullPage.js/wiki/Migration-from-fullPage-v3-to-fullPage-v4

Version 3 no longer receives updates. So, if there's any bug, we won't be able to fix it in any case.

Let me know if you have any issues with version 4.

**Comment by eribertocaria** [comment]
ok thanks!

**Comment by AnkushThakur63** [comment]
Hello, after updated to lastest version scroll stop working..

could you check this: https://luxrite-lighting.myshopify.com/pages/our-story
password: luxrite

**Comment by alvarotrigo** [comment]
@AnkushThakur63 can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

We don't check specific websites here. That's reserved for customers with the Business license.

**Comment by AnkushThakur63** [comment]
Its still not working for me, seems like the amount of content is too much....
Anyway, thanks will find some other way to fix this..

**Comment by alvarotrigo** [comment]
@AnkushThakur63 probably your issue was related to https://github.com/alvarotrigo/fullPage.js/issues/4391.
The issue has been fixed on the dev branch and will get merged on a new release soon! 

I'll close this issue for now.
