### ISSUE TITLE
Using fullpage.js to scroll a PDF embedded on a website, with inertia scroll

### ISSUE THREAD

**Issue by Falmenara** [alvarotrigo/fullPage.js#4385]
### Hi there, 

- I am trying to embed a PDF on a website, but keeping the text selectable (so not rendering it). 
- The pages of the PDF are like a presentation deck, for fitting on a screen. 
- And I'd like to scroll it, page by page. 
- I am using fullpage.js but the problem is that there's no inertia scroll on it. Or I could not find how to do it. 
- I want this scroll effect https://snap-scrolling.web.app/ (notice that it ends the inertia on a full page, not randomly at any random point of a page)
- And this is what I achieved: https://pdf-convert-6f84a.web.app/ but it's far from the previous one

### 

- I am trying this https://snap-scrolling.web.app/  but not rendered
- This is not rendered, and it has fulpage.js, but it's also awkward (if you scroll several pages, you'll see they don't load properly) and I can't make inertia scroll https://pdf-convert-6f84a.web.app/ 

Thanks!

**Comment by alvarotrigo** [comment]
> https://pdf-convert-6f84a.web.app/

This link is broken.
