### ISSUE TITLE
Video don't play

### ISSUE THREAD

**Issue by eribertocaria** [alvarotrigo/fullPage.js#4387]
### Description
In Firefox video don't play

### Link to isolated reproduction with no external CSS / JS
https://barracuda.pixelarte.com

**Comment by alvarotrigo** [comment]
See the docs regarding autoplay:
https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media

And the demo:
https://codepen.io/alvarotrigo/pen/pXEaaK

**Comment by eribertocaria** [comment]
I’m sorry but don’t work fine

**Comment by alvarotrigo** [comment]
It works perfectly on the provided codepen, so unless you provide us with an isolated reproduction we can only assume the issue is in your side and not in fullPage.js.
