### ISSUE TITLE
HTMLDivElement is not a constructor in Safari

### ISSUE THREAD

**Issue by derogit** [alvarotrigo/fullPage.js#4390]
Original codepen from docs: [https://codepen.io/alvarotrigo/pen/NxyPPp](https://codepen.io/alvarotrigo/pen/NxyPPp)

Not working in:
macOs Mojave 10.14.6
Safari  12.1.2 (14607.3.9)
but work fine in Chrome

Error: 
`TypeError: HTMLDivElement is not a constructor (evaluating 'new fullpage('#fullpage', {
  licenseKey: 'YOUR KEY HERE',
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'] })') 
 at https://cdpn.io/cpe/boomboom/pen.js?key=pen.js-fbde72af-da27-6906-1ea5-4f2aee92f54e:1
`

**Comment by alvarotrigo** [comment]
I can not reproduce the issue using Safari in Mac OS 10.15.7.

However I can see it by using Browserstack.com using Mojave and Safari 12.1.

I also noticed the main codepen.io website doesn't load in that same browser, so my guess is Codepen is no longer supporting Safari 12. (Current Safari version is 15).

Sounds like a non-fullpage issue.
A similar one was reported time ago [here](https://github.com/alvarotrigo/fullPage.js/issues/3397) and it wasn't a fullPage.js issue either.

**Comment by alvarotrigo** [comment]
Oh, I tried Safari 11 and it seems to load codpen correctly. So I'll assume this is a problem in browserstack.com.
I can reproduce the issue. 

I'll investigate further.

**Comment by alvarotrigo** [comment]
Fixed in 4.0.8!! 🎉
