### ISSUE TITLE
Problem with scrollOverflow

### ISSUE THREAD

**Issue by Oleksandr07** [alvarotrigo/fullPage.js#4391]
### Description
When the content in the first section does not fit and a scrollbar appears, it is not possible to scroll the page to the second section

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/Oleksandr07/pen/mdXEpZX

### Versions 
Browser - Chrome
operating system - Android
device - Xiaomi

**Comment by alvarotrigo** [comment]
I can not reproduce the issue on a real device on browserstack.com
Video here:

https://user-images.githubusercontent.com/1706326/167840127-c527eacb-4800-437b-8aa7-fb5cdd83bca4.mp4


What version of Xiamoi are you using?

**Comment by Oleksandr07** [comment]
> 

Moved this code to a real site, and you can check it on browserstack.com Redmi note 9
[http://mistery.biz.ua/ticket/fullpage/](url)

**Comment by alvarotrigo** [comment]
I was able to reproduce this. Thanks for reporting it!! 👍 

The issue has been fixed on the dev branch 4.0.8!

Until the branch gets merged you can get the latest fullpage.js file from here:
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

**Comment by Oleksandr07** [comment]
> I was able to reproduce this. Thanks for reporting it!! +1
> 
> The issue has been fixed on the dev branch 4.0.8!
> 
> Until the branch gets merged you can get the latest fullpage.js file from here: https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

Thank you for such a quick response

**Comment by alvarotrigo** [comment]
Fixed in 4.0.8!! 🎉
