### ISSUE TITLE
Unable to go to next section from scroll section

### ISSUE THREAD

**Issue by lgambier** [alvarotrigo/fullPage.js#4394]
### Description

I've different issues on specific screen size, when i am on a section who have scrollable content it's impossible to go to the next section. 
I've reproduced the bug on a simple project.

### Link to isolated reproduction with no external CSS / JS

https://codepen.io/lgmb10/full/mdXEqZE

with code : https://codepen.io/lgmb10/pen/mdXEqZE

### Steps to reproduce it
1. Open the first link and go to the inspector with Chrome
2. Set creen size to iPhone SE or iPhone XR
3. try to scroll to the second section

### Versions 
Iphone SE, iPhone XR.
This bug is not only on iphone SE/XR is for exemple.

**Comment by alvarotrigo** [comment]
4.0.8 has been released.
You can try it out. I'll close the issue but feel free to comment if you still having the issue even after the update.
