### ISSUE TITLE
Text disappears/reappears on entering section, mostly Safari

### ISSUE THREAD

**Issue by rubymused** [alvarotrigo/fullPage.js#4396]
### Description
The section contains a full-screen image, with text overlaid. The image has a zoom animation effect. When I navigate/scroll to the next section then back again, the text is initially visible but quickly disappears. It sometimes reappears in a couple seconds, though not in the pared down test case. If I remove the animation effect, the problem goes away. The problem seems to be always present in Safari. Since upgrading to fullpage.js V4 I'm also seeing it in Chrome on mobile, though not definitively because of the upgrade (I'm not sure).

### Link to isolated reproduction with no external CSS / JS
This is the most pared down I can manage so far: http://dev.rubymuse.com/cmg/
It's a WordPress site, but I've removed all extraneous non-WP js libraries and custom animation code.

### Steps to reproduce it
1. Load the site in Safari. Note the text "This should display continuously" at the bottom right.
2. Scroll from section 1 to section 2.
3. Scroll back to section 1.
4. The text disappears. It should remain visible continuously.
5. Scroll to section 2 again; note that just as you begin to scroll away from section 1, the text reappears. That's consistent behavior on the pared down test site, but it varies on different versions/installations of the site. This is the full site (on a development server), which shows similar behavior with variation/less consistency: http://cmgsitedev.wpengine.com.

### Versions 
Safari 15.4 on Mac OS Monterey (or Safari anywhere as far as I can tell)

**Comment by alvarotrigo** [comment]
That sounds more like a Safari bug.

Try applying `transform: translate3d(0,0,0);` on the `figcaption` that is having the issue.

![image](https://user-images.githubusercontent.com/1706326/169627899-393ff40b-3199-46c5-94ba-9cf4b0c01ef0.png)


I'll close the issue as this is a Safari issue and not a fullpage.js one .
