### ISSUE TITLE
Fullpage stops scrolling after holding for 1 or 2 seconds

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#4397]
Yes, Clicked somewhere else in the body. But, sometimes scroll is disabled and not able to scroll the page.

You can test with this link.
https://testing-343bd.web.app/

_Originally posted by @programmershailesh in https://github.com/alvarotrigo/fullPage.js/issues/4393#issuecomment-1134396889_

**Comment by programmershailesh** [comment]
@alvarotrigo 
One more issue found That is when you blur the input field will focus on another section of the page. Not the same where I click on input.

You can test with this link.
https://testing-343bd.web.app/

**Comment by alvarotrigo** [comment]
Good news!  I think I found the issue!
Can you try again using version 4.0.9 on the dev branch?
https://github.com/alvarotrigo/fullPage.js/blob/dev/dist/fullpage.js

**Comment by programmershailesh** [comment]
- Stop scroll issue is solved I think.

- Another issue found. When you leave the focus from textbox section does not appear correctly.
It means let's consider that right now I'm on section5. When I leave the foucs from input will show section 4 not the current section( section 5 ).

- After foucs out from textbox. I can see Half section the screen.

You can test those issue on below link.
https://testing-343bd.web.app/

**Comment by alvarotrigo** [comment]
Can you open a new issue for each of those bugs? Thanks.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.9! 🥳
