### ISSUE TITLE
Enable scrollbar cause no scroll transition when scrolling back

### ISSUE THREAD

**Issue by meisken** [alvarotrigo/fullPage.js#4398]
In 0.1.25,  this bug happens when I scroll back and the scrollingSpeed is above 5000.  It also barely happens when the scrollingSpeed is below 5000. 

https://user-images.githubusercontent.com/38470704/169698998-cf51bc55-b7cc-4471-9bc7-93ee0448a26f.mp4

Reproduction code: https://codesandbox.io/s/react-fullpage-js-example-forked-ylxyp2?file=/src/index.js

The reproduction steps:
1. scroll down
2. scroll back

**Comment by alvarotrigo** [comment]
Reproduction in vanilla fullPage.js:
https://codepen.io/alvarotrigo/pen/yLvzqRq

**Comment by alvarotrigo** [comment]
The issue should be fixed now in version 4.0.9.

I've also updated the dev branch in react-fullpage.js. 
So you can try it by installing it:

```sh
npm install "https://github.com/alvarotrigo/react-fullpage.git#dev" --save
```

**Comment by meisken** [comment]
Indeed, the issue is fixed in the new version.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.9! 🥳
