### ISSUE TITLE
 n.fn.fullpage.getFullpageData is not a function using the continuousHorizontal extension

### ISSUE THREAD

**Issue by claralayti** [alvarotrigo/fullPage.js#4402]
Currently getting this error on initialization, when using the continuousHorizontal Extension. 

_jQuery.Deferred exception: n.fn.fullpage.getFullpageData is not a function TypeError: n.fn.fullpage.getFullpageData is not a function
    at new window.fp_continuousHorizontalExtension_ 

This issue appears initializing either in jquery or vanilla js.

After isolating everything I can't seem to find a solution, wondering if it has to do with the versions? We've created a pen with the isolated reprordction but as its a paid extension, we would like to send it to you privately.

Versions:
Continuous Horizontal Scrolling Extension 0.0.4
fullPage 4.0.9 (using the [fullpage.extensions.min.js](https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/4.0.9/fullpage.extensions.min.js) file)

Thank you in advance! :-)
Clara

**Comment by alvarotrigo** [comment]
It sounds you like you  might be using a fullpage.js extension for fullPage.js version 2 or 3. 
And now you upgraded fullPage.js to version 4  (or used a CDN that always load the latest version)

You might have to purchase a new extension or keep using the old version of fullPage.js.

For further support regarding extensions please use the [contact form](https://alvarotrigo.com/contact/).
