### ISSUE TITLE
afterSlideLoad and onSlideLeave events don't work

### ISSUE THREAD

**Issue by plcdnl** [alvarotrigo/fullPage.js#4403]
### Description
I don't know if is it normal but fullpage.js never call the follow events.

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/plcdnl/pen/MWQGobW

### Versions 
OS: MacOS Monterey 12.3.1
Browser: Google Chrome 102.0.5005.61 (arm64)

**Comment by alvarotrigo** [comment]
No problem! :)
