### ISSUE TITLE
Aligning slide images to left or right

### ISSUE THREAD

**Issue by farhanmasud** [alvarotrigo/fullPage.js#4404]
I have some vertical images that I need to use with the fullpage.js slides. How can I need to align some of them left and some of them to the right. Currently all of them are in the middle. How do I achieve this?

![Screenshot from 2022-06-01 19-24-55](https://user-images.githubusercontent.com/43474661/171415326-b0785f2e-a339-416c-8312-4a990687c3c2.png)

Interestingly, the `img` element shows the it's area with the whitespace so I can't use the margin left right as auto to move it. Tried messing with the `flex` property with `fp-slide` and `fp-table` classes but now luck.

![Screenshot from 2022-06-01 19-27-27](https://user-images.githubusercontent.com/43474661/171416059-0374cb59-0df0-4c19-83a4-5fda5e07b19f.png)

**Comment by alvarotrigo** [comment]
This is CSS issue and not a fullPage.js one.
fullPage.js uses flex for sections and slides:


```css
.fp-table{
    display: flex;
    flex-direction: column;
    justify-content: center;
    width: 100%;
}
``` 

I'd recommend you to ask in other places such as StackOverflow about how to achieve what you want.
