### ISSUE TITLE
How can i wait that gsap finish the animation on beforeLeave and then go to nextSlide ? 

### ISSUE THREAD

**Issue by plcdnl** [alvarotrigo/fullPage.js#4405]
I see that is possible to interrupt the animation if i set return false but i'd like to complete the animation and on return true pass to the next step. Is it possible? 

Thank you in advance

**Comment by alvarotrigo** [comment]
I've created this other demo using GSAP for you :)

https://codepen.io/alvarotrigo/pen/dydeVWY
