### ISSUE TITLE
Localhost dummy activation

### ISSUE THREAD

**Issue by ecreatures** [alvarotrigo/fullPage.js#4406]
I bought a single Commercial Professional License for fullpage js and during the development process we did use the licence key on LOCALHOST in order to free the console from the numerous fullpage message inside. Now we deployed our app on its website and fullpage js behaviour is like we never had any licence. Howcome does localhot use (I guess mots of us are using this for dev purpose) fire the activation of the license?
Is there a way to have our production solution working with the license we paid for as we nevers deployed it before on a real domain (just localhost).
Thanks for your answer

**Comment by alvarotrigo** [comment]
fullPage.js license is fully independent of your domain name.
If you are having a console error it will be for another reason.

Perhaps you purchased fullPage.js version 3 and now you are using fullPage.js version 4?

Mind sharing a link to your page?

**Comment by ecreatures** [comment]
Hi 

Thanks for your email.

Here's the link
https://postop-story.app/ <https://postop-story.app/>

please log in with your phone and you'll see once loggued that the console is asking for the license key.
We have a valid licence key that we bought and we suppose that it have been activated while developing on localhost…

What should we do at this stage ? Buy another license?


Thanks

Michel

**Comment by alvarotrigo** [comment]
It seems it's a v3 vs v4 problem.
Use the [contact form](https://alvarotrigo.com/contact/) to keep the conversation there. Use the email used for the purchase in the contact form. Thanks.
