### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by fafamiggy** [alvarotrigo/fullPage.js#4407]
Hi, I'm new in web designing so I try to use WordPress, and elementor theme builder, and I watch a video from picnature that says I can use this framework using custom CSS plugins So it works but after a few days it starts having errors so I buy the license but even I add the license on custom code it didn't work, Can anyone help me? Because the license that I bought says only on GitHub I can get help. Sorry I am like a dumb I'm just started making a website.

![Screenshot 2022-06-03 223144](https://user-images.githubusercontent.com/104381207/171982893-c71a8052-9cdc-4ba8-aca1-f9096809f364.png)

![Screenshot 2022-06-03 223101](https://user-images.githubusercontent.com/104381207/171982803-17a62b2d-4b3c-4b70-9607-77d89a51aed7.png)

**Comment by fafamiggy** [comment]
Proof that I buy a license but I can't use it, Can anyone can help me?
![Screenshot 2022-06-03 223648](https://user-images.githubusercontent.com/104381207/171983219-f37e490a-472d-4706-9048-224ecd0fcfbd.png)

**Comment by fafamiggy** [comment]
![Screenshot 2022-06-03 223648](https://user-images.githubusercontent.com/104381207/171983315-16399c9c-0b5e-49ad-89c4-5d833b5f0fd4.png)
 
Proof that I buy a license but I can't use it, Someone can help me?

**Comment by fafamiggy** [comment]
Hi? Is someone can tell me what I need to do?

**Comment by alvarotrigo** [comment]
The license you got is for fullPgage.js version 4.
If you use any prior version (such as fulPgae.js version 3 or 2), then this license won't be compatible.

Make sure to update to the latest fullPage.js version 4.

**Comment by fafamiggy** [comment]
How to get version 4? and how can i use that on wordpress

**Comment by fafamiggy** [comment]
![3 04](https://user-images.githubusercontent.com/104381207/172184800-1fe0c5ec-695a-45b1-9b64-7b1d936ac730.png)
Seems like I had 3.04 version can you help how can I get this link with version 4?

**Comment by fafamiggy** [comment]
So what does it mean? that I can't still able to use even I change to version 4?

**Comment by fafamiggy** [comment]
Oh so the license I buy I can't even use

**Comment by fafamiggy** [comment]
I am integrating full-page js by my own for sure because I didn't purchase any plugins for fullpage js just license

**Comment by fafamiggy** [comment]
If you can see my first message I send a picture of what I did using custom code plugins I integrate all CDN and use some JS and css

**Comment by fafamiggy** [comment]
Is there a refund for what I buy and I will buy the one that extension for elementor?

**Comment by alvarotrigo** [comment]
> I am integrating full-page js by my own for sure because I didn't purchase any plugins for fullpage js just license

Then you can use version 4. You just need to use the correct CDN link for it.
For example:

```js
// JS file
https://unpkg.com/fullpage.js@4.0.9/dist/fullpage.min.js

//CSS file
https://unpkg.com/fullpage.js@4.0.9/dist/fullpage.min.css
```

> Is there a refund for what I buy and I will buy the one that extension for elementor?

Sure, purchase the [Elementor plugin](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and you'll be able to ask for a refund by using the [contact form](https://alvarotrigo.com/contact/).

**Comment by fafamiggy** [comment]
![Screenshot 2022-06-06 123912](https://user-images.githubusercontent.com/104381207/172225154-46673db1-b64d-43cb-9bf1-fa516461b9e2.png)

**Comment by fafamiggy** [comment]
I added on that page the licenceKey and still has an error on console that asking for licence and that license show on the top of my frontpage header

**Comment by alvarotrigo** [comment]
You are including fullPage.js multiple times.
You only need one. If you do not use paid extensions then remove the fullpage.extensions.min.js file.
If you do, remove fullpage.min.js.

I can not see your license key anywhere  in the code you posted.
Make sure to read the <a href="https://github.com/alvarotrigo/fullPage.js" target="_blank">fullpage.js documentation</a> regarding the "licenseKey" option and its usage.

**Comment by fafamiggy** [comment]
I just try 2 times adding the license key on the HTML not multiple times, The problem is why I keep removing it because it shows up on my website header the license which is not good.

**Comment by fafamiggy** [comment]
If buy the extension I need to do the same method as this? I really don't know how to do it

**Comment by alvarotrigo** [comment]
> If buy the extension I need to do the same method as this? I really don't know how to do it

For exentension read the docs regarding [the use of extensions](https://github.com/alvarotrigo/fullPage.js#use-extensions) as well as the manual "How to use it.html" that comes with your extension purchase.
