### ISSUE TITLE
ScrollOverflow not scrolling oversize elements

### ISSUE THREAD

**Issue by itsthex** [alvarotrigo/fullPage.js#4409]
Hello! 

I am having issues with oversized elements. I have a section that is roughly 300px bigger than the viewport height on a mobile device such as an iPhone XR (~800px).

Before I get in too deep, can someone kindly point me to reasons why a slide would not trigger internal scroll when bigger than the viewport? Being that I'm not coding the theme for this web store from the ground up, I can't pinpoint exactly what could be causing the issue. Would be very helpful to get some starting pointers.

Scrollbars: false, scrollOverflow: true, fp-auto-height on each.

Thank you!

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
> Would you be able to possibly give me some things to look at that could be causing interference?

Difficult to say. It can be so many things.

Make sure you are using the latest fullpage.js version 4 for both the CSS and the JS files.
It won't require the scrollOverflow.min.js file that version 3 required.
Check the elements overflowing are not absolute positioned elements. 

> Also, side question, do horizontal slides all have to be the same height?

Yeah. You can use scrollOverflow in them too, but same height with scrollable content.

**Comment by itsthex** [comment]
Understood. That's probably my issue then, uneven height elements in slides. I suppose I could match heights of elements via prior to launching fullpage. Hmm.

Thanks Alvaro!

**Comment by alvarotrigo** [comment]
> That's probably my issue then, uneven height elements in slides.

The content of the slides is independent of each other.
If one slide requires scrollbar it will only be added to that slide.

But without a reproduction, it's difficult to come to a conclusion. 
I'll close this issue for now.

Let me know if you need any further assistance.
