### ISSUE TITLE
Update from v3 to v4 gives licenceKey error but licence only purchased in April 2022

### ISSUE THREAD

**Issue by garylake** [alvarotrigo/fullPage.js#4410]
### Description
Update from v3 to v4 gives licenceKey error. Licence was purchased 3rd of April 2022 and I understand I get 12 months of updates to the latest major version?

### Link to isolated reproduction with no external CSS / JS
N/A, my production site https://www.garylake.co.uk is running v3 still and I'm reluctant to deploy with v4 and have the console errors showing.

### Steps to reproduce it
1. Update to V4 while running in localhost – get licenceKey error in console
2. Rollback to V3 `npm install fullpage.js@~3` and licenceKey console error goes away when running V3 again

### Versions 
N/A

**Comment by alvarotrigo** [comment]
You'll need to update the licenseKey option with the latest license key you got on your email for fullPage.js version 4.
Licenses are not compatible between v3 and v4.

**Comment by garylake** [comment]
I never received a licence for V4 via email... I assume I should have, if not, how can I remedy this?

**Comment by alvarotrigo** [comment]
Use the [contact form](https://alvarotrigo.com/contact/) and share with us the email you used for the purchase.

**Comment by garylake** [comment]
Done and thanks 👍🏻
