### ISSUE TITLE
My licenseKey does not take effect in "vue-fullpage.js": "0.1.7",

### ISSUE THREAD

**Issue by jacky-yanglei** [alvarotrigo/fullPage.js#4411]
http://across.land/ 
this is my website.
I configured like this
![image](https://user-images.githubusercontent.com/17645850/172608060-44fe3bbe-285c-4568-bc56-386e21f8c220.png)
I bought this
![image](https://user-images.githubusercontent.com/17645850/172608409-73e3ba53-c45e-4e8d-a98d-479c01184537.png)

**Comment by alvarotrigo** [comment]
You purchase fullPage.js version 4 and you got a license for v4.
But you are using fullPage.js version 3 on your page. 

Make sure to update the fullPage.js JS and the CSS files to the latest version.

**Comment by jacky-yanglei** [comment]
how to buy v3 ?

**Comment by alvarotrigo** [comment]
Why do you want to use v3?

**Comment by jacky-yanglei** [comment]
My project is based on vue2

**Comment by alvarotrigo** [comment]
Contact us here :
https://alvarotrigo.com/contact/
