### ISSUE TITLE
Question - Scrolloverflow:true scroll to the end of section / any point

### ISSUE THREAD

**Issue by dinonondi** [alvarotrigo/fullPage.js#4414]
Hello,

I'm using the fullpage v4, with the scroll overflow setting, and I was wondering if it's possible to have
 fullpage_api.moveTo(i); work to scroll within that section, so for example to add an anchor that leads to the end of that overflowing section instead of the beginning?
 
I tried to use data-anchor but that did not work.
 
Thank you!

**Comment by alvarotrigo** [comment]
That's not something that is provided by fullPage.js.
But you can use JavaScript functions to do so. It's basically a scrollable element, so you can fully control the scroll with JavaScript by using methods like `scrollTo`.

**Comment by dinonondi** [comment]
Thank you!

I updated my post with a codepen with a working example in case it can be useful for others.

**Comment by alvarotrigo** [comment]
Glad you managed to make it work.
Thanks for the codepen! ;)
