### ISSUE TITLE
On mobile, when i scroll up in a scrollable section, I can't reac

### ISSUE THREAD

**Issue by marconemariellone** [alvarotrigo/fullPage.js#4416]
Hi Alvaro, on mobile, when i scroll up in a scrollable section, I can't reach the top of this section but it scrolls at the previous section.

Thank you,

Marco

### Link to isolated reproduction with no external CSS / JS
I tried to isolate more possibile things but you can see the problem anyway.
https://codepen.io/marconemariellone/pen/LYQaWYX

### Steps to reproduce it
1. Scoll to second slide
2. Scroll inside the slide to the bottom
3. Try to reach the top of the second scrolling slide

### Versions 
Mobile

https://user-images.githubusercontent.com/70100399/174064809-46593985-3954-40dc-b650-4022a6f5bc7c.mov

**Comment by alvarotrigo** [comment]
Make sure to use the latest version 4.0.9

**Comment by alvarotrigo** [comment]
Ok. Now let's try to isolate your issue.
Can you please provide a codepen without any external files to fullPage.js and with only text on the sections?

There's so much going on in your codepen. We need to isolate the issue much more.

**Comment by alvarotrigo** [comment]
> I think that the script wasn't be able to calculate and set the right height for the right scrolling.

Yeah that seems like the issue.
A fix to this is calling `fullpage_api.reBuild` when the image has loaded. Usually third-party libraries provides callbacks for that.
