### ISSUE TITLE
beforeLeave is not triggered on scroll on page load

### ISSUE THREAD

**Issue by Oleksandr07** [alvarotrigo/fullPage.js#4418]
If you do not wait for the page to load completely and scroll to the next slide, the beforeLeave event does not work
https://codepen.io/Oleksandr07/pen/poaYqYL

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
The issue should now be solved on the dev branch version 4.0.10
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳
