### ISSUE TITLE
Fullpage.js white screen when clicking input on Android

### ISSUE THREAD

**Issue by Oleksandr07** [alvarotrigo/fullPage.js#4420]
On the phone, when you focus on the input field in the form, the page turns white. Form at the bottom of the page
Tested on Android

http://mistery.biz.ua/ticket/fullpage/

**Comment by alvarotrigo** [comment]
Can you update to 4.0.9 and see if it still takes place? 
Thanks.

**Comment by Oleksandr07** [comment]
Yes, updated

**Comment by alvarotrigo** [comment]
Thanks.

Can you try again using the dev branch files?
Version 4.0.10

https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

**Comment by Oleksandr07** [comment]
Updated, the problem is gone.
Thanks.

**Comment by alvarotrigo** [comment]
Glad it did! :)
I'll me merging this on the next release then!

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳
