### ISSUE TITLE
Autoplay of sliders an pause or stop on hover / click on next arrow

### ISSUE THREAD

**Issue by netzlounge** [alvarotrigo/fullPage.js#4421]
Hello,

is there a way of pausing or even stoping the slider, 
when the user hovers over the sliderimage oder clicks on the slider arrows?

thx
Alex

**Comment by alvarotrigo** [comment]
It all depends on how you've created your autoplay feature.

But I guess you can use the method `silentMoveTo` to force the scroll to the section/slide you want when the user does the action that you determine.
