### ISSUE TITLE
Numbers on body class fp-viewing are not consecutive

### ISSUE THREAD

**Issue by kevchcm** [alvarotrigo/fullPage.js#4423]
### Description
I have 2 issues on my site right now. Once the scroll past the 4th section, I can see that the class in the body `fp-viewing-4` resets back to `fp-viewing-0` and now I can't go back to the first slides. 
Same thing happen with other slides, the number jumps from 2 to 6 and then my scroll gets stuck and I don't have a way to go up or down, I can only reload the page.
I tried to reproduce this on codepen but it seems to work ok in there. I have a video with the issue.

https://user-images.githubusercontent.com/65916355/176785723-19501281-4e52-4c23-a7f4-28b9e519cdc3.mov

This is my js

```
let fullPageInstance = new fullpage('#fullpage', {
    licenseKey: 'XXXXX-XXXXX-XXXXX-XXXXX-XXXXX',
    css3: false,
    easingcss3: 'cubic-bezier(0.57, 0.54, 0.13, 0.99)',
    scrollingSpeed: 800,
});
```

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Versions
Fullpage.js version 4.0.9 
Chrome version 103

**Comment by alvarotrigo** [comment]
Can you add a link to an isolated reproduction we can check? 
Thanks.

**Comment by alvarotrigo** [comment]
I'll close it for now until an isolated reproduction is provided.
