### ISSUE TITLE
Fullpage.js white blink when clicking input on Android

### ISSUE THREAD

**Issue by VadimMaliiWork** [alvarotrigo/fullPage.js#4424]
On the phone, when you focus on the input field in the form, the window blinks white. Form at the bottom of the page( #slide10 )
Check on Android

https://leadgen.dstage.site/leadgen/

problem check here - https://leadgen.dstage.site/leadgen/#slide10

connected fullpage version 4.0.10

**Comment by alvarotrigo** [comment]
Sounds like its related with these issues:
https://github.com/alvarotrigo/fullPage.js/issues/4420
https://github.com/alvarotrigo/fullPage.js/issues/4393

The blink problem was mentioned in [this comment](https://github.com/alvarotrigo/fullPage.js/issues/4393#issuecomment-1133169955) and unfortunately, there's no solution for it.

I'll close this issue  as a duplicate.
