### ISSUE TITLE
Page jumps on touchpads (lenovo and mac) 

### ISSUE THREAD

**Issue by arnoldsimha** [alvarotrigo/fullPage.js#4426]
### Description

When you use the touchpad to scroll, a page jump happens.
Please see the example in the video attached

https://user-images.githubusercontent.com/815961/178481295-38ed63a9-a86b-4603-9e65-3dcb4ded8649.mp4

### Versions 
Browser: Chrome (latest version) and Safari
Device: Lenovo and Mac

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
> When you use the touchpad to scroll, a page jump happens.

Also, I'm a bit confused here.

Isn't that what fullPage.js is supposed to do?
Scroll down one section when using the touchpad to scroll?

**Comment by arnoldsimha** [comment]
> > When you use the touchpad to scroll, a page jump happens.
> 
> Also, I'm a bit confused here.
> 
> Isn't that what fullPage.js is supposed to do? Scroll down one section when using the touchpad to scroll?

Hi,
The problem is that it scrolls 2 slides when you do one scroll. This is the issue.
I'll try to organize a dev environment for you.

We want to buy the plugin for our website, but we need to understand why this issue is happening

**Comment by alvarotrigo** [comment]
> I'll try to organize a dev environment for you.

Can you reproduce it on the demo page?
http://alvarotrigo.com/fullPage/

> We want to buy the plugin for our website, but we need to understand why this issue is happening

So far I'd say its an issue with your trackpad speed. 
Did you try from another computer?
What version of fullPage.js are you using?

**Comment by arnoldsimha** [comment]
> > I'll try to organize a dev environment for you.
> 
> Can you reproduce it on the demo page? http://alvarotrigo.com/fullPage/
> 
> > We want to buy the plugin for our website, but we need to understand why this issue is happening
> 
> So far I'd say its an issue with your trackpad speed. Did you try from another computer? What version of fullPage.js are you using?

We are using the latest trial version and various laptops. the issue is with touchpad. the mouse scroll working well

**Comment by alvarotrigo** [comment]
> We are using the latest trial version and various laptops. the issue is with touchpad.

What version is that precisely?

**Comment by arnoldsimha** [comment]
> > We are using the latest trial version and various laptops. the issue is with touchpad.
> 
> What version is that precisely?

4.0.9

**Comment by alvarotrigo** [comment]
Can you reproduce your issue on the demo page?
http://alvarotrigo.com/fullPage/

**Comment by alvarotrigo** [comment]
I'll close this as it seems to have no further activity.
