### ISSUE TITLE
license key V3 implementation problem

### ISSUE THREAD

**Issue by RobertKRA** [alvarotrigo/fullPage.js#4427]
Tried to implement my license key in a project I did last year that is finally going live. Fullpage.js is implemented in the WP theme and the license key is "called for" in theme.min.js via:

```js
var myFullpage = new fullpage("#fullpage",{
    licenseKey: 'MY-CODE-IS-HERE',
    anchors: ["..."],
    scrollingSpeed: 900,
    (...)
})
```

Version of fullpage.js is still 3 and your support thankfully gave me a key for Version 3 as well. Double-checked "licenseKey" spelling and have no idea why it is not accepted and still shows the prompt that it requires a license in console.

Happy to provide you with more information if needed.

**Comment by alvarotrigo** [comment]
Your code looks good to me. 
You might be initialising fullPage.js in multiple places and doing it without a key in some.

Feel free to use the [contact form](https://alvarotrigo.com/contact/) and provide us with your URL so we can take a quick look for you.

**Comment by RobertKRA** [comment]
Support helped out, wrong key. Thank you.
