### ISSUE TITLE
fullPage.js can not be installed on WordPress

### ISSUE THREAD

**Issue by Ivanhoe-bg** [alvarotrigo/fullPage.js#4429]
### Link to isolated reproduction with no external CSS / JS
(https://maxxvape.mk/)

### Steps to reproduce it
1. Wodpress - Plugins - Add new 
2. Upload successfull 
3. The package could not be installed. No valid plugins were found.

### Versions 
Wordpress 6.0.1
Elementor 3.6.7

**Comment by meceware** [comment]
fullpage.js by itself as a library is not a WordPress plugin hence it's is the expected behavour that it cannot be installed WordPress directly. Please take a look at [FullPage for Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) or [FullPage for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) to get the WordPress plugins.
