### ISSUE TITLE
Issues with the versions - Oxygen builder

### ISSUE THREAD

**Issue by pvblaze** [alvarotrigo/fullPage.js#4433]
Hi,

I've just purchased your script and I seem to not be able to use the latest version of fullpage.js (4.x.x). I'm using oxygen builder and it seems that I can only use the 3.x.x version.

While using the 3.x.x version my websites CSS doesn't turn out as it should. The div elements aren't where they should be. But the scrolling works well. And that I get an error that I need to insert the license which I have but the error code is still visible. I've also tried you license inspector and it doesn't even register that I've added the fullpage.js script into the website.

While using the 4.x.x version the website looks as it should but there are issues like the scrolling feature doesn't work as it should. And the console seem to not be warning about a license.

Where do we go from here?

Best Regards

**Comment by alvarotrigo** [comment]
We don't provide any plugin for Oxygen and therefore we can't really provide you support there.

If you have any issues with fullPage.js version 4 you can reproduce in an isolated reproduction using  [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), then we'll be happy to help!

**Comment by alvarotrigo** [comment]
As a side note, we do provide plugins (and premium support) for the plugin for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) editors.
