### ISSUE TITLE
Making something like this with Fullpage js

### ISSUE THREAD

**Issue by alexeevamg** [alvarotrigo/fullPage.js#4434]
Hello, @alvarotrigo !
I want to repeat something like [this](https://www.youtube.com/watch?v=fawbvblRsZ8). Blocks changing when scroll and some blocks should be scrollable. I tried it [here](https://wonderussia-testing.webflow.io/home-copy). But can't understan how I can make overlap on previous section. I tried sticky, but it's didn't work with autoScrolling:true.  Maybe there is some other way to overlap the block with the previous one when scrolling? 

Animation which I want to repeat [here](https://www.youtube.com/watch?v=fawbvblRsZ8).

**Comment by alvarotrigo** [comment]
I don't think fullPage.js will be the best option for you.
Such animation is not provided out-of-the-box by fullPage.js, so unfortunately we can't help you much with that.
