### ISSUE TITLE
Question: auto-height + scrollOverflow

### ISSUE THREAD

**Issue by KinIcy** [alvarotrigo/fullPage.js#4435]
### Description
On the project I'm working, we have a footer as the last section of the full page.  The footer is responsive such that it has less height than the viewport on desktop and more than the viewport on mobile. 

As described in the documents, I used the `fp-auto-height` class in the footer section to make it not to use the full screen.  It works fine on desktop but when I switch to mobile the `scrollOverflow` won't work on the footer.

Using `fp-auto-height-responsive` gives the same result.

Is there another way to make those two options work together in my case?

### Link to isolated reproduction with no external CSS / JS
I don't have one right now.

### Steps to reproduce it
1. Setup a page with 2 sections, 1 normal, and one with `fp-auto-height-responsive` class
2. Second section (footer) should have enough content such that it overflows when on smaller viewports
3. Set `scrollOverflow: true`
4. Open the page on desktop
5. Scroll to the second section (footer). 
6. Footer uses the full screen instead of just the space enough to fit it.

### Versions 
Chrome on Windows

**Comment by alvarotrigo** [comment]
Oh hey, apparently I missed this question!

I've verified it and it is indeed a bug! 
Thanks a lot for reporting it! 👍 

I've fixed it on the dev branch and will be merging it into a new release in a few mins.

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳

**Comment by alvarotrigo** [comment]
Here's a working example:
https://codepen.io/alvarotrigo/pen/mdxLNVP
