### ISSUE TITLE
Parallax extension only in one section

### ISSUE THREAD

**Issue by legranddigital** [alvarotrigo/fullPage.js#4437]
Hi, I am using fullpage.JS with horizontalscrolling extention + Parallax extension.

I d like to use the parallax extension only in one specfic section, as it clams other section otherwise.

I tried             

parallax: 'sectionClass'

Without success;

How. can I do this ?

Many thanks

**Comment by alvarotrigo** [comment]
> I d like to use the parallax extension only in one specfic section, as it clams other section otherwise.

You can try  turning it on and off  on  the `afterLoad` callback by using  these methods:

```js
// enable parallax
fullpage_api.parallax.init();

// disable parallax
fullpage_api.parallax.destroy();
```

**Comment by alvarotrigo** [comment]
There's also another approach you can do.

If you use `parallaxOptions.property = 'translate`, then you can add the `fp-bg` element only in the section where you want to apply the parallax effect.

For example:


```html

<div id="fullpage">
  <div  class="section">Section 1</div>
  <div  class="section">
     <div class="fp-bg"></div>
     Section 2
   </div>
  <div  class="section">Section 3</div>
</div>

```  

Js
```js
new fullpage('#fullpage',  {
    parallax: true,
    parallaxOptions: {
        property: 'translate'
    }
});
```

**Comment by legranddigital** [comment]
Thank you for this, unfortunately,  it's not solving my issue.

Ineed it adds  this css transform: translate3d(-3292px, 0px, 0px); into my sctino conntaining horizontalscrolling. How can I avoid this ? ( This because in myy horizontal scrolling I use custoom css fr a FadIn Effect instead).

Or ---

WHen I Use fadeIN EXtension, can I apply it only to the section containing Horizontalscrolling ? And Keeping parallax to my other section. ?
Many thanks

**Comment by alvarotrigo** [comment]
> Ineed it adds this css transform: translate3d(-3292px, 0px, 0px); into my sctino conntaining horizontalscrolling. How can I avoid this ? ( This because in myy horizontal scrolling I use custoom css fr a FadIn Effect instead).

I don't understand, what is exactly the issue?

If you only want to apply it on vertical sections, then use `parallax: 'sections'`

**Comment by alvarotrigo** [comment]
> WHen I Use fadeIN EXtension, can I apply it only to the section containing Horizontalscrolling ? And Keeping parallax to my other section. ?

Yes, use `fadingEffect: 'slides'`
