### ISSUE TITLE
scrollOverflow.min.js missing

### ISSUE THREAD

**Issue by bstnstn** [alvarotrigo/fullPage.js#4438]
I want to make a section scrollable using scrollOverflow as described in the documentation, but the required scrolloverflow vendor library is not part of this repo anymore. There does not seem to be any other officially sources to get it either.

Is scrolloverflow functionality still supported in the current version of fullPage.js? Which version of the scrolloverflow vendor library do I need to use, and where can I get it?

**Comment by alvarotrigo** [comment]
> I want to make a section scrollable using scrollOverflow as described in the documentation, but the required scrolloverflow vendor library is not pa

Who said it's required now?
fullPage.js version 4 doesn't require any external vendor library for that :)

For v3, check [the old release docs](https://github.com/alvarotrigo/fullPage.js/tree/3.1.2)

**Comment by bstnstn** [comment]
Thanks for the fast reply!

> Who said it's required now?

Hmm, the documentation does:
https://alvarotrigo.com/fullPage/help/make-a-section-scrollable-in-fullpage-js-using-scrolloverflow/

`This configuration requires the scrolloverflow vendor library [scrolloverflow.min.js](https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.min.js). This file has to be loaded before the [fullPage.js plugin](https://github.com/alvarotrigo/fullPage.js/), but after jQuery ( in case of using it). For example:`

> fullPage.js version 4 doesn't require any external vendor library for that :)

Ah, thanks, that's good to know. :)

**Comment by alvarotrigo** [comment]
> Hmm, the documentation does:
> https://alvarotrigo.com/fullPage/help/make-a-section-scrollable-in-fullpage-js-using-scrolloverflow/

Right!
Thanks for the heads up, we'll have to update those docs in the Help center! 👍 

Just note that that's not the documentation but the Help center. 
The documentation is currently on Github:
https://github.com/alvarotrigo/fullPage.js

**Comment by alvarotrigo** [comment]
> Thanks for the heads up, we'll have to update those docs in the Help center! 👍

Done!
