### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by hahmmj** [alvarotrigo/fullPage.js#4439]
### Description

Hi all,

I am creating my first portfolio website using webflow and fullpage.js.
I have the problem that home section with big size image with the width 16000px is not well displayed when using fullpage.js
for other sections, there is no problem because the size of section can cover all components. 
how can I solve this issue?

### Link to isolated reproduction with no external CSS / JS

1. webflow link for my portfolio webpage
https://preview.webflow.com/preview/moonjoo-hahm-portfolio?utm_medium=preview_link&utm_source=dashboard&utm_content=moonjoo-hahm-portfolio&preview=fa7eaa7fd70e1d5191ad3a26f8374bea&workflow=preview

It has to be displayed like

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/45761070/182254225-dcbd5b01-ee22-401c-bf8d-2c8ae11bfaa0.png">

2. my portfolio website using fullpage.js
moonjoohahm.com

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/45761070/182254136-6fa19fca-c49f-4235-aff9-756b44f4629d.png">

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by hahmmj** [comment]
@alvarotrigo thanks for your reply

I paid for the webflow package to export code.

There is only one problem that I added image file as png or jpg instead of using url.

I tried to copy and paste code into jsfiddle and codepen but it seems different. 

How can I share you code I made? (Can I send a zip file via email to you?)

**Comment by alvarotrigo** [comment]
I'm not asking you to recreate your whole site, I'm asking you to recreate the issue in a blank jsfiddle or codepen :)

Perhaps you might find it useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

Unfortunately, we do not check websites here, but if you need some premium support you can get a Business License from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> and we'll take a look at your website.

**Comment by alvarotrigo** [comment]
I've closed it so far as there's no isolated reproduction we can inspect.
But let me know if you manage to create one so we can keep on investigating the issue.
