### ISSUE TITLE
not work callback "afterSlideLoad"

### ISSUE THREAD

**Issue by 6pm** [alvarotrigo/fullPage.js#444]
maybe I'm doing something wrong? my code

``` javascript
//Full page plugin
$(document).ready(function() {
      if (document.body.clientWidth > 767) {
    setTimeout(function() {
      $.fn.fullpage({
        anchors: ['home', 'about', 'services', 'works', 'team', 'contacts', 'facts', 'pricing', 'video', 'faq', 'stories', 'newPosts', 'callAction'],
        navigation: true,
        scrollOverflow : true,
        navigationPosition: 'right',
        navigationTooltips: ['Home', 'About', 'Services', 'Works', 'Team', 'Contacts', 'Some facts', 'Pricing', 'Video', 'FAQ', 'Success stories', 'New posts', 'Call action'],
        onLeave: function(index, direction){
          changeNavColor();
        },
        afterSlideLoad: function(anchorLink) {
          console.log(anchorLink);
        }
      });
      changeNavColor();
    }, 500);
  };
});
//Full page plugin
```

**Comment by saurabhsrb** [comment]
No working for me.

here is my code, Don't know why it is not logging anything in console, Full page scroll is working through..

 $('#main').fullpage({
      anchors: ['1stPage', '2ndPage', '3rdPage', '4thPage', '5thPage', '6thPage'],
      slidesNavigation: true,
      menu: '#main-nav',
      afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
        console.log(anchorLink);
      }

    });

**Comment by saurabhsrb** [comment]
Yoooo, 

This works for me


```javascript

$('#main').fullpage({
      anchors: ['1stPage', '2ndPage', '3rdPage', '4thPage', '5thPage', '6thPage'],
      slidesNavigation: true,
      menu: '#main-nav',
      afterLoad: function(anchorLink, index){
        if(index == 3){
          console.log('3rd Slide | Do Something');
        }
      },
      

    });

**Comment by alvarotrigo** [comment]
@rttmax can you please open a new issue and provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [Codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
