### ISSUE TITLE
Input field  issue on mobile

### ISSUE THREAD

**Issue by raazmi** [alvarotrigo/fullPage.js#4441]

**Comment by alvarotrigo** [comment]
Make sure to update to the latest version 4.0.10.

If you still having issues, can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by raazmi** [comment]
I use the react version of fullpage.js. Is the react version updated?

**Comment by alvarotrigo** [comment]
> Is the react version updated?

Yes, as long as you use version 0.1.27

**Comment by alvarotrigo** [comment]
Let's treat the issue here, as if there's any bug, it will be on fullPage.js and not on the react wrapper's code.
