### ISSUE TITLE
Website missing commit number

### ISSUE THREAD

**Issue by solonovamax** [alvarotrigo/fullPage.js#4444]
### Description
Website is missing number of commits, and instead displays "0+"

![image](https://user-images.githubusercontent.com/46940694/185704700-5926ae8f-52d2-4138-a8a9-fefc407d0767.png)

### Steps to reproduce it
1. Navigate to https://alvarotrigo.com/fullPage/#page2.
2. See "Open" slide
3. The "commits" element has "0+"

### Versions 
Tested on
|-|-|
|Browser|Version|
|-|-|
|Ungoogled Chromium|104.0.5112.79 (Official Build, ungoogled-chromium) Arch Linux (64-bit)|
|Firefox|Firefox Developer Edition 104.0b9 (64-bit)|

**Comment by alvarotrigo** [comment]
Thanks for the heads-up! 👍 
I'll solve that in a few days!

**Comment by alvarotrigo** [comment]
Fixed! 🥳
