### ISSUE TITLE
Hide Navbar when scroll down, show again when scroll up

### ISSUE THREAD

**Issue by Wurlnet** [alvarotrigo/fullPage.js#4445]
Project Status - Still in development - Local machine / local testing
Web Framework - Django
CSS Framework - Bulma
JS Packages / Plugins - fullpage.js

Testing on Chrome and Edge.

I'm currently updating our web-app, its Django and I already have a base.html template which contains the global html structure, links and navbar.

Your fullpage.js plugin is installed, configured and works. Everything shows and functions as it should on django's test server.

I want to hide the top navbar when the user scrolls down and then display it again when they scroll up again. This is usually a simple CSS/JS task however everything that I'm currently trying seems to be conflicting with the functions defined within fullpage.js.

I'm sure I'm not the first to ask this, so hopefully there's a solution that you can suggest?

Thanks

**Comment by alvarotrigo** [comment]
Just use fullPage callbacks or css states to do so.

Here's an example:
https://codepen.io/alvarotrigo/details/wvPgRQm

**Comment by alvarotrigo** [comment]
The other option is including the header within the first section instead of having it outside the fullpage wrapper.

**Comment by Wurlnet** [comment]
Hi

Apologies, this is my first opportunity to reply. Thank you, the CSS state worked fine.

I should also have mentioned that I have a “bouncing down arrow” as an indicator that the user can scroll down. However I’d like that element / down arrow to be hidden once the user either starts to scroll down, or reaches a specific section.

I’ve implemented some “onscroll” javascript and some “scroll” jquery that I’ve used previously, but it doesn’t seem to work with fullpage.js

Can you help??

Thanks

Frank | Director
[wurlnet_logo]

[Mob:]
+44 (0) 1745 815442

**Comment by alvarotrigo** [comment]
Make sure to use the option `scrollBar: true` if you want to use scroll-based events on third-party libraries or your own code.

**Comment by Wurlnet** [comment]
Yes that sorted that, thank you.

I’ve since noticed that when I scroll down to the next section, I can still see approx 1px of the above section at the top of the view – like an overspill? I have a full section height / width video container within the first parent section so its quite noticeable.

I’m using the bulma CSS framework, which also uses ‘.section’ as a class with styles. I’m also adding its ‘.p-0’ class to the section class which removes all padding from that element. By default their styles are –

.Section {
               padding: 3rem 1.5rem;
}

.p-0 {
               padding: 0 !important;
}

If I remove the .p-0 class the overspill seems to correct itself, but then the video container displays with padding. When I remove the padding from the parent .section class directly, this makes the overspill return.

From what I can see on developer tools, you apply “scroll-snap-type: none;” to the body tag. When I un-check this in dev-tools, it seems to correct itself?

I’d appreciate your help with this.

Thanks


Frank | Director
[wurlnet_logo]

[Mob:]
+44 (0) 1745 604143

**Comment by Wurlnet** [comment]
As a trial and error exercise I added this style to the body tag –

scroll-snap-type: both !important;

Its corrected the overspill, but now the scroll snap between sections is too fast?

Frank | Director
[wurlnet_logo]

[Mob:]
+44 (0) 1745 604143

From: Frank @ wurlnet
Sent: 19 September 2022 13:21
To: alvarotrigo/fullPage.js ***@***.***>; alvarotrigo/fullPage.js ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [alvarotrigo/fullPage.js] Hide Navbar when scroll down, show again when scroll up (Issue #4445)
Importance: High

Yes that sorted that, thank you.

I’ve since noticed that when I scroll down to the next section, I can still see approx 1px of the above section at the top of the view – like an overspill? I have a full section height / width video container within the first parent section so its quite noticeable.

I’m using the bulma CSS framework, which also uses ‘.section’ as a class with styles. I’m also adding its ‘.p-0’ class to the section class which removes all padding from that element. By default their styles are –

.Section {
               padding: 3rem 1.5rem;
}

.p-0 {
               padding: 0 !important;
}

If I remove the .p-0 class the overspill seems to correct itself, but then the video container displays with padding. When I remove the padding from the parent .section class directly, this makes the overspill return.

From what I can see on developer tools, you apply “scroll-snap-type: none;” to the body tag. When I un-check this in dev-tools, it seems to correct itself?

I’d appreciate your help with this.

Thanks


Frank | Director
[wurlnet_logo]

[Mob:]
+44 (0) 1745 604143

**Comment by alvarotrigo** [comment]
> scroll-snap-type: both !important;

The latest version of fullPage.js (v 4.0.11) doesn't apply  scroll-snap at all.
So try updating to the latest.

**Comment by Wurlnet** [comment]
I’ve tried ‘scroll-snap-type: both !important;’ and it makes the scroll instant, there’s no smooth transition between sections.

I’ll check to see which version of fullpage.js I have and will try updating.

Frank | Director
[wurlnet_logo]

[Mob:]
+44 (0) 1745 604143
