### ISSUE TITLE
Disable Centering on Big Sections When Scroll Overflow Disabled

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#4446]
Hi,

When `scrollOverflow` is enabled on a big section, since the scroll bar is enabled inside the section, it appears as expected.

However, when `scrollOverflow` is disabled, there is no scroll bar inside the section, hence an overflow happens, the content of the big section overflow to other sections. Since vertical alignment is centered, this overflow goes in both ways, up and down sections.

You can check it here: https://codepen.io/meceware/pen/abYMbGr
PS: Enable `second-section` CSS and `bigSectionsDestination` option to see the effect.

I think, to prevent this, if a bigger section is present in a non-scroll overflow environment (`scrollOverflow` false or `fp-noscroll` added to the section), a class name should be appended to the section to disable the overflow and disable the vertical alignment. However, the `bigSectionsDestination` option should be taken into account when the scrolling happens in this section.

This was working as expected in fullpage v3, but I think it got broken in v4.x. 

Thank you,

**Comment by alvarotrigo** [comment]
This got solved with the fix of this issue https://github.com/alvarotrigo/fullPage.js/issues/4447

If you use the code in the dev branch you can see how it gets fixed:
https://codepen.io/alvarotrigo/pen/YzaMEGg

Let me know if you are able to reproduce the issue there.

**Comment by meceware** [comment]
Thank you :)

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.11 🥳
