### ISSUE TITLE
Big Section Overflows when Scroll Bars Enabled

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#4447]
Hi,

I'm not sure what the expected behaviour is in this case but, when scroll bars are enabled and scroll overflow is disabled, the section content overflows. I think I'd expect it to be an minimum full screen and if more, auto height section. Please check the following link for the issue,

https://codepen.io/meceware/pen/eYMXmma

Thank you,

**Comment by alvarotrigo** [comment]
The behavior with v3 was to allow it to grow larger than the viewport unless `scrollOverflow: true` was used:
https://codepen.io/alvarotrigo/pen/zYWXvby

This can be replicated now in v4 by adding `fp-auto-height` on that section too:
https://codepen.io/alvarotrigo/pen/abYxvgx

We can:

- Leave it like it is now
- Or apply those styles (`display: block; height: auto`) when we detect content larger than the viewport and scrollOverflow is off.

Probably better the latter so people won't get weird layouts?

**Comment by meceware** [comment]
> Leave it like it is now

If we leave it like this, the user cannot do anything once scroll overflow is disabled since he/she doesn't know when the overflow happens. They'd write their own script to make it work. 

> Or apply those styles (display: block; height: auto) when we detect content larger than the viewport

I think this makes more sense. What do you think?

**Comment by alvarotrigo** [comment]
> If we leave it like this, the user cannot do anything once scroll overflow is disabled since he/she doesn't know when the overflow happens.

Not quite sure what you mean here. 
But I've added a fix on the dev branch.

**Comment by alvarotrigo** [comment]
Ok, this needs another round.

I noticed behavior in v3 was not consistent.
When using slides with large content, those wouldn't exceed the height of the viewport.

Large Slide content (2nd section) - Won't exceed viewport
https://codepen.io/alvarotrigo/pen/KKoOXQr

Large Section content (2nd section) - Will exceed viewport
https://codepen.io/alvarotrigo/pen/zYWXvby

Also, thinking about it twice... probably the best thing we can do is to force the height = 100%.
Then, if the developer wants to exceed the height, he can add `fp-auto-height` (or add ScrollOverflow)

This way he has full control.

**Comment by meceware** [comment]
Got it! Thank you for looking into this one,

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.11 🥳
