### ISSUE TITLE
fullPage: Incorrect `licenseKey`. Get one for fullPage.js version 4 here

### ISSUE THREAD

**Issue by mishachto** [alvarotrigo/fullPage.js#4449]
Yesterday I bought a license, but I get an [error](https://prnt.sc/xiwDm8eJ8uGh). What am I missing?

I apologize for creating a new topic, probably already answered a hundred times, but I can not find it.

For React

**Comment by alvarotrigo** [comment]
You need a fullPage.js license. 
You are currently using the Parallax license for both values.

You can get a fullPage.js license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>.
