### ISSUE TITLE
Altering the font size

### ISSUE THREAD

**Issue by silvenon** [alvarotrigo/fullPage.js#445]
What is [this](https://github.com/alvarotrigo/fullPage.js/blob/fc85272fcb07066a8b3723279c28aa0750dc35f9/jquery.fullPage.js#L1117-L1119)? When I resize my browser, the font size of the page changes.

**Comment by drawcard** [comment]
This particular issue confused me for many hours before I finally figured out what was going on by finding this thread. I hope this setting gets switched to "false" by default as it doesn't really serve any purpose having fonts scale down to 10% or less when the window viewport is scaled down.
