### ISSUE TITLE
Hide slide not section

### ISSUE THREAD

**Issue by ekzmgusdls** [alvarotrigo/fullPage.js#4451]
Hello.
I have a problem with how to cover the slide with media query due to device size change.

What's important is that it's not a section, it's a matter of slide.

A section knows how to hide through multiple solutions.
But the slide doesn't work if it's hidden in the same way.

I'm using the scroll Horizontally extension, and when I scroll, it goes over not only the section but also the slide. However, if you make a slide display none by a media query, when you scroll, that slide is ignored and doesn't go over, and the screen goes over to the first slide.

How can we solve this?

**Comment by alvarotrigo** [comment]
fullPage.js automatically deals with hidden sections/slides in version 4.
Consider updating to the latest version 4.0.10 if you are still using fullPage.js v3.
