### ISSUE TITLE
Keyboard scrolling doesn't work on mobile when using the responsiveWidth property

### ISSUE THREAD

**Issue by BossElijah** [alvarotrigo/fullPage.js#4452]
### Description
The responsive width property (`responsiveWidth`) works fine, except that it completely turns off keyboard scrolling. I am able to do something that works with the destroy function, but I think it shouldn't be neccessary. When setting the responsive width property, I believe it should completely turn off fullpage.js's features, but it doesn't.

### Code to reproduce
Jquery:
```js
$wrapper.fullpage({
  lazyLoading: false,
  scrollingSpeed: 800,
  verticalCentered: false,
  responsiveWidth: 768,
});
```

### Steps to reproduce it
1. Open webpage and make sure the viewport is below the `responsiveWidth`'s defined number.
2. Try to scroll with the keyboard (arrow keys, space)

### Versions 
**All browsers I have tested on:**
 - Firefox Version 103.0.2 (64-bit)
 - Chrome Version 104.0.5112.101 (Official Build) (x86_64)
 - Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (x86_64)
 - Safari Version 15.4 (17613.1.17.1.6)

**OS**
macOS Monterey Version 12.3
MacBook Pro (15-inch, 2016)

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 
I was able to reproduce the issue in this codepen:
https://codepen.io/alvarotrigo/pen/WNzBQYR?editors=1010

Taking a look at it!

**Comment by alvarotrigo** [comment]
The issue should be fixed now in the dev branch. 
You can get it from here:
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

Or if you use npm:
```sh
npm install alvarotrigo/fullpage.js#dev --save
```

**Comment by alvarotrigo** [comment]
I'll close it once merged :)

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.11 🥳
