### ISSUE TITLE
Scroll issue's with normalScrollElements on mobile views.

### ISSUE THREAD

**Issue by johannessmit** [alvarotrigo/fullPage.js#4456]
### Description
When working with scrollable content on mobile, we are having an issue with the fact that if you have `normalScrollElements` it is not possible to 'swipe' to other section's / slides on mobile when the `normalSrollElements` are taking up a good portion of the viewport.

It looks to me that on mobile it should work as scrollable, until the scrollBar is to the top/bottom and a person tries to scroll further, it should scroll to the next section/slide (ofcourse, depending on the touch movement of the end-user).

### Link to isolated reproduction with no external CSS / JS
[Codepen](https://codepen.io/j-spijkerman/pen/vYjBzxv)

### Steps to reproduce it
1. Resize the window to a mobile view
2. Go to the third slide, second section
3. Try to scroll to the previous slide (2)
4. This will only work if you're not scrolling within the viewport of the scrollable content

### Versions 
- Generic as soon as a scrollable element takes up a good portion of the viewport.

**Comment by alvarotrigo** [comment]
I'm a bit confused about what are you trying to achieve here.

If all you need is scrollable content within a section, then you'll have to use the option `scrollOverflow: true`.
That will generate the scrollbar within the section and allow you to scroll to content that is larger than the viewport.

scrollOverflow option will automatically scroll up / down when reaching the top/bottom of the scrollable section/slide.

The option `normalScrollElements` should only be used to tell fullPage.js to completely ignore the wheel event and leave the browser deal with it. 
It is usually used on modals, maps or elements that require any kind of mouse wheel interaction outside the fullPage.js behavior.

> It looks to me that on mobile it should work as scrollable, until the scrollBar is to the top/bottom and a person tries to scroll further, it should scroll to the next section/slide (ofcourse, depending on the touch movement of the end-user).

So, answering this. 
That's not what `normalScrollElements` is suppose to do :) 
That's what `scrollOverflow` does.

**Comment by johannessmit** [comment]
@alvarotrigo I've updated the posted Codepen in the initial issue comment, I've removed the normalScrollElements and added a little bit more text to the specific section (third slide, second section).

As you can see, when you first scroll completely to the bottom in the scrollable position (whether mobile or desktop) and then scroll a little bit up, you also move up to the previous slide (2), while the scrollbar for the content is not yet on the top position.

**Comment by alvarotrigo** [comment]
Remove `overflow-y: scroll;` from the wrappers of your content. (`grid__content` and `grid`)
Also and `height: 100%;`.

Give fullPage.js total control over that and you'll be fine :)
https://codepen.io/alvarotrigo/pen/jOxNQOe
