### ISSUE TITLE
Responsive Slides extension is un-nesting slides from their sections.

### ISSUE THREAD

**Issue by anakadote** [alvarotrigo/fullPage.js#4457]
I just purchased and installed the Responsive Slides extension for a Vue 3 app and noticed that, when active, all but the first of a section's slides become un-nested from the section; is this the intended behavior? The issue with that is that I have CSS styles based on sections, and when the slides become un-nested then the CSS selector are no longer correct. For example:
```
.section-1 .slide-2 {
    // some styles here.
}
```
The above no longer works when `.slide-2` becomes un-nested as a child of `.section-1`. You can see this happening in the attached screenshot.

![Screen Shot 2022-09-06 at 2 29 02 PM](https://user-images.githubusercontent.com/2798169/188713466-e3ec9a1a-ebad-4297-8821-4be1a943aac0.png)

**Comment by alvarotrigo** [comment]
Yes. That's the intended behaviour.

**Comment by alvarotrigo** [comment]
Consider applying styles directly to the slides by using specific selectors for those slides.
