### ISSUE TITLE
In Ipad reverse scrolling not working fine

### ISSUE THREAD

**Issue by abdul891** [alvarotrigo/fullPage.js#4458]
**When we do reverse scrolling in ipad , the title appears on the top**

We have implemented this javascript
see screenshot https://www.awesomescreenshot.com/image/32150218?key=fdcfdf1198ad1f676aa2ca706fd48383
Site url https://aleadamedi2stg.wpengine.com/

**Comment by alvarotrigo** [comment]
What title?
I'm not able to reproduce the issue on the [fullpage website](http://alvarotrigo.com/fullPage/).

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by abdul891** [comment]
see this video link https://drive.google.com/file/d/1SLOgOcCHNADYiYn6oSdRG7pFI6FN4L9Z/view?usp=sharing

**Comment by alvarotrigo** [comment]
Sorry but I don't see any issue. 
Can you bee more specific?

**Comment by abdul891** [comment]
see title

**Comment by abdul891** [comment]
**When I click on the menu the title appear on the top**

**When I do first time scroll ,the postion of the title is diffrent from the postion when click.**

**This issue comes on the Ipad.**

**Comment by alvarotrigo** [comment]
What do you mean by "the title". 

Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by abdul891** [comment]
**Title means** page section title(example About Aleada Media Group
See this video properly https://drive.google.com/file/d/1SLOgOcCHNADYiYn6oSdRG7pFI6FN4L9Z/view

**Comment by alvarotrigo** [comment]
Yeah, I can see it appears moved to the top when you scroll up.
However, note on this forum we only provide support for issues that can be reproduced outside your website/page to make sure the issue is in fullPage.js and not within your website's code.

That's why I suggest you reproduce your issue in codepen or jsfiddle.

If you need premium support consider getting a Business license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>.

**Comment by abdul891** [comment]
We have already premium business plan.
Where can we contact for premium  support.

**Comment by alvarotrigo** [comment]
Sure, use the [contact form](https://alvarotrigo.com/contact/) and send us your URL.
