### ISSUE TITLE
Testing Fullpage.js

### ISSUE THREAD

**Issue by cherri-labs** [alvarotrigo/fullPage.js#4463]
### Description
I've been testing Fullpage.js in React with no license key since I made a request for an open-source one but don't have it yet.
There's this watermark on the bottom right corner which does not appear on the examples provided (though they show no license key as well). I was wondering what's going on. Did the examples actually sport a license someway? Or is there a way to remove it (which is not CSS display/visibility)? Otherwise, will it just disappear once I receive my license key and I just have to wait?

I'm sorry I have to write about such a silly question but I found literally zero info about the issue.

Thanks.

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/7ku2m2?file=/src/App.js

### Steps to reproduce it
1. Import react-fullpage
2. Render
3. It's there!

**Comment by alvarotrigo** [comment]
You can read about the `credits` license in the docs:
https://alvarotrigo.com/fullPage/docs/

Also, no need to request open-source license.
You can also read about it on the `licenseKey` option in the docs.

**Comment by cherri-labs** [comment]
But the `gplv3-license` option still gives me the `fullPage: Incorrect 'licenseKey'.` error.

Also I read the part about comments:
`You will have to provide a prominent notice that fullPage.js is in use. The credit comments in the JavaScript and CSS files should be kept intact (even after combination or minification).`
but does this include the watermark as well?

**Comment by alvarotrigo** [comment]
Yeap, good catch!

Fixed on the dev branch!
