### ISSUE TITLE
Android : Slider + Form inputs  + " fullpage_api.movex()" strange behavior 

### ISSUE THREAD

**Issue by GamxXamg** [alvarotrigo/fullPage.js#4466]
### Description

Hello, i bought a licence few months ago and played around your amazing plugin. Eveyrthing went well, i was able to achieve almost everything i needed/asked to.

Using 4.0.7 I had problem with blank screen issue on input focus (only on mobile), so i checked issues on github and saw people had the same one, and that the plugin got updated, i decided to upgrade to 4.0.11.

Now when i tried to make a single/multiple form using implemented slider, i have a really strange behavior, after filling the second input, i can't use fullpage_api.moveSlideLeft(); neither the arrows nor the nav 

## Tests & devices : fullpage.js v4.0.10
 
Desktop : As intended

lambdatest   : iphone12 emulator : as intended

android emulator : issue.
4  android phone : issue.

## fulllpage v4.0.7

Android : Weird input white screen/scrolling on input focus, but no issue with  fullpage_api.movex() after second input.
Desktop : As intended

### Link to isolated reproduction with no external CSS / JS

I tried to isolate this behaviour on a blank v4.0.11 

uploaded on personal hosting

https://gamx.fr/fullpagetestinput/examples/active-slide.html#secondPage/1

### Steps to reproduce it

On android : (if someone can test on real iphones and tell me if it's working as intended like on my emulator)

1.Fill an input (first or seconde slide , it dosen't matter.
2. Press Next/Prev 
3. It goes well.
4. fill the second input, press next/prev
5. everything is locked, button doesn't fire, nor the arrow keys or nav buttons

I hope this is a cronstructive issue and that i didn't miss something stupid 🗡️ 

I really appreciate  your work,. Thanks for taking a look at it :)

**Comment by alvarotrigo** [comment]
Good catch!
Fixed on the dev branch v4.0.12!
https://github.com/alvarotrigo/fullPage.js/tree/dev/dist

**Comment by GamxXamg** [comment]
Perfect ! Thank you so much !

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳
