### ISSUE TITLE
Elementor - Background Overlay Appearance Delayed When Scrolling (Safari)

### ISSUE THREAD

**Issue by joeyparisi** [alvarotrigo/fullPage.js#4473]
### Description
During our testing Safari on Desktop and iOS is showing graphical bugs that don't appear on other platforms. 

VIDEO OF ISSUES: https://youtu.be/wd66gT6Nh4U

- Home Page: Background Overlays appear after a delay of coming into view. There is no animation applied to them.
- Flip Card's freak out on hover, no other way to describe it. You can see it in the "Engines" section on the home page and on the team members on the "About" page
- Games Page: Slider flashes white when scrolling
- Games Page: Lightbox background doesn't animate smoothly in when clicking on a game box art

These things seem to all be related to Safari's animation issues. I can mitigate some of the issues by using the "transform: translateZ(0)" hack, which I have done on the Flip Cards on the live site. It does not seem to work on the background overlays.

Are there any suggestions?

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. Enable Fullpage.js in Elementor
2. Add a background image to two sections
3. Add a gradient overlay over each section
4. Scroll between sections
5. Notice the background overlay doesn't appear until after a delay in Safari, but is fine on other browsers.

### Versions 
Safari 16, Mac OSX 12.6, reported on iOS as well (I don't have an iOS device.)

**Comment by alvarotrigo** [comment]
In order to report bugs on the [official Elementor plugin for fullPage.js](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) please use the [contact form](https://alvarotrigo.com/contact/).
