### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'length')

### ISSUE THREAD

**Issue by mot-K** [alvarotrigo/fullPage.js#4476]
I'm using Drupal and getting the following error in the console:

Uncaught TypeError: Cannot read properties of null (reading 'length')
    at fullpage.js?v=3.1.0:5836:78
    at setAPI (fullpage.js?v=3.1.0:5841:10)
    at new fullpage (fullpage.js?v=3.1.0:5809:7)
    at $.fn.fullpage (fullpage.js?v=3.1.0:5890:11)
    at HTMLDocument.<anonymous> (slider.js?v=9.4.8:3:24)
    at e (jquery.min.js?v=3.6.0:2:30038)
    at t (jquery.min.js?v=3.6.0:2:30340)

Version of Fullpage.js: 4.0.12

**Comment by alvarotrigo** [comment]
Could you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

**Comment by alvarotrigo** [comment]
Closed until an isolated reproduction is provided as detailed in the [reporting issues guidelines](https://github.com/alvarotrigo/fullPage.js#reporting-issues) and the [issue skeleton](https://github.com/alvarotrigo/fullPage.js/blob/master/.github/ISSUE_TEMPLATE.md).
