### ISSUE TITLE
CSS : z-index ignored because of translate3d with an HTML structure generated by the libraries javascript fullpagejs and animejs

### ISSUE THREAD

**Issue by kegilko** [alvarotrigo/fullPage.js#4477]
### Link to isolated reproduction with no external CSS / JS
https://codepen.io/kegilkoo/pen/OJERXwb

### Steps to reproduce it
I create a simple personal website using the libraries [fullpagejs][1] and [animejs][2].

The website shows a set of slides (by means of fullpagejs), and I want to add an absolute overlay to the top of each slides. The height of the overlay must be increased if I scroll to the next slide, and the next slide, etc..

[![enter image description here][3]][3]

v and if I swipe to the next slide v

[![enter image description here][4]][4]

The height of the overlay grows with an animation (with animejs). In some slides, I add some elements and sometimes, one of these element may be over the overlay. (by example the element A bellow)

[![enter image description here][5]][5]

But ! and this is my issue, the element A is behind the overlay, not over as expected : 

[![enter image description here][6]][6]

After a while and some lost hairs, I find the issue. Here is a simplified code : 

```html
<style>

.pr{position:relative;}
.pa{position:absolute;}
.ps{position:static;}

.overlay{z-index:5}
.element{z-index:10}

.fullpagejs{
	transform: translate3d(0px, 0px, 0px); /* automatically added by animejs */
	transition: transform 700ms ease 0s; /* automatically added by animejs */
	position:relative;
}


</style>

<body class='pr' style="width:360;height:640px">
	<!-- The overlay I added-->
	<div class='pa overlay' style='width:100%;height:100px;background-color:blue'></div> 
	
	<!-- This structure (simplified ) bellow is automatically generated by the library fullpagejs-->
	<div class='fullpagejs' style='height:100%;width:100%;background-color:lightgrey'>
		<div class='pr'>
			<div class='ps fullpagejs_slide'>
				<div class='pa element' style='height:200px;width:200px;background-color:orange'></div>
			</div>
		</div>
	</div>
</body>
```

([link codepen][7])

In the result, the orange square is behind the blue overlay and **this is because** the css properties `transform: translate3d...` and `transition: transform...` automatically added by fullpagejs.

[![enter image description here][8]][8]

Because theses properties, the property `z-index` is ignored ! If you remove theses problematics properties then the property `z-index` work well and the orange element become over the overlay as I want 

After somes searches and somes tries I don't find a way for have blocks elements inner a slide block and blocks elements over the overlay...
Thanks for any help ! 

  [1]: https://alvarotrigo.com/fullPage/
  [2]: https://animejs.com/
  [3]: https://i.stack.imgur.com/eREIW.png
  [4]: https://i.stack.imgur.com/YkY1I.png
  [5]: https://i.stack.imgur.com/6mr5A.png
  [6]: https://i.stack.imgur.com/KyZqD.png
  [7]: https://codepen.io/kegilkoo/pen/OJERXwb
  [8]: https://i.stack.imgur.com/O959O.png
  [9]: https://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d

### Versions 
Tested on Chrome and Firefox browsers

**Comment by alvarotrigo** [comment]
This is not really a fullPage.js issue but probably a bug in the browser/s dealing with `translate3d` transformations and `z-index`.

See [this](https://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d).

You can try some things like adding `transform-style: preserve-3d;`.

Another way to fix it is by creating the elements outside the fullPage.js structure.

And probably the simplest one, turning of `css3` transitions on fullPage.js by using `css3:false` or `scrollBar: true`.

**Comment by kegilko** [comment]
thank you for your help :) 
The css3 to false works well !
