### ISSUE TITLE
fullpage.js overwrites menu and makes it sticky - it should stay at top of page.

### ISSUE THREAD

**Issue by rwiman** [alvarotrigo/fullPage.js#4478]
### On our page https://dev.forebygg.se/hem_ny/ we are using a header that is supposed to be transparent and non-sticky.

The site is built on WP with Oxygen Builder.

As soon as we began using fullPage.js it made the menu sticky. What can we do about fullPage.js so that this does not happen?

At the same time, fullPage.js made it so that the footer is not visible anymore (i.e. it is not possible to scroll down to the footer).

### Link to isolated reproduction with no external CSS / JS
https://codepen.io/rwiman/pen/dyKNraw

### Steps to reproduce it
1. scroll and the menu will be sticky
2. continue scrolling and you cannot reach the footer

### Versions 
chrome, latest version

**Comment by alvarotrigo** [comment]
It looks like an integration issue more than a fullpage.js one.
We don't provide any official plugin for Oxygen Builder, so we don't provide support for such integration.

We currently only provide plugins for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) builders. 

In general terms what you need to do is:

- Keep the sticky menu inside the 1st section (or whatever section you want it in)
- Keep the footer outside fullPage.js structure and use fullPage.js version 4.  [Example](https://codepen.io/alvarotrigo/pen/bGvErae)(version 3 won't support scroll after fullpage.js.)

Another option for the footer:

- Create a section for the last footer and use `fp-auto-height` on it. [Example](https://codepen.io/alvarotrigo/pen/BKjRYm).

**Comment by rwiman** [comment]
Thanks for the swift reply, I'm onboard with that you do not offer support on everything. Just to point out that this solution does not work since we are using a global header that propagates from a template (i.e. we cannot add it into a section as such).

We will continue to investigate. Thanks still

**Comment by alvarotrigo** [comment]
> (i.e. we cannot add it into a section as such).

You can use fullPage.js callbacks such as `afterRender` to move wherever you need by using JS.
