### ISSUE TITLE
license v4 to v3

### ISSUE THREAD

**Issue by lumiere10** [alvarotrigo/fullPage.js#4494]
As I’ve written above in the previous issue task(https://github.com/alvarotrigo/fullPage.js/issues/4493), the scroll does not jump in v3. Given that, please confirm, can the license be changed from v4 to v3? and will it (v3) be further relevant? Thank you!

**Comment by alvarotrigo** [comment]
Is up to you.
If you think you have issues with v4 you can stay on v3.

If you believe this is a bug in fullPage.js we'll need an isolated reproduction to start looking for the issue.

So feel free to stay in v3 if you are not able to reproduce this outside your page.

**Comment by lumiere10** [comment]
thanks, but how to switch to v3 if we bought v4? buy a license again?

**Comment by alvarotrigo** [comment]
No problem!
Use the [contact form](https://alvarotrigo.com/contact/) and let us know your case by pointing to this issue. 

We'll provide you the license for v3.
