### ISSUE TITLE
Conflict with Webflow Editor

### ISSUE THREAD

**Issue by kevinbrenkman** [alvarotrigo/fullPage.js#4495]
When using the fullpage.js script, there is a conflict with the Webflow Editor which results in being unable to scroll. This has been discussed before in the Webflow forums: https://discourse.webflow.com/t/fullpage-js-and-the-cms-editor-incompatibility/30270
But I havent been able to come to a solution.

### Link to isolated reproduction with no external CSS / JS
I cannot reproduce this issue in either jsfiddle or codepen, but I can provide a read only link of the Webflow project. 
Otherwise clone the example project: https://webflow.com/made-in-webflow/website/Fullpagejs-basic-example?ref=showcase-search&searchValue=fullpage

### Steps to reproduce it
1. Using fullpage.js on a Webflow website
2. Try to edit the website in the Webflow Editor (CMS ui)
3. Not being able to scroll or use the Editor interface

### Versions 
macOS 13.0.1 (22A400)
Safari Version 16.1 (18614.2.9.1.12)
Chrome Version 107.0.5304.110 (Official Build) (arm64)

**Comment by alvarotrigo** [comment]
This is not really a fullPage.js issue but one regarding Webflow integration.

I guess you have to find a way to detect when you are inside the editor and when not.
I don't know if Webflow provides any straight way of doing this directly from JavaScript, but one idea that comes to my mind is manually detecting if you are inside the editor or not by checking if this toolbar is visible:

![image](https://user-images.githubusercontent.com/1706326/205345277-da16b489-b8da-47db-8535-7b32201b5754.png)


Then only initializing fullPage.js when it's not visible.

Would that fix the issue?

**Comment by alvarotrigo** [comment]
Ok, we treated this issue back in the day.
Here's what seems to have worked for another developer:
https://github.com/alvarotrigo/fullPage.js/issues/4318

**Comment by alvarotrigo** [comment]
Other related topics:
https://discourse.webflow.com/t/problems-with-cms-editor-and-fullpagejs/39504/3
https://discourse.webflow.com/t/prevent-loading-js-in-editor-mode/41916

**Comment by kevinbrenkman** [comment]
Hi, thank you for the help, by placing this code from the other topic, before </body> tag the problem was solved!

```
<script>
Webflow.push(function () {
  // check is the CMS editor is there
  if (Webflow.env('editor') != undefined) {
    $('#fullpage').fullpage({

    });
  } 
});
</script>
```

**Comment by alvarotrigo** [comment]
Glad it worked! 👍
