### ISSUE TITLE
Have trouble with using normal scroll sections before auto scrolling sections.

### ISSUE THREAD

**Issue by MasterDev333** [alvarotrigo/fullPage.js#4497]
Hi, thanks for creating such a great plugin.
I really love to use this but I have trouble with using normalScrollElements.
![image](https://user-images.githubusercontent.com/73536317/207151856-8aebfbd3-15ce-4d63-a80e-7063550ed77e.png)
As you can see, above screenshot first section has scrollable-content and it has 3 subsections.

Here's my javascript code for Fullpage
```js
new fullpage("#fullpage", {
      licenseKey: 'xxx',
      navigation: false,
      scrollBar: true,
      scrollingSpeed: 1000,
      scrollOverflow: true,
      sectionSelector: 'section',
      normalScrollElements: '.scrollable-content',
      credits: false,
      responsiveWidth: 800
    });
```

I tried to made normal scrolling elements from this example. https://codepen.io/alvarotrigo/pen/RmVazM

**Comment by alvarotrigo** [comment]
So what's the problem?
Can you please provide a codepen where we can reproduce the issue for further investigation?
