### ISSUE TITLE
Purchased license not valid anymore

### ISSUE THREAD

**Issue by elnurxf** [alvarotrigo/fullPage.js#4500]
### Description
Purchased license (fullPage.js Commercial Hobby License) on Apr 30, 2021 and not valid now for version 3.1.2.

Reached at support but forwarded me here to open an issue.

### Link to isolated reproduction with no external CSS / JS
Demo on https://www.bakucitycircuit.com/en

### Steps to reproduce it
1. Go to demo link https://www.bakucitycircuit.com/en
2. Check console

### Versions 
fullPage 3.1.2, Google Chrome Version 108.0.5359.124

**Comment by alvarotrigo** [comment]
It looks like you are initializing fullPage.js multiple times.
Make sure to do it only once with your current license key.

![image](https://user-images.githubusercontent.com/1706326/208130677-e8290e44-d582-49d3-93d3-1cb69df54ad7.png)

If you need more assistance make sure to provide a URL with unmodified and uncombined JS files so we can investigate the issue.

**Comment by elnurxf** [comment]
@alvarotrigo thank you, will make some research and return back to you on Monday
