### ISSUE TITLE
Change 100% height

### ISSUE THREAD

**Issue by bilalmalkoc** [alvarotrigo/fullPage.js#4501]
Hello. All wrappers heights setting as 100% automatically (main wrapper, body...) . Can i change this? For example can i make it `calc(100% - 32px)` ? Because i have WordPress admin bar on top of the site, and it has 32px height. So, sections not fitting true area.

**Comment by alvarotrigo** [comment]
You can try, but I can't assure you fullPage.js or its extensions will work as expected.

fullPage.js doesn't support such a feature though. 
It [has been suggested](https://github.com/alvarotrigo/fullPage.js/issues/2785) before but it hasn't been implemented yet.
