### ISSUE TITLE
Unlicensed fullPage.js Extension (scrollHorizontally)

### ISSUE THREAD

**Issue by bilalmalkoc** [alvarotrigo/fullPage.js#4503]
Hello. I purchased both fullPage and scrollHorizontally extension. But it is showing `Unlicensed fullPage.js Extension` toast message. Here is my config. (I am using webpack)

```
import '../plugins/fullpage.scrollHorizontally.min'
import fullpage from 'fullpage.js/dist/fullpage.extensions.min'

new fullpage('.home-blocks', {
  autoScrolling: true,
  licenseKey: 'XXXXXXXX',
  sectionSelector: '.vn-block',
  normalScrollElements: '.achievements-block__achievements',
  scrollHorizontallyKey: 'XXXXXXXX',
  scrollHorizontally: true,
  responsiveWidth: 992,
  slidesNavigation: false,
  loopHorizontal: false,
  credits: {
    enabled: false,
  },
})
```

Also, i disabled loop for horizontal scroll, but when i scroll end of the slides, it is going to first page and breaking fullPage instance. Is it related to this license problem?

```
fullPage.js version: 4.0.15
scrollHorizontally.js version: 0.1.0
```

**Comment by alvarotrigo** [comment]
For any issues with extensions please use the [contact form](https://alvarotrigo.com/contact/) and contact us using the email used for the purchase and a link to your page. 

Also, make sure to read the docs regarding [how to activate fullPage.js extensions](https://alvarotrigo.com/fullPage/docs/#use-extensions)
