### ISSUE TITLE
in mobile view navbar is not work

### ISSUE THREAD

**Issue by Nehul50** [alvarotrigo/fullPage.js#4504]
Hello dear,

when I open my project in mobile that time nav bar is not work. nav bar is open but any section link is not work. Ex.=> I click navigation it open but in navigation i click on service, about etc. page is not open. but in laptop its work wonder  please give any solution

**Comment by alvarotrigo** [comment]
It doesn't look like a problem that is directly related to the behavior of the fullPage.js component. 
If you think that's the case, please provide an isolated reproduction of the issue on codepen and I'll happily take a look at it.

**Comment by Nehul50** [comment]
How can I send code on codepen. Please tell me so i can send code. You will be resolve my nav bar  error.

**Comment by alvarotrigo** [comment]
You can find  links to codepen and jsfiddle here:
https://github.com/alvarotrigo/fullPage.js#reporting-issues
