### ISSUE TITLE
Skipping a section when scrolling with trackPad

### ISSUE THREAD

**Issue by Alex-Syd** [alvarotrigo/fullPage.js#4507]
Hello,
I recently encountered a problem with fullpageJs and trackpad navigation

When I scroll with the trackpad we have the jump of a section.
I was not able to reproduce the bug on a linux environment but on windows the bug is very frequent. Many of our customers also have it and have reported it to us. Some cases have also been reported to us on tablets

reproduction
- I start on slide 1
- I scroll with the trackpad
- I arrive on slide 2
- After arround 1 seconds, It automatically switch to slide 3
- However if I click on slide 2 when I arrive on it the bug does not occur

the bug happens 1 once every 2 on my pc

The issue also occured on your example and your website
- https://codepen.io/alvarotrigo/pen/qqabrp
- https://alvarotrigo.com/fullPage/#page3

Browser: Chrome
OS: Windows 11
React Fullpage: 0.1.29
FullpageJs: 4.0.15

**Comment by alvarotrigo** [comment]
Try increasing the value of the `scrollingSpeed` value. 
Try `1000` or `1200` and let me know if that fixes it for you.

If the issue can be reproduced on the [landing page](https://alvarotrigo.com/fullPage/#page3), it means it existed in v3 and it's not a regression. (Landing page stills on v3).

If that's the case, it's most likely the issue is regarding kinetic scrolling devices. (with inertia, like Apple trackpads, the magic mouse from Apple or the Logitech MX Mater 3)
 
Your trackpad can be way too sensitive or you are doing a very long / fast swipe with your fingers.

**Comment by alvarotrigo** [comment]
Can you confirm if you are able to reproduce the issue on this page?
https://alvarotrigo.com/fullPage/#page3

**Comment by Alex-Syd** [comment]
I am able to reproduce the problem on this page "https://alvarotrigo.com/fullPage/#page3". 

I use the trackPad of my laptop

If I increase the value of scrollingSpeed the bug is less frequent. 
Can we fix this sensitivity issue without changing the windows settings?

**Comment by alvarotrigo** [comment]
Yeap, then there's not much we can do about it, unfortunately.
I have a Macbook Pro too and I can't reproduce the issue unless I swipe super fast or for a very long time. 

There haven't been many reports of this kind when using a scrolling speed above 1000ms, so I'd say to keep it say keep a value of around 1100 or 1200 if possible. (1000 should be fine too for most cases. The landing page uses 1000).

> Can we fix this sensitivity issue without changing the windows settings?

Unfortunately, there's not much we can do about it within fullPage.js itself.
fullPage.js already has some features implemented on it to avoid problems related to kinetic scrolling, but it won't be 100% bulletproof.

This is a well-known issue among developers dealing with scrolling behaviors and there are projects like [Lethargy](https://github.com/d4nyll/lethargy) trying to find a good solution for it, but still far from perfect.

**Comment by Alex-Syd** [comment]
Ok, Thank you for the quick and qualitative answers
