### ISSUE TITLE
Using credits: false causes fullPage.js invalid license message

### ISSUE THREAD

**Issue by alvarotrigo** [alvarotrigo/fullPage.js#4510]
When the `credits` option is used incorrectly:

```js
credits: false
```

Instead of:

```js 
credits: {
    enabled: false
}
``` 

Then the error "fullPage: Incorrect `licenseKey`. Get one for fullPage.js version 4 here:" will appear on the console. 

This shouldn't be the case.
![image](https://user-images.githubusercontent.com/1706326/215088296-962a11e1-12ad-4b16-b206-16550f2aa52b.png)

Version 4.0.15

**Comment by alvarotrigo** [comment]
This has been fixed on the new version 4.0.16! 🥳

**Comment by rush-all** [comment]
so when i use vue-fullpage-js 0.2.15 ,the same wrong show ,how to fixed it?

**Comment by alvarotrigo** [comment]
> the same wrong show ,how to fixed it?

what "wrong" shows?
Can you paste or take a screenshot of it?

**Comment by rush-all** [comment]
the same to this problem first,but i use vue-fullpage-js 0.2.15 not fullPage Version 4.0.15
![Uploading Snipaste_2024-01-20_09-45-04.png…]()

**Comment by rush-all** [comment]
![Snipaste_2024-01-20_09-45-04](https://github.com/alvarotrigo/fullPage.js/assets/69186348/edf698f8-becf-4c1b-b7d5-e608d262b17b)

**Comment by alvarotrigo** [comment]
If you purchased a license from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a> then use the [contact form](https://alvarotrigo.com/contact/) and send us an email with the email used for the purchase. 

We'll check your license and let you know how to fix the problem.
