### ISSUE TITLE
Question : update menuanchor label

### ISSUE THREAD

**Issue by mzuer** [alvarotrigo/fullPage.js#4516]
Dear All,

Sorry maybe for the naive question, but I am newbie with javascript.

I am using fullPage.js in a R Shiny App. After a click on a button, I would like to change one title of the menu ; based on the HTML code of the page in the example here below, it looks that I need to replace `temp_title` with my new title. 

How could I access and replace this field with javascript ? would it be possible at all ?

Or does fullPage.js provide other functionalities for updating the labels of the menu ?

```
<ul id="tocMenu">
        <li data-menuanchor="test_page">
          <a href="#test_page">temp_title</a>
        </li>
      </ul>
```

Thanks in advance if anyone could help

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide such a feature out of the box.

I don't know R Shiny so I don't think I can help you much. 
I'd recommend you to task in another place where they can help you better.

This forum is to treat issues regarding the use of fullpage.js, so I'll close this issue for now.
