### ISSUE TITLE
Option: make sections horizontal and slides vertical

### ISSUE THREAD

**Issue by j-nicolas** [alvarotrigo/fullPage.js#4517]
### Change of horizontal / vertical behavior of sections and slides due to content-semantics (as an option)

Perhaps there is such option, but I didn't see it.

If not: 
alternatively to the common way it would be great to have the option to change this behavior
So I could have
* topics on the same "level" (= scrolling sections horizontally)
* details "in depth" (= scrolling slides vertically inside sections)

Is there an easy way to accomplish that?

Thanks - Nicolas
![Section-Slide-Semantic](https://user-images.githubusercontent.com/49005029/220214310-85f64918-ce99-4162-adfe-d463c4161773.png)

**Comment by alvarotrigo** [comment]
You can mimic that same behavior by using the extension Interlocked Slides
https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html

Optionally, you can combine it with `setAllowScrolling` and `setKeyboardScrolling` to disable right and left once you land on a vertical section withing a topic. (if that's actually what you want) 

As a reference, the topic has been previously treated years ago [here](https://github.com/alvarotrigo/fullPage.js/issues/200)

If this is something you need help with, feel free to fill out the [contact form](https://alvarotrigo.com/contact/) to get a quote on it.
