### ISSUE TITLE
Window Resize Speed

### ISSUE THREAD

**Issue by marianohsn** [alvarotrigo/fullPage.js#4518]
I need to increase the page refresh rate when resizing the window, for which I've read this article:
https://stackoverflow.com/questions/50672628/remove-delay-when-resizing-browser-fullpage-js
but when I try to import fullPage.js locally instead of pulling it from CDN, the page gets broken and I get an array of different 'module' errors beyond my coding capacity.

How can I change the refresh rate on window resize while loading fullPage.js from the CDN?
Is there a way of passing the `setTimeout` function mentioned on this article as an option when initializing fullPage?

**Comment by alvarotrigo** [comment]
> How can I change the refresh rate on window resize while loading fullPage.js from the CDN?

You can try adding this after the fullpage initialisation:


```js
window.addEventListener('resize', resizeHandler);

function resizeHandler(){
    fullpage_api.reBuild();
}
```

But that can create performance issues when dragging the window to resize it manually,

You can add a smaller timeout by doing this instead:

```js
window.addEventListener('resize', resizeHandler);

var g_resizeId;
function resizeHandler(){
    clearTimeout(g_resizeId);
    g_resizeId = setTimeout(function(){
         fullpage_api.reBuild();
    }, 100)
}
```

**Comment by marianohsn** [comment]
Neither method seems to have any effect. I've also tried other methods with no luck either.
I'll gladly upgrade my license if it'll help making the resize refresh rate work smoother. Please advise.

**Comment by alvarotrigo** [comment]
> Neither method seems to have any effect. I've also tried other methods with no luck either.

It seems to be working fine here:
https://codepen.io/alvarotrigo/pen/vYzKjOE

Compare with the one with delay:
https://codepen.io/alvarotrigo/pen/qqabrp
