### ISSUE TITLE
LicenseKey not working

### ISSUE THREAD

**Issue by HannuRantakallio** [alvarotrigo/fullPage.js#4519]
Got this error message on the website (sailer.fi):

"fullpage.extensions.min.js:8 fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option."

This is how LicenseKey have been added JS:

![image](https://user-images.githubusercontent.com/126490422/221596390-eba3979c-1d34-4ccf-b8d4-6fbde48f8580.png)

Also got this error message from Fullpage Inspector: "The provided page doesn't contain the fullPage.js script."

Is there something wrong here?

**Comment by alvarotrigo** [comment]
You are probably loading fullPage.js version 3 and using a fullPage.js version 4 license.
Or the other way around.

If you got the fullPage.js license recently, then make sure you also update your fullPage.js file to the latest version 4.0.17.
