### ISSUE TITLE
Disable scrolling/snapping fucnionality below 991px

### ISSUE THREAD

**Issue by dawids96** [alvarotrigo/fullPage.js#4520]
Hey guys!
I’m struggling with this a special case and didn’t manage to find an answer in the documentation.
I want to disable scrolling between sections on devices with resolution 991px and less - the reason for that is I want users to navigate the page using the arrow buttons and nav only.
Here’s a link to an example presentation within my project: https://ingka-staging.webflow.io/spain-luz-shopping
Could you please point me as to where I can find some more information about this or let me know if that’s achievable?
I’ll be really grateful for your help!
Thanks!
Dawid

**Comment by alvarotrigo** [comment]
You can probably call the method  `setAllowScrolling(false)` to disable scrolling.

Then navigation would only be possible using keyboard or custom calls like `moveTo`, `moveSectionUp`, `moveSectionDown`, `moveSlideRight` or `moveSlideLeft`.

You can assign those to any elements in your page so users can navigate using those.
