### ISSUE TITLE
Is there any way to temporarily disable fullpage.js while scrolling through another element?

### ISSUE THREAD

**Issue by JasonnnC** [alvarotrigo/fullPage.js#4529]
Hello, is there any feature for fullPage.js which disables the full-page scroll ability while I'm scrolling inside another element? I have a couple of elements with an overflow: scroll; so people can scroll through the content within the section when it goes off the page. However, when you scroll through the extra content it can also activate the full page scroll and unwillingly move the user onto the next section. 

Is there any way to temporarily disable fullpage.js while scrolling through another element?

Many Thanks,
Jason

**Comment by alvarotrigo** [comment]
Sure! 
Did you check out the [`setAllowScrolling` method](https://alvarotrigo.com/fullPage/docs/#setallowscrollingboolean-directions)?

Here's an example:
https://codepen.io/alvarotrigo/pen/EjeNdq 

You can also check out the [`normalScrollElements` option](https://alvarotrigo.com/fullPage/docs/#setallowscrollingboolean-directions:~:text=)-,normalScrollElements,-%3A%20(default).

Here's an example:
https://codepen.io/alvarotrigo/pen/RmVazM
