### ISSUE TITLE
Autoscroll problem in Safari. 

### ISSUE THREAD

**Issue by obemer** [alvarotrigo/fullPage.js#4533]
Hello, 

Thank you for your amazing work.

I'm experiencing an issue with the auto scroll in Safari. 
It works fine with other browsers including safari on iOs. 

I have sections with scrolling overflow. 
In safari, when I'm scrolling from one section to another (trackpad),  the scrolling movement is carrying away the origin section and the overflow of the destination section. Just a tiny annoying bit. 

You can see it here; 
[https://olivierbemer.com](url)

Thanks for your help.

**Comment by alvarotrigo** [comment]
Make sure to update to the latest version 4.0.19

**Comment by obemer** [comment]
I just did, and I still have the same problem. 
any idea ?

Thanks !

**Comment by alvarotrigo** [comment]
Your page still using 4.0.17.
You can check running this on your JS console:
fullpage_api.version

Or checking the comments on the CSS and the JS files.

**Comment by obemer** [comment]
I upgraded it on desktop. 
It's now online running the 4.0.19
The problem persists.

**Comment by alvarotrigo** [comment]
Check your css
https://olivierbemer.com/style.css

**Comment by obemer** [comment]
I figured it was what you meant and I changed it on desktop. 
It's online now and I still have the same problem. 

Sorry about that.

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections with single or multiple headings unless strictly necessary for the reproduction of the issue?

**Comment by obemer** [comment]
Here is a reproduction. I hope it helps. 
I put multiple images for the section to have enough overflow to reproduce my issue. 
Thank you for your time. 

[https://codepen.io/oliiiv/pen/ZEqWNxr](url)

**Comment by alvarotrigo** [comment]
@obemer thanks! 👍 
I'm investigating the issue. 

It seems to be related to the way Safari deals with inertial scrolling.
The mousewheel event seems to get propagated to the next section but the event is not triggering the event, which prevents fullPage.js from cancelling it before completely landing on the section.

**Comment by obemer** [comment]
I'm glad this can help. 
It was driving me mad. 

Good luck fixing this issue. 

Thanks Alvaro.

**Comment by obemer** [comment]
Hello Alvaro, 

Any solutions to this problem. ?

Thanks.

**Comment by alvarotrigo** [comment]
@obemer not yet.

**Comment by alvarotrigo** [comment]
You'll know when there's any change if I comment on the post.

**Comment by alvarotrigo** [comment]
It seems to be the same issue reported here:
https://github.com/alvarotrigo/fullPage.js/issues/4557

Let's continue the conversation there.
