### ISSUE TITLE
Variable scrolling speed ? 

### ISSUE THREAD

**Issue by obemer** [alvarotrigo/fullPage.js#4536]
Hello Alvaro, 

Is there a way to make the scroll speed variable ? 
My problem is that the scrolling speed is nice and slow from section to section, but I have an index, and if I go from the first section to the last section directly,  then the scrolling speed is way too fast. 

Thank you.

**Comment by alvarotrigo** [comment]
> Is there a way to make the scroll speed variable ?

Sure!
Just use a combination of the callback `beforeLeave` and the method `setScrollingSpeed`.
Here's an example that will make the scrolling speed 5 seconds when the visitor tries to go to section 13.

Online demo:
https://codepen.io/alvarotrigo/pen/xxyRXGg?editors=1010

```js
new fullpage('#fullpage', {
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
  navigation: true,
  
  // Get your license at https://alvarotrigo.com/fullPage/pricing/
  licenseKey: 'YOUR LICENSE KEY HERE ',
  beforeLeave: function(origin, destination, direction, trigger){

    if(destination.index === 12){
      fullpage_api.setScrollingSpeed(4000);
    }
    
    // setting the default scrolling speed
    else{
      fullpage_api.setScrollingSpeed(700);
    }
  },

});
```
