### ISSUE TITLE
Большая секция со скролом

### ISSUE THREAD

**Issue by uDrawing** [alvarotrigo/fullPage.js#4538]
Добрый день,ни как не могу разобраться как сделать секцию где много текста который можно пролистывать внутри секции как в примере https://alvarotrigo.com/fullPage/examples/scrolling.html#firstPage

**Comment by alvarotrigo** [comment]
You can check the example:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scrollOverflow.html

Or read the help center article:
https://alvarotrigo.com/fullPage/help/make-a-section-scrollable-in-fullpage-js-using-scrolloverflow/

**Comment by uDrawing** [comment]
Разобрался спасибо,а есть возможность футер отключить из навигации?
