### ISSUE TITLE
Activations still don't work. Code looks good, but activation codes are bad. I even bought the Elementor plugin, and that won't activate either!!!!

### ISSUE THREAD

**Issue by FarmerJerry** [alvarotrigo/fullPage.js#4542]
Buyer beware. None of my activation codes worked. This cost me hundreds of dollars and I can't even activate it!!!!

**Comment by alvarotrigo** [comment]
You'll be attended on the support system. 
Try to provide us with as much information as you can.

**Comment by dangerstudios** [comment]
yes activation continues to be a major pain, convoluted and often does not work. It's a big setback for this project

**Comment by alvarotrigo** [comment]
> It's a big setback for this project

Did you write us through the [contact form](https://alvarotrigo.com/contact/) with the email used for your purchase?

Activations work as expected.
