### ISSUE TITLE
Gutenberg fullpage.js edit page no longer loading

### ISSUE THREAD

**Issue by S-Lukk** [alvarotrigo/fullPage.js#4543]
Hi,

I have become unable to edit my pages that use the Gutenberg fullpage.js plugin. The pages will load on front end but when I try to edit them they stay blank, or sometimes my browser says the page could not load. This happens regardless of which browser I use. See screenshot.
![Screenshot 2023-05-03 at 11 12 40](https://user-images.githubusercontent.com/132443016/235876788-302bfee3-dad3-46ec-aa24-0a8db1324288.png)
![Screenshot 2023-05-03 at 10 55 57 (2)](https://user-images.githubusercontent.com/132443016/235873438-e69fd83e-d029-4d87-be1f-c48bb766f5b1.png)
![Screenshot 2023-05-03 at 11 13 15](https://user-images.githubusercontent.com/132443016/235876916-c989c060-f369-484e-97eb-01739668bf46.png)

These are the pages that are having issues: 
[https://www.dcdd.nl/resources/srhr-quick-guide/#Home]
[https://www.dcdd.nl/resources/data-quick-guide/#Title]

When I created them, they were slow loading for edits, but the pages did actually load. Now there is simply a blank screen. 

I am aware that the pages are large, but as they are online living documents, it requires that I or someone else can edit them when needed. 

I wondered whether there was a way to work around this / speed up the loading / whether there is something specific which I've done that slows the entire page down / whether I need to look into another option for recreating these documents as they are too complex for the website to load when editing.

Please let me know what information you need to look into this issue. It would be greatly appreciated!

Thanks,

Sanne

**Comment by alvarotrigo** [comment]
For support for the Gutenberg plugin, please use the [contact form](https://alvarotrigo.com/contact/).
We'll help you better there. 

Please contact using the email you used for the purchase. 
Thanks!
