### ISSUE TITLE
Lazy loading for picture tag

### ISSUE THREAD

**Issue by kovinet** [alvarotrigo/fullPage.js#4545]
While lazy loading works well with `<img>` tags it has problems with picture tag, since `<source>` elements inside `<picture>` don't have src attribute (but srcset).  

For example:   

```html
<picture>
  <source media="(max-width:480px)" srcset="mobile.jpg">
  <source media="(min-width:481px)" srcset="desktop.jpg">
  <img data-src="default.jpg">
</picture>
```

In the code above image provided in source is loaded on page load.  

Is there a way to lazy load these?

**Comment by alvarotrigo** [comment]
You should use `data-srcset` instead.
