### ISSUE TITLE
Scroll not working on Safari OSX

### ISSUE THREAD

**Issue by edooley** [alvarotrigo/fullPage.js#4547]
Not sure when this started occurring (possibly since my recent OS updates I just ran), but I have just starting having issues on desktop Safari when attempting to scroll. For example, visiting the [fullpage homepage](https://alvarotrigo.com/fullPage/) does not scroll with my trackpad or mouse wheel. Similar to the homepage, I have purchased and installed the dragAndMove extension with it, but removing it doesn't seem to make a difference. I can click-and-drag on OSX Safari and utilize touch events on mobile Safari just fine.

MacBook Pro (Retina, 15-inch, Mid 2015) running 12.6.5 (21G531)

Safari Version 16.4.1 (17615.1.26.101.10, 17615)

**Comment by alvarotrigo** [comment]
> Similar to the homepage, I have purchased and installed the dragAndMove extension with it, but removing it doesn't seem to make a difference. I can click-and-drag on OSX Safari and utilize touch events on mobile Safari just fine.

I'm not sure to understand this.

Are you having a problem with our without the Drag And Move extension?
Or in both cases?

I've tested it with Browserstack.com on Safari 16.3 and everything works ok on the [demo page](https://alvarotrigo.com/fullPage/)
I have no access to Safari 16.4.1 yet so I can test it there.

**Comment by alvarotrigo** [comment]
[Some people report](https://www.reddit.com/r/ipad/comments/1264qls/bug_with_smooth_scrolling_trackpad_on_safari/) this bug takes place on many pages,  so it might not be related to fullPage.js?

**Comment by alvarotrigo** [comment]
You can try turning the smooth keyboard-based scroll feature off in case it's related, as its one of the new additions on Safari 16.4:
https://underpassapp.com/news/2023-4-11.html

**Comment by alvarotrigo** [comment]
More reports complaining about scroll not working on Safari 16.4:
https://forums.macrumors.com/threads/safari-16-4-buggier-than-usual.2386038/

**Comment by edooley** [comment]
Good finds. Yes, probably a Safari bug. FWIW, disabling the new keyboard scrolling feature had no effect. One thing that may be of interest to you @alvarotrigo : I found that if you set a padding or margin on the parent element, I am still able to scroll the fullpage instance when I scroll in the gutters. For example, on the [fullPage homepage](https://alvarotrigo.com/fullPage/), if you apply `padding:100px` to the `body` element, you can use the mousewheel/trackpad if you scroll in those gutters (as long as you aren't hovering over other elements like the nav/arrows/etc). I understand you can't really see for yourself until you can get your hands on 16.4, but perhaps that information can be of use. Thanks.

**Comment by alvarotrigo** [comment]
Interesting... 🤔 
Hopefully, Safari will fix this issue soon! 

Because there are apparently many others experiencing issues it should be something they pay attention to.

**Comment by alvarotrigo** [comment]
I believe this got fixed in Safari some time ago.
Didn't see any more reports on this.
