### ISSUE TITLE
WANTED: fullPage WordPress developer 

### ISSUE THREAD

**Issue by ehydrant** [alvarotrigo/fullPage.js#4551]
I have an old WP site that has been running a hacked up version of fullPage as the homepage for a few years. I need to make some changes to the homepage and need someone that is skilled with fullPage and WP that can do it.

Anyone here?

Thanks guys!

**Comment by alvarotrigo** [comment]
This is not a forum where people gather to talk about fullPage.js :)

It's a repository where people report fullPage.js issues, bugs and feature requests.

Unfortunately I have to close this topic. 
I'd recommend you take a look at the official plugins for [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) and [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/) builders.
