### ISSUE TITLE
Feature request: disable URL hashes

### ISSUE THREAD

**Issue by phil-broussard** [alvarotrigo/fullPage.js#4555]
### Description

I'd like to request a feature to disable adding hashes to the URL. 

### Scenario
Client wants full functionality of your library with the exception that the URL not be updated with the hashes. 

### Our solution 

Add a new config option
setUrlHash: (default: true)

Set these options
recordHistory: false
animateAnchor: false
setUrlHash: false

Wrap the inside of the setUrlHash() with an if statement 

if (getOptions().setUrlHash) {
 original functioncode goes here
}

This gave use the flexibility we needed without breaking the library.

**Comment by alvarotrigo** [comment]
> I'd like to request a feature to disable adding hashes to the URL.

Why don't you just commit the `anchors` option instead?

Or `lockAnchors: true`?
