### ISSUE TITLE
Sections jump between each other when scrolling on mobile (responsive slides)

### ISSUE THREAD

**Issue by phattiej** [alvarotrigo/fullPage.js#4561]
When I scroll on my mobile website the sections begin to jump from one to another and then back again. It looks like a bug. I bought and included the responsiveslides extension and I've also set the scrolloverflow to false. I've tested it on Chrome, Firefox, Safari and Duckduckgo and the results vary between browsers.

I don't really know how I could reproduce this issue without showing the entire code of my website, it's really a small page and I'm using the fullpage license and the fullpage extension responsive slides. What I can do is show videos of each browser (you'll have to click on the google drive link).

In Safari the scroll is alright until you scroll back up it begins to jump, then if I scroll down again the same thing happens:
https://drive.google.com/file/d/1x3h5PlFKv3qgkwVnyaDb9wMZ2sm2grab/view?usp=sharing

In Firefox the behavior is much worse when I scroll down it already starts jumping:
https://drive.google.com/file/d/1Bcwx8CMnNOSfPvEr7bd5buim_mxMpKWk/view?usp=sharing

In Chrome the behavior is pretty alright, slightly jumpy when I start scrolling up:
https://drive.google.com/file/d/11hYxhWyn24vOBURiHFwXoy86hCuh4tip/view?usp=sharing

In Duck duck go the behavior is almost the same as Safari:
https://drive.google.com/file/d/1Fg39GRbFHjmVCWWdj7cU5QzsrpphPnYD/view?usp=sharing

Any help would be much appreciated!

**Comment by alvarotrigo** [comment]
It might be a problem with your `id` or `name` attributes on sections (or anywhere else) matching the value on the `anchors` option.

This was detailed [in the docs](https://alvarotrigo.com/fullPage/docs/#:~:text=Be%20careful!,tags%20can):

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).


You should get an red error in the JS console if that's the case.
If you think that's not the case, then try to reproduce the issue on an isolated environment using [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp).

Remember we also provide premium support for those purchasing the [Business license](https://alvarotrigo.com/fullPage/pricing/) if you need further assistance.

**Comment by phattiej** [comment]
Hello! Thank you for your quick response. I did not see an error in the JS console, and I checked my data-anchor tags.

I'm trying to reproduce this issue on codepen but page jumping doesn't happen in this environment. This is also the case if I test locally. It's only once I've uploaded my code to my file manager and it's viewed through my website do I see this issue. That's why I tested in on every browser.

You can see the codepen here: https://codepen.io/jaime_ah/pen/gOQgzxd

**Comment by alvarotrigo** [comment]
> I'm trying to reproduce this issue on codepen but page jumping doesn't happen in this environment.

Yeah,  the codepen won't be too useful because it's not an isolated reproduction (it contains the code for your whole site) and the issue can't be reproduced on it.

Try simplifying your page to the maximum and see if you can reproduce the issue with the minimum amount of HTML, CSS, and JS code.
Then send the link to the isolated reproduction so I can take a look.

Although I personally would recommend you to remove CSS, HTML and JS code bit by bit until you can't reproduce the issue anymore. It's an easy way to know what's causing the issue ;)

**Comment by phattiej** [comment]
Thanks a lot for the tips! :)

I think I've narrowed down the issue to be something in the sections which have slides. When I simplify the page and remove the other sections without slides the issue still persists, however when I remove the sections with slides the issue is resolved. I still can't get the issue to show up in codepen nor in my browser. It only shows up when scrolling through the website.

https://codepen.io/jaime_ah/pen/gOQgzxd
https://jaimerative.art/

**Comment by phattiej** [comment]
Hello again!

Would you know if there’s anything that can be done for this issue? I tried
to minimise the code to the maximum to reproduce the issue, but as I
mentioned the issue only shows up when the website is live. I found that it
could be related to the sections and slides.

Any help would be appreciated

Best

Jaime

**Comment by alvarotrigo** [comment]
Do you have the problem without the Responsive Slides extension?

**Comment by phattiej** [comment]
Hi, thank you for your response. I just tried to remove the
responsiveslides key and JavaScript reference from my html. But it has no
effect on my website except that it puts back the carousel arrows that are
there before. I still see my sections visible when I scroll and they are
not in slides. I think it’s possible because the key was activated for my
domain?

The jumping issue is still there

**Comment by phattiej** [comment]
And it seems I can’t even remove the extension even if I remove the html 😂

**Comment by alvarotrigo** [comment]
> But it has no effect on my website except that it puts back the carousel arrows that are there before. I still see my sections visible when I scroll and they are not in slides.

If you remove the extension file, then you should see the slides in a horizontal carousel. Not on vertical slides.
If that's not the case, you are probably loading the extension file somewhere else. Look around your code.

**Comment by phattiej** [comment]
I basically removed the line <script type="text/javascript"
src="fullpage/fullpage.responsiveSlides.min.js"></script> from the head of
my html, and I also removed the file from the cpanel. I also commented out
the responsiveSlides key.

<script type="text/javascript">
$(document).ready(function() {
$('#fullpage').fullpage({
licenseKey: 'L78RH-52N58-7FPK9-J0J6H-ATYPP',
/*responsiveSlidesKey:
'VWxhbUZwYldWeVlYUnBkbVV1WVhKMFVkX3JyT2NtVnpjRzl1YzJsMlpWTnNhV1JsY3c9PXg2ZA==',
responsiveSlides: true,*/
responsiveWidth: 769,
scrollOverflow: false,
touchSensitivity: 0
});
});
</script>

The only place I am calling this is in my HTML file.

I also used some CSS to hide certain slides on mobile screens and I moved
them to a new page. The experience is better only because there's less
content to scroll through. However the issue still persists on my main
page. As I mentioned before it seems to only affect the areas with the
<section> tag.

I have a screen recording here:
https://drive.google.com/file/d/1PVh5w5LzYmFDiuQwmQfixBaDU78G2W32/view?usp=sharing

Thank you!

**Comment by alvarotrigo** [comment]
Unfortunately, I can't really tell what's the issue without an isolated reproduction.
It clearly is not on the extension, but it doesn't seem to be a fullPage.js bug too as you didn't manage to reproduce it outside your site.

I'd encourage you to get the [Business license](https://alvarotrigo.gumroad.com/l/fullpage-business) if you want me to inspect your page and figure it out.

**Comment by phattiej** [comment]
I understand that it’s difficult to find an issue without a reproduction
but I did manage to find that it is indeed a full page issue because no
other code that isn’t from full page is causing the problem. It may be
related to the browser but either way, it’s clear that it’s a full page
problem.  It’s also a bit unsettling that I can’t remove the extension.

On top of this I expected a lot better after paying more than 100€ for the
two products. I’m sorry but continuing to pay more to find the issue isn’t
a viable solution for me.

**Comment by alvarotrigo** [comment]
I understand it.

I'll be happy to help whenever we can find a way to reproduce your issue on an isolated page.
So far, we can't assume the issue is in fullPage.js unless we can reproduce this without any external JS and CSS code to fullPage.js.

**Comment by phattiej** [comment]
Okay, I’ll see what I can do. Thanks for your help.Sent from my iPhoneOn 14 Jul 2023, at 01:18, Álvaro ***@***.***> wrote:﻿
I understand it.
I'll be happy to help whenever we can find a way to reproduce your issue on an isolated page.
So far, we can't assume the issue is in fullPage.js unless we can reproduce this without any external JS and CSS code to fullPage.js.

**Comment by phattiej** [comment]
Or I’ll see what we can try! 😅😂Sent from my iPhoneOn 14 Jul 2023, at 10:31, Jaime Holland ***@***.***> wrote:﻿Okay, I’ll see what I can do. Thanks for your help.Sent from my iPhoneOn 14 Jul 2023, at 01:18, Álvaro ***@***.***> wrote:﻿
I understand it.
I'll be happy to help whenever we can find a way to reproduce your issue on an isolated page.
So far, we can't assume the issue is in fullPage.js unless we can reproduce this without any external JS and CSS code to fullPage.js.
