### ISSUE TITLE
Flexbox and Grid Layouts not working in Webflow

### ISSUE THREAD

**Issue by livstrawbridge** [alvarotrigo/fullPage.js#4562]
Hey @alvarotrigo this is my first time using Github so hopefully I'm doing this right.

I've been having some issues getting my content centred in Webflow, using flexbox and grids. 

– I've had a play with verticalCentered: false, as found in the Webflow forums, (plus many other suggestions), but with no luck.
– I've tried the fullPage.js inspector and it says the JS file isn't present but it is.

Also I noticed the 'made with fullpage' text hasn't disappeared even after buying a license.

Can you please help? Thank you :).

**Comment by alvarotrigo** [comment]
Can you explain what you mean by "centering"?
Virtually? Horizontally?
If you can avoid using grid and just use flexbox, that'd probably help.

We can't provide Webflow support here, but if you can reproduce your issue on [codepen](https://codepen.io/alvarotrigo/pen/qqabrp).

> Also I noticed the 'made with fullpage' text hasn't disappeared even after buying a license.

Use the option `credits: {enabled: false}` as detailed [on the docs](https://alvarotrigo.com/fullPage/docs/).

Unfortunately, we don't check personal sites here. You'll need to get the Business license for that from the <a href="https://alvarotrigo.com/fullPage/pricing/"  target="_blank">fullPage pricing page</a>. Then contact us using the [contact form](https://alvarotrigo.com/contact/) and the email used for the purchase.

**Comment by livstrawbridge** [comment]
@alvarotrigo Yes I mean centering in the middle, so justified horizontally in the centre (in flexbox)
I have purchased a professional license – it says that includes basic Github support?
