### ISSUE TITLE
gif not load

### ISSUE THREAD

**Issue by lollopanta** [alvarotrigo/fullPage.js#4564]
### Description
my gif appears for an instant and disappears. if remove script and style of fullpage.js it works. (main.css is blank). if need i use express js and in js file there is the code.

### Link to isolated reproduction with no external CSS / JS
(https://codepen.io/lollopanta/pen/MWzmamV)

### Steps to reproduce it
there is no step to repruduce it in my code find all you need

### Versions 
chrome 114.0.5735.199 64 bit, windows 11 pro, desktop pc pc with rtx 3060 16gb ram i7

**Comment by alvarotrigo** [comment]
Your gift image is on the `head` of the page?

``html

<head>

    <img src="https://s11.gifyu.com/images/SQrnM.gif" alt="logo">

``` 

This makes no sense. It should be on the `body`.

**Comment by lollopanta** [comment]
i want it always in screen

**Comment by lollopanta** [comment]
stack over flow community say go here lol

**Comment by alvarotrigo** [comment]
As I said, it's not a fullPage.js issue. 
You just shouldn't place any images on the head of the page. 

fullPage.js requires you to know the basics of HTML and JS.

**Comment by lollopanta** [comment]
last things if i want an element always on top
what i need to do
