### ISSUE TITLE
Water effect not working 

### ISSUE THREAD

**Issue by E-Baler** [alvarotrigo/fullPage.js#4565]
Hello,

I use fullpage.js elementor plugin and I wanted to use the water effect (license and activation ok of the full pack). 

Parallax effect works perfectly but when I want to use the water effect I can't scroll and the mouse effect doesn't work either.

After several attempts, I decided to go to the "https://alvarotrigo.com/fullPage/extensions/water-effect.html" site to check that the effect worked on my computer.

 Unfortunately, **even on the official site**, it doesn't work and I stay on the first slide without being able to scroll. 

I tested with 5 different browsers (chrome, vivaldi and arc - same engine, firefox and safari) on macos monterey and same result.

Here's the error that appears in the console:

Uncaught ReferenceError: PIXI is not defined
    at _0x1489a1.init (fullpage.waterEffect.limited.min.js:1:44020)
    at Kt (fullpage.extensions-v3.min.js:8:41994)
    at fullpage.extensions-v3.min.js:8:14025
    at new <anonymous> (fullpage.extensions-v3.min.js:8:14123)
    at water-effect.html:344:197
    at water-effect.html:344:3955
_0x1489a1.init @ fullpage.waterEffect.limited.min.js:1
Kt @ fullpage.extensions-v3.min.js:8
(anonyme) @ fullpage.extensions-v3.min.js:8
(anonyme) @ fullpage.extensions-v3.min.js:8
(anonyme) @ water-effect.html:344
(anonyme) @ water-effect.html:344

My question is: 

does the problem come from me (if so, I'm sorry for taking up your time...) or does the problem come from the plugin (I don't think so)?

Thank you for your help,

Regards

Mac os Monterey, iPhone ios 15 and ios 16

**Comment by alvarotrigo** [comment]
Hi there,

We actually stopped selling the water effect some time ago. 
We've removed it from the [extensions page](https://alvarotrigo.com/fullPage/extensions/) but we might have forgotten some other links.

The demo page hasn't been updated with fullPage.js V4 and that caused the demo to stop working.

You can use the [contact form](https://alvarotrigo.com/contact/) to contact us for a refund or ask for some support for your specific page. The effect should work as long as you use local images and the [official WordPress plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/) or [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/).
