### ISSUE TITLE
Impossible to modify arrow css on slideLoad javascript

### ISSUE THREAD

**Issue by leccyril** [alvarotrigo/fullPage.js#4566]
It is more a question than a bug

i want to display only one arrow and only ine one slide (ON THE SLIDE SECTION) WHEN WE JUMP LEFT TO RIGHT

I have a website with 11 section vertical and 2 slide horizontal, then i want to display only the previous arrows (and specific arrow) only on the second slide on X section

i am using nuxt js, each slide and section have scoped css

i tried to use the onSlideLoad to override CSS to if we go in right direction to display the arrow, but nothing happen, i tried also simply to change the arrow css on slideLoad but nothing happen 

```
<script lang="ts" setup>

const options = {
	licenseKey: '',
	navigation: true,
    fitToSection: true,
	credits: { enabled: false },
	continuousVertical: false,
	continuousHorizontal: true,
	controlArrows: true,
	controlArrowsHTML: [
		'<div class="fp-arrow"> <img id="back" class="back" src="/images/contactUs11/arrow-back.png"/> </div>', '<div class="fp-arrow"> </div>'],
	afterSlideLoad: function( section, origin, destination, direction, trigger){
		document.getElementById("back").style.width = '500px!important';
	},

	anchors: [ 'SectionIntro1', 'SectionCarbon2', 'SectionAdvantages3', 'SectionPreorder4', 'SectionScience5', 'SectionCreateEqual6', 'SectionManufacturing7', 'SectionLayerCarbon8', 'Section9', 'SectionInstagram10', 'SectionContactUs11', 'Footer' ],

}

</script>
```

Any idea ?

**Comment by alvarotrigo** [comment]
Can you provide an isoalted reproduction of your issue in codepen or codesandbox?

There shouldn't be any problem overwriting the CSS. 
Just make sure you use the CSS property `!important` if necessary. 

You can also create your own custom arrows if that helps  you out too. Check out the option [`controlArrowsHTML`](https://alvarotrigo.com/fullPage/docs/#:~:text=right%20or%20left.-,controlArrowsHTML,-%3A%20(default)

**Comment by leccyril** [comment]
it join this ticket
https://github.com/alvarotrigo/fullPage.js/issues/4567

PS could we add an option to say on the first slide we do not want the arrow if for example we navigate with a button ?

**Comment by alvarotrigo** [comment]
> PS could we add an option to say on the first slide we do not want the arrow if for example we navigate with a button ?

That looks like a very specific use case, so probably not something that makes much sense to add as an option.
It can be done with your own logic using callbacks or functions.

**Comment by leccyril** [comment]
I tried. Ut not working the override of callback



Envoyé depuis mon appareil Galaxy



-------- Message d'origine --------
De : Álvaro ***@***.***>
Date : 18/07/2023 20:12 (GMT+04:00)
À : "alvarotrigo/fullPage.js" ***@***.***>
Cc : leccyril ***@***.***>, State change ***@***.***>
Objet : Re: [alvarotrigo/fullPage.js] Impossible to modify arrow css on slideLoad javascript (Issue #4566)


PS could we add an option to say on the first slide we do not want the arrow if for example we navigate with a button ?

That looks like a very specific use case, so probably not something that makes much sense to add as an option.
It can be done with your own logic using callbacks or functions.

**Comment by alvarotrigo** [comment]
Happy to take a look at an isolated reproduction of the issue in codepen.
Let me know when you have one.
