### ISSUE TITLE
Arrow override is not working (old one still displayed)

### ISSUE THREAD

**Issue by leccyril** [alvarotrigo/fullPage.js#4567]
### Description

We override arrow picture, but old one style displayed

![image](https://github.com/alvarotrigo/fullPage.js/assets/3234598/b3bad53b-bb94-4a4b-9d40-c95356826711)

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/p/sandbox/fullpagebug-9tuyly?file=%2Fpages%2Findex.vue

### Steps to reproduce it
Create a small project
create 2 sections
create 2 slides in the first section
override arrows pictures

### Versions 
"@fullpage/nuxt-fullpage": "^0.2.4",

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
I'll take a look at this

**Comment by alvarotrigo** [comment]
Ok, looking at it I just noticed you are still using the fullPage.js class  prefixed by `fp-`.
All you have to do is remove the class `fp-arrow` from your custom arrow HTML and replace it for any other class you want to add  (if any).
