### ISSUE TITLE
Normal scroll before fullpage

### ISSUE THREAD

**Issue by lambdaka** [alvarotrigo/fullPage.js#4569]
Hi everyone

I would like to start with a normal part of a website, and when the fullpage container hit the top of the page, to begin the full page experience.

If I use scrollOverflow:true ;
the first automatic section will start at the bottom of the page.

let me know if you need more explanation of what I want to achieve..!?

Thanks

**Comment by alvarotrigo** [comment]
You can mimic this behavior by having your normal page inside the first section.
If you use scrollOverflow then a scrollable section will be created and you'll have the same experience as in a normal page.

Then you can place the rest of the fullpage  sections underneath the first section.

**Comment by lambdaka** [comment]
Hi Alvaro

Thanks for the suggestion.

I can make it work when I use simple HTML elements in the first scrollOverflow section.

But as my first section is a gsap scrolltrigger in canvas ; I can’t make it work..

Is that something you could be interest to make it work? With a fee of course.

Best
S.

**Comment by alvarotrigo** [comment]
> Is that something you could be interest to make it work? With a fee of course.

Unfortunately, I don't have the time for it
But I'm sure you'll be able to find other developers that can help you with that. 

If you still have any questions regarding the use of fullPage.js let me know.
