### ISSUE TITLE
Question: how to deactivate parallax effect on mobile please?

### ISSUE THREAD

**Issue by E-Baler** [alvarotrigo/fullPage.js#4570]
Hello, 

I'm having a little problem with fullpage and elementor. 

I deactivated fullpage from 500 px (so just for mobiles). This works without a problem, but the parallax plugin of fullpage continues to work on background images and this destructures the site.

My question is: is it possible to disable plugins (parallax) like fullpage.js depending on the viewport please?

Thank you!!!

**Comment by alvarotrigo** [comment]
> My question is: is it possible to disable plugins (parallax) like fullpage.js depending on the viewport please?

Sure, use the destroy method under your custom conditions using callbacks  like `afterResponsive ` or `afterResize`.

https://github.com/alvarotrigo/fullPage.js/wiki/Extension---Parallax#destroy


```js
fullpage_api.parallax.destroy();

```

**Comment by E-Baler** [comment]
Ok thanks a lot !!!!

**Comment by vxsilis** [comment]
how did u deactivated fullpage on specific px ?

**Comment by alvarotrigo** [comment]
> how did u deactivated fullpage on specific px ?

You can use the [`destroy`](https://github.com/alvarotrigo/fullPage.js/wiki/Extension---Parallax#destroy) function for that.

Something like this:

```js
new fullPage('#fullpage', {
    responsiveWidth: 900,
    afterResponsive: function(isResponsive){
        if(isResponsive){
             fullpage_api.parallax.destroy();
        }
        else{
            fullpage_api.parallax.init();
         }
});
```
