### ISSUE TITLE
water effect demo page doesn't work

### ISSUE THREAD

**Issue by Debesyla** [alvarotrigo/fullPage.js#4573]
### Description
Hey, getting console errors in the official water demo page.

```
fullpage.waterEffect.limited.min.js:1 Uncaught ReferenceError: PIXI is not defined
    at _0x1489a1.init (fullpage.waterEffect.limited.min.js:1:44020)
    at Kt (fullpage.extensions-v3.min.js:8:41994)
    at fullpage.extensions-v3.min.js:8:14025
    at new <anonymous> (fullpage.extensions-v3.min.js:8:14123)
    at water-effect.html:344:197
    at water-effect.html:344:3955
```

### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/extensions/water-effect.html

### Versions 
Chrome, Windows 10.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll take a look as soon as I can.

However, we've stopped selling the water effect extension, so I'll be removing it from the docs too.

**Comment by alvarotrigo** [comment]
Water effect is no longer available.
