### ISSUE TITLE
Add/Removed Sections Skipped on Scroll

### ISSUE THREAD

**Issue by AndrewStephenMarkham** [alvarotrigo/fullPage.js#4575]
As I scroll horizontally through slides, I would like to change the section below that slide to display relevant information.  I am currently reading the destination slide, then adding/removing sections with 'display'.  Doing this I experience unexpected behavior.  

[codepen demo
](https://codepen.io/Andrew-Markham/pen/bGOwqjL)

1. Scrolling from _Section 0_ down to _Section 1: Slide 0_ down to _Section 1: Slide 0 Info_ works like I would expect.
2. Scrolling from _Section 0_ down to _Section 1: Slide 0_ right to _Section 1: Slide 1_ and then down sends me up.  

In addition to sending me up initially, when I do manage to eventually scroll down it scrolls past these added sections.  The content is correct, but it skips past them.  Hopefully I am missing something simple, any help is appreciated!

Chrome: Version 116.0.5845.140 (Official Build) (x86_64)

**Comment by alvarotrigo** [comment]
If I understood you correctly, you probably want to use the [Interlocked Slides extension](https://alvarotrigo.com/fullPage/extensions/interlocked-slides.html). 
This way, you'll be able to automatically sync horizontal slides between different sections.

Your use case can be a bit tricky to debug.

**Comment by AndrewStephenMarkham** [comment]
Hi Alvaro, thank you for the response!

Is there a way to disable the slide navigation arrows by section, so that when you arrive at the interlockked slide it essentially "hides" the slides left/right of it?

**Comment by alvarotrigo** [comment]
> Is there a way to disable the slide navigation arrows by section,

Sure, just use `controlArrows: false` on your fullPage.js initialisation.
