### ISSUE TITLE
Scroll Overflow breaks website layout when using Elementor Flexbox

### ISSUE THREAD

**Issue by sawine** [alvarotrigo/fullPage.js#4577]
When using the scroll overflow feature with Elementor Flexbox feature, it breaks the page layout. It somehow stretches the sections horizontally and breaks them.

You can see how it breaks the page here:
https://nuiq2.asban.dev/homepage-broken/

How the page is supposed to look:
https://nuiq2.asban.dev/

Another test of scroll overflow using regular Elementor Sections (no Flexbox) (works fine)
https://nuiq.asban.dev/

Is there some setting we need to enable to make it compatible with Flexbox ?

Thanks

**Comment by alvarotrigo** [comment]
If you purchased the [official fullPage.js plugin for Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/), can you please send your query using the [contact form](https://alvarotrigo.com/contact/)?

We'll take a look at your site and your problem.

Thanks!

**Comment by E-Baler** [comment]
> When using the scroll overflow feature with Elementor Flexbox feature, it breaks the page layout. It somehow stretches the sections horizontally and breaks them.
> 
> 
> 
> You can see how it breaks the page here:
> 
> https://nuiq2.asban.dev/homepage-broken/
> 
> 
> 
> How the page is supposed to look:
> 
> https://nuiq2.asban.dev/
> 
> 
> 
> Another test of scroll overflow using regular Elementor Sections (no Flexbox) (works fine)
> 
> https://nuiq.asban.dev/
> 
> 
> 
> Is there some setting we need to enable to make it compatible with Flexbox ?
> 
> 
> 
> Thanks
> 
> 

Hello, I confirm with flexbox the header doesn't overlap containers which are under fullpage. The solution that I found is to stick the header via fullpage's global settings. and I confirm too with regular section no problem...

**Comment by alvarotrigo** [comment]
Thanks @E-Baler ! 👍
