### ISSUE TITLE
On some safari and apple dekstop mouse scroll dont work

### ISSUE THREAD

**Issue by MrJoakimHan** [alvarotrigo/fullPage.js#4578]
### Description
On our site https://restaurantnour.se/ the mouse scrolling dont work on some apple computers and safari

### Versions 
[Browser, operating system, device, ...]
MacOS 13.4.1
Safari v. 16.5.2

**Comment by alvarotrigo** [comment]
Can you update to the latest fullPage.js version 4.0.20?
You are currently using version 3.1.2 which is no longer maintained.

**Comment by alvarotrigo** [comment]
I'm closing this because we lack the details to keep on investigating it.
