### ISSUE TITLE
after install :2 vulnerabilities (1 moderate, 1 high)

### ISSUE THREAD

**Issue by urban-hostel** [alvarotrigo/fullPage.js#4580]
# npm audit report

fullpage.js  <=4.0.4
Severity: high
Cross-site Scripting in fullpage.js - https://github.com/advisories/GHSA-h3cq-j957-vhxg
Prototype Pollution in fullpage.js - https://github.com/advisories/GHSA-vpgw-ffh3-648h
No fix available
node_modules/@fullpage/angular-fullpage/node_modules/fullpage.js
  @fullpage/angular-fullpage  *
  Depends on vulnerable versions of fullpage.js
  node_modules/@fullpage/angular-fullpage

2 vulnerabilities (1 moderate, 1 high)

Some issues need review, and may require choosing
a different dependency.

**Comment by alvarotrigo** [comment]
That will only affect versions <= 4.0.4.
Current version of fullPage.js is 4.0.20 so we are fine :) 

Only the Angular wrapper that still uses fullPage.js version 3 gets affected by this. 
But we've already clarified this on the [angular-fullpage repo](https://github.com/alvarotrigo/angular-fullpage/issues).
