### ISSUE TITLE
Can't swipe slides when trying to swipe on fixed element.

### ISSUE THREAD

**Issue by BartoszHor** [alvarotrigo/fullPage.js#4582]
### Description

It seems similar issue -> https://github.com/alvarotrigo/fullPage.js/issues/1912 but nothing here helped.

I am trying to swipe slides by touching on fixed area but it does not work as expected (see attached video). Fixed area is child of <ReactFullpage.Wrapper>.

Props used on <ReactFullpage component are:

```
        scrollBar={true}
        pluginWrapper={pluginWrapper}
        licenseKey={clientEnv.NEXT_PUBLIC_FULLPAGE_LICENSE_KEY}
        scrollHorizontallyKey={
          clientEnv.NEXT_PUBLIC_FULLPAGE_SCROLL_HORIZONTALLY_EXTENSION_ACTIVATION_KEY
        }
        dragAndMoveKey={
          clientEnv.NEXT_PUBLIC_FULLPAGE_DRAG_AND_MOVE_EXTENSION_ACTIVATION_KEY
        }
        dragAndMove
        scrollHorizontally
        scrollingSpeed={500}
        css3={false}
        credits={{
          enabled: false,
        }}
        controlArrows={false}
        loopHorizontal={false}
        onSlideLeave={(section, origin, destination) => {
          setActiveSlideIndex(destination.index);
        }}
        afterResize={(width, height) => {
          setWindowSize({
            width,
            height,
          });
        }}
```

I tried to use `normalScrollElements` prop and passed `id` of fixed element but it also did not help. 

I am using Chrome on Mac OS.

https://github.com/alvarotrigo/fullPage.js/assets/64915566/29485da5-bf95-41eb-9077-5d1a6847919c

Any ideas on how to overcome it? Is that even possible?

**Comment by alvarotrigo** [comment]
Just to have it clear. 

Are you referring to the fact that the slides will move while dragging the mouse / finger, but when releasing it, it will not slide to the right side and will instead bounce back to the origin?

**Comment by alvarotrigo** [comment]
So, basically, you want to be able to scroll when swiping on a fixed element "external" to the horizontal/vertical sections. 
Am I correct?

**Comment by alvarotrigo** [comment]
I've fixed this on the DragAndMove extension version 0.1.4
