### ISSUE TITLE
Implementation on Editor X Velo (Wix)

### ISSUE THREAD

**Issue by catalytic-creator** [alvarotrigo/fullPage.js#4583]
I sincerely apologize for posting such a generic unspecified issue, but per your Help section post ["Use fullpage.Js on Wix"](https://alvarotrigo.com/fullPage/help/use-fullpage-js-on-wix/), this is the place to do it.

I am honestly not a programmer or coder. I'm a web designer and graphic designer using Editor X whose client has entrusted to execute full-page responsive scroll snap across all screen sizes, which I successfully executed for desktop [with the help of the second method from this YouTube video](https://www.youtube.com/watch?v=DPBIviTtbC8) but it's a disaster on mobile. 

The code specified in your post ["Use fullPage responsive mode and keep snap scroll effect"](https://alvarotrigo.com/fullPage/help/use-fullpage-responsive-mode-and-keep-snap-scroll-effect/) seems simple enough, though I am admittedly such a novice that I simply don't understand where to start with it and I fear damaging the site without guidance. So, per your instructions in the Wix post above, I'm creating a topic in the forum because I do indeed have doubt while integrating.

For reference, my breakpoints are currently set at 1001px and up for desktop, 751-1000px for tablet, and 320-750px for mobile. My sections all have varying viewport heights with a minimum of 100. 

If anybody could please help me figure out how to implement the plugin, I would be sincerely grateful. Thank you.

**Comment by alvarotrigo** [comment]
Why do you need the responsive mode exactly?
Are you planning to use any of its features such as disabling snap scroll on mobile or using Responsive Slides extension?

What do you exactly mean when you say, "it's a disaster on mobile"?
Can you be more specific? What exactly is not working as you expect?

To learn how to use fullPage.js, you can find the **full documentation** on how to use fullPage.js on the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a> together with tens on examples on codesandbox or [on HTML files](https://github.com/alvarotrigo/fullPage.js/tree/master/examples).

What exactly are you missing in those?

**Comment by catalytic-creator** [comment]
Thank you for your response and I apologize for the delay in getting back to you. I was unaware of the fullpage.js documentation so I tried to give it a shot using the resources you've compiled, but I'm a bit lost again.

I don't think I have a more comprehensive answer for you as to why exactly I need the responsive mode than my client thinks it looks really cool and he's invested quite a bit in this site, and his vision has always included scroll snap for mobile because he's convinced most everyone is using mobile these days and that's where his customers will come from. So I just don't want to let him down on this one, and after failing with one method, my research led me to fullPage.js.

If I can't figure out how to make scroll snap seamlessly functional on mobile, then yes, I would be using the feature to disable it on mobile and tablet. Otherwise, I don't believe we need any sophisticated features. The site has complex custom forms embedded with iFrames, but besides those, the layout is pretty vanilla:

- Home page has five sections with alternating background colors #FFFFFF and #F2F2F4. In order from top to bottom, viewport heights are: 110, 100, 135, 100, 115.4.
- Seven pages have one section and therefore have no need for scroll snap.
- Contact page has two sections with background colors #FFFFFF and #F2F2F4 and viewport heights of 102 and 100. It would be preferred to use scroll snap here but it isn't entirely necessary.

To answer your question about why the code from the YouTube video is a disaster, the biggest issue is it jumps all over the place without prompting, jerks up and down with glitches, skips over the section you want, sometimes just scrolls through all 5 sections on its own. It does this on desktop too depending on the size and dimensions of your browser screen. It's just a mess.

I bought a license key and used npm to install fullPage in Editor X Velo. I copied the complex code with the options from your documentation and tried my best to guess which elements of the code to individualize, but I'm failing. I'm not getting error messages in the code except "menu" says "Parsing error: unexpected token menu" but it isn't snap scrolling anywhere. As this is my first venture into coding as a designer, it's admittedly pretty confusing and frustrating for me.

Thank you again for trying to help. I appreciate your guidance.

**Comment by catalytic-creator** [comment]
Some more site data in case it's helpful to you to provide more concise answers to save your time and effort than to detail what goes where and why. If it isn't helpful, please disregard. Thanks.

**Breakpoints:** Mobile 320-750, Tablet 751-1000, Desktop 1001+

**Mobile Viewport Heights:** 100, 107, 123, 100, 176 (Home page). 162, 115 (Contact page)

**Tablet Viewport Heights:** 110, 100, 115, 100, 120 (Home page). 111, 100 (Contact page)

Not even sure if this is helpful but thanks again for reviewing.

**Comment by catalytic-creator** [comment]
@alvarotrigo Yes, Álvaro, I am indeed quite confused here. That is why I reached out for help. Because as I have mentioned, I am not a programmer, this is my first experience with code, and while under pressure to complete the site in a timely manner, I'm wasting a lot of time trying to understand the documentation because as many times as I read it over the three days I took to respond to your first message, there is a bounty of words, phrases, and verbiage that as a designer, I simply do not recognize.

Thank you for clarifying my confusion about responsive mode. That is great to hear. It seems like all I would need is a very vanilla, bare bones operation of your plugin. Editor X uses only JS, it appears that HTML is unreadable by the terminal.

I don't understand the Examples folder. I see one .js file and the code renders several errors. 

I've tried defining the Anchors, perhaps I'm doing it wrong, but no scroll. I've tried defining sectionSelector, I don't know what I'm doing, and no scroll.

If you can please help **a complete novice** by pointing them in a precise direction of which code(s) would initiate snap scroll, then I can figure out all of the methods, callbacks, everything else out myself.

**Comment by catalytic-creator** [comment]
Since you're unfamiliar with Editor X, I am more than happy to answer whichever questions would help you instruct me to run the absolute most basic elements of your plugin. Please sympathize with my confusion. Thank you.

**Comment by alvarotrigo** [comment]
I can't explain to you how HTML and JS work. 
But I can't point you to the example where you can see how to use fullPage.js.

Take a look at this file:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/simple.html

Then all you have to do is use the same JS code in Editor X and try to replicate the same HTML structure.

Then include the fullpage.min.js file and the fullpage.min.css file from a CDN:
https://unpkg.com/fullpage.js@4.0.20/dist/fullpage.min.js
https://unpkg.com/fullpage.js@4.0.20/dist/fullpage.min.css

That should do the trick.
If you have further questions on how to use JS or create specific HTML structure in Editor X, you can ask in other places where they know about Editor X and how it works.

**Comment by catalytic-creator** [comment]
Hi Álvaro. Just for your information, I've spoken to certified Editor X Velo programmers who say fullPage.js is incompatible with the Velo code.

Take care.

**Comment by alvarotrigo** [comment]
> Hi Álvaro. Just for your information, I've spoken to certified Editor X Velo programmers who say fullPage.js is incompatible with the Velo code.

I'd be surprised if that's the case.

The dev mode, as far as I know through your video, allows you to add JS code.

And the rest of the interface, if it's similar to Webflow (which seems to be the case) should allow you to create the required HTML structure.
https://youtu.be/LZSQb6hHw5E?t=53

But i might be wrong :)
