### ISSUE TITLE
Use focus() after changing sections

### ISSUE THREAD

**Issue by Nikodemsky** [alvarotrigo/fullPage.js#4585]
### Description
I'm trying to use focus on buttons when transitioning from one section to another vertically, thing is that i'm not sure how to do that. afterSlideLoad works only for slides that moves horizontally, which i don't use and callbacks like on onLeave(it fires too soon i guess?)  causes things like fixedElements dissapearing or height miscalculations.

The goal is to keep user on buttons OR forms inputs even after changing sections, but i can't get that to work.

I'm using standard fullpage html structure:
```
<div id="fullpage">
<div class="section"></div>
<div class="section"></div>
</div>
```

Question is - how do i achieve that?

**Comment by alvarotrigo** [comment]
> afterSlideLoad works only for slides that moves horizontally,

What about using [`afterLoad`](https://alvarotrigo.com/fullPage/docs/#afterload-origin-destination-direction-trigger)?
