### ISSUE TITLE
Zooming can break the layout and cause content to overlap, some appear to have scroll bars

### ISSUE THREAD

**Issue by kelilive** [alvarotrigo/fullPage.js#4586]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
Feel free to write about the case files in the examples folder, and if you zoom in and out you'll see that you can't keep the scrollbars always free or the content doesn't overlap. With Bootstrap it's perfectly fine.

### Versions 
4.0.20

**Comment by alvarotrigo** [comment]
Can you clarify how you zooming?
Ctrl+ ? 
Ctrl + mouse wheel?

**Comment by kelilive** [comment]
I'm sorry, but it doesn't seem to make much sense to emphasize what to do, as a lot of routine operations can be problematic.

You don't seem to be a responsive layout template, and it doesn't seem to be quite like an adaptive layout (or equal scale) template, because it doesn't fit into a layout in a variety of situations, such as scaling. I'm currently working on a big screen project to be able to visualize it all the time, no matter what device.

**Comment by alvarotrigo** [comment]
I'm sorry too :D
