### ISSUE TITLE
Android Chrome on "enter" it jumps to next slide having input

### ISSUE THREAD

**Issue by sandeepk9635** [alvarotrigo/fullPage.js#4587]
each section as one common input component 

so for the input component, i have an input tag and it has an onKeyPress prop which checks for condition 
so issue is, that only while on Android Chrome, onFocus input the keypad open up,
while clicking on enter in the keypad, it's not checking for onKeyPress and directly goes to next section having the same input component and focusing on the input

**Comment by alvarotrigo** [comment]
It can be reproduced here:
https://codepen.io/alvarotrigo/full/XWOjwwY

On the standalone fullPage.js library. No need for React.

**Comment by sandeepk9635** [comment]
Hey Alvaro,

Thanks for getting back to me.

When can I expect the bug to be sorted out?

Thanks

**Comment by alvarotrigo** [comment]
> When can I expect the bug to be sorted out?

No idea. I haven't taken a deep look at it yet. I'll do it next week.
But if you want to give it a go feel free! The code is all open :)

**Comment by alvarotrigo** [comment]
I've taken a look at the issue and it seems the easiest fix for you is to use `inputmode="search"` on the `input` element.

Like this:

``` 
<input type="text" name="demo" inputmode="search" /> 
```  

This way you'll be able to capture the key down event and it won't act like a "tab". 

Let me know if that works for you.

**Comment by sandeepk9635** [comment]
Thanks for looking into It,
I have used enterkeyhint="go" on the input element, and that is working
haven't tried inputmode="search"

**Comment by Vue-events-embarrassing5** [comment]
The truth is known https://javascripter.space/questions/please-input-javascript-into-chrome
