### ISSUE TITLE
Scroll-down becomes disabled on fp-section containing video at viewport widths over 1130px when class .fp-overflow is present

### ISSUE THREAD

**Issue by rubymused** [alvarotrigo/fullPage.js#4589]
### Description
We're using fullpage.js on https://cmgsite.com. When the viewport width is  1130px or above, the 2nd fp-section does not scroll down. (Curiously it does scroll back up.) At viewport widths below 1130px it scrolls fine in both directions. 

What is unique to the 2nd fp-section is that it contains a video and some related styling, such as a full-screen overlay containing the video controls. 

What I've noticed at the 1130px breakpoint is that the ".fp-overflow" class is added to the section. If I remove that class, everything works fine (after scrolling up and back down to the 2nd section). If I leave the class but just remove the CSS related to that class (in the web inspector), the problem still exists.

I'm wondering if there is js behavior responding to the presence of that class that could be causing this behavior.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. Set your viewport width at 1130px or above
2. Load the site: https://www.cmgsite.com/
3. Scroll down to the 2nd section
4. Try to scroll down to the 3rd section: doesn't work
5. Shrink the viewport to below 1130px 
6. Try to scroll down to the 3rd section: works

### Versions 
Chrome, Firefox, Safari on multiple versions of Mac OS and Windows, i.e., seemingly everywhere.

**Comment by alvarotrigo** [comment]
Make sure to use the latest version 4.0.20 for both the JS and the CSS file.
You are currently using 4.0.7.

Let me know if you still have issues after the update.

**Comment by rubymused** [comment]
Thank you, I will update, though I seem to have fixed it by setting scrollOverflow to false.
