### ISSUE TITLE
site purchase incompatible files

### ISSUE THREAD

**Issue by imarkdesigns** [alvarotrigo/fullPage.js#4592]
Hi... this issue is referring to my entry from #4591 and you've mention that i need to have all the latest files. however, i need to downgrade my fullpage.js to 3.1.2 because I purchased the extension that is compatible only to 3.

Here's the problem i guess, people purchase the version 4 of fullpage js and will purchase scrollHorizontally v3 but here's the catch:`fullpage.js Scroll Horizontally Extension 0.0.4 for fullPage.js v3`. I registered & got the license key for my staging... and soon i will purchase another one for the live site. I am wondering if you're aware of the versions you have in your gumroad.

Now we use the version 3.1.2 so that to make sure the scroll Horizontally works with the fullPage version. But the problem here is the ability to view the overflow content in the fullPage version 3.1.2. I am forced to go back with version 4 to be able to make the content overflow works to smaller browser size (normally their browsers height is max at 925px).

I'm very confused now here. I'm trying to catch the clients before Thanks giving to present this staging site.

**Comment by alvarotrigo** [comment]
When did you buy the extension?
We actually provide both versions when you purchase the extension. The v4 and the v4, here's a screenshot of the content of the Scroll Horizontally extension, notice the "for-fullpage-v3" zip file:

<img width="890" alt="image" src="https://github.com/alvarotrigo/fullPage.js/assets/1706326/1ab296c1-80f9-4983-8034-3b2969d6bc93">

But I'd recommend you use the v4, as we don't provide support for v3 anymore.

**Comment by alvarotrigo** [comment]
For more personalized support regarding extensions, please use the [contact form](https://alvarotrigo.com/contact/).
There you can share with us your purchase details so we can help you in a better way.
