### ISSUE TITLE
normalScrollElements issue

### ISSUE THREAD

**Issue by KnifeLemon** [alvarotrigo/fullPage.js#4594]
### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### In Mobile
1. go to last slide ( normalScrollElement )
2. try move to previous slide
3. can't not move previous slide in normalScrollElements

### in PC
1. scroll to last slide ( normalScrollEment )
2. try scroll to bottom
3. will be moved to the first slide
 
### Versions 
Using CDN - 4.0.20

Mobile : Chrome
PC : Edge Browser

try : http://bit.ly/4806qWi

**Comment by alvarotrigo** [comment]
As the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a> point out referring to the `normalScrollElements` option:

> This option should not be applied to any section/slide element itself.

If you want scrollable sections ou should be using the option `scrollOverflow`
