### ISSUE TITLE
scrollOverflow overscroll behavior

### ISSUE THREAD

**Issue by hiaselhans** [alvarotrigo/fullPage.js#4597]
### Description

Thanks for this awesome library.
This issue is more a question than a bug report.

I am having issues with overscroll behavior on custom "slides" that are implemented similar to how fullPage implements its slides.
The problem i am facing is, that the mouse wheel focus or "overscroll" does not focus on the slide. the scrollOverflow example seems to do that perfectly but i am struggling to see how this problem is addressed in fullPage.js.
I saw that you are using focus() in [src/js/scrolloverflow.js](https://github.com/alvarotrigo/fullPage.js/blob/3201d4afdd675056b73f70c3eee14a89f8dafd76/src/js/scrolloverflow.js#L127) but it looks like that is primarily for keyboard navigation.

I would be very happy if you can give me a little hint on how this is achieved in fullPage.js.

Thanks!

**Comment by alvarotrigo** [comment]
The focus should work.

If it doesn't, I'd recommend you to ask those kind of questions in other places where they'll be able to help you better, such as stackoverflow.com

Here, we only treat fullpage.js-related issues.
