### ISSUE TITLE
How to do multiple full pages in webflow?

### ISSUE THREAD

**Issue by mzakzok** [alvarotrigo/fullPage.js#4598]
Hi Alvaro
How to do multiple full pages in one page in Webflow?
could you  provide step-by-step instructions

here is a link showing my structure 
https://preview.webflow.com/preview/buy-cheap-bike?utm_medium=preview_link&utm_source=designer&utm_content=buy-cheap-bike&preview=1a267170c836e45f15fe616487a1c7b3&pageId=658a9ca5ecbc3a7acd50326e&workflow=preview

and here is the page URL 
https://www.buycheapbike.com/home-modified-copy

the full page inside section 2 does not work.
What is the problem?

Thanks

**Comment by alvarotrigo** [comment]
@mzakzok there can only be a single fullPage.js initialisation on the whole page.
So I'm not sure what you mean by "multiple full  pages".

To learn how to use fullPage.js in Webflow you can check this tutorial:
https://alvarotrigo.com/blog/how-to-use-fullpage-in-webflow-create-full-screen-slider/ 

And these two clonables:
- https://webflow.com/made-in-webflow/website/Fullpagejs-basic-example
- https://webflow.com/made-in-webflow/website/fullPagejs-Horizontal-Slides

**Comment by mzakzok** [comment]
Hi Alvaro
You give a solution for similar question in this post, but i don't know how to implement it
https://github.com/alvarotrigo/fullPage.js/issues/2720

**Comment by alvarotrigo** [comment]
As the solution there indicates, you just have to destroy the first instance  before you initialise the next.

For example:

```js

// initialise for page 1
new fullpage('#page1', {scrollingSpeed: 700});

// destroy the current instance (can be called on page change, on toggle divs etc)
fullpage_api.destroy('all');

// initialise 2nd instance
new fullpage('#page2', {scrollingSpeed: 5000});
```

**Comment by alvarotrigo** [comment]
Here's a demo of the destroy function:
https://codepen.io/alvarotrigo/pen/bdxBzv

**Comment by mzakzok** [comment]
I couldn't do it myself, I need you to apply this directly to my website for my specific case,  Could you do it , and how much will I pay you?

**Comment by alvarotrigo** [comment]
> I need you to apply this directly to my website for my specific case, Could you do it , and how much will I pay you?

Unfortunately, I don't provide that kind of service. 
But I'm sure you'll find someone who does :)
Any web developer should be able to help you with  those.
