### ISSUE TITLE
Internal linking not working in webflow page that use fullpage.js

### ISSUE THREAD

**Issue by mzakzok** [alvarotrigo/fullPage.js#4599]
### Description
Hi
for [this page ](https://www.bestcheapbikes.com/home-modified-copy-6) when linking the heading (electric bike
) In the fixed side menu to its section using the id Webflow method, it worked in preview mode but when I published the page and opened the online version it didn't work.
I need a fix for this 
to open the read-only backend Webflow preview page [press here](https://preview.webflow.com/preview/best-cheap-bikes?utm_medium=preview_link&utm_source=designer&utm_content=best-cheap-bikes&preview=1a267170c836e45f15fe616487a1c7b3&pageId=65914b617efcce564b712628&workflow=preview)

**Comment by alvarotrigo** [comment]
To link sections internally, make sure to use the `anchors` option in fullPage.js initialisation. 
See more in the <a href="https://github.com/alvarotrigo/fullPage.js?tab=readme-ov-file#creating-links-to-sections-or-slides" target="_blank">fullpage.js documentation</a>

You can also check the examples, like [this one](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/navigation-vertical.html).

**Comment by mzakzok** [comment]
I cloned the [Fullpage.js basic example](https://webflow.com/made-in-webflow/website/Fullpagejs-basic-example) and added the anchors option, but the text links I created didn't navigate to the sections although scrolling manually added the section id to the URL .
What is the problem?
[here is a preview from your basic example](https://preview.webflow.com/preview/mahmouds-five-star-site-0b7f78?utm_medium=preview_link&utm_source=designer&utm_content=mahmouds-five-star-site-0b7f78&preview=3795bb2bbbfda6a2000bcfaff65a42e6&workflow=preview)

**Comment by alvarotrigo** [comment]
It seems like something on Webflow is interfering with fullPage.js.
Try to disable any possible Webflow effects or additional functionalities.

**Comment by alvarotrigo** [comment]
Ah, you are also missing this error. 
<img width="1494" alt="image" src="https://github.com/alvarotrigo/fullPage.js/assets/1706326/9a6c8474-add4-4295-a7ee-6ce6cecd6632">

Fix that by removing the `id` parameters that has the same name as your `anchors`.
