### ISSUE TITLE
Image slideshow not working on firefox devices

### ISSUE THREAD

**Issue by snab-gab** [alvarotrigo/fullPage.js#46]
To answer to your comment (sorry, I'm just discovering github universe).

Here is a link of what I'm trying to do : http://www.gabrodrigues.com/teste  

I got troubles on every Firefox devices (only). Or there no image, or the image scale is not good.

**Comment by lkraav** [comment]
> Simply use the active class added on each section / slide when is active

Follow-up comment here for somebody who just launched the first `fullpage.js` site: this CSS-only based solution has multiple drawbacks - image loading on arrival is too slow, flicker is clearly visible both on leaving the previous and arriving on the next slide. This could possible be improved to adjust `.active` class timings: more eager for the next slide, and lazy remove on previous slide.

**Comment by monolux** [comment]
> This could possibly be improved with adjusting .active class timings: more eager for the next slide, and lazy remove on previous slide.

@lkraav Also interested in lazy loading 20+ slides of a section. Are you thinking to always have 2 slides loaded starting with the initial slide and then as the user progresses through the slide show it keeps always keeps loading the next 2 slides? I will see if I can come up with a fiddle for such a function. Feel free to add your thoughts about this please, thank you.

**Comment by thisisfed** [comment]
This is a nice trick but is there any way to keep the images visibles when leaving the section? Cause right now, as soon as I leave the section the image disappear immediately and it's quite weird :)

**Comment by alvarotrigo** [comment]
> This is a nice trick but is there any way to keep the images visibles when leaving the section?

Then you'll have to load them before leaving the section, which is not easy as you never know to which section is the user going to go next. (if provided a menu or nav)

If bandwidth is not a problem for you, I would encourage you to load them all after load, so they won't influence the loading time of the page. You can do something like this:

```javascript
$(window).load(onLoad);

//loading all images from all sections
function onLoad(){
    $('.fp-section').addClass('loadImage');
}
```

And use the `loadImage` css approach I mentioned before:

```css
#slide1 {
   -webkit-background-size: cover;
   -moz-background-size: cover;
   -o-background-size: cover;
   background-size: cover;
   height: 100%;
}

#slide1.loadImage{
    background: url(../img/portraits/01.jpg) no-repeat center;
}
```

**Comment by thisisfed** [comment]
Thanks Alvaro! I don't know why the javascript isn't working in my case, if I inspect the page it doesn't add that "loadImage" class.
