### ISSUE TITLE
Using fullpage.js with Divi

### ISSUE THREAD

**Issue by Alpasc** [alvarotrigo/fullPage.js#4601]
Hello,

I'm desperately trying to integrate fullpage.js to a wordpress site built with Divi. I saw that there was a plugin for Gutenberg and another for Elementor. I also saw that it was replied in November 2021 that you were working on a plugin for Divi... but I don't see it anywhere (I signed up for the waiting list).

In the meantime, there must be some way to integrate fullpage.js otherwise... I'd really need someone to explain where and how please. I bought the license and I'm trying to integrate the code, but I'm not a very good developer.
If I can't get the answer here, where can I ask for help?

Thanks for your work, it's great!

**Comment by alvarotrigo** [comment]
[Contact us](https://alvarotrigo.com/contact/) and we'll give you access to the beta version we have developed for Divi.
