### ISSUE TITLE
iPad Scrolling adjusting to section when using autoScrolling:false

### ISSUE THREAD

**Issue by rodrigo-arias** [alvarotrigo/fullPage.js#4602]
### Description
Experiencing a bug with fullPage.js on iPad – scrolling, along with address bar dynamics, triggers unexpected readjustments. Similar to a past issue (#799). Exclusive to iPad; unaffected by `fitToSection` or `autoScrolling` tweaks.

### Steps to reproduce

1. Open fullPage.js webpage on iPad.
2. Scroll, note address bar interaction.
3. Observe readjustments attempting to fit sections.
4. No issue on iPhone.
5. Behavior persists despite `fitToSection` or `autoScrolling` changes.

https://github.com/alvarotrigo/fullPage.js/assets/11416255/cf5653d3-aa62-4a77-95f6-e5e28bdfb3a4

https://github.com/alvarotrigo/fullPage.js/assets/11416255/1bcc077f-3698-4025-aa20-1cc498961be4

### Versions 
Device: iPad
OS: iOS 17
Browser: Safari 17
fullPage.js Version: 4.0.20

**Comment by alvarotrigo** [comment]
If you are using [this example](https://alvarotrigo.com/fullPage/setAuto.html#firstPage) for the test, that's using an old version of fullpage.js (version 2.9.7)

Are you able to reproduce the issue on the demo page?
https://alvarotrigo.com/fullPage/

Or any of [the examples](https://alvarotrigo.com/fullPage/#examples)?

**Comment by alvarotrigo** [comment]
Ok, I confirm I can reproduce it on iPad using browserstack real device on the example with `autoScrolling: false`:
https://alvarotrigo.com/fullPage/examples/normalScroll.html

**Comment by rodrigo-arias** [comment]
In the demo page autoscroll is enabled so it is not the same scenario, but I can reproduce it in [Normal Scrolling](https://alvarotrigo.com/fullPage/examples/normalScroll.html) or locally using the latest version of @fullpage/react-fullpage.

**Comment by alvarotrigo** [comment]
Fixed on [the dev branch 4.0.21](https://github.com/alvarotrigo/fullPage.js/tree/dev).

You can install it using npm with:

```sh
npm install alvarotrigo/fullpage.js#dev --save
```

**Comment by alvarotrigo** [comment]
Please confirm and I'll create the new release as soon as possible to push it to React, Vue, Angular and WordPress.

**Comment by alvarotrigo** [comment]
I've updated the files on the live page too, you might have to refresh a couple of times to avoid the cache:
https://alvarotrigo.com/fullPage/examples/normalScroll.html

**Comment by rodrigo-arias** [comment]
Thanks for the quick responses and the fix! I can see a small jump in the normal scrolling example, however after updating the _@fullpage/react-fullpage_ dist files everything looks fine locally.

https://github.com/alvarotrigo/fullPage.js/assets/11416255/76786edd-601b-41de-a250-1ba4ec25230b

**Comment by alvarotrigo** [comment]
> I can see a small jump in the normal scrolling example,

Yeah that's probably the resizing of the sections to fit the new viewport that changes sizes a little bit.

**Comment by rodrigo-arias** [comment]
@alvarotrigo Any chance you'll release the React patch at some point soon? A beta version would also work. Thank you

**Comment by alvarotrigo** [comment]
Fixed in 4.0.21! 🥳 

> @alvarotrigo Any chance you'll release the React patch at some point soon? A beta version would also work. Thank you

Done!
New release available version 0.1.41

**Comment by rodrigo-arias** [comment]
@alvarotrigo This is working. Thank you
