### ISSUE TITLE
when autoScrolling is false and fitToSection is false, does the normalScrollElements is ignored?

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4605]
### Description
I love the autoScrolling:false & fitToSection:false ability...  but when I do that, the normalScrollElements info goes out the window (unexpectedly). When I remove the "autoScrolling:false", and let fullpage to start snapping into sections again, then the same normalScrollElements ifno starts being honored (as expected). This unfortunately prevents me from using the autoScrolling:false option when I have certain divs on the screen, where I do not want mouse scrolls or swipe actions to effect the fullpage sections.  Could you test if that is also so for your testings too pls? 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
When using `autoScrolling: false` the normalScrollElements will behave in the same way any other scrollable element does in any other "normal" website.

Once it reaches the bottom or top of the scrollable element, then the whole page will scroll up / down. 

Here's an example of the default behavior of the browser for scrollable elements:
https://jsfiddle.net/trfawsju/


I don't know what's your use case. Do you want to prevent any kind of scroll inside that normalScrollElements item?
If you don't want the user to scroll over that element, you might want to consider using the CSS option `pointer-events: none;`

**Comment by alvarotrigo** [comment]
> Once it reaches the bottom or top of the scrollable element, then the whole page will scroll up / down.

This can be avoided if you use the style `   overscroll-behavior: contain;` on the overflowing content.

See this demo:
https://codepen.io/anon/pen/oEMmrm
