### ISSUE TITLE
Vertical fullpage

### ISSUE THREAD

**Issue by mewiss1** [alvarotrigo/fullPage.js#4606]
Hello Alvaro.
I have created a vertical fullpage slider and some of them contain videos but when I scroll up the videos are paused. How can I stop them from pausing? 
I don't know anything about programming. I have done this with a tutorial by Oscar Viedma.
https://ovdivi.com/desplazamiento-vertical-a-pantalla-completa-con-fullpage-js-y-divi/

**Comment by alvarotrigo** [comment]
Check out [the autoplay feature](https://alvarotrigo.com/fullPage/docs/#auto-playpause-embedded-media).

You can disable the automatic pause by using `data-keepplaying`.

**Comment by mewiss1** [comment]
Sorry Alvaro. I dont know how do it. Can you explain better....?
I dont know something about data

**Comment by alvarotrigo** [comment]
Just check the HTML used on the demo:
https://codepen.io/alvarotrigo/pen/pXEaaK

You'll see the `data-keepplaying` attribute added on the videos.
