### ISSUE TITLE
making fullpage.js buttons more responsive

### ISSUE THREAD

**Issue by prescriptionlifeline** [alvarotrigo/fullPage.js#4610]
### Link to isolated reproduction with no external CSS / JS
https://alvarotrigo.com/fullPage/examples/normalScroll.html

### Steps to reproduce it
When I view this page on my desktop the "First slide", "Second slide", etc buttons are reasonably sized but when I view it on my phone they're quite tiny relative to everything else:

![Screenshot 2024-03-18 084723 resized 2](https://github.com/alvarotrigo/fullPage.js/assets/77934157/7c17743f-9999-4333-b8d7-bbf2efed0026)

My question is...  could they be made more responsive? Like the buttons on https://alvarotrigo.com/fullPage/ ("Extensions", "Download", "View on GitHub")...  they look great on phones and on the desktop. It'd be cool if the the buttons at https://alvarotrigo.com/fullPage/examples/normalScroll.html could behave similarly.

### What I Tried
I thought I might adapt the CSS from https://alvarotrigo.com/fullPage/ to https://alvarotrigo.com/fullPage/examples/normalScroll.html but when I open up either URL in Chrome's Inspector and then toggle the Device Toolbar in Chrome I'm not seeing any changes in the CSS around those buttons so it's unclear to me where the CSS that's changing their size lives (either in normalScroll.html or /fullPage/)

**Comment by alvarotrigo** [comment]
Just use `<meta name="viewport" content="width=device-width,initial-scale=1">` 

But that's not a fullPage.js issue :)
