### ISSUE TITLE
normal scrolling vs fullpage scrolling and the address bar

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4612]
### Description
When we set the NS to true, and you scroll, mobile devices automatically and smartly hide the browser address bar to allow more spaces. But when fullpage.js's beautiful snap into scroll action in place, we are stuck with that address bar. I know why this is happening but is there a way to hide that area with some CSS trick? 

### Steps to reproduce it
1. visit https://alvarotrigo.com/fullPage/examples/scrollBar.html (where NS =true ) on your mobile device and scroll down
2. you will see that browser address never goes away. 
3. then repeat the same test with https://alvarotrigo.com/fullPage/examples/normalScroll.html where ( NS = true ) ad you will see that the browser address nicely disappears. 
4. 
### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Yeah, unfortunately, that's not possible.
We developers have very little control over the address bars and their behaviors in different mobile browsers.

In the past, it used to hide the address bar as long as you used `scrollBar: true.` Now it seems they've changed the behavior, and it no longer works.
