### ISSUE TITLE
Using fadingEffect on isolated sections

### ISSUE THREAD

**Issue by bashadrew** [alvarotrigo/fullPage.js#4616]
Hello, I'd just like some clarification on the official documentation. Apologies if this is not the right place to post it, happy to be redirected somewhere else. 

> fadingEffect: (default false). [Extension of fullpage.js](https://alvarotrigo.com/fullPage/extensions/). Defines whether to use a fading effect or not instead of the default scrolling one. **Possible values are true, false, sections, slides.** It can therefore be applied just vertically or horizontally, or to both at the time. It can only be used when using: autoScrolling:true. Requires fullpage.js >= 3.0.1.

I'm testing it in React locally. `section` is not defined, and I am wondering how to use the value?
What I'm trying to achieve is to have regular scrolling for the first section, then use the fading effect on the mid sections, and ending with regular scrolling for the final section. 
My guess is that the `section` value is meant to help achieve this.  

My code (just using `true` for the fadingEffect):
```
import ReactFullpage from '@fullpage/react-fullpage';

const pluginWrapper = () => {
  require('../fullpage.fadingEffect.min.js');
};

const Home = () => {
  return (
    <ReactFullpage
      pluginWrapper = {pluginWrapper}
      fadingEffect = {true}

      render={({ fullpageApi }) => {
        return (
          <div>
            <Intro />
            <ReactFullpage.Wrapper>
              <div className="section">Section 1</div>
              <div className="section">Section 2</div>
            </ReactFullpage.Wrapper>
            <Contact />
          </div>
        );
      }}
    />
  );
}

export default Home;
```

Any help would be appreciated, thank you!

**Comment by alvarotrigo** [comment]
> My guess is that the `section` value is meant to help achieve this.

No. The `section` string (as in `fadingEffect: "section"`) will only make sure the facing effect is only applied to vertical sections and not to horizontal slides.

The `slide` string is used to only apply it for horizontal slides and not to vertical sections.

What you want is neither of those. You want to apply it to some vertical sections, but not to all. 
That's a little more tricky.

The only thing you can do is enable and disable the fading effect when reaching certain section, but this won't be perfect. 
You can only trigger the change of behaviour on the `afterLoad` callback, so this will prevent you from enabling and disabling the effect just before leaving the section. 

In any case, if you want to go this route, you'll have to do something like this:


```js 
afterLoad (origin, destination, direction, trigger){
    // disabling fading effect for sections 4, 5, 6....
    if(destination.index > 2){
        fullpage_api.fadingEffect.turnOff();
    }
    
    // enabling fading effect for sections 1, 2, 3
    else if(destination.index < 3){
        fullpage_api.fadingEffect.turnOn();
    }
}
```

Let me know if that clarifies this for you ;)

**Comment by bashadrew** [comment]
Yes, it worked. Thanks Alvaro!

Sharing my final code for reference in case anyone else needs something similar in React:
```
import React from 'react';
import ReactFullpage from '@fullpage/react-fullpage';

const pluginWrapper = () => {
  require('../fullpage.fadingEffect.min.js');
};

class Home extends React.Component {
  afterLoad = destination => {
      if (destination.index >= 1) {
        fullpage_api.fadingEffect.turnOff();
        console.log("Fading effect turned off");
      } 
      else {
        fullpage_api.fadingEffect.turnOn();
        console.log("Fading effect turned on");
      }
  };
  render() {
    return (
      <ReactFullpage
        pluginWrapper={pluginWrapper}
        licenseKey={'YOUR_KEY_HERE'}
        fadingEffect={true}
        afterLoad={this.afterLoad} 

        render={() => {
          return (
            <ReactFullpage.Wrapper>
              {['Section 0', 'Section 1', 'Section 2', 'Section 3', 'Section 4', 'Section 5'].map((section, index) => (
                <div
                  key={index}
                  className={`section section-${index}`}
                >
                  {section} - Index: {index}
                </div>
              ))}
            </ReactFullpage.Wrapper>
          );
        }}
      />
    );
  }
}

export default Home;

```

**Comment by alvarotrigo** [comment]
Glad it helped!

**Comment by codeninja-top** [comment]
great help!
