### ISSUE TITLE
2.6.6

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4618]
### Description
Hello, I mistakingly chose an old version of full-page (2.6.6) and developed an entire application on it. Now it is too late to port it to 4.X versions. So I'm not trying.  

How can I find the documentation on 2.6.6? I realized that I did not even download the packages, I'm linking to CDN's CSS an JS. 

I'd love to share what I came up _with you only_ (as it's a jem) but I cannot share the URL as it is not public yet, still in development stage.   

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
> Hello, I mistakingly chose an old version of full-page (2.6.6) and developed an entire application on it. Now it is too late to port it to 4.X versions. So I'm not trying.

I'd encourage you to try using the latest version, there are almost no changes.
See the [migration guide](https://alvarotrigo.com/fullPage/help/migration-from-fullpage-3/).

fullPage.js 4 is way more robust than version 2. Way less bugs (day and night) and no need to load the whole jQuery.
Also, there are plenty of new features and options that makes it easier for developers. 

> How can I find the documentation on 2.6.6? I realized that I did not even download the packages, I'm linking to CDN's CSS an JS.

You can find it through the releases page:
https://github.com/alvarotrigo/fullPage.js/releases
