### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by AlvaroFalcon** [alvarotrigo/fullPage.js#4619]
### Description
Hello! I wanted to know if its possible to use the library on an open source project under GPL-3.0 license, It seems to be possible but im really unsure, so I prefer to ask first. Thanks

**Comment by alvarotrigo** [comment]
Sure, you can use it in any project that is licensed as GPL-3.0 or any other compatible license. 
Just make sure you follow the GPLv3 requirements and that you make your code publically available.
