### ISSUE TITLE
fullPage.js license in commercial open source site

### ISSUE THREAD

**Issue by unpWn4bl3** [alvarotrigo/fullPage.js#4625]
Hello, I'm wondering if I build a website using fullPage.js under GPL V3 but for commercial usage(kickstarter, pre-ordering...), do I still need to buy a license?

**Comment by alvarotrigo** [comment]
I'd recommend you read [this article](https://alvarotrigo.com/fullPage/help/which-fullpage-js-license-should-i-choose/) on what license to choose.

Let me know if you have any questions.

**Comment by alvarotrigo** [comment]
Regarding the open source license under GPLv3, I'd recommend you seek assistance from a lawyer specialized in licensing or read the terms and conditions of the license [here](https://www.gnu.org/licenses/gpl-3.0.en.html).

It can be tricky to work under GPLv3 if you use other third-party vendors that are non-GPLv3 compatible.

And if you want to keep part of your code private, it might be difficult, too.
