### ISSUE TITLE
Drag and Move seems broken on mobile?

### ISSUE THREAD

**Issue by manuroc** [alvarotrigo/fullPage.js#4627]
### Versions 
Pixel 7, Chrome, Vivaldi Browser and Firefox browser.

Using FullPage for Gutenberg Wordpress plugin.

Hello,

Perhaps I am using the extension wrong, but when activating drag and move, the effect works fine on Desktop while dragging the mouse, but not at all on mobile. The moment I touch the screen, the page goes crazy and jumps all over the place, often jumping between the first and last slides.

My goals:
On Desktop:
- Auto scrolling on (to use wheel mouse and keyboard to switch between sections)
- Drag and move off (set to fingers only)

On Mobile:
- Auto scrolling off (set to responsive width 1200px to disable the effect on tablets and phones)
- Drag and move on (fingers only) to allow users to switch between sections with an "app-like" feel without the forced motion of auto scrolling.

Regardless of what settings I set (auto scrolling on/off, empty theme template, easing styles...), whenever Drag and Move is enabled, it completely breaks the page on mobile. Even a freshly created test page with no special elements on the slides and default settings. The only trigger seems to be enabling Drag and Move and testing it on my phone.

However, it seems to work fine in a simulated environment (desktop browser set to mobile dimensions in developer options).

I will test on other mobile devices and report.

**Comment by alvarotrigo** [comment]
For issues with the WordPress plugins or with fullPage.js extensions we have a ticket system to deal with customer's issues and questions.

Can you copy and paste your message and send it through our contact form?
https://alvarotrigo.com/contact/

Thanks!
