### ISSUE TITLE
fittosection and autscrolling

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4632]
Hi Alvatrigo, 

I have autoscrolling off. But fit to section true. And When I reach a particular section, I'd like the fittosection to be off so we can scroll and read that large content as we wish. Is the best way to make it happen to use the turn this on/off whether I'm on that section or not: 

fullpage_api.setFitToSection(false);

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
> fullpage_api.setFitToSection(false);

That's the way yeah.

Just use it inside some callback like [afterLoad](https://alvarotrigo.com/fullPage/docs/#afterload-origin-destination-direction-trigger), [onLeave](https://alvarotrigo.com/fullPage/docs/#onleave-origin-destination-direction-trigger) or [beforeLeave](https://alvarotrigo.com/fullPage/docs/#beforeleave-origin-destination-direction-trigger).
