### ISSUE TITLE
Removing background image of slides causes content to change

### ISSUE THREAD

**Issue by tomhimsworth** [alvarotrigo/fullPage.js#4635]
Description:
I inherited a BeTheme website (https://beblankandco.flywheelsites.com/) where I'm using FullPage.js for scrolling functionality. Our clients have requested that background images be removed (it's currently a topo/textured bg) and background colors changed on certain slides. However, when attempting to make these changes using the BeTheme builder, I encounter issues where content on the slides either disappears or duplicates unexpectedly.

Steps to Reproduce:

Navigate to the BeTheme builder on the site.
Select a slide where background images need to be removed or background colors changed.
Attempt to remove background images or change background colors.
Observe that content either disappears or duplicates.

Expected Behavior:
When removing background images or changing background colors using the BeTheme builder, the content on the slides should adjust accordingly without disappearing or duplicating.

Actual Behavior:
Content on the slides disappears or duplicates in an unusual manner when attempting to remove background images or change background colors using the BeTheme builder.

**Comment by alvarotrigo** [comment]
That looks like an issue of BeTheme?

Unfortunately we have nothing to do with BeTheme, so we can't help you here.

If you have any specific questions about how to implement or use fullPage.js using JavaScript, feel free to ask ;)
