### ISSUE TITLE
how can I detect a swipe-left and swipe-right events.

### ISSUE THREAD

**Issue by halukkaramete** [alvarotrigo/fullPage.js#4636]
### Description
Hi Alvatrigo, 
I'm not using the side slides... I do not need to. But I need to detect the swipe (left/right) events on the fullpage-sections so I can pop or do various things, depending on the section.  I've used hammer.js to enable gestures, it detects drag-left/right, tap, double tap, and even long-press tap but not the swipe ( though their doc says it does ). Could you suggest a way to do this the vanilla way over the fullpage.js sections? Since I'm still using 2.6, it's gotta be a vanilla/or jquery way I guess.   

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
fullPage.js doesn't provide any callbacks for those events.

But you can create your own by listening to the `mousewheel` event for the trackpad or the `touchmove` for touch devices.

Check this for the trackpad:
https://stackoverflow.com/a/12850780/1081396

Good luck with that! 👍
