### ISSUE TITLE
<------- I am Niwa Eiji on Upwork. -------->

### ISSUE THREAD

**Issue by BlueUnicorn0805** [alvarotrigo/fullPage.js#4638]
"Hi there!
I'm looking for someone who can translate the documentation of a popular JavaScript component from English to Japanese.
Would you be interested?"

above post is yours?

I am ready for you.

live:.cid.349ad8bc6b76368f  this is my skype

**Comment by alvarotrigo** [comment]
Sory, only looking for proofreaders at the moment. See more on Upwork.

**Comment by BlueUnicorn0805** [comment]
I know
