### ISSUE TITLE
scroll is not working on touch screen laptop when full viewport element inside section

### ISSUE THREAD

**Issue by vpteamdev** [alvarotrigo/fullPage.js#4639]
### Description
Scroll with one finger on touch laptop devices (microsoft surface) does not work if there is a full-viewport element inside section. If I try to scroll with two fingers, it works normally.  

### Link to isolated reproduction with no external CSS / JS
https://jsfiddle.net/f69v7etx/2/ In this case the scroll works only sometimes
https://vpsite-staging.valuepartners.com/hp-test In this case (it is almost an isolated reproduction), it never works.

### Steps to reproduce it
1. Basic fullpage.js integration on surface laptop
2. put a div with width: 100vw and height: 100vh inside a section
3. try to scroll with one finger (does not work always)
4. try to scroll with two finger (it works well)

### Versions 
Chrome 126, edge 126. Windows 11. Microsoft surface

**Comment by alvarotrigo** [comment]
> https://vpsite-staging.valuepartners.com/hp-test In this case (it is almost an isolated reproduction), it never works.

Are we talking about swiping on top of the modal here?

The modal is actually outside the fullPage.js wrapper. So that's expected.
It's not actually "inside a section".

By default fullPage.js only listens to the touch events on the element you use to initialise fullPage.js when you do "new fullPage('.element',{});`

But in case you want to change that, you can use the option `touchWrapper` to define a new element to listen  to.
For example:

```js
new fullPage('#fullpage', { 
     touchWrapper: '.my-wrapper'
}
```

**Comment by vpteamdev** [comment]
No, I'm not talking about that modal, you can close it. I'm talking about div.section-inner inside the .section element, you can see that it occupy all his parent (.section) space, and if i try to scroll inside of it with one finger on a microsoft surface nothing appens. If I scroll with two finger instead, section is changed correctly.

**Comment by alvarotrigo** [comment]
What browser are you using on your Microsoft surface? Edge?

**Comment by vpteamdev** [comment]
Yes, I'm scrolling up. I can reproduce the issue on both chrome and edge.

**Comment by alvarotrigo** [comment]
Ok, so I'll be investigating it more, but so far if you want a fix, probably using `scrollOverflow: false` will do it.

I have no access to a Microsoft Surface.
I was trying to reproduce the issue using Edget and touch devices emulation, but it doesn't seem to do the trick. I'm able to scroll up.

![image](https://github.com/user-attachments/assets/ffb1e629-933c-481d-a5d6-047f80c24367)

I assume you can also scroll up on the Edge touch emulator right?

Do you know of any real device emulator for Microsoft Surface or similar?

**Comment by vpteamdev** [comment]
scrollOverflow: false seems to do the job, after lunch i will check if it has any side effect in my real scenario. 
Yes, with edge touch simulator i'm able to scroll up.
Sadly I don't know any real device emulator for surface, I usually use browserstack but it does not support microsoft surface

**Comment by vpteamdev** [comment]
Hi alvarotrigo, scrollOverflow: false, should be okay for my case, thank you for the timely support. From my point you can close the issue.

**Comment by alvarotrigo** [comment]
> scrollOverflow: false seems to do the job

Good to know!

In case anyone, or you, need to use scrollOverflow with your current setting, you probably need to end up replacing the 100vh for your inner container for something like `height: calc(100vh - 1px)`
