### ISSUE TITLE
I update free version to pay version. afterRender option is out of control

### ISSUE THREAD

**Issue by seulite** [alvarotrigo/fullPage.js#4646]
### Description
hi. i live in korea. and i joined in a suit rental company ( It called  MYSWEETINTERVIEW). anyway. our company outsource rebuild the homepage by using fullpage.js. and the outsourcing student  build ver 3.0(widthout lisence Key. and They make on free for portfoilo, )  
anyway,  i pay for version 3, i put the code about licenseKey in the js code. it broken.

here' s my try

first try.
```js 
  $('#fullpage').fullpage({
    licenseKey: '~~~' 
   menu: '.right_menu',
    anchors: ['firstPage', 'secondPage', 'thirdPage',
      'fourthPage', 'fifthPage', 'sixthPage', 'seventhPage',
      'eighthPage'],
    afterRender: function () {
      $('.content-logo').delay(0).animate({ top: 0, opacity: 1 }, 500);
      $('.content-main').delay(400).animate({ top: 0, opacity: 1 }, 500);
    },
   ....})

```
[result}
i just put the   licenseKey: '~~~' , all of jquery  is shutdown.

```
second try.
new fullpage('#fullpage', {
	licenseKey: '~~~' 
}); 
```
[result] jquery  is survive, but afterRender doesn't work. 

here is the link of site. 
https://mysweetinterview.cafe24.com/skin-skin78#firstPage

i put the afterRender for 1st section title. and afterLoad for 2nd section text.

now, i delete licenseKey, It works. 
let me tell how to licenseKey works.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/qqabrp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. [First step]
2. [Second step]
3. [and so on...]

### Versions 
[Browser, operating system, device, ...]

**Comment by alvarotrigo** [comment]
Adding the license key shouldn't break any functionality. 
Make sure you have no errors on your JS console.

I'd recommend you to switch to version 4 anyways. It solves many bugs and it doesn't require jQuery. 

If you are able to reproduce the error in an isolated environment like jsfiddle or codepen I'd be happy to take a look at it even though support for version 3 is no longer provided.

**Comment by alvarotrigo** [comment]
Right now I can see many errors in the JS console.
Make sure to initialise fullPage.js only once. It seems you are doing it multiple times. 

<img width="1565" alt="image" src="https://github.com/user-attachments/assets/ff9a37f9-c094-4291-9f36-63015fb56603">

**Comment by seulite** [comment]
thanks a lot.
