### ISSUE TITLE
 License in development environment

### ISSUE THREAD

**Issue by KelvinAlves28** [alvarotrigo/fullPage.js#4647]
The company I work for is considering subscribing to the fullpage.js service for us to use on the company's website. Only I will act as developer, but we have two environments, a development environment and a production environment, so that fullpage.js works on our Do we have to subscribe to the professional version? Or can we subscribe to a Hobby version and leave the dev environment unsubscribed?

**Comment by alvarotrigo** [comment]
You can use the Hobby license if you only have 1 final site.

**Comment by KelvinAlves28** [comment]
To send it to the production site, it goes through the development site, but as only the production site would have the url registered, the development environment would have the key but the library would be not activated, but even if not activated, would it work normally?

**Comment by alvarotrigo** [comment]
Yeap, you'll be fine with using fullPage.js in the dev environment. No worries.

**Comment by KelvinAlves28** [comment]
One last question, does it work on subdomains of the chosen domain?

**Comment by alvarotrigo** [comment]
Yeap.

**Comment by KelvinAlves28** [comment]
ok, thanks for your quick response!

**Comment by KelvinAlves28** [comment]
We purchased "Hobby", we received a key, but we haven't used it yet because we haven't found how to activate the domain in which I will use the key, how can I do this activation?

**Comment by alvarotrigo** [comment]
> we haven't found how to activate the domain in which I will use the key, how can I do this activation?

fullPage.js licenses don't require activation per domain.  You can use it as it say son the <a href="https://alvarotrigo.com/fullPage/docs/#licensekey" target="_blank">fullpage.js documentation</a>

**Comment by KelvinAlves28** [comment]
Please explain it to me better so that I can activate it in the right environment and not have any problems, since my subscription is for just one site...

**Comment by alvarotrigo** [comment]
Just use the license using the `licenseKey` option, and you won't have issues. There's no more to add.
