### ISSUE TITLE
getPanelByElement function called passing an element instead of an array

### ISSUE THREAD

**Issue by FrancescoMessage** [alvarotrigo/fullPage.js#4653]
Hi, in Fullpage.js V 4.0.28 sometimes I have this javascript error if I load the page to a specific anchor (section):

`Uncaught TypeError: panels.find is not a function`

in this function:

```
function getPanelByElement(panels, el) {
      return panels.find(function (panel) {
        return panel.item === el;
      });
    }
```

I noticed that in this version, this line of code is added ([https://github.com/alvarotrigo/fullPage.js/commit/d3098220ef14aa23160372007c6df4a05ef84a4b#diff-3f4acb3a8da52427effb980e67bb24e6f2092f287d69c9db90dfe35b953d4d25](https://github.com/alvarotrigo/fullPage.js/commit/d3098220ef14aa23160372007c6df4a05ef84a4b#diff-3f4acb3a8da52427effb980e67bb24e6f2092f287d69c9db90dfe35b953d4d25)):

`lazyLoadPanels(getPanelByElement(section));`

getPanelByElement function expects an array as argument, but a single element is given in this case, so the error occurs.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
I was able to reproduce it here:

https://codepen.io/alvarotrigo/pen/wvLQOEK

Fixed on dev!

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.29! 🥳

**Comment by FrancescoMessage** [comment]
Well done!
