### ISSUE TITLE
fitToSectionDelay not working in React & Extensions file

### ISSUE THREAD

**Issue by KelvinAlves28** [alvarotrigo/fullPage.js#4654]
in the codesandbox itself of the normal-scroll example in react, I'm trying to change the fitToSectionDelay parameter, but it's not working.

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/p/sandbox/fullpage-js-demo-normal-scroll-forked-hk53sk?file=%2Fsrc%2FApp.js

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
I'm able to reproduce it.

Fixed on the dev branch of fullPage.js.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 4.0.29! 🥳 
And react-fullpage 0.1.44!
