### ISSUE TITLE
Normal scroll with react-router-dom

### ISSUE THREAD

**Issue by KelvinAlves28** [alvarotrigo/fullPage.js#4656]
I'm making a page using Normal Scroll, but I'm having problems moving from one page to another using react-router-dom. I have 6 sections on my home page, and in the sixth section I have a button that redirects to another page, but when I'm redirected to another page, it renders the page already in section3, what could be happening?

**Comment by alvarotrigo** [comment]
That sounds to me like a React issue more than a fullpage.js one.
fullPage.js doesn't deal with routes at all. I'd suggest you ask in some other place like stackoverflow.com where they'll be able to help you much better.

**Comment by KelvinAlves28** [comment]
obviously when the route is changed, it loads the value of the section of the previous page, I managed to solve it by having the same function that navigates to the next page, I put fullpage_api.silentMoveTo(1), so it goes to the next page, I put fullpage_api.silentMoveTo(1), so it goes to the next page next page with the section value (1)

**Comment by alvarotrigo** [comment]
Glad you managed to solve it ;)
