### ISSUE TITLE
purchased extension bundle usage issue

### ISSUE THREAD

**Issue by ORB-8888** [alvarotrigo/fullPage.js#4660]
Hello, 

I have purchased two package:

first I have purchased that package

1) 
Hobby
$13.50
( billed annually)

I simply used it in the Gitpod dev environment, on the local link:
https://8080-*****-eu116.gitpod.io and it is working, 

I only used that parameters:

    <link href="css/fullpage.min.css" rel="stylesheet">

	new fullpage('#fullpage', {
		licenseKey: 'MY LICENSE KEY HERE', (Which I have received via Email)
		navigation: true,
		navigationPosition: 'right',
		loopTop: true,
		loopBottom: true,
		anchors: ['TNO-Bronze', 'TNO-Silver', 'TNO-Gold', 'TNO-Diamond', 'explorills-Nodes', 'Blue-Minerals'],
		menu: '#menu, #menuMain',
		scrollingSpeed: 1000,  // Increased for smoother scrolling
		touchSensitivity: 6,
		scrollOverflow: true,
		credits: { enabled: false },  // Removes the FullPage.js credit
		onLeave: function(origin, destination, direction){
			$('.header').removeClass('header-shadow');
			if ($(destination.item).scrollTop() > 0) {
				$('.header').addClass('header-shadow');
			}
			if ($(destination.item).hasClass('slide-dark-footer')) {
				$('body').addClass('body-copyright-light');
			} else {
				$('body').removeClass('body-copyright-light');
			}
			if ($(destination.item).hasClass('slide-dark-bg')) {
				$('body').addClass('body-bg-dark');
			} else {
				$('body').removeClass('body-bg-dark');
			}
			$('.a-carousel-projects').trigger('refresh.owl.carousel');
		}
	});

    <script src="js/fullpage.extensions.min.js"></script>

then I purchased fullpage.js Extensions Bundle because I wanted to add the feature "scrollOverflowReset"

2)
fullpage.js Extensions Bundle
Hobby
$129.00

after purchase I have downloaded these files:

bundle-for-fullpage-v3.zip

and 

bundle-for-fullpage.zip

so I have unzipped first v3 file, and replaced in /js old fullpage.extensions.min.js (which was working with simple parameters provided above )with new fullpage.extensions.min.js from bundle-for-fullpage-v3.zip  

also I have moved in /js that file: scrollOverflowReset.min.js. (so there was not "fullpage.min.css" in the bundle-for-fullpage-v3.zip and I kept old one from the previous first FullPage package purchase. 

after I made changes, it gives me that console error:

fullpage.extensions.min.js:16 fullPage: Fullpage.js version 3 has changed its license to GPLv3 and it requires a `licenseKey` option. Read about it here:

also, when I used new fullpage extension it reordered my entire container, I mean previous FullPage just worked smoothly, like I did not change anything, but now it changes some margins for the main container.

so maybe I am doing something wrong?

kindly point me how to correctly implement from my purchased extension bundle the scrollOverflowReset to my previous working project?  

and also what I have to do, before I bring my project into production, to consider the license key activation, if I will activate my license key for the scrollOverflowReset, then will I be able to also use all other extensions I have purchased. 

first of all, kindly help me to use purchased extension bundle, specifically for the scrollOverflowReset, again my basic previous package was working, but the new extension minified version from bundle is not aligns correctly to the project. 

thank you in advance

**Comment by alvarotrigo** [comment]
> https://8080-*****-eu116.gitpod.io and it is working,

The link is not working.

For extensions related stuff, can you contact us through [the contact form](https://alvarotrigo.com/contact/)?
Thanks.
