### ISSUE TITLE
Using Jquery: Take table header text to prepend on table body cell 

### ISSUE THREAD

**Issue by freeecoom** [alvarotrigo/fullPage.js#4663]
I have a table and I need to take each column's header's text to prepend on this column's body cell by using Jquery.  Below is my code:
`$('thead tr th').each(function() {
	var headerText = $(this).text();
  console.log('header: ' + headerText);
   $('tbody tr td').prepend('<span>' + headerText + '</span')
})`

**Problem**: I am getting all 3 headers text prepend on all table body cells! ( It should be: CountryAlfreds, but I get CountryContactCompanyAlfreds, for example)
Please take a look at my live jsfiddle sample below and direct me how to take each column's header's text to prepend on this column's body cell.
Any help would be appreciated!
https://jsfiddle.net/te6cw31d/2/

**Comment by alvarotrigo** [comment]
And why is this related with fullPage.js? 

I'm closing the issue.
You should ask in another place such as stackoverflow.com where they'll be able to help you much better.

Or... use ChatGPT or Claude ;)
