### ISSUE TITLE
Responsive width not working on Instagram

### ISSUE THREAD

**Issue by desoss** [alvarotrigo/fullPage.js#4667]
I've configured responsiveWidth: 768. It works smoothly everywhere except for the Instagram-embedded browser.
I'm printing the viewport size, which is around 400px and even if I expect a regular scroll the full-page scroll is performed.

The problem raises with iPhone on Instagram.
You can check it [here](https://www.instagram.com/desoss/).

Device: iPhone, Instagram embedded browser

**Comment by alvarotrigo** [comment]
Working fine for me. 
See the video:

https://github.com/user-attachments/assets/038ae14b-dde9-4458-9c6d-80a96e079c69

**Comment by alvarotrigo** [comment]
Make sure you have cleaned your browser cache or that you force the refresh of the JS / CSS files in case you changed them and you are getting the cached ones.

**Comment by desoss** [comment]
Thanks a lot, it was my internal Instagram cache. 

By the way, I solved it upgrading from 4.0.22 to 4.0.30.
