### ISSUE TITLE
After an annual business purchase, the licensekey is displayed in the browser, but there is no way to stop it. Can I restrict it to only work on certain domains?

### ISSUE THREAD

**Issue by todaynogada** [alvarotrigo/fullPage.js#4669]
After an annual business purchase, the licensekey is displayed in the browser, but there is no way to stop it. Can I restrict it to only work on certain domains?

**Comment by alvarotrigo** [comment]
> the licensekey is displayed in the browser, but there is no way to stop it. Can I restrict it to only work on certain domains

No. There's no way to properly hide it. 
It's front-end code, so whatever applies to any other front-end code applies here too.

https://alvarotrigo.com/fullPage/help/Can-I-hide-fullPage-js-license-key/

The most you can do is obfuscate it. 

But I wouldn't worry about it much. 
If anyone else uses your key they'll be the ones responsible for the legal consequences, not you.
