### ISSUE TITLE
fullPage only for 1 section

### ISSUE THREAD

**Issue by Ilya-web** [alvarotrigo/fullPage.js#4671]
Good afternoon
My task is to make a screen scroll, only for one section in which there are 4 more sections (https://codesandbox.io/p/sandbox/fullpage-sxdn69). The rest of the page scrolled in the usual way. Tell me how to implement this?

**Comment by alvarotrigo** [comment]
I'd recommend you place your whole "normal-scrolling site" inside a section.
As long as you use `scrollOverflow: true` (which is active by default) your site will scroll as normal when reaching that section.

So for example

- section 1
- section 2
- section 3
- section 4
- section 5 (contains your normal-scrolling site)

See this example:
https://alvarotrigo.com/fullPage/examples/#scroll-inside-sections
