### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by danielbarenkamp** [alvarotrigo/fullPage.js#4679]
### Description

I added the fullscreen.js and css files, but it does not work. 

Code:
```
var test = new fullpage('#content');
```

### Link to isolated reproduction with no external CSS / JS
https://proplan.pak-kuechen.de/

I can not create a Fiddle of this as this is a Wordpress website. 

### Steps to reproduce it
Look at the URL. It just looks broken. 

### Versions 
All, Latest

**Comment by alvarotrigo** [comment]
No problem!

You can check the [list of examples](https://alvarotrigo.com/fullPage/examples/) to see how to implement fullPage.js.
And if you need more info, make sure to read the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a>.

> I can not create a Fiddle of this as this is a Wordpress website.

If you want to make it easier for you, feel free to check out our plugins for WordPress.
fullPage.js is available as a plugin for WordPress for:
- [Elementor](https://alvarotrigo.com/fullPage/wordpress-plugin-elementor/)
- [Divi](https://alvarotrigo.com/fullPage/wordpress-plugin-divi/)
- [Gutenberg](https://alvarotrigo.com/fullPage/wordpress-plugin-gutenberg/)

I hope that helps ;)

**Comment by danielbarenkamp** [comment]
I paid for the license and hope to get real support so you can see why it not works. The examples do not help because my HTML code is correct.

**Comment by alvarotrigo** [comment]
Note that only the "Business" license has premium support. You got a "Hobby" license, which includes basic support and is limited to fullPage.js, not third-party integrations like WordPress. 

But I still encourage you to read the docs and check the examples to understand how to use fullPage.js in the first place.

> I added the fullscreen.js and css files, but it does not work.

It's not just enough to include the files.
You'll need to set up the HTML structure and initialize fullpage.js with the options you want.

More on the <a href="https://alvarotrigo.com/fullPage/docs" target="_blank">fullpage.js documentation</a>
