### ISSUE TITLE
Incorrect height calculated on page load, 15px short

### ISSUE THREAD

**Issue by EricJammin** [alvarotrigo/fullPage.js#472]
I have included this in a Wordpress theme I am developing. Encountering a strange issue— the height of each div.section is being calculated 15px too short when the page loads. This happens in all browsers I've tested on Mac (safari, chrome, firefox).

My dev site: http://staging.ericelliot.com/

If I resize the browser window after the page has loaded, then the sections adjust and the height is correct. But the height is definitely off by 15px when the page loads. I have tried toggling different options such as resize and css3, and paddingTop and paddingBottom are set to the correct values. I removed other js components as well to see if there was a conflict, there was not. 

I have added in background colors and filler content to the sections to make the issue more clear. Any ideas?

**Comment by alvarotrigo** [comment]
@aosmichenko i can't reproduce it on the [demo page](https://alvarotrigo.com/fullPage/) or any of the online examples for that matter. 
Make sure use use the compulsory doctype declaration. `<!DOCTYPE html>`
