### ISSUE TITLE
scroll event doesn't update window location hash

### ISSUE THREAD

**Issue by milesmatthias** [alvarotrigo/fullPage.js#475]
Right now the library does 2 things (which make total sense):
1. When the user clicks on a link with a target as the href, the library recognizes the 'hashchange' event, and changes to the selected page.
2. When the user scrolls on the screen, the library recognizes the scroll event and changes to the next page in the scroll direction.

However, when the user scrolls and the library changes the page, it does not update the window location hash. This means that if someone scrolls to the next page, they won't be able to deep link to that page. They will be able to deep link if they click on a link with a target as the href, but not scrolling.

Here's a user story if this helps:
1. User visits website, first page is shown by default.
2. User clicks on `<a href="#page2">Page Two</a>`, which changes the URL to `http://example.com/#page2` and triggers the `window.hashchange` event.
3. FullPage.js' listener on the `window.hashchange` event animates to the next page.
4. User copies url to direct people to page2 and people who click on `http://example.com/#page2` will successfully see the second page.

Not working story:
1. User visits website, first page is shown by default.
2. User scrolls on window with intention of visiting next page.
3. FullPage.js' listener on `window.scroll` animates to the next page.
4. User copies url (which is still `http://example.com`) with the intention of showing people the second page.
5. People who click on the shared link will not see page 2, instead they will see the default first page.

Ref: #175. Is that clearer?

**Comment by stgermaniac** [comment]
Should it work if I use data-anchor on sections instead of referencing them specifically on initialization?

**Comment by glouton** [comment]
Hello,

I realise this is an old one but I'm facing the same issue.
I've implemented fullPage as a Drupal 8 module. It's working fine except for the URL which is not updated. Neither on scroll for the sections nor using the arrows for the slides.
`autoScrolling` is on default value, hence true.
anchors are named using `data-anchor`

Regards,

**Comment by alvarotrigo** [comment]
@glouton if you believe it is a bug please open a new issue with an isolated reproduciton of it with the minimum amount of HTML code and no external CSS or JS to fullpage.js.
