### ISSUE TITLE
Just Horizontal sections.

### ISSUE THREAD

**Issue by merrybike** [alvarotrigo/fullPage.js#487]
Hey alvaro, I would like to create a horizontal website with this plugin, but I can't figure out how. I don't need the sliders or anything like that other guy. I just want horizontal sections. (but still responsive) Can you give me any tips on how to do this? Thanks alot!

Merijn

**Comment by alvarotrigo** [comment]
> How can move this sections horizontally?

This is now possible using the [scroll horizontally extension](http://alvarotrigo.com/fullPage/extensions/scrollHorizontally.html) of fullpage.js.
