### ISSUE TITLE
Remove left arrow at first slide?

### ISSUE THREAD

**Issue by Sperziemone** [alvarotrigo/fullPage.js#491]
Hi,

Thanks for this great demo! It's awesome!

My title says it all: can I remove the left arrow at the first slides of each section? I don't want people to immediately go to the last slide, but to follow slide1, slide2, slide3, and then slide 4. Not slide 1 and then backwards to slide 4.

I've been trying several things but I'm unsuccessful. Hope you can help me out!

Regards,
Simone

**Comment by sungchoi** [comment]
@Sperziemone 
If you'd like to allow looping from the last slide to the first but prevent looping from the first to the last slide,
you can also 
1) set the loopHorizontal option to true,
2) set the default CSS for the left arrow to display none: 
```css
div.fp-controlArrow.fp-prev { 
    display: none; 
}
```
3) add an onSlideLeave callback:
```javascript
        onSlideLeave: function( anchorLink, index, slideIndex, direction){
            var leavingSlide = $(this);

            //leaving the 0th (first) slide
            if (slideIndex == 0){
                $('div.fp-controlArrow.fp-prev').show()
            }
        }
```

**Comment by sungchoi** [comment]
Oops you'll need these callbacks too (you can probably use this callback without the onSlideLeave callback actually):
```javascript
        afterSlideLoad: function( anchorLink, index, slideAnchor, slideIndex){
            var loadedSlide = $(this);

            //after loading the 0th (first) slide
            if (slideIndex == 0){
                $('div.fp-controlArrow.fp-prev').hide()
            } else {
                $('div.fp-controlArrow.fp-prev').show()
            }
        }
```

**Comment by lorenzomarri** [comment]
You solved me lots of problems with this!
Thanks
