### ISSUE TITLE
Scrolling with MacBook Pro touchpad is difficult

### ISSUE THREAD

**Issue by thelfensdrfer** [alvarotrigo/fullPage.js#5]
If you use the touchpad of the macbook pro it is very difficult to scroll only one page, often one page is skipped. I don't know if it's possible to enhance, but would be great.

**Comment by djvs** [comment]
Still an issue

**Comment by alvarotrigo** [comment]
@djvs not if you keep  the scrolling speed by default or the one used on the [demo page](http://alvarotrigo.com/fullPage/).
Which value are you using?

**Comment by djvs** [comment]
Actually, with some testing, it seemed that reenabling css3 scrolling
mostly negated the issue.

**Comment by alvarotrigo** [comment]
It should work exactly in the same way with boty, `css3:true` or `css3:false`.

**Comment by sv3k** [comment]
What if I need fast scroll animation (say, 300) and don't want to skip the pages on MacBook? This issue is still alive.
Probably it makes sense to reopen this issue with more specific title: «Scrolling with MacBook Pro touchpad is difficult _on small scrollingSpeed values_».

**Comment by alvarotrigo** [comment]
@sv3k feel free to open a new topic for it. This one has nothing to do with the slow scrolling speed. In fact, the problem didn't exist when it was created.
