### ISSUE TITLE
Does not work with AngularJS

### ISSUE THREAD

**Issue by nikhilvij** [alvarotrigo/fullPage.js#504]
Using Angular, if we re-render only parts of views, we still are left with additional dom inserted into the body for navigation. Is there a way to get around that?

**Comment by volyx** [comment]
+ 1 Plunker

**Comment by CYFERIOUS** [comment]
hey i have the same problem, but its difficult to find an answer, where i have to set the destroy function?

![image](https://cloud.githubusercontent.com/assets/4229345/16700159/0b0a2318-451e-11e6-857b-9c04bb33db40.png)

**Comment by alvarotrigo** [comment]
@CYFERIOUS see the resources section of the docs. There are multiple angular directives created for fullpage.js.
