### ISSUE TITLE
scrollOverflow doesn't work well on touch devices

### ISSUE THREAD

**Issue by vmahabir** [alvarotrigo/fullPage.js#506]
Hi Alvaro, 

First of all; nice job on Fullpage!
I'm implementing it in a responsive Boilerplate template. It seems to work, however I encounter some problems during testing. 

When scrolling (autoscroll = true) from the first slide to the second and to the third; works perfect The fourth and last slide contains the full website content so the fourth slide is bigger than the other slides. I've implemented it in the last slide so there has to be a scrollable area because it's larger than the other three slides. The scrolling in the scrollable area seems very choppy. autoscrolling and scrollOverflow is true. Do you have an idea what's causing this choppy scrolling?  On a mobile device it's really bad..

Also, when scrolling from the third slide to the fourth slide: it looks like the third slide is overlapping the fourth slide at the top while scrolling down to the fourth slide.

Do you have an idea about what could happends at that moment? And can I fix it in some way?
You could view a demopage here: http://vishumahabir.com/test/tmc/fpjstwitter/html/

Thank you!

**Comment by webdrifter** [comment]
This helped me:
http://stackoverflow.com/questions/26334827/slimscroll-bar-very-slow-in-mobile-browser
Downloading v1.3.7 in https://github.com/rochal/jQuery-slimScroll/releases

**Comment by alvarotrigo** [comment]
With the change of slimScroll to iScroll.js in 2.8.0 this issue has been solved.
