### ISSUE TITLE
How to Change Transition slide?

### ISSUE THREAD

**Issue by acitjazz** [alvarotrigo/fullPage.js#517]
hi alvaro .. 
nice plugin very well. :+1: 

but how to change trasition  horizontal slide to fade ?

```
                $('#fullpage').fullpage({
                    anchors: ['slide1', 'slide2', 'slide3'],
                    menu: '.menu',
                    easing: 'linear',
                    animation: "fade",  // <--- can i do this?
                });
```

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
