### ISSUE TITLE
onLeave moveTo function

### ISSUE THREAD

**Issue by Chibz0r** [alvarotrigo/fullPage.js#522]
I am trying to use onLeave to move past slides but it doesn't seem to work.

```
        $('#fullpage').fullpage({
            'verticalCentered': true,
            'css3': true,
            'slidesColor': ['#FFF', '#000', '#FFF', '#FFF', '#FFF', '#FFF'],
            'anchors': ['firstPage', 'secondPage', 'secondPageA', 'secondPageB', 'thirdPage', 'fourthPage', 'fithPage', 'sixthPage', 'seventhPage', 'lastPage'],

            'onLeave': function(index, direction){
                if (index == '1' && direction == 'down'){
                    $.fn.fullpage.moveTo('4');
                }

                if(index == '4' && direction == 'up'){
                    $.fn.fullpage.moveTo('1');
                }

            }

        });
    });
```

I'm trying to use this within the onLeave: function(), so that when the user leaves 'secondPage' in a downward direction they jump to 'thirdPage' alternatively when they leave 'thirdPage' in an upward direction they jump back to 'secondPage' (I have two sections in-between 'secondPageA' and 'secondPageB' which i want to scroll past but not stop on)

**Comment by ZetCoby** [comment]
I used this to make move to work, but then somehow it messes up the navigation menu, is there really no right way to do this? All I want to be able to skip a section on scroll

```
if(index == 6 && direction == "up"){
                $.fn.fullpage.setScrollingSpeed(1500);
                $.fn.fullpage.moveTo(4);
                throw new Error('This is not an error. This is just to abort javascript');
            }
```

**Comment by alvarotrigo** [comment]
@ZetCoby it is not designed to do so.

**Comment by ZetCoby** [comment]
Oh i see, I managed to make a workaround to make it work, Thanks.

**Comment by lakilevi** [comment]
Could you tell me that workaround please? I have the same problem as you.

**Comment by luiscarlospando** [comment]
Same problem here!

I would like to scroll to a specific slide (for example, the second slide, or Index 1) on the upcoming section when scrolling down. Any help will be very appreciated! Thanks.

**Comment by alvarotrigo** [comment]
@luiscarlospando if you want that to be the starting point, why not using the `active` class for that slide?

**Comment by luiscarlospando** [comment]
Gotcha! Sometimes I like to overcomplicate things.

Thank you very much Alvaro!

**Comment by alvarotrigo** [comment]
@luiscarlospando you're welcome!
