### ISSUE TITLE
Moving slides in different sections at the same time

### ISSUE THREAD

**Issue by strechyjohn** [alvarotrigo/fullPage.js#525]
Hi and thanks in advance for any help you are able to offer.

I have three sections, each with the same number of slides in. I am trying to make it so that when I move to a slide in one section, the corresponding slide is scrolled to in the other two sections.

I have read through this post <a href="https://github.com/alvarotrigo/fullPage.js/issues/200">#200</a> and followed the steps as advised. So far I have:

<ul>
<li>Made the <code>scrollSlider</code> function public</li>
<li>Changed the name of the calls to the <code>scrollSlider</code> function inside the <code>scrollPageAndSlide</code> function.</li>
<li>Added a public function to change the <code>scrollingSpeed</code> value
</ul>

I have then used the <code>afterSlideLoad</code> event to do the following:

```
afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
    var crnt = slideIndex;
    var section1 = $('#scan')
    var section2 = $('#text');
    var section3 = $('#notes');

    if (index == 1) {
        $.fn.fullpage.setScrollingSpeed(0);
        $.fn.fullpage.scrollSlider(section2, crnt);
        $.fn.fullpage.scrollSlider(section3, crnt);
        $.fn.fullpage.setScrollingSpeed(700);
    }

    if (index == 2) {
        $.fn.fullpage.setScrollingSpeed(0);
        $.fn.fullpage.scrollSlider(section1, crnt);
        $.fn.fullpage.scrollSlider(section3, crnt);
        $.fn.fullpage.setScrollingSpeed(2000);   
    }

    if (index == 3) {
        $.fn.fullpage.setScrollingSpeed(0);
        $.fn.fullpage.scrollSlider(section1, crnt);
        $.fn.fullpage.scrollSlider(section2, crnt);
        $.fn.fullpage.setScrollingSpeed(3000);   
    }
}
```

The <code>setScrollingSpeed</code> value is different for each section just to test if is working, which it is perfectly. I can't, however, get the slides to move together. The slides in the section that is currently being viewed act as normal, but slides in the 'hidden' sections stay on their current index and do not follow the slideIndex of the slide being viewed.

I've had a good head scratch, but I'm a bit out of my depth to be honest. If anyone would be kind enough to point me in the right direction I would be very grateful.

Many thanks... a rough work in progress is available <a href="http://novawebs.co.uk/gg/test.html">here</a>

**Comment by alvarotrigo** [comment]
This can now be done in some way using the [Interlocked Slides extension](http://alvarotrigo.com/fullPage/extensions/interlockedSlides.html).
