### ISSUE TITLE
How I can make an autoplay of sliders

### ISSUE THREAD

**Issue by tianxxxchris** [alvarotrigo/fullPage.js#532]
How I can make an autoplay of sliders? 

hello thank you very much for your work 
my problem is that I can not do 
the sliders alone activate 
in other words 
I want to make an autoplay sliders 
as I can do? 

thank you very much

**Comment by Codestorming** [comment]
can we pause the slides on hover?

**Comment by alvarotrigo** [comment]
@Codestorming try it.

**Comment by Codestorming** [comment]
I actually took a different approach to my website now.But anyways thanks for the reply.

**Comment by huaucke** [comment]
How i can make an autoplay of sliders by id?
Its posible?

**Comment by HowellCG** [comment]
This is not working for me, could there be an update that has rendered this fix out-of-date?

**Comment by alvarotrigo** [comment]
@HowellCG  it is working [on the link](http://jsfiddle.net/2dhkR/119/). You are definitely doing something wrong.

**Comment by ssuryar** [comment]
This Code however provides auto play. but after placing in HTML (fullPage.js-master/examples/navigationH.html) it adds multiple fpControlArrow code

*******************************************************
$(document).ready(function () {
    $('#fullpage').fullpage({
        sectionsColor: ['#1bbc9b', '#4BBFC3'],
        loopBottom: true,
        afterRender: function () {
            setInterval(function () {
                $.fn.fullpage.moveSlideRight();
            }, 500);
        }
    });
});

***********************************************************

![image](https://cloud.githubusercontent.com/assets/16314650/11830690/62b0ae0e-a3cd-11e5-846c-8020816b20ff.png)

**Comment by ajmaurya99** [comment]
Is there anyway to loop through the sliders.
after reaching at the last slide, it again comes back to the first slide in reverse direction, can me make it a cycle loop.

**Comment by alvarotrigo** [comment]
@ajmaurya99 check out this topic: https://github.com/alvarotrigo/fullPage.js/issues/124

**Comment by rizkysyazuli** [comment]
i have two horizontal slides in my page. and i want to disable this auto-slide on one of the slide using clearInterval like this. but it didn't work. what did i miss?

```
afterLoad: function(anchorLink, index) {
    var autoslide = setInterval(function() {
        $.fn.fullpage.moveSlideRight();
    }, 5000);

    if (index == 3) {
        clearInterval(autoslide);
        autoslide = 0;
    }
}

**Comment by ninadakolekar** [comment]
I want to create some sections that scroll horizontally? I don't want sliders/carousels. I need sections that scroll horizontally. Is that possible with fullPage.js?

**Comment by alvarotrigo** [comment]
@ninadakolekar did you check the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html)?

**Comment by nicolusse88** [comment]
Hi @alvarotrigo,
I'm trying to apply the method to sections instead of slides. It works perfectly with slides, but I don't know what to fix in my script. Could you please help me, I can't find the answer anywhere.

`<script type="text/javascript">
    var myFullpage = new fullpage('#fullpage', {
		continuousVertical: true,
                css3:false,
		afterRender: function () {
		setInterval(function () {
		$.fn.fullpage.moveSectionDown();
		}, 1500);
		}
		});
</script>`

**Comment by Matokosp** [comment]
Hello, the fiddle is not working, and when I copy the code it gives me an error:

 "Uncaught TypeError: $(...).fullpage is not a function
    at index.html:101"

I've tried to fix it but it doesn't work, Could you help me please?

> @HowellCG it is working [on the link](http://jsfiddle.net/2dhkR/119/). You are definitely doing something wrong.

**Comment by alvarotrigo** [comment]
The code is using the jQuery initialization. 
Just transform it to pure javascript according to the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) if you are not using jQuery.

**Comment by jloguercio** [comment]
Hi, its possible to autoslide only one slide section and leave the others only to use the keyarrows?

**Comment by alvarotrigo** [comment]
@jloguercio many things are possible with the right knowledge. Use the search on this forum or on Google to find your answer. It has been answered many times.

**Comment by zeroseisdesign** [comment]
Hi, how I can configure slides autoplay in Angular? Thanks in advance.

**Comment by alvarotrigo** [comment]
> Hi, how I can configure slides autoplay in Angular? Thanks in advance.

Same way than here:
https://alvarotrigo.com/fullPage/help/how-to-autoplay-vertical-section-in-fullpage-js/
https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/

**Comment by zeroseisdesign** [comment]
I was trying with this: https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/
but Angular doesn't find the name 'fullpage_api' in this code and can't compile:
`afterLoad: function (origin: any, destination: any, direction: any) {
        clearInterval(g_interval);
    
        // 1000 milliseconds lapse
        const lapse = 1000;
        
        const shouldAutoPlay = destination.item.hasAttribute('data-auto');
    
        const hasSlides = destination.item.querySelectorAll('.fp-slides').length;
        
        if(shouldAutoPlay && hasSlides){
          g_interval = setInterval(function () {
            fullpage_api.moveSlideRight();
          }, lapse);
        }
      },

    };`

Any idea?

Thanks

**Comment by zeroseisdesign** [comment]
> > Hi, how I can configure slides autoplay in Angular? Thanks in advance.
> 
> Same way than here: https://alvarotrigo.com/fullPage/help/how-to-autoplay-vertical-section-in-fullpage-js/ https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/

[zeroseisdesign](https://github.com/zeroseisdesign) commented [23 minutes ago](https://github.com/alvarotrigo/fullPage.js/issues/532#issuecomment-1101280544) • 
edited 
I was trying with this: https://alvarotrigo.com/fullPage/help/how-to-autoplay-horizontal-slides-in-fullpage-js/
but Angular doesn't find the name 'fullpage_api' in this code and can't compile:

`afterLoad: function (origin: any, destination: any, direction: any) {
clearInterval(g_interval);

    const lapse = 1000;
    
    const shouldAutoPlay = destination.item.hasAttribute('data-auto');

    const hasSlides = destination.item.querySelectorAll('.fp-slides').length;
    
    if(shouldAutoPlay && hasSlides){
      g_interval = setInterval(function () {
        fullpage_api.moveSlideRight();
      }, lapse);
    }
  },

};`
Any idea?

**Comment by alvarotrigo** [comment]
@zeroseisdesign for angular issues please use [the angular wrapper forum](https://github.com/alvarotrigo/angular-fullpage/issues).
