### ISSUE TITLE
The page scroll effect screws up on zooming CTRL + mouse

### ISSUE THREAD

**Issue by surajwy** [alvarotrigo/fullPage.js#55]
When we run the demo page of fullPage.js on NO zoom, i.e. default , it works absolutely fine, but when we zoom in or out and the try to scroll, it gets screwed a bit. 
Though at the end of animation it reaches the right section but the effect gets faulty(it jumps up say 200px and then start scrolling from there, till the correct section's top).
I have seen this happening on Safari. 
Rest in Chrome,FF and IE its working great.
My OS X version is 10.8
and Safari version is 6.0 (8536.25)

**Comment by prusieck** [comment]
I possibly should have found that issue first, before reporting.

I am able to replicate the issue in Chrome and Internet Explorer. In principle the zoom does work while pressing ctrl and scrolling the mouse, however it also keeps scrolling the webpage. On regular webpages when you use this combination scrolling is disabled and the pate zooms only.

I have a feeling that it it could be possible to stop this by disabling the scroll when the ctrl button is pressed. I will be looking into the code over the next few days.

**Comment by alvarotrigo** [comment]
> I have a feeling that it it could be possible to stop this by disabling the scroll when the ctrl button is pressed. I will be looking into the code over the next few days.

Yeah, that sounds like a possibility.

**Comment by alvarotrigo** [comment]
The problem is with the resize event and the redimension of the sections. That's related with [this other issue](https://github.com/alvarotrigo/fullPage.js/issues/64).

**Comment by alvarotrigo** [comment]
Solved in the latest release 2.6.5.

The plugin won't scroll to any other section now. I believe this is as far as we can do to deal with this functionality as the zoom will affect the size of the sections and they would need to recalculate its dimensions and fit on the screen.
