### ISSUE TITLE
"scrollOverflow: true" prevents page from scrolling when autoScrolling is off

### ISSUE THREAD

**Issue by d13** [alvarotrigo/fullPage.js#553]
If you add `allowPageScroll: true` to the .slimScroll options (approx line 1251), this will work as expected.

**Comment by alvarotrigo** [comment]
Fixed in the latest version 2.6.5.

**Comment by Rilliano** [comment]
Can i use "scrollOverflow: true" only on a spicific section, not all the sections?

**Comment by Gayathriram** [comment]
In mobile fullpage.js  is not scrolling in my wordpress one page themes,  can anyone give me solution?

**Comment by HandHugs** [comment]
I had to change the sensitivity setting on mobile to get it to work. Not sure if that is the same issue you are encountering but here is the code that I used: 
`jQuery(document).ready(function($) {
					if ( $(window).width() < 800 || window.Touch) { 
						var $sensitivity = 10;
					} else{
						var $sensitivity = 100;
					}
					$('#fullpage').fullpage({
						verticalCentered: true,
						scrollOverflow: false,
						paddingBottom: '0',
						scrollingSpeed: '800',
						navigation: true,
			    		navigationPosition: 'right',
			    		fixedElements:'#header',
			    		resize: false,
						css3: true,
						touchSensitivity: $sensitivity

					});
				});
`

**Comment by Gayathriram** [comment]
Thank you so much for reply and rectify the my problem.Thanks
