### ISSUE TITLE
Provide an uncompressed version of slimscroll.js

### ISSUE THREAD

**Issue by d13** [alvarotrigo/fullPage.js#556]
As noted in https://github.com/alvarotrigo/fullPage.js/issues/553 I had to update slimscroll.js to fix an issue with it. Doing so was very difficult since slimscroll.js was modified for fullpage.js and only the minified version is provided.

If an uncompressed version is additionally provided, its easier to make these upgrades and troubleshoot.

Thanks,
Keith

**Comment by alvarotrigo** [comment]
I've added it to the repository.
