### ISSUE TITLE
TypeError: element.find(...).get(...) is undefined

### ISSUE THREAD

**Issue by davidrh90** [alvarotrigo/fullPage.js#573]
Hi I'm using scrollOverflow: true option and scroll didn't work. I added the including files: jquery.slimscroll.min, jquery.easings.min and jquery.fullPage. I need this option, because I have sections with different heigths. 

Error in javascript console: 
![captura de pantalla 2014-07-16 a la s 11 26 32](https://cloud.githubusercontent.com/assets/7403698/3596878/64d48a06-0ccb-11e4-8719-69079fd77410.png)

**Comment by langert** [comment]
Hi, I have the same Problem while using bootstrap 3. But in my case, the error message only shows up, when setting a invidivual sliderSelector. If I do not change it and my slides are named ".slide", then I got in mightly get in trouble with bootstrap. So, how is the correct way to use?

**Comment by alvarotrigo** [comment]
@langert you probably are doing something wrong. Give us a link to your page.

**Comment by langert** [comment]
Hi,

the project url should not be made public yet

http://germany.neubert-jones.com/#

Thank in davance
Timo

Am 20.02.2015 um 17:42 schrieb Álvaro:

**Comment by alvarotrigo** [comment]
You shouldn't be having only one single slide in a section. It makes no sense. Try removing it and leaving just a section.
Also, i you can change fullPage.js for the unminified version that'd be better for debugging until we solve the problem.

**Comment by langert** [comment]
thanks, that was the right hint! renamed the div elements with just a single slide and now it works without error message
