### ISSUE TITLE
One "section" only.

### ISSUE THREAD

**Issue by mfgabriel** [alvarotrigo/fullPage.js#581]
Hello, I would like to know if there is a way I could use only one single piece of my website as a "section" to pass through only one scroll, and the rest of the website use it normally!

Thank you.

**Comment by Rumodan** [comment]
Hi, I'm facing an issue with your (amazing) plugin.

I would like to use it as descripted above (use fullpage on a single section), but your fiddles aren't working (tested them on latest Chrome and Firefox version). When you scroll the first section it behaves like fullpage isn't active, and then the page scrolls back to top.

Can you help me solving this? At least to fix the fiddles, with a working example I can work by myself...

Thanks a lot in advance, have a nice day.

**Comment by alvarotrigo** [comment]
> When you scroll the first section it behaves like fullpage isn't active, and then the page scrolls back to top.

Use the option `fitToSection:false`.

**Comment by Rumodan** [comment]
Hi, thanks for the quick answer.

Just tried your solution on your fiddles, in both cases the page doesn't
scroll back to top, but, it still behaves like fullpage isn't active.

I'm sorry for my previous bad explanation (and bad english too), what I
need to achieve is to have as first section of the page a fullpage slider
(and I was able to do it), use fullpage to scroll away all the slider (been
able to do this too), and then have the rest of the content behaving
normally (this is my problem).

Maybe now that I've been clearer you can help me!



Daniel



Daniel Capurro
Content manager @Videeco.com <http://videeco.com/>
Solution manager @Stamp'a'Biella <http://stampabiella.com/>



2016-06-23 11:33 GMT+02:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
> it still behaves like fullpage isn't active.

As expected. Because you are using `autoScrolling:false`.

The only other option is to use scrolloOverflow:true and have something like [in the scrolling example](http://alvarotrigo.com/fullPage/examples/scrolling.html)

**Comment by Rumodan** [comment]
Thanks, using `scrollOverflow` I've been able to have it working as I needed.

Thank you for your help and for the patience you showed with a noob like me.

Have a nice day.

**Comment by rohanchambers** [comment]
Hello. Just to say what a great plugin, so many great features however I am having problems with what the people above have asked for. I was wondering is it possible at all to have only the first div to have the full page affect and then have the rest of the site work as normal. I have been using all the options including the scrolloverflow that you mentioned but nothing seems to work. It just blocks at the second div and doesn't show the rest of the divs. I have followed all the instructions exactly for markup. Thank you for getting back to me.

**Comment by alvarotrigo** [comment]
> I was wondering is it possible at all to have only the first div to have the full page affect and then have the rest of the site work as normal.

Use `scrollOverflow:true` http://jsfiddle.net/97tbk/1345/

**Comment by rohanchambers** [comment]
I am so sorry but I can't seem to replicate this fiddle on my project let alone on a stand alone html page. I have literally copy pasted your fiddle same links same everything. I get this error: 2jquery.fullPage.js:2771 Uncaught TypeError: scroller.wheelOff is not a function
I am sure it's something really small but I have a link that shows the issue. If you have any ideas and a little time that would be great. Many thanks. 
http://www.rohanchambers.net/projects/test/test.html

**Comment by alvarotrigo** [comment]
@rohanchambers if you read the docs you'll find that:

>  it requires the vendor library scrolloverflow.min.js and it should be loaded before the fullPage.js plugin. For example:

Which you are not doing.

**Comment by rohanchambers** [comment]
@alvarotrigo Sorry, me just being careless. Working fine now. Many thanks and what incredible plugin you have built.

**Comment by Shashank-Bhatt1** [comment]
How to enable padding on other normal sections that are below the main section? Only the first section that is in wrapper only applies padding.

**Comment by BenRacicot** [comment]
This plugin is still amazing in 2018. @alvarotrigo  you mentioned: 

> Use scrollOverflow:true for the 2nd section http://jsfiddle.net/97tbk/1345/

That second section is still fixed height and not scrollable in the fiddle. Is there a way to setup the markup so you can "scroll past" the #fullpage sections and into normal scrollable content? Thanks.

**Comment by alvarotrigo** [comment]
@BenRacicot glad you like it!
Regarding your issue, you'll have to use the latest scrolloverflow version, there was a bug that was fixed and that will get released on the next release. 
Here you have the fiddle with the latest scrolloverflow version iScroll.js 0.0.5 (right now available [on the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js))

http://jsfiddle.net/97tbk/2246/

**Comment by BenRacicot** [comment]
Wow @alvarotrigo really impressive and exactly what I was looking for. Thank you very much for replying.

**Comment by vbalasubramani** [comment]
I do have the same problem. Can you provide me the js fiddle link?

**Comment by alvarotrigo** [comment]
Unfortunately jsfiddle has removed thousands of URLs for a strange reason. Nothing we can do. 
I'll just start using codepen more now after the experience...

**Comment by piyushchauhan** [comment]
Is there any alternative similar page link? It would be of great help.

**Comment by alvarotrigo** [comment]
See [this example](https://alvarotrigo.com/fullPage/examples/oneSection.html) which is available on the [demo page](https://alvarotrigo.com/fullPage/) examples link.

**Comment by piyushchauhan** [comment]
Actually, what I want is little different from https://alvarotrigo.com/fullPage/examples/oneSection.html this.
I have some content (divs) on my page and below all that I want a slider section. Will it work when the section is just way below before the footer? @alvarotrigo

**Comment by alvarotrigo** [comment]
You probably want to look at other sliders out there.
This is a fullpage slider. Though to be used in full screen as the only main element in the page.

**Comment by stivoox** [comment]
@alvarotrigo Thanks for this great plugin , but how to have this smooth scolling effects with one single section : https://alvarotrigo.com/fullPage/examples/oneSection.html and I want to know if there's a way to add a button to scroll down to rhe rest of content . 
Thanks

**Comment by soham98** [comment]
Hi, so I'm trying to achieve the same effect of having only the first few sections of my website work to have the fullpage effect and the following pages to go back into a normal scroll. Except I'm using webflow and I don't know what to write in the body section. (I followed your video on how to set it up)

**Comment by alvarotrigo** [comment]
@soham98 look at [this site](https://www.espasso.com/storefront/test). They seem to have implemented a good enough solution by using  `scrollBar:true` and some custom code.
