### ISSUE TITLE
Dissapearing navigation with css3:true

### ISSUE THREAD

**Issue by tomi-os** [alvarotrigo/fullPage.js#586]
I've noticed some funky horizontal navigation behavior when using css3:true. It sometimes disappears (both the arrows and the dots), they are there and you can click on them and they reappear when you slide on (and sometimes stay on, sometimes disappear again). I can't seem to find any pattern to it.

Only happens in Chrome and Opera tho.

**Comment by alexeyenko** [comment]
Applying -webkit-transform: translate3d(0,0,0); to .fp-controlArrow solves the problem.

**Comment by gtluszcz** [comment]
Thanks a lot alexeyenko! I've been searching for this problem solving for a couple of hours. You realy made my day :D. It needs to be pulled into base code.
