### ISSUE TITLE
Is it possible listen the scroll event when set scrollOverflow as true?

### ISSUE THREAD

**Issue by xinz** [alvarotrigo/fullPage.js#589]
Hello,

I'm setting `scrollOverflow` as true to resolve the last section displaying with the footer case, however I want to setup a scroll event(e.g. $(window).scroll();) to process some html elements when scrolling the scrollbar in this section, but I don't find the way to do, please advise.

Thanks in advance!

**Comment by Ashhadsmallaxe** [comment]
For those still searching for this. Found something that might be useful we can use the initialized scroll overflow 

```javascript
var sections = jQuery.fn.fp_scrolloverflow.iscrollHandler.iScrollInstances;

sections.forEach(function (elem){
    elem.on('scrollStart', function(){
		console.log('scroll'); 
	});
});
```
