### ISSUE TITLE
fullPage.js + parallax

### ISSUE THREAD

**Issue by toastedpixel** [alvarotrigo/fullPage.js#59]
Hi! Does anyone tried to make parallax effects with the fullpage.js? Is that possible combine with other code?

**Comment by ProfCMA** [comment]
Is this to say that using css based parallax is not possible?

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
