### ISSUE TITLE
Make it compatible with full page backstretched images

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#6]
Something like :

http://srobbin.com/jquery-plugins/backstretch/

**Comment by firojkhan-UI** [comment]
Hi...!
I'm trying to set background image can you tell me which props name to pass fro background images ?

**Comment by alvarotrigo** [comment]
@firojkhan-UI check the backgrounds.html example:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/backgrounds.html

**Comment by firojkhan-UI** [comment]
Hi Alvarotrigo,
But I'm using React hooks It's working  when i passed color inside sectionsColor,
for example : sectionsColor={["#FF5733","#FFBD33","#DBFF33","#75FF33","#33FF57","#FFBD33","#DBFF33",]}
But my requirement how to set images for background ?

**Comment by alvarotrigo** [comment]
Using CSS? :)
