### ISSUE TITLE
"Footer" content underneath section with slides

### ISSUE THREAD

**Issue by eneles** [alvarotrigo/fullPage.js#601]
Hi,

The last full-page section of a web page I'm building contains slides. I want to include footer content (copyright info, etc) below the slides, that the user can scroll normally to, without having to jump into another section. 

I'm using scrollOverflow and the slimScroll plugin within sections, and I'd like the slides to slide normally, independent of any footer content, but I can't seem to find a way to make it work. I've included a diagram that will hopefully explain further what I'm trying to achieve.

![full-page-slides-with-footer-scrollable](https://cloud.githubusercontent.com/assets/8262108/3715947/becf0430-15fb-11e4-9302-295fed8eee72.png)

I can include a footer on other pages where the last full-page section does not have any slides, and the user can simply scroll into the footer normally, but when the last section does have slides, the slides seem to take control of the entire section and not allow any extra content. I've tried a bunch of different styling methods to try and display footer content, but haven't come up with a solution.

**Comment by Tharaka-karunarathne** [comment]
http://jsfiddle.net/reddy887/o4uywjrn/ Here they have done that. But I cant get the code where the trick happens. Can some one explain.

**Comment by Battin** [comment]
Thanks Tharaka,

but it does not solve the problem we're trying to solve. What you want is really a footer that is scroll-able like any other normal page. Not another container that you can not scroll.

**Comment by owenXin** [comment]
I think I found one solution, that is when you want the page scroll as normal, just call function ```$.fn.fullpage.setAutoScrolling(false);```
and you can call ```$.fn.fullpage.setAutoScrolling(true);``` to make it change back to the sliders.
