### ISSUE TITLE
Scrolling the page body? (paralax)

### ISSUE THREAD

**Issue by aaronware** [alvarotrigo/fullPage.js#603]
Just wondering if you have ever set up fullPage.js to adjust the scrollTop of the page instead of moving the container? If not I was going to build that option into a fork a do a pull request if interested. I didn't see anything in the code that jumped out at me that this functionality was available.

The reason for the functionality is to work with other libraries that interact with the scroll position of the page, waypoints, parallax libraries etc.

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
