### ISSUE TITLE
onLeave direction parameter

### ISSUE THREAD

**Issue by adamvranckx** [alvarotrigo/fullPage.js#609]
I followed the documentation to create an "onLeave" function, however it doesn't seem to work with the direction parameter. If i remove the direction parameter the function will fire upon leaving the specific section however the direction is key to the effects i want to achieve. I've copy and pasted your example form the documentation with no success. Here is my current implementation:

``` javascript
$('#fullpage').fullpage({
        verticalCentered: false,
        animateAnchor: false,
        resize : false,
        anchors: ['home', 'mission', 'curriculum', 'menu', 'information', 'contact'],
        menu: '#submenu',
        scrollingSpeed: 700,
        autoScrolling: false,
        css3: false,
        paddingTop: '0',
        paddingBottom: '0',
        normalScrollElementTouchThreshold: 5,
        keyboardScrolling: true,
        touchSensitivity: 15,
        continuousVertical: false,
        scrollOverflow: false,
    onLeave: function(index, direction){
            //after leaving section 2
            if(index=="1" && direction =="down"){
                alert("Going to section 2!");
            }
            else if(index=="2" && direction =="up"){
                alert("Going to section 1!");
            }
        }


});
```

**Comment by versionmj** [comment]
alvarotrigo, I realize that this response is old but I am currently having the same issue as above and the docs say: 

"onLeave (origin, destination, direction)
This callback is fired once the user leaves a section, in the transition to the new section. Returning false will cancel the move before it takes place.

Parameters:

origin: (Object) section of origin.
destination: (Object) destination section.
direction: (String) it will take the values up or down depending on the scrolling direction."

Please clarify. Thanks.

**Comment by alvarotrigo** [comment]
Version 3 of fullpage.js changed the signature of the callback, changing the parameters.

**Comment by versionmj** [comment]
I am using the direction parameter exactly as shown in the docs and it i not working ie. 

>  if ( destination.index == 2 ){ do something }  

Please advise.  Thanks.
