### ISSUE TITLE
Normal scrolling after one section

### ISSUE THREAD

**Issue by agaletta** [alvarotrigo/fullPage.js#614]
Hi, I have a scrolling vertical section in 100% height of viewport for each section. Under last section i have a footer. I would set autoScrolling to false when i'm in last section because i need to set normal scrolling behaviour and then, in direction up, re-set autoScrolling to true. 

My code:

``` javascript
  var actualIndexSlide;
  var totalSlides = $('main > section.section').length;
  $('#main').fullpage({
    // autoScrolling: true,
    css3: true,
    verticalCentered: false,
    touchSensitivity: 15,
    easing: 'easeInCirc',
    normalScrollElements: '.fd-footer',
    resize: false,
    scrollingSpeed: 700,

    afterRender: function(){
      console.log("rendered");
      $('main > section').css('height','auto');
    },

    afterResize: function(){
      console.log("resize");
      $('main > section').css('height','auto');
    },

    afterLoad: function(anchor, index){
      actualIndexSlide = index;
      // console.log("after load | anchor:"+anchor+" | index: "+index);
      if(actualIndexSlide == totalSlides) {
        // $.fn.fullpage.scrollOverflow(false);
        $.fn.fullpage.setAutoScrolling(false);
      }
    },

    afterSlideLoad: function(anchorLink, index, slideAnchor, slideIndex){
    console.log("hereeee");
    },

    onLeave: function(index, newIndex, direction){
      console.log("nuova "+newIndex);
      console.log(index+"-"+totalSlides);
      console.log(direction);
      if(direction == "up" && index == totalSlides) {
        // $.fn.fullpage.moveSectionUp();
        $.fn.fullpage.moveTo(newIndex);
        setTimeout(function() {
          $.fn.fullpage.setAutoScrolling(true);
        }, 1300);
      }
    }

  });
```

When i'm coming from last slide in up direction to second-to-last i have a flickering.
I have 2 problem: afterSlideLoad not firing, never! And a blank page in google chrome on MAC.

Any solutions? 
Thanks and sorry for my english! :)

**Comment by markadrake** [comment]
+1 for this functionality. I'm working on the implementation of a design where the brand wants to use fullpage.js to communicate it's message one "slide" at a time, but when you reach the last slide (which is full page of course) the footer of the site cannot be reached. I'd like to suggest this be a feature that's implemented into the core project.

**Comment by markadrake** [comment]
This is actual similar enough to #696 that the solution you provided there works for the intended purpose of my design. :)

**Comment by alvarotrigo** [comment]
> the footer of the site cannot be reached. I'd like to suggest this be a feature that's implemented into the core project.

You can always use `fp-auto-height` for the footer as [in this example](http://alvarotrigo.com/fullPage/examples/autoHeight.html).

**Comment by dangelion** [comment]
+1

**Comment by rahulmax** [comment]
:+1: You're right, @alvarotrigo I was looking for this functionality for the footer and `fp-auto-height` does exactly this. Better experience than switching to normal scroll just for the footer.

**Comment by ctf0** [comment]
am having the same issue, with the latest build, i set `fitToSection: false,` but no luck :(

**Comment by alvarotrigo** [comment]
@ctf0 if you try the latest dev version [2.7.8 (Beta)](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js), you can use normal scrolling in sections by using the class `fp-normal-scroll` in the section you expect to have normal scrolling. Then use the option `hybrid:true` in fullpage.js initialisation. 

This is a feature under testing and therefore it is not perfect and will probably have bugs.

**Comment by ctf0** [comment]
@alvarotrigo right now i found a way around, not perfect but for now it works,
i set 
```
fitToSection: false,
autoScrolling: false,
```
and nothing add to the footer, ofcourse the autoscroll doesnt work but maybe that would help u with ur debug, thanx again

**Comment by codercooooder** [comment]
Hey Alvaro, 

I love that you are adding this feature - but I can't seem to get it to work (although you state upfront that it might still be buggy because this is a beta).  I am wondering if I am applying the settings correctly. 

I would like fullpage.js to use normal autoScrolling when transitioning from the first section (Section0), to the second section (Section1) , and from that point on, on all subsequent sections (e.g. Section2, Section3, Section4) for autoScrolling to be disabled: I don't want any jumping behavior after Section1 loads. 

In order to accomplish this, you indicated that I set `hybrid:true `in fullpage.js initialisation, that is clear, but I have some other questions. 

 1.  What should the AutoScrolling setting be set to , do I set it to 'false' or just leave it be, on its default setting 'true'?  
 2.  So, is it correct that all sections lacking the class "fp-normal-scroll" will not autoscroll if hybrid is set to 'true'?

Thanks!

**Comment by alvarotrigo** [comment]
It is a concept under development, so it is not perfect. Right now it won't auto scroll back to the 1st section:

[Demo online](http://jsfiddle.net/97tbk/1191/)

```javacript
$('#fullpage').fullpage({
    sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
    hybrid:true,
    fitToSection: false
});
```

**Comment by codercooooder** [comment]
Alvaro, sorry I don't understand.  I thought this feature turned off autoScrolling/page jumping for sections lacking the class.  I don't see any difference the old default and the demo you supplied. I apologize if I am being dense.

**Comment by alvarotrigo** [comment]
In my demo you have autoscrolling from 1st section to 2nd. Then normal scroll.

**Comment by codercooooder** [comment]
I tested your demo in chrome and firefox, as far as I can tell it autoScrolls in all sections.

**Comment by alvarotrigo** [comment]
@codercooooder tested on Mac and Windows, Chrome and Firefox. It autoScrolls from 1st to 2nd and then uses normal scroll.

**Comment by codercooooder** [comment]
when you say autoscrolling - you mean section jumping, and by normal scroll  - you mean when I press the down arrow key it should not jump sections??? Because when I press the down arrow key it is scrolling down to the next section. If it press it four times after loading the jsfiddle, I reach the bottom of the page - each key press of the down arrow key makes the section jump.  Other people in a forum who I had test this produced the same thing. Are you testing on a mobile device? I'm on a laptop.

**Comment by alvarotrigo** [comment]
Nothing to do with the keyboard navigation. Read the docs regarding autoScrolling for more info.

**Comment by codercooooder** [comment]
autoScrolling and Keyboard navigation are not the same thing?

**Comment by codercooooder** [comment]
Can you turn off keyboardScrolling for certain sections only?

**Comment by codercooooder** [comment]
From reading the documentation, setKeyboardScrolling turns off keyboard functionality completely.  I want the keyboard arrow to work but NOt in an autoscroll/section-jumping way, but instead I want the keyboard to work in a slow/traditional/normal/incremental way, but only for the last sections.

**Comment by alvarotrigo** [comment]
Just use a callback for it and set it off for any other section rather than the 1st one by using setKeyboardScrolling.

**Comment by codercooooder** [comment]
I don't understand this, I just posted my question on stackExchange. http://stackoverflow.com/questions/36610071/producing-autoscrolling-with-keyboard-but-only-only-for-some-sections-when-u

**Comment by codercooooder** [comment]
Alvaro, the callback almost does the trick- how do I adapt this so that the keyboard skipping is turned on **only when I scroll from section0 to section1 and then never turned back on?  **  Scrolling up from second section (section1) back to the first section (section0) creates problems on my page.

**Comment by codercooooder** [comment]
I posted my follow-up question on StackExchange, as well: http://stackoverflow.com/questions/36649572/fullpage-js-autoscrolling-and-keyboard-jump-only-when-leaving-not-returningas well:

**Comment by alvarotrigo** [comment]
@codercooooder please stop adding post in this topic. Your question is totally out of topic and it is very specific issue for your use case.

**Comment by codercooooder** [comment]
Should I open an new thread?

**Comment by alvarotrigo** [comment]
@codercooooder not really. Just use stackoverflow.

**Comment by fschneid** [comment]
The hybrid feature works great. Except if you scroll in your [demo](http://jsfiddle.net/97tbk/1191/) from slide1 to slide2 auto-scroll is enabled. But if you scroll up from slide2 to slide1 auto-scroll is disabled. Is there any way to enable auto-scroll if you scroll from a section with normal-scroll to a section with auto-scroll? Thanks.

**Comment by alvarotrigo** [comment]
> Except if you scroll in your demo from slide1 to slide2 auto-scroll is enabled. But if you scroll up from slide2 to slide1 auto-scroll is disabled.

As I said:

> This is a feature under testing and therefore it is not perfect and will probably have bugs.

**Comment by fschneid** [comment]
Ok, I managed to create a workaround by adding a scroll animation inside the onLeave handler. Little bit hacky but it works.

**Comment by KokoDonchev** [comment]
Hi @alvarotrigo,

Firstly, great job with all of the functionality that you have added into this, I love using it!
Today I went into one problem, I am using the `fp-normal-scroll` class for few sections but so far I can't make it work on mobile and unfortunately I need it to be working there as well, right now it seems to be ignoring the class entirely, I checked the unminified version but I am not really sure why this is happening. Any advices?

Thanks!

**Comment by alvarotrigo** [comment]
> I am using the fp-normal-scroll class

That feature was never documented and still under development. Support for it is not provided I'm afraid.

**Comment by s10wen** [comment]
I think I have a similar issue. I have multiple slides, then I'd like 'normal' scroll for a large footer (that allows all the content to be shown).

The following demo works well for a small footer:
https://alvarotrigo.com/fullPage/examples/autoHeight.html#3rdPage

I've created a demo for the issue I'm having with the large footer:
https://codepen.io/s10wen/pen/eVoMga

Thanks in advance for any help :)

**Comment by alvarotrigo** [comment]
@s10wen use scrollOverflow:true. Then put all your content in your last section. That will emulate the behaviour you want. `hybrid` and `fp-normal-scroll` are not supported features.

**Comment by s10wen** [comment]
@alvarotrigo jackpot! Is there a way to manipulate the `.fp-nav` as so:

`.section header-slide` = no nav
`.section slide-one` = nav starts on 1 (and shows 3)
`.section slide-two` = nav 2 (and shows 3)
`.section slide-one` = nav ends on 3 (and shows 3)
`.section footer-slide` = no nav

p.s. I found https://github.com/alvarotrigo/fullPage.js/issues/1110 but it looks like the demo is a 404 http://jsfiddle.net/97tbk/512/

**Comment by alvarotrigo** [comment]
Make use of [fullPage.js state classes](https://github.com/alvarotrigo/fullPage.js#state-classes-added-by-fullpagejs) or [callbacks](https://github.com/alvarotrigo/fullPage.js#callbacks) for that. 
Check [this video tutorial I did](https://www.youtube.com/watch?v=qiCVPpI9l3M) regarding css3 conditions based on fullpage.js state classes.

**Comment by taraskhvyl** [comment]
> The hybrid feature works great. Except if you scroll in your [demo](http://jsfiddle.net/97tbk/1191/) from slide1 to slide2 auto-scroll is enabled. But if you scroll up from slide2 to slide1 auto-scroll is disabled. Is there any way to enable auto-scroll if you scroll from a section with normal-scroll to a section with auto-scroll? Thanks.

hi. this is actual question. any updates on it? how can i make auto scroll from 2-nd section? 

thank you

**Comment by alvarotrigo** [comment]
> any updates on it?

If there were, you'll see my comment on it. 
But you can't see any right? Then there's none :)

**Comment by taraskhvyl** [comment]
> > any updates on it?
> 
> If there were any, you'd see my comment on it.
> But you can't see any right? Then there's none :)

I can share my fast solution for it. Maybe it will help somebody :)

`let allowScrollTop = false;
    
	$('#fullpage').fullpage({
		hybrid:true,
		fitToSection: true,
        
		afterLoad : function( anchorLink, index) {
		    
		    if(index === 2) {
				allowScrollTop = true;
			}
		}
	});
    
	$(window).on('scroll', function() {
		let scrollTop = $(window).scrollTop();
        
		if((firstScreenHeight > scrollTop) && (allowScrollTop === true)) {
			$.fn.fullpage.moveSectionUp();
			allowScrollTop = false;
		}
	});`

**Comment by vanhunselm** [comment]
@taraskhvyl Do you have an example to show?

**Comment by alvarotrigo** [comment]
This is finally possible now in v4! 🥳 👯 🕺 🎈 

It took 7 years and a half but we got there!! :) 
I'll be adding examples soon.

**Comment by alekskravchenko** [comment]
> 

Hey @alvarotrigo, can you please explain how to implement this feature in v4?

**Comment by alvarotrigo** [comment]
Sure, just add any content after fullPage.js and that's it :)
You can see a working example on the examples folder:
https://github.com/alvarotrigo/fullPage.js/blob/master/examples/scroll-after-fullpage.html
