### ISSUE TITLE
Min-Height/Min-Width settings 

### ISSUE THREAD

**Issue by JeanHules** [alvarotrigo/fullPage.js#627]
Is it possible to set min-width and height settings? I am running into issues where I only want the site viewable on desktop and tablet as the content is not responsive enough to go down to mobile.

**Comment by alvarotrigo** [comment]
You can not use the `responsive` option detailed in the docs: 

> **responsive:** (default 0) A normal scroll (autoScrolling:false) will be used under the defined width in pixels. A class fp-responsive is added to the plugin's container in case the user wants to use it for his own responsive CSS. For example, if set to 900, whenever the browser's width is less than 900 the plugin will scroll like a normal site.
