### ISSUE TITLE
on window resize, current page resets too slowly, background image reset not ideal

### ISSUE THREAD

**Issue by acturbo** [alvarotrigo/fullPage.js#64]
Really great component. Should become a classic in no time.
1. When the browser window is resized, the current page should update instantly along with the window resize. Currently, there is a delay, then a slow animation to reset the current page properly. It looks terrible. Can you please change this, or add an option (and make it default) FastResizeUpdate = true. Meaning, no animations to reset the current page/slide when resizing --- just do it instantly. It is one of the few missing features keeping me from building 2 client sites using this awesome plugin. I see some improvement by by changing 500 to 100 on line 658 ... in $(window).resize(function() ...
2. The other issue relates to resizing the background image proportionately. I use full page background images, but when the browser window is resized, the plugin fails to recalculate whether to use the height or the width of the image at 100% to properly fill the screen. This should be updated upon an window resizing, and re-focus (as you tab between other web sites, resize the window, the return to your site that has this component, the "current" div/page has to be reset instantly). 

To test what im saying, open your demo, go to section 2 (any section other than the 1st/top one), then resize your browser, you will see the messy animations struggling to update. I should not see other pages/slides -- i should only see my current page/slide being updated. It should be instant -- no animations. Animations should be used only when a user clicks a link, or performs a distinct movement (up arrow, etc.). That is, you animate his intentions to move/jump etc. All other updates and refreshes (non-user initiated) should be instant.

Seems both should be very doable.
Keep up the GREAT work. Thanks.

**Comment by jeffxu** [comment]
For the first question, I think the animation is caused by below inline css code which are generated to the '#js_fullpage' div by fullscreen.

```
-webkit-transition: all 700ms ease; transition: all 700ms ease;
```

So my quick solution is to remove those transitions after window resize. It works for me.
```     
afterResize: function() {
     var offset = $('#js_fullpage').offset();
     var top = parseInt(offset.top);
     $('#js_fullpage').attr('style', 'height: 100%; position: relative; touch-action: none; -webkit-transform: translate3d(0px, '+top+'px, 0px); transform: translate3d(0px, '+top+'px, 0px);'); 
}, 
```

**Comment by alvarotrigo** [comment]
Improved in the latest release 2.6.5. It might be improved even more in a future. So I'll keep the issue open.

**Comment by williamhodge** [comment]
On my site, when you resize the screen in IE the blue border doesn't resize until you start scrolling.  Can you help me with this issue?

**Comment by Google-material-icons** [comment]
https://hypertexter.space/questions/utilizing-jquery-for-a-dynamic-sliding-effect-using-the-animate-function-to-shift-text-horizontally-based-on-a-percentage-of-the Mystery solved
