### ISSUE TITLE
snap when stop scroll

### ISSUE THREAD

**Issue by okbk** [alvarotrigo/fullPage.js#647]
Hello, is it possible to allow someone to freely scroll and then when you 'let go' it snaps to the relevant slide?

**Comment by OpsinM** [comment]
> > is there some sort of delay before it snaps? Seem a little 'slow' to act and snap after stopping scrolling?
> 
> Yeah, exactly. The user has to stop for it to work and fullPage waits 1 second to start the auto scrolling. This was done on purpose so the user won't get crazy with the plugin scrolling by itself when they haven't decided yet where to stop.

Hello, Im missing exactly that feature. But that 1 second before it auto scrolls is something I need to change. For me its so annoing to always wait that 1 second before it snaps. Would it be possible that it take the speed of the scroll and then instantly starts a smooth eased scroll to the section? Or for the auto scrolling, does a option exist, so you dont have to wait before you keep scrolling?

**Comment by alvarotrigo** [comment]
You can configure the option `fitToSectionDelay` and reduce the value. 
https://alvarotrigo.com/fullPage/docs/#fittosectiondelay

Try setting it to `100` milliseconds. Less will probably cause issues.
See a demo here:
https://codepen.io/alvarotrigo/pen/VwomNKv
