### ISSUE TITLE
Cannot read property 'scrollHeight' of undefined 

### ISSUE THREAD

**Issue by hyyan** [alvarotrigo/fullPage.js#666]
This error keep showing when I enable the "scrollOverflow: true" option , What should I do ???

**Comment by frankhale** [comment]
@hyyan, were you able to fix this because I have this issue now. The only way I could make the issue go away was to patch jquery.fullPage.js around line 1924 so that it wouldn't try to use access scrollHeight on an undefined element.

**Comment by janein** [comment]
I'm still experiencing this error when calling reBuild more than once.
Any news on this? I would prefer not to manipulate fullpage.js because of update-reasons.

**Comment by alvarotrigo** [comment]
@jackmu95 provide an isolated reproduction of the issue in jsfiddle or codepen.

**Comment by janein** [comment]
I managed to reproduce my error in this codepen:
http://codepen.io/janein/pen/BKbNGy

Click on the "toggle content"-button in the 2nd section more than once and you will see the error  in the console.
Also the content isn't properly vertically-centered after resizing.

**Comment by alvarotrigo** [comment]
You are using `scrollOverflow` but you are not importing slimScrol.js vendor. Just include it as detailed in the docs.

**Comment by janein** [comment]
Thanks for the quick reply!
I did some testing and it seems as it's the fault of my custom scrollhandler.
I copied the one from your script and just removed some slimscrolling functionality because I want "normal" scrolling.
I've implemented it into the fiddle - did I miss something in the scrollhandler?

**Comment by alvarotrigo** [comment]
> did I miss something in the scrollhandler?

I only provide support for the official one I'm afraid.

**Comment by janein** [comment]
But what functionality does fullpage.js require the scrollhandler to have to work properly?
As I said I pretty much just copied the existing one and removed the slimscroller...

Anyway - as the error doesn't impact the result - is there a chance you could just implement a check so scrollHeight isn't accessed from an undefined object? (like @frankhale stated above)

**Comment by alvarotrigo** [comment]
> Anyway - as the error doesn't impact the result - is there a chance you could just implement a check so scrollHeight isn't accessed from an undefined object? (like @frankhale stated above)

Sure. Feel free to create a PR for it.

**Comment by janein** [comment]
I see. When I enlarge my content to more than the viewport-height and do a reBuild, the fp-tableCell gets created.
If I then reduce my content and do another reBuild, the fp-tableCell gets removed.
On the next reBuild no fp-tableCell gets created and I get my error.

I will investigate some more...

**Comment by janein** [comment]
I found the mistake!

In my custom scrollhandler remove-method I did this:
`element.find(SCROLLABLE_SEL).children().first().unwrap().unwrap();`

This removed one layer of nodes too much (probably necessary for slimscroll) so I changed it to:
`element.find(SCROLLABLE_SEL).children().first().unwrap();`

Now it works fine.
Thank you very much for your help - it guided me directly to the bug!
