### ISSUE TITLE
Mousewheel / touch scroll inactive in Fancybox when scrollOverflow true

### ISSUE THREAD

**Issue by jonbarratt** [alvarotrigo/fullPage.js#673]
An interesting one. When scrollOverflow is set to 'true' and the current section or slide requires scrolling, a Fancybox launches with controllable scrollbars, the mousewheel and touch scrolls are disabled. However, if scrollOverflow is set to 'false', the mousewheel and touch scrolls are reactivated.

This causes an issue on touch devices where the scrollbar is only visible on touch scroll (e.g. iPhones). Really need the touch and mousewheel scrolls enabled at all times.

I'd be very grateful for a solution. Please refer to fiddle -

http://jsfiddle.net/xkr4w027/

**Comment by faliqaiman** [comment]
Can someone share the reproduction link for this issue? Thanks.
