### ISSUE TITLE
Disables Bootstrap mobile menu scrolling

### ISSUE THREAD

**Issue by minimaluminium** [alvarotrigo/fullPage.js#678]
Hi.
When I use it with Bootstrap, it disables mobile menu scrolling. Instead of scrolling the menu area, it is scrolling the page in the background. Is it possible to disable fullPage.js scrolling when Bootstrap mobile menu is toggled on?

**Comment by Simpleqode** [comment]
Anything changed in version 2.9.4? I am trying the same fix sodbileg suggested, but it doesn't work on iPhone 7 and 6, though works on Android.

**Comment by ReneHetzel** [comment]
I solved it this way

```
$('.navbar-collapse').on('shown.bs.collapse', function() { 
   $('body').css('overflow', 'hidden');
});
	
$('.navbar-collapse').on('hidden.bs.collapse', function() {
   $('body').css('overflow', 'auto');
});
```
Because `fullpage_api.setAllowScrolling(false);` and `fullpage_api.setAutoScrolling(false);` doesnt work in version fullpage.js v3

**Comment by alvarotrigo** [comment]
> Because fullpage_api.setAllowScrolling(false); and fullpage_api.setAutoScrolling(false); doesnt work in version fullpage.js v3

Of course they work, have you seen [the codepen on the docs](https://codepen.io/alvarotrigo/pen/EjeNdq)?

**Comment by ReneHetzel** [comment]
maybe I'm doing something wrong :( 

I init the fullpage like this: 

```
new fullpage('#page',{
	scrollingSpeed: 900,
	autoScrolling: 	false,
	fitToSection: false,
	scrollBar: 	true,
	bigSectionsDestination: 'top',			
	
	verticalCentered: true,
	normalScrollElements: '#main-nav',
	paddingTop: '80px',
	paddingBottom: '0px',
	fixedElements: '#main-nav, #PageTop',
	lazyLoading: true
});
```

And i handle the click this way: 

```
	$('.navbar-collapse').on('shown.bs.collapse', function() { 
		fullpage_api.setAutoScrolling(true);
		fullpage_api.setAllowScrolling(false);
		//$('body').css('overflow', 'hidden');
	});
	
	$('.navbar-collapse').on('hidden.bs.collapse', function() {
		fullpage_api.setAutoScrolling(false);
		fullpage_api.setAllowScrolling(true);
		//$('body').css('overflow', 'auto');
	});
```	
`fullpage_api.setAutoScrolling(true);` works but `fullpage_api.setAllowScrolling(false);` doesn´t.

I'll check the case again :)
