### ISSUE TITLE
only apply paddingTop and paddingBottom if it has been set by the user

### ISSUE THREAD

**Issue by pg1671** [alvarotrigo/fullPage.js#68]
I have padding set for some of my pages set in CSS and the code then sets the style on the element explicitly which overrides my own settings. 

Can you change the code to only apply padding if the user specifices them?

There is also a problem if people want to specify units other than px .. as the code expects px only.

Setting paddingtop also caused my pages to not fill the screen.

**Comment by emrereyiz** [comment]
türkçe yazsanıza olm
