### ISSUE TITLE
Scrolling to Footer

### ISSUE THREAD

**Issue by markyeoj** [alvarotrigo/fullPage.js#696]
Hello, first of all, let me say thank you for this great plugin. I just have a little problem, our website http://www.swenk.me/ has a footer  which is very small for a section so it has large white space at the bottom
![current-site](https://cloud.githubusercontent.com/assets/3370608/4230550/9fa6650a-3985-11e4-8465-6afe292645b0.jpg) 

Now, what we want is when scrolling to footer  it should be look like this
![what-we-want](https://cloud.githubusercontent.com/assets/3370608/4230575/0a12df40-3986-11e4-9ec3-7179346984e3.jpg)

Is there a way to do that. Thanks :)

**Comment by alvarotrigo** [comment]
It is possible now by adding the class `fp-auto-height` to the section as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections).

**Comment by tkapelis** [comment]
Hello , i added a Google Map in the footer( has class  `fp-auto-height` ) with the google map api with width: 100% and height: 300px; but it shows only the background of the google map if the window is over 800px and if it is under it seems ok. Do you know what is wrong ?

**Comment by alvarotrigo** [comment]
@tkapelis you'd better ask in other place such as stackoverflow.com. It sounds like a very specific issue with CSS and probably not related with fullpage.js.

**Comment by tkapelis** [comment]
Ok i ll do that , Thank you.
