### ISSUE TITLE
Doesn't work with Angular ng-App directive

### ISSUE THREAD

**Issue by sumikumar** [alvarotrigo/fullPage.js#714]
It works perfect however once you add:

html
body ng-app="yourApp"   (if you leave ng-app="" empty it works but you need that to manage angular scripts) 
....
...
/body
/html

It doesn't scroll. Why is that? Can someone help here.

**Comment by alvarotrigo** [comment]
Update
===
A few angular directives are now available as listed in the [resources section of the docs](https://github.com/alvarotrigo/fullPage.js#resources).

- https://github.com/meiblorn/ng2-fullpage
- https://github.com/hellsan631/angular-fullpage.js
- https://github.com/mmautomatizacion/angular-fullpage.js
