### ISSUE TITLE
page skipping

### ISSUE THREAD

**Issue by morganrallen** [alvarotrigo/fullPage.js#72]
I'm encountering a problem where scrolling skips one or two sections. When using anchors I can actually see the hash change to the proper one then change to the following section.

**Comment by benkirkby** [comment]
@alvarotrigo - have you tried e.preventDefault?

**Comment by alvarotrigo** [comment]
@benkirkby yep.

**Comment by benkirkby** [comment]
I should have tried it before I wrote that as I realized immediately that it doesn't work nor does it make much sense that it would. Regardless, this is a fantastic plugin. Thanks for putting it out there for us. I donated a few bucks into your account - as should everyone else who uses this - so have a beer on me tonight!

**Comment by alvarotrigo** [comment]
@benkirkby thanks!! :) I appreciate it!

**Comment by dudu06** [comment]
I was having the same issue. @quackpack was right! I set the css value to false and the page works fine now.

**Comment by carlorizzante** [comment]
Ok, I had the same issue and wasted like an hour trying to figure it out a fix. Doh.

Anyway, if I use as anchors different identifiers than sections' ids I loose the scrolling animation, which basically means the scrolling is back to default, no need for the plugin at all for that kind of immediate scrolling.

Am I missing something?

**Comment by alvarotrigo** [comment]
@dudu06 you were doing something wrong then. 
css3 should be try nowadays. It makes no sense to set it to false to fix a problem that shouldn't exist. 
See the [examples available](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) and make sure you are not missing anything.
