### ISSUE TITLE
Velocity.js integration

### ISSUE THREAD

**Issue by unaszplodrmann** [alvarotrigo/fullPage.js#728]
Hey :)

Thanks for the script. I've been having quite a lot of fun playing with it. Replacing the CSS3 transformations with the Velocity.js equivalent appears to work rather well. I considered using the transitionEnd event to release GPU resources after scrolling to a section/slide, but Velocity.js handles this automagically and is also backwards compatible with IE8/9. Given that it outperforms jQuery animations across the board and does not require CSS3 transform3d detection, it seems like a perfect fit for fullPage.js, apart from the fact that adds another dependency. I've offset this by using a non-standard jQuery build without the animation module etc.

Might it be worth looking at using Velocity.js instead of CSS3 or jQuery for animation?

**Comment by elizabeth268** [comment]
Hi Alvaro,

Really interested in your plugin and very excited to integrate in my projects. Anyhow, I am more familiar with velocity and would like to use your plugin with it integrated in. In the post you've mentioned earlier:

> I believe I might integrate it as an option instead of using jQuery animations.

But I can't seem to find where the integration is in your code. Where might or how might I use the integration you've mentioned?

 Thank you. Amazed and truly appreciated by the work you've done for the community.

**Comment by alvarotrigo** [comment]
@elizabeth268 if you read the whole topic you will notice that I said:
> I'm not sure to what extend does it make sense to integrate it in fullpage.js.

That's after I pointed out that I see not benefit at all in using velocity for fullpage.js or even for pagepiling.js. The performance is slower and therefore it won't be integrated.

If you prefer not to use jQuery, you can start to play with the [pure Javascript Alpha version of fullpage.js](https://github.com/alvarotrigo/fullPage.js/tree/master/pure%20javascript%20(Alpha)).

**Comment by elizabeth268** [comment]
Thanks Alvaro. Looking at it right now and trying to play around with it. Anyhow, seeing that you are not to support it currently... makes me wonder if the pure Javascript Alpha version is slower in web performance? 

Also, as I am inserting your plugin into my project I noticed the css files that comes along. Are they required? But I thought this was a javascript plugin. How does the css come in?

**Comment by alvarotrigo** [comment]
> makes me wonder if the pure Javascript Alpha version is slower in web performance?

The performance of the pure javascript version is even faster than the jQuery one when using the option `css:true`. Not sure about when using `css3:false`, but in any case, you should be using with `css3:true`.
And as you are using CSS3 for the animations, it doesnt matter if you use one or another version, the performance is determined by CSS animations... which will be faster than using Velocity.js in any case. (as per the comments above).

> But I thought this was a javascript plugin. How does the css come in?
Plugins usually need CSS styes as well. Pure Javascript means that its free from the use of external javascirpt libraries as jQuery.

**Comment by elizabeth268** [comment]
css3 is fastest of all alternatives for sure. Anyhow, after reading an interview of yours. You've mentioned you also support Zepto and you've mentioned it is faster than jQuery.  Is it still supported currently? Since I don't seem to find any trace of it? 
Sorry for all the questions but trying to optimize my site for speed and also understand you're plugin a bit more. Thank you very much.

**Comment by alvarotrigo** [comment]
@elizabeth268 I don't know what interview are you talking about because I didn't do any :) You might be talking about other guy.
In any case, why would you use Zepto instead of the pure javascript one?

**Comment by elizabeth268** [comment]
@alvarotrigo Haha. Sorry my apologies. I did get you mixed up with someone else with the similar plugin. http://www.smashingmagazine.com/2014/08/25/how-i-built-the-one-page-scroll-plugin/
The other one is built with the same concept but the possibilities and functionality is just not the same. 
Thanks for the amazing work again.

**Comment by alvarotrigo** [comment]
@elizabeth268 I guessed it. But just to clarify it. Zepto against pure javascript has no advantage in terms of speed as far as I know. It is just a library (for modern browsers only) to make things easier for developers.

**Comment by elizabeth268** [comment]
Well, that's good to know. Now I don't have to dive into another library and learn more syntax. I'm starting to get a bit mixed up with all the libraries, plugins, languages ... etc. 
Anyhow, from what I learned in javascript html and css writing it's best to write the script tag at the bottom of the body tag but for some reasons in all your examples and tutorials ... you always put in the head. Wouldn't that slow down the performance and not the best practice?

**Comment by alvarotrigo** [comment]
@elizabeth268 it was the only way to do it in older versions of fullPage.js.
Now, you can choose where to put it since version 2.

The reason I usually put it in the header is because I consider fullPage.js is necessary for a proper visualization of the site. Take off fullPage.js and any content loaded in the screen will be looking out of place and giving an ugly view of your site until the plugin is called.
Other plugins might be unnecessary or totally independent from the visualization of the data, and that's why it makes sense in those cases.
Check out [this answer](http://stackoverflow.com/questions/143486/unobtrusive-javascript-script-at-the-top-or-the-bottom-of-the-html-code).

**Comment by elizabeth268** [comment]
@alvarotrigo Haha. That's what I thought. Since your plugin would be the main layout for the whole page ... it's best to place it in the head and load as early as possible to reduce the FOUC on a webpage. Thanks for the support so far.
