### ISSUE TITLE
auto slide the horizontal slides

### ISSUE THREAD

**Issue by sachinsangde** [alvarotrigo/fullPage.js#730]
I want to slide the horizontal slides automatically with interval. How to do it?

**Comment by alvarotrigo** [comment]
@anil1067 I don't see why it wouldn't work.

**Comment by anil1067** [comment]
@alvarotrigo Please check - https://codepen.io/anil1067/pen/ExjepOb

**Comment by alvarotrigo** [comment]
That's a general JS question regarding settInterval and clearInterval, you'd better ask about it in places such as stackoverflow.com.

Otherwise you can get a [Business license for fullpage.js](https://alvarotrigo.com/fullPage/pricing/) and get premium support.
