### ISSUE TITLE
mixing non fullpage elements

### ISSUE THREAD

**Issue by wiiiimm** [alvarotrigo/fullPage.js#749]
is it possible to have non full page elements (like a footer) added in a page that is using fullpage?

**Comment by alvarotrigo** [comment]
It is possible now by adding the class `fp-auto-height` to the section as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections).

**Comment by chongyuan** [comment]
After adding the class, the footer section still fullpage. My html is as same as the autoheight.html; 
When I find the autoheight.html in the download files, but I can't find it;
Can you upload the autoheight.html so that we can download it;
Thanks;

**Comment by alvarotrigo** [comment]
Check out this [codepen](http://codepen.io/alvarotrigo/pen/BKjRYm)

**Comment by chongyuan** [comment]
After I copy js and css from autoHeight.html, now it is good;
Thanks very much;
