### ISSUE TITLE
Using fullpage.js with scrollReveal.js or similar

### ISSUE THREAD

**Issue by djmtype** [alvarotrigo/fullPage.js#753]
I realize this issue was closed on the scrollReveal thread. [https://github.com/julianlloyd/scrollReveal.js/issues/45](https://github.com/julianlloyd/scrollReveal.js/issues/45) But curious, if anyone has gotten both to play together. Is there a special callback function needed? I can get [scrollReveal](http://scrollrevealjs.org/) to load on the initial panel. But, navigating to any other sections with [fullPage.js](http://alvarotrigo.com/fullPage/) does not work with scrollReveal or similar animated plugins for that matter.

**Comment by romuloinnocencio** [comment]
I'm with the same problem, can't use Fullpage + ScrollReveal;
I need that the page scrolls like a fullpage but, show the elements like a scrollreveal when scrolls to another section.
How do I proceed?

**Comment by alvarotrigo** [comment]
As pointed out in [fullPage.js FAQs](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions):

> Parallax, **as well as many other plugins which depends on the scrolling of the site**, listens the scrollTop property of javascript. fullPage.js doesn't actually scroll the site but it changes the top or translate3d property of the site. Only when using the fullPage.js option scrollBar:true or autoScrolling:false it will actually scroll the site in a way it is accessible for the scrollTop property.

**Comment by romuloinnocencio** [comment]
Ok, thank I'll try;

**Comment by romuloinnocencio** [comment]
Now it works (with  scrollBar:true), thanks a lot =)
