### ISSUE TITLE
Possible to have the slides crossfade?

### ISSUE THREAD

**Issue by QuintonC** [alvarotrigo/fullPage.js#760]
Hello, 

My question is whether or not you can have the slides stacked, and when you go to the next slide, the current one fades out on top of the new one as it fades in.

The reason that I ask this is because if there are multiple slides, the scrolling gets a bit 'clunky' as you go from one to two over or more. Sometimes it seems that it's rather clunky when you just go over one as well.

If you would like to preview the 'clunkiness', here is a link to the slides page: 
http://kevophoto.com/#FavoriteWork

Thank you,

Quinton

**Comment by alvarotrigo** [comment]
This is now possible with the [Fading Effect Extension](http://alvarotrigo.com/fullPage/extensions/fadingEffect.html).
Assured compatibility with future releases of fullpage.js.
