### ISSUE TITLE
Disable horizontal scrolling. The mouse to sensitive?

### ISSUE THREAD

**Issue by vnguyen9** [alvarotrigo/fullPage.js#769]
I have an overflow div to the right, but when I scroll to right, it jumps to the next section. Is it the mouse is set to be too sensitive.

**Comment by dhavalchaudhary** [comment]
Even though horizontal scrolling is not recommended, can we enable horizontal scrolling as mentioned in this issue?

**Comment by alvarotrigo** [comment]
@dhavalchaudhary what exactly you mean by that?
With mouse wheel? With trackpad? With some kind of horizontal scroll bar?

**Comment by dhavalchaudhary** [comment]
I want to use a horizontal scrollbar. Something like this 
![github](https://cloud.githubusercontent.com/assets/11704610/15475470/e2b2d60e-2127-11e6-93f1-733e72807ecd.PNG)

**Comment by alvarotrigo** [comment]
The plugin doesn't provide such an option I'm afraid.
