### ISSUE TITLE
footer not full height

### ISSUE THREAD

**Issue by sandrodz** [alvarotrigo/fullPage.js#781]
I saw issue #750 but I wonder if there could be a way to achieve this with css / js hack.

Is it possible to add a small footer to the very last slide? It could defined height or percentage of viewport. 

The other plugin scrollSections.js doesn't seem to have problem with it, but it is not even remotely as well written as fullPage.js

So anyone?

**Comment by GoToBoy** [comment]
was anyone solved that problem about footer not a full page

**Comment by bajzarpa** [comment]
im interested in this topic too

**Comment by shanDB** [comment]
I'm also very keen for this feature. My solution involved utilising the "scroll inside section" feature, and placing my footer into the last slide. It works, but does detract from the overall experience since it doesn't adopt the same scrolling mechanism.

**Comment by alvarotrigo** [comment]
Check out [this pull request](https://github.com/alvarotrigo/fullPage.js/pull/1263)

**Comment by shanDB** [comment]
Thanks alvarotrigo. That pull request was EXACTLY what I was looking for. 
I spent so many hours looking for a solution, testing, writing, reverse engineering a solution - None of which worked to my liking - Until this one.. 
<Big sigh of relief>

**Comment by alvarotrigo** [comment]
@shanDB it very probably be added in future versions of fullPage.js.

**Comment by alvarotrigo** [comment]
This is now possible with the class `fp-auto-height` as detailed [in the documentation](https://github.com/alvarotrigo/fullPage.js#creating-smaller-sections).

[Example online](http://alvarotrigo.com/fullPage/examples/autoHeight.html)
