### ISSUE TITLE
Intercept Scroll event even when movement is disabled.

### ISSUE THREAD

**Issue by lucadegasperi** [alvarotrigo/fullPage.js#787]
Hello Alvaro,

What I want to do is have the section remain stopped while the user scrolls and have something else appear on scroll, then resume the plugin normal behavior after all the element in the section have appeared on scroll. Is it achievable? Is there at least a way to hook into the plugin before the section changes and eventually prevent the section from changing?

**Comment by alvarotrigo** [comment]
Solved time ago.
See ["Canceling scroll before it takes place"](https://github.com/alvarotrigo/fullPage.js#cancelling-the-scroll-before-it-takes-place)
