### ISSUE TITLE
Allow vertical positioning only one certain slides

### ISSUE THREAD

**Issue by ghost** [alvarotrigo/fullPage.js#788]
Currently the only way to vertically align content within sections is applying verticalCentered:true when initialising the plugin. This vertically aligns every section. Is there a way to only apply vertical positioning within certain sections only and not all of them?

**Comment by ds1239** [comment]
Just tried this on an image and it is staying centered.

**Comment by otelo29200** [comment]
Hey,

CSS apply top to down, so you need to apply the rule given above after jquery.fullpage.css

Hope it could help
