### ISSUE TITLE
Hide Sections In Mobile Media Query

### ISSUE THREAD

**Issue by toastedpixel** [alvarotrigo/fullPage.js#80]
Hi!

Im working on an responsive website with this plugin, which is great! Congrats Alvaro, once again.

I was wondering if its possible to hide Specific SECTIONS when you visit the site on a phone. I tryed through CSS with Display:None / Visibility: Hidden and so on, but nothing seems to work.

Anybody faces the same problem?

Thank you!

**Comment by jk171505** [comment]
I have the same issue - I want to hide some section in specific media query. How can I deal with the scroll problem or how can I tell the plugin to skip this section in specific media query?
