### ISSUE TITLE
Limitation to using AfterSlideLoad callback to highlight nav links?

### ISSUE THREAD

**Issue by crizpeecritter** [alvarotrigo/fullPage.js#800]
Disclaimer first: I don't know jquery but I'm logical and clever, so I was able to use some examples I found here and elsewhere to use AfterSlideLoad to highlight some fixed nav links for slides. It works beautifully but there is one thing wrong. 

The site I'm designing has 4 sections, and two of them (second and third) contain slides. Let's say I move vertically down from section 0 to section 1, and then move horizontally between three slides in section 1. Nav links light up fine. Then I move down to section 2. Then I move back up to the slide in section 1 that I just left. The nav link does not light up. But if I then move horizontally again, the callbacks fire and the links light up.

Is this a limitation in the code I've created? Or a limitation in fullPage? Thanks in advance for any info...

**Comment by alvarotrigo** [comment]
Related with https://github.com/alvarotrigo/fullPage.js/issues/1124. I'll close this issue.
