### ISSUE TITLE
Our users doesn't use the vertical navigation dots. What do you think about this idea?

### ISSUE THREAD

**Issue by metaxos** [alvarotrigo/fullPage.js#806]
Hi Alvaro

First of all, again, we love your work :)

To all who use this nice scripts:

In our first draw we did not had the vertical dots. The analyse of the visitors way on our site showed us, that many users are still not "used" to scroll down a page. So some contents where 'newer' visited. To try to help our visitors we then added the vertical navigation dots, also with the labels.

A new assessment  brought up, that many of the visitors do not use the vertical navigation dots. This leads to the conclusion that we still have to bring up some improvement. We would like to let the dots at this size. Somebody in our team had the idea to show a "big" arrow at first and last position to help the user to "realize" the page is going down/up. Of course the arrows should only be displayed when there are more sections. Nice would be to see the label of the active section.

![mock](https://cloud.githubusercontent.com/assets/5360113/4844000/ffa4cd24-6037-11e4-935e-57f3101c1392.png)

We would appreciate any feedback of others... do you have similar feedbacks?
If yes how would you suggest to implement this?

Regards
Jacques

**Comment by alvarotrigo** [comment]
@metaxos the option `scrollBar` was introduced to solve this UX problem.
