### ISSUE TITLE
How to use my slider with class 'slide'? It has conflict with fullPage.js.

### ISSUE THREAD

**Issue by eshengsky** [alvarotrigo/fullPage.js#822]
Hi! I'm from China, now I'm using the fullPage.js, I think it's very wonderfull and helpful!
Now I meet a problem, My English is not good, I will try to describe it as clearly as possible.
As you know, fullPage.js let `<div class="slide"></div>`into `<div class="section"></div>` to make a horizontal slider. While I used 'carousel' in Bootstrap in my project, it has the same class 'slide'.
The codes like:

```
<div id="fullpage">
    <div class="section">
        <!-- carousel -->
        <header id="myCarousel" class="carousel slide"/>
             <!--Other codes-->
         </head>
     </div>
</div>
```

Because there's a 'slide' class within 'section', it will add additional Left and right arrows in the section, it's a mistake. According to the doc, I write this:

```
$(function () {
        $('#fullpage').fullpage({
            slideSelector: '.slideNone'  //it's inexistence
        });
```

I thought fullPage will just find '.slideNone' element, ignore my '.slide' slider, but failed.
Could someone help me?

BTW, if I don't use carousel in Bootstrap, I find the slider in fullPage.js is also good, but I don't know how to let the vertical sections not auto scroll, and let the sliders in particular section auto scroll.
Thanks a lot!

**Comment by RosApr** [comment]
good job!

**Comment by 72OTA** [comment]
@alvarotrigo ![image](https://user-images.githubusercontent.com/24867922/44242842-39b90200-a1a2-11e8-8da6-7415916ec473.png)

**Comment by alvarotrigo** [comment]
@72OTA you are checking a link from 2014. Jsfiddle removed many of their old links. Thus the error :)
