### ISSUE TITLE
Move/Slide to with no animation

### ISSUE THREAD

**Issue by sidonaldson** [alvarotrigo/fullPage.js#831]
A little feature request here!

Would it be possible to add a parameter to the these functions:
moveSectionUp()
moveSectionDown()
moveTo(section, slide)
moveSlideRight()
moveSlideLeft()

So that the animation happens instantly but still makes the relevant callbacks? Kinda like setting the speed to 0 and then back to the predefined scroll speed.

**Comment by alvarotrigo** [comment]
A new method for it `$.fn.fullpage.silentMoveTo()` was added in the latest release 2.6.5.

**Comment by Irina23** [comment]
I used code

afterRender: function () {
            setInterval(function () {
                $.fn.fullpage.moveSlideRight();
            }, 6000);
},

but if click on the fp-slidesNav slide open next and quickly scroll to next
example active 3 slide, click to 1, open 1 and then quickly to 2 
Can this be fixed?
