### ISSUE TITLE
normalScrollElements doesn't work on specific overlay

### ISSUE THREAD

**Issue by sandrodz** [alvarotrigo/fullPage.js#838]
Hey,

I was successful with disabling plugin behaviour on number of overlay screens:
normalScrollElements: '#booking-overlay, #nav, #header, #blank-overlay'

Except the last one, #blank-overlay. This one appears when you click hamburger menu icon in the right side: https://sandbox.idev.ge/roomshotel/mobile_html5_v1/

Overlay is added, but I still can scroll up and down. While on other elements like booking-verlay (which is triggered by clicking icon next to hamburger icon).

Why is this happening? :S

**Comment by dexterns88** [comment]
I have problem with normalScrollElements when set to auto scroll doesn't work on one page. On Desktop device is everything OK but on mobile where I have scroll on drug he ignore this option. 
Need this option because have Google map in one page and can't scroll the map.

**Comment by alvarotrigo** [comment]
@dexterns88 it supports mobile phones as well. Please check the `normalScrollElementTouchThreshold` option in the docs. That might be your problem.
