### ISSUE TITLE
Is it possible to have normal scroll pages with this plugin active?

### ISSUE THREAD

**Issue by sandrodz** [alvarotrigo/fullPage.js#840]
Hi again,

Sorry for the deluge of questions :)

Anyhow, I've this plugin included in the html, it seems to interfere with scroll on normal pages, I'm trying to pinpoint the source of problem. fullpage.js is initiated on #fullpage. Normal scroll page doesn't have this selector, but still scroll doesn't seem to work at all (normal scroll I mean).

Any thoughts?

https://sandbox.idev.ge/roomshotel/mobile_html5_v1/single.html

Thanks!

**Comment by alvarotrigo** [comment]
This is finally possible in v4!! 🥳 
It only took 7 years!! :)
