### ISSUE TITLE
Full screen video hides content

### ISSUE THREAD

**Issue by pr1moz** [alvarotrigo/fullPage.js#853]
Hey alvarotrigo,
thanks for the awesome plugin :) I'm having an issue with full screen video, because it hides overlaying content while scrolling. I don't have my page available for showing, because it's not public yet, but the same issue can be seen on the example page here - http://alvarotrigo.com/fullPage/examples/videoBackground.html. When you scroll down and then back up again, the title 'fullPage.js fullscreen videos' isn't visible until the animation has finished. I've tried setting z-index, but it doesn't help.

I've also checked out your other pagePiling.js plugin, which doesn't seem to have this issue - http://alvarotrigo.com/pagePiling/examples/videoBackground.html. Any ideas how this can be fixed for the fullPage.js plugin?

PS: On the project I'm currently working on, I also implemented an option for responsiveHeight, because there are some narrow (short?) window sizes out there that are not big enough to fit the content, but are still wider than the set responsive width. Just a suggestion for an additional feature :)

Thanks

**Comment by awlyng** [comment]
Love the .js @alvarotrigo 

I know this has nothing to do with the js but in Firefox Mac & PC, the video doesn't fill the full screen. There are black bars to the left and right of the screen. Would you happen to know how to fix this?

**Comment by alvarotrigo** [comment]
@awlyng as you say, that has nothing to do with fullPage.js, so I would recommend you to ask in other places such as http://stackoverflow.com/ where they will help you much better.
