### ISSUE TITLE
Fullpage smooth scrolling

### ISSUE THREAD

**Issue by michalcik** [alvarotrigo/fullPage.js#86]
Hi Alvaro First of all I just want to thankk you for the gret plugin which also works awesome
I just have a questions:
1. Is it possible to setup full page smooth scrolling? Scrolling without stops on slides ? And can I control the speed of it? If it is possible where I can setup this in the code?
   It is like at this page: 
   http://www.apple.com/ipad-mini/features/
2. It is possible to extended slide area for more then a screen? Needed if I have more texts
3. Is it also oossible to use parallax effect like at Apple iPad mini feature on design page? And how it is possible?

Thanks very much for the answer and wor your great work of course 

Peter

**Comment by leonardeveloper** [comment]
Smooth scrolling doesn't work when I set `scrollBar:true`. 

`var myFullpage = new fullpage('#fullpage', {
        licenseKey: 'XXXXXXXXXXXXXX',

        // anchors: ['hero', 'welcome', 'tours', 'heritage', 'landmarks', 'testimonial', 'moretestimonials', 'footer'],
        anchors: ['hero', 'welcome', 'tours', 'heritage', 'landmarks', 'testimonial', 'footer'],

        lazyLoad: true,

        navigation: true,

        navigationPosition: 'right',

        scrollBar: true,

        animateAnchor: true,

        touchSensitivity: 5,

        normalScrollElementTouchThreshold: 5,

        easing: 'easeInOutCubic',

        easingcss3: 'ease',

        responsiveWidth: 769,
        scrollOverflow: true,

        afterLoad: function() {
            new WOW().init();
        }


    });`

I am using wow animation and I already set the body to `overflow:hidden` when `scrollBar:true`

**Comment by alvarotrigo** [comment]
> already set the body to `overflow:hidden` when `scrollBar:true`

Why would you do that?
The whole point of using scrollbar is removing `overflow:hidden`.

**Comment by alvarotrigo** [comment]
@leonardeveloper but yeah, I don't think smooth scroll will work anyways. fullpage.js is making it's own scroll animation and it makes no sense to delegate it to any third party library. As there's no way they can make it smoother  :)

**Comment by leonardeveloper** [comment]
> > already set the body to `overflow:hidden` when `scrollBar:true`
> 
> Why would you do that?
> The whole point of using scrollbar is removing `overflow:hidden`.

I wanted to have the smooth scroll when `scrollBar:false` but if I set this the WOW animation won't work. 
Now, how can I apply the same smooth scrolling when I use `scrollBar:true` because it's a little bit jittery if this is the case.

**Comment by alvarotrigo** [comment]
Unfortunately I don't think there's no way you can apply smooth scroll to an scroll animation that is already "smooth" and triggered by JS.
