### ISSUE TITLE
Disable slides on mobile devices

### ISSUE THREAD

**Issue by lukpon** [alvarotrigo/fullPage.js#884]
Hi there,
which is the best way to disable slide elements (`<div class="slide">`) on mobile devices? I want to list these elements one below the other with `autoScrolling:false` option, the height doesn't need to be fitted. It must be ensured that the sliders are still working on desktops.

**Comment by AmanSahota** [comment]
@alvarotrigo I just wanted to confirm is this still the up to date method for this?
I am thinking of disabling slides on mobile.

**Comment by alvarotrigo** [comment]
@AmanSahota no. Nowadays you can make use of the [Responsive Slides extension](https://alvarotrigo.com/fullPage/extensions/responsive-slides.html) as detailed in the [the fullpage.js documentation](https://github.com/alvarotrigo/fullPage.js) on the `responsiveSlides` option.
