### ISSUE TITLE
resize doesn't work always

### ISSUE THREAD

**Issue by curvedb** [alvarotrigo/fullPage.js#885]
I think resize function doesn't work always on desktop and mobile. (tested with imac, iphone, ipad and android)

My settings are :

```
responsive: true,
resize: true,
```

my backgrounds :
    background-position: 50%;
    background-repeat: no-repeat;
    background-size: cover;
    height: 100%;

**Comment by mjoellnier** [comment]
I hate to 'rewarm' this old thread but I have a similar problem with the actual version 2.9.5: When I first open up the page the sections are moved to the bottom but as soon as I resize the window just a little bit the sections are aligned to the vertical center and are all right. As far as I can see I would guess that the class `fp-tableCell` is doing something wrong in the determination of the height (see screenshots) 

On initial load: 
<img width="1208" alt="bildschirmfoto 2017-11-23 um 14 15 00" src="https://user-images.githubusercontent.com/19910271/33174646-379edbfe-d059-11e7-8524-e9f067391770.png">

After resizing the window: 
<img width="1210" alt="bildschirmfoto 2017-11-23 um 14 15 21" src="https://user-images.githubusercontent.com/19910271/33174645-3782bf8c-d059-11e7-8402-371cd477692f.png">

**Comment by alvarotrigo** [comment]
@mjoellnier if you believe this is a bug in fullpage.js please open a new issue with **an isolated reproduction** with the minimum amount of HTML and CSS code required to reproduce the issue.
