### ISSUE TITLE
Horizontal scroll with mouse wheel

### ISSUE THREAD

**Issue by et** [alvarotrigo/fullPage.js#9]
Scrolling horizontally with a touchpad will trigger vertical scrolls.

This is because of `function MouseWheelHandler` only compensating for vertical transitions. This can be achieved by differentiating between `e.wheelDeltaX` and `e.wheelDeltaY`.

**Comment by alvarotrigo** [comment]
This is now possible using the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).
