### ISSUE TITLE
Re-enabling auto scroll in chrome breaks site when scrolling with trackpad

### ISSUE THREAD

**Issue by resting** [alvarotrigo/fullPage.js#900]
Need some help here.

Example of the bug [here](http://codepen.io/resting/pen/myVbNd).
Have to view it in **debug** view to see the bug.

Here's what the script does. Upon reaching the last section, I disable autoscroll and attach a listener to window's scroll event. This is to enable users to view the footer, and to scroll back up a section when user scrolls above 20px of the last section.

Here's the problem. When I scroll right to the bottom in Chrome with the touch pad on my MBA, scrolling back up to section 3 caused chrome to display a grey screen, and the site just stop responding.

This only happens when I try to re-enable the auto scroll. Only seems to happen in Chrome (39.0.2171.71) too.

**Comment by sbehrends** [comment]
@resting The example work quite good... but still have some scrolling issues when going back to autoScrolling. The site "jumps" getting back. I guess is a elastic scroll thing. I have tried overriding the scrolling effect but sadly couldn't get it to work.

**Comment by alvarotrigo** [comment]
@resting which version of Chrome are you using ?

**Comment by sbehrends** [comment]
With Chrome 40.X works more or less good but "jumps". IE does not work correctly :| Firefox looks just like Chrome.

**Comment by alvarotrigo** [comment]
The latest stable version of Chrome is 39.0.2171.95. Any error in a non stable version won't be solved here.

> IE does not work correctly

Version? The demo pages work correctly.


> Firefox looks just like Chrome.

Version? The demo pages work correctly.

**Comment by resting** [comment]
@alvarotrigo I am always using the latest stable build. A side issue, we found that doing a "huge" scroll with the trackpad causes the page to scroll twice. But I'll probably only look into tomorrow or so. Maybe some sensitivity settings?

**Comment by alvarotrigo** [comment]
> A side issue, we found that doing a "huge" scroll with the trackpad causes the page to scroll twice.

That's another issue. I already knew about it as it has been mentioned some times before. It is due to the fact that the scrolling event is being registered for some milliseconds or even 1 second after the user stops scrolling. It depends on the acceleration of it. It is known as the "kinetic scrolling effect". 
Not a simple solution for it...

**Comment by DomenicRoti** [comment]
I'm experience the same problem, specially after I removed the anchors, and can duplicate it on this demo: http://www.alvarotrigo.com/fullPage/examples/noAnchor.html, were you ever able to find a solution?
