### ISSUE TITLE
Moving the mouse after scrolling in IE 11 (Win 8.1) causes page to scroll.

### ISSUE THREAD

**Issue by resting** [alvarotrigo/fullPage.js#904]
This problem is present on the demo site as well, in IE 11 with Win 8.1.
Try scrolling down a few pages.
Now moving the mouse up/down also causes the page to scroll with it.
Win 7 doesn't have this problem.

**Comment by berlinercode** [comment]
is this Driver prinstalled? I have excactly the same problem with my Yoga13

**Comment by alvarotrigo** [comment]
@berlinercode it's not an easy issue,check this [open topic treating it](https://github.com/alvarotrigo/fullPage.js/issues/937).
