### ISSUE TITLE
Scroll position

### ISSUE THREAD

**Issue by boazhoch** [alvarotrigo/fullPage.js#915]
Hey, is there any possibility to change the `scrollTop()` position?

i mean 
currently i have a fixed header which is 130 height. when scrolling down to a section the header is on top of the section `top` property. the header is overlay the top section ( taking 130px )
////////////////////////////////////////////////////////////////////////
/                           display                               /
////////////////////////////////////////////////////////////////////////
 /                  header (covers the top section)   /
////////////////////////////////////////////////////////////////////////
 /                                                                      /
 /                            section                               /
 /                                                                      /
 /                                                                      /
////////////////////////////////////////////////////////////////////////

**Comment by muhamadamin1992** [comment]
hello ,can you help me

**Comment by muhamadamin1992** [comment]
for fullpage example
