### ISSUE TITLE
afterRender get only global window object

### ISSUE THREAD

**Issue by mad99** [alvarotrigo/fullPage.js#918]
Hi,
when fullPage have to create a SlimScrollHandler, the function-call() at the end will only pass the window-object.
Better, or more useful it would pass the variable »container« instead of »this«.
So maybe you could change the line 531 (https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L531)

FROM : $.isFunction( options.afterRender ) && options.afterRender.call( this );
TO: $.isFunction( options.afterRender ) && options.afterRender.call( container );

or to an other similar useful code.
Kind regards
Martin

**Comment by alvarotrigo** [comment]
Right. Same for other callbacks.
Thanks for pointing it out. I'll add the changes in the next version.

**Comment by alvarotrigo** [comment]
Solved in 2.5.6
