### ISSUE TITLE
Menu anchors highlight next section too early when using `height: auto !important`

### ISSUE THREAD

**Issue by noahstokes** [alvarotrigo/fullPage.js#919]
Hello. Excellent plugin, thank you for all your work on it. I've run into an issue where I am seeing the menu anchors highlight the next section too early. 

Here is my page: http://noahstokes.com/clients/bell/

*Steps to reproduce:*
If you scroll down to the 2014 By the Numbers you'll see the anchors jump to Excellence while you're about 2/3 of the way through the 2014 By the Numbers section. 

I've checked to make sure that none of the ID's match the anchors as the docs state, not sure what else I'm missing here.

Any advice is much appreciated!

**Comment by alvarotrigo** [comment]
Just to point it out, this only happens when using:
```css
.section{
    height: auto !important;
}
```

**Comment by TWSgit** [comment]
Is there any workaround, hack or fix for this issue already? :/ (I've run into the same effect and I have to fix it as soon as possible, but I have to use auto height sections either:/)

**Comment by alvarotrigo** [comment]
> Is there any workaround, hack or fix for this issue already?

Nop, that's why it stills open. If you really need it to be fixed you can [ask for an urgent request](http://alvarotrigo.com/#contact-page).

**Comment by TWSgit** [comment]
well I try to debug it myself at first (and contribute the fix if I can) but if I don't find a solution then I'll write.. thank you:) (I just thought perhaps there is a workaround already which isn't released yet or hacky (but works) which would be enough for me right now, but then I continue my debugging session;))

**Comment by alvarotrigo** [comment]
Fixed in 2.7.7.
