### ISSUE TITLE
Problem: Scrolling on iOS?

### ISSUE THREAD

**Issue by BeBo007** [alvarotrigo/fullPage.js#922]
HI Alvaro,

thanx for your great work! Your script is really amazing and i reeally love to work with it. There is just one litte fun killer: on iOS-Devices the script is not offering scroll-bars if the content ist to large to show in the section - and now comes the crazy part: the problem only occurs, when i'm working with videos in the sections.
The user has to change its devive from landscape-mode to portrait-mode and back (or from portrait to landscape and back) to get scroll-bars, which isnt't the spirirt of a good usability. 

An example with videos: http://bit.ly/1AAxSUI
an example without videos: http://bit.ly/13J3VIb

The only css-code for videos i'm using is:

```
    .section video {
        width: 100%;
        height: auto;
        background-color: #fff;
    }
```

i set the script in the header "verticalCentered: false" and "resize : false" to avoid the the forefox-bug with resizing and used media queries instead (issue #284).

First i thought this could be the ios scale bug, but no bugfix (like this one: http://bit.ly/1AAxSUI)  is working at all. 
Can you help me solving this problem?

Thanx a lot and best whishes
BeBo

**Comment by mrj0909** [comment]
I have used the full Js which is awesome, the only issue is coming scroll on iphones otherwise it is working 100% perfect on all devices. To fix it I have used onload function still the issue is there. Any suggestions? Please see my code here http://beta.autonomyx.com/product-tour

**Comment by alvarotrigo** [comment]
@mrj0909 if you believe there's a bug please open a new issue with an isolated reproduccion with the less minimum HTML code and no external CSS or JS to fullpage.js. 
Then specify device and version of OS and browser.

**Comment by mrj0909** [comment]
It has fixed I was using old js library which was "javascript.fullPage.js" now I am using "jquery.fullPage.min.js"

**Comment by rosell921** [comment]
I'm using jquery.fullpage.extensions.min.js and I still have the same issue of scrolling on iPhone devices

**Comment by alvarotrigo** [comment]
@rosell921 please provide an isolated reproduction of it. With no external CSS or JS files to fullpage.js and the minimum HTML code. Use empty sections if possible.
