### ISSUE TITLE
Quirkiness example

### ISSUE THREAD

**Issue by quintendewilde** [alvarotrigo/fullPage.js#936]
Hey I have my test site online to show odd things when scrolling.

If you scroll one section down, go left to then scroll back the site shows turquoise bands.

Does anybody know where they come from, I'm unable to find it what's causing it.

http://theoctopushideaway.nz

**Comment by Lazyfattree** [comment]
I thought it was a fullpage.js problem because the error showed the color of the original setup of the fullpage.js

**Comment by alvarotrigo** [comment]
Solve your other problems first.
