### ISSUE TITLE
Lastest pages (slides) on the section doesn't show up

### ISSUE THREAD

**Issue by Xsmael** [alvarotrigo/fullPage.js#938]
Hi!

When I try to show a lot of slides (about 15) 
- On computer, the last slide doesn't appear but when i check the code source in the browser nothing is wrong, so I have to add one more slide(empty) so that the last one will appear, but i'm not confortable doing this.

- On mobile it's even worse, more than 3 slides doesn't show.

**Comment by alvarotrigo** [comment]
- Make sure to use the latest version of fullPage.js.
- Review your HTML markup and make sure you don't have any HTML mistake and that you are following the needed HTML structure detailed in the documentation of fullPage.js.

Can't help you more without any code or link to your site reproducing the problem.
