### ISSUE TITLE
Two enhancements - down arrow and scroll using spacebar

### ISSUE THREAD

**Issue by g123456789l** [alvarotrigo/fullPage.js#939]
Great plugin.  Very simple to use and easy to customize.  I would like to extend this to add two other functionalities - a simple down arrow to click on and a way to let the user scroll down using the spacebar,

In my intro page, I want to make sure users understand there is more to see than the first slide.  I know some users prefer scrolling with the spacebar (not common, but I know they exist) and in my current demo before I found your plugin, I was using a down arrow icon to show there is more to the page.

For the down arrow:
I know you have the option for a vertical navbar with circles and it shows nice detail since it will lists all pages and I like the tooltips, but I was wondering if it would be useful to simply have a down arrow that is located in the bottom center.

I will use my current code which includes a div in the html on each slide and styling it with css and using the link to the next section.  I could add another function similar to addVerticalNavigation with a name like addArrowDown and append the html to the end of each section and still style the same with the css so that I do not have to manually add the arrow html to each section.

For the spacebar:
I think this can be added by extending the function keydown function and changing these lines (case 32 is for a spacebar):

```
switch (e.which) { ...
     //down
     case 40:
     case 34:
```

to
```
switch (e.which) { ...
     //down
     case 40:
     case 34:
     case 32:
```

Maybe you wanted to prevent this for some reason?

**Comment by alvarotrigo** [comment]
> For the down arrow:

Very easy to do it with CSS and the functions provided by the plugin. See [this topic](https://github.com/alvarotrigo/fullPage.js/pull/814) where the same issue was treated.

> For the spacebar:

Again, very easy to accomplish using basic javascript and the functions provided by the plugin. Plus it wouldn't be a nice option for websites using text inputs.

**Comment by g123456789l** [comment]
Thanks for posting that other topic.  I looked though some of them but missed that one and thats very much the idea that I will add.  My intro has no text input and agree you do not want to add more complexity to your plugin.  I'll make my own fork and follow you.  Great work!
