### ISSUE TITLE
How create previous and next buttons on fullPage-nav?

### ISSUE THREAD

**Issue by nikos19pap** [alvarotrigo/fullPage.js#94]

**Comment by zshahab91** [comment]
@alvarotrigo 
hi 
how to next page in fullpage js using angular 5?

**Comment by alvarotrigo** [comment]
Just use [$.fn.fullpage.moveSectionDown](https://github.com/alvarotrigo/fullPage.js#movesectiondown).

Also check the angular components available:
https://github.com/meiblorn/ngx-fullpage
https://github.com/hellsan631/angular-fullpage.js

**Comment by zshahab91** [comment]
@alvarotrigo 
yes I Use ngx-fullpag and how do it?

**Comment by zshahab91** [comment]
@alvarotrigo 
I found it
thanks alot
