### ISSUE TITLE
IE and Fixed Elements

### ISSUE THREAD

**Issue by errazib** [alvarotrigo/fullPage.js#940]
This only really shows in IE11, but when you have fixed elements within a section, it scrolls over to the next. For example, if you look at this page http://loiseau-noir.com/seb/music.html you can see how the content from the top page goes down to the bottom page.

**Comment by alvarotrigo** [comment]
Fixedelements will just move those elements just before the closing '</body>'. 
It was introduced when fullPage.js didn't require a wrapper to be initialised. 

Now fixedElements is no longer needed. Just place the fixed elements outside the plugin's wrapper. 

> when you have fixed elements within a section,

Fixed elements are never just within a section. They will be fixed for all sections. You might be talking about using absolute positioned elements. 

> if you look at this page http://loiseau-noir.com/seb/music.html you can see how the content from the top page goes down to the bottom page.

That's a matter of your own design. You don't need fixedElements. Try using:
```css
.section{
    overflow:hidden;
}
```
