### ISSUE TITLE
How to reBuild FullPage after $.fn.fullpage.destroy(); on resize

### ISSUE THREAD

**Issue by SickyBuffalo** [alvarotrigo/fullPage.js#944]
i got something like this : 
$('#fullpage').fullpage({
        afterResize: function(){
            if($(window).height() < 850){
                   $.fn.fullpage.destroy();
            }
            else{
                  $.fn.fullpage.reBuild();
            }
        }
    });
and when resize under 850px works fine , but after that if you resize agai more than 85opx  FullPage doesn't fire again ? Can you help me, where i go wrong ! Thanks !

**Comment by SickyBuffalo** [comment]
I want this ,bacause i have animations  and responsive: 850, and on mobile view i want to change animations delayand with  $.fn.fullpage.destroy(); i fix them , but on desktop view i want Full Page again

**Comment by alvarotrigo** [comment]
Rebuild is not the opposite to destroy. 
You would need to initialize fullPage.js again if you use `destry('all')`.

You might not want to use `destroy` anyway.... it seems that you want to use `setAutoScrolling(false)`.

**Comment by codev0** [comment]
Hi.
I have issue. After reinit fullpage mousewheel sliding go to last slide.
http://jsfiddle.net/s5huzx9p/
Try resize result frame.

**Comment by aaroncrawford** [comment]
For anyone in the future that runs into this, I was able to solve the back button functioning by changing scrollPageAndSlide() to the following : 
`function scrollPageAndSlide(destiny, slide){
            var section = getSectionByAnchor(destiny);


            //do nothing if there's no section with the given anchor name
            if(!section.length) return;
            
            //default slide
            if (typeof slide === 'undefined') {
                slide = 0;
            }

            //we need to scroll to the section and then to the slide
            if (destiny !== lastScrolledDestiny && !section.hasClass(ACTIVE)){
                scrollPage(section, function(){
                    scrollSlider(section, slide);
                });
            }
            //if we were already in the section
            else{
                if(slide == 'undefined') {
                    scrollSlider(section, 0);
                }
                else {
                    scrollSlider(section, slide);
                }
                
            }
        }`
I haven't tested this in every scenario, but it works for my purposes.  If it doesn't work for you you may need to continue modifying this method.  But it worked for me.
