### ISSUE TITLE
horizontal slider not working on rtl direction elements

### ISSUE THREAD

**Issue by omid-khd** [alvarotrigo/fullPage.js#945]
hi. when i was trying to use slider (horizontal slider, second section in demo) on a elements that had a rtl text direction i notice that slider functionality don't work.
i.e this isn't working:

```html
<html dir="rtl" xmlns="http://www.w3.org/1999/xhtml">
```
but this is working:
```html
<html  xmlns="http://www.w3.org/1999/xhtml">
```

**Comment by alvarotrigo** [comment]
Tried it with `<html dir="rtl" xmlns="http://www.w3.org/1999/xhtml">` and it works fine in the examples I provide. 
Try to reproduce the error somehow, because I didn't manage to.
