### ISSUE TITLE
Auto horizontal scroll

### ISSUE THREAD

**Issue by jacklinwood** [alvarotrigo/fullPage.js#947]
Great plugin!

My page has 3 sections, the first one being an image slideshow with horizontal scroll added.
Is there a way of having it scroll through the slideshow automatically in that section?

**Comment by alvarotrigo** [comment]
Please use [the search](https://github.com/alvarotrigo/fullPage.js/issues?q=automatic) where the topic was already treated multiple times.

Also [check this example](http://jsfiddle.net/6SQhb/7/).
