### ISSUE TITLE
Changing the window location hash should be optional when auto scrolling is turned off

### ISSUE THREAD

**Issue by d13** [alvarotrigo/fullPage.js#948]
When auto-scroll is off in fullpage, the browser history can get very overloaded depending on how much scrolling is done up and down the page, making the back button a mess for users.

**Comment by alvarotrigo** [comment]
You are totally right. Thanks for naming it.
More than optional, I guess we could keep using them but preventing them to be added in the history.

**Comment by alvarotrigo** [comment]
A new option has been added for it. `recordHistory` as detailed [in the docs](https://github.com/alvarotrigo/fullPage.js)

> recordHistory: (default true) Defines whether to push the state of the site to the browser's history. When set to true each section/slide of the site will act as a new page and the back and forward buttons of the browser will scroll the sections/slides to reach the previous or next state of the site. When set to false, the URL will keep changing but will have no effect ont he browser's history. This option is automatically turned off when using autoScrolling:false.

A new method has also been provided [`$.fn.fullpage.setRecordHistory()`](https://github.com/alvarotrigo/fullPage.js#setrecordhistoryboolean).
