### ISSUE TITLE
Fast clicking on the side nav breaks scrolling

### ISSUE THREAD

**Issue by dflomin** [alvarotrigo/fullPage.js#949]
Hi, noticed that it looks like rapid clicking on the side nav for vertical scrolling seems to break the scrolling event - nothing happens until you've clicked on a nav option below your current position. While it's perhaps rare for any real user to rapid fire click on the navigation, it's still somewhat of a problem.

Other than that, love this plugin. Awesome work!

**Comment by alvarotrigo** [comment]
Are you using the latest version? When you say "nav", are you talking about the menu or the bullets?

**Comment by dflomin** [comment]
Am using the latest yup. The bullets, sorry for ambiguity (navigation, navigationPosition, navigationTooltips are being utilized).

**Comment by alvarotrigo** [comment]
> vertical scrolling seems to break the scrolling event

What do you exactly with that?


> nothing happens until you've clicked on a nav option below your current position.

I can not reproduce the problem [in the demo page](http://alvarotrigo.com/fullPage/examples/navigationV.html). The bug I can find is related with scrolling more than one section when scrolling once by using an Apple trackpad.

If you can provide a link to a reproduction of the problem that'd be nice.

**Comment by dflomin** [comment]
Here's a link:

http://www.flashmade.com/flashmadenoscroll/index.php

When clicking on the right nav randomly in rapid succession, the page will be brought to the appropriate section and then prevent you from scrolling until you've clicked on the nav again to go to another section.

Not terribly worried about it as it does seem outside of normal user behavior but the issue does pop up infrequently during regular testing. Would love to hear if you can't seem to reproduce this problem!

**Comment by alvarotrigo** [comment]
Your fullPage.js code has been modified. I'm sorry but I don't provide support to any kind of modifications. 
Try with the original fullPage.js code, if you keep having the same problem come back again.
