### ISSUE TITLE
Is this possible to get this working?

### ISSUE THREAD

**Issue by Electrofenster** [alvarotrigo/fullPage.js#951]
My html File looks like this:

```html
<div id="fullpage">
	<div id="staticContent" class="active">
		<div class="content">
		</div>
	</div>

	<div class="section" id="section0">
	A
	</div>

	<div class="section" id="section1">
	B
	</div>
</div>
```

the div#staticContent (400x250) is always in the middle of the screen. The content from div#staticContent .content changes when the next section is triggered. I'd load the content dynamically with jQuery to prevent the slidingeffect. But I don't know how to make the div#staticContent always visible. :-1: 

When the user scrolls the page on section one, I want to display with jQuery the A in the div.content text, but the div#staticContent is over the div.section.

**Comment by alvarotrigo** [comment]
Static content should be placed outside the plugin's wrapper.
You should follow the needed structure as detailed in the docs.
