### ISSUE TITLE
Background reload

### ISSUE THREAD

**Issue by levi223** [alvarotrigo/fullPage.js#952]
I have a problem with my background which becomes extremely annoying when using the sliders.
My problem is that when im using the slider arrows to navigate, the page refreshes and the website therefore doesn't go to the next slider. I also have this problem when im not using the sliders but it isn't a very big problem in that case because you can just use your mouse scroller. 

If u dont know what i mean go to www.levijochemchris.tk/leviwebsite.html , scroll one down and click the background.

**Comment by alvarotrigo** [comment]
Nothing to do with fullPage.js.
