### ISSUE TITLE
SWF / embed obejct not showing on firefox

### ISSUE THREAD

**Issue by jdelafuente** [alvarotrigo/fullPage.js#953]
Hi,
I have noticed that flash content doesnt show on Firefox. It works great on Chrome, but in Firefox the content doesnt appear.
Is there a bug? Any idea to get it working? 
For example in this url http://cabeceras.eldiariomontanes.es/documentales/2015/aniversario-hundimiento-mina-reocin/prueba.html
Thank you very much and congratulations for your great plugin.

**Comment by alvarotrigo** [comment]
Make sure it works correctly before applying fullPage.js.
It might be that the problem has nothing to do with fullpage.js but with the SVG you are trying to use or with firefox dealing with this kind of content.

(Mira a ver si se ve bien en firefox antes de aplicar fullpage.js a tu pagina, tal vez no tenga nada que ver con fullPage.js)

**Comment by alvarotrigo** [comment]
I'm getting this in Firefox:
![capture](https://cloud.githubusercontent.com/assets/1706326/5706288/709169a6-9a77-11e4-8f31-ee278d40794e.PNG)

**Comment by jdelafuente** [comment]
It works ok before Fullpage and outside the "fullpage" div. I tried with other swf files and same problem.
I have the latest flash player installed and tested in more than 10 different computers.
Any idea?

**Comment by alvarotrigo** [comment]
It might be related with this in your code:

>             
            <script type="text/javascript">brightcove.createExperiences();</script>


Remove the line as the comment says, or use `brightcove.createExperiences()` inside the `afterRender` callback.

Also, load the following line after fullPage.js or befor ethe closing body, and remove it from the place where it is right now:

     <script language="JavaScript" type="text/javascript" src="http://admin.brightcove.com/js/BrightcoveExperiences.js"></script>

**Comment by alvarotrigo** [comment]
That's because as detailed [in the FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions#my-other-plugins-dont-work-when-using-fullpagejs):

> if you are using options such as verticalCentered:true or overflowScroll:true of fullPage.js, your content will be wrapped inside other elements changing its position in the DOM structure of the site. This way, your content would be consider as "dynamically added content" and most plugins need the content to be originally on the site to perform their tasks. Using the afterRender callback to initialize your plugins, fullPage.js makes sure to initialize them only when fullPage.js has stopped changing the DOM structure of the site.

**Comment by jdelafuente** [comment]
I tried what you said this morning. I have changed it again and tested and nothing.
The problem continues.
I have added normal swf content so you can see that is not problem of the way of load the flash.

**Comment by alvarotrigo** [comment]
Are you talking about this file? http://www.aulaclic.es/html/graficos/pelicula.swf

**Comment by jdelafuente** [comment]
that file is an example

**Comment by alvarotrigo** [comment]
So, is that the file which is not being showed at Firefox?

**Comment by jdelafuente** [comment]
that file is an example. I used it to test swf content different than mine. What I want to show finally is my videos

**Comment by alvarotrigo** [comment]
I know it... but again, is that the file which is not being showed at Firefox?

**Comment by jdelafuente** [comment]
Yes. That file and my video. All the swf / embed in the code

**Comment by alvarotrigo** [comment]
It's [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=819763#c0) when dealing with css3 transformations.

You can see similar topics [in other places](http://stackoverflow.com/questions/13882629/firefox-bug-with-translate3d-on-a-flash-element).

You can solve it using `css3:false` for fullPage.js.

**Comment by jdelafuente** [comment]
solved. Thank you very much.
When you come back to Burgos tell me and I will invite you to eat lamb, morcilla, jijas ... drink some beers or whatever you want.
Gracias amigo ;)

**Comment by alvarotrigo** [comment]
:) Your welcome! 
Haha! de nada!
