### ISSUE TITLE
If Scrollbar and scrollOverflow set to true it doesn´t work on Firefox

### ISSUE THREAD

**Issue by jdelafuente** [alvarotrigo/fullPage.js#954]
May be there are a conflict using both. The normal scroll works and the one inside doesn´t.
In Chrome it works.
Any idea ?

**Comment by alvarotrigo** [comment]
Already treated [here.](https://github.com/alvarotrigo/fullPage.js/issues/553)

It's a bug related with slimScroll vendor plugin.
I'd recommend you to use the following to create sections with a bigger height than the one of the viewport. It doesn't make sense to have two scrollbars, (slimScroll + normal scroll bar).

```javascript
.fp-setion{
    height: auto !important!
}
```
