### ISSUE TITLE
Twentytwenty with fullpage doesn't work in mobiles

### ISSUE THREAD

**Issue by resting** [alvarotrigo/fullPage.js#955]
I'm sure [Twentytwenty](https://github.com/zurb/twentytwenty) works on mobile. Works on desktops though.
But wrapped in the fullpage div, user is not able to slide the slider.
Does anyone have any idea why that happens and whether there's a work around?
See example [here](http://play.sohulk.pw/fullpageTwentytwentyTest.html)

**Comment by alvarotrigo** [comment]
Read [the FAQ](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions) where you'll find the answer.
