### ISSUE TITLE
'autoscrolling' becomes 'true' after screen resize.

### ISSUE THREAD

**Issue by nikkop** [alvarotrigo/fullPage.js#957]
Mainly using fullPage.js for the easy way to get sections to take up 100% height and center the content vertically. Would use it for the autosSrolling-feature too if the support for overflowing content would be greater. 

However, to my problem.

To ensure 100% functionality across different platforms/screen sizes I've decided to turn autoScrolling off. However, the autoScrolling is activated once the browser gets new dimensions. 

For example, on computer: 
Loading the page the scrolling is normal (autoScrolling: false). Resizing the browser window to "mobile size" it's still behaving like 'autoScrolling: false'. However, going back to the original size again will activate the autoScrolling feature even though it's set to 'false' in the code.

On a mobile device the same thing is happening, however when screen orientation is being triggered the first time. So if visiting the site and turning your phone/tablet (triggering the auto rotate screen) the autoScrolling feature will be activated and the site will behave badly (because it's not been designed for it).

What is causing this? This is not the cause of my own HTML/CSS/JS as it is happening in the fullPage.js examples too.

I could shoot a video of this if needed.

Thanks in advance

**Comment by alvarotrigo** [comment]
It seems to me that you are using the `responsive` option. Correct me if I'm wrong.

**Comment by alvarotrigo** [comment]
In any case, this issue is directly related with [this other one](https://github.com/alvarotrigo/fullPage.js/issues/553).

And not easy to solve. slimScroll.js is not perfect and fullPage.js might stop working it in a near future. Maybe changing to [iScroll.js](http://cubiq.org/iscroll-5)

**Comment by alvarotrigo** [comment]
Solved in 2.5.4.
