### ISSUE TITLE
[Solve] Flicker when scrolling with dark color images as background on mobile

### ISSUE THREAD

**Issue by dreamgo** [alvarotrigo/fullPage.js#959]
Awesome plugin! Thanks for your amazing work. I meet a problem when I use it to develop a mobile website. 
There are some white blink when sliding page horizontally each time on iPhone5 and iPad air.(not test on Android device yet). A white bar will quickly appear then disappear on left or right part of page. It seems won't happen with light color image background. you can reproduce the bug by at http://alvarotrigo.com/fullPage/examples/backgrounds.html on ipad or iphone.
 Are there any method to fix this problem?

Once again, really appreciate for you create and share such awesome plugin.

**Comment by dreamgo** [comment]
BTW, what final effect I'd like to realize is sliding horizontal with continuous background to display some different contents. I define four <div class="slide>  and set same background for them ,  then set each of them display different part of background in css. Are there any better to realize that?

**Comment by alvarotrigo** [comment]
I was not able to reproduce it on iPhone with Safari and Chrome.
Can't it just be the time the image needs to be loaded? As your page background is white, you'll see it before the image finishes loading.

**Comment by dreamgo** [comment]
Thanks for your reply!  
Can you test again with repeating scroll screen left and right several times？I think it's easy to reproduce the problem on both iPad and iPhone. I agree with you that  the problem is caused by image loading. But I can't figure out why the bug still exist when I scroll back to the same page that the image has finishes loading.
 I just found even if scrolling up and down the problem also exist.

**Comment by alvarotrigo** [comment]
You can try difference things such as the ones suggested [here](http://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform).

Let me know if any work for you. But it seems you have to be careful using some of them as said in some of the comments.

**Comment by dreamgo** [comment]
Great! The problem is fixed by add "-webkit-backface-visibility: hidden;"
Really appreciated for you great help!
