### ISSUE TITLE
Parallax and Full Page plugins combination issue

### ISSUE THREAD

**Issue by tomytree22** [alvarotrigo/fullPage.js#96]
I have a problem when including jparallax plugin, the problem is that the jparallax plugin only is functional with jquery 1.7 or minor version, and the fullPage plugin need jquery 1.10 someone has achieved integrate parallax and full page ? Which parallax plugin can i use?

**Comment by alvarotrigo** [comment]
There's now a [parallax extension](http://alvarotrigo.com/fullPage/extensions/parallax.html) to create parallax effects!
