### ISSUE TITLE
Can a fullscreen video section show its overlay elements at the same time? 

### ISSUE THREAD

**Issue by bryan-xu** [alvarotrigo/fullPage.js#960]
Sliding to a section with a `<video>` in it brings up the video first, then any overlay elements, can everything be shown at the same time?

**Comment by alvarotrigo** [comment]
That has nothing to do with fullPage.js. It seems a question for CSS. I'd recommend you to ask in other places such as http://stackoverflow.com/

**Comment by bryan-xu** [comment]
Thanks for the quick response. When I turn off CSS3, it's fine. So I guess it is somewhat of a CSS and browser issue (I am using the latest Chrome), as the performMovement function will only use jQuery animate.

**Comment by alvarotrigo** [comment]
Probably related with the `transform3d` property of CSS used by fullPage.js to scroll the page.
