### ISSUE TITLE
Fullpage.js horizontal scrolling website

### ISSUE THREAD

**Issue by siddharth251189** [alvarotrigo/fullPage.js#961]
Hi alvarotrigo,

I want make an horizontal scrolling website.Is it possible with Fullpage.js ? If it is possible how please advise

Thanks
siddharth

**Comment by alvarotrigo** [comment]
You can create horizontal slides as detailed [in the documentation](https://github.com/alvarotrigo/fullPage.js).

If you want to scroll horizontally with the mouse wheel, that's not provided by fullPage.js, but probably you can achieve it by using jQuery and the methods provided by fullPage.js such as `moveSlideRight` and `moveSlideLeft`

**Comment by alvarotrigo** [comment]
This is now possible using the [Scroll Horizontally extension](https://alvarotrigo.com/fullPage/extensions/scroll-horizontally.html).
