### ISSUE TITLE
Cannot add a class/id to second or third slide

### ISSUE THREAD

**Issue by cbalasa** [alvarotrigo/fullPage.js#963]
Hello,

I have this strange issue. I create a class, basically it doesn't matter, but let say I want a class or an id for a text container. If I add the text container in the first section it looks great and it sticks with the section or the slide of that section, but if I want to add it to another section, 2nd or 3rd etc, it appears on the first section only. 

What do I have to do in order to be able to put a class/id on any other section than the 1st one. 

You can check a demo here to see what I am talking about.
http://jsfiddle.net/cbalasa/6SQhb/40/

The white rectangle is put in the 2d section but it appears on the first section above those 3 slides in the 1st section. If you copy/paste the rectangle in the first section it looks ok and it sticks with the correct slide.

Thank you in advance,
Cristi

**Comment by alvarotrigo** [comment]
Your problem has nothing to do with fullPage.js but with CSS knowledge.
That's because you are using `position:fixed` instead of `positio:absolute`.

You would need to add `position:relative` for `.section` in that case.

**Comment by cbalasa** [comment]
Thank you very much. I am a newbie in webdesign. I searched a lot before writing here, but I couldn't find any answer.
