### ISSUE TITLE
I'm having a problem in Google Chrome

### ISSUE THREAD

**Issue by mlai01** [alvarotrigo/fullPage.js#964]
Hi there, I used your script with Zurb Foundation 4 and it works great in Firefox, but I tried in Chrome and doesnt seem to work.  I tried redownloading your files to see if it was me, and i tried your demos in chrome and it looks like the same problem occurs.  Particularly for background slides, the pages get vertically squished and there is no scroll functionalty.  Even when you click on the navigation dots, i see the anchor appear in the address bar but the page is static.

I managed to get the full background to appear, but still no scrolling occurs. These errors are duplicated on chrome using your demos, I didn't even get to my own site yet. Any ideas?  I wrote css3: false already, included the latest js scripts etc.

**Comment by alvarotrigo** [comment]
The problem doesn't seem to be in the plugin, as you can easily see how all [demo pages](http://alvarotrigo.com/fullPage/) as well as the [examples provided by the plugin](https://github.com/alvarotrigo/fullPage.js/tree/master/examples) work properly on Chrome.

You are probably doing something wrong, but if you don't provide more information or a link to your site, its impossible to determine the cause of it.

Start by checking your Chrome javascript console.

**Comment by mlai01** [comment]
Thank you for your response. I realized I was working behind a firewall, that's why the scripts didn't come through.
