### ISSUE TITLE
iPad (Tablet) Scroll Sections not working with enabled Scrollbar

### ISSUE THREAD

**Issue by emitremmus** [alvarotrigo/fullPage.js#966]
I have tested here in my iPad.
When i set Scrollbar: enable then on Touch is slides not smooth from Section to Section. It is working like on a normal Site, with Scrollbar.
On Desktop it is working fine. When scroll down, it takes me from Section to Section.

Is there anything witch i configured wrong. Here the Link: http://goo.gl/XSn396

**Comment by alvarotrigo** [comment]
Thanks for reporting it. Solved in the 2.5.5.

**Comment by emitremmus** [comment]
Yes, working now. Thanks for fixing!!! :+1:
