### ISSUE TITLE
"Footer" normal Scroll Event - but Site still moves on Top of this Section automatic

### ISSUE THREAD

**Issue by emitremmus** [alvarotrigo/fullPage.js#968]
Hello,

my last Section on Site is the Footer. Here is set in js the following:  normalScrollElements: '.kontakt',
When i now scroll to the Bottom, the Site automatic scrolls up to the Top of the Section. Every Time.
I scroll with Mouse totally to the Bottom and want to Read the Content. After some Seconds site moves automatic to Top of this Section.

How can i avoid this?
See here my example: http://bit.ly/1xKJLVY

**Comment by emitremmus** [comment]
Is there any solution for this???

I need here quick help.

**Comment by alvarotrigo** [comment]
I guess you are talking about the case in which you drag the scroll bar with your mouse until you reach the bottom of the page. Correct me if I'm wrong.

You are not suppose to use `normalScrollElements` in a section. This is not the purpose of it, and less if you are using `scrollBar:true`.

The plugin doesn't provide any way to deal with your problem. If you really need it to be fixed, I could customise the plugin for you for some price. Just [contact me](http://alvarotrigo.com/#contact-page).

**Comment by emitremmus** [comment]
No it is also when i am in last Section (Contact) Section and i scroll with Mouse to the Bottom of the Side.
After some seconds the Side scrolls automatic back to the Top of the Section.
This is what i mean.

So the only way to solve this, is NOT to make a section for the Contact Part, or?

**Comment by alvarotrigo** [comment]
Yeah ok, but its the same problem. 

> So the only way to solve this, is NOT to make a section for the Contact Part, or?

I told you before the options you can use instead. 
If you want to keep using this same options, the plugin doesn't provide a solution for it.
