### ISSUE TITLE
Different Backgrounds Horizontal Scroll

### ISSUE THREAD

**Issue by ljibbyl** [alvarotrigo/fullPage.js#969]
First off, many thanks for the beautiful script!

I am having issues with page backgrounds on the horizontal scroll.  I am not sure why, but I have no problem changing backgrounds for the vertical scroll pages, but just cannot seem to for horizontal.  I want my first page to have one background and the pages to the left and right to have a different background.

I noticed that in your page demo, you demonstrated multiple background colors for only vertical, not horizontal, so I am wondering if I have been coding incorrectly or if this script does not allow for it ...

**Comment by alvarotrigo** [comment]
It seems you didn't take a proper look to [the available example](http://alvarotrigo.com/fullPage/examples/backgrounds.html) because it is using different backgrounds for different horizontal slides.

In any case, that has nothing to do with fullPage.js but with your CSS knowledge.
