### ISSUE TITLE
Drag and selection

### ISSUE THREAD

**Issue by sumesh1234** [alvarotrigo/fullPage.js#975]
hi alvarotrigo !

Thank you very much for your great plugin !
Iam facing a problem on this,which is on selecting or dragging the content of the section also its going to next section.how to deny this thing..

here is the structure of the script how iam exicuting

```javascript
$(document).ready(function () {
    $('#fullpage').fullpage({
        menu: '#menu',
        anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', '5thpage', '6thpage'],
        sectionsColor: ['#C63D0F', '#1BBC9B', '#7E8F7C', '#C63D0F'],
        autoScrolling: false,
        scrollOverflow: false
    });
```
and iam using more contents in the scetion. with the help of css property- overflow: scroll;

**Comment by alvarotrigo** [comment]
Your configuration looks ok, nothing weird on that as you can see in this demo I just made with it.

The site is actually acting like a normal site, in which, when you drag anything, the site will scroll down or up when you are in the bottom or the top of the page.

I would recommend you to look for solutions in other places such as stackoverflow.com, as this question has nothing to do with fullPage.js and its a problem in any other kind of site.

Take a look at this questions:
http://stackoverflow.com/questions/16783014/how-do-i-prevent-screen-scrolling-on-mouse-drag-when-an-absolutely-positioned-el
http://stackoverflow.com/questions/6920274/stop-the-page-scrolling-when-selecting-dragging-text
http://stackoverflow.com/questions/15784792/disable-scrolling-via-dragging

**Comment by sumesh1234** [comment]
thank you for the quick reply . and i will go with these solutions..

**Comment by sumesh1234** [comment]
I tried with the above solutions but it's not working for me.

**Comment by alvarotrigo** [comment]
You should ask in other place. I'm sorry, it's not related with fullPage.js.

**Comment by sumesh1234** [comment]
thank you for the response..
