### ISSUE TITLE
Snap to page

### ISSUE THREAD

**Issue by swehunter2000** [alvarotrigo/fullPage.js#978]
When "autoScrolling:false" and a user stops scrolling when the page isn't aligned, a option should be provided (in code) to snap it into position after x amount of time. 
![unsnapped](https://cloud.githubusercontent.com/assets/3661126/5965762/e7a7c8f2-a7fe-11e4-9817-0fe039fd04cd.PNG)

**Comment by alvarotrigo** [comment]
You have that when using `scrollBar:true`.

**Comment by swehunter2000** [comment]
when initializing with 

"  $('#fullpage').fullpage({
        scrollBar: true
});"

I get a "Uncaught TypeError: Cannot read property 'top' of undefined" on line 121

"$('html, body').scrollTop(element.position().top);"

**Comment by swehunter2000** [comment]
is there any way to get the same effect but with a hidden scrollbar?

**Comment by alvarotrigo** [comment]
Then... why are you using `autoScrolling:false` ?
I don't understand what are you looking for, a normal scroll without scroll bar? That's not possible...

**Comment by swehunter2000** [comment]
because the user experience on my site is smoother when you can scroll on your own, but that it snaps into place.

**Comment by alvarotrigo** [comment]
I'm sorry, I don't understand what are you asking for.
