### ISSUE TITLE
Disable autoscroll to active section for autoscroll=false on responsive

### ISSUE THREAD

**Issue by neilmuralee** [alvarotrigo/fullPage.js#979]
Hi!

I notice on the responsive example html page on git, that if you resize between two widths within the responsive threshold that the the page scrolls to the active section. Is there anyway to disable the autoscroll to the active section?

To recreate:
- open the responsive example (900px responsive setting)
- resize between 500px and 505px wide (Or arbitrary movement below the 900 threshold)
- The screen will scroll to the top of the active section

I'm having an issue with my page on iphone and browser where the content is higher that the viewport - and there is a case where it is not user friendly the page to scroll all the way back to the top of the section.

**Comment by alvarotrigo** [comment]
> I'm having an issue with my page on iphone and browser where the content is higher that the viewport - and there is a case where it is not user friendly the page to scroll all the way back to the top of the section.

And when are you re-sizing the browser in your phone? Not quite sure if I'm understanding your problem very well...

**Comment by alvarotrigo** [comment]
Closed due to lack of information to understand or solve the problem.

**Comment by neilmuralee** [comment]
Apologies - i found a solution not related to fullpage.js

**Comment by alvarotrigo** [comment]
Good. No problem.
