### ISSUE TITLE
scrollOverflow should be disabled on responsive mode

### ISSUE THREAD

**Issue by adriandmitroca** [alvarotrigo/fullPage.js#980]
As it says responsive mode changes `autoScrolling` to `false` and with `scrollOverflow` enabled there are a lot of mess on mobile device. It should be disabled by default or give user choice.

For temporary solution I disabled it via PHP (simple `if` statement) basing on useragent which works but isn't proper fix.

**Comment by alvarotrigo** [comment]
Related with [this bug](https://github.com/alvarotrigo/fullPage.js/issues/553).
