### ISSUE TITLE
re-sizing problem

### ISSUE THREAD

**Issue by alpersari** [alvarotrigo/fullPage.js#983]
Hello,

I've a problem with re-sizing the the pages. When I try to re-size it works in large width sizes but when width size less than 970 it's not working. 

my website is: www.ustayim.com 

please help me

**Comment by alvarotrigo** [comment]
Re sizing is working properly.
You are using `min-width: 960px;` for your body...

**Comment by alpersari** [comment]
Sorry :)
Thank you so much for your quick response.
Have a nice day.
