### ISSUE TITLE
Android resize problems and textareas

### ISSUE THREAD

**Issue by RikuAnsem** [alvarotrigo/fullPage.js#984]
Hi.
First of all, sorry for my bad english.

I'm using "fullPage 2.5.6" but it fails in android devices (I can't test it on iOs and Explorer mobile), when the webpage re orientated it crash the plugin (I fixed it with this https://github.com/alvarotrigo/fullPage.js/issues/248), but I have other problem, it do the same when I try to use a textarea (when keyboard open it work nice, but when I leave the focus it crash).

Configuration:
```javascript
$('#fullpage').fullpage({
	anchors: ['inicio', 'contacto'],
	sectionsColor: ['#fff', '#181937'],
	css3: true,
	navigation: true,
	navigationPosition: 'right',
	navigationTooltips: ['Inicio', 'Contacto'],
	responsive: 900,
	loopBottom: true,
	loopTop: true,
	scrollOverflow: true,
	resize: false,
	touchSensitivity:5,
	//paddingTop: '56px'
});
```

Test page:
http://test.emosistemas.com/

Device: Nexus 5
Android: 5.0.1
Navigator: Chrome

Any idea?
Thanks for all in advance.

EDIT:
Small fix (It may not work well - Works in 95% of cases):
```javascript
$(document).ready(function() {
	$( window ).resize(function() {
		clearTimeout(resizeId);
		resizeId = setTimeout('resize();', 1000);
	});
});

var resizeId = 0;
var lastHeight = null;
var lastWidth = null;
function resize() {
	var newHeight = $( document ).height();
	var newWidth =  $( document ).width();
	
	if (lastHeight != null && (lastHeight < newHeight || (lastHeight == newHeight && newWidth != lastWidth))) {
		$.fn.fullpage.reBuild();
		nonResized = true;
	}
	
	lastWidth = newWidth;
	lastHeight = newHeight;
}
```

**Comment by alvarotrigo** [comment]
This issue will treat only the problem described in the title, the one with the textarea.

**Comment by alvarotrigo** [comment]
> when keyboard open it work nice, but when I leave the focus it crash).

What do you mean with "it crashes". Be more specific.

**Comment by RikuAnsem** [comment]
Well.. really I think is the same problem but generated by other actions.
With "crashes" I mean that the javascript donesn't work, so it show the webpage without correct styles (like the photos in this post: https://github.com/alvarotrigo/fullPage.js/issues/248#issuecomment-72189019)

I can't describe more the problem... I will try with firefox later.

**Comment by alvarotrigo** [comment]
@RikuAnsem The sites looks totally the same to me (on iPhone Safari and Chrome) before and after focusing and unfocuosing the textarea.

**Comment by RikuAnsem** [comment]
I tried to solve with it but it don't work.

**Comment by RikuAnsem** [comment]
I have to edit the post, the problem is Google Chrome (computer too)

**Comment by alvarotrigo** [comment]
You can solve one of the problems using `scrollOverflow: false,` as the issue breaking fullpage.js functionality is related with [this bug](https://github.com/alvarotrigo/fullPage.js/issues/553).

**Comment by RikuAnsem** [comment]
If I disable that it fails too, I will review the css.
Thanks

**Comment by alvarotrigo** [comment]
So, what's the problem now? Images getting resized as before? I don't see anything weird with the textarea.

**Comment by RikuAnsem** [comment]
Nope... I will try to explain, the bug is again the first, the image when window is resized.
In some cases, the script resize correctly the images, but sometimes not (like the images in the other post). To fix it, I use "$.fn.fullpage.reBuild();", but, sometimes it resize correctly all... and when "$.fn.fullpage.reBuild();" is called... it crashes all...

I've uploaded the last revision to http://test.emosistemas.com.
Open it in chrome and resize the window (I disabled $.fn.fullpage.reBuild();)

In my opinion:
The bug is executed "randomly" but when it occurs, every second time that it rebuild it do it bad (apparently only in chrome, I'll try it in opera too).

**Comment by alvarotrigo** [comment]
fullPage.js won't resize the images for you. Or you other plugin does it, or you will have to do it by yourself. 
If the image is bigger than the viewport, the section will get the size of the image height. That's normal.

**Comment by RikuAnsem** [comment]
Yes, I know, I don't know how to explain...
I thought about it and the "resize" is the content of div... (<a>), it works sometimes and other times no (I do it through css... but it works sometimes...
When I back to home I try to record a video to explain you.

Anyway I will to fix it with JavaScript.

Thanks
