### ISSUE TITLE
One section with slider - not working

### ISSUE THREAD

**Issue by GeorgeTodea** [alvarotrigo/fullPage.js#987]
Hi, been searching through issues and did not found anything similar.

I have for example on one page, the fullpage plugin enabled on a single section with more "slide"-s. But the arrows of the slider do not work).

Is there a solution for that?

**Comment by alvarotrigo** [comment]
It seems you are doing something wrong. Take the available examples as a base to start your project if you have troubles.

**Comment by GeorgeTodea** [comment]
http://i.imgur.com/EJB7bOB.png - I have followed your example http://jsfiddle.net/97tbk/158/. Still nothing

**Comment by alvarotrigo** [comment]
Well, as you can see, the example is working, so you are very probably be doing something wrong.
You don't even need to go to the fiddle, you have that example available on [the downloaded files](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/oneSection.html) and even [online](http://alvarotrigo.com/fullPage/examples/oneSection.html).
