### ISSUE TITLE
Title on horizontal navigation bar with dots in fullpage.js

### ISSUE THREAD

**Issue by aakankshabhujbal** [alvarotrigo/fullPage.js#988]
I am designing website using fullpage.js. I want to give title to each dot in horizontal navigation bar.
```javascript
function addSlidesNavigation(section, numSlides){
        section.append('<div class="fp-slidesNav"><ul></ul></div>');
        var nav = section.find('.fp-slidesNav');

        //top or bottom
        nav.addClass(options.slidesNavPosition);

        for(var i=0; i< numSlides; i++){
            nav.find('ul').append('<li><a href="#"><span></span></a></li>');
        }

        //centering it
        nav.css('margin-left', '-' + (nav.width()/2) + 'px');

        nav.find('li').first().find('a').addClass('active');
}
```

function call from :
```javascript
if(options.slidesNavigation){
    addSlidesNavigation($(this), numSlides);
}
```
This function generates horizontal navigation bar. I want to add title for each. I am not getting how do I do it. Please help.

**Comment by alvarotrigo** [comment]
This is not a functionality provided by fullpage.js. If you want my help I can customize the plugin for you for some price, as detailed in the docs. Just [contact me](http://alvarotrigo.com/#contact-page). 

Otherwise, I would recommend you to ask this kind of questions in other place such as stackoverflow.com

**Comment by aakankshabhujbal** [comment]
ok thnx for quick reply.

**Comment by alvarotrigo** [comment]
Also, take a look [at this topic](https://github.com/alvarotrigo/fullPage.js/issues/176)
