### ISSUE TITLE
Conflict using Magnific Popup with 'autoScrolling: false,' option

### ISSUE THREAD

**Issue by pinkp** [alvarotrigo/fullPage.js#990]
Opening and then closing a popup using Magnific Popup on a fullPage.js site seems to stop the autoScrolling: false, option working.
So once the pop up closes you can no longer scroll manually up and down the site. You can use the menu anchors to snap to sections but not scroll. Its normal again once refreshed but will happen again after opening a popup.

Any ideas why this happens and how to resolve it?

**Comment by alvarotrigo** [comment]
Have you read the [FAQS](https://github.com/alvarotrigo/fullPage.js/wiki/FAQ---Frequently-Answered-Questions)?

**Comment by blimpmason** [comment]
I'm having the same issue even when initializing Magnific Popup within the afterRender callback. Any other ideas?
