### ISSUE TITLE
How to disable the vertical dotted navigation on the first section?

### ISSUE THREAD

**Issue by kokoda** [alvarotrigo/fullPage.js#991]
Hello everyone,

 I need to disable the dotted vertical navigation only on the first section. Any idea on how to achieve it?

Thank you!

**Comment by jakobgrommas** [comment]
#fp-nav ul li:first-child {
          display: none
    }

**Comment by kokoda** [comment]
Thank you for your prompt reply. This doesn't hide the dotted vertical nave on the first section (i want to totally hide it from the first section). 

#fp-nav ul li:first-child {
          display: none
    }
It hides the first dotted circle on the nav bar. Any other solution?

Thank you!

**Comment by jakobgrommas** [comment]
then I misunderstood you. you can do it with afterLoad.. just check if ‘index === 1’ and add an visuallyhidden class or whatever to your navigation.

**Comment by kokoda** [comment]
Thank you. I really don't understand that. Could you tell me an example. here is my html:

<div id="fullpage">
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>

Thanks!

**Comment by jakobgrommas** [comment]
```javascript
$("#viewport").fullpage({
    sectionSelector: 'section',
    // and the rest of your configuration
    afterLoad: function(anchorLink, index){
        if (index === 1) {
            $('#fp-nav').hide(); // or toggle by class
        }
        else {
            $('#fp-nav').show(); // or toggle by class
        }
    }
});
```

**Comment by kokoda** [comment]
Thanks. It didn't work for me. Here is my full javascript. Could you please help to integrate the code you provided for me? 

https://dl.dropboxusercontent.com/u/28092/fullpage.js

**Comment by jakobgrommas** [comment]
```javascript
afterLoad: function(anchorLink, index) { // you need to add the parameters
    navColor();
    addClassNav();
    // doesn't make sense:
    // $('#fp-nav').fadeIn(); 
    section.not('.active').find('.section-content').mCustomScrollbar('scrollTo', 'top');
    videoBg();
    setTimeout(function() {
        sandwichAnimation();
    }, 0);
    // simply ask fullpage for section index:
    if (index === 1) {
         $('#fp-nav').hide(); // or toggle by class
     }
     else {
         $('#fp-nav').show(); // or toggle by class
     }
} //,
```

**Comment by kokoda** [comment]
Thank you indeed! It works perfectly!
Many thanks!
kokoda

**Comment by kokoda** [comment]
Hello again,

 I just realized there is an issue. Now when the page loads the vertical nav bar is disappeared which is what I wanted, but when the page is refreshed, the vertical nav bar comes again as the link has an anchor #intro. e.g. domainname.com/#intro where the "intro" is the first section in the website where I want to disable the vertical nav. Any suggestion?

Kind regards,
Kokoda

**Comment by kokoda** [comment]
Oops. It works! There was  an error in smoother code!

**Comment by kokoda** [comment]
Hello again,

 I still have the same issue. Sometimes the vertical navigation bar appears in the first section where I want to disable it. Any advice? I am using the following code as you suggested:

<pre>
afterLoad: function(anchorLink, index) { // you need to add the parameters
    navColor();
    addClassNav();
    // doesn't make sense:
    // $('#fp-nav').fadeIn(); 
    section.not('.active').find('.section-content').mCustomScrollbar('scrollTo', 'top');
    videoBg();
    setTimeout(function() {
        sandwichAnimation();
    }, 0);
    // simply ask fullpage for section index:
    if (index === 1) {
         $('#fp-nav').hide(); // or toggle by class
     }
     else {
         $('#fp-nav').show(); // or toggle by class
     }
} //,
</pre>

**Comment by codinglover** [comment]
I guess that would be a little bit complicated why don't you try for something different active and non active function. like a prev next thing.
