### ISSUE TITLE
Normal scrolling on mobile phones and tablets  

### ISSUE THREAD

**Issue by kokoda** [alvarotrigo/fullPage.js#992]
Hello every one,

 I am trying to disable the auto scrolling on tablets and phones but it seems it doesn't work. I want my site to behave as a normal site on both mobiles and tablets.  Any solution would be greatly appreciated.

**Comment by jakobgrommas** [comment]
you could try to use modernizr, ask for touch and rebuild fullpage. you could also use the search, I think there were already similar questions.

**Comment by alvarotrigo** [comment]
@kokoda, the question is: what's a mobile phone or a table for you? Would a PC with touch screen be one of those? Will a tablet with mouse be one of those? A device with slow resolution? What about retina displays in iPads?

There's no way to define what a tablet or a phone is. So you'd better clear your mind about why you want to have a non scrolling site for "mobile phones and tablets". 
If its a matter of resolution, then use it as a way to differentiate both and based on that, use one or another initialization. 

The plugin can't just know what you mean with "tablet or phone".

**Comment by alvarotrigo** [comment]
You can also try to detect a "mobile browser" by using a similar technique used by fullPage.js inside. 
You'll probably have to check it every year as new devices are added and it changes constantly, but you can try [the solution proposed here](http://stackoverflow.com/questions/11381673/detecting-a-mobile-browser).
