### ISSUE TITLE
the third, the bottom

### ISSUE THREAD

**Issue by AlonsoZeng** [alvarotrigo/fullPage.js#993]
1. no matter how many sections you've got, it will automatically recognize the third section as the last section, when you reach the third and wanna go down, it slips to the first section(if loopBottom is on). 
2. when reaching the fourth section(cant do it by scrolling my mouse due to issue1, have to do it with the help of navigator), you go up, it automatically thinks the fourth section is the top, so it slips to the last section instead of the third(if loopTop is on).

**Comment by alvarotrigo** [comment]
1 and 2: you are doing something wrong. Review your HTML markup and the javascript console. 

Without a way to reproduce the problem or a link to your site, I can not help you more.
