### ISSUE TITLE
Scrolling animation problems in Chrome

### ISSUE THREAD

**Issue by lanzs** [alvarotrigo/fullPage.js#995]
Hi, I noticed that there is some problems with scrolling animation in latest Chrome (40.0.2214.111 m) on Windows – sections change without any animation, just "jump" to other section. It can be seen even on standart example (http://alvarotrigo.com/fullPage/), so it's not about options (animation speed).
On Mac everything works good, I noticed problem only in latest Chrome on Windows.
Is I am the only one who face this problem or it is a common problem (have not got another/alternative Win PC to test this issue more)?

**Comment by alvarotrigo** [comment]
Can you explain how can we reproduce it? 
I'm not having that problem.

**Comment by lanzs** [comment]
I just used Windows 7 with latest Google Chrome and even on this page: http://alvarotrigo.com/fullPage/ there is no smooth scrolling – just "jumps" from section to section.
So I'm wondering if it is my own problem or it is a problem of new version of Google Chrome.

**Comment by alvarotrigo** [comment]
Sounds like your own problem.

**Comment by bala8103** [comment]
https://code.google.com/p/chromium/issues/detail?id=451756
lanzs: check #88 above link  
brendans
========
I have tested this on three machines (details below), 2 don't work, 1 does work correctly. Oddly, if you reboot the XP machine, the transitions work for a short time, but then revert to not working again.

Machine 1 (NOT Working)
Win 7 Professional, SP1, 64-bit, Intel Xeon CPU E5430
Nvidia GeForce GTX 760 (Driver 9.18.13.4725)
Chrome Version 40.0.2214.111 m

Machine 2 (NOT Working)
Win XP, SP2, 32-bit, Genuine Intel CPU T2500
ATI Mobility Radeon X1400
Chrome Version 40.0.2214.111 m

Machine 3 (WORKING!)
Win 8
Chrome Version 40.0.2214.111 m

[Note : now all css transition not working in lower version os--> xp,win7--> [chrome]]

**Comment by alvarotrigo** [comment]
@bala8103 tested in http://www.browserstack.com/ on Windows XP with the latest stable Chrome. It works as expected.

**Comment by alvarotrigo** [comment]
The topic is being now treated [here](https://github.com/alvarotrigo/fullPage.js/issues/1005). 
Please, try to take an screen shoot of the fullpage.js wrapper in the developer tools.
