### ISSUE TITLE
Fixed bottom position - on scroll fixed top position

### ISSUE THREAD

**Issue by Lazyfattree** [alvarotrigo/fullPage.js#996]
Hi, 

I can't seem to get my menu bar fixed on top of the first page and when it scroll just to the next page that it stays on the top for the rest of the pages. 

Its not in the basic package, but would be a cool feature. If anyone can help with?!
I'll post the answer if I find it myself

**Comment by alvarotrigo** [comment]
You can see it working in [the available example online](http://alvarotrigo.com/fullPage/examples/fixedHeaders.html) and in [the download files inside the examples folder](https://github.com/alvarotrigo/fullPage.js/blob/master/examples/fixedHeaders.html).
