### ISSUE TITLE
Deactivate fullPagejs autoscrolling on mobile devices.

### ISSUE THREAD

**Issue by SebastianBotez** [alvarotrigo/fullPage.js#997]
Hellow like the title said i want to deactivate this awesome js on mobile devices, I tried searching the web but noting worked. 
This is the website:
http://bit.ly/1C1PnN9
setAutoScrolling:false isnt working
I realy appreciate your work, thanks.

**Comment by alvarotrigo** [comment]
Why `seAutoScrolling(false)` won't work? Explain yourself, because as far as I know it works as expected.

**Comment by SebastianBotez** [comment]
Hello and thank you for the answer. Well isnt working:
		$(document).ready(function() {
			$('#fullpage').fullpage({
				scrollBar: true,
				responsive: 0,
				seAutoScrolling:false,
				setAutoScrolling:false,
				afterRender: function(){
					//playing the video
					$('video').get(0).play();
				}
			});
		});
as you can see in the source code, the setAutoScrolling:false, is written but the website is still autoscrolling. Thanks ...

![untitled](https://cloud.githubusercontent.com/assets/10911720/6097924/302f83d2-afd7-11e4-92ae-4ef8f4bd3d96.png)

**Comment by alvarotrigo** [comment]
`setAutoScrolling` is a function, not a plugin option... Review [the documentation again](https://github.com/alvarotrigo/fullPage.js).
