### ISSUE TITLE
"afterSlideLoad" is not working?

### ISSUE THREAD

**Issue by drioou** [alvarotrigo/fullPage.js#999]
```javascript
afterSlideLoad: function (anchorLink, index, slideAnchor, slideIndex) {
    var loadedSlide = $(this);
    if (index == 3 && slideIndex == 1) {
        $('.pg3').addClass('animated');
    }
},
```

this  is my code but  it's not working ?
somebody could tell me where is bug?/worong?

**Comment by mnotw** [comment]
please make sure slides exist.
are you sure you don't wanna give afterLoad a try ?

**Comment by alvarotrigo** [comment]
Nothing we can say without more info / code.
Your `afterSlideLoad` is correct. It seems a problem in other part of your code.
